### ISSUE TITLE
Should language, dubbings and subtitles be a part of the availabilities research? 

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1022]
We have to wait for @Jackseed if we should implement the versioning of the movie to be calculated as well like duration, media and territory.

**Comment by Jackseed** [comment]
Yes we had confirmation that it has to be implemented, same as the territory, rights and other parameters

**Comment by Maxstgt** [comment]
- [x] filtering on dubbings
- [x] filtering on subtitles
- [ ] filtering on original languages
https://github.com/blockframes/blockframes/pull/1099
