### ISSUE TITLE
Unit testing framework

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1044]
# Unit testing framework

## Objectives 
 - [x] Find a good unit testing framework
 - [ ] Implement it

## Description
Angular makes it difficult to create unit tests, we need a specific framework to do so.

**Comment by Maxstgt** [comment]
spectator from netanal

**Comment by jpsubra** [comment]
Si ça peut aider (mais vous connaissez sans doute déjà ça):
https://medium.com/welldone-software/an-overview-of-javascript-testing-in-2019-264e19514d0a
