### ISSUE TITLE
Tests E2E - Training

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1049]
# Tests E2E - Training

## Objectives
- [ ] Document & Explain the testing flow (epic, implem, review, etc).

- [ ] Document & Explain Page Objects, test-ids, etc.

- [ ] Document & Explain data sharing.

**Comment by lsenta** [comment]
@Jackseed Do you have info regarding the UX / EPIC / SPRINT breakdown? I'll need this as a starting point to document the flow.
