### ISSUE TITLE
Data Model - Refining

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1051]
# Data Modeling - Refining

## Objectives
- [x] Clean current Data model in draw.io & code (remove useless parameters & duplication)
- [x] Update draw.io to match the code
- [x] Rename all parameters when necessary (precise vocabulary, understandability, avoid duplication & misunderstandings)
- [x] Compare with firestore model of using data

**Comment by phpgeekfr** [comment]
There is also an old issue #752 .

**Comment by Jackseed** [comment]
@Mussuranae we should keep in mind this issue #639
