### ISSUE TITLE
Avails search not working

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1069]
# Expected behavior
The search should display some feedback on either the film is available corresponding to the search parameters or not. 
Here there is no feedback either when it is available or when it's not.

# Steps to reproduce the bug
1. Connect with hello@logicalpictures
2. Go on Rubber avails search page
3. First tried a research from October 15th 2019 to October 20th / Afghanistan / Pay TV: got no feedback
4. Then tried a research from October 15th 2019 to October 20th / France / Free TV / Exclusive: got no feedback
5. Then tried a research from October 15th 2019 to October 20th / Germany / Pay TV / Exclusive: got no feedback

**Comment by Maxstgt** [comment]
- 3 = `YOU CAN BUY YOUR DIST RIGHT, NO MEDIAS AND TERRITORIES OVERLAPPING FOUND`
- 4 ![Screenshot from 2019-10-17 09-35-23](https://user-images.githubusercontent.com/39312833/66987699-8b6c5d80-f0c1-11e9-8954-df143b5a230f.png)
- Same as 4 but Koch Films is the company
