### ISSUE TITLE
Refactoring the MovieData Model

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1071]
- [x] State issue number in the code
- [x] Search the current issues, for a similar issue.
- [x] Put relevant labels (which App / Bug / Refactoring )
- [x] move to icebox (if it's a low priority) or backlog (for future) or in progress
- [ ] Include relevant screenshots, if possible. Drag your screenshots directly into this text box. 
- [x] State the expected behavior and the steps needed to reproduce the problem.
_____

After the refactoring of the types in #1043, the MovieData Model isn't suitable anymore. But the UI is going to change anyway, so the best would be to wait for the decision of the UI Team.

**Comment by Jackseed** [comment]
this is referenced in others issues related to the data model > I close this one
