### ISSUE TITLE
Update Create your org workflow

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1095]
## Description

Users will be able to create organizations and accounts, still with an acceptation required by Cascade8. The flow has to work and needs to be completed.

## Objectives
- [x] Join the community page (https://projects.invisionapp.com/d/main#/console/18708905/389334914/preview)
1. Add the subtitle
2. Change the illustration
3. Css magic
From this:
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/829eca35-4438-4d63-b967-6a8ce29b391a)
to this:
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/cb091a5b-f0ef-4518-88f4-76a7069a7492)

- [x] Find my org page (https://projects.invisionapp.com/d/main#/console/18708905/389334917/preview)
1. Change the buttons: "Let's go" becomes "Send a request"; "Back" becomes "Create my company" and leads to the Create my org page
2. Change the illustration
3. Change titles

Goes from this:
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/01b39ba0-0c7b-49ab-8d2f-1b6eb5904962)
To this:
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/81f318f6-ffab-440e-9766-6311b134869f)

- [x] Congratz page (from joining a company request)
1. Change texts & url > see issue #1057
2. Add a button Edit my profile that leads to the "My account" page
3. Every other links / buttons should send the user to the congratulations page // this will be resolved with issue #1136 

- [x] Request notification (https://projects.invisionapp.com/d/main#/console/18708905/389334918/preview)
Update the notification from:
![image](https://user-images.githubusercontent.com/14964443/67202260-787ec380-f408-11e9-8f18-c34d5f87eb20.png)

to this: 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/8244bbae-5159-41c0-b0c2-83fb6b8ba194)

**Comment by pldespaigne** [comment]
#1114

**Comment by Jackseed** [comment]
Update of the issue:
- [ ] Block the user on the Join the community page while his request is pending (either for a Cascade8 acceptation when he creates an org or when it's for an org acceptation of the user)
- [ ] Add a cancel button to the pending request @Hugo-Hontans

**Comment by Jackseed** [comment]
- [ ] Add a feedback to the user when sending a request to join an org with a snackbar "Request sent!" when it works or "We encountered an error, please try again." when it doesn't
- [ ] Re-direct the user to the Join the community page when he clicks in "Send a request" button
