### ISSUE TITLE
Update Organization members page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1096]
## Description
This page should be fully working and needs some minor front changes
https://projects.invisionapp.com/d/main#/console/18708905/389334921/preview

## Objectives
Minor corrections from: 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/8d1404d1-78a9-4e7e-9b0c-577f493a25d6)
to
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/4cd854ea-38d2-4ebc-9bf3-294353bbf1df)
- [x] Add the org name on top of page
- [x] Icons should be on the right
- [x] Send invitation button centered 
- [x] The add new member field should be larger
- [x] Send invitation snackbar message should be: "Your invitation was sent"
- [x] Add a tip message when clicking on the field send an invitation: "Please enter a valid email address."
- [x] Put an uppercase on the Role
- [x]  Remove Signer column
- [x] Add bold characters following UI screen

**Comment by pldespaigne** [comment]
#1114

**Comment by Jackseed** [comment]
Also, this page is simply missing in the app catalog marketplace so it needs first to be implemented there with dark theme

**Comment by pldespaigne** [comment]
#1130 PR has removed signer column & move avatar next to the name

**Comment by Maxstgt** [comment]
what is the route in the catalog-marketplace for this? @Jackseed

**Comment by Jackseed** [comment]
@Maxstgt can you also remove the Role column + pencil since we won't use it ?

**Comment by Maxstgt** [comment]
On it
