### ISSUE TITLE
Update My Organization page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1101]
## Objective
Update the form when modifying the info following the UI view:
https://projects.invisionapp.com/d/main#/console/18708905/389334920/preview

- [ ] remove the ether addresses
- [x] put the according subtitles to the form
- [ ] change the save button to blue

**Comment by pldespaigne** [comment]
#1114

**Comment by Jackseed** [comment]
Removed the task about address field and created a dedicated issue #1126
