### ISSUE TITLE
Welcome to Bigger Boat landing page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1105]
## Description
Landing Page should be the welcome to Bigger Boat homepage instead of the Main app home.

## Objective
- [x] Link the landing page to the Welcome to bigger boat homepage (https://projects.invisionapp.com/d/main#/console/18708905/389335190/preview)
- [ ] Update the landing page to match this 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/0413e7ef-74b3-4c70-a949-5b928412de5f)
- [x] The button should lead to the sign in / sign up page

**Comment by Hugo-Hontans** [comment]
A similar page already exists in libs/auth/src/lib/pages/welcome-view

**Comment by Jackseed** [comment]
Subtitle text should be:
"The only marketplace offering package deals for TV and Film rights."
