### ISSUE TITLE
Bigger Boat homepage

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1109]
https://projects.invisionapp.com/d/main#/console/18708905/389334924/preview
Some small fixes:
- [x] Center the presentation text
- [ ] Give @Jackseed the good dimensions for banner pictures
- [ ] link the banner pictures to the corresponding movie page

Specific to AFM version, change the 3 sections:
- [x] New films first with a random between all films
- [x] In Production films with a random between films with status being "on production"
- [x] Completed films with a random between films with status being "finished"

**Comment by Jackseed** [comment]
- [ ] Add subtitles under each selection:
News Films : Check out our newest gems!
In production : Discover the potential of projects still in production
Completed films : Complete films for complete success

**Comment by Maxstgt** [comment]
@ioaNikas assigned him to this issue
