### ISSUE TITLE
Implement front Admin / Member roles

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1121]
## Description
Currently the roles are linked with the org smart wallet. We won't use Ethereum on the AFM version so we need to remove this link and make the roles work on the firebase + front side. 

## Objectives 
- [x] Remove the use of Ethereum on the admin / member roles
- [x] Implement Super Admin / Admin / Member roles on firebase
- [x] Super Admins can do everything (including set a member admin and take it off) + Admin roles
- [x] Admins can send invitation to new members, accept or refuse pending members and cancel pending invitations, they can also change org info.
- [ ] Members can read & modify every org docs
>this can be done only in the front side if needed

Related to #1097

**Comment by Hugo-Hontans** [comment]
We already use an isSuperAdmin boolean in the front-end

**Comment by ioaNikas** [comment]
Close this issue, last step of it will be on #1097
