### ISSUE TITLE
Create a new object Wishlist in the data model

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1132]
## Description 
We need to create a new object wishlist that we will still use after AFM. It is a list of movies with a status (sent, pending) and if sent a date of sending.
Cf. https://projects.invisionapp.com/d/main#/console/18708905/389334927/preview
Every other info display in the page are related to wishlist movies.

**Comment by phpgeekfr** [comment]
Here is my suggestion:
![Screenshot_2019-10-23 Modèle de données - Diagram drawio - draw io](https://user-images.githubusercontent.com/1194344/67379485-4b0d5380-f589-11e9-80ba-2b7bf8bc4498.png)
![Screenshot_2019-10-23 Modèle de données - Diagram drawio - draw io(1)](https://user-images.githubusercontent.com/1194344/67379504-519bcb00-f589-11e9-988b-40f8d692fa66.png)

Organization have an array of wish lists. Only  one can be in `pending` status at the same time. Once user click on `Express my interest`, current wish list status is updated to `sent` and a date is added. A new wish list in `pending` status can then be created.

@Mussuranae @Jackseed  can you check if it seems OK  ?
