### ISSUE TITLE
Check uniqueness of org name on creation

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1142]
## Description
Currently the code check the uniqueness on Ethereum, it should be also checked on firebase

##
- [ ] On the org creation form, check if the name is already used 
- [x] Block the user if the name is taken and show message to explain it

**Comment by pldespaigne** [comment]
when you say "also", you mean "instead" ?

**Comment by pldespaigne** [comment]
it just a query inside `function UniqueOrgName(control: AbstractControl)` in `utils/forms/validators`

**Comment by Jackseed** [comment]
I mean also because in the master the Ethereum check should stay, it is only for the AFM version that we will remove it
