### ISSUE TITLE
Send password reset email with Sendgrid

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1169]
Improvement of #1106

This might be good ressources:
https://medium.com/firebase-developers/generating-email-action-links-with-the-firebase-admin-sdk-4b9d5e2cf914
https://firebase.google.com/docs/auth/web/manage-users#send_a_user_a_verification_email

**Comment by pldespaigne** [comment]
will be fixed by #1102

**Comment by Jackseed** [comment]
done > closed
