### ISSUE TITLE
Add global classes like bold and uppercase

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1189]
Quote from @ioaNikas :
If you use it often, you can also create some variables in styles/style.scss file and reuse them

styles.scss
```
.bold {
   font-weight: bold;
}

.capitalize {
  text-transform: capitalize;
}
```
In component
```
<span class="bold capitalize">...</span>
```
___________________________
Max says: good idea!

**Comment by 11000100111000** [comment]
I'd like to work on this issue, is there a specific list of styles which should be accessable via a standalone class or do i just take a look and see what fits :)

**Comment by Jackseed** [comment]
@Mussuranae : "bold is defined in typo now so no use for this proposition now, only could be for capitalization but not worth it"
