### ISSUE TITLE
Movie model improvements (based on AFM import) 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1193]
- [x] Length: can be string (TBC = To be confirmed), or just accept TBC as a valid value
- [x] Release Date in origin country: can be string when film is not finished yet (like "Summer 2020", "TBC", Q4-2021,...
- [x]  Director's name: for import, include names with space (Marc Di Domenico)

linked to #1562

**Comment by phpgeekfr** [comment]
@Jackseed You said this issue was obsolete right ?

**Comment by phpgeekfr** [comment]
In fact, it is not.
