### ISSUE TITLE
Change page titles according to the page the user is in

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1198]
- [x] Make some research
- [x] Implement it on marketplace first

**Comment by 2amarkina** [comment]
I'm preparing the list of titles to implement, that is here. It'll be finished next Tuesday 
https://docs.google.com/spreadsheets/d/1s1ZSWE0WSTMztJCC2lUxSEba_nYGOkszkhINx6_jmtw/edit#gid=0

**Comment by Maxstgt** [comment]
> I'm preparing the list of titles to implement, that is here. It'll be finished next Tuesday
> https://docs.google.com/spreadsheets/d/1s1ZSWE0WSTMztJCC2lUxSEba_nYGOkszkhINx6_jmtw/edit#gid=0
we should keep this spreadsheet, cause there will be new pages and they need titles

**Comment by Jackseed** [comment]
Got "No titles" on dashboard titles page while I got titles
![image](https://user-images.githubusercontent.com/14964443/78693404-7d262e00-78fb-11ea-87cc-1647d345c871.png)
