### ISSUE TITLE
Bug report for main app

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1251]
### Missing Elements :
- [ ] Nav bar 
  - [ ] context menus
  - [ ] wishlist
  - [ ] notification
- [ ] Update user profile menu to the most recent one

### Bugs :
- [x] [**Yohann**] Wrong links to the applications on route `/layout/o/apps` (missing `/layout/o/` before app name)
- [ ] Side nav elements appear twice when opened
- [ ] Wrong links in both elements of side nav :
First elements : `/layout/o/apps/:appName`
Second elements : `/:appName`
- [ ] Can't access to Wallet page
- [ ] Catalog-Dashboard url seems wrong (`/layout/o/catalog-dashboard/catalog/home`). It maybe make more sense to have something like (`/layout/o/catalog-dashboard/home/`).
- [ ] `Upload Avails & film docs` button doesn't work in Catalog-Dashboard
- [ ] [**Yohann**] Route to delivery seems wrong as `/layout/o/delivery` redirect to delivery lib module. `/layout/o/delivery` should instead redirect to a delivery home, delivery lib module should only be loaded with a movie id.
- [ ] 3 buttons for creating delivery don't work in delivery app
- [ ] Logo & name should be change from Bigger boat to Archipel Content in main app page
- [ ] Terms and Conditions in footer are different for each application. Here we always load the one from archipel content (the only one we have btw).
- [ ] Archipel Content : filters not working in search component (line-up).

**Comment by Jackseed** [comment]
No more main app > close
