### ISSUE TITLE
Internationalization - Research & test

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1260]
## Description 
Archipel Content will gather buyers from all over the world, deliver them a local version is vital. This is not necessary related to the app languages but more about ratings (censorship), movie title and posters (list to be updated by UX). 

## Objectives 
- [x] Create a test project
- [x] Implement Transloco in this project
- [x] Configure Remote config
- [x] Load different version of the site according to the country of the user (France & Germany for titles or textes for instance)

## Questions to answer
- Is it working?
- Does Remote config delay the page load?
- Do we have to put all the texts to change in Remote config or just the language to display?
- If we can put the text in Remote Config, can we put it in the realtime database (not Firestore) or do we have to use a json file in the code?

**Comment by Maxstgt** [comment]
https://www.notion.so/cascade8/Remote-Config-6d20ed9db19b4edf8a0dd5e7b07a464f docs for remote config

**Comment by Jackseed** [comment]
Transloco doc: https://www.notion.so/cascade8/Transloco-48f5c5012b264bd9b812e0d0fdde5c31
i18n doc: https://www.notion.so/cascade8/i18n-57746e8994ab4b198dbf29c3f042ecc6

Thanks guys, I close it.
