### ISSUE TITLE
Implement Akita ng-fire for Delivery guard & service 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1318]
Complete #1258
- [ ] Guard (wait for an update of akita ng fire for delivery-list guard to be functional)
- [x] Service

**Comment by Hugo-Hontans** [comment]
- [ ] Create 3 different services instead of one material service (this to avoid having a dynamic path that could be misused later)
- [ ] Correct updates and other CRUD functions that do not use batch or transactions (for material services)
