### ISSUE TITLE
Implement unit testing in the CI

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1326]
A framework has been implemented, we need to execute it in the CI

- [ ] Execute Spectator in the CI
- [ ] Write some sample tests to pass

**Comment by GrandSchtroumpf** [comment]
We don't need much unit testing on the frontend as it's evolving a lot and would require to much time to maintain. Let's focus on e2e.
Some critical elements of the frontend could still be unit-tested if we realise this is needed like services or some reusable components.
