### ISSUE TITLE
Syntax { relativeTo: this.route } not working as intended in MovieTitleFormComponent (dialog)

### ISSUE THREAD

**Issue by ioaNikas** [blockframes/blockframes#1332]
Seems like this.route is empty when we call it.
Same as TemplateAddComponent (dialog)

**Comment by Hugo-Hontans** [comment]
A solution would be to use resolvePath of @blockframes/utils/routes

**Comment by Hugo-Hontans** [comment]
- [ ] Check navigate relative routes, maybe we use yet "hard link"
- [ ] Check if syntax` { relativeTo: this.route }` working as intended
- [ ] Use relative link the most possible

**Comment by Jackseed** [comment]
outdated > closed
