### ISSUE TITLE
Create a "public users" collection to set/get non sensitive user data

### ISSUE THREAD

**Issue by ioaNikas** [blockframes/blockframes#1359]
It should be a copy of the actual user from `users` collection with public fields like name, surname and avatar.

It should come with firebase functions that catch each modification from users collection and apply them to public users collection.

It should come with specific rules, more secure for users collection, and in the same time more friendly for the public users collection.

**Comment by Jackseed** [comment]
This should be done also with orgs

**Comment by phpgeekfr** [comment]
Closing this old issue. Will re-open it if needed
