### ISSUE TITLE
Activity page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1383]
Implement Activity Feed page (= all notifications). 
Sections are: 
- orgName: notif related to org (new members & request)
- Archipel: org acceptation by Archipel Content
- Titles: CRUD on movies

No modify settings for now
https://projects.invisionapp.com/d/main#/console/19020838/396930413/preview

**Comment by Jackseed** [comment]
should be closed with #1458

**Comment by ioaNikas** [comment]
Can't open pull request for this issue until we fix Catalog, as we need to test it in the right route (dashboard, right now it is in organization/organizationId/activity for testing purpose).
