### ISSUE TITLE
Distribution Deals optimizations

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#1388]
- [x] Update `TERRITORIES` static model to be `ISO-3166` compliant
- [x] Update `LANGUAGES` static model to be `RFC-5646` compliant dedicated issue create #1658
- [x] search for `#1388` in code
- [x] rename to `licensedRights` . checked with @Jackseed

**Comment by Jackseed** [comment]
Best thing for distributionRights would be licensedRights
