### ISSUE TITLE
Replace old code by native akita-ng-fire functions

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#1389]
- [x] see `#1389` in code
- [x] Excel Import - Use the add() method from akita-ng-fire to save movies and sales to DB : It'll create a batch for all movies and sales.

**Comment by Jackseed** [comment]
from the discussion with @GrandSchtroumpf , we'll use akita ng fire where devs want to implement it, closing this ticket

**Comment by phpgeekfr** [comment]
Oppening it again to remove comments
