### ISSUE TITLE
Small updates on organization

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#1398]
- [x] Rename organization.name into organization.denomination
- [x] Add field description : string

**Comment by phpgeekfr** [comment]
@Mussuranae Is this issue completed ?

**Comment by Mussuranae** [comment]
@phpgeekfr yes, my PR is ready too but need the migration script to be merged.
Maybe we can do little script for every change we want to do, because I think that the big script that does all change will never be merged...
