### ISSUE TITLE
Add film + rights tunnel - 4 (credits)

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1409]
https://projects.invisionapp.com/d/main#/console/19020838/398261745/preview
ref blockframes/storymapping#14
On Zeplin :
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0b1e9d81af9a983f2a6d1b

### location
libs/movie/form/sales-cast (existing component - refactoring)
libs/movie/display/sales-cast (existing component - refactoring)
### name
MovieFormSalesCastComponent
MovieDisplaySalesCastComponent

- extract Production year, Production Company, Co-production from main
- do not use mat-chip and split string by comma

![image.png](https://images.zenhubusercontent.com/5cf3f9a6d8501ed6b9d49556/e696248b-f784-4874-981d-c27ac580dca6)
seperate with comma (confirmed with UX team)

**Comment by vwmathilde** [comment]
@jenna1k I think it's commas, but confirm with Anastasiia :)

**Comment by jenna1k** [comment]
> @jenna1k I think it's commas, but confirm with Anastasiia :)

@2m

**Comment by jenna1k** [comment]
@2amarkina 

> @jenna1k I think it's commas, but confirm with Anastasiia :)

**Comment by jenna1k** [comment]
@Mussuranae should talk with anastasiia, mathilde for drop down instead of input for roles

**Comment by Mussuranae** [comment]
DATA :
Production year -> movie.main.productionYear
Producer(s) -> movie.salesCast.credits[].firstname/lastname (role = executive producer)
Production Company -> movie.main.productionCompanies[]
Co-production -> movie.main.productionCompanies[]
Writer(s) -> movie.salesCast.credits[].firstname/lastname (role = writer)
Score composer -> movie.salesCast.credits[].firstname/lastname (role = score composer)
Name of crew member -> movie.salesCast.credits[].firstname/lastname
Role -> movie.salesCast.credits[].role

**Comment by Jackseed** [comment]
- [ ] Producers / Writers / Score Composer / Crew member first name + last name to be done by back team

**Comment by Jackseed** [comment]
First name and last name inputs to create on every credit fields
