### ISSUE TITLE
Add film + rights tunnel - 6 (technical information)

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1411]
https://projects.invisionapp.com/d/main#/console/19020838/398261747/preview
ref blockframes/storymapping#14
On Zeplin :
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0b36dcd30a77171ff94f2b

### location
libs/movie/form/version-info (existing component)
libs/movie/display/version-info (existing component)
### name
MovieFormVersionInfoComponent
MovieDisplayVersionInfoComponent

@2amarkina 
![image](https://user-images.githubusercontent.com/20438637/71071838-a0c33e00-217d-11ea-8d03-6862f78e9650.png)
what formats can user select?
will be format quality changed depends on format?

# E2E Tests to implement 

## Page 6
- [ ] Selects "Dolby SR" for "Sound Format"
- [ ] Selects "SD" for "Format Quality"
- [ ] Selects "Color" for "Color"
- [ ] Toggles "Yes" for "Original language"
- [ ] Selects "English" for "Language" 
- [ ] Clicks "Subtitled" for "English"
- [ ] Clicks on "Next" button
- [ ] Redirects to movie tunnel page 7 Keywords

**Comment by Mussuranae** [comment]
DATA : 
Format and Format Quality need to be created
Color -> movie.salesInfo.color
Language -> movie.versionInfo.languages[]

**Comment by Jackseed** [comment]
- [ ] Format 
- [ ] Format quality
- [ ] Sound format
to be done by back team
