### ISSUE TITLE
Add sidenav for movie tunnel

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1412]
ref blockframes/storrymapping#14

location: libs/movie/layout
name: MovieLayout

features:
- [x] should show the current step in the sidenav
- [x] should have a save button next to the X icon
- [x] should have a X icon for closing the tunnel

@vwmathilde 
![Screenshot from 2019-12-16 17-43-18.png](https://images.zenhubusercontent.com/5d19e757a91f961fd8457e0f/daeefddf-37d9-4ce5-9941-8a13edbc9c94)
I know you know about this, but just to make it official

**Comment by vwmathilde** [comment]
@Maxstgt Haha ! Ok, and I add a save button on my mockup.

**Comment by Jackseed** [comment]
#1468

**Comment by Jackseed** [comment]
- [ ] Align the button on top bar
- [ ] Change expansive pannel on left
- [ ] Use mat nav list
- [ ] Use the good icons
