### ISSUE TITLE
Add film + rights tunnel - 8 (distribution rights)

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1413]
ref blockframes/storymapping#14
On Zeplin :
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0b47c505c6a3160759b6bb

### location
libs/movie/src/lib/distribution-deal (existing component but location should be updated with #1435) 

### name
DistributionRightCreateComponent
DistributionRightDisplayComponent

## Data
This page creates a contract between the right holder (active org) and Archipel Content. 
The form fills in the distribution deal parameters attached to the contract. Every "Licensed Rights" create a new distribution deal. 
So the data architecture is:
Contract AC - Active org > Distribution deals (Licensed Rights # 1, # 2,...) > params from the form

### Contract
The contract parameters are fills in by default
- [ ] Parties:
There are 2 parties in this contract:
*Active org*
-> contract.parties[0].party.orgId = active org id
-> contract.parties[0].party.displayName = active org name
-> contract.parties[0].party.showName = active org name
-> contract.parties[0].party.role = "licensor"
-> contract.parties[0].childRoles = ["sub-licensor", "signatory"]
-> contract.parties[0].status = "submitted"
*Archipel Content*
-> contract.parties[1].party.orgId = archipel org id
-> contract.parties[1].party.displayName = "Archipel Content"
-> contract.parties[1].party.showName = "Archipel Content"
-> contract.parties[1].party.role = "licensee"
-> contract.parties[1].status = "waiting for signature"

-> contract.partyIds = [ activeOrgId; ArchipelOrgId]

- [ ] Film -> contract.titleIds = active movieId
- [ ] Contract status -> contract sub collection version .status = "in negotiation"
- [ ] Contract scope -> contract sub collection version .scope blocked by #1623
.floatingStart = "Contract Signature Date"
.floatingDuration.duration = 10
.floatingDuration.unit = "years"

- [ ] Titles 
-> contract sub collection version .titles.titleId = active movieId
-> contract sub collection version .distributionDealsIds = distribution deal ids from the form

### Distribution deals 
Some parameters are filled by default:
- [ ] Exclusivity -> movie sub collection DistributionDeals (exclusive = yes)
- [ ] Terms  -> movie sub collection DistributionDeals (terms = same as contract)
- [ ] ContractId -> movie sub collection DistributionDeals (contractId = active contract id)

- [ ] Component 1 Territories:
      - Territories -> movie sub collection DistributionDeals (territory[])
      - Excluding the following countries or territories -> movie sub collection DistributionDeals (territoryExcluded[])

- [ ] Component 2 Rights:
 - Rights ->  movie sub collection DistributionDeals (licenseType[])

- [ ] Component 3 Languages :
      - Original language -> movie sub collection DistributionDeals (assetLanguage[])
      - Language -> movie sub collection DistributionDeals (assetLanguage[])

**Comment by Mussuranae** [comment]
DATA : 
Territories -> movie sub collection DistributionDeals (territory[])
Excluding the following countries or territories -> movie sub collection DistributionDeals (territoryexcluded[])
Right name/Holdback/Period -> movie sub collection DistributionDeals (holdbacks[])
Exclusivity -> movie sub collection DistributionDeals (exclusive)
Original language -> movie sub collection DistributionDeals (assetLanguage[])
Language -> movie sub collection DistributionDeals (assetLanguage[])

**Comment by Jackseed** [comment]
@Jackseed datepicker needed / accordeon
