### ISSUE TITLE
Add film + rights tunnel - 10 (upload media)

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1414]
ref blockframes/storymapping#14
on Zeplin :
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0b5ce0ce5cf519870bb60e

#### location
libs/movie/form/promotional-elements
libs/movie/display/promotional-elements
#### name
MovieFormPromotionalElementsComponent
MovieDisplayPromotionalElementsComponent

- should be refactored from ControlContainer to state
- one image for banner and poster, multiple images for promotional photo

@2amarkina 
![image](https://user-images.githubusercontent.com/20438637/71072522-006e1900-217f-11ea-920a-25c2898f0ac4.png)
user can adjust picture size inside of existing cropper
should use the bar?

# E2E Tests to implement 

## Page 10
- [ ] Uploads an image to banner (if possible with cypress)
- [ ] Uploads an image to poster (if possible with cypress)
- [ ] Clicks on "Next" button
- [ ] Redirects to movie tunnel page 11 Files & links

**Comment by 2amarkina** [comment]
user can use the bar to zoom the picture

**Comment by Mussuranae** [comment]
DATA :
Banner image -> movie.promotionalElements[] (type = banner)
Movie poster image -> movie.promotionalElements[] (type = poster)
Promotional photo -> movie.promotionalElements[] (type = other)

**Comment by Jackseed** [comment]
@vwmathilde can you give us image ratios
