### ISSUE TITLE
Add film synopsis and keyword assets - page 3

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1416]
https://projects.invisionapp.com/d/main#/console/19020838/398261744/preview
ref blockframes/storymapping#14
OnZeplin :
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0b1758288676190d30ff72

location
libs/movie/form/synopsis-keyassets

name 
MovieFormSynopsisKeyAssetsComponent - new component
MovieDisplaySynopsisKeyAssetsComponent - libs/movie/display/synopsis-keyassets - new component

things to change
- [x] extract the part html of synopsis from MovieFormMainComponent and keyassets from PromotionalDescriptionComponent
- [x] create own Form with FormEntity, connect to akita

**Comment by Mussuranae** [comment]
DATA :
Storyline -> movie.story.synopsis
Key Assets -> movie.promotionalDescription.keyAssets[]

**Comment by jenna1k** [comment]
data model for Key Assets should be updated (#1478)
