### ISSUE TITLE
Add film budget quota critics - page 5

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1417]
https://projects.invisionapp.com/d/main#/console/19020838/398261746/preview
ref blockframes/storymapping#14
On Zeplin :
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0b2a9a6278a516db62924f

location 
libs/movie/form/budget-quota-critics

name
MovieFormBudgetQuotaCriticsComponent - new component 
MovieDisplayBudgetQuotaCriticsComponent - libs/movie/display/budget-quota-critics - new component

things to change
- [ ] create new form for FormEntity, connect to akita
- [ ] create new component
- [ ] use pegi form and html from SalesInfoComponent
- [ ] Add button should update the current form and render new inputs, see `festival-prizes.form - addPrize()` for example.

**Comment by Mussuranae** [comment]
DATA :
Budget range -> movie.budget.estimatedBudget
Box Office -> movie.budget.boxOffice (need to be created)
Quotas -> movie.salesInfo.certifications
ISAN -> movie.main.officialIds.ISAN
Country -> movie.salesInfo.rating.country
Registration -> movie.salesInfo.rating.system
Rating -> movie.salesInfo.rating.value

For the film review section, need to create all these fields in the DB.

**Comment by Jackseed** [comment]
To be done by back:
- [ ] Film Review
- [ ] Box Office
- [ ] Rating

**Comment by GrandSchtroumpf** [comment]
Wait for update of the data model

**Comment by Jackseed** [comment]
done by @GrandSchtroumpf
