### ISSUE TITLE
Add film keywords - page 7

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1418]
https://projects.invisionapp.com/d/main#/console/19020838/398261748/preview
ref blockframes/storymapping#14
Zepplin https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0b3b1d05c6a3160759a827

location libs/movie/form/keywords

name
MovieFormKeywords - extract existing one from MovieFormPromotionalDescriptionComponent and refactor it

MovieDisplayKeywords -  libs/movie/display/keywords-  extract existing one from MovieDisplayPromotionalDescriptionCompnent and refactor it  

things to change
- [ ] text-area with mat-chips if the word is complete

**Comment by Mussuranae** [comment]
DATA :
Keywords -> movie.promotionalDescription.keywords[]
