### ISSUE TITLE
Add film filesupload page - 11

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1420]
ref blockframes/storymapping#14
on Zeplin :
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0f04da9fc811981cbc7802

location
libs/movie/form/files-upload

name
MovieFormUploadFilesComponent - new component
MovieDisplayUploadFilesComponent - libs/movie/display/files-upload - new component 

things to change
- [ ] create new form with FormEntity, connect to akita
- [ ] remove controlContainer

@vwmathilde 
![Screenshot from 2019-12-17 11-56-28](https://user-images.githubusercontent.com/39312833/70989754-72cdf300-20c4-11ea-86ec-3f3d1ca5b63f.png)
new component detected

# E2E Tests to implement
## Page 11
- [ ] Fills in "https://www.youtube.com/watch?v=n22yzBmr5sY" in "Trailer link" input
- [ ] Clicks on "Next" button
- [ ] Redirects to movie tunnel page 12 Chain of Titles

**Comment by Mussuranae** [comment]
DATA :
Promo reel -> movie.promotionalElements[] (type = reel)
Moodboard -> movie.promotionalElements[] (type = other?)
Scenario -> movie.promotionalElements[] (type = scenario)
Screener link -> movie.promotionalElements[] (type = screener)
Trailer link -> movie.promotionalElements[] (type = trailer)
Teaser link -> movie.promotionalElements[] (type = teaser)

**Comment by Jackseed** [comment]
@Jackseed no promo reel

**Comment by jenna1k** [comment]
new design: https://projects.invisionapp.com/d/main#/console/19020838/398261753/preview

Moodboard -> movie.promotionalElements[].moodBoard
Scenario -> movie.promotionalElements[].scenario
Promo reel link -> movie.promotionalElements[].promoReelLink
Screener link -> movie.promotionalElements[].screenerLink
Trailer link -> movie.promotionalElements[].trailerLink
Teaser link -> movie.promotionalElements[].teaserLink
