### ISSUE TITLE
Add film summary - page 13

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1421]
ref blockframes/storymapping#14
[zeplin](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0f53f7ff95e519ad57c658)
location
libs/movie/form/summary

name
MovieFormSummaryComponent - new component 

things to change
- [x] direct the user to the corresponding page when he clicks on the edit button , pen icon.
- [ ] update the database when the user clicks on submit to archipel content 

## Acceptation criteria
- [ ] Every field marked with * on the form should be marked in red with "Mandatory" if missing
Production status, International Title, Director name, country of origin, original language, genre, running time, cast member, synopsis, production year, production company, banner image, poster image
- [x] Every field not mandatory missing should be marked in yellow with "Missing"

## Data
- [x] Main information component
- Content Type -> movie.main.workType
- Freshness -> movie.main.storeConfig.storeType 
- Production Status -> movie.main.status
- Original Title -> movie.main.title.original
- International Title -> movie.main.title.international
- Reference # -> movie.main.internalRef
- Director Name -> display all the list movie.main.director.firstName + movie.director.lastName
- Director Filmography -> movie.main.director.shortBiography
Countries of Origin section -> display the list for each movie.main.originCountries[x]
- Country -> movie.main.originCountries[0]
- Domestic Distributor -> display  movie.main.stakeholders.displayName where movie.main.stakeholders.role === "distributor" & movie.main.stakeholders.countries === movie.main.originCountries[0]
- Release Media -> movie.salesInfo.originalRelease.media where movie.salesInfo.originalRelease.country === movie.main.originCountries[0]
- Release Date -> movie.salesInfo.originalRelease.date where movie.salesInfo.originalRelease.country === movie.main.originCountries[0]
- Original Languages-> movie.main.originalLanguages[] (display all)
- Genres -> movie.main.genres[] & movie.main.customGenres[] (display all)
- Running Time -> movie.main.totalRuntime
- Principal Cast -> movie.salesCast.cast[].firstName + movie.salesCast.cast[].lastName if movie.salesCast.cast[].role === "lead-role" (display all) 
- Secondary Roles -> movie.salesCast.cast[].firstName + movie.salesCast.cast[].lastName if movie.salesCast.cast[].role === "secondary-role" (display all) 
- Festival -> movie.festivalPrizes.prizes[].name,  movie.festivalPrizes.prizes[].prize,  movie.festivalPrizes.prizes[].year, movie.festivalPrizes.prizes[].premiere (display all)

- [x] Storyline Elements component
- Synopsis -> movie.story.synopsis
- Key Assets -> movie.promotionalDescription.keyAssets
- Keywords -> movie.promotionalDescription.keywords[] (display all)

- [x] Credits component
- Production Year -> movie.main.productionYear
- Production Company -> movie.main.stakeholders[].displayName + (movie.main.stakeholders.country) where movie.main.stakeholders[].role === "executive-producer"  (display all)
- Producers movie.salesCast.producers[].firstName + movie.salesCast.producers[].lastName + (movie.salesCast.producers[].role) (display all) 
- Co-Production movie.main.stakeholders[].displayName + (movie.main.stakeholders.country) where movie.main.stakeholders[].role === "co-producer"  (display all)
- Distributors movie.main.stakeholders[].displayName + (movie.main.stakeholders.country) where movie.main.stakeholders[].role === "distributor"  (display all)
- Artistic crew:
key is -> movie.salesCast.crew[].role / value is movie.salesCast.crew[].firstName + movie.salesCast.crew[].lastName (display all)

- [x] Budget, Quota & Critics
- Budget -> movie.budget.estimatedBudget
- Box office -> 
key: movie.budget.boxOffice.territory / value: movie.budget.boxOffice.number + movie.budget.boxOffice.unit
- Quotas -> movie.salesInfo.certifications[] (display all)
- Rating  -> movie.salesInfo.rating[].country + ": movie.salesInfo.rating[].value" (display all)
- Film Review  -> movie.review[].criticName in movie.review[].journalName "movie.review[].criticQuote" (display all) 

- [x] Technical Information
- Shooting Format -> movie.salesInfo.format
- Format Quality -> movie.salesInfo.formatQuality
- Color - > movie.salesInfo.color
- Sound Format -> movie.salesInfo.soundFormat
- Versions -> "movie.versionInfo.languages key: Original / Dubbed / Subtitled / Closed-Captions if yes | .." display all

- [ ] Images
Banner movie.promotionalElements.banner.media.originalFileName- we don't save the original file name so display the image instead of the file name. 
Blocked by #1665 
Movie Poster movie.promotionalElements.poster[0].media.originalFileName
Blocked by #1665 
Still Photos movie.promotionalElements.still_photo[].ref (?) (display all) - caroussel of pictures we see here
![image](https://user-images.githubusercontent.com/14964443/73002642-a65b1600-3e04-11ea-84d6-2030ac5bb969.png)

- [ ] Files & Links
Promo Reel movie.promotionalElements.promo_reel_link.media.url
Presentation Deck movie.promotionalElements.presentation_deck.media.url
Screener movie.promotionalElements.screener_link.media.url
Trailer movie.promotionalElements.trailer_link.media.url
Pitch Teaser movie.promotionalElements.teaser_link.media.url 

- [ ] Archipel Content Rights
Talk with @GrandSchtroumpf & @Maxstgt or @ioaNikas to get the good contractId & distributionDealsIds[]
Rights # 1
- Territory movie sub collection DistributionDeals (territory[])   
- Except movie sub collection DistributionDeals (territoryExcluded[])
- Terms 2 possibilities: 
movie sub collection DistributionDeals (terms.start) - movie sub collection DistributionDeals (terms.end)
or
"From the movie sub collection DistributionDeals (terms.floatingStart) for  movie sub collection DistributionDeals (terms.floatingDuration.duration) movie sub collection DistributionDeals (terms.floatingDuration.unit)
- Rights movie sub collection DistributionDeals (licenseType[])
- Exclusivity movie sub collection DistributionDeals (exclusivity)
- Dubbed versions : to remove
- Languages movie sub collection DistributionDeals (assetLanguage[]) ; same display as Versions for Technical info
- Subtitled Version: to remove

Rights # 2...
Same but with other distribution deals, if any 

- [ ] Ongoing Deals

- Licensor name contract.parties[X].party.displayName where contract.parties[X].party.role === "licensor"
- Licensee name contract.parties[X].party.displayName where contract.parties[X].party.role === "licensee"
- Territories same as above
- Excluding territories: same as above
- Rights same as above
- Exclusivity same as above
- Terms same as above
- Holdback rights movie sub collection DistributionDeals (holdback.media[])
- Holdback terms movie sub collection DistributionDeals (holdback.terms) same behavior as Terms above
- Versions rename it Languages and same as above 

- [ ] Chain of Titles
Same contractId as for Archipel Rights
- Chain of Titles contract.documents.chainOfTitles.media.originalFileName
Blocked by #1665 

- [x] Marketplace Evaluation
movie.salesInfo.scoring (pipe to display label from the static)

# E2E Tests to implement 

## Page 14
- [ ] Verifies that every field is matching the inputs
- [ ] Clicks on "Submit to Archipel Content" button
- [ ] Redirects to Thank you! page
- [ ] Clicks on "Close window" button
- [ ] Redirects to "My Titles" page

**Comment by Jackseed** [comment]
@Jackseed missing & errors

**Comment by Hugo-Hontans** [comment]
For the field Domestic Distributor of originCountries, I don't have the controls role and countries inside stakeholders (actually we just have displayName).

**Comment by Jackseed** [comment]
for contract summaries: fetch firebase database; it's saved when the user leaves page 8 or 9

**Comment by Jackseed** [comment]
contract query will be made by @ioaNikas #1747

**Comment by Hugo-Hontans** [comment]
I added link to Mandatory and Missing.

**Comment by Jackseed** [comment]
Updated with a more accurate issue #1844
