### ISSUE TITLE
Deals view in detail 

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1425]
ref blockframes/storymapping#11

location 
apps/catalog/deals/view

name
DealsViewComponent - new component

- [ ] fetch the id out of the route
- [ ] depending on the state of the deal, render different components 

# Data
The query has been prepared by @ioaNikas and he detailed how it works here : https://github.com/blockframes/blockframes/issues/1503

**Comment by Jackseed** [comment]
done with #1546
