### ISSUE TITLE
Add film + rights tunnel - 12 evaluate title

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1432]
ref blockframes/storymapping#14
on Zeplin :
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0f0a98517a3eaf17ea7da5

new component

#### location
libs/movie/form/evaluation-title
libs/movie/display/evaluation-title
#### name
MovieFormEvaluationTitleComponent
MovieDisplayEvaluationTitleComponent

@2amarkina 
![image.png](https://images.zenhubusercontent.com/5cf3f9a6d8501ed6b9d49556/8003add4-237c-4a1a-bfd1-cae6671a9499)
should be able to upload multiple files at once?

# E2E Tests to implement 

## Page 12
- [ ] Uploads a pdf file to Chain of titles (if possible with cypress)
- [ ] Clicks on "Next" button
- [ ] Redirects to movie tunnel page 13 Marketplace Evaluation

## Page 13
- [ ] Selects "B" for evaluation
- [ ] Clicks on "Next" button
- [ ] Redirects to movie tunnel page 14 Summary

**Comment by 2amarkina** [comment]
yes, should be able do multiple files at once

**Comment by Mussuranae** [comment]
DATA :
Evalation for AC -> movie.salesInfo.scoring
Chain of titles -> we haven't field for that in DB

**Comment by Jackseed** [comment]
This page will be cut in 2:
1. Chain of titles
2. Evaluation
About Chain of titles, I create a ticket to prepare it in the DB.
For the upload component, better to focus on uploading one pdf at a time, many at once can be done later if complicated

**Comment by Jackseed** [comment]
- [ ] Chain of title to be included by back team
