### ISSUE TITLE
prepare akita for handle the movie tunnel import process 

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1436]
@GrandSchtroumpf should we extend the MovieState with a property `form` or should we create a new +state folder in the movie/lib.
@jenna1k how we can connect the distribution right state that is also in the movie/lib but as a subcollection in our tunnel?

**Comment by Jackseed** [comment]
@Maxstgt is it about excel import or movie tunnel for 1 film ?

**Comment by GrandSchtroumpf** [comment]
Close as we'll use `MovieForm` & `CatalogForm` instead.
Feel free to reopen if it's not the case.
