### ISSUE TITLE
Add a deleted mark to movies when they are deleted instead of deleting them permanently

### ISSUE THREAD

**Issue by Hugo-Hontans** [blockframes/blockframes#1438]
### Description
We won't really delete movies but users will be able to:
- Archive movie (new movie status)
- Once archive, delete it which in fact will remove that org from this movie, but movie will stay in db

### UX
[Here are the wireframes](https://www.figma.com/file/WSbqoyv3Mzkip6yQJGrQR6/%5B-Dashboard-Film-Page-Header-Update-%5D?node-id=108%3A0)

Description of two new statuses:
Archived - titles that are not “in work” anymore, are not displayed in “All titles”, exist as a sort of "trash bin"
Deleted - “deleted” for user (do not appear on app), but actually means for us that a title still exists in the database, but is not displayed in this particular app

**Comment by Jackseed** [comment]
We already store some metadata on `_meta`, we could use that

**Comment by phpgeekfr** [comment]
Update write also the movie guards

**Comment by Jackseed** [comment]
All the guards has to change also so the deleted movies are not loaded

**Comment by Jackseed** [comment]
This is a button to add on the admin panel

**Comment by Jackseed** [comment]
This is a good idea but it has to be developed on the UX side: for the user the mark "deleted" would be more something like "archive" so then they could be re-created if needed. 
It means that we should think of a place where the user can find back the deleted objects. 

There is also the pending question of what do we do with the "satellite" objects that depend on the one we just deleted (for example events linked to movies). 
We could keep it but then if there is a link to the archived movie where does it redirect? Or do we delete it but then we should warn the user of this. Also it could be archived too but then the db would become a great mess. 

@Mussuranae started a list of the satellite objects and what are the delete consequences: https://docs.google.com/spreadsheets/d/1tnAAKEnoUOwpn1yaDGPjmoFcmO34rOCEhjcLji92hYk/edit#gid=0. 

@2amarkina this is not an urgent subject but I add it on the design board so you can work on it at a time before it's implemented.

**Comment by Jackseed** [comment]
Some comments made during sprint 48 retro:

we could use same tabs from Content on top of the title table
"archived" would be a new title status
users should be able to delete the title once archived
flows to design: archive, unarchive and delete a title
could use the same validation modale used in the crm (delete a movie or org)

**Comment by jdrns** [comment]
Wireframes of discussion above are available [here](https://www.figma.com/file/WSbqoyv3Mzkip6yQJGrQR6/Switch-from-draft-to-published-4304?node-id=108%3A0) 

However the reasoning is based on [this other issue](https://github.com/blockframes/blockframes/issues/4304). We would like to allow the user to perform different actions from the movie page directly (dashboard)

**Comment by 2amarkina** [comment]
Updt.
sprint launch: keep up with archive + delete solution 

TO DO: 
- [ ] Cover the case with multi-org

**Comment by Jackseed** [comment]
sprint retro: edge case of multi-orgs on a same movie > we need to cover that edge case, an org can't arbitrary delete a movie if they're not the only owner

**Comment by RemcoSimonides** [comment]
@2amarkina Can you provide the wireframe links for this one?

**Comment by 2amarkina** [comment]
[Here are the wireframes](https://www.figma.com/file/WSbqoyv3Mzkip6yQJGrQR6/%5B-Dashboard-Film-Page-Header-Update-%5D?node-id=108%3A0)

Description of two new statuses: 
Archived - titles that are not “in work” anymore, are not displayed in “All titles”, exist as a sort of "trash bin"  
Deleted - “deleted” for user (do not appear on app), but actually means for us that a title still exists in the database, but is not displayed in this particular app

**Comment by stephanie-cascade8** [comment]
header-view :
https://zpl.io/bLqzqw7

<img width="886" alt="Capture d’écran 2021-06-18 à 13 28 59" src="https://user-images.githubusercontent.com/66258851/122554365-2eb10b00-d039-11eb-862d-8290992f01a2.png">

popup-delete
https://zpl.io/blOqOPk

<img width="899" alt="Capture d’écran 2021-06-18 à 13 28 48" src="https://user-images.githubusercontent.com/66258851/122554389-34a6ec00-d039-11eb-88df-44882cb50453.png">

**Comment by Jackseed** [comment]
Retro notes:
- [ ] Missing the title list with tabs based on status
- [ ] Modale text to update based on [that](https://docs.google.com/spreadsheets/d/1N06uryQf5J7g56kyenJgpZ_HtiXmYb_Evf798E4fwsY/edit?ts=60a244ce#gid=0)
- [ ] Change app logo with the written app name
