### ISSUE TITLE
Create DisplayMovieListComponent

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1447]
location
libs/movie/components/display-movie-list/

name
DisplayMovieListComponent - new component

things to do
- [ ] create a table for all the inputted movies
- [ ] create a table headers that can be used for sorting
- [ ] create a searchbar for regex search
- [ ] add a button for redirecting to movie tunnel

**Comment by Jackseed** [comment]
Has been updated with #1549
