### ISSUE TITLE
Considering deleting the all the display-* components

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#1448]
in the libs/movie/components/display-* directory there are a lot of the display component which where used in the old marketplace app for displaying movie information. But we can use the libs/movie/displays which are used to display the values that are corresponding to the libs/movie/forms components. And from the meeting with Kate at the 18th of December, she assured us, that the form will always stay the sames as the display counterpart and vice versa. 
@GrandSchtroumpf you feel the same?

**Comment by GrandSchtroumpf** [comment]
We can delete the components that are the same (like display-prize & festival-prize I guess). But if there is no equivalent in the display folder we should keep it (like display-keyword for example).

**Comment by fritzschoff** [comment]
display folder are not existing anymore
