### ISSUE TITLE
Play with Kaleido

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1451]

**Comment by lsenta** [comment]
Went through the doc, looks good, but no private stack documentation, sent a request, waiting for feedback from support.

**Comment by lsenta** [comment]
@GrandSchtroumpf if you know some of these guys internally, could you ask them about the private stack and if it's actively supported?

**Comment by GrandSchtroumpf** [comment]
What do you mean by "private stack" ? The privacy layer on the Blockchain ? If yes, it's specific per blockchain. Quorum is using an internal tx manager called "tessera" that keeps it's own state. And Hyperledger besu uses an external tx manager that follow the eea standard.

**Comment by lsenta** [comment]
@GrandSchtroumpf 
https://docs.kaleido.io/kaleido-platform/foundational-concepts/borderless/

Ideally we'd want to run on-premises, with the `Private Stack` option (in the pic, https://docs.kaleido.io/images/hybrid_borderless.png)

**Comment by GrandSchtroumpf** [comment]
So we would stick with Kaleido, but with their stack inside our own infrastructure ?
I'm not 100% sure to understand what is their "stack" exactly, and what we would pay (are we going to pay the Ethereum Node price?).

Did you send them a message ? They were quick to answer to my issues.
