### ISSUE TITLE
Distributed CI with Nx 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1454]
Quick win:
- [ ] implement the easy to implement part and let the rest for later

**Comment by lsenta** [comment]
https://blog.nrwl.io/blazing-fast-distributed-ci-with-nx-a1f5974f7393

**Comment by lsenta** [comment]
run-many used in the article is angular 8.8
https://blog.nrwl.io/storybook-support-run-many-command-ui-improvements-and-more-in-nx-8-8-90575cb5dda4

**Comment by lsenta** [comment]
`npx nx affected:apps` shows ALL APPS affected even on master.

**Comment by lsenta** [comment]
we compute bundle sizes on all apps
but we don't want to build all apps,
this is blocking, we have to either get rid of bundle size, or change how it's run.

**Comment by Jackseed** [comment]
still 1 or 2 days work
