### ISSUE TITLE
Rules for shared doc between orgs

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1457]
Read & Edit rights to implement

**Comment by ioaNikas** [comment]
Movie case : Movies in Catalog marketplace app have to be readable by everyone. Do we want every movies in Delivery to readable by everyone too ? If not, we shall either put movieIds into subArrays making reference to apps, like :

```
moviesIds : {
    catalog: [ movieId1, movieId2, movieId3],
    delivery: [ movieId2, movieId4]
}
```

But it means a LOT of refactoring everywhere in the app (everywhere movie CRUD is used).

Other solution would be to add a property to set the movie public or not like :

```
movie : {
    main : {
        isPublic: true
    }
}
```

**Comment by ioaNikas** [comment]
I'd like to define different rules for subcollections. For example, I only want the document owner to be able to invite or remove new stakeholders to work on it, but I still want those stakeholders to perform every CRUD operations in materials subcollection.

Problem is firestore rules doesn't seem to work if we write something like this 
```
match /deliveries/{deliveryId} {
      allow read: if documentPermissionsExist(userOrgId(), incomingData().movieId);
      allow create: if userHasValidOrg()
      	&& documentIdChecked(deliveryId, 'deliveries');
      allow update: if orgCan('canUpdate', userOrgId(), deliveryId)
      	&& documentIdChecked(deliveryId, 'deliveries')
        && incomingData().id == existingData().id
        && incomingData().movieId == existingData().movieId;
      allow delete: if orgCan('canDelete', userOrgId(), deliveryId);
			
      match /materials/{materialdId} {
      	allow read: if userHasValidOrg();
      	allow create: if userHasValidOrg();
      	allow update: if orgCan('canUpdate', userOrgId(), deliveryId)
          && incomingData().id == existingData().id;
      	allow delete: if orgCan('canDelete', userOrgId(), deliveryId);
      }

      match /stakeholders/{stakeholderId} {
      	allow read: if userHasValidOrg();
      	allow write: if isOwner(userOrgId(), deliveryId);
      }
    }

```

BUT this however works
```
match /deliveries/{deliveryId} {
      allow read: if documentPermissionsExist(userOrgId(), incomingData().movieId);
      allow create: if userHasValidOrg()
      	&& documentIdChecked(deliveryId, 'deliveries');
      allow update: if orgCan('canUpdate', userOrgId(), deliveryId)
      	&& documentIdChecked(deliveryId, 'deliveries')
        && incomingData().id == existingData().id
        && incomingData().movieId == existingData().movieId;
      allow delete: if orgCan('canDelete', userOrgId(), deliveryId);
			
      /// stakeholders & materials ///
      match /{documents=**} {
      	allow read: if userHasValidOrg();
      	allow create: if userHasValidOrg();
      	allow update: if orgCan('canUpdate', userOrgId(), deliveryId)
          && incomingData().id == existingData().id;
      	allow delete: if orgCan('canDelete', userOrgId(), deliveryId);
      }
    }
```

Need to find out why.

**Comment by ioaNikas** [comment]
To make document sharing more secure, we need to change Delivery data model.
It is related to an old issue #639 

Currently, when we invite an Organization to work on a Delivery, we grant her access to the movie, and the invited Organization can view the list of all deliveries of this movie (even if she can't navigate to a Delivery where she is not stakeholder).

To ensure this behavior and keep other deliveries "private", we need to specify in the query that we only want deliveries where this organization appears in the delivery's stakeholders. To do so, we must have a reference of the stakeholders **inside** the Delivery object.

This is how the query looks like
```
const deliveriesListQuery = (movieId: string, orgId: string): Query<DeliveryWithTimestamps[]> =>  ({
  path: 'deliveries',
  queryFn: ref => ref.where('movieId', '==', movieId).where('stakeholderIds', 'array-contains', orgId),
  stakeholders: delivery => ({
    path: `deliveries/${delivery.id}/stakeholders`,
    organization: stakeholder => ({
      path: `orgs/${stakeholder.orgId}`
    })
  })
})
```

**Comment by Jackseed** [comment]
@lsenta is rewieving the PR
I'll will check on the app side

**Comment by Jackseed** [comment]
#1490 is opened after this issue
