### ISSUE TITLE
Implement new list component

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1458]
- [ ] Update component corresponding to Zeplin
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5dee65a7e78a5a143d18a94e
- [ ] Update searchbar results
- [ ] Update Activity feed
- [ ] Update Notifications

ref #1379 #1383 #1380

**Comment by Jackseed** [comment]
@ioaNikas worked on it already - to confirm. @jenna1k @Mussuranae can you talk to him and finish it? Let's focus on our strength ;)

**Comment by ioaNikas** [comment]
> @ioaNikas worked on it already - to confirm. @jenna1k @Mussuranae can you talk to him and finish it? Let's focus on our strength ;)

@Jackseed I just worked on the reusability of "lists" components so we can call them by their selector in both Activity feed and widget. Right now, they are `mat-card`, not `mat-list`. I'll open a pull request about that next monday, but @jenna1k already can work on mat list style I guess.

**Comment by Jackseed** [comment]
Not relevant anymore
