### ISSUE TITLE
Movie form : check how to create a route for each section

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#1463]
use akita to store form inputs between routes

**Comment by lsenta** [comment]
- [ ] decide to save as draft? how? etc.
- [ ] decide how to deal with routes, etc.

**Comment by Jackseed** [comment]
- [ ] how components will get the data from other pages?

**Comment by Jackseed** [comment]
- [ ] can we re-use the form to edit the film?

**Comment by GrandSchtroumpf** [comment]
Tunnel routes : 
- movie-tunnel/:movieId/{tunnel-page-name} (if movideId === 'create' don't fetch existing data)

Store data locally before saving : 
- Option 1: Injectable `MovieForm` (but might not be garbaged collected when you leave tunnel)
- Option 2: Store data in Store, and use `PersistForm` plugin from akita

Save as draft : 
- Should be a flag (public/private) on the document that we can use for queries.

How components will get the data from other pages : 
_Not sure to understand the question_
- Data will be global (either in store or in a MovieForm) and can be reach from all pages.

Can we re-use the form to edit the film :
- Yes with the `:movieId` param in the route. If param is different from "create", then fetch (once) the data from firestore and fill the form with the content.

**Comment by Jackseed** [comment]
- [ ] flag private / public implemented by back team

**Comment by Jackseed** [comment]
ref #1410
