### ISSUE TITLE
Sync Data and UI

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1478]
list of unmatch data:
- [x] key assets : should be string not array (#1416) C 
- [x] Distributor of country of origin (add distributor on  MovieOriginalReleas ? confirm with @Jackseed ) B => not usefull since we have the data into stakeholders
- [x] Specific genre C

**Comment by Jackseed** [comment]
- [ ] Update migration script

**Comment by Jackseed** [comment]
Genre other: 
add a field custom genre: string if the user fills a genre other

**Comment by Jackseed** [comment]
Distributor country of origin:
object with country / distributor / release

**Comment by Jackseed** [comment]
- [ ] Add boxOffice object in the code
- [ ] Rating
- [ ] Film review

**Comment by Jackseed** [comment]
- [ ] Chain of titles documents

**Comment by Jackseed** [comment]
- [ ] flag for private / public movies

**Comment by Jackseed** [comment]
- [ ] Producers / Writers / Score Composer / Crew member first name + last name

**Comment by Jackseed** [comment]
- [ ] Format 
- [ ] Format quality
- [ ] Sound format

**Comment by jenna1k** [comment]
[ ] co-production company

**Comment by phpgeekfr** [comment]
- [ ] check version info (ask @Maxstgt )

**Comment by jenna1k** [comment]
- [ ] movie.poster : main.poster should be moved to PROMOTIONAL_ELEMENT because main poster for a given movie may vary depending on the country.
So we could add a new type in PROMOTIONAL_ELEMENT_TYPES : `main_poster` so we can fetch the main movie poster for a specific country (confirmed with @phpgeekfr )
- [ ] new type `still_photo` in PROMOTIONAL_ELEMENT_TYPES

**Comment by phpgeekfr** [comment]
- [ ] remove formatProfile from distributiondeals & merge quality format & quality profile enums
- [ ] multidiffusion => Terms[]

**Comment by phpgeekfr** [comment]
- [ ] move `europeanQualification` to `certifications`

**Comment by Jackseed** [comment]
- [ ] Add sub-licensor to the legalRoles staticModels and automatically add the licensor of the licensor sub-licensor to a contract.
e.g. Netflix (licensee) buys to AC (licensor) a film; the producer/sales agent in this film is sub-licensor of this contract

**Comment by phpgeekfr** [comment]
- [ ] rename `MovieMain.languages` to `MovieMain.originalLanguages` B

**Comment by phpgeekfr** [comment]
@jenna1k I found several comments `<!-- TODO#1478 Sync Data and UI  -->` and `//  TODO#1478 Sync Data and UI, remove movie-form-key-assets from selector` . I don't understand them and would like to close this issues soon without Issues 1478 references in comments. Can you be more specific ?

**Comment by phpgeekfr** [comment]
- [] Transform child role of party into array so that a Party can be [signatory, sublicensor] for child contracts B
