### ISSUE TITLE
e2e test for movie tunnel page 5

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1479]
## Page 5 (related to #1417 )
- [x] Selects "$ Less than a 1 million" from "Budget range"
- [x] Selects "Box office in $" from "World-wide" 
- [x] Fills in "120000" in "World-wide box office"
- [x] Selects "# Entrances" from "Domestic" 
- [ ] Fills in "30000" in "Domestic box office" / There is only one input for number here
- [x] Clicks on "EOF" chip 
- [x] Clicks on "European" chip 
- [x] Fills in "Fr" in "Rating Country" autocomplete input
- [x] Selects "France" in the autocomplete list
- [x] Fills in "Tous publics" in "Rating" input
- [x] Fills in "NY Times" in "Revue or journal name" input
- [x] Fills in "“Lagerfeld Confidential,” an intimate portrait of the designer who has ruled the House of Chanel for more than two decades." in "Film critic quote" input
- [x] Fills in "https://www.nytimes.com/2007/10/24/movies/24lage.html" in "Revue link" input
- [x] Clicks on "Next" button
- [x] Redirects to movie tunnel page 6 Technical information

**Comment by Hugo-Hontans** [comment]
I need #1417 to be progressed to continue on this issue
