### ISSUE TITLE
backend function onMovieCreate must use transaction

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#1498]
backend function `onMovieCreate` must use transaction because if we add 10 movies in parallel, some org.movieIds are missing.

**Comment by Jackseed** [comment]
ref #773

**Comment by phpgeekfr** [comment]
@ioaNikas added a transaction in OnMovieCreate but still getting the same bug.  5 of 10 movie Ids have been added to org.movieIds.

Need more investigation
