### ISSUE TITLE
Link Analytics to Firebase

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1500]
We need to have on Firebase stats from Analytics:
- Movie views (visits on a movie page from marketplace) 
- Promo reel clicks (clicks on "Watch promo reel" on a movie page from marketplace)
- Add to wishlist clicks
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/c906b4b6-e5c4-458b-b2ca-14ae31a8f110)

**Comment by lsenta** [comment]
- [ ] check / implement the tracking for VIEW / CLICKS events
- [ ] implement a firebase function to retrieve google analytics stats and present it to the user (@phpgeekfr has reference materials)

**Comment by Jackseed** [comment]
done, congratz guys
