### ISSUE TITLE
Contract service

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1506]
- [x] Create the service 
- [x] Setup akita ng fire
- [x] Create contract related functions
- [ ] Repeat all these steps for Contract subcollection (versions)

ref #1440

**Comment by ioaNikas** [comment]
@phpgeekfr did the function part.

**Comment by ioaNikas** [comment]
Most of the functions now use native CRUD from CollectionService.
However, beware of subcollection service (versions) as it always need an active Contract to perform his own CRUD. If some of the functions are called without an active Contract in the store, we have two less elegant solutions :
- use basic syntaxe (`db.doc(...)`) with an `id`.
- manually set the contract active in the store (`this.store.setActive(id)`).
