### ISSUE TITLE
unsupported file type when uploading an excel on windows

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#1520]
unsupported file type when uploading an excel document for importing movie/deals/contract  on windows.

**Comment by phpgeekfr** [comment]
@GrandSchtroumpf @pldespaigne  added you to this ticket since you are Windows users. Can you have a look at it ? It should not be something big to debug

**Comment by phpgeekfr** [comment]
added @jenna1k too since she add the issue.

**Comment by GrandSchtroumpf** [comment]
Can you specify the exact path to the page ?

**Comment by jenna1k** [comment]
> Can you specify the exact path to the page ?

http://localhost:4200/c/o/dashboard/import

**Comment by phpgeekfr** [comment]
![image](https://user-images.githubusercontent.com/1194344/73005194-d60c1d00-3e08-11ea-8f50-130da915958d.png)
