### ISSUE TITLE
Dynamically render the plural of words

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1523]
In the designs we see a lot like `Language(s)`. Depending how many languages are displayed or imported or what ever. I think it is nice to have like `Language` and if there are more then one language, we dynamically render the plural of the word instead.

**Comment by Maxstgt** [comment]
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0b36dcd30a77171ff94f2b for instance at `Versions Available`

**Comment by GrandSchtroumpf** [comment]
You can checkout i18n pipe `plural`, maybe you can use it for that : 
https://angular.io/guide/i18n#pluralization

**Comment by Jackseed** [comment]
Good idea, we should implement that if it's as easy as a pipe but then I should point it out where to put it. 
I'll complete this issue with a list.

**Comment by Maxstgt** [comment]
@Maxstgt would say shotgun for next sprint

**Comment by Maxstgt** [comment]
https://www.notion.so/cascade8/Pluralization-63975204b5a742c8a1620d01f1a11e91
