### ISSUE TITLE
Offers & Deals list

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1545]
## UI
[zeplin](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e1f233a1ffb15bd95efb518)
[zeplin every columns](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e1f233d751c53805495da75)

## Path
catalog/dashboard/deal/list

## Name
DealsListComponent - new component

## Acceptance Criteria
- tabs for All / Offers / Ongoing Deals / Past Deals / Aborted Offers #1621
- table component #1555 

## Data
Notes from @Jackseed here we always use the last version of the contract. 
Notes from @ioaNikas who prepared the query:

:fire: We'll need to transform our contract list to have all contracts with the last version in it.
Looks like this in the component.ts
```
public contracts$: Obervable<ContractWithLastVersion[]>;

ngOnInit() {
  this.contracts$ = this.contractQuery.selectAll().pipe(
    map(contracts => contracts.map(async contract => 
      return await getContractWithLastVersion(contract))
    )
  );
}
```

For informations related to movies, we can load organization movies in the guard and fetch information with the id:
```
public getMovie(movieId: string) {
  return this.movieQuery.getEntity(movieId);
}

// call this function in the HTML, movie ids are the key of objects 
// from titles field : contract.last.titles[movieId]
```

Same logic for the territories for each contract :
```
public getTerritories(contractId: string) {
  const deals = await this.distributionDealService.getContractDistributionDeals(contract.id);
  return this.distributionDealService.getDistributionDealsTerritories(deals);
}
```
### Tabs 
Contracts are gathered into a tab according to the status of their last version. 
=> Already defined in firestore.ts file. Access with  
-  in the service
```
const contractWithVersion = getContractWithLastVersion(contractId);
const contractStatus =  contractWithVersion.last.status;
``` 
- `contractQuery.getActive().lastVersion.status` in the component.

- [x] Offers: status "submitted", "under negotiation", "waiting for signature"
- [x] Ongoing Deals "accepted", "waiting for paiment"
- [x] Past Deals "paid"
- [x] Aborted Offers "aborted", "rejected"

### Table
- [x] Buyer name (= licensee display name)
=> ContractVersion.parties[index].party  
Licensee name is stored into `displayName` property.
To get licensee informations into an object
```
const licensees = getContractParties(this.contractQuery.getActive(), 'licensee');
console.log(licensees[0]);
// we assume there is only 1 licensee per contract.
// returns this object: { displayName: "Rodriguez", logo: {...}, orgId: "ezf4f8z45efz", role: "licensee", displayName: true}
```
- [x] Date received -> contractWithVersion.last.creationDate
- [x] Territories 
This comes from distribution deals:
=> Distribution deals are loaded into the state of movies (ContractMoviesGuard).
You can loop into movies and then into distributionDeals.
```
@Component({
  selector: 'movie-distribution-deals-list',
  template: `
    <section *ngFor="let movie of (movies$ | async)">
      <distribution-deal-item 
          *ngFor="let deal of movie.distributionDeals" [deal]="deal">
      </distribution-deal-item>
    </section>
  `
})
export class MovieDistributionDealsListComponent extends onInit {
  public movies$ = Obervable<Movie[]>
  constructor(private movieQuery: MovieQuery) {}
  
  ngOnInit() {
    this.movies$ = this.movieQuery.selectAll();
  }
}
```
Territories column includes all the territories from all the distribution deals on all movies owned by the active org included in one deal. 
The territories from one distribution deals is equal to the territories included minus the territories excluded:
-> T = deal.territory (Territories[]) - deal.territoryExcluded (Territories[])
Then you sum T from all the distribution deals on a movie (= Tm)
Then sum the Tm from all the movies owned by the active org in the deal (=Tfinal)

- [x] # Films
=> Specific query (ContractMoviesGuard) + ContractTitleDetail
Total amount of movies owned by the active org on Archipel Content ( -> org.movieIds.archipelContent) included in the contract (contract.titleIds)
Display the total amount of movies loaded

- [x] Titles
 => Movies will be fully loaded, every property is reachable
-> movie.title.international 
for each films counted above
- [x] Price
Price is the sum of each film price counted above 
-> sum of contractWithVersion.last.titles.[movieIdsOwnedByActiveOrg].price
- [x] Paid -> not ready yet #1397
- [ ] Remaining -> not ready yet #1397
- [x] Status -> contractWithVersion.last.status

**Comment by Maxstgt** [comment]
deals and offers should be available cause we already passes the o/ and c/ route which checks if your are connected and gives you the possibilities to query all the information you need from your organization

**Comment by Jackseed** [comment]
I deleted the acceptance criteria:
- menu to view deal memo, download and share deal (new tab for view deal memo? how to share with member? with url?)
This menu 
![image](https://user-images.githubusercontent.com/14964443/72336315-cb42e100-36c0-11ea-981c-f34c7419ce74.png)
is on hold for first version, we'll see when we get there.

**Comment by Jackseed** [comment]
Issue edited with data
