### ISSUE TITLE
Deal page (+ counter offer / closed states)

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1546]
## UI
[zeplin](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e2581820bc6f52d464e2b6f)

## Path
catalog/dashboard/deal/view

## Acceptance Criteria
- Breadcrumb navigation #1618 
- [show negotiation history](https://projects.invisionapp.com/d/main?origin=v7#/console/19020838/398158859/preview?scrollOffset=1433.3333740234375)
- Table component #1555 
- Expansion panel cards #1622

## Dev Notes/Resources
- check catalog/marketplace/wishlist

## Data
All the data displayed in this page comes from the last version of the contract. Except for the Negotiation history component

### Page title
![image](https://user-images.githubusercontent.com/14964443/72685815-02185d00-3aee-11ea-92c5-c52882c994bf.png)

- [x] Contract status "New offer" chip -> contractWithVersion.last.status;
=> Already defined in firestore.ts file. Access with  
-  in the service
```
const contractWithVersion = getContractWithLastVersion(contractId);
const contractStatus =  contractWithVersion.last.status;
``` 
- `contractQuery.getActive().lastVersion.status` in the component.

- [x] Licensee name, logo and address

=> ContractVersion.parties[index].party is missing the field `address`. 
Licensee name is stored into `displayName` property.
To get licensee informations into an object
```
const licensees = getContractParties(this.contractQuery.getActive(), 'licensee');
console.log(licensees[0]);
// we assume there is only 1 licensee per contract.
// returns this object: { displayName: "Rodriguez", logo: {...}, orgId: "ezf4f8z45efz", role: "licensee", displayName: true}
```
- [x] Movie number "2 films"
Loads only movies included in the contract (contract.titleIds) where the active org owns the film on Archipel Content ( -> org.movieIds.archipelContent)
=> Specific query (ContractMoviesGuard) + ContractTitleDetail
Display the total amount of movies loaded

- [x] Active org price "$143 450" is the total amount of each price titles owned by the active org (=Z):
=> Specific query (ContractMoviesGuard) + ContractTitleDetail
-> Z = sum of contractWithVersion.last.titles.[movieIdsOwnedByActiveOrg].price

- [x] Date is the contractWithVersion.last.creationDate

### Contract summary
![image](https://user-images.githubusercontent.com/14964443/72685153-64ba2a80-3ae7-11ea-8c20-466c893db0ab.png)

The text is composed with: 
- [x] Licensee name (same as page title) "Netflix"
- [x] Total amount of movies included in the deal ( -> contract.titleIds.length) "6 titles"
- [x] Total amount of movies owned by the active org (same as page title) (=X) "X of which are yours"
- [x] Total of contract parties with the "sub-licensor" role (= Y)
( -> contract.parties[index].party.role === "sub-licensor")
if Y =1 skip the sentence "We are gathering approval from 2 other sellers."
if Y > 1 "We are gathering approval from X-1 other sellers."
- [x] Active org price is the total amount of each price titles owned by the active org (=Z):
=> Specific query (ContractMoviesGuard) + ContractTitleDetail
-> Z = sum of contract.lastVersion.titles[orgMovieId].price.amount.
if Y =1 display the sentence "The offer is Z for the X titles". 
if Y > 1 "Your share of the deal is Z for the X titles."
- [x] Movie titles owned by the active org
 => Movies will be fully loaded, every property is reachable
-> movie.title.international
"- Suicide Tourist
- Simon's Got a Gift"
The 3 action buttons are OPTIONAL: 
- [x] show it only if the active org has a role "signatory" in the contract 
-> contract.parties[orgActiveIndex].party.role (static LEGAL_ROLES)
@Jackseed Shall we also check `status` so if it's "accepted" or "rejected" we can't see the buttons anymore ?
- [x] Decline button change the status of the active org as a contract party to "Rejected"
-> contract.parties[orgActiveIndex].status (enum) = "rejected"
- [x] Accept button change the status of the active org as a contract party to "Accepted" & set the signDate to the current date
-> contract.parties[orgActiveIndex].status (enum) = "accepted"
-> contract.parties[orgActiveIndex].signDate (Date) = current
- [x] Connect with the Archipel Team button opens Intercom panel

### Payment schedules 
![image](https://user-images.githubusercontent.com/14964443/72684504-5701a680-3ae1-11ea-9c6c-a893a0db1df7.png)
=> ref #1397 
- [x] Display the list of payment schedules included in the last version of the contract (version.paymentSchedule: PaymentSchedule[])
"20%" -> contractWithVersion.last.paymentSchedule.percentage
"On Signature" -> contractWithVersion.last.paymentSchedule.label
"S2-2020" -> contractWithVersion.last.paymentSchedule.date

### Negotiation history
![image](https://user-images.githubusercontent.com/14964443/72685110-2290e900-3ae7-11ea-9e85-e2af59dd89f2.png)
- [x] Display all the version of the contract
Access with  
- `contractVersionService.getValue()` in the service.
- `contractVersionQuery.selectAll({ sortBy: 'id', sortByOrder: Order.DESC })` in the component. NB: sort by 'id' and sort by 'creationDate' should return same order.
The table is composed with:
version.creationDate (US format)
version.price (US format)
version.status

### Movies
Display only movie owned by the active org included in the contract.
=> Specific query (ContractMoviesGuard) + ContractTitleDetail
![image](https://user-images.githubusercontent.com/14964443/72685974-cf6f6400-3aef-11ea-8ceb-1102d6ea39d7.png)
- [x] Movie titles, origin countries, production year, poster, director
=> Movies will be fully loaded, every property is reachable
movie.main.poster
movie.main.title.international
movie.main.directors (Person[])
movie.main.originCountries (TerritoriesSlug[])
movie.main.productionYear

- [x] Movie price on the contract
-> contract.lastVersion.titles[movieId].price.amount

![image](https://user-images.githubusercontent.com/14964443/72685983-e2823400-3aef-11ea-869a-3a93bc36977f.png)

- [x] Distribution deals attached to each movie included in the contract 
=> Distribution deals are loaded into the state of movies (ContractMoviesGuard).
You can loop into movies and then into distributionDeals.
```
@Component({
  selector: 'movie-distribution-deals-list',
  template: `
    <section *ngFor="let movie of (movies$ | async)">
      <distribution-deal-item 
          *ngFor="let deal of movie.distributionDeals" [deal]="deal">
      </distribution-deal-item>
    </section>
  `
})
export class MovieDistributionDealsListComponent extends onInit {
  public movies$ = Obervable<Movie[]>
  constructor(private movieQuery: MovieQuery) {}
  
  ngOnInit() {
    this.movies$ = this.movieQuery.selectAll();
  }
}
```
The distribution deal table columns are:
- [x] Territory
Territories column includes all the territories from all the distribution deals on all movies owned by the active org included in one deal. 
The territories from one distribution deals is equal to the territories included minus the territories excluded:
-> T = deal.territory (Territories[]) - deal.territoryExcluded (Territories[])
Then you sum T from all the distribution deals on a movie (= Tm)
Then sum the Tm from all the movies owned by the active org in the deal (=Tfinal)
- [x] Start Date - deal.terms.start (date) or deal.term.floatingStart (enum) (the one which is correct)
- [x] End Date - deal.terms.end (date) or deal.term.floatingDuration (the one which is correct)
- [x] Rights - deal.licenseType  : Media[]
- [ ] Languages - deal.assetLanguage {[language in LanguagesSlug (static)}
- [ ] Holdback - deal.holdbacks.terms.media deal.holdbacks.terms.start deal.holdbacks.terms.end (Holdback[])
- [ ] 1st Broadcast Date - deal.multidiffusion.[0].start (Terms[])
- [ ] Exclusive - deal.exclusive
- [ ] Multidiffusion - deal.multidiffusion.length
- [ ] Catch up - deal.catchUp.start-deal.catchUp.end

**Comment by Maxstgt** [comment]
@jenna1k I don't see where breadcrumbs navigation should take place? 
This is a detailed view of a deal. So in the route there should be an :id of this deal for akita to fetch the correct data. **So there should be a guard for that.**
Also the child components should be placed in the corresponding lib depending on what data model they operating on.

**Comment by jenna1k** [comment]
> @jenna1k I don't see where breadcrumbs navigation should take place?

it is above the company information, but actually it just links to deals page and show refrence number of the current deal.
![image](https://user-images.githubusercontent.com/20438637/72265174-54540c80-361c-11ea-8607-19e135a590c3.png)
