### ISSUE TITLE
Dashboard superUser

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1547]
## UI
[invision](https://projects.invisionapp.com/d/main#/console/19020838/397122067/preview)

## Path
catalog/dashboard/overview

## Acceptance Criteria
- chart component #1556 
- marketplace activity: line chart with counts & percentage
- sales revenue: 
  - pie chart for total revenue by format
  - period tabs & toggle for total revenue
- sales deals (@vincent same with offer&deals list?)
## Dev Notes/Resources

**Comment by Maxstgt** [comment]
these charts can be made with d3.js.
these charts component can placed in the ui lib. Cause they are reusable. Also make them configurable through the input, so that you can specify the text and the number they should show. Make them stateless.
