### ISSUE TITLE
Search Result

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1548]
## UI
[Zeplin search result page](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e26f3f5966e017e134f6865)
[Zeplin searchbar](https://projects.invisionapp.com/d/main?origin=v7#/console/19020838/396930416/comments?scrollOffset=3563.33349609375)

## Path
catalog/dashboard/pages/search

## Acceptance Criteria
- search only on movies index
- movie title, keywords, genre or director is used for search input
- only one tab "Titles (x)", no Offers and Deals yet #1738 
- use re-usable table component from #1555 (no styling, no bold)
- display search results with the search bar
- display search results in the search result page

## Dev Notes/Resource
Use what has been done for marketplace

**Comment by Maxstgt** [comment]
table -> lib/DATA-MODEL?/components/
