### ISSUE TITLE
Film list query

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1549]
## UI
[invision](https://projects.invisionapp.com/d/main?origin=v7#/console/19020838/396946394/preview?scrollOffset=1433.3333740234375)

## Path
catalog/dashboard/title/list

## Name 
DisplayMovieListComponent - new component

## Acceptance Criteria
- add button links to movie-tunnel
- delete/edit with menu @Jackseed What about this button ? Still need it ? Vincent: no, we don't
- DisplayMovieListComponent #1447 
### Tabs
Filter the movies displayed in the table
- [x] All -> active org movies (org.movieIds)
- [x] Library -> movie.main.storeConfig.storeType === "Catalog"
- [x] Line-up -> movie.main.storeConfig.storeType === "Line-up"

### Table
- [x] Title -> movie.main.title.international
- [x]  View -> http request to BigQuery, ask @Hugo-Hontans #1636 
- [x] Sales -> it's the number of contracts where the movie is included (1 contract = 1 sale):
1. Use only contracts where the active org is a party with sub-licensor role (-> contract.parties.party[?].orgId === active org id & contract.parties.party[active org id].role === sub-licensor) and where the contract status is validated ( contractWithVersion.last.status === "waiting for paiement" or " paid" or "accepted")
2. In this contract we want to know only those where the movie is included (contractWithVersion.last.titles[movieId] exists)

=> contractWithVersion already defined in firestore.ts file. Access with
in the service
const contractWithVersion = getContractWithLastVersion(contractId);
const contractStatus =  contractWithVersion.last.status;
contractQuery.getActive().lastVersion.status in the component.

- [x]  Total Gross Receipts -> We want the same contracts as for "Sales" and sum the movie price of each of them (contractWithVersion.last.titles[movieId].price.value)

- [x] Status -> movie.main.storeConfig.status

**Comment by Maxstgt** [comment]
table with filter and button can live in lib/movie/components/
