### ISSUE TITLE
Film page stats

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1550]
## UI
[invision](https://projects.invisionapp.com/d/main?origin=v7#/console/19020838/397098005/preview?scrollOffset=1766.666748046875)

## Path
catalog/dashboard/title/sales

## Acceptance Criteria
- chart component #1556 
- user can see [view sales report](https://projects.invisionapp.com/d/main?origin=v7#/console/19020838/398134575/preview?scrollOffset=1766.666748046875)  first half of the year and latter half of the year
(is it for download? is sales report sales screen or there will be more detail? @vincent) 
- Movie stats components #1450 
## Dev Notes/Resources
most part is same as catalog/dashboard/overview but for one movie

**Comment by Maxstgt** [comment]
these charts could be made previously by another issue and can be reused here. One new chart is the bars chart. place it in the ui lib.
