### ISSUE TITLE
Film page details

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1551]
## UI
[invision](https://projects.invisionapp.com/d/main?origin=v7#/console/19020838/397981273/preview?scrollOffset=1766.666748046875)

## Path
catalog/dashboard/title/details

## Acceptance Criteria
- edit button links to movie-tunnel page
- carousel for promotional photo
- wait for the query from #1624 for the contract parts
## Dev Notes/Resources
can reuse catalog/dashboard/movie-tunnel/[summary page](https://projects.invisionapp.com/d/main?origin=v7#/console/19020838/398261755/preview?scrollOffset=5137.7138671875)?
we need to discuss about movie/display, should be by components or by page?

**Comment by Maxstgt** [comment]
this page should use the component located int the lib/movie/display/* . They need a refactoring!

**Comment by Jackseed** [comment]
updates listed on #1865
