### ISSUE TITLE
Film page Sales tab - Offers & Deals Table

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1552]
## UI
[Zeplin](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e26d5fc683ce156ce01990b)
![image](https://user-images.githubusercontent.com/14964443/73384555-c63e7e00-42cb-11ea-8c78-bf684b5f204b.png)
## Path
catalog/dashboard/title/avails
## Acceptance Criteria
- no map
- use reusable table (blocked by?) #1774
## Data 
Same parameters as #1545, query:
- [ ] all contracts where the active org is a "sub-licensor" party and where the active movie is in contract.titleIds

**Comment by Maxstgt** [comment]
worldmap => ui lib with d3.js
distribtuionTable => lib/movie/distribution-deal/components/
