### ISSUE TITLE
Table with filter and button/filter menu

### ISSUE THREAD

**Issue by jenna1k** [blockframes/blockframes#1555]
## UI
[Deals table](https://projects.invisionapp.com/d/main#/console/19020838/400422884/preview)
[Distribution deals table](https://projects.invisionapp.com/d/main#/console/19020838/398158859/preview)
[Payment history table](https://projects.invisionapp.com/d/main#/console/19020838/400798075/preview)
[Bulk upload table](https://projects.invisionapp.com/d/main#/console/19020838/397981061/preview)
[Org members table](https://projects.invisionapp.com/d/main#/console/19020838/401452566/preview)
[Search results table](https://projects.invisionapp.com/d/main#/console/19020838/397530768/preview)

## Path
lib/movie/components/table
lib/catalog/components/table

## Acceptance Criteria
- filter with input
- sort by table header
- status (can be text or icons, waiting for validation)
- pagination
- page jump with drop down
- button to add or remove columns
- sticky table for mobile view #1210 
### movie table
- add button (@Jackseed: we will remove this button)
### catalog table
- [filter menu](https://projects.invisionapp.com/d/main?origin=v7#/console/19020838/400422884/comments?scrollOffset=1433.3333740234375)
- [tooltip for number of films](https://projects.invisionapp.com/d/main?origin=v7#/console/19020838/396547290/comments?scrollOffset=1433.3333740234375)

## Dev Notes/Resources

**Comment by Jackseed** [comment]
The menu button is not needed for now

**Comment by Jackseed** [comment]
done by @GrandSchtroumpf
