### ISSUE TITLE
e2e tests for movie tunnel - 10 Images

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1579]
# UI
on Zeplin :
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0b5ce0ce5cf519870bb60e

# E2E Tests to implement 
## Page 10
- [ ] Uploads an image to banner (if possible with cypress)
- [ ] Uploads an image to poster (if possible with cypress)
- [ ] Clicks on "Next" button
- [ ] Redirects to movie tunnel page 11 Files & links

**Comment by phpgeekfr** [comment]
closing this in favor of https://github.com/blockframes/blockframes/issues/3419
