### ISSUE TITLE
Test rules and security

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1582]
going through the data model and assess / rate how critical is it if a user access a certain document from another org.
(and within the same org too if needed)
If there are project-killer we should verify these immediately. (contracts, etc).
Then we can decide on a testing approach, either automate, or at least have a protocol to validate these in staging before pushing to prod.

**Comment by Jackseed** [comment]
@phpgeekfr recommends to implement public / private contract, org ...

**Comment by lsenta** [comment]
Tested contract security, permission objects security
other items are not critical (movies)
and critical object will be read & written ONLY by blockframes admins (invoice, etc).

We solved this, we have a test system in the CI (firestore emulator + ci run)

We have risk 003 to take care of: `a user can give themselves a permission for a document owned by another org (R003)`
