### ISSUE TITLE
Strict mode on backend function block use of string literal

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#1607]
**Use case** : 
Slug type should be strings literals (example: `type TerritorySlug = 'france' | 'germany' | ...`
Then in the factories functions we should set the default value to `null` :
```typescript
function createSomethingWithCountry(): { country: TerritorySlug  } {
  return {
    country: null
  }
}
```
**Issue** -> This is working on angular apps but **fails to build** on `backend-functions`.

**Current research** : 
- `strict` mode in tsconfig is enabled on `backend-functions` and not on other apps (This is fine !).
- We should be able to override the specific `strictNullChecks` rule to false, this remove the warning **BUT** creates more `strict` warnings like "Not all code paths return a value." linked to the rule `noImplicitReturns` or "...implicitly has an 'any' type." linked to `noImplicitAny`.

**Current Conclusion** : 
- It seems that `strict` mode doesn't work as expected (`noImplicitReturns` & `noImplicitAny` errors are not raised by default).
- We should override the `strictNullChecks` rule to support null as a default value for strings literals.

Patch in the meantime: `country: null as any` or `country: '' as any` should do the trick. Please notify this issue in a `@todo(#1607)` comment when doing that.

**Comment by lsenta** [comment]
The type you give is wrong, you should expect your typing system to throw an error.
Just declare `{ country: TerritorySlug | null }`, don't lie to the functions' clients.

**Comment by lsenta** [comment]
Following the discussion we have on slack,
please share a branch that shows your use case and the issues so we can reproduce and figure out the culprit of the issue. Losing null checks will make you write wrong code faster.

**Comment by Jackseed** [comment]
@george43g @GrandSchtroumpf is it still an open issue?

**Comment by phpgeekfr** [comment]
closed . See #3795
