### ISSUE TITLE
Breadcrumbs navigation component

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1618]

**Comment by GrandSchtroumpf** [comment]
I'm very curious about the real use of this component as it's used only to do : list/:id (example: "deals/ref#", "title/suicide tourist", "catalog/suicide tourist") which means that you can only click on the "list" part of it (as you're already on the ":id" part.
But the "deals", "titles" & "catalog" are already available in the sidebar. So we are just doubling the link.

**Comment by Jackseed** [comment]
outdated
