### ISSUE TITLE
Only blockframes admin or contract party can read contract.

### ISSUE THREAD

**Issue by ioaNikas** [blockframes/blockframes#1619]
We got this unique situation where we upload contracts and check the contracts collection for any match before adding them to the database. As we can't be `party` of a non existing contract, security rules block us from uploading contracts.

Quick fix : set the rule to `allow read: if true;`
Problem : all contracts are public, we don't want that.

Clean fix : set the rule to `allow read: if isParty(userOrgId()) || isBlockframesAdmin(userId());`
Problem : only blockframes admins can upload contracts via Excel.

There is maybe a better fix to that, need to be discussed.

**Comment by lsenta** [comment]
Taking care of this as part of #1582 and securing contracts. fyi @Jackseed
