### ISSUE TITLE
Fix staging

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1629]

**Comment by lsenta** [comment]
Staging deploy working,
staging setup working,
database reset to current prod
=> I restored user from prod with "password" as password,
=> I restore the firestore database using prod and keep the "users", "permissions" and "organizations"

**Comment by lsenta** [comment]
I did what I could taking into account the fact that there's no single source of truth for the data model (it's changing, it will change, not sure about migration being implemented, etc). We have a cleaned out database that looks like prod and we have a staging that is correctly deployed.
