### ISSUE TITLE
Finalize prod maintenance

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1631]

**Comment by lsenta** [comment]
We need:
- [ ] block the app when the app is in maintenance and force a refresh
- [ ] block the database when the app is in maintenance

**Comment by lsenta** [comment]
@Jackseed  @GrandSchtroumpf 
I'm implementing the database part, I'd need someone from frontend to deal with the other half of the ticket:

Block the app when the app is in maintenance and force a refresh:
When `isInMaintenance()` is true we want to disable the app, move to a "maintenance in progress" overlay / page. when `isInMaintenance()` goes to false, we want to force the user to refresh the app.

NOTE: WE SHOULD FORCE THE USE TO USE THE LATEST VERSION OF THE APP,
but this implies more modifications that we can keep for post-berlin.

Should take 20min: one-line subscribe to the maintenance document, check the isMaintenance and redirect / display a single refresh button.

**Comment by lsenta** [comment]
The ideal solution is related to #1219

**Comment by lsenta** [comment]
The ideal solution is related to #1219

**Comment by lsenta** [comment]
Requires #1582 to be cleared out cleanly!
