### ISSUE TITLE
Movie tunnel - Page 5 Budget updates

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1634]
### Budget Range
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/ddd67c87-3139-41a5-86c0-1b76667be018)
- [ ] Either remove the $ sign when there no input so it's just written "Budget Range" or add "Budget Range" as a label as in here:
![image (1).png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/6f81d83d-b68d-4570-86c8-5bec68c0e62f)

### Box Office
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/96fcde91-91bc-4ac7-b757-22eebfb62b8c)
- [ ] put a capital O to "Box Office"
- [ ] Replace "World-wide" with "You can choose World as a country to indicate World-wide Box Office"
- [ ] Replace "Country of Origin" with "Country"

### Quotas
- [ ] Rename the section "Qualifications"
- [ ] Add a tooltip to "EOF": "French speaking film label"
- [ ] Add a tooltip to "Art & Essai": "French label for arthouse pictures"
- [ ] Remove "Media"

### Ratings
- [ ] Rename "Country of Origin" to "Country"
- [ ] Replace the select input from Rating with a classic text input (we don't have the list for each country for now)

**Comment by GrandSchtroumpf** [comment]
If I align the placeholder with the dollar, all placeholder won't be centered anymore. I'll remove the "$" for now, if this issue is raised again I'll consider changing the theme.

**Comment by GrandSchtroumpf** [comment]
As the form country is reused everywhere, changing the placeholder will change it everywhere.
