### ISSUE TITLE
BigQuery requests for a list of movieIds

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1636]
Use here:
- [dashboard](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e26f53712aaa07e871d90fc)
- [movie list](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e26cf3d3d11857fb0842193)
For a list of movieIds, we need to get 
- [ ] Movie page views for each
- [ ] Clicks on watch trailer button for each
- [ ] Number of adds to wishlist for each
It will be used here:
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/5ba804ae-ff13-458c-8f26-bd555895e076)

And here (only movie page views for each on this page)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/7d1e70cd-d428-4cdf-b0c1-a4c17fa31aa4)

@lsenta any ideas on how to do this with what we've done so far with bigQuery?

**Comment by lsenta** [comment]
After discussing,
comparing "pipelines firestore", "views", and "basic version" => just change the current query and let the user do the aggregations, etc.
