### ISSUE TITLE
Update LANGUAGES static model to be RFC-5646 compliant

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1658]
- check for TODO #1658 in the code

**Comment by phpgeekfr** [comment]
Added  @Mussuranae because she have an open PR about this. She will be able to determine if this issue can be closed or not

**Comment by fritzschoff** [comment]
@Mussuranae can you please check what are the missing steps here. We can do something like for territories. Having multiple entries for ISO2 ISO3 etc.
