### ISSUE TITLE
Marketplace - New filters

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1742]
## UI 
[Zeplin](https://app.zeplin.io/project/5de7944cf85691577aacfbb7/screen/5e3306a09d2d355501c2e3e3)

## Acceptance Criteria
Add the new filters regarding film metadata on the all titles page:
- [x] Add the section title "TITLE METADA"
- [x] Rename Genres "Genre"
- [x] Update "Languages":
- Rename to "Language & Version" ok
- Change the add button ok
- Change the style of the chosen language chip ok
- add the "Closed-Captioned" option for version ok
- filter with the movie.salesInfo.languages parameter
- use a "or" statement for multiple version checked
- [x] Update "Production Status":
- Align vertically the options
- [x] Remove Sales Agents filter
- [x] Add Country of Origin filter:
- Use the component from the movie tunnel
- Territories are considered with an "or" statement
- display the territory list with a mat autocomplete
- filter with the movie.main.originCountries paramater
- [x] Add Budget filter:
- Show the budget possibilities from rangeBudget (considered with an "or" statement)
- filter with movie.budget.estimatedBudget

**Comment by GrandSchtroumpf** [comment]
We must consider the case when header is too small for the screen : 
- Create a chips-row container with overflow hidden
- Add arrow if overflowed
- scroll X when arrow is clicked OR wheel scrolled

Quick ressources : 
- CDK scrolling : https://material.angular.io/cdk/scrolling/overview
- Flexbox: https://codeburst.io/how-to-create-horizontal-scrolling-containers-d8069651e9c6
- Pure CSS:  https://css-tricks.com/pure-css-horizontal-scrolling/

**Comment by Jackseed** [comment]
dedicated issue created with #1932
