### ISSUE TITLE
account pre delete checks 

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#176]
check if user is not the only admin of an org before deletion
remove uid from org.userIds

**Comment by phpgeekfr** [comment]
check in code for ```@todo remove uid from org.userIds```

**Comment by phpgeekfr** [comment]
This is not possible anymore to delete user from applications.
@Jackseed Is this functionality going to be accessible again or do I remove user deletion method from code and close this issue ?

**Comment by Jackseed** [comment]
@phpgeekfr yes we need to give the user ability to delete his account but need the UX to design a workflow
