### ISSUE TITLE
Check themoviedb.org API to retreive movie data 

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#1767]
Check ratings

**Comment by fritzschoff** [comment]
really good feature! Missing such data in every streaming service

**Comment by Jackseed** [comment]
Yes would be really nice to pre-filled as much as we can the movie form and it would be also really cool to get licence free images for cast & crew.

**Comment by phpgeekfr** [comment]
Is it still a required feature ?

**Comment by Jackseed** [comment]
Yeah it is though I should have a legal look to the API license first

**Comment by Jackseed** [comment]
Worth noticing:

> 
> 3. Attribution
> You shall use the TMDB logo to identify your use of the TMDB APIs.
> 
> You shall place the following notice prominently on your application: "This product uses the TMDB API but is not endorsed or certified by TMDB."
> 
> Any use of the TMDB logo in your application shall be less prominent than the logo or mark that primarily describes the application and your use of the TMDB logo shall not imply any endorsement by TMDB.
> 
> 7. Copyright
> TMDb respects the rights of copyright holders and publishers and requires all users to confirm they own the copyright or have permission from the copyright holder to upload content. We comply with the Digital Millennium Copyright Act (DMCA) and expeditiously remove content when properly notified, unless it reasonably appears to us that the content does not infringe upon copyright. Please note, however, that under Section 512(f) any person who knowingly materially misrepresents that material or activity is a copyright infringement may be subject to liability for damages. You should educate yourself as to whether content does, in fact infringe upon your copyright, or whether, for instance "fair use" under 17 U.S.C. §107 applies. If you are unsure whether the content you are reporting is infringing your legal rights, you may wish to seek legal guidance. Keep in mind that submitting intentionally misleading reports of infringement may be punishable under the Digital Millennium Copyright Act (DMCA) in the United States or similar laws in other countries.

**Comment by phpgeekfr** [comment]
`myapimovies` is really easy to use and seems to fit our needs.
I tried several endpoints and it looks ok.

Here is what I get when querying `v1/movie` with ImdbId :
```
{
  "imdbId": "tt0107290",
  "imdbUrl": "https://www.imdb.com/title/tt0107290",
  "metascore": "68",
  "plot": "Huge advancements in scientific technology have enabled a mogul to create an island full of living dinosaurs. John Hammond has invited four individuals, along with his two grandchildren, to join him at Jurassic Park. But will everything go according to plan? A park employee attempts to steal dinosaur embryos, critical security systems are shut down and it now becomes a race for survival with dinosaurs roaming freely over the island.",
  "posterUrl": "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1.jpg",
  "rated": "PG-13",
  "rating": "8.1",
  "releaseDate": "19930611",
  "runtime": "127 min",
  "simplePlot": "During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run amok.",
  "title": "Jurassic Park",
  "type": "M",
  "votes": "791,214",
  "year": "1993",
  "lastUpdate": "2019-08-13T03:21:37.000Z"
}
```

for genres for example : `/v1/movie/${imdbId}/genres`

```
[
  {
    "genre": "Adventure"
  },
  {
    "genre": "Sci-Fi"
  },
  {
    "genre": "Thriller"
  }
]
```

@Jackseed @cams-goussale  By looking at  https://www.myapimovies.com/api/swagger-ui.html#/ can you give me the kind of data/endpoint you would like to query ?
