### ISSUE TITLE
Create a library "global/common/layout" to manage common layouts

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#1775]
This library would manage reusable routes :
- [ ] errors (not-found, ...)
- [ ] layouts (dashboard, marketplace, accounts, tunnel)
- [ ] maintenance
- [ ] store app-level information

This will manage routes while UI manage reusable component.

**Comment by fritzschoff** [comment]
@GrandSchtroumpf still a thing, if not, please close
