### ISSUE TITLE
Use the same interface DocumentMeta between all Documents

### ISSUE THREAD

**Issue by Hugo-Hontans** [blockframes/blockframes#1791]
We already have this interface to have the userId:
```
interface DocumentMeta {
  createdBy: string;
  updatedBy?: string,
  deletedBy?: string
}
```
and we use differents fields like to store the Date:
```
interface Template { 
   updated: Date;
  created: Date
 }
```

We have to merge it into only one interface DocumentMeta

**Comment by Jackseed** [comment]
@Mussuranae @Hugo-Hontans is it still a pending issue?
