### ISSUE TITLE
Landing page - Archipel Content - UI changes

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#1794]
**Header part**  

- [ ] Delete white line between menu and background (ex. screenshot)
- [ ] Change navigation text color from gray to white 
- [ ] Align the border "sign up" (ex. screenshot ; maybe : .light-theme .mat-stroked-button {height: 38px;})
- [ ] Add an anchor link to "Schedule a demo" (should lead to "Want learn more ?!)
- [ ] Change all text to white 
- [ ] Resize the text : Archipel Content (font-size: 24px;  font-weight: 800;) The only marketplace offering package deals (font-size: 60px;  font-weight: 800; font-style: normal; line-height: normal;)
for TV, VOD and ancillary rights (font-size: 24px; font-weight: normal;)
![header_changes.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/60aebab5-f4f8-49ff-a6db-37065403fa98)

- [ ] Add more space "Join now" and the button of the section (maybe : padding-bottom: 90px;)

**Key features**
- [ ] Add more space header section and key feature 1 (maybe : padding: 60px; )
- [ ] Add more space key feature 1 and key feature 2 (maybe : 100px;)
![key_features.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7eef6b9f-2c29-4f6d-8510-e0c864fd4710)

**How does it work ?** 
- [ ] Change the text "How it works?" to "How does it work?" 
- [ ] Add background color for "How does it work?" block (gray)
- [ ] When you click on "Buyer" tab the text is not aligned (now it is like this and needed to be as for "Seller" -> ![byuer bug.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a147aeca-ab0a-49aa-ac25-2e0574c4f218))
- [ ] Add space between tabs and "Mutualize" text (maybe : 20px;)
- [ ] Add space between "Pricing" and "Features" (maybe : 10px;)
![how it works.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/58e1ceda-3bf4-4ab7-9c49-be8bbd3b20b2)

**Video**
- [ ] Change title color "View the marketplace" to white in "Video" block 
- [ ] Change the font size to 48px 
- [ ] Add spaces to the section (as proposed on the screenshot )
![video.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/777c9575-cc5f-4df1-9a2c-e03107afdac4)

**Interested? Join now**
- [ ] Change font-size "Interested? Join now" to 60px
- [ ] Add space to the section (80px)
- [ ] Add space between title and button (30px) 
![interested.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9bc45684-6700-44c4-85ca-17a783b72e7f)

**Want to learn more ?** 
- [ ] Need to change size of the fields
- [ ] Text "Program a personalized demonstration of the platform with a member of the Archipel Content team" should be center-aligned
- [ ] Need to change size of the fields (width: 400px;)

**Footer**
- [ ] Change color of Archipel logo in footer (from white to blue)
- [ ] Delete underline in footer "Learn more" links
- [ ] Links in "Learn more" section should be left-aligned 
- [ ] Delete "Follow us" section 
- [ ] Change color of the footer titles (black; var(--text_100))
- [ ] Change color of footer links text (color: #17304f;)
- [ ] Keep informed takes 3/5 of place 

![archi_footer.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a759a1aa-0f95-44fd-847e-5a59678b59f4)

N.B. The size and space propositions are from zeplin in most cases (https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5de910969b04ba81210e5561)

**Comment by Jackseed** [comment]
updated with #1909
