### ISSUE TITLE
Map should have a better behaviour

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#1813]
Currently map listen on change of ContentChild, and for every child, change listen on color & tag change. This is difficult to maintain especially to remove previous state.
This should be improved

**Comment by fritzschoff** [comment]
@GrandSchtroumpf which map are you talking about? Maybe close?

**Comment by GrandSchtroumpf** [comment]
It's the Leaflet map. It's still an issue. But I'll work on it when we reimplement it.

**Comment by RemcoSimonides** [comment]
@GrandSchtroumpf Is still issue still relevant?
