### ISSUE TITLE
searchbar parameters

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#1830]
if we are using the searchbar for searching in our indices, we might ran out of space for the url maximum length. So if the user clicks on "view all activity" this might lead to some weird behavior. ![Screenshot from 2020-02-06 12-24-06.png](https://images.zenhubusercontent.com/5d19e757a91f961fd8457e0f/62c35b52-8c99-4229-a2f3-8ba6b22c10fb)
we could use akita for it to store the ids temporarily and fetch it from the DB.

**Comment by Jackseed** [comment]
@fritzschoff is still an open issue?

**Comment by fritzschoff** [comment]
Checked and you can have a really long url with a lot of query parameters, so should be fine
