### ISSUE TITLE
Seller's Dashboard - General navigation 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#1858]
- [x] Logo Archipel  should be clickable (leading to the Dashboard page)
- [x] Change "Overview" to "Dashboard" 
- [x] Add active state to the menu : color + bord (see the screen shot)
![dashboard nav.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1945c161-98c7-4ec4-b222-84c6ee68099b)
- [x] Menu "Dashboard"  should be clickable and lead to the Dashboard page (now we have "page not found")
- [x] There should be user information on the right from the avatar (as on screen shot)
![profile.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a525bfbb-2db9-4754-923c-9a5cc078f563)
- [x] Change phrase in a search field to "try searching for clients, negotiations, deals..." 
- [x] Delete "Marketplace" from navigation 
- [x] Delete "FAQ" from navigation
- [x] Change "Deals" to "Offers and Deals" 

I created the issue #1883 for the contact page

**Comment by Jackseed** [comment]
dedicated issue created with #1923
