### ISSUE TITLE
Notifications & Invitation style fixes

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1919]
## UI
[Zeplin](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5dee65aa8938c60608b36d0e)

## Updates
- [ ] Align the right side of notification panel with the notification button this way:
![image](https://user-images.githubusercontent.com/14964443/74608924-8e19a680-50e5-11ea-9365-9f8f2f586b4c.png)
- [ ] fix UI of the notification
![image](https://user-images.githubusercontent.com/14964443/74608861-f9af4400-50e4-11ea-9fc3-5da371aa2faa.png)
- [x] Remove the gear button on top right
- [x] Check with @ioaNikas what we have for the /activity page; if not working, remove the link from the notification list

**Comment by ioaNikas** [comment]
About activity page, it's kinda basic right now : we got no sorting by apps, but we got a full list of notifications and invitations.
