### ISSUE TITLE
Movie Tunnel - last fixes

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1926]
## UI 
[Zeplin](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0b1449a2ab6098620fecef)

## Updates
- [x] Add a white background everywhere
- [x] When click on save: add a snackbar "Title saved"
- [x] **Close and save button erase information instead of saving** @GrandSchtroumpf 
- [x] Submit to Archipel Content button raise an error while every mandatory fields are filled @GrandSchtroumpf 
![image](https://user-images.githubusercontent.com/14964443/74612726-5d973400-5108-11ea-8217-66e1de29d14d.png)

### Lobby page
- [x] Remove "Files you will need" + text Poster(s), banner image, still photos and the promo reel. You will also need to provide the links to the screener and trailer .
- [x] Change title to "Add a Title" (= remove "and Licensed Rights")
- [x] Change subtitle to :
The 3-step process will take about a half-hour to complete.
- [x] Remove the text upside begin "You can fill it out in one go or over time. You may navigate between steps, but all sections must be completed before submitting to Archipel Content for validation." (it's already written in instructions)
- [x] Remove the card "Licensed Rights" and ask Mathilde for new illustrations
- [x] Remove the text from the cards and change "Upload Media" to "Media"
- [x] Align the 3 cards same as UI
- [x] Add Archipel Content logo on the navbar

### Sidenav
- [x] Rename Main informations to "Main Information" (without s)
- [x] Remove Licensed Rights section
- [x] Rename Uploaded Media to "Media"
- [x] Rename Technical info to "Technical Information" and move it to the Media section on first position
- [x] Rename Synopsis to "Storyline Elements"
- [x] Remove Keywords sub-section
- [x] Rename "Budg., quota, critics" to "Budget, Quotas, Critics"
- [x] Rename Images to "Promotional Images"

### Navbar
- [x] Change logo color to blue
- [x] On title info section, change steps for x/4 and time for "15 min"
- [x] On media section, change steps for x/3 and time for "10 min"
- [x] On legal info section, change steps for x/2 and time for "5 min"
- [x] When the cross top right is clicked and there is no previous page (after a refresh for example), the cross doesn't work, it should lead to the active movie page tab details instead 

### Title information section
_Main info_
- [x] Freshness: use the store type Enum (Library instead of Catalog)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/796702fe-f6e9-4730-a7e7-70020afc93cc)
- [x] Reference: help text "This reference is for you only, to help you find your content more easily."
- [x] Capital letters on every words from the input labels: First Name, Last Name, International Title, Original Title, and cast members First Name and Last Name
- [x] On country of origin, rename Media for "Release Media"
- [x] Domestic Distributor name is not required

_Synopsis_
- [x] change section title to Storyline Elements
- [x] Rename Storyline "Synopsis"
- [x] Add Keywords after Key Assets

_Credits_
- [x] Put capital letters to every words in label: Production Information, Production Year, First Name, Last Name
- [x] Rename "Producers Name" to "Producers"
- [x] Role list for Producers is not working, it should display values from PRODUCER_ROLES in the static model

### Media section
_Technical Information_
- [x] replace Format label with "Shooting Format"
- [x] when there is no original languages selected, "Original Languages" section shouldn't be displayed
- [x] rename versions available for "Available Versions"

_Promotional Images_
- [x] Change the title Images for "Promotional Images"
- [x] Rename Movie poster image for "Poster" (title + inside the upload box)
- [x] Rename Still photos for "Stills" (title + inside the upload box)

_Files & Links_
- [x] capital L to all Links, capital D to Presentation Deck, Promo Reel Link,...

- [ ] Chain of Titles is broken, blocked by #1928 & #1956 

### Summary page
- [ ] Same as #1923 
- [x] Remove "& Licensed Rights" from the title

**Comment by Maxstgt** [comment]
@Jackseed What about the two checkboxes about chain title, are they still active? Or can they be checked and then the issue can be closed if the remaining are fulfilled? 
@GrandSchtroumpf What about the checkboxes that are assigned to you? Did you finished it?

**Comment by GrandSchtroumpf** [comment]
They should be solved, except if it comments after Berlin
