### ISSUE TITLE
Change Budget range

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1927]
Less than $1 million
$1 - 2 millions
$2 - 3.5 millions
$3.5 - 5 millions
$5 - 10 millions
$10 - 20 millions
More than $20 millions

**Comment by phpgeekfr** [comment]
There is no const or static for a such list.

For bugetRange we use createRange( from, to ).

Currently, for the excel, I parse a string like `$5 - 10 millions` into { from: 5000000, to :1000000}

So even, $3.5 - 5.66344 millions is valid

**Comment by phpgeekfr** [comment]
Ho okay, just saw a `BUDGET_LIST` Coming from nowhere in code (not in static but it should be). I'm gonna update this
