### ISSUE TITLE
Marketplace - All titles - last fixes 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1932]
## UI 
[Zeplin](https://app.zeplin.io/project/5de7944cf85691577aacfbb7/screen/5e3306a09d2d355501c2e3e3)

## Updates
- [x] Ask Mathilde for the search bar new design
- [x] Align the arrow with Sort by button and fix it (doesn't work for me)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/9dd89d09-b540-40f7-bbc6-54a80ad85734)

### Filters
- [x] Add space between the divider and "Title Metadata"
- [x] Rename Originale Genres > "Genres"
- [x] Languages & Version filter looks broken, error
`Error: Cannot find control with name: 'french'`
- This filter should apply when a version is selected (original, dubbed,...) not a language
- [x] Budget filter doesn't work, either fix it or remove it
- [x] Territories Available change label for Territory
- [x] Remove the help text for Territory
- [x] Media: display only the list from the UI

**Comment by Jackseed** [comment]
- [ ] Budget seems still broken
- [ ] For searchbar, placeholder: "Search for titles, directors, keywords,..." 
- [ ] Change Subtitles for "Subtitled" in the language part

**Comment by Jackseed** [comment]
- [ ] Align movie title on left
- [ ] reduce margin so we can add a 4th movie card on one line
- [ ] display bigger poster image
![image (26)](https://user-images.githubusercontent.com/14964443/74753710-d0bbba00-5270-11ea-9964-abdf2a14f52b.png)

**Comment by GrandSchtroumpf** [comment]
@Hugo-Hontans Can we close that ?
