### ISSUE TITLE
Wishlist page - last fixes

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1933]
- [x] Remove the poster from the table
- [x] Rename the page "My Wishlist"
- [x] Remove Please submit this order for it to be processed.
- [x] Remove Sales Agent column
- [x] Remove Submit to sellers button
- [ ] Use re-usable table
    I don't use re-usable component because the current code works and the elements nested like `main.title.international` will cause an issue to display correctly 
- [x] Change the remove button

**Comment by GrandSchtroumpf** [comment]
@Hugo-Hontans can we close that ? Did you solve the situation with the table ?
