### ISSUE TITLE
Move all Queries from services to the guards to avoid circular dependencies

### ISSUE THREAD

**Issue by ioaNikas** [blockframes/blockframes#1974]

**Comment by Jackseed** [comment]
@GrandSchtroumpf @ioaNikas @Maxstgt @Hugo-Hontans

**Comment by ioaNikas** [comment]
We already have this architecture implemented in `movie-contract.guard`. In my opinion, I find it more readable this way, we have a good vision of what `sync()` is doing and on what it is "syncing".

I'll go further on this issue since I got some time.
