### ISSUE TITLE
Admin Panel - Add orgIds to partyIds from a contract

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1992]
Use @GrandSchtroumpf code

**Comment by phpgeekfr** [comment]
@Jackseed  Is this what you want ?

On admin panel you can see contract parties: 
![Screenshot_2020-02-24 Archipel Content](https://user-images.githubusercontent.com/1194344/75160749-e15dab80-571a-11ea-8cbd-15595638b6ec.png)

On pencil click, open a form to enter orgId:
![Screenshot_2020-02-24 Archipel Content(1)](https://user-images.githubusercontent.com/1194344/75160757-e3c00580-571a-11ea-9d40-f430fd5598f4.png)

**Comment by phpgeekfr** [comment]
If so, code is ready in #1832
