### ISSUE TITLE
Design Review: Library

### ISSUE THREAD

**Issue by vwmathilde** [blockframes/blockframes#2002]
REALLY IMPORTANT
- [x] not the right color for fab button -> primary 500
![image](https://user-images.githubusercontent.com/51743840/74940954-88c4a080-53f2-11ea-94bd-e3c0b538dfd0.png)
- [x] please change primary color for dark theme. It's not the good color !!!
- [x] Caption interline : 21px
- [x] 4px between H6 and Caption
![image](https://user-images.githubusercontent.com/51743840/74941168-e1943900-53f2-11ea-8fe3-17730e088b43.png)
- [x] use right color for mat-chips 
- [x] use two tone icons please, everywhere
![image](https://user-images.githubusercontent.com/51743840/74941278-0a1c3300-53f3-11ea-931b-bdaa52fd8c6c.png)
- [x] 4 px between H5 and caption
![image](https://user-images.githubusercontent.com/51743840/74941551-8282f400-53f3-11ea-879d-71dd02744aa2.png)
- [x] Please, do the same spacing between same elements
![image](https://user-images.githubusercontent.com/51743840/74941666-b4945600-53f3-11ea-89e0-86eec076478b.png)
- [x] Right calendar icon on library
![image](https://user-images.githubusercontent.com/51743840/74941702-c70e8f80-53f3-11ea-8396-7112c9fbe19d.png)
- [x] Spacing 24 px
![image](https://user-images.githubusercontent.com/51743840/74941818-fd4c0f00-53f3-11ea-8b6b-e5435ffaf0c1.png)
- [x] Card font : title -> H6 / Real -> caption
![image](https://user-images.githubusercontent.com/51743840/74942946-8e22ea80-53f4-11ea-8377-ee72335a3e55.png)

It's ok, I may not cry
- [ ] Normally it's a menu drop down, not mat-select
![image](https://user-images.githubusercontent.com/51743840/74937260-ffaa6b00-53eb-11ea-8a9a-63d452478a49.png)
- [ ] It's possible to have a more beautiful scrollabar ?
![image](https://user-images.githubusercontent.com/51743840/74938479-63ce2e80-53ee-11ea-9f06-aa7a6fa71170.png)
- [x] more space between Two elements
![image](https://user-images.githubusercontent.com/51743840/74938869-1d2d0400-53ef-11ea-92d2-7a50c5bba615.png)
- [ ] for item "genre", it should be the same component like Country of Origin
- [x] more space between lines (24 px)
![image](https://user-images.githubusercontent.com/51743840/74941477-5e271780-53f3-11ea-869e-8accd34da320.png)
- [x] Intercom in primary (light theme everywhere)
![image](https://user-images.githubusercontent.com/51743840/74943532-d17d5900-53f4-11ea-8fb1-212d608f8b8e.png)

**Comment by Mussuranae** [comment]
LAST THING TO DO :
- For scroll bar, we have to discuss about custom scroll bar (for example : http://grsmto.github.io/simplebar/ ).
- Need to refactor the genre component (movie-form-genre) to get the same design as country of origin component (call the chips-autocomplete component)
- The drop down menu doesn't enable customers to know with which data movies are sorted.
