### ISSUE TITLE
Design Review: All Tunnel

### ISSUE THREAD

**Issue by vwmathilde** [blockframes/blockframes#2040]
- [x] No margin between H4 and H1
![image](https://user-images.githubusercontent.com/51743840/75029703-def11c80-54a2-11ea-87ce-9cd6523a9fae.png)
- [ ] 40px margin between this block and toolbar
![image](https://user-images.githubusercontent.com/51743840/75029756-f3cdb000-54a2-11ea-87e4-cf4271c76fa4.png)
- [x] change nav bar like we have on design

**Comment by Mussuranae** [comment]
I can't reduce the margin between the nav-bar and the h4 because the 'skip and do later' button is between them. So in fact, there is no margin but just a section with the button.
