### ISSUE TITLE
Public Collections: how to store them ?

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2049]
- Into subcollection of the parent document ?
- Directly on DB root ?

Currently, PublicOrg:
`const { id, denomination } = await getDocument<PublicOrganization>(`orgs/${current.partyIds[0]}`);`

**Comment by phpgeekfr** [comment]
Beware of the contract types flow

**Comment by Jackseed** [comment]
Outdated issue > closed
