### ISSUE TITLE
[Discussion] - Cart collection Design

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#2052]
Currencly Cart has a sub-collection under organization/:orgId/cart.

For the ID we have two choices : 
- one cart/organization/app : `organizations/:orgId/cart/:appId`.
- Many cart/organization/app : `organizations/:orgId/cart/:cartId` with the appId as a field of the doc.
-> Managing several cart per organization looks tedious at first glance but should be discussed.

In both cases, this mean that Data model have to be generic enough in most future Carts (can be done overtime, but we need to think about this now).

The easiest solution would be an array of items with generic type with some metadata like the list of user who updated it. Adding the wishlist is also an option: 
```typescript
interface Cart<Item> {
  modifiedBy: string[];
  wishlist?: string[];
  items: Item[];
}
```
A deal cart might looks like :
```typesript
interface DealItem {
  movieId: string;
  deals: DistributionDeals[];
}
type DealCart = Cart<DealItem>;
```

Then we can have either : 
- One service app that uses a cart: `class DealCart extends CartService<DealCart> {}`
- Use InjectionToken: `const DEAL_CART = new InjectionToken({ factory: new CartService<DealCart>() })`.
-> I think the first option will be easier to understand for most developers.

A store is not required here. But if we want we could use an EntityStore based on the Items. (In the case of the DealItem the idKey would be the movieId).

**Comment by Jackseed** [comment]
Bear in mind that:
- for now Archipel is the only app using a cart, maybe Media Financiers will too but it certainly won't have the same parameters
- we want for future upgrades:
1. Users to have their own carts and name it
2. Users to be able to share their cart to the org lvl
3. Org & Users to have multiple carts
