### ISSUE TITLE
Use the right role list on the movie form

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2056]
Currently all the roles for crew members use the producer roles list. We should use the cast list for cast, the producer list for producers and the crew list for crew members (page main & credits)
![Capture d’écran 2020-02-24 à 12.05.42.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/2481b55d-984c-42dd-85f5-d2f96c2278d6)

**Comment by Maxstgt** [comment]
when I remove the body and html height:100% property, the window.scrollY is now working as expected. So the problem comes from here

**Comment by Jackseed** [comment]
doesn't look like the good issue for your comment @Maxstgt ;)
