### ISSUE TITLE
Movie form Next button from storyline elements debug

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2057]
Next button from /synopsis to credits links to a blank page and block the form
Uncaught (in promise): TypeError: Cannot create property 'next' on string '
https://sentry.io/organizations/cascade-8/issues/1525748883/?project=1540126&query=is%3Aunresolved&statsPeriod=14d

**Comment by Maxstgt** [comment]
should be fixed with PR #2056

**Comment by Maxstgt** [comment]
closing this issue, seems to be fixed, if not. reopen it
