### ISSUE TITLE
Admin Panel - Missing features 

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2090]
Following  #1832 & linked to #2089

Features:
- [x] To be accessible, user id need to be in `blockframesAdmin` collection. For this, we can now use `AuthQuery.isBlockframesAdmin`
- [x] Add some css
- [x] Be able to display uncompleted tables contracts, movies, etc without errors
- [x] Be able to change user org ? (update user, org, permissions documents)
- [x] When deleting a title from a contract, update distributionDeal, contractId etc.
- [x] Be able to `edit contrat.last.titles<titleId>` Price
- [x] Use @GrandSchtroumpf new form builder (WIP)

- [x] add  a way to use admin panel for @maltmayer  to create account for prospective customer
current process is:
```
- Create the org with demo@cascade8.com 
- Note the orgId you just created by going to My organization page
- Go to firebase, project blockframes, be careful it's prod
- Go to tab Database > permissions collection > orgId you just created
- In another tab go back to archipelcontent.com > Organization members 
- Invite users for the demo 
/!\ THEN QUICKLY /!\ 
- Refresh firebase page
- Paste her/his userId in the permissions collection orgId > superAdmins
- Remove the demo@cascade8.com userId from superAdmins
- Go to orgs collection, orgId > userIds; remove the demo@cascade8.com userId 
- Go to users collection, delete demo@cascade8.com user document 
- Go to Authentication tab, remove demo@cascade8.com account for future use
```

check `#2090` in code.

**Comment by Jackseed** [comment]
@phpgeekfr I would also add:
- [ ] Implement a guard to enable only blockframesAdmin
- [ ] Add a way to delete a movie / contract / user / ...

**Comment by maltmayer** [comment]
- [ ] I'd like to be able to modify any information referring to the org (logo, activity description, etc)

- [ ] Same for every movie (edit synopsis, poster, anything)

**Comment by Jackseed** [comment]
- [ ] Enable the modification of the org role for a user
- [ ] If possible, see the pending invitations so we can accept it

**Comment by maltmayer** [comment]
- [ ] "Sort by" features don't work. It would be great to be able to sort by Name or status etc.
![image](https://user-images.githubusercontent.com/55785823/82814853-3f279e00-9e98-11ea-8026-1b8fed13fabf.png)

**Comment by maltmayer** [comment]
- [ ] export all info

- [ ] ideally, the panel should show all info on 1 page (not separate pages with 10/25/50 infos)

- [ ] org name filter doesn't work. it would be super useful

**Comment by phpgeekfr** [comment]
- [ ] change user avatar (lower priority)

- [ ] change movie images (high priority)

**Comment by Jackseed** [comment]
- [ ] Add a "reset password" button on the users

**Comment by Jackseed** [comment]
- [ ] Org name bigger on org page

**Comment by Jackseed** [comment]
- [ ] Invite a user to an event

**Comment by phpgeekfr** [comment]
Closing this issue in favor of #3189
