### ISSUE TITLE
Dashboard Loading issues 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2111]
Loading dashboard and titles pages is too long. 
Same thing on title page tab stats.

- [ ] Have tests to understand where the loading issues come from
- [ ] Implement fixes to upgrade loading 

> maybe load one time the stats and then keep it for the next pages

**Comment by GrandSchtroumpf** [comment]
@Hugo-Hontans Can we close ?

**Comment by Hugo-Hontans** [comment]
We load the data one time in a store integrated in the movie store. And we change the view to display all other info pending analytics.
