### ISSUE TITLE
Dashboard Title page / edit issues > Marie's feedback

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2113]
- [x] Layout problem on the Film Page, The "Marketplace Activity" title is too close to the top. Whereas the title in the "Film Details" tab ("Title information") is not that close to the top. It should be the same component shouldn't it ? 
- [x] Display problem on the Film page, in "Film Details" tab, in "Storyline Elements": Keywords don't all appear. Just one. (But I know they are in the database, as when I click "Edit" they're all there)
![image](https://user-images.githubusercontent.com/55785823/75674449-52561380-5c85-11ea-9dc7-6349961a2cb2.png)
![image](https://user-images.githubusercontent.com/55785823/75674456-55510400-5c85-11ea-9a61-96ed24a30de6.png)
- [x] Display problem on the Film page, in "Film Details" tab, in "Technical information": Versions don't appear. But I know they are in the database, as when I click "Edit" they're all there)
![image](https://user-images.githubusercontent.com/55785823/75674476-626df300-5c85-11ea-8afd-9bf074617da3.png)
![image](https://user-images.githubusercontent.com/55785823/75674481-66017a00-5c85-11ea-993c-f102cdf519b6.png)
- [x] Display problem on the Film page, in "Film Details" tab, in "Main information": Cast doesn't appear. But I know they are in the database, as when I click "Edit" they're all there)
- [x] General display problem: There are a lot of situations where, when a word is too long, or there are too many words in a card, the text goes out of the box. 
![image](https://user-images.githubusercontent.com/55785823/75674492-6ac62e00-5c85-11ea-99f0-ca872a3f2196.png)
- [x] Display problem on the Film Page, in the "Film Details" tab, in "Credits", there should be no space between a word and brackets around it.
![image](https://user-images.githubusercontent.com/55785823/75674508-787bb380-5c85-11ea-9970-ecf865fe5a45.png)
- [x]  Wording problem on the Film Page, in the "Film Details" tab, in "Credits", "exectuive" should be replaced by "executive"
![image](https://user-images.githubusercontent.com/55785823/75674512-7c0f3a80-5c85-11ea-880a-db86eb3c653e.png)
- [x] Display problem on the Film Page, in the "Film Details" tab, in "Budget, Quota & Critics", budget should be in millions. Replace "2000000" by "2 millions" for all Budget ranges. 
![image](https://user-images.githubusercontent.com/55785823/75674527-8598a280-5c85-11ea-8604-2b8a494adc38.png)
- [x] Display problem on the Film Page, in the "Film Details" tab, in "Budget, Quota & Critics", the "Box office" line makes no sense. It should appear in this way : The title should be "Box office" (and not "Country"), then the number value, then the unit (don't spell it out like "Box office in $". Just put "$" after the value). Then specify the Country (in brackets). 
![image](https://user-images.githubusercontent.com/55785823/75674531-892c2980-5c85-11ea-84a9-c79bd3a06b97.png)
- [x] General comment on the Film Page, in the "Film Details" tab, in "Budget, Quota & Critics", the "Box office" default value shouldn't be 
- [x] Display problem on the Film Page, some fields are empty but don't appear "Missing"
![image](https://user-images.githubusercontent.com/55785823/75674542-8f220a80-5c85-11ea-82d5-1472b304f5d3.png)
- [x] Display problem on the Film Page, in the "Film Details" tab, in "Main information" : "Release date" display problem
![image](https://user-images.githubusercontent.com/55785823/75674552-9a753600-5c85-11ea-8782-8ac5d6a2848e.png)
- [x] Similar problem here:
"I don't understand how you got this, the date in salesInfo.originalRelease.date is a string, not a timestamps" comment from Hugo
![image](https://user-images.githubusercontent.com/14964443/74610823-f2913180-50f6-11ea-8ada-a18de0b7f207.png)
- [x] Wording problem on the Film Page, in the "Film Details" tab, in "Main information", on Editing mode, for Domestic Distributor : replace "Countries" by "Country" 
![image](https://user-images.githubusercontent.com/55785823/75674562-9f39ea00-5c85-11ea-88bd-95152bd38837.png)
- [x] Data problem on the Film Page, in the "Film Details" tab, in "Main information", on Editing mode, for Principal Cast, we have to select a "Role". Makes no sense. Delete the field.
![image](https://user-images.githubusercontent.com/55785823/75674568-a52fcb00-5c85-11ea-99fc-9fd65b224e5a.png)
- [x] Festival: 
  - [x] add a "s" Festivals 
  - [x] remove the space before the coma
![image](https://user-images.githubusercontent.com/14964443/74610921-cfb34d00-50f7-11ea-997a-30b8aa76d00b.png)
  - [x] add a space after the coma for premieres, put a capital letter and add Premiere after so it make something like this in the example:
Cannes, Selection, 2020, International Premiere, Market Premiere, World Premiere, National Premiere
- only one festival is shown even if there is 2 or more, we need to display all by going on a new line or separate them with "|"
- [x] Loading error on the Film Page, in the "Film Details" tab, in "Main information", Editing mode, a few times, the "Festival" card didn't appear anymore. I had to refresh to see it again.
- [x] Data problem on the Film Page, in the "Film Details" tab, in "Main information", for "Country of Origin" : the rights available in "Release Media" field are not right. They're only TV, VOD and ancillary.... "Theatrical" is not in the list, for instance. Not the right list! @Jackseed @phpgeekfr, we need to make 2 different lists
![image](https://user-images.githubusercontent.com/55785823/75674592-afea6000-5c85-11ea-98d7-36fe905257fa.png)
- [x] Freshness: display the enum value not key
![image](https://user-images.githubusercontent.com/14964443/74610891-82cf7680-50f7-11ea-9946-82bc5b2f6cbe.png)
- [x] Co-Production Company & Production Company:
  -  [x] "()" to remove when there is no country
![image](https://user-images.githubusercontent.com/14964443/74611637-e78dcf80-50fd-11ea-91cc-1fe95020df85.png)
  - [x] only one is showed, if more, they should be displayed all by going on a new line or separate them with "|"
- [x] Rating: all elements from the array should be displayed
- [x] Film Review: nothing is displayed, all elements from the array should be displayed
- [x] Versions are not displayed
![image](https://user-images.githubusercontent.com/14964443/74612356-f1ff9780-5104-11ea-9440-dfcce0742a09.png)
- [x] Presentation deck should show the name of the original file
![image](https://user-images.githubusercontent.com/14964443/74612579-c41b5280-5106-11ea-8689-a2904d418661.png)

**Comment by Maxstgt** [comment]
about the second checkbox, that keywords doenst get displayed in its full length and also for technical information bug. This problem originates from form.patchValue or form.patchAllValue. These functions have problem with nested objectes like languages -> french -> specifications... The reason they are not displayed is simple, they dont get updated. Could take some time

**Comment by GrandSchtroumpf** [comment]
This can happen when the chain of fonction is broken. `patchAllValue` will call the `patchAllValue` of all children if it exist. If the "LanguagesForm" is not an `FormEntity ` for example it'll break. We need to make sure we don't use FormGroup or FormArray, but FormEntity & FormList instead

**Comment by Maxstgt** [comment]
![Screenshot from 2020-03-24 12-13-44](https://user-images.githubusercontent.com/39312833/77420196-e705ea00-6dc9-11ea-83a2-1c72ee61d222.png)
So as the object is not enumerable when the function is called, the factory function returns an empty object and this is the reason why languages are not shown up in the film details tab

**Comment by Maxstgt** [comment]
there are now pricinipal cast, cause the role is not set in the form
