### ISSUE TITLE
Scroll issues 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2123]
When you go from /search to a movie page, most of the time you land at half the page, not on top of the page 
Edit: It looks like this issue is a big one and another people encounter it in their project.
https://github.com/angular/angular/issues/24547
TLDR: router property `scrollPositionRestoration` and other workarounds like `window.scrollTo` don't work with dynamic content.
Edit2: Using `html { min-height: 100% }` instead of `height` + `scrollPositionRestoration: top` make it work, but sticky elements are not sticky anymore (toolbar, filters etc)

**Comment by Maxstgt** [comment]
So the getter function from the global window object like `window.scrollY` returns 0. Which should be on top of the screen. Which might be correct in terms of beeing into a nested `router-outlet`. View Component renders the header with the poster and the main information about the movie and then the avails or main component renders the detailed information. This router-outlet thinks he is the top level entry point.

**Comment by Maxstgt** [comment]
I guess this is a scss problem here. Cause the router and the extraOptions for the router works as expected. And when I do some scss magic, like suggested in the edit2 comment. It works.

**Comment by Maxstgt** [comment]
I discovered that the filters tab in the movie detail view :movieId/view/details , there are no arrows on the tabs main information and avails, but if I click on one, the arrows appear. It might break some background process to scroll to the top. Cause when I reload the page with the refresh button from the browser it is always on top. So I guess it has nothing to do with the router settings

**Comment by Maxstgt** [comment]
If you want to go back from the movie view deail page to the search page, it is not possible when you clicked on one of the filter tabs. This will jump back and forth if you click on the back button of the browser. Might be an indicator?

**Comment by Maxstgt** [comment]
![Screenshot from 2020-03-03 14-11-11](https://user-images.githubusercontent.com/39312833/75778858-e349ef00-5d58-11ea-9e7a-53155988bcb7.png)
the first is from the search page and the last one is from the detail view page. So the component thinks he is on the top of the page

**Comment by Maxstgt** [comment]
when I remove the body and html height:100% property, the window.scrollY is now working as expected. So the problem comes from here

**Comment by Maxstgt** [comment]
the problem is that we can't set scrolling position until we handle the issue with the hight : 100% property

**Comment by Maxstgt** [comment]
html {
  min-height: 100%;
  display: flex;
}
body {
  min-height: 100%;
  flex: 1;
  margin: 0;
}
this seems to work

**Comment by Jackseed** [comment]
We can't afford to loose sticky behavior... we need a better option

**Comment by Maxstgt** [comment]
alright

**Comment by Maxstgt** [comment]
So if you set the ``` html{
  height: 100vh;
} ```
You get what you need. Cause 100% points just to the parent html tag. But since the html is the root, there is now parent. This is why you need to set it to view height which seems to be the same but it points to the viewport of the window

**Comment by Jackseed** [comment]
@Maxstgt still got the issue, did we change css according to your comment?

**Comment by Maxstgt** [comment]
We did but I experienced the issue again a while a go. We need to find a way to statically define the height so that during development nobody can change it

**Comment by Maxstgt** [comment]
https://github.com/angular/components/issues/4280 
The problem originates from the sidenav container. The container is always on top and and for the window object it seems that you never scrolled. Which is the case, you only scrolled inside of the container. Which makes native calls to the window object useless. You need to reset the scroll position of mat-sidenav-content to 0 everytime you navigation finished.
Normally the angular router would do that, but he does native calls to the window object which, indicated above, is useless when you are in a wrapper. Thats why we need to make it manually until this feat request (link above) gets fullfilled.

**Comment by Maxstgt** [comment]
wise words: https://github.com/angular/components/issues/4280#issuecomment-462712310
