### ISSUE TITLE
Move enum to string litterals

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#2134]
Angular 9 now check types in the template. Is good 😁... but when we use enum it means that we need to pass the enum in the template. It's super annoying 😒.

Let's use string litterals instead. Here is the migration process : 

**Level 1: "It's just a string !"**
```typescript
type StoreType = 'line_up' | 'library';
```

**Level 2: "It's an array of strings"**
```typescript
const storeType = ['line_up' | 'library'] as const;
type StoreType = typeof storeType[number]; // 'line_up' | 'library'
```

**Level 3: "But I want to display it in the page"**
```typescript
const storeType = {
  line_up: 'Line Up',
  library: 'Library'
} as const;
type StoreType = keyof typeof storeType; // 'line_up' | 'library'
```
> We are not using camelCase for the key here. Francois is not happy 😢, but we want the string here, and as it already exist like that, I think he can understand. For the new keys let's KFH (Keep Francois Happy) 😉.

**Comment by phpgeekfr** [comment]
updated notion : https://www.notion.so/cascade8/Data-modeling-conventions-d09e9d6e4e3d48b2b71274bb330e3d2e#3d5371f0e0ca4cf2910e45691c700519

and draw.io
