### ISSUE TITLE
Access problem to an accepted org

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2154]
Context : I use the same email address to create different orgs : to invite clients to Archipel, I create their org, send invites, and discretely leave the org and delete my user account on firebase)
- [ ] When I create a new org (with the same email address : demo@cascade8.com), there's no problem during the creation. But once the org is accepted, I try to log in with demo@cascade8.com but I keep ending up on the page saying the org is still in the process of being accepted. I have to clear site data to be able to log in.
![image](https://user-images.githubusercontent.com/55785823/75997307-72910700-5eff-11ea-8941-98aafef8e03a.png)

**Comment by maltmayer** [comment]
Actually, it's a general bug. It happened with someone who went on archipelcontent.com for the first time and followed the usual process to sign up. She got stuck at on the same page even after I accepted her org.

**Comment by phpgeekfr** [comment]
Maybe there is some missing subscription to organization state that prevent org status update on client side.
> She got stuck at on the same page even after I accepted her org.

@maltmayer do you know if she reloaded the page or if she just waited for the page to update?

**Comment by maltmayer** [comment]
She reloaded the page

**Comment by phpgeekfr** [comment]
Problem should be resolved in next deployment
