### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2157]
- [ ] I get this when I try to connect
![image](https://user-images.githubusercontent.com/55785823/76007633-a1fb4000-5f0e-11ea-90e1-467cfa88a75e.png)

**Comment by Jackseed** [comment]
This is often a bug linked to a cache issue, not sure a 'real' user can run into this issue. If it happens again we need more context to fix it. 
I close it and will re-open if needed
