### ISSUE TITLE
Cropper problem on Organization page

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2161]
(when I log in and create an org or also when I edit the org information when I'm logged in)
- [ ] cropper is not centered
![image](https://user-images.githubusercontent.com/55785823/76069819-bd5c5e80-5f93-11ea-8234-26092507d694.png)
- [ ] when logo is too big, cropper is also too big. So we can't see the whole thing at once.
![image](https://user-images.githubusercontent.com/55785823/76069756-a289ea00-5f93-11ea-869e-0f42ae722556.png)

**Comment by Jackseed** [comment]
outdated > closed
