### ISSUE TITLE
Loading problem on Dashboard 

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2162]
- [ ] When I get on the Dashboard, either on the "Dashboard" page or "My Titles", the page normally takes a long time to charge but in the end, it does charge. But this time, it loaded indefinitely and never charged. It's still loading as I write this (it been more than 5 minutes) and it's not a wifi problem. All the rest works fine
![image](https://user-images.githubusercontent.com/55785823/76073840-93f30100-5f9a-11ea-9c74-9df7abb095ea.png)

**Comment by Jackseed** [comment]
outdated issue > closed
