### ISSUE TITLE
Movie Stats not accurate

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2165]
## Context
On prod dashboard, connecting with vchoukroun+pulsar@cascade8.com (org Pulsar Content), stats where different on each pages:
- /home displayed 15 movie views
- /titles displayed one movie at 4 view and another at 20 (Aznavour)
- /title/Aznavour showed 25 movie views

## Acceptance criteria
- [x] Fix stats so /home is equal to the sum of all title views and /titles show same numbers than /title/id

**Comment by Hugo-Hontans** [comment]
We have differents stats between paths movie/view/main and movie/view/avails. To fix it, we keep only stats from movie/view/main.
We have to think about which stats we have to keep.
We should aggregate stats per userId.
