### ISSUE TITLE
Movie Tunnel Sidenav

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#2167]
Need to refactor entirely this sidenav, it doesn't fit the mockup.

Example on Zeplin : 
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e0b144c41df769a14f55c1e

**Comment by GrandSchtroumpf** [comment]
Design is not consistent with contract tunnel : 
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5e4670704dbf7faac4ff350f 
Also, for us to be able to reuse the whole layout we need to have the same design for all links (here overview & summary are different). This was an issue when implementing the difference between mandate & sale tunnel.

**Comment by fritzschoff** [comment]
the logic how to show what link and what pages are done by the movie shell component
