### ISSUE TITLE
Creation of a contract

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#2177]
At the end of the contract tunnel when we submit a new contract, this error appears in a snackbar
```Error: Uncaught (in promise): FirebaseError: [code=not-found]: No document to update: projects/block```

In the code, we update a document but at the creation, we can't update a document that doesn't exist.

```
async submit() {
    const lastIndex = this.form.get('versions').value.length - 1;
    const contractId = this.query.getActiveId();

    // Make sure everything is saved first and that deals have ids
    await this.tunnel.save();
    const write = this.db.firestore.batch();
    this.service.update(`${lastIndex}`, { status: 'submitted' }, { params: { contractId }, write });

    for (const movieId in this.dealForms.value) {
      const dealIds = this.dealForms.get(movieId).value.map(deal => deal.id);
      this.dealService.update(dealIds, { status: 'undernegotiation' }, { params: { movieId }, write });
    }
    return write.commit();
  }
```
Need to find a way to differentiate when a contract is created or updated. Also, the contract is well created (in my case, it appears in firebase with the data I put in the form) but no redirection and no information about the creation of the contract.

**Comment by GrandSchtroumpf** [comment]
Could use `service.upsert` instead of `update`. BUT at this page the contract & rights (previously deals) should already exist. So the issue should come from somewhere else.
