### ISSUE TITLE
Film page spacing issues

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2196]
- [ ] "Technical information" card has no space under it. It's too close to the en of the screen.
![image](https://user-images.githubusercontent.com/55785823/76526735-4a108c00-646e-11ea-8e66-3c7437d0aab8.png)
- [ ] "Add to wishlist / Remove from wishlist" CTA is too close to the right. should be aligned with the right end of the "Switch to avails" CTA
![image](https://user-images.githubusercontent.com/55785823/76526886-880db000-646e-11ea-85a4-0b658fc03f4a.png)

**Comment by fritzschoff** [comment]
new design is comming
