### ISSUE TITLE
Dashboard movie import tunnel display problems

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2198]
- [ ]  the light line at the right of the side bar of the import tunnel is not continuous and changes depending on which tab we open
![image](https://user-images.githubusercontent.com/55785823/76527227-29950180-646f-11ea-808e-7cb59df232fc.png)
![image](https://user-images.githubusercontent.com/55785823/76527240-2ef24c00-646f-11ea-8086-0887bcdca824.png)

- [ ] on first page (Add a title), steps numbers' font is not the right one I think. Looks like Times New Roman
![image](https://user-images.githubusercontent.com/55785823/76530687-5f88b480-6474-11ea-878a-619091794b83.png)

- [ ] On Legal information page > Chain of titles > Upload documents car : there is a line at the botom of the card that shouldn't be here (after "Add a document")
![image](https://user-images.githubusercontent.com/55785823/76530779-847d2780-6474-11ea-91ca-a717bd074abd.png)
- [ ] Same problem for Media > promotional images > stills
![image](https://user-images.githubusercontent.com/55785823/76534543-e8eeb580-6479-11ea-96a1-bc970ffb769f.png)

**Comment by fritzschoff** [comment]
we got a new tunnel now
