### ISSUE TITLE
Dashboard movie import tunnel bug

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2199]
- [ ] When I navigated through the different steps of the import tunnel, at some point, it stoped working. I didn't do anything in particular outside of clicking on different steps (in a random order, without following the chronological order)
![image](https://user-images.githubusercontent.com/55785823/76527449-8a243e80-646f-11ea-898f-c47154cdf91c.png)

**Comment by maltmayer** [comment]
More info : it works when I click on "Skip and do later" but not when I click on different steps on the side bar

**Comment by maltmayer** [comment]
Other info : everything works fine (even when I navigate betweens steps) until I click on a field (as if I was starting to fill up info for my film) and go to other step without saving.

**Comment by fritzschoff** [comment]
we got a new tunnel
