### ISSUE TITLE
Adaptable display on film page info

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2200]
- [x] Is it possible to only show International Title when international title and original title are the same ? 
![image](https://user-images.githubusercontent.com/55785823/76527517-a58f4980-646f-11ea-8300-0468086df635.png)

- [x] Is it possible not to show the running time when the information is "TBC" (meaning "to be confirmed" so not determined yet) in the info on top of the film page ? 
![image](https://user-images.githubusercontent.com/55785823/76528067-8513bf00-6470-11ea-8c87-6c2cad19221e.png)

- [x] Is it possible not to show a field if empty ?
![image](https://user-images.githubusercontent.com/55785823/76528110-92c94480-6470-11ea-81d7-0222866c56d8.png)
(About this field, I fear that that might be a display bug ? Cause I think I remember filling in some information on this film (Teddy) about Budget and Quotas)

**Comment by ioaNikas** [comment]
> (About this field, I fear that that might be a display bug ? Cause I think I remember filling in some information on this film (Teddy) about Budget and Quotas)

@maltmayer I checked on the database and all the fields are empty. Try to fill them again and if they are still not displayed, open an issue about this bug.
