### ISSUE TITLE
Carousel image display problem

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2206]
- [ ] (Sorry if I already added this issue...I don't remember if I did or not, and can't find it in the list... so just in case: ) images don't fit right in the marketplace home page carousels. Previous images show overlap on the next one, and little by little, it overlaps more and more. 
![image](https://user-images.githubusercontent.com/55785823/76531459-8a273d00-6475-11ea-8996-4680ac7b766a.png)
![image](https://user-images.githubusercontent.com/55785823/76531473-8f848780-6475-11ea-96cc-bd9c1cd8b353.png)

**Comment by Maxstgt** [comment]
@Jackseed can you reproduce? cause I dont have this issue and I cant reproduce. @maltmayer still persist?

**Comment by Maxstgt** [comment]
new carousel are coming. closing this issue
