### ISSUE TITLE
Notification page needs refactoring

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#2209]
Currently we use the same component for the notification page and the pop-up of notification.
It can't be the same because of the design that will be different (different size available for text in page and pop-up, etc).

**Comment by GrandSchtroumpf** [comment]
The best way to deal with this kind of issue is to provide a pattern for this kind of components that we could apply for other case: 
Example : _entity_-page / _entity_-widget
- notification-page
- notification-widget

Like that @vwmathilde can apply this pattern to other data in the future, and it provide developers an easy way to organise the project.
