### ISSUE TITLE
[Component] Slider

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#2242]
# Slider
## Implement Component
- [x] Create story with storybook
- [ ] Connect component to Zeplin with zeplin-connect

## Description

- **name**: "mat-slider"
- **lib**: ui

> Remove the current ui/carousel to ui/slider instead.

This is a reusable component to replace the "mat-carousel" that we have.
As part of our component library we need to manage our own version to be able to update it depending on UI/UX needs.

Take the code from this repository as example: 
https://github.com/gbrlsnchs/material2-carousel/tree/master/projects/carousel/src/lib

## Type
- [ ] **Layout**: _Structure a page with content projection (ex: MovieView)._
- [ ] **Page**: _Loaded by the router. Usually used in an app (ex: CatalogDashboardMovieView)._
- [x] **Component**: _Structure a piece of data in the page (ex: MovieTable)._
- [ ] **Display**: _Render data in a page. Can use a component-type (ex: MovieMain, MovieBudget)._
- [ ] **Form**: _Get data from the user (ex: MovieFormBudget)._

### Input
**Slider** ([link](https://github.com/gbrlsnchs/material2-carousel/blob/master/projects/carousel/src/lib/carousel.component.ts)): 
- [x] autoplay: boolean
- [x] interval: number
- [x] ratio: number ???
- [x] useMouse: boolean (should scroll move the slides)

**Slide** ([link](https://github.com/gbrlsnchs/material2-carousel/blob/master/projects/carousel/src/lib/carousel-slide/carousel-slide.component.ts)):
- [x] asset: string (link to a local image)
- [x] ref: ImgRef (link to firestorage)
- [x] hasOverlay: boolean

### Theme
Default overlay color should depend on the theme because of color of typography.
Check with @vwmathilde for any other recommandation.

## Where is it used
In marketplace home

**Comment by Maxstgt** [comment]
I would do the ratio as a string like ```    ratio: '1:1' | '6:5' | '5:4' | '4:3' | '2:1' | '16:9';``` and the useMouse, I would call it swipe

**Comment by Maxstgt** [comment]
@GrandSchtroumpf why do you need an img ref in the slide component ? ```ref: ImgRef (link to firestorage)```

**Comment by GrandSchtroumpf** [comment]
All our media are stored as an ImgRef. So it would be super handy to manage the background of the slide with the BackgorundRef directive.

**Comment by Maxstgt** [comment]
okay sounds good
