### ISSUE TITLE
[Events] Create library event for calendar

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#2244]
# Event

## Description
The new application "festival" requiers a calendar view of the user. This leads to the creation of an "events" collections & library.

> The collection should be agnostic of the application (a little bit like "notification").

In the case of "festival" we need to use it for : 
- **meeting**: _appointement between several users (seller & buyer for instance)_.
- **screening**: _streaming session of a movie_.

User A can _invite_ another user B to an event. Then user B can _accept_ or _decline_.
An event can be used for permission to access. For example a screening is only available to people that have accepted the event.
[optional] An event can be visible or hidden (cf "calendar.status" below). If the calendar is shared, an event can still be hidden (the content cannot be seen, but the calendar would have a gray zone).

> I would recommand to look at google calendar & outlook to see how they deal with events.

## Model
- period: { from: Date, to: Date }
- label: string
- description: string
- type: 'meeting' | 'screening'
- invitations: { id: string, status: 'pending' | 'accepted' | 'declined' }[] (can be something better for better queries)

Maybe we need a "owner" of the event who can modify it.
We might need also more field depending on the type. Like a link for a call for "meeting", but let's keep it simple for now.

## Components
The library will hold the component needed to manage the event like the calendar, forms or notifications. Nothing precise yet.

# Calendar
_Maybe this is not needed, if we can achieve the same with firebase query on event_
User & organization can have one calendar. It's an object inside the user or organization document to easily share a full calendar.

## Model
- status: 'public' | 'shared' | 'private'
- eventIds: string[]
- sharedWith: string[]

- [ ] check `#2244` in code

**Comment by phpgeekfr** [comment]
model 
```
// Event types
type EventTypes = 'meeting' | 'screening';
interface Meeting {
  callUrl: string;
}
interface Screening{
  movieId: string;
}
interface EventBase<D extends Timestamp | Date, Meta = any> {
  id: string;
  ownerId: string;
  type: EventTypes;
  title: string;
  start: D;
  end: D;
  meta: Meta;
}
// firestore
type EventDocument<Meta> = EventBase<Timestamp, Meta>;
type MeetingEventDocument = EventDocument<Meeting>;
type ScreeningEventDocument = EventDocument<Screening>;
// angular
type Event<Meta> = EventBase<Date, Meta> & CalendarEvent<Meta>;
interface MeetingEvent extends Event<Meeting> {
  type: 'meeting';
}
```
