### ISSUE TITLE
[Refactoring] Move CatalogSearchForm to Movie library

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#2249]
Currently the form to search for a movie in apps "catalog" and "festival" is called `CatalogSearchForm` and it leaves inside the "movie/distribution-deal" library.
It looks like this form concern only information concerning the movie (not the distribution rights) + it's used by the "festival" app that doesn't filter over rights. So I would recommand to move this form into "movie/form". 

If possible we should use the same forms & form component in the search movie & in the tunnel movie.

**Comment by fritzschoff** [comment]
fixed by title layout component
