### ISSUE TITLE
Should users validate their email

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2283]
- [ ] Merge Welcome email with Verification email. I can work on a new text when you tell me to.

**Comment by pldespaigne** [comment]
@Jackseed Marie just created this issue, we should think of how to integrate this issue in the dev cycle

**Comment by fritzschoff** [comment]
@maltmayer is this still valid? if not please close

**Comment by maltmayer** [comment]
Yep. But now I have a question that comes to mind: to we need the verification email? What is its use?

**Comment by Jackseed** [comment]
@maltmayer @fritzschoff that has already been done. 
The use of this verification is to be sure that the user hasn't made mistake on his/her email address. 
It's implemented (one welcome email that has verification inside) but in fact we don't really use as you can still access the app without verifying your email address

**Comment by fritzschoff** [comment]
@Jackseed so we need to check if email is verified and if not notify the user with a new small page?

**Comment by Jackseed** [comment]
@fritzschoff that's more of a UX decision to take with @2amarkina & @maltmayer:
- do we block user's connexion while they haven't verify their email;
- do we just suggest it; 
- do we keep it as it is: non blocking, not suggested except with welcome email

**Comment by Jackseed** [comment]
Update here, it's confirmed that we should validate users' email address and block them as long as it's not validated. This ticket will be integrated in the new connexion flow #3212
