### ISSUE TITLE
Transform objects that are living in FormControl into FormGroups|FormEntity

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#2284]
I found some objects that lives inside of a formcontrol, which makes in most cases no sense. It should be a formgroup aka formEntity. I found often on data objects like logo : {url: ' ' media: ' ', orignialRef: ' '} this should be transformed into an own formgroup otherwise missing control has no chance to distinguish between valid values and not valid values.

**Comment by Jackseed** [comment]
No clue on this, @GrandSchtroumpf  ?

**Comment by GrandSchtroumpf** [comment]
Be careful not to apply this pattern blindly. Most of the time it's better to have a form entity. 
But in some cases we need to have a FormControl. Like when we have a ControlValueAccessor (which might be the case of the ImgRef object with the cropper). 
In this case we consider the object as one unbreakable value. You can still create custom validators for them if needed.

**Comment by Maxstgt** [comment]
this question appeared on displaying value in film details tab. So either we update the missing control component so it can handle that specific case, which I think is not a good way, or we update the way we store information about imgRef. This is not aboout validators.

**Comment by GrandSchtroumpf** [comment]
The cropper beeing a ControlValueAccessor I think it would be a mistake to have a FormEntity to manage for it. If it's already the case, it might be a problem (to verify). 
I don't understand why it's an issue anyway. If an object is in a FormControl it means that it should be treated as a single value. Why the missing control is not working for that ?
The missing control is all about validators (it checks the required). So if it cannot check object based FormControl we should add some custom validators that "missing control component" could understand.

**Comment by Maxstgt** [comment]
The missing control can't check the object and what is necessary to display correctly. Thats why you will never get any value to display OR a missing or mandatory out of the missing control component. That lead to issues in the film details page for instance where no value where displayed. 
If you have an object inside of a formcontrol how does the form is going to look like?

**Comment by GrandSchtroumpf** [comment]
I thought the missing control component could content a template ?
For me a good design would be : 
```html
<missing-control [control]="posterCtrl" mandatory="hasUrl" missing="anotherErrorKey">
  <ng-template isValid let-poster>
     <!-- Display a previous of the poster, or a short version of the url or whatever -->
  </ng-template>
  <ng-template isInvalid let-errors>
     <!-- Display the message from the control or something else -->
  </ng-template>
</missing-control>
```
With posterCtrl: 
```typescript
posterCtrl = new FormControl(
  {url: ' ' media: ' ', orignialRef: ' '},
  (control) => control.value.url ? { hasUrl: 'You should enter the URL' } : null
);
```
Basically the missing-control should : 
- By default if the control is require, show "mandatory"
- If no input "mandatory" or "missing" is povided, check the property "valid" of the form.
- If "mandatory" or "missing" is povided, check the "hasError()" for each key and display the "isInvalid" template if provided (else show "mandatory" or "missing" depending on the error with mandatory > missing).
- ...

Let's do this component step by step to make sure we cover all cases, but with some common sens and by not rushing it, we should be able to create something that works nicely.

**Comment by Maxstgt** [comment]
anyway, this issue was created on your behalf.
![Screenshot from 2020-04-08 14-29-45](https://user-images.githubusercontent.com/39312833/78784316-6cca8d80-79a5-11ea-8036-5f9e01e68690.png)

**Comment by GrandSchtroumpf** [comment]
"Except very specific cases (like with control value accessor)" ^^
Anyway I think this conversation can help improving the missing-control component.
