### ISSUE TITLE
Archipel Festival dashboard calendar

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2286]
2 options for the dashboard calendar : 
Option 1 
- A page "My Schedule" with all the sellers' events (Meetings + Screenings)
- On this page, a CTA "Plan a screening" would redirect to another page (or pop up) with the general screening schedule (with all the screenings booked in all the screening rooms). On this schedule, users could create a request to Archipel (to book a screening at that time). 

Option 2
- A page "My Schedule" with all the sellers' events (Meetings + Screenings), on which they could chose to see or not see different agendas (like in Google Cal). So they would have "My Events" and "General Screening Schedule"
If we go with this 2nd option, we could even show the calendars of other members of the org

**Comment by Jackseed** [comment]
outdated issue > closed
