### ISSUE TITLE
[Event] Meeting connect to jisti-meet

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#2291]
## Event - Meeting
Use the [jitsi api](https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md) to create a room for the meeting based on the "id" of th event document.

### Module
Create a module inside `utils` that wrap the jisti api to simplify the code.

#### Service
Wrapper around the jitsi API

#### Component
Create an embedded version of jisti that we could put in the meeting page.

**Comment by Jackseed** [comment]
@phpgeekfr @GrandSchtroumpf here the flow is:
1. A user creates an event 
2. A custom unique event session link is generated for the event using jitsi as visio tool (link available on the event page)
3. The user invites other users
4. Other users accept / refuses the invitation
5. Only invited users (don't care if they accept or refuse the invitation) can access the session link
Question remaining: time when the link is accessible, are they problems to keep it alive for a while ? or should we restrict it a lot?
