### ISSUE TITLE
Make all images responsive depending of the user screen width

### ISSUE THREAD

**Issue by ioaNikas** [blockframes/blockframes#2308]
- [ ] Update and debug cropper module to force specific ratio on images upload.

- [ ] Create a pattern that loads specific image size base on the screen width. Use CSS media queries instead of rxjs to avoid subscriptions.

- [ ] We could still enforce a size for all screen width. For example, avatar in profile widget should always be an xtra small image.

- [ ] Create a firebase cloud function to create multiple versions of an uploaded image, fitting each of our breakpoints if necessary.

Documentation
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by Jackseed** [comment]
Let's go on the easy solution: firebase extension

**Comment by Jackseed** [comment]
Explaining + directive
