### ISSUE TITLE
[Component] movie_card_small

### ISSUE THREAD

**Issue by vwmathilde** [blockframes/blockframes#2344]
# Component

Zeplin
- [Editable Link](https://app.zeplin.io/styleguide/5e0f7156cf562c1cb478f0f5/components?coid=5e82fd7111ff716b5d37528d)
- [Dark](https://zpl.io/VY4q1gp) | [Light](https://zpl.io/boz37mE)
- [Dark](https://zpl.io/VY4q1ld) | [Light](https://zpl.io/Vxd3WNx)

## UI review
_remove this section once everything is checked_
- [X] UI doesn't already have a existing component.
- [X] Name display in Zeplin is the same as the one in the issue (see below).
- [X] Data can be display like in the UI (see notion).
- [x] A link to this issue in the zeplin object

## Implement Component
- [ ] Create story with storybook
- [ ] Connect component to Zeplin with zeplin-connect

## Description

- name: movie-card-small
- lib/app: movie

## Type
- [ ] **Layout**: _Structure a page with content projection (ex: MovieView)._
- [ ] **Page**: _Loaded by the router. Usually used in an app (ex: CatalogDashboardMovieView)._
- [X] **Component**: _Structure a piece of data in the page (ex: MovieTable)._
- [ ] **Display**: _Render data in a page. Can use a component-type (ex: MovieMain, MovieBudget)._
- [ ] **Form**: _Get data from the user (ex: MovieFormBudget)._

### Input
_can be data (movie, distribution right, ...), or UI related (dense, appearance)_
- [ ] movie

### Data view
_data displayed in the UI, derived from the inputs (ex: **title**: movie.main.title.international)
- [ ] movie.main.title.international
- [ ] movie.main.directors | displayName
- [ ] oneLineDesciption "[genre] | movie.****.productionYear | movie.durationTime"

## Where is it used
-links and snapshots where the component is used_
https://app.zeplin.io/project/5e82f6ca1c987015ec21c1d7/screen/5e830f0a69814511d8862b8b

**Comment by Mussuranae** [comment]
I think we can close this one, we can use the same movie-card for every size of movie-card, so we can use the movie-card-large issue (2354) to reference every movie-card, no ?

**Comment by GrandSchtroumpf** [comment]
Ok
