### ISSUE TITLE
Replace Territories/Countries List

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2347]
- [ ] Replace current list to : 

- Afghanistan
- Albania 
- Algeria 
- American Samoa
- Andorra 
- Angola 
- Anguilla
- Antigua and Barbuda 
- Argentina 
- Armenia 
- Aruba
- Australia 
- Austria 
- Azerbaijan 
- Bahamas 
- Bahrain 
- Bangladesh 
- Barbados 
- Belarus 
- Belgium 
- Belize 
- Benin 
- Bermuda
- Bhutan 
- Bolivia 
- Bonaire, Sint Eustatius and Saba
- Bosnia and Herzegovina 
- Botswana 
- Brazil 
- British Virgin Islands
- Brunei 
- Bulgaria 
- Burkina Faso 
- Burundi 
- Côte d'Ivoire (Ivory Coast)
- Cabo Verde 
- Cambodia 
- Cameroon 
- Canada 
- Cayman Islands
- Central African Republic 
- Chad 
- Chile 
- China 
- Christmas Island
- Cocos Islands
- Colombia 
- Comoros 
- Cook Islands
- Congo (Congo-Brazzaville) 
- Costa Rica 
- Croatia 
- Cuba 
- Curaçao
- Cyprus 
- Czech Republic (Czechia) 
- Democratic Republic of the Congo 
- Denmark 
- Djibouti 
- Dominica 
- Dominican Republic 
- Ecuador 
- Egypt 
- El Salvador 
- Equatorial Guinea 
- Eritrea 
- Estonia 
- Eswatini (former Swaziland) 
- Ethiopia
- Falkland Islands
- Faroe Islands 
- Fiji 
- Finland 
- France 
- French Guiana
- French Polynesia
- Gabon 
- Gambia 
- Georgia 
- Germany 
- Ghana 
- Gibraltar
- Greece 
- Greenland
- Grenada 
- Guadeloupe
- Guam
- Guatemala 
- Guernsey
- Guinea 
- Guinea-Bissau 
- Guyana 
- Haiti 
- Honduras 
- Hong Kong
- Hungary 
- Iceland 
- India 
- Indonesia 
- Iran 
- Iraq 
- Ireland 
- Isle of Man
- Israel 
- Italy 
- Jamaica 
- Japan 
- Jersey
- Jordan 
- Kazakhstan 
- Kenya 
- Kiribati 
- Kuwait 
- Kyrgyzstan 
- Laos 
- Latvia 
- Lebanon 
- Lesotho 
- Liberia 
- Libya 
- Liechtenstein 
- Lithuania 
- Luxembourg 
- Macao
- Madagascar 
- Malawi 
- Malaysia 
- Maldives 
- Mali 
- Malta 
- Marshall Islands 
- Martinique
- Mauritania 
- Mauritius 
- Mayotte
- Mexico 
- Midway Islands
- Micronesia 
- Moldova 
- Monaco 
- Mongolia 
- Montenegro 
- Montserrat
- Morocco 
- Mozambique 
- Myanmar
- Namibia 
- Nauru 
- Nepal 
- Netherlands 
- New Caledonia
- New Zealand 
- Nicaragua 
- Niger 
- Nigeria 
- Niue
- Norfolk Island
- North Korea 
- North Macedonia 
- Northern Cyprus
- Northern Mariana Islands
- Norway 
- Oman 
- Pakistan 
- Palau 
- Palestine State 
- Panama 
- Papua New Guinea 
- Paraguay 
- Peru 
- Philippines 
- Pitcairn Islands
- Poland 
- Portugal 
- Puerto Rico
- Qatar 
- Republic of Kosovo
- Réunion
- Romania 
- Russia 
- Rwanda 
- Saint Barthélémy
- Saint Helena, Ascension and Tristan da Cunha
- Saint Kitts and Nevis 
- Saint Lucia 
- Saint Martin
- Saint Pierre and Miquelon
- Saint Vincent and the Grenadines 
- Samoa 
- San Marino 
- Sao Tome and Principe 
- Saudi Arabia 
- Senegal 
- Serbia 
- Seychelles 
- Sierra Leone 
- Singapore 
- Sint Maarten
- Slovakia 
- Slovenia 
- Solomon Islands 
- Somalia 
- South Africa 
- South Korea 
- South Sudan 
- Spain 
- Sri Lanka 
- Sudan 
- Suriname 
- Sweden 
- Switzerland 
- Syria 
- Tajikistan 
- Taiwan
- Tanzania 
- Thailand 
- Timor-Leste (East Timor)
- Togo 
- Tokelau
- Tonga 
- Trinidad and Tobago 
- Tunisia 
- Turkey 
- Turkmenistan 
- Turks and Caicos Islands
- Tuvalu 
- Uganda 
- Ukraine 
- United Arab Emirates 
- United Kingdom 
- United States  
- United States Virgin Islands
- Uruguay 
- Uzbekistan 
- Vanuatu 
- Vatican City
- Venezuela 
- Vietnam 
- Wallis and Futuna
- Yemen 
- Zambia 
- Zimbabwe

**Comment by GrandSchtroumpf** [comment]
Could you provide more context ? I think the current list follow an iso @phpgeekfr can you confirm ?
We use this list for the map (which has predefined borders) so we need to keep them in sync.

**Comment by maltmayer** [comment]
Ok I'll do it differently. I'll list the changes I'd like to make. 
It's mostly changes of names for some countries, cause the name are not modern at all (like instead of the UK or United Kingdom, we currently have "United Kingdom of Great Britain and Northern Ireland (the)" which looks ridiculous to me.) So mainly it shouldn't impact the map, just the names.
(But it's true that I spotted some territories that were not in our list, and should maybe be added. I'll investigate if it's necessary to update the map or if it's good as it is.)
It's not of major importance but Vincent told me to make an issue out of it, to update the list when we can.

**Comment by maltmayer** [comment]
Name updates : 
- Bahamas (the) > Bahamas 
- Bolivia (Plurinational State of) > Bolivia
- Virgin Islands (British) > British Virgin Islands
- Brunei Darussalam > Brunei
- Cayman Islands (the) > Cayman Islands
- Central African Republic (the) > Central African Republic
- Cocos (Keeling) Islands (the) > Cocos Islands
- Comoros (the) > Comoros
- Congo (the) > Congo (Congo-Brazzaville)
- Congo (the Democratic Republic of the) > Democratic Republic of the Congo
- Cook Islands (the) > Cook Islands
- Côte d'Ivoire > Côte d'Ivoire (Ivory Coast)
- Czechia > Czech Republic (Czechia)
- Dominican Republic (the) > Dominican Republic
- Falkland Islands (the) [Malvinas] > Falkland Islands
- Micronesia (Federated States of) > Micronesia
- Gambia (the) > Gambia
- Iran (Islamic Republic of) > Iran
- Lao People's Democratic Republic (the) > Laos
- Northern Mariana Islands (the) > Northern Mariana Islands 
- Marshall Islands (the) > Marshall Islands 
- Moldova (the Republic of) > Moldova
- Netherlands (the) > Netherlands
- Niger (the) > Niger
- Korea (the Democratic People's Republic of) > North Korea
- Palestine, State of > Palestine
- Philippines (the) > Philippines
- Pitcairn > Pitcairn Islands
- Russian Federation (the) > Russia
- Korea (the Republic of) > South Korea
- Sudan (the) > Sudan
- Syrian Arab Republic (the) > Syria
- Taiwan (Province of China) > Taiwan
- Tanzania, the United Republic of > Tanzania
- Timor-Leste > Timor-Leste (East Timor)
- Turkish Republic of Northern Cyprus > Northern Cyprus
- Turks and Caicos Islands (the) > Turks and Caicos Islands
- United Arab Emirates (the) > United Arab Emirates
- United Kingdom of Great Britain and Northern Ireland (the) > United Kingdom
- United States of America (the) > United States
- Virgin Islands (U.S.) > United States Virgin Islands
- Venezuela (Bolivarian Republic of) > Venezuela
- Viet Nam > Vietnam

**Comment by phpgeekfr** [comment]
[Updates list of countries.xlsx](https://github.com/blockframes/blockframes/files/4514880/Updates.list.of.countries.xlsx)

**Comment by fritzschoff** [comment]
make a migraction script for every field which uses territories
