### ISSUE TITLE
[Component] Header

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2352]
# Component

[Light](https://zpl.io/2Gl5pYr)
[Dark](https://zpl.io/Vk09rrG)

## UI review
_remove this section once everything is checked_
- [x] UI doesn't already have a existing component.
- [ ] Name display in Zeplin is the same as the one in the issue (see below).
- [x] Data can be display like in the UI (see notion).
- [x] A link to this issue in the zeplin object

## Implement Component
- [x] Create story with storybook
- [x] Connect component to Zeplin with zeplin-connect

## Description

- name: catalog-footer
- lib/app: catalog - app

## Type
- [ ] **Layout**: _Structure a page with content projection (ex: MovieView)._
- [ ] **Page**: _Loaded by the router. Usually used in an app (ex: CatalogDashboardMovieView)._
- [x] **Component**: _Structure a piece of data in the page (ex: MovieTable)._
- [ ] **Display**: _Render data in a page. Can use a component-type (ex: MovieMain, MovieBudget)._
- [ ] **Form**: _Get data from the user (ex: MovieFormBudget)._

### Input
_can be data (movie, distribution right, ...), or UI related (dense, appearance)_
movie

### Data view
_data displayed in the UI, derived from the inputs (ex: **title**: movie.main.title.international)

------

## Where is it used
-links and snapshots where the component is used_
https://app.zeplin.io/project/5e82f6ca1c987015ec21c1d7/screen/5e830f0a69814511d8862b8b

**Comment by Maxstgt** [comment]
@Jackseed rename the issue, its about the footer not the header.
@vwmathilde catalog-footer in zepplin as well as here

**Comment by Maxstgt** [comment]
@vwmathilde please rename this component `movie-header`

**Comment by Maxstgt** [comment]
@2amarkina about the breadcrumbs, are they clickable? what is the structure for them? Like the user navigation behavior?

**Comment by Maxstgt** [comment]
@2amarkina about the `More` button where does it link to? to movie detail page?

**Comment by Maxstgt** [comment]
@2amarkina where is the link from pitch trailer coming from?

**Comment by Jackseed** [comment]
@Maxstgt re the breadcrumbs, it's not implemented yet and I assume it will be a component on its own (@GrandSchtroumpf ?), imo it's not related to this issue and just know when you work on the Header component that in the future it should include a breadcrumb component. 
Re the More button, it can't lead to the movie page as you already are on the movie page. I think it's related to the CTA buttons `Download Scenario`,.. in case there is more promotional content to display and then I assume it should be a dropdown menu where you can select the other contents. Though @2amarkina should confirm this. 
Re the pitch trailer I think it's missing from the data model @2amarkina @Mussuranae

**Comment by Maxstgt** [comment]
this going to be tricky but I will and try to implement whats possible

**Comment by Maxstgt** [comment]
@Jackseed as state in this picture from Anastasiia it is not related to CTA 
[img](https://user-images.githubusercontent.com/55499036/78556485-5ab6e680-780f-11ea-8130-4a212526c089.png)

**Comment by GrandSchtroumpf** [comment]
@Maxstgt This image is outdated. Look at the most recent comment: 
![image](https://user-images.githubusercontent.com/8143464/79320489-3099ae80-7f0a-11ea-8e25-6790824fcf91.png)

**Comment by Maxstgt** [comment]
yes, the more button is not in the CTA, read again my comment

**Comment by Maxstgt** [comment]
@Jackseed @2amarkina Since movie.promotionalElements.poster is an array, which means it can be multiple poster, what should happen if there are many? only the first? should it slide through all the posters?

**Comment by Maxstgt** [comment]
@2amarkina about the poster. In your sketch the grey box. We can have multiple posters, which one should we display?

**Comment by Maxstgt** [comment]
@vwmathilde are the three dots icon befor of the `More` available?

**Comment by 2amarkina** [comment]
@Maxstgt 
**Breadcrumbs :** 
Yes, the breadcrumbs should be clickable. There are can be different types of breadcrumbs, but the idea is really to present the path how a user got this page. Exemple : 
<img width="361" alt="breadcrumbs" src="https://user-images.githubusercontent.com/55499036/79440392-39f04d00-7fd6-11ea-96c3-58c21d05fc03.png">

As @Jackseed mentioned this element hasn't been well thought yet, but it's place is shown for future. 

**More button :** 
Sorry if it was not clear enough. The element "...More" if always there from app to app (that's why it is in black). It has always the same behavior : "open the list of other actions". Then actions are specified. 

I've change it to be more precised 
<img width="724" alt="banner image case2" src="https://user-images.githubusercontent.com/55499036/79441657-cea77a80-7fd7-11ea-8cda-4f2937cf6f33.png"> 

**Poster** 
As you know, for the instance we ask a user to choose a banner image and a poster image in the movie tunnel. So, this image comes from there and he/she can change it, but for the instance there is only one image related to this particular place.

**Comment by Maxstgt** [comment]
@2amarkina  thanks for the clearification.
The poster in our code is an array, which means there can be multiple. Like movies can have multiple poster for marketing. Thats why I was asking myself which one I choose.

**Comment by 2amarkina** [comment]
@Maxstgt  Actually we were thinking about the potential "geo-localisation" of the posters, but for the moment it's not decided / thought over and the poster behavior is rather simple. But I see your point and it's great that technically we can have many posters. I put it also as something to think over (especially for our movie form tunnel)

**Comment by Maxstgt** [comment]
okay then I just use the first one and when geo localisation is ready we can rework on that

**Comment by vwmathilde** [comment]
> @vwmathilde are the three dots icon befor of the `More` available?

@Maxstgt I don't know if I understand your question, but the icon name is dot_menu in icon library
