### ISSUE TITLE
[Component] Medium movie card

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2353]
# Component
**Normal** [Dark](https://zpl.io/VY4qz1L) | [Light](https://zpl.io/bAyKeN6)
**Hover** [Dark](https://zpl.io/2vpDpBv) | [Light](https://zpl.io/b67KW3P)

## UI review
_remove this section once everything is checked_
- [ ] UI doesn't already have a existing component.
- [ ] Name display in Zeplin is the same as the one in the issue (see below).
- [ ] Data can be display like in the UI (see notion).
- [ ] A link to this issue in the zeplin object

## Implement Component
- [ ] Create story with storybook
- [ ] Connect component to Zeplin with zeplin-connect

## Description

- name: ...
- lib/app: ...

## Type
- [ ] **Layout**: _Structure a page with content projection (ex: MovieView)._
- [ ] **Page**: _Loaded by the router. Usually used in an app (ex: CatalogDashboardMovieView)._
- [ ] **Component**: _Structure a piece of data in the page (ex: MovieTable)._
- [ ] **Display**: _Render data in a page. Can use a component-type (ex: MovieMain, MovieBudget)._
- [ ] **Form**: _Get data from the user (ex: MovieFormBudget)._

### Input
_can be data (movie, distribution right, ...), or UI related (dense, appearance)_
- [ ] ...

### Data view
_data displayed in the UI, derived from the inputs (ex: **title**: movie.main.title.international)
- [ ] ...

## Where is it used
-links and snapshots where the component is used_

**Comment by Jackseed** [comment]
From @2amarkina 
Has two states : basic and hover. 
![image](https://user-images.githubusercontent.com/14964443/78028698-affe7e00-735f-11ea-9fda-6051bdc3f91b.png)
Background image 
Contenu modifiable : 
if “production status” is “completed” -> show “production year”, “runtime” 
else -> show “production status” 
Contenu modifiable : selon l’application on affiche les informations plus importantes 
CTA qui dirige vers la movie page 
If there is “additional information” considered more important, then -> show search preferences on hover on the left of add to wishlist

**Comment by vwmathilde** [comment]
@GrandSchtroumpf can you review this ?

**Comment by GrandSchtroumpf** [comment]
Closed in favor of #2354 
All three movie-card view will be merged into one
