### ISSUE TITLE
[Component] movie-card-large

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2354]
# Component

**Normal** [Dark](https://zpl.io/258jB1J) | [Light](https://zpl.io/boz37mE)
**Hover** [Dark](https://zpl.io/2Glq0lJ) | [Light](https://zpl.io/Vxd3WNx)

## UI review
_remove this section once everything is checked_
- [ ] UI doesn't already have a existing component.
- [x] Name display in Zeplin is the same as the one in the issue (see below).
- [x] Data can be display like in the UI (see notion).
- [x] A link to this issue in the zeplin object

## Implement Component
- [x] Create story with storybook
- [x] Connect component to Zeplin with zeplin-connect

## Description

- name: MovieCardComponent < movie-card >
- lib/app: UI

## Type
- [ ] **Layout**: _Structure a page with content projection (ex: MovieView)._
- [ ] **Page**: _Loaded by the router. Usually used in an app (ex: CatalogDashboardMovieView)._
- [x] **Component**: _Structure a piece of data in the page (ex: MovieTable)._
- [ ] **Display**: _Render data in a page. Can use a component-type (ex: MovieMain, MovieBudget)._
- [ ] **Form**: _Get data from the user (ex: MovieFormBudget)._

### Input
_can be data (movie, distribution right, ...), or UI related (dense, appearance)_
- [x] movie
- [ ] feature size (depending on how many data are displayed with | between them)
- [x] card size (large, medium, small)
### Data view
_data displayed in the UI, derived from the inputs (ex: **title**: movie.main.title.international)
- [x] Title film : movie.main.title.international
- [x] Directors : movie.main.directors.firstName & lastName
- [x] Feature : movie.main.genres[] & movie.main.productionYear & movie.main.totalRunTime
- [ ] preference of user % (not implemented yet)
- [ ] on hover, link to the movie page

## Where is it used
- home page of marketplace ([link to Zeplin](https://app.zeplin.io/project/5e82f6ca1c987015ec21c1d7/screen/5e830f0a69814511d8862b8b))

**Comment by Jackseed** [comment]
![image](https://user-images.githubusercontent.com/14964443/78028993-2dc28980-7360-11ea-927b-3d7dccbb2515.png)

**Comment by vwmathilde** [comment]
@Mussuranae can you review this plz ?

**Comment by Mussuranae** [comment]
I can do everything for you ! <3
@vwmathilde The title is always the international title right ? Is it possible to rename it in International title instead of "film title" if it is the case for every movie-card ?

**Comment by vwmathilde** [comment]
@Mussuranae 

- Yes, it's an international title. 
- I can't have the same for all of this in sketch, sorry :(
- Ok, I gonna put the ratio on description for all of pictures.

**Comment by Mussuranae** [comment]
Thank you !
