### ISSUE TITLE
[Component] movie-slider

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2357]
# Component

[Dark](https://app.zeplin.io/styleguide/5e0f7156cf562c1cb478f0f5/components?seid=5e8466c4dd077544c2a20867)
[Light](https://app.zeplin.io/styleguide/5e05fbe68925c3177b82ebd1/components?seid=5e846604489a7f48bfd5f3d8)

## UI review
_remove this section once everything is checked_
- [x] UI doesn't already have a existing component.
- [x] Name display in Zeplin is the same as the one in the issue (see below).
- [x] Data can be display like in the UI (see notion).
- [x] A link to this issue in the zeplin object

## Implement Component
- [x] Create story with storybook
- [x] Connect component to Zeplin with zeplin-connect

## Description

- name: SliderComponent - "movie-slider"
- lib/app: Movie

## Type
- [ ] **Layout**: _Structure a page with content projection (ex: MovieView)._
- [ ] **Page**: _Loaded by the router. Usually used in an app (ex: CatalogDashboardMovieView)._
- [x] **Component**: _Structure a piece of data in the page (ex: MovieTable)._
- [ ] **Display**: _Render data in a page. Can use a component-type (ex: MovieMain, MovieBudget)._
- [ ] **Form**: _Get data from the user (ex: MovieFormBudget)._

### Input
_can be data (movie, distribution right, ...), or UI related (dense, appearance)_
- [ ] movie

### Data view
_data displayed in the UI, derived from the inputs (ex: **title**: movie.main.title.international)
- [ ] title: movie.main.titles
- [ ] director: movie.main.directors[] 
- [ ] feature: ....
- [ ] description: movie...logline

## Where is it used
-links and snapshots where the component is used_

**Comment by vwmathilde** [comment]
@Maxstgt Can you review this plz ?

**Comment by Maxstgt** [comment]
@vwmathilde can you rename the component to `movie-slider` ? Because slider-home points to a specific page and we will use this component everywhere we want to have a slider that displays a movie.

**Comment by Maxstgt** [comment]
@vwmathilde Where is the part that is reusable and where is the part that is specific to an app?

**Comment by vwmathilde** [comment]
@Maxstgt I don't know yet. it will depend on what we will need in the other marketplace. See it with @2amarkina

**Comment by Maxstgt** [comment]
@vwmathilde also pls update the name in zepplin, if possible, not only here int he issue

**Comment by vwmathilde** [comment]
@Maxstgt Done !

**Comment by Maxstgt** [comment]
@2amarkina

**Comment by 2amarkina** [comment]
Still working on it. 

Got a proposition for the "homepage-slider" 
<img width="616" alt="Снимок экрана 2020-04-06 в 13 47 23" src="https://user-images.githubusercontent.com/55499036/78555389-34904700-780d-11ea-89ba-b10f16cec919.png">

1. New to {App name} - shows the recently added titles
2. International title 
3. Contenu est displayed like this : 
4. Director and Genre - always displayed  if production status is “completed” -> show “production year”, “runtime”; else -> show only “production status” 
5. Two CTA buttons (one is principal for the direct action, the other is secondary and leads to the movie page)
6. Logline is limited in signs. (P.S. logline is not Synopsis, which can be really long)
7. Percentage info with search preferences (AC) OR minimum ticket (MF)  + add to wishlist. If search preferences are not set up -> they are not displayed
8. Navigation type slider 
9. Background - Vient de Banner image / Movie Tunnel -  / Ratio 16:9 / Format .jpg / .png

**Comment by 2amarkina** [comment]
header-movie-page 

In red - parts that are sensibles to be changed
<img width="597" alt="Снимок экрана 2020-04-06 в 14 03 05" src="https://user-images.githubusercontent.com/55499036/78556485-5ab6e680-780f-11ea-8130-4a212526c089.png">

**Comment by GrandSchtroumpf** [comment]
@2amarkina I think it would be good to give a name to the red block. Like "call to action" or something like that. It's a good way to describe what we should put inside, and stay consistant across the apps.

**Comment by 2amarkina** [comment]
UPDATE : 

Three cases for homepage slider, where CTA is always a button.
1. HOMESLIDER - CASE 1 - GENERAL
 <img width="715" alt="HOMESLIDER - CASE 1 - GENERAL" src="https://user-images.githubusercontent.com/55499036/78877235-d2278880-7a50-11ea-802a-5582842124c7.png">

2. HOMESLIDER - CASE 2 - ESTIMATED RUNTIME
<img width="783" alt="HOMESLIDER - CASE 2 - ESTIMATED RUNTIME" src="https://user-images.githubusercontent.com/55499036/78877339-fd11dc80-7a50-11ea-9735-82b33c11e5a7.png">

3. HOMESLIDER - CASE 3 - TOO MUCH INFORMATION 
<img width="784" alt="HOMESLIDER - CASE 3 - TOO MUCH INFORMATION " src="https://user-images.githubusercontent.com/55499036/78877387-0dc25280-7a51-11ea-9fb4-efd5261dac47.png">


Banner for the movie page seems to be the same, but still some important elements are changed : 

BANNER MOVIEPAGE - CASE 1 - GENERAL 
<img width="773" alt="BANNER MOVIEPAGE - CASE 1 - GENERAL" src="https://user-images.githubusercontent.com/55499036/78877488-39ddd380-7a51-11ea-9518-314dadc25bbd.png">

**Comment by Maxstgt** [comment]
@2amarkina if you got any information about the header, pls put it in this issue: https://github.com/blockframes/blockframes/issues/2352 . This issue is only about the slider. If we are mixing that up, we will have later complications to distinguish between them and what has been done and what not. 

About the search preferences, do we got any new about that? Where it comes from?

**Comment by Maxstgt** [comment]
> header-movie-page
> 
> In red - parts that are sensibles to be changed
> <img alt="Снимок экрана 2020-04-06 в 14 03 05" width="597" src="https://user-images.githubusercontent.com/55499036/78556485-5ab6e680-780f-11ea-8130-4a212526c089.png">
the movie header here as arrows, which indicates that it is not a header, it is a slider

**Comment by GrandSchtroumpf** [comment]
@Maxstgt Don't look at the previous comments but only the latest from @2amarkina. She provided three views of the HomeSlider that should be enough to start. Also concerning the "BANNER MOVIEPAGE - CASE 1 - GENERAL" as you said it's for #2352 so don't look at it for this issue.

> About the search preferences, do we got any news about that? Where it comes from?

As you can see this part is inside a red square meaning that this depend on the app. In the code it should be a `<ng-content select="movie-slider-actions"></ng-content>`. Do the same for the CTA (call-to-action) zone : `<ng-content select="movie-slider-cta"></ng-content>`

**Comment by Maxstgt** [comment]
For this component I will create a second component in movie libs. So that we can have the underlaying `bf-slider` to serve the needs of marketplace/home page. And one component for the new design of the marketplace.

**Comment by GrandSchtroumpf** [comment]
I'm not sure to understand. You want a `movie-slider` & a `home-slider` ?
If so, I think this is not a good idea. Let's try to implement a  `movie-slider` in the home page instead.
The goal is to reuse the `movie-slider` as much as possible in every home page.
By following this format we could have an organization-slider, event-slider, ... for specific app.

**Comment by Maxstgt** [comment]
Sure thing. 
So right now we have the `bf-slider`. Right now in action on the develop branch on marketplace/home page.
But in the images stated above from Anastasiia, you got different informations then you got right now in the marketplace/home. Thats why I need to create a `movie-slider` which inputs different value in the `bf-slider` then it gets in the marketplace/home page.

**Comment by GrandSchtroumpf** [comment]
Ok, but the `movie-slider` is build on top of the `bf-slider` right ?

**Comment by Maxstgt** [comment]
yes

**Comment by Maxstgt** [comment]
yep, should be possible
