### ISSUE TITLE
[Component] Festival Card

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2364]
# Component

[Light](https://zpl.io/V47jpk4)
[Dark](https://zpl.io/VY4Dvwk)

## UI review
_remove this section once everything is checked_
- [x] UI doesn't already have a existing component.
- [x] Name display in Zeplin is the same as the one in the issue (see below).
- [x] Data can be display like in the UI (see notion).
- [x] A link to this issue in the zeplin object

## Implement Component
- [ ] Create story with storybook
- [ ] Connect component to Zeplin with zeplin-connect

## Description

- name: festival-card
- lib/app: ui (if static-model), movie (if specific to movie) @Mussuranae do you have any idea ?

## Type
- [ ] **Layout**: _Structure a page with content projection (ex: MovieView)._
- [ ] **Page**: _Loaded by the router. Usually used in an app (ex: CatalogDashboardMovieView)._
- [x] **Component**: _Structure a piece of data in the page (ex: MovieTable)._
- [ ] **Display**: _Render data in a page. Can use a component-type (ex: MovieMain, MovieBudget)._
- [ ] **Form**: _Get data from the user (ex: MovieFormBudget)._

### Input
_can be data (movie, distribution right, ...), or UI related (dense, appearance)_
- [ ] festival

### Data view
_data displayed in the UI, derived from the inputs (ex: **title**: movie.main.title.international)
- [ ] logo
- [ ] ...

## Where is it used
-links and snapshots where the component is used_
https://app.zeplin.io/project/5e82f6ca1c987015ec21c1d7/screen/5e860a3353d08246ce01c1d7

**Comment by GrandSchtroumpf** [comment]
@Mussuranae Where can I find the data of the festival ? Is it in the database or is it a static model ?

**Comment by fritzschoff** [comment]
@Mussuranae we need to answer the question first that @GrandSchtroumpf asked. Is there something in the datamodel for that?

**Comment by fritzschoff** [comment]
@fritzschoff pretty sure there are several components that are the same, check upon them!
