### ISSUE TITLE
[Component] Film Review Card

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2365]
# Component

[Light](https://zpl.io/VDZYrNv)
[Light without image](https://zpl.io/aRp6Dwe)
[Dark](https://zpl.io/2583KMr)
[Dark without image](https://zpl.io/bA1N9xq)

## UI review
_remove this section once everything is checked_
- [x] UI doesn't already have a existing component.
- [x] Name display in Zeplin is the same as the one in the issue (see below).
- [x] Data can be display like in the UI (see notion).
- [x] A link to this issue in the zeplin object

## Implement Component
- [ ] Create story with storybook
- [ ] Connect component to Zeplin with zeplin-connect

## Description

- name: movie-review-card
- lib/app: UI

Need to be created.

## Type
- [ ] **Layout**: _Structure a page with content projection (ex: MovieView)._
- [ ] **Page**: _Loaded by the router. Usually used in an app (ex: CatalogDashboardMovieView)._
- [x] **Component**: _Structure a piece of data in the page (ex: MovieTable)._
- [ ] **Display**: _Render data in a page. Can use a component-type (ex: MovieMain, MovieBudget)._
- [ ] **Form**: _Get data from the user (ex: MovieFormBudget)._

### Input
- [x] movie.movieReview

### Data view
_data displayed in the UI, derived from the inputs (ex: **title**: movie.main.title.international)
- [ ] movieReview.journalName (or logo if we have, but it will be for the future)
- [x] movieReview.criticQuote
- [ ] writer and date (need to be added in the code)
- [x] movieReview.revueLink

## Where is it used
- movie view, festivals and critics tab (marketplace for the moment) 
[Link to the page](https://app.zeplin.io/project/5e82f6ca1c987015ec21c1d7/screen/5e860a3353d08246ce01c1d7)

**Comment by Mussuranae** [comment]
I have a problem with the logo of the journal. Currently we haven't it in the database, and if we need it, won't it be difficult to get a good logo for EVERY journal that we could have in the DB ? I mean it will be very painful because there are too much journal for critics no ? And we can't let the user put a logo for the journal (same problem than festival logo).

**Comment by vwmathilde** [comment]
> I have a problem with the logo of the journal. Currently we haven't it in the database, and if we need it, won't it be difficult to get a good logo for EVERY journal that we could have in the DB ? I mean it will be very painful because there are too much journal for critics no ? And we can't let the user put a logo for the journal (same problem than festival logo).

@Mussuranae I add an other review card without image
https://zpl.io/aRp6Dwe
https://zpl.io/bA1N9xq
