### ISSUE TITLE
RGPD Updates (GDPR)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2403]
- [x] Design the data model
- [x] [Cookie banner](https://projects.invisionapp.com/d/main#/console/19607961/418968442/preview) > should disable the corresponding cookies when refused
- [x] [Privacy Policy page](https://projects.invisionapp.com/d/main#/console/19607961/418952854/preview) 
- [x] Tickbox on [create an account](https://projects.invisionapp.com/d/main?origin=v7#/console/19273040/403408476/preview?scrollOffset=0) + [identity page ](https://projects.invisionapp.com/d/main?origin=v7#/console/19273040/405393351/preview?scrollOffset=0)
- [x] [Market CGS](https://projects.invisionapp.com/d/main#/console/19607961/418938376/preview)
- [x] [Cookie settings](https://projects.invisionapp.com/d/main#/console/19607961/418991527/preview) > should disable the connected cookies when refused
- [x] Register IP address and date when user accept policy privacy
- [ ] Update privacy policy (ask @Jackseed)

**Comment by GrandSchtroumpf** [comment]
Work with @2amarkina to see how to use YandexMetrica.
Work with @stephanie-cascade8 to improve the UI of the cookie settings (maybe use a slider !)

**Comment by GrandSchtroumpf** [comment]
Footer: https://projects.invisionapp.com/d/main#/console/19607961/418968442/preview
Modal : https://projects.invisionapp.com/d/main#/console/19607961/418991527/preview
Profile config : https://projects.invisionapp.com/d/main#/console/19607961/420299224/preview

**Comment by RemcoSimonides** [comment]
@Jackseed 
Issue says
"Update privacy policy (ask @Jackseed)"
What was the update?

**Comment by Jackseed** [comment]
@RemcoSimonides > PM

**Comment by RemcoSimonides** [comment]
Reopened because there is one thing left to do ;)
Add this: https://projects.invisionapp.com/d/main#/console/19607961/420299224/preview

**Comment by Jackseed** [comment]
> Reopened because there is one thing left to do ;)
> Add this: https://projects.invisionapp.com/d/main#/console/19607961/420299224/preview

I created a [dedicated issue](https://github.com/blockframes/blockframes/issues/3935) so we close this one
