### ISSUE TITLE
[UI Design] Missing icons

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#2407]
**Goal**: We want to get rid of the dependance on material icons.

Some material icons that we are using in the apps are missing in Mathilde's icons library. Here is the list : 
- [theaters](https://material.io/resources/icons/?search=theaters&icon=launch&style=baseline)
- [launch](https://material.io/resources/icons/?search=launch&icon=launch&style=baseline)
- [lock](https://material.io/resources/icons/?search=lock&icon=lock&style=baseline)
- [attachment](https://material.io/resources/icons/?search=attachment&icon=attachment&style=baseline)
- [add_circle](https://material.io/resources/icons/?search=add_circle&icon=add_circle&style=baseline)

**Comment by vwmathilde** [comment]
I don't understand when you use "add_circle"

**Comment by GrandSchtroumpf** [comment]
In the movie tunnel it seems

**Comment by vwmathilde** [comment]
Can you send me a screenshoot plz ?
