### ISSUE TITLE
Use Guards to subscribe to Firestore

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#241]
Subscription to Firestore should be done with the guards instead of the service.

- [ ] movie
- [ ] stakeholder
- [ ] IP
- [ ] delivery
- [ ] organization (only active)
- [ ] auth (organization list)

**Comment by pldespaigne** [comment]
- [ ] notifications : see [here](https://github.com/blockframes/blockframes/blob/36ea6a5d802941abf87947d7686b12a69842a0de/libs/ui/src/lib/notification/%2Bstate/notification.service.ts#L20)

**Comment by Hugo-Hontans** [comment]
- [ ] stakeholders of delivery

**Comment by phpgeekfr** [comment]
- [ ] movie  [here](https://github.com/blockframes/blockframes/blob/36ea6a5d802941abf87947d7686b12a69842a0de/libs/movie/src/lib/movie/%2Bstate/movie.service.ts#L48) 
- [ ] auth (organization list)  :  [here](https://github.com/blockframes/blockframes/blob/36ea6a5d802941abf87947d7686b12a69842a0de/libs/organization/src/lib/%2Bstate/organization.service.ts#L20)

**Comment by pldespaigne** [comment]
- [ ] tempaltes in delivery list (@ioaNikas ?)
