### ISSUE TITLE
Notification && invitation models

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2433]
On draw.io :

**for notification, we have** 
userId String
organization: PublicOrg

**for invitation we have:**
orgId 
userId

But in practice:
**for notification, we have** 
user: publicUser
organization:  publicOrg

**for invitation we have:**
user: publicUser
organization:  publicOrg

My opinion is that we should not duplicate data and only use Ids to then fetch publicOrg or publicUser.
In any cases, draw.io should reflect what we have in production.

**Comment by ioaNikas** [comment]
@phpgeekfr @Mussuranae Take care about userId of notification : this property is used to tell that this notification is for this particular user. For exemple, a notification will be duplicated for each user of an organization.

In the other side, an invitation won't be suplicated and will be treated by only 1 person (a user when an organization invites him, an admin when an organization is invited to work on a document etc.)

**Comment by phpgeekfr** [comment]
I have spoken with Francois about this and we will stick with what is currently implemented.
Since Notification & Invitation are something not really persistent in time, we can use public Orgs & Users here. If the org name or user name change but not the one on the invitation or notification, it is not a big deal (il est beau mon lavabo).

@ioaNikas So we will keep userId and publicUser on notifications.

I updated draw.io to reflect current implementation so I'm closing this issue.
