### ISSUE TITLE
How to handle img links to banner and posters that were entered by user

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#2441]
We got a discussion going on about how to protect us from XSS if the user imports a movie and enters a link to his images and trailers. And we save it to our database and later we will display the images for instance in our app. Shouldn't we protect ourselves from XSS attacks? As stated in this article, Angular sanitizes all the value by default. Is that enough? [Article](https://netbasal.com/angular-2-security-the-domsanitizer-service-2202c83bd90)

![Screenshot from 2020-04-03 10-15-01](https://user-images.githubusercontent.com/39312833/78339215-69459980-7594-11ea-9765-d801518e66cb.png)

**Comment by Jackseed** [comment]
@lsenta any thoughts on this question?
