### ISSUE TITLE
[Component] person-card

### ISSUE THREAD

**Issue by vwmathilde** [blockframes/blockframes#2448]
# Component

/!\ Check the already existing components to be sure this one is not already implemented 

## UI review
_remove this section once everything is checked_
- [x] UI doesn't already have a existing component.
- [ ] Name display in Zeplin is the same as the one in the issue (see below).
- [ ] Data can be display like in the UI (see notion).
- [x] A link to this issue in the zeplin object

## Implement Component
- [ ] Create story with storybook
- [ ] Connect component to Zeplin with zeplin-connect

## Description

- name: PersonCardComponent - "person-card"
- lib/app: ui

## Type
- [ ] **Layout**: _Structure a page with content projection (ex: MovieView)._
- [ ] **Page**: _Loaded by the router. Usually used in an app (ex: CatalogDashboardMovieView)._
- [ ] **Component**: _Structure a piece of data in the page (ex: MovieTable)._
- [x] **Display**: _Render data in a page. Can use a component-type (ex: MovieMain, MovieBudget)._
- [ ] **Form**: _Get data from the user (ex: MovieFormBudget)._

### Input
_can be data (movie, distribution right, ...), or UI related (dense, appearance)_
- [ ] movie

### Data view
_data displayed in the UI, derived from the inputs (ex: **title**: movie.main.title.international)
- [ ] festivalPrizes: movie.festivalPrizes
- [ ] ...?
- [ ] ...?

## Where is it used
-links and snapshots where the component is used_
[Used in](https://zpl.io/aMGkg0K)
[Light](https://zpl.io/aXNDN1E)
[Dark](https://zpl.io/bzo5oLG)

**Comment by Maxstgt** [comment]
@vwmathilde please name the component person-card in zepplin, remove the cast suffix

**Comment by Maxstgt** [comment]
@2amarkina is there something specific for some apps?

**Comment by 2amarkina** [comment]
@Maxstgt  Normally "person card" if always common for the all applications

**Comment by vwmathilde** [comment]
@Maxstgt Sorry I can't. I need to have different status name in my library. So, like @GrandSchtroumpf advised me, I used undescore after the principal component name
Component name : person-card
For me : I need to use _principal_cast
It's ok for you ?

**Comment by Maxstgt** [comment]
ah okay I see, yeah sure no problem!

**Comment by Maxstgt** [comment]
@2amarkina There are two other buttons which I can't see the state and can't see what data is being used there but if you can answer that question this component is ready to go!

**Comment by fritzschoff** [comment]
@stephanie-cascade8 can you have a look here and tell me the different states of this component? Also we don't have the festival prize in our database atm, is that a problem?

**Comment by fritzschoff** [comment]
@GrandSchtroumpf did you already did this component when you created the new movie view layout? I thought, I saw something in the last standup?

**Comment by GrandSchtroumpf** [comment]
Yes it's called `credit-card`, because it only applies for credit, and because it's funny :)
