### ISSUE TITLE
Remove link tag for google mat icons

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#2450]
remove all the `<link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined" rel="stylesheet">`
since we dont need them anymore, cause we are using mathildes svg icons.

**Comment by Jackseed** [comment]
Looks right to me, @GrandSchtroumpf ?

**Comment by GrandSchtroumpf** [comment]
Should be good now. A quick search on "<mat-icon>" should show of some still remain.
