### ISSUE TITLE
Switch back to angularFire ref.getMetadata() when bug is fixed on AngularFire lib

### ISSUE THREAD

**Issue by ioaNikas** [blockframes/blockframes#2451]
Since `getMetadata()` from `AngularFireStorageReference` doesn't seem to work as intended, we use classic firebase storage reference to get the metadata.

We opened an issue about this bug on AngularFire official repo :
https://github.com/angular/angularfire/issues/2375

**Comment by fritzschoff** [comment]
will get resolved by #3091
