### ISSUE TITLE
[Festival app] decision on screening flow

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2460]
Commented some code about sharing private screening URL because we need to wait for the true screening flow.

**Comment by phpgeekfr** [comment]
Reopened it because I need to clean comments I put on code for preparing this issue.
@GrandSchtroumpf @Jackseed Can you explain me the choosen flow ?

**Comment by phpgeekfr** [comment]
Same question for #2291

**Comment by Jackseed** [comment]
@phpgeekfr the screening flow is the following:
- for now, every event will be private (public being more difficult than forecast) 
1. Sales agent creates an event from the event form 
2. He adds guests to the event from the form 
3. The guests receive an invitation (both mail + in-app invites)
4. If they accept, they are whitelisted
5. The event takes place on the eventId/session page
6. Only whitelist guests can join the meeting
7. Re screenings, the session page is additionally accessible within the time period of the event only
So regarding private urls, you can share it but you won't access it if you're not whitelisted (+ within the event timeframe if screening session)
