### ISSUE TITLE
Handle created invitation to event on the backend side

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2461]
in `apps/backend-functions/src/invitation.ts` : update `onInvitationWrite` write to handle new type "event".

 * If we have an user or an org we can create a notification.
 * If we have an email, the function will send an email.
 * If user created an account, we will then be able to replace email by user

- [ ] @Mussuranae implement mails in `apps/backend-functions/src/internals/invitations/events.ts`
- [x] @phpgeekfr check `#2461` in code
- [x] @phpgeekfr deploy new functions and test the whole invitation/notifications flow.
- [x] @phpgeekfr implement cron backend function

**Comment by Mussuranae** [comment]
@Jackseed I think about how I will do the email function, but I will need a template for the mail, have you a little template for me to begin the work and test the function ?
