### ISSUE TITLE
Create light/heavy versions for the org page

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2467]
Create a "light version" of the org page, for the first connection
Fields : 
- Company information 
   * Company Name
   * Email Address
   * Phone Number
   * Website
   * Company Activity (dropdown)
   * Company Description (open text)
   * Fiscal Identification Number
- Address
   * Street
   * City
   * Zip Code
   * Country
- Logo 
    (Upload logo)

"Heavy version" once connected : 
Light version + 
- Bank information (as is)

**Comment by maltmayer** [comment]
@GrandSchtroumpf

**Comment by phpgeekfr** [comment]
@Jackseed can we close this?

**Comment by Jackseed** [comment]
Yep that's outdated
