### ISSUE TITLE
[Release 1.3] Permission denied on movie form

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2472]
Users tested: drew.bradley@santiago-group.fake.cascade8.com & sarah.gregory@turner-gray.fake.cascade8.com
Title: Teddy
Bug description: On the movie form, I tried to update a field (director filmography) and got Permission denied when I save or quit. I can't leave the page anymore. 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/c9de0e3b-fb7d-49a0-b3b8-57e6943afa74)

**Comment by ioaNikas** [comment]
Bug is due to the lack of permission document corresponding of this movie. It's not an excepected behavior since every movie/contract should have a corresponding permission document for each organization working on it.
