### ISSUE TITLE
Front loading data process

### ISSUE THREAD

**Issue by Hugo-Hontans** [blockframes/blockframes#2496]
Some guards use the `@CollectionGuardConfig({ awaitSync: true })`. This can be an issue when we navigate between components on routes that use the same guard. For example this creates flash (the same page is reloaded before navigate) when we jump from one route to another.
To fix it, the solution is to manage the loading of data inside the component (not inside the guard) and past the `awaitSync` to `false`. For example we can use the `selectLoading` of akita. But we have to find the good process so as not to create differences between the pages of the app.
- We can wait the entire data before display the page. (can break the animation)
- We can display directly the page and load the data when it arrives (an empty table can be displayed before being filled for example)
- We may not want to manage tables in the same way as cards or lists

**Comment by Jackseed** [comment]
@2amarkina or @GrandSchtroumpf any advice on this ? 
I would say that we can stick with the behavior we have on the statistics component: loading the shell component when the user arrives and adding a spinner while the data is being loaded.

**Comment by GrandSchtroumpf** [comment]
From the UX articles I've read about loading, all of them recommended to have a "loading in place" by displaying the shell first with some loading indication where data should be.
But we cannot just put a spinner everywhere there is a data missing as it would create a surcharge of information + reduce the perf because of heavy animation.
We should find something more subtle & light. [Skeleton Screen](https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a) could be one option, by placing geometrical shapes in place of the incoming data.

**Comment by Jackseed** [comment]
@2amarkina that's something worth thinking about it, we still face that issue on so many pages. Having a good structure on loading states becomes more and more urgent

**Comment by 2amarkina** [comment]
Work in progress here : https://www.figma.com/file/8a63I0IuHPtHKW2G14vg86/Loading-Cases-and-Rules?node-id=0%3A1

**Comment by Jackseed** [comment]
Looks good to me but don't know if that's acceptable on the technical side @GrandSchtroumpf ?

**Comment by Jackseed** [comment]
@2amarkina I discussed your propositions with @GrandSchtroumpf and some of it could make the performances slower (blurring images for example) and skeletons look like a good amount of work. 
What it appears from our discussion is that before taking any decision we need a better overview of what's already there. Could you make a summary of what content is displayed on each page and how the loading is handled please? 

From there we should be able to take decision on a page per page basis
