### ISSUE TITLE
Suggestion for "Sales Agents" filter on Archipel Market Library page

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2499]
Would it be possible to have [that](https://material.angular.io/components/select/overview#multiple-selection) for the « Sales agents » filter on Archipel Market Library page ? instead of using chips like for other filters. 
(if possible : with an « All » option, to check everything. That would automatically get unchecked when the user unchecks a box)
![image](https://user-images.githubusercontent.com/55785823/78903923-1b410200-7a7c-11ea-83fb-a24132be57a7.png)

**Comment by maltmayer** [comment]
@pldespaigne désolée je n'arrive pas à t'assigner alors je te mentionne ;)

**Comment by fritzschoff** [comment]
new design was implemented for the title layout page
