### ISSUE TITLE
scroll to top in mat-sivenav-content

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#2502]
since we layouting  all of our apps in a mat sidenav the router cant set the scrollY position to 0 because the content you want to be on top is the content of the mat side nav but not the mat sidenav itself. 
We have to investigate how we want to restore the scroll position.
- Either we can manage to inject the DOCUMENT element in the VIEWPORTSCOLLER from angular and say, this is what we care about for scrolling.
- Or we manage do notify the router from the component level and say "hey, this is the main content you want to care about"
There are also some helpful links to github issues about that in this issue ref #2123 
Since we are before release 1.3 there is no time to investigate but should be done in the future to handle this scroll position issue.

**Comment by GrandSchtroumpf** [comment]
I think the current workaround is enough for us for now. We could tune it a little to keep memory of the previous page location. But it shouldn't take more than 1-2h of work. Else it does not worth it.
