### ISSUE TITLE
AdminModule interferes routing 

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#2508]
For instance your are a blockframes admin and you want to to access some other pages directly from the tunnel, let say: `dashboard/tunnel/contract/success` this is not possible because the admin panel router module will catch that route requests and looks for his matching routes. 
- First, he shouldn't be responsible for that because he is not getting called .
- Second, the context of the url tree is different. We are not on an admin route we are in a dashboard route.
If you try to access that route without an admin account, you just get a firebase permission error.
That is all I could find out about this weird behaviour.

**Comment by Jackseed** [comment]
I think this is a discussion to have with @phpgeekfr

**Comment by Mussuranae** [comment]
![error-contracts-success](https://user-images.githubusercontent.com/48033264/79590017-a3f01b80-80d6-11ea-900e-c71906c88e3f.png)
This is the error encountered during the process.

So I worked on this, and I manged to do 4 routes that all worked well :
`dahsboard/tunnel/contract/contractId/sale/summary/success`
`dahsboard/tunnel/contract/contractId/success`
`dahsboard/tunnel/contract/success`
`dashboard/tunnel/contract/contractId/sale/success`

I think the `success` in the error is considered as an contractId, so maybe the module of the `success.component` wasn't exported correctly. And, I don't know if it is possible, but I suppose that like no route matched the `contract-tunnel-routing.module`, it maybe saw if it could find something in the `admin-panel.module` ?

**Comment by phpgeekfr** [comment]
Is this still an issue ? If so @fritzschoff can you explain again ?
I did not found why admin panel could interfere in this and the route `dashboard/tunnel/contract/success` does not exists (and indeed `success` is interpreted as a contractId).  The only route I found with `success` in it is  : `/c/o/marketplace/tunnel/contract/CONTRACTID/mandate/summary/success`

**Comment by fritzschoff** [comment]
@Mussuranae was working on it the last time. She can give you more information. She shifted the routes around.

**Comment by phpgeekfr** [comment]
closing this since admin panel (crm) have been moved to a standalone app
