### ISSUE TITLE
Nominative stats on Festival

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2524]
On the app festival, the sellers will know who went to the the screening. 
We need to first get the following data:
- [x] What users went on the screening page
- [x] How long did they stay on the page
Then implement the statistics on the screening dashboard page ([UI](https://projects.invisionapp.com/d/main#/console/19607961/411890750/preview):
- [ ] Use the same components as catalog dashboard for the cumulated stats
- [x] Use the re-usable table to include the nominative stats

=> Average time on page: check with the JW Player

**Comment by Hugo-Hontans** [comment]
I used a simple mat-card to show for the cumulated stats because we don't need a graphic but just show the number of differents views

**Comment by Hugo-Hontans** [comment]
In the table I just show the first name, last name and email of different users (not attented and watch time)
