### ISSUE TITLE
[UI] Design last V1 & V2 Festival functionnalities

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2527]
Pages à finir dans l'ordre de priorité:
V0
- [x] Updater les écrans existants en suivant les commentaires (en jaune quand validé)
- [x] Ajouter les écrans d'import excel de Content (sans doute quelques remaniements de texte mais je te les ferais en commentaires dessus)

V1
- [x] Landing page, reprendre celle de Content en mettant à jour avec les commentaires de Marie: https://docs.google.com/document/d/1tv0r9-hZ3pPClroYpoGsfUOKjHHd2hhQAo4MbPsQ-Jo/edit
Si possible, tenter une nouvelle gamme de couleur pour la bannière qui différencierait de Content
- [x] Copier la page d'accueil de Content vers Market
- [x] Ajouter la liste des Reserved territories sur la page film en ajoutant un onglet "Available territories" et la carte du monde en 2 couleurs: territoires vendus ("Sold territories") et territoires disponibles ("Available territories)
- [x] Ajouter la page tous les films de Content sur Market:
             - renommer "Library" en "Line-up"
             - si possible sur les nouvelles movie cards: ajouter le nom du vendeur sur la carte
             - sur les filtres: 
             - retirer le titre "Title metadata"
             - retirer toute la partie Avails du bas
             - ajouter un filtre "Sales Agents" tout en haut avec liste autocomplete
- [x] Page avec la liste de toutes projections rassemblées par jour + ajouter un bandeau similaire à ce que t'avais fait sur la page film > 
titre: Showtimes
sous titre: Look at all the screenings going on
bouton "Go"
- [x] Proposition fifou de salle de cinéma

V2
- [ ] Flow 2FA:
             - Ajouter une page (qui viendra après la login page) avec:
titre "Two-factor Authentication"
sous-titre "Enter the 6-digit code from your authentication app". 
un form pour remplir 6 chiffres
un message "Problem with your authentication app? Contact us" avec un lien sur contact us
Bouton "Validate" (grisé tant qu'il n'y a pas les 6 chiffres)
             - Ajouter des onglets à la page profil (https://projects.invisionapp.com/d/main#/console/19273040/402393777/preview)
             - Le premier "Profile" avec les mêmes infos qu'actuellement
             - Le second "Security avec  un nouvel encart "Mobile Verification":
sous titre "Verify your mobile to enable two-factor authentication."
form pour ajouter un portable "Mobile Phone Number"
un bouton "Verify"
un autre form avec "Verification Code" 
un bouton "Validate"
             - Toujours dans l'onglet Security, sous Mobile Verification, un nouvel encart "Two-factor Authentication" avec un toggle "Disabled / Enabled"

**Comment by vwmathilde** [comment]
@Jackseed peux pas rajouter le nom du vendeur sur la carte désolé. Sinon il faut qu'il soit partout, sur toutes les cartes, sur toutes les applis.
