### ISSUE TITLE
Merge img[asset] & img[imgRef]

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#2528]
Currently there is two directive : 
- AssetDirective used for static images.
- ImageReference used for the images from firestorage.

It would be easier to have only one directive that would have either [asset] or [imgRef] : 
```typescript
@Directive({ selector: 'img[imgRef], img[asset]' })
```

**Comment by joanofdart** [comment]
We should do the same for backgroundRef and asset.
So as soon as this one is merged. I'll do the same :)
