### ISSUE TITLE
Firebase data location/region

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2531]
Because of the recent deploy issues we have this days, I checked the region from where the functions are hosted and I found it was from `us-central1` which is a bit weard since our `firestore` in located in europe.

Cloud Firestore : `eur3 (europe-west)`
Storage: I have one bucket `us` and one `eu`
Hosting: don't know
Functions: `us-central1`

All data should be handled in Europe for performances and legal issues.

**Comment by george43g** [comment]
hosting is worldwide via fastly CDN so no need to worry about that. Main challenge is functions. Storage buckets can be copied over with gsutil, then bucketnames can be updated in next release (could use a function to sync resources in the meantime)

**Comment by george43g** [comment]
the plan is to make a PR

- [ ] - integrate PR that launches new functions in the correct region
- [ ] - ensure it is released and new functions are deployed, WITHOUT deleting the old functions
- [ ] - integrate another PR where the front-end points to the newly created functions
- [ ] - release

**Comment by george43g** [comment]
https://github.com/blockframes/blockframes/pull/3839

**Comment by george43g** [comment]
https://github.com/blockframes/blockframes/pull/3839

**Comment by george43g** [comment]
- [ ] look at moving storage

**Comment by phpgeekfr** [comment]
- [ ]  If I visit https://catalog-blockframes-bruce.web.app/admin/data/restore I get redirected to https://us-central1-blockframes-bruce.cloudfunctions.net/admin/admin/data/restore
