### ISSUE TITLE
Implement a test coverage tool

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2537]
[SonarQube](https://www.sonarqube.org/) looks good, the objective is to raise more stats about our test coverage so we are not blind anymore on what's tested and what's not. 
Also can motivate to test more by having concrete results when writing tests.

**Comment by Jackseed** [comment]
@xmano what do you think? would it be useful to have a test coverage tool?

**Comment by xmano** [comment]
I had a quick look. It appears that SonarQube is a code analysis tool and scan the code for issues / code smells. This certainly can help us with some feedback about potential issues.

While we can potentially use this, there are 2 more priority items to do - improve our Lint process by effect TS code and second integrate Sentry into our workflow more effectively. This will yield immediate results as these tools are already integrated in our workspaces.

If you are looking at test coverage then we can integrate Mochawesome into our UT/E2E Tests.

**Comment by Jackseed** [comment]
@xmano thanks for the feedback, I Icebox this issue and we'll discuss that after the 2 priorities you mentioned. Could you open dedicated issues for lint & sentry so we link it to this one?

**Comment by xmano** [comment]
For Unit Test there are some changes planned. Will check on the impact and see if we can improve it further. I will file an issue after that.

For Sentry see this:
https://github.com/blockframes/blockframes/issues/4014

**Comment by phpgeekfr** [comment]
@GrandSchtroumpf suggested that it could be done by CI itself maybe
