### ISSUE TITLE
Correct mistake on Archipel Content Marketplace : empty cart

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2550]
- [ ] Correct "You have not yet selected any titles" to "You have no title in your selection."
- [ ] Change this sentence: "Do you need help ? Explore our FAQ page or chat with us." There is no FAQ + put a clickable link on "chat with us"
![image](https://user-images.githubusercontent.com/55785823/79473692-ca925180-8005-11ea-9ea0-f9e029288167.png)

**Comment by fritzschoff** [comment]
was resolved
