### ISSUE TITLE
Upgrade Algolia to v4

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#2554]
Algolia just migrate it's api from v3 to v4 introducing some breaking changes.
It would be wise to migrate our code to v4 since we are not (yet) heavily relying on Algolia.

**Comment by fritzschoff** [comment]
@phpgeekfr I assigned you, because this could be something for the sanity team?

**Comment by fritzschoff** [comment]
watch out. Angular webpack config points to node js modules if you upgrade this package to v4. You will need to find a workaround

**Comment by pldespaigne** [comment]
I guess it's too late now, we are using algolia a lot & everywhere
