### ISSUE TITLE
Implement avails filter on Algolia

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2562]
## UI
[Invision](https://projects.invisionapp.com/d/main#/console/19607961/413928510/preview)

### Festival
Festival has simpler avails than Content: we only take into account Territories. 
Cascade8 don't have rights on Festival films, we only use them for filtering. 
There is only one contract by film:
- A mandate between Sales agent & producer 
One distribution right is attached to the film + contract. It gives us the available territories on the film **by doing the operation `territories` - `excluded territories`**

The filter works like this:
1. A buyer enters a country on the chips autocomplete input (e.g. France)
2. The filter check the distribution right on each film, it excludes all the films that don't have the territory from the user input in their territory available (= `territories` - `excluded territories`) 
3. It displays the remaining films

### Content
We need to update Content avails filters so they use Algolia on the `/search` page like the other filters. 
Here is described the filter behavior wanted #1743 
Be sure to use territories such as described above i.e. territories to check = `territories` - `excluded territories` on distribution rights

### Festival
- [ ] Add `Distribution Rights` & `Contracts` in Algolia
- [ ] Recalculate territories available by doing `territories` - `excluded territories` from distribution rights **(only for Festival app)**
- [ ] Include the "Available Territory" on the Festival `/title` page (same as Territory in the avails section on Content)
- [ ] Update the territory filter so it works with Algolia, following the steps above
- [ ] Create a unit test to check if the filter works (@Jackseed will give you the dataset if a firebase db is needed) 
### Content
- [ ] Implement the avails filter using Algolia
- [ ] Same behavior as #1743 
- [ ] Create unit tests to check if filters work (@Jackseed will give you the dataset if a firebase db is needed)

**Comment by Jackseed** [comment]
@lsenta made a test repo on that

**Comment by pldespaigne** [comment]
Closing, fell free to reopen if the issue is still on the roadmap

**Comment by Jackseed** [comment]
Oh yeah it is and it was hard to spec that one so let's keep it!

**Comment by Jackseed** [comment]
I de-assign you let's wait for catalog rebirth

**Comment by Jackseed** [comment]
Not wanted anymore > close
