### ISSUE TITLE
Redirection Problem (Archipel Content marketplace notification)

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2574]
- [ ] When I click on my notifications and then "Go to document" (which, btw, I don't understand what this is supposed to be), I get redirected to the landing page https://archipelcontent.com/catalog/
![image](https://user-images.githubusercontent.com/55785823/79848699-b82b6580-83c1-11ea-8de7-41862561ba95.png)

**Comment by Jackseed** [comment]
@maltmayer did you try this being admin ? It looks like a permission issue

**Comment by maltmayer** [comment]
I am admin

**Comment by fritzschoff** [comment]
@RemcoSimonides can you have a look? and close if this is depreciated

**Comment by RemcoSimonides** [comment]
Pop up is removed so it's deprecated

**Comment by fritzschoff** [comment]
thanks
