### ISSUE TITLE
Better title-filter nesting

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#2576]
Right now title-filter only used ng-template for inserting filter, it's good enough but there probably a better way by using more nested levels of components.

like that for example
```html
<title-filter>
  <filter-section>
    <filter-section-label>Title Metadata</filter-section-label>
    <filter>
      <filter-label>Sales Agents</filter-label>
      <filter-content>
        <algolia-chips-autocomplete ... />
      </filter-content>
    </filter>
   </filter-section>
</title-filter>
```

**Comment by fritzschoff** [comment]
@pldespaigne can be closed?

**Comment by phpgeekfr** [comment]
@fritzschoff still a lot of comments `<!-- TODO issue#2576 -->` in code. Do we clean comments or does this mean that issue should be reopened ?

**Comment by fritzschoff** [comment]
yes lets remove it

**Comment by fritzschoff** [comment]
I will do a PR for it
