### ISSUE TITLE
Update on movie pre-defined list

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2581]
New list:

https://docs.google.com/spreadsheets/d/1_i3aphiAxkdtUkjDfM3w1Y0kMuGfSW2G/edit#gid=1565367341

red: to add,
black: to remove

**Comment by Jackseed** [comment]
@phpgeekfr this has been done, right?

**Comment by phpgeekfr** [comment]
I don't think so but import will be updated in #3816 . Closing in favor of #3816
