### ISSUE TITLE
Remove duplicate between MovieModel and staticModels

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#2582]
A lot of data is shared between the MovieModel and the staticModels.
In the long run it will become difficult to maintain.

- [ ] choose either one to be the only source of truth
- [ ] refactor the code accordingly

**Comment by Mussuranae** [comment]
There is now a `staticConsts.ts` where all static constants can be moved. We can rework all static models that have only slug and label choice to const as well.

**Comment by GrandSchtroumpf** [comment]
We will use only key / value structures : 
- [ ] Create a key/value pair for each slug/label
- [ ] Update `toLabel` pipe with the new values
- [ ] Change every `translateSlug` to `toLabel`
- [ ] Update the FormStaticValue (#3478 )
- [ ] Create a key/value pair for { [country]: ISO }

Clean current code
- [ ] Remove static model
- [ ] Remove static model specific code in `chips-autocomplete`, `static-select`, ...

**Comment by phpgeekfr** [comment]
@Mussuranae Can you check if we can close this issue ?
