### ISSUE TITLE
Upload heavy files (films) on Firestorage

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2586]
- [x] remove the old `hostedVideo` key + new movie video data model + corresponding migration
- [x] Add a way to upload videos **& screening** to a movie through the admin panel
- [x] Upload video should go to the private folder of the corresponding movie
- [x] refactor the `getPrivateVideo` backend function to handle any kind of video and not only the screening
- [x] refactor the `uploadVideoToJWPlaye`r backend function to handle the new file architecture
- [x] Use the backend function created by @pldespaigne to upload the video from firebase storage to JW Player
- [ ] check for #2586 in code
- [x] wait for `jwPlayer` response for api_key error

link to master issue #3639

**Comment by Jackseed** [comment]
UX work to make the user wait @2amarkina

**Comment by phpgeekfr** [comment]
can we close this issue ?

**Comment by pldespaigne** [comment]
We don't have neither movie upload nor storage rules.
But maybe those 2 things are in others issues ?

**Comment by Jackseed** [comment]
This issue is still to be done but it will be integrated with @2amarkina's work on #2832 so we wait for wireframes before implementing the upload

**Comment by Jackseed** [comment]
@phpgeekfr should give the right path to upload the movie on firebase

**Comment by pldespaigne** [comment]
@Jackseed @2amarkina where should I put the upload in the front-end ?

**Comment by Jackseed** [comment]
@pldespaigne it goes on the dashboard movie view with a new tab, here is the corresponding [invision](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/418106483/preview?scrollOffset=7564)
(+ following pages)
Not sure it has been integrated into Zeplin.. @stephanie-cascade8 do you know ?
