### ISSUE TITLE
Movie Model - App access

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2591]
We need to differentiate movies from Content of those from Market with something like
```
appAccess: {
  catalog: boolean;
  festival: boolean;
}
```
- [x] Migration script for already existing films on Content (all the current movies can be tagged Content but need to be based on a list for future migrations, can't be by default)
- [x] Add this when creating a film on content or festival 
- [ ] Update the query so the films are loaded correctly

**Comment by phpgeekfr** [comment]
example: 
```
appAccess: {
  catalog {
    marketplace: true, 
    dashboard: false
  }
  festival {
    marketplace: true, 
    dashboard: false
  }
}
```
