### ISSUE TITLE
Archipel Content Debug

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2593]
- [x] Change prod Central org id (ask @Jackseed )
- [x] Change landing vimeo url (ask @Jackseed)
- [x] Title issue on homepage
![image](https://user-images.githubusercontent.com/14964443/79873246-2a627100-83e7-11ea-972b-2a905f450945.png)
- [ ] After org creation, add a "Go to Dashboard" or "Go to Marketplace" CTA button depending on the org access. Button must be disabled while org is not accepted

- [x] Avails search on title page: 
Got this message `Archipel Content got no mandate` on a movie when trying to look at avails on marketplace/movieId/view/avails.
I tried on 3 different movies with the parameters above and I'm pretty sure that we do have a mandate for this. Looks relative to the distribution rights migration
The movies were Felicita, A Perfect Enemy and Teddy
![image](https://user-images.githubusercontent.com/14964443/79873557-9218bc00-83e7-11ea-9186-4a8093528c55.png)

- [x] On org settings page got this error (not blocking)
error-logger.module.ts:15 Error: Uncaught (in promise): TypeError: Cannot read property 'label' of undefined
TypeError: Cannot read property 'label' of undefined
    at MatAutocomplete.FormCountryComponent.displayFn [as displayWith] (country.component.ts:32)

- [x] Update wishlist page, keep the message but should be a title and add a « Explore the Library » button that navigates to /search like no deals page
![image](https://user-images.githubusercontent.com/14964443/79873718-c0969700-83e7-11ea-9b05-79ad4aded812.png)
![image](https://user-images.githubusercontent.com/14964443/79873742-c5f3e180-83e7-11ea-9eb8-691971a8c433.png)

- [x]  Responsive: on marketplace title page force the card background of the buttons to stay full, put the whole card before Storyline Elements taking the whole height when the page is too small
![image](https://user-images.githubusercontent.com/14964443/79873766-d1470d00-83e7-11ea-917b-9db08fd85917.png)

- [x] Change « Sign in » in the button for « Log in »
![image](https://user-images.githubusercontent.com/14964443/79873778-d73cee00-83e7-11ea-930b-f76835f449f4.png)

- [x]  Add a capital letter to the status on the table dashboard/titles (e.g. « Accepted »)
￼![image](https://user-images.githubusercontent.com/14964443/79873801-defc9280-83e7-11ea-85b0-7a9d39caa176.png)

**Comment by Jackseed** [comment]
@fritzschoff 
1 minor correction after review, please add a h1 or h2 markup on the "Your wishlist is empty" message plz, same as the image below
![image (18)](https://user-images.githubusercontent.com/14964443/80385222-19fa3c80-88a6-11ea-8cc1-a0df35316b60.png)

**Comment by fritzschoff** [comment]
done, included in ref #2637
