### ISSUE TITLE
Reorganize storage to apply rules in the future

### ISSUE THREAD

**Issue by ioaNikas** [blockframes/blockframes#2600]
The project is growing big and we're going to need security on files in the storage.
Since storage rules behave like database rules, we need to have a structure and use ids to recognize ownership of files.

Right now, we have this chaotic architecture :
```
avatar/avatarFile
logo/logoFile
movies/bannerOrPosterOrSalesAgentLogoFile
poster/someUnusedPosterFile
```

To clean this mess, we need to switch to this kind of architecture :
```
users/:userId/avatar
orgs/:orgId/logo
movies/:movieId/posters/:lang
movies/:movieId/banners/:lang
movies/:movieId/trailers/...
```

Those folders are created when we upload a file to the storage, based on a path we give. For exemple :
```
this.storage.ref('folderName/fileName');
```

This will create a folder named `folderName` and have a file which name is `fileName`. To create a securized avatar file for a specific user, we can do the same :
```
this.storage.ref('avatars/this.authQuery.userId/userAvatarFileName');
```

Keep in mind that the reorganization of the storage means a complex migration script.

**Comment by Jackseed** [comment]
@Mussuranae @phpgeekfr can you have a look at Yohann's proposition? Any recommandation?

**Comment by phpgeekfr** [comment]
Seems a good Idea and a good way of organizing files. Go go !

**Comment by Mussuranae** [comment]
Looks muuuuuuch better than what we have right now. It will be simpler also for all developers to know where to find or to store pictures.

**Comment by pldespaigne** [comment]
UPDATE : Everything above is **outdated**

State of storage and rules is as follow :

- we have no rules at all for the storage : see #3188 
- every file is stored exactly as the same path as it's ref in the firestore
  - ex: `users/<ID>/avatar/original/myImage.webp` is linked in the db as `users/<ID>/avatar.original.ref`
   - ex: `movies/<ID>/promotionalElements.banner.media/original/myImage.webp` is linked in the db as `movies/<ID>/promotionalElements.banner.media.ref`

**Comment by GrandSchtroumpf** [comment]
Close in favor of https://github.com/blockframes/blockframes/issues/3188
