### ISSUE TITLE
Catalog e2e bugs

### ISSUE THREAD

**Issue by Hugo-Hontans** [blockframes/blockframes#2616]
- [x] `Cannot read property 'orgId' of null` in login page
- [ ] `Error: invitations doesn't exist` on movie-start-tunnel page
- [ ] `FirebaseError:[code-permissions=denied]: Missing or insufficient permissions` on Join Community Page ( when you choose Find or Create your organization
- [ ] `FirebaseError:[code-permissions=denied]: Missing or insufficient permissions` on marketplace/home and marketplace/search

**Comment by fritzschoff** [comment]
moved to ref#2617
