### ISSUE TITLE
[Component] screening (online and offline)

### ISSUE THREAD

**Issue by vwmathilde** [blockframes/blockframes#2635]
# Component

## UI review
_remove this section once everything is checked_
- [x] UI doesn't already have a existing component.
- [x] Name display in Zeplin is the same as the one in the issue (see below).
- [x] Data can be display like in the UI (see notion).
- [x] A link to this issue in the zeplin object

## Implement Component
- [ ] Create story with storybook
- [ ] Connect component to Zeplin with zeplin-connect
```
update the components.json in blockframes/.zeplin/
{
    "path": "libs/ui/src/lib/slider/slider.component.ts",
    "zeplinNames": [
        "component/slider/archipel_content/movie-slider"
    ]
}
path leads to the component.ts file and zeplinNames are the matching names from this component in zeplin. Can be multiple names if there are different states of this component.
```

## Description

- name: festival-screening
- lib/app: festival-app

## Type
- [ ] **Layout**: _Structure a page with content projection (ex: MovieView)._
- [x] **Page**: _Loaded by the router. Usually used in an app (ex: CatalogDashboardMovieView)._
- [ ] **Component**: _Structure a piece of data in the page (ex: MovieTable)._
- [ ] **Display**: _Render data in a page. Can use a component-type (ex: MovieMain, MovieBudget)._
- [ ] **Form**: _Get data from the user (ex: MovieFormBudget)._

### Input
_can be data (movie, distribution right, ...), or UI related (dense, appearance)_
- [ ] movie.main.directors
- [ ] movie.main.title.international
- [ ] org.avatar
- [ ] org.name

### Data view
_data displayed in the UI, derived from the inputs (ex: **title**: movie.main.title.international)
- [ ] service which calculates the remaining time? Needs to check for time zone from the user.
- [ ] check on init, what theme is selected to render background correct image.

## Where is it used
- [Dark Online](https://zpl.io/25BQ56J)
- [Dark Offline](https://zpl.io/2ZN6orq)
- [Light Online](https://zpl.io/2E0nYrg)
- [Light Offline](https://zpl.io/agJRMlQ)

**Comment by fritzschoff** [comment]
approved

**Comment by fritzschoff** [comment]
duplicate #2707
