### ISSUE TITLE
MAINTENANCE - Movie form

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2636]
### Main 
- [x] Festival section: Year should only accept 4 digits numbers (with error message « Please enter a 4 digit date (e.g. 2020)»
![image](https://user-images.githubusercontent.com/14964443/80373266-190cdf00-8895-11ea-8c63-9424ed4cc307.png)

### Credits
- [x] Production information section: Production Year - Same as above for festival
![image](https://user-images.githubusercontent.com/14964443/80373276-1c07cf80-8895-11ea-8429-a09773568374.png)

### Budget, Quotas, Critics
- [x] Qualifications section: remove Awarded Film & European Qualification from the list
![image](https://user-images.githubusercontent.com/14964443/80373327-32ae2680-8895-11ea-97db-34e3cb817e1c.png)
- [x] Film Reviews section: Revue link: only accepts url (if there is similar control) and add an error message « Please fill in a url (e.g. www.revue.com)»
![image](https://user-images.githubusercontent.com/14964443/80373415-54a7a900-8895-11ea-80b2-79a65aeb75e0.png)

### Technical Information
- [x] rename « Technical Information » (capital I) 
- [x] Format section: Color, add « Both » to the list with Color & Black & White
![image](https://user-images.githubusercontent.com/14964443/80373559-891b6500-8895-11ea-8e91-4a3197e1fe08.png)

- [x] Available Versions section: when a new language is added, don’t check « Original » by default, if possible leave the 4 tick boxes empty 
![image](https://user-images.githubusercontent.com/14964443/80373555-86b90b00-8895-11ea-8b51-69f3aa61d8a3.png)

### Promotional Images
- [x] When entering the page got the above non blocking error. Got the same error when click on « Add Still » button
``` 
error-logger.module.ts:15 TypeError: control.registerOnChange is not a function
-     at setUpModelChangePipeline (forms.js:2422)
-     at setUpControl (forms.js:2365)
-     at FormControlDirective.push.../../../node_modules/@angular/forms/__ivy_ngcc__/fesm5/forms.js.FormControlDirective.ngOnChanges (forms.js:5424)
-     at FormControlDirective.wrapOnChangesHook_inPreviousChangesStorage (core.js:19348)
-     at callHook (core.js:2919)
-     at callHooks (core.js:2885)
-     at executeInitAndCheckHooks (core.js:2838)
-     at selectIndexInternal (core.js:6221)
-     at ɵɵadvance (core.js:6194)
-     at MediaImageComponent_Template (template.html:30)
```
- [x] Movie poster image: rename just « Poster »
- [x] Seems to have a ratio error, the poster ratio from the cropper is horizontal not vertical, it’s not 120x160px like the text says
![image](https://user-images.githubusercontent.com/14964443/80373740-d3044b00-8895-11ea-8fa7-b04b4b626047.png)

### Files & Links
- [x] Rename « Files & Links » (capital L)
- [x] Rename « Presentation Deck » with capital D)
- [x] Upload box for Presentation deck & Scenario: if possible:
    - add a button delete the doc after upload (same as for Chain of Titles)
    - Add also the name of the file to give feedback to the user, here it’s saved but I can’t see it when I leave and come back to the form (do it also for Chain of Titles)
![image](https://user-images.githubusercontent.com/14964443/80375813-2deb7180-8899-11ea-812d-09e0284360ee.png)
![image](https://user-images.githubusercontent.com/14964443/80375860-39d73380-8899-11ea-9c86-1a86d35533fa.png)
- [x] File links: add a verifier that inputs are url (if possible)
![image](https://user-images.githubusercontent.com/14964443/80375945-5ecba680-8899-11ea-9aef-b1e84ac60a80.png)

### Summary page
- [x] When submitting the film « Submit to Archipel Content » button on Summary page got the snackbar message: « Fill all mandatory fields before submitting » and the below error in the console while I've filled all that I could
```
- summary.component.ts:47 (6) ["documents", "chainOfTitles", "0", "media", "1", "media"]
- (anonymous) @ summary.component.ts:47
- step @ summary-summary-module.js:331
- (anonymous) @ summary-summary-module.js:312
- (anonymous) @ summary-summary-module.js:306
- ZoneAwarePromise @ zone.js:915
- push../src/app/dashboard/movie-tunnel/summary/summary.component.ts.__awaiter @ summary-summary-module.js:302
- push../src/app/dashboard/movie-tunnel/summary/summary.component.ts.TunnelSummaryComponent.submit @ summary.component.ts:34
- TunnelSummaryComponent_Template_button_click_76_listener @ template.html:102
- executeListenerWithErrorHandling @ core.js:14820
- wrapListenerIn_markDirtyAndPreventDefault @ core.js:14855
- (anonymous) @ platform-browser.js:575
- ZoneDelegate.invokeTask @ zone.js:431
- onInvokeTask @ core.js:27859
- ZoneDelegate.invokeTask @ zone.js:430
- Zone.runTask @ zone.js:198
- ZoneTask.invokeTask @ zone.js:513
- invokeTask @ zone.js:1671
- globalZoneAwareCallback @ zone.js:1697
```
- [x] Release Media & Date buggy, they are filled in & saved but showed as missing in the summary page
![image](https://user-images.githubusercontent.com/14964443/80376075-95a1bc80-8899-11ea-80ca-2d0e81683932.png)
![image](https://user-images.githubusercontent.com/14964443/80376135-a94d2300-8899-11ea-803f-096e130e6a72.png)
![image](https://user-images.githubusercontent.com/14964443/80376147-ac481380-8899-11ea-997e-bfc53297483e.png)

- [x] Summary Credits / Producers we should use the label « Associate Producer » instead of « associate-producer » 
￼
![image](https://user-images.githubusercontent.com/14964443/80376209-c4b82e00-8899-11ea-8137-82995e894752.png)

- [x] Summary Credits Director of Photography: missing a whitespace before value
￼
![image](https://user-images.githubusercontent.com/14964443/80376219-c8e44b80-8899-11ea-87bc-f2073ef6f805.png)

- [x] Budget, Quota & Critics / Box Office: missing the « € » symbol , rename « Box Office » (capital O), use same text color for the box office country as the figures, and format the number, e.g. here should be €150.000 Algeria
￼
![image](https://user-images.githubusercontent.com/14964443/80376238-d26db380-8899-11ea-94f0-1276a8c72b6b.png)￼
![image](https://user-images.githubusercontent.com/14964443/80376245-d6013a80-8899-11ea-805d-3554d97d5c94.png)

- [x] Film review not display while it’s saved: 
![image](https://user-images.githubusercontent.com/14964443/80376257-d994c180-8899-11ea-8b93-a6b26481dfaf.png)
![image](https://user-images.githubusercontent.com/14964443/80376283-e0bbcf80-8899-11ea-8dda-37a6f3e39773.png)
![image](https://user-images.githubusercontent.com/14964443/80376291-e31e2980-8899-11ea-80be-43699d96b288.png)

- [x] Navbar typo « Summary & Submit »
￼
![image](https://user-images.githubusercontent.com/14964443/80376302-ea453780-8899-11ea-84ee-f6126dfa7c15.png)

- [x] Movie page / Details on Dashboard / Promotional Images: they are marked as missing while they are loaded and saved, show the original file name instead
![image](https://user-images.githubusercontent.com/14964443/80376322-ef09eb80-8899-11ea-9665-8ada5683688f.png)
![image](https://user-images.githubusercontent.com/14964443/80376339-f6c99000-8899-11ea-8206-20d314d38eef.png)
![image](https://user-images.githubusercontent.com/14964443/80376345-f9c48080-8899-11ea-9bd6-9d06fe5a07e8.png)

**Comment by fritzschoff** [comment]
All bugs related to images and storages have to wait. Permission denied error

**Comment by Jackseed** [comment]
- [ ] Still format is wrong, here it's the poster format that is used
![image (20)](https://user-images.githubusercontent.com/14964443/83240345-8adc8f00-a199-11ea-8e5e-11eaf023f3c2.png)

- [ ] Got an error message when trying to publish this film that has all the required fields
![image (37)](https://user-images.githubusercontent.com/14964443/83240463-b8c1d380-a199-11ea-95ca-8ee86ba9bfd6.png)
![image (36)](https://user-images.githubusercontent.com/14964443/83240464-b95a6a00-a199-11ea-8245-eeee67803973.png)
![image (35)](https://user-images.githubusercontent.com/14964443/83240465-b95a6a00-a199-11ea-888f-a930c2625a80.png)



![image (38)](https://user-images.githubusercontent.com/14964443/83240462-b8293d00-a199-11ea-9ec4-8000f059a84b.png)

**Comment by maltmayer** [comment]
- [ ] There is a problem in the form with the Box office. When the user doesn't fill in anything, it gets filled automatically anyway. So it always appears like this on the marketplace (which is obviously not right)
![image](https://user-images.githubusercontent.com/55785823/83869867-89790c80-a72d-11ea-9683-3e60634b86ac.png)

**Comment by fritzschoff** [comment]
@Mussuranae dunno if still valid, if not please close this issue
