### ISSUE TITLE
[Component] seller-profil-banner

### ISSUE THREAD

**Issue by vwmathilde** [blockframes/blockframes#2640]
# Component

## UI review
_remove this section once everything is checked_
- [x] UI doesn't already have a existing component.
- [ ] Name display in Zeplin is the same as the one in the issue (see below).
- [x] Data can be display like in the UI (see notion).
- [x] A link to this issue in the zeplin object

## Implement Component
- [ ] Create story with storybook
- [ ] Connect component to Zeplin with zeplin-connect
```
update the components.json in blockframes/.zeplin/
{
    "path": "libs/ui/src/lib/slider/slider.component.ts",
    "zeplinNames": [
        "component/slider/archipel_content/movie-slider"
    ],
     "storybook": {
                "kind": "Movie Slider",
                "storybook": [
                    "Movie Slider"
                ]
            }
}
path leads to the component.ts file and zeplinNames are the matching names from this component in zeplin. 
Can be multiple names if there are different states of this component.
```

## Description

- name: org-header
- lib: organization

## Type
- [ ] **Layout**: _Structure a page with content projection (ex: MovieView)._
- [ ] **Page**: _Loaded by the router. Usually used in an app (ex: CatalogDashboardMovieView)._
- [X] **Component**: _Structure a piece of data in the page (ex: MovieTable)._
- [ ] **Display**: _Render data in a page. Can use a component-type (ex: MovieMain, MovieBudget)._
- [ ] **Form**: _Get data from the user (ex: MovieFormBudget)._

### Input
_can be data (movie, distribution right, ...), or UI related (dense, appearance)_
- [ ] organization

### Data view
_data displayed in the UI, derived from the inputs (ex: **title**: movie.main.title.international)_
- [ ] logo
- [ ] activity
- [ ] denomination.name
- [ ] address
- [ ] description

### Content projection
- [ ] Call to Action: `org-header-cta`
- [ ] Action list: `org-header-actions`

## Where is it used
-[Dark](https://zpl.io/bA1gWgp)
-[Light](https://zpl.io/awkzOoK)

**Comment by GrandSchtroumpf** [comment]
It shoudl be used for every organization (not only sale agent) the same way "movie-header" can be used for every movie in every app.
Let's call it "organization-header" to be consistent with "movie-header".

@2amarkina can we have a wireframe with the dynamic zones (like you did with the movie-header component) ?

**Comment by 2amarkina** [comment]
ORGANIZATION HEADER - CASE 1 - GENERAL
<img width="844" alt="Organization_header" src="https://user-images.githubusercontent.com/55499036/80463014-d819d680-8937-11ea-8e60-29297273a2ad.png">
