### ISSUE TITLE
Festival - Debug issue

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2648]
### Movie page
- [x] Respect [zeplin](https://app.zeplin.io/project/5e82f6ca1c987015ec21c1d7/screen/5e85f957c8b24247fad2036d) dimensions  (1440x588px) for the whole banner
- [x] Don't stretch the poster, it should also keep its dimensions
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/08d4487f-c0ba-4d31-ad9e-c5f7006ae5c7)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/63f63ccc-059a-4874-82eb-eecc2bb497b4)
- [x] First text block with 4 lines (from director to title type, genre,,..) should stick together
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/34bc7371-4137-41cd-9f75-c24b916455c8)
- [x] If possible, double the size of the owner org logo
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/282e7ef7-3726-4ef7-920e-2a8c0d12ef55)
- [x] Add space between text block / org logo & CTA contact Sales Agent / other CTA buttons 
- [x] Change text "Added to WishlistT" for "Add to Wishlist", if possible when added change the text for "Remove from Wishlist"
- [x] Change the color of the Add to Whishlist button to same as zeplin
- [ ] If possible, add the CTA buttons from Archipel Content (watch promo reel, watch screener,...) on the action list line with "Add to Wishlist", otherwise add the CTA block from Content to main info tab on Festival
![image](https://user-images.githubusercontent.com/14964443/80985721-df594c80-8e2f-11ea-882f-8782012d610c.png)
![image](https://user-images.githubusercontent.com/14964443/80985850-0f085480-8e30-11ea-9fa5-ee8a4f1f79a8.png)

### Org list
- [x] Blocked by #2629, filter by displaying orgs with appAcces Festival + dashboard

### Invitations 
- [x] Copy the notification page when empty, replacing "notifications" with "invitations" in the text
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/f1b1ca00-8def-4513-95a0-f2659ee34283)

### Navbar
- [x] Change logo for the good one, if not already in assets, they are available [here](https://drive.google.com/drive/u/2/folders/1iGZfSqE74MO4tUOAu5fNQBgM4P6nhFY3)
- [x] Update the invitation icon
- [x] Add the calendar icon, on click use a snackbar with the text "Market Screening List is coming soon!"

### Sidenav
- [x] Rename "All Titles" > "Films"
- [x] Add "Screening List" below Sales Agents with the same snackbar as with the calendar icon in the navbar "Market Screening List is coming soon!"
- [x] Rename "My Screenings" to "My Calendar" and move it above "Wishlist"
- [x] Rename "Wishlist" to "My Wishlist"

### Marketplace All Titles
- [x] Change the label text for Sales Agents filter to "Search for a Sales Agent"
- [ ] Check if Sales agent filter is working, it should look for the org existing as owner of the films, here I got 0 result
![image](https://user-images.githubusercontent.com/14964443/80513766-d3791080-897f-11ea-9a0e-dcaf530b8044.png)

### Org public page (/c/o/marketplace/organization/orgId)
- [x] Tab Contact, add the "Company Information" section (cf. [invision](https://projects.invisionapp.com/d/main#/console/19607961/409944635/preview))
- [x] Tab Contact, center the teammate emails and add a mailto on each
- [x] On the banner, rename "Contact Sales Agent" to "Get in touch"

### Homepage
- [x] Use the banner from [here](https://projects.invisionapp.com/d/main#/console/19607961/414935540/preview)
- [x] Change the banner text according to Invision

### Wishlist
- [x] Use the right h1-2-3 markup for "Your wishlist is empty" 
![image](https://user-images.githubusercontent.com/14964443/80569674-b54ff680-89f9-11ea-8f5a-75de09aff659.png)
- [x] Use same table width as `catalog`
![image](https://user-images.githubusercontent.com/14964443/80569964-40c98780-89fa-11ea-88fa-c5e70093f774.png)

### Dashboard
- [x] 0 illu glitch when going from "My Schedule" to "My Titles" or "My Titles" to "Dashboard", same as #2392 

### Dashboard Import - before import state
- [x] **X QUICK VERSION** : Change title text following [invision](https://projects.invisionapp.com/d/main#/console/19607961/413904542/preview), "Import multiple titles at once"
- [x] Remove the buttons to download excel distribution rights & excel contract
- [x] Modify the template remaining with the updated one (ask @Jackseed)
- [x] Remove the select import type as it will always be movies (so mb select it by default if needed ? @phpgeekfr )
- [x] Use a bigger drag & drop box following [invision](https://projects.invisionapp.com/d/main#/console/19607961/413904542/preview)

### Dashboard Import - after import state
- [ ] After importing a film got the error `Error retrieving icon :warning! Unable to find icon with the name ":warning"` (ask @Jackseed or @phpgeekfr for a filled excel)
- [ ] After import also `Error retrieving icon :error! Unable to find icon with the name ":error"`
- [ ] On the warnings, remove the ones linked to blockframes admins:
    - Movie store type
    - Movie store status 
    - Scoring
![image](https://user-images.githubusercontent.com/14964443/80575888-9014b580-8a04-11ea-952a-a5c66442146b.png)

- [x] Remove the column Status & Store type from the import table
![image](https://user-images.githubusercontent.com/14964443/80575973-aa4e9380-8a04-11ea-8522-9433723e42a0.png)

- [x] Change the subtitle for "Please make sure everything you want to import is correct before finalizing your submission."
![image](https://user-images.githubusercontent.com/14964443/80576146-f994c400-8a04-11ea-8c1b-09d1be066588.png)

- [x] Add a centered text below the table(s) "Please make sure everything is correct. Once you submit your titles they will instantaneously appear on the Archipel Market platform." cf [invision](https://projects.invisionapp.com/d/main#/console/19607961/413904543/preview)
![image](https://user-images.githubusercontent.com/14964443/80576272-2f39ad00-8a05-11ea-9dec-6703f39188cb.png)

- [x] **X QUICK VERSION** : Rename "Submit to AC" & "Submit to Archipel Content" to respectively "Publish" & "Publish to Marketplace" 
![image](https://user-images.githubusercontent.com/14964443/80578647-17642800-8a09-11ea-921c-944c9890b4da.png)
![image](https://user-images.githubusercontent.com/14964443/80578660-1cc17280-8a09-11ea-8fa7-ec0168a3d4a0.png)

- [x] If not already, "Save & finish later" creates the movie in "Draft" status, "Submit" & "Submit to Marketplace" creates the movie with "Accepted" status or switch status from draft to accepted if already existing

- [x] On `festival`, change the import so `movie.main.storeConfig.appAccess` is set to festival: true, catalog: false by default
- [x] On `catalog`, change the import so `movie.main.storeConfig.appAccess` is set to festival: false, catalog: true

- [x] Change the review icon for the one from invision
![image](https://user-images.githubusercontent.com/14964443/80577445-2f3aac80-8a07-11ea-84ae-5bb95401b91f.png)

- [x] **X QUICK VERSION** : remove the review button /// Not quick version: When click on the review button, if the film isn't created yet, don't redirect to the title page, add a snackbar "You have to save the film before reviewing it."

### Dashboard My Titles
- [x] Director name is not load correctly, got [object Object] 
![image](https://user-images.githubusercontent.com/14964443/80579097-c30d7800-8a09-11ea-8519-1ed7828318aa.png)
- [x] Use the label for production status so they have capital letters, should be "Post-production"

### Movie tunnel

- [x] **X QUICK VERSION**: **remove the logo** //Change Archipel Content logo with Archipel Market one on the navbar
![image](https://user-images.githubusercontent.com/14964443/80983529-edf23480-8e2c-11ea-9179-b1f2586a41a7.png)
- [x] Remove "Freshness" on main & summary 
- [x] **X QUICK VERSION** On summary page, change the Submit to Archipel button text to "Publish to Marketplace" //// **Not quick version**: and change the function so the film is accepted when clicked on this button instead of submitted
![image](https://user-images.githubusercontent.com/14964443/80983691-21cd5a00-8e2d-11ea-8112-a6e5968e2c97.png)
- [x] After org creation, add a "Go to Dashboard" or "Go to Marketplace" CTA button depending on the org access. Button must be disabled while org is not accepted

**Comment by fritzschoff** [comment]
@Jackseed 
``` 
 Blocked by #2629, filter by displaying orgs with appAcces Festival + dashboard
``` 
wrong issue ref. This is just about festival and catalog, but this not distinguish between dashboard and marketpalce

**Comment by fritzschoff** [comment]
ref #2650 for the org route in festival we need to wait for this issue

**Comment by fritzschoff** [comment]
wishlist might be removed in festival, waiting for decision here

**Comment by GrandSchtroumpf** [comment]
@fritzschoff Concerning the wishlist. It's just some html/css hotfix. Let's do that without worrying about the reusability. Thoses pages have been copy pasted from catalog and will deserve a full rewor **later**.
The 2 fixes should take less than 30min, if this is not the case come to me.
