### ISSUE TITLE
Use JW Player for promotional videos

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2658]
## Description
Now that we have our own in-app video player, we should use it to display promotional videos like trailers, promo reels,... instead of using external urls. 
Still, both systems should co-exist as it shouldn't block our uers if they don't have the file available. 

## Acceptance criteria
- [ ] UX updated to add video player on marketplace and file management on dashboard
- [ ] Update the db accordingly
- [ ] Implement wireframes

**Comment by Jackseed** [comment]
Update: it has been decided to only keep internal videos and completely remove external links so the 2 systems shouldn't co-exist. 

Thus movie view has to be updated in order to include JW Player (player) included

**Comment by pldespaigne** [comment]
link to #3820

**Comment by pldespaigne** [comment]
link to #4115

**Comment by Jackseed** [comment]
Update:
JW Player is used on movie view with the Sales pitch video. We should use the same component to display promotional videos listed on Other videos section in the movie form (eg trailers, teasers,..) 
![image](https://user-images.githubusercontent.com/14964443/103778730-f55c8400-5032-11eb-9695-b8e5041a0b39.png)
(Please also correct "Tailer" in the list for "Trailers"

This video section is at the bottom of the marketplace movie view, on every tabs like images & files (cf. [Zeplin](https://app.zeplin.io/project/5fa1637022e6a88784fbb052/screen/5fa17fe86b5aaa4e7a6d56a2))
![image](https://user-images.githubusercontent.com/14964443/103778854-23da5f00-5033-11eb-8646-6a2ccafd179c.png)
