### ISSUE TITLE
E2E Test - Create screenings

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2687]
**Connected dashboard festival user with movies***
- [x] Homepage - Dashboard page 
- [x] Click “My Calendar"
- [x] Click on the empty space to add a new event 
- [x] Input a "test screening" name
- [x] Click on Private
- [x] Click on More details
- [x] Click on Select Title 
- [x] Select a movie
- [x] Click on save

This test should be used 4 times: 
- Once to create a private screening taking place right now
- Once to create a public screening taking place right now
- Once to create a private screening taking place tomorrow
- Once to create a public screening taking place tomorrow

**Comment by Jackseed** [comment]
We'll need a video on an org/user & 1 or 2 films + JW Player id (see with @pldespaigne)

**Comment by pldespaigne** [comment]
Here is how to proceed :
1) go to your firebase console > Database > `movies` collection
2) choose a random movie and add `hostedVideo: "IotixOa0"` to it's document
3) Remember the title of this movie as you will be able to create screening only for this movie
4) In the app create a screening event for this movie

That's all !
Ask me on slack if you have more question
