### ISSUE TITLE
Organizations reading security issues

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2692]
To better fit our current needs, it have been decided to allow every logged in user to be able to read organization documents.

To do so, we need to comment some code about org private data such as bank account info.

This issue is here as a reminder for when we will have the time to resolve #2049

------------------

Whe should also change the way we link movies and org.
We should have movie.orgIds instead or org.movieIds[] (movie => org and not org => movie or both )

**Comment by xmano** [comment]
Removing comment from Org create E2E test to link to this.

Basically Security Rules unit test should cover the scenarios mentioned here. E2E test is for checking overall integration and not document level test cases.

**Comment by Jackseed** [comment]
I close this as for now org doc is public and we don't have critical info to protect for now
