### ISSUE TITLE
Avoid being in spams 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2703]
The last thing we want is to end up in spams
First have a look to server config on sendgrid

**Comment by phpgeekfr** [comment]
https://sendgrid.com/blog/8-best-practices-to-improve-your-email-deliverability/
https://sendgrid.com/blog/email-authentication-explained/

Added forwarding to thoses mails (but we could create a google suit email group) :
![image](https://user-images.githubusercontent.com/1194344/82029396-3ca69680-9697-11ea-9f2f-2cc6350d4c4b.png)
![image](https://user-images.githubusercontent.com/1194344/82029672-9f982d80-9697-11ea-8e41-310131627342.png)



Domain authentification seems ok (SPF and DKIM) :
![image](https://user-images.githubusercontent.com/1194344/82030220-6dd39680-9698-11ea-87a0-b98f9b8efd6d.png)


Updated "link branding" conf : 

![image](https://user-images.githubusercontent.com/1194344/82035830-5e584b80-96a0-11ea-8bac-294d1e3c7405.png)
![image](https://user-images.githubusercontent.com/1194344/82035849-6617f000-96a0-11ea-80c1-86d3fc0b90b9.png)

![image](https://user-images.githubusercontent.com/1194344/82035872-6e702b00-96a0-11ea-87a6-55b121a9b930.png)

**Comment by phpgeekfr** [comment]
Also, mail content should reflect as much as possible the domain used to send mails.
So If we use blockframes.io,  we should mention it somewhere in mail content and/or subject.

**Comment by phpgeekfr** [comment]
Another option is to get a dedicated IP but sendgrid advise this only when you send up to 25kmails/day
