### ISSUE TITLE
Set the correct domain when sending emails

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2719]
Currently we use the same domain for links in every mail we send.
But in fact there can be two domains and the user should be redirected to the good one when he clicks on a link of an email.

- [ ] Identify the mails that uses links and check which domain it should use.
- [ ] If user to who we are sending the mail have an orgId, we can guess the domain using org.appAcess

**Comment by Jackseed** [comment]
We should also send different welcome emails depending on the app where the user created an account.
For now we have one for Archipel Content only ID: d-eb8e1eb7c5a24eb8af1d2d32539ad714

**Comment by Jackseed** [comment]
Emails where we should change the url according to the org appAccess:
- [ ] Request to join your org received Template ID: d-b1ab5d21def145ccb759520e2d984436
- [ ] Organization Created Template ID: d-8c5f7009cd2f4f1b877fa168b4efde48
// Looks like url was hardcoded, I removed the link for now
- [ ] Join an org request - Accepted Template ID: d-d32b25a504874a708de6bfc50a1acba7

Emails with different ids depending on the app:
- [ ] Welcome email
- Archipel Content: Template ID: d-eb8e1eb7c5a24eb8af1d2d32539ad714 
- Archipel Market: tbc
[ ] Invited user credentials
- Archipel Content: Template ID: d-a34ce9ea59c5477f9feae8f556157b6b 
- Archipel Market: tbc
