### ISSUE TITLE
Festival debug

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2735]
- [x] Modify link on the welcome email to landing page not org page as your blocked in it otherwise (no nav)

- [x] on dashboard home, when empty, change text for 
Title: « You have no titles on the market » 
Subtitle:« For now, you haven’t publish any titles to the market. 
You can choose one of the following according to your situation : »
![image (19).png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/7d7df548-6951-47c1-a246-13689219741d)

- [x] 	Dashboard/invitation illu broken
![image (20).png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/af3e183a-6beb-49d3-b28b-186ee2725f82)

- [x] 	Identity guard looks blocking
- [x] 	Algolia search error sur find an org: https://sentry.io/organizations/cascade-8/issues/1652836029/?referrer=slack
- [x] 	When submitting a movie: Fill all mandatory fields before submitting
- [x] 	Can’t save org form (when there is a logo uploaded?) : https://sentry.io/organizations/cascade-8/issues/1650371368/?referrer=slack
- [x] 	Change routing when clicking on an event for c/o/dashboard/eventId/edit
- [x] Add an edit button on the film page dashboard side

**Comment by maltmayer** [comment]
- [ ] Dashboard > Marketplace activity stats still take a few minutes to load.

**Comment by maltmayer** [comment]
- [ ] Display problem with keywords (DASHBOARD)
They're here when I edit
![image](https://user-images.githubusercontent.com/55785823/81658777-606ca100-9439-11ea-8dca-622a2b2cb0ac.png)
but don't appear on Film Details
![image](https://user-images.githubusercontent.com/55785823/81658856-71b5ad80-9439-11ea-9c5a-c8ec589020e4.png)

**Comment by maltmayer** [comment]
- [ ] Same display problem with Versions
There's English (Original Version) in Edit mode 
![image](https://user-images.githubusercontent.com/55785823/81659300-df61d980-9439-11ea-8f2d-823d63844271.png)
That doesn't appear on Film Details
![image](https://user-images.githubusercontent.com/55785823/81659344-eab50500-9439-11ea-979a-39c0dc222635.png)

**Comment by maltmayer** [comment]
- [ ] Other display problem for Presentation deck : it's missing but doesn't appear "Missing" on Film Details
![image](https://user-images.githubusercontent.com/55785823/81659499-10420e80-943a-11ea-8257-de07243710b3.png)

**Comment by maltmayer** [comment]
Dashboard > Film tunnel > Production information

- [ ] remove spaces between country and parenthesis for "Co-production"

- [ ] Why is "Producer" separated from "Role" ?? Doesn't make sense, they should go together. It should appear like this : 
_Producers 
Producer Name (Role), Producer Name (Role)_ 

![image](https://user-images.githubusercontent.com/55785823/81659880-6f078800-943a-11ea-962a-78a5aa39dcb8.png)

**Comment by maltmayer** [comment]
- [ ] Org activity should appear with full name, not "dev name". Here for example it should be "International Sales" not "intlSales"
![image](https://user-images.githubusercontent.com/55785823/81661568-97908180-943c-11ea-844b-a317075364a0.png)

**Comment by maltmayer** [comment]
@Jackseed c'est là

**Comment by Jackseed** [comment]
I will add these items to a dedicated issue, I close this one
