### ISSUE TITLE
Org page logo Edit function

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2749]
- [ ] There should be a way to edit the logo (as in re-crop). Here you can either delete or select new one. 
![image](https://user-images.githubusercontent.com/55785823/81661339-42547000-943c-11ea-87fc-bbc443e1853f.png)

**Comment by 2amarkina** [comment]
Here the low-fidelity wireframes are here for this functionality. If needed, can be reworked for high-fidelity ones. https://www.figma.com/file/mJYm8VIclQcNBzP4AItjgk/Cropper

**Comment by Jackseed** [comment]
@2amarkina I copy here your comment on figma:

> 
Also If I want just to modify the existing image, a simple click on a photo can lead to the cropper state + hover in a desktop version for showing that there is an action

@stephanie-cascade8 would be good to have a visual proposition for the hover state of the image that leads to cropper again if clicked
