### ISSUE TITLE
Create a movie notification - change the trigger

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2758]
Currently we create a notification at the movie creation. We should replace it to a notification:
- on catalog when the movie is submitted to Archipel Content (status "submitted")
- on catalog when the movie is accepted by Archipel Content (status "accepted")
- on festival when the movie is published online (status "accepted")

**Comment by fritzschoff** [comment]
@Jackseed can you please assign the sanity team if it is still a thing?

**Comment by Jackseed** [comment]
@fritzschoff in fact that's done > closing this
