### ISSUE TITLE
Add App Logo Component

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#2760]
This component should take care of displaying the correct logo depending on the app this component is displayed

**Comment by fritzschoff** [comment]
@Jackseed for the next sprint

**Comment by GrandSchtroumpf** [comment]
Component should use the `ImgAssetModule` to load the right image depending on the theme.
```html
<img [asset]="appLogo" alt="application logo" />
```
And it should get the key "app" from the router's data to know in which app we are : 
```typescript
appLogo = this.routerQuery.getData('app');
constructor(private routerQuery: RouterQuery) {}
```

**Comment by fritzschoff** [comment]
I linked the PR to the issue, so it gets closed when you merge it.
