### ISSUE TITLE
How to handle application specific behaviors ?

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2765]
For example, when we "publish" a movie it can result in movie.status equal to 'published' or 'submitted' depending of the current app we are.

We need to find a way to handle this kind of behaviors without using `getCurrentApp` everywhere in the code.

**Comment by fritzschoff** [comment]
@phpgeekfr can be closed since now the production status can be set in the movie form?

**Comment by phpgeekfr** [comment]
@fritzschoff I don't see the link with productionStatus here. The point of this issue was to say that regarding of the app we are, the save button will not behave the same and we need to use `getCurrentApp` to check if status must be set to `published` or `submitted` when we hit the save button.

But maybe this can be closed or set to low priority
