### ISSUE TITLE
[DRAFT] Remove/update OrganizationMember interface

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2779]
[DRAFT]
The only important difference between `OrganizationMember` and `User` is the role attribute we append.

To do: 
`OrganizationMemberRequest` must be removed.

`OrganizationMember` should  only extend User and have the role attribute. 
Or maybe something like that:

```
interface UserWithRole {
user: USer,
role: UserRole
}
```

**Comment by Mussuranae** [comment]
Same thing with the `PublicUser`, it's pretty much the same as `User` (only 3 fields more in User).
Refactor also the user service with Akita-ng-Fire.
Put the new interface in user lib and not auth lib.

**Comment by Jackseed** [comment]
@phpgeekfr @Mussuranae  is it still an open issue ?

**Comment by phpgeekfr** [comment]
Yes, this still need a bit of clearing. But this is low priority
