### ISSUE TITLE
createUser client side makes low sense

### ISSUE THREAD

**Issue by lsenta** [blockframes/blockframes#278]
https://github.com/blockframes/blockframes/blob/master/libs/auth/src/lib/%2Bstate/auth.service.ts#L69-L72

This is risky, doesn't create actually create a user (you need to use firebase auth for that) and duplicate the already more reliable function:
https://github.com/blockframes/blockframes/blob/master/functions/src/users.ts#L18-L21

**Comment by Maxstgt** [comment]
@lsenta can be closed?

**Comment by Jackseed** [comment]
Still relevant but low priority (just front)

**Comment by Jackseed** [comment]
done > closed
