### ISSUE TITLE
Debug - catalog / Archipel Content 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2781]
This issue will gather on comments all the bugs to fix on `catalog`.

**Comment by maltmayer** [comment]
- [ ] all library titles have disappeared from Archipel Content...

**Comment by maltmayer** [comment]
- [ ] There should be more space before a title than after (here I'm talking about Company Credits)
![image](https://user-images.githubusercontent.com/55785823/82303350-219b9580-99bb-11ea-959b-fcb4f3f5b4ee.png)

**Comment by maltmayer** [comment]
- [ ] Recent activity "card" shouldn't go to the bottom of my screen. It should stop at 3/4 

![image](https://user-images.githubusercontent.com/55785823/82303815-bdc59c80-99bb-11ea-8c53-31f3ba98f67e.png)

**Comment by maltmayer** [comment]
MARKETPLACE WISHLIST
- [ ] not enough padding on the left and on the right of the page
![image](https://user-images.githubusercontent.com/55785823/82303949-f4031c00-99bb-11ea-9251-e11d48db1688.png)

**Comment by joanofdart** [comment]
Regarding the activity card... was that feature reworked? I'm not seeing it working like that. @Jackseed 
I have gone ahead and checked the others. I'm waiting for feedback from @maltmayer regarding the padding on the title.

**Comment by joanofdart** [comment]
Just had a chat with @maltmayer regarding the spacing and card.
Everything within this issue should be okay now :)

**Comment by Jackseed** [comment]
outdated issue > closed
