### ISSUE TITLE
Debug - festival / Archipel Market

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2782]
This issue will gather on comments all the bugs to fix on `festival`.

**Comment by maltmayer** [comment]
MARKETPLACE > TITLE LIST
- [ ] "Sort by" doesn't work

**Comment by maltmayer** [comment]
MARKETPLACE > SALES AGENT PAGE > LINE UP

- [ ] the directors don't appear on the movie cards in the line-up
![image](https://user-images.githubusercontent.com/55785823/82302837-696ded00-99ba-11ea-97ce-bc32692c30bd.png)

MARKETPLACE > ORG PAGE 

- [ ] the org cards don't all have the same size 
![image](https://user-images.githubusercontent.com/55785823/82302927-8efaf680-99ba-11ea-9119-e2c695ab14a1.png)

**Comment by maltmayer** [comment]
- [ ] My Wishlist should be in the top bar

- [ ] The icons in the top bar (calendar / invitations / notifications) have weird proportions. They should have the same space between one another. And is it possible make them the same size ?? (calendar icon is 2 times bigger thant invitations)

![image](https://user-images.githubusercontent.com/55785823/82304255-607e1b00-99bc-11ea-9c5d-05c7a6634e91.png)

- [ ] My Calendar should be in the side menu 
![image](https://user-images.githubusercontent.com/55785823/82304284-6c69dd00-99bc-11ea-9639-da8d288bb098.png)

**Comment by maltmayer** [comment]
- [ ] Wishlist doesn't work

**Comment by maltmayer** [comment]
DASHBOARD NO TITLE

- [ ] wrong "import your titles in bulk"  logo for dark theme

- [ ] put period points at the end of sentences. 

- [ ] Correct text : Title : "You have no title yet." / after that : "You haven't imported titles yet. You may add several titles at once through bulk import, or just one at a time."

![image](https://user-images.githubusercontent.com/55785823/82425227-83750180-9a86-11ea-842b-06f6ea9a7726.png)

**Comment by maltmayer** [comment]
- [ ] Here my event is over and I see that. If there is no statistic to show, then there should either be an illustration saying there is no statistic to show, or juste delete this area.

![image](https://user-images.githubusercontent.com/55785823/82425818-59700f00-9a87-11ea-9477-61e37f58cd3c.png)

**Comment by maltmayer** [comment]
- [ ] Archipel Market logo is blurred. change to better quality
- [ ] Archipel Market logo changes color in dark / light theme. should stay the same (I like the dark theme logo better)
![image](https://user-images.githubusercontent.com/55785823/82426230-e1eeaf80-9a87-11ea-80c4-0dcb549ff525.png)
![image](https://user-images.githubusercontent.com/55785823/82426270-ec10ae00-9a87-11ea-9894-39a6419d095c.png)

**Comment by Jackseed** [comment]
- [ ] Display films & more generally algolia results only when they are complete

**Comment by Jackseed** [comment]
- [ ] Safari updates

**Comment by Jackseed** [comment]
- [ ] Let all the members change a movie on the movie form (and not only admins or superAdmins)

**Comment by Jackseed** [comment]
- [ ] `Can't find variable: ResizeObserver` https://sentry.io/organizations/cascade-8/issues/1706834837/?project=1540126&referrer=slack
- [ ] `undefined is not an object (evaluating 'this.layout.layout$.subscribe')` https://sentry.io/organizations/cascade-8/issues/1706834891/?project=1540126&referrer=slack

**Comment by Jackseed** [comment]
- [ ] Add the "Upcoming Screenings" tab on the movie view marketplace side following [this UI ](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/414884197/preview?scrollOffset=101.11111450195312)
It's something forgotten on the way..
This component is already in use on the organization public view and the global screening list @GrandSchtroumpf is the one who has implemented it if any questions

**Comment by Jackseed** [comment]
- [ ] Add the "who's on the market today" button from [this UI](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/414935540/preview?scrollOffset=101.11111450195312) on the marketplace homepage, should link to `/c/o/marketplace/organization`

**Comment by Jackseed** [comment]
- [ ] Only display the value not "min" (nor null) when `movie.main.length` is a string on the movie view
![image](https://user-images.githubusercontent.com/14964443/83899022-0c16c180-a758-11ea-8924-a48a6816ba9a.png)
Should be a hot fix too

**Comment by Jackseed** [comment]
- [ ] Typo on notification when requesting an invitation to an event
Currently `Your request to attend event "Screening right now" have been sent.`
Should be `Your request to attend event "Screening right now" has been sent.`
![image](https://user-images.githubusercontent.com/14964443/84031659-5f765300-a996-11ea-9830-9dfdab19b8d9.png)

**Comment by joanofdart** [comment]
@Jackseed regarding that last one, I just checked it but I'm not sure this should be done on this component. Perhaps we should make a better case with the form criteria? To make sure we just accept numbers?

**Comment by Jackseed** [comment]
- [ ] On dashboard, event form / view when event finished, I've never seen any statistics... check with @Hugo-Hontans how it should work
![image](https://user-images.githubusercontent.com/14964443/84032243-52a62f00-a997-11ea-87fc-b63f55e8d78d.png)

**Comment by Jackseed** [comment]
> @Jackseed regarding that last one, I just checked it but I'm not sure this should be done on this component. Perhaps we should make a better case with the form criteria? To make sure we just accept numbers?

No we want to accept string has it can be "TBD" (i.e. To be determined). We will make a better update on the form part when we'll work again on the movie form but we need a patch on the view side asap as most of the films we have currently are TBD

**Comment by joanofdart** [comment]
> No we want to accept string has it can be "TBD" (i.e. To be determined). We will make a better update on the form part when we'll work again on the movie form but we need a patch on the view side asap as most of the films we have currently are TBD

Gotcha!

**Comment by Jackseed** [comment]
> * [ ]  On dashboard, event form / view when event finished, I've never seen any statistics... check with @Hugo-Hontans how it should work
>   ![image](https://user-images.githubusercontent.com/14964443/84032243-52a62f00-a997-11ea-87fc-b63f55e8d78d.png)

@Hugo-Hontans will take care of this, I've created a dedicated issue #3004, I close this comment

**Comment by Jackseed** [comment]
- [ ] Following what has been done on the dashboard (screen menu with "Buyer's Platform" separated with a divider), we should add the same thing on Marketplace, after "My Wishlist", separated by a divider, a link "My Dashboard"
- The link should redirect to `
/c/o/marketplace/home` 
- The link should be displayed only for orgs that have `appAccess` festival & dashboard parameters both `true`, if only one don't display it (same as "Buyers' Platform" on dahsboard)
- Icon incoming, crafted by @stephanie-cascade8 
![image](https://user-images.githubusercontent.com/14964443/84035487-1a551f80-a99c-11ea-91f3-32951fdd28b2.png)
![image](https://user-images.githubusercontent.com/14964443/84035973-db739980-a99c-11ea-9608-4556ab525fd3.png)

**Comment by joanofdart** [comment]
Done :)
![image.png](https://images.zenhubusercontent.com/5ed501a5f73c640fafa5b69d/faee45a8-a72c-4a53-a71c-83dff74aa34b)

**Comment by Jackseed** [comment]
- [ ] When a user attached to an org that has access to both festival & dashboard is connecting, he should be redirected to `c/o/dashboard/home` instead of marketplace

**Comment by Jackseed** [comment]
- [ ] On `c/o/marketplace/organization` the films counted on the sales agent cards should only count the films on the org movieIds + `storeConfig.status` `accepted` +  `storeConfig.appAccess.festival` `true`, not the falsy ones.
This filter is the same as the `/c/o/marketplace/organization/orgId/title` which is working (on the example screens, 9 vs 8 movies)
![image](https://user-images.githubusercontent.com/14964443/84038973-ddd7f280-a9a0-11ea-8d8f-10e7a79000c6.png)
![image](https://user-images.githubusercontent.com/14964443/84039006-e6c8c400-a9a0-11ea-8131-19ffae4db056.png)
![image](https://user-images.githubusercontent.com/14964443/84038680-833e9680-a9a0-11ea-8b1a-661b0a27fe4d.png)

**Comment by Jackseed** [comment]
- [ ] On `c/o/marketplace/organization` film counts are not updated all the time for example here I clicked on Hart Caldwell org card and then go back and now this org only has films counted. 
Then I click on Turner Gray card and go back, it's the only one to have films and the others all 0... 
![image](https://user-images.githubusercontent.com/14964443/84039088-0bbd3700-a9a1-11ea-8d42-f684baec5e48.png)
![image](https://user-images.githubusercontent.com/14964443/84039219-38714e80-a9a1-11ea-831d-aacbb924249b.png)

**Comment by Jackseed** [comment]
- [ ] Not sure if it deserves an issue on its own (too big?) but when there is a link inside an automated email, if the user is not connected it will have to login and then he's not redirected to the first link he clicked on but on the app homepage. 
Is there a way to have something like "persistent" redirection?
So the flow would be
1. Clicks on a email link
2. Log in page
3. Redirects to the email link (instead of the homepage)

**Comment by stephanie-cascade8** [comment]
@joanofdart, for the design of the icon, I shared in Invision an example of the page with the menu. [](https://invis.io/Q7XLR5J6MXY). In zeplin styleguide/navigation/added-items, you'll find the component with it's active version as well. Telle me if any questions.

**Comment by joanofdart** [comment]
> * [ ]  Not sure if it deserves an issue on its own (too big?) but when there is a link inside an automated email, if the user is not connected it will have to login and then he's not redirected to the first link he clicked on but on the app homepage.
>   Is there a way to have something like "persistent" redirection?
>   So the flow would be
> 
> 1. Clicks on a email link
> 2. Log in page
> 3. Redirects to the email link (instead of the homepage)

This should be an issue on its own in my opinion.

**Comment by GrandSchtroumpf** [comment]
@joanofdart Feel free to create one and ask @Jackseed to update his comment.

**Comment by joanofdart** [comment]
@GrandSchtroumpf 👍

**Comment by Jackseed** [comment]
> * [ ]  On `c/o/marketplace/organization` film counts are not updated all the time for example here I clicked on Hart Caldwell org card and then go back and now this org only has films counted.
>   Then I click on Turner Gray card and go back, it's the only one to have films and the others all 0...
>   ![image](https://user-images.githubusercontent.com/14964443/84039088-0bbd3700-a9a1-11ea-8d42-f684baec5e48.png)
>   ![image](https://user-images.githubusercontent.com/14964443/84039219-38714e80-a9a1-11ea-831d-aacbb924249b.png)



> * [ ]  Not sure if it deserves an issue on its own (too big?) but when there is a link inside an automated email, if the user is not connected it will have to login and then he's not redirected to the first link he clicked on but on the app homepage.
>   Is there a way to have something like "persistent" redirection?
>   So the flow would be
> 
> 1. Clicks on a email link
> 2. Log in page
> 3. Redirects to the email link (instead of the homepage)

I tick this one, @joanofdart opened #3024

**Comment by Jackseed** [comment]
- [ ] Movie form creates a first empty element on box office at the creation of a film, it shouldn't

**Comment by joanofdart** [comment]
> * [ ]  Movie form creates a first empty element on box office at the creation of a film, it shouldn't

could you provide me with a screenshot about this? if you don't mind @Jackseed

**Comment by Jackseed** [comment]
@joanofdart yep here it is:
- One from the movie tunnel, I just created a new film on dashboard an let the box office empty
- on firebase when I save it adds an empty element which mess up with the view
- on firebase it should stay empty as last screenshot except if there is a value filled in
![image](https://user-images.githubusercontent.com/14964443/84241931-75078c00-ab00-11ea-9123-317d5da36686.png)
![image](https://user-images.githubusercontent.com/14964443/84242002-851f6b80-ab00-11ea-9c33-f8e2ab9cbc9c.png)
![image](https://user-images.githubusercontent.com/14964443/84242024-8bade300-ab00-11ea-8829-fb5a52973f72.png)

**Comment by Jackseed** [comment]
- [ ] Display events on calendar even when they are status `pending`, as well as `accepted`; the UI of pending events [is here](https://app.zeplin.io/project/5ee11c774f5880b7452e7933/screen/5ee11d485d22e4b3acc595e0) (the ones with the red badge)

**Comment by Jackseed** [comment]
- [ ] Instead of removing the notifications read on the activity feed, remove the button "Mark as read", keep the More button and give them [this UI], (https://app.zeplin.io/project/5ee11c774f5880b7452e7933/screen/5ee1e1db17603cb727ec61e0)
![image](https://user-images.githubusercontent.com/14964443/84362128-08a68e80-abcd-11ea-9800-2de11534e9f2.png)

**Comment by joanofdart** [comment]
The last two @Jackseed, I need to be invited to the project :) Says I have not been invited.

**Comment by GrandSchtroumpf** [comment]
In `apps/festival/festival/src/app/marketplace/wishlist/wishlist.compoennt.ts`
Line 48 change : 
`tap(wishlist => this.hasWishlist = !!wishlist.movieIds.length),`
to 
`tap(wishlist => this.hasWishlist = !!wishlist?.movieIds.length),`
(with a "?" after "wishlist")

**Comment by Jackseed** [comment]
@joanofdart just saw your comment, it's ok you're invited now. 
Forget about the one on the notifications, I'm afraid it changes too many things before the release, just focus on the event one please

**Comment by Jackseed** [comment]
- [ ] Dashboard part, event form, movie list displayed when creating an event shows all the movieIds of the org. It should instead be filtered to display only movies matching all these fields:
- movies contain in active org `org.movieIds`
- `main.storeConfig.appAccess.festival: true`
- `main.storeConfig.appAccess.status: accepted`
![image](https://user-images.githubusercontent.com/14964443/84396133-8931b300-abfe-11ea-88f7-6eda40469b72.png)

**Comment by Mussuranae** [comment]
For `downloading  script` button on movie view, it's corrected, but in the DB we always have scenario. I change only the label on the static model to display the good word. If we want to keep consistency, we will have to do a migration script to correct scenario onto script in the DB.

**Comment by GrandSchtroumpf** [comment]
@Mussuranae The whole point of having key & label is not to update the database one label changes. It would be like changing `catalog` to `archipelContent`. Make sure though that @Jackseed is aware it'll change the label everywhere it's used (list them for him).

**Comment by Jackseed** [comment]
### Org public view
- Remove « ‘ » if `runningTime` is a string
![image](https://user-images.githubusercontent.com/14964443/85429788-85e3e300-b57f-11ea-9d1b-aa6bfce90a09.png)

- Tab contact, members should be align on the same grid https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/409944635/preview?scrollOffset=357.7778015136719
![image](https://user-images.githubusercontent.com/14964443/85429838-972cef80-b57f-11ea-92a7-bb72209d5f1c.png)

### MOVIE LIST 
- Remove the title « Title Metadata » 
![image](https://user-images.githubusercontent.com/14964443/85429917-b62b8180-b57f-11ea-890b-5cd315198f89.png)

### Dashboard Homepage
- Change the + button link to the movie tunnel: `c/o/dashboard/tunnel/movie`
![image](https://user-images.githubusercontent.com/14964443/85429938-bdeb2600-b57f-11ea-8897-36a8342bee51.png)

### Org settings
- Remove the user position on the banner (eg here « Master of the world »)
![image](https://user-images.githubusercontent.com/14964443/85429961-c4799d80-b57f-11ea-83ca-5397a92e0df9.png)

- Too much space between input and error message
![image](https://user-images.githubusercontent.com/14964443/85429974-ccd1d880-b57f-11ea-9d06-ee6df034ad4e.png)

### General
- White page when you logout with at least 2 tabs open on the app (only one tab is reloaded and redirect to landing, it should be all of them)

### Event page
- « Ask for invitation » should use an observable to switch when the button is clicked and display the invitation status (currently we need to reload the page so the user clicks more than once)
![image](https://user-images.githubusercontent.com/14964443/85430069-ee32c480-b57f-11ea-84f5-54dda7e9ed08.png)
![image](https://user-images.githubusercontent.com/14964443/85430076-f12db500-b57f-11ea-913c-01910b15f05e.png)

### Meeting page
- Change links for meeting to be external > don’t add archipelmarket.com at the beginning
https://staging.archipelmarket.com/zoom.com

- Festival: Display the premiere with a capital letter eg here « International Premiere »
- [ ] Don't display festival date if it's set to _null_ 
![image](https://user-images.githubusercontent.com/14964443/85430211-1e7a6300-b580-11ea-81f2-03de28c4f274.png)

- Producers: there is a missing space after the comma separating the 2 producers
![image](https://user-images.githubusercontent.com/14964443/85430319-4bc71100-b580-11ea-84e8-06f71dd20d75.png)

- Dialogue Writer should be displayed on the artistic crew but he’s not
_Marketplace view_
![image](https://user-images.githubusercontent.com/14964443/85430346-52ee1f00-b580-11ea-89fc-df9ac66a847c.png)
_Vs dashboard form_
![image](https://user-images.githubusercontent.com/14964443/85430419-6305fe80-b580-11ea-99ec-5f7a18086648.png)

- Box office: When it’s box office in € or $, just display the symbol before the number eg here should be: « €10,000 (Algeria), $1,000,000 (World)
![image](https://user-images.githubusercontent.com/14964443/85430459-6d27fd00-b580-11ea-83d2-de3bf848600d.png)

- Name shouldn’t be cut

![image](https://user-images.githubusercontent.com/14964443/85430493-77e29200-b580-11ea-9d96-2cdd66485b6e.png)

**Comment by maltmayer** [comment]
- [ ] Correct English mistake. "The name is already taken" is incorrect. > "This company already exists."
https://user-images.githubusercontent.com/14964443/85429974-ccd1d880-b57f-11ea-9d06-ee6df034ad4e.png

- [ ] Marketplace event view when screening is finished: correct "screening done" to "Screening session closed"
![image](https://user-images.githubusercontent.com/55785823/85271176-bdb53280-b47a-11ea-836e-82e522a769f1.png)

**Comment by Jackseed** [comment]
Marketplace movie list

- [ ] clickable area shouldn't be just the small "View more" area. Should be the whole poster (except for the heart for the wishlist of course) and the film title also
![image](https://user-images.githubusercontent.com/55785823/82926090-f860a380-9f7e-11ea-9409-c172f1128a7e.png)

**Comment by Jackseed** [comment]
- [ ] Marketplace, `/c/o/marketplace/organization`, don't display org that has no movie with status accepted + appAccess festival to true
![image](https://user-images.githubusercontent.com/14964443/85882641-ecffd280-b7df-11ea-9457-019a1ffe06fd.png)

- [ ] Marketplace homepage, carousels with "In Production" films & "In development" are not displayed on prod but they should. Currently only completed films
![image](https://user-images.githubusercontent.com/14964443/85882734-1b7dad80-b7e0-11ea-8926-2de044ebf30a.png)

- [ ] Marketplace homepage, all this page should only display films with status "accepted", no "draft"

- [ ] Movie form, "Close" icon and then "Close without saving" doesn't close the form

- [ ] Dashboard event form, shouldn't be able to send an invitation to someone who was already invited.
![image](https://user-images.githubusercontent.com/55785823/82893137-db14e080-9f50-11ea-98a3-8fe915cdde56.png)

- [ ] There should be a little padding in event box
![image](https://user-images.githubusercontent.com/55785823/83037953-b433d880-a03c-11ea-91cb-feedabaf9f6a.png)

**Comment by Jackseed** [comment]
- [ ] https://staging.archipelmarket.com/c/o/marketplace/organization
There is a glitch when you click on the movie icon on the org card

**Comment by Jackseed** [comment]
- [ ] Profile image not updating on the navbar nor https://staging.archipelmarket.com/c/o/marketplace/organization/sLchj1Ib4Cxhwr0ZBW4m/member
![Capture d’écran 2020-08-25 à 18 53 06](https://user-images.githubusercontent.com/14964443/91204393-5038b300-e704-11ea-82a1-286e7c21fa12.png)

**Comment by maltmayer** [comment]
The search bar on the film page is confusing, it looks like an image that didn't load. Should have a placeholder, and generally, the same design as the original search bar
![image](https://user-images.githubusercontent.com/55785823/91325556-a1f44280-e7c3-11ea-8948-1357b9789d9b.png)

**Comment by Jackseed** [comment]
- [ ] `/c/o/marketplace/home` Change the New films carousel on marketplace homepage to really display new films, i.e. sort films by creation dates and display them from the newest to oldest

**Comment by Jackseed** [comment]
- [ ] Test reset password function, it's not reliable, lot of complaints about it. Works for me unfortunately so can't give much more details...

**Comment by Jackseed** [comment]
- [ ] Invitations: the request to access a screening from buyer to seller has a wrong link id, it uses the invitation id instead of the event id
![image](https://user-images.githubusercontent.com/14964443/92743478-dc8fda80-f380-11ea-84d9-aa358f7bc7bb.png)

**Comment by Jackseed** [comment]
- [ ] Dashboard event form, email adresses starting with an "s" are not working, the "s" is deleted...
