### ISSUE TITLE
Debug - Movie form

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2783]
This issue will gather on comments all the bugs to fix on `movie-form`.

**Comment by Jackseed** [comment]
- [ ] Let all the members change a movie on the movie form (and not only admins or superAdmins)

**Comment by joanofdart** [comment]
Currently, I'm waiting for Francois to discuss about this. Seems that the issue should be already fixed.

**Comment by Jackseed** [comment]
- [ ] Calendar card doesn't fit the content for the release date
![image](https://user-images.githubusercontent.com/14964443/84900839-f041e280-b0aa-11ea-837b-deaacb5f4440.png)
- [ ] Center the icon in the button
![image](https://user-images.githubusercontent.com/14964443/84900921-0f407480-b0ab-11ea-8d54-99c2d7281065.png)
- [ ] Button text to change for: « Add Producer »
![image](https://user-images.githubusercontent.com/14964443/84900990-22ebdb00-b0ab-11ea-8fad-f3685fcff2a4.png)
- [ ] Button text to change to: « Add Crew member »
![image](https://user-images.githubusercontent.com/14964443/84901031-2ed79d00-b0ab-11ea-9d8c-540bb2a759b9.png)

### Summary page
- [ ] I still got missing fields while I've filled it
![image](https://user-images.githubusercontent.com/14964443/84901114-4e6ec580-b0ab-11ea-9177-26cb462c295c.png)

- [ ] The « premiere » (4th value) should be written « {{premiere value}} Premiere », e.g. in this example: « International Premiere »
![image](https://user-images.githubusercontent.com/14964443/84901218-70684800-b0ab-11ea-89de-c6d7dbadafbc.png)

- [ ] Producers line (see below): commas should be next to parenthesis > eg: « (Production Manager), test film »
- [ ] Co-Production line: no space before after parenthesis and neither before comma > eg: « (American Samoa), test film »
![image](https://user-images.githubusercontent.com/14964443/84901464-cccb6780-b0ab-11ea-84df-d36ccfa9a719.png)

- [ ] Numbers should be American style > eg: « €10,000 Algeria»
- I’ve selected « Box office in $ » for world and it’s shown in euros
![image](https://user-images.githubusercontent.com/14964443/84901512-e10f6480-b0ab-11ea-91e8-88d9ddc696a3.png)
![image](https://user-images.githubusercontent.com/14964443/84901522-e2d92800-b0ab-11ea-9f1d-2c06f206db60.png)
![image](https://user-images.githubusercontent.com/14964443/84901534-e5d41880-b0ab-11ea-9047-7f71011a14be.png)

- [ ] there is an extra space before the _"_ eg: "quote" 
- [ ] Add the url in parenthesis after the quote separated with a space > eg: revue "quote" (url)
![image](https://user-images.githubusercontent.com/14964443/84901569-f7b5bb80-b0ab-11ea-9d17-221bd637dee9.png)

- [ ] Add commas between each version except for the last one > eg here: « Azerbaijani: Closed-Captions, Dubbed, Original, Subtitled »
![image](https://user-images.githubusercontent.com/14964443/84901705-259b0000-b0ac-11ea-8765-517e669327dd.png)

- [ ] **/!\ Check with the media team if they're already on this /!\**  Presentation Deck & Scenario where uploaded but nothing found in summary
![image](https://user-images.githubusercontent.com/14964443/84901868-567b3500-b0ac-11ea-9418-019c661abf3b.png)
![image](https://user-images.githubusercontent.com/14964443/84901884-59762580-b0ac-11ea-9c2d-790c1c2f8a84.png)
![image](https://user-images.githubusercontent.com/14964443/84901891-5b3fe900-b0ac-11ea-9d23-58435ab22be4.png)

**Comment by Mussuranae** [comment]
For the file name that doesn't appear, I wait the media team finishes the work on the media to update the view if needed.

**Comment by Jackseed** [comment]
- [ ] Lobby page, the text after start button is not centered 
![image](https://user-images.githubusercontent.com/14964443/92730849-a2204080-f374-11ea-86b4-91a4672fe636.png)
vs https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/428012744/preview?scrollOffset=1274
