### ISSUE TITLE
Debug - Shared Services

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2785]
This issue will gather on comments all the bugs to fix on shared services, namely:
- Account
- Movie Cards 
- Filters
- ...

**Comment by maltmayer** [comment]
MARKETPLACE > TITLE LIST > "Sort by"
- [ ] Delete "All films" from list (keep Title and Director).

MARKETPLACE > TITLE LIST > filters
- [ ] For dark theme, lists are hard to distinguish visually from other filters @vwmathilde 
![image](https://user-images.githubusercontent.com/55785823/82191934-8a1f3f80-98f3-11ea-9cc0-d39c9877b04b.png)

**Comment by Jackseed** [comment]
outdated issue > closed
