### ISSUE TITLE
MatLayout listen on resizing event

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#2787]
@GrandSchtroumpf created four directives which helps us to order our content in the app. The directives were created in respect of the material layout design [doc](https://material.io/design/layout/responsive-layout-grid.html#columns-gutters-and-margins)

The directive can be found in `blockframes/libs/ui/src/lib/layout/layout.module.ts`
And an example of how it could be used is found here `blockframes/libs/ui/src/lib/carousel/carousel.stories.ts`

We want the `layout` directive on our `mat-sidenav-content` component so every child of this component got the correct size and margin. But what happen if the window resizes, there is no resize event on the `mat-sidenav-content`. So if the window resizes, the directive won't get notify for recalculation. 
```
​
  ngOnInit() {
    const el = this.el.nativeElement;
    if (ResizeObserver) {
      this.observer = new ResizeObserver(([ entry ]) => this.width.next(entry.contentRect.width));
      this.observer.observe(el);
    } else {
      // do something with window:resize
    }

// Can be found in layout.module.ts
``` 
# Acceptance
- [ ] Find a way to notify the directive for recalculation.

**Comment by GrandSchtroumpf** [comment]
Currently this resize is managed by the `ResizeObserver`. The only browser that doesn't support it is Firefox for Android & IE... Also I don't expect the main view to resize on a mobile. So I think it's actually ok.
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

**Comment by Jackseed** [comment]
@GrandSchtroumpf @fritzschoff so do we close this issue?

**Comment by GrandSchtroumpf** [comment]
Yes I think we can
