### ISSUE TITLE
Event Reminder emails

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2793]
- [ ] Create automated reminder emails for events 

- is it possible to differentiate screenings and other events ? 
- and is it possible to add the timeframe set by the sales agent for the screening as a variable specified in the email ? to specifiy "you have ((timeframe)) to launch the film"

**Comment by fritzschoff** [comment]
@Jackseed if we need this feature we need to create a proper issue out of it with creating email template etc...

**Comment by Jackseed** [comment]
@fritzschoff Here is more details:
- we need to implement 2 mails: 
1. 24h before the screening - Template ID: d-0c7bcb6e4a234ddc95ed74b9ecc433dc
2. 1h before the screening (this one will be also implemented for meetings) - Template ID: d-8a9439a404cc4b51887e9dea44f7fbd7 

They are referenced at the bottom of Marie suggestion tab [here](https://docs.google.com/spreadsheets/d/1b1K7YfnquxnfCgGGPxIz5ZNIjr9eK_bUrRJqLvPYGIk/edit#gid=97734814).
