### ISSUE TITLE
Handle multiple video upload for a given movie

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#2796]
Right now we can upload only one video for a given movie.
Uploading another video will overwrite the first one.

In the future we will need a way to handle several videos (trailers, full movie, etc...)

- [ ] refactor UI to let the user upload several videos and manage witch video is what
- [ ] refactor UI of event to let the user choose what video to display in a screening for a given movie
- [ ] refactor backend & data-model (`movies/ID/hostedVideo`) to handle that

**Comment by pldespaigne** [comment]
@Jackseed @phpgeekfr @GrandSchtroumpf what are your thoughts about that ?

**Comment by phpgeekfr** [comment]
ok with something like that `movies/ID/hostedVideo`.  right now the video id is not attached on movieDocument ?

**Comment by pldespaigne** [comment]
right now we have :
1) on firebase storage we store the video file under `movies/ID/hostedVideo`
2) we upload this file to JWPlayer, this create a JWPlayer ID
3) on firestore we save this JWPlayer id in the movie document under the key `hostedVideo`

is it clearer ?

**Comment by phpgeekfr** [comment]
Thanks, I will update draw.io
