### ISSUE TITLE
MAINTENANCE - Movie lists

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2799]

**Comment by pldespaigne** [comment]
![image](https://user-images.githubusercontent.com/5858657/82422380-a7364880-9a82-11ea-95cc-4ca13fbcf11a.png)

**Comment by maltmayer** [comment]
- [ ] correct "Library" to "On the market today" 
![image](https://user-images.githubusercontent.com/55785823/82428735-3cd5d600-9a8b-11ea-9e4c-534d6df6fd90.png)

**Comment by maltmayer** [comment]
- [ ] dark theme "minimum budget" component color not adapted. can't see it
![image](https://user-images.githubusercontent.com/55785823/82428948-81fa0800-9a8b-11ea-8b62-16b82a4e20d4.png)

- [ ] "minimum budget" should be the other way around (orange on the right, not on the left)
![image](https://user-images.githubusercontent.com/55785823/82429062-a3f38a80-9a8b-11ea-8c7c-38efb1acf6d8.png)

**Comment by Jackseed** [comment]
- [ ] Sales agent filter not working, the behavior we want is:
- to list the orgs with appAcess dashboard festival
- when an org is selected to display only films from the movieIds of the selected org that have appAccess festival true
![image (28)](https://user-images.githubusercontent.com/14964443/82684885-9be64700-9c53-11ea-8cd4-73bddd70a9e1.png)
![image (27)](https://user-images.githubusercontent.com/14964443/82684893-9e48a100-9c53-11ea-850f-a1b1ae91f85c.png)

**Comment by Jackseed** [comment]
- [ ] On the search banner, we should use white text color (same as on landing page banner) so the color is ok on both light + dark thems
![image](https://user-images.githubusercontent.com/14964443/82688207-c090ed80-9c58-11ea-99d6-9f4c56a647fd.png)

**Comment by maltmayer** [comment]
DASHBOARD movie list / NO TITLE

- [ ] wrong "import your titles in bulk" logo for dark theme

- [ ] Correct text : Title : "You have no title yet." / after that : "You haven't imported titles yet. You may add several titles at once through bulk import, or just one at a time." Don't forget the period points at the end of sentences please.
![image](https://user-images.githubusercontent.com/55785823/82894137-617df200-9f52-11ea-8902-8d26ea34f375.png)

DASHBOARD movie list / WITH TITLES
- [ ] change "# View" to "# Views" with an "s"

- [ ] Change icon for « import movies » from this "text document" to "excel document" (to show them that it’s an excel import)
![image](https://user-images.githubusercontent.com/55785823/82902372-a78d8280-9f5f-11ea-9dc7-5483320c9dc9.png)
![image](https://user-images.githubusercontent.com/55785823/82902386-ab210980-9f5f-11ea-92cc-2286fc8172cc.png)

**Comment by maltmayer** [comment]
MARKETPLACE MOVIE LIST
Why are the information on the movie card 1. not in capital ? 2. with "..." at the end.
That's weird
![image](https://user-images.githubusercontent.com/55785823/82903103-bf193b00-9f60-11ea-8f90-9303a7f610ea.png)

**Comment by maltmayer** [comment]
- [ ] "On the market today" too small
- [ ] "Sort by" doesn't work
![image](https://user-images.githubusercontent.com/55785823/82904862-5b444180-9f63-11ea-8b36-a0ace827c944.png)
https://projects.invisionapp.com/d/#/console/19607961/413928510/preview

**Comment by maltmayer** [comment]
Marketplace movie list

- [ ] clickable area shouldn't be just the small "View more" area. Should be the whole poster (except for the heart for the wishlist of course) and the film title also
![image](https://user-images.githubusercontent.com/55785823/82926090-f860a380-9f7e-11ea-9409-c172f1128a7e.png)

**Comment by maltmayer** [comment]
- [ ] No film appear on this page but they are on firebase...
![image](https://user-images.githubusercontent.com/55785823/83144718-10a5ff00-a0f4-11ea-9111-5c10622e0758.png)

**Comment by maltmayer** [comment]
- [ ] poster size adaptation problem
When I unzoom, I get different sizes of images, it's chaotic
![image](https://user-images.githubusercontent.com/55785823/83781850-5da74980-a68f-11ea-9d39-9ea272517438.png)
