### ISSUE TITLE
MAINTENANCE - Movie views

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2801]

**Comment by Mussuranae** [comment]
Marketplace :
- [Contact](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/409944635/preview?scrollOffset=114)
- [Line-Up](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/409949583/preview?scrollOffset=114)
- [Screening list](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/412878490/preview?scrollOffset=114)

**Comment by Jackseed** [comment]
- [ ] Looks like the "header" is a bit buggy
![image](https://user-images.githubusercontent.com/14964443/82689966-a1478f80-9c5b-11ea-826b-04f17f418c14.png)

**Comment by Jackseed** [comment]
- [ ] Dashboard side use label not slug for movie type (feature_film on the screenshot) 
- [ ] remove the extra space after "Ireland" in the example (can't know what this is .. origin countries?)
![image](https://user-images.githubusercontent.com/14964443/82689988-b3293280-9c5b-11ea-9cd5-c34cfee226e3.png)

**Comment by Jackseed** [comment]
- [ ] Dashboard side on the movie header, we should add a CTA button "Publish to Marketplace" on the top right corner that switch storeConfig from draft to accepted
If the film is already accepted, button should be disable with the text "Published to Marketplace"

**Comment by maltmayer** [comment]
- [ ] missing "running time" on Dashboard and Marketplace
![image](https://user-images.githubusercontent.com/55785823/82925845-99029380-9f7e-11ea-8b53-23793da3a0ff.png)
![image](https://user-images.githubusercontent.com/55785823/82925887-a91a7300-9f7e-11ea-98c9-b21f7098c6c9.png)

**Comment by maltmayer** [comment]
- [ ] Same issue as org view: sometimes, the temporary toolbar stays stuck, the main toolbar doesn't come back
![image](https://user-images.githubusercontent.com/55785823/82926238-2cd45f80-9f7f-11ea-9776-9f541f92f9bf.png)

**Comment by maltmayer** [comment]
- [ ] Missing "General information" between "storyline elements" and "festivals"

![image](https://user-images.githubusercontent.com/55785823/82926413-758c1880-9f7f-11ea-8b9f-9aae61885e58.png)
![image](https://user-images.githubusercontent.com/55785823/82926456-82107100-9f7f-11ea-96e4-f2a9c9665cdd.png)

**Comment by maltmayer** [comment]
I got a bug after editing information on film details (through movie tunnel).
After I saved, I got that: 
![image](https://user-images.githubusercontent.com/55785823/83006496-9b163200-a012-11ea-9650-fac87a3339b0.png)
no tool bar no side bar, I was stuck

**Comment by maltmayer** [comment]
- [ ] delete extra space between cast first and last name
![image](https://user-images.githubusercontent.com/55785823/83007021-58088e80-a013-11ea-8d90-58d087af2e74.png)

- [ ] Version display still has a problem
![image](https://user-images.githubusercontent.com/55785823/83006995-4f17bd00-a013-11ea-9e49-e7acc14c81d4.png)

**Comment by Mussuranae** [comment]
I can't add the button for the release, it's too complicated because of the form in the child component. Also, I didn't have time to work really on the problem of the toolbar animation that stucks sometimes. I don't see anything wrong in the code and it will take time to investigate more. Sorry for that.

**Comment by maltmayer** [comment]
- [ ] Sales agent name is not the same color in dark mode and light mode. Should keep the dark mode one
![image](https://user-images.githubusercontent.com/55785823/83261707-16ffae00-a1bc-11ea-8b34-8e553c1ae43e.png)
![image](https://user-images.githubusercontent.com/55785823/83261698-136c2700-a1bc-11ea-87d0-bda919b2ce6c.png)

**Comment by maltmayer** [comment]
- [ ] a field should not appear if empty
![image](https://user-images.githubusercontent.com/55785823/83749965-dba22b00-a664-11ea-87f0-19fe27e1278d.png)
