### ISSUE TITLE
MAINTENANCE - Movie import

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2802]

**Comment by pldespaigne** [comment]
![image](https://user-images.githubusercontent.com/5858657/82422620-f67c7900-9a82-11ea-9d66-2f129b114dd7.png)

https://projects.invisionapp.com/d/main#/console/19607961/413904542/preview

**Comment by Jackseed** [comment]
- [ ] can't create the movies when selecting all the films + "Publish to Marketplace" on top
- [ ] on each line the Publish to Marketplace button is disabled
![Found 5 movie(s)](https://user-images.githubusercontent.com/14964443/82888396-8883f600-9f49-11ea-9604-f7511f6ff3c7.png)

**Comment by maltmayer** [comment]
- [ ] wrong "import your titles in bulk" logo for dark theme

- [ ] Correct text : Title : "You have no title yet." / after that : "You haven't imported titles yet. You may add several titles at once through bulk import, or just one at a time." Don't forget the period points at the end of sentences please.
![image](https://user-images.githubusercontent.com/55785823/82894137-617df200-9f52-11ea-8902-8d26ea34f375.png)
