### ISSUE TITLE
MAINTENANCE - Org view

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2804]

**Comment by Mussuranae** [comment]
[Marketplace](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/413933528/preview?scrollOffset=1653)

**Comment by Mussuranae** [comment]
So on the screening schedule tag, the button `add to my calendar` or `ask for an invitation` works, but the user can accept or decline his own demand....

**Comment by Jackseed** [comment]
@Mussuranae yep it's gonna be changed so you can't ;)
new issue:
- [ ] On tab line-up, only display movies from the org that have appAccess `festival: true` + storeConfig `accepted`

**Comment by Jackseed** [comment]
- [ ] On tab Screening schedule, add a link on the title event to the event page

**Comment by Jackseed** [comment]
- [ ] Add a snackbar when the user clicks on "Ask for invitation" (1), "Add to my calendar" (2), "Accept invitation" (3) or "Decline invitation" (4), respectively:
1. "Request sent." (+ if easy "More details" button on the right linking to the invitations page `/c/o/marketplace/invitations`)
2. "Event added." (+ if easy "More details" button on the right linking to the calendar page `/c/o/marketplace/event/calendar`)
3. "Invitation declined" (not sure it creates a notif/invitation, if yes, add a link also to the correct page)
4. "Invitation accepted" (not sure it creates a notif/invitation, if yes, add a link also to the correct page)

**Comment by Jackseed** [comment]
- [ ] I added a public screening to my calendar and the action buttons changed for accept / decline invitation > should be "Added to calendar" instead with a primary color on the button
![image](https://user-images.githubusercontent.com/14964443/82678358-c59a7080-9c49-11ea-9709-be5d1ef0e5dc.png)

**Comment by Mussuranae** [comment]
Send a meeting request works, but the request is a invitation and doesn't appear very well on the invitation page (there is no information about the event, only 'you have been invited to an event').
Meeting doesn't appear on calendar also

**Comment by maltmayer** [comment]
- [ ] header / tool bar bug. sometimes the "temporary" tool bar gets stuck and we can't go back to seeing the "main" toolbar (+ it looks like we're connected as the sales agent we're looking at)
![image](https://user-images.githubusercontent.com/55785823/82911169-dad60e80-9f6b-11ea-9398-ef55759c48ea.png)

ASK FOR A MEETING
- [ ] Meeting request doesn't work. Might just be demo mode, I don't know, but nothing happens when I click "Request meeting"

**Comment by maltmayer** [comment]
- [ ] shouldn't be able to click on "Contact Sales Agent" if there is no email address connected

**Comment by Mussuranae** [comment]
For the request a meeting, it creates an invitation to the admin of the org. If you connect to the org admin account after sending a meeting request, you must see an new invitation.
I will add a snackbar `An invitation has been sent to the org`.

**Comment by Jackseed** [comment]
@Mussuranae we decided to remove the "Ask for a Meeting" tab as it has a lot of UX issues on that and it's not really helping the users. 
So can you please:
- [ ] Remove the tab Ask for a Meeting
- [ ] Rename Get in touch with "Ask for a meeting"
- [ ] When you click on the Ask for a meeting button, it should open the mail app (so mailto?), addressed to the contact email of the org (as it is currently for the Get in touch button) BUT, if possible, the object of the mail should be: 
“Meeting request from [Name Lastname] via Archipel Market”

**Comment by Jackseed** [comment]
- [ ] Not sure if it's something doable quickly but could we use this banner picture by default on the header? 
![image](https://user-images.githubusercontent.com/14964443/83032368-07565d00-a036-11ea-95fd-4b0dda2ee81f.png)

**Comment by Jackseed** [comment]
- [ ] There are some extra spaces between street address, country, .. 
![image](https://user-images.githubusercontent.com/14964443/83164803-f2003200-a10c-11ea-8f10-d62241d23ef7.png)
