### ISSUE TITLE
MAINTENANCE - Homepage dashboard

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2805]

**Comment by maltmayer** [comment]
- [ ] Archipel Market logo is blurred. change to better quality
- [ ] Archipel Market logo changes color in dark / light theme. should stay the same (I like the dark theme logo better)
![image](https://user-images.githubusercontent.com/55785823/82426230-e1eeaf80-9a87-11ea-80c4-0dcb549ff525.png)
![image](https://user-images.githubusercontent.com/55785823/82426270-ec10ae00-9a87-11ea-9894-39a6419d095c.png)

**Comment by maltmayer** [comment]
- [ ] wrong "import your titles in bulk"  logo for dark theme

- [ ] Correct text : Title : "You have no title yet." / after that : "You haven't imported titles yet. You may add several titles at once through bulk import, or just one at a time." Don't forget the period points at the end of sentences please. 

![image](https://user-images.githubusercontent.com/55785823/82425227-83750180-9a86-11ea-842b-06f6ea9a7726.png)

**Comment by maltmayer** [comment]
Why did this logo change? does it have to be the same as "Import titles" in "My Titles" ?? (movie list)
![image](https://user-images.githubusercontent.com/55785823/83045312-b0f11a80-a045-11ea-90cc-0ee574f750f3.png)
Previous logo was better

**Comment by Hugo-Hontans** [comment]
movies must be "accepted"

**Comment by maltmayer** [comment]
- [ ] Add space between text and boxes : empty dashboard page should be the same as empty titles page with same spacing.
![image](https://user-images.githubusercontent.com/55785823/83250160-f88fb780-a1a7-11ea-970b-b0ead3928ee9.png)

![image](https://user-images.githubusercontent.com/55785823/83250154-f4639a00-a1a7-11ea-93b0-c43c90f83ac0.png)
