### ISSUE TITLE
MAINTENANCE - Landing page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2807]

**Comment by maltmayer** [comment]
- [ ] Correct "Login / Sign in" > "Log in / Sign up"
![image](https://user-images.githubusercontent.com/55785823/82428496-e1a3e380-9a8a-11ea-8ae7-74821f04aa0e.png)

**Comment by maltmayer** [comment]
- [ ] Missing the IFCIC logo
![image](https://user-images.githubusercontent.com/55785823/82686548-4f503b00-9c56-11ea-83c0-5088e96ea7bb.png)

https://projects.invisionapp.com/d/#/console/19607961/413916191/preview
![image](https://user-images.githubusercontent.com/55785823/82686660-7ad32580-9c56-11ea-8572-0e3ed5290187.png)

**Comment by maltmayer** [comment]
- [ ] default theme should be light, not dark

- [ ] toolbar logo is too light for the light version
![image](https://user-images.githubusercontent.com/55785823/82914789-3aceb400-9f70-11ea-8033-fd75a824c109.png)
should be same color as the rest of the toolbar I think

- [ ] Archipel Market logo in the footer (before partner logos) is not great quality
![image](https://user-images.githubusercontent.com/55785823/82914934-66519e80-9f70-11ea-88ec-544a6dd21cda.png)

**Comment by Jackseed** [comment]
- [ ] Image logo, feature images and CNC + IFCIC logos broken on staging
![image](https://user-images.githubusercontent.com/14964443/83001564-39eb6000-a00c-11ea-8e8d-fad0a73addb0.png)
![image](https://user-images.githubusercontent.com/14964443/83001638-525b7a80-a00c-11ea-8a52-31b0ef47037d.png)

![image](https://user-images.githubusercontent.com/14964443/83001627-4f608a00-a00c-11ea-9e3f-4a996824f305.png)

**Comment by maltmayer** [comment]
- [ ] there should be more space after the Archipel Market logo (same amount of space between  "Proudly associated with the following partners"  and the other logos and Archipel Market logo and  "Proudly associated with the following partners")
![image](https://user-images.githubusercontent.com/55785823/83143957-ff102780-a0f2-11ea-8ade-b1a7c7623285.png)

**Comment by maltmayer** [comment]
- [ ] Replace "The endless film market" with "The ongoing film market"
