### ISSUE TITLE
MAINTENANCE - Wishlist

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2808]

**Comment by maltmayer** [comment]
- [ ] Empty wishlist : CTA should say "Explore the Marketplace"
![image](https://user-images.githubusercontent.com/55785823/82432561-870d8600-9a90-11ea-94c1-9cc48532af2c.png)

**Comment by maltmayer** [comment]
- [ ] Wishlist doesn't work on side bar

**Comment by maltmayer** [comment]
- [ ] I just realized that a wishlist was shared by all members of an org. Should be individual

**Comment by Jackseed** [comment]
> * [ ]  I just realized that a wishlist was shared by all members of an org. Should be individual

this is a feature request
