### ISSUE TITLE
MAINTENANCE - Login / Creation flow

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2809]
- [ ] Login 
- [x] Forgot password
- [x] session terminated on logout? cannot create account or login after
- [x] If you are not logged and try to access a page with auth guard (https://archipelcontent.com/c/o/marketplace/search for example) you get a blank page instead of beeing redirected to /

**Comment by Jackseed** [comment]
- [ ] change the url `/auth/connexion#signin` for `/auth/connexion#login`

**Comment by maltmayer** [comment]
- [ ] Correct text + go to line at the end of sentences
« It seems to be your first time using one of the Blockframes applications. 
To create your account, we need to make sure that you’re attached to a company. 
Please choose an option below: » 
![image](https://user-images.githubusercontent.com/55785823/82688048-7f98d900-9c58-11ea-863c-5060bace776c.png)

**Comment by maltmayer** [comment]
- [ ] Correct text:
"Thank you for creating your organization!
You’ll receive an email confirmation once your organization is validated.
Thank you for your patience."

- [ ] Delete CTA 'Go to marketplace"

![image](https://user-images.githubusercontent.com/55785823/82688466-3bf29f00-9c59-11ea-8276-eeb4c0a3b714.png)

![image](https://user-images.githubusercontent.com/55785823/82688213-c4247480-9c58-11ea-84c2-2619347bc075.png)

**Comment by Jackseed** [comment]
- [ ] Redirect connected user that goes to landing page to homepage

**Comment by phpgeekfr** [comment]
`If you are not logged and try to access a page with auth guard (https://archipelcontent.com/c/o/marketplace/search for example) you get a blank page instead of beeing redirected to /` This seems to be corrected already

**Comment by phpgeekfr** [comment]
@Jackseed `Redirect connected user that goes to landing page to homepage`. What is the landing page please ?

**Comment by Jackseed** [comment]
- [ ] Add this message on the snackbar error when a user tries to create an already existing account:
"An account already exists for this email address. 
If you don't remember your password, please reset it or try searching in your past emails. You might have received an invitation containing credentials to join Archipel."
+ if possible link to the reset password page on "please reset it"

**Comment by Jackseed** [comment]
> @Jackseed `Redirect connected user that goes to landing page to homepage`. What is the landing page please ?
@phpgeekfr 
it's www.archipelmarket.com or www.archipelcontent.com

**Comment by phpgeekfr** [comment]
> > @Jackseed `Redirect connected user that goes to landing page to homepage`. What is the landing page please ?
> > @phpgeekfr
> > it's [www.archipelmarket.com](http://www.archipelmarket.com) or [www.archipelcontent.com](http://www.archipelcontent.com)

So the homepage can be `/c/o/marketplace/home` or `/c/o/dashboard/home` ?

**Comment by maltmayer** [comment]
This is low priority, I know, but this page is really way too big. I feel oppressed when I'm on it.
Here is the 100% view where I have to scroll down to sign up (which is unnecessary, for the amount of info we ask the user) + illustration is cut
![image](https://user-images.githubusercontent.com/55785823/82917889-49b76580-9f74-11ea-845c-e071cc8a197f.png)
Would it be possible to have something more "airy" like this. 
![image](https://user-images.githubusercontent.com/55785823/82918067-7ff4e500-9f74-11ea-9089-d25bac41c288.png)

**Comment by Jackseed** [comment]
- [ ] If possible as a quickwin, see #2741

**Comment by maltmayer** [comment]
This illustration looks weird. Is it the right one that's supposed to be here?
![image](https://user-images.githubusercontent.com/55785823/83242486-cc226e00-a19c-11ea-9486-f9786b0b95d0.png)

**Comment by Jackseed** [comment]
> This illustration looks weird. Is it the right one that's supposed to be here?
> ![image](https://user-images.githubusercontent.com/55785823/83242486-cc226e00-a19c-11ea-9486-f9786b0b95d0.png)

Yep https://projects.invisionapp.com/d/main?origin=v7#/console/19273040/405393351/preview?scrollOffset=1446.666748046875
