### ISSUE TITLE
MAINTENANCE - Org settings 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2810]

**Comment by maltmayer** [comment]
- [ ] This message should tell the user what field is not valid. Or highlight invalid field in red in the form
![image](https://user-images.githubusercontent.com/55785823/82433136-4e21e100-9a91-11ea-963c-ac08b7e9ba7c.png)

**Comment by Jackseed** [comment]
- [ ] Same as @maltmayer above but also wondering what is the error comes from as all the fields are filled
![image](https://user-images.githubusercontent.com/14964443/82687724-f5507500-9c57-11ea-8968-3c012d0032ea.png)

**Comment by Jackseed** [comment]
- [ ] looping error on tab Member
```
ypeError: Cannot read property 'length' of null
    at TableFilterComponent_div_5_Template (table-filter.component.html:33)
    at executeTemplate (core.js:7575)
    at refreshView (core.js:7452)
    at refreshDynamicEmbeddedViews (core.js:8515)
    at refreshView (core.js:7472)
    at refreshComponent (core.js:8579)
    at refreshChildComponents (core.js:7255)
    at refreshView (core.js:7498)
    at refreshComponent (core.js:8579)
    at refreshChildComponents (core.js:7255)
````

**Comment by maltmayer** [comment]
- [ ] correct text in snack bar to "Organization profile was successfully changed"
![image](https://user-images.githubusercontent.com/55785823/83004346-d82cf500-a00f-11ea-93bd-f897dffff47e.png)

**Comment by maltmayer** [comment]
- [ ] "World" shouldn't be an option in the address part, for countries

**Comment by maltmayer** [comment]
- [ ] same problem (that @Mussuranae sorted for Org view): country should have capital letter
![image](https://user-images.githubusercontent.com/55785823/83027226-28b44a80-a030-11ea-964f-3f9b34faed25.png)

**Comment by maltmayer** [comment]
- [ ] country still appears without capital letter
- [ ] user position (here Archipel Market Concierge) shouldn't be in bold I think
![image](https://user-images.githubusercontent.com/55785823/83735795-1b5f1780-a651-11ea-99b3-f437e204f68e.png)

**Comment by maltmayer** [comment]
- [ ] Missing element in "Activity description" list : Inflight
![image](https://user-images.githubusercontent.com/55785823/84160660-b8191f00-aa6e-11ea-8449-3c097ef4d2b5.png)

**Comment by maltmayer** [comment]
Just so we have this written down somewhere : 
A user should be able to select multiple activities + enter "other"
