### ISSUE TITLE
MAINTENANCE - Event view

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2813]

**Comment by maltmayer** [comment]
Marketplace event view / Accepted invitation / Before event time
- [ ] There should be a CTA to access screening room (even before the right time) : https://projects.invisionapp.com/d/#/console/19607961/412246439/preview

Marketplace event view / Accepted invitation / Event time
- [ ] I noticed that CTA does appear at event time. But it is not clickable, so there's no way to access the screening room through the marketplace
![image](https://user-images.githubusercontent.com/55785823/82925400-f64a1500-9f7d-11ea-8c0a-45bf2ecef1be.png)

**Comment by maltmayer** [comment]
Careful, I can still access the session link when the session is finished
![image](https://user-images.githubusercontent.com/55785823/83260023-58db2500-a1b9-11ea-8bfc-958455a084fd.png)

**Comment by maltmayer** [comment]
- [ ] Correct "Screening done" to "Session Closed"
![image](https://user-images.githubusercontent.com/55785823/83496974-1e73cf80-a4ba-11ea-87fe-9408dc571334.png)
