### ISSUE TITLE
MAINTENANCE - Event session

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2814]

**Comment by Jackseed** [comment]
@GrandSchtroumpf 
- [ ] the illustration doesn't fit entirely the window
![image](https://user-images.githubusercontent.com/14964443/82678640-3c376e00-9c4a-11ea-8514-cd24ad88b067.png)

**Comment by GrandSchtroumpf** [comment]
> the illustration doesn't fit entirely the window
I'm not sure to understand what's the issue here. But for responsive / image quality issues, this is the best we came out with @Mussuranae

**Comment by Jackseed** [comment]
Ok then, also is it possible to center the spinner on the player?
![image](https://user-images.githubusercontent.com/14964443/82686442-25971400-9c56-11ea-9b0e-910dd2b4f102.png)

**Comment by Jackseed** [comment]
- [ ] On the meeting session, the link must be absolute, here it's relative to archipelmarket.com so if I feel `zoom.us/myMeeting` on the url I'm redirected to `archipelmarket.com/zoom.us/myMeeting`

**Comment by Jackseed** [comment]
- [ ] Ask @vwmathilde for the good illustration on meeting session (currently it's the same as screening)

**Comment by maltmayer** [comment]
- [ ] the bottom part should disappear after a few seconds, to get a "real" full screen 
![image](https://user-images.githubusercontent.com/55785823/83497224-74e10e00-a4ba-11ea-98fa-978ce9bac8f1.png)
