### ISSUE TITLE
MAINTENANCE - Notifications

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2815]

**Comment by pldespaigne** [comment]
![image](https://user-images.githubusercontent.com/5858657/82421680-a4872380-9a81-11ea-970b-fcc044692cb5.png)

**Comment by pldespaigne** [comment]
Notion : https://www.notion.so/cascade8/Invitations-and-Notifications-1721854686a34230ab04079f7ab977dc

**Comment by maltmayer** [comment]
- [ ] For the empty activity feed, Correct text to : Title "You have no notification." / after that : "You haven't received any notifications yet." Please don't forget the period points at the end of the sentences.
![image](https://user-images.githubusercontent.com/55785823/82431113-870c8680-9a8e-11ea-82d1-fa7cfa2000f6.png)

**Comment by Jackseed** [comment]
- [ ] Loading issue, when just connected, if I go on /notifications the page is empty, if I reload, notifications appear 
![image](https://user-images.githubusercontent.com/14964443/82689495-d9020780-9c5a-11ea-8fea-25432d245cc0.png)
![image](https://user-images.githubusercontent.com/14964443/82689510-df907f00-9c5a-11ea-800b-5f66d7a24c4e.png)

**Comment by maltmayer** [comment]
- [ ] loading issue still happening. I have to refresh to get notifications
![image](https://user-images.githubusercontent.com/55785823/82919352-32797780-9f76-11ea-8e56-99afe8dbdcd4.png)

**Comment by pldespaigne** [comment]
@maltmayer  loading issue should be ok now, can you retry please ?

**Comment by maltmayer** [comment]
Yes it's good for Activity Feed loading.

Other comment: 
- [ ] This notification is not appropriate for Archipel Market. It was written for Archipel Content. 
Here it should just be "Your movie has been successfully uploaded to the Marketplace."
![image](https://user-images.githubusercontent.com/55785823/83024203-513b4500-a02e-11ea-8449-6c08b8ba9a21.png)

**Comment by maltmayer** [comment]
weird, Archipel didn't identify my first and last name in this notification
![image](https://user-images.githubusercontent.com/55785823/83051788-c28af000-a04e-11ea-9760-1aa1f94ac538.png)

**Comment by phpgeekfr** [comment]
- [ ] If I click on the "more details" links of a  "A new movie has been submitted"  notification I end up in a 404 error page.

**Comment by Jackseed** [comment]
- [ ] Change the text for the notification on movie storeConfig > accepted; currently it's
"Your movie was accepted by the Archipel team. It will now appear in..."
Instead it should be: "Your film is published on the marketplace."
