### ISSUE TITLE
MAINTENANCE - Invitations

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2816]

**Comment by maltmayer** [comment]
- [ ] Correct text : Title "You have no invitation." / after that : "You haven't received any invitation yet." Please don't forget the period points at the end of the sentences.

**Comment by Mussuranae** [comment]
During the maintenance of the org view, in the screening schedule tag, we can add a public screening in our calendar or ask for an invitation to a private screening. But this invitation can be accepted or declined by the user who asked for the invitation... We can see this together if you want.

**Comment by Jackseed** [comment]
- [ ] Invitations looked declined at first (I didn't click on the button and it's like that:

**Comment by Jackseed** [comment]
@Hugo-Hontans we've discussed this but I write here to be sure
- [ ] Change the invitation the user receives when he asks for a request. Currently:
![image](https://user-images.githubusercontent.com/14964443/82677633-9e8f6f00-9c48-11ea-844a-fdb0b595f250.png)
Change it for "Your request to attend the event has been sent + button "See event" linked to the event page and on the right a string status "Pending" / "Refused" / "Accepted"

**Comment by GrandSchtroumpf** [comment]
Concerning this specific subject I changed the observable in the invitation list. Im not sure if my PR will be ready by then so here is how it should look like : 
```typescript
// Invitation sent to you
invitations$ = this.query.selectAll({ filterBy: invitation => invitation.mode === 'invitation'});
// Invitation sen by you ("add to my calendar" or "request invitation")
requests$ = this.query.selectAll({ filterBy: invitation => invitation.mode === 'request'});
```

**Comment by maltmayer** [comment]
- [ ] Change the message when invitations are being sent to: 
"Your invitations are being sent. It might take a few seconds. 
Thank you for your patience."
- [ ] change field title from "search for a guest" to "invite guests"
- [ ] when an invitation is sent, the address should disappear from the invitation field, not stay in it
- [ ] shouldn't be able to send an invitation to someone who was already invited.
![image](https://user-images.githubusercontent.com/55785823/82893137-db14e080-9f50-11ea-98a3-8fe915cdde56.png)

- [ ] shouldn't be able to send invitation when there is no email in the field.

**Comment by maltmayer** [comment]
Invitations should specify details This list doesnt make sense if you don't have any information
![image](https://user-images.githubusercontent.com/55785823/82917031-22ac6400-9f73-11ea-8db2-0c282f6adbfe.png)

**Comment by phpgeekfr** [comment]
- [ ] If I click on the "more details" links of a notification "A new movie has been submitted" I end up in a 404 error page.
