### ISSUE TITLE
MAINTENANCE - Rules

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2817]

**Comment by Jackseed** [comment]
- [ ] Got permission denied while connecting on festival with wayne.massey@hart-caldwell.fake.cascade8.com; orgId sLchj1Ib4Cxhwr0ZBW4m switch to festival dashboard true by hand

**Comment by Jackseed** [comment]
- [ ] Got permission denied while connecting to the event session page of a public screening that I added to my calendar, though not blocking
![image](https://user-images.githubusercontent.com/14964443/82678532-0c886600-9c4a-11ea-84fb-2e0c651cf937.png)

**Comment by phpgeekfr** [comment]
Nothing to update so far. @Jackseed  Maybe we can close it and re-open a new one more specific if needed ?
