### ISSUE TITLE
MAINTENANCE - Emails

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2818]
- [x] add from email first name and last name (Archipel - Market for example)

**Comment by phpgeekfr** [comment]
Mail list and problems:

1. Notify admin(s) of app access changes : contain "festival" and "catalog" `templateIds.newAppAccessForOrg`

**Comment by phpgeekfr** [comment]
email list : https://docs.google.com/spreadsheets/d/1b1K7YfnquxnfCgGGPxIz5ZNIjr9eK_bUrRJqLvPYGIk/edit#gid=0
