### ISSUE TITLE
MAINTENANCE - Screening list

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2820]

**Comment by Mussuranae** [comment]
[InVision](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/413933528/preview?scrollOffset=1653)

**Comment by Mussuranae** [comment]
Nothing particular on this page, only button for invitation are not very well but we fixed this in an other PR with Hugo.

**Comment by Jackseed** [comment]
@Mussuranae @GrandSchtroumpf can one of you add an empty screening list state using the same illustration as always (spaceship) 
with the title "No screening has been scheduled at this point."
This must be set on the 3 locations of the screening list:
- [ ] General Screening list (menu > Screening list)
- [ ] Sales agent screening list (menu > sales agents > org > schedule tab)
- [ ] Film screening list (film > schedule tab)

**Comment by GrandSchtroumpf** [comment]
@Mussuranae Could you do that ? Sorry I don't have much time those days =="

**Comment by maltmayer** [comment]
- [ ] event title + "Private screening" should be clickable and lead to event page
![image](https://user-images.githubusercontent.com/55785823/82924530-c0f0f780-9f7c-11ea-8eb0-d02bb776c7c6.png)
