### ISSUE TITLE
[UX] Media ressources flows

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2832]
Different use cases are to be taken into account:
1. Video/ressource uploads (where and how)
2. Ressource management: where to find these ressources, how to change it, how to organize it
3. Ressource display: how can a user chose to display an existing ressource, on a static page (movie) or during a meeting

@fritzschoff @phpgeekfr & @pldespaigne will be the ones working on these implementations, @GrandSchtroumpf will help for the start

**Comment by pldespaigne** [comment]
Everything is detailed on the Meeting Master Issue #3639
