### ISSUE TITLE
Update MF wireframes

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2833]

**Comment by 2amarkina** [comment]
Check with @vwmathilde if such UI is possible for wireframes design validation : 

- [ ] check the design options for the "Overview" (production status)
- [ ] check if the name of tab tab "Investment & Waterfall" in Partner's dashboard can be used (check the question of text size)
- [ ] check the "Notes &  Statements" view in marketplace

**Comment by 2amarkina** [comment]
The update is done. Waiting for tests to pass to the next update.
