### ISSUE TITLE
we should use callbable functions to get the proper application used instead of guessing it with org id

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2848]

**Comment by phpgeekfr** [comment]
try to remove use of  `getFromEmail` and `getAppUrl`

**Comment by phpgeekfr** [comment]
idea: create _meta.updatedFrom ?

**Comment by Jackseed** [comment]
@phpgeekfr still an open issue? 
Looks connected to #5049

**Comment by phpgeekfr** [comment]
This is more a reminder than a real issue but yes it can be linked to #5049

**Comment by phpgeekfr** [comment]
@Mussuranae did a part of this issue in https://github.com/blockframes/blockframes/pull/5464 . Since this one is old and that main issues are solved in @Mussuranae PR, I'm closing this one
