### ISSUE TITLE
MAINTENANCE - Calendar page (marketplace + dashboard)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2849]
- [x] On marketplace side, clicked on an event that was happening right now and I've been routed to the event page instead of session page

**Comment by maltmayer** [comment]
- [ ] display problem : some lines are continuous, others broken
![image](https://user-images.githubusercontent.com/55785823/82888520-b36e4a00-9f49-11ea-9c38-d013d65f8fa2.png)

- [ ] Correct in the "sort by" list : "Screenings" and "Meetings" (with an "s")
![image](https://user-images.githubusercontent.com/55785823/82888656-e6184280-9f49-11ea-844f-22afa60c1ba9.png)
