### ISSUE TITLE
Org denomination public

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#2860]
Currently in the DB we have an `org.denomination.full` and `org.denomination.public`, but we ask to user only the `denomination.full` when they create their organization and also on the org form (profil of the organization).
We check everytime if we have the `denomination.public` in the code but it would be good to implement this `denomination.public`.
Ckeck Todo in the code.

**Comment by Jackseed** [comment]
This will be done only when we will invoice clients through the app, otherwise we don't need that information. I put it in Icebox for now

**Comment by phpgeekfr** [comment]
have both public and full is confusing, we should stick to only one denomination

**Comment by RemcoSimonides** [comment]
Let's tackle this issue posted by Bruce in [Release 4.2 - Organization](https://github.com/blockframes/blockframes/issues/8303#issuecomment-1120955514)

- [ ] updating org name does not update algolia indexes if org have denomination.full defined

on the form, input is for `denomination.full` 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/bc8975fe-39e3-4b5f-a7d9-2f194a3c47f8)

but `orgName` pipe displays `denomination.public`  by default (example in `<organization-display>`) and algolia is also updated with public denomination by default

linked with https://github.com/blockframes/blockframes/issues/2860

( NB: only old orgs have `denomiation.public` defined)

Quick fix would be to update both public and full denomination

**Comment by RemcoSimonides** [comment]
Moving this issue out of the icebox so we can start the discussion again

**Comment by Jackseed** [comment]
Closing that issue for now as in-app invoice is not on the roadmap for long
