### ISSUE TITLE
MAINTENANCE - General layout

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2866]
## Everywhere
- [x] Homogenize typo, all the titles and subtitles are not the same size => moved to #2928
- [x] On the tabs we have "Login - Archipel Market" everywhere, it should be only "Archipel Market"
![image](https://user-images.githubusercontent.com/14964443/83040382-7c7a6000-a03f-11ea-9180-4bb3e7757449.png)

## Dashboard
- [x] Add a "Buyers' Platform" link on the menu at the end of the list cf. 
https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/417497937/preview?scrollOffset=5245

**Comment by maltmayer** [comment]
Marketplace logo is not good quality (bit blurry)

![image](https://user-images.githubusercontent.com/55785823/82920025-132f1a00-9f77-11ea-8c15-9dcd8230362f.png)
![image](https://user-images.githubusercontent.com/55785823/82920052-1924fb00-9f77-11ea-9d77-d2d0b9e840ec.png)

**Comment by maltmayer** [comment]
I think I wrote that somewhere already but just wanted to make sure it didn't get lost: 
- [ ] There should be "My Calendar" in the marketplace side bar 
- [ ] Wishlist should be named "My Wishlist"
![image](https://user-images.githubusercontent.com/55785823/83021354-2c44d300-a02a-11ea-8d2c-1d0d3c30cc74.png)

**Comment by maltmayer** [comment]
- [ ] Is it possible to "pull up" the hear icon ? it really looks super low compared to other icons in the toolbar
![image](https://user-images.githubusercontent.com/55785823/83029357-e50f1000-a032-11ea-9483-2e37a415e274.png)

**Comment by phpgeekfr** [comment]
@maltmayer for the "My Calendar" link, should it redirect to /c/o/marketplace/event/calendar ?

**Comment by maltmayer** [comment]
@phpgeekfr Yep !

**Comment by phpgeekfr** [comment]
@maltmayer 
Do you have some examples pour those two points ?
```
Homogenize typo, all the titles and subtitles are not the same size
On the tabs we have "Login - Archipel Market" everywhere, it should be only "Archipel Market"
```
Thanks !

**Comment by phpgeekfr** [comment]
`in the tabs we have "Login - Archipel Market" everywhere, it should be only "Archipel Market"` seems to be corrected already
