### ISSUE TITLE
Festival - Update dynamic tab titles

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2869]
Do the same as for catalog following @2amarkina's doc

Use the dynamicTitleService on utils lib (@fritzschoff is the one who can help)

**Comment by 2amarkina** [comment]
Here's the document: 
https://docs.google.com/spreadsheets/d/1PjNR51a09b3m-qPRYWT_mBMcEoo7xKzoKXMbtBvk8kw/edit?usp=sharing
It's pretty much done for the Marketplace part. I'll make a sign when it's completely ready.

**Comment by pldespaigne** [comment]
solved by #3464
