### ISSUE TITLE
ARCHIPEL MARKET EVENT FORM "Delete event" protection

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2873]
- [ ] It is too easy to delete an event. There should be some kind of protection like a pop "Are you sure you want to delete this event? Guests will be notified." (if possible, guest should be notified. otherwise delete second part of the sentence)

**Comment by stephanie-cascade8** [comment]
Mockup here https://projects.invisionapp.com/d/#/console/20048194/434347464/preview

**Comment by Jackseed** [comment]
Duplicate with #3870
