### ISSUE TITLE
Auth relative routes cleaning

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2875]
Currently we have:
```
  { path: 'email-verification', component: EmailVerificationComponent},
  { path: 'password-reset', component: PasswordResetComponent}
```

But in fact, `email-verification` leads to password reset page and should be renamed to `password-reset` and  `password-reset` should be removed

**Comment by phpgeekfr** [comment]
`http://localhost:4200/auth/welcome` seems to be not used

**Comment by Jackseed** [comment]
@phpgeekfr is it still an open issue?
Re the welcome page, it should have been removed already

**Comment by phpgeekfr** [comment]
Yes still an issue. Low priority

**Comment by fritzschoff** [comment]
would close it in favor of the new upcoming connection flow? @phpgeekfr if you agree, can you close it pls?

**Comment by phpgeekfr** [comment]
ok
