### ISSUE TITLE
Refactor rules file

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2883]
check: 
https://medium.com/firebase-developers/imports-for-firestore-security-rules-are-the-best-26f0770ad23c

**Comment by fritzschoff** [comment]
@phpgeekfr I guess reworked the rules recently?

**Comment by phpgeekfr** [comment]
This article is showing how we can split rules into several files using `include "functions.rules";` 
We do not use this for now. This issue was kind of a reminder that we can use "includes".

You can close it or make it low priority
