### ISSUE TITLE
DESIGN REVIEW - Carrousel / Marketplace homepage

### ISSUE THREAD

**Issue by vwmathilde** [blockframes/blockframes#2912]
Carrousel : 
![image](https://user-images.githubusercontent.com/51743840/83264455-6647dd80-a1c0-11ea-8623-604f1de0132f.png)
- [x] Align title and first card
![image](https://user-images.githubusercontent.com/51743840/83264523-7e1f6180-a1c0-11ea-87b0-1760b16bc0a2.png)
- [ ] Basic button in primary
![image](https://user-images.githubusercontent.com/51743840/83264818-f25a0500-a1c0-11ea-85a6-2082be211920.png)
- [x] align button and card
![image](https://user-images.githubusercontent.com/51743840/83265302-980d7400-a1c1-11ea-8a92-607529e125c0.png)
- [x] 8px between H6 and picture
![image](https://user-images.githubusercontent.com/51743840/83265113-5b417d00-a1c1-11ea-85dd-1f937f7dba98.png)
- [x] put the buttons in the right place and they are fab buttons, not icons button
![image](https://user-images.githubusercontent.com/51743840/83265399-bf644100-a1c1-11ea-9b13-f64d176ccf2f.png)

![image](https://user-images.githubusercontent.com/39312833/83419249-1453c180-a425-11ea-8824-35718525e5c8.png)
@fritzschoff  :point_up: include here

**Comment by fritzschoff** [comment]
@vwmathilde  If I use the arrow buttons as fab buttons they will loose their transparency. Saying, they will have the primary or accent color. Meaning I have to override global styles. Are you sure that they are fab buttons?
Same as by `See all` they got a global set padding, which I can override locally, but this would cross the line of global style rule.

**Comment by vwmathilde** [comment]
> @vwmathilde If I use the arrow buttons as fab buttons they will loose their transparency. Saying, they will have the primary or accent color. Meaning I have to override global styles. Are you sure that they are fab buttons?
> Same as by `See all` they got a global set padding, which I can override locally, but this would cross the line of global style rule.

@fritzschoff I've two fab button : Fab and mini fab. Mini_fab are used on dashboard, and fab are bigger and transparency (for exemple, on login / signup page). Maybe, wrong fab are used actually ?

**Comment by fritzschoff** [comment]
ah okay, then I will try the bigger one! brb

**Comment by fritzschoff** [comment]
![image](https://user-images.githubusercontent.com/39312833/83417841-eff6e580-a422-11ea-9b5f-291e233b2987.png)
hmm... the mat-fab (big) are not transparent in the code. And in the login page they are not transparent anymore
![image](https://user-images.githubusercontent.com/39312833/83417980-216fb100-a423-11ea-94ff-cb7cabfaa960.png)

**Comment by fritzschoff** [comment]
I guess our code is not updated with your latest styles

**Comment by vwmathilde** [comment]
Oh :( 
I'll try to fixe it with someone this week :)
