### ISSUE TITLE
DESIGN REVIEW - Activity feed / marketplace

### ISSUE THREAD

**Issue by vwmathilde** [blockframes/blockframes#2918]
![image](https://user-images.githubusercontent.com/51743840/83274034-86ca6480-a1cd-11ea-8680-65c8f1001a57.png)
- [x] 24px margin bottom between H1 and Card element
- [x] it's missing card background

![image](https://user-images.githubusercontent.com/51743840/83274191-bb3e2080-a1cd-11ea-9f50-a661f395880b.png)
- [ ] too much margin between body-2 and caption. No margin

![image](https://user-images.githubusercontent.com/51743840/83274276-de68d000-a1cd-11ea-8634-2081c3c19de8.png)
- [x] I don't recommend using basic buttons here. Rather icon button with a label below caption

**Comment by Hugo-Hontans** [comment]
@vwmathilde I think the h1 is inside the mat-card, no ?
