### ISSUE TITLE
DESIGN REVIEW - Log in / Sign up

### ISSUE THREAD

**Issue by vwmathilde** [blockframes/blockframes#2938]
![image](https://user-images.githubusercontent.com/51743840/83416230-ad340e00-a420-11ea-9b2e-02ef1536edd9.png)
- [x] Wrong fab button. It should be like this
![image](https://user-images.githubusercontent.com/51743840/83416332-d18fea80-a420-11ea-9b5c-c43463aa1826.png)

![image](https://user-images.githubusercontent.com/51743840/83416834-92ae6480-a421-11ea-90f8-66a1d66f104d.png)
- [x] change check box color in primary
- [x] align center check box and text
- [x] wrong link color : primary 500, not primary 200

![image](https://user-images.githubusercontent.com/51743840/83417017-cdb09800-a421-11ea-9ee8-ae16f5046d0b.png)
- [x] too much margin bottom. 80px is enough

![image](https://user-images.githubusercontent.com/51743840/83417116-f33da180-a421-11ea-91cf-1de9013dfe78.png)
- [x] use link for "forget password", not a basic button.

![image](https://user-images.githubusercontent.com/51743840/83417446-6515eb00-a422-11ea-936a-e0e60cfbb3e3.png)
- [x] form background color in #ffffff
- [x] image background color #F4F4F4

**Comment by fritzschoff** [comment]
haha makes sense now @vwmathilde . Gonna take that

**Comment by vwmathilde** [comment]
You can find fab button spec here
https://zpl.io/bAJxWpq
https://zpl.io/VOwLA5L

**Comment by fritzschoff** [comment]
thanks!
