### ISSUE TITLE
Admin Panel - Analytics

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2952]
Update admin panel to add some analytics on users for the business development.
Here [are some examples](https://projects.invisionapp.com/d/main#/console/19564186/411037156/preview).
Check with @maltmayer the priorities 

- [x] be able to export orgs list into excel or csv
- [x] be able to export users list into excel or csv @phpgeekfr missing orgname & role
- [x] be able to export films list into excel or csv
- [x] be able to export event list into excel or csv
- [x] check https://docs.google.com/spreadsheets/d/1jckFAorLiD2TaZMG_FdoYO7ktCIStBRKgQP8eDKWmIA/edit#gid=7312071

- [x] @maltmayer reco in #2090 https://github.com/blockframes/blockframes/issues/2090#issuecomment-639395819

**Comment by phpgeekfr** [comment]
@Jackseed @maltmayer Can we schedule a demo so I can show you what I have done so far ?
