### ISSUE TITLE
[Component] list-actions

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#2954]
# Component
A generic component that display a list of elements with grouped actions.
For the dev team the goal would be to use the same component as much as possible. Here is a list of places where it could be used: 
- notification list
- invitation list (invitation received)

> This is a different component than the `search-list`.

---------------
## UI / UX decisions : 
- [ ] When to use a table over a list ?
- [ ] Define where the grouped actions vs individual actions should be.
- [ ] How to filter / sort the list ?
- [ ] In the case of list, define the type of data we can display in each line (the amount of lines avaiable, typography to use, avatar/logo pictures, ....).
- [ ] Define the state of each element (idle, selected, disabled, ...)

----------
## UI review
_remove this section once everything is checked_
- [ ] UI doesn't already have a existing component.
- [ ] Name display in Zeplin is the same as the one in the issue (see below).
- [ ] Data can be display like in the UI (see notion).
- [ ] A link to this issue in the zeplin object

## Implement Component
- [ ] Create story with storybook
- [ ] Connect component to Zeplin with zeplin-connect
```
update the components.json in blockframes/.zeplin/
{
    "path": "libs/ui/src/lib/slider/slider.component.ts",
    "zeplinNames": [
        "component/slider/archipel_content/movie-slider"
    ],
     "storybook": {
                "kind": "Movie Slider",
                "storybook": [
                    "Movie Slider"
                ]
            }
}
path leads to the component.ts file and zeplinNames are the matching names from this component in zeplin. 
Can be multiple names if there are different states of this component.
```

## Description

https://zpl.io/agY0BD9

- name: ...
- lib/app: ...

## Type
- [ ] **Layout**: _Structure a page with content projection (ex: MovieView)._
- [ ] **Page**: _Loaded by the router. Usually used in an app (ex: CatalogDashboardMovieView)._
- [x] **Component**: _Structure a piece of data in the page (ex: MovieTable)._
- [ ] **Display**: _Render data in a page. Can use a component-type (ex: MovieMain, MovieBudget)._
- [ ] **Form**: _Get data from the user (ex: MovieFormBudget)._

### Input
_can be data (movie, distribution right, ...), or UI related (dense, appearance)_
- [ ] ...

### Data view
_data displayed in the UI, derived from the inputs (ex: **title**: movie.main.title.international)
- [ ] ...

## Where is it used
-links and snapshots where the component is used_

**Comment by stephanie-cascade8** [comment]
Component available here 
https://zpl.io/agY0BD9

**Comment by GrandSchtroumpf** [comment]
Example : 
```html
<mat-list-item role="listitem">
  <mat-icon mat-list-icon>folder</mat-icon>
  <h3 matLine>Title</h3>
  <p matLine>Title</p>
  <div class="row" style="margin-right: 24px">
    <button mat-button>Add</button>
    <button mat-button>Remove</button>
  </div>
  <button mat-icon-button>
    <mat-icon>add</mat-icon>
  </button>
</mat-list-item>
```

**Comment by fritzschoff** [comment]
Hey @stephanie-cascade8 @2amarkina , 
I need more information about the different states of this component.
- What is happening when you click on share?
- What should happen if you click on See details?
- What should happen when you click on Mark as read => like what are the possibilities for a notification or an invitation? Is this triggering an email? If yes, what kind of?
- Is there a button in the header that accepts all / refuse all => Whats happening afterwards?

**Comment by 2amarkina** [comment]
1. For the **"share" fonction**. For the moment this action is not designed completely, but it might come soon. The idea was that a user could "share" this information with his organization's members. For the moment we can put it aside. 
2. When we **click on "see details"** . This information will depend on the info type. For exemple, if it is an invitation for a screening / meeting (functional invitation) -> user is directed to the page with details of screening / meeting. If it is info about organization, like "Name was added to org" then a user is directed to the page with his organization members. For this sprint i'm working on redefining of the notification structure and i could precise each type of info + redirections. 
3. No email triggered. Mark all as read - disable the red circle in a toolbar and all the notifications / invitations are considered as read. If one invitation / notification is read, than a number in a circle in toolbar is "n-1"
4. No, we put only mark as read. Like this we "push" a user to learn more about an invitation received and pay more attention to it.

**Comment by fritzschoff** [comment]
cool, thanks a lot!

**Comment by fritzschoff** [comment]
@2amarkina about the different time zones, like today, yesterday? what are possible state? Like Today => Yesterday => Later ?

**Comment by GrandSchtroumpf** [comment]
@fritzschoff There is a pipe (FilterByDatePipe) that deals with that in the code. 
- If the time is desc : "Today", "Yesterday", "X days ago", "Last Week", "X weeks ago", "Last Month", "X months ago"
- If the time is asc : "Today", "Tomorrow", ...., "Next Week", ...

My concern here is that if we hardcode the filters as "date relative to today", the component will be hard to use in other cases. If possible make it work with any kind of filter titles. Else go with relative dates and hope we don't have to use the component with something else 🤞

**Comment by fritzschoff** [comment]
How on earth should this pipe work with the mat-subheader to organize where the action are put. Furthermore you need to make the actions accessible via the templateOutlet. I don't see how this should work

**Comment by GrandSchtroumpf** [comment]
You can find examples in the [notification-list component](https://github.com/blockframes/blockframes/blob/develop/libs/notification/src/lib/notification/components/list/list.component.html) that should look much like yours.
