### ISSUE TITLE
Movie view dashboard / banner image

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#2975]
- [ ] I think the filmpage on the dashboard should show the banner image 
Or have like a "Marketplace view" so that sellers can see what buyers see in just a click
![image](https://user-images.githubusercontent.com/55785823/83751122-a0086080-a666-11ea-9d1e-d2320a1711cf.png)

**Comment by fritzschoff** [comment]
fixed by new design from Stephanie
