### ISSUE TITLE
Img sizes references in documents are overwritten when form is saved to db

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#2987]
Img sizes references in documents are overwritten when form is saved to db:

- [ ] org
- [ ] movie
- [ ] user

There is also an issue with excel upload

**Comment by pldespaigne** [comment]
This issue will be partly solve with merge of the `release/media` branch, but we will still need to tackle the import excel part

**Comment by pldespaigne** [comment]
Closed : Everything will be solved with the merge of #3142
