### ISSUE TITLE
[Component] UploadWidget

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#3002]
# Component

## UX
This component will be used to upload files in the background once a form with one or many images have been updated. A use case is: 
"On the movie form, a user upload many images from his/her computer. We only upload them to the server if the form it saved. Once it's save the upload can be long so we open a widget (on top of the app) to display the progress without blocking navigation."

Should include: 
[ ] - Be over the app (many on the left because there is already a chat on the right).
[ ] - Summary: the amount of element uploaded
[ ] - Upload list: progress of each file
[ ] - Upload actions: play / cancel / pause

## UI 
Ressources : 
- [Expansion Panel](https://material.angular.io/components/expansion/overview)
- [Snack Bar](https://material.angular.io/components/snack-bar/overview)
- [Progress Bar](https://material.angular.io/components/progress-bar/overview)
- [Progress Spinner](https://material.angular.io/components/progress-spinner/overview)

Example (google drive) :
![image](https://user-images.githubusercontent.com/8143464/84020938-fbe32a00-a983-11ea-8e5c-691c8a1c51ee.png)

-------
## UI review
_remove this section once everything is checked_
- [ ] UI doesn't already have a existing component.
- [ ] Name display in Zeplin is the same as the one in the issue (see below).
- [ ] Data can be display like in the UI (see notion).
- [ ] A link to this issue in the zeplin object

## Implement Component
- [ ] Create story with storybook
- [ ] Connect component to Zeplin with zeplin-connect
```
update the components.json in blockframes/.zeplin/
{
    "path": "libs/ui/src/lib/slider/slider.component.ts",
    "zeplinNames": [
        "component/slider/archipel_content/movie-slider"
    ],
     "storybook": {
                "kind": "Movie Slider",
                "storybook": [
                    "Movie Slider"
                ]
            }
}
path leads to the component.ts file and zeplinNames are the matching names from this component in zeplin. 
Can be multiple names if there are different states of this component.
```

## Description

- name: upload-widget
- lib: ui/media

## Type
- [X] **Component**: _Structure a piece of data in the page (ex: MovieTable)._

### Input
_can be data (movie, distribution right, ...), or UI related (dense, appearance)_
- [ ] files: A list of files to upload (with required information to display)

## Where is it used
-links and snapshots where the component is used_

**Comment by pldespaigne** [comment]
From a UX point of view, what should happen to a file that has succeeded or have been canceled ?
- should he disappear instantly from the list ?
- should he stay on the list with an icon (cross/check mark), if yes when do we remove it from the list ?

**Comment by GrandSchtroumpf** [comment]
I think @stephanie-cascade8 has cover thoses cases in her design. It should be there by tomorrow

**Comment by pldespaigne** [comment]
This component is done, there is still some bug to fix, but they are listed in another issue.
closing in favor of #3267
