### ISSUE TITLE
Clean db migration / script

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3006]
### Description
We need to delete old docs that are related to deleted docs (such as notifications, users, orgs,...). 
One good advice from Laurent is to have a function onDelete that takes cares of automatically delete these docs, and better to tag the docs "deleted" instead of really deleting it. 
But this is a big work and we need first a patch to prevent prod errors currently happening. 

As we will need to play the script often, a migration script may be blocking as it will be played only once. Better would be to create a script that we can run whenever we want or a special migration scripts that is played on all migrations. 
I let the devs decide

### Acceptance criteria 
- [x] Delete notifications related to users that don't exist anymore
- [x] Delete invitations related to users that don't exist anymore
- [x] Delete userIds on org related to users that don't exist anymore + connected permissions
- [x] Delete movieIds on org related to movies that don't exist anymore + connected permissions
- [x] Delete notifications related to movies that don't exist anymore
- [x] Delete invitations related to events that don't exist anymore
- [x] Delete notifications related to orgs that don't exist anymore
- [x] Delete orgId on users related to orgs that don't exist anymore

**Comment by Mussuranae** [comment]
Related to #1438
