### ISSUE TITLE
Redirect user after login

### ISSUE THREAD

**Issue by joanofdart** [blockframes/blockframes#3024]
> Not sure if it deserves an issue on its own (too big?) but when there is a link inside an automated email, if the user is not connected it will have to login and then he's not redirected to the first link he clicked on but on the app homepage.
> Is there a way to have something like "persistent" redirection?
> So the flow would be
> Clicks on a email link
> Login page
> Redirects to the email link (instead of the homepage)
> 

@Jackseed could you add a bit more regarding this? thanks!

**Comment by RemcoSimonides** [comment]
Related PR: https://github.com/blockframes/blockframes/pull/3290
Related issue: https://github.com/blockframes/blockframes/issues/3210

**Comment by RemcoSimonides** [comment]
It's actually the same issue as #3210 so closing
