### ISSUE TITLE
New features for event form / calendar ARCHIPEL MARKET

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#3042]
- [ ] When we close a form, the calendar returns to the current week. Should stay on the day/week the user was when they generated the form

- [ ] When we create a screening, user should be forced to associate it to a film. For now, the user has to click on "More Details", it's not very practical

**Comment by fritzschoff** [comment]
@pldespaigne can you have a look? maybe for Remco?

**Comment by pldespaigne** [comment]
I'll check that later if I have more time, otherwise maybe @RemcoSimonides can have a look if he is not too busy
or maybe it can be a good first issue for Samir, @Mussuranae 's trainee

**Comment by Jackseed** [comment]
These are in fact 2 issues:
- I created one ready for implementation #4016 re the calendar
- Re the the film being associated to the event I created another issue for the design team to propose something #4017 
I close this one
