### ISSUE TITLE
Release 1.6 - Last fixes

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3051]
- [x] [Bruce] There is a bug with join an org requests. The invitation is sent but when it's accepted the user stays blocked on the congratulations page and he's not added to the org. When I launched a new tab with that user I was back on the Join the Community page
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/c0ee673a-3f46-4a88-9daa-e9d41287bc8f)

- [x] [Hugo] On Invitations, the More button link `c/o/marketplace/event/eventId` even for member request, it should be `c/o/organization/orgId/view/members`
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/5bf741f7-d5d3-4af0-870d-1c009d8a61fc)

- [x] [@pldespaigne ] When a user is on Safari, add a banner with same UI as the [cookie banner](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/418968442/preview?scrollOffset=2767.77783203125) with this message
```Hi, we’ve noticed you are using Safari as a web browser, for a better experience on our website we recommend using Firefox or Google Chrome instead. Thank you. ```

- [x] [@RemcoSimonides] Change the Footer:
- "Legal Terms" (vs Term)
- Contact is not redirecting to the right page
- "¢Archipel Market" (on festival) vs Archipel Content currently

- [x] [@fritzschoff] Add same UI for the "Move to Wishlist" button than the other action buttons on movie view (marketplace)

- [x] Movie view marketplace: if budget.boxOffice.value === 0, don’t show box office to avoid this:
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/b2ba8d3d-95cb-458d-9507-82824a040f2f)

- [ ] [Hugo]  Org public view page tab screening Schedule, add an empty illustration page (spaceship) when there are screenings but they are all finished (same for `/c/o/marketplace/event`)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/5605f29f-0b9b-484c-8ea8-db138d9e6fd7)

- [ ] [Sebastian] Add the "Upcoming Screenings" tab on the movie view marketplace side following [this UI ](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/414884197/preview?scrollOffset=101.11111450195312)
It's something forgotten on the way..
This component is already in use on the organization public view and the global screening list 

- [x] [Hugo] Tab members on org settings, add email should be on the right side of the input and Send invitation centered
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/f6462514-23a0-48f9-b689-e5a2c9658a8a)

- [ ] [Francois] Add a way to delete events even if there is invited users, the existing invitations should be changed to status "Canceled"

- [x] [Hugo] Stats on homepage: change for « Clicks on promo elements » so hopefully it stays in one line
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/ea8378d6-7090-490d-b52b-f3588438d04e)

**Comment by phpgeekfr** [comment]
@Jackseed tested the first point on my side. Worked like a charm

**Comment by Jackseed** [comment]
@phpgeekfr ok I'll retry with fresh develop
