### ISSUE TITLE
Improve Environment Setup & Configuration

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#3075]
Developers use several environment files in order to configure their local environment.
Here is a breakdown:

`env/`
This folder contains *.ts files that define the local environment when accessed via typescript code. It is accessed via the configured path `@env`. 

`env/env.ts` is subject to gitignore. This is the file that is required. It is commonly required from within the default `environment.ts` file generated by NX. It contains named exports

`**/environments/environment.ts` Contains its own configuration logic and often imports from `@env`.

`secrets.sh` this is yet another set of environments secrets that are subject to gitignore. This is a bash script which `export`s a set of environment variables to be used in proceeding scripts, such as devops scripts in ops folder or commands found in config.yml

`.firebaserc`, `config.yml` and `angular.json` are also partially relevant to this issue, despite not being subject to gitignore, these files often refer to and depend on above config files. I do not want to get too broad on this issue as I could technically include many more files.

I just want to discuss and propose a better system for managing environment configuration. These changes should be made in conjunction with the documentation, so once they are completed the documentation becomes current as well.

## Other issues

Although this is not the same as #1046, it may solve many of the issues present. Or, it's a necessary step to solving that issue.

## Proposal

Let's think about environment configuration in two stages:
- validation & setup
- structure and configuration

Each user or CI will run `npm install` on the repo. This should trigger a script which checks the presence of necessary environment variables, and shows a warning if a required one is missing. This could be integrated into a CLI tool.

The structure itself should try to consolidate as much of the configuration as possible, provide a source of truth, and make it impossible to mix up separate environments (for instance, using prod values in staging, etc..)

### Structure:
`.env` will act as a source of truth.
Depending on the types of data we need to store, it may be problematic to use a .env, as there is no standard for parsing objects etc... will investigate this.

All other scripts will draw on this `.env` file. It will contain configuration for multiple environments if need be, denoted by a namespace, like so: `BLOCKFRAMES_DEV_projectId`.

Then, we'll create a library - `libs/shared/env` - that will contain a module which stores logic for loading environment configuration for all typescript based resources (since its a TS library).

### Possible solution for angular
It is also possible to use a custom builder in `angular.json` that allows you to modify the webpack configuration of an `ng build`. So it may be possible to configure angular to do a replacement using variables from `.env`. However, it involves using a non-standard builder wrapper from npm. If not, will investigate another solution to this.

This will hopefully allow us to eliminate the `env/` folder and `secrets.sh` file. However, this may not be possible, as there are complex interdependencies. Eliminating the `secrets.sh` file will aid in making scripts compatible with windows (not require an WSL installation).

**Comment by GrandSchtroumpf** [comment]
Quick feedback on that : 
- Having a script / cli / GUI to help dev setup your environment would be great. I should also help upgrading it, not only setting it up once.
- When possible use `angular.json` logics like `replaceWith`.
- Avoid modifying default builder. Use custom builders only for custom actions (like building storybook for example).
- I think this issue goes beyond just environment variables. You should also take care of the setup of external services (gcloud, sendgrid, Algolia, ...).
- I personally think this is not a good idea to mix `env.ts` (which are shared variables specific to an environement) & `secret.sh` (which are private API keys specific to an envrionment). `env.ts` doesn't have to be ignored, it was just an easy way not to multiple the files. While `secret.sh` have to be ignored.

**Comment by phpgeekfr** [comment]
@george43g can we close this ?
