### ISSUE TITLE
Switch Slug object to enum object

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#308]
Use an `enum` format for the staticModel instead of the object { slug, label }.
Example : 
```typescript
const COUNTRIES = [
  { slug: "france", label: "France" },
  { slug: "germany", label: "Germany" },
]
```
Becomes
```typescript
enum Country {
  france = "France",
  germany = "Germany"
}
```
**Note : Write a script to do that.**

**Comment by Maxstgt** [comment]
Since there will be [ISO](https://www.iso.org/home.html) codes at the static model as well, for example, you can see it in the movieCurrencyArray, enum would not fit our needs.

**Comment by phpgeekfr** [comment]
OK right. I'm closing this issue ;)
