### ISSUE TITLE
Migrate *sh scripts to use TS/JS, so windows machines no longer depend on WSL

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#3082]
## Context

The goal is to improve the testing process as well as enable *sh scripts to run on windows. Many devs are currently unable to run e2e tests properly who are working from windows machines. This is because of the need for WSL to run *sh scripts in the repo. WSL cannot properly run cypress for e2e tests. There may be other issues stemming from this root cause.

## Solution

In order to improve cross-platform reliability, we want to convert all *sh scripts into TS/JS.

## Considerations

- Will the code be js or ts?
- will it be stored in a library?
- if it is ts, how will it be compiled?
- should any of this code be in a CLI? What does the *sh code achieve?
- what is the specific issue with cypress and wsl? can it be patched somehow?

## Expected Outcome

All script actions run from `npm` or `nx` should run successfully in windows without WSL.

**Comment by GrandSchtroumpf** [comment]
> Will the code be js or ts?

If it doesn't require more config, go for TS obviously 😀

> if it is ts, how will it be compiled?

If possible use the angular / nx configuration instead of adding custom configuration.

> will it be stored in a library?

We currently have a `backend-ops`. If the code should be used by many source (CLI, GUI, npm, ...) it could make sense to use a library. Else we can stick to an app OR put it in tools.

> should any of this code be in a CLI? What does the *sh code achieve?

I think the first part will be to find all *sh script ^^. Some of them are used in the npm script, other are run by the config.yml. Some are in `ops/`, but I don't know if they are still used.

> what is the specific issue with cypress and wsl? can it be patched somehow?

When you run cypress in WSL, it runs inside Linux. But WSL cannot open a window. Must of dev using WSL run script in WSL and open there browser in Windows. It can be linked through "localhost", but if it's open by WSL it fails. I can do a demo if you want.

**Comment by george43g** [comment]
This post will be a listing of all bash scripts that need to be translated:
```
8 results - 8 files

deploy-prod.sh:
  1: #! /usr/bin/env bash

secrets.sh:
  1: #!/usr/bin/env bash

secrets.template.sh:
  1: #!/usr/bin/env bash

.circleci/deploy-and-test-e2e.sh:
  1: #!/usr/bin/env bash

.circleci/submit-stability.sh:
  1: #!/usr/bin/env bash

apps/backend-ops/nocollide.sh:
  1: #! /usr/bin/env bash

ops/deploy_demos.sh:
  1: #! /usr/bin/env bash

ops/deploy_secrets.sh:
  1: #!/usr/bin/env bash
```

- `deploy-prod.sh` is a script which deploys to production. Don't know if it's actually in use but the script is messy and can easily be rewritten in a much better and more reliable way. It sets firebase secrets, selects a project, copies the env file (file replacement) and deploys. This file may not be called at all.
- `secrets.sh` is an environment configuration file. It simply has a bunch of `export`s. This can be tackled with a `.env` file.
- `secrets.template.sh` is the incomplete and outdated template of the above file
- `.circleci/deploy-and-test-e2e.sh` this is a script that deploys to CI project, which is where tests happen and runs the tests, and returns a 0 exit code if they are successful. This is called from `config.yml`.
- `.circleci/submit-stability.sh` submits test results and stats to `DASHBOARD_API_URL`, which is not clear as to what it is or where it's set.
- `apps/backend-ops/nocollide.sh` in its own words: 
```
# This script is used to transform a golden database backup to
# alternate version with organization names suffixed.
# say you have a golden data with "OrgA", "OrgB", "OrgC", etc.
# It'll generate a DEMO1 version with "OrgA 1", "OrgB 1",...
# and a DEMO2 version with "OrgA 2", "OrgB 2",...
# this is a last minute quick fix to get the demos working for Toront
```
- `ops/deploy_demos.sh` seems to deploy the app to the demo environments. Not sure about this line: `scp -r dist/apps/* blockframes:~/www/www-data/demo${i}/` - no references found in search
- `ops/deploy_secrets.sh` is called by `firebase.json` and sets env secrets to firebase function secrets `functions.config()`

Translation alone is not enough - once done, all scripts that depend on these need to be updated to point to the newer versions. For example, `.circleci/config.yml` points to old bash scripts. The scripts should be located in a library or the tools folder, and possibly have unit tests (if necessary).

As well as this, there are certain things within commands that must change. Windows uses a different path separator. We may need to use `cross-env` to reliably set env vars in scripts. So commands in `config.yml` need to be looked over, as well as `npm` (`package.json`, `firebase.json predeploy`) and `nx` (`angular.json`).

**Comment by george43g** [comment]
There is one additional root problem here, which is that there are bash commands embedded within other files. For example, the config.yml has a line as follows:

```
 command: |
            AFFECTED=`npx nx affected:apps --plain --base=origin/develop`;
            echo "Building: ${AFFECTED}"
            for app in ${AFFECTED}; do
              echo "building ${app}";
              npm run build:${app};
            done;
```

However, the above is less of an issue because this file is only executed on CI, which is always *nix. However, there are other files we must consider in case there are any hidden commands:
- any script files which have bash-like commands in them
- config.yml (not as important since only CI runs this) but less commands the better regardless
- firebase.json - predeploy commands
- package.json - contains paths that use static path separator
- angular.json - contains `run-commands` builder

**Comment by GrandSchtroumpf** [comment]
> submits test results and stats to DASHBOARD_API_URL, which is not clear as to what it is or where it's set.

I think this is an external API (you can find the code in [this repo](https://github.com/blockframes/stability)). This is a react app that display the how many tests are passing depending on which app. It's really nice to track the result to the tests. I think it can be move to the monorepo in the future in an Angular app. It could be part of a super-admin app where we can backup the DB & see some performance stats.

> `scp -r dist/apps/* blockframes:~/www/www-data/demo${i}/` - no references found in search

Looks like it's pointing to the "blockframes" docker (`scp == ssh copy`). It looks deprected to me.

**Comment by george43g** [comment]
Update:
firebase.json and deploy_secrets.sh have been converted. The repo now runs a TS file to deploy secrets to firebase.

The rest of the actual *.sh files are not run on the local machine - these are for CI. I will clean them up anyway.

But it seems that one of the main issues that require WSL are the commands themselves - not so much bash scripts.

So the files: angular.json, package.json are what I'm working on currently to get them to work. This will require restructuring, so whether I like it or not, I'm already starting to deal with the env configuration issue.

**Comment by george43g** [comment]
Update: I have written a script that automatically migrates secrets.sh to .env - it runs on postinstall

**Comment by george43g** [comment]
I think this issue is complete - let's merge it in!

**Comment by george43g** [comment]
This issue has been successfully merged and completed!
