### ISSUE TITLE
Movie migration

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#3083]
Here are the future changes for the movie data model and it would be good to do unit test for testing :

**Main Section :**
- [x] productionYear => DELETE
- [x] officialsIds => KEP ONLY IMDB
- [x] stakeholders => MOVE INTO OTHER SECTION
- [x] directors[].filmography => RENAME FROM shortBiography
- [x] directors[].status => CREATE
- [x] directors[].category => CREATE
- [x] workType => RENAME IN contentType
- [x] poster => **it has been done in the `media-backend` branch** (ask @pldespaigne if needed)
- [x] banner => **it has been done in the `media-backend` branch** (ask @pldespaigne if needed)

**Sales Info Section : (deletion of this section)**
- [x] broadcasterCoproducers => DELETE
- [ ] certifications => MOVE INTO ADDITIONAL SECTION
- [x] color => MOVE INTO TECHNICAL SECTION
- [x] format => MOVE INTO TECHNICAL SECTION
- [x] formatQuality => MOVE INTO TECHNICAL SECTION
- [ ] originalRelease => MOVE INTO ADDITIONAL SECTION
- [x] physicalHVRelease => DELETE
- [ ] rating => MOVE INTO ADDITIONAL SECTION
- [ ] scoring => ???
- [x] soundFormat => MOVE INTO TECHNICAL SECTION
- [x] releaseYear => MOVE INTO MAIN

![image](https://user-images.githubusercontent.com/48033264/84780978-8a8c2280-afe6-11ea-9c41-0efa50d8761c.png)

**Production Section : (new section)**
- [ ] producers => MOVE FROM SALE CAST
- [ ] productionCompany => MOVE FROM MAIN (STAKEHOLDERS)
- [ ] coProductionCompany => MOVE FROM MAIN (STAKEHOLDERS)
- [ ] distributors => MOVE FROM MAIN (STAKEHOLDERS)
- [ ] salesAgent => MOVE FROM MAIN (STAKEHOLDERS)

**Technical Section : (new one)**
See Sales Info section

**Additional Section : (new one)**
See Sales Info section and Budget Section

![image](https://user-images.githubusercontent.com/48033264/84781033-9aa40200-afe6-11ea-8058-5099727ff9f1.png)

**Budget Section :**
- [ ] boxOffice => MOVE INTO ADDITIONAL SECTION

**Sales Cast :**
- [x] Rename it to Artistic Team

**Sales Agent Deal Section**
- [x] Remove this section

![image](https://user-images.githubusercontent.com/48033264/84781070-a7c0f100-afe6-11ea-9103-fa558629194f.png)

**Delivery Ids Section**
- [x] Remove this section

Try to find a pattern to unit test migration script but not write one unit test per migration.
- [ ] Unit tests

**Comment by GrandSchtroumpf** [comment]
To make the update easier we can build some pipes & transformation operation so we can updates on one place. For example:
```typescript
@Pipe({ name: 'producers' })
export class ProducerPipe {
  transform(movie: Movie) {
    return getProducers(movie);
  }
}
export const getProducers = (movie) => movie.stakeholders.producers;
```
Like that we can only update the `getProducers` methods when we do the migration.

**Comment by GrandSchtroumpf** [comment]
Wait for the migration of media to work on promotional elements.
Create a feature branch to implements the Movie Form with this.
