### ISSUE TITLE
Unit test the Media service

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#3087]
link to the master issue #3084

**Comment by Jackseed** [comment]
examples:
- test if the file is uploaded
- pause the upload
- resume the upload
-...

**Comment by fritzschoff** [comment]
@pldespaigne @pldespaigne dunno the state of this issue since the PR I did was closed due to some decisions from Mano and George. I will remove myself from the assign tab.

**Comment by pldespaigne** [comment]
@xmano @george43g @Jackseed
