### ISSUE TITLE
[E2E] Greenlight wishlist e2e tests

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3089]

**Comment by xmano** [comment]
Looking at improvements in E2E Tests in create-wishlist.spec.ts.

Issues noticed:
1. 'movie-card' component sometimes is not ready and fails to get selected
2. Unnecessary waiting in some places

**Comment by xmano** [comment]
We are using a different approach and giving hardcoded timeout.

Suggested way by Cypress is this:

https://docs.cypress.io/faq/questions/using-cypress-faq.html#How-do-I-wait-for-my-application-to-load

**Comment by xmano** [comment]
Update 28-Sep-2020 Nightly CI E2E test:

Logs:
https://e2e.blockframes.io//result/21312

It appears a timeout issue. Cannot conclude if there was a temporary network issue. Will keep it open to check it again.
