### ISSUE TITLE
Excel import and media

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#3091]
Quick fix:
- [x] Import image using an url is _temporary_ disabled and fields are removed from excel template

Permanent fix:
Refactor the media part of the excel import; images should be downloaded to the user's browser so the user can crop them. Once the line is saved, the image is uploaded. The design for this component is to be determined. A first proposal is to add a preview + button to the import line and once the image/button is clicked, the CropperComponent is opened in a Dialog to manually select an image.

- [ ] Think about what to do with other media such as videos and pdf (link to #3088)

link to master issue #3084

**Comment by GrandSchtroumpf** [comment]
Disable images in the excel.

**Comment by RemcoSimonides** [comment]
ye
