### ISSUE TITLE
e2e test - Add a new member

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3093]
### Description
Members: verify the list of members and add a new member, re-connect on this new user, test identity page and try to have access to the app

**Comment by Jackseed** [comment]
Some ressource for ready the email: temp-mail.org

**Comment by Hugo-Hontans** [comment]
> Some ressource for ready the email: temp-mail.org

We can't access to an external website with cypress

**Comment by xmano** [comment]
Will go through this scenario manually first and then have a strategy to automate with E2E

**Comment by Jackseed** [comment]
Great, tell me if it needs an update

**Comment by xmano** [comment]
We will use the EPIC to track the issues mentioned here. Also new E2E test requirements go to that EPIC with individual issues mentioned therein.

https://github.com/blockframes/blockframes/issues/3782
