### ISSUE TITLE
Redefine Notification structure

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#3094]
# UX
Define :
- [x] when we should display a notification
- [x] what kind of notifications
- [x] who should see the notification (user, member of the org, admin of the org, ...) 
- [x] what message to display for each kind notification (depending of what ?)
- [x] should a notification be always displayed or should be removed once read.
- [x] which page is linked to this notification (depending on marketplace / dashboard, or depending on the app).
- [x] what are the state of a notification (related to should remove or read)

# UI
Design: 
- [ ] the states of the notifcation
- [ ] what kind of transition between those states

# Data model
- [ ] design the data model based on UX recommandation
- [ ] verify that design can be done with rules
- [ ] verify that data for the UI can be query (check indexes) and that there is not too many jointures.

# Code implementation
- [ ] Update the service & query & store
- [ ] Update the notification list & item accordingly.

**Comment by Jackseed** [comment]
@2amarkina 2 new upgrades to come that would be good to include in this reflection: 
- Notification settings (ability for the user to choose what notification to receive and how)
- New notification to remind an event to come

**Comment by 2amarkina** [comment]
Here is the evolutive table of notifications / invitations : 
https://docs.google.com/spreadsheets/d/1DCO2PH0HaSnt3y6DSPnIX6hXbGsaCw10tCR38gG8LyM/edit#gid=0 

Here is the proposition of notification settings + an upgrade for the profile / organization page : https://www.figma.com/file/NigQKi1NqtSjGDzAVqkglw/%5B-Notifications-Settings-%5D?node-id=0%3A1
