### ISSUE TITLE
Add access to mnemonic and private key

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#311]
- [x] Exposes ~~mnemonic~~ and private key from RelayerWallet.
- [x] Create a JSON from ~~mnemonic~~ or private key in RelayerWallet.
- [x] Create a component in wallet to manage it.
Bonus : 
- [X] Remove old wallet module.
- [ ] Split the RelayerWallet

**Comment by pldespaigne** [comment]
this is related to #213

**Comment by pldespaigne** [comment]
I think this can be closed now
