### ISSUE TITLE
Change link for "A new organization has been created" email

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3180]
- [ ] link to `https://archipelmarket.com/c/o/admin/panel/organization/orgId` instead of `https://archipelcontent.com/c/o/admin/panel/organization/orgId`

**Comment by phpgeekfr** [comment]
@maltmayer @Jackseed I changed default from content to market. But keep in mind that admin panel will soon be a standalone app, so the URL choice content/market will not be an issue anymore.
