### ISSUE TITLE
Storage Rules NON EXISTENT

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#3188]
At the moment, all files in storage, including production data that has private user info, is publicly available due to the fact that none of the storage has any security rules applied.

This is an urgent task that shouldn't be too hard to fix - simply deploy security rules as part of the standard repo.

link to main issue #3639

**Comment by pldespaigne** [comment]
State of storage and rules is as follow :

- we have no rules at all for the storage
- every file is stored exactly as the same path as it's ref in the firestore
        ex: users/<ID>/avatar/original/myImage.webp is linked in the db as users/<ID>/avatar.original.ref
        ex: movies/<ID>/promotionalElements.banner.media/original/myImage.webp is linked in the db as movies/<ID>/promotionalElements.banner.media.ref

**Comment by GrandSchtroumpf** [comment]
It seems that we cannot check the database from the rules. So we need to update the storage structure.

**Comment by Jackseed** [comment]
advice from @phpgeekfr: 
- block every ready
- allow only create
