### ISSUE TITLE
[CRM APP] - Missing features bis

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3189]
This is the updated version of #2090.

- [x]  Add a way to delete a movie / contract / user / ... #3933  #3932 
- [ ] change user avatar (lower priority)
- [x] change movie images (high priority) (draft PR Clélia)

- [x] remove `Image sizes` that is now obsolete

**Comment by phpgeekfr** [comment]
@Jackseed is `change user avatar (lower priority)` still a required feature ?

**Comment by Jackseed** [comment]
No we can close this one and open it if the need comes back
