### ISSUE TITLE
Clean /reset all stores on user logout

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#320]

**Comment by pldespaigne** [comment]
Is this not already the case ?
https://github.com/blockframes/blockframes/blob/c6f930667861a1b71f9f5b471e7ec6d200b9f7a8/libs/auth/src/lib/%2Bstate/auth.service.ts#L58

**Comment by phpgeekfr** [comment]
Only auth state is cleared but not organization and movies for example.

**Comment by phpgeekfr** [comment]
https://netbasal.gitbook.io/akita/general/reset-stores

**Comment by phpgeekfr** [comment]
- [ ] Attention à ne pas reset le store des wallets
- [ ] créer un bouton `logout and clear local data`?

**Comment by Maxstgt** [comment]
@phpgeekfr can I take over the issue?

**Comment by phpgeekfr** [comment]
@Maxstgt go go go

**Comment by Maxstgt** [comment]
@phpgeekfr 
So about your checkboxes above:
 ```Attention à ne pas reset le store des wallets
 créer un bouton logout and clear local data?```
You want to reset the wallet store and clear the local storage?

**Comment by Maxstgt** [comment]
So I did some test and if you set some value to the wallet store and log out, it gets reset to the initial value. Guess the problem that Marie encountered, which is the same problem here in this issue, is about the data in the local storage?
