### ISSUE TITLE
[Festival] "Go back" arrow for better navigation

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3204]
## Description
As we don't have breadcrumbs implemented, would be good to add a "go back" arrow on most of the pages for the users to easily go back to where he/she was.

## Acceptance criteria
Implement it on the following pages (invision links attached)
- [x] [Wishlist](https://projects.invisionapp.com/d/main#/console/20186702/422956125/preview)
- [x] [Screening list](https://projects.invisionapp.com/d/main#/console/20186702/422956127/preview)
- [x] [All film page](https://projects.invisionapp.com/d/main#/console/20186702/422956126/preview)
- [x] [Terms & conditions](https://projects.invisionapp.com/d/main#/console/20186702/422956128/preview)
- [x] [Data privacy](https://projects.invisionapp.com/d/main#/console/20186702/422956129/preview)
- [x] [Movie page](https://projects.invisionapp.com/d/main#/console/20186702/422956130/preview)
- [x] [Org public view](https://projects.invisionapp.com/d/main#/console/20186702/422956131/preview)
- [x] [Event view (all states)](https://projects.invisionapp.com/d/main#/console/20186702/422956135/preview)
- [x] [Event Session](https://projects.invisionapp.com/d/main#/console/20186702/422956134/preview) / [Screening](https://projects.invisionapp.com/d/main#/console/20186702/422956133/preview)
- [ ] Calendar (invision to come from @stephanie-cascade8 @2amarkina )

**Comment by joanofdart** [comment]
Hey,
I require permission to check the designs :) could someone help me with this? thanks! @GrandSchtroumpf
