### ISSUE TITLE
Change email address for CI emails

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3206]
## Description
Currently the email used is team@cascade8.com which is quite disturbing cause the emails are mixed up with prod ones. 

## Acceptance criteria
Use developers@cascade8.com:
- [ ]  for CI admin emails (org creation, first user connexion,..)
- [ ] for staging emails
- [ ] more generally for every emails that don't come from prod

**Comment by GrandSchtroumpf** [comment]
Currently the value is in [libs/utils/src/lib/apps.ts](https://github.com/blockframes/blockframes/blob/develop/libs/utils/src/lib/apps.ts#L21).
We need to movie it to the `env.***.ts` with specific addresses depending on the environement.

**Comment by GrandSchtroumpf** [comment]
Find where this email is used. Might be in: 
- Circle CI environement variable
- secret.sh from staging

**Comment by joanofdart** [comment]
Hey,
I've been doing some research and found some stuff but I need clarification:
````typescript
export const sendgridEmailsFrom = {
  catalog: { email: 'team@archipelcontent.com', name: 'Archipel Content' },
  festival: { email: 'team@archipelmarket.com', name: 'Archipel Market' },
  default: { email: 'team@cascade8.com', name: 'Cascade 8' }
} as const;
```
We are defining a list of emails from which we will send. Theres a default block but I don't know if this is related to the CI stuff?
Also..
```typescript
export function getSendgridFrom(a?: App): EmailData {
  if (!a) {
    return sendgridEmailsFrom.default;
  } else {
    return sendgridEmailsFrom[a] || sendgridEmailsFrom.default;
  }
}
```
Again, we are using the default email but I don't think this is related to CI at all. Just commenting here to make sure.

Last but not least, there's an ENV variable in circleCI which is **CASCADE8_ADMIN**, I'm wondering if this is the email @Jackseed was referring to?

FYI,
@GrandSchtroumpf

**Comment by Jackseed** [comment]
@joanofdart sorry I your comment just now. 
In fact I'm not sure your fix was the correct one. We still receive emails from CI to team@cascade8.com. I have the feeling that now the emails sent from dev projects are received to developers@cascade8.com (because we do receive some of them to that address now).
Also to that issue we should include mails from staging, e.g. every mails not coming from prod should go to developers@cascade8.com so we don't mix up with client emails.

**Comment by phpgeekfr** [comment]
Not closing this until we decide to use blockframes.io for email other than prod.

**Comment by phpgeekfr** [comment]
blockframesCi_CASCADE8_ADMIN => dev+ci@blockframes.io ( redir => blockframes.dev@gmail.com)
    blockframesDemo1_CASCADE8_ADMIN => dev+demo1@blockframes.io ( redir => blockframes.dev@gmail.com)
    blockframesStaging_CASCADE8_ADMIN => dev+staging@blockframes.io ( redir => blockframes.dev@gmail.com)
