### ISSUE TITLE
[Festival] Sales Agent filter - mat-autocomplete

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3208]
## Description
Page `/c/o/marketplace/title`
Sales agent filter should use a mat-autocomplete in order for the user to see the list of all the sales agents when he/she clicks on the input (same as genre autocomplete). 
We need to use `algolia-autocomplete` with the organization index.

![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/a7c446b2-6a80-4121-ab05-aa4c2c015e7c)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/de77ffa9-bccb-425d-a79f-0d7d2c87ea99)

## Acceptance criteria
- [ ] Add a mat-autocomplete list on the filter Sales Agents
- [ ] List the sales agents by alphabetic order
- [ ] Be sure that Archipel Content (= central org id) is not listed in the sales agents

**Comment by GrandSchtroumpf** [comment]
Investigate why we have "cascade8" in the result.
Exclude organization from unsubmitted movie.
It's not easy to use a select instead of an autocomplete. So let's not do it.

**Comment by Jackseed** [comment]
@GrandSchtroumpf any recommandation so we may achieve this one day?

**Comment by GrandSchtroumpf** [comment]
We have a algolia-autocomplete in the event form, we could take this example. I think the main difficulty is going to filter the organization to only display sellers of the specific app...

**Comment by Mussuranae** [comment]
I look for this issue, and we use the `algolia-chips-autocomplete` component, so it works well. The only 'problem' I see is that we have to write the first letter to see a list of organization appears.
Also, it looks like the filter show only organizations that are accepted and that have movies accepted.

**Comment by Jackseed** [comment]
@Mussuranae a simple fix for this issue would be to display the whole list when the user selects the field and then filter it if s/he types letters. Do you think that's doable?

**Comment by Mussuranae** [comment]
No idae at all. I can look at it tomorrow.

**Comment by Jackseed** [comment]
Yes please have a look it would be a good improvement since it's a filter common to all apps

**Comment by RemcoSimonides** [comment]
@Jackseed Should this 'show autocomplete results on focus' be implemented everywhere where algolia-chips-autocomplete is implemented? Or only for Sales Agent Filter

Everywhere is:
- Sales Agent filter
- Invite users on event

**Comment by Jackseed** [comment]
No it should only be fore Sales Agent as for events it would mean display all our user email list, that's something we should avoid as much as possible

**Comment by GrandSchtroumpf** [comment]
We should definitely avoid having multiple behaviors for the same component : 
- Difficult to implement
- Difficult to maintain
- Create un-wanted side effect

**Comment by Jackseed** [comment]
Couldn't we use the same components as genre filter then? It's the same behaviour that is wanted here

**Comment by RemcoSimonides** [comment]
No, genre doesn't get its values from Algolia

**Comment by Jackseed** [comment]
Ok so after discussion we should then change component to use a mat-select with multiple selections. 
https://material.angular.io/components/select/overview#multiple-selection

**Comment by Jackseed** [comment]
The Sales agent list should be sorted by alphabetical order in the select

**Comment by RemcoSimonides** [comment]
To maintain code readability and maintainability we do not implement this feature.
