### ISSUE TITLE
[Bug] [Festival] Event invitation - Add context 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3209]
## Description
We need to tell a bit more info to the user than "You've been invited to an event".

## Acceptance criteria 
- [ ] Based on[ this example](https://projects.invisionapp.com/d/main#/console/19607961/418496013/preview), change invitation text to display org logo (organizer), event title, event date and event link
This issue is only about text and image, **don't change the general UI**

**Comment by fritzschoff** [comment]
@GrandSchtroumpf Why did you add [Bug] to the title?

**Comment by GrandSchtroumpf** [comment]
I wanted to give it the the debug person, but you know the rest of the story...
