### ISSUE TITLE
[UX] Easier connexion flow

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3212]
## Description
Il nous faut un flow de connexion plus simple pour les acheteurs invités à un événement, à décliner en wireframes.
La piste à étudier est celle où l'utilisateur recevrait un mail d'invitation, alors qu'il n'a pas de compte sur la plateforme. Un bouton le renvoie vers la plateforme, un compte "fantôme" existe déjà pour lui auquel est rattachée l'invitation en question. L'utilisateur ne devrait avoir qu'à rentrer les infos nécessaires:
- nom
- prénom
- organisation (faire que si le nom tapé n'est pas dans notre base on crée l'org en question?)
- mot de passe

Toutes les options sont ouvertes avec un seul objectif: simplicité.

**Comment by 2amarkina** [comment]
Screens to optimize the general sign up + invitations : https://www.figma.com/file/UMbfjswSE7stwg4riRLOjH/%5B-Easier-connection-flow-%5D?node-id=0%3A1

**Comment by Jackseed** [comment]
Idea from @maltmayer, what about adding a popup or something to warn users that they should keep their creds safely:

> Remember that, with your Archipel Market account, you can access projects and screenings from multiple sales companies all year round. So keep your logins close for your future screenings!

**Comment by Jackseed** [comment]
New user/org creation flow sum up:
only one form page for everyone
app specific info (logo, texts like hints, input names for example Dashboard / Marketplace (not sure of that))
3 new fields: org activity, org nationality, app access (dashboard/marketplace)
Every fields are mandatory
activity list is the same for all the apps
new org is created only when user click on “Sign up” button
Then we have 2 flows depending on the org name (the org list is app specific):
If the org exists, the 3 new fields (activity, nationality, app access) are filled in with the already known values and disabled
If the org doesn’t exist, the fields stay empty and enabled
Some considerations about org name select:
The user has to select a choice from the org name select (either existing or create), if not it raises an error
If the user change the org name after touching the 3 new field values: if it’s a new org we keep the values, if it’s an existing org it erases the values and replace it with the existing ones.
There is a problematic use case where the user creates a new org that exists in another app. We don’t want duplicates but the burden will relies on the business development side that shall check if the org already exists on another app before accepting its creation.
        If so there should be a discussion between business dev & client to know what’s the best option here. If this use case happens too many times, we’ll consider    updating that flow with mb a new field that appears only when the org exists but not on this app.
Eventually there was a question about displaying a 2nd page on certain use cases with more info but we dropped it for now. Instead, the empty dashboard homepage will be changed to add a new CTA button that asks the user to fills in company information.
