### ISSUE TITLE
Movie Form UI

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3213]
## Description
Le chantier avance bien, il faudrait qu'à la fin de ce sprint l'on puisse valider certaines pages et avoir une première version de toutes celles rattachées à Archipel Market.

**Comment by GrandSchtroumpf** [comment]
@2amarkina :
- Validate the Mockups from @stephanie-cascade8 without the form list.
- Design the structure for the form list.
- Review the current summary & update if needed.

@stephanie-cascade8 : 
- Work with @maltmayer on the subtitle / dubbed / ... + hint / errors
