### ISSUE TITLE
Update title list

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#3219]
We need to update the title list page with: 
- [ ] "Load more" button instead of pagination
- [x] Change the "Reset all filter" to an icon with tooltip

https://projects.invisionapp.com/d/main#/console/20048194/421241776/preview

When you're done, add a link to the result in this issue : 
https://github.com/blockframes/blockframes/issues/2631

**Comment by stephanie-cascade8** [comment]
https://projects.invisionapp.com/d/main#/console/20048194/429026308/preview
