### ISSUE TITLE
Close without saving - Movie tunnel

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#3223]
I don't know if it happens only with me but here is the problem : 

In movie tunnel when I want to close it (capture below) and click on "close without saving" I stay on the same movie tunnel page, but it should redirect a user to the dashboard page or title page (depending from where s/he started adding a title)

![Снимок экрана 2020-06-30 в 17.09.20.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/78bfc658-ac3d-4379-82f0-3eb4f3af2359)

**Comment by fritzschoff** [comment]
fixed by https://github.com/blockframes/blockframes/pull/3709
