### ISSUE TITLE
Marketplace Movie view

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#3227]
Design the view of each pink section of a movie (see [here](https://docs.google.com/spreadsheets/d/1z4FFNABgDyRGgD5AQZf-ebWbA_m-7hlueFMCVUuk2fI/edit#gid=430128331)).
- [ ] Reference
- [ ] General Information
- [ ] Directors
- [ ] Logline
- [ ] Synopsis
- [ ] Key Assets
- [ ] Keywords
- [ ] Production
- [ ] Distributor
- [ ] International Sales
- [ ] Cast Member
- [ ] Crew Member
- [ ] Festival & Award
- [ ] Festival (other)
- [ ] Film Review
- [ ] Release
- [ ] Box Office
- [ ] Rating
- [ ] Qualifications
- [ ] Format
- [ ] Available Versions
- [ ] Files
- [ ] Notes & Statements
- [ ] Images
- [ ] Video

**Comment by stephanie-cascade8** [comment]
https://app.zeplin.io/project/5de7944cf85691577aacfbb7/dashboard?seid=5f3e3f1429e65833889df45d
