### ISSUE TITLE
[Feat] Testing library to generate mock data for unit tests

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#3238]
### Use Case

For Unit-Tests we most often need to inject fake test data into the UUT (unit/module under test).
This can be done with faker.js on an individual field / property level.

The challenge is to do this in a generic manner, so that it can be done automagically by a test utility.

- [x] Generate mock data
- [ ] Type safe (use constructors / fallback)
- [ ] Automatic generation using schema
- [ ] Generic Type - works with any class under test

### Example

In the illustration below `fakeData`  is the object generated by the test utility.

![image](https://user-images.githubusercontent.com/8731418/86448848-faafdd80-bd34-11ea-9747-fd7ed64acd9e.png)

### Prior Art
We have StoryBook for app components or even factory methods for the unit / components itself.
In such cases where it makes sense, we will go with these constructor factories or fallback to test utility. The test utility can it self be used with the factories if needed.

### Expectation

Using this, the developer can quickly write different unit test cases with Jest or other test framework
and focus on the test scenario.

It might save time for developer when used with some test patterns.

**Comment by phpgeekfr** [comment]
@xmano can we close this one ?

**Comment by xmano** [comment]
We are using anonymized production data for the fixtures. We will go with this for now.

For auto generated fixtures, we might need a specific library. Closing this for now. It can be opened later if needed.
