### ISSUE TITLE
Fix Zapier prod backup

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3245]
## Description
A [zap](https://zapier.com/app/editor/70344508/nodes/70344510/sample) from Zapier backup prod everyday. That file is then saved with a cron job on a server we rent.
The zap is currently broken and needs to be updated so the flow is up again.

## Acceptance criteria
- [x] Fix the zap
- [ ] Test the db backup flow to be sure it's up & running

**Comment by Jackseed** [comment]
@phpgeekfr this looks done to me (zaps are green at least). Can you confirm & close?

**Comment by phpgeekfr** [comment]
Checked right now:  zapier is making daily backup of prod db and hetzner server is fetching it every day to store it in :`/home/blockframes/firestore-backup/data`

```
ssh root@144.76.172.41 
su blockframes
crontab -l
```
