### ISSUE TITLE
Find way to test migration scripts via emulator

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#3247]
George + Mano - discovered this issue and Want to document it.

Find a way to setup unit tests for migration scripts.

The problem is that the migration scripts have hardcoded connecting to the env in env.ts. We need to override this config for tests to ensure they connect to the emulator instead.

**Comment by xmano** [comment]
Issues with current code in **george/configure-emulator-testing** branch

1.  Connection cannot be made to local emulator.
     Debugged this issue and found the cause to be GOOGLE_APPLICATION_CREDENTIALS not being set properly in .env file : check the quotes and path. Path should be relative.

2. After fixing this manually in .env, encounter another config issue.
    
```
    Cannot find module './operations_client_config' from 'operationsClient.js'

    However, Jest was able to find:
        './operations_client_config.json'
```

3. The current setup sometimes seems to download a jar file - this can slowdown tests and may hog the bandwidth. Verify this.

4.  Need a way to inject local emulator config into apps for unit-test mode.
