### ISSUE TITLE
Use image placeholders when image URL is not working

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3248]
Currently we are calling image placeholders only when there is no url image at all but when this image is not working, we display a broken image.
> Left image (placeholder) vs right image (broken image)
![image](https://user-images.githubusercontent.com/14964443/86751221-cdb64000-c03e-11ea-9951-2c4ed14bcb74.png)

- [ ] Find a way to know that image is broken
- [ ] Update placeholder to be displayed when image is broken
- [ ] Implement it for user avatar placeholders
- [ ] Implement it for org logo placeholders
- [ ] Implement it for movie poster placeholders

**Comment by RemcoSimonides** [comment]
Has been fixed during the media rework
