### ISSUE TITLE
Clean Movie Medias

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#3291]
We already took care of the underlying structure of medias, but we still have some legacy field (label, size, ....) in `banner`, `poster ` and every `promotionalElements`, so we need to get rid of those fields.

This issue is blocked by #3283 : wait until its closed to start

This issue is also closely related to #3083 so be sure to coordinate with them.

Legacy fields are in `main.banner`, `main.poster` and in every child of `promotionalElements`, those field are :
  - label
  - ratio
  - size
  - media (the content of media should be moved upward in the object)

- [x] we also need to clean inner structure of media to remove `url` and move `ref` upward, so a media become just a string containing the **full** ref of the file in the storage

- [x] remove legacy field from the movie : Backend
- [x] remove legacy field from the movie : Forms
- [x] remove legacy field from the movie : Frontend
- [x] write corresponding migration

link to main issue #3084

**Comment by Jackseed** [comment]
This has to be coordinated with @Mussuranae migration script + @phpgeekfr cleaning script
