### ISSUE TITLE
[UI] Add a description field on screening form & screening view & session

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3320]
## Description
We want to add a way for the users to specify some custom things on the screening. For example if there is a conference on another app related to the screening or some more data about it outside of the app. 
The 4 pages to update are:
1. [Screening form](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/414852847/preview?scrollOffset=1562.2222900390625)
2. [Screening view - dashboard side](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/411890750/preview?scrollOffset=1562.2222900390625)
2. [Screening view - marketplace side](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/411867784/preview?scrollOffset=1562.2222900390625)
3. [Session view](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/414850638/preview?scrollOffset=1562.2222900390625)

Regarding the form, we should have a validator limiting the characters to approximately 2 lines of text so around 500 characters?

## Acceptance Criteria
- [ ] Screening form update
- [ ] Screening view - dashboard side update
- [ ] Screening view - marketplace side update
- [ ] Session view update

**Comment by stephanie-cascade8** [comment]
@Jackseed this is ready for content, placement and design review (use the same initial links in this issue ; mockups were replace at the same spot in Invision)
