### ISSUE TITLE
[UI] Update user account creation flow based on wireframes

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3324]
## Description
This flow is about making easier the process for users to onboard when invited to a screening. @2amarkina is working on wireframes. There is still a decision pending about this flow becoming the main and only one or having 2 flows: 1 "full" (actual) vs 1 "simple" (for invitations only). 

## Acceptance criteria
- [ ] Create / update existing design on the login / sign up flow to match the wireframes from #3212

**Comment by stephanie-cascade8** [comment]
Business review is done.
Dev review needed here https://invis.io/5JYJJLPQU2X

**Comment by Jackseed** [comment]
@stephanie-cascade8 need also the login page plz

**Comment by Jackseed** [comment]
@stephanie-cascade8 also:
- organization waiting for validation page
- forget my password page
- identity page (user name for 1st connexion)
- request to join an org waiting for an answer page
