### ISSUE TITLE
[UI] Add better showcasing of the screenings to come on homepage

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3328]
## Description
We want a user that connects for a screening to know rapidly where he/she has to go to watch that screening. 
Different scenarios are being evaluated:
- banner displaying today's screenings
- widget with "Your screenings" 
- mb both
Based on Anastasiia's wireframes, create the corresponding screens.

**Comment by stephanie-cascade8** [comment]
Animated interaction on the header ( first idea) https://projects.invisionapp.com/prototype/Upcoming-screening-test-ckgm4495d00lrw401jmvqo120 Needs to be debated and discussed with UX, Devs and Business.

**Comment by stephanie-cascade8** [comment]
https://www.figma.com/file/P55iBTLX6jUqIFeA926gOY/%5B-Events-Widget-%5D?node-id=0%3A1

**Comment by Jackseed** [comment]
Duplicate of #4048
