### ISSUE TITLE
e2e watermark restore

### ISSUE THREAD

**Issue by Hugo-Hontans** [blockframes/blockframes#3329]
When we restore database with prepareForTesting, there are lot of users without watermark, I think actually watermark are created by onUpdateUser. We should probably create a small ops script that generate all the watermarks and include it at the end of prepareForTesting.

**Comment by pldespaigne** [comment]
migration 24 is responsible for generating all the watermarks.
- [ ] copy paste & refactor migration 24 into it's own ops script
