### ISSUE TITLE
[UI] Update Privacy settings for film page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3330]
## Description
Privacy settings feature will be for a user to be able to choose **not** to display the film page to every buyers but only to the invited one.
This feature shall use the same components used for event invitation. Screen already exist [here](https://projects.invisionapp.com/d/main?origin=v7#/console/20048194/421221109/preview?scrollOffset=751.1111450195312), but it's worth updating it with dev review to be sure that components are re-usable from [event form](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/412244898/preview?scrollOffset=5463.33349609375)

**Comment by stephanie-cascade8** [comment]
https://zpl.io/2ynnKpK

**Comment by Jackseed** [comment]
I added some comments and zeplin, also just a reminder but there is the form page that needed too
