### ISSUE TITLE
[UI] Notification settings

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3331]
## Description
Based on @2amarkina wireframes (#3094) , create the corresponding screens

**Comment by stephanie-cascade8** [comment]
@Jackseed business review is done
We need a dev's review here https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/429010252/preview?scrollOffset=1275
_Note: see expansion panel with label in bold without padding left (is it possible?)_

**Comment by Jackseed** [comment]
@stephanie-cascade8 just a reminder to check if we can have app-specific info on the settings layout
