### ISSUE TITLE
Display problem on Marketplace Organization view / Contact information tab

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#3338]
- [x] When too long, position should not be displayed fully (have "..." at the end if too long), with ideally the full text displayed on hover if possible.
![image](https://user-images.githubusercontent.com/55785823/87925363-76719000-ca80-11ea-9691-109427340f5e.png)

**Comment by Jackseed** [comment]
Check for the max length pipe (@fritzschoff advice)

**Comment by Jackseed** [comment]
(and forget about the hover thing)
