### ISSUE TITLE
Filters of marketplace-title-list

### ISSUE THREAD

**Issue by Hugo-Hontans** [blockframes/blockframes#3354]
The clear function of some filters don't work:
https://image.noelshack.com/fichiers/2020/30/3/1595419174-capture-d-ecran-de-2020-07-22-13-59-23.png

Catalog marketplace title-list filters:
- library / line-up
- languages
- production status
- budget

Festival marketplace title-list filters:
- languages
- production status
- budget

Apparently is an display bug, the form should be correctly reset but display and list of movies don't trigger the changes.

**Comment by RemcoSimonides** [comment]
Issue was only with filters using checkboxes. UI didn't update to the new value.
