### ISSUE TITLE
App Bar Search

### ISSUE THREAD

**Issue by Hugo-Hontans** [blockframes/blockframes#3355]
Talking about the App Bar Search inside the top nav bar of catalog/marketplace/title-list and festival/marketplace/title-list components.
This bar appears when we scroll to bottom and replace the classic search bar.
We got issues:
  - When the user does a search without result, he is stucked at the top of the page without the App Bar Search. So he cannot start a new search, he is blocked and must refresh the page.
  - If the result of the search if for example only one movie and the user scroll to top, the App Bar Search disappears and he doesn't understand how start a new search.

This 2 bugs can be solved by linked the 2 search bars with the same value. Like this the user is never lost.
Can be good t do a point on the expected UX with @2amarkina and @Jackseed before.

**Comment by Jackseed** [comment]
Best would be to 'connect' the 2 bars so they have the same text on both. 
Check with @2amarkina the wanted behavior and if too complicated remove the search bar on top
