### ISSUE TITLE
Festival E2E : - Verify the screening page and created screenings may fail

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#3359]
CI E2E test for Festival app might fail

`cy.get('festival-organization-list org-card', { timeout: 30000 }).contains(orgName).parent().parent().find('a').click();`

find() command may not be able to reach parent and fail

==> 
check if it works & add a new test

**Comment by xmano** [comment]
Another one:
screening-invitations-2688.spec.ts : Step 2 : "John Briant logs in and accepts his invitations and run the video"

Timed out retrying: Expected to find element: `festival-event-view a[test-id=event-room]

**Comment by phpgeekfr** [comment]
Closing since this it seems to be working now.
