### ISSUE TITLE
ARCHIPEL MARKET / Wrong number of movies displayed on library page

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#3367]
When I leave an org page to go to the library page (through the side menu), it doesn't show all the films... I see only  "11 titles available." 
![image](https://user-images.githubusercontent.com/55785823/88392290-059de100-cdbc-11ea-8d93-741bb28f0e5c.png)

When I refresh, I get 50.
![image](https://user-images.githubusercontent.com/55785823/88392307-0b93c200-cdbc-11ea-87e9-b65b4577ffe9.png)

**Comment by RemcoSimonides** [comment]
Fixed in PR #3490
