### ISSUE TITLE
Invitations refreshment

### ISSUE THREAD

**Issue by Hugo-Hontans** [blockframes/blockframes#3379]
When a user accept or refuse an invitation, he needs to reload the page for the view to be updated.
The status of invitation is not updated in the store when you accept the invitation. It can come from the guard which does not refresh the store.
`syncCollection` doesn't detect changes on `status` field.
We don't notice it too much now because the message of the invitation remains the same.

- [x] Fix the bug
- [x] Remove the trick reload in e2e test (marked with issue number)

One solution can be to create indexes and add a where for each case inside invitation guard like:
```
this.service.syncCollection(ref => ref.where('toUser.uid', '==', user.uid).where('status', '==', 'pending')),
this.service.syncCollection(ref => ref.where('toUser.uid', '==', user.uid).where('status', '==', 'accepted')),
this.service.syncCollection(ref => ref.where('toUser.uid', '==', user.uid).where('status', '==', 'declined')),
```
but it seems very bad to create a lot of syncCollection and use a trick like `this.service.syncCollection(ref => ref.where('toUser.uid', '==', user.uid).where('status', '>=', '0'))` doesn't work.

**Comment by fritzschoff** [comment]
we might need to upgrade to akita v5 and also to akita ng fire 3.0.2. We got a similar issue with the firebase console and not updating the store correctly.
