### ISSUE TITLE
[Unit test] Test existing firestore rules

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3383]
Main issue to cut into smaller pieces

**Comment by xmano** [comment]
[ ] Create the setup for unit-test Firestore Security Rules
[ ] Identify the main areas of security concerns (secure areas, private info)
[ ] Write example tests for each of the areas

**Comment by xmano** [comment]
Got basic test to work with new recommended library `@firebase/rules-unit-testing`

![image](https://user-images.githubusercontent.com/8731418/98338045-8d3bf280-202f-11eb-92ae-9a2663604b45.png)

**Comment by xmano** [comment]
Individual collections to test:

[ ] - Campaign : #4187

**Comment by xmano** [comment]
Merging current changes with todos:

![image](https://user-images.githubusercontent.com/8731418/98652641-f5f1da80-2361-11eb-8216-1a14405787c6.png)

**Comment by xmano** [comment]
Closing this issue and tracking the tests using separate issue:
https://github.com/blockframes/blockframes/issues/4373
