### ISSUE TITLE
[Dev design] Validate notification settings

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3385]
[Figma](https://www.figma.com/file/NigQKi1NqtSjGDzAVqkglw/%5B-Notifications-Settings-%5D?node-id=0%3A1)

**Comment by fritzschoff** [comment]
- if we want to enable notification by sms, we need to query that from the user somewhere, in the sign up process or somewhere else.
- about GDPR, I'm not sure if there is an intersection, like the user disables everything, are we still allowed to notify him by sms/email... ?
- for push notifications we need to ask the user for allowance to enable push notification in the browser. So we might need a special overlay for that.
![image](https://user-images.githubusercontent.com/39312833/89766473-7ea97200-daf8-11ea-8208-371a65fbdb93.png)
- we need a third party library for the sms notification and this would also be part of the GDPR?
- what should happen if we toggle enable all button but no checkboxes where check. We only notify the user with in our own notification page? 
- push notification can have an img. So we might want also have an img here?

**Comment by Jackseed** [comment]
Re SMS & Push notification, that's something we won't push in the short term. But yes, this is definitely something related to GDPR.
Re the tunnel layout, I can't say but if it is possible we should definitely re-use it
