### ISSUE TITLE
[Dev design] Validate Easier connexion flow

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3386]
[Figma](https://www.figma.com/file/UMbfjswSE7stwg4riRLOjH/%5B-Easier-connection-flow-%5D?node-id=0%3A1)

**Comment by fritzschoff** [comment]
for the terms and the GDPR, you want to show that in a modal?

**Comment by 2amarkina** [comment]
- For GDPR we can redirect a user to a page needed : Terms or Legal. Modal not really needed here

- If I'm not mistaken, if "Cascade8" is a valid org it will appear in a list. Exactly like for the countries. So logically, if it's in a list -> user joins, if not in a list -> creates. Does it work for you ?

**Comment by fritzschoff** [comment]
but the user doesn't click on Cascade8 he just types it. We can't know if he wants to join the org or wants to create a new one, that is alos named `Cascade 8`. We need validation here!

**Comment by maltmayer** [comment]
He should click on it. Just like for countries.
If he wants to create a new one but the exact same name already exists, he should be stopped.

**Comment by 2amarkina** [comment]
To come back for GRPD just need to precise : the new page where user is redirected should be opened in a new tab. We don't close the form.

**Comment by fritzschoff** [comment]
From a talk with @2amarkina we agreed on a different design for the organization input. The user has to specify if he wants to create a new one or wants to join one. Otherwise it is hard to tell if he wants to join or wants to create a new one or wants to create a new one with the same name with the same one

**Comment by maltmayer** [comment]
I'm not sure of this... Part of the idea of simplifying this process was not to ask the user that question. They most likely won't know if their organization already exists or not. That is why we shouldn't give them the choice I think.
As inspiration, I'm using Pipedrive and they offer both options here for example: 
![image](https://user-images.githubusercontent.com/55785823/90487927-68746500-e13b-11ea-8d75-461008d0cc1c.png)

**Comment by 2amarkina** [comment]
I'm working on different solutions to existing problem (how we could do if we not specify directly if he wants to "join" or "create") and we also had a discussion with @GrandSchtroumpf last Thursday on this subject. I think it would be better if we agree on a solution all together (maybe a call this afternoon ?)

First thing that we'll surely use : to prevent an error we'll provide a hint to a user where we precise that s/he needs to choose an org from a list, if not - s/he will create a new one.

**Comment by fritzschoff** [comment]
We do got something already. The user types `casca` and the auto-completion suggests `Cascade 8 `. But the problem is that we can't be sure, if we wants to create a new organization or wants to join IF he not selects from the dropdown.

**Comment by maltmayer** [comment]
Ah I get it. I think he should have to click (like in the example) on either option then, but on the same field. Choosing between creating or joining should not be another step that’s what I mean. It should feel like it’s the same process and not add any steps. 

Would it be possible to block them if the exact same org already exists ? Like « this org name already exists. Click here to join the existing org or change your organization name to create a new one » or something like that ?

**Comment by fritzschoff** [comment]
>  Like « this org name already exists. Click here to join the existing org or change your organization name to create a new one » or something like that ?
Yes we can have something like that, but we need so sandbox it, like should we throw an error if user types `cascade8` without a whitespace or is this a new org. something like that

**Comment by fritzschoff** [comment]
ref #3767
