### ISSUE TITLE
[Dev-Design] Production status page on movie form

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3387]
link to [main issue](https://github.com/blockframes/blockframes/issues/2956)

Check the designs made by @stephanie-cascade8 and think of a solution to dynamically render the movie form depending on the chosen status

[Invision]([Dev-Design] Production status page on movie form #3387)

**Comment by fritzschoff** [comment]
https://projects.invisionapp.com/d/main#/console/19607961/426714808/preview is this the prototype?

**Comment by pldespaigne** [comment]
Design is now ready
![image](https://user-images.githubusercontent.com/5858657/90608427-e9e2fa80-e202-11ea-8d3f-2e76448469e1.png)
https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5f3aa7c49c028265bd427ad9
