### ISSUE TITLE
[UI] Update email templates on Sendgrid

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3398]

**Comment by stephanie-cascade8** [comment]
https://mc.sendgrid.com/dynamic-templates/d-eb8e1eb7c5a24eb8af1d2d32539ad714/version/e18e099f-2abb-4d62-9903-b1258d79388e/editor

**Comment by stephanie-cascade8** [comment]
I also put it in Invision with a mailbox layout so you can think about the subject content and view it correctly. https://projects.invisionapp.com/d/#/console/19607961/429011775/preview

**Comment by Jackseed** [comment]
@stephanie-cascade8 I think you should also add the Unsuscribe possibility on your template as it will be in every emails. 
Apart from that it looks good to me!

**Comment by stephanie-cascade8** [comment]
https://mc.sendgrid.com/dynamic-templates/d-eb8e1eb7c5a24eb8af1d2d32539ad714/version/e18e099f-2abb-4d62-9903-b1258d79388e/editor

**Comment by Jackseed** [comment]
@stephanie-cascade8 that's great!!! So cool :)

While you're on that, could you have a look at the archipel market logo? Don't know if it's me but looks way worse quality than the MF one you sent me Yesterday
