### ISSUE TITLE
Featured organization & movie

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3413]
## Description
We'd like to spotlight organization or movies by giving them a special area like this:
![image](https://user-images.githubusercontent.com/14964443/88958084-3c826400-d2a0-11ea-82d5-ab43bcbea4d1.png)

The component has been implemented on the festival marketplace homepage but it chooses a random organization. We need to be able to choose ourselves who is in that area.
Same thing will be for movies

## Acceptance criteria
- [ ] Add a corresponding parameter on the data model
- [ ] Add a way on the admin panel to toggle that parameter, on movie pages & org pages

**Comment by Jackseed** [comment]
I reopen this issue now that we have org description. To be able to display sales agent banner component on homepage we still need to be able to choose what org to display as this should be a paying feature. 
The component has been created here: https://github.com/blockframes/blockframes/commit/04ba8e58ba63cbe58274503bdfe5739f39494051

It misses the description + a way to choose what org to display before re-enabling it

**Comment by pldespaigne** [comment]
Everything work as intended, all features described above are implemented and working
