### ISSUE TITLE
Archipel Market - no "empty screening list" illustration

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#3439]
The "No screening has been scheduled" illustration does not show up anymore (either on the org page or the screening list):
![image](https://user-images.githubusercontent.com/55785823/90034147-8ddb1c00-dcc0-11ea-92da-232122125d8c.png)

![image](https://user-images.githubusercontent.com/55785823/90033985-5ff5d780-dcc0-11ea-94dd-ea48e7868e5f.png)

**Comment by Jackseed** [comment]
This has been corrected 
![image](https://user-images.githubusercontent.com/14964443/95093149-bf082380-0728-11eb-959f-d6de81b24a7a.png)
