### ISSUE TITLE
Critical Improvement : Prevent improper use of anonymization / migration scripts

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#3458]
When work with anonymized data, ensure that any improper configuration of environment variables does not result in sending emails / usage inadvertently or incorrectly

#3075 talks of this in a generic way but I am creating this specifically to address the critical issue of emails being sent due to mistake /error.

- [ ] When using dev setup ensure emails are not sent due to invalid SENDGRID_API_KEY  settings 
- [ ] Alert users when environment is not setup properly & abort the operation in scripts  (eg wrong email id config)
- [ ] Improve error message reporting : if needed point it to proper notion document
- [ ] Good to have a shell script that can do these since there are several steps involved.

**Comment by Jackseed** [comment]
@xmano @george43g @phpgeekfr  is it still an ongoing issue?

Also, I saw that we could create sub accounts on Sendgrid so we could stop using our prod account for dev environments. Don't know if it helps

**Comment by phpgeekfr** [comment]
Closing this one since it is old and looks like a bit outdated. But feel free to re-open/re-create if needed
