### ISSUE TITLE
Archipel Market Marketplace film page loading problem

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#3459]
I've noticed this a few times now, sometimes when I log in and I go directly to the film page, it displays "50 titles available." (which is the right number). It loads for a while and at some point, it goes down to "41 titles available" for some reason. 
![image](https://user-images.githubusercontent.com/55785823/90266671-a0865a00-de54-11ea-8389-93ea18250b77.png)
![image](https://user-images.githubusercontent.com/55785823/90266599-86e51280-de54-11ea-9908-ea10fb02963d.png)

**Comment by maltmayer** [comment]
Now it's 33... quite random. Didn't do anything particular I think.
![image](https://user-images.githubusercontent.com/55785823/90268654-a7fb3280-de57-11ea-86e4-6f0def13456d.png)

**Comment by RemcoSimonides** [comment]
May be related to issue #3367. Fixed that one, so this one may be fixed too. Let me know if this issue occurs again

**Comment by RemcoSimonides** [comment]
No signs of this issue still happening so closing
