### ISSUE TITLE
Change initialization of unit test methods 

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3479]
```
initializeAdminApp({ projectId: string }) => FirebaseApp
```
see https://firebase.google.com/docs/rules/unit-tests#emulator_methods

It looks like that we can also handle auth :
```
firebase.initializeTestApp({
  projectId: "my-test-project",
  auth: { uid: "alice", email: "alice@example.com" }
});
```

so maybe `libs/testing/src/lib/firebase/adminAuthMocked.ts` can be removed

**Comment by xmano** [comment]
We have a new function to include auth in test, see:

https://github.com/blockframes/blockframes/blob/8f9eebffea01cdcfd645327920b19c82c55eb9ff/libs/testing/src/lib/firebase/functions.ts#L57
