### ISSUE TITLE
Staging tests

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3480]
- [x] create 1.8 release branch @phpgeekfr 
- [x] deploy to staging every two days. @george43g @phpgeekfr 
- [x] fresh db and storage anonymized from production @george43g 
- [ ] Update notion.so with the anonymization process & how to make a clean deploy to staging @george43g 
- [x] make manual test on the 3 apps (content, festival, crm) with many users, test emails etc.. @Jackseed

**Comment by Jackseed** [comment]
outdated
