### ISSUE TITLE
Unit-Test firebase-utils fails with INTERNAL ASSERTION FAILED: value must be undefined or Uint8Array

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#3482]
Running tests from angular or nx CLI causes the tests to fail

`
>  NX   WARNING  The Angular CLI was invoked instead of the Nx CLI. Use "npx ng [command]" or "nx [command]" instead.

(node:11688) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11688) UnhandledPromiseRejectionWarning: Error: FIRESTORE (7.9.2) INTERNAL ASSERTION FAILED: value must be undefined or Uint8Array
(node:11688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:11688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 FAIL  libs/firebase-utils/src/lib/clear.spec.ts
  Clear DB
    × Should have data (247ms)

  ● Clear DB › Should have data

    FIRESTORE (7.9.2) INTERNAL ASSERTION FAILED: value must be undefined or Uint8Array'
`

However running tests directly using Jest works fine

`
npx jest clear.spec.ts
`

This appears to be some environment config issue either from Nx workspace / Angular project.

**Comment by xmano** [comment]
I noticed ng test does not setup the jest.config.js setup files. It could be problem with Nx workspace.

**Comment by phpgeekfr** [comment]
@xmano can we close this issue ?

**Comment by phpgeekfr** [comment]
Closing this issue. @xmano feel free to open it again if needed
