### ISSUE TITLE
Featured Sales Agents component shouldn't show organizations without accepted movie

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#3484]
The section "Featured Sales Agents", don't display ALL the sales agents, use the same query used in `/c/o/marketplace/organization`, i.e. sales agents that have at least 1 film published on the marketplace:
- org with `appAccess.festival.dashboard: true` &&
- movieIds including at least 1 movie with `storeConfig.appAccess.festival: true` && `storeConfig.status: accepted`
![image](https://user-images.githubusercontent.com/14964443/88957223-d9440200-d29e-11ea-87e6-fcca3f4333d7.png)

Possible ways to solve the issue;
* Query all accepted movies and then filter organizations based on this
* Change data model to movie contains an array of organization ids. This way the query `movieService.valueChanges(ref => ref.where('orgs', 'array-contains', orgId).where('status', '==', 'accepted'));` can be used
* According to @pldespaigne is it possible with a tiny change or with Algolia

**Comment by pldespaigne** [comment]
link to #3498

also for the algolai stuff, we already have the orgName in the movies, so we could also add the orgId, it should be straightforward

**Comment by Jackseed** [comment]
This has been corrected with 1.8 release
