### ISSUE TITLE
[UI] Movie page screens

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3485]
- [x] Finalize marketplace movie page on zeplin
- [x] Re-work dashboard movie page on invision for validation (use Media Financiers wireframes with tabs) 
- [x] Finalize dashboard movie page on zeplin

**Comment by stephanie-cascade8** [comment]
https://app.zeplin.io/project/5de7944cf85691577aacfbb7/dashboard?seid=5f3e3f1429e65833889df45d
