### ISSUE TITLE
[UI] Media Financiers screens

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3486]
Transform Anastasiia's wireframes into screens. 
[Figma](https://www.figma.com/file/x1s9SZZT2mts6kmBuIk9uU/MVP-Media-Financiers?node-id=0%3A1)
[Already existing screens on Invision](https://projects.invisionapp.com/d/#/projects/prototypes/20048194)

TODO

- [x] Add Movie Form 
- [ ] Dashboard views
- [ ] Investisseur Marketplace
- [ ] Reviews and content

**Comment by stephanie-cascade8** [comment]
Tunnel - Media financiers - Add movie 
https://invis.io/GEYKZWTU4HP

**Comment by stephanie-cascade8** [comment]
Media financiers movie form is ready for business & dev review here. 
https://invis.io/6AYLJAPPYGJ
Content (placeholders, labels, validators, error...) will be put in the usual excel file by Marie & Anastasiia and will be corrected later in the mockups. 
https://docs.google.com/spreadsheets/d/1z4FFNABgDyRGgD5AQZf-ebWbA_m-7hlueFMCVUuk2fI/edit#gid=279324582
