### ISSUE TITLE
E2E Regression : tests fail due to change in database entries 

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#3496]
Nightly e2e tests and deploy to staging will fail due to changes in database records.

**Comment by xmano** [comment]
From : screening-invitations-2688.spec.ts

`
  it('Pamela logs in, go on event page, asserts she can\'t access to the video and force the url', () => {
    //david.ewing@gillespie-lawrence.fake.cascade8.com <-- user should be signed-up  (1)
    signIn(USER_4);
    const p1 = new FestivalMarketplaceHomePage();
    p1.clickOnMenu();
    // Marketplace Layout shoud have "Sales Agents"
    const p2: FestivalOrganizationListPage = p1.selectSalesAgents();
    // ORG_NAME = 'Curtis, Klein and Romero'  <---  Should be registered to this Org (2)
    const p3: FestivalMarketplaceOrganizationTitlePage = p2.clickOnOrganization(ORG_NAME);
    const p4: FestivalScreeningPage = p3.clickOnScreeningSchedule();
    const p5: FestivalMarketplaceEventPage = p4.clickPrivateEvent();
    p5.assertJoinScreeningNotExists();

    // Navigate with url
    cy.visit(SCREENING_URL);
    // Assert the user is redirect to event page
    const p6 = new FestivalMarketplaceEventPage();
  });
`

Currently these e2e tests have dependency to Fixtures having specific values and relationship between them.
After anonymization these values will be lost and these tests will fail.

Writing tests according to data queries in DB will be more work and will have maintenance issues as well.

**Comment by phpgeekfr** [comment]
Can we close this one @xmano ?
