### ISSUE TITLE
add unit tests to build-and-test ci process

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3569]
Like E2E tests, UT tests should run when we enter `build-and-test` ci process

**Comment by phpgeekfr** [comment]
@george43g can you tell me which ones ? Is it possible to includes only the tests we want for now ?

**Comment by phpgeekfr** [comment]
And e2e tests don't pass either but they are in ci-workflow

**Comment by george43g** [comment]
moving this to e2e nightly areas rather than pre PR merge

**Comment by george43g** [comment]
nightly should be full, PR should only be affected
