### ISSUE TITLE
Support for Safari version 12.1 and older

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#3580]
A decision needs to be made which versions of Safari we still support and which not. Apple is doing a good job on forcing users to upgrade to newer versions of Safari but there may still be some users left.

Vincent looked into the analytics to see which version of Safari our users are using, but he wasn't able to. We could get this insight if we add code to send browser and browser version to Firebase analytics.

Suggestions to tackle this issue:
- [ ] Edit warning for Safari users if they are on version 12.1 or lower to upgrade their Safari version
- [ ] Deny access for Safari users if they are on version 12.1 or lower

Open bugs related to older versions of Safari
- [ ] Screening List not displaying events eventhough there should be
- [ ] Calendar icon from marketplace navbar doesn't work ([flat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) method isn't supported)

**Comment by RemcoSimonides** [comment]
A source for a working method to get the browser including browser version https://stackoverflow.com/questions/5916900/how-can-you-detect-the-version-of-a-browser

**Comment by fritzschoff** [comment]
@RemcoSimonides in you rlast PR you tagged this issue as fixed. Close it?

**Comment by RemcoSimonides** [comment]
No sorry, that wasn't a fix. That's just to get insight in which browser and version our users are using. Dependent on the results from that we decide what we do with this issue ;)

**Comment by fritzschoff** [comment]
I mean this issue is a year old. We sure we want to support 12.1? Since this will become deprecated pretty quickly

**Comment by RemcoSimonides** [comment]
What do you mean deprecated? Safari v12?
The users need to update their Safari version, right?

But this issue is indeed about whether we should support Safari v12, or show a big red warning that they should upgrade their browser before continueing

**Comment by fritzschoff** [comment]
currently we are on safari 14. Until we will support safari 12.1 this will become not relevant anymore, I guess

**Comment by RemcoSimonides** [comment]
Jep, but we never decided on which version we still support and which we don't

**Comment by fritzschoff** [comment]
@Jackseed here

**Comment by Jackseed** [comment]
Thanks as told during the sprint launch @SamirTouira  we can conclude that issue by just removing the footer banner for Safari users. Safari is doing a good job at updating their browser version so let's rely on them and we just won't support Safari 12.xx & lower
![image](https://user-images.githubusercontent.com/14964443/116224958-8aee6180-a751-11eb-96cd-a2017d5bd34c.png)
