### ISSUE TITLE
Admin panel - Prepare external support

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3592]
## Description
An external company will act as our client support. We will only give them access to admin panel so they don't use firebase directly. 
They should start working early September, we need to update admin panel before that. 

## Features and updates requested
- [x] Org import (/c/o/dashboard/import), contact email shouldn't be necessary

**Comment by maltmayer** [comment]
- [ ] event invitation through CRM : should come from the org organizing the screening, not Archipel Content. 
![image](https://user-images.githubusercontent.com/55785823/91712534-34ac2d00-eb88-11ea-836e-2ebfc48d17bc.png)

**Comment by maltmayer** [comment]
- [ ] "change user role in an org" function does not work

**Comment by maltmayer** [comment]
- [ ] pages take a lot of time to load, would be great to optimize that

- [ ] remember filters/research through navigation (when we go back to previous page, would be great to retrieve the filter used for the search, otherwise we keep researching the same things over and over again)

**Comment by maltmayer** [comment]
- [ ] would be great to have 2 options to create orgs : 1. through import, 2. one by one manually (just like for movies on the dashboard)

**Comment by Jackseed** [comment]
- [ ] Heavy but important: we need to add a delete button (+ confirmation dialog) on users. The delete should delete the user and all corresponding entry in the db (id in org userIds, invitations, notifications,...)

**Comment by RemcoSimonides** [comment]
A combination of Pagination, Filtering and Sorting isn't possible to make. Therefore we need to come up with a different solution to improve performance. Here are some of the options;

1. Remove filtering functionality or focus filtering on only one field (or select a field you want to filter on)
2. Remove sorting functionality (by switching to Algolia)
3. Remove distribution rights count & contracts count from movies, and user role from users

Hopefully soon I'll come up with more solutions... to be continued

**Comment by RemcoSimonides** [comment]
- [ ] Move user from one org to another without invitation
