### ISSUE TITLE
Update notion.so documentation

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3598]
Some pages on notion needs an update: 

- [x] Unit-testing-setup https://www.notion.so/cascade8/Unit-testing-setup-710c09dfbc8f4119bbf0e8a0be7ba6bf @xmano 
- [x] E2E-Setup https://www.notion.so/cascade8/E2E-Setup-280025748f3d40ef8a9f7eb9cef0da81 @xmano 
- [x] Image data https://www.notion.so/cascade8/Image-data-1baf6d559350493f839a934be3c92cee @pldespaigne or @phpgeekfr  or @Mussuranae 
- [ ] data migration ops https://www.notion.so/cascade8/Database-migration-OPS-668a9415f1b841d188186b010ceb50f3 @george43g 
- [ ] data import & backup https://www.notion.so/cascade8/Data-import-backup-c3279edb834f4a25b130adaecacef0d4 @george43g @phpgeekfr

**Comment by pldespaigne** [comment]
Image data is done ✔️

**Comment by xmano** [comment]
Unit-Test and E2E test documentation is updated ✔️ 

If there are any specific need will work on these later

**Comment by phpgeekfr** [comment]
@RemcoSimonides Should be good to handle this soon so the new team members can have a basis to look at.
For example some new team members would like to have a  doc explaining (technically) what are differences between apps etc.. Others did not knew we had an existing data model schema..

I think @Mussuranae can be the perfect person for this during her last days here :) What do you think ?
I already created this issue https://github.com/blockframes/blockframes/issues/6282  I can handle it if you want

**Comment by RemcoSimonides** [comment]
@phpgeekfr what exactly needs to be written still? The open topics described here are for George I think

**Comment by phpgeekfr** [comment]
@RemcoSimonides I don't really know, that's part of the issue. I think that most of the pages are outdated and a global rework/cleaning of our documentation is needed.

Maybe make it simpler or focus on "mandatory" pages asked from new devs ( PFT, DB schema, migration, blockframesAdmin...).

@Mussuranae I remember that you created a tutorial to onboard Samir, can you point where it is ?

**Comment by Mussuranae** [comment]
Sure, [here](https://www.notion.so/cascade8/Setup-for-Devs-4068062ade2d4967a9f04383ff30dd5b) is the notion page.
It's a list of things to do for a dev to set up the project. I tried to do it the most clearly possible, but I think we can improve it.
