### ISSUE TITLE
Parse .env rather than read hardcoded values

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#3620]
At the moment, when deploying to firebase functions, there are a number of hardcoded keys searched for inside the .env folder then deployed to functions config.

Rather than do it this way, and need to update multiple areas in the code each time we add a new env var, we should just prefix all of the firebase keys like so:

envName_functionsConfig_keyName="val..."

So, for example,

dev_functionsConfig_SENDGRID_API_KEY=***

That way, the deploy function can just read and parse the variable deploy all of the ones that have a _functionsConfig_ prefix.

The envName section has a different utility to it.

The other thing to keep in mind is that a file called `.runtimeConfig` is used often to tell an emulator what the config is, and also used on the actual server to store those values - in keeping consistent, we could just use this file to store functions config - it's already gitignored.

And finally, we could just merge everything including .env into the env.ts file. It's worth noting that we have a `json`In tools called `mandatory-env-vars.json` (should be called `required-env-vars.json`) that lists all of the required environment variables for the env to function.

**Comment by phpgeekfr** [comment]
@george43g is this still usefull ?

**Comment by george43g** [comment]
yes always, it's been on the backburner for ages! Will simplify how we store and use env vars. We will need to rename many shell env variables in CI though so it will take work, but worth it in the long run. Now that firebase has a new way of managing secrets though, we should investigate and incorporate this into our new solution as well
