### ISSUE TITLE
Use firebase-tools to backup user accounts on prod

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#3647]
In that exact code. It just has a maximum batch size is all.

Once we upgrade to using just the CLI tools, however, might be worth switching to `firebase-tools` commands - however these preserve passwords and hashes for users. Good to backup actual auth on Prod - should make a new issue out of this

_Originally posted by @george43g in https://github.com/blockframes/blockframes/pull/3636#discussion_r485764351_

**Comment by phpgeekfr** [comment]
@george43g Can we close this one ? I think it is done now?
