### ISSUE TITLE
Waterfall - Manhattan wireframe

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3652]
Using [GG Editor](https://ggeditor.com/examples/component/detail-panel) views, present a wireframe for the project form waterfall page. ![image (2).png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/6cbd7799-3d7a-48bf-aeeb-b442efafba0b)

The wireframe should be cut in 3 parts:
- Terms selection (& creation ?): a term being an addition of territories (excluded or included, e.g. World excluding France or France, Belgium) and channels (TV, theatrical,...)
- The waterfall itself on the selected terms (cf. picture above)
- A Receipt Right form showing how to create or modify a receipt right. The parameters are: terms as a source, org as a beneficiary, parent right, condition to the receipt right and a percentage. Example: Terms: France theatrical - Org: Logical Pictures - Parent right: MG - Condition: no - Percentage: 20%. It means that LP will get 20% from what comes out of the MG rights from French theatrical receipts.

A condition is set by: an object (org, receipt right, movie, terms), a min (from) or a max (until) and a number. 
For example: Until Logical Pictures gets 1M$

**Comment by fritzschoff** [comment]
with the upcoming issues. Do you think this is still needed? @Jackseed

**Comment by Jackseed** [comment]
No you're right let's close it and will open a new one if it comes back
