### ISSUE TITLE
Catalog Market UI wrinkles

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#3666]
- [x]  The default sort causes title display to be stuck.
![image](https://user-images.githubusercontent.com/8731418/92924715-061b3580-f457-11ea-849e-2f9e96a3f556.png)

- [x]  Movie detailed view sometimes UI does not get updated

![image](https://user-images.githubusercontent.com/8731418/92924961-627e5500-f457-11ea-81ca-fceaf069b4e0.png)

A properly generated page looks like:

![image](https://user-images.githubusercontent.com/8731418/92926953-75deef80-f45a-11ea-8a4b-ae9324699622.png)

Using workaround for former to clear the filters but later requires additional setup code for writing e2e scripts. Would like to have this fixed.

**Comment by RemcoSimonides** [comment]
First task is done in PR #3717
For the second task the UI has changed to now use libs/movie/component/header component; see PR #3687
