### ISSUE TITLE
Debug issue release 1.9 - summary

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3674]
## Cropper
- [x] When I hover an already uploaded image with another image, it deletes the previous one 
![image](https://user-images.githubusercontent.com/14964443/92749715-aa817700-f386-11ea-8e15-52b6cb13a525.png)
- [x] The search bar on the film page is confusing, it looks like an image that didn't load. Should have a placeholder, and generally, the same design as the original search bar
![image](https://user-images.githubusercontent.com/55785823/91325556-a1f44280-e7c3-11ea-8948-1357b9789d9b.png)

## Invitations
- [x] Accept all butons turns all invitations to accepted, even the declined one, it should only affect the pending ones
- [x] request to access a screening from buyer to seller has a wrong link id, it uses the invitation id instead of the event id
![image](https://user-images.githubusercontent.com/14964443/92743478-dc8fda80-f380-11ea-84d9-aa358f7bc7bb.png)

## Org list page `/c/o/marketplace/organization`
- [x] https://staging.archipelmarket.com/c/o/marketplace/organization
There is a glitch when you click on the movie icon on the org card

## Marketplace homepage
- [x] `/c/o/marketplace/home` Change the New films carousel on marketplace homepage to really display new films, i.e. sort films by creation dates and display them from the newest to oldest
- [x] Same sort by should be use for films in `c/o/marketplace/organization/orgId/title` > newest to oldest

- [x] Carousels with "In Production" films & "In development" are not displayed on prod but they should. Currently only completed films
![image](https://user-images.githubusercontent.com/14964443/85882734-1b7dad80-b7e0-11ea-8926-2de044ebf30a.png)

## Reset password
- [x] Test reset password function, it's not reliable, lot of complaints about it. Works for me unfortunately so can't give much more details...

## Dashboard event form
- [x] On invitations, email adresses starting with an "s" are not working, the "s" is deleted - I can't reproduce this one. 's' is not removed.
- [x] We shouldn't be able to send an invitation to someone who was already invited.
![image](https://user-images.githubusercontent.com/55785823/82893137-db14e080-9f50-11ea-98a3-8fe915cdde56.png)
- [x] When we change start date of an event, end date should adapt: event should stay the same duration. E.g. Start date 09/15/20 10:00 am / End date  09/15/20 11:00 am > start date changed to 09/16/20 11:00 am, end date should be automatically updated to 09/16/20 noon

## Titles page
- [x] Fix infinite loading of titles page

## Upload component
- [x] Clicks on the page are not registered anymore when the upload component is active (Francois)

**Comment by RemcoSimonides** [comment]
Reset password function is working for me too... Can you ask the users what kind of issue they exactly experience?
- Do they not receive the email with the reset link?
- Do they set a new password but they still can't login?

**Comment by Jackseed** [comment]
@RemcoSimonides from Sendgrid data I see that they do receive the email but they don't open it so it's more likely ending up in spams. 
Leave this behind as it we can only work with Sendgrid for better reception of our email; that's too big an issue

**Comment by maltmayer** [comment]
Shouldn't be able to create an event for a film that is still a draft.

**Comment by maltmayer** [comment]
- [ ] Dashboard movie view shows producers as "Missing" when they're not (they appear on the marketplace)

**Comment by Jackseed** [comment]
- [ ] Still image issues on Safari... These are screenshots from a user:
<img width="1440" alt="Capture d’écran 2020-09-24 à 14 50 03" src="https://user-images.githubusercontent.com/14964443/94532163-cd909f80-023d-11eb-972c-46335a4c3485.png">
<img width="1440" alt="Capture d’écran 2020-09-24 à 14 49 55" src="https://user-images.githubusercontent.com/14964443/94532168-cf5a6300-023d-11eb-8069-15478e59e698.png">

- [ ] Display statistics of an event at the end of the event form; same as event dashboard view. For the moment, you can't access the view before the event is finished (or with the direct url) and that's annoying for multiple day screenings since they'd like to have their stats asap

- [ ] Pictures from the invitation list are all mixed up, here we see that Marie doesn't have her own profile pic on the list (in fact she has none)
![image](https://user-images.githubusercontent.com/14964443/94535737-32e68f80-0242-11eb-9f44-f02365da700d.png)

- [ ] Screening lists (`/c/o/marketplace/event` + `/c/o/marketplace/organization/orgId/screening` + `/c/o/marketplace/title/movieId/screenings`) display events based on their starting date but for multiple day screenings they should appear on every day of the screening.
For example: an event from 10/15 to 10/17 is currently shown only for the 15th while it should be displayed on 15th, 16th and 17th

**Comment by Jackseed** [comment]
- [ ] Update public screenings on screening lists (/c/o/marketplace/event + /c/o/marketplace/organization/orgId/screening + /c/o/marketplace/title/movieId/screenings):
![image](https://user-images.githubusercontent.com/14964443/94542827-8ad4c480-0249-11eb-8fd5-60610d458484.png)
- When the event is public and the user not invited, the CTA button should be "Access event" > this would create the request and automatically accept it as it does already + **leading to the event page so the user can access the screening**

- On the marketplace event view, if the user is not invited, the CTA should also be "Access event"
![image](https://user-images.githubusercontent.com/14964443/94543304-2b2ae900-024a-11eb-8b5c-83d9e1ace81c.png)
Also, here we would need an observable so after clicking on "Access event" the "accepted" state + "Access Screening Room" should appear without the user reloading the page
![image](https://user-images.githubusercontent.com/14964443/94543443-5f9ea500-024a-11eb-86b4-e73d51e7d20c.png)

**Comment by Jackseed** [comment]
- [ ] Move upward "check out upcoming screenings" banner on homepage so it's just before the top banner "the ongoing film market" this is to help the users find their screening more easily. Mb good to check quickly with @stephanie-cascade8 if there should be some margin between the 2 banners but the goal is to see the screenings banner without scrolling. 
![image](https://user-images.githubusercontent.com/14964443/94543976-fc614280-024a-11eb-824d-4e9eaf146db5.png)
![image](https://user-images.githubusercontent.com/14964443/94543683-a9878b00-024a-11eb-9378-6f6a42303ac8.png)

**Comment by Jackseed** [comment]
- [ ] Homogenize the way users are mentioned. For now, sometimes they’re mentioned by their names (no email, no company information. In notifications for example), sometimes just their first name & company (email notifications), sometimes just by their email address (guest list). When we mention someone, wherever this is (in a notification/an invitation/a list/ an email), it should always show first name, last name, email address & company name.
The format should be: "firstName lastName (orgName) blablabla" + adding the user email on link mailto on the firstname + lastName.
e.g. [Vincent Choukroun](Vchoukroun@cascade8.com) (Cascade8) has accepted your invitation to screening "blabla""

**Comment by Jackseed** [comment]
- [ ] When event title is too long and has to go on 2 lines, it is not centered anymore. Should stay centered.

**Comment by Jackseed** [comment]
- [ ] When a user creates a multiple day event, it should automatically starts from 00:00 AM on the first day to 11:59PM last day and this info should be displayed on the time of the event, same as the all day event (already implemented) 
![image](https://user-images.githubusercontent.com/14964443/94546480-397b0400-024e-11eb-9f6b-f2b4a0a2c584.png)

**Comment by Jackseed** [comment]
Couldn't find the zeplin, just got the [invision](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/412246439/preview?scrollOffset=3441.25) but spaces between event title and event type + spaces between event status & CTA button doesn't look good:
![image](https://user-images.githubusercontent.com/14964443/94546945-df2e7300-024e-11eb-94f2-c04091f16c48.png)
vs
![image](https://user-images.githubusercontent.com/14964443/94546958-e48bbd80-024e-11eb-98bd-de2bd30e3dff.png)

**Comment by Jackseed** [comment]
- [ ] Security pop up when deleting an event: “Are you sure you want to delete this event? All of the invitations and requests associated to it will be deleted.”
> linked to the design issue [here](https://github.com/blockframes/blockframes/issues/2873)

- [ ] Use that same pop-up with different text when viewer is about to leave a screening room: “Are you sure? You might not be able to come back to this screening as its access is time-limited.”

**Comment by Jackseed** [comment]
- [ ] Add a description input on event form
https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/415037534/preview?scrollOffset=6661.25 & 
event marketplace view https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/411867784/preview?scrollOffset=3358.75

**Comment by Jackseed** [comment]
- [ ] Search bar on the invitation list (dashboard event form) is not consistent and doesn't work on some cases (not all of them, no pattern found :/) 
<img width="1082" alt="Capture d’écran 2020-09-29 à 12 54 02" src="https://user-images.githubusercontent.com/14964443/94565305-54a73d00-0269-11eb-8386-cc2f322b11a2.png">
<img width="1106" alt="Capture d’écran 2020-09-29 à 12 54 25" src="https://user-images.githubusercontent.com/14964443/94565314-56710080-0269-11eb-87f3-76d800bbefd8.png">
<img width="1090" alt="Capture d’écran 2020-09-29 à 12 56 05" src="https://user-images.githubusercontent.com/14964443/94565316-57a22d80-0269-11eb-880e-cce97452d605.png">
<img width="1089" alt="Capture d’écran 2020-09-29 à 12 54 17" src="https://user-images.githubusercontent.com/14964443/94565329-5a048780-0269-11eb-9fcc-2e3be34a755e.png">

**Comment by GrandSchtroumpf** [comment]
New issue on marketplace movie view : https://github.com/blockframes/blockframes/issues/3822

**Comment by phpgeekfr** [comment]
File size estimate before upload is multiplied by 10 when showed as `MB`
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/99b9d688-4651-4c3f-a0b1-c3527effd16d)

File is 1.29 GB and not 12.9 GB

**Comment by phpgeekfr** [comment]
Search bar on marketplace is not filtering movies

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/d630404c-52f0-4c56-9c2e-d7c4281b8d8d)

**Comment by Jackseed** [comment]
### Marketplace Movie page
- [ ] Screening banner CTA button text is: "Contact Sales Agent"
- [ ] Images section title shouldn't be displayed if there is no stills on the film
![image](https://user-images.githubusercontent.com/14964443/94836334-2a917e80-0413-11eb-97d6-08d27f8ed760.png)

**Comment by maltmayer** [comment]
- [ ] Move to wishlist CTA is too close to the bottom, it makes the whole "featured film" banner component unbalanced 
![image](https://user-images.githubusercontent.com/55785823/94924181-58cb9880-04bd-11eb-9caf-b48cb7c14859.png)

**Comment by maltmayer** [comment]
- [ ] Wishlist always appears empty before loading titles. Very confusing

**Comment by maltmayer** [comment]
- [ ] empty dashboard screen doesn't look the same in "Dashboard" and " My Titles"
![image](https://user-images.githubusercontent.com/55785823/95069674-4d6bad80-0707-11eb-951a-619d58c48ab7.png)
![image](https://user-images.githubusercontent.com/55785823/95069692-52c8f800-0707-11eb-8189-fe0cabd67856.png)

**Comment by Jackseed** [comment]
- [ ] Cookie preferences bar stays visible after setting the preferences, it should disappear (need to refresh for now)

**Comment by Jackseed** [comment]
> * [ ]  Wishlist always appears empty before loading titles. Very confusing

@RemcoSimonides I created this broader [issue](https://github.com/blockframes/blockframes/issues/3858) related to this problem. 
If you have a quick fix let's go for it but I guess it's too big for the release

**Comment by RemcoSimonides** [comment]
- [ ] on movie page, banner says there are no screenings even though there is one
![image](https://user-images.githubusercontent.com/27687382/95084184-d097fe00-071d-11eb-9b9b-398a7231f2b8.png)

- [ ] Able to select second session, even though there is only one session available
![image](https://user-images.githubusercontent.com/27687382/95084321-0341f680-071e-11eb-87e0-e927f55adc34.png)

**Comment by Jackseed** [comment]
- [ ] Production status filter on all films page is not blue when selected
![image](https://user-images.githubusercontent.com/14964443/95085374-6ed89380-071f-11eb-96a0-28e154c58c06.png)
![image](https://user-images.githubusercontent.com/14964443/95085384-71d38400-071f-11eb-8495-7ff51cb6876f.png)

- [ ] The checkboxes inside Production status and Language & Version filters are not cleared when clicking the "Clear all filters" button. That's confusing as it looks like the filter is still applying while it's not.
![image](https://user-images.githubusercontent.com/14964443/95085628-c5de6880-071f-11eb-960a-bd9326350e17.png)

**Comment by Jackseed** [comment]
- [ ] Dashboard title list table don't display the value of the films
![image](https://user-images.githubusercontent.com/14964443/95085812-04742300-0720-11eb-9dbe-62c6fcdcd711.png)

**Comment by Jackseed** [comment]
### Dashboard movie view
- [ ] Running time: great to have this new pipe from minutes to hours, just change "Xh Ym" for "Xh Ymin"
![image](https://user-images.githubusercontent.com/14964443/95086194-7cdae400-0720-11eb-9661-68e1795fe2b1.png)

**Comment by Jackseed** [comment]
## Movie 
- [ ] Custom festivals:
- change custom for "Other" > "Other Festival & Awards' on form title and change label for "Other festival name", "Other Festival" on dashboard
- custom festivals don't appear on marketplace, they should be mixed in with festivals
![image](https://user-images.githubusercontent.com/14964443/95101388-5e7de400-0732-11eb-8626-23bb64b60fc4.png)

- [ ] Shooting info:
- add the hint "You can put the first day of month if there is no exact date." Shooting completed
- add the label "Approximate end date" + hint "You can put the first day of month if there is no exact date." on shooting in progress
![image](https://user-images.githubusercontent.com/14964443/95100903-e2839c00-0731-11eb-815b-f3530285c126.png)

**Comment by Jackseed** [comment]
/!\
- [ ] Invitations: can't accept a request to attend an event, it goes back to pending right after I click on accept (currently with dev+crystel-fhw@cascade8.com) 
![image](https://user-images.githubusercontent.com/14964443/95102352-95a0c500-0733-11eb-9359-a34ef50619de.png)

**Comment by Jackseed** [comment]
- [ ] Seller org list (`/c/o/marketplace/organization`), don't know what are the arrows for at the bottom of the org card but they're not working, we should remove it
![image](https://user-images.githubusercontent.com/14964443/95102773-16f85780-0734-11eb-8d2c-7ca64662830c.png)

**Comment by Jackseed** [comment]
- [ ] Wishlist button on the film card (`/c/o/marketplace/title`) is not working at first. If I add to wishlist from the movie view page and then go back to the list, then it's working
![image](https://user-images.githubusercontent.com/14964443/95103198-9f76f800-0734-11eb-9cd2-6ad612736703.png)

**Comment by Jackseed** [comment]
**- [ ] Dashboard My titles page not loading**

**Comment by Jackseed** [comment]
- [ ] Request access to a public event not accepted automatically (needs the owner to accept it)

**Comment by phpgeekfr** [comment]
Closing this in favor of #3887
