### ISSUE TITLE
E2E : Configuration issue when adding a new custom command

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#3676]
Adding a new custom command in support folder results in error.

In  apps\catalog\catalog-e2e\src\support\commands.ts
`
Cypress.Commands.add("getTestID", (sel:string, testID?:string) => cy.get(`${sel}[test-id=${testID}]`));
`
which is included in support\index.ts

To add support for this need to modify in cypress.json

`
  "supportFile": "./src/support/index.ts",
`

However on running e2e get:

`
Error: Webpack Compilation Error
./src/integration/marketplace/create-distribution-rights.spec.ts
Module not found: Error: Can't resolve '@blockframes/e2e/pages/auth' in 'D:\C8\blockframes-dev\apps\catalog\catalog-e2e\src\integration\marketplace'
resolve '@blockframes/e2e/pages/auth' in 'D:\C8\blockframes-dev\apps\catalog\catalog-e2e\src\integration\marketplace'
  Parsed request is a module
  using description file: D:\C8\blockframes-dev\package.json (relative path: ./apps/catalog/catalog-e2e/src/integration/marketplace)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      D:\C8\blockframes-dev\apps\catalog\catalog-e2e\src\integration\marketplace\node_modules doesn't exist or is not a directory
      D:\C8\blockframes-dev\apps\catalog\catalog-e2e\src\integration\node_modules doesn't exist or is not a directory
      D:\C8\blockframes-dev\apps\catalog\catalog-e2e\src\node_modules doesn't exist or is not a directory
      D:\C8\blockframes-dev\apps\catalog\catalog-e2e\node_modules doesn't exist or is not a directory
      D:\C8\blockframes-dev\apps\catalog\node_modules doesn't exist or is not a directory
      D:\C8\blockframes-dev\apps\node_modules doesn't exist or is not a directory
      D:\C8\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
`

It might be webpack config issue since we have done everything needed for adding a custom command per Cypress docs.

I found a similar issue but we are using Nx10 and it should have been resolved.

https://github.com/nrwl/nx/issues/2739

**Comment by xmano** [comment]
Can do without a custom command for now but it will be clean way to implement generic functionality like auto form fill.

Using this issue to track and arrive at a solution for future.

**Comment by phpgeekfr** [comment]
@xmano Is this issue still needs to be fixed or can we close it ?

**Comment by xmano** [comment]
Need to keep it open. Currently using workaround of adding a utility function but it is not clean.

**Comment by xmano** [comment]
One of the issue I have today is knowing when the function is completed and doing next steps - specifically fill the form and click the component saves.

With custom command we can do .then() and execute the synchronous code but with functions, I have to roll up the Cypress Promise. Taking this approach for now.

**Comment by xmano** [comment]
With Nx 11 I was able to configure a new command in import test and I think we now have a good way to do this. Therefore closing this issue since this is no longer a problem.
