### ISSUE TITLE
Get rid of JSONL

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#3697]
## JSONL migration list

- [x] rewrite anonymization script to work via emulator (or any DB object passed to it)
- [x] use passthrough command execution for streaming output
- [ ] update backup/restore commands in backend-ops to utilize CLI by running commands locally
- [x] remove backup/restore function from firebase functions
- [ ] write code that automatically stores binary backup in bucket from local emulator
- [x] write code that can pull binary backup from bucket and convert to emulator backup format
- [ ] update CI config to run more prepareForTesting related steps in weekly cron
- [x] update CI to create weekly binary backups instead of jsonl
- [ ] update CI to anonymize in CI: launch emulator, download binary backup, anonymise through emulator, shut down emulator, upload saved state as binary backup

**Comment by phpgeekfr** [comment]
@george43g  does it imply to take care of  "get rid of "admin" backend function that use Express to backup/restore#3973 " before doing this?
