### ISSUE TITLE
E2E: Verify fixture generation is without any issues and can work reliably with test specs

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#3700]
Close the loop wrt to fixture generation

- [ ] Ensure user fixtures can be auth-ed correctly.
- [ ]  Add more tests as it goes to backend scripts.

**Comment by phpgeekfr** [comment]
@george43g This issue was created because @xmano had some issues with broken tests when fetching last fixtures your created.

We will talk about this in our today call .
