### ISSUE TITLE
Meeting - Configuration - Twilio API Key and Configuration

### ISSUE THREAD

**Issue by OmarSebouai** [blockframes/blockframes#3755]
* [x] Create and configure Twilio Account
* [x] Generate Twilio ApiKey and add it to env for preprod - production

link to epic #3608

**Comment by pldespaigne** [comment]
Twilio accounts has been set up, you should have been invited, check your c8 gmail inbox.
If you don't have the invitation or if it has expired ask @Jackseed for a new one.

Every dev is now able to setup is own Twilio env by following the tuto on notion.
Alternatively you can also ask me on slack if you have any trouble.
