### ISSUE TITLE
E2E : Make existing Catalog E2E Test specs pass

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#3764]
![image](https://user-images.githubusercontent.com/8731418/93993907-ef58d500-fdac-11ea-8002-160840013609.png)

- [ ] Contract Tunnel
- [x] Organization Creation
- [ ] Wishlist Creation  (Need to again refactor due to timing issues)

Movie Tunnel cases will be handled by a separate issue.

**Comment by xmano** [comment]
Earlier test logs where it worked properly:

![image](https://user-images.githubusercontent.com/8731418/94101388-59c15200-fe4d-11ea-914a-5d529a538abe.png)

https://e2e.blockframes.io//result/19869

https://circleci.com/gh/blockframes/blockframes/19869

**Comment by xmano** [comment]
Organization Creation:
https://github.com/blockframes/blockframes/pull/3761

**Comment by phpgeekfr** [comment]
Closing this is favor of 

-  [E2E] make contract tunnel tests pass #3787
- [E2E] Greenlight wishlist e2e tests #3089
