### ISSUE TITLE
Checking Sendgrid for better spam score 

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3773]
check spam issues, improve reliability, check how we can improve spam score (signature, dedicated ip, Pro plan)

- [x] Try to identify critical mails (welcome message with credentials, reset password...) and separate them from less critical mails:
- [x] Use separate sendgrid API KEY for prod and other env #3852
- [x] create a doc on notion to setup sendgrid for devs

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/41e17d1f-5e9b-42cf-be78-71916591c556)

**Comment by phpgeekfr** [comment]
this part `Try to identify critical mails (welcome message with credentials, reset password...) and separate them from less critical mails:`  has been handled by @Mussuranae . Can you confirm ?

**Comment by Jackseed** [comment]
We got a 99% score for a while and everything on the above list, can we close @phpgeekfr ?
