### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3774]
This Epic is a list of issues to make releases safe and transparent. 

- DevOps (upgrade, prepareForTesting, deploy-to-prod etc..)
- debug
- E2E and Unit tests
- Manual testing

**Issues created but to prioritize:**

- add unit tests to build-and-test ci process #3569

**Issues not created yet / to organize :**

**Comment by fritzschoff** [comment]
@phpgeekfr close mc close?
