### ISSUE TITLE
switch type checking back on progressively

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#3795]
may need, but for this PR had to turn off due to the number of errors caused preventing merging. we can switch back on in another PR if need be

_Originally posted by @george43g in https://github.com/blockframes/blockframes/pull/3711#discussion_r494419311_

This issue is about how to progressively upgrade to strict type checking in this repo

**Comment by phpgeekfr** [comment]
I think this can be closed since we are now using `eslint`
