### ISSUE TITLE
Get rid of default data

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#3798]
We want to avoid default data as much as possible.
We need to rework a little form and initialization of object to do that.

**Comment by Mussuranae** [comment]
In the sames time we update the form, we need to update also the excel import, the behavior of the excel import has to be as closed as possible to the behavior of the form.

**Comment by GrandSchtroumpf** [comment]
- [ ] Set leaf value as optional in the model (except if it's required of course)
- [ ] Remove the default values in the factory functions

**Comment by pldespaigne** [comment]
@Mussuranae what was this issue about ? what form is concerned ? can we close ?

**Comment by Mussuranae** [comment]
It's for all forms, when we initialize object (like movie or contract, etc), there is some default value (line-up or catalog for movie for example). The idae was to avoid default value to not display some tab on the "object" view if there is no data from the user.
I think a big part of this issue has been done. But not sure it was done for every collection.
