### ISSUE TITLE
Upload & Ressource management

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3806]
The flows and structure have to be validated with devs (PL as team leader).
It includes:
- meeting form, space to import files
- upload section for files on the organization level

link to epic #3680

**Comment by Jackseed** [comment]
@2amarkina something we haven't discussed yet is the image displayed on top of video player before it's played. Since we'll handle the video player we should ask the user to upload one, or mb see if there is something offered by JW Player to do so
![image](https://user-images.githubusercontent.com/14964443/95578384-19102e00-0a34-11eb-94f9-0826e1ad8a16.png)

**Comment by stephanie-cascade8** [comment]
File and videos uploader : https://zpl.io/VKr5BNP
