### ISSUE TITLE
Banner new ratio component

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3808]
Define what actions we can remove from the banner to have some more spare space for small screens

**Comment by fritzschoff** [comment]
There was an issue that the ratio of the banner was wrong. @stephanie-cascade8 @GrandSchtroumpf worked on that

**Comment by phpgeekfr** [comment]
@fritzschoff I removed myself from assignee because I don't understand what I can add here but feel free to update me if I'm wrong

**Comment by RemcoSimonides** [comment]
@Jackseed @stephanie-cascade8 Does any of you know what to do for this issue? We can close it otherwise

**Comment by stephanie-cascade8** [comment]
@2amarkina we need a UX descision on this too. Let's discuss it after the holiday?

**Comment by stephanie-cascade8** [comment]
This issue is solved by the "Responsive large screens issue".
