### ISSUE TITLE
Meeting Session

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3810]
Adapt [wireframes](https://www.figma.com/file/YukjSA7E5kpG5VzdeF64VN/%5B-Meetings-%5D?node-id=0%3A1) to screens, PL is the team leader for the devs

link to epic #3680

**Comment by stephanie-cascade8** [comment]
mockups available here 
https://projects.invisionapp.com/d/main?origin=v7#/projects/prototypes/20186702
