### ISSUE TITLE
 Documenting tests 

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3817]
Documenting tests to prepare meeting with blockchain xdev

 - notion doc

**Comment by xmano** [comment]
For unit-tests I am proposing following sections:

`
Unit-Tests Docs
===============
1. Introduction & Background
    - Jest 

2. Setup; Run the tests.

2.1  General Test

2.2  Using Firestore Emulator


3. Test Organization
    
3.1 Backend Tests

3.2 Angular Services

3.3 Angular Components

`

**Comment by xmano** [comment]
Review the notion documents on E2E and Unit-Tests and close the issue.
