### ISSUE TITLE
Create JWPlayer component

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#3820]
# Component
- name: jw-player
- lib/app: ui

## Description
Generic component for displaying video.

## Type
- [X] **Component**: _Structure a piece of data in the page (ex: MovieTable)._

### Input
- [x] ref: The reference of the movie in cloud storage

## Where is it used
- event-player
- movie marketplace

**Comment by fritzschoff** [comment]
@pldespaigne is that issue for you?

**Comment by pldespaigne** [comment]
link to #2658

**Comment by pldespaigne** [comment]
link to #4115
