### ISSUE TITLE
[Bug] Still photo low quality 

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#3822]
I've uploaded a high quality image for still photo and the result is bad.
Looks like Imgix params are too low for these images:
![image](https://user-images.githubusercontent.com/8143464/94670156-79a3ba80-0312-11eb-93d4-6be8852ef8e4.png)

**Comment by pldespaigne** [comment]
This is definitely the ImageDirective that ask imgix for an Image with a default size that is too small for the display size (css).
You should update the ImageDirective to either add a new default format or add a size override input.
