### ISSUE TITLE
Initialization of app crash when doing Unit tests on backend-functions dir.

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3824]
Initialization of app crash when doing Unit tests on backend-functions dir.
This is certainly due to this line in "apps/backend-functions/src/internals/firebase.ts" :
```
admin.initializeApp(functions.config().firebase);
```
Which is being called before `initFunctionsTestMock();` inside beforeAll of tests.

**Comment by xmano** [comment]
Do you have a sample Unit Test for this?

An idea I have for this is to gate the initialization with some Jest environment check

`
if (!Jest.test()) {
  admin.initializeApp(config().firebase);
}
`
Also I want to check on best practice for cloud functions unit test before implementing it.. just to be sure.

**Comment by phpgeekfr** [comment]
@xmano npx jest apps/backend-functions/src/twilio.spec.ts

gives 
```
The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initia
lizeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.
```

**Comment by xmano** [comment]
Got the tests to run against local emulator:

![image](https://user-images.githubusercontent.com/8731418/96960551-4d99e480-1520-11eb-8c48-143a9c86ee49.png)


However we need to refactor events to get it working:

`
import {hasUserAcceptedEvent} from "./internals/invitations/events";
`
