### ISSUE TITLE
Improvments on upload heavy file on storage

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3831]
This follows #2586

- [x] add other file ext support (ogg, webmp etc)
- [ ] clean
 ```  
  // @TODO #2586 remove this when we can upload 
  // videos through movie tunnel and remove the component for external links
  // + migration for cleaning
  clip_link: string,  
  promo_reel_link: string,
  screener_link: string,
  teaser_link: string,
  trailer_link: string,
  other_links: OtherLink[],
 ```  

- [x] include `MovieVideoUploadComponent` into movie-tunnel

link to master issue #3639

**Comment by pldespaigne** [comment]
only the cleaning is needed now thanks to the new file-explorer architecture

**Comment by pldespaigne** [comment]
We decided to leave link in the data model until full video support is done.
After that we will need to decide how to handle existing link in prod:
- do we simply delete them (user lose data)
- do we download all the video and then upload them to jwPlayer (no data loss but really complex and costly migration)

**Comment by Jackseed** [comment]
@pldespaigne we will delete them and warn users that we're doing so. When it's possible to upload it ourselves we will offer them to do it for them but most of the time we will ask them to do it as handling media ressources is their job and they should know what they have on Archipel Market. 
This has to be prepared of course so the release of this feature will be a bit trickier than usually
