### ISSUE TITLE
Set a loading state before displaying the data

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3858]
On a lot of pages we use two states:
- empty (illustration + message)
- full (content)

Since we display the page before loading the data, we usually have a glitch showing the empty state for a second or so and then the full state when the data is loaded. 

This is frustrating for the user and we should instead have a loading state displayed while the data is loading and then display the correct status when we know if there is content to show or not. 

I guess this is a generic use case that should be discussed with @GrandSchtroumpf for the strategy and @2amarkina & @stephanie-cascade8 for the layout.

**Comment by Jackseed** [comment]
referencing #2496 for design discussion

**Comment by phpgeekfr** [comment]
This as been done on wishlist page and dashoard/home.

Loader for movie list was already done in develop
