### ISSUE TITLE
Homogenize the way users are mentioned

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3868]
Homogenize the way users are mentioned. For now, sometimes they’re mentioned by their names (no email, no company information. In notifications for example), sometimes just their first name & company (email notifications), sometimes just by their email address (guest list). 

When we mention someone, wherever this is (in a notification/an invitation/a list/ an email), it should always show first name, last name, email address & company name.
The format should be: "firstName lastName (orgName) blablabla" + adding the user email on link mailto on the firstname + lastName.
e.g. [Vincent Choukroun](Vchoukroun@cascade8.com) (Cascade8) has accepted your invitation to screening "blabla""

**Comment by Jackseed** [comment]
@RemcoSimonides @Mussuranae, Marie also gave me the feedback that we should display more info on the invitation list placed in the event form
![image](https://user-images.githubusercontent.com/14964443/98944828-f5884980-24f1-11eb-8b09-c67b9a2e0f4a.png)
If that's possible we should display: First Name Last Name - email address (org name)

Is there a link to this issue or should I create a separate one?

**Comment by RemcoSimonides** [comment]
Here is fine ;) it's sort-of related

**Comment by Jackseed** [comment]
Re my last comment I just opened a discussion on #design, the answer could impact that so let's discuss it when you get to that point
![image](https://user-images.githubusercontent.com/14964443/98952752-18b7f680-24fc-11eb-93c4-792f27bd6cb8.png)

**Comment by Mussuranae** [comment]
For the email part, we will do it later as the email needs a complete rework also.
See the issue for emails here #4263
