### ISSUE TITLE
Style bugs

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3869]
### Marketplace event view
- [x] Couldn't find the zeplin, just got the [invision](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/412246439/preview?scrollOffset=3441.25) but spaces between event title and event type + spaces between event status & CTA button doesn't look good:
![image](https://user-images.githubusercontent.com/14964443/94546945-df2e7300-024e-11eb-94f2-c04091f16c48.png)
vs
![image](https://user-images.githubusercontent.com/14964443/94546958-e48bbd80-024e-11eb-98bd-de2bd30e3dff.png)

### Notifications
- [x] Not sure of that grey bar on top of notifications, can we remove it?
![image](https://user-images.githubusercontent.com/14964443/94840924-8eb74100-0419-11eb-8784-e7c1dc776358.png)

### Marketplace Homepage
- [ ] Move to wishlist CTA is too close to the bottom, it makes the whole "featured film" banner component unbalanced
An issue has been created about the rework on this component #4144 
![image](https://user-images.githubusercontent.com/55785823/94924181-58cb9880-04bd-11eb-9caf-b48cb7c14859.png)

**Comment by RemcoSimonides** [comment]
- [ ] Missing placeholder in "genres", "country of origin", "languages & version" filters
![image](https://user-images.githubusercontent.com/27687382/95319719-99019100-0898-11eb-8b37-aa734be6103a.png)

**Comment by RemcoSimonides** [comment]
- [ ] Arrow doesn't disappear when being at the end of the carrousel
![image](https://user-images.githubusercontent.com/27687382/95319769-b0d91500-0898-11eb-89f8-90e2c5ac1f2b.png)

**Comment by Jackseed** [comment]
From @xmano 
Image upload issue in Movie Form:

![image](https://user-images.githubusercontent.com/8731418/95338903-0fba8080-08d1-11eb-9040-b664ffc8c0fa.png)

1.  The file upload dialog allows you to select any type of file to upload. Similarly for drag and drop. It should be restricted to image files (jpg, png) only.

2. If user cancels drag & drop, the UI state does not change to browse / drag option as shown below:

![image](https://user-images.githubusercontent.com/8731418/95339377-a25b1f80-08d1-11eb-8baf-cf761e3f0e8d.png)
