### ISSUE TITLE
Patch release 1.9 bug list - summary

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3887]
**There are two branches for this: **
- `hotfix/release/1.9` for fixes that involve only front
- ` hotfix/release/1.9-back` for fixes that involve backend funcs

----------------------

- [x] on movie page, banner says there are no screenings even though there is one
![image](https://user-images.githubusercontent.com/27687382/95084184-d097fe00-071d-11eb-9b9b-398a7231f2b8.png)

- [x] Able to select second session, even though there is only one session available
![image](https://user-images.githubusercontent.com/27687382/95084379-15bc3000-071e-11eb-8253-af6f9b814d61.png)

**Comment by xmano** [comment]
Image upload issue in Movie Form:

![image](https://user-images.githubusercontent.com/8731418/95338903-0fba8080-08d1-11eb-9040-b664ffc8c0fa.png)

1.  The file upload dialog allows you to select any type of file to upload. Similarly for drag and drop. It should be restricted to image files (jpg, png) only.

2. If user cancels drag & drop, the UI state does not change to browse / drag option as shown below:

![image](https://user-images.githubusercontent.com/8731418/95339377-a25b1f80-08d1-11eb-8baf-cf761e3f0e8d.png)

**Comment by Jackseed** [comment]
### Maintenance
- [ ] Blank page on prod while the deploy was on its way, no maintenance page

**Comment by Jackseed** [comment]
- [ ] Bad quality on stills https://github.com/blockframes/blockframes/issues/3822

**Comment by Jackseed** [comment]
### Marketplace all films filters
- [ ] Production status filter on all films page is not blue when selected
![image](https://user-images.githubusercontent.com/14964443/95085374-6ed89380-071f-11eb-96a0-28e154c58c06.png)
![image](https://user-images.githubusercontent.com/14964443/95085384-71d38400-071f-11eb-8495-7ff51cb6876f.png)

- [ ] The checkboxes inside Production status and Language & Version filters are not cleared when clicking the "Clear all filters" button. That's confusing as it looks like the filter is still applying while it's not.
![image](https://user-images.githubusercontent.com/14964443/95085628-c5de6880-071f-11eb-960a-bd9326350e17.png)

**Comment by Jackseed** [comment]
- [ ] Missing placeholder in "genres", "country of origin", "languages & version" filters
![image](https://user-images.githubusercontent.com/27687382/95319719-99019100-0898-11eb-8b37-aa734be6103a.png)

- [ ] Arrow doesn't disappear when being at the end of the carrousel
![image](https://user-images.githubusercontent.com/27687382/95319769-b0d91500-0898-11eb-89f8-90e2c5ac1f2b.png)

**Comment by phpgeekfr** [comment]
- [ ] Dashboard movie view shows producers as "Missing" when they're not (they appear on the marketplace)

<img width="405" alt="Capture d’écran 2020-09-29 à 09 56 43" src="https://user-images.githubusercontent.com/27687382/95720136-1d755a80-0c71-11eb-80d4-731407f2bf70.png">
<img width="801" alt="Capture d’écran 2020-09-29 à 09 57 01" src="https://user-images.githubusercontent.com/27687382/95720138-1ea68780-0c71-11eb-9ca1-70ea32a54d2c.png">

this is the movie I spotted it on: RYQvSEka2kxefOrl8g8L

**Comment by phpgeekfr** [comment]
- [ ] Display statistics of an event at the end of the event form; same as event dashboard view. For the moment, you can't access the view before the event is finished (or with the direct url) and that's annoying for multiple day screenings since they'd like to have their stats asap

**Comment by phpgeekfr** [comment]
- [ ] Update the stats table for events by adding: Org name (label: Company Name), org activity (label: Company Activity)
![image](https://user-images.githubusercontent.com/14964443/94548896-af349f00-0251-11eb-9fa2-ae38352eddbc.png)

**Comment by phpgeekfr** [comment]
- [ ] Homogenize the way users are mentioned. For now, sometimes they’re mentioned by their names (no email, no company information. In notifications for example), sometimes just their first name & company (email notifications), sometimes just by their email address (guest list). When we mention someone, wherever this is (in a notification/an invitation/a list/ an email), it should always show first name, last name, email address & company name.
The format should be: "firstName lastName (orgName) blablabla" + adding the user email on link mailto on the firstname + lastName.
e.g. [Vincent Choukroun](Vchoukroun@cascade8.com) (Cascade8) has accepted your invitation to screening "blabla""

> dedicated issue #3868

**Comment by phpgeekfr** [comment]
- [ ] Couldn't find the zeplin, just got the [invision](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/412246439/preview?scrollOffset=3441.25) but spaces between event title and event type + spaces between event status & CTA button doesn't look good:
![image](https://user-images.githubusercontent.com/14964443/94546945-df2e7300-024e-11eb-94f2-c04091f16c48.png)
vs
![image](https://user-images.githubusercontent.com/14964443/94546958-e48bbd80-024e-11eb-98bd-de2bd30e3dff.png)

=> dedicated issue #3869

**Comment by phpgeekfr** [comment]
- [ ] Security pop up when deleting an event: “Are you sure you want to delete this event? All of the invitations and requests associated to it will be deleted.”
> linked to the design issue [here](https://github.com/blockframes/blockframes/issues/2873)

- [ ] Use that same pop-up with different text when viewer is about to leave a screening room: “Are you sure? You might not be able to come back to this screening as its access is time-limited.”

=> dedicated issue #3870

**Comment by phpgeekfr** [comment]
- [ ] Add a description input on screening form
https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/415037534/preview?scrollOffset=6661.25 & 
screening marketplace view https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/411867784/preview?scrollOffset=3358.75

=> dedicated issue #3871

**Comment by phpgeekfr** [comment]
- [ ] Search bar on the invitation list (dashboard event form) is not consistent and doesn't work on some cases (not all of them, no pattern found :/) 
<img width="1082" alt="Capture d’écran 2020-09-29 à 12 54 02" src="https://user-images.githubusercontent.com/14964443/94565305-54a73d00-0269-11eb-8386-cc2f322b11a2.png">
<img width="1106" alt="Capture d’écran 2020-09-29 à 12 54 25" src="https://user-images.githubusercontent.com/14964443/94565314-56710080-0269-11eb-87f3-76d800bbefd8.png">
<img width="1090" alt="Capture d’écran 2020-09-29 à 12 56 05" src="https://user-images.githubusercontent.com/14964443/94565316-57a22d80-0269-11eb-880e-cce97452d605.png">
<img width="1089" alt="Capture d’écran 2020-09-29 à 12 54 17" src="https://user-images.githubusercontent.com/14964443/94565329-5a048780-0269-11eb-9fcc-2e3be34a755e.png">

=> dedicated issue #3872

**Comment by phpgeekfr** [comment]
- [ ] [Bug] Still photo low quality #3822

- [ ] Move to wishlist CTA is too close to the bottom, it makes the whole "featured film" banner component unbalanced 
![image](https://user-images.githubusercontent.com/55785823/94924181-58cb9880-04bd-11eb-9caf-b48cb7c14859.png)

=> dedicated issue #3869

- [ ] Wishlist always appears empty before loading titles. Very confusing

=> dedicated issue #3858

**Comment by phpgeekfr** [comment]
- [ ] on movie page, banner says there are no screenings even though there is one
[edit: this happens when the events are already running, not when it's in the future]
![image](https://user-images.githubusercontent.com/27687382/95084184-d097fe00-071d-11eb-9b9b-398a7231f2b8.png)

- [ ] Able to select second session, even though there is only one session available
![image](https://user-images.githubusercontent.com/27687382/95084379-15bc3000-071e-11eb-8253-af6f9b814d61.png)

**Comment by phpgeekfr** [comment]
- [ ] Production status filter on all films page is not blue when selected
![image](https://user-images.githubusercontent.com/14964443/95085374-6ed89380-071f-11eb-96a0-28e154c58c06.png)
![image](https://user-images.githubusercontent.com/14964443/95085384-71d38400-071f-11eb-8495-7ff51cb6876f.png)

- [ ] The checkboxes inside Production status and Language & Version filters are not cleared when clicking the "Clear all filters" button. That's confusing as it looks like the filter is still applying while it's not.
![image](https://user-images.githubusercontent.com/14964443/95085628-c5de6880-071f-11eb-960a-bd9326350e17.png)

=> dedicated issue #3869

**Comment by Jackseed** [comment]
- [ ] Add Google Analytics & google tag manager as necessary cookie that can't be disabled as it's part of our value proposition to give accurate stats to sales agents on screenings.
Concretely, it means changing Google position to go below Cascade 8, enabled by default and that can't be disabled. 
The text is changed for:
"Google Tag Manager and Google Analytics are used to monitor users’ behavior on our services, which include giving accurate statistics to sales agents based on that cookie."
![image](https://user-images.githubusercontent.com/14964443/95972654-01a9ba00-0e13-11eb-88e8-c209b4fac905.png)
