### ISSUE TITLE
Festival: Event UI calendar display needs improvements

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#3900]
Images on event are stretched and event display does not look good.

![image](https://user-images.githubusercontent.com/8731418/95324039-bfd1be80-08bc-11eb-98da-887ff5e13dec.png)

**Comment by Jackseed** [comment]
From @jdrns review 
### Dashboard / My events
- [ ] Title of event screening cropped (text too big) 
<img width="587" alt="Screenshot 2021-03-18 at 16 11 39" src="https://user-images.githubusercontent.com/79836137/111649971-290f1380-8805-11eb-8b70-f51b9c561bc4.png">

**Comment by stephanie-cascade8** [comment]
Let's do this to make it way better : 
- [ ]  line-height: 1;
- [ ]  margin-bottom: 0;
- [ ]  font-size: 13px;

See the result 
<img width="679" alt="Capture d’écran 2021-08-11 à 17 43 51" src="https://user-images.githubusercontent.com/66258851/129061333-0f2243a5-3370-4d48-a918-e2ca9da7b63f.png">

<img width="490" alt="Capture d’écran 2021-08-11 à 17 48 28" src="https://user-images.githubusercontent.com/66258851/129061456-7821e8cb-a48b-4ab0-bf5d-56484f644ea9.png">

@2amarkina do you want to discuss cutting with ellipsis the titles when they are over a certain number of caracters and show tooltip with fullname on hover maybe?

**Comment by RemcoSimonides** [comment]
@stephanie-cascade8 @2amarkina has this question already been answered?
"@2amarkina do you want to discuss cutting with ellipsis the titles when they are over a certain number of caracters and show tooltip with fullname on hover maybe?"

**Comment by 2amarkina** [comment]
Not yet. 
This worths discussion, indeed! I do not know if it should go with global improvements of calendar or can be done directly. 

@stephanie-cascade8 I think that adding a tooltip with a full name can be introduced right now, if possible.
For the number of characters some tests should be done.

**Comment by RemcoSimonides** [comment]
> Let's do this to make it way better :
> 
> * [ ]   line-height: 1;
> * [ ]   margin-bottom: 0;
> * [ ]   font-size: 13px;
> 
> See the result <img alt="Capture d’écran 2021-08-11 à 17 43 51" width="679" src="https://user-images.githubusercontent.com/66258851/129061333-0f2243a5-3370-4d48-a918-e2ca9da7b63f.png">
> 
> <img alt="Capture d’écran 2021-08-11 à 17 48 28" width="490" src="https://user-images.githubusercontent.com/66258851/129061456-7821e8cb-a48b-4ab0-bf5d-56484f644ea9.png">
> 
> @2amarkina do you want to discuss cutting with ellipsis the titles when they are over a certain number of caracters and show tooltip with fullname on hover maybe?

Your image says `font-size: 12px` but you write `font-size: 13px`. Which one do you want?
This is result with 13px
![image](https://user-images.githubusercontent.com/27687382/137472636-d38f909d-5953-427b-b32b-8827a0890e80.png)

This is result with 12px
![image](https://user-images.githubusercontent.com/27687382/137472784-88853d0f-9a74-4829-8e4b-e72ceafa4007.png)
