### ISSUE TITLE
Factorize the confirmExit in shell

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#3908]
Currently we need to reimplement the `confirmExit` on every tunnel shell
A simple solution would be to create a parent component `TunnelShell` that manage the `confirmExit` methods in the shells.
Or create a reusable function just for this method...
I'm open to ideas

**Comment by fritzschoff** [comment]
I moved the confirmExit function inside the exit tunnel component. When clocked on exit this function calls the onSave function on the formConfigs or navigates away without saving.

**Comment by fritzschoff** [comment]
Also removed the TunnelGuard since the confirmExit function is not part of the root component anymore

**Comment by fritzschoff** [comment]
https://github.com/blockframes/blockframes/pull/4612 
Financiers, Festival and Catalog building without an error, but crm and cms are crashing but I can't find the issue
