### ISSUE TITLE
E2E Tests fail to run

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#3927]
Nightly E2E test fail to run.

Logs show:

```
DB backup in local storage bucket is being restored into Firestore...
invalid status code on restore: 302. Check your firebase functions logs (admin function)
Time running command "prepareForTesting": 37689.427ms

Exited with code exit status 1
CircleCI received exit code 1
```

It could be DB restore issue. Or further issues may be present in CI environment.

**Comment by phpgeekfr** [comment]
Closing this since we know what is the issue. @george43g is currently working on it : #2531

**Comment by xmano** [comment]
Update: 15/Oct/2020

`
var algolia = __assign(__assign({}, _env__WEBPACK_IMPORTED_MODULE_1__["algolia"]), { adminKey: _env__WEBPACK_IMPORTED_MODULE_1__["dev"] ? Object(_firebase_utils__WEBPACK_IMPORTED_MODULE_5__["mockConfigIfNeeded"])('algolia', 'api_key') : firebase_functions__WEBPACK_IMPORTED_MODULE_2__["config"]().algolia.api_key });
                                                                                                                                                                                                                                                                                                                ^

TypeError: Cannot read property 'api_key' of undefined
    at Module../libs/firebase-utils/src/lib/algolia.ts (/home/circleci/repo/dist/apps/backend-ops/main.js:3579:305)
    at __webpack_require__ (/home/circleci/repo/dist/apps/backend-ops/main.js:20:30)
    at Module../libs/firebase-utils/src/index.ts (/home/circleci/repo/dist/apps/backend-ops/main.js:3510:70)
    at __webpack_require__ (/home/circleci/repo/dist/apps/backend-ops/main.js:20:30)

`

**Comment by phpgeekfr** [comment]
@xmano  This time the issue seems to be related to something I did yesterday. I'm on it

**Comment by phpgeekfr** [comment]
@xmano should be corrected, we will see tomorrow morning
