### ISSUE TITLE
Change admin email recipient for support@appName

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3928]
Admin emails should be redirected to their dedicated support@appName adresses.
It includes:
- [x]  org creation 
- [x] app access
- [x] demo request on landing page

**Comment by Jackseed** [comment]
@phpgeekfr also need to change the email recipient for the contact for demo request on landing page

**Comment by phpgeekfr** [comment]
@Jackseed  does 
- support@archipelmarket.com
- support@archipelcontent.com
- support@mediafinanciers.com

already exists ?

**Comment by Jackseed** [comment]
@phpgeekfr now they do :)

**Comment by phpgeekfr** [comment]
New env vars to put on CI :
```
#prod
blockframes_CASCADE8_ADMIN_CATALOG => support@archipelcontent.com
blockframes_CASCADE8_ADMIN_FESTIVAL => support@archipelmarket.com
blockframes_CASCADE8_ADMIN_FINANCIERS => support@mediafinanciers.com

#staging
blockframesStaging_CASCADE8_ADMIN_CATALOG => dev+staging_catalog@blockframes.io
blockframesStaging_CASCADE8_ADMIN_FESTIVAL => dev+staging_festival@blockframes.io
blockframesStaging_CASCADE8_ADMIN_FINANCIERS => dev+staging_financiers@blockframes.io

```

For other envs, `projectId_CASCADE8_ADMIN` will be used as fallback for `projectId_CASCADE8_ADMIN_appName`
