### ISSUE TITLE
CRM App - Delete a movie

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3932]
Add a button on the movie page to delete a movie (and all objects related to it). Before deleting, the confirmation modale should be used. 

Bonus: if it's not too difficult, would be good to add it on the movie list also with the ability to select multiple movies to delete at once. Here again the confirmation modale should be used

**Comment by Jackseed** [comment]
Other docs to check when deleting a movie: 
- orgs: movieIds
- Invitations: docId
- Contracts: titleIds
- Wishlist
- Permissions ?
- Events
- Invitation to event

**Comment by phpgeekfr** [comment]
Display a popup before deleting that shows what is going to be deleted and add an input where user must type "DELETE" to make the delete button working + do the same for user deletion on crm app
