### ISSUE TITLE
CRM App - Delete an org

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3933]
Add a button on the org page to delete an org (and all objects related to it). Before deleting, the confirmation modale should be used.
Related objects are:
- users included in userIds
- permissions
- notifications
- invitations
- movies included in movieIds

Bonus: if it's not too difficult, would be good to add it on the org list also with the ability to select multiple orgs to delete at once. Here again the confirmation modale should be used

**Comment by phpgeekfr** [comment]
Display a popup before deleting that shows what is going to be deleted and add an input where user must type "DELETE" to make the delete button working + do the same for user deletion on crm app
