### ISSUE TITLE
Dashboard Movie view - Button to see film on marketplace

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3939]
We should add a button for the sales agents to go directly from their movie page on dashboard to their movie page on marketplace. 
Before creating the UI would be good to have a UX proposition on where to place that button

**Comment by 2amarkina** [comment]
Three propositions for the place of the CTA to go to directly to the movie page : 

1. Version 1 - replace the "Edit" btn by "See on the marketplace" as the all parts of the Movie are editable on the movie page 
<img width="693" alt="Снимок экрана 2020-12-01 в 16 33 44" src="https://user-images.githubusercontent.com/55499036/100761289-05a98f80-33f3-11eb-86c0-9530afe91a4c.png">
2. Version 2 - Have three different actions 
<img width="800" alt="Снимок экрана 2020-12-01 в 16 34 39" src="https://user-images.githubusercontent.com/55499036/100761387-2245c780-33f3-11eb-805a-3c56c48ccf74.png">
3. Version three (the best one to my mind) - "Edit btn" changes it place and goes on the poster and opens the "Main information" page of Movie tunnel. "App specific CTA" and "See on the Marketplace" are on the right 
<img width="840" alt="Снимок экрана 2020-12-01 в 16 36 27" src="https://user-images.githubusercontent.com/55499036/100761602-5faa5500-33f3-11eb-8c59-b3d78bb88752.png">

All the screens are accessibles on this figma page [CTA Propositions ](https://www.figma.com/file/qpLBi85x3y0s4fLpJPACOm/Wireframing-Elements?node-id=198%3A530)
