### ISSUE TITLE
Create a page on Notion with a check list of what should be done to setup developers env

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3950]
Create a page on Notion with a check list of what should be done to setup developers env.

- [ ] cascade8 email setup
- [ ] How to access slack
- [ ] How to access github project
- [ ] How to setup env
- [ ] How to setup imgIx 
- [ ] How to setup algolia
- [ ] How to setup jwplayer
- [ ] How to setup ...
- [ ] How run prepare for testing #3583

And maybe a word about backup / restore DB and storage CF `Update notion.so documentation` #3598

Link every step to corresponding notion tutorial if any.
Add all tips and troubleshooting steps you encountered.

**Comment by phpgeekfr** [comment]
Also added @Jackseed on this issue for the steps he is responsible for as project admin

**Comment by Jackseed** [comment]
@Mussuranae I created this page re the accounts to create when we onboard a new person: https://www.notion.so/cascade8/Checklist-for-a-new-teammate-3e2e925e8e8b4d7f91bde02a5e0fd91d

This checklist should be used every time there is a new person coming, I don't know what's better between creating a column per person or just adding the name of the person once it's done as I did in this page. Looking forwarding having your point of view ;)

**Comment by Mussuranae** [comment]
I guess your file is incomplete, but the way you did is good.
For the dev, I created a page with more details on what's we have to do to set up the project, deploy function/hosting, etc... We can also complete it next time we onboard a new dev, I feel the part about the command line of George can be improved a lot.

https://www.notion.so/cascade8/Set-Up-for-Devs-4068062ade2d4967a9f04383ff30dd5b

**Comment by phpgeekfr** [comment]
@george43g As @Mussuranae mentioned above can you look at this notion page & improve your part ?

**Comment by RemcoSimonides** [comment]
Would be cool to have this finished before June. Then the new developers can use this.

**Comment by Mussuranae** [comment]
I guess there is only a part about the .env file we can add. As I didn't run the command to create it a lot of time, maybe @george43g can do a little explanation in the notion page.
