### ISSUE TITLE
Check Invitations & Notifications

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#3958]
Ensure that all notifications & invitation are triggered correctly and have the **good message**.

List of required notifications & invitation can be found [here](https://docs.google.com/spreadsheets/d/1DCO2PH0HaSnt3y6DSPnIX6hXbGsaCw10tCR38gG8LyM/edit#gid=0) under the category "Event" & "Meeting"

link to epic #3679

**Comment by RemcoSimonides** [comment]
There are a few differences:
Line numbers are referring to the row in the excel doc

- [ ] line 34: [ Organizer's Name {mailto: Organizer's Email}] ([ Organization Name ])  invited you to [ Event Type ] [ Event Name {Marketplace Event URL} ]. [ Event Date ]
- [ ] line 35: [ User's Name {mailto: User's Email}] ([ Organization Name ]) has accepted your invitation to [ Event Name {Dashboard Event URL}].
- [ ] line 36: [ User's Name {mailto: User's Email}] ([ Organization Name ]) has declined your invitation to [ Event Name {Dashboard Event URL}].
- [ ] line 37: [ User's Name {mailto: User's Email}] ([ Organization Name ]) would like to attend [ Event Type ] [ Event Name {Dashboard Event URL}], [ Event Date ].
- [ ] line 38: Your request to attend [ Event Type ] [ Event Name {Marketplace Event URL}] has been sent.
- [ ] line 39: [ Organization Name ] has accepted your request to [ Event Type ] [ Event Name {Dashboard Event URL} ].
- [ ] line 40: [ Organization Name ] has declined your request to [ Event Type ] [ Event Name {Dashboard Event URL} ].
