### ISSUE TITLE
Invitation bug with email address starting with "s"

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3961]
On invitations, email adresses starting with an "s" are not working, the "s" is deleted - I can't reproduce this one. 's' is not removed.

**Comment by Jackseed** [comment]
Re this ticket, @RemcoSimonides had worked on it so he may have insights

**Comment by RemcoSimonides** [comment]
I couldn't reproduce this one. I could see the mail being queued in SendGrid without the 's' being removed

**Comment by Jackseed** [comment]
@RemcoSimonides hum yep same for me, I'll ask Marie again to have details

**Comment by Jackseed** [comment]
@RemcoSimonides @phpgeekfr I finally can reproduce it! It's indeed for all invitations of email addresses starting with an "s" (lower case) BUT it works for the first email on the list and not for all the others. 
Examples:
shy@fake.com, bruce@fake.com, sirius@fake.com > shy@fake.com, bruce@fake.com, irius@fake.com
bruce@fake.com, shy@fake.com, sirius@fake.com > bruce@fake.com, hy@fake.com, irius@fake.com
bruce@fake.com, Shy@fake.com, Sirius@fake.com > bruce@fake.com, Shy@fake.com, Sirius@fake.com

**Comment by phpgeekfr** [comment]
Looking forward to find the source of this kind of cool bug ^^

**Comment by Jackseed** [comment]
New occurence of what looks like the same bug:
<img width="237" alt="Capture d’écran 2020-11-06 à 18 57 04" src="https://user-images.githubusercontent.com/14964443/98546862-9fb86500-2297-11eb-9ba3-4e53581c5fcc.png">

The "s" from ".es" has disappeared, though the user was in the last position of the list
