### ISSUE TITLE
Update the stats table for events by adding: Org name (label: Company Name), org activity (label: Company Activity) & org country (label Country)

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3965]
- [x] Update the stats table for events by adding: Org name (label: Company Name), org activity (label: Company Activity)
![image](https://user-images.githubusercontent.com/14964443/94548896-af349f00-0251-11eb-9fa2-ae38352eddbc.png)

Edit from Vincent: we also need to add the org country (label: Country) to the table by taking the org address country. 

_Originally posted by @phpgeekfr in https://github.com/blockframes/blockframes/issue_comments/707651149_

**Comment by Jackseed** [comment]
I created a new issue that is more broader than this one: #4257. 
It could be done in 2 times but I prefer to reference this in case you prefer to do all at once

**Comment by phpgeekfr** [comment]
#4257 will be done after since the two tables (invitations & attendees) are not fetching data from the same source

**Comment by phpgeekfr** [comment]
@Jackseed does this fit your needs ? 

![image](https://user-images.githubusercontent.com/1194344/99667509-d0a15280-2a6c-11eb-8c80-3fe20ffb4f4d.png)

**Comment by Jackseed** [comment]
@phpgeekfr it's perfect! Thanks :)
