### ISSUE TITLE
on movie page, banner says there are no screenings even though there is one

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3966]
- [x] on movie page, banner says there are no screenings even though there is one
[edit: this happens when the events are already running, not when it's in the future]
![image](https://user-images.githubusercontent.com/27687382/95084184-d097fe00-071d-11eb-9b9b-398a7231f2b8.png)

- [x] Able to select second session, even though there is only one session available
![image](https://user-images.githubusercontent.com/27687382/95084379-15bc3000-071e-11eb-8253-af6f9b814d61.png)

_Originally posted by @phpgeekfr in https://github.com/blockframes/blockframes/issue_comments/707653419_

**Comment by Mussuranae** [comment]
Fix with the #3977  pull request
