### ISSUE TITLE
E2E : Cypress XHR response very slow during movie creation

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4000]
In movie-tunnel test, at the step when a new movie is created, there is extreme slowness noticed.

It is suspected that multiple XHR at this point are causing the issue.

cy.wait() is not a good workaround here. We need better way to avoid this slow response issue.

A possible solution could be to disable GA since they are not directly related for the UI test.

**Comment by xmano** [comment]
It is similar to the issue:

https://github.com/blockframes/blockframes/issues/3708

But now the problem is severe when multiple XHR requests are ongoing. During movie create I suspect we might be calling some additional network services.

**Comment by phpgeekfr** [comment]
@xmano I don't see how it is related to GA, can you explain ?
Did you tried to disable it on your local to check if tests passes ?

**Comment by xmano** [comment]
One thing is that these steps are ok on normal browser and seem to be slow with Cypress launched browser. Its my suspicion that this may be related to GA since they are also involved at the movie creation step. But I need to do further debugging to confirm this. 

I checked network tab in debugger and indeed some requests were stalling. I am unable to pin-point which requests that might be and why.

How do I disable GA on my local? 

I need some help in check this further.  We will discuss it and see additional debug steps that can be done.

**Comment by xmano** [comment]
I noticed that there are 502 errors with logging:

![image](https://user-images.githubusercontent.com/8731418/96605622-0b9c5300-1314-11eb-9e3c-c48b4ec1b2d0.png)

Maybe this causes Cypress to get confused and retry it some more. Will check on this. 

Normal browser testing does not have this problem as it is ignored.
