### ISSUE TITLE
Clean lib media

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#4002]
`lib/media` is starting to be a mess, take some times to reorganize it.
Every cleaning steps is detailed in comments bellow, but here is a quick summary:

- [x] rename & move components
- [x] implement new file architecture in the back-end
- [x] factorize standalones & puppets
- [x] refactor file-carousel

- implement new file architecture in the front-end
  - [x] new upload service
  - movie
    - [x] presentation_deck
    - [x] moodboard
    - [x] scenario
    - [x] notes
    - [x] salesPitch
    - [x] financialDetails
    - [x] screener
    - [x] otherVideos
    - [x] stillPhotos
    - [x] banner
    - [x] poster
  - campaign
  - user
  - org
  - [ ] cleaning
  - [ ] bug fix

**Comment by GrandSchtroumpf** [comment]
General idea for the upload: 
- Updates of firestore should be done on the frontend (instead of backend).
- We should get rid of /tmp.
- Upload service should has the information of files to upload on which path, and which key in the object should be updated.

How it should look on the frontend : 
```typescript
save() {
  const doc = this.form.value;
  // Upload the images currently stored in the media service & once it's uploaded callback to update document
  this.mediaService.upload((field, path) => this.service.upate(doc.id, { [field]: path }));
  return this.service.update(doc);
}
exit() {
  this.service.clear(); // Remove all upload queue if not uploading
}
```
the issue with method above is that the document will change in the UI before images are uploaded, so we need to make sur img-uploader is not rerendered if the image is not uploaded yet. For that we need a service to store this information : 
```typescript
export interface UploadMedia {
  field: string;
  file: Blob;
}
@Injectable()
export class MediaService  {
  private tasks: AngularFireUploadTask[] = [];
  queue: Record<string, UploadMedia | null> = {};
  
  private attachWidget() { ... }
  private detachWidget() { ... }
 
  async upload(onUploaded: (field: string, path: string | null) => void) {
    this.isUploading = true;
    for (const [path, media] of Object.entries(this.queue)) {
      const ref = this.storage.ref(path);
      if (media === null) {
        ref.delete();
      } else {
        const task = ref.put(media.file);
        this.tasks.push(task);
        task.then(_ => onUploaded(media.field, path)).catch(_ => onUploaded(media.field, null));
      }
    }

    this.attachWidget();
    // Prevent Promise.all to fails
    const tasks = this.tasks.map(task => task.catch(_ => null))
    await Promise.all(tasks);
    this.detachWidget();
    this.isUploading = true;
    this.clear();
  }
  
  clear() {
    if (!this.isUploading) this.queue = {};
  }
}
```
And make the ImgUpload as a ControlValueAccessor:
```typescript
@Component({ ... })
export class ImgUpload implements ControlValueAccessor {
  @Input path: string;
  @Input field: string;
  control = new FormControl();
  initialValue = null;
  // Whenever server send current path in Firestore
  async writeValue(value: string) {
    if (value) {
      // Rerender only if value hasn't change
      if (value !== this.initialValue ) this.control.setValue(value);
    } else {
      // Remove the file from queue only if we changed from "hasValue" to "hasNoValue"
      if (value !== this.initialValue) {
        delete this.mediaService.queue[this.path];
        this.control.reset();
      }
    }
    this.initialValue = value;
  }
}
```

The examples above work only with single document upload. We can make it work with multiple collection/document with another field in `UploadMedia` interface.

**Comment by GrandSchtroumpf** [comment]
Components / Directives (selector is prefixed with folder name) : 
**file**: 
- uploader
- uploader-list
- widget
- selector (carousel)
- explorer
- preview (modal)
- puppet-viewer

**img**:
- upload (cropper)
- ref

**video**: 
- upload
- player
- control

**pdf**:
- viewer
- control

**Comment by pldespaigne** [comment]
factorize standalones & puppets

**Comment by pldespaigne** [comment]
refactor media-list (file-carousel) to be decoupled form event

**Comment by RemcoSimonides** [comment]
- [ ] Missing control component in movie form gives error
