### ISSUE TITLE
Improve notification feed display by providing more information

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4006]
After successful publishing the movie, a notification is received:

![image](https://user-images.githubusercontent.com/8731418/96579371-5efea900-12f4-11eb-8e4d-7a2200d5dd7e.png)

The notification feed should provide more information about the activity itself to be clear what was achieved.

Also from E2E test point of view, we can make sure the movie / activity was successfully carried out.

**Comment by Jackseed** [comment]
Yes changing "Your project for "MovieTitle" would be better

**Comment by Mussuranae** [comment]
Done here
https://github.com/blockframes/blockframes/pull/4586
