### ISSUE TITLE
Arrow doesn't disappear when being at the end of the carrousel

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#4013]
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/02316f7a-bd68-4fb1-9ed6-9f79102a1385)

**Comment by phpgeekfr** [comment]
This needs to be tested

**Comment by Jackseed** [comment]
It works only for In prod carousel but not the others, I guess there is a link with the amount of films as In prod has only 8 movies while the others a lot more

**Comment by Jackseed** [comment]
This bug is also there on stills, marketplace movie view

**Comment by RemcoSimonides** [comment]
Has already been fixed
