### ISSUE TITLE
Feat : Integrate Sentry into our workflow

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4014]
Need better integration of Sentry tool in our workflow

- [ ] Combine it with Unit-Test to detect potential problems
- [ ] Debug and Fix Sentry issues from staging and production
    - [ ] Sentry: Firebase Err - Missing or insufficient permissions. #4024

**Comment by Jackseed** [comment]
@xmano I feel that you are in the best position to transform Sentry issues into github ones (there is an existing connexion between the 2 services). 
These issues would be all debug ones for the sanity team

**Comment by phpgeekfr** [comment]
duplicate of  #8877
