### ISSUE TITLE
Patch release 1.9 bug list - summary bis

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#4019]
- [x] When country of an organization is too long, it changes the size of the organization-card on the organization list page
![image (3).png](https://images.zenhubusercontent.com/5d51508f6f935933f7158b07/2fb3d147-ed03-4ec9-8cdb-3c404b0430a7)

- [x] Not really a bug, but on the wishlist, we don't distinguish clearly the cell when some text are very long (here the country)
![image (4).png](https://images.zenhubusercontent.com/5d51508f6f935933f7158b07/b7798c45-50e2-4f2d-9a32-7f928376692f)

- [x] Here the margin isn't right, we need the same space between header and text and text and blue bar on the bottom (like 24px or maybe 36px), on organization page and movie page
![image](https://user-images.githubusercontent.com/48033264/96723312-b5302280-13ae-11eb-8678-7595c75f3bef.png)
![image](https://user-images.githubusercontent.com/48033264/96723349-c24d1180-13ae-11eb-855a-2ac23682fccf.png)

- [x] Here I think it's the slug that is displayed, not the label of the static data (movie page main tab)
![image](https://user-images.githubusercontent.com/48033264/96724005-9a11e280-13af-11eb-8714-5286db7171ec.png)

- [x] don't display 'confirmed' status if we haven't value for the running time (movie page main tab)
![image](https://user-images.githubusercontent.com/48033264/96724157-d04f6200-13af-11eb-9d80-6e79b1ab42dd.png)

- [x] No value displayed for language version
![image](https://user-images.githubusercontent.com/48033264/96724339-0391f100-13b0-11eb-972b-04240b38cb1c.png)

- [x] On movie list, the running time in the movie card is displayed differently depending on ????
![image](https://user-images.githubusercontent.com/48033264/96724769-7c914880-13b0-11eb-89ef-70e3314f4d3b.png)
![image](https://user-images.githubusercontent.com/48033264/96724824-8a46ce00-13b0-11eb-886b-96fff39a4ef4.png)

- [x] Same thing with the movie-header
![image (5)](https://user-images.githubusercontent.com/48033264/97014985-50f69580-154b-11eb-8c37-130fce954f08.png)

- [x] On event page, we have the back-arrow two time on the event header and the movie header
![image](https://user-images.githubusercontent.com/48033264/96726782-a0558e00-13b2-11eb-9b0c-89c04b335009.png)

- [ ] Marketplace home page, the arrow on the big slider aren't visible depending on the color of the banner in background
An issue has been created for this component rework #4144 
![image](https://user-images.githubusercontent.com/48033264/96727385-43a6a300-13b3-11eb-9f68-a2e721296fcf.png)

- [x] @phpgeekfr Marketplace home page, when I click on the `see all` button, I expect to have a list of movie with the status completed, but I have all the movies on the app (Linked to  #4032)
![image](https://user-images.githubusercontent.com/48033264/96728668-a187ba80-13b4-11eb-880c-54635a7294d7.png)

- [x] Marketplace Movie list page, when I enter a filter that will return no movie, there are movies and no-movie-message for few second before movies completely disappear
![weird](https://user-images.githubusercontent.com/48033264/96730901-f6c4cb80-13b6-11eb-9e6c-6f10a6debbeb.jpg)

- [x] the logo in the footer isn't clickable

- [x] The contact page has a scrollbar and is too big in regards to its content

- [x] On the dashboard title page when I click on "Click to see preview" of some images, if the image is broken (i.e. image doesn't exists in the storage) the preview is also broken instead of displaying a fallback image
![image](https://user-images.githubusercontent.com/5858657/97556805-3c4a4f80-19da-11eb-999c-3c71299e146d.png)

- [x] Confirm dialog before exiting an event always says "screening" even if the event is a meeting
![image](https://user-images.githubusercontent.com/5858657/97557147-ae229900-19da-11eb-94c3-35a3431dd10a.png)

**Comment by Jackseed** [comment]
- [ ] Dashboard film list, the production status use slug instead of label
![image](https://user-images.githubusercontent.com/14964443/96726515-5b315c00-13b2-11eb-9922-75b723221c6c.png)

**Comment by Jackseed** [comment]
- [ ] Dashboard movie view, there is still the additional info tab while there is no data (movieId 056cKWz9hCamDCgdIzeY)
![image](https://user-images.githubusercontent.com/14964443/96727329-37bae100-13b3-11eb-8e08-0b264d264177.png)

**Comment by Jackseed** [comment]
- [ ] One movie without poster keeps getting a poster from another film
![image (1)](https://user-images.githubusercontent.com/14964443/96746937-fbde4680-13c7-11eb-9f5a-c20d26f12e17.png)
![image](https://user-images.githubusercontent.com/14964443/96746941-fc76dd00-13c7-11eb-8235-e52a1d7019cf.png)

Id gao4ARHuWtY4vkf78AkR

**Comment by Jackseed** [comment]
- [ ] Dashboard film view there is an extra space before the coma
![image](https://user-images.githubusercontent.com/14964443/96850576-40fd8980-1457-11eb-816f-cbd830568a2a.png)

**Comment by phpgeekfr** [comment]
missing top text "on the market today" and refresh button on develop 
Example on production: 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/58d5c51c-53c8-4fff-8b96-3ad9b597593a)

**Comment by phpgeekfr** [comment]
@Mussuranae can we close or is there still some work to do before?

**Comment by Mussuranae** [comment]
There was still one last about `One movie without poster keeps getting a poster from another film` but can't reproduce it :/

**Comment by Jackseed** [comment]
That's alright, let's close it and wait to see if it happens again
