### ISSUE TITLE
Movie form design review

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4035]

**Comment by stephanie-cascade8** [comment]
https://docs.google.com/document/d/1_8jHnImpjCc7ECU5Q8_fBcadAFh85DQo5Wl-zT4Z9cg/edit

**Comment by 2amarkina** [comment]
https://docs.google.com/document/d/1bpJomjfNj5VrcfRJl9FzGJDxwPmAI8JpQ3jZasKeFwI/edit
