### ISSUE TITLE
Screeners

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4040]
## Description
Screeners are private urls where you can watch a film. Screeners are available during a chosen timeframe for invited people only. Though, what differentiates it from screenings is that most of the time it will be for only a few people (if not only 1) and for a larger timeframe in order to let the buyer decides when s/he will watch the film.
Also, screener should be easy to access and should live aside the app without an authentication needed. 

Screener is all about privacy on-demand, giving seller the choice to setup its own security rules.
Usual screener settings are:
- window: start & end time 
- text of the watermark
- enable / disable option (at any moment)
- maximum views
- password protection
- download as an option
Advanced settings are:
- phone verification 
- IP protection

Screeners shouldn't be considered as screenings so they won't appear in calendar or anywhere else than in the seller dashboard. 

Over a second phase, we should use screener web page security for meetings and screenings in order to enable "guests" (i.e. non connected users) to attend events. 

### Dashboard screener section
- screener list 
- screener view (stats)
- screener form (security settings, invitation list, movie selection, private url)

### Screener web page
- new web page layout (outside the app)
- view count
- video player
- password protection (if enabled)

### Email
- invitation email

### Notification
- first screening notification

### Seller creates a screener
1. User connects
2. User clicks on Screeners section > navigates to it
3. User clicks on add new > navigates to the form
4. User fills in the form 
5. User clicks on save

### Seller sends a screener with invitations
1. User connects
2. User clicks on Screeners section > navigates to it
3. User clicks on a screener in the list > navigates to screener view
4. User fills in invitation with email address(es)
5. User clicks on send
6. Invited person receives an invitation email with screener url

### Seller sends a screener with email
1. User connects
2. User clicks on Screeners section > navigates to it
3. User clicks on a screener in the list > navigates to screener view
4. User clicks on the copy url button > copied to clipboard 
5. User opens her/his email client
6. User sends an email with the url inside

### Seller monitor her/his screeners
1. User connects
2. User clicks on notifications
3. User clicks on a new notification saying that a buyer watched a screener > navigates to screener view
4. User watches the stats > buyer watched 4 times out of 5 views accepted

**Comment by Jackseed** [comment]
@2amarkina these are the options we may be able to do at first:

- text of the watermark
- enable / disable the screener (at any moment)
- maximum views
- password protection
- download as an option

**Comment by Jackseed** [comment]
Sprint 42: business & dev reviews to be done and wireframes to be updated accordingly

**Comment by pldespaigne** [comment]
Following the dev review, I created a new issue to discuss this feature from a technical point of view: #4681

**Comment by Jackseed** [comment]
Dev estimation
![image](https://user-images.githubusercontent.com/14964443/140921433-e5dfa32c-cca8-46dc-a725-a6c9bddff9a6.png)
