### ISSUE TITLE
Meetings - 1 to many

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4047]
## Description 
Now that we have 1 to 1 meetings we can go to the next level: 1 to many! The idea here is to enable sales agents to organise conferences, pitch session, Q&As, Webinars,... 
They are different types of the same thing which is having one (or more) person(s) presenting (host) and the others listening (participants) with a limited ability to interact. 
Defining this different types to be sure that they are the same is a first important step. 

## What's new
The common features should be:
### Event settings
- Mute participants by default
- Turn off participant camera by default (?)
- Invite either co-hosts or participants

### Event session
- Add a way for host(s) to unmute a participant
- If camera are off by default, ability to allow a participant to turn it on
- Participant list, host listed but showed differently
- Search on participant list
- New view with host as central video & the others small or not present at all
- Ability for participants to "raise their hand" or ping the host(s) so they can talk

Chat would be ideal for this kind of event but it's a different feature #4050

**Comment by fritzschoff** [comment]
sorry, closed it while working on the roadmap

**Comment by pldespaigne** [comment]
@jackseed this is "just" regular meeting but with an UI/UX that handle a very large number of participants

**Comment by Jackseed** [comment]
More or less, there is some small new features related to that (listed in "What's new" above) but most of the work relies on design and then UI modifications
