### ISSUE TITLE
Event widget

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4048]
## Description
We want to facilitate the flow for users connecting for a specific event. Anastasiia worked on different models and we will go for a sort widget / card that goes above the homepage banner. 
It will indicate either in that order of priority:
1. Events the user is invited to
2. Next screenings to come
3. No widget or a message saying there is no upcoming screenings

## What's new
[Wireframes](https://www.figma.com/file/P55iBTLX6jUqIFeA926gOY/%5B-Events-Widget-%5D)
![image](https://user-images.githubusercontent.com/14964443/97849923-99544700-1cf3-11eb-8780-36189400faf6.png)

### Screening widget
- Expandable card
- List of events either invited ones or upcoming
- Remove widget if empty / Add an empty state (@2amarkina what do you think?)
- Event details on each item: icon depending on type, event starting time & date, ending time & date, event type, name & button leading to the event view page
- pagination

**Comment by Jackseed** [comment]
@2amarkina plz change the wireframes when it's updated

**Comment by 2amarkina** [comment]
Usabillity Hub results for Empty State Testing : https://app.usabilityhub.com/do/f21cd718138e/1211 

**Total : 6 responses** 
With image: 5 participants
No image: 1 participants 

**NO EVENTS, NO SCREENINGS** 
Animated Proto: 
https://drive.google.com/file/d/18cZO-Zu6TOfwViNVqwEZx6hXfhFBApXR/view?usp=sharing

Principal Actions: 
1/ CTA to Library page "Explore titles" 

**NO EVENTS, WITH SCREENINGS** 
Animated Proto: 
https://drive.google.com/file/d/1C5eY_piuzgE5ozOgdJoceRnggJ30KU4Q/view?usp=sharing

Principal Actions: 
1/ CTA to Screenings Page "Discover upcoming screenings"

**WITH EVENTS, WITH SCREENINGS**
Note: From 1 event to n+1 events

Animated Proto: 
https://drive.google.com/file/d/1KjhYjQZ9y92UAcvQmPAmBiMVRNkAh_1X/view?usp=sharing 

Principal Actions: 
1/ CTA to Screenings Page "Discover other screenings"
2/ CTAs to Screening page concerned "See details" 
3/ CTAs to Meetings page concerned "See details"  
4/ Link to List of invitations "See all invitations

**Comment by 2amarkina** [comment]
UPD. Wireframe 
![Uploading Снимок экрана 2020-11-05 в 12.36.13.png…]()

**Comment by Jackseed** [comment]
1st meeting to validate wireframes and then preparation of the screens

**Comment by jdrns** [comment]
Mockups in progress [here](https://www.sketch.com/s/1d114419-1566-4444-83c6-7e2e19167571)
