### ISSUE TITLE
Live stats & watch time

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4053]
## Description
Currently we have approximatively 24h delay between viewers action and stats on dashboard. This is linked to the fact that we use google analytics, we could instead use JW Player stats (still through analytics) to display real time stats. 
That's a feature which will bring excitement to sales agents, thus really important as it will enable our platform to create emotions. 
Watch time is also a critical statistic offer by JW Player that we currently don't display. 

## What's new
- Live viewers count
- Live viewers graph over time
- World map showcasing live viewers localisation
- New screening stat column with watch time per user
- Average watch time on a screening

**Comment by Jackseed** [comment]
Ressource: https://developer.jwplayer.com/jwplayer/docs/jw8-analytics-system-integrations

**Comment by Jackseed** [comment]
This feature is planned for Berlinale, except for the world map

**Comment by Jackseed** [comment]
Sprint 40: objective is to finish wireframes by Friday 11th December then UI for the next week

**Comment by Jackseed** [comment]
Wireframes: https://www.figma.com/file/9c97sMY0zklWphrX7mpZSq/%5B-Live-Statistics-%5D?node-id=0%3A1

**Comment by 2amarkina** [comment]
UI : https://app.zeplin.io/project/5fff4521d801571bac57c98e/screen/5fff45abead9311da2b12167
