### ISSUE TITLE
MF Landing page illustrations & images

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4062]
List of images to create (I print the same from Archipel Market as examples):
- [ ] For all landing pages, remove the question mark on "How it works?" > "How it works"
- [ ] Top banner landing
![image](https://user-images.githubusercontent.com/14964443/97446896-3d727280-192f-11eb-88dc-6aef0b48e546.png)
- [ ] Top banner marketplace homepage (if different from landing)
![image](https://user-images.githubusercontent.com/14964443/97448321-d48bfa00-1930-11eb-82a7-cd923d2b6ab0.png)
- [x] Film fund dashboard images
![image](https://user-images.githubusercontent.com/14964443/97448083-87a82380-1930-11eb-9e2b-addf23aa2573.png)
- [x] Investor marketplace images
![image](https://user-images.githubusercontent.com/14964443/97448123-92fb4f00-1930-11eb-871b-6e2cb90b512d.png)
- [ ] Features icons 
![image](https://user-images.githubusercontent.com/14964443/97448181-a8707900-1930-11eb-9149-eb916d276aa9.png)

**Comment by stephanie-cascade8** [comment]
@Jackseed Is there a real need to change the banner backgrounds ? I don't know what else I can use to illustrate... The same mosaique of films seems to be appropriate as well , no?

**Comment by Jackseed** [comment]
@stephanie-cascade8 I'll see with Louis what direction we should use for the look & feel of this app but I personally think it would be best to have some difference from app to app to create an unique brand, even if they're part of the same suite

**Comment by Jackseed** [comment]
@stephanie-cascade8 we updated the text for Media Financiers with Louis, it's all here: https://docs.google.com/document/d/1OGr-lKxphKuZxhvpIrdyARR7PNnT1x0_Vn55xc9sicg/edit

Tell me if that's not clear, otherwise you can go for illustrations of every features. We can also give you some direction if you need it to illustrate one or another feature.

**Comment by stephanie-cascade8** [comment]
> @stephanie-cascade8 I'll see with Louis what direction we should use for the look & feel of this app but I personally think it would be best to have some difference from app to app to create an unique brand, even if they're part of the same suite

I agree with a diferentiation :) You'll tell me what is decided.

**Comment by Jackseed** [comment]
@stephanie-cascade8 yes let's go for a differentiation, can you please make 2 or 3 propositions? (could be only colours as you like)

**Comment by stephanie-cascade8** [comment]
> @stephanie-cascade8 yes let's go for a differentiation, can you please make 2 or 3 propositions? (could be only colours as you like)

OK great!

**Comment by stephanie-cascade8** [comment]
Mockups are here : https://app.zeplin.io/project/5fa1637022e6a88784fbb052/dashboard?seid=5faac9fb38a73613a391e592

**Comment by Jackseed** [comment]
A few comments but icons are good for me

**Comment by fritzschoff** [comment]
what is the status here? ready for implementation?

**Comment by fritzschoff** [comment]
images were created by stephanie and send it to me over slack. Closing issue now
