### ISSUE TITLE
Safari - Upload image not working

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4064]
Image upload is working fine (cropper > save > thumbnail displayed correctly) BUT after saving the form, the image just doesn't show up and if you go back on the form again you get that question mark:
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/03869530-e88f-4f17-b79a-bb08ec336c67)

**Comment by phpgeekfr** [comment]
@Jackseed image and pdf upload are working fine in latest safari on browserstack. If you hit refresh too quickly just after uploading image, you can have an empty image for few seconds but this bug is not related to Safari.

**Comment by Jackseed** [comment]
@phpgeekfr ok that should have been fixed in the meantime: I tried again on staging and it wasn't working but worked on François' app that is fresh from Yesterday
