### ISSUE TITLE
Movie form navigation issue with save / next

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4075]
E2E testing of movie forms has some navigation issues in certain steps:

For instance in step 3/9 Production Information, clicking on next button `` results in some mess up with router url and page does not rendered properly:

![image](https://user-images.githubusercontent.com/8731418/97285697-88758280-1868-11eb-8d37-dddf640cefa6.png)

We can notice some issue of routing here with 2 urls being navigated to:

![image](https://user-images.githubusercontent.com/8731418/97285773-a2af6080-1868-11eb-9112-1548b2fe88bf.png)

If intermediate 'save' buttons are not pressed, then the form does not navigate to next step : Artist Information:

![image](https://user-images.githubusercontent.com/8731418/97285649-7b589380-1868-11eb-8f15-d0565c353d50.png)

**Comment by xmano** [comment]
Expectation from the fix:

1. Clicking next should take to Artistic Information irrespective if the form is 'dirty', values may not persist (not sure)
2. newURL shown in Cypress log might be a problem with frontend code, need to debug and make sure that we just move to next step after saving in the form.

**Comment by phpgeekfr** [comment]
@xmano Only bugs lefts:

1. Pdf are created in `apps/festival/festival-e2e/` and not removed. Can you move them to a specfic folder with git ignore?
2. Last check in summary page fails
![Sans titre](https://user-images.githubusercontent.com/1194344/97310206-3f6eff80-1863-11eb-9ef3-79b7cef25c16.png)
3. Check comments in PR

**Comment by phpgeekfr** [comment]
(tested with cypress `5.2.0`)

**Comment by xmano** [comment]
PDF issue will be fixed with #4137.
E2E issue resolved with #4128
