### ISSUE TITLE
"Audience & Goals" sub step of "sales-pitch" in movie-tunnel  should be accessible only from  MF app

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#4084]
"Audience & Goals" sub step of "sales-pitch" in movie-tunnel  should be accessible only from MediaFinanciers app

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/15eac321-8794-49e6-b5cc-babd299932e1)

**Comment by Jackseed** [comment]
@phpgeekfr @GrandSchtroumpf my bad in fact we just move audience & goals to additional information, to the bottom & keep it for every app + every prod status
We also rename it "Positioning"
<img width="439" alt="Снимок экрана 2020-10-27 в 16 39 28" src="https://user-images.githubusercontent.com/14964443/97325851-b1e7db80-1873-11eb-9de9-6f0f6e19760f.png">

**Comment by Jackseed** [comment]
@xmano e2e has to be modified accordingly

**Comment by fritzschoff** [comment]
just checked the code and is has been done!
