### ISSUE TITLE
Fills in queryParams url when user filters a page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4098]
This will help user saves her/his filters when leaving the filtered page and going back to it

**Comment by phpgeekfr** [comment]
- [ ] When I choose filters in the filter form, it should update the URL.
- [ ] If I copy and paste URL, all filters should be updated from parameters in URL

**Comment by Jackseed** [comment]
Interesting request from Christophe, could we use it as well for avails? 
Use case:
- user fills in avails filter in the library page
- s/he clicks on a movie card
- expansion panel in the avails tab is filled in by default with the library page search
- user clicks on "Add all to Selection" without further research

**Comment by GrandSchtroumpf** [comment]
Be careful not to hit the max size of the url (2048 characters). After that the page will never load.

**Comment by pldespaigne** [comment]
Currently we avoid updating the url if the query is longer than 1500 characters, (we simply do nothing in this case)
