### ISSUE TITLE
MF review 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4101]
- [x] "Explore the marketplace" > "Discover projects"

### Homepage
- [x] Add a "Featured films" category that just takes all the movies accepted on media financiers with a random order. It should use the poster view and be displayed between "New projects" and "In development"
![image](https://user-images.githubusercontent.com/14964443/97696037-45ecb980-1aa5-11eb-8fbc-c90c564442f1.png)

### Footer
- [x] Contact page not working

- [ ] Change Legal Terms & Privacy Policy according to @lladreyt ' proposition

### Movie list
- [x] Animation on movie card click is awesome but goes beyond the card itself, @stephanie-cascade8 should confirm but imo, it should be contained by the card

### Movie view 
- [x] Add the pdf guide for download
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/5d9ed835-196a-4c17-b202-a926887238f1)

- [ ] ~On hover, the number goes transparent so we can't read it well~ (This is in Apex, I won't do)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/5e927f7e-e3a7-46ee-8706-196b3129250f)

- [x] Scenario should be changed for "Script"
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/6e9f11ee-65ea-4e38-ab6d-9be96b509d72)

- [x] Return on Investment, change the text for (1st sentence is changed):
Your Return on investment is your share of the total amount of proceeds resulting from the distribution of the film. It may be calculated in % by dividing your share of revenue by the initial investment. If the result is superior to 100%, this means your investment was profitable.

- [x] Change CTA button text for "Open discussion" + add a line of text before "Meet the fund to have further information" 
![image](https://user-images.githubusercontent.com/14964443/97697119-d8418d00-1aa6-11eb-947d-0db4c2178e28.png)

- [x] Invest modale:
- "I'm all set. Ready to invest" is on one line
- Align left the text "Please precise the amount you would like to invest.
If you are not ready to provide us with uch kind of information, just leave a message." and put it after "Subject"
- Add a placeholder to Message: "Questions about cast, financing, investment conditions..."
![image](https://user-images.githubusercontent.com/14964443/97697251-08892b80-1aa7-11eb-8503-7df6f84de483.png)

- [x] Shooting dates are not displayed though working on form & summary
![image](https://user-images.githubusercontent.com/14964443/98002748-2f6c9800-1dee-11eb-9efa-118fcb1e336a.png)
![image](https://user-images.githubusercontent.com/14964443/98002839-4ca16680-1dee-11eb-8e09-aabba8da7012.png)
![image](https://user-images.githubusercontent.com/14964443/98002898-604ccd00-1dee-11eb-90c3-d78618e8d9c2.png)

### Partner list
- [x] Use the country list without "World"
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/2e8c9a29-d1a1-4aa0-81ef-5397fd3d0927)

- [ ] Films listed in the partner cards should count accepted configStore status films only
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/49dda0d2-70e2-4c97-b099-3c1521a7d711)

- [ ] Orgs listed in the partner list should have at least 1 accepted configStore status film

- [x] « You’ve viewed 2 partners from 2 » > "You've viewed 2 of 2 partners"

### Movie view
- [x] coma issue 
![image](https://user-images.githubusercontent.com/14964443/97467102-238f5a80-1944-11eb-80f9-bb109c6c49d0.png)

### Movie form
- [x] Change the tooltips on the ROI page:
- Low: "Profitability in the worst case"
- Medium: "Reasonable profitability you are targeting"
- High: "Best profitability you could expect"

- [x] "Title1" to modify
![image](https://user-images.githubusercontent.com/14964443/97468343-74538300-1945-11eb-903c-c3d0d46718de.png)

- [x] Best would be to enable that by default 
![image](https://user-images.githubusercontent.com/14964443/97468530-aebd2000-1945-11eb-97dc-a5177fafdec5.png)

- [x] Let the user choose the film currency and not forced dollar
![image](https://user-images.githubusercontent.com/14964443/97468639-ceecdf00-1945-11eb-9760-36c2f0dc69d7.png)

- [x] On top of the pages Financing plan & Investment proposal, add a line of "classic" text (black) before the subtitles saying: "US Dollar ($) is the default currency, you may change it on the Budget page." + if possible a link to budget page on "Budget page"

- [x] Extract current amount to the movie view
![image](https://user-images.githubusercontent.com/14964443/97468865-08bde580-1946-11eb-9413-b66ea0733718.png)

- [x] Budget: all the fields except "Other charges" are mandatory

- [x] Return on investment: Change the text for
"Please add your estimated return on investment (in %) for each case. Calculate it by dividing the expected share of revenue by the initial investment."
![image](https://user-images.githubusercontent.com/14964443/97597301-f86d3f80-1a05-11eb-9d57-d2a1c71040e6.png)

- [x] Remove the bottom part of the privileges, there won't be limited privileges for the MVP
![image](https://user-images.githubusercontent.com/14964443/97697517-63bb1e00-1aa7-11eb-8fe3-59abe2515bba.png)

- [x] Add Running time as mandatory (it is for the acceptation of the form but there is no * and it's not written mandatory in the summary page)

### Movie list
- [x] On the movie table change "On Going" for "Ongoing"

**Comment by 2amarkina** [comment]
For the Privileges : 
We can have a short description like in example and we also can have a long description -> so we'll need a "learn more". To homogenize all the cards it was decided to keep the "learn more". If there is no "learn more" the size of the card changes so it is not ok to see the different size cards and if we keep the "learn more" disabled the question is "why is it disabled ?". So, the decision to keep "learn more" everywhere was taken as less painful.

**Comment by 2amarkina** [comment]
Also for Sales Estimates section -> we had a discussion with Louis about this part and he told that actually this is not important, so we put it aside

**Comment by 2amarkina** [comment]
Current amount help us to create the "progress" on the "Invest in this project" section

**Comment by Jackseed** [comment]
UX feedbacks: https://docs.google.com/document/d/1bpJomjfNj5VrcfRJl9FzGJDxwPmAI8JpQ3jZasKeFwI/edit
UI feedbacks: https://docs.google.com/document/u/1/d/1_8jHnImpjCc7ECU5Q8_fBcadAFh85DQo5Wl-zT4Z9cg/edit?urp=gmail_link&gxids=7628

**Comment by Jackseed** [comment]
> For the Privileges :
> We can have a short description like in example and we also can have a long description -> so we'll need a "learn more". To homogenize all the cards it was decided to keep the "learn more". If there is no "learn more" the size of the card changes so it is not ok to see the different size cards and if we keep the "learn more" disabled the question is "why is it disabled ?". So, the decision to keep "learn more" everywhere was taken as less painful.

Thanks for the explanation, I remove my comment

**Comment by Jackseed** [comment]
Edit: I removed the crossed tick boxes for a more readable issue
