### ISSUE TITLE
Embedded promotional videos

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4115]
## Description
Now that we have both video player & server (JW Player) + the in-app video uploads, we should migrate all the promotional videos to our own systems. Thus, videos will be secured and we'll be sure to keep the assets available. It will also help user accessing these assets during meetings. 

## What's new
- Upload box for promotional videos on movie form
- A video thumbnail system: depending on the implementation difficulties it could be either a default thumbnail, an image imported through cropper and/or a image selected from the video itself (JW Player has an option for that)
- Update movie views to embed these videos
- Security: only connected user should be able to access these files
- Update data model accordingly

**Comment by pldespaigne** [comment]
link to #3820

**Comment by pldespaigne** [comment]
link to #2658
