### ISSUE TITLE
Running time status and time are difficult to display depending on each other

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#4124]
At this moment the `runningTime.time` can be type of number or string, so we can have different kind of data in the DB.
But it's difficult to homogenize the way we dislay the data because of that and also, it complicates the way to display the status data.

For example, if the type of the time is equal to string, we can have some display like this one
![runningtime.png](https://images.zenhubusercontent.com/5d51508f6f935933f7158b07/acb3873f-e781-4dea-9e7f-9c43bed36347)
And actually, I have 4 differents values for the time in my DB : `TBC, TBD, -` or a number (of course it can be null or empty string  also).

I think we have to rework a little the data and let the time only be a number and let the status changed depending on the time exists or not.

!! Check the number of the issue in the code !!

**Comment by Jackseed** [comment]
I approve that we should clean that up but I'm not sure it could be only numbers. What about TBD ? 
Anyway - / TBC / TBD are all the same so we could arbitrary change every string value to TBD and keep to that one when selected on the status. 
![image](https://user-images.githubusercontent.com/14964443/97852977-c3a80380-1cf7-11eb-877a-74549f438cb9.png)

**Comment by Mussuranae** [comment]
Also if we rework it, we will maybe be able to use only the `duration` pipe everywhere we display the `runningTime.time` and not the `getRunningTime` pipe anymore.
It would be nice to use only one pipe for this data.

**Comment by Mussuranae** [comment]
@Jackseed the status can be `To be determined, Estimated, Confirmed`, is that not enough to display the data ?
If the time became only number, if can say `if time exists, display it` and `if not, display nothing`.
And for the status, it would be easier also : `is time exists, display status, if time doesn't exist, status === TBD`

What do you think about that ?

**Comment by Jackseed** [comment]
Ok I though TBD was a string but if it's a status we can indeed accept only numbers. 

The thing is that "TBD" is a status a bit odd:
- "Estimated" and "confirmed" should be complementary of a number > e.g. 80min confirmed
- TBD is for when you don't have number so it's only TBD

Imo, in the form when TBD is selected we should disable the number input.

Also, running time is a mandatory field so there should be at least a number or a status

**Comment by Mussuranae** [comment]
Yeah, for the moment TBD is sometimes on the time data, but it's an option for the status too.
I remember that time is required only if the status is equal to confirmed (so for the released movie at least).

**Comment by Mussuranae** [comment]
Here are the wireframes for the running time made by Anastasiia
[Figma](https://www.figma.com/file/O2KS5ZjKwwx01ut4JgbYzP/%5B-Running-Time-%5D?node-id=10%3A53)

**Comment by Jackseed** [comment]
That's perfect 👍
