### ISSUE TITLE
Update Archipel Market Landing page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4127]
With new features coming we should update the landing page to reflect these changes

**Comment by maltmayer** [comment]
**1. BANNER**
- Add subtitle "One tool for your year-round promotion & acquisitions"
- Update banner with a more original design 

**2. NEW COMPONENT: BUYERS**
- Title: "Already using Archipel:"
- Buyers logos (@stephanie-cascade8 will see what looks better to showcase these logos)

**3. HOW IT WORKS**
- Delete title "How it works:" too big and not very impactful.
- Keep the 2 tabs but update text to : "FOR SALES AGENTS" / " FOR BUYERS"
- Delete the illustration (too big, not impactful)
- Keep the text as an intro: Delete the title "For Sales Agents" + Update text to: "Archipel Market enables sales agents to replicate the market experience online and promote their projects all year round on one single tool, already used by hundreds of buyers and centralizing multiple virtual promotion features (line-up sharing, screenings, meetings…) / Delete "For Buyers" + Update text to: "Archipel Market enables buyers to replicate the market experience online and access projects & events from multiple sales companies, all year round on one single tool."

FEATURES
- Update component so there are 3 features one 1 line:
=> Title: "LINE-UP PROMOTION" / Text: "Promote your line-up on your year-round digital booth"
=> Title: "SECURE LIVE SCREENINGS" / Text: "Recreate the momentum of live screenings anytime of the year in a secure environment."
=> Title: "MEETINGS with HD live-sharing features" / Text: "Share your documents in high quality during your meetings with buyers."

WHY USE ARCHIPEL TO PROMOTE YOUR LINE-UP? _(NEW COMPONENT) Title = same importance as "FEATURES" title_
_this "user benefit component" should look a bit like this but with better illustrations by @stephanie-cascade8 :)_
![image](https://user-images.githubusercontent.com/55785823/106899629-e0d4df80-66f5-11eb-9a21-bb3b0713c6e5.png)
- Title: "**Gain time and energy** by using one tool all year round" / Text: "Upload your title information once and for all and create your own comprehensive launch strategy by promoting your projects and events anytime during the year."
- Title: "**Simplify your buyers’ lives** on a user friendly platform" / Text: "With one single login, buyers can access a feature-rich platform regrouping projects and events from multiple sales companies, all in one place and available all year round."
- Title: "**Don’t change your habits,** use a tool adapted to your needs" / Text: "Co-developed with industry professionals, Archipel Market helps you promote your films in a secure environment, keep track and follow up with your buyers while allocating costs according to your needs."
- Title: "**Expand your reach,** on a collaborative tool" / Text: "Generate interest from new buyers by promoting your projects and events on a community platform, frequently use by hundreds of buyers."

_I'll finish this later_

**Comment by maltmayer** [comment]
**3. HOW IT WORKS** _(BUYERS VERSION)_

(Delete title "How it works:" too big and not very impactful.)
(Keep the 2 tabs but update text to : "FOR SALES AGENTS" / " FOR BUYERS")
- Delete the illustration (too big, not impactful)
- Keep the text as an intro: Delete "For Buyers" + Update text to: "Archipel Market enables buyers to replicate the market experience online and access projects & events from multiple sales companies, all year round on one single tool."

FEATURES

Update component so there are 3 features one 1 line:
=> Title: "CENTRALIZED LISTINGS" / Text: "Search and discover projects and events from multiple sales companies on one single tool, all year round."
=> Title: "LIVE SCREENINGS" / Text: "Attend live screenings and presentations from your favorite sales agents."
=> Title: "MEETINGS with HD live-sharing features" / Text: "Get high quality videos and documents during your meetings with sales agents."

WHY USE ARCHIPEL FOR YOUR ACQUISITIONS? (Title = same importance as "FEATURES")

(NEW COMPONENT) This "user benefit component" should look a bit like this https://docs.google.com/document/d/13kiUzr70lZq3wld4Wt5BYZ-SNk9xW1YX2Sl_kLYAnBs/, but with better illustrations by @stephanie-cascade8 :)

Title: "Gain time and energy by using one same tool all year round" / Text: "Stop jumping from one platform to the other. With one single password, access projects and events from multiple companies all year round."
Title: "Discover new content on a centralized tool" / Text: "Get regular updates and discover projects and events that were not on your radar."

**Comment by jdrns** [comment]
Landing page propositions discussed some sprints ago are available [here](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/448368356/preview?scrollOffset=82): 
- new style for images (new banner image + new hero image)
- updated structure 
- updated text

**Comment by Jackseed** [comment]
Banner update, element that can/should be added:
- festival badge
- headset
- triangle film presentation
- updated line up page
- underline people in the back
- ipad could used instead of Mac

On the Mac 3 possibilities:
- [Screening stats](https://app.zeplin.io/styleguide/5fce4283f696fa5197244ad3/components?coid=60af97bb32ac257aeedb6574)
- Screening session about to start (with theater-like illustration)
- Calendar with meetings & screenings filled in

**Comment by stephanie-cascade8** [comment]
Page illustrations available for download in svg here
https://zpl.io/aw5Wlgn
(download logos in png and illustrations in svg)

**Comment by stephanie-cascade8** [comment]
@maltmayer @Jackseed 
you can also find it on invision for the content review [here](https://projects.invisionapp.com/d/main?origin=v7#/console/19607961/453966784/preview?scrollOffset=312)

**Comment by jdrns** [comment]
[File for the banner](https://drive.google.com/file/d/1-KWxUBlVdMth4FiClcHX_EL4KcCZNG3r/view?usp=sharing) is ready

**Comment by Jackseed** [comment]
[Zeplin](https://app.zeplin.io/project/5de7944cf85691577aacfbb7/screen/60c9c2ef572ec78d4d00e600) with Marie's comment. Once updated accordingly we're good to go for devs

**Comment by stephanie-cascade8** [comment]
> [Zeplin](https://app.zeplin.io/project/5de7944cf85691577aacfbb7/screen/60c9c2ef572ec78d4d00e600) with Marie's comment. Once updated accordingly we're good to go for devs

@Jackseed I don't see new comments or corrections to make. @maltmayer do you want to check one last time though?

**Comment by Jackseed** [comment]
Oh my bad I haven't seen that the mockup was updated, then we're good to go!
@RemcoSimonides we can make an issue out of this but it should be blocked by #5560 since we want this page to be our first experiment of the new responsive layout.

**Comment by RemcoSimonides** [comment]
Dev issue created ☝️
