### ISSUE TITLE
MF Test - Message from investor to film fund

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4138]
## Description
On the Media Financiers marketplace, from the movie view (`/c/o/marketplace/title/titleId`), investors may send a message to the film fund.
(CTA text gonna change:)
![image](https://user-images.githubusercontent.com/14964443/97996415-0943f980-1de8-11eb-82e0-72172cc33cc9.png)

![image](https://user-images.githubusercontent.com/14964443/97996451-119c3480-1de8-11eb-9194-4512f8c68405.png)

I'm not sure of the right way to test this but it's the first time we use the Sendgrid email template feature and would be good to test that every use cases are well covered.  `Template ID: d-e902521de8684c57bbfa633bad88567a`
There are 3 subject possibilities and for each possibility 2 if statements, it makes 9 use cases to test:

### Subject ready
1. Ready, range & message
{
from: 100000
to: 200000
investor: {firstName: "Jack", lastName: "Prodace", email: "jack.prodace@cascade8.com"}
message: “I love your project!”
subject: "ready"
title: "Titanic 3"
user: {firstName: "Michelle"}
}
2. Ready, range
{
from: 100000
to: 200000
investor: {firstName: "Jack", lastName: "Prodace", email: "jack.prodace@cascade8.com"}
message: ""
subject: "ready"
title: "Titanic 3"
user: {firstName: "Michelle"}
}
3. Ready
{
from: null
to: null
investor: {firstName: "Jack", lastName: "Prodace", email: "jack.prodace@cascade8.com"}
message: ""
subject: "ready"
title: "Titanic 3"
user: {firstName: "Michelle"}
}
### Subject question
4. question, range & message
{
from: 100000
to: 200000
investor: {firstName: "Jack", lastName: "Prodace", email: "jack.prodace@cascade8.com"}
message: “What’s your waterfall?”
subject: "question"
title: "Titanic 3"
user: {firstName: "Michelle"}
}
5. question, range
{
from: 100000
to: 200000
investor: {firstName: "Jack", lastName: "Prodace", email: "jack.prodace@cascade8.com"}
message: “”
subject: "question"
title: "Titanic 3"
user: {firstName: "Michelle"}
}
6. question
{
from: null
to: null
investor: {firstName: "Jack", lastName: "Prodace", email: "jack.prodace@cascade8.com"}
message: “”
subject: "question"
title: "Titanic 3"
user: {firstName: "Michelle"}
}
### Subject other
7. other, range & message
{
from: 0
to: 0
investor: {firstName: "Jack", lastName: "Prodace", email: "jack.prodace@cascade8.com"}
message: “Please contact me I’d like to propose you another project.”
subject: "other"
title: "Titanic 3"
user: {firstName: "Michelle"}
}
8. other, range
{
from: 0
to: 0
investor: {firstName: "Jack", lastName: "Prodace", email: "jack.prodace@cascade8.com"}
message: “”
subject: "other"
title: "Titanic 3"
user: {firstName: "Michelle"}
}
9. other
{
from: null
to: null
investor: {firstName: "Jack", lastName: "Prodace", email: "jack.prodace@cascade8.com"}
message: “”
subject: "other"
title: "Titanic 3"
user: {firstName: "Michelle"}
}

**Comment by phpgeekfr** [comment]
Use sendGrid test key API

**Comment by phpgeekfr** [comment]
https://sendgrid.com/docs/for-developers/sending-email/sandbox-mode/

**Comment by phpgeekfr** [comment]
List of emails along with templates ( second tab but needs to be updated) :
https://docs.google.com/spreadsheets/d/1b1K7YfnquxnfCgGGPxIz5ZNIjr9eK_bUrRJqLvPYGIk/edit?usp=sharing

**Comment by xmano** [comment]
Using Mailosaur to test the flow

**Comment by xmano** [comment]
Got some information about mail sent from front end..

Hope to wrap this up now..

![image](https://user-images.githubusercontent.com/8731418/133472232-12a83add-44f9-45ea-8f66-9db3a92560d5.png)
