### ISSUE TITLE
Bf-slider needs refactor

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#4144]
The bf-slider needs a rework, there is a plenty of CSS bugs and the behavior of the content isn't right also.
We have to rework this component and we can't do a quick fix for the CSS problem.
Some problems have been reported on 
#3869 ticket 
![image.png](https://images.zenhubusercontent.com/5d51508f6f935933f7158b07/a8f6cf18-1f41-4ee0-b772-725fd89d87ac)
and #4019 ticket.
![image.png](https://images.zenhubusercontent.com/5d51508f6f935933f7158b07/50d822fc-9a75-4d9b-a61b-bbbcf916a744)

**Comment by pldespaigne** [comment]
Both underlying tickets are closed
