### ISSUE TITLE
Algolia autocomplete selects wrong value

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#4153]
First value in the results is selected instead of the one clicked

.gif is a little fast. I click on "Murphy, Ullrich and Hills" but "Murphy Group" is selected

![wrong organization selected](https://user-images.githubusercontent.com/27687382/98130046-1d582b80-1eba-11eb-9817-fac95e6c5900.gif)

**Comment by phpgeekfr** [comment]
Bug it still there, it takes the first result
