### ISSUE TITLE
Meeting is over Page

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#4156]
- [x] implement/refactor the "Meeting is over Page" to match [this design](https://app.zeplin.io/project/5e82f6ca1c987015ec21c1d7/screen/5f96a39d7983a5a400918108).

I'm not really sure about the "There where 8 attendee from 9 expected" feature, so let's discuss that together.

link to master issue #3639

**Comment by RemcoSimonides** [comment]
If the time is the total time a user has attended a meeting; then we have to figure out what the smartest way is to record this data.
Either by
- Using the analytics in BigQuery (check with Bruce which data is already available in BigQuery)
- Add `guests: {[ uid: string]: number}` to event data and enable a guest to (only) update their value in the object. The number represents the time the guest has spent in the meeting

**Comment by pldespaigne** [comment]
Following discussion with @Jackseed & @2amarkina we decided that the meeting time will be only the recorded in local session and will be discarded when user reload/leave the page.
