### ISSUE TITLE
Add member email is broken

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#4160]
When adding a new member to an org, the cloud function fails and doesn't send the mail:
![image](https://user-images.githubusercontent.com/8143464/98231699-0c142b00-1f5d-11eb-9856-8df413a2e11c.png)

**Comment by phpgeekfr** [comment]
@GrandSchtroumpf Can you add more context ? I just tested it from develop via `/c/o/organization/jnbHKBP5YLvRQGcyQ8In/view/members` and it worked well.

**Comment by GrandSchtroumpf** [comment]
This one wasn't working : 
https://blockframes-francois-financier.web.app/c/o/organization/OZAMSlWvqgrYxwL3y6E8/view/members
