### ISSUE TITLE
Refactor Jest expect extension by moving to a separate module and clean TS syntax

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4166]
Issue #3383 

Using some helpful utilities for asserting expects like toAllow(), toDeny(). 
At present this added in a quick and dirty way and requires cleanup.

**Comment by phpgeekfr** [comment]
@xmano Is this still a thing to do ?

**Comment by xmano** [comment]
Closing this as it was considered too much abstraction and difficult API during review.
