### ISSUE TITLE
MF Homepage - Business review to design & implement

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4170]

**Comment by stephanie-cascade8** [comment]
Content of the page will be in it's most updated verison here : https://docs.google.com/document/d/1OGr-lKxphKuZxhvpIrdyARR7PNnT1x0_Vn55xc9sicg/edit?ts=5fa97534

**Comment by fritzschoff** [comment]
can't access this document with my cascade8 gsuite emial
