### ISSUE TITLE
Design system update

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4176]

**Comment by stephanie-cascade8** [comment]
@Jackseed @fritzschoff **Description of what I'll be doing in this sprint for this task :**
Objectives: prepare the arrival of the intern and enable future improvements in our themes (eg: responsive, different components states, consistency...)
1- group theme colors and text styles in one file (with a combined dark and light role)
2- replace links in mockups and Zeplin with this new Styleguide file
3- rename colors and have the same as in the developed version (repo Github )
4- write margin and padding rules with examples on Notion
5- call François and Max to present and add more improvements

**Comment by GrandSchtroumpf** [comment]
Concerning the theme, there is an issue with dark-theme injected inside light theme (sidenav, text over image). This creates issues with the colors: for example you'll end up having the dark primary nearby the light primary.

**Comment by stephanie-cascade8** [comment]
https://www.notion.so/UI-Color-palettes-ec30a692ffa848deba495ba33b73ff1d

**Comment by Jackseed** [comment]
Sprint 39:
- [ ] Finish light theme
- [ ] Review typography with Anastasiia
- [ ] Space

**Comment by stephanie-cascade8** [comment]
Light theme here : https://www.notion.so/Theme-Color-Builder-ec30a692ffa848deba495ba33b73ff1d

**Comment by stephanie-cascade8** [comment]
Due to the arrangements on builder's structure some corrections to make with françois listed here
https://docs.google.com/document/d/1w96ykUZR92qCWa1xXt_1XcyCAokIihXksnNucAZEpQ4/edit#
