### ISSUE TITLE
Cleaning Figma & movie form spreadsheet

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4178]
- Clean and verify that everything is clean and finished in Figma
- Clean movie form spreadsheet

**Comment by Jackseed** [comment]
Sprint 39:
- Clean meetings

**Comment by 2amarkina** [comment]
**Figma Cleaning** 

For the purpose of optimizing the work of the design team, main layouts are cleaned and structured. These pages contain layout itself and essential components needed to go faster in producing screens.  

1.[ Movie Tunnel](https://www.figma.com/file/qpLBi85x3y0s4fLpJPACOm/Movie_Tunnel-%5B-Wireframing-Elements-%5D?node-id=0%3A1) (all the forms are updated with the last version of the [Validators Spreadsheet](https://docs.google.com/spreadsheets/d/1z4FFNABgDyRGgD5AQZf-ebWbA_m-7hlueFMCVUuk2fI/edit#gid=279324582))
2. [Marketplace ](https://www.figma.com/file/IRVExcGMB23lA84QrsoO5W/Marketplace-%5B-Wireframing-Elements-%5D)
3. [Dashboard ](https://www.figma.com/file/LPMeeNorVxWnkrm4yo2AfY/Dashboard-%5B-Wireframing-Elements-%5D) 
4. [Homepage ](https://www.figma.com/file/8lXoqiPsfsEhXis1WKHBQo/Homepage-%5B-Wireframing-Elements-and-Future-Editoralisation-%5D) 


This was the first step of reorganization and optimisation. Some new elements as detailed flows, new fields and components could be added. So these working zones can still be improved with time. 

The App Specific Working Zones ([Meetings / Media Ressources](https://www.figma.com/file/vBJGpcE68Fyc8IPNEi5slY/%5B-Media-Ressources-%5D?node-id=147%3A777)) are also cleaned and the important elements are decomposed. 

**Content Template**
Is to be used once the initial wireframes and mock-ups are validated. The purpose of "[Content Template](https://docs.google.com/spreadsheets/d/1Vee-I33quuDA556Zi6DyDWyljFHpfBmDRZRxPp0E0Gc/edit#gid=1852025806)" is also to help designers to gain the time if corrections concern different naming, changing wording or texts. It could help to be up to date with no information missing and gain a lot of time. This document could also become a first-drafted base for the future internalisation.


Proposition of steps / rules to take into account to try to make this system work: 
1. All the main common blocks and zones are predefined (reusable components) ; 
2. All specific new zones are to be specified and a screenshot of the concerned zone is important. 
3. All the designs should reflect the structure of the page and IF the content of the screen is not ok, the App Content Table should be a referent document.

**Comment by 2amarkina** [comment]
**Wireframing Elements** 

- All the main, common to all apps [ Wireframing Elements ] (https://www.figma.com/file/qpLBi85x3y0s4fLpJPACOm/%5B-Wireframing-Elements-%5D?node-id=0%3A1) are cleaned and decomposed. 

- On the left side of the working space we can find **Movie Tunnel, Marketplace, Dashboard, Homepage** elements.  

- Movie Tunnel Form Elements are up-to-date according to the [Movie Form Excel ](https://docs.google.com/spreadsheets/d/1z4FFNABgDyRGgD5AQZf-ebWbA_m-7hlueFMCVUuk2fI/edit#gid=279324582). 

**Meetings / Media Ressources**
[Media Ressources ](https://www.figma.com/file/vBJGpcE68Fyc8IPNEi5slY/%5B-Media-Ressources-%5D?node-id=0%3A1) elements are also cleaned and decomposed. 

**Content Table**
To optimize the work of designers the [Content Table template](https://docs.google.com/spreadsheets/d/1Vee-I33quuDA556Zi6DyDWyljFHpfBmDRZRxPp0E0Gc/edit#gid=0) was created.

**Comment by Jackseed** [comment]
That's great! Look like this ticket is done > closed
