### ISSUE TITLE
Buggy invitation pagination

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4180]
Pagination on invitations change the number of invitation per day and not per page. It's confusing and not the logic behaviour. 
The right behaviour would be that when the user selects 10 / 25 / 50 invitations per page, there is that same amount of invitations listed in the page (and not 10 / 25 / 50 invitations per day)
![invitations](https://user-images.githubusercontent.com/14964443/98534144-51e63180-2284-11eb-8d21-4c6dd302d635.png)

**Comment by phpgeekfr** [comment]
To fit new UI, paginator has been removed.
