### ISSUE TITLE
Debug screening banner on movie view

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4183]
A new banner has been implemented on marketplace movie view
![banner.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/b887f059-2a76-4385-ab8c-1ce9c7bc1947)
It needs a few debug:
1. Update the names to be the same as their number: "Third session" / "Fourth session" ...
2. The select should list all the sessions available
3. Time should display minutes and timezone (e.g. "5:00AM - 5:30AM (GMT+1)") 
4. The time and date should be centered
5. This banner has to be implemented in all the movie view tabs for the festival app only

**Comment by Jackseed** [comment]
Feedback from prod: this banner enables user to have multiple invitations on the same event (either by previous invitation or by requesting access through the event page/list). 
This is a non wanted behaviour as there could be one accepted and one refused and it's confusing for the sales agent to receive a request from a user already invited. 

Could we limit user invitation for a screening to one only? Or disable the "Ask for invitation" button if the user already has an invitation on the event selected? 
I can create a specific issue if needed but I don't know what's the best option

**Comment by Mussuranae** [comment]
I prefer to do the second comment in an other tickets. I created one for that : see #4311 
It will be a little more complicated because of who ask for invitation or who invite the buyers. We will do it in a second time.

**Comment by Jackseed** [comment]
Alright 👍
