### ISSUE TITLE
New illustration for movie poster fallback

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4188]
Current illustration could be updated to have something more beautiful or less visible than this one that looks like a 404 error
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/76952b4b-7c79-4792-a6ab-78fbe8614db1)

**Comment by stephanie-cascade8** [comment]
1- we want  background or borders to avoid the current visual bad effect. the image is not different enough from it's background and creates the impression that the size of the empty_poster is wrong.
2- as discussed with Vincent, we don't want to illustrate a fake movie poster but the absence of image (empty, missing...)

Proposition before/after

<img width="669" alt="Capture d’écran 2021-06-11 à 15 02 47" src="https://user-images.githubusercontent.com/66258851/121878288-d8c42680-cd0b-11eb-9822-2b7705ce55cc.png">

We also need an empty logo that matches the poster (for buyer, sellers...)
<img width="160" alt="Capture d’écran 2021-06-14 à 12 00 20" src="https://user-images.githubusercontent.com/66258851/121878385-f1ccd780-cd0b-11eb-9b41-2c25aa4166c1.png">

**Comment by stephanie-cascade8** [comment]
https://zpl.io/bzdXq67

**Comment by RemcoSimonides** [comment]
New illustration seems to already have been implemented

**Comment by 2amarkina** [comment]
I like the one with the text, i think that when the camera is a bit smaller the poster seems more elegant ! 

@stephanie-cascade8  maybe you could try to make the camera a bit smaller on the 2nd one?

**Comment by stephanie-cascade8** [comment]
![empty_poster-light](https://user-images.githubusercontent.com/66258851/140323020-34b0d782-9eb5-4572-af61-b4ccfffdf665.png)
![empty_poster-dark](https://user-images.githubusercontent.com/66258851/140323043-f02d017f-8312-4ca0-9b70-7eb3fd24dfe1.png)
