### ISSUE TITLE
Update emails workflows to integrate financiers emails

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#4206]
Update emails workflows to integrate financiers emails

- [x] update / create templates
- [x] set the correct app name in mails
- [x] set the correct "from" email
 - #2826
- [ ] update images and texts

**Comment by phpgeekfr** [comment]
List of emails along with templates ( second tab but needs to be updated) :
https://docs.google.com/spreadsheets/d/1b1K7YfnquxnfCgGGPxIz5ZNIjr9eK_bUrRJqLvPYGIk/edit?usp=sharing

**Comment by Jackseed** [comment]
@phpgeekfr can we discuss that when you start working on it? That's one the last breaking change to come for MF and I want to be sure we can be ready for the MF release

**Comment by Mussuranae** [comment]
I will work on it this week, we can schedule a call tomorrow if you are available.

**Comment by phpgeekfr** [comment]
Maybe this can be linked to #4263

**Comment by Mussuranae** [comment]
So I created an objet to pass app config in every template of Sendgrid, so it will be easier to get the app name or app logo for example.
But one problem persists, the logo has to be in PNG type, because SVG isn't supported by Gmail. I tried with Outlook and I saw the logo, but I guess a lot of people use Gmail so it will be a problem.

**Comment by Jackseed** [comment]
@Mussuranae there is also the question of the demo request 
- [ ] Add the app name on the demo request emails (sendDemoRequestMail) 
from ticket #4191
Can you have a look and tell me if it can be app specific there plz?

**Comment by Jackseed** [comment]
@Mussuranae I see in the repo that we still have this: 
```
    // Template for sending the verify email
    verifyEmail: 'd-81438bdf511b43cfa866ca63a45a02ae',
    resetPassword: 'd-6a0710945bc841ffb6955e3dc202704c',
```
In fact I think it's not used anymore and we use only this instead:
```
    // Template for welcome message when user created his account by himself
    welcomeMessage: 'd-fc05a8cf5b1548ebae9ca44247a6c256',
```
Could you please confirm and delete that old code so I erase the sendgrid template?

**Comment by phpgeekfr** [comment]
I think this is related to https://github.com/blockframes/blockframes/issues/2875

**Comment by Jackseed** [comment]
Hum not quite sure to see the link between the 2 🤔 
To give a bit more details ` welcomeMessage: 'd-fc05a8cf5b1548ebae9ca44247a6c256',` have a welcome message + validation email link that works (it's a firebase link + page)

**Comment by phpgeekfr** [comment]
For me  
```
verifyEmail: 'd-81438bdf511b43cfa866ca63a45a02ae',
resetPassword: 'd-6a0710945bc841ffb6955e3dc202704c',
```
are still used because of the routes still existing to reset your password or re-send email verify

**Comment by Jackseed** [comment]
Oh ok got you, I'll test that thanks

**Comment by Mussuranae** [comment]
- [ ] I tried from CRM to invite member in an org, functionality works well and emails are sent, but on Outlook, the links inside block like image are not displayed well, and the logo for example isn't clickable
![image](https://user-images.githubusercontent.com/48033264/101756872-c7892b80-3ad6-11eb-9912-442172a38f21.png)
![image](https://user-images.githubusercontent.com/48033264/101756950-db349200-3ad6-11eb-9be5-2f9db4933b6a.png)

**Comment by Jackseed** [comment]
- [ ] Event name (variable `eventName`) is not well loaded on email `attendEvent` id `d-ce3e57248a694cefacad49bc4c820078`
![image](https://user-images.githubusercontent.com/14964443/101931742-24213f00-3bda-11eb-9bd1-e676b18602f0.png)

**Comment by phpgeekfr** [comment]
@Mussuranae can we close ?

**Comment by Mussuranae** [comment]
> @Mussuranae there is also the question of the demo request
> 
>     * [ ]  Add the app name on the demo request emails (sendDemoRequestMail)
>       from ticket #4191
>       Can you have a look and tell me if it can be app specific there plz?

Yes there is information about the app (at least the appName in the code (so catalog, festival and financiers)), so I can add this in the email and you will know from which app it was sent.

I think we can close it yes @phpgeekfr
