### ISSUE TITLE
Fix E2E regressions

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#4208]
On november 10, nighly-CI tests: 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/aad9bac7-43ac-412f-9ffb-11e5e29614eb)

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/648c2e8a-acf2-4354-835a-3d82a1d845f9)

**Comment by phpgeekfr** [comment]
@xmano I think we can close this one ?

**Comment by xmano** [comment]
Lets check nightly E2E test on develop and refer that to close this. It is fixed on R2.0 branch.

**Comment by xmano** [comment]
Nightly E2E passing #24078

Closing
