### ISSUE TITLE
[FESTIVAL] Shell component per organization

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#4221]
We want to shell the market with an organization type shell example: 
- c/o/seller/berlinal: See the market of the festival of Berlin with a seller shell
- c/o/buyer/cannes: See the market of the festival of Cannes with a buyer shell

A shell will give access to organization specific actions, for example : 
- Seller: org / profile / titles / statistics / events
- Buyer: org / profile / events
- Festival: org / profile  / events / ...

A shell is compose of : 
- toolbar
- sidenav
- specific pages

**Comment by Jackseed** [comment]
Mission aborted
