### ISSUE TITLE
[Festival] replace "dashboard" / "marketplace" by ":orgtype/:festival"

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#4222]
With the operator "festival" the structure of the app is changing. 
The apps will be organized like that : `c/o/:orgtype/:festival` with : 
- orgtype: `"buyer" | "seller" | "operator"`
- festival: name of the festival

- [ ] #4220 Update org creation
- [ ] #4221 Create shell component per type of organization
- [ ] Update queries for organization
- [ ] Update guards to only give access to org that have the right type for the shell
- [ ] Change path in everything libs & apps that start with `c/o/marketplace` or `c/o/dashboard`

**Comment by Jackseed** [comment]
Mission aborted
