### ISSUE TITLE
Large white area on short page and sidenav opened

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#4224]
Go to a page which content doesn't cover the full screen (e.g. wishlist if you don't have too many wishes), then open the sidenav.
![image](https://user-images.githubusercontent.com/27687382/98813703-ebe4e000-2424-11eb-803a-cffba61855e6.png)

I think something changed to the footer because the footer used to be always just below the screen view, now it's directly below the content.

**Comment by Jackseed** [comment]
@RemcoSimonides I confirm, this has changed since prod still has the previous behaviour you described. 
![Uploading image.png…]()

Older behaviour was better, I don't know what changed that. @GrandSchtroumpf do you know where it comes from?

**Comment by Jackseed** [comment]
fixed now :)
