### ISSUE TITLE
[FESTIVAL] Dynamic branding

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#4233]
Applications & Operators should be able to have a dynamic branding :
- Logo
- Theme (dark / Light)
- Filters on movie query
- Filters on org query
- Image set

## Theme
- SCSS variables should depend on css variables
- ThemeService should be able to update css variables
- Store CSS variables in the document of the festival
- Create UI to change variables
- Provide feedbacks on accessibility & ...
- Create a preview mode to see the result of the theme
- Modify every illustration in the application to support dynamic coloration based on the theme.

## Logo
- app-logo should use a service to display the right logo at the right place.
- ..

**Comment by Jackseed** [comment]
Mission aborted
