### ISSUE TITLE
Prompt warning when upload task still running

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#4246]
When trying to leave the page and an upload task is still running (or paused), then a warning should be prompted saying the upload task will be terminated.

Use classic modale:

Mini-proto 
![MODAL WARNING](https://user-images.githubusercontent.com/55499036/115265915-fc1d8b80-a137-11eb-963a-abfa6826ad70.gif)

Screenshot 
<img width="732" alt="Снимок экрана 2021-04-19 в 17 50 46" src="https://user-images.githubusercontent.com/55499036/115265727-cb3d5680-a137-11eb-9c04-5b2f82dd7045.png">

#### Title
Warning!
#### Text
You are about to leave this page while some files are still being uploaded.
If you leave now, these files will not be uploaded.
#### Main CTA
Stay & Continue Uploading
#### Light CTA
Leave anyway

**Comment by Jackseed** [comment]
@RemcoSimonides can we close this? The upload task runs even if you leave the page right?

**Comment by RemcoSimonides** [comment]
This prompt should appear when you try to exit the website when upload
tasks are still running. This prompt would be especially useful in the case
of long lasting uploads like screeners.

**Comment by Jackseed** [comment]
Oh ok thanks for confirming

**Comment by Jackseed** [comment]
@RemcoSimonides is still valid with the new media refactoring?

**Comment by RemcoSimonides** [comment]
Yes, it is

**Comment by Jackseed** [comment]
Comment from retro 48: should be consistent with the modale used when leaving movie form or an event

**Comment by 2amarkina** [comment]
Mini-proto 
![MODAL WARNING](https://user-images.githubusercontent.com/55499036/115265915-fc1d8b80-a137-11eb-963a-abfa6826ad70.gif)


Screenshot 
<img width="732" alt="Снимок экрана 2021-04-19 в 17 50 46" src="https://user-images.githubusercontent.com/55499036/115265727-cb3d5680-a137-11eb-9c04-5b2f82dd7045.png">


Wireframes "Modal for leaving a page, if upload widget is there" (in a red box)
https://www.figma.com/file/vBJGpcE68Fyc8IPNEi5slY/Media-Ressources?node-id=1409%3A6896 

@maltmayer is it ok for you for the text?

**Comment by maltmayer** [comment]
Here is my suggestion for the texts:

Warning!
You are about to leave this page while some files are still being uploaded.
If you leave now, these files will not be uploaded.
Main CTA: Stay
Light CTA: Leave anyway

**Comment by 2amarkina** [comment]
> Here is my suggestion for the texts:
> 
> Warning!
> You are about to leave this page while some files are still being uploaded.
> If you leave now, these files will not be uploaded.
> Main CTA: Stay
> Light CTA: Leave anyway

Thanks ! 
I would just add for Main CTA "Stay and upload files" to show directly the main action needed to be made by app. As user will see the main cta even before the text, we should be as mush explicit as possible.

**Comment by maltmayer** [comment]
> I would just add for Main CTA "Stay and upload files" to show directly the main action needed to be made by app. As user will see the main cta even before the text, we should be as mush explicit as possible.

Okay then let's go for "Stay & Continue Uploading"

**Comment by Jackseed** [comment]
Thanks for the design, this looks now good to implementation > I pass it to the dev team

**Comment by GrandSchtroumpf** [comment]
It's not possible to open a custom dialog when you want to leave the app. You can only display the native modal from the browser. And you cannot customize the text. Here is how it looks like: 
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onbeforeunload

**Comment by Jackseed** [comment]
@2amarkina what do you think? To me it's ok to go with what François linked as it's pretty common when you try to leave a page that still download something

**Comment by 2amarkina** [comment]
yes, seams good to me!
