### ISSUE TITLE
Add a csv export on event stats table

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4288]
App: Archipel Market
url: `/c/o/dashboard/event/eventId/edit`
Page: Event form 

We need to add an export button that gives a csv file with the info of the stats table. 

![image](https://user-images.githubusercontent.com/14964443/123962207-7d539300-d9b1-11eb-8237-324f4d4e2585.png)

**Comment by Jackseed** [comment]
@2amarkina I think this one is still an open issue that could be good to implement while working on the new event form structure. Could you add an export button on the wireframes plz so we have what we need for this as well?

**Comment by 2amarkina** [comment]
Should go with [this issue](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/5895)

**Comment by 2amarkina** [comment]
<img width="513" alt="Снимок экрана 2021-07-06 в 14 36 55" src="https://user-images.githubusercontent.com/55499036/124601007-a53a6f00-de67-11eb-8352-d5e51cb2f201.png">

**Comment by jdrns** [comment]
[Mock up](https://zpl.io/2jqoBKA) for attendees
Preview: 
<img width="836" alt="Screenshot 2021-07-07 at 09 33 26" src="https://user-images.githubusercontent.com/79836137/124718428-627ba400-df06-11eb-8522-737d842787d4.png">
