### ISSUE TITLE
Design review - Meetings

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4290]
#### Global
Following this wireframe
![image](https://user-images.githubusercontent.com/14964443/100338057-6a6e7f80-2fd8-11eb-961f-a79a6f99dc89.png)
- [x] Add a subtitle below "My Files" title: "This is your File Storage. Its structure is predetermined. We trust you to upload the right content in the right place!"
- [x] Rename the org section "Company Files" 
- [x] Add an arrow below the breadcrumbs and above the files table that goes back to the previous page
- [x] Sort movies by international title by default
![image](https://user-images.githubusercontent.com/14964443/100338365-c9cc8f80-2fd8-11eb-95c4-1d4516724086.png)
- [x] Rename Still Photo « Images » 
![image](https://user-images.githubusercontent.com/14964443/100339177-d2719580-2fd9-11eb-813b-f38d8c5c72a0.png)
- [x] In title files, change "Main information" for "Poster & Banner" (if possible)
![image](https://user-images.githubusercontent.com/55785823/99797823-3efb1900-2b30-11eb-920c-70300a7991c7.png)

#### Upload box
- [x] Upload box on org docs, change label for « File title » 
![Add File - copie](https://user-images.githubusercontent.com/14964443/100338574-09937700-2fd9-11eb-84c0-81e0ccc8df61.png)
- [x] Upload box on Still Photo is the one from logo and not stills
![The Killing Of Two Lovers  Promotional Elements  Still Photo - copie](https://user-images.githubusercontent.com/14964443/100339002-976f6200-2fd9-11eb-95ba-01db670d0184.png)

- [x] Upload box titles should take the same titles as in the movie form
![elicita  Promotional Elements  Presentation Deck - copie](https://user-images.githubusercontent.com/14964443/100341560-fb475a00-2fdc-11eb-8e03-3f4c08970d6e.png)
![image](https://user-images.githubusercontent.com/14964443/100341581-0306fe80-2fdd-11eb-8e32-a832e0f9bb8d.png)

- [x] Update upload box title for Moodboard / Artistic Deck > "Upload Moodboard / Artistic Deck"

#### File table
- [x] Table for org docs & still photo: remove the sort by on « Type » & « Actions » as all docs have the same types & actions

PL : Idk if this will be easy to since we use a reusable bf-table component under the hood, imo we should try to fix it but no spend to much time on it if it become difficult

![the Killing Of Two Lovers  Promotional Elements  Still Photo - copie](https://user-images.githubusercontent.com/14964443/100338876-6f7ffe80-2fd9-11eb-92e8-2bbb185bf375.png)
- [x] Add an icon after the file name to know if there is something uploaded or not (@stephanie-cascade8 will provide the icons)
![image](https://user-images.githubusercontent.com/14964443/100339237-e7e6bf80-2fd9-11eb-93f5-cedc00b8e0fd.png)

#### Cropper
- [x] Disable update button before crop is done as nothing will be uploaded if they click on that button before cropping
![Edit Image - copie](https://user-images.githubusercontent.com/14964443/100339106-b968e480-2fd9-11eb-9e1a-167187767a2e.png)

#### Upload widget
- [x] When cancel, change the text for « Upload canceled » instead of « A problem has occurred! »
![image](https://user-images.githubusercontent.com/14964443/100341813-5ed18780-2fdd-11eb-898f-b7571c0e63ea.png)
Remco: issue in AngularFire package causes cancel to result in error. It should be fixed once we upgrade our package to v6.1.1

### New event modale

- [x] "Create" CTA becomes "More details" and we remove the secondary button to keep only one that leads to the event form
![image](https://user-images.githubusercontent.com/14964443/100342026-aa843100-2fdd-11eb-8d05-31702c24d00f.png)

- [x] Move "Type" select on first position and add an empty field by default
PL : note for the dev -> this mean add a validator required to the field and prevent create event until type is set

![image](https://user-images.githubusercontent.com/14964443/100342169-e3240a80-2fdd-11eb-8d80-147c486fa808.png)

#### Global
Following this wireframe

![Meeting_Creation_V2](https://user-images.githubusercontent.com/14964443/100344346-f4bae180-2fe0-11eb-9c17-70203116fe5c.png)

- [x] (1) Change checkboxes for toggles for "All day" and "Private"
- [x] (2) add an autofilled input "Meeting link" filled with the meeting session url + a copy to clipboard button to copy it (already implemented for invitations)
- [x] (3) Add a hint below "Organized by": "This person will be the one displayed in the invitations sent to buyers."
- [x] (4) Remove "Files" from the Meeting block and create a dedicated card called "My Files for this Meeting"
- [x] (5) Change the subtitles of "My Files.." for: 
"Add the files you'll want to share during the meeting.
(line break) If you can't find the files you're looking for, you can upload them directly in My Files (hyperlink) page."
- [x] (6) Change "Manage Files" button text for: "Attach the files you want to share during the meeting" and align it to left

#### Manage Files modale
- [x] Add the file type before the file name, same as when it’s added to the event (e.g. instead of "Felicità_Script.pdf" > "Scenario - Felicità_Script.pdf"
![image](https://user-images.githubusercontent.com/14964443/100344509-351a5f80-2fe1-11eb-91dd-d33cfbd21430.png)
![image](https://user-images.githubusercontent.com/14964443/100344516-38ade680-2fe1-11eb-84c4-4309cb3427c6.png)

- [x] On selected files, for images (ex Still photo) call it « Image X », X being their index + 1 (to avoid 0) instead of the index only
![Movie  La Fine Fleur  0  8 025f49a98d63-0 a0dab476c234-4a c5435bd44bf1-3a a373759f33- - copie](https://user-images.githubusercontent.com/14964443/100344734-917d7f00-2fe1-11eb-9d7d-5de317ddbfb9.png)

- [x] Disable "Add Files" button when nothing selected
![image](https://user-images.githubusercontent.com/14964443/100346921-e2db3d80-2fe4-11eb-9573-a9eb910f54f1.png)

- [x] Put selected files on top, not centerd
![image](https://user-images.githubusercontent.com/14964443/100346949-ecfd3c00-2fe4-11eb-9a5f-c9f7af126d69.png)

#### Selected files list
- [x] If possible, add a preview button and delete button on the right of the list 
![image](https://user-images.githubusercontent.com/14964443/100346848-ca6b2300-2fe4-11eb-84ab-240461f4a8b7.png)

### Meeting view
- [x] Remove «  | » after the organiser name
- [x] Remove « Description » when empty
![DESCRIPTION - copie](https://user-images.githubusercontent.com/14964443/100344856-c1c51d80-2fe1-11eb-8fbd-109dbe75c6ac.png)
- [x] Remove the Guest list section
![image](https://user-images.githubusercontent.com/14964443/100344894-d0abd000-2fe1-11eb-8840-846aab02c608.png)

- [x] If possible, when you are a member of the org organizing the event, hide the button "Session has already started, request access"
- [x] Change text of the button "Session has already started, request access" for: 
"This event has already started. 
(line break) Request access."
![99793339-cf356000-2b28-11eb-8f43-364a2afd999e - copie](https://user-images.githubusercontent.com/14964443/100357396-ebd40b00-2ff4-11eb-8245-e5d80e3586ec.png)

- [x] Change the text "Pending" to "Your request has been sent to the organizer. We're waiting for them to let you in." 
![image](https://user-images.githubusercontent.com/55785823/99793656-42d76d00-2b29-11eb-9390-1894f37d12d7.png)

### Meeting lobby
- [x] "Lobby" page should not be accessible outside of the event timeframe
- [x] Change both error texts for (use appropriate camera or microphone): 
"Your browser doesn't allow us to access your camera/microphone. To activate it, please change your browser preferences."
![image](https://user-images.githubusercontent.com/55785823/99795611-57693480-2b2c-11eb-8b71-aad73070858b.png)
![image](https://user-images.githubusercontent.com/55785823/99795540-39033900-2b2c-11eb-864f-207a1b88c5a5.png)

#### Shared space
- [x] Remove it when empty
- [x] Between shared ressource and ressource control add:
1. On the left add the icon + "Presentation shared with participants" for reassurance 
2. On the right, add the icon + Stop Sharing option (button that stops sharing)
![image](https://user-images.githubusercontent.com/14964443/100345101-1ec0d380-2fe2-11eb-902d-6cc49dd01e8c.png)

#### Ressource list
<img width="749" alt="Pasted Graphic - copie" src="https://user-images.githubusercontent.com/14964443/100347323-76147300-2fe5-11eb-8628-0e69a577155d.png">

- [x] (1) Add a title "Your Files" to this section 
- [x] (2) on hover, add a tooltip "Share on screen" + CSS style
- [x] (3) Change the link to edit page with a "+" button with "Add a file" tooltip, if possible it should open the Manage files modale directly in over the meeting session so the user doesn't leave session
- [x] Arrow on the right shouldn't appear when not needed
![image](https://user-images.githubusercontent.com/55785823/99797019-c5aef680-2b2e-11eb-9941-fdeb85ec9ab7.png)

**Comment by maltmayer** [comment]
MEETING FORM

- [ ] Description field should be in "Details" not "Meeting"

- [ ] "Organized by" field should be in details if possible. Or just before invitations. Make no sens here in "Meetings"

- [ ] Should be able to select multiple organizers

- [ ] "Meeting" should be called "Files" or "Prepare your meeting" 

- [ ] Center "Manage Files" CTA

- [ ] Change the sentence to "Add the files you'll want to share during the meeting. If you can't find the files you're looking for, you can upload them directly in My Files." + Go to next line after the stop. +  Add hyperlink on "My Files" page in the sentence.

- [ ] Wouldn't it be possible to have the same "carousel" view for the "Selected Files" as the view during meeting (instead of a list like this)

- [ ] Need preview for the files

- [ ] Don't show "Statistics" part, it's not needed.

- [ ] Add another "Go to event page" at the bottom of the page

![image](https://user-images.githubusercontent.com/55785823/99791149-7fa16500-2b25-11eb-9b7e-248723db8f0c.png)

**Comment by maltmayer** [comment]
MEETING MARKETPLACE VIEW MARKETPLACE

- There's an access inconsistency: I have 2 CTAs here. One telling me to request access, the other to join the meeting. 

+ why is there so much space above the "Access Meeting Room" ?
![image](https://user-images.githubusercontent.com/55785823/99793339-cf356000-2b28-11eb-8f43-364a2afd999e.png)

- Change "Session has already started, request access" to "This event has already started. Request access."(go to next line after the stop)

- Description text is too small and too close to the timeframe. Should be more readable, separate it more from the time details.

- For a meeting, a pending request shouldn't show "Pending" but "Your request has been sent to the organizer. We're waiting for them to let you in." 
![image](https://user-images.githubusercontent.com/55785823/99793656-42d76d00-2b29-11eb-9390-1894f37d12d7.png)

- [ ] Don't show Guest list on marketplace view
![image](https://user-images.githubusercontent.com/55785823/99794345-4cada000-2b2a-11eb-88fc-96fdab24f9a6.png)

- [ ] "Lobby" page should not be accessible outside of the timeframe

**Comment by maltmayer** [comment]
LOBBY
- [ ] "Lobby" page should not be accessible outside of the timeframe

- Would be nice to see if people are already in the meeting (not a priority but nice to have)

**Comment by maltmayer** [comment]
MEETING SESSION 
- Empty video field. Can't test anything related.
- Even when there's no one, I should have an empty state with my video in it.
![image](https://user-images.githubusercontent.com/55785823/99796689-330e5780-2b2e-11eb-9ea1-4fac6407570c.png)

- Selected files is too close to the video 
![image](https://user-images.githubusercontent.com/55785823/99796889-854f7880-2b2e-11eb-98f4-f1d87caf6d22.png)

- There's no option to manage the files
![image](https://user-images.githubusercontent.com/55785823/99796279-7fa56300-2b2d-11eb-9d1a-a4855507ab87.png)

- The only "manage" option appears when I have a pdf with multiple page. But the page count should be centered, should be right under the pdf.
![image](https://user-images.githubusercontent.com/55785823/99796689-330e5780-2b2e-11eb-9ea1-4fac6407570c.png)

- I can't stop sharing a file. Once I've clicked on it, I can only click on another, not stop sharing.
- Should be able to close the "sharing part" and see only the video

- I see the organizer view event as marketplace user.
![image](https://user-images.githubusercontent.com/55785823/99796229-67cddf00-2b2d-11eb-85b8-8223420a6eec.png)

- Shouldn't have to leave the page to upload files.
![image](https://user-images.githubusercontent.com/55785823/99796422-c1360e00-2b2d-11eb-9355-b50ba04cef14.png)

- File icons shouldn't be icons, should be the actual preview of the file
- Arrow on the right shouldn't appear when not needed
![image](https://user-images.githubusercontent.com/55785823/99797019-c5aef680-2b2e-11eb-9941-fdeb85ec9ab7.png)

- Loading a file should look like this. This looks buggy. There should be a screen saying it's loading with a pretty image 
![image](https://user-images.githubusercontent.com/55785823/99796387-b1b6c500-2b2d-11eb-9685-427b61e00022.png)

**Comment by maltmayer** [comment]
DASHBOARD FILE MANAGEMENT

**MEETING FORM : CHOOSE FILES POP UP**
- Title Files should be first, Organization Files second
- "Add files" CTA leads nowhere
- A list is not very practical, we need to see the files here. maybe just a preview. But "image mode" would be better than a list
- Same for the selected files. Show the files, not list them
![image](https://user-images.githubusercontent.com/55785823/99797413-7d440880-2b2f-11eb-9dfe-882909d474e0.png)

**MY FILES PAGE**
-  make the distinction between org file and titles clearer. Here it's easy to miss it
![image](https://user-images.githubusercontent.com/55785823/99797683-02c7b880-2b30-11eb-9fdf-d7565399c4f6.png)

- In title files, "Main information" doesn't make sense. Maybe call it "Poster & Banner"
![image](https://user-images.githubusercontent.com/55785823/99797823-3efb1900-2b30-11eb-920c-70300a7991c7.png)

- Change "Still photo" to "Images"
![image](https://user-images.githubusercontent.com/55785823/99797964-7a95e300-2b30-11eb-9bd8-183e0a19d827.png)

- Add possibilité to add files/documents. This is very static

- Add "return" arrow everywhere to go back for smoother navigation. People don't use breadcrums
- Add a little "X" also when a document is open (to go back) 
![image](https://user-images.githubusercontent.com/55785823/99798146-c2b50580-2b30-11eb-996f-d8069b03ccc7.png)

**Comment by stephanie-cascade8** [comment]
- [ ] Replace by stroke button and take off the paper plane icon

<img width="669" alt="Capture d’écran 2020-11-23 à 12 10 33" src="https://user-images.githubusercontent.com/66258851/99955622-fbe5b380-2d84-11eb-8623-9a5d4f894b17.png">

**Comment by stephanie-cascade8** [comment]
- [ ] Have the same color on text and arrows. Keep the same current hover effect on text if possible.

<img width="309" alt="Capture d’écran 2020-11-23 à 12 12 42" src="https://user-images.githubusercontent.com/66258851/99955800-394a4100-2d85-11eb-95ca-6a6283a540f8.png">

**Comment by stephanie-cascade8** [comment]
- [ ] Add 24px margin all around the blue dashed zone

<img width="783" alt="Capture d’écran 2020-11-23 à 12 14 46" src="https://user-images.githubusercontent.com/66258851/99955967-7f070980-2d85-11eb-8e2b-f893676ec2c2.png">

**Comment by stephanie-cascade8** [comment]
- [ ] Title: put h2 instead of h1. Text centered in the dialog. 
- [ ] 24px under the title's divider
- [ ] Take off the paper plane in the Update Button.
- [ ] In this case, "cancel" button should also be primary since it's already differentiated with "update" by the button shape.
If you can (not mandatory at all) use a lighter shade of primary palette.

<img width="842" alt="Capture d’écran 2020-11-23 à 12 21 11" src="https://user-images.githubusercontent.com/66258851/99956492-65b28d00-2d86-11eb-9f13-6faca4dcf84b.png">

**Comment by stephanie-cascade8** [comment]
- [ ] Action List icons on the right should be stuck on the right and aligned with same icons under and above in table lines. 
- [ ] "Document name" and any column's width shouldn't be based on it's content's size and always be the same in every line.

<img width="842" alt="Capture d’écran 2020-11-23 à 12 21 11" src="https://user-images.githubusercontent.com/66258851/99957003-4831f300-2d87-11eb-86aa-b9640816a5ee.png">

**Comment by stephanie-cascade8** [comment]
- [ ] If you can, center the icon inside the light effect. If impossible take it off.

<img width="288" alt="Capture d’écran 2020-11-23 à 12 31 28" src="https://user-images.githubusercontent.com/66258851/99957339-d6a67480-2d87-11eb-9b8a-1f4b78e3f46c.png">

**Comment by stephanie-cascade8** [comment]
- [ ] Icons "accept / refuse" have to be the same size (smaller one would be best)
<img width="776" alt="Capture d’écran 2020-11-23 à 12 27 18" src="https://user-images.githubusercontent.com/66258851/99957444-005f9b80-2d88-11eb-8e5e-4915350afc19.png">

**Comment by 2amarkina** [comment]
Review here:

https://docs.google.com/document/d/129UBMdasNRmvPIOEBTgs6dObpIGu0vTTYMIhgw9FGUI/edit?usp=sharing

**Comment by stephanie-cascade8** [comment]
- [ ] Same Padding as other usual buttons for right and left (24px)

<img width="403" alt="Capture d’écran 2020-11-23 à 12 40 08" src="https://user-images.githubusercontent.com/66258851/99958122-1883ea80-2d89-11eb-8221-081a978413af.png">
<img width="670" alt="Capture d’écran 2020-11-23 à 12 39 36" src="https://user-images.githubusercontent.com/66258851/99958133-1ae64480-2d89-11eb-910d-a7c279759708.png">

**Comment by stephanie-cascade8** [comment]
Here I would like to see what is technically possible. I would like to differentiate backgrounds of the 3 areas "file showing" on left "videos on right" and "files slider" in the bottom. To visually separate those 3 different roles.
I would like also to talk about a solution for more spaces between areas (maybe have the files icons in the slider smaller so we can add more space after the title at the top). 
@pldespaigne can we have a call about this after you're done with your priorities? 

<img width="1435" alt="Capture d’écran 2020-11-23 à 12 43 41" src="https://user-images.githubusercontent.com/66258851/99958357-8c25f780-2d89-11eb-8438-c4de53e45943.png">

**Comment by stephanie-cascade8** [comment]
- [ ] Possible to have dialogs with size of the content and 36px padding all around ? Here it's not proportional with the content.

<img width="1059" alt="Capture d’écran 2020-11-23 à 12 48 39" src="https://user-images.githubusercontent.com/66258851/99958795-461d6380-2d8a-11eb-9be3-8ed7a6672b38.png">

**Comment by Jackseed** [comment]
Update about this ticket: I gathered every feedbacks, including Anastasiia's doc into the first comment. 
Also different issues have been created for subjects that can't be done right now. 
- #4337 for style issues as we need an updated design system first
- #4333 for small new features that are currently blocked or too big

**Comment by RemcoSimonides** [comment]
Ticked all checkboxes
