### ISSUE TITLE
Selecting the same other Video file twice in a row causes UI not to update

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#4293]
When trying to add the same video file twice in a row in the other videos component, the UI doesn't update.
It is possible to upload the same file twice in a row when you use drag 'n drop instead of browse.

![file upload ui](https://user-images.githubusercontent.com/27687382/99686670-1f0e1b80-2a84-11eb-92ee-48cc7ddd541d.gif)

This is caused by the `autoAdd` after save in the `bf-form-list` component. If `setTimeout(() => this.add(), 0)` is used, the UI doesn't occur anymore. However this doesn't solve the underlying issue.

**Comment by fritzschoff** [comment]
also add a margin to the save button
