### ISSUE TITLE
JW Player dev env

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4299]
Would be good to have a side env for devs to make your tests outside the prod videos

**Comment by Jackseed** [comment]
There is a tag feature, mb just add "dev" tag and "prod" tags could be enough?

**Comment by Jackseed** [comment]
There is also a "Property" thing that looks like envs, that looks better than tags

**Comment by pldespaigne** [comment]
Might be cool to auto add the tag/property to an uploaded video so that we can see if a video is "real" or "test" in the JWPlayer dashboard. We can probably achieve this in the upload video backend functions
