### ISSUE TITLE
Add a way for users to switch from draft to published directly on the movie page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4304]

**Comment by 2amarkina** [comment]
[Work in progress here ](https://www.figma.com/file/WSbqoyv3Mzkip6yQJGrQR6/%5B-Switch-from-draft-to-published---%234304-%5D?node-id=108%3A0) 

**Aims of design:** 
- inform a user about the actual status of a film directly from the Dashboard Film Page ; 
- add an action to change the status (respecting the cross-app logic) ; 
- try to reduce the amount of actions on the Dashboard Film page (the right part of the banner) ; 
- improve the preview mode (inform a user that s/he's using the preview mode and the title has not been published yet). 

**Reviews needed:** 
- **business review** to see the proposed solutions + wordings to confirm (_preview on marketplace_ for "drafts" and "submitted" and _see on the marketplace_ for "published"); 
- **tech review** to validate the options we have.

All other details about each solution are described in the working spaces.

**Comment by Jackseed** [comment]
Well done to use that issue to change the main actions on dashboard movie banner. 

I feel it's a really good idea to replace original title with the marketplace status as it's way more important for dashboard users. 
I would favour to keep actions on the right side of the banner and static info on the left side, even if the action list on the marketplace status could indeed be useful to save some space. 

Regarding the actions, I do think that icons is not enough for our non tech friendly users. What about something in-between like we put a button with text as the main action and below a list for secondary actions? This way we help users understand correctly the main action + direct them to look at that right space for other actions. 

Regarding the preview solutions, I think that the clearer the better so I would prefer the banner solution that can't be missed by users.

Also, not sure it's really relevant but it's worth mentioning it, each movie has a status **per app** meaning it could be accepted in Market but draft in Content. Imo we can keep with the current app status and don't display other apps status nor give the ability to change it but I prefer you to confirm that.

**Comment by Jackseed** [comment]
Some comments made during sprint 48 retro:
- we could use same tabs from Content on top of the title table 
- "archived" would be a new title status
- users should be able to delete the title once archived
- flows to design: archive, unarchive and delete a title
- could use the same validation modale used in the crm (delete a movie or org)

**Comment by jdrns** [comment]
[Mock up](https://zpl.io/bLqzqw7) of banner is available on zeplin. 
Preview: 
<img width="1108" alt="Screenshot 2021-06-22 at 10 06 47" src="https://user-images.githubusercontent.com/79836137/122887848-8f925900-d341-11eb-85ad-639f0a1534a1.png">

As for all the different actions depending on the status (main and secondary), [this file](https://docs.google.com/spreadsheets/d/1e4qahYcBxsYJ4Dpuu_RyL_onlgkMRNts4k5kai-Zu20/edit#gid=0) summarises all the cases

**Comment by Jackseed** [comment]
Thanks @jdrns! 
Some comments:
- still missing the mockup for the title list with all the tabs (All | Draft | Submitted | Published | Archived) - or I missed it?
![image](https://user-images.githubusercontent.com/14964443/122897424-4abef000-d34a-11eb-9fa6-ef68e1b96b14.png)

Re the banner: 
- Could you put "Preview on Marketplace" as main CTA and remove it from the Action list plz?
- We also need to add "Update Funding Status" in the action list for Media Financiers, especially to have an icon as the others
- We need a mockup for another use case: when there is only 1 action available in the list, it should be displayed directly in the banner 
![image](https://user-images.githubusercontent.com/14964443/122897839-a7220f80-d34a-11eb-9818-301187fb30c2.png)

Re the modale:
- The text are:
Title: "You are about to delete *Title Name* permanently."
Subtext: 
"This Title will still be available on App Name."
"If you wish to proceed, please type "DELETE" in the field below."
Placeholder within the input: "Type "DELETE""
CTA: "Delete Title"
2nd action: "Keep Title"

**Comment by jdrns** [comment]
- [ ] [Dashboard](https://zpl.io/2yDNAvw)  with new tabs 

- [ ] [Different variants](https://zpl.io/2GPrXqr) of banner (I put all the different actions in the same drop down to see all the different icons, to know which actions goes with which status depending on the app, check out [this file](https://docs.google.com/spreadsheets/d/1e4qahYcBxsYJ4Dpuu_RyL_onlgkMRNts4k5kai-Zu20/edit#gid=0))

- [ ] [Pop-up](https://zpl.io/bPBZwKD) updated

**Comment by Jackseed** [comment]
Perfect thanks :)
All good we can close it, dev have this new issue #6084
