### ISSUE TITLE
Add a hint on document upload to warn that it will be downloadable 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4305]

**Comment by 2amarkina** [comment]
Hints are added everywhere where a document can be eventually downloaded (event for the images and poster / banner). All screens are available [here](https://www.figma.com/file/qpLBi85x3y0s4fLpJPACOm/%5B-Wireframing-Elements-%5D?node-id=0%3A1)

Exemples : 
Hint_1
<img width="549" alt="hint_1" src="https://user-images.githubusercontent.com/55499036/100857686-49e96e00-348d-11eb-9a03-c94a1464d60d.png">

Hint_2 
<img width="509" alt="hint_2" src="https://user-images.githubusercontent.com/55499036/100857783-64bbe280-348d-11eb-8978-c21ed90b81df.png">

Hint_3
<img width="684" alt="hint_3" src="https://user-images.githubusercontent.com/55499036/100857803-6ab1c380-348d-11eb-8988-a7eeb29884b0.png">

**Comment by Jackseed** [comment]
Thanks > closed
