### ISSUE TITLE
Optimize build performances with cache

### ISSUE THREAD

**Issue by laurentsenta** [blockframes/blockframes#431]
it appears that webpack gives us tool to enable persistent caching at build time,
https://webpack.js.org/guides/build-performance/#persistent-cache

this should gives us a huge build perf increase in the CI

Ref #1454

**Comment by Jackseed** [comment]
- [ ] Try the library
- [ ] Timing it 
- [ ] Make decisions
- [ ] Deploy

**Comment by GrandSchtroumpf** [comment]
[ ] - Check if this is already part of Angular cli / NX cli
[ ] - If no, check if there is a custom angular builder for that
[ ] - Not related to Webpack Persitent Caching, but try to implement the affected:build/affected:test for nx cli could also reduce timing if we found why it's not working currently.

**Comment by Jackseed** [comment]
@lsenta is it different than what Nx offers with the CI and what has been implemented with #1454 ?
