### ISSUE TITLE
Prevent user to ask for several invitation for a screener

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#4311]
From @Jackseed 
```
Feedback from prod: this banner enables user to have multiple invitations on the same event 
(either by previous invitation or by requesting access through the event page/list).
This is a non wanted behaviour as there could be one accepted and one refused 
and it's confusing for the sales agent to receive a request from a user already invited.

Could we limit user invitation for a screening to one only? 
Or disable the "Ask for invitation" button if the user already has an invitation on the event selected?
```

See [#4183](https://github.com/blockframes/blockframes/issues/4183) Debug screening banner on movie view.

**Comment by Jackseed** [comment]
Anastasiia's feedback

I was not sure if it concerns specifically Screening List or Movie Page and I don't know if it is difficult to handle right now, but  leave it here. 

When user gets his "accepted", is it possible to change CTA "Ask for invitation" by text "You already have your invitation" or smth  (not sure for the text)? 

As if on the Screening List the invitation was already accepted, there is no need for a user to ask for it one more time 

![FireShot Capture 601 - Film Page - Screening Schedule - Archipel Market - staging archipelmarket com](https://user-images.githubusercontent.com/55499036/101757788-dae8c680-3ad7-11eb-822f-b21a75bf8bf9.png)

**Comment by Jackseed** [comment]
- [ ] Comment from Marie:
![Enregistrement de l’écran 2020-12-10 à 17 17 30](https://user-images.githubusercontent.com/55785823/101800059-1e115c80-3b0d-11eb-909f-d2a3223e5645.gif)
- When I request an invitation to a screening session, I can't request for another session after.
- Change CTA text to "Register for this session"
