### ISSUE TITLE
3 graphics implementation (Apex Charts)

### ISSUE THREAD

**Issue by SamirTouira** [blockframes/blockframes#4331]
Issue : implement 3 graphics and adapt it to blockframes. 

Types of graphics to implement :

- Curve of users connected per day over the last 30 days (+ change compared to the last 30 days) :  https://apexcharts.com/angular-chart-demos/line-charts/basic/

- Curve of first connections per day over the last 30 days (+ evolution compared to the last 30 days) > to be put on the same graph as the first of another color 

- Number of screenings bars per week over the last 4 weeks + average number of guests + average number of participants : https://apexcharts.com/angular-chart-demos/column-charts/basic/

- Connexions rate to the session screenings / guest over the le last 30 days and resume the same as those in place on the dashboard home

Releated to : #3972

**Comment by phpgeekfr** [comment]
@Jackseed Is this still an issue ? Since we can  now use Data Studio and embed it into CRM app.

**Comment by Jackseed** [comment]
I think best would be for @SamirTouira and @RemcoSimonides to discuss and see what's best to implement these now that the architecture changed a bit. 
I guess we can at least use the front part of Samir but not sure of the state of this work

**Comment by SamirTouira** [comment]
Yep let me know if I should continue this part, @RemcoSimonides maybe your have another way to implement these grap?

**Comment by RemcoSimonides** [comment]
Ye I think Bruce is right. We can use Data Studio for this now and embed it.
