### ISSUE TITLE
Update loading spinner component

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4336]
Center it and add a sentence below to explain what's loading

**Comment by stephanie-cascade8** [comment]
Zeplin component here : https://zpl.io/bz4lrgM
@Jackseed can you review the content (text has to be generic to work at different places in the apps ;))

**Comment by fritzschoff** [comment]
@Jackseed is this still valid?

**Comment by Jackseed** [comment]
All good we can close this it's done regarding UI. I'll create the corresponding implementation issue
