### ISSUE TITLE
Not able to call isNotUpdatingField too often in rules

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#4341]
It's not possible to call the isNotUpdatingField too often. Likely due to some limitations by [firestore](https://firebase.google.com/docs/firestore/security/rules-structure#security_rule_limits). Which limitation we do not know yet. Might be that a server call is done everytime `existingData()` or `incomingData()` is called, or how deep the functions are nested
```
isNotUpdatingId('id', existingData().id)
        && isNotUpdatingField(['allDay'])
        && isNotUpdatingField(['end'])
        && isNotUpdatingField(['isPrivate'])
        && isNotUpdatingField(['ownerId'])
        && isNotUpdatingField(['start'])
        // && isNotUpdatingField(['title'])
        // && isNotUpdatingField(['type'])
        // && isNotUpdatingField(['meta', 'organizerId'])
        // && isNotUpdatingField(['meta', 'titleId'])
        // && isNotUpdatingField(['meta', 'controls'])
        // && isNotUpdatingField(['meta', 'files']);
```

**Comment by RemcoSimonides** [comment]
https://stackoverflow.com/questions/55651525/firestore-rules-maximum-of-1000-expressions-to-evaluate-has-been-reached

**Comment by phpgeekfr** [comment]
https://www.notion.so/cascade8/Database-rules-80024b4805b74e1a98ac154f4afeaad7
