### ISSUE TITLE
Cannot display org name in invitation search

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#4356]
Following: #4260
Cannot display org name in invitation search because data is coming from Algolia.
If we want to display it, we need to push orgId on Algolia users indexe or fetch orgId from userId coming from Algolia.

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/8a6ce1d6-39b4-46f5-b845-a29ab6d692fd)

**Comment by Mussuranae** [comment]
So there is a piece of code that was deleted in the algolia file (lib firebase-utils). It added the orgId on the user in algolia to display the name of the org.
Also, just a reminder, if the orgId change on the user and if we registered it on Algolia, we have to update algolia when it changed.

**Comment by Jackseed** [comment]
@fritzschoff @GrandSchtroumpf any recommandation on what's the good way to go here? Would be really helpful for the users to have the org displayed so they're sure of who they invite

**Comment by fritzschoff** [comment]
Don't put only the orgId in the index, cause then you would need to do a second query to Algolia or firebase to get the name. Put the denomination object in the index

**Comment by Jackseed** [comment]
Alright, looks good thanks! then we can put the public denomination and as Mussu said we should be careful to change that on Algolia if the org or the user change
