### ISSUE TITLE
hide broken "avails" search on catalog app 

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#4368]
with a coming back soon message or something like this.
any ideas @Jackseed  ?

**Comment by Jackseed** [comment]
@phpgeekfr I would say that best is event to comment the Avails tab and Avails button on movie view, same with the filters on movie list with a TODO #4368 or whatever issue so we keep track on that when we want to re-implement it

**Comment by Mussuranae** [comment]
Do we hide also the offers and deals link in the sidenav ? And the cart icon on the toolbar ?

**Comment by phpgeekfr** [comment]
My guess is, just hiding the avails tab is enough. Other pages can stay, they are not broken and there is no way to add something since avails search is hidden.

@Jackseed  ?

**Comment by phpgeekfr** [comment]
@Jackseed should we now uncomment the hidden code ?

**Comment by Jackseed** [comment]
@phpgeekfr re the title list avails filter, it has been reworked so we may delete that code
re the movie view avails tab, I would let the team that will work on it (starting in 2 weeks) decide what they want to do. 

@GrandSchtroumpf mb you can confirm for old title list avails filter deletion?
