### ISSUE TITLE
Different level of features accessibility for customers

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4398]
Business plans to sell subscriptions with different features according to what customer choose:
- access only to film dashboard: film list, view & tunnel
- access to screening creation: could be disabled entirely, allowed for unlimited usage or limited to a specific amount of screenings
- access to meeting creation: could be disabled entirely or allowed for unlimited usage

We shall work on wireframes to explore related flows, including the CTAs or tricks to give users a glance of the features they don't have so they see how it works and may upgrade their plans.

**Comment by Jackseed** [comment]
**04/26 meeting notes**

Variables:
- screening counter (+ enable / disable)
- meeting time subscription (+ enable / disable)
- movie counter (+ enable / disable, if disable user can create movie but can't publish it)
- membership ? free / pay-as-you-go / premium

Features limitation:
- secret events
- watch time  

Implementation steps:
1. Enable / disable
2. Counters
3. Better incitation flows

Screening unit = 24h max

Ideas to display options:
- Tag paying features? 
- Membership badge?

Open questions: 
- meeting counter
- features limitation
- display price

CRM needs:
- list variable options

**Comment by 2amarkina** [comment]
**Work in progress**

Wireframes [here](https://www.figma.com/file/dXn5OCa6KZRIAIlW6kbZHt/%5B-Different-levels-of-features-accessibility-for-customers-%5D?node-id=40%3A0) 
- Badge propositions, 
- Company Profile + upgrade plan, 
- Cases coved 

List of Features is [here](https://docs.google.com/spreadsheets/d/1vtSN6KGAjfIlzhSCTzwJsMv7lpesbE58v5lIiPHqSeU/edit#gid=0)

**Comment by Jackseed** [comment]
> UPDT. Important - the access should be shared with other apps. Membership only can be difficult to manage and to secure.

what do you mean?

**Comment by 2amarkina** [comment]
As the main change will concern the users' action to Marketplace / Dashboard, the following step-by-step actions should be taken: 

**TO DO:** 
1.  - [ ] Make a pass to distinguish all the elements where we have different accesses (sidenav, action buttons etc.). 

2. - [ ]  Find alternative solutions for the elements where the switch to other side is crucial (Preview on Marketplace). 

3. Make a new pass on the features accessibility to see if it's still ok. 
- [ ] Check the Badge Solution 
- [ ] Check the Features blocked
- [ ] Check the Organization page 

Maybe finally not modal but a page with features? With future updates.

**Comment by 2amarkina** [comment]
Ideas to design new features to come, Slack example ![Снимок экрана 2021-12-09 в 09.03.45.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/29d46820-0588-4800-82d1-7717ded6284b)
