### ISSUE TITLE
Design review - Release 2.0 preparation 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4400]
Release is planned for December 16th, would be good to have one last design review for:
- Meetings (especially the session page)
- Media Financiers (especially landing & homepage)
- CMS (especially the homepage rendered through the app)

This should be done asap so devs may implement the fixes. There should be a release on staging on Tuesday 8th, reviews can be done there so please plan time to review between Tuesday and Wednesday

**Comment by 2amarkina** [comment]
Last Media Financiers Review is here : https://github.com/blockframes/blockframes/issues/4406

**Comment by stephanie-cascade8** [comment]
Design Review on Media financiers made in task #4406

**Comment by Jackseed** [comment]
I know but homepage and landing pages have been updated since so it's worth reviewing it. Plus, if you have time to make a small tour of the app to be 100% confident on this that's for the best

**Comment by 2amarkina** [comment]
Do not worry, it's not the previous tour that we've made. It was done this week, we created a new issue to keep it clear.

**Comment by Jackseed** [comment]
Oh ok great!

**Comment by stephanie-cascade8** [comment]
CMS design review (after marie tests) : 
Archipel Market ([blockframes-francois-festival.web.app](url))

- [ ] Can you put this on the Banner :     
     min-height: 236px;
    display: flex;
    align-items: center;
    justify-content: center;

before 
<img width="1424" alt="Capture d’écran 2020-12-09 à 10 36 41" src="https://user-images.githubusercontent.com/66258851/101612367-db675b80-3a0a-11eb-94a6-f635cb512182.png">

after
<img width="1440" alt="Capture d’écran 2020-12-09 à 10 36 26" src="https://user-images.githubusercontent.com/66258851/101612401-e28e6980-3a0a-11eb-921d-6ffb22450d7f.png">

- [ ] Slider bullet (replace accent by primary or basic foreground value (700 or 600)
<img width="241" alt="Capture d’écran 2020-12-09 à 10 40 14" src="https://user-images.githubusercontent.com/66258851/101612554-1073ae00-3a0b-11eb-9301-eee088cbbb6d.png">

- [ ] More space between sections (sorry I realize now that what I told you before : 24px is not enough)
I would like to try 60px or 72px.
It would look like this (see the space before title)
<img width="1418" alt="Capture d’écran 2020-12-09 à 10 42 24" src="https://user-images.githubusercontent.com/66258851/101612972-8415bb00-3a0b-11eb-95cb-7cb695ea60f7.png">

- [ ] Title on top of the heading should be a H4 (the same as the one in the landing page's header)

**Comment by Jackseed** [comment]
> CMS design review (after marie tests) :
> Archipel Market ([blockframes-francois-festival.web.app](url))
> 
> * [ ]  Can you put this on the Banner :
>   min-height: 236px;
>   display: flex;
>   align-items: center;
>   justify-content: center;
> 
> before
> <img alt="Capture d’écran 2020-12-09 à 10 36 41" width="1424" src="https://user-images.githubusercontent.com/66258851/101612367-db675b80-3a0a-11eb-94a6-f635cb512182.png">
> 
> after
> <img alt="Capture d’écran 2020-12-09 à 10 36 26" width="1440" src="https://user-images.githubusercontent.com/66258851/101612401-e28e6980-3a0a-11eb-921d-6ffb22450d7f.png">
> 
> * [ ]  Slider bullet (replace accent by primary or basic foreground value (700 or 600)
> 
> <img alt="Capture d’écran 2020-12-09 à 10 40 14" width="241" src="https://user-images.githubusercontent.com/66258851/101612554-1073ae00-3a0b-11eb-9301-eee088cbbb6d.png">
> 
> * [ ]  More space between sections (sorry I realize now that what I told you before : 24px is not enough)
>   I would like to try 60px or 72px.
>   It would look like this (see the space before title)
> 
> <img alt="Capture d’écran 2020-12-09 à 10 42 24" width="1418" src="https://user-images.githubusercontent.com/66258851/101612972-8415bb00-3a0b-11eb-95cb-7cb695ea60f7.png">
> 
> * [ ]  Title on top of the heading should be a H4 (the same as the one in the landing page's header)

Thanks Stéphanie, I added this comment on the CMS issue here: #4415

**Comment by stephanie-cascade8** [comment]
@pldespaigne @2amarkina @Jackseed I'm currently making my review for **Meetings** here: 
[](https://docs.google.com/document/d/1w96ykUZR92qCWa1xXt_1XcyCAokIihXksnNucAZEpQ4/edit#)
