### ISSUE TITLE
Prepare Screen ads

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4401]
We should have some banners and print ads on Screen Daily, should be good to take some time with Marie to prepare roughs in advance so we don't do it in the hurry when it comes (from mid-January to mid-April)

**Comment by stephanie-cascade8** [comment]
https://invis.io/FXZTC5KMYBP

**Comment by pldespaigne** [comment]
This issue seems to be over with the previous comment ☝️ 
Feel free to re-open if it's not the case
