### ISSUE TITLE
MF Last modifications

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#4406]
- [x] remove a dot from "Download" 
<img width="788" alt="Снимок экрана 2020-12-07 в 15 50 02" src="https://user-images.githubusercontent.com/55499036/101365424-113e0000-38a4-11eb-83ea-c5f1837ba46c.png"> 

- [x] map doesn't appear on the "Contact" page using Chrome (OK for Mozilla, OK for Safari)
<img width="1430" alt="Снимок экрана 2020-12-07 в 15 54 39" src="https://user-images.githubusercontent.com/55499036/101366102-d8525b00-38a4-11eb-8366-3ff435eb12f4.png">

- [x] verify the alignment on hover in the toolbar 
<img width="1133" alt="Снимок экрана 2020-12-07 в 16 04 23" src="https://user-images.githubusercontent.com/55499036/101367028-f9677b80-38a5-11eb-8872-dac2412d4b4e.png">

- [x] Dashboard side, some image problem while clicking on notifications / invitations 
![bug](https://user-images.githubusercontent.com/55499036/101367961-e012ff00-38a6-11eb-806f-6d86e05433b2.gif)

**Comment by 2amarkina** [comment]
This two are better to verify with @Stéphanie, but I put them here not to forget
- [ ] not readable tooltip
<img width="276" alt="Снимок экрана 2020-12-07 в 16 32 58" src="https://user-images.githubusercontent.com/55499036/101370635-06866980-38aa-11eb-92c1-6482ea911d78.png">

- [ ] The BG color for the Header is grey, but I suppose that it should be light blue 
<img width="1440" alt="Снимок экрана 2020-12-07 в 16 28 44" src="https://user-images.githubusercontent.com/55499036/101370848-4ea58c00-38aa-11eb-816f-42dec1f7d7d9.png">

**Comment by 2amarkina** [comment]
- [ ] As we have no video upload for the Sales Pitch for the moment, we need to change the text here (screenshot). I would propose  "Please provide your sales presentation description to interest buyers and investors" as a hint. 
<img width="1111" alt="Снимок экрана 2020-12-07 в 16 41 40" src="https://user-images.githubusercontent.com/55499036/101371590-38e49680-38ab-11eb-9caa-196edef3cdeb.png">

**Comment by stephanie-cascade8** [comment]
- [ ] Can you have cards content align vertically with content of other cards ? (img are already same height)
<img width="1361" alt="Capture d’écran 2020-12-08 à 11 34 03" src="https://user-images.githubusercontent.com/66258851/101473253-e0180b00-3949-11eb-8f95-e0fd3abac210.png">

**Comment by stephanie-cascade8** [comment]
- [ ] I'm not sure , can those carousels be empty for the user in real life? If yes let's make a placeholder or something?
<img width="1425" alt="Capture d’écran 2020-12-08 à 11 40 00" src="https://user-images.githubusercontent.com/66258851/101473649-5caae980-394a-11eb-984d-2dc9a10b0259.png">
<img width="1423" alt="Capture d’écran 2020-12-08 à 11 39 52" src="https://user-images.githubusercontent.com/66258851/101473681-692f4200-394a-11eb-8de9-67f82f056186.png">

**Comment by stephanie-cascade8** [comment]
Dashboard 

- [ ] replace class mat-body-1 by mat-body-2 for the line starting by "NB"
<img width="1089" alt="Capture d’écran 2020-12-08 à 11 48 55" src="https://user-images.githubusercontent.com/66258851/101474373-5f5a0e80-394b-11eb-8197-00675ec26b34.png">

**Comment by stephanie-cascade8** [comment]
- [ ] Little bug with ripple effect
<img width="129" alt="Capture d’écran 2020-12-08 à 11 47 24" src="https://user-images.githubusercontent.com/66258851/101474762-d7c0cf80-394b-11eb-94f5-57779aeac22e.png">

**Comment by stephanie-cascade8** [comment]
@fritzschoff That's it for my review. I think It looks good enough, good job :)  I still can see some problems with some spacing and title colors but it's related to my current work on design updates anyway so it should be solved properly soon.

**Comment by fritzschoff** [comment]
![image](https://user-images.githubusercontent.com/39312833/101505698-eec7e780-3974-11eb-91d1-d4b41b434768.png)
@stephanie-cascade8  I need an agreement from you. and if blue. which blue

**Comment by fritzschoff** [comment]
@stephanie-cascade8 can't align the images cause the reward svg has different height then the other svgs 
![image](https://user-images.githubusercontent.com/39312833/101621095-9bf23c80-3a15-11eb-922c-6cb22d4a27ca.png)
