### ISSUE TITLE
CRM

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4416]
Main thing to worry about:
- delete an org (and linked documents)
- delete a movie (and linked documents)
- delete a user (and linked documents)
- change the status of an org (pending > validated)
- invite member to an existing org
- upload excel to create organizations

Tester: @RemcoSimonides + @Mussuranae (each one the part you didn't do)
Bug fix: @RemcoSimonides + @Mussuranae (each one the part you did)

**Comment by RemcoSimonides** [comment]
- [ ] File explorer should should have a defined min-width
![image](https://user-images.githubusercontent.com/27687382/101491112-a18f4a00-3963-11eb-9b79-282e7cd63041.png)

**Comment by pldespaigne** [comment]
**WARNING** : if/when you upload a video to JWPlayer be sure to put the word "test" in the file name. This way we know which videos are tests and which are real production screenings

**Comment by Jackseed** [comment]
Remco improvements are good ones, but low priority for the release so focus on that only if you have spare time

**Comment by Mussuranae** [comment]
I test to invite member in an org with Gmail and Outlook, and both are receiving emails correctly.
Also try to change the status of an org and it works fine.

**Comment by Mussuranae** [comment]
- [ ] For the upload of organization, if you choose `organizations` in the select after downloading your excel, it doesn't work and the spinner is turning forever
![image](https://user-images.githubusercontent.com/48033264/101754805-6ceed000-3ad4-11eb-8669-a456a29fbf01.png)

**Comment by Mussuranae** [comment]
- [ ] There is no simultaion for the user when we want to delete it.
![image](https://user-images.githubusercontent.com/48033264/101759087-729ae480-3ad9-11eb-8ebc-00a55daffced.png)
Functionality works fine !

**Comment by Jackseed** [comment]
> * [ ]  For the upload of organization, if you choose `organizations` in the select after downloading your excel, it doesn't work and the spinner is turning forever
>   ![image](https://user-images.githubusercontent.com/48033264/101754805-6ceed000-3ad4-11eb-8669-a456a29fbf01.png)
>   The upload works fine if we choose our type of document before uploading the excel.

@Mussuranae can you send the file you used? Usually it comes from the data in it when it spins forever

**Comment by Mussuranae** [comment]
I just upload the organization template and add one line with company name/public company name/ contact email adress/org activity/country/ admin email/ festival marketplace for the appAcces. Can't send you the file on Slack -_-

**Comment by RemcoSimonides** [comment]
I think I've seen that bug before and it happens with any file

**Comment by Jackseed** [comment]
I tested organization import and it worked fine both for Safari & brave

**Comment by RemcoSimonides** [comment]
But did you insert excel file before you selected 'Organization'? @Jackseed

**Comment by Jackseed** [comment]
Oh no ok my bad I read too quickly Clélia's comment, indeed that works when you select before the upload but doesn't if you change after the upload

**Comment by Jackseed** [comment]
Remaining issues have been listed here #4514. I close this one until we find another blocking bug for the release
