### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4417]
Tester: @Jackseed 
Bug fix: @SamirTouira

**Comment by Mussuranae** [comment]
The `more` button redirect to the wrong page when the notification is about a project accepted on the platform.
![image](https://user-images.githubusercontent.com/48033264/101501693-592a5900-3970-11eb-8872-cbd14a38d052.png)
![image](https://user-images.githubusercontent.com/48033264/101501667-4dd72d80-3970-11eb-8e97-dc65745471c2.png)

**Comment by Jackseed** [comment]
> The `more` button redirect to the wrong page when the notification is about a project accepted on the platform.
> ![image](https://user-images.githubusercontent.com/48033264/101501693-592a5900-3970-11eb-8872-cbd14a38d052.png)
> ![image](https://user-images.githubusercontent.com/48033264/101501667-4dd72d80-3970-11eb-8e97-dc65745471c2.png)

Didn't test it yet but correct behaviour would be to redirect to **marketplace** movie view for this film

**Comment by 2amarkina** [comment]
- [ ] Need to find other text to explain to a user that the request was sent. I would propose just "Sent" If not - a message is a way too long 
![Uploading Снимок экрана 2020-12-09 в 15.09.51.png…]()

**Comment by Jackseed** [comment]
@Mussuranae for screenings we hide the request access buttons when you are organizer of the event, could we do the same for meetings ?

**Comment by Mussuranae** [comment]
We can but it's on the screening list, do we have somewhere where the meetings appear like the screening and we can ask access to meetings ?

**Comment by Jackseed** [comment]
Right, I tried to reproduce this and the only way you have to request access as the organizer is on the meeting view page on the marketplace
![image](https://user-images.githubusercontent.com/14964443/101659899-d7f1c580-3a46-11eb-88c2-2d39578bba14.png)
![image](https://user-images.githubusercontent.com/14964443/101659919-dde7a680-3a46-11eb-8bb4-7f329c570e00.png)
![image](https://user-images.githubusercontent.com/14964443/101659962-e809a500-3a46-11eb-8ade-f648dfa3c7a7.png)

**Comment by Jackseed** [comment]
- [ ] Existing ticket to take care of #4340

**Comment by Jackseed** [comment]
- [ ] I'll investigate more but it looks like notifications store is not reset after a logout. I just create a new organization and got 15 notif waiting that are not linked to my fresh new account
![image](https://user-images.githubusercontent.com/14964443/101779204-3aa19a80-3af5-11eb-9b90-69b4c6667c03.png)
![Uploading image.png…]()

**Comment by Jackseed** [comment]
- [ ] Notifications to the organizing org when meeting invitation is accepted or declined not sent. They should be implemented following line 35 & 36 from this sheet: https://docs.google.com/spreadsheets/d/1DCO2PH0HaSnt3y6DSPnIX6hXbGsaCw10tCR38gG8LyM/edit#gid=0
Please note that notifications should be sent only to the org super admins

**Comment by SamirTouira** [comment]
Indeed, I am looking for this and I could trigger this notification issue connexion from an account A to an account B.
However, I'm afraid it will be more complicated than we'd think, because when we refresh the notification list page with F5, the issue disappears

**Comment by Jackseed** [comment]
> Indeed, I am looking for this and I could trigger this notification issue connexion from an account A to an account B.
> However, I'm afraid it will be more complicated than we'd think, because when we refresh the notification list page with F5, the issue disappears

Check with @Mussuranae mb but I really look as a Akita notification store issue: when reloading the page it's reset and reloaded but not when you log out

**Comment by Jackseed** [comment]
- [ ] Got permission denied when trying to mark all notifications as read (7 disappeared, 8 remained)
user: dev+maxime-xoh@blockframes.io
app: festival
https://sentry.io/organizations/cascade-8/issues/1883156193/?project=1540126&referrer=slack
mb @phpgeekfr you can give some help on this one?

**Comment by phpgeekfr** [comment]
This may be fixed by the incoming fix from @SamirTouira . I think you tried to mark notification as read that are not yours.

**Comment by Jackseed** [comment]
- [ ] Nice to have but not necessary: change the trigger for `[ User's Name ] was added to your organization.` to be when user saves his/her name (click on sign up button on the identity page). 
Currently it looks like it's when the user enters the identity page but here I did it 3 times and got 3 notifications 
![image](https://user-images.githubusercontent.com/14964443/101909751-39887000-3bbe-11eb-96d3-b385a0076fb1.png)

**Comment by Jackseed** [comment]
- [ ] Notifications are triggered too many times: 2-3 times for the same event
![image](https://user-images.githubusercontent.com/14964443/101910074-bca9c600-3bbe-11eb-9e60-1e049fef1ed8.png)

**Comment by lladreyt** [comment]
- [ ] In Media Financiers I get notifications from Archipel Market 

<img width="1440" alt="Capture d’écran 2020-12-11 à 15 35 20" src="https://user-images.githubusercontent.com/73707444/101915998-a7389a00-3bc6-11eb-93e1-8fc1a70f5414.png">

**Comment by Jackseed** [comment]
> * [ ]  In Media Financiers I get invitations from Archipel Market
> 
> <img alt="Capture d’écran 2020-12-11 à 15 35 20" width="1440" src="https://user-images.githubusercontent.com/73707444/101915998-a7389a00-3bc6-11eb-93e1-8fc1a70f5414.png">

That's something really tricky, currently we don't differentiate apps for notifications and I'm not sure we really want to do that. I opened a dedicated ticket on design #4501

**Comment by Jackseed** [comment]
- [ ] Change notification text triggered when movie status is turned to "accepted". Currently it's "Your project was successfully published on the marketplace."; should be instead: "[ Title name ] was successfully published on the Marketplace."

**Comment by SamirTouira** [comment]
> * [ ]  Notifications to the organizing org when meeting invitation is accepted or declined not sent. They should be implemented following line 35 & 36 from this sheet: https://docs.google.com/spreadsheets/d/1DCO2PH0HaSnt3y6DSPnIX6hXbGsaCw10tCR38gG8LyM/edit#gid=0
>   Please note that notifications should be sent only to the org super admins

@Jackseed How did you triggered this bug ? I've tested it in the meeting invitations part and I've the expected rendering : 

![image](https://user-images.githubusercontent.com/52285231/102109455-5a59fb00-3e34-11eb-9a78-79bf26056522.png)

I have also tested on staging

**Comment by Jackseed** [comment]
@SamirTouira all good then it must have been corrected since.
