### ISSUE TITLE
Invitations

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4418]
New thing to be careful of: screening, check the status of the invitation when organizer 
Tester: @Jackseed 
Bug fix: @SamirTouira

**Comment by RemcoSimonides** [comment]
As I've already tested a bit this morning; here are some of my findings.

## Event invitations
- [ ] Clicking on 'event name' or 'more details' leads to event marketplace page, 
but clicking on the event in calendar directly leads to the lobby of the meeting. Should both lead to lobby immediately? If event has started.

**Comment by Jackseed** [comment]
I confirm, both should lead to lobby if event has started

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101789583-c5889200-3b01-11eb-90a7-1f3f94d485a5.png)

- [ ] If possible, put the org name in capital letters (to distinguish from rest of the text)

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101804589-08eafc80-3b12-11eb-95fa-1e2d7a425c3a.png)

- [ ] There's a display problem with pending invitations. Should show "Pending" here instead of  "Your request has been sent to the organizer. We're waiting for them to let you in."

**Comment by Jackseed** [comment]
> ![image](https://user-images.githubusercontent.com/55785823/101804589-08eafc80-3b12-11eb-95fa-1e2d7a425c3a.png)
> 
> * [ ]  There's a display problem with pending invitations. Should show "Pending" here instead of  "Your request has been sent to the organizer. We're waiting for them to let you in."

already listed (and debugged!) on notifications issue #4417

**Comment by SamirTouira** [comment]
> > ![image](https://user-images.githubusercontent.com/55785823/101804589-08eafc80-3b12-11eb-95fa-1e2d7a425c3a.png)
> > 
> > * [ ]   There's a display problem with pending invitations. Should show "Pending" here instead of  "Your request has been sent to the organizer. We're waiting for them to let you in."
> 
> already listed (and debugged!) on notifications issue #4417

Maybe not with the "pending", it probably appears only when the status of the invitation is "pending" as you said @maltmayer  if you have tested right now

**Comment by Jackseed** [comment]
@SamirTouira then Marie is right it has to be changed to Pending
