### ISSUE TITLE
Homepage MF

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4419]
Tester: @pldespaigne 
Bub fix: @GrandSchtroumpf

**Comment by pldespaigne** [comment]
- [ ] wish-list button can be hard to spot

![image](https://user-images.githubusercontent.com/5858657/101618212-f5586c80-3a11-11eb-91a8-11cea0268026.png)

**Comment by Jackseed** [comment]
@stephanie-cascade8 any recommandation for the comment above?

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101918502-b8cf7100-3bc9-11eb-81f9-b252c665128b.png)

- [ ] org logos are too big they should look like the ones on Archipel Market:
![image](https://user-images.githubusercontent.com/55785823/101918636-e1576b00-3bc9-11eb-9239-1f216e5ff636.png)

**Comment by Jackseed** [comment]
I close this ticket, everything has been transferred to ticket #4514
