### ISSUE TITLE
Marketplace - Movie list

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4420]
Old remaining bug, hard to catch and debug but worth mentioning it:
- [x] when a poster is missing, it takes the poster of another movie; 

Things to check also:
- load more button
- full text query (search bar)

Tester: @SamirTouira  
Bug fix: @RemcoSimonides

**Comment by pldespaigne** [comment]
- [ ] Ouch

![image](https://user-images.githubusercontent.com/5858657/101617596-1b314180-3a11-11eb-88c5-06d8e87a5eb5.png)

**Comment by RemcoSimonides** [comment]
@Jackseed I can't reproduce the one you mentioned. Is it always replaced or do I have to do something in order to trigger the bug?

**Comment by SamirTouira** [comment]
> @Jackseed I can't reproduce the one you mentioned. Is it always replaced or do I have to do something in order to trigger the bug?

Same for my side, i don't find this bug, then same question ^^'

**Comment by Jackseed** [comment]
@RemcoSimonides no sorry but we couldn't reproduce it either when it was a ticket for sanity team. It's actually currently in prod for the movie Beast but no clue what is responsible of it (when trying to reproduce it, we can't..)
I added as a reminder but just leave that as it is if you don't have any lead and we'll wait for this to happen again :/

**Comment by phpgeekfr** [comment]
@RemcoSimonides 
I got this on Ubuntu / Firefox
![image](https://user-images.githubusercontent.com/1194344/101652319-64e45100-3a3e-11eb-9cfa-eaab2668c4be.png)

Caused by this poster : https://staging.archipelmarket.com/c/o/marketplace/title/iU65gXv1FwMEW35qIaQt/main

And if I search for this movie only: 
![image](https://user-images.githubusercontent.com/1194344/101652449-89d8c400-3a3e-11eb-9648-6ae167e5afe1.png)


I'm not sure the movie is funny at all. Maybe a hint ..

**Comment by 2amarkina** [comment]
**LIBRARY FESTIVAL MARKETPLACE** 
- [ ] Searching in toolbar should have an icon and the text as in the normal search bar 

Here: 
<img width="847" alt="Снимок экрана 2020-12-10 в 17 06 07" src="https://user-images.githubusercontent.com/55499036/101797270-2025ec00-3b0a-11eb-85bd-92d1a9b40e4b.png">

Should be like: 
<img width="1388" alt="Снимок экрана 2020-12-10 в 17 05 59" src="https://user-images.githubusercontent.com/55499036/101797290-261bcd00-3b0a-11eb-82ea-892b4470014b.png">

**Comment by Jackseed** [comment]
Closed for #4549
