### ISSUE TITLE
Marketplace - Public org list

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4421]
Tester: @RemcoSimonides  
Bug fix: @phpgeekfr

**Comment by RemcoSimonides** [comment]
- [ ] Search bar is searching something else than organizations...
- [ ] It says 'You've viewed 8 partners from 11.', and when I click 'load more' button, it is showing 7 more organization making it 15 in total. Also, on another tab I have 'You've viewed 8 partners from 9. Without using any filters in both scenario's.
![Search bar doing weird things](https://user-images.githubusercontent.com/27687382/101497742-950eef80-396b-11eb-881a-52bdb92a4b81.gif)

**Comment by RemcoSimonides** [comment]
- [ ] Wrong image shown in first item of list
![Wrong image shown in first item](https://user-images.githubusercontent.com/27687382/101613181-bcb59480-3a0b-11eb-96fd-e2b3e8bfeaf0.gif)

**Comment by Jackseed** [comment]
- [ ] Load more button doesn't work on Safari (works on Brave)
![image](https://user-images.githubusercontent.com/14964443/101781374-0380b880-3af8-11eb-8a0b-b3652f204c05.png)

**Comment by Jackseed** [comment]
- [ ] Display 25 organizations by default

**Comment by 2amarkina** [comment]
**FESTIVAL MARKETPLACE ORG LIST (Sales Agents)**
@maltmayer could confirm the texts, pls?
- [ ] Title should be "Sales Agents" 

- [ ] Text in searchbar : Search for our sales agents... 

- [ ] CTA text change to "Company's Nationality" 
<img width="1380" alt="Снимок экрана 2020-12-10 в 17 08 52" src="https://user-images.githubusercontent.com/55499036/101797962-db4e8500-3b0a-11eb-8556-927646092f6d.png">


When we scroll search bar should be the same : 

- [ ] Text : Search for our sales agents...  

- [ ] Searching icon inside of a search bar 

- [ ] Verify for that a CTA filter stays "Company's Nationality"  

<img width="903" alt="Снимок экрана 2020-12-10 в 17 12 28" src="https://user-images.githubusercontent.com/55499036/101798093-02a55200-3b0b-11eb-87f0-26b95d41e411.png">

**Comment by Jackseed** [comment]
- [ ] MF: partner page is empty though there are at least 2 partners, here I'm connected with one (user `
dev+roberta-yfa@blockframes.io`, orgId `e1VXeusNJK6pb8kmVnUn`

![image](https://user-images.githubusercontent.com/14964443/101801827-0dfa7c80-3b0f-11eb-9966-66f2da381004.png)

![image](https://user-images.githubusercontent.com/14964443/101801993-3c785780-3b0f-11eb-9cf5-2e90d35256bb.png)

**Comment by phpgeekfr** [comment]
On MF we have 'partner's country' 
![image](https://user-images.githubusercontent.com/1194344/101904399-0f32b480-3bb6-11eb-94b9-bb2a828708fe.png)

On archipelMaket 'partner country'
![image](https://user-images.githubusercontent.com/1194344/101904469-2a052900-3bb6-11eb-8974-4c2bc58b69b7.png)

**Comment by phpgeekfr** [comment]
But nvm because text should be changed to `Company's Nationality`

**Comment by phpgeekfr** [comment]
>     * [ ]  MF: partner page is empty though there are at least 2 partners, here I'm connected with one (user ` dev+roberta-yfa@blockframes.io`, orgId `e1VXeusNJK6pb8kmVnUn`
> 
> 
> ![image](https://user-images.githubusercontent.com/14964443/101801827-0dfa7c80-3b0f-11eb-9966-66f2da381004.png)
> 
> ![image](https://user-images.githubusercontent.com/14964443/101801993-3c785780-3b0f-11eb-9cf5-2e90d35256bb.png)

This is due to the restore process after each release to staging. UpgradeAlgoliaOrgs is performed before we restore data, so there is no orgs with appAccess.financiers

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/102078998-31be0b00-3e0c-11eb-9257-566e1f15bd6e.png)
![image](https://user-images.githubusercontent.com/55785823/102079011-3682bf00-3e0c-11eb-8b2b-ee57e424b609.png)

- [ ] "Partners" have been replaced by "Sales Agents" on MF. "Sales Agents" is for Archipel Market. "Partners" is for MF
