### ISSUE TITLE
Marketplace - Public org view

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4422]
Don't forget to test the screenings tab on festival app

Tester: @fritzschoff  
Bug fix: @Mussuranae

**Comment by fritzschoff** [comment]
![image](https://user-images.githubusercontent.com/39312833/101615885-f50aa200-3a0e-11eb-8263-680e390d597a.png)
No intercom icon on brave/linux

**Comment by fritzschoff** [comment]
![image](https://user-images.githubusercontent.com/39312833/101616104-3a2ed400-3a0f-11eb-8d32-1a4a3cf50c04.png)
should be clickable and open up the email app

**Comment by Jackseed** [comment]
> * [ ]  ![image](https://user-images.githubusercontent.com/39312833/101615885-f50aa200-3a0e-11eb-8263-680e390d597a.png)
>   No intercom icon on brave/linux
>   visible on MF but not on AF

Couldn't reproduce this one, I close this ticket in the meantime
