### ISSUE TITLE
Marketplace - Wishlist

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4423]
Don't forget to check the implication of a movie deleted via CRM while being on a wishlist

Tester: @Jackseed 
Bug fix: @RemcoSimonides

**Comment by Jackseed** [comment]
URL https://staging.archipelmarket.com/c/o/marketplace/title/6bBG8bnM2NRjUErIHmep/main
Config: Mac / Safari 14.0
User: dev+maxime-xoh@blockframes.io

Add to wishlist on movie view banner doesn't work:
- the snackbar "added to wishlist" appears but wishlist doesn't increment nor the button turn red
![image](https://user-images.githubusercontent.com/14964443/101635208-ec739500-3a29-11eb-9d08-68a823a382d0.png)

And in fact the whole wishlist doesn't work: I can't delete any items from the existing one. 

I tried with same user and film on Brave and it worked so looks linked to Safari.

Han tried with another user on Safari and it worked :O

**Comment by RemcoSimonides** [comment]
I just tested this one Safari 12 and it does work. Which version of Safari did you use? And with which account did you login?

**Comment by Jackseed** [comment]
Re above, it was a nice bug that just disappeared over night, if only they were all like this ..

**Comment by lladreyt** [comment]
- [ ] Cannot access to the film page when I click on the title from the wish list 

<img width="1431" alt="Capture d’écran 2020-12-11 à 13 35 34" src="https://user-images.githubusercontent.com/73707444/101904296-ea3e4180-3bb5-11eb-8e61-095879956705.png">

**Comment by Jackseed** [comment]
> * [ ]  Cannot access to the film page when I click on the title from the wish list
> 
> <img alt="Capture d’écran 2020-12-11 à 13 35 34" width="1431" src="https://user-images.githubusercontent.com/73707444/101904296-ea3e4180-3bb5-11eb-8e61-095879956705.png">

Working on my side, we'll need more details to reproduce it in the meantime I close this
