### ISSUE TITLE
Festival Marketplace - Screening list

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4424]
Tester: @GrandSchtroumpf  
Bug fix: @SamirTouira

**Comment by 2amarkina** [comment]
I was not sure if it concerns specifically Screening List or Movie Page and I don't know if it is difficult to handle right now, but  leave it here. 

When user gets his "accepted", is it possible to change CTA "Ask for invitation" by text "You already have your invitation" or smth  (not sure for the text)? 

As if on the Screening List the invitation was already accepted, there is no need for a user to ask for it one more time 

![FireShot Capture 601 - Film Page - Screening Schedule - Archipel Market - staging archipelmarket com](https://user-images.githubusercontent.com/55499036/101757788-dae8c680-3ad7-11eb-822f-b21a75bf8bf9.png)

**Comment by Jackseed** [comment]
I agree with you @2amarkina, in fact we have an existing issue for that #4311 but I'm afraid it's gonna be too much for the release. 
@SamirTouira and mb @Mussuranae what's your call on this one?

**Comment by Mussuranae** [comment]
I will look at it right now and tell you here, if we can do it quickly. I completely forget this ticket because we don't put it in a sprint since its creation.

**Comment by maltmayer** [comment]
![Enregistrement de l’écran 2020-12-10 à 16 34 28 (1)](https://user-images.githubusercontent.com/55785823/101793711-6416f200-3b06-11eb-850b-461441e6137e.gif)
Public event approval process still weird. We shouldn't see the sentence about the org approval appear. Should directly go to the event page, without this kind of weird jump

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101794051-c2dc6b80-3b06-11eb-8233-06a67ef49a60.png)
- [ ] Change text to "Add to My Calendar"

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101794130-d38ce180-3b06-11eb-8907-e994fc37fa95.png)

- [ ] "This event has already started" should be in another color I think. Blue maybe? Smaller text also I think

- [ ] Change "Request access" CTA text to "Request Access"

- This Request access CTA has a weird alignment I think, but I'll let @stephanie-cascade8 do her review

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101794585-501fc000-3b07-11eb-9377-bc749b4725e3.png)
The status text looks kind of naked. Should maybe have an icon next to it. Or other format maybe ? @stephanie-cascade8 what do you think?

**Comment by maltmayer** [comment]
click on poster on this page should lead to event page, not movie page.
I can imagine that will be complicated.Another idea would be to have a CTA to go to event page directly (people are confused and don't think of clicking on the title to go to event page. We have to find a way to make them less confused) @2amarkina

**Comment by 2amarkina** [comment]
I agree to lead a user to an event page, and to my mind it's quicker solution than trying to find a good place for a CTA. 

But I would note it as a future improvement - to have a more explicit link to show to user where to go and keep the clickable poster leading to the movie page to find out more details. Just to keep in mind that we use the same component for "upcoming screening list" where user discovers the future screenings and needs to learn more about a film and also we use it on the Movie page itself, where a user has already seen the details and wants only access to the event page. So the best improvement would be to cover these two cases.

**Comment by Jackseed** [comment]
I sorted a bit comments on this ticket, @SamirTouira the remaining changes to make for the release:

- [ ] Change public event CTA text to "Add to My Calendar"
![image](https://user-images.githubusercontent.com/55785823/101794051-c2dc6b80-3b06-11eb-8233-06a67ef49a60.png)

- [ ] Change "Request access" CTA text to "Request Access"
![image](https://user-images.githubusercontent.com/55785823/101794130-d38ce180-3b06-11eb-8907-e994fc37fa95.png)

- [ ] Change link on the poster to be the same as event title > `/c/o/marketplace/event/eventId`
![image](https://user-images.githubusercontent.com/55785823/101794585-501fc000-3b07-11eb-9377-bc749b4725e3.png)
