### ISSUE TITLE
Festival Marketplace - Calendar view

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4425]
Tester: @fritzschoff  
Bug fix: @GrandSchtroumpf

**Comment by fritzschoff** [comment]
couldn't find an UI bugs. Only the loading time is like 2 seconds and when you switch weeks with the arrows it takes also a good 2 seconds to load the page.

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101790643-fcab7300-3b02-11eb-9773-97b47bdb697b.png)

- [ ] Change text from "Filter-by" to "Filter by"
