### ISSUE TITLE
Festival Marketplace - Event view (screening + meeting)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4426]
Tester: @fritzschoff 
Bug fix: @RemcoSimonides & @pldespaigne

**Comment by RemcoSimonides** [comment]
As I've already tested a bit this morning; here are some of my findings.

- [ ] Organized by Organization name should link to Organization page

**Comment by fritzschoff** [comment]
![image](https://user-images.githubusercontent.com/39312833/101617168-98a88200-3a10-11eb-82bf-4b38827a6146.png)
the title seems off

**Comment by Jackseed** [comment]
> ![image](https://user-images.githubusercontent.com/39312833/101617168-98a88200-3a10-11eb-82bf-4b38827a6146.png)
> the title seems off

Should be instead:
Screening name - Screening - Archipel Market
Meeting name - Meeting - Archipel Market

**Comment by 2amarkina** [comment]
To verify with @stephanie-cascade8 , but 

- [ ] hover on the organization should not take all the line

- [ ] space checking needed between "org logo + name" and "More Details"

<img width="1399" alt="Снимок экрана 2020-12-10 в 10 44 17" src="https://user-images.githubusercontent.com/55499036/101758505-b2150100-3ad8-11eb-9e1e-ccb10bac5c00.png">

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101793208-d6d39d80-3b05-11eb-9eb1-41cf8a02bc5e.png)

- [ ] Put a stop at the end of the sentences and update text:
You are the owner of this event.
You can invite members and edit the event details in your dashboard.

**Comment by maltmayer** [comment]
- [ ] click on poster on this page should lead to event page, not movie page.

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101800781-ed7df280-3b0d-11eb-9abe-6562d75d43bd.png)

- [ ] Reduce space between "Accepted" and CTA

**Comment by maltmayer** [comment]
- [ ] Light mode pending status shows up in the wrong color
![image](https://user-images.githubusercontent.com/55785823/101805336-ee655300-3b12-11eb-9361-634fc7094e09.png)

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101915088-6db35f00-3bc5-11eb-9a6c-123a9d576f2f.png)

- [ ] color of CTA "More Details" in light them is not good here (should be lighter, like on prod) 

- [ ] CTA too close to org logo when the synopsis is long

![image](https://user-images.githubusercontent.com/55785823/101915219-9b000d00-3bc5-11eb-800a-f44a0f047965.png)

**Comment by Jackseed** [comment]
- [ ] Access screening room CTA has disappeared for a second invitation status 
![image](https://user-images.githubusercontent.com/14964443/101920146-bc63f780-3bcb-11eb-9e1d-bed6f84fd272.png)

**Comment by maltmayer** [comment]
> * [x]  As the event owner, I see a button to 'request access'. This should be 'access event' and immediately go to the event.
>   ![image](https://user-images.githubusercontent.com/27687382/101891474-5e6eea00-3ba2-11eb-9277-4be12fa04df3.png)

If I can add something, it should be "Access Event" with capital E :) thanks

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/102076331-da1da080-3e07-11eb-8ea7-8dc290192269.png)
- [ ] Event is currently ongoing and there's no CTA
