### ISSUE TITLE
Festival Marketplace - Screening lobby + session

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4427]
Don't forget to check the modale when leaving the session and especially when trying to log out

Tester: @phpgeekfr 
Bug fix: @pldespaigne

**Comment by phpgeekfr** [comment]
unnecessary vertical scroll bar ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/3996a0c7-067b-49ae-8c62-d4cae92b10ac)

**Comment by phpgeekfr** [comment]
During a screening, If I attempt to leave page I got the popin. 
If I try to logout, no popin but no error & I get redirected to homepage.

I think this behavior is OK. If an user wants to logout, this is intentional

**Comment by phpgeekfr** [comment]
Loader displayed just before this image : 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/0af50410-059a-4806-ac3e-869b3431c25b)

is not centered

**Comment by Jackseed** [comment]
> During a screening, If I attempt to leave page I got the popin.
> If I try to logout, no popin but no error & I get redirected to homepage.
> 
> I think this behavior is OK. If an user wants to logout, this is intentional

to homepage or landing ? landing is ok 👍

**Comment by phpgeekfr** [comment]
@Jackseed Yes to landing (https://staging.archipelcontent.com) sorry

**Comment by Jackseed** [comment]
- [ ] Watermark has been reduced it's way too small now and not placed well; could it be changed to what it was before?
![image](https://user-images.githubusercontent.com/14964443/101793654-519cb880-3b06-11eb-9fa3-1027e926e102.png)

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/102077705-03d7c700-3e0a-11eb-8e97-7d7c133cdde1.png)

- [ ] video should be centered vertically when opened in full screen
