### ISSUE TITLE
Festival Marketplace - Meeting lobby + session

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4428]
Tester: @Mussuranae 
Bug fix: @pldespaigne

**Comment by RemcoSimonides** [comment]
As I've already tested a bit this morning; here are some of my findings. @Jackseed should determine whether they should be in the release or not

## Meeting session
- [ ] Everyone is immediately kicked out when refreshing page. Maybe there should be a delay to give the owner a minute to return before everyone is kicked out?
- [ ] Camera light of laptop stays on even though I disabled the camera (&microphone)

**Comment by Jackseed** [comment]
@RemcoSimonides @pldespaigne I checked with Anastasiia & Marie re your first point and best would be:
Meeting is closed when the last sales agent member is out of the meeting for more than 15min. 
Is that doable without too much trouble?

**Comment by stephanie-cascade8** [comment]
Design review for Meetings here:
https://docs.google.com/document/d/1w96ykUZR92qCWa1xXt_1XcyCAokIihXksnNucAZEpQ4/edit#

**Comment by Jackseed** [comment]
- [ ] Got that error when trying to share a pdf (that loads for ever): https://sentry.io/organizations/cascade-8/issues/2083403988/?project=1540126&referrer=slack
It was on that meeting https://staging.archipelmarket.com/c/o/marketplace/event/HGzRiZGbMiTzJgEBJsCp/session
with user dev+maxime-xoh@blockframes.io trying to share "Group Logical pdf"

**Comment by Jackseed** [comment]
- [ ] weird behaviour when I stop the cam, initials appear but background of the last cam image stays
![image](https://user-images.githubusercontent.com/14964443/101796339-1d76c700-3b09-11eb-94f8-1e95bc413d03.png)

**Comment by Jackseed** [comment]
- [ ] Movie should be centered vertically when shared
![Uploading image.png…]()

**Comment by Jackseed** [comment]
> @RemcoSimonides @pldespaigne I checked with Anastasiia & Marie re your first point and best would be:
> Meeting is closed when the last sales agent member is out of the meeting for more than 15min.
> Is that doable without too much trouble?
> 
> PL: Nope it's pretty hard to implement this kind of timer,
> @Jackseed any opinion on that and above ?

Alright let's drop that

**Comment by Jackseed** [comment]
- [ ] Change a bit the UI for video control:
- add the time already passed to the left of the slider
- keep the Play / Pause button above the slider but center it 
=> something similar to this
![image](https://user-images.githubusercontent.com/14964443/101797802-b78b3f00-3b0a-11eb-8788-053c3513aabf.png)
![image](https://user-images.githubusercontent.com/14964443/101797972-df7aa280-3b0a-11eb-9be5-dbfa4c2b6f33.png)

**Comment by Jackseed** [comment]
- [ ] When the video is finished, the countdown keep counting. If possible, stop the count when current time === ending time and put video on pause. If the user clicks on play while current time === ending time it should play back the video from the beginning 
![image](https://user-images.githubusercontent.com/14964443/101798314-3da78580-3b0b-11eb-9810-d0a3825b163d.png)

**Comment by Jackseed** [comment]
- [ ] When clicking on an element that has already been shared, it should reset it. Here I clicked on the video already shared and it was still at then end of the video

![image](https://user-images.githubusercontent.com/14964443/101798747-beff1800-3b0b-11eb-815f-6795e8300907.png)

**Comment by Jackseed** [comment]
- [ ] Full screen button doesn't work on Safari
![image](https://user-images.githubusercontent.com/14964443/101799825-e1456580-3b0c-11eb-8039-a02bd72ea75d.png)

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101903428-9121de00-3bb4-11eb-892a-5adbb74a2415.png)

- [ ] adding a file, it should be Title Files first, Organization Files second

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101903616-d7773d00-3bb4-11eb-9f2e-852d8bd79faa.png)

- [ ] + should be on the same line as the files no? @stephanie-cascade8

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101903710-ff66a080-3bb4-11eb-8521-b0939dd3f3d6.png)

- [ ] When adding a file the icons should be aligned on the right no? @stephanie-cascade8  (sorry if it's already in your review, I can't access it)

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101903867-3c329780-3bb5-11eb-8377-3cc7c6b6c661.png)

- [ ] I get a file that loads indefinitely

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/102077838-384b8300-3e0a-11eb-956b-2281f75ed86c.png)

- [ ] video should be centered vertically (even when opened in full screen)
