### ISSUE TITLE
MF Marketplace - Movie view (including Financial + campaign tabs)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4429]
Tester: @RemcoSimonides  
Bug fix: @fritzschoff  

The fixing is related to MF Dashboard - Movie view #4438

**Comment by RemcoSimonides** [comment]
- [ ] Maybe it's my db - i'll test again after prepareForTesting
![Uploading image.png…]()

**Comment by 2amarkina** [comment]
Really sorry, but I found one more thing ... 

- [ ] Snackbar here after sending is a way too fast. I didn't have enough time to read what was the error (so there was also an error with sending a form and it's essential)
<img width="748" alt="Снимок экрана 2020-12-09 в 16 01 08" src="https://user-images.githubusercontent.com/55499036/101646640-12a03180-3a38-11eb-8ac1-607d613c9bfa.png">

**Comment by Jackseed** [comment]
- [ ] Coming of age has no label ? anyway it's not displayed on the movie view. The label had been changed to "Young adults" so maybe that's linked
![image](https://user-images.githubusercontent.com/14964443/101786144-e222cb00-3afd-11eb-9f59-9daa0a9c769f.png)
![image](https://user-images.githubusercontent.com/14964443/101786383-2746fd00-3afe-11eb-8c9f-09adaed176c2.png)

**Comment by 2amarkina** [comment]
Do not know how difficult it is and if it's considered as "new" thing, but maybe do these images clickable ? A click will open a preview with full-size picture ? 
<img width="1098" alt="Снимок экрана 2020-12-10 в 16 44 07" src="https://user-images.githubusercontent.com/55499036/101794445-2c5c7a00-3b07-11eb-8319-b5c00f4d91f3.png">

**Comment by maltmayer** [comment]
![Enregistrement de l’écran 2020-12-10 à 17 17 30](https://user-images.githubusercontent.com/55785823/101800059-1e115c80-3b0d-11eb-909f-d2a3223e5645.gif)
- When I request an invitation to a screening session, I can't request for another session after.
- Shouldn't be able to "request" if the event is public. It should say "Add to Calendar" for public events...

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101800678-ce7f6080-3b0d-11eb-8d69-d3ab07fa4428.png)

- [ ] Delete "Pay attention, the screenings are live sessions. They will only be available at the mentioned times."

- [ ] If possible, put the date on 1 line and the time on the second line (just like on the marketplace view of an event)

**Comment by maltmayer** [comment]
![Enregistrement de l’écran 2020-12-10 à 17 15 32](https://user-images.githubusercontent.com/55785823/101805677-51ef8080-3b13-11eb-86e4-a02e94943690.gif)

- [ ] Loading problem on this component for movies with screenings

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101805940-a561ce80-3b13-11eb-9206-e61abf41bdce.png)

- [ ] Next screening hero component should not appear on the "upcoming screenings" tab

**Comment by Jackseed** [comment]
- [ ] Stills are misshapen on Safari (right screen vs Brave on the left)
![image](https://user-images.githubusercontent.com/14964443/101806030-c0344300-3b13-11eb-98f8-687e218b34ea.png)

**Comment by Jackseed** [comment]
- [ ] Actor card, weird only the first one has a status icon while they're all confirmed
![image](https://user-images.githubusercontent.com/14964443/101806194-f8d41c80-3b13-11eb-9dd6-96d756a8c1a9.png)

**Comment by maltmayer** [comment]
- [ ] org info doesn't show on movie banner
![image](https://user-images.githubusercontent.com/55785823/101809273-a4cb3700-3b17-11eb-845b-a3af8f5303ae.png)

**Comment by Jackseed** [comment]
- [ ] Artistic is listed twice in MF modale "Open discussion"
![What do you want to know about this project](https://user-images.githubusercontent.com/14964443/101895798-4bf7af00-3ba8-11eb-97d0-ba5f0dd4e1ba.png)

- [ ] Safari film review icon is too big
![Film Reviews](https://user-images.githubusercontent.com/14964443/101895846-5b76f800-3ba8-11eb-9684-a78199cc6260.png)

- [ ] Miss space for producer roles (eg "LINE PRODUCER" or "EXECUTIVE PRODUCER")
![LINEPRODUCER](https://user-images.githubusercontent.com/14964443/101895861-629e0600-3ba8-11eb-9508-13077c8e2274.png)

- [ ] Remove `-` after the last element 
![EXPECTED PREMIERE](https://user-images.githubusercontent.com/14964443/101895930-7d707a80-3ba8-11eb-875c-0a9eb414ca40.png)

- [ ] If possible, use currency icon instead of initials and round numbers to be integers (eg $259,865)
![Pasted Graphic 23](https://user-images.githubusercontent.com/14964443/101895969-8c572d00-3ba8-11eb-8ea8-56dc7b09f092.png)

**Comment by fritzschoff** [comment]
> ![Enregistrement de l’écran 2020-12-10 à 17 17 30](https://user-images.githubusercontent.com/55785823/101800059-1e115c80-3b0d-11eb-909f-d2a3223e5645.gif)
> 
> * When I request an invitation to a screening session, I can't request for another session after.
> * Change CTA text to "Register for this session"

wrong issue. This is issue about media financiers. @maltmayer can you move this to the propper issue

**Comment by lladreyt** [comment]
- [ ] The currency is not asked/precise in the "Open discussion" CTA

<img width="609" alt="Capture d’écran 2020-12-11 à 15 19 30" src="https://user-images.githubusercontent.com/73707444/101914526-b61e4d00-3bc4-11eb-81b8-b679c087b98d.png">

**Comment by Jackseed** [comment]
> > ![Enregistrement de l’écran 2020-12-10 à 17 17 30](https://user-images.githubusercontent.com/55785823/101800059-1e115c80-3b0d-11eb-909f-d2a3223e5645.gif)
> > 
> > * When I request an invitation to a screening session, I can't request for another session after.
> > * Change CTA text to "Register for this session"
> 
> wrong issue. This is issue about media financiers. @maltmayer can you move this to the propper issue

I told Marie to put here as there is no issue specific to Archipel Market movie view. Mb @Mussuranae or @SamirTouira you could take the comments related to the screening banner as you debugged it already?

**Comment by lladreyt** [comment]
- [ ] What about xlx/xls format ? On my computer it opens up with Numbers (MAC)

<img width="623" alt="Capture d’écran 2020-12-11 à 16 01 23" src="https://user-images.githubusercontent.com/73707444/101918932-4612c580-3bca-11eb-98f1-eea6c86f768f.png">

**Comment by maltmayer** [comment]
- [ ] this should be "Storyline Elements" instead of "Story Elements"
![image](https://user-images.githubusercontent.com/55785823/101918961-5165f100-3bca-11eb-8cff-d66630036180.png)

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101919361-c1747700-3bca-11eb-9851-8b2da31d2b56.png)

- [ ] Sales Pitch shouldn't appear when empty

- [ ] Sales Pitch shouldn't be first here. Should it even be on this page @2amarkina @Jackseed ? If so, put it after Directors

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101919666-1dd79680-3bcb-11eb-9ad9-c0b3c463b160.png)

- [ ] This font is not Montserrat. Is this normal @stephanie-cascade8 ?

**Comment by Jackseed** [comment]
> * [ ]  What about xlx/xls format ? On my computer it opens up with Numbers (MAC)
> 
> <img alt="Capture d’écran 2020-12-11 à 16 01 23" width="623" src="https://user-images.githubusercontent.com/73707444/101918932-4612c580-3bca-11eb-98f1-eea6c86f768f.png">

This is default behaviour of the library we use, it's a new feature to have .xls

**Comment by fritzschoff** [comment]
> ![image](https://user-images.githubusercontent.com/55785823/101805940-a561ce80-3b13-11eb-9206-e61abf41bdce.png)
> 
> * [ ]  Next screening hero component should not appear on the "upcoming screenings" tab

this is not possible cause the screening component is a app specific component

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/102079257-a1cc9100-3e0c-11eb-9526-ed431b6b4def.png)

- [ ] Change hint from "Meet the fund to have further information" to "Contact financier for further information"

- [ ] Change transparent CTA text to: "Learn more about investing in the content industry"

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/102079619-54045880-3e0d-11eb-84cd-619d27679b41.png)

- [ ] Weird dotted line in this component in Artistic tab

**Comment by fritzschoff** [comment]
> ![image](https://user-images.githubusercontent.com/55785823/102079619-54045880-3e0d-11eb-84cd-619d27679b41.png)
> 
> * [ ]  Weird dotted line in this component in Artistic tab

can't find it. Guess the screenshot is wrong

**Comment by fritzschoff** [comment]
> * [x]  Actor card, weird only the first one has a status icon while they're all confirmed
>   ![image](https://user-images.githubusercontent.com/14964443/101806194-f8d41c80-3b13-11eb-9dd6-96d756a8c1a9.png)

checked with my database and all actors are checked when they are confirmed. Which movie was that on staging

**Comment by maltmayer** [comment]
> > ![image](https://user-images.githubusercontent.com/55785823/102079619-54045880-3e0d-11eb-84cd-619d27679b41.png)
> > 
> > * [ ]   Weird dotted line in this component in Artistic tab
> 
> can't find it. Guess the screenshot is wrong?
> @maltmayer

No it's not, zoom in and compare it to the following picture. It's light but there are dots under the funding line
![image](https://user-images.githubusercontent.com/55785823/102085491-02f96200-3e17-11eb-8f9d-dfa17f68817f.png)
