### ISSUE TITLE
MF Marketplace - Movie filters

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4430]
This has to be tested on MF since there is a campaign filter only there

Tester: @Mussuranae  
Bug fix: @SamirTouira

**Comment by Jackseed** [comment]
- [ ] Remove "All languages" from Language & Version filter list
![image](https://user-images.githubusercontent.com/14964443/101780581-0202c080-3af7-11eb-8c9c-5a5ca9d0b6a4.png)

**Comment by Jackseed** [comment]
- [ ] Budget filter not working on Safari (cf screenshot Brave on left vs Safari on right)
![image](https://user-images.githubusercontent.com/14964443/101785741-66c11980-3afd-11eb-99be-c5d452698417.png)

**Comment by Jackseed** [comment]
- [ ] Change budget filter behaviour (nice to have for the release, not required so low priority): we should reverse the way it works and go from right to left, starting at a maximum 20M$ budget and choosing till how much it goes down.
E.g. I go halfway from 20M to 10M and got all films that have budget range between 10M & 20M$

**Comment by 2amarkina** [comment]
- [ ] There is an "search-icon" missing in a search bar while scrolling 
Here : 
<img width="918" alt="Снимок экрана 2020-12-10 в 16 57 28" src="https://user-images.githubusercontent.com/55499036/101796228-02a45280-3b09-11eb-8fa7-ea6626cf5ef2.png">

Should be like : 
<img width="562" alt="Снимок экрана 2020-12-10 в 16 57 22" src="https://user-images.githubusercontent.com/55499036/101796254-089a3380-3b09-11eb-8150-be91e1a5269d.png">

**Comment by Jackseed** [comment]
All issues have been duplicated here: #4514 
that's not needed for the release, I close this ticket
