### ISSUE TITLE
MF Marketplace - Org filters

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4431]
Tester: @phpgeekfr  
Bug fix: @fritzschoff

**Comment by phpgeekfr** [comment]
@Jackseed the only filter to test here are text search and country right ?

https://staging.mediafinanciers.com/c/o/marketplace/organization

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/a5e2ff22-0d61-4307-a15a-c3c05c6096d8)

**Comment by Jackseed** [comment]
Yep

**Comment by phpgeekfr** [comment]
So, despite images that can be mixed (but fixed already in another issue). everything seems to work fine

**Comment by Jackseed** [comment]
Re-opened:
- [ ] World shouldn't be on that list
![image](https://user-images.githubusercontent.com/14964443/101780075-58bbca80-3af6-11eb-867d-a697cd8de027.png)

**Comment by Jackseed** [comment]
- [ ] Got nothing on France while there are some
![image](https://user-images.githubusercontent.com/14964443/101780156-75580280-3af6-11eb-84b6-bece0cc28526.png)
![image](https://user-images.githubusercontent.com/14964443/101780246-94ef2b00-3af6-11eb-923e-7ff5417f1a50.png)

- [ ] Clear doesn't reload the whole list
![image](https://user-images.githubusercontent.com/14964443/101780202-856fe200-3af6-11eb-9330-846fabc85929.png)

**Comment by Jackseed** [comment]
Country filter works well on movie list for Safari so mb check for differences ? 
Also if we could add the chips on that filter would be a good update (nice to have not required)
![image](https://user-images.githubusercontent.com/14964443/101780764-37a7a980-3af7-11eb-9826-be0d1904ba5e.png)

**Comment by Jackseed** [comment]
- [ ] Not sure if that's possible for the release but let me know: could we remove the filters bar when scrolling down? It gives us 2 bars with navbar + filters and that's too much. Same goes for movie filters

**Comment by 2amarkina** [comment]
- [ ] Searching icon is missing 
<img width="672" alt="Снимок экрана 2020-12-10 в 17 01 25" src="https://user-images.githubusercontent.com/55499036/101796675-77778c80-3b09-11eb-9ff5-931a4626f025.png">

- [ ] Need to put a searching icon inside 
<img width="846" alt="Снимок экрана 2020-12-10 в 17 02 51" src="https://user-images.githubusercontent.com/55499036/101796853-a857c180-3b09-11eb-9f84-25e7bf41fe1b.png">

**Comment by Jackseed** [comment]
> * [ ]  You can only search by the name of a person and not by company name
> 
> <img alt="Capture d’écran 2020-12-11 à 15 39 26" width="1435" src="https://user-images.githubusercontent.com/73707444/101916494-4b224580-3bc7-11eb-91c0-629a4c4a5dfa.png">

This is working, XYZ has a different name on staging to preserve confidentiality
