### ISSUE TITLE
Dashboard - Homepage

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4432]
Tester: @RemcoSimonides  
Bug fix: @SamirTouira

**Comment by Mussuranae** [comment]
First gift, the sidenav isn't in dark theme
![image](https://user-images.githubusercontent.com/48033264/101495574-fda89d00-3968-11eb-9ce7-bb1f715c11ee.png)

**Comment by RemcoSimonides** [comment]
@Mussuranae I think that's a change in the design

**Comment by Mussuranae** [comment]
Yeah, that was I said to Samir, but as I'm not sure, I let you see if it's wanted or not

**Comment by RemcoSimonides** [comment]
Alright, I asked Stephanie ;) Let's wait for answer

**Comment by RemcoSimonides** [comment]
No bugs to report otherwise

**Comment by RemcoSimonides** [comment]
She is still working on the colors but the current light theme is intended! :wink:  @Mussuranae  @SamirTouira

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101902509-0c829000-3bb3-11eb-9fc6-a68ee248bc51.png)
- [ ] add capital letters: "See My Titles"

**Comment by Jackseed** [comment]
I close this ticket for the release, duplicated issue here #4514
