### ISSUE TITLE
Festival Dashboard - Meeting form

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4436]
Tester: @phpgeekfr 
Bug fix: @pldespaigne

**Comment by RemcoSimonides** [comment]
As I've already tested a bit this morning; here are some of my findings.

- [ ] Dark theme disabled button is really hard to read
- [ ] Link that can be copied is also hard to read in dark mode
- [ ] Organized by doesn't seem to be mandatory and isn't pre-filled. I think it should have been?

**Comment by Jackseed** [comment]
Thanks Remco, I confirm the first 2 points, the last one changed since now the organizer doesn't have all the power but in fact every org member have so that's ok not to be mandatory and pre-filled

**Comment by 2amarkina** [comment]
- [ ] The clickable "My files" should be in bold to show that there is an action behind 
<img width="1146" alt="Снимок экрана 2020-12-09 в 14 05 02" src="https://user-images.githubusercontent.com/55499036/101633604-c51bc880-3a27-11eb-9575-204f2492c5bb.png">

**Comment by phpgeekfr** [comment]
Sames remarks as in #4434

+ Typo in sentence `There no selected files yet. Click on the button above to add some files.`

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/71d3a3f7-0c40-458e-bcf7-9a2f8467c962)

**Comment by 2amarkina** [comment]
- [ ] Add a tooltip to "copy" icon "Copy the link" 
<img width="1164" alt="Снимок экрана 2020-12-09 в 14 44 43" src="https://user-images.githubusercontent.com/55499036/101637869-9b65a000-3a2d-11eb-8291-4174db449e1d.png">

**Comment by phpgeekfr** [comment]
In file explorer, when I try to preview file, loader is not centered:

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/aeba3c54-330f-47a4-9826-de4e1772eab5)

**Comment by stephanie-cascade8** [comment]
Design review for Meetings here:
https://docs.google.com/document/d/1w96ykUZR92qCWa1xXt_1XcyCAokIihXksnNucAZEpQ4/edit#

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101780298-a6383780-3af6-11eb-9fd1-989c6de6adcd.png)
- [ ] Change "Link to video call" to "Link to Video Call"
- [ ] Change "Organized By" to "Organized by"
- [ ] Change Organized by hint to "This person will appear as event organizer on the marketplace and all invitations will be sent in their name."

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101781012-93723280-3af7-11eb-913b-3af8ca6334cd.png)
- [ ] Change CTA text to "Add Files"
- [ ] Change empty Selected Files text to: "There is no selected files yet. Please click the button above to add files."

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101781792-8f92e000-3af8-11eb-894e-054a94b3d99a.png)

- [ ] Change text to "Go to Event Page"

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101782298-1d6ecb00-3af9-11eb-805f-c0ce9747da1c.png)

- [ ] Change placeholder to "Invite Guests"
- [ ] Add capital to Guests in the number of guests. here : "2 Guests"
- [ ] Change the invitation status texts from "yes" to "accepted" and from "no" to "declined"

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101782552-6fafec00-3af9-11eb-9c8b-63ef5b4562a3.png)

- [ ] Change search bar text to "Search for a Guest"

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101782643-90784180-3af9-11eb-8011-c63e7c6e974a.png)
- [ ] Change Delete CTA color to red.
- [ ] Put Delete first, Cancel second
- [ ] I think there's too much space between the 2 CTAs (not a huge problem)

**Comment by Jackseed** [comment]
- [ ] Don't display Statistics section at the bottom if the event hasn't started yet (for screening & meeting forms)

**Comment by RemcoSimonides** [comment]
> ![image](https://user-images.githubusercontent.com/55785823/101782643-90784180-3af9-11eb-8011-c63e7c6e974a.png)
> 
> * [ ]  Change Delete CTA color to red.
> 
> Vincent:
> According to discussion forget about below comments
> 
> * [x]  Put Delete first, Cancel second
> * [x]  I think there's too much space between the 2 CTAs (not a huge problem but would be better with half I think)
> 
> Anastasiia's Comment : Delete should stay here. For such kind of representation the main action should be on the right side. UPDT. but if we want that the main action here is "cancel" than we should put it ont the right side with the main CTA color. But I if a user has clicked on "delete" his main action should stay "delete"

Changing the color of the Delete CTA to red will change it in all confirm dialogs. @stephanie-cascade8 what do you say? should this button be red (warn) everywhere?
