### ISSUE TITLE
Festival Dashboard - File explorer

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4437]

**Comment by RemcoSimonides** [comment]
As I've already tested a bit this morning; here are some of my findings.

- [ ] Update btn should be disabled when form is not dirty
- [ ] Padding around single file-upload component

**Comment by pldespaigne** [comment]
**WARNING** : if/when you upload a video to JWPlayer be sure to put the word "test" in the file name. This way we know which videos are tests and which are real production screenings

**Comment by Mussuranae** [comment]
When you see a document in full screen you uploaded, the button at bottom-right sticks the edge of the window
![image](https://user-images.githubusercontent.com/48033264/101620059-5f721100-3a14-11eb-8f55-1ab8259491f5.png)

**Comment by 2amarkina** [comment]
- [ ] Preview of uploaded documents doesn't work 
![preview](https://user-images.githubusercontent.com/55499036/101638958-05327980-3a2f-11eb-8716-37eba5a586ca.gif)

- [ ] Download of a doc doesn't work 
![download](https://user-images.githubusercontent.com/55499036/101639229-52165000-3a2f-11eb-9abf-e622d1fe1bd7.gif)

**Comment by stephanie-cascade8** [comment]
Design review for Meetings here:
https://docs.google.com/document/d/1w96ykUZR92qCWa1xXt_1XcyCAokIihXksnNucAZEpQ4/edit#

**Comment by Jackseed** [comment]
- [ ] Not really file explorer but upload widget, icon is not well rendered on Safari
![image](https://user-images.githubusercontent.com/14964443/101805344-f02f1680-3b12-11eb-8e29-5e4e492f9cab.png)

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101810662-5880f680-3b19-11eb-8f33-ce1429973d0f.png)

- [ ] Update text to:
This is your File Storage. Its structure is predetermined. 
We trust you to upload the correct content into the relevant folder!

- [ ] Highlight File Storage to show that it's a link/ Pag. Maybe just put it in bold? @2amarkina ?

**Comment by 2amarkina** [comment]
Actually, I do not think that we really need it here. User is already on this page (My Files = File Storage). If we put it in bold here it might be confusing - user might think that it will lead somewhere (contrary of Event Creation page). Only advantage I see is that such a link will work as a "refresh" btn

**Comment by Jackseed** [comment]
From Marie:
![image](https://user-images.githubusercontent.com/55785823/101903710-ff66a080-3bb4-11eb-8521-b0939dd3f3d6.png)

- [ ] When adding a file the icons should be aligned on the right no? @stephanie-cascade8  (sorry if it's already in your review, I can't access it)

**Comment by Jackseed** [comment]
From Marie:
![image](https://user-images.githubusercontent.com/55785823/101903428-9121de00-3bb4-11eb-892a-5adbb74a2415.png)

- [ ] when adding a file, it should be Title Files first, Organization Files second

**Comment by RemcoSimonides** [comment]
> From Marie:
> ![image](https://user-images.githubusercontent.com/55785823/101903428-9121de00-3bb4-11eb-892a-5adbb74a2415.png)
> 
> * [ ]  when adding a file, it should be Title Files first, Organization Files second

Titles Files take a moment to load while Organization Files are instant. Do you still want to switch these tabs around knowing this? Loading time depends on number of titles

**Comment by maltmayer** [comment]
> > From Marie:
> > ![image](https://user-images.githubusercontent.com/55785823/101903428-9121de00-3bb4-11eb-892a-5adbb74a2415.png)
> > 
> > * [ ]   when adding a file, it should be Title Files first, Organization Files second
> 
> Titles Files take a moment to load while Organization Files are instant. Do you still want to switch these tabs around knowing this? Loading time depends on number of titles

I think so yes
