### ISSUE TITLE
MF Dashboard - Movie view (including campaign, financial and campaign modale on banner)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4438]
Tester: @pldespaigne 
Bug fix: @fritzschoff 

The fixing is related to MF Marketplace - Movie view #4429

**Comment by Jackseed** [comment]
- [ ] Duplicate Country of origin 
![image](https://user-images.githubusercontent.com/14964443/101496965-b58a7a00-396a-11eb-8ee7-ba74fdbb75fb.png)

**Comment by pldespaigne** [comment]
- [ ] Missing & Mandatory links of the "General Information" section don't point to the tunnel (movie form), they point to the same page. (Other links are fine)
![image](https://user-images.githubusercontent.com/5858657/101610016-f2f11500-3a07-11eb-9c82-e0582af98c54.png)

**Comment by pldespaigne** [comment]
- [ ] Empty funding display only the table header, that's weird (idk if it's a bug or not, sorry if it was intended)
![image](https://user-images.githubusercontent.com/5858657/101611690-187f1e00-3a0a-11eb-963b-276a65698c9e.png)

**Comment by pldespaigne** [comment]
- [ ] When "Needed investment" is missing the error message is weird, maybe use 0 as default if it's missing ? Or maybe disable the modal button "Update funding status" as long as "Needed investment" hasn't been filled up.
![image](https://user-images.githubusercontent.com/5858657/101612109-92170c00-3a0a-11eb-8b82-322a2bdd2157.png)

**Comment by pldespaigne** [comment]
- [ ] Unable to update the funding status if "Minimum investment needed" is missing
![image](https://user-images.githubusercontent.com/5858657/101614652-837e2400-3a0d-11eb-99d2-6da0b493d1f8.png)

**Comment by pldespaigne** [comment]
- [ ] title is always "Main Information" all tabs

![image](https://user-images.githubusercontent.com/5858657/101620657-19697d00-3a15-11eb-9912-189d66bbf0bf.png)

**Comment by Jackseed** [comment]
> * [ ]  title is always "Main Information" all tabs
> 
> ![image](https://user-images.githubusercontent.com/5858657/101620657-19697d00-3a15-11eb-9912-189d66bbf0bf.png)

I confirm it's a bug, "Main information" should be replaced with active tab name (eg "Financial" here)

**Comment by Jackseed** [comment]
![image](https://user-images.githubusercontent.com/14964443/101802551-db9d4f00-3b0f-11eb-9dde-0cad3e4ce4ee.png)

**Comment by Jackseed** [comment]
- [ ] tab production, remove the comma after the first production company, copro, distrib..
![Production Information](https://user-images.githubusercontent.com/14964443/101895150-72691a80-3ba7-11eb-99e1-4cced073e49f.png)

- [ ] tab artistic miss description for both cast & crew and crew role for crew; remove the last comma after "1 (2015)
![Artistic Team](https://user-images.githubusercontent.com/14964443/101895217-86148100-3ba7-11eb-8b9f-3a1b8bfa4f16.png)
Zeplin [here](https://app.zeplin.io/project/5ca741b3ed21e79faa266664/screen/5f4661c0e0b519853085cf7f)

**Comment by Jackseed** [comment]
- [ ] If possible to be app-specific there, above "Update funding status" a percentage of the current funding (eg "82% funded"). Round the number to be integer
![The Execution](https://user-images.githubusercontent.com/14964443/101895720-31253a80-3ba8-11eb-8287-b4478cbc5a74.png)
