### ISSUE TITLE
MF Dashboard - Movie form + campaign form

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4440]
Tester: Design + Business teams
Bug fix: @GrandSchtroumpf @fritzschoff

**Comment by pldespaigne** [comment]
**WARNING** : if/when you upload a video to JWPlayer be sure to put the word "test" in the file name. This way we know which videos are tests and which are real production screenings

**Comment by RemcoSimonides** [comment]
- [ ] Typo in priveleges
![image](https://user-images.githubusercontent.com/27687382/101504357-685ed600-3973-11eb-9adc-9db0596e35e9.png)

- [ ] Also, for some reason I gave invalid input but I don't know why
![image](https://user-images.githubusercontent.com/27687382/101504480-8f1d0c80-3973-11eb-9652-a1bd0230e1a2.png)

**Comment by 2amarkina** [comment]
Error message for the Minimum Investment Amount : 
"Your minimum investment amount should be lower than the total investment needed" @maltmayer would it be ok as a text?

**Comment by RemcoSimonides** [comment]
There is an error message if I enter too much;
![image](https://user-images.githubusercontent.com/27687382/101507877-53844180-3977-11eb-89f2-6814099f6e5b.png)

Also, the error is gone now... Let me try to get it back and figure out what I did 😅

**Comment by RemcoSimonides** [comment]
- [ ] Alignment of image and status is odd
![image](https://user-images.githubusercontent.com/27687382/101508271-bc6bb980-3977-11eb-910c-81f66ca7446f.png)

**Comment by RemcoSimonides** [comment]
- [ ] Able to set a number below zero and no error message is shown. And still able to save the form
![Able to update to number below 0](https://user-images.githubusercontent.com/27687382/101514203-4f5b2280-397d-11eb-95d6-ded56e55f736.gif)

**Comment by pldespaigne** [comment]
- [ ] Create a Privilege, save, close the movie form, go back to the movie form > Privilege : your privilege are gone
![image](https://user-images.githubusercontent.com/5858657/101616264-77936180-3a0f-11eb-98a7-ab5b3f6155df.png)

**Comment by RemcoSimonides** [comment]
- [ ] Low ROI can be higher than medium ROI and high ROI, same with medium ROI can be higher than high ROI. We should probably prevent this behavior

**Comment by 2amarkina** [comment]
- [ ] Here instead of "Crew's filmography" should be "Release Year" 
<img width="1102" alt="Снимок экрана 2020-12-09 в 16 09 19" src="https://user-images.githubusercontent.com/55499036/101647855-84c54600-3a39-11eb-8dfb-4177c3c3580c.png">

**Comment by Jackseed** [comment]
> * [ ]  Here instead of "Crew's filmography" should be "Release Year"
> 
> <img alt="Снимок экрана 2020-12-09 в 16 09 19" width="1102" src="https://user-images.githubusercontent.com/55499036/101647855-84c54600-3a39-11eb-8dfb-4177c3c3580c.png">

I confirm

**Comment by Jackseed** [comment]
- [ ] Issue #4338 has some debug also, especially the part for promo videos

**Comment by Jackseed** [comment]
- [ ] Shooting info page, display issue on Safari (right screen vs Brave on left)
![image](https://user-images.githubusercontent.com/14964443/101803601-ffad6000-3b10-11eb-86ce-9defeaf7b4c5.png)

**Comment by Jackseed** [comment]
- [ ] If possible, format numbers with American number style within the number inputs (eg here pledge level: 10,000) 
![Pasted Graphic 3](https://user-images.githubusercontent.com/14964443/101892573-d8ec3980-3ba3-11eb-9b3c-0b6a09b90035.png)

- [ ] Cast & Crew members filmographies don't appear on the bf table (it works on director)
![Cast Member](https://user-images.githubusercontent.com/14964443/101892717-06d17e00-3ba4-11eb-8cdc-aa372d6a3907.png)

- [ ] For the list component, remove the last "-" (eg here "Oscar - Best Foreign Movie - 2021")
![Oscar Academy Awards Best Foreign Movie - 2021 -](https://user-images.githubusercontent.com/14964443/101892854-31bbd200-3ba4-11eb-9491-0fc471ac19de.png)

- [ ] Dark mode, button toggles are unreadable when selected
![Other Festival   Awards](https://user-images.githubusercontent.com/14964443/101892949-51eb9100-3ba4-11eb-8e71-e25b106aec3c.png)

- [ ] Summary page, some edit links are broken:
- all the ones included in Storyline Elements (logline, synopsis, Key assets, Keywords)
- technical information format

- [ ] If possible, remove "Funding Status" in the summary page as it's not editable from here anymore. It should stay on the dashboard movie view tab investment
![Investment conditions](https://user-images.githubusercontent.com/14964443/101893116-937c3c00-3ba4-11eb-97fc-a595d9883e09.png)

**Comment by Jackseed** [comment]
- [ ] Add a line of text with the total amount for financing plan below financing plan and budget: 
- Below financing plan: "Your total financing plan is: {{movieCurrency}} {{totalFinancing}}" (formated with american style number)
- Below budget: "N.B. Your total financing plan is: {{movieCurrency}} {{totalFinancing}}" (formated with american style number)
- If financing plan has not been touched yet, instead of $0, display "N.B. Your total financing plan is: N/C"
![image](https://user-images.githubusercontent.com/14964443/101893804-8ad83580-3ba5-11eb-9284-9a0da8678a44.png)

- [ ] Add a line of text the total amount of estimated budget below financing plan
- "N.B. Your total estimated budget is: {{movieCurrency}} {{totalBudget}}" (formated with american style number)
- If budget has not been touched yet, instead of $0, display "N.B. Your total estimated budget is: N/C"

**Comment by lladreyt** [comment]
- [ ] Could we name the last section "other" and put "cotingency, producers fees, OH fees" in (). Sorry Max I know I never got back to you on the matter. 
<img width="1437" alt="Capture d’écran 2020-12-11 à 15 49 18" src="https://user-images.githubusercontent.com/73707444/101917657-c9cbb280-3bc8-11eb-9738-8829522e62b4.png">

**Comment by lladreyt** [comment]
- [ ] Is it necessay to have the arrows on the right since they allow to move/up down with 1$ = 1 click and here we're talking millions ? 

<img width="1417" alt="Capture d’écran 2020-12-11 à 15 54 00" src="https://user-images.githubusercontent.com/73707444/101918193-5e361500-3bc9-11eb-9c04-57c49eea5344.png">

**Comment by lladreyt** [comment]
- [ ] Why are these 2 companies suggested as producers ? When you save a production company on another movie, it is automatically proposed for other movies ? 
<img width="1437" alt="Capture d’écran 2020-12-11 à 19 17 22" src="https://user-images.githubusercontent.com/73707444/101939740-b24ef280-3be5-11eb-956a-da50425742ff.png">

**Comment by Jackseed** [comment]
> * [ ]  Why are these 2 companies suggested as producers ? When you save a production company on another movie, it is automatically proposed for other movies ?
> 
> <img alt="Capture d’écran 2020-12-11 à 19 17 22" width="1437" src="https://user-images.githubusercontent.com/73707444/101939740-b24ef280-3be5-11eb-956a-da50425742ff.png">

It's production companies that have been saved on that movie

**Comment by lladreyt** [comment]
No but these 2 companies where predefined when I created a new film (not produced by these companies) 


> > * [x]   Why are these 2 companies suggested as producers ? When you save a production company on another movie, it is automatically proposed for other movies ?
> > 
> > <img alt="Capture d’écran 2020-12-11 à 19 17 22" width="1437" src="https://user-images.githubusercontent.com/73707444/101939740-b24ef280-3be5-11eb-956a-da50425742ff.png">
> 
> It's production companies that have been saved on that movie

**Comment by Jackseed** [comment]
> No but these 2 companies where predefined when I created a new film (not produced by these companies)
> 
> > > * [x]    Why are these 2 companies suggested as producers ? When you save a production company on another movie, it is automatically proposed for other movies ?
> > > 
> > > <img alt="Capture d’écran 2020-12-11 à 19 17 22" width="1437" src="https://user-images.githubusercontent.com/73707444/101939740-b24ef280-3be5-11eb-956a-da50425742ff.png">
> > 
> > 
> > It's production companies that have been saved on that movie

Oh right my bad it's definitely a bug, good catch!

Just reproduced it by:
- going on dashboard movie view of a film
- creating a new film
=> Production company use the prod info from the movie view visited

**Comment by RemcoSimonides** [comment]
> > No but these 2 companies where predefined when I created a new film (not produced by these companies)
> > > > * [ ]     Why are these 2 companies suggested as producers ? When you save a production company on another movie, it is automatically proposed for other movies ?
> > > > 
> > > > <img alt="Capture d’écran 2020-12-11 à 19 17 22" width="1437" src="https://user-images.githubusercontent.com/73707444/101939740-b24ef280-3be5-11eb-956a-da50425742ff.png">
> > > 
> > > 
> > > It's production companies that have been saved on that movie
> 
> Oh right my bad it's definitely a bug, good catch!
> 
> Just reproduced it by:
> 
> * going on dashboard movie view of a film
> * creating a new film
>   => Production company use the prod info from the movie view visited

Someone with knowledge about the MovieForm has to take over creating a solution for this bug. I created a draft PR which proposes a solution for the issue but isn't generic. https://github.com/blockframes/blockframes/pull/4534

**Comment by fritzschoff** [comment]
I can take over!

**Comment by fritzschoff** [comment]
@GrandSchtroumpf okay for you?
