### ISSUE TITLE
Landing Festival & MF

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4441]
Tester: Design + Business teams
Bug fix: @Mussuranae

**Comment by 2amarkina** [comment]
**Landing Finaniers** 
- [ ] CTA "Schedule a demo" doesn't lead to demo section form 
<img width="1427" alt="Снимок экрана 2020-12-09 в 15 40 13" src="https://user-images.githubusercontent.com/55499036/101644093-14b4c100-3a35-11eb-8527-6589e57d7f8a.png">

- [ ] Put  "Wellcome to MF" in uppercase 
<img width="1210" alt="Снимок экрана 2020-12-09 в 15 42 31" src="https://user-images.githubusercontent.com/55499036/101644373-665d4b80-3a35-11eb-8f4b-68a2c86061de.png">


- [ ] Do not we miss "s" at the end of "professional"?
<img width="397" alt="Снимок экрана 2020-12-09 в 15 45 39" src="https://user-images.githubusercontent.com/55499036/101644946-1763e600-3a36-11eb-9677-b4e42a70adf9.png">

- [ ] When demo request is sent, no spacing between the text and "!" in the snackbar 

- [ ] Here we seem to be forcing the french phone number. Or we do not show it at all, or we need to make it clickable and we can choose this prefix 
<img width="397" alt="Снимок экрана 2020-12-09 в 15 52 07" src="https://user-images.githubusercontent.com/55499036/101645681-efc14d80-3a36-11eb-8113-f384d4ed53ee.png">

- [ ] Maybe make these ones clickable ? 
<img width="1056" alt="Снимок экрана 2020-12-09 в 15 55 34" src="https://user-images.githubusercontent.com/55499036/101645789-0bc4ef00-3a37-11eb-9724-fefec059ff9e.png">

**Comment by Jackseed** [comment]
I don't think it's really useful to have links there, some of it will be only French and the others are well known in the cinema industry

**Comment by Jackseed** [comment]
- [ ] #4335  still open issue for festival & catalog

**Comment by 2amarkina** [comment]
**Landing Market** 

- [ ] Uppercase for "Welcome" 
<img width="1414" alt="Снимок экрана 2020-12-10 в 11 16 52" src="https://user-images.githubusercontent.com/55499036/101758954-441d0980-3ad9-11eb-9093-a68bcd937e0c.png">

- [ ] Spacing question (check with @stephanie-cascade8 ), but I would say that we should take Financiers example 
<img width="910" alt="Снимок экрана 2020-12-10 в 11 20 04" src="https://user-images.githubusercontent.com/55499036/101759467-ee952c80-3ad9-11eb-90f2-3adaa04a8694.png">

**Comment by Jackseed** [comment]
- [ ] On MF image for Investors is misshapen on Safari (left Brave, right Safari)
![image](https://user-images.githubusercontent.com/14964443/101801380-8c0a5380-3b0e-11eb-8439-f0d8786ad14e.png)

**Comment by maltmayer** [comment]
- [ ] not enough margin on the left compared to prod
![image](https://user-images.githubusercontent.com/55785823/101896677-9d546e00-3ba9-11eb-8675-874ebafcf2f2.png)
![Uploading image.png…]()

**Comment by lladreyt** [comment]
- [ ] In the "Want to learn more" section, should we limit the number of figures after the "+" so that you can only but a country phone code and not the entire number ? 

<img width="1051" alt="Capture d’écran 2020-12-11 à 13 26 49" src="https://user-images.githubusercontent.com/73707444/101903999-756b0780-3bb5-11eb-98f5-5035d199d322.png">

**Comment by Jackseed** [comment]
> * [ ]  In the "Want to learn more" section, should we limit the number of figures after the "+" so that you can only but a country phone code and not the entire number ?
> 
> <img alt="Capture d’écran 2020-12-11 à 13 26 49" width="1051" src="https://user-images.githubusercontent.com/73707444/101903999-756b0780-3bb5-11eb-98f5-5035d199d322.png">

Good idea, it should be max 3 numbers

**Comment by Jackseed** [comment]
remaining issues moved to #4514

**Comment by maltmayer** [comment]
> > * [ ]   In the "Want to learn more" section, should we limit the number of figures after the "+" so that you can only but a country phone code and not the entire number ?
> > 
> > <img alt="Capture d’écran 2020-12-11 à 13 26 49" width="1051" src="https://user-images.githubusercontent.com/73707444/101903999-756b0780-3bb5-11eb-98f5-5035d199d322.png">
> 
> Good idea, it should be max 3 numbers

- [ ] Also, should force it to be number value. Right now you can also write text

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/102077416-8f048d00-3e09-11eb-90d9-79dc9ef56117.png)

- [ ] Change text on MF: replace "Archipel team" by "Media Financiers team"

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/102077509-b5c2c380-3e09-11eb-9f6e-dace02ea9fcc.png)
- [ ] Role field goes up when error hint appears. Should stay put
