### ISSUE TITLE
Auth flow (org + account)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4443]
Tester: @Jackseed 
Bug Fix: @pldespaigne

**Comment by Jackseed** [comment]
**Identity page**
- [ ] Change "Join Archipel Market" with "Welcome!" to be app-agnostic 
![image](https://user-images.githubusercontent.com/14964443/101909184-6d16ca80-3bbd-11eb-8822-acf84ae6d782.png)
- [ ] Change 1st checkbox text for "I hereby accept Term and Conditions." to app agnostic too

**Comment by Jackseed** [comment]
**Sign up page**
- [ ] Remove "Terms and Conditions" that is not underlined with link to have it only once with a link
![image](https://user-images.githubusercontent.com/14964443/101910639-802a9a00-3bbf-11eb-958a-86c6af6a229f.png)

**Comment by maltmayer** [comment]
- [ ] Change activity list to (in this order):

- Actor
- Buyers' Rep
- Consulting
- Director
- Distribution
- Film Commission
- Film Festival
- Film Fund
- Film Library
- Film School
- Financial Institution
- International Sales
- Institution
- Organization
- Press
- Private Investor
- Production 
- Talent Agency
- Technical
- TV Broadcast
- Theatrical Exhibition
- VOD Platform
- Other
