### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4445]
Things to test:
- 'normal' one 
- test writing on the db 
- maintenance during a screener 
-backup/restore process

**Comment by phpgeekfr** [comment]
After a small fix, maintenance mode seems to work well.

It now starts only during the upgrade part, functions and hosting are deployed before without maintenance mode active.

during maintenance mode, db access if forbidden and the various triggers are stopped (no mails sent).

A backup / restore was successfully performed with :

```
npm run backend-ops use blockframes-staging
npm run backend-ops displayCredentials
npm run backend-ops healthCheck

npm run backend-ops backup
npm run backend-ops restore
```

And the maintenance mode was correctly set during the restore part.

**Comment by phpgeekfr** [comment]
If the maintenance mode is set during a screening session, users in screening **are still redirected**

The only current way to prevent this is to perform an deploy without db version changes
