### ISSUE TITLE
General layout

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4454]
Tester: everyone
Bug Fix: @SamirTouira @phpgeekfr @pldespaigne

**Comment by pldespaigne** [comment]
- [ ] All scroll bar are not styled in firefox

![image](https://user-images.githubusercontent.com/14964443/101618429-44060680-3a12-11eb-9b4d-b46dcf6dae77.png)

**Comment by phpgeekfr** [comment]
@pldespaigne do you have an example of what it should look like please ?

**Comment by Jackseed** [comment]
- [ ] elements are too close on navbar 
![image](https://user-images.githubusercontent.com/14964443/101777909-6c196680-3af3-11eb-8755-a642d7225ff6.png)

**Comment by maltmayer** [comment]
- [ ] The dark theme logo is too blue I think. It's more blue than the existing logo on prod
![image](https://user-images.githubusercontent.com/55785823/101805178-bfe77800-3b12-11eb-9728-485579729798.png)

![image](https://user-images.githubusercontent.com/55785823/101805200-c4ac2c00-3b12-11eb-8421-726b423521c2.png)

**Comment by maltmayer** [comment]
Logo in dark them is good now but not for light theme. Logos should be different from one theme to the other
![image](https://user-images.githubusercontent.com/55785823/101809762-3a66c680-3b18-11eb-8a9f-1e8a929923b7.png)

**Comment by maltmayer** [comment]
![image](https://user-images.githubusercontent.com/55785823/101809781-418dd480-3b18-11eb-829d-dac349dce77e.png)
Logo in dark them is good now but not for light theme. Logos should be different from one theme to the other


> * [ ]  The dark theme logo is too blue I think. It's more blue than the existing logo on prod
>   ![image](https://user-images.githubusercontent.com/55785823/101805178-bfe77800-3b12-11eb-9728-485579729798.png)
> 
> ![image](https://user-images.githubusercontent.com/55785823/101805200-c4ac2c00-3b12-11eb-8421-726b423521c2.png)

**Comment by phpgeekfr** [comment]
@Jackseed can we close ?

**Comment by Jackseed** [comment]
yes!
