### ISSUE TITLE
Optimize Assets

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#4489]
It's a mess to work with assets currently : 
- old assets
- Safari enforce us to use png over webp
- difficulty to keep sizing amongst themes

A solution would be to store the asset in imgix directly : 
1. clean the asset folder from deprecated assets
2. upload assets to imgix in Webp (one per theme)
3. create UI for Stéphanie to freely upload the assets (checkout [imgix assets management](https://www.imgix.com/solutions/image-management) or us the CMS)

Bonus: 
- Specify why to use svg (illustration, icons) and when to use webp (placeholders, images)

**Comment by stephanie-cascade8** [comment]
updating https://docs.google.com/document/d/1jBJ3kBS8n4PTsq2NqFWIvtuZwcUL4WTGM8LJEv6iCEE/edit

**Comment by stephanie-cascade8** [comment]
Clean logos 
Response to @Mussuranae (clelia) here 
https://github.com/blockframes/blockframes/commit/6e1e2ad97e4bc0ccff21901651cc9fc3aa5cbf9c

- Empty_org (feel free to rename it and tell me if the name already exist)
https://zpl.io/aRR7WjE
<img width="160" alt="Capture d’écran 2021-06-14 à 12 00 20" src="https://user-images.githubusercontent.com/66258851/121874916-1d4dc300-cd08-11eb-85b2-bea67d46ba35.png">

- "2 logo don't have dark and light mode"
no need for dark/light on those logos (plus we want to ask the forced light mode for future landings and they are coming soon) let's keep logos like that.

- "Reorganise logos in the apps"
1. let's keep 2 version (light and dark) for each
2. every logo in svg (delete any png and webp)
find the right version here:
https://zpl.io/bePjDKN

Or find them all here as well:
https://drive.google.com/drive/folders/1x-EorKxNND7CBIRK1gB6y2daLyNKHXjU

**Comment by Mussuranae** [comment]
Logos are reworked, I create a folder for the logo for the emails, because those one have to be in PNG (Gmail doesn't support SVG). And like that, it's more specific, we know what is used in email template.

**Comment by stephanie-cascade8** [comment]
@Mussuranae That's it :) I reviewed your list and put the last missing in [here](https://drive.google.com/drive/u/0/folders/1NOPwZK58YNioRKjhi3Q6UkLTq7CFRzSa)
Check list is updated here as well : https://docs.google.com/document/d/1jBJ3kBS8n4PTsq2NqFWIvtuZwcUL4WTGM8LJEv6iCEE/edit
