### ISSUE TITLE
Style builder updates

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4490]

**Comment by stephanie-cascade8** [comment]
The list I'm corruntly working on 
[](https://docs.google.com/document/d/1iNyhfBZOPfMlRgAow11401khz0P30TBcMRe6YWeMzrQ/edit)

**Comment by phpgeekfr** [comment]
While reviewing this PR https://github.com/blockframes/blockframes/pull/5500 , @Mussuranae suggested that `styles/style.scss` should be cleaned.

For example : 
```
main {
  height: 100%;
}
```
should be updated with `min-height: 100vh`
