### ISSUE TITLE
Merge Invited user's credentials emails

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4510]
Currently we have one email per app. It should be merged into one

**Comment by fritzschoff** [comment]
with the new connection flow we will have this sorted out, no? @Jackseed close this issue in favor of new connection flow?

**Comment by Jackseed** [comment]
No that's really a sendgrid issue. For now we have
- welcome to MF
- welcome to AM
- welcome to AC
While we should have "Welcome to {{app.name}}".
There is a bit to change to add an app.description but it's an open issue we need to work on, different than new connexion flow

**Comment by Mussuranae** [comment]
Last thing to do !
- add the description text inside the appMailSetting.description
- Remove old and unused template of mail in Sendgrid

See TODO in code

**Comment by Mussuranae** [comment]
@Jackseed I think if you provide us the description text, we can close this issue as you have access to the app object now in Sendgrid template (reminder of the app mail object : `app.name`, `app.logo`, `app.description`, `app.url`)
