### ISSUE TITLE
Cleaning script - check for duplicate on org userIds

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4523]
We had an org on prod that had multiple times the same userId listed on userIds. This created duplicated notifications. Duplicates have been manually removed but a check on the clean script to avoid this scenario to happen again would be good

**Comment by phpgeekfr** [comment]
We should also clean this in db-cleaning script along with a unit-test

**Comment by Mussuranae** [comment]
Is it done ? If no, we can maybe use the [...new Set(array)] to remove duplicate user ids from the organization.

**Comment by Jackseed** [comment]
Not to my knowledge, I cleaned prod db manually but I don't think a script handles that

**Comment by phpgeekfr** [comment]
maybe do the same for movie.orgIds
