### ISSUE TITLE
All titles Marketplace - Display issue

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4549]
- [ ] Ouch (Win10 x Firefox 83.0 (64-bit))

![image](https://user-images.githubusercontent.com/5858657/101617596-1b314180-3a11-11eb-88c5-06d8e87a5eb5.png)

_Originally posted by @pldespaigne in https://github.com/blockframes/blockframes/issues/4420#issuecomment-741679845_

@Remco can you confirm the state of that bug?

**Comment by RemcoSimonides** [comment]
Fixed
