### ISSUE TITLE
Festival homepage marketplace - Missing featured sales agents on Safari

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4555]
It works on Brave but not Safari

![Don't miss anything on Archipel Market.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/313507f4-0c15-43fe-a843-92becb6b26e1)

**Comment by phpgeekfr** [comment]
Safari 14:
![image](https://user-images.githubusercontent.com/1194344/102326999-643f4380-3f85-11eb-8db6-73c2396254be.png)

Safari 13.1
![image](https://user-images.githubusercontent.com/1194344/102327145-92bd1e80-3f85-11eb-9dcf-89ba174c5467.png)

Safari 12.1 
![image](https://user-images.githubusercontent.com/1194344/102327220-b41e0a80-3f85-11eb-944f-461c3125b0fa.png)

@Jackseed What is your Safari version ?

**Comment by Jackseed** [comment]
@phpgeekfr 14.0.1
