### ISSUE TITLE
Change huge sentence to "Pending" 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4557]
Alright so I've no idea where this sentence comes from but it's way too big and the status "Pending" was enough. It's still on some use case, please replace it everywhere on list or pages except on snackbar

![Your request has been sent to the.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/cdb734e4-a348-4242-88ca-0ece4eec6b90)

**Comment by phpgeekfr** [comment]
FROM 
![image](https://user-images.githubusercontent.com/1194344/102338129-b9825180-3f93-11eb-93cd-5c88cbde6914.png)

TO

![image](https://user-images.githubusercontent.com/1194344/102338318-fa7a6600-3f93-11eb-9adc-7760bf614146.png)
----------------------

FROM
![image](https://user-images.githubusercontent.com/1194344/102338706-7d9bbc00-3f94-11eb-87fc-5c7da4dbde74.png)

TO 

![image](https://user-images.githubusercontent.com/1194344/102338662-71affa00-3f94-11eb-8a8a-e70e3f910508.png)

**Comment by phpgeekfr** [comment]
i added a snackbar when user clicks on "Ask for Invitation"  with message `Your request has been sent to the organizer. We're waiting for them to let you in`

**Comment by phpgeekfr** [comment]
I shorted the message in snackbar  to : `Your request has been sent to the organizer.`  to prevent display on two lignes for small screens
