### ISSUE TITLE
MF - Movie view marketplace - Open discussion modale doesn't work

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4559]
I got an error message when trying to send a message to partner through the open discussion dialog

![Open discussion.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/3aad9b99-3a02-4ba8-9b2d-614f67cf997b)

**Comment by fritzschoff** [comment]
closing due to @Mussuranae PR merged
