### ISSUE TITLE
Homogenize modales & update texts 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4599]
We currently have 2 different dialogs on the apps and we should have only one. Texts should be also updated to have a more direct approach.

**Comment by 2amarkina** [comment]
Here is the [notion article about the modals](https://www.notion.so/cascade8/Modals-0c8d7ccd3bab4c1c904da5c4b8aa48e4)

Here is [work in progress for modals inventory ](https://docs.google.com/spreadsheets/d/1N06uryQf5J7g56kyenJgpZ_HtiXmYb_Evf798E4fwsY/edit#gid=0)

**Comment by RemcoSimonides** [comment]
Changed a lot of modals in the last release. They should all be the same now :)
