### ISSUE TITLE
Firebase CLI : Update to v9.1.0 from 8.4.3

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4627]
Update firebase CLI to v9.1.0

![image](https://user-images.githubusercontent.com/8731418/103084879-1de18880-4606-11eb-9076-3b0a701472d8.png)

It has better emulator auth support.

[ ]  Verify Unit-Tests work fine
[ ] Anything related with devops tools (TBD)

**Comment by xmano** [comment]
@george43g - do you have any items to test for this change?

I would like to make sure there is no breakage due to this move.

**Comment by george43g** [comment]
I'm almost certain that there won't be, however, I think it's better to do the upgrade because I'm working on a PR now that should be made to work with latest version rather than the current one

**Comment by xmano** [comment]
Tools have a newer release. We might as well update to this. Checking with this:

![image](https://user-images.githubusercontent.com/8731418/105007066-854ff400-5a5d-11eb-99cf-9a9123aaaaae.png)

**Comment by xmano** [comment]
The unit-test results are similar to with 8.4.3

![image](https://user-images.githubusercontent.com/8731418/105012405-1fb33600-5a64-11eb-9b6a-b8288089eba6.png)

![image](https://user-images.githubusercontent.com/8731418/105012416-22ae2680-5a64-11eb-9edd-2c2b90838219.png)

**Comment by xmano** [comment]
Closing this issue as another PR addresses it:

https://github.com/blockframes/blockframes/pull/4752
