### ISSUE TITLE
Firefox: Wrong image size in the movie-card in the movie-list

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#4647]
@RemcoSimonides worked on that during the release in december '19

**Comment by RemcoSimonides** [comment]
It's still there?

**Comment by fritzschoff** [comment]
I knew that we didn't merge the PR you made for the release, so I add this issue to keep a ref. But if it fixed, pls close this issue

**Comment by RemcoSimonides** [comment]
Alright; I did merge it after the release ;)
