### ISSUE TITLE
windows, chrome. Browser settings could prevent user from sharing file in meeting

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#4648]
@ybossenmeyer had an issue with a production meeting shared video: she saw a static thumbnail when everybody else could watch the video

**Comment by pldespaigne** [comment]
I will need more info to be able to reproduce

**Comment by Jackseed** [comment]
New test planned for tomorrow, let's see if we have more info

**Comment by pldespaigne** [comment]
We fixed some bug that could be related to this, I'm closing for now.
Feel free to re-open or create a new issue with clear steps to reproduce if the bug persists.
