### ISSUE TITLE
SEO (search engine optimization)

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#4654]
some SEO tweaks should be done like:

- [ ] 301 redirections to main domains
- [ ] robots.txt & sitemap.xml files
- [x] meta title and meta desc for at least homepage :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/f538c55d-03c7-4d44-a557-e47f7890f9ef)

- [ ] JSON-LD
- [ ]  cannonical

**Comment by phpgeekfr** [comment]
Basic robots.txt files implemented in https://github.com/blockframes/blockframes/issues/2296

**Comment by phpgeekfr** [comment]
better now ;) 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/705532f3-3e0f-4bab-9af6-f5b47cb2c95d)

**Comment by Jackseed** [comment]
@phpgeekfr do you need some business info for the other tick boxes?

**Comment by phpgeekfr** [comment]
@Jackseed no, or not yet. We need to check this on technical side first

**Comment by Jackseed** [comment]
@phpgeekfr you closed it but checkboxes are unchecked: is the issue really done or outdated?

**Comment by phpgeekfr** [comment]
I closed it because it was outdated, but 301 redirections to main domain have been done.
