### ISSUE TITLE
Bug - Update Sales pitch UI

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4680]
_Marketplace movie view_

Current sales pitch doesn't respect designs:
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/feee384a-08fa-46b2-ad40-8cbacde32565)
vs [Zeplin](https://app.zeplin.io/project/5fa1637022e6a88784fbb052/screen/5fa17fb5f154286c7a445c14)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/e2cef9a9-f95e-48f8-b46a-2b2a6e0a3e5f)

**Comment by fritzschoff** [comment]
I would say, the design is not respecting the code. Cause we are using the summary components from the tunnel here. If you want to change it, it would require a new component
