### ISSUE TITLE
Screeners : Dev overview

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#4681]
This issue is for listing and discussing the new Screeners feature from a dev point of view.
The higher level (business/design) issue about Screeners can be found here : #4040 

---
- [ ] need more info about analytics : what is mandatory to have, what are the limitations, what lib to use, what are RGPD implication for "unknown" user who comes on the screeners ? How to store and display the data to sellers ?
---
- [ ] `movie.promotional.videos` refactoring to merge `screening` & `otherVideo` into a single array
- [ ] movie form > video : refactoring according to the new data model ☝️ 
- [ ] create event form refactoring: event generic tabs / specific tabs
- [ ] even if not really related to screeners, we where also talking about letting users upload banner for their org, we could then use the org banner in the screener view
---
- [ ] create a new data model sub-type for events & invitations to handle Screeners
- [ ] refactor the player & corresponding backend to handle configurable watermarks
- [ ] implement the new create event screener form
- [ ] implement the back & front needed for the screeners views

**Comment by fritzschoff** [comment]
@Jackseed can we close this because we don't go for screeners?

**Comment by Jackseed** [comment]
let's icebox it it will be useful at some point
