### ISSUE TITLE
Update Notion

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4688]
### Description
Following @xmano advice, we'll adopt a new architecture for Notion. The objective is to respect that architecture for better documentation and facilitate the maintenance through time. 
We should benefit from current cleanup time to update a lot Notion and add at least links to existing documentation, if not create from scratch articles. 

### New architecture
```
Apps 
  o Cross-app
    - Features
       1. User
           - Creation
               > User scenario
               > Designs 
               > Engineering
...
  o Festival 
    - Features
       1. Event
...

Process
  o DevOps 
  o Testing 
Conventions
  o Documentation 
     - Structure
  o Dev
     - Coding Guidelines (Structure, Naming,)
  o Design
     - Tool
```

### What to do
1. First implement the new architecture and re-order existing folders and articles to respect it. I created the corresponding folders for app features but the process & conventions part still need to be updated. 

2. Assign yourself to parts you feel confident with and look at the doc to update or create it. This may include:
- removing obsolete stuff
- adding links to existing documents outside of Notion
- writing new stuff

=> To assign yourself just comment this ticket with the name of the part you're working on to avoid duplicates

**Comment by xmano** [comment]
I will work on Quality Assurance section. 

Inside Notion Wiki, I will add a note about updating this wiki itself.

**Comment by Jackseed** [comment]
Too old an issue and structure has been changed
