### ISSUE TITLE
Store structured analytics data into Firestore

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#4693]
Create a schedule functions to get the analytics every **day**, process them & upload them to firestore.
On the frontend, call the analytics collection instead of the callable function.

**Comment by fritzschoff** [comment]
ref #4677

**Comment by fritzschoff** [comment]
1. Getting the data from bigQuery every day.
2. What data structure? maybe new collection? stats/analytics?

**Comment by fritzschoff** [comment]
![image](https://user-images.githubusercontent.com/39312833/104027693-0be81400-51c8-11eb-9143-09477c1bff0c.png)

**Comment by fritzschoff** [comment]
![image](https://user-images.githubusercontent.com/39312833/104028009-7ac56d00-51c8-11eb-82da-ffbe1365015b.png)
