### ISSUE TITLE
Live stat for sellers

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#4695]
For realtime stat we should store & aggregate them directly into Firestore: 

Stat to store:
- event: amount of user / org that have seen the event page
- movie: amount of user/ org that have seen the movie page

Example of structure: 
```typescript
interface Stat {
  ownerId: string; // Id of the organization which has access to these stat
}

interface MovieStat extends {
  movieId: string;
  views: { [uid: string]: number }
  ...
}
```

**Comment by Jackseed** [comment]
@RemcoSimonides I think that's what you did but could you confirm and close?

**Comment by RemcoSimonides** [comment]
Ye, we can see this of any page because we save all page navigation in Analytics. So we have the data, we just don't have a place to view it yet. For that I'd need to create dashboards for movie and event too
