### ISSUE TITLE
Video upload - Add .mov files on the accepted media list

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4701]
In fact let's copy the accepted media list from JW Player:
.3gp
.avi
.mov
.mp4
.flv
.wmv
https://support.jwplayer.com/articles/preparing-videos-for-upload
And keep .mkv that works already

**Comment by RemcoSimonides** [comment]
Unable to create storage security rules for .flv files as it isn't recognized by the types supported by Google https://www.iana.org/assignments/media-types/media-types.xhtml
