### ISSUE TITLE
Enable Unit test for PR

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#4706]
When ever a PR is opened up, we need the CI to run the (affected) unit test

**Comment by xmano** [comment]
Jest config issue in Nx 11 workspace is now fixed. 

The new test respect the "Nx way" of running the tests.

```
nx test app
```

I think we can now enable unit-tests on CI.

There are some failing unit-tests that we need to fix.

**Comment by xmano** [comment]
Investigating this for the right nx command:

![image](https://user-images.githubusercontent.com/8731418/105483594-17f7c980-5cd0-11eb-8256-c7499bb4e23b.png)

![image](https://user-images.githubusercontent.com/8731418/105483620-20e89b00-5cd0-11eb-8672-b1b90d1aef0a.png)

Seems to work but want to make sure the right approach.
