### ISSUE TITLE
Clean update to Nx 11

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4709]
TODOs:
- [x] Move to new workspace generated by Nx 11
- [-] Migrate to ES Lint (Dropped) 
- [x] Use latest Jest 26
- [x] Use Cypress 6.2.1 - Updated for 6.8.0
- [ ] Remove express from config

Tests:
- [x] Jest unit-test run on local and CI with command line 
- [-] Lint rules are properly migrated  (ES Lint migration is deferred)
- [x] Cypress E2E runs fine
- [x] Firebase emulator works
- [x] App functionality test

CI:
- [x] Supports CI CLI tools

## Cleanup warnings

1. firebase-utils
2.

**Comment by GrandSchtroumpf** [comment]
Should work on windows, Linux, Max, CI.

**Comment by fritzschoff** [comment]
@xmano can we close this issue?

**Comment by xmano** [comment]
I had planned several tasks with this issue. Will need more time to close this due to various stuff involved and testing needed.

Also high priority issues on hand. So have to keep this on hold.

**Comment by fritzschoff** [comment]
alright

**Comment by xmano** [comment]
Unit-Test, E2E and firebase utilities are working cross-platform. 

CI configs are stable and working fine.

**Comment by xmano** [comment]
All process related stuff are working fine.

Unit-Test and E2E configs are now fixed. The last issue with unit-test will be fixed with:
https://github.com/blockframes/blockframes/pull/5483
Refer:
libs/firebase-utils/src/lib/util.spec.ts

**Comment by xmano** [comment]
Main config issues related with tools for Nx 11 are solved. I am going to close this Issue confirmed by some devs.
