### ISSUE TITLE
Sendgrid - Include unsubscribe link directly in email core

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4710]
Currently Unsubscribe link is added on the footer email through Subscription tracking (https://app.sendgrid.com/settings/tracking). This way we can't change text format and adapt it with our template. 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/f7968a69-cf14-4df5-8210-63cfed9524a7)

Instead, we should use their replacement tag that should enable use to include an unsubscribe link directly in our template. I tried to do it without success, would be good that a dev tries it. 

/!\ Be careful when touching unsubscribe settings as it's currently used on prod. Best would be to test with another Sendgrid account.

**Comment by Jackseed** [comment]
This will be removed with notification settings so don't bother work on it

**Comment by phpgeekfr** [comment]
> This will be removed with notification settings so don't bother work on it

I think this is still needed since we will now have a link to unsubscribe on sendgrid side and a link to update user's settings  on the app side

**Comment by Jackseed** [comment]
100% right, still valid issue
