### ISSUE TITLE
Uploader problem

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#4713]
N.B. Referring to the discussion in @design. 

The uploader shows that a document exists only when clicking on "browse" or other element. 

- [ ] Video uploader in Movie_Tunnel
- [ ] Document uploader in Movie Tunnel 
- [ ] Video Uploader in Files Manager 
- [ ] Document Uploader in Files Manager 

Bug presentation movie tunnel side: 
![movie tunnel.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/53e945db-cf33-4fbb-8b88-d1c846d6f3a3)

Bug presentation Files Manager: 
![my files.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/079c7653-d280-45cc-898b-11e63cc6ebeb)

**Comment by pldespaigne** [comment]
@SamirTouira becareful with this issue.
@GrandSchtroumpf and I are about to change the whole file architecture

**Comment by SamirTouira** [comment]
> @SamirTouira becareful with this issue.
> @GrandSchtroumpf and I are about to change the whole file architecture

Ok thank you for telling me, indeed @phpgeekfr talked a bit about this to me 

then what can I do with this issue ? Should I just wait for the moment ?

**Comment by pldespaigne** [comment]
After discussing on Slack we decided to wait before fixing this issue, because the Media Cleaning sprint will probably tackle it.
However it's better to let the issue open as a reminder to check if the bug still exists at the end of the sprint.

**Comment by pldespaigne** [comment]
This should be fixed now
