### ISSUE TITLE
draft of refused movies are still accessible by their URL

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#4716]
`/c/o/marketplace/title/MOVIEID/main` is still accessible even if movie is not in 'accepted' status.

Users should be redirect to movie list. And maybe update rules to prevent user that is not related to movie (movie.orgIds) to access a movie document if not in good status.

**Comment by phpgeekfr** [comment]
rules example:

```
allow read: if userHasValidOrg() && notInMaintenance() && ( existingData().storeConfig.status == 'accepted' || isAllowedToUpdateMovie() );
```

**Comment by phpgeekfr** [comment]
and maybe add a new rules test

**Comment by RemcoSimonides** [comment]
Adding the rule also prevents being able to access the data in the `MovieGuard` and therefore can't redirect the user to somewhere else. However, because the data can't be read on the page, the user is already automatically redirected to somewhere else (homepage)

What do you mean with 'adding a new rules test'?

**Comment by RemcoSimonides** [comment]
Also, there is a button on dashboard/title/_titleId_ that says 'See on the marketplace' also for movie in draft. This should be removed if we can't access it anymore in marketplace

**Comment by phpgeekfr** [comment]
> Also, there is a button on dashboard/title/_titleId_ that says 'See on the marketplace' also for movie in draft. This should be removed if we can't access it anymore in marketplace

Since you are in dashboard, you are listing movies that you own.  Owners of movies should still have buttons and should still be able to display movie in marketplace to check what it will look like before publishing it (a bonus would be to display a "draft" flag).

So for me, if you are owner of movie, you can access it from everywhere even if in draft. If you are not owner, if you attempt to access draft movie by url, you are redirected.

@Jackseed can you confirm?

**Comment by phpgeekfr** [comment]
> What do you mean with 'adding a new rules test'?

We have unit tests for firestore rules. So we can have a new test to check if org owners can read a movie even if in draft and another one to test if regular user cannot read it.

**Comment by Jackseed** [comment]
@phpgeekfr exactly, that's really useful for now to be able to access marketplace movie view even in draft for sales agents. Though no one else should be able to access it as it's draft. 

To be honest this stuff is kind of a workaround to maintain the "See on the marketplace" button working. There is an ongoing discussion with @GrandSchtroumpf to think of better structure/solution for dashboard users visiting the marketplace but in the meantime the rules proposed by Bruce is the good workaround.

**Comment by phpgeekfr** [comment]
@RemcoSimonides can we close now ?
