### ISSUE TITLE
Prod bug - Sales pitch video not loading

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4723]
Sales pitch video should be public, so accessible to all connected users. Here it loads indefinitely with the error "You are not authorized to see this video".
![image](https://user-images.githubusercontent.com/14964443/104441455-0148c880-5594-11eb-8ef2-7ebc34898f3c.png)

MovieId: `c8e3k3RhlE1oQK2RWMJ3`
Sentry error: https://sentry.io/organizations/cascade-8/issues/2135165446/?project=1540126&referrer=slack
Page: https://www.archipelmarket.com/c/o/marketplace/title/c8e3k3RhlE1oQK2RWMJ3/main

**Comment by RemcoSimonides** [comment]
Fixed by Bruce 🥳
