### ISSUE TITLE
Bug - Movie banner carousel on homepage 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4724]
We have 2 bugs here:
1. Banner doesn't take the full width while it should. What's weird is that for now we have 2 movie banner carousel and the screen width from which it's not full anymore differ from one another
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/f8bf8f85-fb5c-4ffa-b6bd-2be12f3e6b4e)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/703aa73b-866f-404d-b662-9e862e2ba33b)

2. This carousel should not display arrows when there is only one film on the carousel

**Comment by fritzschoff** [comment]
Found this text from @GrandSchtroumpf 
```
After another discussion with Stéphanie here is the current solution :
Keep the current ratio for movie-card & slider (if ratio is ok for slider).
Create a new image for header of the movie with a prefect ratio
Remove content from the header for movie view for smaller screen to keep good ratio
This means that :
User will have to upload another image for movie header.
We need to fallback to something else while they are doing that (I don't think we can use the current ratio else, people might never update to the new version).
We'll need to spend some time creating the right media queries.
```

**Comment by RemcoSimonides** [comment]
Did only the 2nd point mentioned. 
The first one is caused by old banners?

**Comment by Jackseed** [comment]
The discussion @fritzschoff quoted is linked to the banner used on marketplace movie view. But as it's said, we'll keep the current banner image for carousels so this issue is still relevant and we should correct it
