### ISSUE TITLE
Movie card | banner | view | poster - Add production countries ISO A2 ref

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4729]
Production countries is an important info that is currently not displayed in the 'small' movie views but it should. 
As we don't have that much place we will use the country ISO A2 code (`territoriesISOA2` in static-model.ts). 

This info has to be displayed on 4 different places:
1. Movie card
- 2nd position, after genres and before langages
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/9da93b3c-2e87-4412-9788-f3a6ec86e9f2)

2. Movie view - banner
- 3rd position after duration, before langage
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/7c30f549-4f4d-4784-90fd-606c70e78914)

3. Carousel banner
- 3rd position after duration, before langage
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/e9e8354b-7a48-465d-9d82-6eb9b0801d9b)

4. Poster card
- 2nd position, after genres and before langages
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/17d74650-b7da-43d8-9d06-16f807d9f161)

Each time we should use the ISOA2 code and display no more than 2 countries, if more add ",..." as the others parameters

**Comment by RemcoSimonides** [comment]
Are you sure it will be clear for the user what is meant with this information?
![image](https://user-images.githubusercontent.com/27687382/104574733-a9bf6100-5656-11eb-82f5-8b80142c6abe.png)

**Comment by RemcoSimonides** [comment]
For the posters on the movie list page, the data comes from Algolia. Algolia does not contain this information. Recommendation is not to add this data since it will increase the size of the objects and it won't be used for queries.

**Comment by Jackseed** [comment]
Thanks for the screenshot. We definitely go on with the change for cards & banners and we'll follow your advice by not displaying ISO code on posters.
