### ISSUE TITLE
Video Thumbnail 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4737]
Implementation went super fast and we now have promotional videos uploaded and screened directly in-app! The only missing thing is the video thumbnail. For now it's a black screen with watermark that is used. 

Some research and test have already been done for thumbnails so we should now validate wireframes and go to UI before implementation. 

2 possibilities here:
1. User uploads its own image
2. User chooses one from the video

The first one is something we already know how to do so it can be really quick to implement. The second one would use JWPlayer API so we have more uncertainty here. 

Depending on implementation difficulty we shall go for 1st possibility asap and then implement the 2nd one or do both at once if that's doable.
Wireframes should reflect these 2 possibilities.

**Comment by pldespaigne** [comment]
Both solution will use JWPlayer APi and none of them will be "really quick to implement".

For now it's not just a black screen, it took the 10th second of the video as the default video Thumbnail.

Note for the design : It's only possible to set the thumbnail **after** the video has been uploaded & processed by JW

**Comment by pldespaigne** [comment]
Note about solution 2:

The way it works is by saying to JWPlayer "use the 142th second as the thumbnail".
So that means that we need a way to show to the user what image correspond to the 142th second, and I think that will be really hard to implement.

**Comment by 2amarkina** [comment]
[Wireframes here ](https://www.figma.com/file/RtccIK1tfaiusFmtLBrJsF/%5B-Video-Thumbnail-%5D?node-id=0%3A1)

**Comment by 2amarkina** [comment]
**TO DO:** 

- [ ] Check and update the[ already proposed upload box solutions ](https://www.figma.com/file/Hlqmog9lrajjquJoXi18w6/%5B-Uploading-System-%5D?node-id=0%3A1)

- [ ] Find a solution to keep the same component in MovieTunnel and in My Files. Make the actions happen directly on the page. 

- [ ] Check if behavior is ok with the player
