### ISSUE TITLE
Refactor storeConfig.appAccess & storeConfig.status

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4738]
Currently when a movie is `storeConfig.status === accepted` it concerns all apps. It shouldn't as movies could have different status depending on the app. 

StoreConfig status should be modified to handle that use case:
- Movie is accepted on festival
- Movie is draft on catalog

When the status is changed it should also impact the validatedAt parameter yet to be created (#4732)

**Comment by Mussuranae** [comment]
We have already a `appAccess` on the `movie.storeConfig` to allow the movie on each app. We can maybe use it and register on the `acceptedAt` the date when the `appAccess` turn `true`.
Otherwise, we delete it and merge both `appAccess` and `status` together.

**Comment by Jackseed** [comment]
I must say my issue was a suggestion but I guess final word should be discussed with @phpgeekfr and/or @GrandSchtroumpf.
Business objective: be able to have a title that is `accepted` in one app and `draft` on another

**Comment by GrandSchtroumpf** [comment]
There are many issues here.

1. Each app can have a set of status which is different. For example `submitted` is not on archipel market. So the first step would be a defined what are the **final** list of status so we can define a generic way of doing.
2. The `storeConfig` manages the `storeType` data. Is it also app specific ? Else we would remove it from `storeConfig`
3. If there any other data that we want to be different between apps ?

Concerning the data model there are two options: 
- sub-object: `movie.app[appName]`
- sub-collection: `movies/{movieId}/apps/{appName}`

The sub-object seems to be a better option for query & rules.

In any case we need to define what data are app specific and we put them there.

**Comment by Jackseed** [comment]
> 1. Each app can have a set of status which is different. For example `submitted` is not on archipel market. So the first step would be a defined what are the **final** list of status so we can define a generic way of doing.
The status name displayed to users is being discussed right now but on a technical point of view we have the final list:
- draft
- submitted
- accepted
- refused
Based on that list we have 2 scenarios depending on the app:
1. 'Direct process': Title goes directly from `draft` to `accepted`
2. 'Validation process': Title goes from `draft` to `submitted` and admins may change this status to `accepted` or `refused` 

> 2. The `storeConfig` manages the `storeType` data. Is it also app specific ? Else we would remove it from `storeConfig`
For now every apps have the dashboard / marketplace sections but I can't say for sure it will stay as it is for the new ones.

Also please bear in mind that issue when thinking of a new data model https://github.com/blockframes/blockframes/issues/4732

**Comment by GrandSchtroumpf** [comment]
> For now every apps have the dashboard / marketplace

The `storeType` is something like "line-up". Should it be the same for all apps ?

If not, we could have something like : 
```typescript
interface Movie {
  ...
  storeType: 'line-up' | '...';
  app: {
    [name: AppName]: {
      status: 'draft' | 'submitted' | 'accepted' | 'declined';
      acceptedAt?: Date;
      declinedAt?: Date;
      ...otherAppSpecificInfoGoesHere
    }
  }
}
```

**Comment by Jackseed** [comment]
Oh my bad, `storeType` isn't used anymore so we can remove it. If it ever comes back with the same purpose it would in fact mean do we show the movie in Archipel Content or in Archipel Market
