### ISSUE TITLE
Fix twilio unit test

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4740]
Twilio unit tests need to be refactored to work with new nx 11 new configs.

![image](https://user-images.githubusercontent.com/8731418/104591320-80bcc180-5692-11eb-8376-276a791916eb.png)

**Comment by phpgeekfr** [comment]
should be fixed by #4678

**Comment by xmano** [comment]
Along with twilio env vars we would need to setTimeout

![image](https://user-images.githubusercontent.com/8731418/105463103-94c97a00-5cb5-11eb-960f-91352e2e3977.png)
