### ISSUE TITLE
Small offset issue on carousel

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#4759]
The offset grows 1/3 of a pixel per slide
For bigger screens it's on the left side, for smaller screens it's on the right side

See green line at left side of image. This is at slide 20 but you can already see a small line at slide 2
![image](https://user-images.githubusercontent.com/27687382/104752561-1d489780-5757-11eb-9e62-2646fe446182.png)

**Comment by fritzschoff** [comment]
just tried it and I couldn't reproduce the bug. Added like 25 movies to the array but never got something off. Maybe this was because of different cropped images? 
@RemcoSimonides if it is okay for you, I would close it

**Comment by RemcoSimonides** [comment]
That's good to hear. It's minor anyway so yea let's close it :)
