### ISSUE TITLE
Notification - new movie published not created

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4761]
On staging - develop from last Friday - notification `[ Title name ] was successfully published on the Marketplace.` for movies with `storeConfig.status` changed to `accepted` is not created. 

I tested with 2 movies created with dev+kenneth-ixf@blockframes.io (member) and dev+camilla-swf@blockframes.io (super admin)
https://staging.archipelmarket.com/c/o/dashboard/title/zOCXD3jCUdfRxwxxQCpD/main

This error spawned on Sentry https://sentry.io/organizations/cascade-8/issues/2161751276/?project=1540126&referrer=slack

**Comment by Jackseed** [comment]
This bug looks as related to another https://github.com/blockframes/blockframes/issues/4764

**Comment by phpgeekfr** [comment]
Indeed, #4764 may fix this. Also, for the notification to be triggered, movie status must change from `draft` or `submitted` to `accepted`. It will not trigger if status changed from `rejected` to `accepted` for example

**Comment by SamirTouira** [comment]
after testing, the notification is automatically sent now when the movie is published in the market place, because after have click on this button, the status `draft` is now `accepted` in Archipel Market
