### ISSUE TITLE
Public org page line-up not complete

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4762]
URL: https://staging.archipelmarket.com/c/o/marketplace/organization/sLchj1Ib4Cxhwr0ZBW4m/title
https://staging.archipelmarket.com/c/o/dashboard/title
User: dev+camilla-swf@blockframes.io

Line-up shows 2 films while I got more than 20 accepted films on dashboard
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/5ab26f61-25c7-458b-863e-eef99b730a0a)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/40688eb9-ed5c-426f-aafd-51430bacf913)

This list is supposed to display: all movies that belong to the org that are accepted and linked to that application

**Comment by RemcoSimonides** [comment]
This is probably due to movies not having _meta.createdAt field yet
The query orders the movies by createdAt, but if the movie doesn't have this field yet, it's left out

**Comment by Jackseed** [comment]
Good catch it looks indeed linked to that. Do you know when the _meta.createdAt field has been added? 
As hotfix I would add that date to every movies that has no _meta.createdAt

**Comment by phpgeekfr** [comment]
_meta.createdAt was introduced few months ago. As you said, best way is to create a migration that adds the field. Which date should we use @Jackseed  ?

**Comment by RemcoSimonides** [comment]
Two options that came to my mind:
- Same date as when org was created
- Begin of the year of field `release.year`

**Comment by phpgeekfr** [comment]
Thanks, I will go with same as org.
