### ISSUE TITLE
Screening session - UI bugs

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4769]
Spinner & error message + illustration should be centered both horizontally & vertically in the page
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/60f14e1c-dd66-4e27-9fa0-e6a7df77571b)![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/25f9f634-b7b3-4275-867c-ccbed603536d)

**Comment by RemcoSimonides** [comment]
Spinner seems to be horizontally aligned already. Can you check again @Jackseed? Closing for now

It sounds really easy to do but we can't center the loader vertically... Well, at least not with side effects in the footer
![image](https://user-images.githubusercontent.com/27687382/105062031-73c91500-5a7a-11eb-9b6a-72f1bfba1041.png)
