### ISSUE TITLE
Movie form - Festival premiere: uncheck an option

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4789]
URL: /c/o/dashboard/tunnel/movie/movieId/reviews
Section: Festival & awards

Currently there is no way to uncheck a Premiere clicked on the toggle button. User should be able to uncheck the option when clicking again on the active element. 
![image](https://user-images.githubusercontent.com/14964443/105166371-aecd5600-5b17-11eb-80cf-4a108eaf843d.png)

Related question: https://stackoverflow.com/questions/51282112/uncheck-active-angular-material-toggle-buttons-on-click

**Comment by phpgeekfr** [comment]
closing this since #4808 indicate that issue is fixed.
