### ISSUE TITLE
Re-implement default video screener with PFT

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4801]
Some weeks ago a default video has been implemented allowing every movies to have a screener uploaded by default so we may tests screenings without uploading a video or using real prod films. 
Now this video file spawn an error on screening. When uploading a new file everything works well so I guess it comes from a change in PFT script but can't say more

![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/e44dbed3-001b-4cd9-9ad2-7d3aa1b54d57)

**Comment by phpgeekfr** [comment]
```
function updateHostedVideo(screener: HostedVideo): HostedVideo {
  const jwPlayerId = 'Ek2LPn3W';
  return {
    ...screener,
    jwPlayerId
  }
}

function processMovie(movie: Movie): Movie {
  if (movie.promotional?.videos?.screener) {
    movie.promotional.videos.screener = updateHostedVideo(movie.promotional.videos.screener);
  }
  if (movie.promotional?.videos?.otherVideos) {
    movie.promotional.videos.otherVideos = movie.promotional.videos.otherVideos.map(updateHostedVideo);
  }
  return movie;
}

```
The id `Ek2LPn3W` has been removed from JW player dashboard so I guess that's why we have an error.

It looks like that id `sduHGGRk` is now the "test" video. @Jackseed can you confirm ? If yes, we just need to change this id in anon script

**Comment by Jackseed** [comment]
@phpgeekfr yes it's a correct test id we can go for it. Sorry for the delay...
