### ISSUE TITLE
Media - Add a warning for heavy files

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4814]
We have rules to prevent uploads for files that are too heavy but we don't warn users. 
@pldespaigne gave me these rules
```
// Only allow uploads of any image file that's less than 5MB
// Only allow uploads of any image file that's less than 50MB
// Only allow uploads of any video file that's less than 50GB
```
I tested for images and it's working for 10Mb files but not 15Mb files. 

I don't know exactly when we know the file size, depending on that we shall either use a validator or a snackbar saying: "Your file is too heavy, maximum size is {{maximumSize}}Mb"

**Comment by pldespaigne** [comment]
blocked by #4002
