### ISSUE TITLE
Analytics refactoring

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4815]
## Objectives
Analytics need refactoring with 3 objectives in mind:
- debug the existing stats for users
- speed up stats creation and loading for users
- start an admin dashboard with general analytics

## Battle plan
1. [Store on firebase users’ analytics](https://github.com/blockframes/blockframes/issues/4693) & [debug existing queries](https://github.com/blockframes/blockframes/issues/4677)
A list of analytics data displayed to users is [here](https://docs.google.com/spreadsheets/d/1VXZKbd1KPE7GPIjsFA_h6G-_xl166p1IJz58suzhoVQ/edit#gid=1148924705).
2. [Get firebase data on BIgQuery](https://github.com/blockframes/blockframes/issues/3772) to be able to join analytics to firebase 
- Start with users collection as a test
3. Create admin queries on BigQuery
- I'll add an issue with the most interesting stats for which we shall already have the data needed 
4. Create dashboard on Data Studio 
- Following #3 would help business side to look at that data, should be done with the few stats created above

**Nice to have:**

5. Implement Yandex Metrica for hit maps #3317 

6. Add parameters on page_view event
- Need to add `orgId` and `movieId` on some page view events to facilitate queries

7. Create new click events
- Some UX analysis need users' click monitoring, we should start first with a test on landing & sign up page

**Comment by RemcoSimonides** [comment]
To do:
- [ ] Combine intraday events table with the other table (scheduled query)
- [ ] Fetch data from Sendgrid

**Comment by phpgeekfr** [comment]
@RemcoSimonides The 3 issues of this epic are closed. Does it means that we can close this epic?

**Comment by RemcoSimonides** [comment]
@phpgeekfr No, not yet. What we have currently is the bare minimum. When there's some more time I can continue with this one.
