### ISSUE TITLE
Unit test for query movies list

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#4833]
Create a unit test to make this query :
```
return this.movieService.valueChanges(ref => ref
          .where('orgIds', 'array-contains', org.id)
          .where('storeConfig.status', '==', 'accepted')
          .where('storeConfig.appAccess.financiers', '==', true)
          .orderBy('_meta.createdAt', 'desc')
          )
````

Where org.id is not user's org. (CF `apps/financiers/financiers/src/app/marketplace/organization/title/title.component.ts`)

And another with (CF `fromOrg(`)
```
return this.movieService.valueChanges(ref => ref
          .where('orgIds', 'array-contains', org.id)
          )

````
Where org.id is the one user is connect with and with movies that are `accepted` or `draft`

**Comment by xmano** [comment]
For ref:

`$ nx test rules --test-file movie.spec.ts --skip-nx-cache`

![image](https://user-images.githubusercontent.com/8731418/144439110-90c45578-e929-4441-8300-f59cf970396e.png)
