### ISSUE TITLE
Theme discussion - Success color?

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4835]
Update of theme colours should be discussed before changing something here

**Comment by Jackseed** [comment]
I also add that comment from @jdrns 

> Should we keep "accepted" in blue? It looks clickable as it is the same colour as the links.
> ![image](https://user-images.githubusercontent.com/14964443/111998272-26216500-8b1c-11eb-8d4b-72646d073a9d.png)
>

**Comment by jdrns** [comment]
We won't go for a success colour but we will remove the primary for "accepted" and the warn for "declined" and change them to foreground 600 (typeface secondary text)

**Comment by RemcoSimonides** [comment]
Dev issue created ☝️
