### ISSUE TITLE
Secret events tests

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4840]
A new feature was speced here #4839. 
I can't say if unit tests are useful here but I think we can build on event e2e tests to add secret type test. 

### User scenario
1. Dashboard user with a film A and a screener file on it connects and creates a secret screening on film A

**Do the same as a private screening:** 

2. Invite 1 marketplace user, connects with invited marketplace user and check you can connect to session page, connects with not invited marketplace user and check you cannot connect to session page

**Specific to secret screening:**
3. Connect with a marketplace user go on screening list, verify that screening is not listed
4. Go on marketplace film view, screening tab and verify: 
- there are no screening listed
- no screening banner is here with "There is no screening scheduled at the moment. You can contact the organization for any questions."
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/12f09b33-8e3d-41b1-ab0d-79ed1043cfb7)

**Comment by RemcoSimonides** [comment]
In `apps\festival\festival-e2e\src\support\pages\dashboard\EventEditPage.ts` the `uncheckPrivate()` method needs to be updated after to support radio button

**Comment by phpgeekfr** [comment]
Maybe start with Unit testing first, there is some already but more can be added I think

**Comment by phpgeekfr** [comment]
linked to #7174

**Comment by phpgeekfr** [comment]
@n-germain-work In Notion list I see that these 2 points are in progress: 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/44798423-c404-4958-94bd-d489ed2ff41a)

Is it part of job done in #8220 (PR #8714) ?

**Comment by n-germain-work** [comment]
yes
