### ISSUE TITLE
Refactor the Download file feature

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#4868]
Currently the download file feature use ImgIx even for pdf & video, this seems like a bad practice.
Moreover the new file & upload architecture broke the download feature.

Refactor the download feature to use the firebase storage directly (we might need a backedn function that generate firebase storage token)

Look in the code for `// TODO issue#4868` to find where this need to be done.

**Comment by phpgeekfr** [comment]
There is no #4868 in the code anymore. can we close ?

**Comment by pldespaigne** [comment]
I think our in app download file process is not really working, but that's not high priority imo

**Comment by Jackseed** [comment]
@pldespaigne do you remember where download is broken? I tested it on every docs in the movie and it worked well
