### ISSUE TITLE
CRM - User page - Add invitation list(s)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4877]
For admin purposes it would help to have a list of all the pending invitations of a user (org invitations + event invitations). It should be on the user page. 

If that's easier to separate org invitations from event invitations and have 2 different tables/lists that's more than ok.

**Comment by GrandSchtroumpf** [comment]
We could have a generic query : 
```typescript
ref => ref.where('toUser.uid', '==', uid)
```
And then inject everything in a table with sorting on the type.
