### ISSUE TITLE
Issues for unit testing httpsCallable function  from Angular service.

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#4913]
With @SamirTouira we discovered several issues that prevent us to test httpsCallable function inside an Angular service:

When we start emulator, DB is empty so maintenanceMode check is broken and triggers are not working:
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/92999064-4381-43fa-a894-9e42c2135bb7)

We can tel functions to use emulator but we cannot customize projectId (for example I must use "blockframes-bruce" for the function call to work)

```
AngularFireModule.initializeApp({ projectId: 'blockframes-bruce' }),
```

Inside unit test, we are not logged in, so the httpsCallable on the backend side is crashing because it expects `context.auth.uid`:

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/16e8fa81-2c2b-410a-80f5-3d59143e75f6)

For now we skipped the test in `libs/consents/src/lib/+state/consents.service.spec.ts`, waiting for a solution.

**Comment by xmano** [comment]
Will have a look into this. See if the following link helps:
https://github.com/firebase/firebase-functions-test/issues/9#issuecomment-504735863

**Comment by phpgeekfr** [comment]
Another issue related to custom projectId: https://github.com/firebase/firebase-tools/issues/1960

(If I don't use blockframes-bruce I get a 404 error response)

**Comment by xmano** [comment]
Closed per PR
https://github.com/blockframes/blockframes/pull/5082

**Comment by phpgeekfr** [comment]
@xmano  do we need to create a new issue for testing createConsent function from backend-function ?

**Comment by xmano** [comment]
Yes
https://github.com/blockframes/blockframes/issues/5085
