### ISSUE TITLE
LinkFile is crashing when upsertWatermark is triggered

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#4916]
When a new user is created, we generate a watermark for him with `upsertWatermark` .
At watermark creation, `linkFile` backend-function is triggered and crash saying that file meta-data are incorrect.

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/54612bda-50bb-4479-929b-74b1ea99b258)

**Comment by RemcoSimonides** [comment]
Can't reproduce.
Tried regular sign-up flow and via event invite. Both ways I got the watermark without an error in the logs
