### ISSUE TITLE
Avails search tests

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4918]
Tests based on sales import: https://docs.google.com/spreadsheets/d/1KHKdN9HAzDUfbKaoSi6_OHxCjMsMd-vQh0VL_qKSKls/edit#gid=0

Avails search for movie Resurrected (`Cr3NYe9RXaMwP98LQMyD`)

1
- [x] Mandate test (territory)
Terms: 01/01/2022 - 06/30/2023
Territory: South Korea
Rights: Free TV
Exclusive: No

Expected result: Not licensed

2
- [x] Mandate test (terms)
Terms: 01/01/2028 - 06/30/2036
Territory: Afghanistan
Rights: Free TV
Exclusive: No

Expected result: Not licensed

3
- [x] Mandate test (rights)
Terms: 01/01/2022 - 06/30/2023
Territory: France
Rights: Planes
Exclusive: No

Expected result: Not licensed

4
- [x] Terms check (existing ended sale)
Terms: 01/01/2033 - 06/30/2033
Territory: Germany, Russia, Czech Republic
Rights: Free TV
Exclusive: Yes

Expected result:  Available 

5
- [x] Terms check (existing ongoing sale)
Terms: 01/01/2029 - 06/30/2031
Territory: Germany, Russia, Czech Republic
Rights: Free TV
Exclusive: Yes

Expected result:  Not available 

6
- [x] Cross territory check + exclusivity
Terms: 01/01/2022 - 06/30/2022
Territory: Germany, Russia, Czech Republic
Rights: Free TV
Exclusive: No

Expected result: Available

7
- [x] Cross territory check + exclusivity
Terms: 01/01/2022 - 06/30/2022
Territory: Germany, Russia, Czech Republic
Rights: Free TV
Exclusive: Yes

Expected result:  Not available 

8
- [x] Rights check
Terms: 01/01/2022 - 06/30/2022
Territory: Argentina
Rights: S-VOD
Exclusive: Yes

Expected result:  Available 

9
- [x] Rights check
Terms: 01/01/2022 - 06/30/2022
Territory: Argentina
Rights: Pay TV
Exclusive: Yes

Expected result:  Not available 

10
- [x] Exclusivity test (non exclusive)
Terms: 01/01/2022 - 06/30/2022
Territory: Germany
Rights: Free TV
Exclusive: No

Expected result:  Available 

11
- [x] Exclusivity test (exclusive)
Terms: 01/01/2020 - 06/30/2020
Territory: Canada
Rights: Free TV
Exclusive: Yes

Expected result:  Not available

**Comment by cams-goussale** [comment]
Modified Test #3: Terms were 01/01/2028 - 06/30/2036 ; changed to 01/01/2022 - 06/30/2023

>Mandate test (rights)
Terms: 01/01/2028 - 06/30/2036
Territory: France
Rights: Planes
Exclusive: No
Expected result: Not licensed
