### ISSUE TITLE
Implement minimal IAM policies for our firebase functions

### ISSUE THREAD

**Issue by lsenta** [blockframes/blockframes#492]
⚠️ this HAS to be done for November 1st.
We can stick to no auth, but this HAS to be configured explicitly.

https://cloud.google.com/functions/docs/securing/managing-access

https://cloud.google.com/functions/docs/securing/authenticating

**Comment by Jackseed** [comment]
will be really important/necessary when we go prod

**Comment by lsenta** [comment]
```
Note: The default behavior for HTTP functions will change after November 1, 2019. New HTTP functions created after this date will be private by default and you will need to specify that your function is publicly invokable during or after deployment.
```

Three common use cases for authentication include:

- Securing developer access so that only specific users can invoke the function during testing.
- Securing function-to-function access so that only authorized functions can invoke your function.
- Securing end-user access to an application from mobile or web clients.

**Comment by lsenta** [comment]
- Securing developer access: some training on how to configure function using the gcloud console for dev envs should be enough.
- Securing function-to-function access: no such case for now.
- Securing end-user access: we need to secure access to the admin function.

**Comment by lsenta** [comment]
Recommendation:
- [ ] update security on production to disable access to everyone but a few select members
- [ ] leave the rest as is and deal with security on a per-case basis. @Mussuranae has seen issues with firebase functions and backup restore that requires setting a few IAM, but this is a rare case that we'll document rather than over-engineer
- [ ] implements a user-based authentication in firebase admin, no need to IAM it'll be simpler to auth members as any app user.

**Comment by lsenta** [comment]
@Jackseed  ^ notes regarding security, please let me now if you have any questions, I'll move on with this plan and close the ticket.

**Comment by Jackseed** [comment]
@lsenta let's go for it, I'll PM you some rules for prod

**Comment by lsenta** [comment]
Admin page password merged to master,
IAM roles configured correctly on staging, @Jackseed to be tested by Marie & others before replicating to production
