### ISSUE TITLE
MF Consent modales

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4922]
### Description
 Two modales should be added for users to validate their consent: 
1. When submitting a movie on the movie form to acknowledge that they have the rights to share these information
2. When downloading financial documents on marketplace to acknowledge that it's confidential documents
Both acceptations should be saved and stored on the new consent collection. 

### UI 
[Wireframes](https://www.figma.com/file/x1s9SZZT2mts6kmBuIk9uU/MVP-Media-Financiers?node-id=1782%3A39)
We don't have zeplin component ready yet but here is an Invision [link](https://projects.invisionapp.com/d/#/console/19020838/444279771/preview) of a similar UI.
If it's possible I guess best is to re-use the component made in CRM app for delete movie or users 
![image](https://user-images.githubusercontent.com/14964443/107640495-a974ae80-6c72-11eb-9a29-7649628df8ff.png)

### Acceptance criteria

- [x] Marketplace movie view modale
![image](https://user-images.githubusercontent.com/14964443/107641300-bf36a380-6c73-11eb-878a-ad7f75613cd9.png)
- url: `https://www.mediafinanciers.com/c/o/dashboard/tunnel/movie/movieId/summary`
- text:
_Title:_ 
Confidentiality Reminder
_Sub paragraph:_ 
You are about to submit your project for publication. We kindly remind you that some of the information you're about to share might be confidential. 

By submitting your project, you assume the responsibility of disclosing all of the information previously filled out to potential future investors. Before submitting your project, please confirm by writing “I AGREE” in the field below.
_Input label_:
Confirm

CTA button: Accept
Cancel button: Cancel

- This modale should be visible only on Media Financiers when the user clicks on "Publish to Media Financiers"
- Accept button should be disabled until "I AGREE" is written in the input
- When clicking Cancel, the movie should stay on `draft` status and the user get back on the summary page
- When clicking Accept, the movie status should switch to `submitted` and the user redirected to the Thank you page
- Consent is saved in the new consent collection with timestamp, user first name, last name, email address and the movieId

- [x] Movie form modale
 ![image](https://user-images.githubusercontent.com/14964443/107641890-76cbb580-6c74-11eb-8a8e-d4fbf763fbd4.png)
- url: `https://www.mediafinanciers.com/c/o/marketplace/title/movieId/financial`
- text:
_Title:_ 
Confidentiality Reminder
_Sub paragraph:_ 
You are about to download a confidential document. 
Please make sure that you are aware of our **Confidentiality Policy** **[link to: https://www.mediafinanciers.com/c/o/marketplace/privacy]** before doing so.

To confirm that you agree with these terms, please write “I AGREE” in the field below. 

_Input label_:
Confirm

CTA button: Confirm and download
Cancel button: Cancel

- This modale should be visible only on the marketplace movie view when the user clicks on one of the 3 download buttons of the financial tab: Download estimated budget, financing plan or waterfall
- Confirm and download button should be disabled until "I AGREE" is written in the input
- When clicking Cancel, the download shouldn't be triggered and the user stays on the same page
- When clicking  Confirm and download, the download is triggered and user stays on the same page
- Consent is saved in the new consent collection with timestamp, user first name, last name, email address and a reference to the download document

**Comment by GrandSchtroumpf** [comment]
Might worth creating one (or more) Modal component with a list of params. Would be good to define these params before starting.

**Comment by SamirTouira** [comment]
Does it mean that should be better to creating a new component instead of re-use the modal component in CRM app if I understood correctly?

**Comment by SamirTouira** [comment]
@Jackseed when i'm going to the InVision link, it ask me some permission, can you please allow me to access it?
![image](https://user-images.githubusercontent.com/52285231/107658011-04fc6780-6c86-11eb-8f04-4840bacb7e14.png)

**Comment by GrandSchtroumpf** [comment]
We need one (or more) reusable component that we can use over all apps (crm included). If there is already a component for that, us it. But params need to be well defined so it work everywhere the same way.

**Comment by Jackseed** [comment]
I'm not sure if that's the params you want but different variables we've used so far for modals are:
- title
- text (could be 1 or 2 paragraphs with a line break)
- list (used for delete movie & users with a list of objects that will be deleted)
- buttons: 0 | 1 | 2 + text on button
- disabling a button (eg here if the input is not what we wanted)
- input to confirm the action (eg here "I CONFIRM")
- button actions (cancel | confirm)
- redirection links on buttons
- snackbars displayed depending on the action

**Comment by SamirTouira** [comment]
@stephanie-cascade8 @Jackseed do you have some Zeplin link for these images when you'll be available please? Or are there already an example somewhere? When I access to the old links it's not exactly the same and I don't have any informations about the properties css like colours, font size etc. 

![image](https://user-images.githubusercontent.com/52285231/113898886-8d9e0c80-97cc-11eb-8563-79951361e689.png)

![image](https://user-images.githubusercontent.com/52285231/113898911-94c51a80-97cc-11eb-966e-bcd823a0de7b.png)

**Comment by Jackseed** [comment]
@SamirTouira we don't have specific UI for that component, best is to use the same as when deleting an org or a user within the CRM App
![image](https://user-images.githubusercontent.com/14964443/113981231-b3b4c280-9847-11eb-831c-8053aeeeaf84.png)

**Comment by stephanie-cascade8** [comment]
> @stephanie-cascade8 @Jackseed do you have some Zeplin link for these images when you'll be available please? Or are there already an example somewhere? When I access to the old links it's not exactly the same and I don't have any informations about the properties css like colours, font size etc.
> 
> ![image](https://user-images.githubusercontent.com/52285231/113898886-8d9e0c80-97cc-11eb-8563-79951361e689.png)
> 
> ![image](https://user-images.githubusercontent.com/52285231/113898911-94c51a80-97cc-11eb-966e-bcd823a0de7b.png)

Hey @SamirTouira No zeplin for those screens but I can do them this afternoon or tomorrow. If it's more urgent tell me.

**Comment by phpgeekfr** [comment]
Does this issue needs to be opened again ?

**Comment by Jackseed** [comment]
I didn't test it but I thought it was done since it's closed... @SamirTouira ?

**Comment by SamirTouira** [comment]
Indeed I've completed the tasks requested. I think it just needs to be improved now
