### ISSUE TITLE
Remove sentry from backend functions

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#5011]
Sentry is used in the backend but no data are actually sent to sentry dashboard.
That means that error log are lost.

- [ ] remove sentry from `backend-functions`
- [ ] check that functions exceptions are logged correctly in firebase loggs

**Comment by xmano** [comment]
A possible solution could to be log both to Sentry as well firebase console.

I am exploring the possibilities and will implement something that makes debugging cloud functions easy.

There is something for AWS Lambda function
https://blog.sentry.io/2020/10/01/debug-errors-in-lambda-functions

Could check  option for Firestore

**Comment by phpgeekfr** [comment]
linked with #4014

> remove sentry from backend-functions

I would rename this to: Check how to improve sentry logger in backend functions.

**Comment by phpgeekfr** [comment]
linked to #5384

**Comment by phpgeekfr** [comment]
Errors are now correctly logged to sentry with projectId, location and region

![image](https://user-images.githubusercontent.com/1194344/115686629-b17b5980-a359-11eb-8a70-c4a782b7e301.png)
