### ISSUE TITLE
Release 2.2 Financiers & Festival & Content

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#5044]

**Comment by xmano** [comment]
Media related:

https://github.com/blockframes/blockframes/issues/5058

**Comment by phpgeekfr** [comment]
E2E test results from my local computer using chrome 89.
As @xmano said, there are intermittent failures but with some retries here are the results :

Catalog:
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/c24141b5-9751-4033-a082-8283a7aa3281)
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/5c4890f0-6b41-4728-add8-17e530341042)

Other tests on catalog are currently skipped.

Festival:

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/70fcfdec-f557-4ad6-92c8-cf17e1084374)
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/d490c944-08e3-4893-9173-29208aacf429)
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/805cefe8-56eb-4616-9ad4-61e75fc47020)

All green but sometimes algolia gives no response and some time firebase too
