### ISSUE TITLE
Dashboard analytics not loading on staging

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5056]
Dashboard homepage analytics are not loading correctly. If it's an env issue we may encounter the same on prod.
user: dev+kenneth-ixf@blockframes.io
url: https://staging.archipelmarket.com/c/o/dashboard/home
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/d2c514fd-35ec-403a-b304-8082e089cf46)

**Comment by RemcoSimonides** [comment]
@Jackseed the daily analytics import has not ran yet on staging. It runs once a day and I think it's around 10am Paris time. Is that an issue?

**Comment by Jackseed** [comment]
No it's ok if that's the issue, I keep that ticket open to check tomorrow if it's resolved

**Comment by Jackseed** [comment]
It's indeed loaded now
![image](https://user-images.githubusercontent.com/14964443/109786498-8011c780-7c0d-11eb-96ee-e34212e34ae4.png)
