### ISSUE TITLE
Upload widget not closing automatically after upload ended

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5058]
Steps to reproduce
- connect with dev+kenneth-ixf@blockframes.io
- go to https://staging.archipelmarket.com/c/o/dashboard/tunnel/movie/02L9gsoY4WTdGbxpOKha/media-videos#videos
- upload a screener video
- once finished the upload widget on the bottom left should close but it stays open
![image](https://user-images.githubusercontent.com/14964443/109773578-a892c500-7bff-11eb-8ba3-0a0e59fa5674.png)

**Comment by RemcoSimonides** [comment]
Should be fixed with the next media update release

**Comment by Jackseed** [comment]
ok thanks I keep it open and will close it when it's fixed with media branch being merged

**Comment by phpgeekfr** [comment]
seems fixed (tried with image upload) but check #5106 & #5105
