### ISSUE TITLE
remove sales / receipts from tables for AC

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#5060]
due to the new data model, we don't have these properties in these kind of shape anymore. Would need to be removed or comment out

**Comment by phpgeekfr** [comment]
@fritzschoff can you give an url example or a screenshot ?

**Comment by fritzschoff** [comment]
In the catalog dashboard my titles table, you got a column sales(gross sales receipt), which is not possible atm due to the state of the app. I briefed @SamirTouira

**Comment by SamirTouira** [comment]
issue still opened but I made a PR here: https://github.com/blockframes/blockframes/pull/5093 #5093 approved by Max but I don't know if we have to close this now. I prefer give this info to avoid unnecessary work on it

**Comment by fritzschoff** [comment]
sure thanks! If you want to close an issue with your PR, connect the PR to the issue, there is a button above the merge PR. Will close the issue now. Thanks !
