### ISSUE TITLE
Screening banner on marketplace movie page - Ongoing screening state

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5064]
We lack a state when the screening is happening. According to Marie, users tend to go to the movie view when they are looking for an ongoing screening.
There is the screening tab with screening event available but they may not understand it's clickable. 

Screening banner is available on every tabs so we could use to show a direct link to the event and/or add a sentence or label to indicate that screening is currently open. 

Currently that banner + CTA buttons has 2 states depending on whether the user is invited to the screening or not:
- enable when no invitation
- disable when already invited

![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/b37685ba-a965-4206-9862-d341c1ed8a4d)

This should be taken into account when designing this new flow

**Comment by 2amarkina** [comment]
[ongoing ](https://www.figma.com/file/YQ1InKhkvENsID48sPIUhh/Screening-Banner?node-id=0%3A1)

**Comment by Jackseed** [comment]
@2amarkina re the header I prefer the 1st option with banner since we could re-use what has been proposed for draft movies as well. 
What are the actions of this banner? is it clickable?
Re the Hero I prefer 1st or 2nd option (they are the same?) since the 3rd one prevent users from registering to other screenings

**Comment by 2amarkina** [comment]
@Jackseed yes, for the banner there is an action - it clicking on it leads to the event page (same for icon on the right side). Let's keep with 1st option as the "phare" one, but it also need to be seen on UI side, as we've got a come back button on the left and it shouldn't be overlaid by this banner. So, even if a banner is pretty thin, we could play with accent color. 

For the Hero, actually, here are different states (no other events to come, one or more other sessions to come etc.) So the 3rd, it's just the state when screening has started, but there are no upcoming sessions. 

Also need to check on UI level what exact button could we place as "Screening Ongoing" should be clickable. So for the moment I reflected two main versions: 
- Keep everything on a one line with more view is having "Screening Ongoing - Click here to access event" all phrase clickable 
- other solution is to play with colors and button forms to keep with only clickable "Screening Ongoing". 


Also discussed with Marie about other possibilities that we could have: 
- in a hero have a title "Screening Ongoing + CTA" (clear for buyer, but this can be heavy visually, and not sure that technically we can differentiate the prio of CTAs : if there is a screening ongoing, "go to event" becomes the main, if not "request access remains the main" ; 
- use banner "ongoing title" inside the poster + use it in a screening list (but it will cover some important info as logo festivals, not sure if possible technically)

These two I haven't reflected with wireframes yet.

**Comment by Jackseed** [comment]
@2amarkina could you highlight the phare versions in the wireframes please? I think we're good on a business perspective, devs need to review it now

**Comment by 2amarkina** [comment]
### Hero Section with ongoing screenings

1. **Case if screening ongoing, with no other upcoming sessions** 
![Снимок экрана 2021-05-31 в 15.00.17.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/f59b8ad7-0a39-41b1-9795-ef2577d4ca99)

2. **Case if NO screenings ongoing, with upcoming sessions, user has no access**
![Снимок экрана 2021-05-31 в 15.06.44.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/915c8f2c-be2a-4f24-a600-37b5064c054a)

3. **Case if screening ongoing, with one other upcoming sessions, user has no access to future screenings**
![Снимок экрана 2021-05-31 в 15.02.10.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/e6a7baf2-c899-48a6-89a8-2caebae1b719)

4. **Case if screening ongoing, with two other upcoming sessions, user has no access to future screenings**
![Снимок экрана 2021-05-31 в 15.03.22.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/5729f52c-ecbf-406f-8fa5-93109ebce00a)

5. **Case if NO screenings ongoing, but user has already applied for future session**
![Снимок экрана 2021-05-31 в 15.07.40.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/d3afd6e6-67de-482e-aff8-879447c9a739)

6. **Case with ongoing screening, with upcoming sessions, user has already applied**
![Снимок экрана 2021-05-31 в 15.08.46.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/66635eb2-fe3a-48d3-b418-bc48cdade967)

**Comment by 2amarkina** [comment]
### Screening List View 

Introduce a badge "Screening Ongoing" to make it more visible for a user
![Снимок экрана 2021-05-31 в 15.10.43.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/aee430c3-d98e-4c48-83ae-b8e557968c48)

**Comment by 2amarkina** [comment]
### Film Page

Show directly that a screening is ongoing. 
The best option for Business 

![Снимок экрана 2021-05-31 в 15.11.10.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/6b6af841-819e-478f-9c31-4c2725c11171)

**Actions**
- Should be clickable and lead to the screening page

**Potential problems:** 
- On UI the banner should not cover the "arrow" to go back, but still should be visible ; 
- Check if this element can be introduced here as it's not the cross-app.

**Comment by 2amarkina** [comment]
**Dev Review:** 

- Ok for Hero Section 
- Ok for screening list component 


- Version 1 with banner is not easy to implement, requires tests. Reasons: not cross-app zone, eventual UI problem with arrow, loading problems that could lead to jump. 

Version 3 is preferable as badge is in the App-Specific zone. 
![Снимок экрана 2021-06-03 в 16.27.20.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/5751c034-4dad-47cf-be21-8cc808e82887)

- [ ] see with business team if v3 is also ok 
- [ ] prepare mobile / tablet version where the badge will go

**Comment by Jackseed** [comment]
@2amarkina we confirmed the v3 with Marie so mobile/tablet version to go and then I guess we can pass it to UI

**Comment by 2amarkina** [comment]
**On tablet:** 
- do not show "original title" 
![Снимок экрана 2021-06-10 в 15.25.33.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/72a7579a-8f7a-4fcc-b97d-f807d4a9d3a7)

**On mobile**
- do not show "original title" 
- do not show supp-action btns 
![Снимок экрана 2021-06-10 в 15.32.01.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/36907ca1-dfa8-4e3c-ab34-29a4b25d9f33)

If ok @Jackseed this issue can go to UI

**Comment by Jackseed** [comment]
all good for me 👍

**Comment by stephanie-cascade8** [comment]
2 propositions on the raised button 'screening ongoing'. ![header-movie_page copy](https://user-images.githubusercontent.com/66258851/123662519-d7c7e480-d835-11eb-8cb2-1c3bb05c9713.png)1- basic
![header-movie_page](https://user-images.githubusercontent.com/66258851/123662467-cb438c00-d835-11eb-8267-ef44891b5086.png)

2- lightly animated icon (tested in css only)
![header-movie_page copy](https://user-images.githubusercontent.com/66258851/123662541-ddbdc580-d835-11eb-8306-bd57c118ebf0.png)
![raised-button__icon__animated](https://user-images.githubusercontent.com/66258851/123662570-e31b1000-d835-11eb-8b02-20a53c2068da.gif)

**Comment by Jackseed** [comment]
I really like the animated one but it's a bit jerky and there is a cut at then end while it should be infinite. I think it worths polishing it a bit so we go for that (if implementation is ok ofc)

**Comment by stephanie-cascade8** [comment]
@Jackseed issue still in progress

**Comment by RemcoSimonides** [comment]
Created a dev issue for this. Please check if it contains all the needed information as it's a lot ^^
