### ISSUE TITLE
MF Staging - missing logos on the home page (+ sentry error 'too many requests')

### ISSUE THREAD

**Issue by SamirTouira** [blockframes/blockframes#5079]
url: https://staging.mediafinanciers.com/c/o/marketplace/home

- [ ] When you go to MF staging in Professional Financiers section, the images are broken. On the localhost - develop branch we don't have this issue (at least on my side)

- [x] We also got many (but the sames) sentry error messages in the navigator console (issue related : #5094)

![image](https://user-images.githubusercontent.com/52285231/109867768-33f37100-7c67-11eb-88f3-31445f757c39.png)

Let me know if this is just related to a simple next merge or something like that and I close this.

**Comment by phpgeekfr** [comment]
shoudl be fixed by https://github.com/blockframes/blockframes/pull/5096

**Comment by SamirTouira** [comment]
@phpgeekfr it's due to your changes here I guess `libs/organization/src/lib/organization/components/card-minimal/card-minimal.component.ts`? good job. If yes, I think I could close this
