### ISSUE TITLE
3. As a Super Admin or Admin, I want to be able to share documents with other users (organizations).

### ISSUE THREAD

**Issue by lsenta** [blockframes/blockframes#508]

**Comment by Jackseed** [comment]
- [ ] Laurent: check if the email is already associated to a user; if yes: notification + request for acceptation, if not: email with a link to the creation account tunnel

**Comment by lsenta** [comment]
@Jackseed 
- [ ] Blocked by: what's the url for the verification flow

![Screenshot 2019-07-10 at 16.52.26.png](https://images.zenhubusercontent.com/5ade0d334b5806bc2bd04a95/12d49be5-1924-41ad-8bd8-ccf435fa6766)

**Comment by ioaNikas** [comment]
No more invitation on movie. Inviting an organization on a document will grant it access to the document and the movie attached to it.

**Comment by lsenta** [comment]
Few notes:
- [ ] add stakeholders "users" so that you can invite a new user without org
- [ ] make sure the ui will let a user go through the auth funnel, then join/create an org BEFORE interacting with the notification
- [ ] when we add a stakeholder, create an "invite" (in its own collection) that is either for a user or for an org
- [ ] the user sees the invites / notifications in the UI
- [ ] the user can accept the invite, it'll update the permission and the stakeholder.

**Comment by Jackseed** [comment]
outdated issue > closed
