### ISSUE TITLE
Movie form save bug

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5080]
### Steps to reproduce
user: dev+kenneth-ixf@blockframes.io
url: https://staging.archipelmarket.com/c/o/dashboard/tunnel/movie/02L9gsoY4WTdGbxpOKha/main
1. Go to page above
2. Modify running time
3. Click on save
4. Try to exit
5. Warning modale keep spawning, it's impossible to save change
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/0eaea3c6-e533-412e-8aa7-4732adb8bebb)

### Correct behaviour
Form should be saved and step 4. should lead to movie view with updated info

### Error logs
[Sentry error 
](https://sentry.io/organizations/cascade-8/issues/2249032776/?project=1540126&referrer=slack)

**Comment by phpgeekfr** [comment]
Problem was solved by updating DB with correct value for movie.banner

expected: 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/38fb74e8-c25d-4718-970a-598b44bdf8d7)

What we had:
![Screenshot_2021-03-04 blockframes-staging - Cloud Firestore - Console Firebase.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/7342ec02-5dbc-4f06-96c6-b93bf5c38138)

I will investigate a bit more on this, to check how problem can occur and also fix the save button problem if we have a new case like this.

**Comment by phpgeekfr** [comment]
see https://github.com/blockframes/blockframes/issues/5091 &  https://github.com/blockframes/blockframes/pull/5090
