### ISSUE TITLE
Movie front improvements

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5087]
user:dev+kenneth-ixf@blockframes.io

### Marketplace movie view
https://staging.archipelmarket.com/c/o/marketplace/title/Kl5zVlKjJVb2Ih48otMb/main
- [x] **SAMIR** Remove video type in the video title to keep only its name > instead of "Video type - Video name" we go for "Video name" because most of the time users add the video type inside the name
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/135b45a0-82aa-4851-99a2-bf3000831b09)

- [x]  **Bruce** Switch award/selection & premiere in the festival card and add the word "Premiere" after the premiere param:
FESTIVAL NAME
Award/Selection (Year)
Wolrd/Market/National Premiere

instead of
FESTIVAL NAME
Wolrd/Market/National (Year)
Award/Selection
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/057f4ab7-e0fe-460b-8237-8b4e9030bdc6)

- [x] **Bruce** Use the value of the festival for festival name instead of the key. E.g here it should be: San Sebastian International Film Festival and not SANSEBASTIAN
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/120412ae-22c0-42bf-9002-1ef109601fda)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/923fd6e4-9be3-4863-aab4-952eddef48ae)

- [x] **SAMIR**  Statuses in parenthesis (running time & release year) should not be displayed when the status is "confirmed"
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/b8403b61-ae2d-41f7-8dd0-8e944ded88ad)

- [x] **SAMIR** add a capital "R" to "Selection and Reviews"
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/9f6427e2-b587-4410-a56f-a4e2711ebf8c)  

- [x] **SAMIR** Person card / filmography tab: when the title is more than one line long, it's not centered anymore but it should 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/007543af-da09-4a02-af56-705016ac84ea)

- [x] **SAMIR** Director's card: Add a "Director's Category: " before the category name. For example here: "Director's Category: Prestige"
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/23cd8af8-4698-41f7-9425-157e6f8bc989)

### Movie form
url https://staging.archipelmarket.com/c/o/dashboard/tunnel/movie/lFjibYglnyZgOuSIqQyp/sales-pitch
- [x] **SAMIR** Change "Sales Video Pitch" for "Sales Pitch Video"
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/53945b28-97de-4684-bf7e-f301d30e7cf9)

- [x] **SAMIR** Video type list: change value "Reel" for "Promo Reel"
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/fcaf0d4f-ed41-4e0c-8a3e-e68ab6f30111)

### Dashboard movie view
url: https://staging.archipelmarket.com/c/o/dashboard/title/lFjibYglnyZgOuSIqQyp/main
- [x] **SAMIR**  Spacing between Section title / Sub section title / Parameters are not respected. Should be same as zeplin [here](https://app.zeplin.io/project/5f9fe54601fa6b6c2d9f0bb3/screen/5fa16a40e0c2b720ce95438b)

![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/7e03c8b1-9217-47b4-92ea-076c72d87edb)
vs Zeplin
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/6fd421df-24c6-4b42-b9ae-190573443e85)

- [x] **SAMIR** Both movie form summary page & dashboard movie view: replace the word "Mandatory" in red when a required data is missing by "Mandatory info missing" still in red
![image](https://user-images.githubusercontent.com/14964443/109970044-e4f41d00-7cf4-11eb-849b-5cd18eb10a6f.png)
![image](https://user-images.githubusercontent.com/14964443/109970112-fa694700-7cf4-11eb-8038-e11f58bb7781.png)

**Comment by SamirTouira** [comment]
> Statuses in parenthesis (running time & release year) should not be displayed when the status is "confirmed" 
![image](https://user-images.githubusercontent.com/52285231/110157096-16014a00-7de8-11eb-946d-a76747723d8b.png)

Should we also apply this into the movie form summary page?

**Comment by Jackseed** [comment]
@SamirTouira no it's just for the marketplace movie view. On the dashboard (view + summary) I prefer users to have access to full information as they may change it if necessary

> > Statuses in parenthesis (running time & release year) should not be displayed when the status is "confirmed"
> > ![image](https://user-images.githubusercontent.com/52285231/110157096-16014a00-7de8-11eb-946d-a76747723d8b.png)
> 
> Should we also apply this into the movie form summary page?
