### ISSUE TITLE
banner path is transformed into mapping when I remove existing banner from movie tunnel and save

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#5091]
banner path is transformed into mapping when I remove existing banner from movie tunnel and save.

expected: 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/453435c5-3331-4741-8d9f-efce70202801)

What we get :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/6e689de0-f9b1-4a83-ae43-b8f93e60ba27)

Linked to #5080

**Comment by phpgeekfr** [comment]
Fix to prevent blocking error : https://github.com/blockframes/blockframes/pull/5090
it will remove the mapping and put "" instead and allow user to save movie without error

**Comment by pldespaigne** [comment]
@phpgeekfr should fixed now that #4894 is merged
