### ISSUE TITLE
MF Marketplace buggy

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5094]
user: dev+aliza-peq@blockframes.io
url: https://staging.mediafinanciers.com/c/o/marketplace/home

I manually switched app access on firebase for orgId `vcyZAPBMZaxyDsszeMZo` to have both marketplace & dashboard accessible on MF.
Dashboard is ok but marketplace is super buggy and I can't even open the sidenav, sentry is spammed with errors

**Comment by phpgeekfr** [comment]
Anastasiia told me about it.
Should be fixed with https://github.com/blockframes/blockframes/pull/5096
