### ISSUE TITLE
"Error: Cannot find form control with name: jwPlayerId" when accessing http://localhost:4200/c/o/dashboard/tunnel/movie/KPs2XBsQ2pFTdXXb8JP5/media-videos

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#5105]
"Error: Cannot find form control with name: jwPlayerId" when accessing http://localhost:4200/c/o/dashboard/tunnel/movie/KPs2XBsQ2pFTdXXb8JP5/media-videos
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/b69cf6dd-7737-4aa7-92af-ffedc07424b7)

**Comment by pldespaigne** [comment]
Can't reproduce, with today's develop, latest deploy & pft.
I checked several movie and everything seems fine.
Also double checked on today's latest staging deploy and still no errors.

Feel free to re-open if keep seeing this bug.

**Comment by pldespaigne** [comment]
My bad ! you had to :
1) select a video in the file-uploader
2) click on the tunnel save button to start the upload
in order to get the error
