### ISSUE TITLE
cannot upload a screener in movie tunnel 

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#5106]
cannot upload a screener in movie tunnel 
Upload seems ok but video is not saved
maybe linked with #5105

**Comment by pldespaigne** [comment]
Can't reproduce, upload works fine, file is saved in storage, db & jwp. I tested both local and staging.
You can't preview the file in the front yet because of #5119, but this will be fix with this PR #5122
Feel free to reopen if needed
