### ISSUE TITLE
1. As an Admin, I can give full access to a specific application to my organization members.

### ISSUE THREAD

**Issue by lsenta** [blockframes/blockframes#513]

**Comment by Jackseed** [comment]
- [ ] Tab dapps in Org Settings 
- [ ] When a dapp is added to an org, the request is pending and the dapp not accessible yet
- [ ] Manual acceptation of a dapp request (by C8 members)

**Comment by vwmathilde** [comment]
https://projects.invisionapp.com/d/main#/console/17965246/373055172/preview
<img width="920" alt="Capture d’écran 2019-07-10 à 11 14 05" src="https://user-images.githubusercontent.com/51743840/60956866-eabd1380-a303-11e9-82b7-77be36928937.png">

**Comment by Jackseed** [comment]
too much issues on roles > closed
