### ISSUE TITLE
CRM - Permission error org view

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5139]
url: https://staging.crm.blockframes.io/c/o/admin/panel/organization/035zZAYcEXjSkcf8BmSi
user: dev+brandyn-xio@blockframes.io
sentry: https://sentry.io/organizations/cascade-8/issues/2248425528/?project=1540126&referrer=slack

I can't access any org view page due to permission error.

**Comment by Mussuranae** [comment]
I have no error in the console for my part (on staging and on my local environment), but I have no organization too. I will investigate more
