### ISSUE TITLE
Reminders - time zone issue

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5154]
It looks like there is one hour difference between reminders and GMT+0, maybe because I'm on time zone GMT+1? 
Anyway reminders and comparaison with event time should be synced with GMT+0 to be sure both are on the same time zone. 
 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/da6b032a-91c1-4326-a887-28267fb9e0f0)

**Comment by Jackseed** [comment]
@Mussuranae I re-open that issue as it looks like it changed from 1h but in the wrong direction
![image](https://user-images.githubusercontent.com/14964443/110907737-1c268780-830e-11eb-886e-e77269ce281d.png)

I'm on GMT+1 so 11:30pm for me is 10:30pm GMT+0 and here I received a 1h reminder for 1:30AM for an event that will start in fact in 3h

**Comment by phpgeekfr** [comment]
@Mussuranae is it solved or do we need to work on this ?

**Comment by Mussuranae** [comment]
I will test it again, but last time I worked on it, I could only send the good time but in GMT+0 for everyone. Will try to improve it.

**Comment by Mussuranae** [comment]
So I tried on my side, and the email are well send with the good hour for event. But it's in GMT+0 always. I though how I could get the good timezone for user, but I think there is no solution. We send those emails via the notification process. Our backend will check every 30min if there is event starting between 24h and 25h or between 1h and 1h30 from the current hour. So there is no contact with the front also. I guess I can't use functions like the `Intl.DateTimeFormat()` from the front to get the good timezone of the user.

What I saw on some issues is that developers registered on their database the preferred timezone of the user and use it when they need it. I don't see any way to get the timezone of each user and even more when there is no link to the front :/

**Comment by Jackseed** [comment]
Imo we can't keep these emails if it's always based on GMT+0. We have users all over the world so it could cause misunderstandings. 
So either we have a way to know in which timezone is the user (IP when accepting the privacy policy..?) and/or we had an input to know it in the future but then we'll have to remove it until it's implemented.

@pldespaigne @phpgeekfr @GrandSchtroumpf any insight on that issue? 
@maltmayer as well on business side

**Comment by pldespaigne** [comment]
Imo best solution is to remove completely hours from the email and only say something like "event start in 24h" so its not time zone dependent.

**Comment by Jackseed** [comment]
> Imo best solution is to remove completely hours from the email and only say something like "event start in 24h" so its not time zone dependent.

Right, @Mussuranae is that doable from what you've seen:
- we look at the event time & date for GMT+0
- we compare to the actual hour GMT+0
- we send reminders when there is either 24h or 1h delay between the event time GMT+0 and the actual time GMT+0
?
We could hand over that issue to the release team if that's too much work

**Comment by Mussuranae** [comment]
As told this morning, we can't know from the backend the timezone of the user.
Best would be for the moment to change wording and don't be exact on the hour, as @pldespaigne said, and start thinking about implementing an option on the user's profile to let them choose their timezone. At this moment we will be able to change the function and do something more specific for each user.

**Comment by Jackseed** [comment]
Reminders work well with GMT+0, I close this issue and will open another one later to improve these reminders
