### ISSUE TITLE
Permission issue on meetings

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5171]
Meeting url: https://staging.archipelmarket.com/c/o/marketplace/event/WeC0OFKHrglMLdZECFPu/session
organizer: dev+brandyn-xio@blockframes.io 
invitee: dev+carson-yck@blockframes.io

Videos & Pdf do load on the organizer side but there is a permission issue on the invitee side so nothing is displayed.

Sentry related error: https://sentry.io/organizations/cascade-8/issues/2266751082/?project=1540126&referrer=slack

**Comment by phpgeekfr** [comment]
@Jackseed  can't it be linked to the fact that video & pdf used for this meeting belongs to a draft movie ?

**Comment by phpgeekfr** [comment]
movie linked to this event  (0Rl7IIHX5Mz7t8lPXEhS) is in draft. I think this is the problem

**Comment by Jackseed** [comment]
I got same issue here https://staging.archipelmarket.com/c/o/marketplace/event/MJuuKPIORUY1viznXpiW/session
with dev+billy-rvi@blockframes.io and files from accepted movies
https://sentry.io/organizations/cascade-8/issues/2186795686/?project=1540126&referrer=slack

**Comment by phpgeekfr** [comment]
I'm not able to reproduce error

**Comment by pldespaigne** [comment]
me neither

**Comment by Jackseed** [comment]
ok let's close that ugly boy, not to myself: clean cache before opening last release issues
