### ISSUE TITLE
issue with upload component

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#5176]
On the movie tunnel, I upload a new screener :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/f6e61760-1ebf-4114-bb59-6cc992e2862e)

But I don't save form and click on next: ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/dff4c639-3b88-46db-b30c-b466cfe31935)

If I go back, upload zone is empty:

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/ed456623-8810-4ca8-bef0-fbcdcd482be6)

But If I click to save, file is still uploaded so it's only a display issue

**Comment by pldespaigne** [comment]
ok I'll test
