### ISSUE TITLE
CMS app

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#5183]
- [x] if the cms banner component doesn't contain an image, nothing should show up. Right now, there is un "unidentified" element:
![image](https://user-images.githubusercontent.com/55785823/110802491-87287d80-827e-11eb-8dce-6fc9889e0e6d.png)

**Comment by phpgeekfr** [comment]
Related error on sentry:
https://sentry.io/organizations/cascade-8/issues/2278916810/?environment=staging&project=1540126&query=is%3Aunresolved

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/676afb9b-1d35-4adc-80b9-2b6e9d867d2d)

I think we just need to add `?` to `section.image.storagePath` => `section?.image.storagePath`
