### ISSUE TITLE
Change release media

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5184]
url: /c/o/dashboard/tunnel/movie/movieId/additional-information (production status to "released")

Currently we display 3 media for release:
- Theatrical
- Video
- Hotels
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/ef12c789-1726-4054-a3d3-dbee95bf1d1b)

This list should be changed for:
- Theatrical
- Video
- TV

Since we remove "Hotels", db should be checked before changing that to look for a movie that has hotel as release media. I don't think there is one so it should be fine, but better safe than sorry

**Comment by RemcoSimonides** [comment]
Hee @Jackseed ,
No matter whether there is 'Hotels' in the database, I think it's still best to create a migration for it. Just to be save ;) But what value would you change it to? video?

Also, this is the list we have to choose from
```
  payTv: 'Pay TV', // pay-tv
  freeTv: 'Free TV', // free-tv
  payPerView: 'Pay Per View', // pay-per-view
  est: 'EST',
  nVod: 'N-VOD', // n-vod
  aVod: 'A-VOD', // a-vod
  fVod: 'F-VOD', // f-vod
  sVod: 'S-VOD', // s-vod
  theatrical: 'Theatrical',
  video: 'Video',
  planes: 'Planes',
  boats: 'Boats',
  hotels: 'Hotels',
  educational: 'Educational',
  rental: 'Rental',
  through: 'Sell Through'
  ```
  which doesn't contain a 'TV'; only Pay TV and Free TV. What should I do?

**Comment by Jackseed** [comment]
@RemcoSimonides ok then you can use theatrical, video, payTv and freeTv
