### ISSUE TITLE
Sendgrid email updates

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5186]
A lot has been done within Epic #4046  but there is still some we can do to improve our systems. 

### Standardised objects
One good practice that has been implemented with `events` and `app` objects is to send the whole object standardised so we may change texts without sending new variables and avoid wrong variable name in the emails. 
As an example, `event` is sent with parameters `type`, `start`, `end`, `viewUrl`, `sessionUrl`, `title`. 

We could do the with orgs and users. So far parameters used are:
Org
- name
- contact email
- orgId

User
- first name
- last name
- email
- password

### Mailto
For emails where a second user is mentioned (eg. "Hello XX, **YYY** would like to join your org") we'd like to add his/her email address as a mailTo since we're a marketplace that connects the business industry it looks right to give users a way for direct contact

**Comment by Jackseed** [comment]
@Mussuranae I updated the mailTo needs ;)

**Comment by Mussuranae** [comment]
Can you list all email templates that need the org object, those that need the user object (all ?) and those that need the Mailto object ? I will begin to change some data in the code, but it would be good to have a double check to not forget some template. Thanks.
