### ISSUE TITLE
Illustration for emails

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5190]
We'd like to add illustrations on 3 core emails of the app:
- Organization validated 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/b47315b6-b074-4513-912e-10b1d73103b6)

- Movie validated
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/ffa31a68-2745-4fd7-abb8-d495a1c8bfac)

- Event invitation
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/ce7e36d5-003f-4b4d-b117-c431b737ef58)

Here are the specs in French by @maltmayer, she should be the one reviewing / answering questions for these illustrations

Org validée : illustration qui montre que le process de création d’org est terminé. Youpi, on a accès à la plateforme. C’est le début d’une belle aventure. Peut-être une personne déterminée en mode allez c’est parti, que la fête commence. 

Film validé : super, ton film est validé, il va pouvoir "décoller" et vivre sa vie sur la plateforme (être montré / vendu / financé / faire de l’argent). Peut-être un truc à faire avec une bobine et genre des petites ailes? ahah peut-être que je délire. Ou sinon un truc plus simple en mode petit logo certifié / validé sur un visuel de film. ou un stamp "approved" ?

Invitation à un event pour ceux qui ont déjà un compte : petite enveloppe d’invitation, comme un faire part ? Genre « you’ve got mail » mais un truc un peu plus sympa. Peut-être avec des tickets de cinéma qui dépassent ?

**Comment by jdrns** [comment]
@Jackseed @maltmayer here are the new illustrations, please let me know if you need a different format, they are currently 380x380px png

**Organization created:**
![adventure](https://user-images.githubusercontent.com/79836137/114513402-6fa43200-9c3a-11eb-87d3-46811b86a474.png)

**Movie validated:**
![publicatin_validated](https://user-images.githubusercontent.com/79836137/114513410-70d55f00-9c3a-11eb-83f4-239cbf85f53a.png)

**Invitation:**
![invitation](https://user-images.githubusercontent.com/79836137/114513409-703cc880-9c3a-11eb-8699-aabc9b9b6323.png)

**Illustrations in context here:** 
![Mockup organisation created](https://user-images.githubusercontent.com/79836137/114513764-d590b980-9c3a-11eb-8465-f8cb9f6a08cd.png)
![Mockup successfully published](https://user-images.githubusercontent.com/79836137/114513751-d1fd3280-9c3a-11eb-9518-4aa3d288dfdc.png)
![Mockup invited to event3](https://user-images.githubusercontent.com/79836137/114513942-05d85800-9c3b-11eb-8353-bbfcaa777116.png)

**Comment by Jackseed** [comment]
All good, email changed!
