### ISSUE TITLE
Marketplace org list empty

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5194]
url: c/o/marketplace/organization
user: dev+ardella-iio@blockframes.io

Marketplace org list is empty while there are plenty of orgs that should be listed
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/8a03c865-6982-4c30-9aec-4224a4e07f62)

**Comment by RemcoSimonides** [comment]
This one is caused by Algolia not having records.
Probably because `npm run backend-ops upgradeAlgoliaOrgs` hasn't ran during the PFT

@phpgeekfr @george43g can one of you fix this?

**Comment by phpgeekfr** [comment]
@RemcoSimonides asking this for staging ?

**Comment by phpgeekfr** [comment]
using latest PFT, I have all the orgs in the list

**Comment by RemcoSimonides** [comment]
All good then!
