### ISSUE TITLE
Meeting issue - "You're not authorized to see this video"

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5195]
url: https://staging.archipelmarket.com/c/o/marketplace/event/5BHhDZJQYHblOJlly84N/session
users: dev+mabel-imk@blockframes.io (organizer) / dev+raymond-ndc@blockframes.io (invitee)
sentry error: https://sentry.io/organizations/cascade-8/issues/2266940312/?project=1540126&referrer=slack
video: "test-video.mp4" in the middle
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/1fdda512-e252-4ba8-b16f-9d99f087dc79)

Image was shared fine but then the video keeps spinning on the invitee side while playing nicely for the organizer. Sentry error "You're not authorized to see this video" spawned and from there I couldn't see any file as the invitee.

Other related errors:
https://sentry.io/organizations/cascade-8/issues/2266756083/?project=1540126&referrer=slack
https://sentry.io/organizations/cascade-8/issues/2266751082/?project=1540126&referrer=slack

**Comment by pldespaigne** [comment]
Ok I was able to reproduce !
In fact it seems that it's not a meeting issue, but an "Other Videos" issue.
If a user try to view the same video on the marketplace page of the film, he will get the same error.
