### ISSUE TITLE
Marketplace homepage randomly flashes

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5196]
From that release marketplace homepage starts flashing while loading images (around 2 to 3 times before being stable). Now it got worst and sometimes it just keeps flashing without stopping at any time.

https://user-images.githubusercontent.com/14964443/110909817-d6b78980-8310-11eb-9943-fb10e634c847.mp4

**Comment by RemcoSimonides** [comment]
Tough one to reproduce... It's not blinking indefinitely for me

But the observable on the page is called twice. To have less blinking we could change it to a value instead of Observable, or use the magic of 
```
this.page$ = this.db.doc<CmsPage>('cms/festival/home/live').valueChanges().pipe(
  distinctUntilChanged((a, b) => JSON.stringify(a) === JSON.stringify(b))
);
```

@Mussuranae do you want to have a look at it?

**Comment by RemcoSimonides** [comment]
Lazy loading of images doesn't seem to be the issue either
