### ISSUE TITLE
2. As an admin of an organisation, I want to invite new members to collaborate. 

### ISSUE THREAD

**Issue by lsenta** [blockframes/blockframes#520]

**Comment by Jackseed** [comment]
- [ ] Page Teamwork org (5.4 design incomplete)
- [ ] Design to complete
- [ ] Laurent: Research function to improve (new member autocomplete - see Yohann's article)
- [ ] Signatory icon linked to the wallet (PL / Max)

**Comment by Jackseed** [comment]
![image](https://user-images.githubusercontent.com/14964443/60948650-b93c4c00-a2f3-11e9-9e3a-985c26a0fab3.png)
