### ISSUE TITLE
Movie form - Running time TBD blocks saving

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5213]
url: https://staging.archipelmarket.com/c/o/dashboard/tunnel/movie/uquO6xBo5Hb0r4oWiHMM/summary
user: dev+brandyn-xio@blockframes.io

Movie form has been changed to hide "Running time field" when status "To be determined" is selected on main page.
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/aeef53bc-b85f-4669-945e-ca2754f3e82e)

The problem is that "Running time" stays mandatory so the form is blocked if no value has been filled in
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/4d51464c-9312-485f-93f5-375a2ca05197)

Best would be that "Running time" is not considered mandatory when TBD is selected. Idk if that's possible.
Also on the summary + dashboard view, "Running time" should be ignored if TBD is selected so in the screenshot above, it should be:
"Running time: To be determined"

Instead of "Running Time Mandatory info missing (To be determined)"

**Comment by GrandSchtroumpf** [comment]
Easy solution : don't make running time mandatory at all
Hard solution : create a custom validator that check both the running time & the status.

The hard solution will create side effect of the error state of the form. The status might be red if set to something else that "to be determine" for example.

**Comment by Jackseed** [comment]
> Easy solution : don't make running time mandatory at all
> Hard solution : create a custom validator that check both the running time & the status.
> 
> The hard solution will create side effect of the error state of the form. The status might be red if set to something else that "to be determine" for example.

Thanks I'll check but I guess we can go for the easy solution

**Comment by Jackseed** [comment]
I confirm we can switch running time (& its status) as optional
