### ISSUE TITLE
Meetings - Turn on webcam green light only when camera is on

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5219]
Device: Macbook pro
OS: MacOs Big Sur 11.2.2

Currently I got my webcam green light indicating that webcam is on as long I'm on a meeting page, even if I disable camera on the meeting. 
When the camera is disabled on the meeting, that green light should be turned off as well

**Comment by pldespaigne** [comment]
I think this issue is caused by the way we handle media stream inside the meeting service. IMO this will be hard to fix and could potentially break the meetings if we are not really cautious.

**Comment by RemcoSimonides** [comment]
NOTE: Although disabling a LocalVideoTrack whose source is a camera stops sending media, the camera is still reserved by the LocalVideoTrack and hence its light still stays on. In some use cases, the desired behavior might be that the light should turn off when users mutes their camera. Although this method is not recommend, this can be achieved by calling stop on the LocalVideoTrack and unpublishing it from the Room:

```
room.localParticipant.videoTracks.forEach(publication => {
  publication.track.stop();
  publication.unpublish();
});
```

https://www.twilio.com/docs/video/javascript-getting-started#mute-and-unmute-audio-and-video

**Comment by Jackseed** [comment]
I prioritised this issue since we're pushing the meeting feature to clients
