### ISSUE TITLE
Titles inventory (h1, h2, h3,...)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5227]
Now that design system is clean on typos we need an inventory of what titles have to be changed within the app. 
Each page should be reviewed with indications on what titles have to be changed and for what.

**Comment by stephanie-cascade8** [comment]
https://docs.google.com/document/d/1Xds_UVbdjtOCtN1eupspt1POp4YsYBinJcl-cMLAP8g/edit

**Comment by Jackseed** [comment]
Thanks @stephanie-cascade8, I passed it to devs through this issue #5551
