### ISSUE TITLE
Invitation icon to be changed

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5229]
This icon is considered as not clear so we should change it.

**Comment by jdrns** [comment]
@Jackseed New icon invitation is ready (image for preview) but might require a little test in context to see if it works and is not too detailed 
<img width="145" alt="Screenshot 2021-03-22 at 10 18 50" src="https://user-images.githubusercontent.com/79836137/111967166-02e4be80-8af8-11eb-89bd-860a9c2f2410.png">

**Comment by Jackseed** [comment]
Thanks @jdrns! I'm indeed a bit worried that the star gives it too much detailed but will test it in context. It's gonna be too tight to include that in the release as we're on the last days to wrap it up but it will be included in next dev sprint

**Comment by Jackseed** [comment]
Retro feedbacks:
- [ ] Check in context if not too much details with the star
- [ ] Think it not to be redundant with notifications mark as read

**Comment by jdrns** [comment]
Here is the new version for the invitation icon, available [here](https://drive.google.com/file/d/1zpKL657O2I1VsPCEdOASlBiwKckn7gJE/view?usp=sharing) 

> * [ ]  Check in context if not too much details with the star

Preview in context: 
![preview-04](https://user-images.githubusercontent.com/79836137/112840391-8f1a5700-909f-11eb-9185-973eb12918ab.png)


> * [ ]  Think it not to be redundant with notifications mark as read

We considered we could change the Mark as read icon 
Preview in context:
![preview-02](https://user-images.githubusercontent.com/79836137/112840459-a8230800-909f-11eb-9612-7b5cf25fdec3.png)

**Comment by Jackseed** [comment]
ok that's great thanks! 
@jdrns could you also send me the mark all as read icon plz? so we implement both at the same time
That's good to me but as a reminder, Invitation icon will also be used here 
![image](https://user-images.githubusercontent.com/14964443/114399583-5ef3ad80-9ba1-11eb-91d7-7d2c33d5cb2e.png)

**Comment by jdrns** [comment]
@Jackseed you can find the mark as read icon [here](https://drive.google.com/file/d/1YHkhXt4TMN5rfX0904P_oA3ZVBpX91dm/view?usp=sharing) 

Invitation icon will work nicely here too!

**Comment by Jackseed** [comment]
Thanks! Transferred to devs over here #5554
