### ISSUE TITLE
Screenings list rules movie draft bug 

### ISSUE THREAD

**Issue by SamirTouira** [blockframes/blockframes#5237]
We are able to create a screening for draft movies, however rules will prevent user to read this movie and this will break the screening list.

Solution is change the rules or better solution will be to prevent creating screenings which contains draft movie

Movie ID: EK0VXki3vP7dph43J24P
User ID: 00ELdRUpAthOw8Nis8iaLuA8xzA3
Event ID: afXU0RhTtMtaIuukDhRH

**Comment by phpgeekfr** [comment]
> solution will be to prevent creating screenings which contains draft movie
this is already the case.
