### ISSUE TITLE
Design Review - UI 

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#5250]

**Comment by stephanie-cascade8** [comment]
Dashboard
----------
- [ ] Dashboard

**Comment by stephanie-cascade8** [comment]
Archipel Content
------------------

**Comment by Jackseed** [comment]
> ## Archipel Content
> * [ ]  Replace Typeface by Body-1 for paragraph after title
> * [ ]  Selection color should be primary not accent
> 
> <img alt="Capture d’écran 2021-03-17 à 15 10 02" width="597" src="https://user-images.githubusercontent.com/66258851/111481149-f8f74000-8732-11eb-9156-37fad4a19ca2.png">
> 
> * [ ]  The width of the whole form should be 60%. Background image to provide (rocket same as easier connexion flow)
> 
> <img alt="Capture d’écran 2021-03-17 à 15 14 32" width="1309" src="https://user-images.githubusercontent.com/66258851/111481768-93578380-8733-11eb-83d1-6ab7d2e8076e.png">
> 
> * [ ]  Section form width should be 60% as well
> * [ ]  Take off margin-top: 40px on the link and put it on accent color
> 
> <img alt="Capture d’écran 2021-03-17 à 15 18 44" width="1172" src="https://user-images.githubusercontent.com/66258851/111482632-5f309280-8734-11eb-8566-4d65dec55dce.png">
> 
> <img alt="Capture d’écran 2021-03-17 à 15 21 23" width="760" src="https://user-images.githubusercontent.com/66258851/111482915-a028a700-8734-11eb-9991-a980bd44b28c.png">
> 
> * [ ]  There should be a surface behind the content.
>   The width of the whole section should be 80%.
>   Title should make a new line after the word "organisation"
>   Illustration size should be 20%
>   New illustration to provide.
> 
> <img alt="Capture d’écran 2021-03-17 à 15 24 48" width="1165" src="https://user-images.githubusercontent.com/66258851/111484101-b97e2300-8735-11eb-8fb2-7870947b2b24.png">
> 
> <img alt="Capture d’écran 2021-03-17 à 15 29 01" width="836" src="https://user-images.githubusercontent.com/66258851/111484160-c7cc3f00-8735-11eb-92cf-167d680cce66.png">
> 
> * [ ]  Here the mat card should look like squares (they are two narrow, I can't see why in the cass sorry)
> 
> <img alt="Capture d’écran 2021-03-17 à 15 34 59" width="744" src="https://user-images.githubusercontent.com/66258851/111485138-a4ee5a80-8736-11eb-97e4-d00e3abd71c5.png">
> 
> * [ ]  New illu to provide (or take the same from market) and Size 20%
> 
> <img alt="Capture d’écran 2021-03-17 à 15 24 48" width="1165" src="https://user-images.githubusercontent.com/66258851/111485455-ebdc5000-8736-11eb-93ac-8fe2f205a9f3.png">
> 
> * [ ]  basket icon should be aligned at the extreme bottom of the card.
>   I know it's inside a button so I tested with flexboxes on the button and on the span inside (it works)
> 
> <img alt="Capture d’écran 2021-03-17 à 15 46 48" width="696" src="https://user-images.githubusercontent.com/66258851/111486945-37432e00-8738-11eb-83b2-3cc3c3c908af.png">
> 
> * [ ]  Invitations 'accept' refuse' : one of the icons is bigger. Can you choose the smallest one?
> 
> <img alt="Capture d’écran 2021-03-17 à 15 48 56" width="317" src="https://user-images.githubusercontent.com/66258851/111487207-72ddf800-8738-11eb-96db-d886352397f8.png">
> 
> * [ ]  New logo to provide with right color
> 
> <img alt="Capture d’écran 2021-03-17 à 15 56 24" width="332" src="https://user-images.githubusercontent.com/66258851/111488381-77ef7700-8739-11eb-94aa-9062f0884fa3.png">

Most of it has changed with the new auth flow, I check what is not relevant anymore

**Comment by Jackseed** [comment]
> * [ ]  New logo to provide with right color
> 
> <img alt="Capture d’écran 2021-03-17 à 15 56 24" width="332" src="https://user-images.githubusercontent.com/66258851/111488381-77ef7700-8739-11eb-94aa-9062f0884fa3.png">

@stephanie-cascade8 please send me the correct logo I can change it manually

**Comment by Jackseed** [comment]
Everything has been taken care of > I close it, feel free to re-open it if you have something new or create another issue
