### ISSUE TITLE
Design Review Release 2.3 UX

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#5253]
**Movie Tunnel** 

- [x] add a possibility to choose nothing for not mandatory dropdowns (cast status, director's category...); 
- [x] **added to issue #5298** snackbar text after clicking on Save (from "Movie saved" to "Title saved");
- [x] snackbar should each time we click on "Save" to provide a feedback;

Summary Page
- [x] **added to #5269** the missing element in Director should lead to the Director's bloc in the Main information part (now leads to the top of the same summary page); 
<img width="443" alt="director" src="https://user-images.githubusercontent.com/55499036/111485482-f1399a80-8736-11eb-8237-ce3c64ca0220.png">
![director2](https://user-images.githubusercontent.com/55499036/111487344-91dc8a00-8738-11eb-806d-543fae7869dd.gif)

- [ ] when clicking on "Missing" for key assets, prod, co-prod, distrib, international sales -> there is a moment when we see a needed field (for about a sec) and than it jumps to the top. Same for cast and crew, festivals, other festivals, film reviews, missings in shooting. 
![missing2](https://user-images.githubusercontent.com/55499036/111487112-5d68ce00-8738-11eb-835a-30abb5dccc4a.gif)

- [ ] almost the same problem: the missing leads to the top of the page, but there is no jump. Elements concerned: presentation deck, scenario, moodboard. 

- [x] for the promotional images we could add the text "Still photo" or "Promotional image" to reduce the emptiness. Or just use the name of an image. (n.b. images were added)
<img width="700" alt="images MT" src="https://user-images.githubusercontent.com/55499036/111498527-5050dc80-8742-11eb-9753-b9e5e083d48b.png">
N.B. nevertheless, it works for the Film Page (Dashboard), but only for 1 image
<img width="498" alt="film page images" src="https://user-images.githubusercontent.com/55499036/111500871-bfc7cb80-8744-11eb-9ebb-d9aa4131723e.png">

- [ ] feedback or action needed when click on "Publish to Marketplace". Proposition: go to the "My titles page" with snackbar "[Title name] Successfully published to Marketplace". 
![cta publish](https://user-images.githubusercontent.com/55499036/111498829-9b6aef80-8742-11eb-91c0-661e8c19459c.gif)

- [x] files do not appear after saving... 
![files](https://user-images.githubusercontent.com/55499036/111500443-4cbe5500-8744-11eb-80fe-b611e91ce8fd.gif)

**Comment by 2amarkina** [comment]
**New connexion flow**

- [ ] if the invitation icon is changed on the toolbar, than should also be changed here 
<img width="1440" alt="invitation" src="https://user-images.githubusercontent.com/55499036/111601283-7f169380-87d2-11eb-8091-b313f7b76b8c.png">

- [ ] while trying to create a company there is a problem that "create a company" disappears and don't let a user to create one (gif below). we should keep "create a company" all the time. (other solution would be to allow creation automatically, but that can lead to the double companies if org with the same name is not selected)

![company](https://user-images.githubusercontent.com/55499036/111602568-c3eefa00-87d3-11eb-960e-4a789b4f81b6.gif)

**Comment by 2amarkina** [comment]
**Marketplace**

- [ ] for the countries of origin, it should be "Russia", not "Russian" 
<img width="267" alt="Снимок экрана 2021-03-15 в 16 03 44" src="https://user-images.githubusercontent.com/55499036/111609171-52ff1080-87da-11eb-9395-341c524861f6.png">

**Comment by 2amarkina** [comment]
**Dashboard Market**

My Events -> Details of event

- [ ] add tooltip to the icon copy for invitations. Text proposition "copy guests emails" 
<img width="1146" alt="Снимок экрана 2021-03-18 в 11 44 09" src="https://user-images.githubusercontent.com/55499036/111613869-44ffbe80-87df-11eb-8f80-e7031499173b.png">

**Comment by 2amarkina** [comment]
**Media financiers** 

Landing page 
- [ ] do we keep the "first invitation" for financiers ?

**Comment by Jackseed** [comment]
> [ ] add a possibility to choose nothing for not mandatory dropdowns (cast status, director's category...);

I'll need a complete list of concerned dropdowns. I'll do it but I won't have time before the release so it will be postponed to that time.

**Comment by Jackseed** [comment]
> **Movie Tunnel**
> 
> * [ ]  add a possibility to choose nothing for not mandatory dropdowns (cast status, director's category...);
> * [ ]  **added to issue #5298** snackbar text after clicking on Save (from "Movie saved" to "Title saved");
> * [x]  snackbar should each time we click on "Save" to provide a feedback;
> 
> Summary Page
> 
> * [ ]  **added to #5269** the missing element in Director should lead to the Director's bloc in the Main information part (now leads to the top of the same summary page);
> 
> <img alt="director" width="443" src="https://user-images.githubusercontent.com/55499036/111485482-f1399a80-8736-11eb-8237-ce3c64ca0220.png">
> 
> ![director2](https://user-images.githubusercontent.com/55499036/111487344-91dc8a00-8738-11eb-806d-543fae7869dd.gif)
> * [ ]  when clicking on "Missing" for key assets, prod, co-prod, distrib, international sales -> there is a moment when we see a needed field (for about a sec) and than it jumps to the top. Same for cast and crew, festivals, other festivals, film reviews, missings in shooting.
>   ![missing2](https://user-images.githubusercontent.com/55499036/111487112-5d68ce00-8738-11eb-835a-30abb5dccc4a.gif)
> * [ ]  almost the same problem: the missing leads to the top of the page, but there is no jump. Elements concerned: presentation deck, scenario, moodboard.
> * [ ]  for the promotional images we could add the text "Still photo" or "Promotional image" to reduce the emptiness. Or just use the name of an image. (n.b. images were added)
> 
> <img alt="images MT" width="700" src="https://user-images.githubusercontent.com/55499036/111498527-5050dc80-8742-11eb-9753-b9e5e083d48b.png">
> 
> N.B. nevertheless, it works for the Film Page (Dashboard), but only for 1 image
> <img alt="film page images" width="498" src="https://user-images.githubusercontent.com/55499036/111500871-bfc7cb80-8744-11eb-9ebb-d9aa4131723e.png">
> 
> * [ ]  feedback or action needed when click on "Publish to Marketplace". Proposition: go to the "My titles page" with snackbar "[Title name] Successfully published to Marketplace".
>   ![cta publish](https://user-images.githubusercontent.com/55499036/111498829-9b6aef80-8742-11eb-91c0-661e8c19459c.gif)
> * [ ]  files do not appear after saving...
>   ![files](https://user-images.githubusercontent.com/55499036/111500443-4cbe5500-8744-11eb-80fe-b611e91ce8fd.gif)

@2amarkina Marie also proposed a new order for files & folders, it's low priority as it's not that easy to change but could you check her proposition and reply there plz so we agree on best order? #5261

**Comment by Jackseed** [comment]
> * on this step (after email verification) user should be just redirected to the thank you page with the "check" for email verification

unfortunately we can't change this

**Comment by 2amarkina** [comment]
**VERY IMPORTANT BUG ARCHIPEL MARKET MEETINGS**

**Comment by 2amarkina** [comment]
**Screenings on Archipel Market** 

- [ ] video isn't stable. continue to get this error when to play a video for the first time. after refreshing backs to normal 
<img width="1432" alt="Снимок экрана 2021-03-19 в 11 30 44" src="https://user-images.githubusercontent.com/55499036/111767386-f3226b80-88a6-11eb-858d-f001481d7dca.png">

**Comment by 2amarkina** [comment]
**Archipel market**

Creation of event

- [ ] date was not later, but still had an error 
<img width="667" alt="Снимок экрана 2021-03-19 в 12 25 09" src="https://user-images.githubusercontent.com/55499036/111773305-4d72fa80-88ae-11eb-85a3-296cae5cdadd.png">

**Comment by Jackseed** [comment]
> * we should leave a possibility to leave the page for a user, like if i created my org and waiting for an approval, i can go the landing for example and the "verification-thank" you screen appears only if i try to enter the platform by sign up or first invitation.

this has been pointed out also by @jdrns, it's related to the fact that we didn't want users to come the landing while connected. We can change that but it has been decided a while ago and should be well thought before going back to the origins..

**Comment by 2amarkina** [comment]
> > * we should leave a possibility to leave the page for a user, like if i created my org and waiting for an approval, i can go the landing for example and the "verification-thank" you screen appears only if i try to enter the platform by sign up or first invitation.
> 
> this has been pointed out also by @jdrns, it's related to the fact that we didn't want users to come the landing while connected. We can change that but it has been decided a while ago and should be well thought before going back to the origins..

ok, i remember about blocking access to login, sign up etc, but thought that s/he could still come back to landing, my bad !

**Comment by 2amarkina** [comment]
> > * we should leave a possibility to leave the page for a user, like if i created my org and waiting for an approval, i can go the landing for example and the "verification-thank" you screen appears only if i try to enter the platform by sign up or first invitation.
> 
> this has been pointed out also by @jdrns, it's related to the fact that we didn't want users to come the landing while connected. We can change that but it has been decided a while ago and should be well thought before going back to the origins..

i got it now why there is also this desire to come back to the landing. on the wireframes for the "verification-page" there was no logo (but Archipel Market team was in bold), so there was no reflex to click and wait for the action.

**Comment by Jackseed** [comment]
> * do we keep the "first invitation" for financiers ?

ça me semble ok vu que y aussi les invitations à une org mais pas primordial
