### ISSUE TITLE
No movie card when clicking on load more button

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#5256]
On the movie list, at the end of the page, when you click on the "load more" button, the two last place for movie-card are empty and stay empty. If you scroll up a little, two movies appear but if not, the places stayed empty.
![image.png](https://images.zenhubusercontent.com/5d51508f6f935933f7158b07/e77aeb31-3c33-42f7-a670-770b01859df4)

**Comment by SamirTouira** [comment]
@Mussuranae on my side, I failed to trigger this issue, tried it on my local environnement and on staging. Is it a cache issue?

**Comment by pldespaigne** [comment]
Everything works fine on my side, feel free to re-open with more details if you are able to reproduce
