### ISSUE TITLE
Auth flow - UI fix

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5264]
Issue from @stephanie-cascade8 
Connexion flow (tested on content)

- [x] Illustration missing in the background (same as create account)
<img width="813" alt="Capture d’écran 2021-03-17 à 18 20 04" src="https://user-images.githubusercontent.com/66258851/111510063-ae36f180-874d-11eb-8812-907b2a8c4241.png">

- [x] Images didn't load. Each text should take one line not two (maybe enlarge the bloc)
<img width="775" alt="Capture d’écran 2021-03-17 à 18 33 07" src="https://user-images.githubusercontent.com/66258851/111511784-5a2d0c80-874f-11eb-987c-9c7d183b3b24.png">

- [x] For me - provide the right illustrations for dark mode and resize the illustration with the cloud (to close to the logo)
- [x] The content with title and form should come below the logo
<img width="1119" alt="Capture d’écran 2021-03-17 à 18 51 40" src="https://user-images.githubusercontent.com/66258851/111514327-eb9d7e00-8751-11eb-9ebd-6c802b7ac2e7.png">

- [x] Size of the mat-card containing the form should be 56% on desktop (currently it's way too large)
<img width="1255" alt="Capture d’écran 2021-03-17 à 18 54 48" src="https://user-images.githubusercontent.com/66258851/111514842-68c8f300-8752-11eb-90eb-e39982d2a8c4.png">

- [x] background of toggle doesn't work. let's put the variable --background-800 if possible (can we test together)
<img width="271" alt="Capture d’écran 2021-03-17 à 18 57 03" src="https://user-images.githubusercontent.com/66258851/111515383-01f80980-8753-11eb-8382-124d889506eb.png">

**Comment by Jackseed** [comment]
@Mussuranae updated comments
- [ ] Overlap of logo and illustration and logo should be clickable and go back to landing
<img width="364" alt="Screenshot 2021-03-18 at 09 04 00" src="https://user-images.githubusercontent.com/79836137/111592277-e29bc380-87c8-11eb-8b1e-9a84a6698b7b.png">

- [ ] In terms and conditions modal (second last paragraph), Privacy Policy is clickable but leads to dashboard while user isn't connected. I think it's a shared text with the T&Cs page inside the app (linked in the footer). If it is, then just remove that link to Privacy policy so it works all the time. 
If it's not, then the link from sign up page should open the Privacy modale  
![Kapture 2021-03-18 at 09 25 56](https://user-images.githubusercontent.com/79836137/111595043-03194d00-87cc-11eb-94ea-a115c7a0b2ad.gif)

**Comment by Mussuranae** [comment]
I confirm it's actually the same component for T&C page.
I can do nothing for the background, it is stuck to the right bottom corner of the page, it will change with the screen size.
