### ISSUE TITLE
New auth flow - improvements & debug

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5265]
Issue from @maltmayer 

### FIRST INVITATION

- [x] Filled in every info but can't sign up I think the problem is in the Company field. 
My company obviously doesn't exist but it does not suggest me to create it. And since I didn't click on "create" the platform doesn't seem to register my company information. I'm stuck.
Actually I noticed it suggests to create the company when it finds matching companies. But when it doesn't, the list doesn't appear so the "create company" doesn't appear either. I put a video to explain better.
![image](https://user-images.githubusercontent.com/55785823/111517063-f1489300-8754-11eb-8ef7-76149e1b6b33.png)

https://user-images.githubusercontent.com/55785823/111517510-70d66200-8755-11eb-875d-54182021403c.mov

- [x] Very unpleasant automated box appears. I figure it might be out of our control but if we could disable the automated suggestions, it would be GREAT as this is quite annoying:
![image](https://user-images.githubusercontent.com/55785823/111517180-14734280-8755-11eb-830c-85036ae20e4e.png)

- [x] When I create a company and realize I made a mistake, I can't go back, I'm stuck with the company I initially created. Don't know what to do appart from refreshing and filling in again all the info... Not very pleasant

https://user-images.githubusercontent.com/55785823/111517665-98c5c580-8755-11eb-92ea-0efb15c35acb.mov

- [x] the "CREATE th COMPANY" line should look different from the list of existing companies. Maybe in bold? maybe have a separation line? 
@jdrns @stephanie-cascade8 could you update this [screen](https://app.zeplin.io/project/6037b2f5d6cf497ddfe6e473/screen/603812fe191c299fc3b87388) with a proposition to highlight this Create item?

- [x] Also, there should be quotation marks around the company name. here it should say:  _CREATE "th" COMPANY_
![image](https://user-images.githubusercontent.com/55785823/111517985-f0643100-8755-11eb-83f2-94905e0236b2.png)

- [ ] Also, the "create" option should always appear I think. Currently, when the list is too long, we have to scroll to see the option.

**Comment by phpgeekfr** [comment]
> Filled in every info but can't sign up I think the problem is in the Company field.

fixed via https://github.com/blockframes/blockframes/pull/5263

**Comment by phpgeekfr** [comment]
@maltmayer regarding, `the "CREATE th COMPANY" line should look different from the list of existing companies. Maybe in bold? maybe have a separation line?`

is this ok ? 
![image](https://user-images.githubusercontent.com/1194344/111611713-08cb5e80-87dd-11eb-9c80-c37eedf76c26.png)

**Comment by phpgeekfr** [comment]
@maltmayer regarding ` Also, the "create" option should always appear I think. Currently, when the list is too long, we have to scroll to see the option.` Shout I put it in first position instead ? 
![image](https://user-images.githubusercontent.com/1194344/111612213-8c854b00-87dd-11eb-97fd-a760c5100dde.png)

**Comment by maltmayer** [comment]
> @maltmayer regarding, `the "CREATE th COMPANY" line should look different from the list of existing companies. Maybe in bold? maybe have a separation line?`
> 
> is this ok ?
> ![image](https://user-images.githubusercontent.com/1194344/111611713-08cb5e80-87dd-11eb-9c80-c37eedf76c26.png)

Looks great yes

**Comment by maltmayer** [comment]
> @maltmayer regarding ` Also, the "create" option should always appear I think. Currently, when the list is too long, we have to scroll to see the option.` Shout I put it in first position instead ?
> ![image](https://user-images.githubusercontent.com/1194344/111612213-8c854b00-87dd-11eb-97fd-a760c5100dde.png)

I'm not sure this make sense. what do you think @2amarkina  
Would it be possible to have it always displayed on the bottom of the box. I mean the box, not the list (that way even when you don't scroll down you see it)? That would be ideal.

**Comment by phpgeekfr** [comment]
> Would it be possible to have it always displayed on the bottom of the box. I mean the box, not the list (that way even when you don't scroll down you see it)? That would be ideal.

It will be hard to achieve this today, I don't know if this is even possible.  For me the fact that is  at the end of the results is not a big problem because if there are results, it means that the company he is looking for can be in the search results. If none of the results fit the user needs, he can create it at the end

**Comment by maltmayer** [comment]
> > Would it be possible to have it always displayed on the bottom of the box. I mean the box, not the list (that way even when you don't scroll down you see it)? That would be ideal.
> 
> It will be hard to achieve this today, I don't know if this is even possible. For me the fact that is at the end of the results is not a big problem because if there are results, it means that the company he is looking for can be in the search results. If none of the results fit the user needs, he can create it at the end

Okay I'm convinced. Let's keep it that way then

**Comment by 2amarkina** [comment]
i agree that if it's possible it's better to have "create" solution at the bottom : like at first we check for the existing companies and only then propose to create a new one.

It would be great to have it visible all the time, like stuck to the bord, but the most important is that it should stay when user continues to enter the company name and there are no more searching results and only possibility is to create a new company

**Comment by phpgeekfr** [comment]
> but the most important is that it should stay when user continues to enter the company name and there are no more searching results and only possibility is to create a new company
Yes this is fixed (not on staging yet)

**Comment by Jackseed** [comment]
@phpgeekfr, @maltmayer found a new one:
- [ ] Org validated email isn't triggered (template id `d-8c5f7009cd2f4f1b877fa168b4efde48`)

**Comment by phpgeekfr** [comment]
>Very unpleasant automated box appears. I figure it might be out of our control but if we could disable the automated suggestions, it would be GREAT as this is quite annoying:

I added ` autocomplete="off" ` that may prevent this but not sure (I don't have it on my PC)

**Comment by Jackseed** [comment]
- [ ] When clicking on "create xxx company", drop down should close
![3](https://user-images.githubusercontent.com/79836137/111596434-71aada80-87cd-11eb-9d88-288d8bd90780.gif)

**Comment by phpgeekfr** [comment]
>     * [x]  When clicking on "create xxx company", drop down should close

already solved

**Comment by Jackseed** [comment]
Comments from #5261 

### SIGN UP / "Thank you for joining us!"

- [ ] A snackbar showed up when I arrived on this page but didn't get the time to read it / screenshot. Should appear a bit longer.

- [ ] Change introduction text to:
"We care about security on the Cascade8 applications. Please validate your email to help us authenticate you. 
The ((app name)) Team will come back to you shortly concerning your Company Account creation request.
- [ ] Contact us should be underlined (I think) and clickable.
- [ ] There should be more space before all "i" information icons. There too close to the text.
- [ ] The refresh icons are confusing, we want to click on them to resend email. Or refresh page... They feel clickable. Could we have them clickable? If so, I think they should refresh the page.
- [ ] "Refresh your page" button should say "Refresh Page"
- [ ] "Refresh your page" button is too close to the Contact button (to me at least) 
![image](https://user-images.githubusercontent.com/55785823/111628957-125ec180-87f1-11eb-814c-b3da586e84f9.png)

- [ ] Change Profile Data tooltip to: "Fill in your Personal Information (First Name, Last Name...)"
![image](https://user-images.githubusercontent.com/55785823/111630075-438bc180-87f2-11eb-90dc-d20ed98e57d6.png)

- [ ] Change Organization Data tooltip to: "Fill in your Company Information (Activity, Country...)"
![image](https://user-images.githubusercontent.com/55785823/111630176-5ef6cc80-87f2-11eb-9972-5ba18bd0d323.png)

- [ ] Change Email Validation tooltip to: "Click the link provided in your verification email."
![image](https://user-images.githubusercontent.com/55785823/111630338-8baae400-87f2-11eb-86a2-e3d0befcfb22.png)

- [ ] Change Organization Approval tooltip to: "Please wait for the ((app name)) team to verify the company information you provided."
![image](https://user-images.githubusercontent.com/55785823/111630781-007e1e00-87f3-11eb-895c-69f953216aba.png)
