### ISSUE TITLE
Movie form - Publish movie doesn't work

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5268]
Issue from #5261

- [ ] I try to publish my movie vW8kyOnJKVafoKNG0vZr. It says movie online but the movie stays draft. It did that multiple times. Maybe it's just because I had multiple movie tunnel open? (need investigation @SamirTouira)
![image](https://user-images.githubusercontent.com/55785823/111509323-e68a0000-874c-11eb-92e0-7492c1622553.png)

**Comment by SamirTouira** [comment]
After have created a movie on staging and in my local environnement, this bug isn't there from my side. I also saw the movie ID vW8kyOnJKVafoKNG0vZr and tried to switch from "accepted" to "draft", and when I publish again this, is online with the "accepted" status. Cannot trigger it actually

**Comment by Jackseed** [comment]
Ok thanks then we close it
