### ISSUE TITLE
Movie form - When Review info filled in, Journal name should be mandatory

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5271]
url: /c/o/dashboard/tunnel/movie/5Z7LhR6CqRLdQ1ARS2qG/reviews#festival

Journal name should be mandatory when something one of the fields have been filled in. Same as Festival fields above.
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/5b027e16-a462-431d-a0f5-e825755b53db)

@Mussuranae @phpgeekfr can it break something for existing reviews without journal name?

**Comment by Mussuranae** [comment]
I don't think so, but the next time users will go through the movie tunnel, it will appear as a mandatory field. If the movie is already published, it shouldn't break anything. If the movie is a draft, and if users already registered some review without journal's name, it will say that the field is mandatory and the users won't be able to publish the film (I guess so, not sure at 100% ;) )

**Comment by Jackseed** [comment]
You're right, in fact that's exactly what happened with festivals so that's all good no need for migration
