### ISSUE TITLE
MF : Org logo not displayed

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#5273]
Logo is displayed in MF Marketplace Org details

![image](https://user-images.githubusercontent.com/8731418/111614925-2d87fc00-8806-11eb-9153-dc1e1e70962f.png)

However it is missing in marketplace home

![image](https://user-images.githubusercontent.com/8731418/111615028-48f30700-8806-11eb-9654-c1ea40871425.png)

**Comment by fritzschoff** [comment]
justed checked it out and there seems to be an issue with the request to imigix that fails
