### ISSUE TITLE
My Files - Org docs - Preview & delete bugs

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5290]
login: dev+howell-mxf@blockframes.io
url: https://staging.archipelmarket.com/c/o/dashboard/files

- [x] When clicking on preview, the modale while loading should keep the same size as when it's loaded to avoid weird behaviour

- [x] Delete doc doesn't work

![9](https://user-images.githubusercontent.com/79836137/111633453-cf531d00-87f5-11eb-958e-813ad337bba6.gif)

**Comment by pldespaigne** [comment]
> When clicking on preview, the modale while loading should keep the same size as when it's loaded to avoid weird behaviour

The modal take the space of it's content, and we cannot know the size of the content while it's not laded, that's why we have this strange behavior. I cannot change that, however I can put a `min-width` to reduce the weird resize.
What do you think @Jackseed

**Comment by Jackseed** [comment]
le's go for min-width
