### ISSUE TITLE
Video document icon

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5293]
Following @jdrns review she noted that we have icons for image and docs but not video. 

It would definitely worth to add it!

**Comment by jdrns** [comment]
@Jackseed The new icon can be found [here](https://drive.google.com/file/d/1JSrks2sUG38Z1U90qRoy5_kWNZd6eDWc/view?usp=sharing)

**Preview of the icon**
<img width="256" alt="Screenshot 2021-04-06 at 15 21 30" src="https://user-images.githubusercontent.com/79836137/113717287-c4e8bc80-96eb-11eb-985c-25f4dd214bee.png">

**Comment by Jackseed** [comment]
Thanks, dedicated dev issue over here #5548. I close this one
