### ISSUE TITLE
Notifications - Sort it chronologically within a day

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5294]
- [x] Activity feed notifications aren't chronological (last ones at the top)
<img width="1107" alt="Screenshot 2021-03-18 at 14 12 30" src="https://user-images.githubusercontent.com/79836137/111631892-38d22c00-87f4-11eb-983e-4088bf5c9754.png">

**Comment by phpgeekfr** [comment]
The label is incorrect I guess here :
![image](https://user-images.githubusercontent.com/1194344/111659518-99219780-880d-11eb-8886-960eb682b05c.png)
![image](https://user-images.githubusercontent.com/1194344/111659548-9fb00f00-880d-11eb-9e9b-843607c97192.png)
![image](https://user-images.githubusercontent.com/1194344/111659595-a8a0e080-880d-11eb-8a35-54cbac0f472b.png)


![image](https://user-images.githubusercontent.com/1194344/111659461-8d35d580-880d-11eb-8138-8b718e6eecc7.png)

**Comment by phpgeekfr** [comment]
Finally fixed in https://github.com/blockframes/blockframes/pull/5301 with @GrandSchtroumpf help
