### ISSUE TITLE
Text changes 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5298]
### Title homogenization 
**Movie Tunnel** 
- [x] snackbar text after clicking on Save (from "Movie saved" to "Title saved");

MF dashboard
- [x] Navbar - change "My Projects" for "My Titles"
![image](https://user-images.githubusercontent.com/14964443/111658891-0f71ca00-880d-11eb-84d0-23d0602bcc06.png)

- [x] change the meta-title from "Title page" to "My files" 
<img width="791" alt="title" src="https://user-images.githubusercontent.com/55499036/111503935-7d53be00-8747-11eb-95c5-a68a932c4d7d.png">

### EMPTY DASHBOARD HOMEPAGE / TITLES
- [x] Change Title from "You have no title yet." to "No title to display"
- [x] Change the bulk import text to from Import you titles in bulk" to "Import titles in bulk"
- [x] Change CTA text to: "Contact the ((app name)) team"
![image](https://user-images.githubusercontent.com/55785823/111637351-a0d74100-87f9-11eb-9403-4cf12d1b704d.png)

### EMPTY DASHBOARD TITLES

- [x] Add CTA "Contact Archipel Team" to match with Empty Dashboard Homepage.
![image](https://user-images.githubusercontent.com/55785823/111638122-56a28f80-87fa-11eb-862e-588d32ede551.png)

### ADD NEW EVENT
(for both small modale form & complete form view)
- [x] Add a title for the privacy section: "Privacy Settings"
- [x] Change text from "Accessible only on invitation (private event)" to "PRIVATE - upon invitation only"
- [x] Change text from "Do not show on Marketplace" to "SECRET - not listed on the Marketplace"
- [x] Change CTA text from "Add More details" to "More Details"

![image](https://user-images.githubusercontent.com/55785823/111770247-75f8f580-88aa-11eb-98b9-8c4f5d883998.png)

- [ ] tooltip should be closer from the icon and vertically aligned with the text
- [ ] tooltip text is too tight
- [x] Change text from "Only users with a direct link will be able to access your event."

![image](https://user-images.githubusercontent.com/55785823/111771253-bf961000-88ab-11eb-9779-5d0f105af1ee.png)

- [x] "Video Call link":
1. link is not good (replace /lobby by /session) 
2. Change text to "Direct link to Screening Room"
![image](https://user-images.githubusercontent.com/55785823/111772613-57482e00-88ad-11eb-8883-ec677c3290f2.png)

- [x] add tooltip to the icon copy for invitations. Text proposition "Copy Guests' Emails" 
<img width="1146" alt="Снимок экрана 2021-03-18 в 11 44 09" src="https://user-images.githubusercontent.com/55499036/111613869-44ffbe80-87df-11eb-8f80-e7031499173b.png">

### Auth flow
- [x] Couldn't take a screenshot but when creating an account there is a snackbar saying something like "Your account have been created" it should be "Your account has been.."

### Movie view marketplace
- [x] "Add to Wishlist" instead of "Move to Wishlist"
![image](https://user-images.githubusercontent.com/14964443/111998554-697bd380-8b1c-11eb-9cba-fa79f124fd4d.png)

- [x] Change "Watch" to "View" when it's a pdf document > "View Script" "View Presentation Deck" "View Moodboard"
![image](https://user-images.githubusercontent.com/14964443/112005963-8b2c8900-8b23-11eb-8d14-4b7e60237dc1.png)

**Comment by Mussuranae** [comment]
> 
>     * [ ]  tooltip should be closer from the icon and vertically aligned with the text
> 
>     * [ ]  tooltip text is too tight
> 
> 
> ![image](https://user-images.githubusercontent.com/55785823/111771253-bf961000-88ab-11eb-9779-5d0f105af1ee.png)
>

The only things I can't do are about the typography of the tooltip. If I change something it will impact all tooltips in the app, and we need first to rework typo with Stéphanie. I think it can wait for the good moment to rework all typos.

**Comment by Jackseed** [comment]
alright
