### ISSUE TITLE
My Files - Org docs - Enable array of documents

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5310]
- [x] for the company documents we should be able to add many documents (have a list of documents). but for the moment it seems to be that only one document can be uploaded 
![list documents](https://user-images.githubusercontent.com/55499036/111595801-ca2da800-87cc-11eb-93a2-0dd7ce5fe235.gif)

**Comment by pldespaigne** [comment]
also fixed by #5341
