### ISSUE TITLE
Dashboard title list - Sort titles alphabetically 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5314]
url /c/o/dashboard/title

- [ ] Title list should be ordered alphabetically by default I think. We can't guess the logic here (@SamirTouira)
![image](https://user-images.githubusercontent.com/55785823/111515791-8054ab80-8753-11eb-8821-675105f01b4f.png)

**Comment by SamirTouira** [comment]
Next week is my school week. I have not been able to find the solution to fix this before my school week sorry. I did not understand the code side that make alphabetic sort. It was too complex for me.

**Comment by pldespaigne** [comment]
@SamirTouira I found a simple way to do it, we can do that together when you come back, it will be a good exercise !
