### ISSUE TITLE
Media - error filePath and metadata at null when we add simultaneously 2 or more images

### ISSUE THREAD

**Issue by SamirTouira** [blockframes/blockframes#5317]
url: http://localhost:4200/c/o/dashboard/tunnel/movie/KvW9rnQqsPEbEcPeMN29/media-images (you can take or create any movies you want)

account: dev+austen-crh@blockframes.io (same remark here)

![image](https://user-images.githubusercontent.com/52285231/111784184-61712900-88bb-11eb-9a84-ab93c024127c.png)

**Steps to reproduce this issue:**

- In the Images tab and in the Promotional Elements, just add 2 images simultanely or more
- Save before moving into Last Step tab
- You can see yourself some images that you have added (1 or more) are missing
- Click on the edit button to return to the Images tab in the Promotional Elements
- Try to save and/or delete an image. The error message will appears

(the metadata error message comes when we try to save, and the filePath message error comes when we try to delete an image)

If you refresh the page, all seems good, but it can be embarassing on users side

**Comment by pldespaigne** [comment]
fixed by #5358
