### ISSUE TITLE
Edit Meeting Bug

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#5325]
> moved from #5307 

>strange bug, when uploaded new documents to share in the edit meeting space, for seller they are shown correctly, but for the buyer there was the modal "are you sure to quite the meeting".
![image](https://user-images.githubusercontent.com/5858657/111819674-e6bb0480-88e0-11eb-9a63-00ca3e8ff745.png)

This bug happen when a seller is editing meeting files in the dashboard event page while the corresponding meeting is ongoing in a separate browser tab.
This caused by the edit page that will over-right the meeting event in db with the value of the event form, but the meeting event form doesn't have fields for attendees. So when the user click on "Save" the update actually delete all ongoing attendee from the meeting thus triggering a redirect (and the confirm dialog) on the buyers side.

**Comment by pldespaigne** [comment]
After some investigation, this will be pretty hard to fix because the app has never been built to support simultaneous browser tabs.
So after some discussion with @Jackseed, we decided to not include this in release 2.3

**Comment by Jackseed** [comment]
@pldespaigne is it still an issue with your last fixes?

**Comment by pldespaigne** [comment]
Yup, it come from the way the edit form is done.
I'm not sure it's worth changing the behavior of the form though, because it will pretty complex to do and also it means that now we want multi-tabs support ???

**Comment by Jackseed** [comment]
@pldespaigne Idk what multi-tabs support would mean/imply for the rest of the apps but here it could happen since, as a user, you don't want to leave the meeting page while adding files. 
Though I definitely think that we can live with that bug for a while, couldn't we fix it by changing a bit the data structure? 

@GrandSchtroumpf some advice here?

**Comment by pldespaigne** [comment]
> but here it could happen since, as a user, you don't want to leave the meeting page while adding files.

You don't need to leave the meeting to do that. That's exactly why we added the big blue plus button

![image](https://user-images.githubusercontent.com/5858657/113832017-7dfcd480-9788-11eb-8fab-42fbf64fb6bf.png)
