### ISSUE TITLE
Meeting Lobby / Initials are really big, not really aesthetic

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5334]
Recommendations from @jdrns to contact if necessary: 
- [ ] Change font size to 24px 
- [ ] I could find a y position at 64 in the inspector, and 59 would be perf but definitely requires test with a dev

<img width="1440" alt="Screenshot 2021-07-05 at 09 29 14" src="https://user-images.githubusercontent.com/79836137/124433851-7b078500-dd73-11eb-8ddc-5213d59595aa.png">

**Comment by jdrns** [comment]
Recommendations: 
- [ ] Change font size to 24px 
- [ ] I could find a y position at 64 in the inspector, and 59 would be perf but definitely requires test with a dev

<img width="1440" alt="Screenshot 2021-07-05 at 09 29 14" src="https://user-images.githubusercontent.com/79836137/124433851-7b078500-dd73-11eb-8ddc-5213d59595aa.png">

**Comment by RemcoSimonides** [comment]
@RemcoSimonides Create dev issue

**Comment by phpgeekfr** [comment]
@SamirTouira check with @jeremie74 if he can work on this or not
