### ISSUE TITLE
Marketplace navbar - icons not aligned 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5335]
Icons on the left (calendar & wishlist) should be a bit more top to be aligned with invitations and notifications
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/bd671098-3142-4679-992c-e23ae3f0b40a)

**Comment by RemcoSimonides** [comment]
![image](https://user-images.githubusercontent.com/27687382/116075945-e2c69300-a693-11eb-8c38-3a51473d8656.png)
I don't see any difference. Maybe it's not visible anymore because of the icon change? Re-open this issue if you disagree @Jackseed
