### ISSUE TITLE
UI Review

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5336]
Don't use that issue before we start the release process on AC. I put it there not to forget about it and test it again when we'll be ready

Comments from @jdrns 

### Library / Filter avails

- [x] In territories, when trying to type in a country, two clics are required. First click open the drop down but if trying to type then, it displays a weird behavior (scroll the list down but doesn't display letters typed). Requieres second clic on the field to start typing 
![11](https://user-images.githubusercontent.com/79836137/111752003-720ea880-8895-11eb-8a6e-1859e23f21f2.gif)

- [x] When searching for a country, if I [√] that country it will [√] the whole continent if that country is the only result, but then when deleting the search, it puts the continent box in [-] state. Can be confusing to users
![10](https://user-images.githubusercontent.com/79836137/111749310-dfb8d580-8891-11eb-9a0f-4be344a654c6.gif)

- [x] Bug after clearing the filter avails (forced to refresh page)
<img width="1440" alt="Screenshot 2021-03-19 at 09 32 19" src="https://user-images.githubusercontent.com/79836137/111752503-15f85400-8896-11eb-9426-11aa6d3a00df.png">

### Library 
- [x] Space missing between the different directors names (or after the comma). Should be "Ludovic Boukherma, Zoran Boukherma" not "Ludovic Boukherma,Zoran Boukherma"
<img width="327" alt="Screenshot 2021-03-19 at 12 10 00" src="https://user-images.githubusercontent.com/79836137/111771594-2fa49600-88ac-11eb-9cd3-64fe5e69fbc9.png">

### Library / Movie page

- [x] Movie PG: Psycho Goreman has an undefined value in the Genres section 
<img width="346" alt="Screenshot 2021-03-19 at 12 24 07" src="https://user-images.githubusercontent.com/79836137/111773318-519f1800-88ae-11eb-8214-062e80a7bec6.png">
<img width="343" alt="Screenshot 2021-03-19 at 12 24 22" src="https://user-images.githubusercontent.com/79836137/111773325-549a0880-88ae-11eb-8123-60ca5cdcb55d.png">

- [x] Should be "Add to Wishlist" not "Move to Wishlist"
<img width="997" alt="Screenshot 2021-03-19 at 14 35 49" src="https://user-images.githubusercontent.com/79836137/111788578-8a47ed00-88c0-11eb-8b3c-1a6b35ccf327.png">

### Partners / partners page
- [x] If no line up, should we remove the title or say something like "there's no line up yet" so that the user knows that it's not that the content didn't load 
- [x] No button "Contact" on partners page to contact? (cf ""Ask for a meeting" in Market)
<img width="1440" alt="Screenshot 2021-03-19 at 12 19 05" src="https://user-images.githubusercontent.com/79836137/111772797-8f4f7100-88ad-11eb-86a3-dac7be754597.png">

### Dashboard / My titles 
- [x] Some links don't work to see the titles 
![12](https://user-images.githubusercontent.com/79836137/111756799-eb5cca00-889a-11eb-8ff6-dfdfd2ce7366.gif)

- [x] It's written "All projects", shouldn't it be "All titles"?
<img width="1040" alt="Screenshot 2021-03-19 at 10 06 46" src="https://user-images.githubusercontent.com/79836137/111756717-d1bb8280-889a-11eb-9c86-e1d28a1418d5.png">

- [x] Space is missing below blocks of sales revenue and footer 
<img width="1171" alt="Screenshot 2021-03-19 at 14 26 09" src="https://user-images.githubusercontent.com/79836137/111787453-3c7eb500-88bf-11eb-9f43-654911996829.png">

**Comment by Jackseed** [comment]
> * When searching for a country, if I [√] that country it will [√] the whole continent if that country is the only result, but then when deleting the search, it puts the continent box in [-] state. Can be confusing to users
>   ![10](https://user-images.githubusercontent.com/79836137/111749310-dfb8d580-8891-11eb-9a0f-4be344a654c6.gif)

@jdrns @2amarkina re that comment could you confirm the behaviour you'd like please? 
If I understand correctly it would be **not to** select the region when a country inside is selected? the side effect I can see is that, if the user closes the expansion panel s/he won't know that there is a selected country in it

![image](https://user-images.githubusercontent.com/14964443/113308572-98f1c380-9306-11eb-9e23-616a92fd6fdd.png)

**Comment by Jackseed** [comment]
> * No button "Contact" on partners page to contact? (cf ""Ask for a meeting" in Market)
> 
> <img alt="Screenshot 2021-03-19 at 12 19 05" width="1440" src="https://user-images.githubusercontent.com/79836137/111772797-8f4f7100-88ad-11eb-86a3-dac7be754597.png">

we prefer not to for now as buyers could then bypass us and buy directly from seller

**Comment by jdrns** [comment]
> > * When searching for a country, if I [√] that country it will [√] the whole continent if that country is the only result, but then when deleting the search, it puts the continent box in [-] state. Can be confusing to users
> >   ![10](https://user-images.githubusercontent.com/79836137/111749310-dfb8d580-8891-11eb-9a0f-4be344a654c6.gif)
> 
> @jdrns @2amarkina re that comment could you confirm the behaviour you'd like please?
> If I understand correctly it would be **not to** select the region when a country inside is selected? the side effect I can see is that, if the user closes the expansion panel s/he won't know that there is a selected country in it
> 
> ![image](https://user-images.githubusercontent.com/14964443/113308572-98f1c380-9306-11eb-9e23-616a92fd6fdd.png)

Ideally, if not ALL countries from a region are selected, the region should display [—] (which is already the case) expect while doing a search. For example in the gif above, when typing and [√] France, Europe goes [√] and then goes [—] when deleting the search. But it might not be technically possible to fix. What do you think @2amarkina ?

**Comment by 2amarkina** [comment]
> > > * When searching for a country, if I [√] that country it will [√] the whole continent if that country is the only result, but then when deleting the search, it puts the continent box in [-] state. Can be confusing to users
> > >   ![10](https://user-images.githubusercontent.com/79836137/111749310-dfb8d580-8891-11eb-9a0f-4be344a654c6.gif)
> > 
> > 
> > @jdrns @2amarkina re that comment could you confirm the behaviour you'd like please?
> > If I understand correctly it would be **not to** select the region when a country inside is selected? the side effect I can see is that, if the user closes the expansion panel s/he won't know that there is a selected country in it
> > ![image](https://user-images.githubusercontent.com/14964443/113308572-98f1c380-9306-11eb-9e23-616a92fd6fdd.png)
> 
> Ideally, if not ALL countries from a region are selected, the region should display [—] (which is already the case) expect while doing a search. For example in the gif above, when typing and [√] France, Europe goes [√] and then goes [—] when deleting the search. But it might not be technically possible to fix. What do you think @2amarkina ?

Yes, i confirm that we talk only about the  behavior of an "icon" inside the checkbox.  We still need to select the region, but improvement is :  show [√]  only when _all_ the countries are selected. So, if a user makes a search and in _Europe_ region there is only _France_ shown, other countries still exist but they are hidden, so we need to use  [—] icon (the aim is to avoid the confusion that all the Europe is chosen).

If it's pretty difficult or takes much time we can put it aside for the moment.

**Comment by Jackseed** [comment]
Ok my bad I finally got your initial comment @jdrns. Honestly I didn't see that there were 2 different icons [√] vs [—] when I used that list 😳 
I'll check with devs if that's something we can change

**Comment by Jackseed** [comment]
Everything has been transferred to devs so I close this issue. If you find some new problems, you can either re-open it or open a new one and tag me so I check it asap
