### ISSUE TITLE
PDF Export for deliveries

### ISSUE THREAD

**Issue by lsenta** [blockframes/blockframes#534]
@Jackseed please review this ticket.

Open questions:
- [x] When do we trigger the PDF export (before the transaction to submit the hash / after the transaction with the QR code)?
- [x] Where / How to we retrieve the PDF file? Authorizations to access the file?

Tasks:
- [x] Simple PDF export with dummy data
- [x] PDF export with actual delivery data
- [x] PDF export integrated in the delivery app flow
- [ ] Nice PDF export

**Comment by lsenta** [comment]
refs:
https://github.com/bpampuch/pdfmake/blob/0.1/dev-playground/server.js
https://pdfmake.github.io/docs/getting-started/server-side/examples/

**Comment by lsenta** [comment]
Left:
- [ ] Implement security & data input protection. Will implement once we have authorizations on the backend

**Comment by Jackseed** [comment]
issue finished, improvements to come later
