### ISSUE TITLE
Change Org invitation email template-ids

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5340]
We currently use 3 different emails when an org invite a member, one per app:
- AC template id: `d-a34ce9ea59c5477f9feae8f556157b6b`
- AM template id: `d-f0c4f1b2582a4fc6ab12fcd2d7c02f5c` 
- MF template id: `d-a34ce9ea59c5477f9feae8f556157b6b`

Now everything related to apps have been changed to variables so we can switch to only one template used for every app. 

The correct id is the one currently used for AM:  `d-f0c4f1b2582a4fc6ab12fcd2d7c02f5c`

**Comment by RemcoSimonides** [comment]
@Jackseed do you want me to delete or deactive the templates in SendGrid too?
