### ISSUE TITLE
Remove old link on movie

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#5350]
There is still some old properties on the movie regarding links for video. Now we can upload video, it should be good to clean them everywhere in the project.
![image.png](https://images.zenhubusercontent.com/5d51508f6f935933f7158b07/1a4a0ffe-0c6c-48ea-9888-2e965ad536c5)

**Comment by RemcoSimonides** [comment]
Don't we still support this for movies that were created before it was possible to upload videos?

**Comment by phpgeekfr** [comment]
I think we  still need to keep it for some time since old movies are still using this
