### ISSUE TITLE
E2E - Add to bucket

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5353]
### Description
We want to test that users are able to add titles to their bucket with corresponding terms.

### Context 
BDD based on these contracts & related films https://docs.google.com/spreadsheets/d/1KHKdN9HAzDUfbKaoSi6_OHxCjMsMd-vQh0VL_qKSKls/edit#gid=0
MovieId `bR4fTHmDDuOSPrNaz39J` should be added as a title from Pulsar Content orgId (`e1VXeusNJK6pb8kmVnUn`)

### Scenario
1. Connect with marketplace user
2. Go to title list 
3. Fills in avails filter:
- Dates: 01/01/2025 - 12/31/2026
- Media: S-VOD
- Territories: World
- Exclusivity: Yes
4. Add "Movie 2" to bucket (should be listed)
5. Add "Movie 4" to bucket
6. Add "Movie 3" to bucket
7. Go to bucket page
8. Check that there are 2 cards for "Movie 2" (one for SVOD, another one for A-VOD) and one card for the other titles

### Future upgrades
New edge cases should be added to that test when we'll be able to create discontinued mandates (#5267):
- 2 orgs selling the same title (media will come from 2 different companies)
- A mandate includes 2 discontinued terms 
- 2 org selling the same title with discontinued terms (mixing the 2 other edge cases)

**Comment by Jackseed** [comment]
End of the test:
9. Select US Dollar for currency
10. Add 5,000 to Mother Schmuckers 
11. Add 10,000 to Gaza mon amour
12. Add 20,000 to Bigfoot family
13. Check if total price === $35,000
14. Click on Create offer
15. On the modale, select specific terms and fill in with "Payment schedule: 20% each semester starting at the following from signature date"
16. select delivery list and fill in with "Prores file deliver through cloud"
17. Click on Send your offer
18. Check that page include "Your contract offer has been successfully sent"

**Comment by Jackseed** [comment]
@xmano re the modifications we discussed to fit the excel import test, I've edited the names of the movie to select:
- "Mother Schumckers" > Movie 2
- "Gaza mon amour" > Movie 4 
- "Bigfoot famliy" > Movie 3

**Comment by xmano** [comment]
Updating the `create-bucket` spec to work with this.

**Comment by xmano** [comment]
![image](https://user-images.githubusercontent.com/8731418/116117209-9bfb8c00-a6d9-11eb-92b8-786b57055a55.png)

**Comment by xmano** [comment]
https://github.com/blockframes/blockframes/pull/5623

**Comment by cams-goussale** [comment]
Hello @Jackseed here is a suggestion of E2E when a title shared by 2 orgs receives 2 offers. Can we review it before creating an issue?

## Context
Org-1 wptWZnXiAzjIJorVbycy has 5 titles with some sales/mandates (see excel)
Org-2 ySt7UnrX3zaRUrwPeJTw has 2 titles with some sales/mandates (see excel)

Dashboard user of org-1 (seller 1) rzf1Zw3fxTXYp56UlJj01pSbaCG3
Dashboard user of org-2 (seller 2) ZrXKPJ3kq5fCOx4E0jofepfTOTZ2
Marketplace user (buyer) XB46CFAuXuYUUErx1DYH4BUbLpk2

## Scenario 2 (Org1 and Org2 get an offer on same title)

_Same beginning as above_
1. Connect with Marketplace user
2. Go to title list
3. Fills in avails filter:
	- Dates: 01/01/2025 - 12/31/2026
	- Media: S-VOD
	- Territories: World
	- Exclusivity: Yes
4. Add "Movie 2" to bucket (should be listed)
5. Add "Movie 4" to bucket
6. Add "Movie 3" to bucket
7. Go to bucket page

_New_
8. Click on "Add Rights" under "Movie 2" card
9. Fills in avails filter:
	- Dates: 01/01/2025 - 12/31/2026
	- Media: A-VOD
	- Territories: World
	- Exclusivity: Yes
10. Check that there are 2 cards for "Movie 2" (one for SVOD, another one for A-VOD) and one card for the other titles
11. Add price "5000" to the first card of "Movie 2".
12. Add price "20000" to "Movie 3".
13. Leave "Movie 4" and the 2nd card of "Movie 2" empty.
15. Check if total price == €25,000
14. Click "Create Offer". Click "Send Your Offer"

_Here we check Buyer receives the deal_
13. Click on "See Offers & Deals".
14. Check there is 1 deal in the table with status "New", number of titles "4", total price == €25,000
15. Open the deal and check there is 4 rows in the Contracts table: 2 for "Movie 2", 1 for "Movie 3", 1 for "Movie 4"

_Here we check Seller 1 receives the offers_
15. Connect with Dashboard user of org-1 and go to My Sales.
16. Check there is 3 offers with Status "Pending"

_Here we check Seller 2 receives the offer_
17. Connect with Dashboard user of org-2 and go to My Sales.
18. Check there is 1 offer with Status "Pending"

_Here we check CRM receives the deal_
19. Connect on CRM, go to the Offers list.
20. Check there is 1 deal in the table with status "New", number of titles "4", total price == €25,000
21. Open the deal and check there is 4 rows in the Contracts table: 2 for "Movie 2", 1 for "Movie 3", 1 for "Movie 4"
