### ISSUE TITLE
Notifications - improvements

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5356]
- [x] New texts for notifications have been updated here https://docs.google.com/spreadsheets/d/1b1K7YfnquxnfCgGGPxIz5ZNIjr9eK_bUrRJqLvPYGIk/edit#gid=1590038159
It concerns only lines in orange

- [x] `d-f84d8c5a70884316870ca4ef657e368f` is spawned for every new member in the org but in fact it would be better if it was used only when a user accepts an invitation to join an org.
Cause here it's sent also for requests being accepted but we already have 3 mails related to requests, it's a bit too much

- [x] Small improvement for Event request refused `d-4e36dd72f50d4e7e9ec738476efa84a9`, would be good to add a `pageUrl` that leads to the marketplace org view (/c/o/marketplace/organization/orgId/title) of the organizer org

- [x] We need a more accurate variable for app access email, it shall give us the new app name that has been given during the update. Send email for every app the org gained access to. Also, update notification text. (issue #5471)

- [x] Don't send email if the app access are removed and not added

- [x] Add app name and organization name in email the to cascade8 admin when a user/org requests access to an app

**Comment by RemcoSimonides** [comment]
> - [ ] d-f84d8c5a70884316870ca4ef657e368f is spawned for every new member in the org but in fact it would be better if it was used only when a user accepts an invitation to join an org.
Cause here it's sent also for requests being accepted but we already have 3 mails related to requests, it's a bit too much

This one is actually quite difficult because the notification is triggered when length of array of `userIds` is changed on org update. How important is it to remove this notification? 😅
