### ISSUE TITLE
File explorer - sorting

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5357]
Comments from @maltmayer - 2.3 Release reviews (#5261)
- [ ] the files in each movie are ordered alphabetically. they should not, it does not make sense
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/6a3d9bbc-72aa-466d-a1ca-ec4f3dd95695)

I think it should be in more logical order:
- Poster
- Banner
- Images
- Screener
- Sales Pitch
- Other Videos
- Scenario
- Presentation Deck
- Moodboard / Artistic Deck
- Notes & Statements

Comment from @2amarkina 
>  i would propose to put the folders first and then put the single documents in alphabetical order OR put everything as they appear on the movie tunnel

Comment from @pldespaigne 
> having a predefined/hardcoded order will be really hard or ugly

 But on the contrary, the movies should be ordered alphabetically in the File storage. We can't guess the logic here: 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/5779ab7b-9ad6-4e6a-8c6c-40b974b2243c)

PL:
> PL: It's currently ordered by ID, probably possible with a sort function or an order clause in the query, this might have side effects though

**Comment by Jackseed** [comment]
Re the 1st point there are too many different suggestions, @pldespaigne is there an option that is easier than the others on a technical perspective?
(arbitrary vs movie form order vs folders then docs)
I think it could also be by document types like: folders, video, images, pdf

**Comment by maltmayer** [comment]
> Re the 1st point there are too many different suggestions, @pldespaigne is there an option that is easier than the others on a technical perspective?
> (arbitrary vs movie form order vs folders then docs)
> I think it could also be by document types like: folders, video, images, pdf

Sorry to insist but to me it is confusing to have the folder "images" separated from poster image and banner image, same for "Videos" folder separated from screener and sales pitch video. 
This is my business opinion. 
Of course, let's go for what's easier on a technical perspective. But if it comes down to decide on the order ourselves, I don't agree with the folders then docs order. I think it con't be logical (confusing even) for the user.

**Comment by Jackseed** [comment]
@maltmayer looks indeed more intuitive to me, @2amarkina what do you think?

@pldespaigne any technical constraint we should be aware of here?

**Comment by 2amarkina** [comment]
> @maltmayer looks indeed more intuitive to me, @2amarkina what do you think?
> 
> @pldespaigne any technical constraint we should be aware of here?

Ok, if we put all the elements together it will give us this: 

**Folder "Images"** 
- Poster
- Banner 
- folder "Promotional Images"
     - Img1...
     - Img2..

**Folder "Videos"** 
- Sales Pitch 
- Screener 
- folder "Other Videos" 
     - Video1...
     - Video2..

**Folder "Promotional Files"** 
- Presentation Deck 
- Moodboard 
- Scenario 

**Folder "Notes & Statements"** 
_(this one could also go in "Promotional Files" as sub-folder)_ 
- N&S1...
- N&S2...


This seems ok to me, if possible to implement.

**Comment by maltmayer** [comment]
> > @maltmayer looks indeed more intuitive to me, @2amarkina what do you think?
> > @pldespaigne any technical constraint we should be aware of here?
> 
> Ok, if we put all the elements together it will give us this:
> 
> **Folder "Images"**
> 
> * Poster
> * Banner
> * folder "Promotional Images"
>   
>   * Img1...
>   * Img2..
> 
> **Folder "Videos"**
> 
> * Sales Pitch
> * Screener
> * folder "Other Videos"
>   
>   * Video1...
>   * Video2..
> 
> **Folder "Promotional Files"**
> 
> * Presentation Deck
> * Moodboard
> * Scenario
> 
> **Folder "Notes & Statements"**
> _(this one could also go in "Promotional Files" as sub-folder)_
> 
> * N&S1...
> * N&S2...
> 
> This seems ok to me, if possible to implement.

Can we do Folders and sub folders ??

**Comment by 2amarkina** [comment]
> > > @maltmayer looks indeed more intuitive to me, @2amarkina what do you think?
> > > @pldespaigne any technical constraint we should be aware of here?
> > 
> > 
> > Ok, if we put all the elements together it will give us this:
> > **Folder "Images"**
> > 
> > * Poster
> > * Banner
> > * folder "Promotional Images"
> >   
> >   * Img1...
> >   * Img2..
> > 
> > **Folder "Videos"**
> > 
> > * Sales Pitch
> > * Screener
> > * folder "Other Videos"
> >   
> >   * Video1...
> >   * Video2..
> > 
> > **Folder "Promotional Files"**
> > 
> > * Presentation Deck
> > * Moodboard
> > * Scenario
> > 
> > **Folder "Notes & Statements"**
> > _(this one could also go in "Promotional Files" as sub-folder)_
> > 
> > * N&S1...
> > * N&S2...
> > 
> > This seems ok to me, if possible to implement.
> 
> Can we do Folders and sub folders ??

Not sure about that. Needs the tech review, but i thought it was what you're talking about not separating the banner and poster  from images, for example. 

If sub-folders are not ok, we can just follow that order for the elements that have common type: images, video, promo elements and notes at the end, as proposed above. 

> I think it should be in more logical order:

Poster
Banner
Images
Screener
Sales Pitch
Other Videos
Scenario
Presentation Deck
Moodboard / Artistic Deck
Notes & Statements

**Comment by pldespaigne** [comment]
Sub folder seems doable, ordering also but it requires ugly code I think.
@GrandSchtroumpf what are you thoughts on that ?

**Comment by GrandSchtroumpf** [comment]
@2amarkina @maltmayer @Jackseed we can have subfolder AND hardcode the order which means that : 
- items inside a folder/subfolders will be ordered has we want (Poster > Banner > Images > Screener > ...)
- titles will be display in the order we query them (by id).

If we go for that we will not update the query to order title differently as it'll create multiple indexes and increase a lot complexity.
Could you validate this so that @pldespaigne can update it ?

**Comment by maltmayer** [comment]
I'm up for it if we all agree, but with the following texts:

- Folder "Images"
   - Poster
   - Banner
   - Folder "Other Images"

- Folder "Videos"
   - Screener
   - Sales Pitch
   - Folder "Other Videos"

- Folder "Other Documents"
   - Presentation Deck
   - Moodboard
   - Scenario
   - Folder "Notes & Statements"

**Comment by Jackseed** [comment]
Looks good to me
