### ISSUE TITLE
Org without users

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#5371]
There is some organizations on prod that have 0 user (userIds empty).
We can add this case on the cleaning script to remove properly those organizations.
![image.png](https://images.zenhubusercontent.com/5d51508f6f935933f7158b07/cbf47ebc-0787-47b1-b063-438104778a0f)

**Comment by phpgeekfr** [comment]
Currently, the db-cleaning script  is executed during upgrade process with maintenanceMode set to `true`.
In this context, document deletion is not triggering any 'onDocumentDelete' methods in backend-functions.

This made me realize that some deletions performed  during execution of this script are not deleting related document in cascade (IE: if I remove an user, I also want to remove logo on storage, delete notifications linked to this users etc..).

So to have a good cleaning-script, related document should be deleted also but this require a huge refactoring to allow interaction with bucket, algolia, jwplayer etc.. outside of backend-functions.

We could also call this db-cleaning script when app is not in maintenanceMode but this can be very risky as we don't know  all the sides effects and this cannot be fully tested with unit-testing.

My suggestion is to let the script as it is for now (what we does not handle right now  is media deletion when we delete users but there is no other side effect).

Regarding orgs without users, there is only 4 in production, we could delete them manually.

Regarding other documents that may be deleted during db-cleaning script, we need to check how we can manage this cleanly.

**Comment by Jackseed** [comment]
orgs manually deleted 👍
