### ISSUE TITLE
New icon for promotional pdf

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5391]
We use the video icon for pdf documents and that's not really accurate, we should replace it for something closer to a document
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/3e52ca48-5b41-462c-8244-2416fdebeeeb)

**Comment by jdrns** [comment]
@Jackseed there is already an existing icon used in different places (ex: movie form)
In the depository assets folder, you can find it by the name **document.svg**

**Preview of the icon:** 
<img width="258" alt="Screenshot 2021-04-01 at 15 50 44" src="https://user-images.githubusercontent.com/79836137/113304151-06e7bc00-9302-11eb-981d-90279982ba70.png">

**Comment by Jackseed** [comment]
cool thanks 👍
