### ISSUE TITLE
V1 & V2 Archipel Content screens

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5395]
After MVP launch (April 7th), we'll make a short-sprint break before going back to new implementation on Archipel Content. 

The focus for that next V1 version will be avails tab on the marketplace title view. 

Wireframes have been validated and shall be transformed into screens. It includes:

### Avails
- [x] Map view (beware of colour layers, check with devs)
[zeplin](https://zpl.io/aN6q1ZD)
- [x] Expansion panel contracts (jus below the map)
[zeplin (from this screen)](https://zpl.io/2p8rdll)
- [x] Avails form (left panel on the avails tab) - **1st version will be without flexibility and time period, only exact dates**
[zeplin](https://zpl.io/aN6q1ZD)
### Selection
- [x] Holdback form and add button
[zeplin](https://zpl.io/aM67153)

### Avails
- [x] Calendar view (will be fully custom, thus we need to remain "basic" to make it doable; beware of numerous states (hovered, available, not available, disabled,...)) 
[zeplin](https://zpl.io/VOvopkL)
[behaviour to comment and review ](https://github.com/blockframes/blockframes/issues/5395#issuecomment-818795113)

### CRM - Package list & view
Usually we don't make screens for CRM but here it will be the first contract list to build out of 3 (also for dashboard + marketplace). It means that we shall try to use the same components as much as we can and this will be the first to be implemented. 
- [x] Package list
- [x] Package view
- [x] Interactions (status change, acceptation,...)
https://zpl.io/bL9P4OB

**Comment by Jackseed** [comment]
@jdrns Calendar updates to include:
- state when user starts a period and then go back in time
- state when user hovers and/or selects an unavailable month or that include an unavailable month
both screens & text to explain these behaviours are needed for clarity

**Comment by jdrns** [comment]
## Calendar ##
Screens with the new calendar are ready [here](https://zpl.io/bl3rPDz). 

To help understanding the interaction, a prototype is available [here](https://invis.io/AV10QXMBN3HP). 
Scenario: For start date, hover Jan 2022 then Feb 2022 then select Feb 2022. For end date, hover Mar 2022 then Apr 2022 then select Apr 2022.

After discussion with @2amarkina, regarding the 'error behaviours', we agreed on the following:
### Correct behaviour ###
- Start date
On hover: Cell shows ‘start’
On click: Cell is selected as start date
- End date (posterior to start date)
On hover: Cell shows ‘end’
On click: Cell is selected as end date (and modal opens)

**Preview**
![1](https://user-images.githubusercontent.com/79836137/115029561-64653680-9ec6-11eb-94aa-d0fae0381db6.gif)


 ### Error behaviours after start date selected ###
On hover on the ‘correct’ dates (as in the ones that are possible to select), the cells show “end”. 
On click the cell becomes the end date.

- If the start date is selected and user try to select an anterior date: 
On hover: Cell will show “start” 
On click: Cell will become the new start date

**Preview**
![2](https://user-images.githubusercontent.com/79836137/115029705-8bbc0380-9ec6-11eb-8228-1d9e59204304.gif)



- If the start date is selected and user try to select an end date that is separated by unavailable dates
On hover: Cell will show “start” 
On click: Cell will become the new start date

**Preview**
![3](https://user-images.githubusercontent.com/79836137/115029722-8f4f8a80-9ec6-11eb-9fdb-dc7894183ade.gif)


 ### Other error behaviours ###
- In the case of the user trying to select a date that isn’t available: 
On hover: No action
On click: Snackbar saying 'not available'

- In the case of the user trying to select a date that isn’t licensed: 
On hover: Tooltip saying 'contact seller' 
On click: Snackbar saying 'not licensed' + Action 'contact seller' inside snackbar

**Comment by Jackseed** [comment]
Thanks @jdrns I'll make a review for Calendar on Zeplin, gif proto are great!

Business review made on world map screens, @stephanie-cascade8 @jdrns please have a look this week to update it

**Comment by stephanie-cascade8** [comment]
Here are some corrections to make after the dev review with françois yesterday (april.22)
Changes are being made on zeplin mockups and the calendar invision prototype.

- [ ] butons (single territory and multi) should be outside the surface.
- [ ] the map legend has to present at any state (all the time)
- [ ] the mat-button bellow the map ("add territories") should be outside the surface too.
- [ ] Tooltips on the legend has to be tested. Not sure if possible with leaflet. If not possible we decided with Anastasiia to take it off.
- [ ] the mat-button "add..." bellow the map should also be present all the time to avoid a change of height on the map and visual problems. It will be disabled in the initial state.
- [ ] in the rights panel take off the edit button.
- [ ] Correct the expansion pannel in our compoenents (françois will send the override css we have). It should be bold body-2 and have shadows behind it's background when open.
- [ ] On the calendar, we suggested to have a blur around the interaction's space when the user has clicked on a date. That way, he can click outside the zone to cancel his selection.
- [ ] After selecting the dates, and after managing them in the popup the calendar should return to zero.

**Comment by 2amarkina** [comment]
for the last comment : 
- the pop-up should disappear (to validate one more time avec Vincent), but it's necessary to avoid entering into "partially available situation"  

(possible solution: keep pop-up; show a month as available if >15 days in a month are available; when users clicks on"end date" a pop-up with _available only from (date/month)_) appears) 

Flow for selection on calendar: 
- first click: start date 
- second click: end date 
- rights card is created 
- calendar still shows the availabilities for the search 
- user can choose the other availabilities 
- it creates other rights card below 

So behavior remains the same as for the map. Calendar returns to zero after clicking on "search for new rights button" or "Clear" filters

**Comment by Jackseed** [comment]
- [ ] Holdback view to add

**Comment by Jackseed** [comment]
@jdrns I reviewed calendar with some comments on the others sections (form & modale) but the calendar itself is great, nice job 👍

**Comment by Jackseed** [comment]
@stephanie-cascade8 I also reviewed contracts and except some few comments everything looks good, congratz too!
