### ISSUE TITLE
RELEASE MVP: User CRUD

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#5408]
Auth flow (org + account)
Account settings (org + profile + cookies)
Delete: CRM

**Comment by RemcoSimonides** [comment]
I just received 12 emails "Hi Remco, We wanted to let you know that your request to join ... was succesfully sent" when signing up
![image](https://user-images.githubusercontent.com/27687382/113108282-1df4b400-9205-11eb-855e-d0160b325d6a.png)

**Comment by phpgeekfr** [comment]
@RemcoSimonides can you add details to reproduce ?

**Comment by RemcoSimonides** [comment]
To reproduce you just need to sign up ;) Second time I registered I received 'only' 2 of those emails.

**Comment by Jackseed** [comment]
- [ ] Small text change for snackbar "This email does not exists." action "CREATE AN ACCOUNT" > "This account does not exist." action: "CREATE ACCOUNT"
<img width="621" alt="This email does not exists" src="https://user-images.githubusercontent.com/14964443/113295802-f2eb8c80-92f8-11eb-870c-0775efc6729b.png">

**Comment by Jackseed** [comment]
- [ ] sign up page not responsive for big screen, image and form is cut at a fixed height (login page is working fine if it can help)
![image](https://user-images.githubusercontent.com/14964443/113577396-7ff85380-9621-11eb-985c-9897ca495368.png)

**Comment by SamirTouira** [comment]
Please let me know if there are still something to do here
