### ISSUE TITLE
RELEASE MVP: Org: CRUD, list, view

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#5409]
Public org list
Public org view (tab Screenings on festival)
Org filters > test on MF for specific filter
Delete: CRM

**Comment by Jackseed** [comment]
user: dev+verner-phz@blockframes.io
url https://staging.archipelcontent.com/c/o/marketplace/organization/emaVtLWE8YFK3AQo2CaS/title
- [ ] Orgs are listed in the partners section even though they have no film accepted **&** `storeConfig.appAccess.catalog` to `true`; correct listing should use orgs with:
- appAccess.catalog === true
&&
- at least 1 title with status accepted + appAccess.catalog to true

![image](https://user-images.githubusercontent.com/14964443/113004753-218c2a80-9174-11eb-85b9-56bba3cb7d31.png)

**Comment by Mussuranae** [comment]
I could create an org on Catalog and ask app access for an other one. Change information of the org and invite new member correctly.
I saw nothing special on the org list for al the apps. Same for the org view for Catalog and Financiers.
There was nothing wrong on Festival except that the poster of the movie on the screening tab can make you epileptic.

https://user-images.githubusercontent.com/48033264/113177233-954e3600-924d-11eb-97d5-b43d514d4254.mp4

**Comment by Mussuranae** [comment]
- [ ] Same remark as Jackseed on Media Financiers. We see organization on the org list even if they have no project accepted on the app
![image](https://user-images.githubusercontent.com/48033264/113178957-65a02d80-924f-11eb-84ea-b779da2f9f72.png)

**Comment by Jackseed** [comment]
user dev+hilbert-lcj@blockframes.io
urls: https://staging.archipelmarket.com/c/o/marketplace/organization/sLchj1Ib4Cxhwr0ZBW4m/title
- [ ] Blinking line-up - look like an image loading issue

https://user-images.githubusercontent.com/14964443/113270383-b52b3b80-92d9-11eb-8846-97ff1a31ecfa.mp4

**Comment by Jackseed** [comment]
### CATALOG MARKETPLACE ORG LIST

- [ ] Title should be "Sellers"
- [ ] Search bar should say: "Search for a specific company..."
- [ ] Also change the word in the number mention: "There are X sellers available."
![image](https://user-images.githubusercontent.com/55785823/113129590-5f905980-921b-11eb-9a8b-88dc5bd2ac48.png)

### MARKETPLACE
- [ ] Side bar texts should be: 
- Home
- Library
- Sellers
- My Selection
- My Wishlist
![image](https://user-images.githubusercontent.com/55785823/113124287-a8451400-9215-11eb-930c-3953dca617b3.png)
