### ISSUE TITLE
RELEASE MVP: Avails: create, delete, view

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#5410]
Create avail, check the selection page, create offer and validate the email
Cards on selection page

**Comment by Jackseed** [comment]
- [ ] the avails filters were cleared, but the btn remains active. If filters cleared need to change back to initiate state. 
![avails](https://user-images.githubusercontent.com/55499036/113128316-f78d4380-9219-11eb-94aa-ac4662de548d.gif)

**Comment by Jackseed** [comment]
### My Selection page

- [ ] After touching the filters, the column "Action" disappears 
![10](https://user-images.githubusercontent.com/79836137/113127780-7170fd00-9219-11eb-8db7-06603dec4404.gif)

- [ ] Background visible behind rounded corner of drop down
<img width="1440" alt="Screenshot 2021-03-31 at 12 07 48" src="https://user-images.githubusercontent.com/79836137/113128244-e47a7380-9219-11eb-8216-553f7c9c5640.png">

**Comment by Jackseed** [comment]
### Avails filter
- [ ] If possible, could we select by default the typing zone when user clicks on the "Territories" select?
- [ ] When typing a wrong value on Territories, the select doesn't open anymore
https://user-images.githubusercontent.com/14964443/113309166-27664500-9307-11eb-8747-bf293dcbca70.mp4

**Comment by Jackseed** [comment]
- [ ] Change the territory list displayed in the avails filter for this one
```

export const territoriesGroup: StaticGroup<"territories">[] = [
  {
    label: "Europe",
    items: [
      "aland-islands",
      "albania",
      "andorra",
      "austria",
      "belgium",
      "bosnia-and-herzegovina",
      "bulgaria",
      "croatia",
      "czech",
      "denmark",
      "estonia",
      "faroe-islands",
      "finland",
      "france",
      "germany",
      "gibraltar",
      "greece",
      "guernsey",
      "vatican",
      "hungary",
      "iceland",
      "ireland",
      "isle-of-man",
      "italy",
      "jersey",
      "latvia",
      "liechtenstein",
      "lithuania",
      "luxembourg",
      "malta",
      "monaco",
      "montenegro",
      "netherlands",
      "north-macedonia",
      "norway",
      "poland",
      "portugal",
      "romania",
      "san-marino",
      "serbia",
      "slovakia",
      "slovenia",
      "spain",
      "svalbard-and-jan-mayen",
      "sweden",
      "switzerland",
      "ukraine",
      "united-kingdom",
    ],
  },
  {
    label: "CIS",
    items: [
      "armenia",
      "azerbaijan",
      "belarus",
      "kazakhstan",
      "kyrgyzstan",
      "moldova",
      "mongolia",
      "russia",
      "tajikistan",
      "turkmenistan",
      "uzbekistan",
    ],
  },

  {
    label: "Africa",
    items: [
      "algeria",
      "angola",
      "benin",
      "botswana",
      "british-indian-ocean-territory",
      "burkina",
      "burundi",
      "cabo-verde",
      "cameroon",
      "central-african-republic",
      "chad",
      "comoros",
      "congo",
      "congo-democratic-republic",
      "ivory-coast-cote-d-ivoire",
      "djibouti",
      "equatorial-guinea",
      "eritrea",
      "eswatini",
      "ethiopia",
      "french-southern-territories",
      "gabon",
      "gambia",
      "ghana",
      "guinea",
      "guinea-bissau",
      "kenya",
      "lesotho",
      "liberia",
      "libya",
      "madagascar",
      "malawi",
      "mali",
      "mauritania",
      "mauritius",
      "mayotte",
      "morocco",
      "mozambique",
      "namibia",
      "niger",
      "nigeria",
      "reunion",
      "rwanda",
      "saint-helena-ascension-and-tristan-da-cunha",
      "sao-tome-and-principe",
      "senegal",
      "seychelles",
      "sierra-leone",
      "somalia",
      "south-africa",
      "tanzania",
      "togo",
      "tunisia",
      "uganda",
      "western-sahara",
      "zambia",
      "zimbabwe",
    ],
  },

  {
    label: "North America",
    items: [
      "bermuda",
      "canada",
      "greenland",
      "saint-pierre-and-miquelon",
      "united-states-of-america",
    ],
  },
  {
    label: "Latin America",
    items: [
      "argentina",
      "belize",
      "bolivia",
      "brazil",
      "chile",
      "colombia",
      "costa-rica",
      "ecuador",
      "el-salvador",
      "french-guiana",
      "guatemala",
      "guyana",
      "honduras",
      "nicaragua",
      "panama",
      "paraguay",
      "peru",
      "suriname",
      "uruguay",
      "venezuela",
    ],
  },
  {
    label: "Caribbean",
    items: [
      "aruba",
      "anguilla-&-barbuda",
      "antigua-and-barbuda",
      "bahamas",
      "barbados",
      "bonaire",
      "bouvet-island",
      "cayman-islands",
      "cuba",
      "curacao",
      "dominica",
      "dominican-republic",
      "falkland-islands",
      "grenada",
      "guadeloupe",
      "haiti",
      "jamaica",
      "martinique",
      "montserrat",
      "puerto-rico",
      "saint-barthelemy",
      "saint-kitts-and-nevis",
      "saint-lucia",
      "saint-martin-french",
      "saint-vincent-and-the-grenadines",
      "saint-martin-dutch",
      "south-georgia",
      "trinidad-and-tobago",
      "turks-and-caicos-islands",
      "virgin-islands-uk",
      "virgin-islands-us",
    ],
  },
  {
    label: "Oceania",
    items: [
      "american-samoa",
      "australia",
      "christmas-island",
      "cocos-islands",
      "cook-islands",
      "fiji",
      "french-polynesia",
      "guam",
      "heard-island-and-mcdonald-islands",
      "kiribati",
      "marshall",
      "micronesia",
      "nauru",
      "new-caledonia",
      "new-zealand",
      "niue",
      "norfolk-island",
      "northern-mariana-islands",
      "palau",
      "papua",
      "pitcairn",
      "samoa",
      "solomon-islands",
      "tokelau",
      "tonga",
      "tuvalu",
      "united-states-minor-outlying-islands",
      "vanuatu",
      "wallis-and-futuna",
    ],
  },
  {
    label: "Middle East",
    items: [
      "bahrain",
      "egypt",
      "iran",
      "iraq",
      "israel",
      "jordan",
      "kuwait",
      "lebanon",
      "oman",
      "palestine",
      "qatar",
      "saudi-arabia",
      "south-sudan",
      "sudan",
      "syria",
      "turkey",
      "united-arab-emirates",
      "yemen",
    ],
  },
  {
    label: "Asia",
    items: [
      "afghanistan",
      "bangladesh",
      "bhutan",
      "brunei",
      "cambodia",
      "china",
      "cyprus",
      "georgia",
      "hong-kong",
      "india",
      "indonesia",
      "japan",
      "north-korea",
      "south-korea",
      "laos",
      "macao",
      "malaysia",
      "maldives",
      "myanmar",
      "nepal",
      "pakistan",
      "philippines",
      "singapore",
      "sri-lanka",
      "taiwan",
      "thailand",
      "timor-leste",
      "vietnam",
    ],
  },
];
```

**Comment by Jackseed** [comment]
- [ ] Change "United States of America" for "United States of America (USA)" and "United Kingdom" for "United Kingdom (UK)"

**Comment by Jackseed** [comment]
- [ ] Update avails filter rights placeholder from "Tap to filter" to "Specify right(s) to filter" and territories placeholder for  "Specify territory to filter"
![image](https://user-images.githubusercontent.com/55785823/113308693-b4f56500-9306-11eb-9b67-1536ac1cdbaa.png)

**Comment by Jackseed** [comment]
- [ ] Comment from the UX team, it's nice to have but maybe a simple tweak? Ask me if not clear:
When searching for a country, if I [√] that country it will [√] the whole continent if that country is the only result, but then when deleting the search, it puts the continent box in [-] state. Can be confusing to users
![10](https://user-images.githubusercontent.com/79836137/111749310-dfb8d580-8891-11eb-9a0f-4be344a654c6.gif)

**Comment by Jackseed** [comment]
### Snackbars
- [ ] Add a snackbar when a title is added to Selection: "[ Title name ] was added to your Selection." for 4 sec
- [ ] Change message when user clicks on add to selection without avails: "Fill in avails filter to add title to your Selection." for 5sec
- [ ] Add a snackbar when removing an entire Title from a selection: "[ Title name ] was removed from your Selection." for 5 secs
- [ ] Add a snackbar when removing a terms from a title in the selection: "Rights deleted." for 4 secs
- [ ] Change snackbar message when user clics on Send offer without a price: "Missing price information."

**Comment by Jackseed** [comment]
- [ ] Safari img bug: posters on selection are stretched out 
![image](https://user-images.githubusercontent.com/14964443/113581472-7a057100-9627-11eb-8bd8-ba2ef812d525.png)

(same thing as #5419 mb factorize and let the same person do it?)

**Comment by Jackseed** [comment]
- [ ] Offer email, change "seller name" & email for "buyer name" & email
![image](https://user-images.githubusercontent.com/14964443/113581923-129bf100-9628-11eb-83ad-ab3b3c0d42e3.png)

**Comment by RemcoSimonides** [comment]
> * [ ]  Comment from the UX team, it's nice to have but maybe a simple tweak? Ask me if not clear:
>   When searching for a country, if I [√] that country it will [√] the whole continent if that country is the only result, but then when deleting the search, it puts the continent box in [-] state. Can be confusing to users

What solution would you propose to avoid the confusion?

**Comment by Jackseed** [comment]
@RemcoSimonides it would be that when user filters through typing, region tick boxes keep the same logic as they have without filtering:
- it's checked [√] when all countries from the region are selected
- it's [-] when more than one but not all countries from the region is selected

Currently when you filter it uses the filter context: if there is only 1 territory listed within a region after filtering and you check it, the whole region will be checked [√], even if there are 10 other territories inside that region that were filtered but not checked.

This is really low priority issue and should be taken care of after the other ones

**Comment by Jackseed** [comment]
- [ ] @fritzschoff since you're on the filters: we should filter "Theatrical" from the Rights list in the avails filter
