### ISSUE TITLE
RELEASE MVP: Invitations, notifications & emails

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#5411]
Trigger Notifications
Invitations (screening: check the status of the invitation)
Emails => Timezones

**Comment by Jackseed** [comment]
user dev+neha-fja@blockframes.io
url https://staging.archipelcontent.com/c/o/marketplace/invitations
- [ ] As discussed, we should add the correct and full url of an app on invitations / notifications so they may worked cross-app. 
Example: Here I click on a screening invitation link from `catalog` which leads to `https://staging.archipelcontent.com/c/o/marketplace/event/Nxq2CNi7DscC0oekm43g`. It's a dead link as screenings only happen on archipelmarket.com.
If I manually change the url for `https://staging.archipelmarket.com/c/o/marketplace/event/Nxq2CNi7DscC0oekm43g` then it's working properly
![Kapture 2021-03-30 at 17 38 51](https://user-images.githubusercontent.com/14964443/113017683-02939580-9180-11eb-88de-e38152bc5a08.gif)
 
![image](https://user-images.githubusercontent.com/14964443/113017931-47b7c780-9180-11eb-883e-388a5bcf2321.png)

**Comment by Jackseed** [comment]
- [ ] Change demo email text, remove "Archipel Content" to avoid misunderstandings from "A user wants to schedule a demo of Archipel Content." --> "A user wants to schedule a demo."

**Comment by Jackseed** [comment]
- [ ] Movie accepted email is always triggering for Archipel Market even if the movie is only on Content (didn't test on MF but I guess it's the same)
template id: `Template ID: d-bfcf2760bcb7484ab55f864a59331d26`

**Comment by Jackseed** [comment]
Invitations have flashes on loading:
https://user-images.githubusercontent.com/14964443/113551442-f29f0a00-95f4-11eb-8453-5f0772270189.mov

We had the same problem on other lists, here is a comment from @RemcoSimonides about it:
> The first time the screening appear on the screening list page, the data probably comes from the Cache. After that the data comes from firestore and thus rerenders the page.
> I see 4 blinks though, so probably this happens twice.
> On homepage I resolved something similar with a beautiful
> distinctUntilChanged((a, b) => JSON.stringify(a) === JSON.stringify(b) or something. That may solve half of the blinks if the data from firestore is the same as in the cache

**Comment by Jackseed** [comment]
- [ ] New movie submitted email (for admins) is sent to every blockframes admins, instead it should be to business@cascade8.com
![image](https://user-images.githubusercontent.com/14964443/113584156-d8801e80-962a-11eb-91ed-b431cf389e4d.png)
