### ISSUE TITLE
RELEASE MVP: CRM: stats

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#5415]

**Comment by Jackseed** [comment]
- [ ] On movie view links to marketplace pages are dead (currently `c/o/marketplace/movieId/view/main` while it should be `/c/o/marketplace/title/movieId/main`
![image](https://user-images.githubusercontent.com/14964443/113272288-c07f6680-92db-11eb-9f7f-667fd5f1e2a0.png)

**Comment by Jackseed** [comment]
- [ ] User list loading is still very long, don't know if that's something that can be fixed for the release

**Comment by Jackseed** [comment]
url https://staging.crm.blockframes.io/c/o/admin/panel/movie/ZG4aXHI76Wvxb6CbUBk9
user dev+hettie-fvh@blockframes.io
- [ ] Same as above it's more of a new feature than bug fix so it can be skipped for the release if too big but would be great to add the sales pitch video upload box & the stills images upload box on the CRM movie page for the ressource section
![image](https://user-images.githubusercontent.com/14964443/113281887-76e84900-92e6-11eb-9345-0e8a6dfa0dee.png)

**Comment by RemcoSimonides** [comment]
> url https://staging.crm.blockframes.io/c/o/admin/panel/movie/ZG4aXHI76Wvxb6CbUBk9
> user [dev+hettie-fvh@blockframes.io](mailto:dev+hettie-fvh@blockframes.io)
> 
> * [ ]  Same as above it's more of a new feature than bug fix so it can be skipped for the release if too big but would be great to add the sales pitch video upload box & the stills images upload box on the CRM movie page for the ressource section

Promotional Images are still photos, right? They are in there already. sales pitch is added :)

**Comment by Jackseed** [comment]
Cool thanks @RemcoSimonides! and good catch for the promo images I missed it ><
