### ISSUE TITLE
RELEASE MVP: Excel import: orgs, movies

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#5417]

**Comment by Jackseed** [comment]
- [ ] Snackbar error message though no warning or error are counted in the table (and no explanation on what's blocking). Here I think it's because of org activity missing or no appAccess - I'll test by filling it but I guess there is a problem with the error count
[org-test.xlsx](https://github.com/blockframes/blockframes/files/6235598/org-test.xlsx)

![image](https://user-images.githubusercontent.com/14964443/113125457-e68f0300-9216-11eb-990a-301cf7a2162f.png)

**Comment by Jackseed** [comment]
- [ ] it worked after adding an appAccess but the invitation was for Archipel Market though org appAccess was catalog
![image](https://user-images.githubusercontent.com/14964443/113126182-abd99a80-9217-11eb-8120-7b86ba16c88a.png)

**Comment by Jackseed** [comment]
> * [ ]  it worked after adding an appAccess but the invitation was for Archipel Market though org appAccess was catalog
>   ![image](https://user-images.githubusercontent.com/14964443/113126182-abd99a80-9217-11eb-8120-7b86ba16c88a.png)

Super strange... I re-tested it with almost the same file and this time it did was Archipel Content welcome email
[org-test.xlsx](https://github.com/blockframes/blockframes/files/6235735/org-test.xlsx)
![image](https://user-images.githubusercontent.com/14964443/113127859-851c6380-9219-11eb-93f2-3c5f05bc16f7.png)

**Comment by Jackseed** [comment]
- [ ] I updated a bit the template by adding list choice to prevent errors on countries & org activity
[import-organizations-new-template.xlsx](https://github.com/blockframes/blockframes/files/6235870/import-organizations-new-template.xlsx)

**Comment by Jackseed** [comment]
- [ ] Change the download icon for the same one with arrow down instead of up
![image](https://user-images.githubusercontent.com/14964443/113279182-1acff580-92e3-11eb-850b-3a5b460940fc.png)

**Comment by Jackseed** [comment]
- [ ] I think we miss an illustration here
![image](https://user-images.githubusercontent.com/14964443/113557170-e0759980-95fd-11eb-92f9-8961d1cde0b5.png)

**Comment by phpgeekfr** [comment]
>     * [ ]  I think we miss an illustration here
>       ![image](https://user-images.githubusercontent.com/14964443/113557170-e0759980-95fd-11eb-92f9-8961d1cde0b5.png)

@Jackseed which one do we use ?
