### ISSUE TITLE
RELEASE MVP: ALL LANDING PAGES

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#5419]

**Comment by Jackseed** [comment]
- [ ] Update texts between Fred's video and "How it works":

**PACKAGE DEALS**
On Archipel Content, Content Buyers can browse through a consolidated library in which they can pick and choose titles from a multitude of Sellers (Sales Agents, Distributors, Producers…) to make one single multi-title package offer.

**One curated library,
One package offer,
One contract.**

**BLOCKCHAIN**
A blockchain is an open, distributed ledger that can record transactions between different parties efficiently in a verifiable and permanent way.
On Archipel Content, we aim to use it for securing authentication processes, timestamping transactions, and implementing an automated and instantaneous revenue redistribution.

**SECTOR EXPERTISE**
Cascade8 is the tech branch of Logical Pictures Group, which designs and implements tailor-made financial, artistic and technological solutions in entertainment to foster talent.
It has made its mark internationally in the content industry by developing a unique creative environment, thanks to specialized and autonomous sister companies: **Logical Pictures** (films & series financing and production), **21 Content Ventures** (films & series financing), **Pulsar Content** (international sales), **The Jokers** (distribution), **Loveboat** (advertising) and **Cascade8** (software tools).
This expertise and network help us design tech solutions that correspond to the industry professionals’ needs and standards.


- [ ] Update HOW IT WORKS / Seller tab text:
**Valorize your back catalog.**
Get extra visibility on your back catalog and maximize revenues on library sales.
- [ ] Update HOW IT WORKS illustrations. Those who are currently on the landing page are Media Financiers illustration (wrong logo + "my investments") for both Buyer and Seller tabs.
![image](https://user-images.githubusercontent.com/55785823/113123975-5603f300-9215-11eb-92b9-ee1965931f01.png)



- [ ] Update FEATURES texts:
- Import your content easily _(no change)_
- Manage your offers and deals _(no change)_
- Track your films’ activity _(no change)_
- A Human Salesforce: _change to_ "Benefit from a dedicated sales person"

**Comment by SamirTouira** [comment]
On my localhost I have this and this:
![image](https://user-images.githubusercontent.com/52285231/113307453-6dbaa480-9305-11eb-836c-f30c6e2d91e7.png)

![image](https://user-images.githubusercontent.com/52285231/113309193-2e8d5300-9307-11eb-8152-efdebbfc3e57.png)

is it the good illustrations @Jackseed @maltmayer ?

**Comment by Jackseed** [comment]
Indeed that's good ones my bad

**Comment by maltmayer** [comment]
> On my localhost I have this and this:
> ![image](https://user-images.githubusercontent.com/52285231/113307453-6dbaa480-9305-11eb-836c-f30c6e2d91e7.png)
> 
> ![image](https://user-images.githubusercontent.com/52285231/113309193-2e8d5300-9307-11eb-8152-efdebbfc3e57.png)
> 
> is it the goods illustrations @Jackseed @maltmayer ?
> 
> I think the answer is yes after have seen the #5436 issue closed.

But why do I have these then?
![image](https://user-images.githubusercontent.com/55785823/113312804-f0922e00-930a-11eb-9a54-f6ad10c14f28.png)
![image](https://user-images.githubusercontent.com/55785823/113312824-f556e200-930a-11eb-96bc-e0e20d62926a.png)

**Comment by Jackseed** [comment]
@maltmayer on https://staging.archipelcontent.com/ ? reset your cache mb?

**Comment by maltmayer** [comment]
> @maltmayer on https://staging.archipelcontent.com/ ? reset your cache mb?

I did, still have these showing up...

**Comment by Jackseed** [comment]
I really don't know what's the issue here.. 
Though you made me find a nasty bug on safari
- [ ] landing images are stretched out 
![image](https://user-images.githubusercontent.com/14964443/113313952-0eac5e00-930c-11eb-931f-045b8a1620ca.png)

**Comment by Jackseed** [comment]
- [ ] And I see Archipel Content pictures in mediafinanciers landing page
I think you need to investigate what's happening there @SamirTouira mb with help from @Mussuranae 
![image](https://user-images.githubusercontent.com/14964443/113314083-33a0d100-930c-11eb-8a81-5b085c843e2c.png)

**Comment by SamirTouira** [comment]
I've got also the right illustration on Staging and localhost aswell..

Ok I will also have a look for the pictures issue

**Comment by Jackseed** [comment]
- [ ] Update demo component: Put capitals everywhere (First Name / Last Name / Company Name
- [ ] Update CTA text to "Send Request"
![image](https://user-images.githubusercontent.com/55785823/113307586-98a4f880-9305-11eb-9536-f5a57cc5ee96.png)

**Comment by Jackseed** [comment]
I don't know where to put this, @SamirTouira @Mussuranae could you have a try?
### MARKETPLACE TOOL BAR
- [ ] the menu circle is not circle on the menu icon. I've noticed that's true on Market also
![image](https://user-images.githubusercontent.com/55785823/113316653-e3773e00-930e-11eb-86f0-c94c9a090c9b.png)

**Comment by SamirTouira** [comment]
> > @maltmayer on https://staging.archipelcontent.com/ ? reset your cache mb?
> 
> I did, still have these showing up...

About the "How it works" images part:
The issue comes from the light/dark theme by default. For example if on Windows (like Apple) we set up the dark theme, the landing page becomes dark, then we have the good images. But if we have the light theme  configuration by default, instead of the good images we have the wrong images (Media Financiers on Catalog).

We continue to investigating to resolve this.

**Comment by fritzschoff** [comment]
@SamirTouira correct me if I'm wrong, but there is a themeservice that checks the preferences from the users browsers and if light or dark it sets the corresponding theme. So could it be the case that the images are simple not available in their light or dark versions?

**Comment by Mussuranae** [comment]
Exactly @fritzschoff , we saw with @SamirTouira that images for catalog are only in the dark folder, and those for MF are in the light folder. I just show him the Image Directive and he can now fix the issue ;)

**Comment by fritzschoff** [comment]
Nice!

**Comment by Jackseed** [comment]
Well done guys!

**Comment by Jackseed** [comment]
@SamirTouira I still got the wrong landing images on Media Financiers 
![image](https://user-images.githubusercontent.com/14964443/113582757-0fedcb80-9629-11eb-981a-8a05960ca5e7.png)

**Comment by RemcoSimonides** [comment]
[ ]  Images seem to be missing catalog landing page (hosted by my local env, not staging)
![image](https://user-images.githubusercontent.com/27687382/113681323-2005b980-96c2-11eb-9930-0e16eb94c28b.png)

**Comment by maltmayer** [comment]
> * [ ]   Images seem to be missing catalog landing page (hosted by my local env, not staging)
>   ![image](https://user-images.githubusercontent.com/27687382/113681323-2005b980-96c2-11eb-9930-0e16eb94c28b.png)

Also, as I see this screenshot, the first sentense here (Valorise your back catalog) should be bold, and then, go to next line and the rest of the text should be normal (not bold)

**Comment by SamirTouira** [comment]
> @SamirTouira I still got the wrong landing images on Media Financiers
> ![image](https://user-images.githubusercontent.com/14964443/113582757-0fedcb80-9629-11eb-981a-8a05960ca5e7.png)

@Jackseed on staging right? Did you made a deploy to staging from `fix-for-release-3-0` recently? I have checked the 3 apps from my branch, which is merged into ` fix-for-release-3-0` and it's fine on my side : 

![image](https://user-images.githubusercontent.com/52285231/113683372-69ef9f00-96c4-11eb-9af2-d4b9a3e33f40.png)

**Comment by SamirTouira** [comment]
> * [ ]   Images seem to be missing catalog landing page (hosted by my local env, not staging)
>   ![image](https://user-images.githubusercontent.com/27687382/113681323-2005b980-96c2-11eb-9930-0e16eb94c28b.png)

@RemcoSimonides which navigator did you used? have you fetch/pull in the fix-for-release-3-0 branch? everything work on my side strangly

**Comment by RemcoSimonides** [comment]
Safari 😬

**Comment by SamirTouira** [comment]
well seen, i'm fixing this
