### ISSUE TITLE
RELEASE MVP: Contract: creation, email, excel import

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#5420]

**Comment by Jackseed** [comment]
- [ ] After review from business we should in fact send a copy of the offer email **to the user that created it**. If that's simpler we could also send it to every org members but best is the one that created the offer. 
We may use same template as admin but it shall give them some feedback as they have no other way to double check that offer

- [ ] It may be a no-go here but I'll try, can we horizontally align the currency icon with the price number?
![image](https://user-images.githubusercontent.com/14964443/113006801-f571a900-9175-11eb-8468-47d312533964.png)

- [ ] I got an error while trying to open the excel contract template downloaded from `/c/o/dashboard/import`
![image](https://user-images.githubusercontent.com/14964443/113007364-73ce4b00-9176-11eb-956b-f6b5e5bc88af.png)
Here is a copy from the google spreadsheet that should be ok 
[import-contracts-template-admin.xlsx](https://github.com/blockframes/blockframes/files/6229795/import-contracts-template-admin.xlsx)

**Comment by Jackseed** [comment]
- [ ] When clicked on "Create offer" button, I got a snackbar saying something like "Please add a price to every item" but in fact there was a price already. I clicked a second time and then it worked

**Comment by Jackseed** [comment]
- [ ] Cancel button doesn't close the modale
![image](https://user-images.githubusercontent.com/14964443/113014058-92374500-917c-11eb-9db6-4b9b1079da28.png)

**Comment by Jackseed** [comment]
- [ ] Congratulation pages `/c/o/marketplace/selection/congratulations` change texts:
1.
Your Contract Offer
has been successfully sent
>>>
Your Offer was successfully sent.

2.
You can always find your Contract Offer on Offers & Deals page.
Feel free to contact Archipel Content Team if you have a question.
>>>
You will receive a confirmation email with your detailed offer. 
Our team will get back to you as soon as possible to coordinate the deal.
Feel free to contact us if you have a question.

(with "contact us" underlined as a link and opening Intercom)

3.
Button Continue Browsing Library
>>>
Return to Browsing

![image](https://user-images.githubusercontent.com/14964443/113014477-e80bed00-917c-11eb-9b77-106651b87b12.png)

**Comment by fritzschoff** [comment]
We won't do the email for the user. This is not the scope of the MVP

**Comment by fritzschoff** [comment]
![image](https://user-images.githubusercontent.com/39312833/113116848-230a3100-920e-11eb-8ba8-aae3cb2d96b1.png)
@Jackseed dont have this issue. @RemcoSimonides can you take a look with your excel app if you got something?

**Comment by Jackseed** [comment]
> We won't do the email for the user. This is not the scope of the MVP.
> We can give it a low priority and if we got time in the end, we can do it

Alright I was indeed afraid that it would be too big an issue for the release. I made its own issue there #5434

**Comment by fritzschoff** [comment]
will close then this issue

**Comment by Jackseed** [comment]
@fritzschoff that's done also for the congratulations page?

**Comment by RemcoSimonides** [comment]
@fritzschoff you haven't updated all the text of the congratulations page yet. There are text changes left. Do you do it or should I?

**Comment by RemcoSimonides** [comment]
Same error when trying to open the excel file as Vincent (but less pretty)
![image](https://user-images.githubusercontent.com/27687382/113125025-74b6b980-9216-11eb-9d14-de05369bffe9.png)

**Comment by phpgeekfr** [comment]
Is it the same with other templates (movies, orgs ) ?

**Comment by fritzschoff** [comment]
it doesnt make sense to change the text if we dont send an email to the user

**Comment by RemcoSimonides** [comment]
@phpgeekfr no, they do work 👍

**Comment by RemcoSimonides** [comment]
@fritzschoff Good point. But button text and  "Our team will get back to you as soon as possible to coordinate the deal.
Feel free to contact us if you have a question." can still change.
@Jackseed what do you think?

**Comment by Jackseed** [comment]
@RemcoSimonides @fritzschoff I removed the sentence about the email so you can use text in the comment above

**Comment by fritzschoff** [comment]
done with the text changes

**Comment by RemcoSimonides** [comment]
Excel fix has been merged too

**Comment by Jackseed** [comment]
### SELECTION PAGE / EMPTY STATE

- [ ] Update text to "There is no title to display in your Selection."
- [ ] Add subtext if possible: "Select titles to populate your Selection."
- [ ] Update CTA text to: "Browse Library"
![image](https://user-images.githubusercontent.com/55785823/113307926-f1749100-9305-11eb-924d-9c99d89f5edb.png)

**Comment by fritzschoff** [comment]
done
