### ISSUE TITLE
UX/UI Design Review 

### ISSUE THREAD

**Issue by jdrns** [blockframes/blockframes#5425]

**Comment by jdrns** [comment]
## Dashboard 
### Dashboard
- [ ] Shouldn't we use different illustrations? It feels a bit repetitive
<img width="1181" alt="Screenshot 2021-03-30 at 16 09 49" src="https://user-images.githubusercontent.com/79836137/113002728-5d25f500-9172-11eb-9912-1ef39ae3fdda.png">

- [ ] I thought it was a button to create a new title but it actually takes me to "import in bulk", should we adapt the icon? 
![Screenshot 2021-03-30 at 16 20 23](https://user-images.githubusercontent.com/79836137/113004842-323ca080-9174-11eb-8316-3883ecc2a6bf.png)
Maybe something similar as what's used on the other apps like this? Or maybe just keep the arrow?
<img width="331" alt="Screenshot 2021-03-30 at 16 22 46" src="https://user-images.githubusercontent.com/79836137/113004902-42ed1680-9174-11eb-8315-8f5c22c82485.png">

- [ ] (Not really Content, more Market/Financiers) Should the icons for import and download be different? Maybe one having the arrow facing up and the other facing down?
<img width="634" alt="Screenshot 2021-03-30 at 16 25 15" src="https://user-images.githubusercontent.com/79836137/113005431-c149b880-9174-11eb-83af-742d1b6bc668.png">
<img width="331" alt="Screenshot 2021-03-30 at 16 22 46" src="https://user-images.githubusercontent.com/79836137/113005434-c27ae580-9174-11eb-97ea-3d837f466855.png">
Knowing that the button "Start import" has an arrow facing down.
<img width="283" alt="Screenshot 2021-03-30 at 16 27 51" src="https://user-images.githubusercontent.com/79836137/113005566-e1797780-9174-11eb-915b-36746005ce9f.png">

### Movie form 
- [ ] As other production status are disabled, shouldn't "released" be pre-selected? 
<img width="1440" alt="Screenshot 2021-03-30 at 16 30 26" src="https://user-images.githubusercontent.com/79836137/113006218-77150700-9175-11eb-9876-9287ba9e7650.png">

### My titles
- [ ] Sorting filters are not all working 
![1](https://user-images.githubusercontent.com/79836137/113003710-46cc6900-9173-11eb-9eb9-016fc9cfa4ca.gif)

### Title page 
- [ ] Padding missing below the number 
![Screenshot 2021-03-30 at 16 17 33](https://user-images.githubusercontent.com/79836137/113003976-84c98d00-9173-11eb-8d47-8b3d07b1e10e.png)

**Comment by Jackseed** [comment]
> * (Not really Content, more Market/Financiers) Should the icons for import and download be different? Maybe one having the arrow facing up and the other facing down?
> 
> <img alt="Screenshot 2021-03-30 at 16 25 15" width="634" src="https://user-images.githubusercontent.com/79836137/113005431-c149b880-9174-11eb-83af-742d1b6bc668.png">
> 
> <img alt="Screenshot 2021-03-30 at 16 22 46" width="331" src="https://user-images.githubusercontent.com/79836137/113005434-c27ae580-9174-11eb-97ea-3d837f466855.png">
> 
> Knowing that the button "Start import" has an arrow facing down.
> <img alt="Screenshot 2021-03-30 at 16 27 51" width="283" src="https://user-images.githubusercontent.com/79836137/113005566-e1797780-9174-11eb-915b-36746005ce9f.png">

Mathilde always mixed up download & upload arrows ><

@stephanie-cascade8 do you know if we have an existing icon for downloads? (arrow down)

**Comment by stephanie-cascade8** [comment]
@Jackseed Yes indeed, arrow donw for dowload , up for upload. 
just the arrow and no cloud when it's inside a button. 
(all versions already exist in our assets).
If missing, they are exactly the same as the angular icons version which can be included easily in the code. 
https://material.io/resources/icons/?search=download&style=baseline

<img width="279" alt="Capture d’écran 2021-04-01 à 10 59 41" src="https://user-images.githubusercontent.com/66258851/113270371-b0668780-92d9-11eb-8291-b83943d143cc.png">

**Comment by Jackseed** [comment]
> ### Wishlist
> * [ ]  Why is it written confirmed instead of a duration?
> 
> <img alt="Screenshot 2021-03-31 at 11 41 19" width="1440" src="https://user-images.githubusercontent.com/79836137/113124730-20133e80-9216-11eb-9458-e57c750cae48.png">

This bug came from the movie itself - it didn't have running time anymore but instead only a confirmation status (here "Confirmed)
Fixed by modifying the movie
![image](https://user-images.githubusercontent.com/14964443/113282456-3c32e080-92e7-11eb-8b1a-78bcbeb1df99.png)

**Comment by Jackseed** [comment]
> * Cancel buttons don't work in selection & reviews (all page), as well as Production Information, Additional information
>   ![4](https://user-images.githubusercontent.com/79836137/113110942-f3f0c100-9207-11eb-84d0-df0646f55ff0.gif)

@jdrns 
In fact that button is useful /enabled only when you save first an item and then try to edit it. It allows you to cancel your changes. This component has been a pain to design and is really touchy to modify. 
On the other hand you're right it's disturbing, @2amarkina do you know if we could hide the Cancel button while the item is not on an edit mode?

**Comment by Jackseed** [comment]
Everything has been taking care of > closed
thanks for the review 👍
