### ISSUE TITLE
Screening without movie attached to it

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5433]
Currently we can create a screening without a movie attached to it. It gives empty screening pages and could lead users to a mistake if they forget to attach a movie before the event start. 

Though it's hard to add movie as a mandatory field as it could be useful for some users who want to prepare their event before having the movie created/prepared. 

Last thing is that for now we don't allow to attach movie without screener files, which could lead to screening without a file. 

I think we should think of a UX solution that takes care of these 3 scenarii that can happen in that same page

**Comment by 2amarkina** [comment]
Ideas and work in progress [here](https://www.figma.com/file/vBJGpcE68Fyc8IPNEi5slY/%5B-Media-Ressources-%5D?node-id=1596%3A13106)

**Comment by Jackseed** [comment]
@2amarkina ok for your propositions:
- we change movie as mandatory
- we add this chip to warn users that no screener is attached
![image](https://user-images.githubusercontent.com/14964443/119318652-dbd27680-bc79-11eb-92fd-0c5d8bda4903.png)
@maltmayer could you confirm it's ok for you?

**Comment by Jackseed** [comment]
I got 2nd thoughts on this one. 

Event is already created when users come to the long form so we can't have mandatory options in that step. 
If we want to make title selection as mandatory it should be moved to the short form (calendar view) and thus make a dynamic form (visible only if screening selected). 
To me it's ok but it's a change that we should validate with both UX, business and dev (@GrandSchtroumpf ?)

**Comment by 2amarkina** [comment]
It will mean that we'll have to introduce different forms for different event types.. we've got screenings and meetings for now and we'll have Presentation and Conference to come. The video attached will be also important for Presentation and it's not a simple select but there is also a text. 

We need to pay attention to not introduce too many conditions in such case. 

If this mandatory field becomes a real pain, I think we can limit for the "Warning Chips" only.

**Comment by Jackseed** [comment]
Yep looks easier to maintain, let's start with this chip only and see if this problem remains

**Comment by 2amarkina** [comment]
Following our last business review, maybe we can close this issue? @Jackseed

**Comment by Jackseed** [comment]
Yep
