### ISSUE TITLE
AC - Christophe's review

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5435]

**Comment by ChristophePecot** [comment]
###avails theatrical
please remove theatrical from the list
![image](https://user-images.githubusercontent.com/77780563/113309550-8d52cc80-9307-11eb-9c27-36b98f8caf9e.png)

**Comment by ChristophePecot** [comment]
###format
can you add animation?
![image](https://user-images.githubusercontent.com/77780563/113311370-875deb00-9309-11eb-8d30-978e9ac2dd03.png)
