### ISSUE TITLE
Business Review (Marie) Archipel Content MVP

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#5436]
### LANDING PAGE

- [x] Update texts between Fred's video and "How it works":

**PACKAGE DEALS**
On Archipel Content, Content Buyers can browse through a consolidated library in which they can pick and choose titles from a multitude of Sellers (Sales Agents, Distributors, Producers…) to make one single multi-title package offer.

**One curated library,
One package offer,
One contract.**

**BLOCKCHAIN**
A blockchain is an open, distributed ledger that can record transactions between different parties efficiently in a verifiable and permanent way.
On Archipel Content, we aim to use it for securing authentication processes, timestamping transactions, and implementing an automated and instantaneous revenue redistribution.

**SECTOR EXPERTISE**
Cascade8 is the tech branch of Logical Pictures Group, which designs and implements tailor-made financial, artistic and technological solutions in entertainment to foster talent.
It has made its mark internationally in the content industry by developing a unique creative environment, thanks to specialized and autonomous sister companies: **Logical Pictures** (films & series financing and production), **21 Content Ventures** (films & series financing), **Pulsar Content** (international sales), **The Jokers** (distribution), **Loveboat** (advertising) and **Cascade8** (software tools).
This expertise and network help us design tech solutions that correspond to the industry professionals’ needs and standards.

- [x] Update HOW IT WORKS / Seller tab text:
**Valorize your back catalog.**
Get extra visibility on your back catalog and maximize revenues on library sales.
- [x] Update HOW IT WORKS illustrations. Those who are currently on the landing page are Media Financiers illustration (wrong logo + "my investments") for both Buyer and Seller tabs.
![image](https://user-images.githubusercontent.com/55785823/113123975-5603f300-9215-11eb-92b9-ee1965931f01.png)

- [x] Update FEATURES texts:
- Import your content easily _(no change)_
- Manage your offers and deals _(no change)_
- Track your films’ activity _(no change)_
- A Human Salesforce: _change to_ "Benefit from a dedicated sales person"

### DASHBOARD MOVIE LIST
- [x] The bulk import CTA has disappeared here. It should be here shouldn't it?
![image](https://user-images.githubusercontent.com/55785823/113115102-5cda3800-920c-11eb-840e-dff5c855f1fd.png)

### MARKETPLACE
- [x] Side bar texts should be: 
- Home
- Library
- Sellers
- My Selection
- My Wishlist
![image](https://user-images.githubusercontent.com/55785823/113124287-a8451400-9215-11eb-930c-3953dca617b3.png)

**Comment by maltmayer** [comment]
### MARKETPLACE ORG LIST

- [ ] Title should be "Sellers"
- [ ] Search bar should say: "Search for a specific company..."
- [ ] Also change the word in the number mention: "There are X sellers available."
![image](https://user-images.githubusercontent.com/55785823/113129590-5f905980-921b-11eb-9a8b-88dc5bd2ac48.png)

**Comment by maltmayer** [comment]
### MARKETPLACE NOTIFICATIONS & INVITATIONS

- [ ] Archipel Market notifications & invitations should not appear on Archipel Content
![image](https://user-images.githubusercontent.com/55785823/113130392-50f67200-921c-11eb-9fe7-478dc95aa04e.png)
![image](https://user-images.githubusercontent.com/55785823/113130441-5eabf780-921c-11eb-8d34-2cd436805aea.png)

**Comment by Jackseed** [comment]
> ### MARKETPLACE NOTIFICATIONS & INVITATIONS
> * [ ]  Archipel Market notifications & invitations should not appear on Archipel Content
>   ![image](https://user-images.githubusercontent.com/55785823/113130392-50f67200-921c-11eb-9fe7-478dc95aa04e.png)
>   ![image](https://user-images.githubusercontent.com/55785823/113130441-5eabf780-921c-11eb-8d34-2cd436805aea.png)

@maltmayer not sure of this one, links will be updated to link to the correct app but with a cross-app strategy I don't see a problem to have cross notifications / invitations. Why do you want to hide it?
Anyway we won't change that behaviour for the release cause it's too big a change but for mid-term strategy it's an open question.

**Comment by maltmayer** [comment]
> > ### MARKETPLACE NOTIFICATIONS & INVITATIONS
> > 
> > * [ ]   Archipel Market notifications & invitations should not appear on Archipel Content
> >   ![image](https://user-images.githubusercontent.com/55785823/113130392-50f67200-921c-11eb-9fe7-478dc95aa04e.png)
> >   ![image](https://user-images.githubusercontent.com/55785823/113130441-5eabf780-921c-11eb-8d34-2cd436805aea.png)
> 
> @maltmayer not sure of this one, links will be updated to link to the correct app but with a cross-app strategy I don't see a problem to have cross notifications / invitations. Why do you want to hide it?
> Anyway we won't change that behaviour for the release cause it's too big a change but for mid-term strategy it's an open question.

Because it's confusing. If I'm a user, I go on an app, I expect to see my notifications for this app, not for an app that has "nothing to do" with what I'm doing here. 
Or at least, maybe mention the app somewhere in the notification then ? like next to the date, specify the app name. It's not a priority but on the long term I think it's be good to have this conversation with @2amarkina

**Comment by 2amarkina** [comment]
> > > ### MARKETPLACE NOTIFICATIONS & INVITATIONS
> > > 
> > > * [ ]    Archipel Market notifications & invitations should not appear on Archipel Content
> > >   ![image](https://user-images.githubusercontent.com/55785823/113130392-50f67200-921c-11eb-9fe7-478dc95aa04e.png)
> > >   ![image](https://user-images.githubusercontent.com/55785823/113130441-5eabf780-921c-11eb-8d34-2cd436805aea.png)
> > 
> > 
> > @maltmayer not sure of this one, links will be updated to link to the correct app but with a cross-app strategy I don't see a problem to have cross notifications / invitations. Why do you want to hide it?
> > Anyway we won't change that behaviour for the release cause it's too big a change but for mid-term strategy it's an open question.
> 
> Because it's confusing. If I'm a user, I go on an app, I expect to see my notifications for this app, not for an app that has "nothing to do" with what I'm doing here.
> Or at least, maybe mention the app somewhere in the notification then ? like next to the date, specify the app name. It's not a priority but on the long term I think it'd be good to have this conversation with @2amarkina

I agree that all the info related to events should not appear on Content, as this feature exists only for Market. But for the notifications in general - they can easily stay here as they include the info about the organization and adding a new member, or submitting a new title for example.

**Comment by Jackseed** [comment]
I opened that [issue](#5458) so we can think of a broader solution that encompasses future applications and will not only focus on event invitations though they are the pain point here

**Comment by Jackseed** [comment]
thanks for the review @maltmayer! everything has been reported on dedicated issues, I close this one but don't hesitate to open a new one or re-open this one if you spot something else

**Comment by maltmayer** [comment]
### LANDING PAGE

- [ ] Update demo component: Put capitals everywhere (First Name / Last Name / Company Name
- [ ] Update CTA text to "Send Request"
![image](https://user-images.githubusercontent.com/55785823/113307586-98a4f880-9305-11eb-9536-f5a57cc5ee96.png)

### SELECTION PAGE / EMPTY STATE

- [ ] Update text to "There is no title to display in your Selection."
- [ ] Add subtext if possible: "Select titles to populate your Selection."
- [ ] Update CTA text to: "Browse Library"
![image](https://user-images.githubusercontent.com/55785823/113307926-f1749100-9305-11eb-924d-9c99d89f5edb.png)

### MARKETPLACE MOVIE LIST
- [ ] Update avails filter placeholder from "Tap to filter" to "Specify right(s) to filter"
![image](https://user-images.githubusercontent.com/55785823/113308693-b4f56500-9306-11eb-9b67-1536ac1cdbaa.png)

- [ ] Remove s from "Genre" filter (should show "Genre" not "Genres"). Same for Market if possible to do both changes. And in that direction, Market also has a "Sales Agents" filter that shouldn't take an s either
![image](https://user-images.githubusercontent.com/55785823/113309344-58467a00-9307-11eb-9329-51e42e36bddd.png)


### MARKETPLACE MOVIE VIEW
- [ ] We agreed that banner component should show the seller, no? @Jackseed 
![image](https://user-images.githubusercontent.com/55785823/113308795-cdfe1600-9306-11eb-9187-dfc1ed8f0c9b.png)

### MARKETPLACE ORG VIEW
- [ ] Change first tab name & title to "Catalog" instead of "Line-up". Juste for Content, not Market.
![image](https://user-images.githubusercontent.com/55785823/113308930-f423b600-9306-11eb-8e29-1af938332876.png)

### MARKETPLACE ORG LIST
- [ ] Is it possible to show X films in catalog here (instead of line-up)? Without impacting Archipel Market? @Jackseed 
![image](https://user-images.githubusercontent.com/55785823/113308907-eec66b80-9306-11eb-8af8-51319d859be4.png)

- [ ] We're display orgs that have line-up titles but no library title... Content should only display org with validated library titles.
![image](https://user-images.githubusercontent.com/55785823/113309228-38af5180-9307-11eb-8f9a-8dea5767614c.png)

### MARKETPLACE WISHLIST

- [ ] Wishlist shouldn't be common for Market and Content as the titles listed on each app are not the same. Here, there's a line-up film in my wishlist that should be here.
![image](https://user-images.githubusercontent.com/55785823/113309583-95ab0780-9307-11eb-96bd-a67ecaa4ce1c.png)

**Comment by maltmayer** [comment]
### DASHBOARD MOVIE FORM

- [ ] I know this might be a long shot since it comes from the whole structure of the movie form but ccouldn't we skip/hide this step on Content as we already know the status? 
![image](https://user-images.githubusercontent.com/55785823/113309812-d014a480-9307-11eb-8104-801662ea0db1.png)

**Comment by maltmayer** [comment]
### MARKETPLACE TOOL BAR

- [ ] the menu circle is not circle on the menu icon. I've noticed that's true on Market also
![image](https://user-images.githubusercontent.com/55785823/113316653-e3773e00-930e-11eb-86f0-c94c9a090c9b.png)

**Comment by Jackseed** [comment]
> * I know this might be a long shot since it comes from the whole structure of the movie form but ccouldn't we skip/hide this step on Content as we already know the status? @Jackseed
>   ![image](https://user-images.githubusercontent.com/55785823/113309812-d014a480-9307-11eb-8104-801662ea0db1.png)

We can't do this, pre-fill it was the best option we got.

Everything has been done or duplicated into specific issues, I close this one. Thanks for the review 👍
