### ISSUE TITLE
Enable sellers to check their stand from dashboard

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5457]
The same as sellers have a button to check movie pages in the marketplace from the dashboard view, we should think of a place to add a button that would lead them to their "stand" (organization view with line-up)

**Comment by 2amarkina** [comment]
Proposition to resolve this is connected to[ this issue ](https://github.com/blockframes/blockframes/issues/4304) and here are [wireframes](https://www.figma.com/file/WSbqoyv3Mzkip6yQJGrQR6/%5B-Dashboard-Film-Page-Header-Update-%5D?node-id=108%3A0)

**Comment by Jackseed** [comment]
@2amarkina are you sure it's related to that issue? Maybe I missed something but on the wireframes I see only movie related solutions.
This issue is about the organization "stand" on the marketplace.
![image](https://user-images.githubusercontent.com/14964443/117676751-1df5b580-b1ae-11eb-9217-92bf7e1a60fe.png)

I think it's a bit different than movies since to me here the main question is: where to display the button? because the only org view on the dashboard side is the org settings page, which I find too hard to find and not really related to that scenario.
On the other hand the solution with the banner to warn that it's a preview is a good one we may re-use

![image](https://user-images.githubusercontent.com/14964443/117677191-85136a00-b1ae-11eb-89fc-66d7913682e2.png)

**Comment by 2amarkina** [comment]
Wanted to present it more in details during tomorrow stand-up. 
One of the ideas was to use the secondary action buttons to lead a seller directly to see the org page with movie on it: _See on the stand_ link.
<img width="695" alt="Снимок экрана 2021-05-10 в 17 11 45" src="https://user-images.githubusercontent.com/55499036/117681854-cf96e580-b1b2-11eb-8db6-78f080a717a3.png">

It was an idea while working on other issue, so noted it as a proposition. 

The other propositions to discuss : 
- change the link from "dashboard organization settings" to "stand on the marketplace" (the organization details at the bottom)
<img width="269" alt="Снимок экрана 2021-05-10 в 17 19 17" src="https://user-images.githubusercontent.com/55499036/117682953-e12cbd00-b1b3-11eb-9ee3-79462ddaf980.png">
- use dashboard (no wireframe yet) 
- use menu (after Buyer's platform -> See my Stand (no wireframe yet)) 

The last solutions will also demand an error state eventually as only the published titles can be shown on the Marketplace Side.

**Comment by Jackseed** [comment]
@2amarkina thanks for the clarification. I think we could do 1 & 2:
1. Link from movie view: this action list doesn't have that much items so 1 more lgtm 
2. I've always found weird to have this org settings link over here, I think a link to the marketplace stand is way more logical. 
Though I'm a bit worried that it could lead to technical complications, navbar is unstable and we shall change it as less as we can. That's why solution 3 looks not good and I think best we can have is 2 between these ones. 
Do you think it's ok to use both 1 & 2?

**Comment by Jackseed** [comment]
@2amarkina we discussed with @maltmayer and she has some valid points. 
Usually user pictures lead to settings + we could gather similar info with the subscription badge from #4398

Could you make a proposition for solution 3 please? it should definitely be validated with tech.
