### ISSUE TITLE
Multi-app organizations

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5458]
Currently notifications & invitations are attached to a user or an org so if they have access to AM & AC for instance then they will receive screening invitations even in AC. 

I think it opens a broader question of how we want the applications to interact altogether. As we always have thought applications as one ecosystem I think it's good to have these links but they should be designed to be more understandable. 

Same question can apply to titles across applications. Currently you only see titles from the app on your dashboard, meaning that if you have 2 titles A (AC) & B (AM) you will see only A in AC & B in AM. 
That's 2 different behaviours for the same underlying question.

**Comment by 2amarkina** [comment]
- Notifications should be app-specific.
- Invitations should be app-specific.
- Wishlist is app-specific, but is shared with organization members (-> Company' Wishlist, +show "added by" for the first step). 
- No specific section for the total list of titles

- [ ] Prepare the structure how to add an existing title to the other app (title exists on Market, i want to add it to Content). 
- [ ] Think over the structure, when members inside organization should have access to different apps.

**Comment by 2amarkina** [comment]
### Wishlist 
![Снимок экрана 2021-06-03 в 13.34.13.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/5de2f261-a5aa-4108-81fe-b677c9ce5a69)


### The structure of moving a Title from one app to another 

**Main**
1. When user has n+1 application, when s/he arrives to Lobby page s/he can choose if wants to import from "Titles' Bank" or upload a brand new Title. 
![Снимок экрана 2021-06-03 в 13.41.57.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/43769c75-cfa3-4e7b-803c-95d2c039cfef)

2. If user chooses to import from "Titles Bank" s/he is able to choose a title existing on other application from a list. 
![Снимок экрана 2021-06-03 в 13.45.17.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/bd0de814-50a1-49d8-a1fb-04fa94d0bcad)

3. If a title on App1 has the same production status as App2, then after validating a chosen title user is redirected on "My Titles" page with a highlighted recently added title. 
![proto_import.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/e1dbc435-4f8a-481d-85ca-61c60b1eb101)


4. If a title on App1 has different production status then on App2 (i.g. Archipel Market and Archipel Content) then user should be redirected to the Summary Page of a title. This is essential as the production status will be different and some different mandatory fields can be introduced. 
![proto_summary.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/5f2131ce-1f76-469f-91df-499a6f9c69a4)

5. If the title's information is changed on App1, it should also be changed on App2. A title should have exactly the same information on all Apps. 

6. Following the rule 5, if a title on App2 (Content) has changed status to _Released_ then it should be changed on App1 (Market) and choosing other Production Statuses should be disabled.

idea of how to manage this part
![proto.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9b939ec8-883e-48b6-9cfa-87760bc72e08)

7. How to add the new titles? Three versions are presented on wireframes, but the phare solution is to keep everything as it is rights now, but change the tooltip text. 
![Снимок экрана 2021-06-03 в 14.25.55.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/c98e5ba7-573f-4447-b2bf-9e9e7eb5c7a7)

**Comment by RemcoSimonides** [comment]
Hee @2amarkina, what does still need to be done for this issue? and/or what is blocking you?
If a part is already done and a small part isn't, you can create a new issue(s) for the small part(s) if you want?

**Comment by 2amarkina** [comment]
Here it's the part about the members is left to be done (Think over the structure, when members inside organization should have access to different apps.). We can create a special issue for that and move this one to business review!

**Comment by 2amarkina** [comment]
[Dedicated issue is created here](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/6319)

**Comment by 2amarkina** [comment]
**After dev review:** 
_Ideas of improvement:_ 
- [ ] See if at the same time we could improve the "Add a new title" page: have less text, but have more direct actions inside a page (to avoid modals). 
- [ ] Conduct a little A/B testing on the wireframing level inside team to choose the best flow (via global Import Titles section or via New Title page)

**Wishlist** 
We could introduce the name of the person who added a title, but we need to
- [ ] Decide what to do with existing wishlists. What name should be shown? 

**Moving a title with not the same production status**
We could show a warning message that a title's status can be re-wrote everywhere.

**Comment by 2amarkina** [comment]
With the new changes to come on the Avails it would be interesting to see the import section together with this issue.

**Comment by 2amarkina** [comment]
For better organization,[ the dedicated issue about import is created ](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/6743) 

The other part of the issue (import from other app) needs to be reviewed one last time with the devs.
