### ISSUE TITLE
Email validation after creating an account should be mandatory to access app(s)

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#5467]
Email validation after creating an account should be mandatory to access app(s).

Suggestions:
- [x] create a guard to redirect users without validated email to the "send validation email" page
- [x] display this guard only to new created users, not existing one
- [ ] add a information popin in users settings page inviting existing users to validate their email

**Comment by Jackseed** [comment]
@phpgeekfr 
> - create a guard to redirect users without validated email to the "send validation email" page

Is it that page you're talking about? 
![image](https://user-images.githubusercontent.com/14964443/113549522-e2d1f680-95f1-11eb-9130-c0b895f07a52.png)

> - display this guard only to new created users, not existing one
👍 

> - add a information popin in users settings page inviting existing users to validate their email
do we have a way to know how many existing users didn't validate their email address?

**Comment by RemcoSimonides** [comment]
When user wants to validate their email again, they should have a button to re-send a verification email.
For this; search for `@TODO (#2821)` for this

**Comment by RemcoSimonides** [comment]
> do we have a way to know how many existing users didn't validate their email address?
I don't think we have an easy way, but maybe you know @phpgeekfr ?

**Comment by phpgeekfr** [comment]
we could add this information in CRM. Or if is only for a one shot: `firebase auth:export /home/bruce/Bureau/cascade8/ninja/auth/auth-prod-$(date +%d-%m-%Y).json --format=json`
Info will be in json

**Comment by phpgeekfr** [comment]
for auth-prod-07-04-2021:

"emailVerified": false => 1398
 "emailVerified": true, => 2270

**Comment by Jackseed** [comment]
Thanks @phpgeekfr for the figures, we can't block that many users with a guard - especially if they have a wrong email address in the first place. 
For now I would go with your recommendation to propose to users to validate it. 

Could we add a CTA button "Verify Email Address" on the right of the email address input that is visible only for users that didn't verify their email?
Also a snackbar should be added when button clicked with "Validation email sent." for 4s and no action.

![image](https://user-images.githubusercontent.com/14964443/116096186-5cb54700-a6a9-11eb-8775-d63b23c22321.png)

**Comment by RemcoSimonides** [comment]
Do we have a different email template? Because this one contains 'Thanks for signing up to Archipel! '. Or is it ok?
![image](https://user-images.githubusercontent.com/27687382/116434011-53171500-a84a-11eb-8ca5-d7d74f407352.png)

**Comment by RemcoSimonides** [comment]
@Jackseed ☝️ ?

**Comment by RemcoSimonides** [comment]
@Jackseed that's reset password template ;) I need a template for verify email.
The current one is the same email as when you register for the platform and thus 'Thanks for signing up to Archipel' is appropriate. But when you verify email later; then it isn't appropriate anymore. Then we just need "Please click here to validate your email... "

**Comment by Jackseed** [comment]
Oh god my bad I'll make you a new one..

**Comment by Jackseed** [comment]
@RemcoSimonides email created [here](https://mc.sendgrid.com/dynamic-templates/d-81438bdf511b43cfa866ca63a45a02ae/version/5042da39-62de-4aff-bb5d-8931b5735d34/editor)
template id: `d-81438bdf511b43cfa866ca63a45a02ae`

**Comment by RemcoSimonides** [comment]
Thanks! As it's the same templateId I don't need to change any code.
I've set the new version to Active in SendGrid ;) that was the only things that needed to be done to use this new template

**Comment by Jackseed** [comment]
I re-opened it since there are 2 new variables used here:
- app (app.name, app.url,..)
- userFirstName
could you confirm it's passed to the email?

Also I re-used pageURL as the linked to be used

**Comment by RemcoSimonides** [comment]
Thanks for pointing it out :) I've added the new variables
