### ISSUE TITLE
E2E excel import test

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#5469]
We want to test the excel import on Archipel Content.
Scenario would be :

- Connect with an blockframes admin account
- Go on the import page
- Select contract option and import an excel of contracts
- Check if there is no error in the table of imported contracts
- Create all the contracts

@Jackseed can maybe add more details to the scenario, but this is the basis.
Excel file for contract : https://docs.google.com/spreadsheets/d/1KHKdN9HAzDUfbKaoSi6_OHxCjMsMd-vQh0VL_qKSKls/edit#gid=0

**Comment by Jackseed** [comment]
@Mussuranae thanks that's exactly what we need and we could plug it before #5353 so then we can test if data has been loaded correctly since we use excel data in the bucket test.

**Comment by Jackseed** [comment]
excel file that can be use for that test with minimal rights needed for #5353 
[Contract.xlsx](https://github.com/blockframes/blockframes/files/6270290/Contract.xlsx)

**Comment by xmano** [comment]
This is feature is integrated in create-bucket.spec.ts in catalog-e2e. Closing this.
