### ISSUE TITLE
App specific wishlists

### ISSUE THREAD

**Issue by fritzschoff** [blockframes/blockframes#5475]
![image](https://user-images.githubusercontent.com/39312833/113408894-7f0cbb00-93b0-11eb-8b13-2608d7d6b51d.png)
@Jackseed @2amarkina @maltmayer 
when we add a title to wishlist it is only for an app or it is for this title globally ?

**Comment by 2amarkina** [comment]
It should for one app-only. 

If I add a film to wishlist on Financiers, it's shown only on Financiers app. As a user will provide different actions with a title after adding it to wishlist (or just keep it, or buy the rights, or invest in it) we can't mix all the titles in one environment as it can be really confusing.

**Comment by Jackseed** [comment]
I prefer to block that issue while this broader one #5458 isn't solved. We should define the cross-app strategy before implementing it object per object
