### ISSUE TITLE
Corrupted otherVideos

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#5494]
Somehow some `movie.promotional.videos.otherVideos` got corrupted. This field need to be an array _(even if empty)_ and in some case it's an object.

![image](https://user-images.githubusercontent.com/5858657/113693607-0dde4800-96cf-11eb-9991-a522a72059ec.png)

We need to find how this happen so we can patch the root cause.

In the mean time we could also add a data fix to the cleaning script to auto-recover between each release.
@phpgeekfr what do you think ?

**Comment by phpgeekfr** [comment]
It depends off the number of movies that are in this situation. If there is only 5 or 10 maybe we can correct it directly on db ? And find the root cause to prevent this

**Comment by pldespaigne** [comment]
right now it's 3 movies on staging and 0 on prod, correcting data by hand seems totally doable
but to find the root cause we will need more info, I have 0 clue of how this could have happened

**Comment by phpgeekfr** [comment]
Issue still not there on production. Maybe problem was solved. @pldespaigne ok to close & to open it again if needed ?
