### ISSUE TITLE
Add "Marketplace" tab on festival & financiers dashboard movie view

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5495]
![image](https://user-images.githubusercontent.com/14964443/113698749-0e79dd00-96d5-11eb-9f29-9d23cfa2be38.png)

This tab has been created for catalog and was removed at first for festival. It's now working good since the analytics refactoring and we shall make it as re-usable tab available in all apps. 

It means that for now it should be added to `festival` and `financiers`.

In fact that tab mixes 2 kind of statistics:
- movie view & interactions > useful for all apps
- app-specific statistics (catalog: offers & sales amounts)

So as a re-usable tab it should be structured as:
- Top first statistics : cross-app
![image](https://user-images.githubusercontent.com/14964443/113698639-f2763b80-96d4-11eb-885e-4da27b48daef.png)
- Following statistics: app-specific (could be none as it should be for now on `festival` and `financiers`.)
![image](https://user-images.githubusercontent.com/14964443/113698703-028e1b00-96d5-11eb-8c81-e8e05d87944a.png)

**Comment by GrandSchtroumpf** [comment]
If the second part is not generic there is not much interest to do that as we'll still need to create one page/app. If we want to have some flexibility on the content, better copy/paste the page, and change the second section.
