### ISSUE TITLE
remove use of debounceFactory in MarketplaceSelectionComponent

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#5526]
remove use of debounceFactory in MarketplaceSelectionComponent

`debouncedUpdatePriceControl = debounceFactory((index, price) => this.updatePrice(index, price), 1000);`

**Comment by phpgeekfr** [comment]
issue created from https://github.com/blockframes/blockframes/pull/5513
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/e6dd3f19-f6d2-4c92-8001-93da096fe541)

**Comment by RemcoSimonides** [comment]
@GrandSchtroumpf is there another way to debounce an input field?

**Comment by GrandSchtroumpf** [comment]
It's not the input that you need to debounce, but the display.

**Comment by RemcoSimonides** [comment]
Check if there are any changes on the page every second or something?
