### ISSUE TITLE
observable issue in MovieShellConfig

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#5529]
observable issue in MovieShellConfig.

Check for `#5529` in code.

Created from https://github.com/blockframes/blockframes/pull/5513#discussion_r608702898

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/2c02db7c-4663-4b83-818e-a187d0e251c0)

**Comment by Jackseed** [comment]
I don't know how to test that's done :x
