### ISSUE TITLE
Invitation / Notification list - action icons refactoring

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5557]
Some problems have been discussed:
- text below icons are too much on the list component
- the more button should have the same behaviour on notifications & invitations: opens a menu that leads to another page when click on "more details" item
![image](https://user-images.githubusercontent.com/14964443/114558167-b27dfe00-9c6a-11eb-9267-7a403dd26135.png)

This should be linked to the success colour discussion #4835

**Comment by RemcoSimonides** [comment]
Hee @Jackseed , is this issue ready for development? I see above that the pipeline is set to 'UI for Design'

**Comment by Jackseed** [comment]
@RemcoSimonides not yet ready, design team has to work on a proposition

**Comment by jdrns** [comment]
Mock up for [action icons refactoring](https://zpl.io/VxpeXyk) for invitation page and activity feed page. 

**Dev review needed** to see if we can use a component different from the event banner

**Comment by RemcoSimonides** [comment]
Created dev issue #6071
