### ISSUE TITLE
Responsive large screens

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5560]
Large screens don't behave really well on our apps. We have 2 main issues: 
- content size
- texts with fixed size

Some propositions are here but should be tested by the design team before dev review:
- fixed max width with side-panels to avoid the difficulty
- media queries
- variable text size (em, vw,..) 
...

**Comment by stephanie-cascade8** [comment]
Tests started with those propositions here 
https://www.notion.so/cascade8/Responsive-large-screens-8672e055d0c443f8882bae55b370398d

**Comment by stephanie-cascade8** [comment]
Updated with landing page after meeting on grid system.

New solution to test here 
https://www.notion.so/cascade8/Responsive-large-screens-8672e055d0c443f8882bae55b370398d

https://zpl.io/aXjNE5K

**Comment by RemcoSimonides** [comment]
Dev checking if we can enforce light theme on home page #6064

**Comment by Jackseed** [comment]
Last decision was to go page by page with @stephanie-cascade8 proposition. 
Most important pages are the one with banners:
- landing
- marketplace home
- marketplace movie view
&
- marketplace title list

We shall start first with landing since it will be changed soon.

2 pending UI decisions:
- [ ] what do we do with the toolbar?
- [ ] what about the sidenav for marketplace?

**Comment by stephanie-cascade8** [comment]
> Last decision was to go page by page with @stephanie-cascade8 proposition.
> Most important pages are the one with banners:
> 
> * landing
> * marketplace home
> * marketplace movie view
>   &
> * marketplace title list
> 
> We shall start first with landing since it will be changed soon.
> 
> 2 pending UI decisions:
> 
> * [ ]  what do we do with the toolbar?
> * [ ]  what about the sidenav for marketplace?

Toolbar : we said we would keep it spread with no margin on left and right. (just like it is now [see it here](https://app.zeplin.io/project/5f3100d317a0041be2ad99c4/screen/60dc4213015aef929f65789f) )

Sidebar : Stuck on the left. [See it here](https://app.zeplin.io/project/5f3100d317a0041be2ad99c4/screen/60dc42179e3326084504c1fe)

**Comment by RemcoSimonides** [comment]
Created issue for
- [x] Landing page
- [ ] Marketplace home
- [ ] Marketplace movie view
- [ ] Marketplace title list

**Comment by RemcoSimonides** [comment]
Landing page implemented on marketplace, catalog and financiers
https://github.com/blockframes/blockframes/issues/6239

@Jackseed should I create dev issue for marketplace home, movie view and title list too? Or does it need design first

**Comment by Jackseed** [comment]
We need a design work first for the gradient colour to be a bit updated so the transition between banner and borders is less visible. 
We discussed that with @stephanie-cascade8 Yesterday, not sure if she created the design issue but it should block this one.

**Comment by Jackseed** [comment]
@RemcoSimonides we may indeed go on with other pages :)

**Comment by RemcoSimonides** [comment]
Hee @stephanie-cascade8, I've found the design for Marketplace home page for large screen, but do you also have them from marketplace movie view and marketplace title list pages? If no, we can probably do it without design too by just applying the same principles as we did for the other pages.
