### ISSUE TITLE
Corporate identity and style guide

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5561]
External communication materials should comply with app-style guide. 

We miss a synthesis document that gather:
- colours 
- logos
- typos
- general guidelines to follow when creating an external communication document

This should be a Notion article that we may all refer to.

**Comment by stephanie-cascade8** [comment]
@jdrns the assets folder on drive has been updated here https://drive.google.com/drive/folders/1aeREaLjdC7PTQd7uBpipRYrWuZtSxZ5c (please link it to the style guide)
