### ISSUE TITLE
Affordance

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5562]
A general tour of the apps is needed to check component affordance:
- tell the user that something is going to happen when it does
- don't tell the user that something will happen if it's not

Buttons, chips, and most of the components should be checked with that in mind to start a review of what needs to be changed in order to respect affordance. 

Some components have already been pointed out:
- buttons should change on hover
- movie view keywords chips shouldn't have any hover state
...

**Comment by stephanie-cascade8** [comment]
[NOtion](https://www.notion.so/cascade8/Theme-Color-Builder-b3c2b1bdcfc74e5eafe1ad7a452912fd)

In zeplin, refer to the hover state of each components. 

Here are the details of what to implement :

- **Filled buttons** on hover state have their background color change from **primary-500 to primary-800.**
- **Stroke buttons** : idem but on the border.
- **Links** (clickable text inside paragraphs), there should be an animation. The underline text-decoration disappears during hover.
- **Mat-buttons** : original animation on the background (from the angular orginal behaviour)
- **Icons** (idem, original from Angular)

If, for some reasons the **icon** is not inside the mat-button. Make it's color change from **foreground-700 to foreground-900**.

**Comment by stephanie-cascade8** [comment]
This has to be paused until the links updates are implemented.

**Comment by stephanie-cascade8** [comment]
UI recommendation
- [ ] change primary-800 to darker shade : #...
- [ ] apply color change on hover (don't forget the css ease effect)
link to the code. 
- [ ] add discret animation on click. (here I tested simple ones with one line css)
result: 
...

- [ ]

**Comment by stephanie-cascade8** [comment]
The affordance issue is implemented. We made other decisions than the ones described above to fit the builder possibilities. If you need a checkup on the final decisions about affordance here it is : [Notion](https://www.notion.so/cascade8/Links-vs-Buttons-275bc1c81ee04cae98511bdc487a7b52)
