### ISSUE TITLE
Capital Letter Documentation

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#5571]
We use the special english typography rules throughout the apps. 
The aim of the documentation is to explain the main rules to reduce the review time and to automate it if possible. 

N.B. The first letter in a sentence is always capitalized. 

The documentation should contain the rules for the following elements: 
- [ ] Nouns 
- [ ] Verbs
- [ ] Adjectives 
- [ ] Adverbs
- [ ] Pronouns 
- [ ] Articles 
- [ ] Prepositions

And answer the questions: 
- Capitalized or Lowercase? 
- Always or in a special case? 

Possible cases:
- [ ] Main (body) text 
- [ ] CTA
- [ ] Titles (main title, subtitle...)
- [ ] Buttons  

Just an example: 
_Pronouns are in a lowercase for main text and titles, but capitalized in CTAs and buttons_ 

If after filling in the documentation we see that all the elements can be capitalized in a CTA, for example, in CTAs we can give a rule that for CTAs we could use:

 _text-transform: capitalize;_

**Comment by Jackseed** [comment]
We should also consider table column names for this issue

**Comment by 2amarkina** [comment]
Work in progress is [here](https://www.notion.so/cascade8/Capital-Letter-Documentation-a6728c7885314d7d8f6e5a0845ff2768)

**Comment by Jackseed** [comment]
@2amarkina the notion linked is private, it's not in the Cascade8 space

**Comment by RemcoSimonides** [comment]
Hee @2amarkina, this is finished right? Let's give a shout out in Slack to the team so they are aware of its existence and read it. Or do you want to present it?

**Comment by 2amarkina** [comment]
done!
