### ISSUE TITLE
Title Avails - World map & Avails searching criteria

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5573]
## UI
[Zeplin](https://app.zeplin.io/project/5fecb41a2e806651584e265c/screen/606c52549d53ee962c1049b1) - and following pages
[Wireframes](https://www.figma.com/file/oUCgDCGJndPiVhel04GdIH/%5B-Archipel-Content-Renaissance-%5D)

## Description
World map will enable users to look for avails on a title by title basis, compared to the multi-title search implemented in the library page for the MVP. 

Overall, this avails search uses the same logic as the multi-avails search ([see François' explanation of that logic](https://github.com/blockframes/blockframes/issues/4996)). Main differences:
- it focuses only one title; 
- the search is based on 3 parameters out of 4: media, duration and exclusivity (for the calendar view it will be media, territory and exclusivity).

Based on that we display the territories that are available into the world map, we also show territories that are not licensed (not included in the mandate scope between AC & the seller).

The user may then click on any available territory to complete the 4 parameters. It creates a term that is displayed below the world map on the expansion panels.
Some additional criteria may be added by the users in these expansion panels:
- Version: users tell us what are the languages they need to broadcast the title
- Runs: only apply for TV sells (though it will be displayed every time for simplicity). It enable users to specify how many times they want to broadcast the title and if there are catch up rights attached (internet broadcasting on their website).

User may also remove territories or media through the expansion panel. S/he can only **remove** and not add, otherwise we can't know for sure the new terms created through adding are available. 

If the user creates a new search, it will create new terms and thus new expansion panels. 
Terms are saved in the db as soon as they are created so users may leave that page and find it again whenever s/he wants. Terms will be removed from that page only when the user sends the Selection as an offer.

That page was already done last year, some parts of it may be re-used though data model changed. 

## Specs
This Epic is about world map & avails searching criteria, [another Epic](https://github.com/blockframes/blockframes/issues/5574) is dedicated to the expansion panels below.

### Avails form
- Use same logic as multi-avails search
- Use same components as multi avails form (library page)
- Clear button reset all form values
- Apply Filters button saves the form and fills in the world map
- Apply Filters is disabled if one of the inputs is not filled in
- Apply Filters is disabled when clicked 
- Apply Filters is re-enable if one of the inputs changes and all input are fill in

### World map
- Before applying filters, the world map should have an overlay card telling the user to fill the form first
- Above the world map, a sentence says "Click on the territories you're interested in to add them to your Selection.
For territories that are not licensed, feel free to contact CompanyName." CompanyName should be underlined and opens a new tab with the org page view, contact tab `c/o/marketplace/organization/orgId/member`
- Colors:
_Available territories_ - They are the only ones clickable with a hover state, when clicked they change to the validated state. If a new search is made or the inputs cleared, the states are gone. 
_Not licensed territories_ - They are not covered by our mandate, meaning we can't sell it, buyers can still contact seller directly. They have no hover state and no reaction when clicked.
_Unavailable territories_ - They have the world map background color, they have no hover state and no reaction when clicked. 
- For now we won't implement the 2 buttons "Multi-territory" and "Single Territory" as the latter will be implemented with the calendar view (upcoming feature)
- Zoom in & zoom out buttons are for the world map not the whole page
- Select all available territories button does what it says

**Comment by phpgeekfr** [comment]
search for `@TODO #5573` in code
