### ISSUE TITLE
Learn more for Archipel Content

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#5580]
The aim is to provide a user with a tutorial how to use the Avails section on the Film Page. 

The tutorial consists from: 
- clickable link
- modal 
- gifs (demo itself) 

**TO DO:** 
- [x] Validate the modal structure with business team 
- [x] Prepare gifs (check with business team who/how/when)

Here are [the wireframes with 4 versions](https://www.figma.com/file/oUCgDCGJndPiVhel04GdIH/Archipel-Content-Renaissance?node-id=2555%3A1825): 
v1 - simple modal with 1 general gif 
![v1.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1cc01d0b-56f9-4285-86d7-4a49bb74af2a)

v2 - modal with 2 gifs with titles (multi and single territory)
![v2.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1248baef-3fe5-4ab4-a597-28f6673ab6d0)

v3 - modal with 2 gifs + titles and mini descriptions (multi and single territory)
![v3.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1004f9a9-88ae-4092-b6f0-a64ec9e06e28)

v4 - modal with 3 gifs + titles and mini-descriptions (multi and single territory + adding to selection). 
![v4.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/44b9afb9-ec44-4c49-a83b-6d7e96e23c0d)

P.S.
"Ask a question" opens intercom

**Comment by 2amarkina** [comment]
**Last solution** 
The access to the modal remains the same: by clicking on the link "Learn how it works". 

Then this modal appears:
![tabs:toggles](https://user-images.githubusercontent.com/55499036/116057250-e996db00-a67e-11eb-9b33-8a0bd45960ef.gif)

[Link to wireframes udpt.](https://www.figma.com/file/oUCgDCGJndPiVhel04GdIH/%5B-Archipel-Content-Renaissance-%5D?node-id=2555%3A1625)

**Comment by stephanie-cascade8** [comment]
![How-it-works](https://user-images.githubusercontent.com/66258851/117275710-9b43c200-ae5e-11eb-9add-92092e6adaa3.png)
Files to include (temporary, I'm currently working on flinto to have something better with text filling and lighter export)
![multi-territories](https://user-images.githubusercontent.com/66258851/117275785-ae569200-ae5e-11eb-9ad7-c007a442ff10.gif)
![calendar-interaction](https://user-images.githubusercontent.com/66258851/117275805-b1ea1900-ae5e-11eb-8e8a-525c29740cb1.gif)

**Comment by RemcoSimonides** [comment]
This issue is already implemented too :)
