### ISSUE TITLE
Add view counters on NFT player

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5588]
After discussion, we'll have a counter to protect video leaking:
- counter is set to 10 views max per owner
- after 1 view we let 24h to owner to play the film as many times s/he wants
- passed the 24h after a play, a new play is counted and increment his/her counter
- if token owner change we reset the counter
- if token owner change with a transaction value equal to 0 (token give away) > we block the play (counter set to 10?)

**Comment by pldespaigne** [comment]
moved issue to blockframes/nft#61
