### ISSUE TITLE
E2E test - Excel import (movies & contracts)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5589]
To test excel import and allow #5353 to happen we need to import both movies & contracts. 
We'll create movies from scratch to be sure that no contracts are attached to it in the first place. 

Scenario:
- connects with a blockframes admin that has appAccess to `catalog`
- go to catalog app url `/c/o/dashboard/import`
- select "Movies"
- click "Import file"
- selects [that file](https://app.zenhub.com/files/165818079/5f88465e-b0c7-4866-b109-f4c48fac690c/download)
- click on "Start import"
- click on the checkbox "Original Title" on the table header 
- click on Create button on top of the table
- wait for import to be complete (by reading the update text on the button?)
- click on "Cancel" button
- select "Contracts"
- selects [this file](https://app.zenhub.com/files/165818079/24d500b5-705a-4a54-b2b1-8cd95944a5f8/download))
- click on "Start import"
- click on the checkbox "Contract Id" on the table header 
- click on Create button on top of the table
- wait for import to be complete (by reading the update text on the button?)

To check if everything worked out as planned will need another test on the avails.

**Comment by xmano** [comment]
My understanding of the import process..

I think in place of "Create" we have **Save & Finish later** button and click "Cancel" to complete the import:

![image](https://user-images.githubusercontent.com/8731418/115507364-a7922180-a299-11eb-80c2-a003da840b18.png)

**Comment by xmano** [comment]
Was able to get the movie file upload to work. Need to clean up the test script to make it work in actual environment.

![image](https://user-images.githubusercontent.com/8731418/115585410-32e6d380-a2e9-11eb-9ae5-6e81e5257021.png)

**Comment by xmano** [comment]
Tests are working. 

![image](https://user-images.githubusercontent.com/8731418/115846081-2aa0ac80-a43f-11eb-85f0-1987386c6536.png)

Will add this to the repo and also an additional test for importing correct contract.

**Comment by xmano** [comment]
Handled via:
https://github.com/blockframes/blockframes/pull/5609

**Comment by xmano** [comment]
https://github.com/blockframes/blockframes/pull/5609
