### ISSUE TITLE
Analytics discovery

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5590]
We'll use analytics to understand better how users interacts with our apps. This issue is about discovery so it's open to any ideas and you have freedom to go on and try to find patterns wherever you want. 
We should keep track of what you find in the process in a private document and we'll make periodic meetings to discuss your research and see if there are things that need either external data or a deeper search. 

To help you in the process though you can broader your scope as said above, here are main questions that would be interesting to answer:
- How to help buyers connect more often? 
> when and where do they leave?
- Why invited buyers did not come to a screening? 
> did they connect? 
- How to help sellers organize more screenings?

**Comment by 2amarkina** [comment]
Work in progress [here](https://docs.google.com/document/d/1oThKEH9KiuHvdTZlFukP1mdS3ixRnwGmT3Z0IVC3wRc/edit?usp=sharing)
