### ISSUE TITLE
Text inventory

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5591]
At some point we'll need a spreadsheet to implement a CMS that enables admins to change texts without devs' help. 

In the meantime, that spreadsheet will help us:
- to have an overview of text consistency
- to have a single source of truth regarding texts
- to ask for change 

The architecture of the spreadsheet should respect a key/value format. Example
**Homepage Archipel Content**
_Key_                 |    _Value_
Banner title       |     Package together titles from selected sellers

There is no hurry in making the full inventory but the faster we have a first draft the easier it will be to update it with new pages coming.

**Comment by 2amarkina** [comment]
Work in Progress is [here ](https://docs.google.com/spreadsheets/d/1AC2-tjQuBCuF8v-PEof5b6fRhvDe72CMdDwMLaaAMAc/edit#gid=0)
