### ISSUE TITLE
NFT project landing & logo

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5610]
Name: FilmSeriesNFT
url: filmseriesnft.com

### Brand
- Exclusif
- VIP 
- Premium 
- Investissement 
- Collector
- Decentralized 
- Film & série > / Glamour + paillettes 

### Landing page
Title: Welcome to FilmSeriesNFT, the first NFT marketplace for films and TV series.
Subtitle: What can you buy here?
Text:
- VIP Tokens : be the only happy owner of a virtual asset from your favorite content (your favorite movie line, an iconic item from the film…)
- Premiere Tokens : buy access to exclusive virtual screenings of your favorite content and be part of the happy few to watch it on your territory… and re-sell it when you’re done!

Enjoy!
For any questions, please contact : contact@filmseriesnft.com

### References
https://www.popcorngarage.com/
https://opensea.io/

Geeky movies: Star Wars, Toy Story, Back to the future, Jurasik Park...

### Deliverables:
- style guide 
- landing page
- logo
- header / footer (with Powered by Cascade8 & Logical Pictures on the footer)

**Comment by stephanie-cascade8** [comment]
After our meeting with Vincent, we decided to present our idea and first shots to Fred if he's available, before going any further.
Here is our researches, moodboard and first try on illustration and header layouts.
https://www.figma.com/file/cfSSV1Dr0mYgDhhhVg3rvf/NTF-project?node-id=0%3A1

**Comment by Jackseed** [comment]
Artistic direction is validated so now we need to go for finale version:
- [ ] refine colours
- [ ] validate logo
- [ ] validate illustrations

**Comment by jdrns** [comment]
Here is [the figma file](https://www.figma.com/file/cfSSV1Dr0mYgDhhhVg3rvf/NTF-project?node-id=0%3A1) with research work and wip (logo)

**Comment by Mussuranae** [comment]
Done in this [PR](https://github.com/blockframes/nft/pull/65)
