### ISSUE TITLE
3.1 Release - Business Review (Marie)

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#5618]
### IDENTITY PAGE

- [x] Update "Company Name" field hint from "Join an existing company account or create a new one." to **"Select and existing company from the list or create a new one."**
![image](https://user-images.githubusercontent.com/55785823/116065273-2666d000-a687-11eb-8e3d-eb487e68d9dc.png)

- [x] Update "Invitation Pass" field hint from "Your Invitation Pass is the code you received in your invitation email. / Can't find your Invitation Pass code? Contact us" to **"You'll find your Invitation Pass in your invitation email. / Can't find it? Contact us"**
- [x] Underline "Contact us" here, so the user understands it's clickable.

![image](https://user-images.githubusercontent.com/55785823/116065647-83fb1c80-a687-11eb-945c-697036238d65.png)

### POST SIGN UP "WAITING FOR APPROVAL" PAGE

- [x] This snackbar text is not in correct English. It should say: "Your User Account was successfully created. Please wait for our team to check your Company Information."
![image](https://user-images.githubusercontent.com/55785823/116535665-4941f000-a8e4-11eb-9e32-18d1adf8057b.png)

- [x] The introduction text looks too big to me. Could we try a less important text font? Maybe the same font as the small sentence below "Feel free to contact us..." (and maybe juste differentiate the colors?)
![image](https://user-images.githubusercontent.com/55785823/116537414-7db6ab80-a8e6-11eb-8aeb-ec8770f106fd.png)

- [x] Delete white background from Email Validation Icon 
![image](https://user-images.githubusercontent.com/55785823/116537201-35978900-a8e6-11eb-959c-b2f4f25d3e15.png)

- [x] Add capital to "Refresh Page" CTA
![image](https://user-images.githubusercontent.com/55785823/116537345-65469100-a8e6-11eb-8860-acefb7471256.png)

- [x] Line height should not be the same here. The second box sentence should be "closer together" so we understand the separation
![image](https://user-images.githubusercontent.com/55785823/116574245-d51c4200-a90d-11eb-8da0-78da14cd025a.png)

**Comment by maltmayer** [comment]
## MARKETPLACE SCREENING VIEW

- [ ] Invitation status is not centered
![image](https://user-images.githubusercontent.com/55785823/116542084-89a56c00-a8ec-11eb-8972-49ecef074b4d.png)


## MARKETPLACE SCREENING SESSION

- [ ] I don't know if this comes from JWP or from us but the following tooltips should say "Full Screen" not "Fullscreen"
![image](https://user-images.githubusercontent.com/55785823/116535252-d6d11000-a8e3-11eb-920b-bafad68a2ba8.png) 
![image](https://user-images.githubusercontent.com/55785823/116535305-e94b4980-a8e3-11eb-88ab-0fde5c4e90a6.png)

## INVITATIONS
- [ ] The "no" version of a pending invitation should say "Decline" **everywhere** (instead of "Refuse") to match the answered status
![image](https://user-images.githubusercontent.com/55785823/116535543-244d7d00-a8e4-11eb-853f-0dd9d42ff3e3.png)
![image](https://user-images.githubusercontent.com/55785823/116535556-28799a80-a8e4-11eb-9acf-2fde3d89d2f6.png)


- [ ]

**Comment by maltmayer** [comment]
## DASHBOARD MOVIE VIEW

- [ ] Can't see text here
![image](https://user-images.githubusercontent.com/55785823/116569450-af8d3980-a909-11eb-8b8c-f0910903e0e2.png)

- [ ] Display problem here, the image name should stay on one line
![image](https://user-images.githubusercontent.com/55785823/116566432-0d6c5200-a907-11eb-8caa-17742fb1e60e.png)

## DASHBOARD MOVIE FORM 

### SIDE MENU BAR

- [ ] Confusing to have multiple sections in dark grey, it looks like they're all open. I think only the open one should be dark
![image](https://user-images.githubusercontent.com/55785823/116573904-81115d80-a90d-11eb-8b81-83e937286dda.png)
![image](https://user-images.githubusercontent.com/55785823/116574064-a8682a80-a90d-11eb-945d-7822a5a84342.png)

### LEAVING FORM MODALE
- [ ] no space before punctuation in English. Here it's "Are you sure?" not "Are you sure ?"
![image](https://user-images.githubusercontent.com/55785823/116571184-224ae480-a90b-11eb-8074-7f74bfe53b61.png)

### LAST STEP 
- [ ] Spacing issue between Images and Videos
- [ ] Snackbar is not centered
![image](https://user-images.githubusercontent.com/55785823/116569121-61783600-a909-11eb-98c7-1773b94d8e78.png)

- [ ] Spacing is not the same here between the 3 first and the 3 last
![image](https://user-images.githubusercontent.com/55785823/116571665-92596a80-a90b-11eb-8eb8-6e2437e873ed.png)

- [ ] "Technical Information" should be "Technical Specifications"
- [ ] "Format" should be "Formats"
![image](https://user-images.githubusercontent.com/55785823/116571282-3abaff00-a90b-11eb-8092-ad78f78d5ea2.png)

- [ ] "Qualification" should be "Qualifications"
![image](https://user-images.githubusercontent.com/55785823/116571534-75249c00-a90b-11eb-8119-10649a549d33.png)

- [ ] "Selections and Reviews" should be "Selection & Reviews"
![image](https://user-images.githubusercontent.com/55785823/116572691-7bffde80-a90c-11eb-98a0-946cdf4c9e08.png)

- [ ] "Festival & Award" and "Other Festival & Award" should be "Festivals & Awards" and "Other Festivals & Awards"
![image](https://user-images.githubusercontent.com/55785823/116572812-933ecc00-a90c-11eb-85ac-2e9fffdf14d9.png)

- [ ] "Co-production Company should be "Co-Production Company"

- [ ] "Film Review" should be "Film Reviews"
![image](https://user-images.githubusercontent.com/55785823/116571717-9e452c80-a90b-11eb-9586-ed9df9ecf93d.png)

- [ ] I get a permanent error on Production companies, I don't understand why, everything looks okay
![image](https://user-images.githubusercontent.com/55785823/116573718-56bfa000-a90d-11eb-82ba-0dc57730d738.png)
![image](https://user-images.githubusercontent.com/55785823/116573802-69d27000-a90d-11eb-8a5b-2d323e839652.png)


- [ ] Snackbar should say: "Mandatory information missing."
![image](https://user-images.githubusercontent.com/55785823/116568853-24ac3f00-a909-11eb-907e-d09e08c7b2f2.png)

### TITLE INFORMATION / Available Materials

- [ ] Change hint to "Please specify if the original version can be made available or not."
![image](https://user-images.githubusercontent.com/55785823/116566695-41e00e00-a907-11eb-9b7f-c4e09494ec42.png)

### TITLE INFORMATION / Additional Information

- [ ] Rating fields should be 1/2 1/2, not 2/3 1/3 I think as the field hint should not be on 2 lines.

### TITLE INFORMATION / Festivals & Reviews
- [ ] I'm not sur we should show the "*" here as these fields are mandatory only if they're filled. It's confusing
![image](https://user-images.githubusercontent.com/55785823/116568437-c54e2f00-a908-11eb-8e50-e470ccc739fa.png)

### DASHBOARD SCREENING FORM

- [ ] Film list should be in alphabetical order 
![image](https://user-images.githubusercontent.com/55785823/116569577-ce8bcb80-a909-11eb-87b6-0f06e72f6b7a.png)

### MARKETPLACE SIDE MENU

- [ ] Replace "Films" by "Titles"
![image](https://user-images.githubusercontent.com/55785823/116570731-c718f200-a90a-11eb-8e14-243a9a7db8e6.png)

- [ ] I get this weird square around the Archipel Market logo on Safari.
![image](https://user-images.githubusercontent.com/55785823/116570801-d26c1d80-a90a-11eb-9b79-fa155390a798.png)

**Comment by maltmayer** [comment]
## IDENTITY PAGE

- [ ] New Password Confirmation should not appear in error state before clicking on it

https://user-images.githubusercontent.com/55785823/116575555-09443280-a90f-11eb-9d57-d523c1892126.mov

**Comment by maltmayer** [comment]
## DASHBOARD FILE STORAGE
- [ ] The upload component should say "browse your computer." instead of juste "browse"
- [ ] Change CTA text from "Add to list" to "Save Document"
![image](https://user-images.githubusercontent.com/55785823/116576005-76f05e80-a90f-11eb-9b84-77a8e0d61eac.png)

**Comment by maltmayer** [comment]
##DASHBOARD CALENDAR / NEW EVENT MODALE

- [ ] "More Details" with a capital D
![image](https://user-images.githubusercontent.com/55785823/116576275-b3bc5580-a90f-11eb-88b3-6257f49c11a0.png)

- [ ] "Add New Event" with capitals
- [ ] "Select Event Type" with capitals
![image](https://user-images.githubusercontent.com/55785823/116576401-cfbff700-a90f-11eb-9554-e69ff7cbac43.png)

**Comment by maltmayer** [comment]
## SCREENING LIST

- [ ] Invitation statut is not perfectly aligned
![image](https://user-images.githubusercontent.com/55785823/116578065-545f4500-a911-11eb-804f-40b7a150acde.png)

## MARKETPLACE HOMEPAGE
- [ ] Movie carousel banner displays weird
![image](https://user-images.githubusercontent.com/55785823/116578159-693bd880-a911-11eb-8e83-009a5fb44510.png)

**Comment by maltmayer** [comment]
## CALENDAR

- [ ] "Filter-by" should be "Filter by"  
![image](https://user-images.githubusercontent.com/55785823/116578848-1a427300-a912-11eb-9a9f-45825645c67b.png)

**Comment by maltmayer** [comment]
## WISHLIST / EMPTY STATE

- [ ] "Your Wishlist is empty."
- [ ] "Discover Titles"
![image](https://user-images.githubusercontent.com/55785823/116578956-3514e780-a912-11eb-812a-acca94488502.png)

**Comment by maltmayer** [comment]
## DASHBOARD MOViE FORM
- [ ] When I delete a target audience, I get this
![image](https://user-images.githubusercontent.com/55785823/116579263-83c28180-a912-11eb-8e81-3eeb35cf2d21.png)

**Comment by maltmayer** [comment]
## DASHBOARD CALENDAR

- [ ] Weird behavior when I create a new event, it looks like it's "selecting" the calendar field like it's text

https://user-images.githubusercontent.com/55785823/116579549-c8e6b380-a912-11eb-8725-40b50daf93db.mov

**Comment by maltmayer** [comment]
## DASHBOARD MOVIE FORM

- [ ] "persistent links" are "too persistent". Everytime I scroll down, it brings me back to the section I clicked on initially (from the movie view edit buttons)

https://user-images.githubusercontent.com/55785823/116579932-2e3aa480-a913-11eb-8d4c-c6de8082d8c4.mov

**Comment by maltmayer** [comment]
## REQUEST APP ACCESS PAGE

- [ ] Change text to:

Looks like you already have an account on a Cascade8 application!
We noticed that your email address is associated with an existing user account of one of our applications.
To access Archipel Content, please request access and wait for our team's approval.
N.B.: All members from your company will also get granted access to Archipel Content.
Request Access
Refresh Page
![image](https://user-images.githubusercontent.com/55785823/116674744-51ae2f80-a9a5-11eb-93f1-9986cff793be.png)

**Comment by maltmayer** [comment]
## SUCCESSFULLY SENT OFFER

- [ ] "Contact us" is underlined twice
![image](https://user-images.githubusercontent.com/55785823/116693870-c2157a80-a9be-11eb-9517-e2fe92da1842.png)

**Comment by maltmayer** [comment]
## LOG IN PAGE

- [ ] CTA text should be "Log in" to be consistent with the name of the page
![image](https://user-images.githubusercontent.com/55785823/116694092-1c164000-a9bf-11eb-9de1-65a82a86785b.png)

- [ ] "Email address" should be "Email Address"
![image](https://user-images.githubusercontent.com/55785823/116694178-3e0fc280-a9bf-11eb-9cff-80171fc49d6e.png)

**Comment by maltmayer** [comment]
## LANDING PAGE

- [ ] Image display problem on Safari
![image](https://user-images.githubusercontent.com/55785823/116694240-5253bf80-a9bf-11eb-9cb2-cd81bfcf6506.png)

**Comment by maltmayer** [comment]
## CATALOG APP 
### MY SELECTION

- [ ] "Please choose currency" should be "Please select a currency"
![image](https://user-images.githubusercontent.com/55785823/116695890-7ca67c80-a9c1-11eb-853c-c4f95a329c30.png)

- [ ] Is this list the one we agreed on? I thought it was just € and $ or something like that
![image](https://user-images.githubusercontent.com/55785823/116696106-bf685480-a9c1-11eb-98c1-a1350993e697.png)

- [ ] "Total Bucket Price" should be "Total Price"
![image](https://user-images.githubusercontent.com/55785823/116696146-ce4f0700-a9c1-11eb-845c-857b62c8fb92.png)

- [ ] "Delete all the rights for the title" should be "Delete all rights for this title"
![image](https://user-images.githubusercontent.com/55785823/116696281-fe96a580-a9c1-11eb-9911-ed2a06f5462f.png)

- [ ] Image display problem on Safari
![image](https://user-images.githubusercontent.com/55785823/116696386-21c15500-a9c2-11eb-9f5f-c02d48ba6e0c.png)


### MY SELECTION / Offer "Specific terms" Modale

- [ ] Following text should be should be 
"Specific Terms
Please indicate any specific conditions you'd like to request for this deal."
![image](https://user-images.githubusercontent.com/55785823/116695028-4caaa980-a9c0-11eb-9d84-cd58897e0eec.png)

- [ ] There's an unwanted space in the placeholder text of the "Specific Terms" fields
![image](https://user-images.githubusercontent.com/55785823/116694462-9d6dd280-a9bf-11eb-9a87-932a7a346f32.png)

**Comment by maltmayer** [comment]
## DASHBOARD MOVIE VIEW

- [ ] At first when we click on a title, there's an arrow to go back but then it disappears. I think it should either not be here at all, or stay all the time. 

https://user-images.githubusercontent.com/55785823/116712421-20992380-a9d4-11eb-9a4a-784e2140fef1.mov

**Comment by maltmayer** [comment]
## MARKETPLACE EVENT SESSION / Leaving modale

- [ ] No space before punctuation. "Are you sure ?" should be "Are you sure?"
![image](https://user-images.githubusercontent.com/55785823/116713433-13306900-a9d5-11eb-9ef3-a7ee017cc0bc.png)

**Comment by maltmayer** [comment]
## DASHBOARD MOVIE VIEW 
- [ ] The banner theme color is not the same on Chrome and Safari
![image](https://user-images.githubusercontent.com/55785823/116714222-cf8a2f00-a9d5-11eb-8ecd-7e2eb5dc69f4.png)
![image](https://user-images.githubusercontent.com/55785823/116714417-0f511680-a9d6-11eb-9afb-3a7e664d80f0.png)

**Comment by Jackseed** [comment]
Everything transferred to right issue! I keep it open in case there is something new, @RemcoSimonides this is Marie's issue for the release.

**Comment by maltmayer** [comment]
## GENERAL CLICKABLE TEXT DISPLAY ISSUE

- [ ] I've spotted all of the following components where the texts appear underlined and blue when it should be this way (the design team confirms) :
- Calendar 
![image](https://user-images.githubusercontent.com/55785823/116987574-85ec5d80-accf-11eb-812d-d075600bd869.png)
- Marketplace Screening list 
![image](https://user-images.githubusercontent.com/55785823/116987605-8e449880-accf-11eb-88c6-3e96872a85f2.png)
- Marketplace Movie View / banner
![image](https://user-images.githubusercontent.com/55785823/116987629-969cd380-accf-11eb-8532-90cd7a3f3954.png)
- Marketplace Movie View / tabs
![image](https://user-images.githubusercontent.com/55785823/116987645-9ac8f100-accf-11eb-8a30-6589e1e6e065.png)
- Dashboard Movie View / tabs + Missing items
![image](https://user-images.githubusercontent.com/55785823/116987714-addbc100-accf-11eb-8043-cb600c7a432d.png)
- Marketplace Movie component (everywhere) / View More
![image](https://user-images.githubusercontent.com/55785823/116987781-c5b34500-accf-11eb-9ea1-28b3b92a1d91.png)

**Comment by maltmayer** [comment]
## MARKETPLACE MOVIE VIEW / Banner 
- [ ] Wrong default org logo on movie banner in light theme
![image](https://user-images.githubusercontent.com/55785823/116988488-bd0f3e80-acd0-11eb-8ad7-f08abe7427c8.png)

**Comment by maltmayer** [comment]
## IDENTITY PAGE

- [ ] Invitation Pass field behavior issue. The field (even disabled) should not be displayed by default. It should only appear when the user has an invitation.
![image](https://user-images.githubusercontent.com/55785823/116991611-17120300-acd5-11eb-8055-d39beb178839.png)

**Comment by maltmayer** [comment]
## CATALOG MARKETPLACE SELECTION
- [ ] Persistant image display issue on Safari
![image](https://user-images.githubusercontent.com/55785823/117009318-e5586680-aceb-11eb-969a-8ea52b304f22.png)

**Comment by maltmayer** [comment]
## USER PROFILE 

### PROFILE SETTINGS

- [ ] I feel like the titles on this specific page are not in the right color
- [ ] Here, capital i for "Contact Information"
![image](https://user-images.githubusercontent.com/55785823/117008999-94e10900-aceb-11eb-9ca7-842462ddfd01.png)

**Comment by maltmayer** [comment]
## ANY MARKETPLACE
- [ ] I still get this square around the logo. It's not super important to correct I guess, we can live with it but it looks weird. I don't know what you think @RemcoSimonides 
![image](https://user-images.githubusercontent.com/55785823/117010507-28ffa000-aced-11eb-9b85-e2ea30145447.png)

**Comment by maltmayer** [comment]
## ORG CREATION PAGE

- [ ] I get this when I try to log in with maltmayer@cascade8.com on staging. Don't understand what is wrong. 
![image](https://user-images.githubusercontent.com/55785823/117028958-7d5f4b80-acfe-11eb-87ab-2bd9c2a75c33.png)

**Comment by RemcoSimonides** [comment]
I've created an [issue](https://github.com/blockframes/blockframes/issues/5715) for the empty "Thank you for joining us!" page.

Safari fixes should have been solved today. Let's check tomorrow morning in the last deploy to staging.

Square around org logo is not blocking. I'll create an issue for that one too.
