### ISSUE TITLE
Movie: CRUD, list, view, wishlist

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5625]
Tester: Max;
Debugger: Samir

**Comment by Jackseed** [comment]
- [ ] Wrong color foreground-base in light theme and dark theme for the gradient here.

first color of gradient should be #8DA4FA in light
![Capture d’écran 2021-04-28 à 16 19 34](https://user-images.githubusercontent.com/66258851/116419634-8acb9000-a83d-11eb-956f-432b7252ddb5.png)

corrected
![Capture d’écran 2021-04-28 à 16 14 20](https://user-images.githubusercontent.com/66258851/116418932-dcbfe600-a83c-11eb-89fe-b60aa8b6e56f.png)

first color of gradient should be #30344A in dark
![Capture d’écran 2021-04-28 à 16 16 44](https://user-images.githubusercontent.com/66258851/116419278-30323400-a83d-11eb-814d-b1c5568ebedf.png)

corrected 
![Capture d’écran 2021-04-28 à 16 16 33](https://user-images.githubusercontent.com/66258851/116419247-28728f80-a83d-11eb-934c-344936d34458.png)



**Movie: CRUD, list, view, wishlist**
- [ ] Builder/theme colors error on the titles and paragraph.
all h1, h2, h3... should be associated with the var foreground-800
all p, body-1, body-2 foreground-700
all captions foreground-600
This should improve the contrast btw different text types.
<img width="676" alt="Capture d’écran 2021-04-28 à 10 32 45" src="https://user-images.githubusercontent.com/66258851/116375692-cf403700-a80f-11eb-9f12-c3aa3c20964f.png">

- [ ] Chips color background should be associated to background-600
which should correspond to #E7E7E7 in light and #16192E in dark.

On the screenshot, the corrected version (what it should look like)
<img width="389" alt="Capture d’écran 2021-04-28 à 10 56 09" src="https://user-images.githubusercontent.com/66258851/116376590-b5532400-a810-11eb-910d-c77dcf2e9b0b.png">
<img width="412" alt="Capture d’écran 2021-04-28 à 10 57 11" src="https://user-images.githubusercontent.com/66258851/116376598-b6845100-a810-11eb-819a-1c315993f589.png">

- [ ] h5 font-weight from 700 to 600
(I know we're supposed to take off all h5 but we won't be able to work on that soon)
See difference expected here:
<img width="231" alt="Capture d’écran 2021-04-28 à 10 59 57" src="https://user-images.githubusercontent.com/66258851/116376956-05ca8180-a811-11eb-8c22-8a453aba37fd.png">
<img width="226" alt="Capture d’écran 2021-04-28 à 11 00 14" src="https://user-images.githubusercontent.com/66258851/116376977-09f69f00-a811-11eb-96ea-fe167a4c8307.png">

- [ ] On hover darken the color of the icons to show that they are clickable. 
from foreground-700 to 800
_(All other icons are normally inside mat-buttons (so it's not a global solution here).
here, we need to sho the user that the icons are clickable. and especially because we have another icon in the top right-hand corner of the card that is not. Difference of behaviour btw both is important to highlight. )_
<img width="325" alt="Capture d’écran 2021-04-28 à 11 02 41" src="https://user-images.githubusercontent.com/66258851/116377714-c18bb100-a811-11eb-9feb-ce6c3f06d321.png">
![Capture d’écran 2021-04-28 à 11 06 26](https://user-images.githubusercontent.com/66258851/116377750-cb151900-a811-11eb-86a6-e099f0e81a25.png)

- [ ] My Mistake in the background variables called in layout and cards. 
Put back the background-800 on cards.

**Comment by Jackseed** [comment]
- [ ]  **/!\ Wishlist is broken /!\** both card button and banner movie view action button are not doing a thing

**Comment by Jackseed** [comment]
- [ ] The new whishlist button has been implemented but not for all the states (hover and selected are missing)
Here is the initial proposition from @jdrns, who should be contacted for any questions re this component:

> [Here](https://zpl.io/blKQozk) is the new button ready to implement on the movie page with its [hover state](https://zpl.io/2yg45Qp) and [selected state](https://zpl.io/Vk4gLl8) (Wishlist only). For the button "Add to Wishlist/Remove from Wishlist", the new icons can be found [here (outline)](https://drive.google.com/file/d/1S8t-Nq4fBEguMkUXtYxLwHozRirHoIQV/view?usp=sharing) and [here (filled)](https://drive.google.com/file/d/13NK-DTtPtAfYa1iaX8i8VNJdU-SYX6Cb/view?usp=sharing), for the rest, no changes, we should use the same icons as previously.
- [ ] whishlist button should be left align with the others elements above
![image](https://user-images.githubusercontent.com/14964443/116558170-7223ae80-a8ff-11eb-9e0c-eda83262454e.png)

- [ ] Also implement that new button in the screening list for the action buttons and left align it
![image](https://user-images.githubusercontent.com/14964443/116558296-9089aa00-a8ff-11eb-9ed2-db161876db13.png)

**Comment by SamirTouira** [comment]
> * [ ]   *_/!\ Wishlist is broken /!*_ both card button and banner movie view action button are not doing a thing

I didn't see any issues with those wishlist buttons. When I click on add, it adds correctly, same for deleting a movie from the wishlist, otherwise i didn't understood this task.

**Comment by Jackseed** [comment]
> > * [ ]    __/!\ Wishlist is broken /!__ both card button and banner movie view action button are not doing a thing
> 
> I didn't see any issues with those wishlist buttons. When I click on add, it adds correctly, same for deleting a movie from the wishlist, otherwise i didn't understood this task.

My bad, I retried and it's working fine...

**Comment by Jackseed** [comment]
**Projects Page**
- [ ] Strange bug with vertical scrollbar on the filters using Safari. 
<img width="1268" alt="Снимок экрана 2021-04-29 в 09 40 28" src="https://user-images.githubusercontent.com/55499036/116518240-4a692200-a8d0-11eb-8cd7-6c6a48a9c5af.png">

**Marketplace Side everywhere** 

- [ ]  As Promotional Images on the film page became clickable (which is great!), maybe we could put a hand instead of cursor to point it out? 
<img width="597" alt="Снимок экрана 2021-04-29 в 15 20 50" src="https://user-images.githubusercontent.com/55499036/116557197-7ef3d280-a8fe-11eb-8e7d-763e893e8d7b.png">

![1200px-Mouse-cursor-hand-pointer svg](https://user-images.githubusercontent.com/55499036/116557538-ced29980-a8fe-11eb-9daf-450a3e0eaf72.png)

**Comment by Jackseed** [comment]
- [ ] Dashboard title table, change "# VIEWS" for "# Views"
![image](https://user-images.githubusercontent.com/14964443/116569254-81a7f500-a909-11eb-9e60-ce6b6fce0307.png)

**Comment by SamirTouira** [comment]
> * [ ]  The new whishlist button has been implemented but not for all the states (hover and selected are missing)
>   Here is the initial proposition from @jdrns, who should be contacted for any questions re this component:
> 
> > [Here](https://zpl.io/blKQozk) is the new button ready to implement on the movie page with its [hover state](https://zpl.io/2yg45Qp) and [selected state](https://zpl.io/Vk4gLl8) (Wishlist only). For the button "Add to Wishlist/Remove from Wishlist", the new icons can be found [here (outline)](https://drive.google.com/file/d/1S8t-Nq4fBEguMkUXtYxLwHozRirHoIQV/view?usp=sharing) and [here (filled)](https://drive.google.com/file/d/13NK-DTtPtAfYa1iaX8i8VNJdU-SYX6Cb/view?usp=sharing), for the rest, no changes, we should use the same icons as previously.


Zeplin asks me a permission access when I click on those links, can you please allow me this?

**Comment by SamirTouira** [comment]
> **Projects Page**
> 
> * [ ]  Strange bug with **vertical** scrollbar on the filters using Safari, if possible, remove it
> 
> <img alt="Снимок экрана 2021-04-29 в 09 40 28" width="1268" src="https://user-images.githubusercontent.com/55499036/116518240-4a692200-a8d0-11eb-8cd7-6c6a48a9c5af.png">

On Browserstack, sometimes it appears and sometimes not... Even if I change the resolutions window to smaller. I can however make a PR to hide the vertical scrollbar and see later if it will restart or not. What do you think about this @Jackseed ?

**Comment by SamirTouira** [comment]
> * [ ]  Dashboard title table, change "# VIEWS" for "# Views"
>   ![image](https://user-images.githubusercontent.com/14964443/116569254-81a7f500-a909-11eb-9e60-ce6b6fce0307.png)

Sorry but I prefer to ask: In Catalog, all the titles on top of the table are in capital letters. Should we let the first capital letter and we let the rest small like for # Views?

**Comment by jdrns** [comment]
> > * [ ]   The new whishlist button has been implemented but not for all the states (hover and selected are missing)
> >   Here is the initial proposition from @jdrns, who should be contacted for any questions re this component:
> > 
> > > [Here](https://zpl.io/blKQozk) is the new button ready to implement on the movie page with its [hover state](https://zpl.io/2yg45Qp) and [selected state](https://zpl.io/Vk4gLl8) (Wishlist only). For the button "Add to Wishlist/Remove from Wishlist", the new icons can be found [here (outline)](https://drive.google.com/file/d/1S8t-Nq4fBEguMkUXtYxLwHozRirHoIQV/view?usp=sharing) and [here (filled)](https://drive.google.com/file/d/13NK-DTtPtAfYa1iaX8i8VNJdU-SYX6Cb/view?usp=sharing), for the rest, no changes, we should use the same icons as previously.
> 
> Zeplin asks me a permission access when I click on those links, can you please allow me this? @Jackseed @jdrns

You should be good to go know, i granted you access

**Comment by Jackseed** [comment]
> > * [ ]   Dashboard title table, change "# VIEWS" for "# Views"
> >   ![image](https://user-images.githubusercontent.com/14964443/116569254-81a7f500-a909-11eb-9e60-ce6b6fce0307.png)
> 
> Sorry but I prefer to ask: In Catalog, all the titles on top of the table are in capital letters. Should we let the first capital letter and we let the rest small like for # Views in Festival?

@SamirTouira thanks for asking, yes let's do the same as Festival: only first capital letter and rest small like `festival`

**Comment by Jackseed** [comment]
> > **Projects Page**
> > 
> > * [ ]   Strange bug with **vertical** scrollbar on the filters using Safari, if possible, remove it
> > 
> > <img alt="Снимок экрана 2021-04-29 в 09 40 28" width="1268" src="https://user-images.githubusercontent.com/55499036/116518240-4a692200-a8d0-11eb-8cd7-6c6a48a9c5af.png">
> 
> On Browserstack, sometimes it appears and sometimes not... Even if I change the resolutions window to smaller. I can however make a PR to hide the vertical scrollbar and see later if it will restart or not. What do you think about this @Jackseed ?

Yep please do that we don't need that vertical scrollbar

**Comment by SamirTouira** [comment]
> * [ ]  The new whishlist button has been implemented but not for all the states (hover and selected are missing)
>   Here is the initial proposition from @jdrns, who should be contacted for any questions re this component:
> 
> > [Here](https://zpl.io/blKQozk) is the new button ready to implement on the movie page with its [hover state](https://zpl.io/2yg45Qp) and [selected state](https://zpl.io/Vk4gLl8) (Wishlist only). For the button "Add to Wishlist/Remove from Wishlist", the new icons can be found [here (outline)](https://drive.google.com/file/d/1S8t-Nq4fBEguMkUXtYxLwHozRirHoIQV/view?usp=sharing) and [here (filled)](https://drive.google.com/file/d/13NK-DTtPtAfYa1iaX8i8VNJdU-SYX6Cb/view?usp=sharing), for the rest, no changes, we should use the same icons as previously.

I tried to replace the new heart icon filled, but the size isn't the same than the older, then I got this:

![image](https://user-images.githubusercontent.com/52285231/116667386-689c5400-a99c-11eb-9d2a-38b489215327.png)

Was about this: https://drive.google.com/file/d/13NK-DTtPtAfYa1iaX8i8VNJdU-SYX6Cb/view

**Comment by fritzschoff** [comment]
@SamirTouira you need to use `<mat-icon svgIcon="heart"></mat-icon>`
If you having trouble, DM me

**Comment by SamirTouira** [comment]
> * [ ]  Also implement that new button in the screening list for the action buttons and left align it
>   ![image](https://user-images.githubusercontent.com/14964443/116558296-9089aa00-a8ff-11eb-9ed2-db161876db13.png)

Which new button do you mean please?

**Comment by Jackseed** [comment]
I'm not sure whereas it's a new component but it should use the same as add to wishlist button @fritzschoff could you confirm?

**Comment by SamirTouira** [comment]
> * [ ]  Chips color background should be associated to background-600
>   which should correspond to #E7E7E7 in light and #16192E in dark.

Are you sure for this #16192E ? Our basic background-600 is #06081c and the difference between #06081c and #16192E is practically non-existent.

**Comment by RemcoSimonides** [comment]
- [ ] Wrong default org logo on movie banner in light theme
![image](https://user-images.githubusercontent.com/55785823/116988488-bd0f3e80-acd0-11eb-8ad7-f08abe7427c8.png)

Dark theme:
![image](https://user-images.githubusercontent.com/27687382/116989628-45421380-acd2-11eb-987d-153b8d1597e3.png)

Light theme:
![image](https://user-images.githubusercontent.com/27687382/116989669-5723b680-acd2-11eb-8087-8ebe58c5405c.png)

**Comment by RemcoSimonides** [comment]
It's actually correct logo but with this poster it doesn't look good ☝️  let me check with stephanie
