### ISSUE TITLE
User: CRUD

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5626]
Tester: Samir
Debugger: Max

**Comment by Jackseed** [comment]
- [ ] There shouldn't be a space before the question mark 
![Screenshot 2021-04-28 at 10.08.21.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/a0fd67bb-0ffe-42fa-97cf-8f1a10fec259)

- [ ] There shouldn't be a space before the question mark 
![Screenshot 2021-04-28 at 10.10.55.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/a20b644d-439e-4edf-b0e6-40200c3c0cec)

- [ ] Text of selected should be in contrast colour (white for light theme)
![Screenshot 2021-04-28 at 10.14.58.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/e20417fe-4589-40c0-8f61-14f639f7dcc8)

### Sign up confirmation page ###
- [ ] Underline should be the same colour as text
![Screenshot 2021-04-28 at 10.21.46.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/37278667-594f-4dd9-86cf-640614570bb7)

- [ ] There shouldn't be a white background on this icon
![Screenshot 2021-04-28 at 10.22.40.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/9317887c-0487-4fc9-87ef-f7cbbbf9a6d1)

- [ ] Add a tooltip on the refresh button: "Refresh page."
![A.gif](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/b162325d-46d9-49f5-9f55-07a739cb4d6b)

**Comment by Jackseed** [comment]
- [ ] The email validation guard is blocking old users!! It shouldn't as we have no way to help them for now. This guard should only block **new** user while they haven't verify their email address
linked to #5647

**Comment by Jackseed** [comment]
**Auth Login**

- [ ] Put back the background-800 on cards. (same as above)

- [ ] Signing-up : Line height problem here (didn't know how to sole it with inspector css)
![Capture d’écran 2021-04-28 à 16 25 34](https://user-images.githubusercontent.com/66258851/116420941-b69b4580-a83e-11eb-9eba-d7fd2942877d.png)

- [ ] Color white on the text (contrast color for primary_500 backgrounds in the builder)
![Capture d’écran 2021-04-28 à 16 30 14](https://user-images.githubusercontent.com/66258851/116421435-1eea2700-a83f-11eb-8c09-7bc09b040f8b.png)

**Comment by Jackseed** [comment]
> * [ ]  _(@pldespaigne )_ The email validation guard is blocking old users!! It shouldn't as we have no way to help them for now. This guard should only block **new** user while they haven't verify their email address
>   linked to #5647
>   user: [dev+leonel-ody@blockframes.io](mailto:dev+leonel-ody@blockframes.io)
> * [ ]  Looks a bit different but triggered by the same guard, I tried to connect with [dev+malcolm-chl@blockframes.io](mailto:dev+malcolm-chl@blockframes.io) on festival and I got this broken page with error:
>   `TypeError: Cannot read property 'toOrg' of undefined at n.project (organization-pending.component.ts:42)`

these 2 are related to a bad test: I went directly on `/c/organization/join-congratulations` with a correct user

**Comment by fritzschoff** [comment]
![image](https://user-images.githubusercontent.com/39312833/116532950-1f3afe80-a8e1-11eb-874b-465a04bc9e51.png)
 this is the default behavior of mat checkbox labels. Can you check if that is okay or we would need to overwrite it. Side effect: need to check all the other mat checkboxes

**Comment by Jackseed** [comment]
> ![image](https://user-images.githubusercontent.com/39312833/116532950-1f3afe80-a8e1-11eb-874b-465a04bc9e51.png)
> this is the default behavior of mat checkbox labels. Can you check if that is okay or we would need to overwrite it. Side effect: need to check all the other mat checkboxes @Jackseed

Ok nevermind we won't have time to check everything

**Comment by Jackseed** [comment]
### IDENTITY PAGE

- [ ] Update "Company Name" field hint from "Join an existing company account or create a new one." to "Select an existing company from the list or create a new one."
![image](https://user-images.githubusercontent.com/55785823/116065273-2666d000-a687-11eb-8e3d-eb487e68d9dc.png)

- [ ] Update "Invitation Pass" field hint from
1. on the left "Your Invitation Pass is the code you received in your invitation email. " to "You'll find your Invitation Pass in your invitation email."
2. on the right "Can't find your Invitation Pass code? Contact us" to "Can't find it? Contact us"
3. Underline "Contact us", so the user understands it's clickable.
![image](https://user-images.githubusercontent.com/55785823/116065647-83fb1c80-a687-11eb-945c-697036238d65.png)


### POST SIGN UP "WAITING FOR APPROVAL" PAGE

- [ ] This snackbar text is not in correct English. It should say: "Your User Account was successfully created. Please wait for our team to check your Company Information."
![image](https://user-images.githubusercontent.com/55785823/116535665-4941f000-a8e4-11eb-9e32-18d1adf8057b.png)

- [ ] Add capital to "Refresh Page" CTA
![image](https://user-images.githubusercontent.com/55785823/116537345-65469100-a8e6-11eb-8860-acefb7471256.png)

**Comment by Jackseed** [comment]
**Toolbar**
- [ ] When hovering "Log out" there is extra space on the left. The color should take all the place. 
<img width="368" alt="Снимок экрана 2021-04-29 в 09 42 32" src="https://user-images.githubusercontent.com/55499036/116517938-f100f300-a8cf-11eb-942b-75865bd89606.png">

- [ ] Also, "Log out" should be centered

**Comment by fritzschoff** [comment]
all done expect for the email svg. @jdrns will provide soon the new icons

**Comment by Jackseed** [comment]
## IDENTITY PAGE

- [ ] New Password Confirmation should not appear in error state before clicking on it

**Comment by RemcoSimonides** [comment]
- [ ] Invitation Pass field behavior issue. The field (even disabled) and every text associated to it should not be displayed by default. It should only appear when the user has an invitation.
![image](https://user-images.githubusercontent.com/55785823/116991611-17120300-acd5-11eb-8055-d39beb178839.png)

- [ ] the "Can't find it? Contact us" is too far from the Invitation Pass field, it doesn't work.
![image](https://user-images.githubusercontent.com/55785823/116991687-3ad54900-acd5-11eb-9852-8cd14be86846.png)
![image](https://user-images.githubusercontent.com/55785823/116991710-43c61a80-acd5-11eb-825e-ca3cc1291354.png)

**Comment by phpgeekfr** [comment]
>     * Invitation Pass field behavior issue. The field (even disabled) and every text associated to it should not be displayed by default. It should only appear when the user has an invitation.
```
<ng-container *ngIf="true">
```
maybe that is why ^^
```
instead of <ng-container *ngIf="form.get('generatedPassword').enabled">```
