### ISSUE TITLE
Set up DRMs

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#5642]
This is a general issue to think and discuss setting up the DRMs in Archipel.

- Because we fear that DRMs might prevent some legit users to watch video, we also want to keep not DRMs protected videos.
- This mean that we need to go with an hybrid system _(DRM & not DRM)_
- This mean we need to have 2 jwp properties in the env
- This mean we need to have separate jwp ids for a single video _(one id for DRM and one for regular)_
- We need to think of how the hybrid system will work from a user point of view:
  - (A) Is the DRM the default and we allow seller to create regular videos ? Is it the other way around ?
  - (A) Is it both _(DRM and regular)_ by default ?
  - (B) We should update UI accordingly _(dropdown select ? check box ?)_ at upload time and/or at event edit time.
  - We should update the player to handle both video types and to be able to fallback when needed. (⚠️how can we do this without a user manual action or without breaking the security ? )

**Comment by Jackseed** [comment]
Thanks for the sum up issue. 
Regarding business, default should be not DRM as long as we haven't thoroughly tested it. I even consider hiding the option at first and enabling it only for selected sellers that are up for tests.

Re design, indeed it will need a select or radio button to choose what they want to use. It should be on the screening long form.

Re deadlines, we won't have more than this sprint to move on with DRM so I think we should focus on:
- using main JW Player account for NFT app;
- implement & test on Safari

The implementation on festival app will come later when we'll get a dedicated time.
