### ISSUE TITLE
Design Review - 

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#5644]
### **A.Market**

- [x] Design a 404 page and center the content vertically.
![Capture d’écran 2021-04-28 à 10.21.58.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/1ea9aa6e-45be-4988-adf3-98d1ce8ef3a1)

- [x] Wrong color foreground-base in light theme and dark theme for the gradient here.

first color of gradient should be #8DA4FA in light
![Capture d’écran 2021-04-28 à 16 19 34](https://user-images.githubusercontent.com/66258851/116419634-8acb9000-a83d-11eb-956f-432b7252ddb5.png)

corrected
![Capture d’écran 2021-04-28 à 16 14 20](https://user-images.githubusercontent.com/66258851/116418932-dcbfe600-a83c-11eb-89fe-b60aa8b6e56f.png)

first color of gradient should be #30344A in dark
![Capture d’écran 2021-04-28 à 16 16 44](https://user-images.githubusercontent.com/66258851/116419278-30323400-a83d-11eb-814d-b1c5568ebedf.png)

corrected 
![Capture d’écran 2021-04-28 à 16 16 33](https://user-images.githubusercontent.com/66258851/116419247-28728f80-a83d-11eb-934c-344936d34458.png)

**Movie: CRUD, list, view, wishlist**
- [x] Builder/theme colors error on the titles and paragraph.
all h1, h2, h3... should be associated with the var foreground-800
all p, body-1, body-2 foreground-700
all captions foreground-600
This should improve the contrast btw different text types.
<img width="676" alt="Capture d’écran 2021-04-28 à 10 32 45" src="https://user-images.githubusercontent.com/66258851/116375692-cf403700-a80f-11eb-9f12-c3aa3c20964f.png">

- [x] Chips color background should be associated to background-600
which should correspond to #E7E7E7 in light and #16192E in dark.

On the screenshot, the corrected version (what it should look like)
<img width="389" alt="Capture d’écran 2021-04-28 à 10 56 09" src="https://user-images.githubusercontent.com/66258851/116376590-b5532400-a810-11eb-910d-c77dcf2e9b0b.png">
<img width="412" alt="Capture d’écran 2021-04-28 à 10 57 11" src="https://user-images.githubusercontent.com/66258851/116376598-b6845100-a810-11eb-819a-1c315993f589.png">

- [x] h5 font-weight from 700 to 600
(I know we're supposed to take off all h5 but we won't be able to work on that soon)
See difference expected here:
<img width="231" alt="Capture d’écran 2021-04-28 à 10 59 57" src="https://user-images.githubusercontent.com/66258851/116376956-05ca8180-a811-11eb-8c22-8a453aba37fd.png">
<img width="226" alt="Capture d’écran 2021-04-28 à 11 00 14" src="https://user-images.githubusercontent.com/66258851/116376977-09f69f00-a811-11eb-96ea-fe167a4c8307.png">

- [x] On hover darken the color of the icons to show that they are clickable. 
from foreground-700 to 800
_(All other icons are normally inside mat-buttons (so it's not a global solution here).
here, we need to sho the user that the icons are clickable. and especially because we have another icon in the top right-hand corner of the card that is not. Difference of behaviour btw both is important to highlight. )_
<img width="325" alt="Capture d’écran 2021-04-28 à 11 02 41" src="https://user-images.githubusercontent.com/66258851/116377714-c18bb100-a811-11eb-9feb-ce6c3f06d321.png">
![Capture d’écran 2021-04-28 à 11 06 26](https://user-images.githubusercontent.com/66258851/116377750-cb151900-a811-11eb-86a6-e099f0e81a25.png)

- [x] My Mistake in the background variables called in layout and cards. 
Put back the background-800 on cards.

**Auth Login**

- [x] Put back the background-800 on cards. (same as above)
- [x] Signing-up : Line height problem here (didn't know how to sole it with inspector css)
![Capture d’écran 2021-04-28 à 16 25 34](https://user-images.githubusercontent.com/66258851/116420941-b69b4580-a83e-11eb-9eba-d7fd2942877d.png)
-[ ] Color white on the text (contrast color for primary_500 backgrounds in the builder)
![Capture d’écran 2021-04-28 à 16 30 14](https://user-images.githubusercontent.com/66258851/116421435-1eea2700-a83f-11eb-8c09-7bc09b040f8b.png)

- [x] On safari : put some maring-left (16px) before the filled button
![Capture d’écran 2021-04-28 à 16 34 38](https://user-images.githubusercontent.com/66258851/116422133-b9e30100-a83f-11eb-9790-c4c5e7f4a539.png)

- [x] "Company" should be a title not a link? 
![Capture d’écran 2021-04-28 à 16 37 20](https://user-images.githubusercontent.com/66258851/116422515-1cd49800-a840-11eb-9424-fd366f4ba9fc.png)

**Landing**
- [x] Image background not working here on safari
![Capture d’écran 2021-04-28 à 16 48 19](https://user-images.githubusercontent.com/66258851/116424206-9c169b80-a841-11eb-9649-937c0452c097.png)

**Settings**
- [x] Same as all pages: gradient background problem and cards-background ui mistake to correct.
See above.

- [x] Tooltips 
I guess we can't change the foreground on tooltips?
This problem came back several times (can I do it live with a dev to see what's possible with the builder??)
![Capture d’écran 2021-04-28 à 16 54 29](https://user-images.githubusercontent.com/66258851/116425294-79d14d80-a842-11eb-9bcf-d980fd6aa4ca.png)

**Comment by Jackseed** [comment]
@stephanie-cascade8 thanks I transferred everything either to devs or new UI issue (404 page). I close it to know it's done but don't hesitate to re-open it and tag me if you find something new
