### ISSUE TITLE
Design Review UX/UI — Release 3.1

### ISSUE THREAD

**Issue by jdrns** [blockframes/blockframes#5650]
**Review made on Safari** 
# Cross App # 
### Log In ###
- [x] There shouldn't be a space before the question mark 
![Screenshot 2021-04-28 at 10.08.21.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/a0fd67bb-0ffe-42fa-97cf-8f1a10fec259)

### Sign Up ###
- [x] The underline be the same colour as the text
or should we use 'Already have an account?' + below Button 'Login in here' same as 'I don't have an account' on Sign up page? 
![Screenshot 2021-04-28 at 10.02.01.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/4f96f563-02c9-4846-96b1-ce35502e3632)

- [x] There shouldn't be a space before the question mark 
![Screenshot 2021-04-28 at 10.10.55.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/a20b644d-439e-4edf-b0e6-40200c3c0cec)

- [x] Logo is overlapping with a cloud 
![Screenshot 2021-04-28 at 10.12.06.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/c406df79-d96a-49d1-acd2-8fefa9603026)
 
- [x] Text of selected should be in contrast colour (white for light theme)
![Screenshot 2021-04-28 at 10.14.58.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/e20417fe-4589-40c0-8f61-14f639f7dcc8)

- [x] Tooltip is not really readable because its colour is white on a light grey background, either text or background should be darker  
![Screenshot 2021-04-28 at 10.16.26.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/6b301ac4-534b-4ab2-998c-f63751a04660)

- [x] There is two hints here and it can be confusing <img width="878" alt="Screenshot 2021-04-28 at 15 51 09" src="https://user-images.githubusercontent.com/79836137/116418516-82bf2080-a83c-11eb-8072-b98e62f07f64.png">

Possible solution discussed with @2amarkina : We add an icon with text and a link
<img width="369" alt="Снимок экрана 2021-04-28 в 15 53 06" src="https://user-images.githubusercontent.com/79836137/116418674-a84c2a00-a83c-11eb-8dd5-20d9fc3ef5d7.png">

### Sign up confirmation page ###
- [x] Underline should be the same colour as text
![Screenshot 2021-04-28 at 10.21.46.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/37278667-594f-4dd9-86cf-640614570bb7)

- [x] There shouldn't be a white background on this icon
![Screenshot 2021-04-28 at 10.22.40.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/9317887c-0487-4fc9-87ef-f7cbbbf9a6d1)

- [x] Should we have two different icons for Organisation Data and Organisation Approval? 
![Screenshot 2021-04-28 at 10.23.19.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/5f9cfc2b-0930-4af7-965a-cb93d80e9852)

- [x] I'm not sure what that button should do, does it only refresh the page? We should probably have a tooltip here
![A.gif](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/b162325d-46d9-49f5-9f55-07a739cb4d6b)

### Toolbar ### 
- [x] Invitation Icon is too big (we should redesign it with margins around) 
![Screenshot 2021-04-28 at 10.35.07.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/bf6e64f0-96af-434d-bf97-88827f47678d)
- [x] Also the envelope in the icon should be white or at least have an opacity 0 to see the colour of the toolbar

### Activity Feed ### 
- [x] Icon for 'Mark all as read' should be the same icon as 'Mark as read' (double tick) 
![Screenshot 2021-04-28 at 10.32.12.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/14d0c40c-b7f2-40b7-821c-67e4d43cac9d)

**Comment by jdrns** [comment]
# Market #
### Landing page ### 
- [ ] Logo isn't taking the whole toolbar in height
![Screenshot 2021-04-28 at 09.53.19.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/1783db90-5a7a-426c-857c-9e76e42a3414)

- [ ] Invitation icon is a bit too big?
![Screenshot 2021-04-28 at 09.53.56.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/0268c9c9-96ba-4c29-9adb-a9bae1084532)

- [ ] Shouldn't the features cards be white?
![Screenshot 2021-04-28 at 09.56.53.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/5c737a68-f37a-42af-bdac-afe1127cfaa7)

- [ ] Footer is stuck to the bottom of the page, there no padding below 
![Screenshot 2021-04-28 at 09.58.31.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/4cc86ad9-f549-4e0a-a836-c978cca9f3a2)

## Dashboard ##
- [ ] Is it normal to have that illustration with colour? 
<img width="343" alt="Screenshot 2021-04-28 at 10 43 24" src="https://user-images.githubusercontent.com/79836137/116374740-ddda1e80-a80e-11eb-8418-a4e0cd715f3f.png">

 
## Marketplace ##
### Home ###
- [ ] Movie image isn't the same size as the others (it's a movie from my organisation, not sure if that's what makes a difference) 
<img width="1079" alt="Screenshot 2021-04-28 at 11 06 41" src="https://user-images.githubusercontent.com/79836137/116377773-d10afa00-a811-11eb-87f9-0d404c8cf49c.png">

### Films ###
- [ ] Should the checkboxs follow a chronological order? As in the movie form (see below)
<img width="434" alt="Screenshot 2021-04-28 at 11 05 11" src="https://user-images.githubusercontent.com/79836137/116377579-9d2fd480-a811-11eb-8337-a60b2f0bea52.png">
** What's in the Movie form ** 
<img width="835" alt="Screenshot 2021-04-28 at 11 07 45" src="https://user-images.githubusercontent.com/79836137/116377957-f7c93080-a811-11eb-99f9-da782600490d.png">

- [ ] Shouldn't we put original first?
<img width="582" alt="Screenshot 2021-04-28 at 11 12 41" src="https://user-images.githubusercontent.com/79836137/116378683-a8373480-a812-11eb-91b2-e1756ca59a46.png">

- [ ] Is it okay to have a button in all caps here? <img width="1271" alt="Screenshot 2021-04-28 at 11 14 26" src="https://user-images.githubusercontent.com/79836137/116378996-e7fe1c00-a812-11eb-8c45-b94388965a2e.png">

### Film Page ### 
eg: [Hunted](https://staging.archipelmarket.com/c/o/marketplace/title/KUFRFI3VQ5HLOdymnEX5/main) 
- [ ] Illustration shouldn't have a background 
<img width="455" alt="Screenshot 2021-04-28 at 11 22 43" src="https://user-images.githubusercontent.com/79836137/116380237-0fa1b400-a814-11eb-99b4-bd10aced9d29.png">

### Event Page — Screening ###
- [ ] Accepted should be centerred
<img width="705" alt="Screenshot 2021-04-28 at 11 21 13" src="https://user-images.githubusercontent.com/79836137/116379996-da956180-a813-11eb-8265-5f5f2dcf9f55.png">

- [ ] When I am already accepted to attend a screening, or when my request is pending, the section 'Next screenings' doesn't allow me to register for another session (which makes sense) but should we add a message here saying 'You already registered', 'You request is pending' or something along those lines? We could potentially link this to [this issue](https://github.com/blockframes/blockframes/issues/5064) 
![B](https://user-images.githubusercontent.com/79836137/116381987-b89cde80-a815-11eb-8530-74463d382e7e.gif)

- [ ] Tiny detail but when I hover 'Accept', the icon of 'Refuse' jumps a little 
![c](https://user-images.githubusercontent.com/79836137/116383804-7e344100-a817-11eb-9264-6c719a520308.gif)

**Comment by jdrns** [comment]
# Content #
### Landing Page ### 
- [ ] Too much space under the logo, logo should be centered vertically 
<img width="488" alt="Screenshot 2021-04-28 at 12 16 07" src="https://user-images.githubusercontent.com/79836137/116387845-842c2100-a81b-11eb-9e76-49231073eaa1.png">

- [ ] Problem with the size of the image 
![D](https://user-images.githubusercontent.com/79836137/116388050-bb023700-a81b-11eb-96a3-2eae4f87695d.gif)

- [ ] Lots of links have double underline (because of the recent changes of interaction with links) <img width="650" alt="Screenshot 2021-04-28 at 12 18 43" src="https://user-images.githubusercontent.com/79836137/116388230-e422c780-a81b-11eb-99fc-cefc949d0403.png">

- [ ] Same as Market, footer is stuck to the bottom of the page, padding is missing 
<img width="1440" alt="Screenshot 2021-04-28 at 12 20 27" src="https://user-images.githubusercontent.com/79836137/116388439-1f24fb00-a81c-11eb-93b6-3e824d336041.png">

**Comment by Jackseed** [comment]
> * Should we have two different icons for Organisation Data and Organisation Approval?
>   ![Screenshot 2021-04-28 at 10.23.19.png](https://camo.githubusercontent.com/962652bf2bc4d4dfac98e43a7edeb9c86ff511e2a3d6293799a2a6f166043009/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630336361653162356330353863666430613538346635662f35663963666332622d303933302d346166372d393635612d636239336438306539383532)

Agree, would you have an existing icon that work here?

**Comment by Jackseed** [comment]
> ### Dashboard
> * [ ]  Is it normal to have that illustration with colour?
> 
> <img alt="Screenshot 2021-04-28 at 10 43 24" width="343" src="https://user-images.githubusercontent.com/79836137/116374740-ddda1e80-a80e-11eb-8418-a4e0cd715f3f.png">

That's different from the placeholder I got in the org settings so it's not normal but I can't say which one is the good one... @stephanie-cascade8 do you know?
![image](https://user-images.githubusercontent.com/14964443/116400886-dde81780-a82a-11eb-8db5-9969c723a51a.png)

**Comment by stephanie-cascade8** [comment]
> > ### Dashboard
> > 
> > * [ ]   Is it normal to have that illustration with colour?
> > 
> > <img alt="Screenshot 2021-04-28 at 10 43 24" width="343" src="https://user-images.githubusercontent.com/79836137/116374740-ddda1e80-a80e-11eb-8418-a4e0cd715f3f.png">
> 
> That's different from the placeholder I got in the org settings so it's not normal but I can't say which one is the good one... @stephanie-cascade8 do you know?
> ![image](https://user-images.githubusercontent.com/14964443/116400886-dde81780-a82a-11eb-8db5-9969c723a51a.png)

Right! The one with the filled color is old and should be replaced by the second one you're showing! thanks

**Comment by stephanie-cascade8** [comment]
> > * Should we have two different icons for Organisation Data and Organisation Approval?
> >   ![Screenshot 2021-04-28 at 10.23.19.png](https://camo.githubusercontent.com/962652bf2bc4d4dfac98e43a7edeb9c86ff511e2a3d6293799a2a6f166043009/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630336361653162356330353863666430613538346635662f35663963666332622d303933302d346166372d393635612d636239336438306539383532)
> 
> Agree, would you have an existing icon that work here?

Not yet! We should make the icon asap! I'm ont it!

**Comment by Jackseed** [comment]
> ### Toolbar
> * [ ]  Invitation Icon is too big (we should redesign it with margins around)
>   ![Screenshot 2021-04-28 at 10.35.07.png](https://camo.githubusercontent.com/30001cd1d488de33305ec38a94da7fcff7311c2349055ed9036e7cc2c13a3c38/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630336361653162356330353863666430613538346635662f62663665363466302d393661662d343334642d626639372d383838323766343736373864)
> * [ ]  Also the envelope in the icon should be white or at least have an opacity 0 to see the colour of the toolbar

@jdrns re these 2 points above could you work on an updated icon so we change it please?

**Comment by jdrns** [comment]
> > ### Toolbar
> > 
> > * [ ]   Invitation Icon is too big (we should redesign it with margins around)
> >   ![Screenshot 2021-04-28 at 10.35.07.png](https://camo.githubusercontent.com/30001cd1d488de33305ec38a94da7fcff7311c2349055ed9036e7cc2c13a3c38/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630336361653162356330353863666430613538346635662f62663665363466302d393661662d343334642d626639372d383838323766343736373864)
> > * [ ]   Also the envelope in the icon should be white or at least have an opacity 0 to see the colour of the toolbar
> 
> @jdrns re these 2 points above could you work on an updated icon so we change it please?

[This version](https://drive.google.com/file/d/1zpKL657O2I1VsPCEdOASlBiwKckn7gJE/view?usp=sharing) of the invitation should be better

**Comment by Jackseed** [comment]
some things moved to #5677 to have more time to discuss it before implementation. Otherwise passed to devs. 
I close this one, thanks for the review 👍
