### ISSUE TITLE
Preselected Rights - Too many territories or media

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5652]
- [x] Add "See more" if there are too many values.
https://app.zeplin.io/project/5fecb41a2e806651584e265c/screen/606c5bd11c790d92daa741a3

**Comment by Mussuranae** [comment]
For the moment, it was decided that the territories couldn't be removable from the expansion panel. So it is not the case neither in the dialog. I guess we can improve that in the future.
