### ISSUE TITLE
Design Review 3.1 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#5656]
All tests are made using Safari. 
**For the color changes / differences, need to check with UI team, but note them here anyway**

### Archipel Market 
**Landing Page** 
- [x] Little change for snackbar text after clicking on "Send Request". Actual text: Your request has been sent! Proposition: replace "!" by "."

**Login Page** 

- [x] Everything is grey, but should be white 
![Снимок экрана 2021-04-28 в 13.03.18.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4ddecd6f-4709-4054-97c3-5baa4173395a)

- [x] no space for "Forget your password ?"

- [x] I remember discussion about blocking the browsers' autosuggests while filling in forms. For the moment, the autosuggest still exists (Safari + Chrome check)
![Снимок экрана 2021-04-28 в 13.13.52.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/c04331d6-f513-44cd-9f1a-48e7c425853b)

**Sign up**

- [x] no space before "?" in "Already have an account ?"

- [x] we do not see the text in a tooltip 
![Снимок экрана 2021-04-28 в 13.17.26.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/80f7203f-932a-4711-9dc6-78ec0852f0fd)

**Org created page**
- [x] Maybe put the "The Archipel Market team will come back to you shortly concerning your Company Account creation request." phrase on the other line for easier reading? 
![Снимок экрана 2021-04-28 в 13.21.35.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1a0f1336-0ed7-437c-99f2-f5532dd43f59)

- [x] there is white background behind the icon 
![Снимок экрана 2021-04-28 в 13.22.53.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4acd9924-77bf-4d16-ac84-fec16fd1f355)

- [x] it would be better if the color of underline took the color of the text 
![Снимок экрана 2021-04-28 в 13.28.37.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1d57915b-2e7e-44c7-8f2d-781033f04dcc)

**Profile Page**
- [x] Everything is grey / black 
<img width="1440" alt="Снимок экрана 2021-04-28 в 14 16 03" src="https://user-images.githubusercontent.com/55499036/116402091-484d8780-a82c-11eb-968d-36138b11ce9a.png">

**Organization Page**
- [x] Same for org page: everything is grey/black
<img width="1418" alt="Снимок экрана 2021-04-28 в 14 17 45" src="https://user-images.githubusercontent.com/55499036/116402329-93679a80-a82c-11eb-8d21-d29f1a8488fd.png">

**Marketplace Everywhere**
- [x] got a feeling that invitation icon is bigger than other icons 
![Снимок экрана 2021-04-28 в 13.30.53.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/bbd39b64-23bf-4845-9414-d21b5250ff3d)

- [x] in a footer change "Contact us" by "Contact Us" 

- [x] also fees like app become more "heavy" and the loading is slower 

**Marketplace Contact Us**
- [x] make "message field" mandatory
- [x] snackbar text to change from "Your email has been sent !" to "Message sent."

**Marketplace Films**
- [x] when clicking on filters the background color is grey (in light theme) and the text is less bright (in dark theme)
![Снимок экрана 2021-04-28 в 13.36.29.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/e33726d3-5a54-4e81-b918-ca4a2ad60492) and ![Снимок экрана 2021-04-28 в 13.37.54.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/ec79ee25-8d74-43ee-a9e3-d73f389a2e8d)

**Marketplace Film Page**
- [x] Director, Cast, Crew card has become grey 
![Снимок экрана 2021-04-28 в 13.39.53.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/db6a0af8-7759-43ed-a70d-bcb410aaf1d1)

- [x] Same for Selection / Reviews 
<img width="780" alt="Снимок экрана 2021-04-28 в 14 46 18" src="https://user-images.githubusercontent.com/55499036/116406132-a3817900-a830-11eb-9008-d2238dcc57bf.png">

**Marketplace Screening List**
- [x] Need to find a solution to align the btn 
![Снимок экрана 2021-04-28 в 13.54.41.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/27b5fd2a-7afc-4340-87fa-d1e01d10cd72)
![Снимок экрана 2021-04-28 в 13.54.48.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4c286b7f-27c6-46f9-82ea-23755c932d43)

**Wishlist Page**
- [x] table has become grey, columns titles are difficult to read 
![Снимок экрана 2021-04-28 в 13.42.48.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/e75d5747-450a-4efc-a1b5-d5c46c010a6f)

**Activity Feed Page** (checked that it's already ongoing)
- [x] icon "Mark all as read" should be the same as "Mark as read" (we should have two checkmarks everywhere)
![Снимок экрана 2021-04-28 в 13.44.28.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b7337e5e-af0f-4047-80d3-37afae2c612b)

**Comment by 2amarkina** [comment]
### Archipel Market 

**General menu** 
- [ ] Grey color when clicking
![menu](https://user-images.githubusercontent.com/55499036/116404471-f1957d00-a82e-11eb-8df6-b5f6dbdb475d.gif)

**Dashboard Home**
- [ ] Grey color appeared 
<img width="1181" alt="Снимок экрана 2021-04-28 в 14 21 51" src="https://user-images.githubusercontent.com/55499036/116403041-64055d80-a82d-11eb-99a9-b6f7160242b4.png">

**Dashboard My Titles**
- [ ] same: grey color, difficult to read to column titles 
<img width="1145" alt="Снимок экрана 2021-04-28 в 14 25 36" src="https://user-images.githubusercontent.com/55499036/116403235-9e6efa80-a82d-11eb-8c5f-75d98d159fd9.png">

- [ ] I think we need to set a rule for the capital, not capital to be the same everywhere (as for me both can work), but the case should be uniform (here would be better to put views in small letters)
<img width="1081" alt="Снимок экрана 2021-04-28 в 14 26 06" src="https://user-images.githubusercontent.com/55499036/116403393-cc543f00-a82d-11eb-90cd-9c2a1249e661.png">

**Event Creation Page**
- [ ] Same as the previous issues - grey color everywhere
<img width="1174" alt="Снимок экрана 2021-04-28 в 14 28 49" src="https://user-images.githubusercontent.com/55499036/116404080-94013080-a82e-11eb-9877-d81d88ef7eb1.png">

**Comment by 2amarkina** [comment]
**Invitation process**
- [ ] Invitation went to spam (do not know if we can do something about it)
<img width="1019" alt="Снимок экрана 2021-04-28 в 14 37 55" src="https://user-images.githubusercontent.com/55499036/116405036-80a29500-a82f-11eb-88a4-c4f8ad9190e7.png">

- [ ] Maybe i'm mistaken, but could we pre-fill the form with user's mail (and as consequence, show invitation pass), if s/he connects thought mail? 

ex. Click on "Activate Account", come to "Sign Up" page and email is already there as we know that user went directly from it?

**Comment by 2amarkina** [comment]
**My Files**
- [ ] The underline is better to take the same color as text (everywhere, actually)
<img width="296" alt="Снимок экрана 2021-04-28 в 15 26 06" src="https://user-images.githubusercontent.com/55499036/116412624-2ad1eb00-a837-11eb-96ee-bfe638bf495c.png">

- [ ] For Presentation Deck, Moodboard, Scenario the "Save" btn should be on the right (all the actions are on the right side like "Add to list")
<img width="979" alt="Снимок экрана 2021-04-28 в 15 36 09" src="https://user-images.githubusercontent.com/55499036/116413201-b0ee3180-a837-11eb-9495-1724b2791cb5.png">

- [ ] We need to add some space between footer 
<img width="1045" alt="Снимок экрана 2021-04-28 в 15 40 38" src="https://user-images.githubusercontent.com/55499036/116414042-6faa5180-a838-11eb-85b2-981de49f7a7b.png">

**Comment by 2amarkina** [comment]
### Archipel Content 

**Landing Page**

- [ ] There are double underlines. Should be just one line. 
<img width="673" alt="Снимок экрана 2021-04-28 в 15 45 52" src="https://user-images.githubusercontent.com/55499036/116414610-e3e4f500-a838-11eb-81d2-d048956798d5.png">

- [ ] Image problem 
<img width="1034" alt="Снимок экрана 2021-04-28 в 15 55 06" src="https://user-images.githubusercontent.com/55499036/116415892-222ee400-a83a-11eb-99fe-3527d9dd3b86.png">

**Comment by 2amarkina** [comment]
_**Tested with Margarett**_ 

**Everywhere**
- [ ] In a footer "About us" transform to "About Us" 

**Homepage**
- [ ] We need to get rid of bullets or install a rule that we can't have more than 3-5 titles presented. To prevent the situation, I would say that it's better to remove bullets at all. 
<img width="1438" alt="Снимок экрана 2021-04-28 в 15 57 56" src="https://user-images.githubusercontent.com/55499036/116416618-c57ff900-a83a-11eb-8461-cef249f82802.png">

**Selection page filled**
- [ ] Image size problems 
<img width="1416" alt="Снимок экрана 2021-04-28 в 16 12 33" src="https://user-images.githubusercontent.com/55499036/116418564-8f437900-a83c-11eb-9448-acb16c102d64.png">

**Specific Terms Modal**
- [ ] remove the gap on the first line _(t....he exclusive option)_
<img width="722" alt="Снимок экрана 2021-04-28 в 16 16 38" src="https://user-images.githubusercontent.com/55499036/116419319-39bb9c00-a83d-11eb-8d00-27a46ef43e52.png">

- [ ] Wasn't it called "Delivery Wishlist" ? 
<img width="686" alt="Снимок экрана 2021-04-28 в 16 18 09" src="https://user-images.githubusercontent.com/55499036/116419473-61aaff80-a83d-11eb-9304-06d57cf8d941.png">

**Success page**
- [ ] Double underline, should be 1 line 
<img width="854" alt="Снимок экрана 2021-04-28 в 16 18 51" src="https://user-images.githubusercontent.com/55499036/116419614-8606dc00-a83d-11eb-9a25-12c1f6d6c319.png">

- [ ] Here should be "See Offers & Deals" as the Main CTA, but as for now we have only "Continue browsing Library" option, maybe still put it in main and change when we have the "Offers & Deals" page?
from <img width="362" alt="Снимок экрана 2021-04-28 в 16 18 59" src="https://user-images.githubusercontent.com/55499036/116419656-8f904400-a83d-11eb-8897-8edb9272efc6.png"> to 
<img width="323" alt="Снимок экрана 2021-04-28 в 16 20 03" src="https://user-images.githubusercontent.com/55499036/116419694-9a4ad900-a83d-11eb-9a32-e7948caaae4d.png">. 

**Wishlist empty**
- [ ] As we're using app-specific wishlists, texts could be adapted accordingly: from "Discover projects" (which is on MF) to "Discover Titles"? 
<img width="627" alt="Снимок экрана 2021-04-28 в 16 23 51" src="https://user-images.githubusercontent.com/55499036/116420537-573d3580-a83e-11eb-93ee-68c9a69c1a9e.png">

**Selection page empty**
- [ ] The color of CTA is different from Wishlist Empty page, maybe use only one? 
<img width="1140" alt="Снимок экрана 2021-04-28 в 16 26 11" src="https://user-images.githubusercontent.com/55499036/116420893-adaa7400-a83e-11eb-9aba-166dd47ceb96.png">

**Comment by 2amarkina** [comment]
_**Testing with Rodger Watsica / Archipel Market Concierge**_

- [ ] The menu is different for Rodger, even both accounts (Margarett also) are related to Marketplace side
<img width="1438" alt="Снимок экрана 2021-04-28 в 16 30 09" src="https://user-images.githubusercontent.com/55499036/116421509-30333380-a83f-11eb-98bf-858a092967b4.png">

Maybe it's because he's concierge, but it shouldn't have changed the menu...

**Comment by 2amarkina** [comment]
### Archipel Content Dashboard 

**My Titles**

- [ ] I suppose it was already noted, but the header of the Film Page is dark grey and difficult to read. 
<img width="1187" alt="Снимок экрана 2021-04-28 в 16 36 07" src="https://user-images.githubusercontent.com/55499036/116422280-e139ce00-a83f-11eb-963e-6ccdee652778.png">

**Comment by 2amarkina** [comment]
### Media Financiers 

**Toolbar** (saw only here, but will be appropriate to all other apps)
- [ ] When hovering "Log out" there is extra space on the left. The color should take all the place. 
<img width="368" alt="Снимок экрана 2021-04-29 в 09 42 32" src="https://user-images.githubusercontent.com/55499036/116517938-f100f300-a8cf-11eb-942b-75865bd89606.png">

- [ ] Also, "Log out" should be centered 

**Footer**
- [ ] Change "Contact us" to "Contacts Us" 

**Projects Page**
- [ ] Strange bug with vertical scrollbar on the filters using Safari. 
<img width="1268" alt="Снимок экрана 2021-04-29 в 09 40 28" src="https://user-images.githubusercontent.com/55499036/116518240-4a692200-a8d0-11eb-8cd7-6c6a48a9c5af.png">

**Dashboard**
- [ ] Also strange bug. When coming to the Dashboard Homepage there are statistics about my films on the Marketplace. But when I go to "My projects" page I can see that I have no titles at also. Moreover, there are no projects no the Marketplace... 
![mf](https://user-images.githubusercontent.com/55499036/116518859-104c5000-a8d1-11eb-81bc-bd8215addf1e.gif)

**Comment by Jackseed** [comment]
> * I remember discussion about blocking the browsers' autosuggests while filling in forms. For the moment, the autosuggest still exists (Safari + Chrome check)
>   ![Снимок экрана 2021-04-28 в 13.13.52.png](https://camo.githubusercontent.com/fd8eacbe0d35b0631261f5f241a8aebd6e778cc710ca0ada7df6e7c03cc2b969/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f63303433333164362d663531332d343463642d396631612d343865376334323538353362)

We disabled it only for the select autocomplete fields that created problems because user needs to click on the list. It's company name & country; we'll keep it for user name since it's helpful

**Comment by Jackseed** [comment]
> * also fees like app become more "heavy" and the loading is slower

Definitely... loading performance is a hard subject but we'll need to tackle it at some point... especially for Content library page that has more & more content

**Comment by 2amarkina** [comment]
Updt. 

**Marketplace Side everywhere** 

- [ ]  As Promotional Images on the film page became clickable (which is great!), maybe we could put a hand instead of cursor to point it out? 
<img width="597" alt="Снимок экрана 2021-04-29 в 15 20 50" src="https://user-images.githubusercontent.com/55499036/116557197-7ef3d280-a8fe-11eb-8e7d-763e893e8d7b.png">

![1200px-Mouse-cursor-hand-pointer svg](https://user-images.githubusercontent.com/55499036/116557538-ced29980-a8fe-11eb-9daf-450a3e0eaf72.png)

**Comment by Jackseed** [comment]
> **Invitation process**
> 
> * [ ]  Invitation went to spam (do not know if we can do something about it)
> 
> <img alt="Снимок экрана 2021-04-28 в 14 37 55" width="1019" src="https://user-images.githubusercontent.com/55499036/116405036-80a29500-a82f-11eb-88a4-c4f8ad9190e7.png">
> 
> * [ ]  Maybe i'm mistaken, but could we pre-fill the form with user's mail (and as consequence, show invitation pass), if s/he connects thought mail?
> 
> ex. Click on "Activate Account", come to "Sign Up" page and email is already there as we know that user went directly from it?

In fact I thought it was already the case but no.. I'll open an issue but it won't be for the release, I'm pretty sure we've implemented that in a similar use case so should be doable

**Comment by Jackseed** [comment]
@2amarkina thanks for your review! Everything has been passed to the devs for release except the MF comment that will be taken care of later.
I close this to know it's done but re-open it and tag me if you have new comments
