### ISSUE TITLE
Gradient background problem and cards-background

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5667]
- [ ] Put back the background-800 on cards 

- [x] Wrong color foreground-base in light theme and dark theme for the gradient here.

first color of gradient should be #8DA4FA in light
![Capture d’écran 2021-04-28 à 16 19 34](https://user-images.githubusercontent.com/66258851/116419634-8acb9000-a83d-11eb-956f-432b7252ddb5.png)

corrected
![Capture d’écran 2021-04-28 à 16 14 20](https://user-images.githubusercontent.com/66258851/116418932-dcbfe600-a83c-11eb-89fe-b60aa8b6e56f.png)

first color of gradient should be #30344A in dark
![Capture d’écran 2021-04-28 à 16 16 44](https://user-images.githubusercontent.com/66258851/116419278-30323400-a83d-11eb-814d-b1c5568ebedf.png)

corrected 
![Capture d’écran 2021-04-28 à 16 16 33](https://user-images.githubusercontent.com/66258851/116419247-28728f80-a83d-11eb-934c-344936d34458.png)

**Comment by fritzschoff** [comment]
@Jackseed these hex colors you mentioned are not in our design? @stephanie-cascade8

**Comment by fritzschoff** [comment]
![image](https://user-images.githubusercontent.com/39312833/116531486-822b9600-a8df-11eb-9c53-5528b35d8e6b.png)
like that? its --primary

**Comment by stephanie-cascade8** [comment]
> * [ ]  Put back the background-800 on cards
> * [ ]  Wrong color foreground-base in light theme and dark theme for the gradient here.
> 
> first color of gradient should be #8DA4FA in light
> ![Capture d’écran 2021-04-28 à 16 19 34](https://user-images.githubusercontent.com/66258851/116419634-8acb9000-a83d-11eb-956f-432b7252ddb5.png)
> 
> corrected
> ![Capture d’écran 2021-04-28 à 16 14 20](https://user-images.githubusercontent.com/66258851/116418932-dcbfe600-a83c-11eb-89fe-b60aa8b6e56f.png)
> 
> first color of gradient should be #30344A in dark
> ![Capture d’écran 2021-04-28 à 16 16 44](https://user-images.githubusercontent.com/66258851/116419278-30323400-a83d-11eb-814d-b1c5568ebedf.png)
> 
> corrected
> ![Capture d’écran 2021-04-28 à 16 16 33](https://user-images.githubusercontent.com/66258851/116419247-28728f80-a83d-11eb-934c-344936d34458.png)

No! not primary , it's too bright and dark :) Can we do this instead?
first color of gradient should be #30344A in dark
first color of gradient should be #8DA4FA in light

Otherwize, replace those two hexa by primary-200 ?
Can you send me a screenshot on slack? thanks a lot @fritzschoff

**Comment by Jackseed** [comment]
Looks good to me
