### ISSUE TITLE
Tooltip background

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5668]
Issue from @stephanie-cascade8 

- [ ] Tooltips 
I guess we can't change the foreground on tooltips?
This problem came back several times (can I do it live with a dev to see what's possible with the builder??)
![Capture d’écran 2021-04-28 à 16 54 29](https://user-images.githubusercontent.com/66258851/116425294-79d14d80-a842-11eb-9bcf-d980fd6aa4ca.png)

**Comment by stephanie-cascade8** [comment]
> Issue from @stephanie-cascade8
> 
> * [ ]  Tooltips
>   I guess we can't change the foreground on tooltips?
>   This problem came back several times (can I do it live with a dev to see what's possible with the builder??)
>   ![Capture d’écran 2021-04-28 à 16 54 29](https://user-images.githubusercontent.com/66258851/116425294-79d14d80-a842-11eb-9bcf-d980fd6aa4ca.png)

Just tested live with @SamirTouira here , but unfortunately the variable &background-500 (which is called on the tooltip background) can't be updated with a darker color. Indeed the variable is called on other components and that seems arbitrary. I need to do an inventory in the code with @GrandSchtroumpf to see how we can fix it.

**Comment by Jackseed** [comment]
Ok thanks for the test, I add this issue in design then and remove it from the release
