### ISSUE TITLE
Media Financiers - Dashboard homepage based on all org films

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5676]
Dashboard homepage is showing me statistics instead of create new title card because my org have movies from another app. Instead it should look at titles related to MF, same as "My Titles" section
![mf](https://user-images.githubusercontent.com/55499036/116518859-104c5000-a8d1-11eb-81bc-bd8215addf1e.gif)

**Comment by SamirTouira** [comment]
Just FYI, this issue is open but seems to be fixed, if the one who worked on it can confirm this

**Comment by Jackseed** [comment]
@SamirTouira thanks for checking, indeed the statistics issue has been solved but we still have an issue that is related to the same problem. 
Now if I log in with uid `NGKwG6VtYXVbAv1xP1O979Y4vtB2` which is a user from an org with:
- accepted movies on festival
- draft movies on festival
I don't have statistics but the state with the "Manage Drafts" button that should be available only if I have draft on `financiers`
![Kapture 2021-07-05 at 10 24 10](https://user-images.githubusercontent.com/14964443/124440866-629b6880-dd7b-11eb-9751-3e36adfeac5b.gif)

Instead I should have this empty state I got when creating a fresh new org:
![image](https://user-images.githubusercontent.com/14964443/124441354-e2293780-dd7b-11eb-8145-def8cf4bb146.png)
