### ISSUE TITLE
1. As a user, I add new dapps

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#569]
- [ ] Create an organization stepper: Step choose your Dapps (without the stepper) 
- [ ] Home Dapp Explorer

**Comment by Jackseed** [comment]
![image](https://user-images.githubusercontent.com/14964443/60946868-a0ca3280-a2ef-11e9-9a8c-2b14a65f5b94.png)
![image](https://user-images.githubusercontent.com/14964443/60946985-cd7e4a00-a2ef-11e9-96ba-a577c4d0c0cc.png)

**Comment by lsenta** [comment]
Blocked: need a decision on main app (PR prepared with Yohan that adds the basics)

**Comment by lsenta** [comment]
Blocked by https://github.com/blockframes/blockframes/pull/663

**Comment by lsenta** [comment]
Simplified PR #663 into: https://github.com/blockframes/blockframes/pull/709
