### ISSUE TITLE
3.1 release - text changes

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5693]
### LEAVING FORM MODALE
- [x] no space before punctuation in English. Here it's "Are you sure?" not "Are you sure ?"
![image](https://user-images.githubusercontent.com/55785823/116571184-224ae480-a90b-11eb-8074-7f74bfe53b61.png)

### LAST STEP 
- [x] "Technical Information" should be "Technical Specifications"
- [x] "Format" should be "Formats"
![image](https://user-images.githubusercontent.com/55785823/116571282-3abaff00-a90b-11eb-8092-ad78f78d5ea2.png)

- [x] "Qualification" should be "Qualifications"
![image](https://user-images.githubusercontent.com/55785823/116571534-75249c00-a90b-11eb-8119-10649a549d33.png)

- [x] "Selections and Reviews" should be "Selections & Reviews" (& instead of "and)
![image](https://user-images.githubusercontent.com/55785823/116572691-7bffde80-a90c-11eb-98a0-946cdf4c9e08.png)

- [x] "Festival & Award" and "Other Festival & Award" should be "Festivals & Awards" and "Other Festivals & Awards"
![image](https://user-images.githubusercontent.com/55785823/116572812-933ecc00-a90c-11eb-85ac-2e9fffdf14d9.png)

- [x] "Co-production Company should be "Co-Production Company"

- [x] "Film Review" should be "Film Reviews"
![image](https://user-images.githubusercontent.com/55785823/116571717-9e452c80-a90b-11eb-9586-ed9df9ecf93d.png)

- [x] Snackbar should say: "Mandatory information is missing."
![image](https://user-images.githubusercontent.com/55785823/116568853-24ac3f00-a909-11eb-907e-d09e08c7b2f2.png)

### TITLE INFORMATION / Available Materials

- [x] Change hint to "Please specify if the original version can be made available or not."
![image](https://user-images.githubusercontent.com/55785823/116566695-41e00e00-a907-11eb-9b7f-c4e09494ec42.png)

## MARKETPLACE SIDE MENU

- [x] Replace "Films" by "Titles"
![image](https://user-images.githubusercontent.com/55785823/116570731-c718f200-a90a-11eb-8e14-243a9a7db8e6.png)

## DASHBOARD FILE STORAGE
- [x] The upload component should say "browse your computer." instead of juste "browse"
- [x] Change CTA text from "Add to list" to "Save Document"
![image](https://user-images.githubusercontent.com/55785823/116576005-76f05e80-a90f-11eb-9b84-77a8e0d61eac.png)

## DASHBOARD CALENDAR / NEW EVENT MODALE

- [x] "More Details" with a capital D
![image](https://user-images.githubusercontent.com/55785823/116576275-b3bc5580-a90f-11eb-88b3-6257f49c11a0.png)

- [x] "Add New Event" with capitals
- [x] "Select Event Type" with capitals
![image](https://user-images.githubusercontent.com/55785823/116576401-cfbff700-a90f-11eb-9554-e69ff7cbac43.png)

## CALENDAR

- [x] "Filter-by" should be "Filter by"  
![image](https://user-images.githubusercontent.com/55785823/116578848-1a427300-a912-11eb-9a9f-45825645c67b.png)

## WISHLIST / EMPTY STATE
- [x] "Discover Titles"
- [x] "Your Wishlist is empty."
 ![image](https://user-images.githubusercontent.com/55785823/116578956-3514e780-a912-11eb-812a-acca94488502.png)

## REQUEST APP ACCESS PAGE

- [x] Change text to:

Looks like you already have an account on a Cascade8 application!
We noticed that your email address is associated with an existing user account of one of our applications.
To access Archipel Content, please request access and wait for our team's approval.
N.B.: All members from your company will also get granted access to Archipel Content.
Request Access
Refresh Page
![image](https://user-images.githubusercontent.com/55785823/116674744-51ae2f80-a9a5-11eb-93f1-9986cff793be.png)

## LOG IN PAGE

- [x] CTA text should be "Log in" to be consistent with the name of the page
![image](https://user-images.githubusercontent.com/55785823/116694092-1c164000-a9bf-11eb-9de1-65a82a86785b.png)

- [x] "Email address" should be "Email Address"
![image](https://user-images.githubusercontent.com/55785823/116694178-3e0fc280-a9bf-11eb-9cff-80171fc49d6e.png)

### MY SELECTION

- [x] "Please choose currency" should be "Please select a currency"
![image](https://user-images.githubusercontent.com/55785823/116695890-7ca67c80-a9c1-11eb-853c-c4f95a329c30.png)

- [x] "Total Bucket Price" should be "Total Price"
![image](https://user-images.githubusercontent.com/55785823/116696146-ce4f0700-a9c1-11eb-845c-857b62c8fb92.png)

- [x] "Delete all the rights for the title" should be "Delete all rights for this title"
![image](https://user-images.githubusercontent.com/55785823/116696281-fe96a580-a9c1-11eb-9911-ed2a06f5462f.png)

### MY SELECTION / Offer "Specific terms" Modale

- [x] Following text should be should be 
"Specific Terms
Please indicate any specific conditions you'd like to request for this deal."
![image](https://user-images.githubusercontent.com/55785823/116695028-4caaa980-a9c0-11eb-9d84-cd58897e0eec.png)

- [x] remove the gap on the first line _(t....he exclusive option)_
<img width="722" alt="Снимок экрана 2021-04-28 в 16 16 38" src="https://user-images.githubusercontent.com/55499036/116419319-39bb9c00-a83d-11eb-8d00-27a46ef43e52.png">

- [x] Change the label "Delivery List" for "Delivery Specifications" and placeholder for "Please indicate here the specific items you require for your delivery, if any."
![image](https://user-images.githubusercontent.com/14964443/116570940-efa0ec00-a90a-11eb-9d9d-d1568589f4a0.png)

## MARKETPLACE EVENT SESSION / Leaving modale

- [x] No space before punctuation. "Are you sure ?" should be "Are you sure?"
![image](https://user-images.githubusercontent.com/55785823/116713433-13306900-a9d5-11eb-9ef3-a7ee017cc0bc.png)

### Landing demo request
- [x] After clicking on "Send Request". Actual text for snackbar: Your request has been sent! instead use a ".": "Your request has been sent."

**Comment by SamirTouira** [comment]
I let you have a look on my PR: https://github.com/blockframes/blockframes/pull/5700

As @Mussuranae wrote in this PR, `{ movie.certifications.value.length, plural, =0 {} =1 {} other {s}}` serves to give plural dynamically to forms titles. We can choose to put an "s" permanently or let the code dynamize the plural itself, but that is one or the other
