### ISSUE TITLE
3.1 release - Safari issues

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5695]
### Marketplace sidenav
- [x] Archipel Market logo is focused automatically when opening the sidenav on Safari, it shouldn't.
![image](https://user-images.githubusercontent.com/55785823/116570801-d26c1d80-a90a-11eb-9b79-fa155390a798.png)

### Marketplace homepage
- [x] Fallback movie card banner doesn't have the right size on Safari (Lagerfeld Confidential)
Safari
![image](https://user-images.githubusercontent.com/55785823/116578159-693bd880-a911-11eb-8e83-009a5fb44510.png)
vs Chrome
![image](https://user-images.githubusercontent.com/14964443/116730177-7a0b4d80-a9e8-11eb-923d-2c40d7259d31.png)

### Archipel Content landing
- [x] Still deformed images on catalog landings for Safari (both buyer & seller tabs)
![image](https://user-images.githubusercontent.com/14964443/116403769-44226980-a82e-11eb-9432-d4814a338442.png)

### Catalog - Selection page filled
- [x] Image size issue on Safari 
<img width="1416" alt="Снимок экрана 2021-04-28 в 16 12 33" src="https://user-images.githubusercontent.com/55499036/116418564-8f437900-a83c-11eb-9448-acb16c102d64.png">

**Comment by SamirTouira** [comment]
> ### Marketplace homepage
> * [ ]  Fallback movie card banner doesn't have the right size on Safari (Lagerfeld Confidential)
>   Safari
>   ![image](https://user-images.githubusercontent.com/55785823/116578159-693bd880-a911-11eb-8e83-009a5fb44510.png)
>   vs Chrome
>   ![image](https://user-images.githubusercontent.com/14964443/116730177-7a0b4d80-a9e8-11eb-923d-2c40d7259d31.png)

I don't have this Lagerfeld Confidential movie in my localhost, even after a PFTB. do you have this by chance @pldespaigne ?
