### ISSUE TITLE
3.1 release - Small UI changes

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5696]
- [x] Change invitation.svg for [this one](https://drive.google.com/file/d/1zpKL657O2I1VsPCEdOASlBiwKckn7gJE/view)

### Landing page
- [x]  Footer is stuck to the bottom of the page, add a 32px bottom padding
![Screenshot 2021-04-28 at 09.58.31.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/4cc86ad9-f549-4e0a-a836-c978cca9f3a2)

###  **Dashboard**
- [x] Fallback for org logo in the sidenav is an old one, we should use the same as for org settings (without colours)
<img width="343" alt="Screenshot 2021-04-28 at 10 43 24" src="https://user-images.githubusercontent.com/79836137/116374740-ddda1e80-a80e-11eb-8418-a4e0cd715f3f.png">

###  **Catalog - Selection page**
- [x] Bug when deleting a right + button 'close' on snackbar barely visible 
![G](https://user-images.githubusercontent.com/79836137/116413548-09253380-a838-11eb-8d45-e5e55420f1b9.gif)

###  **Catalog - Selection Success page**
- [x] Use a main CTA for "Return to Browsing" (keep same text)
from <img width="362" alt="Снимок экрана 2021-04-28 в 16 18 59" src="https://user-images.githubusercontent.com/55499036/116419656-8f904400-a83d-11eb-8897-8edb9272efc6.png"> to 
<img width="323" alt="Снимок экрана 2021-04-28 в 16 20 03" src="https://user-images.githubusercontent.com/55499036/116419694-9a4ad900-a83d-11eb-9a32-e7948caaae4d.png">. 

###  **Selection page empty**
- [x] Use coral color on the CTA
<img width="1140" alt="Снимок экрана 2021-04-28 в 16 26 11" src="https://user-images.githubusercontent.com/55499036/116420893-adaa7400-a83e-11eb-9aba-166dd47ceb96.png">
 

### Catalog Landing Page ### 
- [x] Too much space under the logo, logo should be centered vertically 
<img width="488" alt="Screenshot 2021-04-28 at 12 16 07" src="https://user-images.githubusercontent.com/79836137/116387845-842c2100-a81b-11eb-9e76-49231073eaa1.png">

### My titles ### 
- [x] Space missing below the number of total sales, add 24px padding bottom 
<img width="1214" alt="Screenshot 2021-04-28 at 13 55 19" src="https://user-images.githubusercontent.com/79836137/116399581-5fd74100-a829-11eb-86c2-78cd4cccbaba.png">

### Screening list
- [x] Invitation statut is not perfectly aligned
![image](https://user-images.githubusercontent.com/55785823/116578065-545f4500-a911-11eb-804f-40b7a150acde.png)

### Marketplace screening view
- [x] Invitation status is not centered
![image](https://user-images.githubusercontent.com/55785823/116542084-89a56c00-a8ec-11eb-8972-49ecef074b4d.png)

### Movie form - Summary page 
- [x] Spacing issue between Images and Videos
- [x] Snackbar is not centered
![image](https://user-images.githubusercontent.com/55785823/116569121-61783600-a909-11eb-98c7-1773b94d8e78.png)
- [x] Spacing is not the same here between the 3 first and the 3 last (use the same as the 3 last)
![image](https://user-images.githubusercontent.com/55785823/116571665-92596a80-a90b-11eb-8eb8-6e2437e873ed.png)

**Comment by pldespaigne** [comment]
> Footer is stuck to the bottom of the page, add a 32px bottom padding
Can't reproduce, there is already a 48px margin on the footer.

![image](https://user-images.githubusercontent.com/5858657/116862937-cda6b280-ac05-11eb-857c-1b5f8fab723a.png)

**Comment by pldespaigne** [comment]
> Snackbar is not centered

The snackbar _is_ centered from the whole page, it's not centered from the main content summary.
But since the snackbar is an overlay on top of everything there is no way to center it to a specific container.
