### ISSUE TITLE
World map test cases

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5697]
Fixtures:
- import movies: [file](https://app.zenhub.com/files/165818079/f0951bc9-b0bc-4982-a933-b39b24033c60/download)
- then import contracts: [file](https://app.zenhub.com/files/165818079/21a8f539-2f69-4eb9-a3eb-b26e2e269e78/download)

Some scenarii to verify that logic is good, they are the same than #4918. If errors, refer to this issue issue and check if something has changed from scenario. 

- [x] Mandate test (territory)
Terms: 01/01/2022 - 06/30/2023
Rights: Free TV
Exclusive: No

**Expected result**: South Korea is not licensed

- [x] Mandate test (terms)
Terms: 01/01/2028 - 06/30/2036
Rights: Free TV
Exclusive: No

**Expected result**: World not licensed 

- [x] Mandate test (rights)
Terms: 01/01/2028 - 06/30/2030
Rights: Planes
Exclusive: No

**Expected result**: World not licensed 

- [x] Terms check (existing ended sale)
Terms: 01/01/2033 - 06/30/2033
Rights: Free TV
Exclusive: Yes

**Expected result**: Germany, Russia, Czech Republic (at least) available

- [x] Terms check (existing ongoing sale)
Terms: 01/01/2029 - 06/30/2031
Rights: Free TV
Exclusive: Yes
**Expected result**: Germany not available

- [x] Cross territory check + exclusivity
Terms: 01/01/2022 - 06/30/2022
Rights: Free TV
Exclusive: No

**Expected result**: Germany, Russia, Czech Republic (at least) available

- [x] Cross territory check + exclusivity
Terms: 01/01/2022 - 06/30/2022
Rights: Free TV
Exclusive: Yes

**Expected result**: Germany not available

- [x] Rights check
Terms: 01/01/2022 - 06/30/2022
Rights: S-VOD
Exclusive: Yes

**Expected result**:  Argentina available 

- [x] Rights check
Terms: 01/01/2022 - 06/30/2022
Rights: Pay TV
Exclusive: Yes

**Expected result**:  Argentina not available 

- [x] Exclusivity test (non exclusive)
Terms: 01/01/2022 - 06/30/2022
Rights: Free TV
Exclusive: No

**Expected result**:  Germany available 

- [x] Exclusivity test (exclusive)
Terms: 01/01/2020 - 06/30/2020
Rights: Free TV
Exclusive: Yes

**Expected result**:  Canada not available

**Comment by phpgeekfr** [comment]
@Jackseed tests should be done for movie Resurected `Cr3NYe9RXaMwP98LQMyD` ?

**Comment by Jackseed** [comment]
It's Movie 1 from the import movie excel + the associated contract in the contract excel

**Comment by phpgeekfr** [comment]
test are already implemented. I just made some updates in https://github.com/blockframes/blockframes/pull/5871
