### ISSUE TITLE
3. Dapp installation

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#571]
- [ ] When an org opt in for a dapp, C8 receives an email
- [ ] When an org acquires a new dapp (accepted by C8), admins of the org receive an email

**Comment by lsenta** [comment]
- [x] add state pending during organization creation
- [x] send a mail to cascade8 admins with a link to activate the organization
  - [x] configure admin mail in functions
  - [x] trigger on org creation
  - [x] send the mail
- [x] raw page to activate the organization
  - [x] create the function per org with a page on GET
  - [x] create the function per org with a reaction on POST
  - [x] send a mail to org's admin when the org is accepted

We'll refactor the express app with the next admin feature (issue #571).

In a future PR we'll deal with the frontend:
- [ ] update the frontend to display the org in pending

In a future PR we'll deal with the rules:
- [ ] update the rules to block organization actions until state is accepted
- [ ] update the rules to allow organization creation if and only if its state is pending

**Comment by lsenta** [comment]
Current PR with the MVP: https://github.com/blockframes/blockframes/pull/698

After a first review:

- [ ] secure the request apps collection (only allow org admins to create requests) #697
- [ ] secure the admin pages #700
- [ ] Implement a nicer design
- [ ] Refactor the data types so they can be shared between the back and front
- [ ] show "request to app" only to admins (OrganizationGuard)
- [ ] guard each app if and only if the org has access to the app
