### ISSUE TITLE
Requested changes after merge back release/3.1 into develop

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#5723]
Original PR https://github.com/blockframes/blockframes/pull/5721

- [x] ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/620c4ed7-da43-4826-9a88-b1594c5cd01a) @SamirTouira  👆
- [x] ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/a2f8e9eb-2817-4959-b0ac-98d5628d058d)
- [x] ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/d19e2014-ebe6-44ed-8bd3-6f76f0613703)
- [x] ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/726e58e6-a02d-4aab-a6ac-b1dcd4ab1ed7)
 @SamirTouira  👆
- [x] ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/96871e94-cc42-4248-9ade-6b9732f0cf35)
- [x] ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/bf697787-1d29-48a0-83e8-602f9d3e6f56)
- [x] ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/b7f3ffcb-031f-4799-a97b-c527154de3a0)
- [ ] ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/d4041abf-1122-4246-8a7f-e2dff853d8cc)
- [x] ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/275b4612-6fbc-4b58-907c-267710bda6dd)

**Comment by GrandSchtroumpf** [comment]
@pldespaigne please update the code related to your PRs in the comments above.

**Comment by phpgeekfr** [comment]
created #5886 so this one can be closed
