### ISSUE TITLE
Invitation field - multiple emails issues

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#5728]
I noticed that the email invitation field doesn't recognize multiple emails anymore (I think it used to). Here I pressed "enter" and I got this

https://user-images.githubusercontent.com/55785823/117268219-5700f380-ae57-11eb-84c6-11fc06333342.mov

Even if I know we're supposed to put commas to separate emails, if I remember correctly, this field used to recognize when there where multiple emails like this. It would generate separated chips, not a big one like this

**Comment by maltmayer** [comment]
- [ ] Can't invite multiple emails at once, even when the chips are separated. The invitation only gets sent to the first guest

**Comment by maltmayer** [comment]
@RemcoSimonides I created this issue as there is also a correlated bug with the multiple emails separation

**Comment by RemcoSimonides** [comment]
> I noticed that the email invitation field doesn't recognize multiple emails anymore (I think it used to). Here I pressed "enter" and I got this
> 
>  Video
> Even if I know we're supposed to put commas to separate emails, if I remember correctly, this field used to recognize when there where multiple emails like this. It would generate separated chips, not a big one like this

This is done because we wanted to be able to enter first name + last name with a spacebar between them. In case you want to invite by name instead of email.

**Comment by maltmayer** [comment]
> This is done because we wanted to be able to enter first name + last name with a spacebar between them. In case you want to invite by name instead of email.

It's a good idea but it doesn't work if it has this effect I think. It's muuuch more common to copy and paste multiple emails at once (probably tens or hundreds) than it is to search for a name. If we can do both great but if it's one or the other, I'd choose the other.

**Comment by RemcoSimonides** [comment]
Alright, I'll discuss it with Vincent next week ;)

**Comment by maltmayer** [comment]
> Alright, I'll discuss it with Vincent next week ;)

Great. I guess this is quite high priority as, if anyone tries to organize a screening at the moment, they'll need to copy and paste large lists. So that should be fixed for next screening (and we can never know when it will happen, hopefully soon)
@Jackseed

**Comment by Jackseed** [comment]
I discussed that issue with Marie and she's right. I didn't think of the copy paste use case though it's used way more than the user typing the name of the invitees. 
@RemcoSimonides sorry for the back & forth but we will have to go back to previous situation where whitespace is considered as a separator. @SamirTouira could you take that one in priority please? It's something we should include in the next hotfix as it's needed when a screening is created

**Comment by SamirTouira** [comment]
I think we can close this now if you agree.

**Comment by RemcoSimonides** [comment]
yep. I've reopened this one though #5217 as the fix reverted the changes for that issue
