### ISSUE TITLE
2. Organization administration

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#573]
- [x] When an admin add a member, he receives an invitation email with an automaticaly generated password
- [x] When a user creates an org, C8 receives an email
- [x] When a new org is accepted by C8, the admin receives an email

**Comment by lsenta** [comment]
- [ ] add state pending during organization creation
- [ ] send a mail to cascade8 admins with a link to activate the organization
  - [ ] configure admin mail in functions
  - [ ] trigger on org creation
  - [ ] send the mail
- [ ] raw page to activate the organization
  - [ ] create the function per org with a page on GET
  - [ ] create the function per org with a reaction on POST
  - [ ] check if we can easily add firebase auth on the page to authorize only admin
- [ ] update the frontend to display the org in pending
- [ ] update the rules to block organization actions until state is accepted

**Comment by lsenta** [comment]
Blocked by:
https://github.com/blockframes/blockframes/pull/668

that implements the tool for emailing

**Comment by lsenta** [comment]
- [x] add state pending during organization creation
- [x] send a mail to cascade8 admins with a link to activate the organization
  - [x] configure admin mail in functions
  - [x] trigger on org creation
  - [x] send the mail
- [x] raw page to activate the organization
  - [x] create the function per org with a page on GET
  - [x] create the function per org with a reaction on POST
  - [x] send a mail to org's admin when the org is accepted

In a future PR we'll deal with the frontend:
- [ ] update the frontend to display the org in pending

In a future PR we'll deal with the rules:
- [ ] update the rules to block organization actions until state is accepted
- [ ] update the rules to allow organization creation if and only if its state is pending

**Comment by lsenta** [comment]
Create issue: https://github.com/blockframes/blockframes/issues/700
to deal with authorizations in admin

**Comment by lsenta** [comment]
Permissions will be implemented all at once: https://github.com/blockframes/blockframes/issues/697
