### ISSUE TITLE
Resend email verification icon 'Thank you for joining us' page.

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5747]
Have a resend email verification icon button instead of a reload page button for email verification.

This is 'needed' for the solution for issue #5715

![image.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/16213eec-e24d-4755-a50f-629101c9e420)

**Comment by stephanie-cascade8** [comment]
<img width="108" alt="Capture d’écran 2021-05-20 à 11 21 13" src="https://user-images.githubusercontent.com/66258851/118954908-82f39d00-b95e-11eb-8642-19dcb1f331e9.png">
Now you can download illustrations directly from zeplin here :
https://zpl.io/2v3gml5

**Comment by RemcoSimonides** [comment]
@stephanie-cascade8  Can you cut out the envelop instead of putting background color? It doesn't look good on dark theme and with Icons we don't have difference between light and dark theme

![image](https://user-images.githubusercontent.com/27687382/120158558-8c012b80-c1f4-11eb-81fd-7174ca5966da.png)
![image](https://user-images.githubusercontent.com/27687382/120158663-a935fa00-c1f4-11eb-9394-b05b1b52374a.png)
