### ISSUE TITLE
2. A user asks to join an existing organization

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#575]
- [ ] Notification to the org admin linking to the tab Members in Org Settings with an accept button
- [ ] Notification to the user when the admin accepts or declines

**Comment by lsenta** [comment]
- [ ] User write to invitations
- [ ] Invitation triggers functions to write to org notifications
- [ ] organisation can list pending requests (invitations) in the tab member
- [ ] organisation can accept the invite
- [ ] => triggers firebase function to update the user and permissions

**Comment by lsenta** [comment]
blocked until: https://github.com/blockframes/blockframes/pull/708

**Comment by lsenta** [comment]
blocked until: https://github.com/blockframes/blockframes/pull/708
