### ISSUE TITLE
Clickable links lost their color

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5750]
- [ ] I think that following the clickable links fix, all clickable links lost their color (for example "Missing" shoul be orange, "Mandatory information" should be red, "Browse your computer" should be blue...)
![image](https://user-images.githubusercontent.com/55785823/117296376-4790a300-ae75-11eb-8318-8d73d396b29a.png)
![image](https://user-images.githubusercontent.com/55785823/117296227-19ab5e80-ae75-11eb-807b-64641cd072e5.png)

**Comment by Mussuranae** [comment]
Partially fixed in #5803 pull request. I will check if there is other links that I don't see, but missing-control component is fixed, as well as link on the several uploaders.
