### ISSUE TITLE
Bf-form-entity component

### ISSUE THREAD

**Issue by Mussuranae** [blockframes/blockframes#5757]
As we have a `bf-form-list` to display correctly a form list, it would be nice to have a `bf-form-entity` to display the same way this form.

First use would be for `languages` in the movie form (and the avails tab of the movie on catalog).
Currently there is a languages component (lib movie/form/languages) that is used to display this case. The `bf-form-entity` should use a `add` function from the entity form that could be something like
```
add<K extends keyof T>(key: Extract<K, string>, value: T[K]) {
    if (!this.createControl) {
      throw new Error('Can not use "add" if "createControl" method not set. Use FormEntity.factory instead.')
    }
    const updates = { [key]: value} as Partial<T>;
    const control = this.createControl({[key]: value});
    this.setControl(key, control);
  }
```

**Comment by Jackseed** [comment]
@Mussuranae could you explain me the benefits of this change please?

**Comment by Mussuranae** [comment]
I think it's better to ask @GrandSchtroumpf , it was some weeks ago now, and I don't remember exactly what we wanted.

**Comment by RemcoSimonides** [comment]
@GrandSchtroumpf do you remember or can I close this for now?

**Comment by GrandSchtroumpf** [comment]
It's not implemented. I fear this will only impact the language form for now. If more models like that happens we might consider this factorization
