### ISSUE TITLE
Review Avails WIP 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#5760]
**Texts** 

- [x] Fill in the following fields to know where, when and in which conditions this title is available. (Dot is missing missing)
- [x]   This phrase should start from newline: «Search results use an "and" logic for multiple conditions, not an "or" logic.»
- [x] «Available Territories»  with capital letter

**Main**
- [x] we need to change a switcher (on/off ; activate/desactivate) to toggle buttons choosing between same-level elements but related to different user tasks. 
![Снимок экрана 2021-05-10 в 13.08.02.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/bad95912-4b05-4001-a785-3f7f33a52e3f)

- [x] when switch to «single territory view» the «avails search criteria» should also change 
- [x] need different colors for "not licensed" and "available" 
- [x] when moving the map strange bug happens: map is getting cut
![moving.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a3b8e696-7764-4b8e-a99a-fa3f441f5da7)

- [x] when switch to other page (i.g. Contact Company) warning modal should also appear (screenshot) (as it does when clicking on Selection icon for example)
if click here ![Снимок экрана 2021-05-10 в 13.15.49.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/e21b9725-9fd5-46ed-bc1c-a36bcba329f9) get also this ![Снимок экрана 2021-05-10 в 12.24.45.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/597a0ad6-1ca2-4c7c-9eca-eea052a86df2) 

- [x] Can't use "select all available countries" 

**Rights Card**
- [x] on the Rights card "edit" and "delete" are missing 
- [x] when adding 1 country, three Rights instead of 1 are created: 
- one card OK (the last one)
- one card added with all non-exclusive countries (initial search was for exclusive) (a long country list)
- one card with two countries (Hungary, Australia in example below). 
![add countries.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/63bcfa2f-e3be-4770-b03e-9de79938e79e)

- [x] when deleting a country it works only for 1 rights card, (which is a good one in previous paragraph), other cards with many countries do not move. 

**Adding to Selection/Selection**
- [x] preselected rights and CTA appear, but no rights added
![Снимок экрана 2021-05-10 в 12.16.15.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/6253353c-a575-4606-9213-363371fe267b)

- [x] when titles’ rights added to selection show a snackbar 
![Снимок экрана 2021-05-10 в 12.22.53.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/438eaf68-391c-4df7-af49-defe770ae511)

- [x] show the «cursor» on the «# more» territories to show that there is an action 
![Снимок экрана 2021-05-10 в 12.26.27.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/0bddc837-70fa-4db6-883e-822034b97770)

- [x] add link to the «Film Page» when click on poster + show cursor 
![Снимок экрана 2021-05-10 в 12.27.39.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/30bc26fa-08eb-4cce-9b86-ea8aec051bf1)

**Comment by RemcoSimonides** [comment]
- [ ] view the filters behavior could we remove the button “apply filters” and change the text of “clear” by “Search for New Rights” (with the same action of filter clearing) ?
![avails](https://user-images.githubusercontent.com/27687382/117944026-0e40b300-b30d-11eb-8440-dbf3479a9b0e.gif)
- [ ], could we put * to ll the fields to show that they are mandatory ?

**Comment by 2amarkina** [comment]
- [ ] recheck the text of Avails Search criteria with Marie and Vincent. This part precisely "Search results use an "and" logic for multiple conditions, not an "or" logic.". Feedback from Christophe that it was not pretty clear.

**Comment by stephanie-cascade8** [comment]
UI review (already discussed and tested with @RemcoSimonides  who is currently making those changes)

- [ ] text on top of the form and map/calendar should have a line-height of 24px
- [ ] card legend : reduce padding (16px)
-[ ] reduce the height of the legend list elements from 48 to 32px.
- [ ] Fix icons alignement for "media" and "exclusive" fields in the criteria pannel on the left. (if we can't for now @2amarkina can we take them off? Remco said he wil try)
![Capture d’écran 2021-05-14 à 10.27.10.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/56a590a1-639f-4193-8821-e236fa62806d)
- [ ] Background of the map can be the same color as the card.
- [ ] Background of the zoom - and + has to gat the same background and border as the legend area below.
- [ ] Inside the expansion pannels, the titles should be body-2 and alignement (margin-left) should make the text go further on the right than the expansion panel title. 32px marfin (or padding?) left.
-[ ] Primary-200 (primary-lighter) for available countries in the map and primary-500 (primary-darker) for selected countires. 
-[ ] Margin 24px between map section block and mat-buttons ("learn how it works" "single territory...") cz we can see it's stuck when hovering the mat-buttons.
-[ ] Initial state of the map and calendar, the message on top of the layout ("please select...) should have the disabled background.
Thanks :)

**Comment by 2amarkina** [comment]
Sorry for back and forth, but could we add "days" into select here, please ? (Avails Page / Preselected Right / Runs/ Catch Up Rights )

![Снимок экрана 2021-05-17 в 09.53.04.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/615d11a9-a4d4-4a44-8481-9e2caf2c279a)

**Comment by 2amarkina** [comment]
Sorry for back and forth, but could we add "days" into select here, please ? (Avails Page / Preselected Right / Runs/ Catch Up Rights )

![Снимок экрана 2021-05-17 в 09.53.04.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/615d11a9-a4d4-4a44-8481-9e2caf2c279a)
