### ISSUE TITLE
Graph animation triggered when hovering 'Add new title'

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5761]
The graphs start to move while hovering “add new title”.
Could be a state change that trigger the component to re-render
![strange.gif](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/81f45ef3-6c4b-4525-bc92-caa7058f3d03)

**Comment by GrandSchtroumpf** [comment]
It looks like a change detection issue. It might be linked to the tooltip. When the mouse is hover the button, Angular trigger a change detection for the tooltip to be displayed. But for some reason apex triggers the animation on every change.
A good way to verify this hypothesis is to remove the tooltip and see if it still triggers the animation.
If yes, then we should check how we could configure apex chart (or the container component) to not react to a change of the state.

**Comment by jeremie74** [comment]
It is the tooltip that create the bug.
There is 2 solutions:
-- Remove Tooltip
-- Deactivate the animation
@Jackseed @2amarkina 
what do u suggest?
