### ISSUE TITLE
E2E Test failure on CI

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#5766]
Catalog App E2E tests failed to run

> nx run catalog-e2e:e2e:ci 
- Generating browser application bundles...
✔ Browser application bundle generation complete.

Initial Chunk Files                                                                                              | Names                                                                                                         |      Size
vendor.js                                                                                                        | vendor                                                                                                        |   8.70 MB
main.js                                                                                                          | main                                                                                                          |   1.03 MB
polyfills-es5.js                                                                                                 | polyfills-es5                                                                                                 | 570.42 kB
styles.css                                                                                                       | styles                                                                                                        | 466.43 kB
scripts.js                                                                                                       | scripts                                                                                                       | 460.89 kB

[snip]

Build at: 2021-05-11T00:39:39.565Z - Hash: 8ae0b224c5366731aa3c - Time: 78138ms

Warning: /home/circleci/repo/apps/catalog/catalog/src/app/dashboard/right/list/list.component.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

✔ Compiled successfully.

Here E2E should have started but next app E2E tests are launched.

> nx run festival-e2e:e2e:ci   <============== Festival App E2E is run
- Generating browser application bundles...
✔ Browser application bundle generation complete.

Catalog App compiles fine but E2E tests don't run..

**Comment by xmano** [comment]
Festival E2E did not run fully:

![image](https://user-images.githubusercontent.com/8731418/117934512-60d79a80-b320-11eb-8e58-6b638d84ce62.png)

The test run get interrupted by another app E2E Test.

**Comment by xmano** [comment]
@phpgeekfr I tried with wait workaround in CRM & Financiers E2E test but it is not working all the time. I think we need to investigate at CI job level.

**Comment by xmano** [comment]
Update : 11th June 2021. Issue still persists. Festival E2E did not run.

```
> nx run festival-e2e:e2e:ci 
- Generating browser application bundles...

Initial Chunk Files                                                                                     | Names         |      Size
vendor.js                                                                                               | vendor        |   8.60 MB

:
:

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.
✔ Browser application bundle generation complete.

>>>> Here the tests don't run.. CI starts with next App <<<<

> nx run financiers-e2e:e2e:ci 
- Generating browser application bundles...
```

Log:
https://app.circleci.com/pipelines/github/blockframes/blockframes/18266/workflows/b43137fd-1ed6-4e08-8e6b-fc6449799c21/jobs/29169/steps

**Comment by xmano** [comment]
@george43g : Please work on this issue with priority.

**Comment by phpgeekfr** [comment]
@xmano @george43g  I just started a new test https://app.circleci.com/pipelines/github/blockframes/blockframes/18576/workflows/98790f5d-16e1-4019-aec9-e336a0342799/jobs/29558

With config :
```
npx nx run catalog-e2e:e2e:ci --headless && catalog_ret_code=$? || catalog_ret_code=$?

npx nx run festival-e2e:e2e:ci --headless && festival_ret_code=$? || festival_ret_code=$?

npx nx run financiers-e2e:e2e:ci --headless && financiers_ret_code=$? || financiers_ret_code=$?

npx nx run crm-e2e:e2e:ci --headless && crm_ret_code=$? || crm_ret_code=$?

if [ $catalog_ret_code -eq 0 ] && [ $festival_ret_code -eq 0 ] && [ $financiers_ret_code -eq 0 ] && [ $crm_ret_code -eq 0 ]; then 
exit 0;
else
exit 1;
fi
```
PR : https://github.com/blockframes/blockframes/pull/6115

If it works, you can merge it

**Comment by xmano** [comment]
The tests now run as expected.

There are some more optimisations required like seeing if PFT can run reliably at all times. These can be addressed via a different PR.

https://github.com/blockframes/blockframes/pull/6115
