### ISSUE TITLE
New illustration for empty states

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5769]
We used almost everywhere the spaceship for empty states
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/be48e5b0-f1a2-416f-9aa5-096d9e2a809c)

It should be updated to correspond to new UI and/or use different illustration on each page

**Comment by Jackseed** [comment]
Retro notes:
- great illustrations!
- no screening one is a bit misleading as there is a cross on one of the days
- miss dark theme versions

**Comment by jdrns** [comment]
All new illustrations for empty states are available [on zeplin](https://zpl.io/2ZMvmvJ) under the section Empty pages. We want to upgrade the current illustration we have (with the spaceship) and change them accordingly. Here's a list of where it should be implemented:

**Cross app**
- [ ] Wishlist page 
- [ ] Activity Feed page 
- [ ] Invitation page 
- [ ] Library page (no results from search)
- [ ] Partners page (no results from search)

**Market**
- [ ] Screening list page (no results) 
- [ ] Partner page / Tab Screening schedule

**Content**
- [ ] Selection page 

Feel free to let me know if any is missing!
