### ISSUE TITLE
Org search function on Find your organization page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#577]

**Comment by lsenta** [comment]
- [ ] Confirm: This looks like full text search, "pix" would match "The Pixar Company" for example. cc @Jackseed 

For full text search, we'd use Algolia:
- [ ] Setup an algolia account and push data there,
- [ ] Implement the auto-complete in angular,
- [ ] Plug this into the corresponding page

**Comment by lsenta** [comment]
blocked: needs Hugo's PR that introduce the "search org flow" to implement the algolia search component.
