### ISSUE TITLE
User Testing 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#5781]
The aim of this issue is to prepare and conduct user testings of Archipel Content. 

TO DO: 
- [x] Prepare the protocole (precise that we'll gather the videos) 
- [x] Decide the flows to test 

Pay attention the duration of meeting with each potential user will be about 30min.

**Comment by 2amarkina** [comment]
[Work In Progress ](https://docs.google.com/document/d/1pca6u_ZTLrGO68FFajjjXN4tskC-ZVGmAjQOQvNmERs/edit#)

**Comment by 2amarkina** [comment]
All the planned tests are done, debrifing with @Jackseed and @ChristophePecot are made. Seems like this issue can be closed.

**Comment by Jackseed** [comment]
Yep let's close it!
