### ISSUE TITLE
404 error redirection on editing a Technical Specification in movie view dashboard

### ISSUE THREAD

**Issue by SamirTouira** [blockframes/blockframes#5782]
url: /c/o/dashboard/title/{movieId]/additional

As the title shows, if you click on the Edit button or on "Missing" in the Technicals Specifications part (Additional tab), you'll be redirect to a 404 page error.

I guess it's due to an old or a bad [href]="link" but i'm not sure.

![image](https://user-images.githubusercontent.com/52285231/117960947-d7bf6400-b31d-11eb-803f-1f5abe960a59.png)

![image](https://user-images.githubusercontent.com/52285231/117960997-e4dc5300-b31d-11eb-8752-37a7653a2246.png)

**Comment by Jackseed** [comment]
Tried today and worked fine, should have been fixed since
