### ISSUE TITLE
Improve the request access

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#5783]
One a user has an account on one app and tries to connects to another app, there is this screen that appear. 
![Снимок экрана 2021-05-12 в 14.08.07.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/33c41467-c2a7-4b6c-9139-0173ef8c257b)

Contrary to "Congrats-page", we do not need to block a user here: this connection might be an error (maybe wanted to use other mail) to connect. 

So, I think we could do these small improvements: 
- [ ] add a possibility to come back to landing page clicking on the logo (if user has no access to AC for example and wants to learn more about that app before requesting access). 

- [ ] also, instead of "Refresh page" we could improve it to "Try with another mail" (if ever it was an error or/and computer is shared.) 

- [ ] when a request was sent, change the cta's color and text
![Снимок экрана 2021-05-12 в 14.22.32.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/0c446a79-be5c-48e2-882e-638c5f164d14)

**Comment by Jackseed** [comment]
- [ ] this page also miss a way to chose access for dashboard or marketplace

**Comment by jdrns** [comment]
Wireframes are available [here](https://www.figma.com/file/UMbfjswSE7stwg4riRLOjH/Easier-connection-flow?node-id=822%3A0) under requesting access flow

**Comment by 2amarkina** [comment]
Prepare a new version: 
- more visual and explicit, 
- maybe cut into 2 screens (?)

**Comment by jdrns** [comment]
[New version](https://www.figma.com/file/UMbfjswSE7stwg4riRLOjH/Easier-connection-flow?node-id=1581%3A405) validated with business

**Comment by jdrns** [comment]
[Mock ups](https://zpl.io/aBvQxJL) ready for business review 
- [ ] Check text
- [ ] Explanatory text needed for last screen 
- [ ] Check text for buttons

Preview 
<img width="934" alt="Screenshot 2021-06-24 at 14 56 24" src="https://user-images.githubusercontent.com/79836137/123266483-5c47f980-d4fc-11eb-9783-d756343a3156.png">

**Comment by jdrns** [comment]
@maltmayer Can you have a look at that issue please? :)

**Comment by maltmayer** [comment]
I can't manage to check the boxes but I've done the 3 tasks ;)

**Comment by jdrns** [comment]
Mock ups are [updated](https://zpl.io/bPyLORm), I only had one comment regarding the first screen, can you have a look @maltmayer?

**Comment by Jackseed** [comment]
@RemcoSimonides this can be pass to the devs

**Comment by Jackseed** [comment]
1. @2amarkina please confirm but to me yes, it logs out
2. We can stick with what we currently have in the org form
![image](https://user-images.githubusercontent.com/14964443/126763038-db3e44bd-c132-4c59-9cab-f0bef5bece38.png)
3. @2amarkina please confirm as well but I would say, redirect to previous page (still logged in)
4. It is, depending on the app we show different name like Buyer | Seller or Investor | Partners; we should keep the same name as already use in the org form
5. Log out and redirect to landing

**Comment by 2amarkina** [comment]
1. Clicking on the app logo should lead to the landing page
2. Should be exactly the same as on the "create account" page. The text needed: _Depending on your role, you might have access to different features of the platform._ (+ change _things on the platform_ to _features of the platform_ it on the create account page).
3. Should lead back to landing. Not sure about word "Cancel" here, would like to re-chech it with @jdrns 
4. The text inside the square brackers is changing depending on the app (_Buyer_ and _Sales Agent_ for Market and Content and _Investor_ and _Partner_ for Financiers). 
5. Exist should log out user and go back to landing. I'm not sure for the wording here, need to check it with @jdrns

**Comment by 2amarkina** [comment]
All good texts are on the preview, not on the zeplin

**Comment by RemcoSimonides** [comment]
Do you mean Wireframe/Figma with 'preview'? If yes, can you give me access? and/or will Zeplin be updated? @jdrns

**Comment by 2amarkina** [comment]
It's in the comment dated from 24 Jun 
![Снимок экрана 2021-07-26 в 11.09.15.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/11336947-fa46-4a0d-a9f0-507b602e090c)

**Comment by jdrns** [comment]
@RemcoSimonides Zeplin is [up to date](https://zpl.io/VkM4q0g)

**Comment by RemcoSimonides** [comment]
@jdrns The text on the cancel button on Step 2 says 'Cancel'. Probably should be 'Do not request access' or 'Go back to landing' as mentioned by Ana [earlier](https://github.com/blockframes/blockframes/issues/5783#issuecomment-885516939)

And 'Exit' button on step 3 should contain the text 'Go back to landing' as mentioned by Ana earlier too

**Comment by jdrns** [comment]
@RemcoSimonides After discussions we all eventually agreed on going with 'Cancel' and 'Exit'. We will keep an eye on it when observing users to see if ever it looks confusing to them

**Comment by RemcoSimonides** [comment]
Alright! :) created dev issue #6382
