### ISSUE TITLE
Open by default the "Territories" expansion panel on the first right card

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5796]
- [x] Open by default the "Territories" expansion panel on the first right card

**Comment by RemcoSimonides** [comment]
What do you mean with this one? 
"Redirect to Selection page once selection validated from movie view avails tab"

Currently when you click 'Add to selection', a snackbar pops-up with a button to navigate to the selection page.

**Comment by Jackseed** [comment]
Yes it was a modification to redirect directly the user instead of giving a link through snackbar. In fact there is a pending UX decision here and we have user tests this week so let's wait for these tests before changing that

**Comment by Jackseed** [comment]
@RemcoSimonides snackbar is well understand by users so we'll keep this as it is, I remove the tick box but keep the one regarding the "opening territories expansion panels by default"
