### ISSUE TITLE
New icon - Organization Approval

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5800]
### Context
After sign up, a waiting page blocks the user explaining why with 4 needed steps including "Organization Approval" meaning us validating the organization. 

Currently icon is the same as "Organization Data", we should have a dedicated one. 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/5c12f41d-1e94-4a96-9d8f-86b11d54b69a)

### Brief
I would avoid check mark as it's already in the right side of this page when the step is ok ✔️
Maybe something like a document that is stamped to make it official?

**Comment by stephanie-cascade8** [comment]
<img width="108" alt="Capture d’écran 2021-05-20 à 11 21 13" src="https://user-images.githubusercontent.com/66258851/118955601-204ed100-b95f-11eb-883b-c5fc9ce74466.png">
download directly from zeplin here:
https://zpl.io/2v3gml5
