### ISSUE TITLE
Meetings - Shared video - Buggy play/pause button

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5808]
Sometimes (it's quite random) the sharing feature play/pause/jump won't respond

https://user-images.githubusercontent.com/55785823/116989761-77537580-acd2-11eb-8afb-f7a820848811.mov

**Comment by Jackseed** [comment]
Maybe it helps, here is a typical error I get when getting a bug in play/pause: https://sentry.io/organizations/cascade-8/issues/2435165220/?project=1540126&referrer=slack

**Comment by RemcoSimonides** [comment]
Can't reproduce 😕

**Comment by phpgeekfr** [comment]
linked to #7061
