### ISSUE TITLE
Archipel Content updates based on user tests

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5813]
After user test sessions here are some updates that we'd like to try to improve usability:
### Movie view - Avails tab
- [x] Remove all the explanation text on the left side above the form fields
- [x] Move the 2 buttons Multiple territory / Single Territory within the form, on the top of the form as a toggle button 
@GrandSchtroumpf do you say it's possible technically?

- [x] **Widen** the overlay above the world map while the form isn't finished + add a big arrow below the text that points to the form (people don't read the text...)
https://zpl.io/am3qzvA

- [x] Create new map & calendar view with the form as header instead of left side
- [x] New colours for the world map, same for both light & dark themes
https://zpl.io/bJDljxD
https://zpl.io/aBz7eGQ

### Library page
- [x] Try to make more visible the cart button within the movie card: best option for now, add a background to the button
here is a proposition to review with the devs 
https://zpl.io/VDg5loO

**Comment by stephanie-cascade8** [comment]
https://zpl.io/bl37REe
