### ISSUE TITLE
Re-design homepage

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5836]
User tests showed us that this page is critical as users tend to spend a lot of time in it. 

This page has 2 main objectives:
1. dynamically highlight content 
2. redirect nicely users to the most important page (ongoing screenings for Archipel Market, library page for Content & Market if no screenings)

Currently banner takes too much space for non-important info: if users are visiting that page, they know our app so we don't have to explain them again why it is made for. 

We also have a good system based on CMS. We should keep this system as a base for objective #1 but rework the page to answer more effectively objective #2

**Comment by RemcoSimonides** [comment]
Also take a look at #4736 when redesigning this page

**Comment by RemcoSimonides** [comment]
More inspiration: #4731

**Comment by 2amarkina** [comment]
### Propositions of Homepage 

**General Changes**
**The **movie banner**** 
was reduced to the essential info (title+CTAs)
![Снимок экрана 2021-05-31 в 10.48.10.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/ba2162d0-6fd5-44a9-a464-78ee2e5b710a)

**The **Feature Film banner** was reworked (as takes to much space on Content)**
- do not show synopsis, 
- add "watch promotional videos" (if any), 
- show only 2 director names and then show "2 others". For this point two solutions can exist to show the rest directors : 
1. show on hover 
2. click and anchor to directors' part of Main tab (need dev validation if possible)

![Снимок экрана 2021-05-31 в 10.52.49.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/35f63b9f-7fa5-4606-b4c3-c29a6109ae7b)

**The "Genres" category**
This section could work as other presentation of regroupement, but as shows not only one particular title, but a group of them, we can't use the film posters. Need to have default pictures on the UI side. 


/ ! \ To keep visual balance, need to alter (if possible) "colored" and "white" zones [as showed on wireframes   ](https://www.figma.com/file/YRQnZZTSFetIFeseXZyTga/Homepages-Screening-carousel-for-AM?node-id=63%3A1)

**MARKET**
see the [comment for the Upcoming Screenings block here #4731](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/4731)

If we introduce the "Upcoming Screenings" section, Hero Section of Market should always lead to to Titles page. 
![Снимок экрана 2021-05-31 в 12.59.35.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a42ee691-4c6c-40a7-8546-c2de27cbb88c)


**CONTENT**
For the Content we do not need to forget about the hero section, that could help the not-advanced users to access the Library page without clicking on the menu. 
![Снимок экрана 2021-05-31 в 13.00.45.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b5150cf5-ebbe-400a-a137-bb6fe93ade94)

**Comment by 2amarkina** [comment]
- [ ] genre component to work on,
- [ ] prepare the description of homepage with possible restrictions and rules.

**Comment by 2amarkina** [comment]
- [ ] check the banner with Marie

**Comment by Jackseed** [comment]
- [ ] Genre grid & Screening carousel are ready to go for UI
- [ ] Movie banner should be changed, it needs a dev issue @RemcoSimonides  > we remove the synopsis from the banner
- [ ] Send the notion article to Marie & Christophe when it's done
- [ ] New issue for UI regarding the top banner to be thiner @RemcoSimonides

**Comment by 2amarkina** [comment]
Notion article is sent to Marie and Christophe and is available **[here ]**(https://www.notion.so/cascade8/Homepage-Design-Rules-10a708180e5542a6a1ab772e0873035f)
