### ISSUE TITLE
Sub-menu for documentary genre

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5838]
Documentary should have sub-entries like Fishing & Hunting, Fashion,... 

This change has some constraints:
- users should still be able to select overall documentary genre
- movie form should be updated accordingly

Here is the current list of sub-documentary genre we have:
- Wildlife
- Nature & Environment
- Hunting & Fishing
- Archeology & History
- Travel & Discovery
- Fashion

**Comment by 2amarkina** [comment]
### Proposition for Genres with sub-categories
**Marketplace View** 
![Снимок экрана 2021-05-31 в 09.54.40.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/07cc2823-3ccb-4374-bd54-b41fe2892feb)

**Movie Tunnel View**
-  for the _Genres_ use the same component as for the Marketplace
- for the _Other Genres_ continue with actual one

![Снимок экрана 2021-05-31 в 09.55.14.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/8cc0f3c0-7a3a-4dca-959f-bbf3d9cb577d)

wireframes can be found [here ](https://www.figma.com/file/vmwPJzLshwzT1FGwrECDlo/Filters-Update?node-id=0%3A1)

**Comment by 2amarkina** [comment]
This one is OK to go to UI

**Comment by RemcoSimonides** [comment]
@RemcoSimonides Make dev issue

**Comment by RemcoSimonides** [comment]
#6068
