### ISSUE TITLE
Running time filter

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5839]
Running time is missing on our filter list, main concern is the component to use to select running time. 
Should we go with the slider? In what direction? Also include it in the filter list to have the correct order of priority

**Comment by 2amarkina** [comment]
### Three propositions for Running Time

Basing on [this article](https://towardsdatascience.com/are-new-movies-longer-than-they-were-10hh20-50-year-ago-a35356b2ca5b) about average runtime the groups of running time are proposed. 

v1 - use the usual checkboxes (multi-selection is possible)
![Снимок экрана 2021-05-31 в 10.03.21.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/43905275-519c-4a24-80da-bf29ff3c968a)

v2 - go for more visual representation (multi-selection is possible)
![Снимок экрана 2021-05-31 в 10.04.13.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/fb1373cc-d79c-4304-8e51-47d52b572854)

v3 - go with a slider, but need to set the min and max runtime. if not possible - to privilege v1 or v2
![Снимок экрана 2021-05-31 в 10.05.04.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/d3d56c8f-b0ff-45db-b145-0e8bd6532cd3)

**Comment by 2amarkina** [comment]
Version 3 is kept: Slider with set "till X minutes"

"13, 26, 52, 90" to set as points

**Comment by 2amarkina** [comment]
![filter running time.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/2ef7c904-2270-4a77-be5c-e85083e1b41f)

**Comment by Jackseed** [comment]
I would prefer to go with the correct abbreviation "min" but mb it takes too much space?

**Comment by 2amarkina** [comment]
Update 
![Снимок экрана 2021-06-02 в 18.08.17.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7f79ea21-5906-4bc5-982c-736397a435da)

**Comment by Jackseed** [comment]
passing it to devs ;)

**Comment by 2amarkina** [comment]
**Dev Review:** 

- [ ] decide if we let a user to choose the intermediate values or exact ones (use or not to use the dots).
As for me, intermediate values can be useful. 

The fact that values we use do not have equivalent difference can lead to the inconsistency of the slider results: user puts the cursor to the 26min and gets 22 instead, for example. 

**Solutions:** 
Use the equivalent difference, something like 13, 26, 39, 52, 65.. etc. (the 13 was taken as difference.) 

- [ ] validate this with @ChristophePecot and @Jackseed

**Comment by Jackseed** [comment]
I would prefer not to use dots if user can only selects these. To me they were here as helpers but not the only possible choice. 
Re the 13min difference it will be weird as 39 and 65 aren't classic running times

**Comment by ChristophePecot** [comment]
Hey,

The benchmark for running time should be 13 / 26 / 52 / 90 / 120 / 180

 

De : Jackseed ***@***.***> 
Envoyé : jeudi 3 juin 2021 16:49
À : blockframes/blockframes ***@***.***>
Cc : ChristophePecot ***@***.***>; Mention ***@***.***>
Objet : Re: [blockframes/blockframes] Running time filter (#5839)

 

I would prefer not to use dots if user can only selects these. To me they were here as helpers but not the only possible choice.
Re the 13min difference it will be weird as 39 and 65 aren't classic running times

**Comment by 2amarkina** [comment]
> I would prefer not to use dots if user can only selects these. To me they were here as helpers but not the only possible choice.
> Re the 13min difference it will be weird as 39 and 65 aren't classic running times

Yes, I see. 
There is also an eventual problem, that results can be not ok, because of number of characters. Also, the numbers will not appear at the same distance.
Here's the example of what we can get:
<img width="646" alt="Снимок экрана 2021-06-03 в 17 08 48" src="https://user-images.githubusercontent.com/55499036/120668079-68f1a880-c48e-11eb-8147-d085bb2c119d.png">

Not precised result, a form which is not balanced... 

**Solution 1** 
Go for more balanced spaces and approximative values with the same interval (20, 40, 60, 80 etc.)
Disadvantage: this is not the usual runtime used, so can be confusing. 

**Solution 2** 
Keep as it is. With possible result confisions.

**Solution 3**
Go for other representation. Basically we loose only this fineness and precision, but we could use the needed values with no visual inconsistency. 
<img width="550" alt="Снимок экрана 2021-06-03 в 17 16 24" src="https://user-images.githubusercontent.com/55499036/120669154-7d827080-c48f-11eb-9441-58a4c2fdc5bf.png">

**Comment by Jackseed** [comment]
I would go for this, the balance is ok as it's following the real time difference between each numbers and they are classic ones so users will understand in my opinion
![image](https://user-images.githubusercontent.com/14964443/120673444-78272500-c493-11eb-80ab-0ae49d579a01.png)

**Comment by 2amarkina** [comment]
- [ ] check with François if dots solution can be ok (always precised results)

**Comment by 2amarkina** [comment]
So, we are not able to do a slider if the gaps between the numbers are not equivalent. 

we've got following solutions: 

1. make gaps equivalent and keep slider. 
2. use checkbox solution (but will take to develop) to be able to choose several running times (like 52-90 and 90-120 to be able to search from 52-120).  
3. use radio buttons solution (will be easier to implement) but user will be able to choose only 1 running time period. 
4. go with other solution: 
![Снимок экрана 2021-06-10 в 16.04.01.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/57e4244b-fba8-4f0b-84c9-95e5e7f7b24c)

**Comment by 2amarkina** [comment]
Last solution 
![Снимок экрана 2021-06-11 в 13.39.56.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/58a1748a-490f-46d0-b875-9be2bfba1393)

**Comment by 2amarkina** [comment]
After business discussion we priorise the checkboxes, but need to check with dev team the level of complexity 

![Снимок экрана 2021-06-11 в 16.58.32.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a9028bb8-7b07-49dc-8c0b-baa4f3ef8406)

**Comment by RemcoSimonides** [comment]
@RemcoSimonides make dev issue

**Comment by RemcoSimonides** [comment]
Created dev issue #6067
