### ISSUE TITLE
Avails form - visibility issue with dropdown list

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5841]
When territory dropdown list is open it hides the other parts of the form, which misleads users. 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/195ecce9-8e20-40b2-b3bb-a73e09e12fe2)

**Comment by stephanie-cascade8** [comment]
Correct the css class ".mat-select-panel" from max-width: 256px to **max-width: 286px**;  (from what I understand this is already an override from ours, if not, please check authorization to do this with François)

See the result expected bellow :
<img width="964" alt="Capture d’écran 2021-08-11 à 18 00 10" src="https://user-images.githubusercontent.com/66258851/129063537-09ce7dc6-2128-4730-a440-2af81c561dd8.png">
