### ISSUE TITLE
Meetings - Upload private videos on movies

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5852]
We had user feedbacks that they'd like to share videos related to their titles but don't want it to be displayed in the marketplace. 
I think that a good option would be to add a private / public button on video uploads.

This should impact both movie form & My Files section

**Comment by RemcoSimonides** [comment]
- [ ] Vincent wants to review first
- [ ] Then check with PL whether it's technically possible. He knows about media and events.

**Comment by Jackseed** [comment]
@2amarkina could you link the wireframes plz?

**Comment by 2amarkina** [comment]
[Link to the wireframes ](https://www.figma.com/file/qpLBi85x3y0s4fLpJPACOm/Wireframing-Elements?node-id=1509%3A7)

**Comment by Jackseed** [comment]
thx!

**Comment by 2amarkina** [comment]
- [ ] improvement of Movie Tunnel 
- [ ] synchro with My Files 
- [ ] update of Event Form (Screenings)

**Comment by 2amarkina** [comment]
**[Access to wireframes with updates](https://www.figma.com/file/fZGHJU4pAI3ENluxMnY5Lk/Video-Uploads?node-id=0%3A1)**

**Comment by 2amarkina** [comment]
This issue should also include the eventual changes for the Sales Pitch 

- [ ] Check Sales Pitch production statuses
- [ ] Check if it's possible to combine it with Promotional Videos block

**Comment by 2amarkina** [comment]
Attempt to merge Sales Pitch and other Promotional videos includes a dynamic object, such as Sales Pitch description, that appears only if Sales Pitch type is selected. 

1. Wireframe 1
![Снимок экрана 2021-07-07 в 17.16.35.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/f62646ed-f303-4323-8655-f51a50364ff1)

2. Wireframe 2
![Снимок экрана 2021-07-07 в 17.16.47.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/09f1f9ba-ef29-48d8-bfed-27c9508883e2)

**Comment by Jackseed** [comment]
Is it ok for devs? I would rather add a video select on the sales pitch page in the movie form because here we will also need to add a dynamic description field on the My files component and I find it strange to update the video upload component only for sales pitch.

**Comment by 2amarkina** [comment]
Not checked with devs yes, as wanted to have business review before.

**Comment by 2amarkina** [comment]
Wireframes with video select on the Sales Pitch page can be found **[here](https://www.figma.com/file/fZGHJU4pAI3ENluxMnY5Lk/Video-Uploads?node-id=111%3A2634)**

**Eventual problems from UX point of view:** 
- If we decide to implement video select on the _Sales Pitch_ page we will need to change the order of the pages in _Promotional Elements_ section: _Sales Pitch_ should go right after the _Videos_ (for now _Sales Pitch_ is the first page).

- As a user can fill in the pages as s/he wants, they might start with the _Sales Pitch_ page with no videos uploaded. Solution for this problem might be a hint "Please upload your videos first in Videos section.", still that means that a user will have to switch the pages several times. 

**Eventual problems to verify with dev team**: 
- If I'm not mistaken, the files are uploaded only after saving the title (e.g. the Still Photo problem). Does the problem persist for the videos? Would it be technically possible to add a video in _Videos_ section and then select it in _Sales Pitch_ section with no saving? 

If not possible, then a hint solution from the previous remark should be extended to "Please upload your videos first in Videos section and then save your title."

**Comment by Jackseed** [comment]
ok so let's go for 1st proposition if ok for devs

**Comment by RemcoSimonides** [comment]
@Jackseed what is the 1st proposition?

**Comment by 2amarkina** [comment]
1st proposition was about having a dynamic description field if choosing Sales Pitch video nature. 

2nd proposition (which is not ok) was about having video select on the Sales Pitch page. 

I distinguished the good one with a red square in [Figma](https://www.figma.com/file/fZGHJU4pAI3ENluxMnY5Lk/Video-Uploads?node-id=35%3A3754) 

And screenshots presented earlier remain the same.

**Comment by RemcoSimonides** [comment]
Dev issue created ☝️
