### ISSUE TITLE
Invitation Pass

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#5893]
**Invitation Pass** is a particular case of [Links issue](https://app.zenhub.com/workspaces/design---ui-60ab5f96c64ec50014c46754/issues/blockframes/blockframes/5770). 

- [x] Before going to dev the UI touch for the icon is needed.

**Comment by jdrns** [comment]
### Long term solution 
Make an inventory of all form fields that include icons and establish rules that would fit all situations. That solution would also help to implement the 'eye' on the password field to 'see password'. 

### Short term solution 
Previously discussed and validated by @GrandSchtroumpf, wireframes can be found [here](https://www.figma.com/file/UMbfjswSE7stwg4riRLOjH/Easier-connection-flow?node-id=1453%3A1), the solution would be to add a  '?'  button with tooltip that opens intercom on click

**Preview**: 
<img width="664" alt="Screenshot 2021-05-31 at 13 48 47" src="https://user-images.githubusercontent.com/79836137/120188857-ef03ba00-c216-11eb-81b1-31796510d0df.png">

**Comment by jdrns** [comment]
**Preview of the UI:** 
<img width="611" alt="Screenshot 2021-06-03 at 14 21 11" src="https://user-images.githubusercontent.com/79836137/120643982-1953b280-c477-11eb-9920-ebe188db1780.png">


There is not zeplin link yet as the mock-ups are not up to date but let me know if there are any questions. You can find [the icon](https://zpl.io/2vjWpve) on zeplin though, size is 24px and colour is foreground 600

On hover, we have a tooltip that says "Contact us to get help"
On click, it should open the intercom

**Comment by Jackseed** [comment]
Retrospective comment:
- [ ] If the help icon is clickable it should be different than the "i" that is only a tooltip. Best to go on a solution that looks more of a button using primary colour at least

**Comment by jdrns** [comment]
Last version validated
**Preview of the UI:** 
<img width="690" alt="Screenshot 2021-06-09 at 16 34 35" src="https://user-images.githubusercontent.com/79836137/121374917-959b3980-c940-11eb-882e-b4f3d6f777a5.png">


Mini fab with icon inside. There is no zeplin link yet as the mock-ups are not up to date but let me know if there are any questions. You can find [the icon](https://zpl.io/bLqW01Y) on zeplin though, size is 24px

On hover, we have a tooltip that says "Contact us to get help"
On click, it should open the intercom

**Comment by RemcoSimonides** [comment]
@RemcoSimonides Create dev issue

**Comment by RemcoSimonides** [comment]
Dev issue: #6069
