### ISSUE TITLE
Movie: CRUD, List View, Wishlist

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5897]
* Movie list
* Movie view + Financial + Campaign view (movie view tabs)
* Movie filters > test on MF for specific filter
* Delete: CRM

**Comment by RemcoSimonides** [comment]
## Movie View
- [ ] Ask a new illustration with the right colors to the design team (those are old wrong colors)
<img width="315" alt="Capture d’écran 2021-06-02 à 11 25 13" src="https://user-images.githubusercontent.com/66258851/120456283-bdfdc380-c395-11eb-881b-3be9427f37ce.png">

## Movie list
When filtering by Languages & Versions
 - [ ] Add more margin-right between inline checkboxes
12px
 - [ ] Add more margin-bottom between inline checkboxes
12px
_(the effect is more obvious when clicking inside the checkbox, the ripple effect crosses on close elements)_

<img width="604" alt="Capture d’écran 2021-06-02 à 11 56 06" src="https://user-images.githubusercontent.com/66258851/120461164-0fa84d00-c39a-11eb-971e-b317e01f6f5e.png">
<img width="488" alt="Capture d’écran 2021-06-02 à 12 05 06" src="https://user-images.githubusercontent.com/66258851/120463013-c22cdf80-c39b-11eb-8584-5e1574f40976.png">

**Comment by RemcoSimonides** [comment]
Bug on Safari:
- [ ] Like on Chrome or mozilla, scroll should be disabled when a filter is open
![f](https://user-images.githubusercontent.com/79836137/120482072-0ecee580-c3b1-11eb-8fc3-137405e2e837.gif)

**Comment by Jackseed** [comment]
Bug on Chrome
https://staging.archipelmarket.com/c/o/dashboard/home
user dev+armando-nwl@blockframes.io

- [ ] Not sure it's linked to movie but it looks like there is an issue with movie stats loading on dashboard homepage, reloading all the time:

![Kapture 2021-06-03 at 11 22 11](https://user-images.githubusercontent.com/14964443/120622028-bce49900-c45e-11eb-8140-379f93b50c4e.gif)

**Comment by RemcoSimonides** [comment]
### Summary Page
- [ ] Add info about Production Status in Reference 
- [ ] Make Production Status mandatory 
![Снимок экрана 2021-06-02 в 14.39.34.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/35f66cca-2e2e-485a-a1af-66a4793b2647)
_For AC production status will always remain Released_

- [ ] Poster and Banner Images are missing, but they are uploaded
![poster:banner.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/3f24d26b-72fb-4f0f-9ca2-73e9e168355c)

- [ ] Clicking on Poster Image should lead to the Film Poster section 
- [ ] Clicking on Banner Image should lead to Film Banner section 

- [ ] Clicking on Missing information about director should lead to Director(s) section
![director.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/bb7b8104-7a01-473b-9df3-2afbc403a38a)

**Comment by Jackseed** [comment]
example: https://staging.archipelcontent.com/c/o/marketplace/title/WKHtW7oydauAiNd1nhUz/main
user: dev+kara-rao@blockframes.io
- [ ] Movie view marketplace - review card - "Read the article" button should redirect to the absolute link, i.e the exact link filled in the database, here it adds the app url before 
example: article link `test.com` redirected to `https://staging.archipelcontent.com/www.test.com`
![image](https://user-images.githubusercontent.com/14964443/120645617-e7435000-c478-11eb-82c0-9e9792d43934.png)

**Comment by RemcoSimonides** [comment]
### Wishlist
- [ ] As the wishlist is shared within Company, there is a proposition to change the title by "Company's Wishlist" when there is something in Wishlist
![Снимок экрана 2021-06-02 в 16.57.30.png](https://camo.githubusercontent.com/37efcb2f02ce502700d1c636621143ff0fca3c8226c68118a837ce1fc4162f7e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f65313331626665372d313638312d343465322d613038332d633866626164623464323364)

- [ ]  Also the empty state text has to be changed as well for “Your Company’s Wishlist is empty.” instead of "Your Wishlist is empty."

- [ ]  As there is not enough space, change the title "My Wishlist" by simple "Wishlist"
![Снимок экрана 2021-06-02 в 16.58.43.png](https://camo.githubusercontent.com/2f3b481ce77c7c7c212c4d5f94030233c236208b7d97bb243ffcb9464e15e033/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f61316666393235352d303633662d343836362d623931622d656263656231633665636536)

**Comment by RemcoSimonides** [comment]
- [ ] Make field for Logline smaller and field for Director's description bigger (basically switch them) Check with Stephanie what the desired height would be for logline (~100 - 120px)
For more information I refer to [issue #5938](https://github.com/blockframes/blockframes/issues/5938#issuecomment-853930360)
![image](https://user-images.githubusercontent.com/27687382/120667996-54adab80-c48e-11eb-8694-f66947b716e7.png)
![image](https://user-images.githubusercontent.com/27687382/120668010-57a89c00-c48e-11eb-8d6a-03f0465cba7e.png)

**Comment by xmano** [comment]
Finding issue with autocomplete of country in Shooting Location of Shooting Information Step:

![image](https://user-images.githubusercontent.com/8731418/120997584-f5f57400-c7a4-11eb-8f46-0e3c4ecbbc90.png)

Countries do not get listed according to character typed.

**Comment by xmano** [comment]
Deleting a title from CRM app does not remove a bucket list entry if created for that movie.

![image](https://user-images.githubusercontent.com/8731418/121182855-1d217380-c881-11eb-9c18-69c4c90a7c38.png)

To recreate:
1. Create a new title from AM & check it is listed fine.
2. Import contract for this
3. Create a bucket for this movie. Optional add the movie to wishlist
4. Delete the title in CRM App
5. Observe that wishlist is removed but bucket still shows notification and entry for the movie.

**Comment by RemcoSimonides** [comment]
- [ ] The table showing a director that was just added needs a horizontal scroll (the action column with edit and delete needs to stay fixed on the right)
![image](https://user-images.githubusercontent.com/27687382/121186591-901df080-c867-11eb-9912-8d5a33341693.png)
If it's not clear; ask Stephanie to explain it more clearly ^^

**Comment by RemcoSimonides** [comment]
- [ ] put the production status in capital "Released". Same for other possible statuses: In Development, In Production, In Post-Production, Completed, Released. 
<img width="347" alt="Снимок экрана 2021-06-08 в 11 14 29" src="https://user-images.githubusercontent.com/55499036/121158820-f21c2d00-c84a-11eb-9d49-22426e335e0d.png">

- [ ] If no production status, put "missing" with yellow color as for other fields. "Missing" should be clickable. A click should lead to the "First Step".
<img width="478" alt="Снимок экрана 2021-06-08 в 11 15 46" src="https://user-images.githubusercontent.com/55499036/121159172-40c9c700-c84b-11eb-9f2f-4ca15f080d13.png">

- [ ] still doesn't lead to film banner, buttons "fly"
![fly](https://user-images.githubusercontent.com/55499036/121160417-5be90680-c84c-11eb-9121-3d76bbbe8c03.gif)

- [ ] key assets - ok, but buttons "fly" 

- [ ] **!!!** all "selection and review" part still leads to "artistic team". should lead to "selection and reviews". 
Festival & Award + Other Festival & Award : lead to the top of artistic team 
Film Review : leads to to the artistic team filmography 
![selections](https://user-images.githubusercontent.com/55499036/121161068-eb8eb500-c84c-11eb-85e6-14fbe5c7a4e0.gif)

**Comment by RemcoSimonides** [comment]
- [ ] new strange error with video player 
<img width="1393" alt="Снимок экрана 2021-06-08 в 11 52 38" src="https://user-images.githubusercontent.com/55499036/121164759-10d0f280-c850-11eb-8f87-386ed19cfdb6.png">

**Comment by Mussuranae** [comment]
>     * [x]  put the production status in capital "Released". Same for other possible statuses: In Development, In Production, In Post-Production, Completed, Released.
> 
> 
> <img alt="Снимок экрана 2021-06-08 в 11 14 29" width="347" src="https://user-images.githubusercontent.com/55499036/121158820-f21c2d00-c84a-11eb-9d49-22426e335e0d.png">
> 
>     * [x]  If no production status, put "missing" with yellow color as for other fields. "Missing" should be clickable. A click should lead to the "First Step".
> 
> 
> <img alt="Снимок экрана 2021-06-08 в 11 15 46" width="478" src="https://user-images.githubusercontent.com/55499036/121159172-40c9c700-c84b-11eb-9f2f-4ca15f080d13.png">
> 
>     * [ ]  still doesn't lead to film banner, buttons "fly"
>       ![fly](https://user-images.githubusercontent.com/55499036/121160417-5be90680-c84c-11eb-9121-3d76bbbe8c03.gif)
> 
>     * [ ]  key assets - ok, but buttons "fly"
> 
>     * [x]  **!!!** all "selection and review" part still leads to "artistic team". should lead to "selection and reviews".
>       Festival & Award + Other Festival & Award : lead to the top of artistic team
>       Film Review : leads to to the artistic team filmography
>       ![selections](https://user-images.githubusercontent.com/55499036/121161068-eb8eb500-c84c-11eb-85e6-14fbe5c7a4e0.gif)

For most of them, I merged my PR this morning, so that wasn't in the deploy last night.
I did a PR about the production status 30min ago ;) It will be merge soon

**Comment by RemcoSimonides** [comment]
Alright. I already expected that :) good good good

**Comment by RemcoSimonides** [comment]
Maybe you've already fixed these or can't reproduce again but just checking with you ;)
After the release I'll create new issues for what's left and we can take our time to look into them.

- [ ] Clicking on Qualification missing should lead to Qualification section.
- [ ] Clicking on Target Audience Missing should lead to Positioning section. Same for Social Responsibility Goals Missing.
- [ ] Files are not uploaded. On the Summary page Presentation Deck is Missing, event if document was uploaded. Same for Scenario and Moodboard.
N.B. After Saving the images and files appeared on the summary page. But showing "missing" is confusing (as user successfully added files). Proposition, maybe use the same solution we had for the Still Photos? Means show only the name of section "Presentation Deck" for example.

**Comment by RemcoSimonides** [comment]
Dedicated issue for
Filter scrolling with page on Safari: #6010 
Flying buttons: #6011
