### ISSUE TITLE
User: CRUD

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5898]
* Auth flow (org + account)
* Account settings (org + profile + cookies)
* Delete: CRM

**Comment by RemcoSimonides** [comment]
"In app" isn't a ✔despite all it's childs being ticked
![image](https://user-images.githubusercontent.com/27687382/120474067-03c38780-c3a8-11eb-94fd-cc5aa3d33304.png)

**Comment by phpgeekfr** [comment]
On auth/identity page, the new background image is overlapping with logo 
![image](https://user-images.githubusercontent.com/1194344/120497684-e948d880-c3be-11eb-9fea-29bf72def312.png)

for all apps

**Comment by RemcoSimonides** [comment]
- [ ] Add 'Already have an account? Log in here' and 'Log in here' should be underlined, not bold
![d.gif](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/da1c0a6e-48b0-49a6-a2be-c753d00092c8)

**Comment by RemcoSimonides** [comment]
- [ ] Need to have a possibility to Log In on this page. 
"Already have an account? Log in here" 
![Снимок экрана 2021-06-02 в 14.15.53.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9e4b639d-8158-4065-be57-215685890840)

**Comment by RemcoSimonides** [comment]
- [ ] **Problems exists only on safari !**
Problem exists for movie, profile, and organization page. Please fix it on all three locations :) 

Background color problem: should go from Primary 200 to transparent. Should be exactly like on Chrome. If needed, check with @stephanie-cascade8 
Movie:
What we have: ![Снимок экрана 2021-06-02 в 15.15.46.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1d5a4204-c74c-4993-bc18-f5c066eee8c5)

What should have: ![Снимок экрана 2021-06-02 в 15.20.38.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/25a8a31b-1766-4e02-891d-0b2c4729f74d)

Profile / Organization:
**Safari view** 
![Снимок экрана 2021-06-03 в 10.18.56.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a73b79bd-3fd4-435d-91d2-a392f6debe06)
**Chrome view**
![Снимок экрана 2021-06-03 в 10.21.50.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/32cee0df-0e97-4288-9c78-a4f8a021d17d)



Same issue is also on Profile and Organization page.

**Comment by Jackseed** [comment]
Bug on Chrome
url: `/c/organization/create-congratulations`

- [ ] Email validation has no more refresh page button (same as Organization approval). There is this ongoing issue #5747; if icon isn't changed yet we should keep the old one in between
![image](https://user-images.githubusercontent.com/14964443/120652620-393ba400-c480-11eb-8994-1c0a9779950b.png)

- [ ] While working on this button, could be worth changing the "Organization Approval" icon cf #5800

**Comment by RemcoSimonides** [comment]
> Email validation has no more refresh page button (same as Organization approval). There is this ongoing issue #5747; if icon isn't changed yet we should keep the old one in between
Should be done already. Let's double check after next deploy to staging
