### ISSUE TITLE
Delivery new settings 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#590]
- [x] Delivery creation tunnel
- [x] Delivery info tab
- [ ] Block the signature if only 1 stakeholder on the delivery

**Comment by Jackseed** [comment]
![Delivery_New delivery tunnel](https://user-images.githubusercontent.com/14964443/60954852-fc9cb780-a2ff-11e9-8401-4b4835920bf8.jpg)
![Delivery_Delivery info](https://user-images.githubusercontent.com/14964443/60954858-feff1180-a2ff-11e9-9cb8-d328f6d6ff89.jpg)

**Comment by lsenta** [comment]
- [ ] Confirm: two users part of the same org are OK? cc @Jackseed

**Comment by lsenta** [comment]
2 types of deliveries, ask the user if they need to sign the delivery and if the materials are payed.

=> some users have just a paragraph "you'll send me the necessary materials", they implicitly agree on what they have or want.

- local distributors,
- worldwide distributors.

the distributor will ask for materials along the life of the project. Every time they order a new material, they'll pay for it.
 
=> long lived deliveries,
=> short lived deliveries.

Sign and Pay. => 4 combinations.

"Delivery creation funnel"
pay the material => add price for each material,
status = ordered / not ordered, payed / not payed
with signature: blockchain sign.

paiement minimum garantie (MG), 
=> dashboard des deliveries, voir les paiements du MG en un coup d'oeil

material price => currency used?

**Comment by lsenta** [comment]
Design:
https://projects.invisionapp.com/d/main?origin=v7#/projects/prototypes/18107883

La première feuille c'est tout ceux qui commencent par 3
La deuxième feuille c'est tout ceux qui commencent par 5

**Comment by lsenta** [comment]
working on flow at: http://localhost:4201/layout/o/delivery/add
