### ISSUE TITLE
Avails: Create, Delete, View

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5900]
* Avails filter
* Add to selection button
* Cards on selection page
* World map view
* Calendar view

**Comment by RemcoSimonides** [comment]
I selected this movie : "CONTACT WITH LEGENDARY FISHES: Nile Perch, Egypt" by Charles Vallee
Then I clicked inside form fields without filling them, which put the fields in their error state.

- [ ] Alignement is destroyed because there is no invisible hint in the neighbor fields (hints should always be here even if not visible for horizontal alignements)
- [ ] Error color should also be on the icons of the fields.
- [ ] the error text should be "mandatory" instead of date "should be in the future". check the right text with Marie.
- [ ] "Exclusif" -> the "c" is missing.
- [ ] "Media" is also mandatory and should also take the error color state.
<img width="1405" alt="Capture d’écran 2021-06-02 à 15 17 16" src="https://user-images.githubusercontent.com/66258851/120491287-6a04d600-c3b9-11eb-9866-60b9c372aaf7.png">

**Comment by RemcoSimonides** [comment]
- [ ] Weird transition behaviour when clicking on Search and Buy Rights
![g](https://user-images.githubusercontent.com/79836137/120481891-e3e49180-c3b0-11eb-8548-1a13dd57c3c6.gif)

**Comment by RemcoSimonides** [comment]
### Calendar
Calendar cells are not all the same width, the width is depending on the content. Can we add a min-width?
![h](https://user-images.githubusercontent.com/79836137/120491863-e0093d00-c3b9-11eb-96ce-0e442c26b8f7.gif)

**Comment by RemcoSimonides** [comment]
### Selection page
- [ ] In the field under please select a currency, there is no placeholder (when not having a bucket doc yet). Either add a placeholder or select a default currency

**Comment by RemcoSimonides** [comment]
### Preselected Rights
- [ ] As Terms and Rights are the part of "Vocabulary" in Capital Letter Documentation, change the text "Search for new Terms and Rights" 
![Снимок экрана 2021-06-02 в 17.15.17.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/12fbcafe-1538-4097-af5f-3df9cffd57f9)

**Comment by pldespaigne** [comment]
> - [ ] Error color should also be on the icons of the fields.
> - [ ] "Media" is also mandatory and should also take the error color state.
> - [ ] Hint says 'Date must be in the future' even though no date is input
> ![screenshot](https://user-images.githubusercontent.com/66258851/120491287-6a04d600-c3b9-11eb-9866-60b9c372aaf7.png)

This items are not related to the avails but to the underlying components. We won't have the time to fix that for the release as it will probably require a full design review of the apps.

**Comment by RemcoSimonides** [comment]
- [ ] Use updated videos in Learn how it works modal (#5953)

**Comment by Jackseed** [comment]
browser: Brave
url: https://staging.archipelcontent.com/c/o/marketplace/title/8zFRZOzrBL65GqyLlXei/avails/map
user: dev+tevin-dtu@blockframes.io
Sentry errors: [1](https://sentry.io/organizations/cascade-8/issues/2442062190/?project=1540126&referrer=slack), [2](https://sentry.io/organizations/cascade-8/issues/2442062229/?project=1540126&referrer=slack) 

- [ ] World map gets completely buggy and can't add new rights when following these steps:
1. Go to avails & add rights
2. Add to selection
3. Get back on the title view
4. Add new rights through world map > territory is not added, Media dropdown is buggy as well

**Comment by pldespaigne** [comment]
> - [ ] Css issue on 4k screen
Cannot reproduce

**Comment by RemcoSimonides** [comment]
- [ ] **!!!** "Search and Buy Rights" CTA doesn't work anymore. If other actions were made, like clicking on "Main" and then click on "Search and Buy Rights" starts working. 
![rights cta](https://user-images.githubusercontent.com/55499036/121162281-14fc1080-c84e-11eb-8671-c179d3a5d93e.gif)

**Comment by RemcoSimonides** [comment]
Calendar doesn't work properly on Safari (ok on chrome). 
- [ ] create a snackbar when period is chosen
- [ ] create a preselected rights card when period is chosen
![calendar](https://user-images.githubusercontent.com/55499036/121163817-622cb200-c84f-11eb-8ed0-bac1fe699e24.gif)

**Comment by RemcoSimonides** [comment]
- [ ] Really great for Edit btn on the selection page !!! 🥇  But just a little remark, could we make it appear that we could see also the title of a card ? (here is a capture) 
like that: 
<img width="1393" alt="Снимок экрана 2021-06-08 в 11 51 06" src="https://user-images.githubusercontent.com/55499036/121164390-d9fadc80-c84f-11eb-8c38-8b2e731153a4.png">
