### ISSUE TITLE
Invitations, Notifications & Emails

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5901]
* Notifications
* Invitations (screening: check the status of the invitation)
* Emails => Timezones

**Comment by RemcoSimonides** [comment]
- [ ] Notification 'Your offer was sent', when clicking on 'More' it goes back to home page. Should go to 'Offers & Deals' page instead.
![j](https://user-images.githubusercontent.com/79836137/120506937-ac80df80-c3c6-11eb-8828-5f92da12c037.gif)

**Comment by Jackseed** [comment]
Chrome
url: https://staging.archipelmarket.com/c/o/dashboard/invitations
user vchoukroun+event@cascade8.com

- [ ] I can't accept a request to attend a screening I created
![Kapture 2021-06-03 at 16 50 32](https://user-images.githubusercontent.com/14964443/120665325-f4b60580-c48b-11eb-9f86-d40ca5a01f28.gif)

**Comment by phpgeekfr** [comment]
> Notification 'Your offer was sent', when clicking on 'More' it goes back to home page. Should go to 'Offers & Deals' page instead.

Staying with HP for now, the page does not exists yet

**Comment by phpgeekfr** [comment]
> Chrome
> url: https://staging.archipelmarket.com/c/o/dashboard/invitations
> user [vchoukroun+event@cascade8.com](mailto:vchoukroun+event@cascade8.com)
> 
>     * [ ]  I can't accept a request to attend a screening I created
>       ![Kapture 2021-06-03 at 16 50 32](https://user-images.githubusercontent.com/14964443/120665325-f4b60580-c48b-11eb-9f86-d40ca5a01f28.gif)

You want to accept an invitation you sent to yourself ?

**Comment by phpgeekfr** [comment]
> Chrome
> url: https://staging.archipelmarket.com/c/o/dashboard/invitations
> user [vchoukroun+event@cascade8.com](mailto:vchoukroun+event@cascade8.com)
> 
>     * [ ]  I can't accept a request to attend a screening I created
>       ![Kapture 2021-06-03 at 16 50 32](https://user-images.githubusercontent.com/14964443/120665325-f4b60580-c48b-11eb-9f86-d40ca5a01f28.gif)

@Jackseed , really weird, the invitation was from `vchoukroun+event@cascade8.com` but toOrg .. 

I removed it and invited `vchoukroun+event@cascade8.com` and I was able the accept invitation.

Can you do what you did again to try to reproduce?

**Comment by Jackseed** [comment]
@phpgeekfr I just tried again and same results:
1. I created a screening "Dédicace for Bruce" happening now with a saler account (vchoukroun+event@cascade8.com)
2. I went to screening list with a buyer (vchoukroun@cascade8.com) and clicked on "Request access" for that event
3. I went to the invitation list with the seller account and still stuck with that pending request

Tested on Chrome

**Comment by Jackseed** [comment]
I got a [permission issue](https://sentry.io/organizations/cascade-8/issues/2435146080/?project=1540126&referrer=slack) on Sentry + a [type error on the invitation ](https://sentry.io/organizations/cascade-8/issues/2435058590/?project=1540126&referrer=slack)

**Comment by phpgeekfr** [comment]
> I got a [permission issue](https://sentry.io/organizations/cascade-8/issues/2435146080/?project=1540126&referrer=slack) on Sentry + a [type error on the invitation ](https://sentry.io/organizations/cascade-8/issues/2435058590/?project=1540126&referrer=slack)

This will be solved via https://github.com/blockframes/blockframes/pull/5954
