### ISSUE TITLE
Meetings: File explorers, CRUD, Stats, Privacy, Share documents, Videoconference, Invitations

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5903]
* Screening form (find someone by the orgname)

**Comment by RemcoSimonides** [comment]
- [ ] Add close button to image preview modal
Image Modal example 
![Снимок экрана 2021-06-03 в 11.15.27.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/053ea9d1-d371-4c35-9fb7-e6936bd08ef8)

**Comment by RemcoSimonides** [comment]
## Your environment
OS: MacOS Big Sur
Browser : Safari 14.0.3 (16610.4.3.1.7)

## Review item
Meeting Page leaving Modal

### Localization
- App name: Archipel Market
- Page: Meeting Page
- Url: https://staging.archipelmarket.com/c/o/marketplace/event/20vZ75BpRL4UcuJFokHG/session
- User used (if anonymized): 
dev+trevor-kcu@blockframes.io 

### Context

- Need to homogenize the modal windows everywhere following [Modals documentation.](https://www.notion.so/cascade8/Modals-warnings-0c8d7ccd3bab4c1c904da5c4b8aa48e4)
- Following the [Modals Text Inventory ](https://docs.google.com/spreadsheets/d/1N06uryQf5J7g56kyenJgpZ_HtiXmYb_Evf798E4fwsY/edit#gid=678850512) change the text

### Fix
- [ ] add close button 
- [ ] title "You are about to leave this meeting.."
- [ ] main text "You might not be able to come back as its access is time-limited."
- [ ] main CTA "Leave anyway" should be above secondary CTA "Stay"

### Images
This modal 
![Снимок экрана 2021-06-03 в 11.49.50.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/ca884942-4c5c-45f0-8a0a-568311db67f0)

Should have this structure 
![Снимок экрана 2021-06-03 в 10.48.14.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/24ffadc0-7f39-43e8-917a-d1e790aa76d8)

**Comment by RemcoSimonides** [comment]
## Your environment
OS: MacOS Big Sur
Browser : Chrome (91.0.4472.77)

## Review item
Meeting Page (Buyer View)

### Localization
- App name: Archipel Market
- Page: Meeting Page (Buyer View)
- Url: https://staging.archipelmarket.com/c/o/marketplace/event/20vZ75BpRL4UcuJFokHG/session
- User used (if anonymized): 
dev+cassandre-mko@blockframes.io

### Context

- [ ] The horizontal scrollbar should not appear

### Images
![horizontal scroll.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1f3e3af7-fc28-4216-af05-3d377162f76e)

**Comment by RemcoSimonides** [comment]
## Your environment
OS: MacOS Big Sur
Browser : Safari 14.0.3 (16610.4.3.1.7)

## Review item
Meeting Page, parameters Modal

### Localization
- App name: Archipel Market
- Page: Meeting Page
- Url: https://staging.archipelmarket.com/c/o/marketplace/event/20vZ75BpRL4UcuJFokHG/session
- User used (if anonymized): 
dev+trevor-kcu@blockframes.io 

### Context

- Need to homogenize the modal windows everywhere following [Modals documentation.](https://www.notion.so/cascade8/Modals-warnings-0c8d7ccd3bab4c1c904da5c4b8aa48e4)

### Fix
- [ ] add close button 
- [ ] main CTA "Unblock autoplay" should be above secondary CTA "Cancel"

This modal 
![Снимок экрана 2021-06-03 в 12.07.49.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/00736ffe-8630-4a5a-9653-60f0b706ea26)

Should have this structure 
![Снимок экрана 2021-06-03 в 10.48.14.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/24ffadc0-7f39-43e8-917a-d1e790aa76d8)

**Comment by RemcoSimonides** [comment]
## Your environment
OS: MacOS Big Sur
Browser : Safari 14.0.3 (16610.4.3.1.7)

## Review item
Full Screen btn

### Localization
- App name: Archipel Market
- Page: Meeting Page for shared elements, My Files ...
- Url: https://staging.archipelmarket.com/c/o/dashboard/files
- User used (if anonymized): 
dev+trevor-kcu@blockframes.io 

### Context

- [ ]  Putting a document / image in full size is not working
![full screen.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/67bb189f-abc3-47e5-a5e0-7e0849e3aa4d)

![seller meeting.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7813a7ab-3c40-4c2f-b1e5-6a75c30bd424)

**Comment by RemcoSimonides** [comment]
> ## Your environment
> OS: MacOS Big Sur
> Browser : Chrome (91.0.4472.77)
> 
> ## Review item
> Meeting Page (Buyer View)
> 
> ### Localization
> * App name: Archipel Market
> * Page: Meeting Page (Buyer View)
> * Url: https://staging.archipelmarket.com/c/o/marketplace/event/20vZ75BpRL4UcuJFokHG/session
> * User used (if anonymized):
>   [dev+cassandre-mko@blockframes.io](mailto:dev+cassandre-mko@blockframes.io)
> 
> ### Context
> * [ ]  The horizontal scrollbar should not appear
> 
> ### Images
> ![horizontal scroll.gif](https://camo.githubusercontent.com/185b4d4f8c4438d388c3d35fce13503df79e96e6b82b27c32e3c31e465e20cfe/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f31663365336166372d666332382d343231362d616630352d336433373731363266373665)

@2amarkina .gif doesn't work and I don't see a horizontal scroll anywhere in the metings. Can you send the working gif?

**Comment by 2amarkina** [comment]
Same environment tested: 
Browser: Chrome, 
User: cassandra

Got this for invitations. Needed to refresh the page before worked correctly 
<img width="1409" alt="Снимок экрана 2021-06-04 в 17 38 27" src="https://user-images.githubusercontent.com/55499036/120827723-05ce4780-c55c-11eb-835f-0be0da2709d7.png">

![horizontal Scroll](https://user-images.githubusercontent.com/55499036/120827734-0830a180-c55c-11eb-89b6-45a9fdddec25.gif)

**Comment by pldespaigne** [comment]
> - [ ] Putting a document / image in full size is not working

Working fine n Chrome x Windows, must be another safari issue
