### ISSUE TITLE
Financing campaign (MF): form & view

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5905]

**Comment by Jackseed** [comment]
App: MF
url https://staging.mediafinanciers.com/c/o/dashboard/title
user dev+madge-wml@blockframes.io

- [ ] Not blocking but worth mentioning, I got this [sentry log](https://sentry.io/organizations/cascade-8/issues/2441953119/?project=1540126&referrer=slack) when creating a new title on dashboard. I didn't do a thing except click on the add a new title button 

```
TypeError
Cannot read property 'received' of null

    this.campaign$ = this.movie$.pipe(
      switchMap(movie => this.campaignService.getValue(movie.id))
    );
    this.sub = this.campaign$.subscribe(data => {
      `this.percentage = Math.floor((data.received / data.cap) * 100);`
      this.cdr.markForCheck();
    });
  }
```

**Comment by Jackseed** [comment]
url https://staging.mediafinanciers.com/c/o/marketplace/title/kmnwQMAqQfievfk1lLY9/financing
user: dev+maverick-qxf@blockframes.io

- [ ] When clicking on the "Open discussion" CTA, the modale subject list has one empty field

![image](https://user-images.githubusercontent.com/14964443/121041330-f1d05300-c7b2-11eb-8e7d-010c80767a99.png)

**Comment by Jackseed** [comment]
url https://staging.mediafinanciers.com/c/o/marketplace/title/kmnwQMAqQfievfk1lLY9/investment
user: dev+maverick-qxf@blockframes.io

- [ ] Title issues:
- "Investment conditions" needs a capital C to conditions
- "Investment Proposal" & "Privileges" should be `h3`
![image](https://user-images.githubusercontent.com/14964443/121043128-a323b880-c7b4-11eb-89e9-0aceeb084a36.png)

- [ ] Same on Financial tab, every text typo looks wrong but best is to show it to @stephanie-cascade8 so she may give the correct title sizes
![image](https://user-images.githubusercontent.com/14964443/121044004-71f7b800-c7b5-11eb-96bd-98c1c8537913.png)
