### ISSUE TITLE
Excel import: orgs, movies

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5906]

**Comment by xmano** [comment]
Found issue with import movie by admin it is not reflected in Catalog App. Use Movie.xlsx in fixtures.

Movies imported successfully.
![image](https://user-images.githubusercontent.com/8731418/120602542-c115b400-c468-11eb-9e9e-801f9bffb348.png)

But can't search in library  and there create-bucket will fail (user: Camilla)

![image](https://user-images.githubusercontent.com/8731418/120602738-eefaf880-c468-11eb-9661-bafe0f22ee61.png)


Exists in release 3.2 branch and also in develop

**Comment by RemcoSimonides** [comment]
Tested on Safari 14.1
- [ ] Replace with the good illustration in svg (probably a problem of webp not working on safari here but the current illustration is obsolete and needs to be updated with a new one anyway. Ask it to the UI team)

<img width="589" alt="Capture d’écran 2021-06-02 à 16 53 10" src="https://user-images.githubusercontent.com/66258851/120503053-4050ac80-c3c3-11eb-980f-f06cc85e91ce.png">

**Comment by phpgeekfr** [comment]
> Found issue with import movie by admin it is not reflected in Catalog App. Use Movie.xlsx in fixtures.
> 
> Movies imported successfully.
> ![image](https://user-images.githubusercontent.com/8731418/120602542-c115b400-c468-11eb-9e9e-801f9bffb348.png)
> 
> But can't search in library and there create-bucket will fail (user: Camilla)
> 
> ![image](https://user-images.githubusercontent.com/8731418/120602738-eefaf880-c468-11eb-9661-bafe0f22ee61.png)
> 
> Exists in release 3.2 branch and also in develop

This is due to the fact that you did not used latest template.  The latest also had a lot of errors that will be corrected in next PR

**Comment by phpgeekfr** [comment]
>  'Need help' button should be a mat button (neither filled nor stroke), in foreground-800 and on click should open the intercom

For the `and on click should open the intercom` part, this is working bug user need to accept cookies before

**Comment by Jackseed** [comment]
Movie import works fine, 
- [ ] I modified a bit the column order to be same as movie form:
    - Logline from BI to AF
    - Social responsibility goals BJ to AX
    - Target Audience BK to AW
Unfortunately it moves all the other columns after BJ as well...

These templates also have an updated "Content type" list, without Documentary, to go along with #5887 
[import-title-template-customer.xlsx](https://github.com/blockframes/blockframes/files/6591817/import-title-template-customer.xlsx)
[import-title-template-admin.xlsx](https://github.com/blockframes/blockframes/files/6591818/import-title-template-admin.xlsx)

**Comment by RemcoSimonides** [comment]
> > 'Need help' button should be a mat button (neither filled nor stroke), in foreground-800 and on click should open the intercom
> 
> For the `and on click should open the intercom` part, this is working bug user need to accept cookies before

Ok. It's also working for me. In the gif you can see that the cookies are accepted because the intercom is in the bottom-right corner. I don't know why it didn't open for Jade then. Maybe Safari?
![Screenshot 2021-06-02 at 11.22.02.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/db3a165d-e3eb-4f38-8b87-dcc315fa64a8)

**Comment by phpgeekfr** [comment]
> I don't know why it didn't open for Jade then. Maybe Safari?
It is working on safari, as long as you accepted cookies

**Comment by phpgeekfr** [comment]
PR https://github.com/blockframes/blockframes/pull/5946 is ready, maybe a change in the image to come because background is not the exact same one

![image](https://user-images.githubusercontent.com/1194344/120658847-190ee380-c486-11eb-9eb6-07f08f48e31e.png)

**Comment by xmano** [comment]
I used a template which was working for a single movie (Content Type: Flow) but the template has problems with TV Series type. Since we are supporting this type of content, we need to have this issue fixed.

[working-test-on-r-3-2.xlsx](https://github.com/blockframes/blockframes/files/6598433/working-test-on-r-3-2.xlsx)

**Comment by phpgeekfr** [comment]
Working on my side and also on https://staging.blockframes.io

**Comment by RemcoSimonides** [comment]
- [ ] The illustration needs margin bellow before the button. 24px
![image](https://user-images.githubusercontent.com/27687382/121187094-fc005900-c867-11eb-91e7-f873f11e5229.png)
