### ISSUE TITLE
CMS + homepages

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5907]

**Comment by phpgeekfr** [comment]
- [x] CMS : LGTM
- [ ] Home pages

**Comment by phpgeekfr** [comment]
despite the bug mentioned in #5870 (not mandatory)  CMS app is functional

**Comment by phpgeekfr** [comment]
found undefined app logo : ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/8d79b986-fda4-4b76-9d35-fd18f7b08704)

Displayed only when not logged yet

**Comment by phpgeekfr** [comment]
also, I can login to cms app even if I'm not blockframes admin (with dev+jared-eix@blockframes.io for example). I cannot edit anything because the rules prevent me but I can see all the config.

When I hit the save button, there is no message letting me known that there was a permission issue

**Comment by phpgeekfr** [comment]
Allowed space for `+33` is maybe too big ?

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/091f556d-d253-4cc5-9601-f3b09dc01045)

**Comment by phpgeekfr** [comment]
Space between the two blockchains lines is not the same as the other paragraph:

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/d072740d-c6c8-44c6-99b1-66d3d449e0ad)


And blockchain ? Really ^^

**Comment by phpgeekfr** [comment]
This is in fact due to my wide screen, with a normal screen size:
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/a482d757-e957-41ca-9227-2b29571711e4)

**Comment by phpgeekfr** [comment]
this happen only on wide screen on financiers but a bit annoying:

When I click on `Professional Content Financiers` tab, window is cropped

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/6a4fcbd3-c265-4831-b051-e6bef4524b0f)


![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/d4bce369-5a8e-42a4-8a8e-05a9942e9c71)
