### ISSUE TITLE
Double validation feature on delivery 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#591]
- [ ] Bottom sheet to show both delivery states & MG payments
- [ ] Delivery states needs both stakeholders to accept to be modified (1. Delivery in negociation /  2. Material Pending / 3. Notice of Availability / 4. Notice of Delivery / 5. Material Accepted)
- [ ] MG payments double validation

**Comment by Jackseed** [comment]
![image](https://user-images.githubusercontent.com/14964443/60956070-6027e480-a302-11e9-9cd5-212127906ecb.png)

**Comment by lsenta** [comment]
Bottom of the delivery page, expand bar:
2 indicators:
- MG status / echéancier
- delivery status (global)

Échéance / paiement deadlines.

Show steps => fix 5 steps on a delivery list. 
Tracking indicators: double validation by stakeholders.

**Comment by lsenta** [comment]
@Jackseed : Moving this to Icebox and removing the sprint marker.
