### ISSUE TITLE
New user test -updates & improvements

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5924]
#### Library 
- [x] Change "Format" filter title to "Content Type"
- [ ] If possible within the release time, remove "Documentary" from Format / Content Type filter list & keep it only in Genres + make a migration that must be title by title to find the right content type instead & tag it as genre documentary
- [x] Country of origin filter: remove "World" from the list
- [x] Remove Language & version filter from `catalog` app only
- [x] Avails filter: if possible, fill start date by default with current day & end date with the current day + 1 year

#### Movie view marketplace 
- [x] Avails tab, world map: do the same as avails filter above (start date = current date; end date = current date + 1 year by default)
- [x] add a hero with a "Contact Us" CTA that opens Intercom cf [zeplin](https://app.zeplin.io/project/5fecb41a2e806651584e265c/screen/6086ad1bcd8a35129d08f3e3)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/3793ac15-cc36-4479-b62a-09d5fbd3e82c)
- [x] Check with @jdrns how to change the contact link UI above the map & calendar 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/178ff8cb-3780-44b0-b00e-63f33d87da90)

**Comment by jdrns** [comment]
> * [ ]  Check with @jdrns how to change the contact link UI above the map & calendar
>   ![image.png](https://camo.githubusercontent.com/5790b5569b3b6ea8b691916de90b452e9256503bb6b4b100993e9b835331dea9/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563366138396163386465316233316435343433616239392f31373866663863622d333738302d343462302d623030652d363366333364383764613930)

Here we have an `<a>` that navigates to another page so we can use an underline. Issue is coming soon with all the changes that will be needed for the long term + the rules that will be applied

**Comment by RemcoSimonides** [comment]
Created dedicated issue for left-overs: #6009
