### ISSUE TITLE
Review: Staging Users for tests

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#5929]
## Your environement
_Please describe your environment_ 
- OS: Mac
- Browser (& version if possible): Chrome _Version 90.0.4430.212_

## Review item
Files Component
### Localization
- App name: Market
- Page: Files
- Url: https://staging.archipelmarket.com/c/o/dashboard/files

### Fix
- [ ] Add margins around the upload area (between the surface and the upload area) 24px
**@RemcoSimonides I see that 12 was added not 24px as asked**
- [x] We need more space between return arrow and the beginning of the breadcrumbs.(group elements by category)

### Images
<img width="583" alt="Capture d’écran 2021-06-02 à 09 17 33" src="https://user-images.githubusercontent.com/66258851/120449196-825ffb00-c38f-11eb-9984-61afd9d4691b.png">

## Review item
App logo, Footer & filled or stroke buttons
### Localization
- App name: Market
- Page: https://staging.archipelmarket.com/c/o/marketplace/home
- Url: https://staging.archipelmarket.com/c/o/dashboard/files

### Fix
- [x] Logo (tag element app logo) should be 48px height instead of 60px.
- [x] Buttons need to be fixed sizes not fluid (just like before the material updates)
related doc for integration here
- [x] Footer. Reduce padding from 40px (top and bottom) to 24px.
App logo size in footer from 60px to 48px just like in the toolbar.

### Images
<img width="502" alt="Capture d’écran 2021-06-02 à 11 05 05" src="https://user-images.githubusercontent.com/66258851/120452875-d3252300-c392-11eb-9c25-35a844467c82.png">
<img width="395" alt="Capture d’écran 2021-06-02 à 11 06 49" src="https://user-images.githubusercontent.com/66258851/120452889-d7514080-c392-11eb-995f-f5af7054fc05.png">
<img width="490" alt="Capture d’écran 2021-06-02 à 11 09 00" src="https://user-images.githubusercontent.com/66258851/120453257-2b5c2500-c393-11eb-9698-4f1b9d3efed0.png">
<img width="789" alt="Capture d’écran 2021-06-02 à 11 09 10" src="https://user-images.githubusercontent.com/66258851/120453276-30b96f80-c393-11eb-9597-5886149e2742.png">

## Review item
Mat-buttons in the movie header 
### Localization
- App name: Market
- Page: Film Page
- Url: https://staging.archipelmarket.com/c/o/marketplace/title/0Qc7ijgedk84sFWZlXgX/screenings

### Fix
- [ ] A special mat-buttons (with no padding on the left) was designed few weeks ago by Jade. 
It needs to be implemented here to solve our alignement problem. 
Please find it here (see it's different states: default, hover...) 

https://zpl.io/blKQozk
**@RemcoSimonides It was not done. Maybe this issue needs to be rediscussed (this component was made a long time ago)**

- [x] Line height needs to be reduced from 26 to 24 in all h5. (& all titles).
<img width="252" alt="Capture d’écran 2021-06-02 à 11 52 26" src="https://user-images.githubusercontent.com/66258851/120460371-5b0e2b80-c399-11eb-8769-92a2ed8b8630.png">

### Images
<img width="638" alt="Capture d’écran 2021-06-02 à 11 14 18" src="https://user-images.githubusercontent.com/66258851/120454721-6e6ac800-c394-11eb-97d8-5f677b64cd90.png">

## Review item
Illustration in credit-cards
### Localization
- App name: Market
- Page: Film Page
- Url: https://staging.archipelmarket.com/c/o/marketplace/title/2qsDg0CPQooNcyhVMyWg/main

### Fix
- [x] Ask a new illustration with the right colors to the design team (those are old wrong colors)

### Image
<img width="315" alt="Capture d’écran 2021-06-02 à 11 25 13" src="https://user-images.githubusercontent.com/66258851/120456283-bdfdc380-c395-11eb-881b-3be9427f37ce.png">

### Review item
Di

### Localization
App name: Market
Page: Movie Tunnel
Url: https://staging.archipelmarket.com/c/o/marketplace/title

### Context
When filtering by Languages & Versions

### Fix
 - [x] Add more margin-right between inline checkboxes
12px
 - [x] Add more margin-bottom between inline checkboxes
12px
_(the effect is more obvious when clicking inside the checkbox, the ripple effect crosses on close elements)_

### Image
<img width="604" alt="Capture d’écran 2021-06-02 à 11 56 06" src="https://user-images.githubusercontent.com/66258851/120461164-0fa84d00-c39a-11eb-971e-b317e01f6f5e.png">
<img width="488" alt="Capture d’écran 2021-06-02 à 12 05 06" src="https://user-images.githubusercontent.com/66258851/120463013-c22cdf80-c39b-11eb-8584-5e1574f40976.png">

## Review item
Illustration in credit-cards
### Localization
- App name: Market
- Page: Film Page
- Url: https://staging.archipelmarket.com/c/o/marketplace/title/2qsDg0CPQooNcyhVMyWg/main

### Fix
- [x] Ask a new illustration with the right colors to the design team (those are old wrong colors)

### Image
<img width="315" alt="Capture d’écran 2021-06-02 à 11 25 13" src="https://user-images.githubusercontent.com/66258851/120456283-bdfdc380-c395-11eb-881b-3be9427f37ce.png">

### Review item
Inline Checkboxes

### Localization
App name: Market
Page: Movie List
Url: https://staging.archipelmarket.com/c/o/marketplace/title

### Context
When filtering by Languages & Versions

### Fix
 - [x] Add more margin-right between inline checkboxes
12px
 - [x] Add more margin-bottom between inline checkboxes
12px
_(the effect is more obvious when clicking inside the checkbox, the ripple effect crosses on close elements)_

### Image
<img width="604" alt="Capture d’écran 2021-06-02 à 11 56 06" src="https://user-images.githubusercontent.com/66258851/120461164-0fa84d00-c39a-11eb-971e-b317e01f6f5e.png">
<img width="488" alt="Capture d’écran 2021-06-02 à 12 05 06" src="https://user-images.githubusercontent.com/66258851/120463013-c22cdf80-c39b-11eb-8584-5e1574f40976.png">

### Review item
Dividers
Form elements
Tables

### Localization
App name: Market
Page: Movie tunnel
Url: https://staging.archipelmarket.com/c/o/dashboard/tunnel/movie/VIHFmbx7YzBbT774cu3e/media-videos
https://staging.archipelmarket.com/c/o/dashboard/tunnel/movie/VIHFmbx7YzBbT774cu3e/main

### Context
Dividers separating sections in general
Table showing the first added director

### Fix
 - [x] Take off unnecessary border of 2px
 - [ ] Cropping area needs space around (before the card's borders) 24px
 @remco space was added but not enough (24px important)
 
 - [ ] The table showing a director that was just added needs a horizontal scroll (the action column with edit and delete needs to stay fixed on the right)
 @remco this was not done
 - [x] Textareas used to be extandable with an icon on right-end corner. Did it disapear with the material update ? let's put it back or have the field's height increase a little with the filled content.
 -> this seemed to be solved when updating chrome.

### Image
<img width="789" alt="Capture d’écran 2021-06-02 à 12 23 02" src="https://user-images.githubusercontent.com/66258851/120465086-e38ecb00-c39d-11eb-837c-df754c47eb00.png">
<img width="634" alt="Capture d’écran 2021-06-02 à 12 29 19" src="https://user-images.githubusercontent.com/66258851/120465467-4e400680-c39e-11eb-8b74-887a0ac05149.png">
<img width="823" alt="Capture d’écran 2021-06-02 à 12 34 03" src="https://user-images.githubusercontent.com/66258851/120466361-42a10f80-c39f-11eb-903e-0f5491e32989.png">
<img width="1088" alt="Capture d’écran 2021-06-02 à 12 40 28" src="https://user-images.githubusercontent.com/66258851/120467070-146fff80-c3a0-11eb-8790-6a1253cd6f9f.png">

**Comment by stephanie-cascade8** [comment]
## Your environement
_Please describe your environment_ 
- OS: IOS
- Browser (& version if possible): Safari 14.1 

## Review item
Files Component
### Localization
- App name: Content
- Page: Dashboard
- Url: https://staging.archipelcontent.com/c/o/dashboard/home

### Fix
- [ ] Manage footer margins so that all elements can fit entirely within the same line.
In fact, padding on all buttons needs to be 24px instead of 32px. (that would solve the footer problem among others)
### Images
<img width="1209" alt="Capture d’écran 2021-06-02 à 14 42 01" src="https://user-images.githubusercontent.com/66258851/120482014-fced4280-c3b0-11eb-9116-7107a9361d0d.png">
![Uploading Capture d’écran 2021-06-02 à 14.45.58.png…]()

**Comment by stephanie-cascade8** [comment]
## Your environement
_Please describe your environment_ 
- OS: IOS
- Browser (& version if possible): Safari 14.1 

## Review item
Files Component
### Localization
- App name: Financiers
- Page: 
- Url: 

### Fix
- [ ] 

- [ ] 


### Images

**Comment by RemcoSimonides** [comment]
> * [ ]  Take off unnecessary border of 2px

Re: for every mat-divider in the every tab when editing a movie? this extra border is used a lot.

> * [ ]  Cropping area needs space around (before the card's borders) 24px

Re: Could you provide a more clear image and/or description what has to change exactly?

> * [ ]  The table showing a director that was just added needs a horizontal scroll (the action column with edit and delete needs to stay fixed on the right)

Re: In your image it looks like the edit and delete do stay fixed on the right. Only when I make the screen smaller to like mobile size, the edit button disappears. Is that what you meant?

> * [ ]  Textareas used to be extandable with an icon on right-end corner. Did it disapear with the material update ? let's put it back or have the field's height increase a little with the filled content.

Re: It's there ;) When you don't have the scroll bar yet (haven't typed text) it's easy to see it. Once you have enough text, the button goes underneath the scroll bar. Since the scroll bar is quite small, this expand icon is also small.

**Comment by RemcoSimonides** [comment]
> * after clicking on "learn how it works", the buttons at the bottom of the modal have the size problem (fixed, fluid after material updates). strange problem since it doesn't happen on all our filled and stroke buttons.

What is the size problem?

**Comment by RemcoSimonides** [comment]
Hee @stephanie-cascade8 , if you have time today; can you check if the issues you mentioned are fixed (and resolved correctly)? If yes, you can tick the box. if not, you can leave the checkbox unchecked open. Let me know when you're finished so I can see those issues.

**Comment by stephanie-cascade8** [comment]
> > * [ ]   Take off unnecessary border of 2px
> 
> For every mat-divider in the every tab when editing a movie? this extra border is used a lot.
> there's a bug at this place (divider is bigger than others I think, maybe they are two of them?)
> > * [ ]   Cropping area needs space around (before the card's borders) 24px
> 
> Could you provide a more clear image and/or description what has to change exactly?
> IMage is there, space is needed betwee the cropping area and the surface. I see that 12px were added, we need 24px.
> > * [ ]   The table showing a director that was just added needs a horizontal scroll (the action column with edit and delete needs to stay fixed on the right)
> 
> In your image it looks like the edit and delete do stay fixed on the right. Only when I make the screen smaller to like mobile size, the edit button disappears. Is that what you meant?
> yes it is fixed! so we want to keep it fixed and have other columns scroll horizontally under with a scrollbar so we can show more of the description and filmography? see the wireframes here : 

> > * [ ]   Textareas used to be extandable with an icon on right-end corner. Did it disapear with the material update ? let's put it back or have the field's height increase a little with the filled content.
> this seemed to be solved with an update of chrome
> It's there ;) When you don't have the scroll bar yet (haven't typed text) it's easy to see it. Once you have enough text, the button goes underneath the scroll bar. Since the scroll bar is quite small, this expand icon is also small.
<img width="688" alt="Снимок экрана 2021-06-08 в 12 02 54" src="https://user-images.githubusercontent.com/66258851/121167209-044d9980-c852-11eb-8904-9ab94d0e6d65.png">
