### ISSUE TITLE
Production / Release Year

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#5935]
The tests showed that buyers were interested in having a possibility to filter the Titles with Production Year. 

Following the meeting with @Jackseed and @ChristophePecot the filter should be a slider with possibility to set a date with "starting from" logic. 

Here is the wireframe proposed 
![Снимок экрана 2021-06-02 в 10.22.23.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7f9940d3-80ec-4177-b85c-aa877f609c3d)

Wireframes could be found [here ](https://www.figma.com/file/vmwPJzLshwzT1FGwrECDlo/Filters-Update?node-id=0%3A1)

N.B. Text to be checked

**Comment by Jackseed** [comment]
looks good to me, waiting for Christophe's feedback

**Comment by 2amarkina** [comment]
This one can take time on development side and also can eventually have negative numbers to work correctly. But apparently it could be hidden. 

![Снимок экрана 2021-06-10 в 16.20.24.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b6783f38-206c-40be-bc25-a951c773d381)


Also tried with "from", "to" version 
![Снимок экрана 2021-06-10 в 16.41.52.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/60472cba-e4b0-4f0e-b36a-4a8a64a8b716)

**Comment by 2amarkina** [comment]
Use phare version if we are able **not to show "-"**

If not possible, use the radios
![Снимок экрана 2021-06-11 в 13.46.35.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/cd5cb6ec-8f16-4ec7-b373-f52661aec30f)

**Comment by RemcoSimonides** [comment]
@RemcoSimonides Make dev issue

**Comment by RemcoSimonides** [comment]
Created dev issue #6066
