### ISSUE TITLE
Review: UX/UI Archipel Content

### ISSUE THREAD

**Issue by jdrns** [blockframes/blockframes#5936]
## Your environement
- OS: Mac OS Big Sur
- Browser (& version if possible): Safari 14.0.3

### Localization
- App name: Archipel Content
- Page: Sign up
- Url: https://staging.archipelcontent.com/auth/identity
- User used (if anonymized): -

### Context
- [ ] Intercom was missing for a bit, despite reloads, and then just re-appeared after a while
_Intercom is still missing time to time_
### Images
**_See other gifs of other review items_**

### Localization
- App name: Archipel Content
- Page: Sign up
- Url: https://staging.archipelcontent.com/auth/identity
- User used (if anonymized): -

### Context
'Already have an account? Log in here' is missing 

### Fix
- [x] Add 'Already have an account? Log in here' and 'Log in here' should be underlined, not bold

### Images
![d.gif](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/da1c0a6e-48b0-49a6-a2be-c753d00092c8)

### Localization
- App name: Archipel Content
- Page: Import titles in bulk
- Url: https://staging.archipelcontent.com/c/o/dashboard/import
- User used (if anonymized): dev+trevor-kcu@blockframes.io

### Context
Various issue with the buttons: 
- Need help is currently an `<a>` with `<strong>` that doesn't do anything on click 
- Import file button background should not be white 

- Image isn't displayed in Safari 

### Fix
- [x] 'Need help' button should be a mat button (neither filled nor stroke), in foreground-800 and on click should open the intercom
- [x] 'Import file' button should be a filled button in primary-500

- [x] Illustration is an old one and the new one should be exported as .png. New illustration should be done

### Images
![Screenshot 2021-06-02 at 11.22.02.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/db3a165d-e3eb-4f38-8b87-dcc315fa64a8)

### Localization
- App name: Archipel Content
- Page: Footer Dashboard
- Url: https://staging.archipelcontent.com/c/o/dashboard/home
- User used (if anonymized): dev+trevor-kcu@blockframes.io

### Context
When side menu is open, "© 2021 Archipel Content, Paris" goes under footer menu

### Fix
- [x] Should be aligned with the rest of the menu, just as when side menu is closed

### Images
![a.gif](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/925bd00e-1d50-42dc-bb2b-d1f1f3bc63d7)

### Context
When clicking on Legal Terms, arrow 'back' doesn't work.
Same for Privacy Policy.

### Fix
- [x] Arrow 'back' should go back to the previous page

### Images
![b.gif](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/d080aa1c-4f33-4a1d-a9a7-851fb0382b65)

### Localization
- App name: Archipel Content
- Page: My Titles
- Url: https://staging.archipelcontent.com/c/o/dashboard/title
- User used (if anonymized): dev+trevor-kcu@blockframes.io

### Context
Tab 'All' doesn't have the blue underline like the other tabs

### Fix
- [x] Tab 'All' should haver that blue underline

### Images
![c.gif](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/81448a62-3351-4ee9-862e-a863b74191f5)

### Localization
- App name: Archipel Content
- Page: Home Marketplace
- Url: https://staging.archipelcontent.com/c/o/marketplace/home
- User used (if anonymized): dev+tevin-dtu@blockframes.io

### Context
On slider, the old version of the 'Add to wishlist button' has padding on the left

### Fix
- [ ] [Issue](https://github.com/blockframes/blockframes/issues/5228) was created for it and is currently closed but not sure it was done completely. In the comment section under 'Movie page', you can find the recommendations

### Images
<img width="1440" alt="Screenshot 2021-06-02 at 14 27 38" src="https://user-images.githubusercontent.com/79836137/120479829-b0086c80-c3ae-11eb-9245-3bb955fc5f8f.png">

### Localization
- App name: Archipel Content
- Page: Library Marketplace
- Url: https://staging.archipelcontent.com/c/o/marketplace/title
- User used (if anonymized): dev+tevin-dtu@blockframes.io

### Context
When opening a filter then scrolling, the scroll isn't blocked and then box stays in position

### Fix
- [x] Like on Chrome or mozilla, scroll should be disabled when a filter is open

### Images
![f](https://user-images.githubusercontent.com/79836137/120482072-0ecee580-c3b1-11eb-8fc3-137405e2e837.gif)

### Localization
- App name: Archipel Content
- Page: Movie Page Marketplace
- Url: https://staging.archipelcontent.com/c/o/marketplace/title/0BrO3forlzjCeBYHEMmy/main
- User used (if anonymized): dev+tevin-dtu@blockframes.io

### Context
- On movie banner, the old version of the 'Add to wishlist button' has padding on the left

### Fix
- [ ] [Issue](https://github.com/blockframes/blockframes/issues/5228) was created for it and is currently closed but not sure it was done completely. In the comment section under 'Movie page', you can find the recommendations

### Images
<img width="1440" alt="Screenshot 2021-06-02 at 14 28 36" src="https://user-images.githubusercontent.com/79836137/120479961-d3331c00-c3ae-11eb-8db5-7e666c3a2a64.png">

### Localization
- App name: Archipel Content
- Page: Movie Page Marketplace
- Url: https://staging.archipelcontent.com/c/o/marketplace/title/0BrO3forlzjCeBYHEMmy/main
- User used (if anonymized): dev+tevin-dtu@blockframes.io

### Context
- [x] Weird transition behaviour when clicking on Search and Buy Rights

### Images
![g](https://user-images.githubusercontent.com/79836137/120481891-e3e49180-c3b0-11eb-8548-1a13dd57c3c6.gif)

### Localization
- App name: Archipel Content
- Page: Movie page Map Marketplace
- Url: https://staging.archipelcontent.com/c/o/marketplace/title/uvnZQ5PaD8Ts2Q8rYETo/avails/map
- User used (if anonymized): dev+tevin-dtu@blockframes.io

### Context
- [ ] When selecting a country, cards are not showing on Safari

- [ ] Fields dates, when in error state, aren't aligned with the other fields anymore
- [ ] Hint says 'Date must be in the future' even though no date is input
- [ ] Typo in field Exclusivity, it should be 'Ex**c**lusivity' not 'Exlusivity'

### Images
<img width="1428" alt="Screenshot 2021-06-02 at 15 23 48" src="https://user-images.githubusercontent.com/79836137/120487776-89e6ca80-c3b6-11eb-8287-3621a6918a54.png">

### Localization
- App name: Archipel Content
- Page: Movie page Calendar Marketplace
- Url: https://staging.archipelcontent.com/c/o/marketplace/title/uvnZQ5PaD8Ts2Q8rYETo/avails/calendar
- User used (if anonymized): dev+tevin-dtu@blockframes.io

### Context
- Calendar cells are not all the same width, the width is depending on the content

- Legend is a bit in the middle of nowhere

### Fix
- [ ] Can we add a min-width? 

- [ ] We should put the legend in a small card just like on the map view but for the calendar on the top left corner of the card

### Images
![h](https://user-images.githubusercontent.com/79836137/120491863-e0093d00-c3b9-11eb-96ce-0e442c26b8f7.gif)

### Localization
- App name: Archipel Content
- Page: Movie page Calendar Marketplace
- Url: https://staging.archipelcontent.com/c/o/marketplace/title/uvnZQ5PaD8Ts2Q8rYETo/avails/calendar
- User used (if anonymized): dev+tevin-dtu@blockframes.io

### Context
- User can select start date and then select that same date as an end date but then on the card it will show 'from 04/01 to 04/01' 
- When selecting March as the start date, no mater what end date is selected, no card is created and nothing happens (no snackbar either) 

### Fix
- [x] Can we block that behaviour by not allowing the cell 'start' to become 'end' on click?
- [ ] Not sure why nothing appears, maybe because the month is already over? But then it's doesn't do it for April or other month

### Images
![i](https://user-images.githubusercontent.com/79836137/120493098-f49a0500-c3ba-11eb-9bdc-7db6f5a4bfb6.gif)

### Localization
- App name: Archipel Content
- Page: My Selection
- Url: https://staging.archipelcontent.com/c/o/marketplace/selection
- User used (if anonymized): dev+tevin-dtu@blockframes.io

### Context
In the field under please select a currency, there is no placeholder (had this issue but when I tried to reproduce the scenario, I couldn't make it happen again)

### Fix
- [x] Either add a placeholder or select a default currency?

### Localization
- App name: Archipel Content
- Page: Activity Feed
- Url: https://staging.archipelcontent.com/c/o/marketplace/notifications
- User used (if anonymized): dev+tevin-dtu@blockframes.io

### Context
Notification 'Your offer was sent', when clicking on 'More' it goes back to home page 

### Fix
- [x] On click should go to 'Offers & Deals' page

### Images
![j](https://user-images.githubusercontent.com/79836137/120506937-ac80df80-c3c6-11eb-8828-5f92da12c037.gif)

**Comment by RemcoSimonides** [comment]
Hee @jdrns , if you have time today; can you check if the issues you mentioned are fixed (and resolved correctly)? If yes, you can tick the box. if not, you can leave the checkbox unchecked open. Let me know when you're finished so I can see those issues.

I believe the issue with the error messages in Avails Criteria Search fields need more time and cannot be quickly fixed before the release; so don't worry about that one
