### ISSUE TITLE
LOG IN time issue

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#5940]
- [ ] When I log in, I noticed that nothing happens when I click of "Log in". The text just changes to "Logging in..." but there's absolutely no movement until I click the button again. This happens regularly (if not everytime) and with different emails

https://user-images.githubusercontent.com/55785823/120626189-b48e5d00-c462-11eb-8c63-de1af38b6890.mov

**Comment by Jackseed** [comment]
Not sure but it could be an observable issue as most of the time when I reload the page I'm instantly connected

**Comment by xmano** [comment]
Trying to recreate this with various ways:

1. With a invalid email id -  PASS (User does not exist)
2. With invalid email id and cache cleared - PASS
3. Valid email id - login works
4. Valid email id - alread logged in, switch app to catalog from festival -  PASS
5. Again logout and login with invalid email id - PASS (User does not exist )

Will try account creation scenarios and update if it happens.

**Comment by xmano** [comment]
Found another issue in the process:

After trying to login with a non-existing email id, trying to create an account for the same, Sign UP button is not enabled and no message is displayed.

![image](https://user-images.githubusercontent.com/8731418/124604022-23a70900-de88-11eb-854e-b2680dd98acb.png)

**Comment by maltmayer** [comment]
> Found another issue in the process:
> 
> After trying to login with a non-existing email id, trying to create an account for the same, Sign UP button is not enabled and no message is displayed.
> 
> ![image](https://user-images.githubusercontent.com/8731418/124604022-23a70900-de88-11eb-854e-b2680dd98acb.png)
> 
> This may be probably related to non existing company but is bit confusing.

I've seen this issue before. It looks like you didn't select a company in the list

**Comment by Jackseed** [comment]
Thanks @xmano this has been resolved with #6200 

> Found another issue in the process:
> 
> After trying to login with a non-existing email id, trying to create an account for the same, Sign UP button is not enabled and no message is displayed.
> 
> ![image](https://user-images.githubusercontent.com/8731418/124604022-23a70900-de88-11eb-854e-b2680dd98acb.png)
> 
> This may be probably related to non existing company but is bit confusing.
> 
> ![image](https://user-images.githubusercontent.com/8731418/124604852-fdce3400-de88-11eb-8982-e4bff060a27d.png)
> 
> The snackbar message disappears if you try to login before account was authorized. In this scenario it is better to keep it open for user to acknowledge

**Comment by phpgeekfr** [comment]
Tried several times today, sometimes it is a bit long for the page to refresh but it always changed at some point.

I will try again to reproduce the problem while fixing other issues.

**Comment by maltmayer** [comment]
> Only feedback here is that snackbar message can be kept open until user explicitly acknowledges it.

Not sure this will be enough. This error happens a lot and the snackbar is not clear on why/what has to be done. Would it be possible to find out the source of this issue to either prevent it from happening as much or offer a quick solution to users?

**Comment by phpgeekfr** [comment]
> Would it be possible to find out the source of this issue to either prevent it from happening as much or offer a quick solution to users?

We tried a lot, but we never managed to reproduce it. So we cannot know how to fx it. If you have a scenario where this always happen it could be very useful.

> Only feedback here is that snackbar message can be kept open until user explicitly acknowledges it.

Maybe we can do this to start ..

**Comment by maltmayer** [comment]
> We tried a lot, but we never managed to reproduce it. So we cannot know how to fx it. If you have a scenario where this always happen it could be very useful.

The problem is that I know it's super random but it really happens a lot. I know it doesn't help to say it, but it's one of the most recurring issues users get when they try to sign up...

> > Only feedback here is that snackbar message can be kept open until user explicitly acknowledges it.
> 
> Maybe we can do this to start ..

No, it's not a question of how long its stays open, they usually do see the error message. They just don't understand what to do. The text is not clear on what the error is. Do we know what triggers this error message? Like in the code I mean. I think we should at least give them a lead on what to do. Maybe just refresh their page / check if there's a spelling mistake...?

**Comment by Jackseed** [comment]
It looks to me that we are mixing 2 conversations, the snackbar about wrong email and/or password and the time to login (ie from correct credentials to the homepage). 

Re the email and/or password normally it's triggered with email or password being incorrect. I've never experienced a bug with that but I think you had one @maltmayer. If it's email or password we can't be more specific for security reason, we don't want to say if the user exists or not. 

Re the login being long, I experienced it as well and indeed when you do something (click, refresh) you are finally led to the homepage. But I didn't find any pattern on when/why this happen

**Comment by xmano** [comment]
I was able to see this issue while testing manually on release 3.5. I was on staging server.

I think here are the steps for record:

1. Login using an account at https://staging.archipelcontent.com/
2. In another tab, login with a different account at the same app
3. The new login appears to be stuck

![image](https://user-images.githubusercontent.com/8731418/141498907-08973ed2-0870-4b9d-80cc-af147ba0879a.png)

This may or may not be valid in real scenario but might help fix the similar issue.

Pressing login button again logs in the user.

**Comment by cams-goussale** [comment]
hey @xmano @phpgeekfr not sure this will help but just in case...

Steps to reproduce (quite quickly):

-Loggin with 1st user.  Successfully logged in. Log out immediately.
-Loggin with 2nd user. Successfully logged in. Log out immediately.
-Loggin with 3rd user - issue happened (CTA changed for "Loggin in...", no snackbar, nothing happened)
![image](https://user-images.githubusercontent.com/93206363/145583108-8deffea0-5dd9-44a1-8751-3f978a0e6aef.png)

-Click a second time on CTA Loggin in. Got successfully logged in.
![image](https://user-images.githubusercontent.com/93206363/145583322-afb09da8-ac94-41d4-9347-fc5bcfbde903.png)

-Log out.
-Loggin with 4th user - issue happened again (CTA changed for "Loggin in...", no snackbar, nothing happened)
![image](https://user-images.githubusercontent.com/93206363/145583424-480c3da4-7068-45b4-a330-346456e8e8b4.png)

-Click on refresh. Got successfully logged in.
![image](https://user-images.githubusercontent.com/93206363/145583534-1474310d-0703-40e5-8f1f-58dccfd4c78c.png)
