### ISSUE TITLE
Update emails templates with OrgEmailData & UserEmailData

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5941]
Following issue #5186 we need to update email templates using new object variables.
See [documentation](https://www.notion.so/cascade8/Email-Data-Object-8ed9d64e8cd4490ea7bc0e469c04043e) 

Example of new variables: `hello user.firstname, we let you know that userSubject.firstname wants to join your org !` 

All templates are to be changed except:
templateIds.user.verifyEmail : d-81438bdf511b43cfa866ca63a45a02ae
templateIds.user.welcomeMessage : d-fc05a8cf5b1548ebae9ca44247a6c256
templateIds.user.resetPassword : d-6a0710945bc841ffb6955e3dc202704c
templateIds.user.appAccessRequest : d-a740796b97bf403292b3940804977bbe (this one could be changed as there is a userFirstName)

**Comment by Jackseed** [comment]
templates created, still need to activate them just after the release

**Comment by RemcoSimonides** [comment]
Checked Sendgrid and looks like Vincent did activate the new templates
