### ISSUE TITLE
Improve Complex choices on Movie Tunnel

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#5962]
_Estimated priority: high_ 

- [ ] this issue will demand notion creation 

Some complex choices (for example Shooting Dates in Movie Tunnel) could be improved. 

From this ![Снимок экрана 2021-06-04 в 18.00.20.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1aa98400-e74e-4384-91cc-5bd5069120a4)

To something with dynamic form (example of idea)
![Снимок экрана 2021-06-04 в 18.02.34.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/29747b18-e965-48d1-ba56-ea5b55c65e81)

**Comment by RemcoSimonides** [comment]
Let's wait for a user test with movie form before we decide to change this
