### ISSUE TITLE
Improve Upload Boxes

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#5964]
_Estimated priority:_ high

The beginning of work was [here](https://www.figma.com/file/Hlqmog9lrajjquJoXi18w6/%5B-Uploading-System-%5D)

- Improving cropper 
- Improving upload of multiple images 

Steps to take:

- [ ] clean this workspace
- [ ] verify all the states for all upload box types
- [ ] **!important** this issue should be related to [the issue about implementation of Video Thumbnail](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/4737) following the last dev review
- [ ] this issue will demand notion creation

**Comment by RemcoSimonides** [comment]
Wait for feedback from user too. Let them test this first.
