### ISSUE TITLE
Table interactions improvements

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#5966]
_Estimated priority: medium_

- [ ] keep the filters in tables saved: i.g. if user removes "status" column, it should be saved and when refreshes the page, should still have no avatar "status"
(would work only if user specific !)

- [ ] #6519

**Comment by RemcoSimonides** [comment]
For the filters we wait for user test first.

For the hover effect on table rows I feel like it should only be applied when the row is clickable. But don't we have that already? Have to check.

**Comment by 2amarkina** [comment]
Exactly, it should be used to show that a user can click on a row and also to better highlight the row info. 

For the moment we do not have it 
![row.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a3732ca0-4a64-4c87-86eb-017e11e29061)

**Comment by Jackseed** [comment]
Hover added on new tables and there is no more column filter > close
