### ISSUE TITLE
Calendar Improvements

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#5967]
_Estimated priority: medium, but can tend to high_

List of improvements / features that wireframes should reflect :
- [ ] able the list view for calendar (prepare screens for switching); 
- [ ] prepare the list view screen;
- [ ] block user if wants to create an event in the past (+ what message to show?);
- [ ] able different period views (day, week, month ?) (prepare screens for each).

**Comment by RemcoSimonides** [comment]
Estimation
UX: 12 days
UI: 6 days

**Comment by 2amarkina** [comment]
Important feedback from WTFilms:

- [ ] When user comes back several times to the planning, keep him always on the last week s/he was working on

**Comment by cams-goussale** [comment]
hello @2amarkina :) can we add also:

- [ ] Maintain the avatar + nav bar when calendar is open

**Comment by cams-goussale** [comment]
>When user comes back several times to the planning, keep him always on the last week s/he was working on

Open issue in Sanity should fix this #6603

**Comment by Jackseed** [comment]
Also add a "+" button ?

**Comment by cams-goussale** [comment]
Slightly out of the scope of this issue, but this was detected by Nicolas. There is an empty option in the filters of the calendar. Is this the expected behavior? Does it make sense to filter by no events?
![image](https://user-images.githubusercontent.com/93206363/161501373-a6a9e0bf-855f-4db2-976f-2ff03fee69c6.png)

**Comment by Jackseed** [comment]
> Slightly out of the scope of this issue, but this was detected by Nicolas. There is an empty option in the filters of the calendar. Is this the expected behavior? Does it make sense to filter by no events? ![image](https://user-images.githubusercontent.com/93206363/161501373-a6a9e0bf-855f-4db2-976f-2ff03fee69c6.png)

Not sure to understand your comment, is it the correct screenshot?

**Comment by 2amarkina** [comment]
> Slightly out of the scope of this issue, but this was detected by Nicolas. There is an empty option in the filters of the calendar. Is this the expected behavior? Does it make sense to filter by no events?
> 
> ![image](https://user-images.githubusercontent.com/93206363/171641037-ced572a9-f6b9-4bd6-a18b-69d93c59e4e7.png)

In this dropdown we do not need to have an empty option. 
Nevertheless, as now we've got three types of events (Screenings, Meetings and Slate Presentations) we have two options depending on what's possible to do: 

1. As a seller I can see the three types (Screenings, Meetings and Slate), so in my dropdown when filtering I can have "All events / Screenings / Meetings and Slate Presentations". But as a Buyer for me Slates are shown as Screenings (All events / Screenings / Meetings). If we can distinguish the filtering for Dashboard and Marketplace - it might be a good option. 

2. If we can't do this ☝️ (and as the calendar view seems to be shared), then we should have "All events / Screenings / Meetings and Slate Presentations" for both views.
