### ISSUE TITLE
Material list (Movie materials)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#597]
- [x] Update Movie materials page with the table component
- [x] Modification panel
- [x] Add the price, owner and storage location info
![Delivery_Material list - Movie Materials](https://user-images.githubusercontent.com/14964443/60958269-5c965c80-a306-11e9-951b-1fbde8a02a96.jpg)

**Comment by ioaNikas** [comment]
[Related view (no charge materials)](https://projects.invisionapp.com/d/main?origin=v7#/console/18107883/375773862/preview)
[Related view (charge on materials)](https://projects.invisionapp.com/d/main?origin=v7#/console/18107883/375773857/preview)
