### ISSUE TITLE
Plan AM user tests

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5970]
- [x] What do we want to test
- [x] How do we test it
- [x] Plan it over time 
- [x] Prepare the user contact strategy

**Comment by 2amarkina** [comment]
[Testing document](https://docs.google.com/document/d/16iijeGKsaJcQuNQOTuph0cpDAuxekmjOqvklygMbaCU/edit)

**Comment by 2amarkina** [comment]
**After Cannes**

- [ ] Organize interviews with real dates / users
