### ISSUE TITLE
Inventory and clean up of form fields 

### ISSUE THREAD

**Issue by jdrns** [blockframes/blockframes#5973]
_Estimated priority: low to medium_

We've been wanting to implement the 'eye' icon on the password field for a while but this has been blocked because of overrides. 
Ideally we would need to do an inventory on all form fields, see why there are overrides and if possible clear them or at least establish unbendable rules. 

- [x] [Inventory ](https://zpl.io/25mw1xW)
- [x] See what's the problem on icons-left and icons-right
svg to replace.
- [x] See what's possible with password's eye and intercom.
[notion](https://www.notion.so/cascade8/Form-fields-8cfb96a1e41b4f378ac5b7f559b65f43)
- [x] Zeplin clean up

**Comment by stephanie-cascade8** [comment]
For the devs:

- [ ] Replace those svg with better ones here.
This will hopefully enable us to clean up all wrong overrides such as this one I think. 

Here you can see what's wrong for example. (svg is way smaller than 24px)
It creates alignement problems with other fields.
<img width="646" alt="Capture d’écran 2021-09-08 à 17 18 05" src="https://user-images.githubusercontent.com/66258851/132538108-e56fbd9f-5b61-4200-b786-a8e71b8b59fd.png">

- [ ] See if you can take off this override without breaking anything on the other icons fields.
<img width="681" alt="Capture d’écran 2021-09-08 à 17 18 58" src="https://user-images.githubusercontent.com/66258851/132538370-75de118b-7318-441a-886b-c085c5d19ebb.png">

- [ ] check with UI (not sure about the overrides, it has to be tested)

**Comment by stephanie-cascade8** [comment]
After some tests with Remco, we realized that those suspicious overrides on fields are not blocking our initial purposes described [here](https://www.notion.so/cascade8/Form-fields-8cfb96a1e41b4f378ac5b7f559b65f43) at the time.

So let's launch our tasks and go back to the inventory only if needed. 

- [ ] Put the eye icon on the right inside form fields. 
- [ ] Make the mockup-up with intercom icon inside the field for invitation pass (and ask for design review again).
@RemcoSimonides tell me if you want me to create new tasks and put this one in "done"

**Comment by RemcoSimonides** [comment]
Let's create new task for this and you can actually close this one then ;)
