### ISSUE TITLE
Bug with request acceptance

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#5981]
## DASHBOARD / INVITATIONS
- [ ] It is impossible to accept/decline a request from the invitation page. Request keeps reloading indefinitely

https://user-images.githubusercontent.com/55785823/121184096-079e5080-c865-11eb-9754-cd0cd5671a85.mov

- [ ] And the names are "blinking"

**Comment by phpgeekfr** [comment]
seems related to https://github.com/blockframes/blockframes/issues/5901 
![image](https://user-images.githubusercontent.com/1194344/121200785-4b4c8680-c874-11eb-8d53-ce2915c8fee7.png)

**Comment by phpgeekfr** [comment]
This test was performed on production  
https://www.archipelmarket.com/c/o/dashboard/invitations 
concierge+xyzfilms@archieplmarket.com

I logged in with same user on staging, issue was fixed in #5901 already.

closing this one
