### ISSUE TITLE
Improve Avail Search Criteria errors

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5985]
- [x] Error color should also be on the icons of the fields.
- [x] "Media" is also mandatory and should also take the error color state.
- [x] Hint says 'Date must be in the future' even though no date is input
<img width="1405" alt="Capture d’écran 2021-06-02 à 15 17 16" src="https://user-images.githubusercontent.com/66258851/120491287-6a04d600-c3b9-11eb-9866-60b9c372aaf7.png">

**Comment by pldespaigne** [comment]
This is not really related to the avails, it's more related to the re-usable input components we designed.
We should update them to solve the listed issues, but we should keep in mind that those component are probably used elswhere in the app and we must ensure that the style stays consistent

**Comment by RemcoSimonides** [comment]
I think "Error color should also be on the icons of the fields." is the only one that applies to all input fields with an icon, but the other ones are specific for avails criteria search, right?

**Comment by pldespaigne** [comment]
"Media" is a `static-group` component and doesn't handle really well validation of the parent form, so it needs refactoring, which might impact everywhere we use static-groups

**Comment by GrandSchtroumpf** [comment]
The `static-group` will require a huge rework to support the status update. We need to move forward with Archipel Content CRM, therefore I ask PL to postpone the work on this issue for now.

**Comment by yspringfield** [comment]
As it stands, it shows all the various error states. Upon testing, I noticed *all* the fields no longer show an error on reset clicked. Don't know if that's intentional. Just mentioning for what it's worth.
