### ISSUE TITLE
Calendar avails - Safari - can't select rights

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5995]
Browser: Safari 14.1
Page: Marketplace Title View - Avails tab - Calendar view
Url: any title; example: https://staging.archipelcontent.com/c/o/marketplace/title/6p4zCBortWOR49VvuBkP/avails/calendar
user: dev+tevin-dtu@blockframes.io 
Error: `Error: Calendar Invalid Selection: a selection must be included in a marker!`
Sentry: [log](https://sentry.io/organizations/cascade-8/issues/2432865687/?project=1540126&query=is%3Aunresolved)

I can't select a time period with Safari; tested on different titles. World map works but not calendar view
![Kapture 2021-06-09 at 11.19.09.gif](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/3f2d4caf-66ff-4093-9fe5-6ba039cc77cd)

PS: works fine on Brave & Chrome

**Comment by phpgeekfr** [comment]
checking on production before closing
