### ISSUE TITLE
Selection is not cleared when user logs out

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5996]
App: Catalog
Page: `/c/o/marketplace/selection`

#### Steps to reproduce
1. Log in with a AC buyer A
2. Add a right to your selection
3. Logs out 
4. Log in with a AC buyer B with an empty selection
5. Go to Selection: you'll have buyer A selection

#### Fix
Selection should be cleared when a user logs out

**Comment by jeremie74** [comment]
Ok i was able to reproduce the issue.
