### ISSUE TITLE
Avails - Rights not correctly associated to the same title

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5997]
url: https://staging.archipelcontent.com/c/o/marketplace/title/8zFRZOzrBL65GqyLlXei/avails/map
user: dev+rafael-jfu@blockframes.io

When clearing avails form on a title, rights are not associated correctly to the same title in the Selection page.
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/59a0fc4c-683f-4e4b-b70e-d523c46ec284)

#### Step to reproduce
1. Go to world map on a title
2. Add a right
3. Click on "Search for new Terms and Rights" 
4. Add a new right
5. Click on "Add to Selection"
6. You have twice the same title instead of 2 lines in the rights table for the same title

https://user-images.githubusercontent.com/14964443/121332871-8e603580-c918-11eb-811c-693671cacc4e.mp4

**Comment by iPR0D1G1** [comment]
@jackseed, I cannot reproduce this, can you check again and let me know if you still experience this issue ? If not can you close it ? Thx

PS: Please ensure your testing environment has the latest state of develop branch.

**Comment by Jackseed** [comment]
@iPR0D1G1 indeed, it has been corrected since. Thanks for the check, I close it
