### ISSUE TITLE
Sentry

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#600]
Add Sentry to the project

- [x] Add simple SentryModule
- [x] Configure with env & user details
- [ ] Figure out where to store it: maybe in an `analytics` library
- [x] Use in every app + add app info in the event info
- [x] add sentry to firebase functions

**Comment by lsenta** [comment]
- [ ] add sentry to automagically catch all errors
- [ ] configure to store informations about the user if possible

**Comment by lsenta** [comment]
The PR is ready to merge
https://github.com/blockframes/blockframes/pull/614

@GrandSchtroumpf @Jackseed @Mussuranae 

Note that we don't have error logging in current prod either.

**Comment by Jackseed** [comment]
@lsenta we rewieved it with Anastasiia, we would prefer not to have a form on the customer feedback. 
Is it possible to keep the current title, add a subtitle "Our team has been notified, we are taking care of it." and remove the other buttons except for a button to close the dialog & "Powered by Sentry"? 
If it's too big an issue, merge this PR, and I'll create a specific issue.

**Comment by Jackseed** [comment]
Last comment is copied in #1319
