### ISSUE TITLE
Remove alt on invitations icon

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6007]
- [x] Remove alt on invitations icon
![image.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/8fb843f9-3e9a-457d-82d5-147665c10c52)

**Comment by phpgeekfr** [comment]
I guess this issue is already fixed in `hotfix-for-release-3-2`

Please @SamirTouira mark it as done when an issue is solved
