### ISSUE TITLE
Full size for images, docs etc. doesn't work

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6008]
Full size for images, docs etc. doesn't work (maybe Safari only related)
![image](https://user-images.githubusercontent.com/27687382/121191597-687d5700-c86c-11eb-8718-123b0eee6987.png)

**Comment by SamirTouira** [comment]
@RemcoSimonides what about this? Is it already done?

**Comment by RemcoSimonides** [comment]
Yes, it is.

**Comment by Jackseed** [comment]
Still not working.
Tested on Safari 14.1
https://staging.archipelmarket.com/c/o/dashboard/files
dev+winnifred-exb@blockframes.io
