### ISSUE TITLE
Remove "Documentary" from Content Type filter list

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6009]
- [ ] Remove "Documentary" from Format / Content Type filter list & keep it only in Genres
- [ ] Make a migration that must be title by title to find the right content type instead & tag it as genre documentary

**Comment by RemcoSimonides** [comment]
@Jackseed did you check if there is any title with "Documentary" as Content Type?

**Comment by Jackseed** [comment]
@RemcoSimonides there are about hundred titles concerned.. It looks like most of it are from Archipel Content imports so I could manually change it. 
I've contacted Raamis to see what we can do here

**Comment by RemcoSimonides** [comment]
Closing because in #7000 we remove even more content types.
Nevertheless, a solution should still be found with which content type we replace it.
