### ISSUE TITLE
Change Terms of Service and Privacy Policy modal to page

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6018]
- [x] Convert privacy policy and terms of service to a page.
- [x] On the sign-up page, when you open the Privacy Policy or Terms of Service, it should open in a new tab instead of modal.
- [x] Check if everything is still working when you navigate to the Privacy Policy or Terms of Service if you click on it from the footer (no need to open the page in a new tab then, just navigate to it).

This should also fix the back navigation on the page since there is no need for these buttons anymore. See issue #5743

**Comment by Jackseed** [comment]
Could we remove the back button on the new pages? Since we open a new tab they are useless

**Comment by GrandSchtroumpf** [comment]
@Jackseed we want to remove the back button all the time or only when it's opened in a new tab ?

**Comment by Jackseed** [comment]
@GrandSchtroumpf only when it opens a new tab.. is it possible?

**Comment by GrandSchtroumpf** [comment]
Normally yes, but it was supposed to work like that with the current state of the application. We are investigating why it's not working yet...

**Comment by Jackseed** [comment]
Ok thanks, best is to do it on hotfix branch if you find a fix before the release

**Comment by GrandSchtroumpf** [comment]
It's actually working as expected right now.
If you click on a link to a new tab you shouldn't see the back button. But if you open a empty tab then paste the url then you see the back button (as there is an history in the browser).
Handling the use case describe above (empty tab + link) would add a lot of overhead, and seems outside of the scope of this issue to me.

**Comment by Jackseed** [comment]
Right my bad I didn't think it distinguished where you came from but was different on urls. Ok to close 👍
