### ISSUE TITLE
Content : Importing an admin movie template shows error in movie created

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#6025]
Use the attached movie template:
[import-title-template-admin-test-mano.xlsx](https://github.com/blockframes/blockframes/files/6631655/import-title-template-admin-test-mano.xlsx)

1. Login with admin access in Content App and import movie titles
2. Complete the import
3. Look for the movie - Last step summary:

Finding three issues:

1. Production Information 
  (Production Manager role is missing for Steven Jobs)
![image](https://user-images.githubusercontent.com/8731418/121531283-e6339500-ca1b-11eb-8e4c-99e409268fd9.png)

2. Film review shows error
![image](https://user-images.githubusercontent.com/8731418/121531456-09f6db00-ca1c-11eb-8cd6-91f42468d8a1.png)

3. Additional Information - Box Office shows error
![image](https://user-images.githubusercontent.com/8731418/121531512-17ac6080-ca1c-11eb-8ddf-72070c6e6965.png)

**Comment by Jackseed** [comment]
@xmano import doesn't look to work at all with this file; do you still experience same error?

**Comment by xmano** [comment]
Template has been updated in the repo. Will check with the latest one and update the issue.

**Comment by xmano** [comment]
With latest admin template import movie is working fine so we will close this issue since it appears to have been fixed.

![image](https://user-images.githubusercontent.com/8731418/124570093-2e4fa700-de64-11eb-8277-9d8cf14b54b0.png)
