### ISSUE TITLE
Tooltips Improvments

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6037]
- [x] **Describe the types of tooltips** 
- onboarding + walk-through tooltips (for future, to help a first-time user)
- new feature announcement tooltip (for future, to highlight new features)
- **contextual tooltips** (most important for us, already using them. Check out Airtable, Asana, Slack, Wiki for insipiration). contextual tooltips can contain description or supplementary information. design for both should be different as not same aim.
- product engagement tooltips (dynamic tooltips appearing depending on users' actions. need to research where can be used)

For each type of tooltip **provide the following improvements**
- [x] introduce an arrow to show directly which element is concerned
- [x]  check for the font size, maybe make it bigger ? (UI team confirmation)
- [x] check for color and contrast (ongoing, UI team)
- [x] verify if pointer appears or not

**Comment by RemcoSimonides** [comment]
Hee @2amarkina, can you provide images of examples and maybe the links to Asana and such? Would make it easier to determine priority :)

**Comment by 2amarkina** [comment]
Here are the examples of different contextual tooltips improvements, that can be used for big descriptions (i.g. multi-directors on the movie banner) and some action/feature descriptions that can be improved: 

**Airtable**: 
Simple feature description
<img width="679" alt="Снимок экрана 2021-06-14 в 11 15 18" src="https://user-images.githubusercontent.com/55499036/121868994-df4da080-cd01-11eb-87c5-a91ded82bf59.png">

Pro Plan feature description 
<img width="642" alt="Снимок экрана 2021-06-14 в 11 16 47" src="https://user-images.githubusercontent.com/55499036/121869172-0d32e500-cd02-11eb-95e5-470ab834efd8.png">


**Slack**
Arrow + Text hierarchy inside tooltip
<img width="150" alt="Снимок экрана 2021-06-14 в 11 18 01" src="https://user-images.githubusercontent.com/55499036/121869422-52571700-cd02-11eb-920f-ed177ba56c1c.png">

<img width="243" alt="Снимок экрана 2021-06-14 в 11 18 20" src="https://user-images.githubusercontent.com/55499036/121869454-5a16bb80-cd02-11eb-9b8d-08a42cfbcf56.png">


**Wiki** 
Big description / Supplementary information
<img width="605" alt="Снимок экрана 2021-06-14 в 11 12 17" src="https://user-images.githubusercontent.com/55499036/121869537-7155a900-cd02-11eb-8b90-9d21f5c19c3c.png">

**Asana**
Big descriptions / Features / Onboarding
<img width="410" alt="Снимок экрана 2021-06-14 в 11 23 48" src="https://user-images.githubusercontent.com/55499036/121870157-09539280-cd03-11eb-80a8-f9073e9f85d8.png">


**Other Inspirations:** 
Github
<img width="112" alt="Снимок экрана 2021-06-14 в 11 25 13" src="https://user-images.githubusercontent.com/55499036/121870346-3e5fe500-cd03-11eb-9550-092e5b3b1874.png">

Awwwards 
![Uploading Снимок экрана 2021-06-14 в 11.26.00.png…]()

**Comment by RemcoSimonides** [comment]
Let's check out what Intercom can do for us already. See issue #6060

**Comment by jdrns** [comment]
- [ ] List of missing tooltips
- [ ] Inventory of all tooltips (in text inventory sheet)

**Comment by jdrns** [comment]
# Rules and inventory regarding contextual tooltips
[Notion article](https://www.notion.so/cascade8/Tooltips-WIP-0ec6e8fa6c344d919271fb99ffc402cb)about different types of tooltips, where and how they should be used.

**Summary**: 
- Descriptive tooltips 
- Providing tooltips 

# Descriptive tooltips
Some descriptive tooltips are missing, here's the list where:
## Cross App 
### Tables
- [ ]  Filter icon: "Filter columns"
### Invitation page 
- [ ] More icon (three dots): "More" / "Other actions"
### Notification page 
- [ ] More icon (three dots): "More" / "Other actions"
### Toolbar
- [ ] Invitations icon: "Invitations"
- [ ] Notifications icon: "Notifications" *(check for the "Activity Feed" page name. Maybe "Notifications" is more appropriate as Activity had to be used with all the actions on the platform and now they are divided)*.
- [ ] Wishlist icon: “Wishlist”

### Movie page / Credits

- [ ] Profile icon: "Profile"
- [ ] Filmography icon: "Filmography"

### Movie Tunnel Elements
- [ ] Versions / delete icon: "Delete"

 **Complex forms / lists :**
        - edit icon: "edit"
        - delete icon: "delete"

## Archipel Market

### Marketplace / Toolbar
- [ ] Calendar icon: "Calendar"

### Dashboard / Event creation page
- [ ] Send Invitations icon: "Send invitations"

## Archipel Content
### Marketplace / Toolbar
- [ ] Selection icon "Selection"

### Marketplace / Library page
- [ ] Selection icon library page: "Add to Selection"

# Providing tooltips 
In a near future, we would like to implement supplementary information tooltips (as in tooltips that are optimised to show “hidden” information). 
ex: 
<img width="1059" alt="Screenshot 2021-07-05 at 11 30 44" src="https://user-images.githubusercontent.com/79836137/124450262-8adb9500-dd84-11eb-842b-947ac9127335.png">

**Dev review needed for [these wireframes](https://www.figma.com/file/9Nl7mED1iBdbFnaKV8LZI5/Tooltips?node-id=0%3A1):** 
- [ ] Can we have each piece of data back to the line 
Preview: <img width="825" alt="Screenshot 2021-07-05 at 11 36 43" src="https://user-images.githubusercontent.com/79836137/124451017-48668800-dd85-11eb-8217-17f05bf13b2b.png">
- [ ] Could we implement something that if there is supplementary data, and there is not icons, we underline (dash) the word 
Preview: <img width="704" alt="Screenshot 2021-07-05 at 11 39 03" src="https://user-images.githubusercontent.com/79836137/124451373-9b403f80-dd85-11eb-8039-9e585e50ffbd.png">
- [ ] On tablet/mobile, could the interactions be not on hover anymore but on click

**Here's a list of all of them** 
## Cross App
### Feature Film Banner
- [ ] Genres (n+1): show the genres that are hidden
- [ ] Running time (if TV Series, if Documentary): "Per Episode"
- [ ] Countries of Origin (n+1): show countries that are hidden
- [ ] Original Languages (n+1): show languages that are hidden
- [ ] Directors (n+3): show the directors that are hidden

### Film Banner (Movie page)
- [ ] Genres (n+1): show the genres that are hidden
- [ ] Running time (if TV Series, if Documentary): "Per Episode"
- [ ] Countries of Origin (n+1): show countries that are hidden
- [ ] Original Languages (n+1): show languages that are hidden
- [ ] Directors (n+3): show the directors that are hidden

## Archipel Market
### Film Banner (Event page)
- [ ] Genres (n+1): show the genres that are hidden
- [ ] Running time (if TV Series, if Documentary): "Per Episode"
- [ ] Countries of Origin (n+1): show countries that are hidden
- [ ] Original Languages (n+1): show languages that are hidden
- [ ] Directors (n+3): show the directors that are hidden


## Archipel Content

### Selection Page
- [ ] Genres (n+1): show the genres that are hidden
- [ ] Running time (if TV Series, if Documentary): "Per Episode"
- [ ] Countries of Origin (n+1): show countries that are hidden
- [ ] Original Languages (n+1): show languages that are hidden

**Comment by jdrns** [comment]
# Rules and inventory regarding contextual tooltips
[Notion article](https://www.notion.so/cascade8/Tooltips-WIP-0ec6e8fa6c344d919271fb99ffc402cb) about different types of tooltips, where and how they should be used.

**Summary**: 
- Descriptive tooltips 
- Providing tooltips 

[Google Sheet](https://docs.google.com/spreadsheets/d/152BY91BxRHMksMK-t9Xw_WzKAnxLhl0M4jtex9NY32Y/edit?usp=sharing) that inventories all tooltips. 



# Descriptive tooltips
Some descriptive tooltips are missing, they can be found in this [Google Sheet](https://docs.google.com/spreadsheets/d/152BY91BxRHMksMK-t9Xw_WzKAnxLhl0M4jtex9NY32Y/edit?usp=sharing), under nice to have status and descriptive type. 

- [ ] **Business review needed for the text**

# Providing tooltips 
In a near future, we would like to implement supplementary information tooltips (as in tooltips that are optimised to show “hidden” information). 
ex: 
<img width="1059" alt="Screenshot 2021-07-05 at 11 30 44" src="https://user-images.githubusercontent.com/79836137/124450262-8adb9500-dd84-11eb-842b-947ac9127335.png">

**Dev review needed for [these wireframes](https://www.figma.com/file/9Nl7mED1iBdbFnaKV8LZI5/Tooltips?node-id=0%3A1):** 
- [ ] Can we have each piece of data back to the line 
Preview: <img width="825" alt="Screenshot 2021-07-05 at 11 36 43" src="https://user-images.githubusercontent.com/79836137/124451017-48668800-dd85-11eb-8217-17f05bf13b2b.png">
- [ ] Could we implement something that if there is supplementary data, and there is not icons, we underline (dash) the word 
Preview: <img width="704" alt="Screenshot 2021-07-05 at 11 39 03" src="https://user-images.githubusercontent.com/79836137/124451373-9b403f80-dd85-11eb-8039-9e585e50ffbd.png">
- [ ] On tablet/mobile, could the interactions be not on hover anymore but on click

**Comment by jdrns** [comment]
- [ ]  Business review needed for [text of tooltips](https://docs.google.com/spreadsheets/d/152BY91BxRHMksMK-t9Xw_WzKAnxLhl0M4jtex9NY32Y/edit?usp=sharing)
- [ ] Business review needed to check prioritisation

Summary from dev review: 
> * [x]  Can we have each piece of data back to the line

Possible, however would need to create a new component, couldn't be based on current tooltips. If validated, we need to think about extreme cases and how to limit them (e.g. very long lists)

> * [x]  Could we implement something that if there is supplementary data, and there is not icons, we underline (dash) the word

Whole line would need to be turned into a component to have an interaction (hover/click). Currently line is only text. Could be a problem in bunch of spots but could technically work in headers

> * [x]  On tablet/mobile, could the interactions be not on hover anymore but on click

Better give up for now, seems really complex with a lot of work for little outcome

**Comment by jdrns** [comment]
- [ ] Update tooltip inventory with text from text inventory

**Comment by Jackseed** [comment]
business review:
- Marie needs to review text
- we put on hold the new providing tooltip since it's too much work for a few use cases for now; if more comes then we shall use it
- dev issue to create for nice to have descriptive tooltips

**Comment by RemcoSimonides** [comment]
You can tell what exactly needs to be changed here ;) No need to wait for the release.
I see a large excel sheet with about 100 lines. Do they all need to be changed?

**Comment by RemcoSimonides** [comment]
Created dev issue: #6851
