### ISSUE TITLE
Empty Pages

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6038]
Set a list of empty pages and propose an action button for each of them.

**Comment by 2amarkina** [comment]
[Notion article ](https://www.notion.so/cascade8/Empty-pages-WIP-c387088dfeff4738b9d4b89f43e3a84c)

**Comment by 2amarkina** [comment]
**Archipel Market**
- [ ] If no screenings, change the page into empty page with following structure 
![Снимок экрана 2021-07-01 в 15.30.54.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9ac8ba1c-e1ab-49ad-93ee-e8e0a181020b)

Title text: Sorry, there is no screenings at the moment. 
CTA text: Discover Titles
leads to Titles List

**Archipel Content**
- [ ]  Add a CTA on Selection page with empty state 

CTA text: Discover Titles
leads to Titles List

**Comment by 2amarkina** [comment]
**Cross-App**

- [ ] Activity Feed, Invitations, 404 page CTA should be "Back to Homepage". But need to see what's possible technically for the App-access. For example, if user is a Seller, his "Back to Homepage" should lead to Dashboard Homepage.

**Comment by 2amarkina** [comment]
UI check: 

- [ ] check if we can reduce image size

**Comment by Jackseed** [comment]
@RemcoSimonides could you create an issue for devs based on the 2 last comments please? It's about adding a CTA on pages with empty states
(same as already implemented on empty wishlist)

**Comment by RemcoSimonides** [comment]
To do for dev: two clear comments above ☝️ 
- [ ] [https://github.com/blockframes/blockframes/issues/6038#issuecomment-872251987](https://github.com/blockframes/blockframes/issues/6038#issuecomment-872251987)
- [ ] [https://github.com/blockframes/blockframes/issues/6038#issuecomment-872255236](https://github.com/blockframes/blockframes/issues/6038#issuecomment-872255236)

**Comment by Mussuranae** [comment]
Except for the screening list, all pages redirect the user on dashboard, marketplace or movie list depending on the purpose of the page. The 404 page redirects to marketplace homepage. The screening list page can't be completely empty, there is always the banner at the top of the page.

When a user has access to dashboard and marketplace, redirection button will redirect him to dashboard first.

Feature implemented in #6366

**Comment by RemcoSimonides** [comment]
- [ ] Check again screening list page. It should be possible

**Comment by RemcoSimonides** [comment]
Never mind! The screening page is using the list-page component. Changing it would impact more pages. Therefore we chose to update the design instead to reflect the app.
