### ISSUE TITLE
Chips / Tag

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6040]
**_Priority: high_**

- [x] Prepare the rules and notion documentation (with inventory), 
- difference between "chips" and "tag", 
- 2 types of chips: clickable (remove an element) and not clickable,  
- 2 types of tags: clickable (leads to other page) and not clickable. 

N.B. !important, the tag on banner should be "flashy" to be easily detected. 

- [x] Prepare the wireframes with new elements (UX), 
- [x] Prepare the prototypes with new elements (UI). 

N.B. one of the declinations of this issue can be "accepted" and "declined" status. This should be taken into account with [the issue of Success color.](https://github.com/blockframes/blockframes/issues/4835)

**Comment by jdrns** [comment]
[Article notion](https://www.notion.so/cascade8/Chips-WIP-95c6b208fa7d415d982ded1f220c5c3a) in progress
**Need dev review to see what's possible**

[Wireframes](https://www.figma.com/file/qpLBi85x3y0s4fLpJPACOm/Wireframing-Elements?node-id=1546%3A6811) in progress

**Comment by RemcoSimonides** [comment]
## For dev:
- [ ] Create new tag component; [zeplin light](https://zpl.io/bPBEyD6) and [zeplin dark](https://zpl.io/aMwoXj3)
> - [ ]  Colour of text foreground-800
> - [ ]  Border 1px foreground-800
> - [ ]  Border radius 2px
> - [ ]  Padding top bottom 4px, padding left right 8px
> - [ ]  Font uppercase
> - [ ]  Font size 14px
> - [ ]  Font weight 500

- [ ] Remove Ripple effect from chips if they are not deletable (hover can't be removed. Plan B?)
- [ ] Change chip to tag in these spots:
> @jdrns let's make a list together

**Comment by Mussuranae** [comment]
>     * [x]  Remove Ripple and hover effect from chips if they are not deletable (can't remove click animation so keep that one)

This is done in the global theme on the `disableRipple` attribute of the mat-chip. Each time we want to implement a informative mat-chip, we need to put this attribute on it to deactivate the hover effect and the ripple effect.

**Comment by RemcoSimonides** [comment]
> > ```
> > * [x]  Remove Ripple and hover effect from chips if they are not deletable (can't remove click animation so keep that one)
> > ```
> 
> This is done in the global theme on the `disableRipple` attribute of the mat-chip. Each time we want to implement a informative mat-chip, we need to put this attribute on it to deactivate the hover effect and the ripple effect.

Sorry, I don't understand. What is done in the global theme? we still need to add `disableRipple` as an attribute and there is the click animation which can't be removed. So the only thing left I can think of, is that the hover effect is removed in the global theme?

**Comment by Mussuranae** [comment]
Yes, when you want to remove the ripple effect, you add this attribute `disableRipple`. In the global theme, I also remove the hover effect on this attribute. So with one attribute, we can disable the two effects.

**Comment by RemcoSimonides** [comment]
Fancy!
