### ISSUE TITLE
Extract contract-item

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#6041]
Extract the contract table on the terms from the
selection page (`apps\catalog\catalog\src\app\marketplace\title\selection\selection.component.html`)
into a `<contract-item>` component inside the `libs/contracts/lib/contracts/item` folder.

It should look like that:

```html
<contract-item [contract]="contract">
  <contract-price>
    <!-- Can be a form or display -->
  </contract-price>
  <contract-actions>
    <!-- Action buttons for the contract -->
  </contact-actions>
  <ng-template termAction let-term let-index="index">
    <!-- Action buttons to display in the action cell per term -->
  </ng-template>
</contract-item>
```

**Comment by iPR0D1G1** [comment]
Please, can you give me the url to a page wherein this selection component is used?
