### ISSUE TITLE
Add Firebase Authentication data to Big Query

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6050]
Firebase Authentication does have useful data to analyze like
- Date created
- Date last signed in
- Email verified

In users data we have date created, created by, and created from (platform) but we record this data only since recently.
This export can be achieved by creating a scheduled function (pubsub) and write the data to BigQuery once a day for example.
Code inspiration can be found [here](https://github.com/keito5656/firebase-authentication-to-bigquery-export/blob/master/index.ts)

Plan B could be to export Date created manually from Firebase Authentication to BigQuery for the users who already signed up before we started recording this metadata (or to migrate this data into the _meta data so we have this data for older users as well in Firestore)

**Comment by Jackseed** [comment]
@RemcoSimonides I think Plan B looks nice as it's a one-time job and then we can rely on Firestore but then we'll got only the Date created; what about Date last signed in?

**Comment by RemcoSimonides** [comment]
Actually I've already implemented this in #6111. Date last signed in is however not in there but that should be possible to get in another way like Google Analytics or an FirebaseAnalytics event in the code.
