### ISSUE TITLE
User Onboarding

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6058]
### Context
We've delivered features and apps and we're now at a stage where we need to focus on these features and apps to be understood and used (or modified/removed). 

### Objectives
1. Explain
- to new users how app is working (onboarding)
- to first-time feature users how the feature is working (support)
- to recurring users how features are working (guide)

2. Measure
- how it's used
- how much it's used

3. Modify
- write hypothesises 
- test it 
- validate it

**Comment by RemcoSimonides** [comment]
Estimation
UX: 2 days
UI: 2 days
