### ISSUE TITLE
FAQ / Tutorial list

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6061]
Create a User Knowledge base where users may find all our tutorials and be guided through apps & features.

**Comment by RemcoSimonides** [comment]
What features / apps should we create a tutorial for
And then we split this issue up into smaller issues
Once we have enough 'articles' to create a knowledge base, we can start working on it.

**Comment by RemcoSimonides** [comment]
- [ ] FAQ on cookies

**Comment by 2amarkina** [comment]
Some texts that were already done for this part are **[here](https://docs.google.com/document/d/1hNd3Y6Lu5a_gP_EhA3fnGuXXDVMEYOPnVcCipmQBsy0/edit)**

First draft of FAQ for Landing page can be used for inspiration and is **[here ](https://www.figma.com/file/7MLs2S23n3iFMniEfcH3wB/Landing-Page?node-id=83%3A228)**

Other in-app FAQ version can be found **[here](https://www.figma.com/file/hRZnnO6pbHxycbKyeszU61/Wireframes-to-be-validated-pre-testing?node-id=473%3A0)**

**Comment by 2amarkina** [comment]
The creation of Help center / FAQ can contain several steps (to validate with business and dev): 

1. Create a [ knowledge base](https://docs.google.com/spreadsheets/d/1fCUSh7qm7SgrdXKPbkpInUH5TYlPIfU6ep7LhsVNKA8/edit#gid=0) 
2. Create Help desk with only explicit videos by section
3. Introduce a search bar 
4. Add articles about using a particular feature (to see with business team)


The wireframes could be found [here](https://www.figma.com/file/4SghqlahJeV0vibkUswGSx/%5B-Helpdesk-%5D?node-id=0%3A1)
