### ISSUE TITLE
AM feature onboarding

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6062]
Create flows to explain existing AM features: 
- [ ] Screenings
- [ ] Meetings

**Comment by 2amarkina** [comment]
- [ ] Where do we put an explanaition? 

- [ ] How the explanation is presented ? 

- [ ] Tuto-scenarios

**Comment by 2amarkina** [comment]
**1.st point** 
Several Versions of where we could put "Learn how it works" button are proposed [here](https://www.figma.com/file/4SghqlahJeV0vibkUswGSx/%5B-Helpdesk-%5D?node-id=0%3A1). 

**2nd point**
The explanation can take two different forms depending on the place where we put it. 

1. [Use the tab system](https://www.figma.com/file/4SghqlahJeV0vibkUswGSx/Helpdesk?node-id=6%3A167) as for "Learn how it works" in AC searching avails section in a case we put "learn how it works" button is used on the Event Creation first form. 

2. [No tab system](https://www.figma.com/file/4SghqlahJeV0vibkUswGSx/Helpdesk?node-id=30%3A980) in case if the "learn how it works" button is placed on the Event creation main form.

**Comment by 2amarkina** [comment]
To validate with business team: 
- [ ] Do we create tutorials for Buyers? Knowing that for them we'll definitely need a special Helpdesk / FAQ zone 


If everything is ok on the Sellers' side, then 
- [ ] Create videos
