### ISSUE TITLE
Invitation / Notification list - action icons refactoring

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6071]
- [x] Change text below icons to a tooltip (make sure accept / decline buttons are not changed on event-banner - those should still have the text underneath)
- [x] The more button should have the same behaviour on notifications & invitations: opens a menu that leads to another page when click on "more details" item

https://zpl.io/V13dBLB

**Comment by jdrns** [comment]
> * [ ]  Change text below icons to a tooltip (make sure accept / decline buttons are not changed on event-banner - those should still have the text underneath)

For this, you can have a look at [that issue about accept/decline buttons](https://github.com/blockframes/blockframes/issues/5849)
> * [ ]  The more button should have the same behaviour on notifications & invitations: opens a menu that leads to another page when click on "more details" item

On the drop down menu, the two actions would be 1. More details 2. Mark as read
Button should be the same as the invitation page (as in not a big button with padding)

**Comment by SamirTouira** [comment]
The Zeplin link leads me to this: 
![image](https://user-images.githubusercontent.com/52285231/126165081-c80a0ca2-8758-4ed8-ac23-8cde3d602052.png)

**Comment by RemcoSimonides** [comment]
This is the design but actually for your issue it isn't really useful ^^
![image](https://user-images.githubusercontent.com/27687382/126166986-2b6da283-9250-42a7-a6ea-e9966e541634.png)

**Comment by SamirTouira** [comment]
> * [ ]  The more button should have the same behaviour on notifications & invitations: opens a menu that leads to another page when click on "more details" item

I thought that I've understood and made this one but finally I don't understand some stuff, are we agree that inside the red square we have to remove it and only let "More Details"?
![image](https://user-images.githubusercontent.com/52285231/126198004-0825b229-0602-49f2-b32d-0424389430e7.png)

**Comment by RemcoSimonides** [comment]
Invitations should have the same behavior as notifications so I think the notifications page should have the pop-up with the More Details button too.
@jdrns should 'accept-' and 'decline invitation' be removed from the pop-up?

**Comment by jdrns** [comment]
@RemcoSimonides @SamirTouira For the invitation page we should have "more details" that leads to the event page and ze should keep "accept" and "decline" too
