### ISSUE TITLE
FEATURE: Mailosaur Email E2E Test for creating account

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#6076]
Test the form and functionality
![image](https://user-images.githubusercontent.com/8731418/122770071-b8273e00-d2c2-11eb-8969-e58331c257c4.png)

Evaluate if we can automate using Mailosaur.

# What's new

# User scenario
Refer to :

https://github.com/blockframes/blockframes/issues/1263

**Comment by Jackseed** [comment]
@xmano there should be an existing test for this, see #1263 & [Notion doc](https://www.notion.so/cascade8/Cross-app-463e2d64c9184eccb58dcdf48636d201#d091d2b16bed4d22b7467807f0ad47e5)

**Comment by xmano** [comment]
Completed and merged with this PR:
https://github.com/blockframes/blockframes/pull/5797/
