### ISSUE TITLE
[CRM] Contract Form

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#6082]
_main issue #5984_ 

[zeplin](https://app.zeplin.io/project/6075614f83ab0350cbea888a/screen/6081beb10b9148145de61fd6)

![image](https://user-images.githubusercontent.com/5858657/122906263-44347680-d352-11eb-9b97-78ead229f949.png)

- [x] select title
- [x] edit title price
- [x] general right information: use the `avails-filter` component
- [x] use the `languages-form` component for the version form.
- [x] Extract the runs form from the avails page into a reusable component in the avails lib.

Polishing : 
- [x] Use version pipe for the version in the table
- [x] Use `toGroupLabel` pipe for the territories & media.
- [x] Add mat-error for titleId & price fields
- [x] query the offer with the offId, and set the currency prefix based on the offer.currency instead of the income currency (that might not exist).
- [x] onInit, check the route.snapshot.queryParams to see if there is a termId. If yes, open the `bf-table-filter` on the right term.

When updating the contract & income, if value has not change, do not update : 
- [x] Store the contract & income as private properties of the class
- [x] Check if income.price is different from form.value.price, if yes -> update
- [x] Check if contract.titleId is different from form.value.titleId, if yes -> update

**Comment by jeremie74** [comment]
If you want to integrate the bf-table-filter above the bf-form-table -> table of terms ng template we need to modify the bf form table

**Comment by jeremie74** [comment]
https://github.com/blockframes/blockframes/pull/6298
