### ISSUE TITLE
Movie view dashboard: change status, archive, "delete"

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6084]
## Description
Dashboard users will now be able to:
- Switch a movie back to draft
- Archive a movie
- "Delete" a movie (= switch active app movie app access to `false`, **not deleting**)

All these actions will be available through a new action list in the movie banner (dashboard side only). 
Tabs will also be added in the dashboard movie list to filter through movie app status. (Already implemented in `catalog` and `financiers` but not `festival`). 

Also, the movie app status will now be available in the banner as a tag, instead of the original title.

## UI 
[New banner](https://zpl.io/2GPrXqr)
[Confirmation modale](https://zpl.io/bPBZwKD)
[Title list tabs](https://zpl.io/2yDNAvw)

### New action list 
This list is linked with the main CTA button on the top right of the banner. The list and main CTA will change depending on:
- movie app status
- current application

[Here](https://docs.google.com/spreadsheets/d/1e4qahYcBxsYJ4Dpuu_RyL_onlgkMRNts4k5kai-Zu20/edit#gid=0) is a recap of different action list status depending on app & movie app status **please respect it (and ask me if not clear)**. 

If only one action is available, the list is replaced with the action button only
![image](https://user-images.githubusercontent.com/14964443/122907453-72ff1c80-d353-11eb-840d-ab509d3a56fd.png)

The possible actions are:
- [x] Submit Title: redirects to the movie form, summary page, anchored to the bottom (CTA Submit)
- [x] Publish on Marketplace: redirects to the movie form, summary page, anchored to the bottom (CTA Publish)
- [x]  Switch back to Draft: switch movie app status to `draft` (opens a snackbar "Title back to Draft." for 4sec)
- [x] Remove from Marketplace: switch movie app status to `draft` (opens a snackbar "Title removed from Marketplace." for 4sec)
- [x] Marketplace Preview: redirects to the marketplace movie view
- [x] Edit Title: redirects to movie form lobby
- [x] Archive Title: switch movie app status to `archived` (opens a snackbar "Title archived." for 4sec)
- [x]  Restore Title: switch movie app status to `draft` (opens a snackbar "Title restored." for 4sec)
- [x] Delete Title: switch movie app access to `false` (opens a modale to validate first, then a snackbar "Title deleted." for 4sec)

### Title list
- [x] Add the new "Archived" tab that show all movies with status `archived`
- [x] Tab "All" display all Titles related to this org with an app access true for the active app **except `archived` status**

### Delete Title
It opens the validation modale; in this modale the sentence "This Title will still be available on App Name." is here only if the movie is available in another app.

**Comment by phpgeekfr** [comment]
also prevent an archived title to be used as a screening movie

**Comment by Jackseed** [comment]
Btw, important thing to consider when "deleting" a movie from user side, we don't touch connected objects (like notifications, events,...). 
Since this title could be shared with another org or still be available in another app it's too risky / complicated to filter so we'll just keep these related objects

**Comment by Jackseed** [comment]
@phpgeekfr @SamirTouira, re the new tag for the movie app status wait for @jdrns to give you an update on the new component before implementing it. What is in zeplin currently is a work in progress 
![image](https://user-images.githubusercontent.com/14964443/122943588-70aeb980-d377-11eb-9341-74998361b36e.png)

**Comment by phpgeekfr** [comment]
First tasks list:
- [ ] add the "status tag" under title
![image](https://user-images.githubusercontent.com/1194344/122949868-4c091080-d37c-11eb-85c8-46d57e737dce.png)

- [ ] create the actions button component (empty links at first)
![image](https://user-images.githubusercontent.com/1194344/122949942-5cb98680-d37c-11eb-91d0-3032ce2732d8.png)

- [ ] add the status tabs on festival app like it is already on catalog & financiers
![image](https://user-images.githubusercontent.com/1194344/122950201-8e325200-d37c-11eb-94a0-2b581666a7c9.png)

- [ ] add the new "archived" status and update rules, guards, functions (on movie update, delete etc)

- [ ] TDB: delete button => `app.access = false` . Rename button `delete` to `hard delete` on CRM to prevent mistakes ?

- [ ] Check if the "confirm delete" component can be re-used and implement it on the movie-header

**Comment by jdrns** [comment]
> @phpgeekfr @SamirTouira, re the new tag for the movie app status wait for @jdrns to give you an update on the new component before implementing it. What is in zeplin currently is a work in progress
> ![image](https://user-images.githubusercontent.com/14964443/122943588-70aeb980-d377-11eb-9341-74998361b36e.png)

Tag is updated [on zeplin](https://zpl.io/2GPrXqr)
Preview of tag: 
<img width="652" alt="Screenshot 2021-06-23 at 14 32 37" src="https://user-images.githubusercontent.com/79836137/123096901-de1e2100-d42f-11eb-8db8-a5ff3dadb819.png">


As discussed previously with @GrandSchtroumpf, this "tag" should be a mat-chip with a new class: 

- [ ] Colour of text foreground-800
- [ ] Border 1px foreground-800
- [ ] Border radius 2px
- [ ] Padding top bottom 4px, padding left right 8px
- [ ] Font uppercase 
- [ ] Font size 14px 
- [ ] Font weight 500 


Lemme know if you need more info

**Comment by SamirTouira** [comment]
> > @phpgeekfr @SamirTouira, re the new tag for the movie app status wait for @jdrns to give you an update on the new component before implementing it. What is in zeplin currently is a work in progress
> > ![image](https://user-images.githubusercontent.com/14964443/122943588-70aeb980-d377-11eb-9341-74998361b36e.png)
> 
> Tag is updated [on zeplin](https://zpl.io/2GPrXqr)
> Preview of tag:
> <img alt="Screenshot 2021-06-23 at 14 32 37" width="652" src="https://user-images.githubusercontent.com/79836137/123096901-de1e2100-d42f-11eb-8db8-a5ff3dadb819.png">
> 
> As discussed previously with @GrandSchtroumpf, this "tag" should be a mat-chip with a new class:
> 
> * [x]  Colour of text foreground-800
> * [ ]  Border 1px foreground-800
> * [x]  Border radius 2px
> * [x]  Padding top bottom 4px, padding left right 8px
> * [x]  Font uppercase
> * [x]  Font size 14px
> * [x]  Font weight 500
> 
> Lemme know if you need more info

I think this one is done but I'm not sure for the Border 1px foreground-800. Is it the same foreground than Colour of text foreground-800? How to know the difference?

**Comment by jdrns** [comment]
> I think this one is done but I'm not sure for the Border 1px foreground-800. Is it the same foreground than Colour of text foreground-800? How to know the difference?

Not sure what's the name of the variable on your side but yes it should be the same as the colour of text. It should be #1F2A3B in light theme and #C7CFF2 in dark theme

**Comment by phpgeekfr** [comment]
Adding two images that don't use same design as Zeplin, which on should be used ?

![image](https://user-images.githubusercontent.com/1194344/123274094-7fc27280-d503-11eb-8f99-4c60a19374ce.png)

![image](https://user-images.githubusercontent.com/1194344/123274118-84872680-d503-11eb-8893-9b5d0c3031e2.png)

**Comment by SamirTouira** [comment]
If the movie is in Draft, could the user be even redirected to the Marketplace preview title ?
also we don't have the same design between zeplin and what @2amarkina showed us in Slack.

> * [ ]   Switch back to Draft: switch movie app status to `draft` (opens a snackbar "Title back to Draft." for 4sec)
> * [ ]  Remove from Marketplace: switch movie app status to `draft` (opens a snackbar "Title removed from Marketplace." for 4sec)

We don't understand these 2 boxes because both seems doing the same thing, do you have a suggestion for this?

**Comment by 2amarkina** [comment]
As it is constructed at the moment, user can access Marketplace Preview, even if a film has "draft" status (you can do a test on **Archipel Market** with _Rossie Armstrong_ account and pick up _Africa Mia_ title, for example). 

You can go for the design in zeplin. 

- 1st checkbox concerns concerns the case, when a title has a status "Archived". If user clicks on "Restore Title", then title's status becomes "draft" and snackbars says "Title back to Draft". 

- 2nd checkbox concerns the case when a title has a status "Published" and a user wants to removed it from Marketplace View.

**Comment by 2amarkina** [comment]
only one remark: attention to the wording, it should be "Marketplace Preview" for the CTA

**Comment by SamirTouira** [comment]
![image](https://user-images.githubusercontent.com/52285231/123439379-fb8af080-d5d1-11eb-8b2f-6cde9ccbb838.png)

I can confirm that these 2 checkboxes do the same thing. When the title is Accepted, if the user click on "Switch back to Draft", the movie is removed from the Marketplace because the Accepted title is switched to Draft. If we add a "Remove from Marketplace" button when the title is Accepted, the title will back to Draft aswell, so it will be removed from the Marketplace. It does exactly the same thing

**Comment by 2amarkina** [comment]
Technically it does the same thing, but UI is not the same. Here it's really about the usage, wording and the origin status. 

1. The first case (Title back to Draft) is used in this view, when we go from "Archived" to "Draft" status. So, here the Title is not published on the Marketplace. It's in the "trash bin". So the wording of the CTA will be "restore title" and a snackbar saying that now it can be found in "Drafts". 
<img width="801" alt="Снимок экрана 2021-06-25 в 16 51 45" src="https://user-images.githubusercontent.com/55499036/123442887-a51fb100-d5d5-11eb-93cc-58d95e432ffc.png">

2. The second case is when a Title is already published on the Marketplace and a user wants to remove it. Here, the technical sense is that a title is "back to draft", but for user we need to say that "Title removed from Marketplace" as it's the main action s/he wants to accomplish. 
<img width="832" alt="Снимок экрана 2021-06-25 в 16 54 08" src="https://user-images.githubusercontent.com/55499036/123443885-97b6f680-d5d6-11eb-8604-d40b124dfbe9.png">

**Comment by jdrns** [comment]
Yes, here it is https://zpl.io/agmwlOR

**Comment by SamirTouira** [comment]
Should I add the CTA "Preview in Marketplace" also in MF app ? We've got already "Update Funding Status" but I have to know where can I implement "Preview in Marketplace" button if yes

![image](https://user-images.githubusercontent.com/52285231/123789097-11075f80-d8dd-11eb-99e6-2f426a1e7c1e.png)

**Comment by jdrns** [comment]
The drop down had all the different options to see the icons and so but in order to know which action should be depending on status and on app, you should have a look at [this file that recaps actions](https://docs.google.com/spreadsheets/d/1e4qahYcBxsYJ4Dpuu_RyL_onlgkMRNts4k5kai-Zu20/edit#gid=0)

**Comment by Jackseed** [comment]
- [ ] "Switch back to Draft" should be visible only when a Title has a status `submitted`, not `validated` 
- [ ] Remove the effect on hover on the title status tag (same as keywords chips in marketplace movie view)
- [ ] Add a "." on snackbar sentences for "Title restored**.**", "Title back to Draft**.**"

@2amarkina shouldn't we add a validation modale before archiving a title? here it looks too easy for something a user may not understand consequences
and / or a tooltip on the status tag to explain what it means to be archived / draft / ... ?
example here https://staging.archipelmarket.com/c/o/dashboard/title/1eJm06mvagJDNJ2yAlDt/activity
dev+winnifred-exb@blockframes.io

**Comment by Jackseed** [comment]
@phpgeekfr @SamirTouira 
I got a question: "Marketplace Preview" currently doesn't work if the org hasn't access to marketplace. 

I don't know how you made that component but could it be possible that **if** active org doesn't have access to marketplace, "Marketplace Preview" action is not listed and the main CTA becomes the first action in the secondary list?

**Comment by Jackseed** [comment]
I got also some more changes to add:
- [ ] In the title list, it was missing in the mockups but we should have the amount of films in parenthesis aside the tab title, something like this (not the good tab names):
![image](https://user-images.githubusercontent.com/14964443/124493210-a743f580-ddb5-11eb-8bee-ac2656836110.png)

- [ ] "Update Financing Status" doesn't work if the movie isn't published so we need to remove it of the action list when movie is `draft` and `submitted`
I've updated the [action list](https://docs.google.com/spreadsheets/d/1e4qahYcBxsYJ4Dpuu_RyL_onlgkMRNts4k5kai-Zu20/edit#gid=0).
- when draft, "Submit Title" becomes main CTA and is removed from the secondary action list
- when submitted "Edit Title" becomes main CTA and is removed from the secondary action list

- [ ] Depending on the result of my question above, if it's not possible we need to remove "Marketplace Preview" from the main CTA and add it to the secondary action list; if active org doesn't have access to marketplace then "Marketplace Preview" button should be removed from the list. 
To replace "Marketplace Preview" as main CTA I've updated the action list [here](https://docs.google.com/spreadsheets/d/1e4qahYcBxsYJ4Dpuu_RyL_onlgkMRNts4k5kai-Zu20/edit#gid=1539144329)

**Comment by Jackseed** [comment]
(these changes can all wait for 3.3 release)
