### ISSUE TITLE
Dashboard homepage - Loading issue

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6101]
There is an issue with movie stats loading on dashboard homepage, reloading all the time:

![Kapture 2021-06-03 at 11 22 11](https://user-images.githubusercontent.com/14964443/120622028-bce49900-c45e-11eb-8140-379f93b50c4e.gif)

**Comment by RemcoSimonides** [comment]
Couldn't reproduce but made a possible fix in #6102
