### ISSUE TITLE
SEO - Festival - Change Google meta description

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6105]
Meta description has changed on Google, it's currently using Maintenance text..
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/fd3eb73a-33fd-49a5-907c-827578cd6a56)

Should be instead
`The ongoing film market: one tool for your day-to-day promotion and acquisitions.`

[Last PR about this](https://github.com/blockframes/blockframes/pull/4791/files)

**Comment by RemcoSimonides** [comment]
@Jackseed, Checking the metatags of Archipelmarket.com on https://metatags.io/, the metatags are correct.
I think Google didn't recrawl the website (yet).
We can request to recrawl the here [URL Inspection Tool](https://search.google.com/search-console/welcome?action=inspect)
There should be a button saying "Request indexing". 

More info here: https://developers.google.com/search/docs/advanced/crawling/ask-google-to-recrawl

**Comment by Jackseed** [comment]
They ask to change DNS in order to verify ownership, I would prefer @phpgeekfr to do this

**Comment by phpgeekfr** [comment]
on my side I have : 
![image](https://user-images.githubusercontent.com/1194344/123784317-9851d480-d8d7-11eb-904a-8f2b1d36d844.png)

**Comment by phpgeekfr** [comment]
No need to update DNS, I just wen to 

https://search.google.com/u/1/search-console/users?resource_id=sc-domain%3Aarchipelmarket.com

with my cascade8 account and link was performed automatically.

@Jackseed you should have access already, @RemcoSimonides  I added rsimonides@cascade8.com with total access

**Comment by phpgeekfr** [comment]
I asked a new indexation for archipelmarket.

I also set up google search console for other apps and updated  DNS entry (to have a second ownership) .

![image](https://user-images.githubusercontent.com/1194344/123786268-cc2df980-d8d9-11eb-8116-16d9fe6b989d.png)

**Comment by RemcoSimonides** [comment]
Same for me now. Maybe Google crawled it yesterday/today ^^
![image](https://user-images.githubusercontent.com/27687382/123795767-a35f3180-d8e4-11eb-9cc9-aee2d02b6089.png)

**Comment by Jackseed** [comment]
Lgtm as well; magical Bruce!
