### ISSUE TITLE
Verify email of 'old' users

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6111]
Since 2021-05-31 we force users to verify their email address. Older users are however still able to enter our platform without verifying their email.
When running prepareForTesting, new anonymized users are created. Their creation date is the date you run the prepareForTesting and thus are considered new users. However, they don't have their email verified yet because the real user behind this account never did so. Therefore we can't access the app with these 'old but new' users.

My suggestion is to run a migration to verify the emails of these old users. Then we can use these accounts again for development, and I can remove the 'verify email' button from the profile page.

For dev:
- [ ] Remove check for old users in EmailVerifiedGuard
- [ ] Remove 'verify email' from Profile page

@Jackseed ok for you?

**Comment by Jackseed** [comment]
Lgtm 

Though just to be sure: we should keep the verify email button on the CRM in case we have a user blocked that doesn't receive our emails

**Comment by RemcoSimonides** [comment]
👍 yes definitely we keep that button.

**Comment by pldespaigne** [comment]
Just for you to know, verify email through CRM works fine, but the CRM ui is not updated so its always saying "verified email: false" even if the email is indeed verified.

**Comment by Jackseed** [comment]
that definitely looks like an issue 😅

**Comment by RemcoSimonides** [comment]
Ah yea, I forgot about that one. I'll fix it. Thanks 👍

**Comment by phpgeekfr** [comment]
anon-db fix to have all users in PFT with emailVerified  can be found here : https://github.com/blockframes/blockframes/pull/6130

**Comment by RemcoSimonides** [comment]
Export of current status of email verified of users can be found here
https://docs.google.com/spreadsheets/d/1R94eUgTFUS0A78bOMfIypS3ihkTIwJ5u2KInksiwhZw/edit#gid=1285095703

**Comment by Jackseed** [comment]
UI improvements mentioned in #6089 
except from that everything looks good 👍
