### ISSUE TITLE
Illustration - Empty contract list

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6120]
We need a new illustration for that page now that we use different illustrations for empty states.

**Comment by stephanie-cascade8** [comment]
- [ ] Empty illu for activity feed to make as well.
<img width="1437" alt="Capture d’écran 2021-07-13 à 11 57 29" src="https://user-images.githubusercontent.com/66258851/125433270-ebd2fa69-23a2-4b85-80f9-1493b15a4759.png">

**Comment by Jackseed** [comment]
> * [ ]  Empty illu for activity feed to make as well.
> 
> <img alt="Capture d’écran 2021-07-13 à 11 57 29" width="1437" src="https://user-images.githubusercontent.com/66258851/125433270-ebd2fa69-23a2-4b85-80f9-1493b15a4759.png">

This looks like a bug. @jdrns I think you made it already, would you have a link to it?

**Comment by jdrns** [comment]
> > * [ ]   Empty illu for activity feed to make as well.
> > 
> > <img alt="Capture d’écran 2021-07-13 à 11 57 29" width="1437" src="https://user-images.githubusercontent.com/66258851/125433270-ebd2fa69-23a2-4b85-80f9-1493b15a4759.png">
> 
> This looks like a bug. @jdrns I think you made it already, would you have a link to it?

Yes I think it's a bug, heres [the light illustration](https://zpl.io/VkMGKMM) and [the dark one](https://zpl.io/V0rJxPQ)

**Comment by SamirTouira** [comment]
@stephanie-cascade8 @jdrns is the new empty artwork image for contracts available or not yet?

**Comment by Jackseed** [comment]
@stephanie-cascade8 @jdrns in fact we do need an illustration for the empty contract page. The bug was for the activity feed. 
Currently we have this:
![image](https://user-images.githubusercontent.com/14964443/129682679-5f15b254-2f42-4d64-9213-1dcedbbbf266.png)

Ideas for this illustration:
- an empty "paper box" (this object on your desk to store ongoing paperwork), with a fly to show it's empty
- an open empty jacket
... ?

**Comment by jdrns** [comment]
Here's the new illustration for empty contracts, what do you guys think? If validated, I'll make the dark version too 

![empty_contract](https://user-images.githubusercontent.com/79836137/130070640-724ce604-35c5-4ac3-920f-372a14db60f0.png)

**Comment by Jackseed** [comment]
Thanks! Could you try with the pen outside of the box please? Otherwise lgtm :)

**Comment by jdrns** [comment]
Better? :) 
![empty_contract](https://user-images.githubusercontent.com/79836137/130076901-9b122e26-832d-46e2-a75b-03bfffd0227a.png)

**Comment by Jackseed** [comment]
Perfect!

**Comment by jdrns** [comment]
New illustrations ready in [zeplin](https://zpl.io/bz3GOXX) 

Preview:
<img width="900" alt="Screenshot 2021-08-20 at 09 37 55" src="https://user-images.githubusercontent.com/79836137/130197801-a02c0054-3dc5-4e61-8e74-8cfa9eba94e5.png">
