### ISSUE TITLE
Dashboard Title List - Sort Titles by # views

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6121]
User can sort every columns of the title list table except "# Views" while it's interesting to sort by most views
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/f32274b2-b513-4b33-b327-ed7d458918a2)

**Comment by pldespaigne** [comment]
@Jackseed what app is this issue about ?

**Comment by Jackseed** [comment]
It's cross so it should be in sanity team; I've missed adding correct label

**Comment by pldespaigne** [comment]
⚠️ **WARNING** ⚠️

The feature team also need to do some other updates on the Catalog Dashboard Title list (#6195).
So be careful to not conflict !
