### ISSUE TITLE
Event stats duplicates

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6122]
Past screenings had duplicates in their statistics. We have multiple times the same user in the stats. Statistics are exactly the same (same running time) but they appear twice or even 3 times.

We saw this in eventId `25iTfhB5sN8vu1rgObFk` but also `vVba5jJRUHf65odNzt8c`

**Comment by pldespaigne** [comment]
All the data seems to be ok, this is probably a front-end bug.
I'll investigate more.
