### ISSUE TITLE
Banner CTA buttons - from stroked to flat

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6154]
### Description
CTA button UI was changed on the movie banner but it should be changed in every banners. 
@GrandSchtroumpf please confirm but it looks like you have to change from `mat-stroked-button` to `mat-flat-button`

`mat-stroked-button`:
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/4395eec9-8124-4c66-aaa5-189203f6d7ca)

`mat-flat-button`:
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/aaf83d38-62c6-4139-9c6d-1d6626967296)

### Concerned pages
- [x] festival app, org view, "Ask for a meeting" `/c/o/marketplace/organization/orgId/member`
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/8e99c398-bb95-4c84-a27c-29e7e1d548d4)
- [x] festival app, event view, movie banner "More Details" `/c/o/marketplace/event/eventId`
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/dfea70e9-9193-4f54-b316-8977b754e58c)

**Comment by GrandSchtroumpf** [comment]
yep, it's should be just that 👍
