### ISSUE TITLE
Answering invitations reload user names

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6155]
url: `/c/o/marketplace/invitations`

When answering in invitation, it reloads all the names, it shouldn't
![Kapture 2021-06-30 at 19.45.11.gif](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/0be46a97-ade4-4bb2-bafa-97e4a37c9b2a)

**Comment by SamirTouira** [comment]
it looks like a Promise behavior if I'm not wrong. If i am able to fix this I can try
