### ISSUE TITLE
Configuration required for production

### ISSUE THREAD

**Issue by lsenta** [blockframes/blockframes#616]
- [x] We need the following api keys / service account for production:
  - [x] sentry (error reporting)
  - [x] sendgrid (mailing)
  - [x] algolia (full-text search)
  - [x] google analytics (via Firebase)
  - [x] intercom (app messaging)

Note: this ticket is likely to get update with more services (analytics, etc).

These should be managed by the cascade8 organisation with billing enabled!

**Comment by lsenta** [comment]
@Jackseed Sending you this as a reminder for getting production ready.

**Comment by Jackseed** [comment]
@lsenta I move this ticket to icebox so we keep it for next services to include in production

**Comment by Jackseed** [comment]
- [ ] Yandex Metrica

**Comment by GrandSchtroumpf** [comment]
- [ ] Firebase Performance
- [ ] Firebase Event / Audiences / ...

**Comment by Maxstgt** [comment]
added performance for catalog marketplace ref #1243

**Comment by Maxstgt** [comment]
added yandex metrika ref #1245
