### ISSUE TITLE
3 line invitations

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6179]
Since invitations can be quite long, it would be nice to have the text wrap to the next line. This wrapping can only happen once in the line (and thus only take up two lines).
![image.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/71278f67-2c4a-4bda-a7e9-5c5cdde6ae74)

Link to discussion in design issue: #4179

**Comment by Jackseed** [comment]
I think this was still to be confirmed by @GrandSchtroumpf

**Comment by GrandSchtroumpf** [comment]
Yes it's ok, just verify that it works for all type of invitations (event & org)

**Comment by SamirTouira** [comment]
For the format time "1 hour ago" is there an existing pipe or function in blockframes or we should create that?

**Comment by RemcoSimonides** [comment]
@Jackseed points out in [this comment](https://github.com/blockframes/blockframes/issues/6530#issuecomment-911912287) that this issue isn't implement correctly:
the 2 first lines are to be dedicated to the invitation message and the third one to the invitation date. 
Here the first line is for the invitation message and then the second line introduce event date but it shouldn't be alone on 2nd line, it's included in the notification text. 
![image](https://user-images.githubusercontent.com/14964443/131890645-217af123-dc43-4435-a57e-38777674252e.png)

It's not possible to say that the area used is capped at max 2 lines. To quote @GrandSchtroumpf about what is and isn't possible:
We can :
limit to one line with an ellipsis "..." at the end
limit the amount of characters to display
We cannot:
limit a text to have maximum n lines with n > 1
Tricks that do not work to enforce a maximum of lines:
set a max-height: we don't know the font-size, ... it could cut in the middle of a line
set a maximum of characters: we don't know the size of the screen & zoom, 250 characters can take 2 lines on a large screen & 3 in a small screen
Some solutions :
If one line is acceptable, we can force the text to not grow beyond one line.
Leave some space below + maximum of characters so that the text can grow to 3 or 4lines without breaking the UI
Do not put more than 1 growing text in an item of a list.
In some rare cases, the items of a list can have different size. In this case you can have more that 1 growing text in the item.


In my opinion the currently implemented solution with the event date on a separate line is a good one considering what is and isn't possible. Let me know what you think.

Here is what it looks like when the lines can wrap many lines on small/medium device. It looks a bit cramped but at least the whole notification can be read.
<img width="662" alt="Screenshot 2021-09-08 at 16 59 17" src="https://user-images.githubusercontent.com/27687382/132643825-b37423a0-0b8d-4a93-9919-28fac2bd6597.png">

**Comment by Jackseed** [comment]
@RemcoSimonides thanks for the update & sum up. I didn't have in mind the limitations you gave... Then indeed, it looks current solution with the date in a 2nd line is the good one. 
@Poppe-A I'm so sorry but it looks like we'll have to back pedal the changes you worked on... :/

**Comment by RemcoSimonides** [comment]
@Poppe-A improved his idea a bit. What we can do is to have the bold username on one line and then have the rest of the sentence on the next line (in case screen is small). wait for screenshot :) 

his changes aren't merged yet btw
