### ISSUE TITLE
Application Specific movie Behaviors

### ISSUE THREAD

**Issue by ioaNikas** [blockframes/blockframes#618]
- [ ] Update the data model so movieIds are now into applications specific arrays
e.g  organization.movieIds.mediaDelivering

- [x] Update `storeConfig` interface so a movie can be in status `draft` for app mediaDelivering & `submitted` for app "media financiers" for example

**Comment by phpgeekfr** [comment]
Is this feature still wanted ? Or just paused?

**Comment by Jackseed** [comment]
Yes still needed, we discuss it earlier. 
## Description
We'd like to now what application(s) of the org has access to which films. 
E.g. I got movie Jurassik Park accessible to Delivery but not Bigger Boat

**Comment by Jackseed** [comment]
@phpgeekfr I think we added this into the new model, can you confirm and close please?

**Comment by phpgeekfr** [comment]
Nop this is not implemented yet (to my knowledge) .

**Comment by Jackseed** [comment]
This is too big a change before Berlin > added to Icebox

**Comment by phpgeekfr** [comment]
I think `Update the data model so movieIds are now into applications specific arrays` is not needed anymore because we use the movie document to fetch the correct titles. @Jackseed can you confirml ?  If so, we can close this issue

**Comment by phpgeekfr** [comment]
@phpgeekfr If so, clean draw.io

**Comment by Jackseed** [comment]
@phpgeekfr yep we have the appAccess to say what app should display what movie > closed
