### ISSUE TITLE
Catalog Dashboard My Titles (list)

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#6195]
_main issue #6191_

![image](https://user-images.githubusercontent.com/5858657/124449447-c45fd080-dd83-11eb-9495-ef67688305c2.png)

[zeplin](https://app.zeplin.io/project/5fecb41a2e806651584e265c/screen/60d1b3d31bc276143e5cbabb)

**route:** `/c/o/dashboard/title`

The page already exists, but the column are not the same as in the design.

⚠️ ⚠️ ⚠️ 
![image](https://user-images.githubusercontent.com/5858657/124616540-75df2e80-de76-11eb-81ab-990ca8a1747b.png)
![image](https://user-images.githubusercontent.com/5858657/124616587-8099c380-de76-11eb-9797-91c1e6f09b2f.png)
The column should be:
- [x] Title
- [x] Release Year
- [x] Director
- [x] #Views
- [x] #Sales (Total Gross Receipts)
- [x] Status

please read @GrandSchtroumpf 's comment bellow 👇

**Comment by GrandSchtroumpf** [comment]
@iPR0D1G1 some update concerning this page : 
- Sale & total gross receipts should be on the same column.
```html
<ng-template colRef="receipt" let-title="title">
  <ng-container *ngIf="title.id | getIncomesFromTitle | async as incomes">
    {{ incomes.length }} ({{ incomes | sum : 'price' }})
  </ng-container>
</ng-template>
```
- We need to query only approved contract. The query for `getIncomesFromTitle` should be : 
```typescript
@Pipe({ name: 'getIncomesFromTitle' })
export class GetIncomesFromTitlePipe implements PipeTransform {
  constructor(
    private contractService: ContractService,
    private incomeService: IncomeService
  ) {}
  tranform(titleId: string) {
    return this.contractService.valueChanges(ref => ref.where('titleId', '==', titleId).where('status', '==', 'approved')).pipe(
      map(contracts => contracts.map(contract => contract.id)),
      switchMap(contractIds => this.incomeService.valueChanges(contractIds))
    );
  }
}
```
Put this code in `libs\contract\src\lib\income\pipes.ts`

**Comment by pldespaigne** [comment]
I updated the description above with the list of the exact columns we want
>The column should be:
> - Title
> - Release Year
> - Director
> - #Views
> - #Sales (Total Gross Receipts)
> - Status
