### ISSUE TITLE
Catalog Dashboard Contract (view)

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#6197]
_main issue #6191_

![image](https://user-images.githubusercontent.com/5858657/124449970-43ed9f80-dd84-11eb-94d0-e33f836eb1ba.png)

[zeplin](https://app.zeplin.io/project/5fecb41a2e806651584e265c/screen/6036a907615267bde9bd8ed4)

- [x] create a new `catalog-contract-view` components for this page in `apps\catalog\catalog\src\app\dashboard\contract\view\view.component.ts`
- [x] in the dashboard module, mount the component to the route `/c/o/dashboard/contract/<CONTRACT_ID>`
- [x] implement the page as shown in the design, use one `contract-item` (don't do the part about holdbacks)

**Comment by GrandSchtroumpf** [comment]
I think the route should be : `/c/o/dashboard/contract/:offerId/:contractId`, like that we can query the offer & contract in parallel :
```typescript
offer$ = this.route.params.pipe(
  pluck('offerId'),
  switchMap((id: string) => this.offerService.valueChange(id))
);
contract$ = this.route.params.pipe(
  pluck('contractId'),
  switchMap((id: string) => this.contractService.valueChange(id))
);
```
