### ISSUE TITLE
Discussion Catalog Tunnel "Available Materials"

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#6209]
![image](https://user-images.githubusercontent.com/5858657/124491271-5af7b600-ddb3-11eb-898f-cf39089c4390.png)

In order to be able to implement this ☝️ page, we will need more info.

- [ ] The `.xls` template file
- [x] We need to define what are the possible values so that we can choose a data-model _(we can discuss that below)_

**Comment by pldespaigne** [comment]
@Jackseed what do you think ?

**Comment by Jackseed** [comment]
@pldespaigne xls will be purely informative: it's the same as movie budget or financing plan in MF: 
- seller uploads it in dashboard
- buyer can download it from marketplace
So the only change re data model is to add a new file `availableMaterials` on the movie (that can be either xls or pdf)

**Comment by pldespaigne** [comment]
All good then !
