### ISSUE TITLE
Improvement of Hero Section on the Film Page

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6221]
**_Priority: low_**
But seems to be easy to implement, so can be introduced soon.

Users study the **Film pages**. They are quite ok to switch between the tabs. They spend some time on the “Contact Seller Hero section”. This part can be improved. Possible improvements. 

Text hierarchy to introduce : 
_“There is no screening scheduled at the moment.”_ -  title (h3 -> check with UI)
“You can contact the [ Organization Name ] for any questions.” - span.  

[ Organization Name ] should be clickable and lead to this Organization page. Need to follow the upcoming rules of links and buttons. 

Check with UI, maybe this part is already ongoing with [Screening Banner improvements](https://www.figma.com/file/YQ1InKhkvENsID48sPIUhh/Screening-Banner?node-id=28%3A121)

![Hero section CTA.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/94d661c2-4459-46af-87f1-520f686e7f5c)

**Comment by Jackseed** [comment]
Thanks @2amarkina I think you said it all and it's not really part of existing issue. 
It looks now more a UI thing so I remove the UX label.

Re UI: could you update the banner according to what Anastasiia proposed? then it'll go to devs

**Comment by jdrns** [comment]
Ui is ready to go, here is [the mockup](https://zpl.io/25jeKMn) 

(Organisation Name) should be a link taking to the organisation page. The underline shouldn't be done locally, it should come with the implementation of [the issue about links and buttons ](https://github.com/blockframes/blockframes/issues/5770)


Preview:![image](https://user-images.githubusercontent.com/79836137/125769648-0598ec3a-4b76-4586-a748-7f7c65eea503.png)

**Comment by Jackseed** [comment]
Great! @RemcoSimonides should be in your backlog but just to be sure, looks ready for devs ;)

**Comment by RemcoSimonides** [comment]
Done in another issue
