### ISSUE TITLE
Counter component

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6225]
**_Priority: medium_**

For the moment our Maintenance page is saying “it might take about 20min”. But 20min starting from which time? It can be confusing. 

Solution phare :  install the counter to tell the exact time when the maintenance is finished. 

P.S. See if a counter can become a resusable component. 

Counter should takes into account these values: 
- days 
- hours 
- minutes

**Comment by 2amarkina** [comment]
Yes, I think it can go directly to UI. 

Places to introduce counter: 
- Maintenance mode, 
- Event Page.

**Comment by stephanie-cascade8** [comment]
**Some ideas to list here** 

Quick test in CSS only 
([see this codepen ref](https://codepen.io/thdoan/pen/ZOoxyP))

'Vintage' film style countdown
https://user-images.githubusercontent.com/66258851/125307850-b3d5ca00-e330-11eb-839f-e7e778c87438.mov

**Comment by 2amarkina** [comment]
Really beautiful!! But the counter was mostly something like that 
![Снимок экрана 2021-07-19 в 14.51.06.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9b0b3f2b-fe29-42a7-98e0-00a7371bf246)

**Comment by stephanie-cascade8** [comment]
![Screening-header__default](https://user-images.githubusercontent.com/66258851/129244961-7c306082-2d80-441d-a590-f6afca70767a.png)
zeplin [here](https://zpl.io/2pg3wnj) (event page)

About an animation, as discussed with François, we cannot be very creative (it's an angular component). So I guess we only can make numbers replace themselves normally. @GrandSchtroumpf can you confirm we can't have them come slide in from the top and disappear in the bottom for example?

**Comment by stephanie-cascade8** [comment]
Proposition 2 :
@jackseed 
![countdown](https://user-images.githubusercontent.com/66258851/130755848-814be076-962f-424c-be17-088dca4aab24.png)

**Comment by Jackseed** [comment]
I find it way more stylish!

**Comment by Jackseed** [comment]
Alright then we shall wait for the maintenance page to be updated only when there is time and nothing important to be done first

**Comment by RemcoSimonides** [comment]
Created dev issue #6643 #6644
