### ISSUE TITLE
Difference between AM / PM and 16:00 format for the time need to be uniformised

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6226]
**_Priority: medium_**

It's better to uniform the time representation everywhere it's possible. 
For the moment we've got a significant difference in time formats on the Calendar creation view. 
![Снимок экрана 2021-07-06 в 14.08.19.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/2b083d36-b860-4569-bd2e-013346d66ca3)

Check this point with business team.

**Comment by Jackseed** [comment]
I'm not 100% sure but I think it uses the browser time format so you have it with 24h but it's because you're in a European format. 
To be checked with devs

**Comment by 2amarkina** [comment]
**After dev review:** 
We can use standard navigator dates format only in the invitation creation form. If we use it for both places, then we are talking about localisation and this is more difficult and task consuming task. 

For now, we do not use standard navigators' format, but we could go for it for this part only.

**Comment by Jackseed** [comment]
@2amarkina it looks to me we need a UI here to be implemented, what do you think?

**Comment by 2amarkina** [comment]
> @2amarkina it looks to me we need a UI here to be implemented, what do you think?

If we go for a standard that is proposed by default, there is no real need to pass by UI (as icons are not customizable). 
So, if there is something that we could personalize then ok to go for UI, but i'm not sure that's possible (to confirm with devs).

**Comment by Jackseed** [comment]
Ok then I let the dev look at it as it is. @GrandSchtroumpf I think you already made some research about this while the issue was on UX board; could you share some thoughts?

**Comment by cams-goussale** [comment]
To clarify a bit. There are 3 different screens:

- Calendar view
- Modale event form
- Event form

We shall use the time format of the user's browser everywhere.
@RemcoSimonides @Poppe-A what's the estimation of work of this? It looks like could be added to the epic #7134

**Comment by RemcoSimonides** [comment]
No clue how to do it but Francois seems to know so I'd estimate it to about ±1 days.
The #7134 epic is specific about event form and this issue also touches outside of that form. Let's keep it separate. I'll explain you monday the logic behind adding/not adding issues to epics ;)
