### ISSUE TITLE
Clickable label + element

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6227]
**_Priority: low_**
We can see that users click on the whole block, instead of one particular element. 
The most representative part is the **name (label) and avatar (element)**. Currently, only avatar is clickable. But it could be easier for a user to be able to click and on the name and on the avatar.

![Снимок экрана 2021-07-06 в 14.17.57.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/fa630414-c620-4808-b459-49ab896ab044)

- [x] Make an inventory of elements where this pattern repeats.

**Comment by jdrns** [comment]
Validated with @GrandSchtroumpf

We want to have the whole section clickable (name + position + image) to open the drop down menu

- [ ] Replace section by button 
- [ ] Remove button from image

Check with @stephanie-cascade8 when done to make sure that it's all good :)
