### ISSUE TITLE
Closed Sessions and Passed Events

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6233]
**_Priority: high_**

Users tend to accept the invitations without paying attention to the date of event. That leads to the situations when they accept the events that already passed. 

Possible solution: do not show outdated invitations. 
Remark: do not delete them, as needed for the history. 

Idea: introduce a section: missed events? (need to think it over)

**Comment by Jackseed** [comment]
Or implement a new invitation status "outdated"? that would switch the invitation to this automatically at the end of the event (if it were pending)

**Comment by Jackseed** [comment]
Note: after a screening most of the time we receive user emails asking for a dedicated screening because they missed it. I guess a "Ask for a Screener" button on an outdated invitation & as a CTA on a close event would be much needed :)

**Comment by RemcoSimonides** [comment]
Estimation
UX: 6 days
UI: 6 days

**Comment by cams-goussale** [comment]
> Note: after a screening most of the time we receive user emails asking for a dedicated screening because they missed it. I guess a "Ask for a Screener" button on an outdated invitation & as a CTA on a close event would be much needed :)

Considering we've implemented "Ask for a screenING", let's consider this action next to outdated invitations.

**Comment by frenchyrules** [comment]
- [ ] Outdated status must appear on expired notifications, this prevents them from interacting with the notification (can't accept or decline).
- [ ] several screens, start with notifications page and event page (some testing required)

**Comment by frenchyrules** [comment]
Wireframes can be found [here](**url**)

**Comment by frenchyrules** [comment]
Following dev review:

Main solution is to have an "outdated" tag like so, on passed events.
![image](https://user-images.githubusercontent.com/85220905/162205669-83c2af1a-27bc-407a-85d7-9a0ce611fade.png)

**Comment by RemcoSimonides** [comment]
We cannot have a third category on the notification with 'outdated' because the end date on the event can be changed after the invitation has been sent. We would have to fetch the event from the database and check if the current date is past the end date of the event

**Comment by frenchyrules** [comment]
Outdated filter
![image](https://user-images.githubusercontent.com/85220905/162744372-80c3005d-1566-4c6b-96d7-5280cfadd761.png)

Outdated section
![image](https://user-images.githubusercontent.com/85220905/162744526-1441de5b-5d4f-4713-a7bc-f91d626879fb.png)

**Comment by 2amarkina** [comment]
**Last decision:** 
Keep only three main statuses for filtering to simplify the understanding of invitations: Pending, Accepted, Declined.

**Comment by cams-goussale** [comment]
> We cannot have a third category on the notification with 'outdated' because the end date on the event can be changed after the invitation has been sent. We would have to fetch the event from the database and check if the current date is past the end date of the event

@RemcoSimonides I understand we cannot have a 3rd status for `outdated` invitations in the db. But could we still show the `outdated` tag to users with past pending invitations? the objective is to prevent users to answer to an invitation which corresponds to a past event.

@2amarkina @frenchyrules don't you think we should still show `accepted` and `declined`, even for past events? Imo it's only the pending invitations that are concerned by this outdated tag. Otherwise if I follow this logic here:

![image](https://user-images.githubusercontent.com/93206363/165540035-68b7df74-7e52-4220-b733-22f49bbc9ba2.png)

it means that 90% of a user's will be outdated all the time. And therefore the filter you have is kinda useless.

**Comment by 2amarkina** [comment]
Yes, indeed. We need to show an appropriate tag depending if a buyer has answered or not.  

Ideal behavior would be: 
- If an invitation is "pending" and the event has already passed, then show a tag "outdated" and move the invitation into the "outdated" section ; 
- if an invitation is "accepted" and the event has not started or is ongoing, then keep it in "new" or "earlier" section ; 
- if an invitation is "accepted" and the event has already passed, then move an invitation to the "outdated" section with a tag "accepted" ; 
- if an invitation is "declined" and the event has not started or is ongoing, then keep it in "new" or "earlier" section ; 
- if an invitation is "declined" and en event has already passed, then move invitation to the "outdated" section with a tag "declined".

**Comment by frenchyrules** [comment]
Wireframes link [here ](https://www.figma.com/file/EIBNmi63WC0wslJSljPUJ3/%E2%8F%B3-Passed-events-%26-Invitation-answers?node-id=50%3A1703)
