### ISSUE TITLE
Correlation between notifications and Event Page

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6235]
**_Priority: medium / high_**

Users were confused seeing “screening is about to start” and have a CTA disabled. 

Possible solution: Need to precise exact time when a screening starts or say screening starts in XX minutes. 
Think how exactly it can be shown, if user is able to see the exact time when a message was received.

**Comment by Jackseed** [comment]
We raised the question of adding a link to the event within the notification; if not technically possible, mb add another action button?

**Comment by RemcoSimonides** [comment]
For dev: Check if technically possible

**Comment by RemcoSimonides** [comment]
Is the issue of the user resolved by having links in the notification or is it still not the perfect for the solution? It could be possible to add a date in the notification and show a countdown within the notification if that would be even better.

**Comment by Jackseed** [comment]
Imo a link is enough, we already have the counter on the event view so the goal here is to lead the user there. The problem with the counter within the notification is that notification are supposed to be fixed so I think it may bring more uncertainty to the user ("is the time displayed relative to the notification creation time or now?")
cc @2amarkina

**Comment by RemcoSimonides** [comment]
@Jackseed @2amarkina is it ok if the page is opened in a new tab? (or in current tab but the page needs to reload any way)

**Comment by Jackseed** [comment]
Current tab looks better to me as most of the time opening a new tab is linked to an external website. Though idk if we can reload the page while rerouting in the same tab?

**Comment by 2amarkina** [comment]
For me a tab is enough. Users are waiting an action under the "event name". With opening a new tab we answer this need of having an action. If we continue to see that they are still blocked, we could think about something else.

**Comment by RemcoSimonides** [comment]
> Current tab looks better to me as most of the time opening a new tab is linked to an external website. Though idk if we can reload the page while rerouting in the same tab?

It's reloading because I can't use navigation within angular. With navigating within Angular, the header and such will stay and only the need components are loaded. But I have to use `href` meaning it's really like entering the url in the browser and hit enter so the full page needs to load again.

**Comment by Jackseed** [comment]
Ok let's go for new tab then nvm ;)
