### ISSUE TITLE
Vertical scroll

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6238]
**_Priority: medium_**

Users still use the vertical scroll to navigate on the page (they try to click on the scroll and move it). Our current scroll is pretty thin to to that. 

We need to introduce a "fatter" vertical scrollbar. 

Need to verify if it doesn't impact the horizontal scrollbar (filters / tables). 

Can go directly to UI. 

You can see an example of this behavior **[here](https://drive.google.com/drive/folders/1CgG20NzpPUtq_dYGfIcZMl-pGo-UNLe0?ths=true)**

**Comment by jdrns** [comment]
- [ ] Test with a dev to see if it doesn't affect horizontal scroll and if it doesn't create spaces

**Comment by RemcoSimonides** [comment]
Do together with dev
- [ ] Make appointment with dev for ±30 minutes
