### ISSUE TITLE
Update Archipel Market Landing page

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6240]
[Zeplin](https://app.zeplin.io/project/5de7944cf85691577aacfbb7/screen/60c9c2ef572ec78d4d00e600)

![image](https://user-images.githubusercontent.com/27687382/129704914-d54ecdbf-3c5f-4bf2-b297-0119888e211d.png)

Link to original design issue: #4127

**Comment by Jackseed** [comment]
@maltmayer should we have Security as a benefit?

**Comment by RemcoSimonides** [comment]
1:
![image](https://user-images.githubusercontent.com/27687382/129745090-c2c44d54-92e1-4178-b01d-d9216b67a84e.png)
- [ ] Update image
- [ ] Add "One tool for your year-round 
promotion & acquisitions" text

2;
![image](https://user-images.githubusercontent.com/27687382/129745479-fc2aea43-38f2-4cad-9dfc-c40cfce14122.png)
- [ ] Add this new banner

3:
![image](https://user-images.githubusercontent.com/27687382/129745620-6416d00b-43c4-431f-91fe-5a2eaf4760ae.png)
- [ ] Add description underneath title
- [ ] Sales Agent tab
- [ ] Buyer tab (I'll ask Stephanie to update this)

4:
![image](https://user-images.githubusercontent.com/27687382/129746964-9de854c9-251e-439e-b5ca-0a8797784bcf.png)

5:
![image](https://user-images.githubusercontent.com/27687382/129747062-4b9e2897-fcc3-4c05-b019-dc5fd5456212.png)
Remco: Ask Stephanie for updated text for reviews

6:
![image](https://user-images.githubusercontent.com/27687382/129747225-2add309b-0072-4805-a923-20b23542562d.png)
- [ ]

**Comment by RemcoSimonides** [comment]
Created new issue for subscribe to newsletter functionality #6640
