### ISSUE TITLE
Images are not displayed on some devices / browsers

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#6253]
Some of the images are not displayed well on iPhone and/or Safari browsers.

Expectations 
- [x] All images should be displayed
- [x] Landing page images need to work all the time.
- [x] update `isSafari()` method to check for iOS user-agent

**Comment by phpgeekfr** [comment]
George on IOS:

![image](https://user-images.githubusercontent.com/1194344/124902624-65989200-dfe3-11eb-9c6e-2b49199549d8.png)

**Comment by RemcoSimonides** [comment]
This issue has been solved by image optimization issue
