### ISSUE TITLE
E2E (enhancement) : Add an invite to user with existing request from user to Org

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#6257]
This is to cover the scenario mentioned in this issue:
https://github.com/blockframes/blockframes/issues/6255

![image](https://user-images.githubusercontent.com/8731418/124907320-a0abbd00-e005-11eb-898f-90e2eeaf908a.png)

**Comment by phpgeekfr** [comment]
I see two scenarios:
- [ ] If existing request from same user that you wan to invite => Auto validate request (see #6255)
- [ ] if existing request from others users => should not crash
