### ISSUE TITLE
Inventory of tag component

### ISSUE THREAD

**Issue by jdrns** [blockframes/blockframes#6259]
List of where the new tag component should be implemented

### Dashboard 
**My Titles** 
- [x] Tables / Title Status (draft/submitted/archived/etc)
<img width="1440" alt="Screenshot 2021-08-17 at 16 12 09" src="https://user-images.githubusercontent.com/79836137/129741862-05ac1ab4-4850-4095-9c0a-0bd521383597.png">

**Titles page**
- [x] Header Title Status
<img width="1440" alt="Screenshot 2021-08-17 at 16 10 39" src="https://user-images.githubusercontent.com/79836137/129741545-18463b5d-b2b0-4b4d-b69e-bbac5b7bd85a.png">

 
### Dashboard 
**Dashboard page**
- [ ] Ongoing deals Tables / Offers Status (new/in negotiations/etc)
- [ ] Ongoing deals Tables / Approval (pending/declined/approved) 
<img width="913" alt="Screenshot 2021-08-17 at 16 09 47" src="https://user-images.githubusercontent.com/79836137/129741405-1bdba871-dc71-482f-8e76-76565c8f6f2e.png">

https://zpl.io/bAN9Wxn

**Contracts**
- [ ] Ongoing deals Tables / Offers Status (new/in negotiations/etc)
- [ ] Ongoing deals Tables / Approval (pending/declined/approved) 
<img width="1061" alt="Screenshot 2021-08-18 at 12 12 33" src="https://user-images.githubusercontent.com/79836137/129880940-8a7c719e-642b-41fa-b59f-8f07f523c891.png">

**Contract page**
- [ ] Header Contract Offer Status
<img width="1055" alt="Screenshot 2021-08-18 at 13 19 07" src="https://user-images.githubusercontent.com/79836137/129889333-2394ab9e-50d4-4a2b-a9cb-dbb073c34426.png">

### Marketplace 
**Offers and Deals** 
- [ ] Tables / Offer Status (new/in negotiations/etc)
<img width="882" alt="Screenshot 2021-08-18 at 13 28 12" src="https://user-images.githubusercontent.com/79836137/129890348-ba50c488-c9f2-4e40-be7e-22f91ef0e716.png">

**Contract page**
- [ ] Header Contract Offer Status
<img width="1054" alt="Screenshot 2021-08-18 at 13 35 40" src="https://user-images.githubusercontent.com/79836137/129891280-52cb6e1c-1bd2-4734-9c0e-c537ba172e8b.png">

## CRM
**Movie page with all contracts**
- [ ] Tables / Offer Status (new/in negotiations/etc)

**All contracts page** 
- [ ] Tables / Offer Status (new/in negotiations/etc)

**Contract page**
- [ ] Titles in package / Sellers approval (pending/declined/approved) 

## Add css property
- [ ] Add line-height: 16px

**Comment by cams-goussale** [comment]
It seems this issue is done or at least can be closed
