### ISSUE TITLE
Quick access buttons change to surfaces(AM / Dashboard)

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6266]
- [x] Prepare the CTAs on the Dashboard homepage. 
Cover only the case when a Seller has titles already uploaded.

**Comment by Jackseed** [comment]
The whole surface should be clickable, best to update this component

**Comment by 2amarkina** [comment]
quick upd. with the elements to show:
<img width="476" alt="Снимок экрана 2021-11-22 в 16 24 26" src="https://user-images.githubusercontent.com/55499036/142888065-dd48d5c9-e90c-4485-ba08-6aa412d4b893.png">

**Comment by stephanie-cascade8** [comment]
Clickable surfaces :
elevation: 1
---------
on hover : 
elevation 2
transition 2px top - 2px left.

To check with François in next UI review for the hover effect but this can go to dev already.

[zeplin](https://zpl.io/VqMrwx7)

![dashboard_quick-actions](https://user-images.githubusercontent.com/66258851/144593700-9cbb0bda-ba28-4f8d-bb95-0c4d874d581b.png)

**Comment by stephanie-cascade8** [comment]
The hover effect and elevation system needs to be worked in the issue that was made for dark theme cards and surfaces colors improvement. (can't find this issue)

**Comment by 2amarkina** [comment]
Just to check up, do we agree that this change :point_up_2: will also apply to the usual empty states? 
<img width="318" alt="Снимок экрана 2021-12-03 в 12 19 50" src="https://user-images.githubusercontent.com/55499036/144594171-6be5bd1e-b6ea-4117-ad7b-d03227cab910.png"> 

+ add cursor pointer on hover
![153265-200](https://user-images.githubusercontent.com/55499036/144594566-0831170f-cc7f-47d0-b61e-b13ab5773ac5.png)

**Comment by stephanie-cascade8** [comment]
Oh yes!  but I have to make the mockups (can't go to dev directly because
of surface sizes, paddings...) I would need an issue for the next sprint :)

**Comment by 2amarkina** [comment]
[Related issue is created here ](https://app.zenhub.com/workspaces/design---ui-60ab5f96c64ec50014c46754/issues/blockframes/blockframes/7323)

**Comment by stephanie-cascade8** [comment]
Mockups [here](https://zpl.io/VYzmylM) 
To me it's ready for dev

**Comment by cams-goussale** [comment]
These screens might be changed a bit with Sellers' analytics project. We probably will use the space of Dashboard to display analytics, right @2amarkina ? I think the screens where there is no title are still good to go. But the screen showing user's activity might need to be reviewed.

**Comment by 2amarkina** [comment]
Yes, following these issues [Title oriented analysis#7517 ](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/7517) and [Buyers oriented analysis #7518](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/7518) the structure of the page with analytics will be changed. 

The following empty states remain as on mock-ups: 
1. [Empty Dashboard when a Seller hasn't uploaded any title yet ](https://app.zeplin.io/project/5f3100d317a0041be2ad99c4/screen/61b78b782d1f024a2b7870da)
<img width="939" alt="Снимок экрана 2022-01-25 в 09 49 34" src="https://user-images.githubusercontent.com/55499036/150943325-f5aa6386-0c8f-485d-99eb-eb51ea568026.png">

2. [Empty Dashboard when a Seller has already uploaded some titles, but hasn't published them yet ](https://app.zeplin.io/project/5f3100d317a0041be2ad99c4/screen/61b78bc37d5f1f3aa83ba4b6)
<img width="937" alt="Снимок экрана 2022-01-25 в 09 50 51" src="https://user-images.githubusercontent.com/55499036/150943539-630ec434-95cd-40a7-b88f-9b660d4abe91.png">

**Comment by 2amarkina** [comment]
**The main difference is the reworked and clickable surfaces:** 
- Manage Drafts 
- Add one Title
- Import Titles in bulk
