### ISSUE TITLE
Language filter 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6269]
Put back the language filter on AC. 

The problem is that is the version is not chosen, then a filter doesn't work.
A solution for that could be to introduce the same filter we have for Market and have the "Original, Dubbings, Subtitles" pre-chosen. 

Maybe do the same for AM (selected cases).

**Comment by Jackseed** [comment]
@RemcoSimonides it wasn't written within the issue but we'd like to have the "Original, Dubbings, Subtitles, cc" pre-chosen for festival app as well. Is it already done cause it's the same component or should I open another issue?

**Comment by RemcoSimonides** [comment]
> @RemcoSimonides it wasn't written within the issue but we'd like to have the "Original, Dubbings, Subtitles, cc" pre-chosen for festival app as well. Is it already done cause it's the same component or should I open another issue?

It's done ;) it was sort-of mentioned in the issue

**Comment by RemcoSimonides** [comment]
Same component too indeed
