### ISSUE TITLE
Change refresh filters icon

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6303]
Change the clear all filters icon with this [svg icon](https://app.zeplin.io/styleguide/60704bdaf4957954498f2f0e/components?coid=60f044716d3719ac8abf2553)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/f112bbb1-6c3e-4142-8a49-53d10e32272c)

This icon is on all the title list page & in the movie view, `catalog` app, on the avails tab

**Comment by RemcoSimonides** [comment]
![image](https://user-images.githubusercontent.com/27687382/125940968-6e8896de-507b-4a11-8182-8683a39a9b3a.png)

**Comment by RemcoSimonides** [comment]
Let's wait with improving this until this new design is approved
https://github.com/blockframes/blockframes/issues/5559
