### ISSUE TITLE
[CATALOG] Add holdback on selection page

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#6308]
- [ ] Update the datamodel of `Bucket` with a list of holdbacks: 
```typescript
export interface BucketContract {
  ...,
  holdbacks: AvailsFilter[];
}
```
- [ ] Update the `createBucketContractControl` function accordingly :
```typescript
function createBucketContractControl(params: Partial<BucketContract> = {}) {
  const contract = createBucketContract(params);
  return {
    ...
    // Normally holdback don't have exclusivity, so we need to set it to false to be able to use the AvailasForm
    holdbacks: FormList.factory(contract.holdbacks, holdback => new AvailsForm({ ...holdback, exclusivity: false });
  }
}
```

[Zeplin](https://app.zeplin.io/project/5fecb41a2e806651584e265c/screen/6036abd740711205efd61b12)
![image](https://user-images.githubusercontent.com/8143464/125811620-10144e1c-d4cc-4dc6-8d79-90e7794b60ec.png)
- [x] Add a button in the footer of the `content-item` of the selection page.
- [ ] When clicking on it, open a dialog with the component `HoldbackFormComponent` describe below 

[Zeplin](https://app.zeplin.io/project/5fecb41a2e806651584e265c/screen/607065d2d2fafd55953feeb7)
![image](https://user-images.githubusercontent.com/8143464/125812241-5c3ae6ec-2fb4-49eb-b5ae-cf50c381f3af.png)
- [x] Create a component `HoldbackFormComponent` in `libs\contract\src\lib\contract\holdback\form` *folder*
- [x] Use the `bf-form-table` to wrap the form
> Note: It's not "add other files" but "add other holdbacks"

**Comment by pldespaigne** [comment]
This have been done, the code is already on develop
