### ISSUE TITLE
Film Page - Dashboard

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6322]
See if move Marketplace Activity tab on the last position till provide the full info about Buyer.
(_following the Sellers' insights this information is less important then in the "Main" tab as provides only general values. Would be more interesting to have direct info about Buyers_)

**Comment by Jackseed** [comment]
Ok let's go for moving the "Marketplace activity" tab on last position within dashboard movie view, we'll remove it completely once #7031 is done

**Comment by 2amarkina** [comment]
One possibly blocking point: 
As being cross-app and not app specific, we risk to have this, that is not OK for UX.  
![Снимок экрана 2021-12-03 в 17.15.02.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9bc97c61-44d6-462f-93e3-1fb321ee20f2)

So, if it's the case let's wait for removing the Marketplace Activity completely and not changing the present structure.

**Comment by 2amarkina** [comment]
Confirmed with dev team that the Marketplace will be "in the middle" for Content and Financiers, so i guess it would be better to wait for separate page that should appear with [Sellers statistics](https://github.com/blockframes/blockframes/issues/7031).

**Comment by Jackseed** [comment]
Ok I close this issue in the meantime then
