### ISSUE TITLE
AM - Invitations

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6323]
Check if possible to add information about the territory and activity sector to the invitations. 

(from Sellers Insights: if territory is sold, Seller can refuse an invitation to a screening).

**Comment by RemcoSimonides** [comment]
UX: 1 day
UI: .5 day

**Comment by cams-goussale** [comment]
I think it makes more sense to use the Buyer preferences than the Territory of the organization. And if Buyer hasn't filled his buyer preferences, we shall not show any territory.

As for the org activity, it adds too much information, makes the text very long.
