### ISSUE TITLE
Broken org invitation

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6324]
Find out how this could have happened
"the guy was invited to the org + he signed up but his invitation didn't work it seems. the invitation is still pending and the dude is not associated with any org"

![Capture d’écran 2021-07-19 à 11.19.06.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/68e1b114-5437-4580-bd2d-bd0b43f7575e)

![Capture d’écran 2021-07-19 à 11.19.55.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/e9859851-03a8-4733-820a-347beceab4a9)

**Comment by phpgeekfr** [comment]
Can this be reproduced or was it a one time issue ?

**Comment by RemcoSimonides** [comment]
It's something Marie noticed when looking at the data. It can be caused a long time ago already. So we don't know how to reproduce this (yet). Maybe you know whether this can be caused due to an old migration or something?

**Comment by RemcoSimonides** [comment]
Actually this user is already created when an invitation is sent to an email. I guess it is the expected behaviour since such thing doesn't happen accidently ^^
@phpgeekfr can you confirm that this is the expected behavior?
Don't we have a lot of unused user accounts because of that?

**Comment by phpgeekfr** [comment]
Yes, when entering `getOrInviteUserByMail` method, invited users that does not already exists on the plateform will be created. So yeah, a lot of accounts are unused because of that. We should maybe delete users that have been created like a month or two ago and never connected

**Comment by RemcoSimonides** [comment]
Does that break the invitation though? If they try to connect after the user has been removed? Or should they simply be invited again?

**Comment by phpgeekfr** [comment]
Yes, if we delete the newly created users, it will break the invitations. But if we remove them cleanly, they should be able to create a account by themself or to be invited again.

**Comment by phpgeekfr** [comment]
I'm currently working on a way to clean some unused DB documents, I will be able to tell how much work is needed.

**Comment by RemcoSimonides** [comment]
@Jackseed we need to check with Business team if removing the users is ok. Or should we keep their emails somewhere for marketing purposes for example?

Also, it might be nice to automatically remove users and invitations after a month and to display this side note somewhere on the invite organisation member page.

Currently we have 1100 out of 3995 users that don't have an orgId. 1099 of which have been created more than a month ago

**Comment by phpgeekfr** [comment]
We already have have a script that delete `joinOrganization` invitations older than 14 days. But this does not remove users yet.
The thing  we do on users is to check if uid in auth exists in DB. If not, user is deleted. We also check if user.orgId match an existing org, if not, we remove the user.orgId attribute, but not the whole user.

This cleaning is performed at each release, not on a daily basis for example.

**Comment by Jackseed** [comment]
We shall discuss that and confirm with @maltmayer when she comes back next week but I think it's a good thing to delete unused users after a month or 2 since imo it will create problems if a non-activated user finally tries to sign up and learn that email is already used.

**Comment by maltmayer** [comment]
I like the idea to delete a user if his first invitation is not activated after a few months.I'd say 2 or 3 is okay just to be sure.


Also, to come back to the initial problem, this behavior is not the "usual behavior" as if you look closely, the user is not just a "dead email" that was invited but did not activate the account: he filled in his first and last name, which means that he did activate his account but for some reason, the "join organization" invitation was not accepted so he staid stuck in the middle.... with an account attached to no organization and an "join organization" invitation still pending.

**Comment by RemcoSimonides** [comment]
The user signed up and requested to join an organisation. That will result in the mentioned results with user not having an orgId but do have a pending invitation. It could be that the organisation invited the user to join the organisation as well; then there are 2 pending invitations.
