### ISSUE TITLE
[CATALOG] Facilitate no price offer add hint - if no price entered should be "0" by default

### ISSUE THREAD

**Issue by jeremie74** [blockframes/blockframes#6325]

**Comment by jeremie74** [comment]
![image](https://user-images.githubusercontent.com/50317241/126185971-e24bae81-92e6-44a5-8375-dfc7a20f6df3.png)

**Comment by jeremie74** [comment]
Impossible to solve issue because of holdbacks modifications of the friday 16th who create others problems, i am not able to go the page with the price field to update. We try to create a fallback for holdbacks with François but it doesn't solve the bug.

**Comment by pldespaigne** [comment]
just do this on your side, it should let you access the page
```TypeScript
formatFromFirestore(bucket): Bucket {
    if (!bucket) return;
    for (const contract of bucket.contracts) {
      for (const term of contract.terms || []) {
        term.duration = convertDuration(term.duration);
      }
      if (!contract.holdbacks) contract.holdbacks = [];
      for (const holdback of contract.holdbacks) {
        holdback.duration = convertDuration(holdback.duration);
      }
    }
    return bucket;
  }
```

**Comment by jeremie74** [comment]
Ok PL it solve the problem thanks.
