### ISSUE TITLE
Feature Film - Homepage Banner

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6327]
The order of the elements should be respected [(see Homepage Design Rules)](https://www.notion.so/cascade8/Homepage-Design-Rules-10a708180e5542a6a1ab772e0873035f)

1. Directors 
2. International Title 
3. Film Details 
4. Main CTA
5. Secondary CTAs (add to wishlist, watch trailer, etc.)

The idea of the re-working was to make this component less "heavy". Check if UI work is needed to provide exact height for the element, following the reduction of the content inside.

**Comment by stephanie-cascade8** [comment]
This was staying in the pipe because some of the rules described needed to be applied in the new carousel structure #4731
