### ISSUE TITLE
Limit the org name characters

### ISSUE THREAD

**Issue by SamirTouira** [blockframes/blockframes#6337]
What do you think about this? 

The org name characters should be limited to avoid this:

![image](https://user-images.githubusercontent.com/52285231/126378039-92e4d64d-3a0b-43f0-9584-5f6af4081aa8.png)

same here:

![image](https://user-images.githubusercontent.com/52285231/126380963-241851e3-5952-48f8-84ad-ce2cf9292026.png)

**Comment by Jackseed** [comment]
We need a front solution here, we won't limit the actual org name but on display we should find a way not to break the UI

**Comment by stephanie-cascade8** [comment]
See with François, the bug actually doesn't exist. It's because the test was made without spaces btw words.
<img width="1423" alt="Capture d’écran 2021-11-04 à 15 50 38" src="https://user-images.githubusercontent.com/66258851/140336272-52fa9957-6bf9-4985-a494-e6f3af06efc8.png">

**Comment by Jackseed** [comment]
Good to know, I close it then
