### ISSUE TITLE
New admin email: org creation sum-up

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6371]
Add a sum-up email every Friday morning 9AM CET:
- this email will be a sum up of all the org creation of the week + a reminder of still pending orgs
- data from 'this week' shall go from previous Friday 9:00AM CET to this Friday 9:00AM 
- one email per app, sending by support@[appname].com
- email title: X organizations were created this week, Y are still pending
- email text:

"
**Org created this week**
_Pending_
Org name(CRM link)
Org name (CRM link)
...

_Accepted_
Org name(CRM link)
Org name (CRM link)
...

**Org still pending**
Org name(CRM link)
Org name (CRM link)
...
"

**Comment by RemcoSimonides** [comment]
There is probably a possibility for this using data studio reports.

**Comment by Jackseed** [comment]
Would be a really good issue to test it then cause it would be super useful to have other types of weekly reports like user connexions, event created, offer,...

**Comment by RemcoSimonides** [comment]
Easy 😁
![image](https://user-images.githubusercontent.com/27687382/126763738-9d26dfb8-e5d1-44ed-a228-b85fceb130de.png)
