### ISSUE TITLE
Marketplace sidenav - close it when already on the page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6372]
When a user is already on a page and click on the same link in the sidenav (eg title list and clicks on "Titles"), it doesn't do a thing. Instead it should close the sidenav.

**Comment by GrandSchtroumpf** [comment]
There is no clean way of handling that. The issue might come from the fact that on Archipel Market the links are not highlighted. If the link were highlighted, clicking on it wouldn't make much sense. This is a bug that @Poppe-A is going to solve.

**Comment by Poppe-A** [comment]
Some menu links were not hilighted. This is fixed. According to Anastasiia this solution will be good enough, no need to implement more logic to close the menu.

**Comment by Jackseed** [comment]
alright, @Poppe-A can you close this issue with the related PR then?

**Comment by Poppe-A** [comment]
#6590
