### ISSUE TITLE
Catalog - org not listed in the sellers 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6373]
Loco films is not listed in catalog though it has around 15 movies accepted to the app. How come?
[Org view page](https://archipelcontent.com/c/o/marketplace/organization/IWWJ6eLjnYqGd0odKize/title)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/a6981a00-31ff-46ac-9f51-83cd604ccc7b)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/6e4d52f7-2b79-45ae-ba4d-62257c512c00)

**Comment by RemcoSimonides** [comment]
This is because the organization list page is only showing orgs that have appAccess to marketplace - not dashboard... Fixed that.
