### ISSUE TITLE
Archipel Content Avails "Learn how it works" videos missing

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#6375]
## ARCHIPEL CONTENT MARKETPLACE > FILM PAGE > AVAILS
- [x] "Learn how it works" videos are missing

https://user-images.githubusercontent.com/55785823/126766099-41834424-b368-42af-a777-77e3ccb2c42a.mov

**Comment by iPR0D1G1** [comment]
I believe this is a false positive as during tests, the videos were available.
