### ISSUE TITLE
Review Catalog

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6383]
Tested on Chrome 91.0.4472.164, 
MacOS 

_P.S. Wanted to test on Safari, but could not connect, as had a message that account doesn't exist._ 

### Marketplace

**Homepage**
- [ ] #6404

**Film Page**
- [x] When clicking on "Search & Buy Rights" for the first time, the anchor stops in the middle on the page. 
![avails page anchor.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1f237b40-cbd5-4f4f-82f1-50ab9b575555)

Then went to "Main" tab and re-clicked on "Search & Buy Rights", everything worked well. 
![search and buy 2.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/2675b770-be4e-4ca1-b36e-45a26e5e5b1d)

**Library Page + Selection Page**
- [x] #6387
Filled in the avails filter, added a title to selection, went to selection page and clicked on arrow back via browser. Library page is empty, avails filter is pre-filled with exactly the same information, but it is not shown with color and the filter data is not taken into account. 
![library avails.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/da99c919-632c-4977-836f-23507c29d539)

**Selection Page**
- [x] Price hint text update _Leave this field empty to request an asking price._
- [x] Text to update "Delete all Rights for this Title" 

**Holdbacks section**
- [ ] To verify with business team, but normally there is no versions in holdbacks _(verification in progress)_
- [ ]  When try to add the Holdbacks, it doesn't work from the 1st time. 
![holdbacks.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/d46584f6-d521-4eef-827f-282ec30e065f)
- [ ] If possible add a possibility to delete a holdback directly from a table
- [ ] If possible add a possibility to edit a holdback directly from a table (opens holdback modal with needed form)

**Offer is sent**
- [x] #6389
![Снимок экрана 2021-07-26 в 14.36.10.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4b75daf8-b8ac-4c99-9df8-c2515c9042a1)

**Offers and Deals > Contract Page > Particular Contract**
- [x] #6403
![Снимок экрана 2021-07-26 в 14.56.03.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/0f1b5b5e-fd3d-4d0c-8d4d-3e236a22e0a8)
- [x] The table with rights should be there
![Снимок экрана 2021-07-26 в 14.56.03.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/20b03fb2-005f-4c0d-80d4-2924706ac408)

P.S. For the other contract it worked properly 
![Снимок экрана 2021-07-26 в 15.08.49.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/d0b05f50-1344-49b5-b671-6db640dee67d)

- [x] "Contact Archipel Team" should open Intercom _(guess it doesn't work as not staging environment)_
![buyer contact.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4c037153-d168-4926-82f8-4469b3e487f4)

- [x] #6407

If no quick solution ,then try to use "Negotiating" label, if ok for business team
![Снимок экрана 2021-07-26 в 15.15.48.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/251bfea5-8086-49e6-85d1-cc5e9a0a8b9c)

- [x] #6405
![Снимок экрана 2021-07-26 в 15.17.13.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/2cba7658-3be9-4265-a68f-4a16b257193a)

### Seller's Dashboard
**Contract List**
- [x] #6409
![no price.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a73848ab-d2ea-4b02-811f-2b95014f32d3)

**Contract Page**
- [x] When access the contract page, then an error appears 
![Снимок экрана 2021-07-26 в 14.39.18.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4d1c3178-f8cb-43f0-9a16-3febf8ff855a)
- [x] #6418
![Снимок экрана 2021-07-26 в 14.44.54.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1a416ef1-c84a-4b9a-9963-e912bc98e2cd)
- [x] "Contact Archipel Content Team" should open Intercom _(guess it doesn't work as not staging environment)_
![contact AC seller.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a8139d76-804b-44a4-9e51-87d7663b8dcf)
- [x] When click on "Decline" the modal should appear to learn the reason why seller is declining an offer 
here is the missing screen https://app.zeplin.io/project/5fecb41a2e806651584e265c/screen/6036a904600fe3044bbbd531 
- [x] even if an offer is declined, seller should still be able to contact archipel team _(guess it doesn't work as not staging environment)_
![contact seller.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/380f8b82-8075-4a03-98b3-4cc14269a8ba)
- [x] Come back arrow should lead to the Contract List page 
![back button.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1a70d60b-b534-42ab-99e9-c3b8440b7c37)

**My Titles** (Cross-App)
- [x] #6426
From ![Снимок экрана 2021-07-26 в 15.35.23.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/aa7f32fb-809a-49d0-afae-04dcf0d61714)
To 
![Снимок экрана 2021-07-26 в 15.36.35.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/e2b19da1-12e8-4d80-8e6a-9053f7b61d35)

**Comment by 2amarkina** [comment]
Tested on Safari 14.1.1 (16611.2.7.1.4) 
MacOS 

Here are some bugs that are specific to Safari + supplementary corrections

### Both Marketplace and Dashboard 

**Toolbar**
- [ ] Logo of Archipel Content seems to be "blured" **(Safari specific)**
Logo on Safari 
![Снимок экрана 2021-07-27 в 09.52.07.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/bb5eebf4-b6ba-47e2-8925-e3913a2f5fe1)

Logo on Chrome
![Снимок экрана 2021-07-27 в 09.53.34.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/395fc052-59d7-46f6-8202-a74041b5fd09)

**Footer**
- [ ] Logo of Archipel Content seems to be "blured" in footer too **(Safari specific)**
![Снимок экрана 2021-07-27 в 09.59.11.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/37efa4b1-d210-4803-aa3a-85582c8bc354)

**Selection Page**
- [ ] If no versions added, put a "-"  
![Снимок экрана 2021-07-27 в 10.04.18.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/0e75b72c-c5be-4b6f-914e-d8556beed6cd)

- [ ] The total price should be updated according to the price entered 
![Снимок экрана 2021-07-27 в 10.05.44.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9d4ebe69-2493-4d23-967b-032c25caddd3)

**Activity Feed**
- [ ] Button "More" should lead to the Offer Page in Marketplace and to the Contract List page in Dashboard 
![Снимок экрана 2021-07-27 в 10.10.12.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/0d22fad4-ca62-4244-9e8d-bed56bd7b8c4)

**Wishlist**
- [ ] If possible, need to align the infos in table 
![Снимок экрана 2021-07-27 в 10.26.19.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1d6e8851-aca5-4a4e-8196-e44ac256be7b)

### Marketplace 
**Offers and Deals**
- [ ] If possible, put the recent offers on the first place. Exemple: 07/27/2021 should be on the first line, then 07/26/2021 and 07/23/2021 on the last place.   
![Снимок экрана 2021-07-27 в 10.16.08.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/8793de96-bfa0-43a8-8938-126b75e46826)

**Offer Page**
- [ ] Background color is not the good one (**Safari Specific**). Should be the same as in Chrome version. 

From 
![Снимок экрана 2021-07-27 в 10.19.30.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1ed9191e-c80c-4403-808a-99da77f73184)

To 
![Снимок экрана 2021-07-27 в 10.22.26.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/67b899e7-8c14-4c14-9433-ebf49bdce0bf)

**Offer Page > Contract Page**
- [ ] Error appears, but at the same time the rights table appears correctly (**Safari specific**)
![Снимок экрана 2021-07-27 в 10.23.07.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/66d946b7-762d-4ba1-b411-a794326274e7)


### Dashboard
**Contract List**
- [ ] If possible, by default order the contracts by the recent date. (The recent on the top)
![Снимок экрана 2021-07-27 в 10.29.05.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9439152f-f33f-4dc4-81f0-5040d3ac1305)

**Comment by 2amarkina** [comment]
Chrome + Safari 

### Marketplace 
**Offers and deals > Offer page**

- [ ] table has a tiny corner that goes out 
![Снимок экрана 2021-07-27 в 12.04.59.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/d88aa772-db8b-48f6-9f9b-13f66ab62132)

**Comment by maltmayer** [comment]
> **Homepage**
> 
> * [ ]  [Compose a new homepage, see with Business Team #6404](https://github.com/blockframes/blockframes/issues/6404)

I guess I can do that directly. What did you have in mind @2amarkina?

**Comment by 2amarkina** [comment]
> > **Homepage**
> > 
> > * [ ]   [Compose a new homepage, see with Business Team #6404](https://github.com/blockframes/blockframes/issues/6404)
> 
> I guess I can do that directly through the CMS. What did you have in mind @2amarkina?

Now we've got this 
![screencapture-archipelcontent-c-o-marketplace-home-2021-07-28-11_17_38](https://user-images.githubusercontent.com/55499036/127297547-ced180b5-5792-49b8-b13d-dad379b6580e.png)


And I was thinking about implementing one more carousel at the end with big posters to make the page more "full". And also, as we still present the Sellers on the platform, maybe we could finally put Featured Sellers, what do you think?
