### ISSUE TITLE
Issue when I filter invitation by "joinOrg" 

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#6395]
Currently, I have no "joinOrganization" invitations so when I select  Join Org : 

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/beba40be-c589-490c-9a9c-7eec60d70e5a) 

Form is removed and I have ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/ccebe9b2-68a8-48e2-b5e8-3ce76febd620)

I should be able to update form values to go back to other invitations.

Maybe something like this ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/049eb283-cff8-4e88-a7c2-b4cad4fc82d7) (with a sentence saying: "update fiilter to get results back" ?) 

@2amarkina what do you think ?

**Comment by 2amarkina** [comment]
Could we have something like that: 

1. No invitations at all 
<img width="530" alt="Снимок экрана 2021-07-27 в 17 51 22" src="https://user-images.githubusercontent.com/55499036/127186001-335c7700-dc45-4899-a24d-439c8b7089f7.png">

2. Add "clear filters" icon on the right when there are invitations
<img width="417" alt="Снимок экрана 2021-07-27 в 17 52 16" src="https://user-images.githubusercontent.com/55499036/127186111-5d793249-007e-4a7c-af55-debc02aba5c7.png">

3. Propose this screen, if no invitations for organization
<img width="524" alt="Снимок экрана 2021-07-27 в 17 52 46" src="https://user-images.githubusercontent.com/55499036/127186208-4a40a611-3321-455d-ad68-6e4222d88eac.png">

4. Propose this screen, if no invitations for events
<img width="520" alt="Снимок экрана 2021-07-27 в 17 53 18" src="https://user-images.githubusercontent.com/55499036/127186277-a095558b-d81c-473a-9bcd-1a7ddb09123e.png">

**Comment by jeremie74** [comment]
HI. I did it to make it simple. If nothing when you load the page you have the message but you always keep the filters. It avoids multiple conditions. If you select a filter and you have no invitations you display the same message :
<h1>You have no invitation yet</h1>
<p>Reload the page or click on the clear filter button above</p>
