### ISSUE TITLE
Contract errors

### ISSUE THREAD

**Issue by iPR0D1G1** [blockframes/blockframes#6403]
- [ ] Error appears
<img src="https://camo.githubusercontent.com/ffb4194d3a0de687feba611fca8af44ac36a2441c92e509dafece6618b73ad9d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f30663162356235652d666433642d346430632d386434642d336532333661323265306138" />

**Comment by GrandSchtroumpf** [comment]
should be fixed by https://github.com/blockframes/blockframes/pull/6412/files#diff-a0035dbc9f5d92309a4e28c2082c5e92a8685604e885c26d3f6ceffc9c298321R18
