### ISSUE TITLE
Status "in negotiation" appears to be a way too long. See this with UI team

### ISSUE THREAD

**Issue by iPR0D1G1** [blockframes/blockframes#6407]

**Comment by iPR0D1G1** [comment]
<img width="856" alt="Bildschirmfoto 2021-07-28 um 10 23 25 AM" src="https://user-images.githubusercontent.com/22674720/127298256-e0b506ce-5caa-4526-a136-3de3551470e3.png">

**Comment by GrandSchtroumpf** [comment]
The real solution is to use css propery `white-space: nowrap`. See my PR: https://github.com/blockframes/blockframes/pull/6412
