### ISSUE TITLE
Table  has tiny corner that goes out

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6413]
Chrome + Safari 

### Cross

- [ ] table has a tiny corner that goes out 
![Снимок экрана 2021-07-27 в 12.04.59.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/d88aa772-db8b-48f6-9f9b-13f66ab62132)

**Comment by SamirTouira** [comment]
Which Chrome & Safari version do you use please ? I don't have this issue from my side. Tested on Chrome 92.0.4515.107 and Safari (Browserstack) 14.1 & 13.1 & 12.1

![image](https://user-images.githubusercontent.com/52285231/127474759-da2203a0-7558-457e-acbf-60e7fc4ed5b8.png)

**Comment by 2amarkina** [comment]
I've got the  91.0.4472.164 version of Chrome and for Safari it's 14.1.1 (16611.2.7.1.4)

**Comment by RemcoSimonides** [comment]
Can't reproduce this either. Using the same Chrome and Safari versions. Tried both on festival and catalog

**Comment by RemcoSimonides** [comment]
Found it!
