### ISSUE TITLE
Movie data model refactoring: split into sections

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#643]
**Split form into section:**
* [ ] Fields of movie form will be different on each app.
* [ ] Movie form must be split into sections for each apps : subForms, ControlValueAccessors
* [ ] Remove current "trick" to flatten `Movie` into `FlatMovie` for actual movie form

**Split data model movie into section:**
* [ ] Check if it is possible because fields can belong to different sections regarding on witch app we are
* [ ] Update data model on draw.io

**Resources**
Form controls and sections: https://docs.google.com/spreadsheets/d/1cQKnEk5cCdMlPPam7bJzTwYoXB0hne1KwcXj9fDHHKw/edit#gid=0

MCD Model: https://www.draw.io/?state=%7B%22ids%22:[%221aJpKnmjbCOisXOEwHkNGV8_4vKDPfE4r%22],%22action%22:%22open%22,%22userId%22:%22101225645681930911579%22%7D#G1aJpKnmjbCOisXOEwHkNGV8_4vKDPfE4r

**split movie-display into section:**
* [ ] The easy part but previous points must be done before that

WIP branch is `implement-movie-sections`. Search for `@todo #643` in code

**Comment by Jackseed** [comment]
this has been done for Toronto, though it may be improved, I close it
