### ISSUE TITLE
Maintenance mode for video player

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6431]
In case we need to disable the player

In `libs\media\src\lib\video\viewer\viewer.component.html` we show a message if the player has an error.
We can temporarily replace this message with
"Sorry, we can't display the video. We're currently solving a technical error! Please come back later or contact us"
Contact us should link to an email address `team@archipelmarket.com` because the team behind Intercom won't be able to help in this scenario.

**Comment by pldespaigne** [comment]
Incident has been resolved
