### ISSUE TITLE
Buttons rules

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#6440]
- [x] Define design rules (add it in the notion doc about links and buttons) on when to use a filled or a stroke button, the accent or primary color ... 
- [x] Inventory of corrections to make in the app
- [x] Communication to the business team (for the CMS).

**Comment by frenchyrules** [comment]
**Inventory of corrections:** WIP

Archipel content
- [ ] "Play video" accent button on landing page should be flat button
- [ ] "Library" accent button on homepage should be flat button and arrow icon should be on the right
- [ ] "Library" accent button on homepage should be flat button and "Sellers" stroke button
- [ ] Search and buy rights, create offer (my selection) should be accent? _check with Stéphanie_

**Comment by RemcoSimonides** [comment]
Hee, this is ready for Dev?
What does the Dev need to do? I see a lot of images with buttons, but most buttons in those images already have the described button, right?

**Comment by stephanie-cascade8** [comment]
Hi :) Yeah it's ready for dev. (very not urgent task however, this is just
an inventory we had to finish. all buttons have to be replaced with the
right primary/accent color and filled/outline aspect)
