### ISSUE TITLE
Content loading strategy

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6447]
When loading a page most of the time we use a loader for users to wait for data to be fully loaded and then display the content (eg. dashboard homepage, or title list)

On homepage we do it differently and let data appears as it loads. It creates a weird effect that breaks page structure as text loads faster than images

![Kapture 2021-08-18 at 17 42 13](https://user-images.githubusercontent.com/14964443/129928931-09393cfc-141e-4184-883e-16199ef7deae.gif)

To avoid this effect we could use a page skeleton as a fallback that would be loaded first and then replace by data when it's loaded. 
Example:
loading state
![image](https://user-images.githubusercontent.com/14964443/129924040-e1527f7e-6ca2-49e7-84c6-22793c0638ed.png)
data appears
![image](https://user-images.githubusercontent.com/14964443/129924236-56dde227-6910-47d9-b62a-f07d7923f32d.png)

I think it's a good practice, especially for pages that mix data from different sources. This way users have the data as soon as it's loaded but the UI is not broken. 

It's a strategy we could implement almost everywhere but I think best is first to:
- [ ] Discuss the possible loading strategies and choose one
- [ ] Test it on one critical page like homepage

**Comment by Jackseed** [comment]
We should also look at all the loaders and check if we can add explanation text on top of this loader or something to show that loading is getting well (like progress bar when possible..)

**Comment by Jackseed** [comment]
Interesting talk of a google ux designer on speed and loading screens ([19:00](https://www.youtube.com/watch?v=Drf5ZKd4aVY)).
Studies show that skeletons are indeed best perceived by users, he also points out that we should of what's the content used within these skeletons

**Comment by cams-goussale** [comment]
Marie brought up the issue of slow loading pages. When clicking somewhere, nothing happens and it can last few seconds before the new page opens. One solution we propose is in this issue #7377 

Another solution is to revise the routing process. Currently, it looks like after clicking somewhere, 1- the app makes the calculation, and 2- it reroutes you to the new page. Do we want to reverse that: 1- it reroutes to the new page, and 2- it calculates and show the content?

>> Cons: we reroute user to a blank page during some seconds
>> Pros: at least the user doesn't feel as if nothing happened

Need to see with devs what is possible.

**Comment by cams-goussale** [comment]
This is an issue reported by Nicolas. If you're fast enough, you can create 2 events in a row when selecting your timeframe on the calendar. Probably a loading indicator after clicking on "More Details" would avoid this type of undesired behavior.
![Festival - my Events - mouse click shoud be disabled waiting for the next page to show](https://user-images.githubusercontent.com/93206363/161500827-f3b33819-6930-47be-9b5d-255dec86dafc.gif)

**Comment by 2amarkina** [comment]
**Some notes after dev review:** 

**Important note about loading:** 
- Or we wait for the whole page to be loaded: the page is shown after the whole data has been successfully loaded. Solutions as spinner, loaders or animations could be used. 
- Or we load data one after another depending on how data has been structured (Invitations example with Event, Org, User variables). 

1. Skeleton solution has a lot of "underwater" problems. We need to adapt skeleton's UI for each case in particular: each page and each element. The alternative solution could be a skeleton that is the same on each page. But in such case, we lose all the interest. 

2. The easier solution is to use the loops for the charging of the entire pages (spinner, looped animated image). 

3. We can upgrade our spinners putting the unique text, that will help a user to: see what's the state of the page and see what kind of page s/he's going to load (1st usage case). 

4. Progress bars in case of infinite loading (loading we can't calculate the end) can make the code really complex.

**Comment by 2amarkina** [comment]
**Some working documents** : 

- [Reflexion about different loading strategies and different loading patterns we have](https://docs.google.com/document/d/1XcWKKu1S34TmOiLe5wqD04_AkwV0ZHz1cOChbDiKhME/edit)

- [Little summary / ideas for our content loading ](https://docs.google.com/spreadsheets/d/1yIOozieG5ULbGHlXgcLhm4oqUf-_vPN8zNkZpna7XjU/edit#gid=1459394533)

**Comment by 2amarkina** [comment]
**Left to do:** 

- [ ] Provide the pages with updated spinner and unique texts. 
- [ ] Provide the propositions with pages where animated looped image might be used. 
- [ ] Review the existing loading strategies for invitations, notifications. Propose a better solution if possible.

**Comment by 2amarkina** [comment]
[Here is the figma link](https://www.figma.com/file/8a63I0IuHPtHKW2G14vg86/%E2%8F%B3-Loading-Cases-and-Rules)

**Comment by 2amarkina** [comment]
- [ ] @dmoncadalv give the dev @KvnMrs the files

**Comment by dmoncadalv** [comment]
Hi @KvnMrs !

Here are the rive links for the loaders. 

Spinner Content Logo :

https://rive.app/community/2743-5627-archipel-content-logo-animation

Spinner Market Logo :

https://rive.app/community/2744-5628-archipel-market-logo-animation

**Comment by phpgeekfr** [comment]
** for dev** If someone work on this issue, @GrandSchtroumpf suggest to use https://github.com/dappsnation/ng-rive
