### ISSUE TITLE
UI bug with tags in Expansion panel

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6454]
When selecting all available countries on the Film Page, the territory list in expansion panel is getting mad...
Chrome 92.0.4515.131 and Safari 14.1.2 (16611.3.10.1.3).
Also on the selection page, when clicking on “World”, the scroll doesn’t work (Chrome 92.0.4515.131).
At the same time it’s OK on Production.

![image.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/bb5c596f-482c-4245-b16c-818669c632f0)
![image.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/f023b2c6-28b9-454f-8f99-294fd76e6e06)

**Comment by iPR0D1G1** [comment]
This pull request resolves this issue already.
#6168
