### ISSUE TITLE
db-cleaning script issues

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#6460]
Currently, the db-cleaning script  is executed during upgrade process with maintenanceMode set to `true`.
In this context, document deletion is not triggering any 'onDocumentDelete' methods in backend-functions.

This made me realize that some deletions performed  during execution of this script are not deleting related document in cascade (IE: if I remove an user, I also want to remove logo on storage, delete notifications linked to this users etc..).

So to have a good cleaning-script, related document should be deleted also but this require a huge refactoring to allow interaction with bucket, algolia, jwplayer etc.. outside of backend-functions.

We could also call this db-cleaning script when app is not in maintenanceMode but this can be very risky as we don't know  all the sides effects and this cannot be fully tested with unit-testing.

My suggestion is to let the script as it is for now (what we does not handle right now  is media deletion when we delete users but there is no other side effect).

Regarding orgs without users, there is only 4 in production, we could delete them manually.

Regarding other documents that may be deleted during db-cleaning script, we need to check how we can manage this cleanly.

_Originally posted by @phpgeekfr in https://github.com/blockframes/blockframes/issues/5371#issuecomment-823973325_

- [x] look for `@TODO #6420` in code

**Comment by Jackseed** [comment]
It would be useful to have a list of objects possibly deleted by the cleaning script, plus the related ones that should be deleted in consequence but won't be as you mentioned. 
Then we may see how critical it is not to delete it and/or find solution object per object.

**Comment by phpgeekfr** [comment]
Yes good idea, will do that

**Comment by phpgeekfr** [comment]
Along with this issue, I will also check how to create a shrinked db for e2e tests on every PR

**Comment by phpgeekfr** [comment]
since anonymous login was activaded `removeUnexpectedUsers` will remove them since they don't have corresponding uid on db. Pay attention to this

**Comment by Jackseed** [comment]
shouldn't we update this script then?

**Comment by phpgeekfr** [comment]
> shouldn't we update this script then?

Not for this release but for the next one yes

**Comment by phpgeekfr** [comment]
- [ ] remove remaining watermarks fields on invitations (fromUser, toUser)  CF #6905

**Comment by phpgeekfr** [comment]
Minimal update have been done in https://github.com/blockframes/blockframes/pull/7222

More work is in https://github.com/blockframes/blockframes/pull/7170 but this is not mandatory anymore
