### ISSUE TITLE
Excel import - Flow refactoring 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6462]
With the rise of AC, titles and contracts should be more and more imported instead of created with movie form due to large number of titles for each seller.
Excel import should be updated as it flow is incomplete and unclear:

#### Shared issues
- creation of a document is indicated as an error, that's very unintuitive 
- update & creation of documents are too similar it's hard to see the difference
- preview button could be added
- errors and warnings could be more explicit (text and difference between one another)

#### Title import
- Miss images & videos import, we shall add a way for users to be aware that these documents are missing and help them to upload it.
- Submit process is not clear enough (vs direct validation on AM)

#### Contract import
- update template to include new fields
- add helpers to fill in territories, medias and dates

**Comment by RemcoSimonides** [comment]
Estimation
UX: 3 days
UI: 4 days

**Comment by 2amarkina** [comment]
- [ ] Validate the possibilities for the Titles with devs

If OK, then 
- [ ] Prepare the screens for the Contracts and validate tables with business team

if not OK, then
- [ ] Propose new screens

**Comment by RemcoSimonides** [comment]
Hee @2amarkina, we just had dev estimation and basically did a review too.

This will need some more investigation on how we can put a small piece of the movie form in here. It can be that the part of the movie form will involve more fields than only the field that is missing. e.g. if 'last name' field is missing we can only display the part with both 'first name' and 'last name' field.
![image](https://user-images.githubusercontent.com/27687382/140383206-57d118ec-44dd-4805-b322-69df162ac6d7.png)

Also, a bigger issue:
We have to import the titles first (so they are added to the db) before we can start adding the files to them.
So first we select the titles we to import on this page.
![image](https://user-images.githubusercontent.com/27687382/140383540-212cd02a-068c-458a-aba8-b97b57fbf5d1.png)
After which we are redirected to another page where we can add the files to the imported titles.

**Comment by 2amarkina** [comment]
[WIP and wireframes are accessible here](https://www.figma.com/file/SiYgdZcNCMqgdTSy1fVLNB/%5B-Import-%5D?node-id=126%3A877)

Flow and screens updated following dev comments

**Comment by 2amarkina** [comment]
Propositions coupled / uncoupled options

**Comment by 2amarkina** [comment]
**LEFT TO DO:** 

- [ ] Add screen with Titles Error List for Archipel Content (Change CTA Publish to Submit, check the texts) ; 
- [ ] Add Contract Error List for Archipel Content (Check the CTAs) ; 
- [ ] Add Modal Error View for Contract Errors (Check and list the fields that are mandatory) ; 
- [ ] Add Promotional Elements with "checked state" ;
- [ ] Verify the Complex Forms with devs ; 
- [ ] Check the "smooth" passage from "Submitted" (Archipel Content) to "Add promotional elements" screens (verify feedbacks) ; 
- [ ] Check two flows: if we go with promo elements only for recently published titles or for all published titles with no promotional elements.

**Comment by 2amarkina** [comment]
**[Updated wireframes can be found here](https://www.figma.com/file/SiYgdZcNCMqgdTSy1fVLNB/%5B-Import-%5D?node-id=126%3A877)**
