### ISSUE TITLE
FAQ / Tutorials

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6466]
Following business review, the following issues are closed [#6060](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/6060), [#6062](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/6062), [#6061](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/6061) in order to create a common one. 

Last decision was not to use Intercom, but create our own video tutorials with explicit and well-seen Help Center. 

- [x] Clean and finalize the wireframes with "Learn how it works" button for the Archipel Market. 
- [x] Clean and finalize the wireframes with access to Help Center. 
- [x] Clean and finalize the wireframes with Help Center. 
- [x] Validate with business team the scenarios for Screenings / Meetings. 
- [x] Create videos for Screenings / Meetings. 
- [ ] Foresee the scenarios for other tutorials. 

Documents needed for work: 
[Wireframes](https://www.figma.com/file/4SghqlahJeV0vibkUswGSx/%5B-Helpdesk-%5D?node-id=0%3A1)
[Scenarios](https://docs.google.com/spreadsheets/d/1XJz7I4VqmVOYr8InIkBKvPnhivLll1iKKmFkPNMpiVw/edit?usp=sharing)
[Future knowledge base](https://docs.google.com/spreadsheets/d/1fCUSh7qm7SgrdXKPbkpInUH5TYlPIfU6ep7LhsVNKA8/edit#gid=0)

**Comment by 2amarkina** [comment]
- [ ] Update wireframes with new views (Ana need to put components)

**Comment by frenchyrules** [comment]
- [ ] Replace meeting image with video
- [ ] Re-work text for a more visible version

**Comment by cams-goussale** [comment]
We forgot to do the Business check on the to do list and it looks like it back fires with too many reviews at a too advanced stage of the videos. Here are Marie's comments (french)

**Commentaires généraux :**

- Vidéo beaucoup trop dézoomée. Ça ressemble pas vraiment à ce la plateforme et ce n’est pas nécessaire, ça fait que l’écriture est trop petite. + ça se voit beaucoup notamment dans les stats de l’event form qui ne vont pass jusqu’au bout de l’écran
- Couleur sombre pas assez visible, mieux vaut faire avec le mode light.
- Commentaires en noir et blanc ne se voient pas assez, il faudrait peut-être de la couleur. Corail en background?
- Ecrire en plus gros le commentaires
- Mettre un faux logo sur la « film company »
- Je trouverais ça pas mal que le background des commentaires aille jusqu’au bord de l’écran pour un effet « ruban » mais ça c'est maxi bonus

### SCREENING:

1. Création de l’event: 

- Titre du screening: My Market Screening
- sélectionner une heure de départ+fin rapidement
- Text du commentaire: Select a time and create your screening

2. Event form - Screening

- Clicker sur Protected + Secret pour montrer le changement de settings (pas besoin de hover sur les tooltip je pense)
- Aller moins vite sur la sélection du titre (My International Title) : il faut montrer la liste et sélectionner.
- Texte du commentaire: Fill in your screening information and select your preferred privacy settings

3. Event form - Invitations

- il faut d’abord copier coller une dizaine d’adresses d’un coup (pour montrer que c’est possible sinon ça peut faire peur de devoir rentrer tous les mails 1 par 1) puis éventuellement en taper une et sélectionner comme c’est fait dans le Tuto existant.
- Text du commentaire: Send invitations by typing or pasting a list of emails

4. Screening event

- Retirer logo SCREEN dans la toolbar
- Ajouter une banner image by default au film pour que le screening ne soit pas vide
- (Pas besoin de lancer le film je pense car on est sur un tuto seller pas buyer)
- Ne pas montrer la modale « leave anyway » 
- Faire apparaitre le commentaire un peu plus tard
- Texte du commentaire : After your screening, access the event’s statistics in a detailed attendance report

5. Event form - Statistics

### MEETING

1. Création de l’event: 

- Titre du screening: Buyer Meeting
- sélectionner une heure de départ+fin rapidement
- Text du commentaire: Select a time and create your meeting

2. Event form - Meeting

- Ne pas sélectionner la date/heure (le faire dans la modale précédente)
- Sélectionner une autre personne dans « Organized by » pour montrer qu’on peut organiser un meeting pour qqn d’autre : il faut montrer la liste et sélectionner.
- Texte du commentaire: Fill in your meeting information and select your preferred settings

3. Event form - Invitations

- Attention le commentaire arrive un chouya trop tot (on est encore sur l’onglet « Meeting » 
- Text du commentaire: Send invitations by typing or pasting emails
- Il faut cliquer sur send  

4. Event form - Files

- Attention le commentaire arrive un chouya trop tot (on est encore sur l’onglet « Invitations » 
- Texte du commentaire : Select the files you’re planning to share before your meeting

5. Meeting event 

- Retirer logo SCREEN dans la toolbar 
- Il faut laisser un peu plus de temps avant d’ajouter des fichiers supplémentaire : montrer les 2 users qui interagissent, l’un qui présente un fichier
- Ajouter un commentaire avant les « supplementary files »: During the meeting, present selected files to your interlocutor
- Texte du commentaire (pendant l’ajout de fichier supplémentaires) : You can also add additional files directly during your meeting

**Comment by cams-goussale** [comment]
Following all this comments, it looks like we must start over. To make easier and faster the editing on the invitation (due to necessary anonymization), let's use [these email adress] (https://docs.google.com/spreadsheets/d/1En5KgIPyHDSYjlDwDoSTRHGhz6BIqEs2jjqW9cBpe8A/edit#gid=1563231860) @frenchyrules

**Comment by frenchyrules** [comment]
New video for screenings [here](https://drive.google.com/file/d/1DSsnEFZ5v7gniP4L8G5ze1aPsYOIlS3x/view?usp=sharing)
