### ISSUE TITLE
Disappearing still images

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6467]
We have a weird behaviour: a title on prod has 4 promotional images, 1 is ok but the 3 others are dead links. When I look on db 4 stills are filled in with link to storage but in storage there is no promotional elements folder... How come that one is working? And what could make these 3 images disappear?
movieId: c8e3k3RhlE1oQK2RWMJ3
title page: https://www.archipelmarket.com/c/o/marketplace/title/c8e3k3RhlE1oQK2RWMJ3/main

![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/8e7e6365-f043-4dd0-8515-eaa5dd06aa7f)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/4aed228e-a461-4507-94fe-11c7b83ff6ad)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/39aeb1b3-c116-4adb-8f30-6c9b3bf31422)

**Comment by phpgeekfr** [comment]
So indeed there is no images in the storage but paths are still referenced in db object.
I looked in backups from may 2021 and images where not there so removal was made a quite long time ago so I cannot dig into logs to check what happened.

The only working image is inside the imgIx cache but I thought that when image was removed from storage, image was also removed from imgix cache. Looks like not.

Can you add new still images and check if new are working ok and staying on storage ?

**Comment by Jackseed** [comment]
I don't have the images anymore, mb @maltmayer does but she asked for us to find it so I assume we don't. 

Looks like we can't do much here, I let you close the issue if you don't have other leads to understand what happened
