### ISSUE TITLE
[CATALOG] Dashboard permission denied

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#6489]
I get a `FirebaseError: Missing or insufficient permissions.` when navigating to the catalog dashboard contract list page :
`http://localhost:4200/c/o/dashboard/contracts`.

![image](https://user-images.githubusercontent.com/5858657/130130508-1fd928c3-35f0-423a-a8d3-d1a4d1d9b73f.png)

**Comment by iPR0D1G1** [comment]
Have you deployed your security rules of lately.

**Comment by pldespaigne** [comment]
Latest rules form today's develop branch gave me the same error.
Also got permission denied on `/c/o/dashboard/contracts/be-567575/X0S9NXayWnGSRF1Dhzb2`, with user `dev+melany-vta@blockframes.io`

**Comment by phpgeekfr** [comment]
It does not look to be linked to #6575 afterall

**Comment by phpgeekfr** [comment]
but looks like linked to https://github.com/blockframes/blockframes/issues/6554#issuecomment-911410685

**Comment by pldespaigne** [comment]
Duplicate from https://github.com/blockframes/blockframes/issues/6554#issuecomment-911410685
