### ISSUE TITLE
Catalog - movie can have wrong production status selected

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6495]
![image.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/96b0ddb7-0123-49ac-b89f-7afd903b640a)
Example movie: HmBSz12EkxnrkCPSoG7v

This is causing bugs like:
- [ ] In movie tunnel the Notes & Statement is shown in the sidebar but it's a dead link
- [ ] Shooting information can be filled in

@Jackseed I remember this issue was spoken about before. Maybe you have more insights about it?

**Comment by cams-goussale** [comment]
Hey! During the clean up for genres & content type, I think i was able to identify these titles which have access to Catalog, but their Release status is not == 'Released'. As you can see, most of them are tests. Here you can't see their catalog status, but there is only 1 in accepted (ON THE WING). The rest is draft / refused / submitted.


<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Movie id | International title | Original title | Content Type | Release status
-- | -- | -- | -- | --
0Rl7IIHX5Mz7t8lPXEhS | Test MArie |   | series |  
1DTboUyEd9Bi94VPezCa | OTHER ANGLE PROMO REELS CANNES 2020 | OTHER ANGLE PROMO REELS CANNES 2020 | feature_film | shooting
1J5uLFThLziaj2j0xPPP | Felicità | Felicità | feature_film | finished
3d91ZMyhNS8tAtsAvogF | ON THE WING | LES AVIONS DU BOUT DU MONDE | series | shooting
5FRNywltPc7YANK9tC64 | test bruce 2 | test bruce 2 | feature_film | shooting
EG5mZFd0yirD09zd81GL | STUDIOCANAL Presentation | STUDIOCANAL Presentation | feature_film | finished
HmBSz12EkxnrkCPSoG7v | Promoreel Loop | Promoreel Loop | feature_film | shooting
KUdqXhfFExEJyb44P1YK | Gaelle TEST | Gaelle test UX | short | development
KxHNAKI376LF3qtnMWSJ | OTHER ANGLE PROMO REELS CANNES 2020 | OTHER ANGLE PROMO REELS CANNES 2020 | feature_film | shooting
Qe5tgAQk2Tzfo1mDowHq | Pleasure | Pleasure | feature_film | post_production
Rsv7OnpjCgCpDfkSy2Mn | Suicide Tourist | Selvmordsturisten | feature_film | finished
S512yYOhaMlezFIgUnrF | MOSKVITCH MY LOVE | MOSKVITCH IM SER | feature_film | finished
SR0hmehDW43RkAicm5mq | OTHER ANGLE PROMO REELS CANNES 2020 | OTHER ANGLE PROMO REELS CANNES 2020 | feature_film | shooting
SjVBWpQHWIPtqWnt5REY | OTHER ANGLE PROMO REELS CANNES 2020 | OTHER ANGLE PROMO REELS CANNES 2020 | feature_film | shooting
VFCHF0NxeimQCZUl83Qh | The Girl With A Bracelet | La Fille au bracelet | feature_film | finished
Z1JECELldplwwfHkjnwq | Deerskin | Le Daim | feature_film | finished
a1FVfmUafFsmQqlOViDk | Gaza Mon Amour |   | feature_film | post_production
bllh9AadNl4ObzYHbWH0 | test |   | feature_film |  


</body>
</html>
