### ISSUE TITLE
Review Catalog 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6496]
## **Environment**
- OS: MacOS BigSur (11.5.1)
- Browser: Chrome (92.0.4515.131 )

### Marketplace
Profile used: Gretchen Ppe 

**Library page**
- [x] Avails filter seems to be broken: rights select is not displayed ![broken avails.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/6061d131-3d69-46ad-bc13-9f20b913d257)

**Avails Film Page**

**MAP VIEW**
- [x] Show the "holdbacks exist" **only if** there are holdbacks. If holdbacks do not exist for this right, then do not display this button. 
![Снимок экрана 2021-08-20 в 14.28.42.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/fe6c27c2-cbe3-46b9-a130-ff9875714be2)

- [x] #6509
![search for new terms and rights.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/8367482a-b796-4f96-ae1d-50bdb902da54)

**CALENDAR VIEW**
- [x] #6510
![Снимок экрана 2021-08-20 в 14.57.19.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4b4a52e7-ed06-45c5-ace4-5aa4f6efcf3e)

Just after clicked on Apr 2023 and Aug 2023 and worked as expected - rights were added correctly. 

- [x] Same remarks as for the Map View, show "Holdbacks exist" button only if the holdbacks really exist. If not - do not display. 
![Снимок экрана 2021-08-20 в 15.01.43.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/07849567-0ede-465f-9dcd-a167b704b96b)

**Selection Page**
- [x] When hovering "edit" button, introduce a tooltip saying "Edit" 
- [x] When hovering "delete" button, introduce a tooltip saying "Delete" 

- [x] If possible, when clicking on "Edit" button lead a user directly to the needed card
![editing rights.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/14ebb073-a64d-4f29-8b66-135b17e9e925)

- [x] #6512

and should be like that (example from staging)
![Снимок экрана 2021-08-20 в 15.12.21.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/85683547-77be-4c71-9151-9e1232273fbe)

Check out with @stephanie-cascade8 and @jdrns if needed. 

_When adding Holdbacks_ 
- [x] Recheck one more time with @Jackseed but normally there is no holdbacks for versions. 
![Снимок экрана 2021-08-20 в 14.34.16.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/0bdc5bb6-1605-4395-8a4d-e9054c24e764)

- [x] Can we add Holdbacks to the table directly after the first click and not the second? 
![double adding holdbacks.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/3287622d-7bd4-4a21-b395-21e8adaf08eb)

- [x] Can we add "Edit" and "delete" buttons directly to the table? If not, maybe change the text to "Add and manage holdbacks" 
![Снимок экрана 2021-08-20 в 14.34.16.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/372bbbee-3dca-4305-a187-47e8164e5642)

- [x] If possible, show Total Price in header and at the end of the page only if price field is filled in. ![Снимок экрана 2021-08-20 в 14.53.32.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/432da078-50c6-4167-86b7-88b4b2fbe5fe)![Снимок экрана 2021-08-20 в 14.53.44.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/3ff9b433-c6dc-4a91-8c6a-743a76f04877)

- [x] After sending an offer, the modal with Specific terms is still displayed, but it's empty. If I'm not mistaken it was our solution to try to avoid the number of items in the Selection, but in such case we need to show longer the Sending process and keep up with the filled modal.

**Offers and Deals page**
General
- [x] Change the title to "Offers & Deals" 
![Снимок экрана 2021-08-20 в 15.05.03.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/11b1d0ca-9fb1-4276-ba4d-4f1f4eaadd46)

No offers
- [x] Could not load the page, had an error all the time
![Снимок экрана 2021-08-20 в 15.04.56.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/02f9c858-c377-4eb4-82ef-9c4034465782)

- [x] Should display en Empty page if no offers and deals yet. [Here is an example ](https://www.figma.com/file/oUCgDCGJndPiVhel04GdIH/Archipel-Content-Renaissance?node-id=2235%3A201)
and here is a screenshot
![Снимок экрана 2021-08-20 в 15.45.26.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/73a9f821-216e-41e1-aa7b-e5f0896a6153)

Updt. 23/08/21 
OK for the list of Offers when there is at least one offer created. 

- [x] When an offer is created and we go for the list for a first time, the number of titles in package is not displayed. It appears only after changing a page. 
![Снимок экрана 2021-08-23 в 15.33.00.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/92fcb20c-2ada-4e56-a285-237ba8780596)

- [x] After refreshing a page, the columns became empty. 
![Снимок экрана 2021-08-23 в 15.35.03.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/88197904-028e-44b5-a0c8-b152149be8df)

Offer page > **Contract page**

- [x] Date is not ok, we see DD instead of a number.
![Снимок экрана 2021-08-23 в 15.36.06.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7da8e0e5-a6d3-4156-9d16-fff3cb7659b7)

**Rights card**
- [x] when clicking on the Territories or Rights, there is a modal that appears but there is nothing inside
![Снимок экрана 2021-08-23 в 15.39.22.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a41f8318-9a34-45f1-bc60-456f71195bbb)

Verify the texts with @maltmayer 
**Main title:** You have no offers created yet.
**Explanation text:** Your contracts will appear on this page when you submit them.
Meanwhile you can browse our library to discover titles you can be interested in. 

- [x] @Jackseed, @maltmayer  I remember discussion with Christophe to change "Sellers" to "Partners" in the side menu, do we keep on with Seller or change to Partners?

**Comment by 2amarkina** [comment]
## Environment
OS: MacOS BigSur (11.5.1)
Browser: Safari 14.1.2 (16611.3.10.1.3)

Same remarks on the behavior as for the Chrome, here are the problems that concern Safari only. 

### Marketplace
The logos are still blur in the header and in the footer 
![Снимок экрана 2021-08-20 в 15.22.06.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/d8b7deaa-e78f-4bbc-b6d6-3b3cbeb2e201)

![Снимок экрана 2021-08-20 в 15.22.59.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/5cf241c7-8d51-400b-845a-f8776b1e841e)

**Film Page**
- [ ] Had this error
![Снимок экрана 2021-08-20 в 15.23.34.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/e9136fb2-a4c8-44fa-8ce8-3531354e3259)

**Comment by 2amarkina** [comment]
## **Environment**
- OS: MacOS BigSur (11.5.1)
- Browser: Chrome (92.0.4515.131 )

### Dashboard
Profile used: Crystal Bednar

**Contracts Page**
- [ ] The price in the table is not charging 
![Снимок экрана 2021-08-20 в 15.56.01.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/254f8510-a72d-43ff-8284-0fa32a46de9b)

- [ ] If there is no price, then show "-" or nothing. 

- [ ] Put a "." and the end of the hint when declining an offer. 
![Снимок экрана 2021-08-20 в 15.58.13.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/ffb7f9ad-9a0a-4729-a34f-89b583a9ab36)

- [ ] There is a strange bug when closing a modal with "Decline" offer. Clicked on "cancel" and then we can see the movement on the buttons level. 
![strang ebug.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7e13cdd0-7f5b-462a-85ed-0c9ed7e83839)

- [ ] almost the same strange bug appeared when tried to accept an offer. 
![accept bug.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/38fbc291-0f56-483c-870b-374ec9cf2ed0)

**Comment by 2amarkina** [comment]
I continue reviewing the CRM part, not touching the Dashboard / Marketplace for the moment. 

## **Environment**
- OS: MacOS BigSur (11.5.1)
- Browser: Chrome (92.0.4515.131 )

**CRM review:**  
- [ ] Show number of the Ongoing deals in the tabs
![Снимок экрана 2021-08-23 в 15.12.45.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/f0eb4cc1-9547-459f-a0b0-76f53f52a241)

- [ ] Very quickly we can see an " Offer not found" page
![Снимок экрана 2021-08-23 в 15.14.42.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/712fe15b-71ad-49dc-8c0f-91b0abf557d0)

For better navigation between the Offer pages we need to have the following: 
- [ ] On the Offer page the come back arrow in the header should lead to the Offers's list (already OK)

- [ ] On the Contract page (inside an Offer, see screenshot) the arrow should lead back to the entire offer page OR we could add a supplementary link helping to come back (see wireframe).
![Снимок экрана 2021-08-23 в 15.23.23.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/8819dd01-7fac-49f8-b4d8-c191a42f11c2)

![Снимок экрана 2021-08-23 в 15.25.10.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7cc0a6f6-74d4-4aa1-b912-d2af6b739644)

P.S. new offers created last week do not appear yet on the CRM (ba-674903)

**Comment by 2amarkina** [comment]
- [ ] For ALL modal refer to[ this ](https://github.com/blockframes/blockframes/issues/6494), but check with UI team if ready to go

**Comment by Jackseed** [comment]
> * [ ]  Recheck one more time with @Jackseed but normally there is no holdbacks for versions.
>   ![Снимок экрана 2021-08-20 в 14.34.16.png](https://camo.githubusercontent.com/f077f291491c1688b5b8d75c3e714ecd6e86e70703ed172d8187eac081851e52/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f30626463356262362d313630352d343339352d386134642d653930353463323465373634)

I confirm, there is no holdback for versions

**Comment by Jackseed** [comment]
> ### Marketplace
> The logos are still blur in the header and in the footer
> ![Снимок экрана 2021-08-20 в 15.22.06.png](https://camo.githubusercontent.com/30898296d739644a5df3d2471c30365b971679596f3a4d41813d4c7fa96ff6fd/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f64386237646561612d653738662d346262632d623664362d336233636265623265323031)
> 
> ![Снимок экрана 2021-08-20 в 15.22.59.png](https://camo.githubusercontent.com/e5f1d90aefa76e9673601e06c79f324d724c7cc4135d0e2c30d403f222b63532/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f35636632343163372d386435312d343030622d383435612d663837373662316538343165)

Re this one, the issue is now on the design side as it seems the problem comes from the svg itself, see issue #6455
