### ISSUE TITLE
Modals rules and inventory 

### ISSUE THREAD

**Issue by jdrns** [blockframes/blockframes#6507]
Lots of weird looking modals, rules are needed, especially for min/max height and width, as well for the structure 

eg:
![Screenshot 2021-08-24 at 17.09.24.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/55879c44-e379-4b6d-8791-c935e7a8483e)![Screenshot 2021-08-24 at 17.09.17.png](https://images.zenhubusercontent.com/603cae1b5c058cfd0a584f5f/3a20ad09-96fa-47a9-952e-02b224188db5)

**Comment by jdrns** [comment]
### For all modals to be consistent we would like: 
- [ ] them to have min-width: 50vw, max-width: 80vw, min-height: 50vh, max-height: 80vh. For that, [global configuration default](https://material.angular.io/components/dialog/overview#specifying-global-configuration-defaults) should be implemented

- [ ] to remove individually on all modals, fixed height and fixed width (once global configurations set)

- [ ] to have a fixed cross at the top right (if scroll, only what is bellow the cross with scroll). For that, a new [dialog content](https://material.angular.io/components/dialog/overview#dialog-content) (something like `mat-dialog-header`) should be created 

### Then depending on the type: 

1. Warning modals (Title + Text + Main Button + Secondary Button)
2. Informative modals (Only text and/or chips and/or images/files)
3. Form modals (Containing at least one form field) 

#### Warning modals should have: 
- [ ] padding: 24px
- [ ] Title in h2
- [ ] Explanatory text in Body-1
- [ ] content horizontally Centered
- [ ] Main action is Flat Button primary 500 
- [ ] Secondary action in Basic Button Primary 500
- [ ] Buttons always stacked (spaced with 4px)

**Preview** 
<img width="878" alt="Screenshot 2021-08-20 at 16 28 59" src="https://user-images.githubusercontent.com/79836137/130248840-3244c211-62dd-4630-a776-e2d60e889a58.png">

**Inventory** 
In this [inventory](https://docs.google.com/spreadsheets/d/1N06uryQf5J7g56kyenJgpZ_HtiXmYb_Evf798E4fwsY/edit#gid=678850512) you can find mostly of the warning modals (not sure if the inventory is complete) but there should be 48 modals in total. 

- [ ] The warning modals needing change are the ones on the inventory with a status _in prod_ and a type _warning_

Once done: 
- [ ] Check with Design

**Comment by KevinDurand974** [comment]
Can i've the right to write on this inventory ? Thanks !

**Comment by KevinDurand974** [comment]
### Warning Modal

<details>
	<summary>
    <code>Padding: no padding</code>
    <code>Paragraph: no max-width: 70%</code>
    <br>
    Show Image
  </summary>
	<img src="https://i.imgur.com/Vu5ztSX.png" >
</details>
<details>
	<summary>
    <code>Padding: no padding</code>
    <code>Paragraph: max-width: 70%</code>
    <br>
    Show Image
  </summary>
	<img src="https://i.imgur.com/CCYhZXo.png" >
</details>

<details>
	<summary>
    <code>Padding: original `padding: 40px 80px 80px 80px`</code>
    <code>Paragraph: no max-width: 70%</code>
    <br>
    Show Image
  </summary>
	<img src="https://i.imgur.com/i6uNjTB.png" >
</details>
<details>
  <summary>
    <code>Padding: original `padding: 40px 80px 80px 80px`</code>
    <code>Paragraph: max-width: 70%</code>
    <br>
    Show Image
  </summary>
	<img src="https://i.imgur.com/5MKwzSk.png" >
</details>
      
<details>
	<summary>
    <code>Padding: `padding: 80px`</code>
    <code>Paragraph: no max-width: 70%</code>
    <br>
    Show Image
  </summary>
  </summary>
	<img src="https://i.imgur.com/dEv1iIu.png" >
</details>
<details>
 <summary>
    <code>Padding: `padding: 80px`</code>
    <code>Paragraph: max-width: 70%</code>
    <br>
    Show Image
  </summary>
	<img src="https://i.imgur.com/INWEhHl.png" >
</details>

@stephanie-cascade8

**Comment by KevinDurand974** [comment]
Ok, its not global at this time, I will do it globally and i will share you my env
