### ISSUE TITLE
Deal negotiation - Specs

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6520]
## Description
A usual dealmaking process includes:
1. Research of good title(s)
2. Discovery
3. Buyer making an offer
4. Seller and Buyer negotiation
5. Signing of the deal (or deal abort)
6. Delivery & Payment
7. Financial reports (if any)

So far we focused on 1, 2 & 3. We'll now include the 4th step to our flows. 

Deal negotiation in the movie industry usually focuses on 2 aspects: variable terms (price, media, version, territory,..) and standard terms (detailed definition of every words, waivers, more 'legal' stuff,...). 
For at least the first version of this feature, we'll focus on the negotiation of variable terms only. Standard terms will be attached by default to every contracts and won't be negotiable, using classic industry templates. 

Regarding the negotiation itself, it means that buyer and seller will be able to modify every aspect of a current offer, i.e. variable terms. 
These may be modified until they reach an agreement or a decline. 

One important aspect of this new feature is that it will decrease the importance of our admin, giving more features directly to sellers and buyers instead of focusing on the admin app. 

## What's new
This feature will be conducted step by step with user tests as a guide to know how far we should go. 

Here is a list of what we've identified as possible sub-features:
- dashboard edit of a contract 
- marketplace edit of an offer 
- marketplace mark contract as archived (delete a title from an offer)
- dashboard acceptation and declining process of a contract
- marketplace acceptation and declining process of an offer
- email & in-app notifications
- sms notifications (profile page update with cell phone, notif preferences)
- contract details within the email notification (harder than versioning)
- include buyer's details in the dashboard section (person name, tel & email)
- direct chat with either AC admin or buyer/seller counterpart (could be but then it's an org chat with every members and the same chat for all the stakeholders + the name of the person writing is displayed (++ details))
- ability for buyers to attach their own standard terms template (would be easier with pdf files instead of html pages)
- contract versioning 
- ability for seller to let AC admin handle the negotiation

(more to come..)

## User scenarii 
1. Seller makes a counter offer
2. Seller accepts an offer
3. Seller declines an offer
4. Buyer accepts a counter offer
5. Buyer declines a counter offer
6. Buyer modifies an offer
7. Buyer removes a title from an offer
8. Seller removes a title from an offer

**Comment by RemcoSimonides** [comment]
- [ ] Create a new Epic for the Feature Team once the design is finished. I'll explain why later ;)
