### ISSUE TITLE
Movie: CRUD, List, View, Wishlist

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6527]
- [ ] Movie list
- [ ] Movie view + Financial + Campaign view (movie view tabs)
- [ ] Movie filters > test on MF for specific filter
- [ ] Delete: CRM

Changes that should be tested
#4246
#5799
#6121

**Comment by xmano** [comment]
Minor UI Issue with Grid movie display. Sometime before the end of movie list is reached, the grid is not fully populated. See the pic below:

![image](https://user-images.githubusercontent.com/8731418/131490178-015a8c85-2e4a-448b-b6d8-53f3fe3e36dd.png)

Expected : Fully populated grid.

It may confuse user that movies got completed or as bug in app.

**Comment by phpgeekfr** [comment]
I'm not sure that is an issue, we load item per batch of 50 and the grid displays 4 titles per row.

**Comment by xmano** [comment]
> I'm not sure that is an issue, we load item per batch of 50 and the grid displays 4 titles per row.

First batch  & second batch is displayed correctly 1 - 50, 51- 100.. so why not in between?

**Comment by xmano** [comment]
For some movies Add to Wishlist is not working:  (eg Two of Us , BtuMTH5Jik8wruYYZF0A)


![image](https://user-images.githubusercontent.com/8731418/131506345-6500455b-b5aa-4faa-ac34-858a6c36a123.png)

**Comment by xmano** [comment]
Feature request / Safety  / Environment Issue

Some movies have trailers. Eg CATS - gQQLyTPPJHBLRHDCpHQs
When playing the trailer the volume starts at high level and can be bothersome:

![image](https://user-images.githubusercontent.com/8731418/131508975-14ad52b3-551d-4284-b124-ddf06c420193.png)

Most other platform Facebook for example I think start the videos muted? Can we do similar or at least start with a low volume?

**Comment by RemcoSimonides** [comment]
## Environment
_Please describe your environment_ 
- OS: **IOS**
- Browser (& version if possible): **Safari 14.1**

## Review item
_Copy & fill this section for each item._
### Localization
- App name: **Archipel Market**
**- Page: Movie Details view**

- [ ] Add a "br" tag before "You can contact"
<img width="1384" alt="Capture d’écran 2021-08-30 à 15 45 23" src="https://user-images.githubusercontent.com/66258851/131352859-c630e2cf-81e2-4319-8a44-c407338d86bc.png">

- [ ] Have 72px margin between end of page content and footer.
<img width="697" alt="Capture d’écran 2021-08-30 à 16 15 04" src="https://user-images.githubusercontent.com/66258851/131353763-331c6984-160b-4987-a02b-0194ec4320af.png">

**- Page: Movie-View Summary page**
- [ ] Have a Mat-button instead of filled for "back".
- [ ] If footer section is necessary, have both buttons inside.
<img width="1302" alt="Capture d’écran 2021-08-30 à 15 33 12" src="https://user-images.githubusercontent.com/66258851/131353015-36aac182-6ea1-4be7-80dc-c10ab99293d4.png">

- [ ] Connect font colors to the builder (foreground-700 for paragraph and all basic body-1 text / foreground-800 for H1, H2, H3) if questions contact UI team.
<img width="1145" alt="Capture d’écran 2021-08-30 à 16 19 27" src="https://user-images.githubusercontent.com/66258851/131354080-628bdd65-3174-4aa7-921d-0aa5b871a4d7.png">
<img width="1268" alt="Capture d’écran 2021-08-30 à 15 50 08" src="https://user-images.githubusercontent.com/66258851/131354123-b00742da-cbca-4215-b2df-11b0e7c6ded8.png">


- [ ] on some filled buttons, not all of them for some reason, the line-height: 24px is not enough and should be replaced by 26px. 
This will center the content of the button vertically: 
<img width="543" alt="Capture d’écran 2021-08-31 à 10 43 32" src="https://user-images.githubusercontent.com/66258851/131473457-d04542f4-c65f-4bbc-8ad2-601ac6c6b714.png">
<img width="594" alt="Capture d’écran 2021-08-31 à 10 48 58" src="https://user-images.githubusercontent.com/66258851/131473473-037d2f0c-c63a-41c8-81df-44e3671329b6.png">

**Comment by Jackseed** [comment]
- [ ] Admin email when movie submitted: the email used here is different than the others, it's dev+guy-xca@blockframes.io whereas other admin emails used dev+staging@blockframes.io. It looks like a mistake
- [ ] Same email, add a direct link to the CRM movie page: "...please check it on CRM here (url to crm movie page)"

**Comment by Jackseed** [comment]
user dev+josue-ldg@blockframes.io
url https://staging.archipelmarket.com/c/o/dashboard/tunnel/movie/PWN0W8A8ZkTxKYDXFNSp/summary
- [ ] Movie form - Summary page "You have 1 mandatory fields to fill in." should be red cf [zeplin](https://app.zeplin.io/project/60745a27456daf28d3b14ec2/screen/60755f7821f1cc406573fac9). Also, there is a mysterious "Value" word just below I don't know why, should it list what field has an error?


![image](https://user-images.githubusercontent.com/14964443/131892344-f2db5f74-5b2c-4d2c-b268-237483b521cb.png)

**Comment by RemcoSimonides** [comment]
## Environment
**- OS:** MacOS Big Sur (11.5.1)
**- Browser** (& version if possible): Safari 14.1.2 (16611.3.10.1.3)

account used: Estevan Murray

### Marketplace

**Titles page**
- [ ] Cross App: According to the [snackbar inventory](https://docs.google.com/spreadsheets/d/11mgu0-s9i0KIBRgRUAlE-WjuJQLOaTmMcdrVLEUKwAk/edit#gid=0), when adding title to wishlist "[ Title name ] was successfully added to your Wishlist. / GO TO WISHLIST". The snackbar should be there for 4-5 seconds and the action button in a snackbar should lead to the wishlist. 

- [ ] When title is removed from the Wishlist use the following snackbar text: "[ Title name ] was removed from your Wishlist."

**Film Page**
- [ ] When open a modal with one particular image, we need to add some space at the bottom. Check with @stephanie-cascade8 for the exact space needed. 
![Снимок экрана 2021-09-02 в 10.07.38.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9f71723d-741d-4bb0-8512-e72984355f2a)

- [ ] show the arrows only if there are n+1 image
![Снимок экрана 2021-09-02 в 10.09.49.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4777bbfa-72f9-4115-88f6-e31a43793bca)

- [ ] This Hero section should change accordingly to the[ following ](https://app.zeplin.io/styleguide/5fce4283f696fa5197244ad3/components?coid=60f004838dbc1aafdc89e624 )

from this ![Снимок экрана 2021-09-02 в 10.15.01.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/32942d5a-579e-41f3-bd22-f0a9db1e46c4)

to that ![Снимок экрана 2021-09-02 в 10.20.46.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/aeb79f4a-8720-4bbd-99f9-67f3102d347d)

N.B. Clicking on [ Organization name ] should lead to [ Organization page ].

**Comment by RemcoSimonides** [comment]
*- Page: Title (Movie) View**

- [ ] Problem of vertical alignement, also caused by line-height and margins. 
h1 and h4 should have line-height: 1. 

before 
<img width="1380" alt="Capture d’écran 2021-08-31 à 10 29 07" src="https://user-images.githubusercontent.com/66258851/131470054-178e3d81-6919-40b3-9df5-b2058afa61cd.png">

after
<img width="1347" alt="Capture d’écran 2021-08-31 à 10 30 22" src="https://user-images.githubusercontent.com/66258851/131469989-28a168d0-1be4-4714-9a98-8dc8a871319d.png">

**Comment by phpgeekfr** [comment]
> For some movies Add to Wishlist is not working: (eg Two of Us , BtuMTH5Jik8wruYYZF0A)
> 
> ![image](https://user-images.githubusercontent.com/8731418/131506345-6500455b-b5aa-4faa-ac34-858a6c36a123.png)

Test that, and I did not have any issue

**Comment by phpgeekfr** [comment]
>     * When open a modal with one particular image, we need to add some space at the bottom. Check with @stephanie-cascade8 for the exact space needed.

@stephanie-cascade8 I'm going to put a `padding-bottom: 62px;` on `section` tag. Like this we have the same spacing as top , right & left. Tell me if this as to be changed
