### ISSUE TITLE
User: CRUD

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6528]
- [ ] Auth flow (org + account)
- [ ] Account settings (org + profile + cookies)
- [ ] Delete: CRM

Changes that should be tested
#6382

**Comment by RemcoSimonides** [comment]
Can't go back to landing page when on this page. Clicking the Logo should log the user out and thus navigate back to landing page

<img width="1440" alt="Screenshot 2021-09-01 at 09 17 23" src="https://user-images.githubusercontent.com/27687382/131628895-0ad44f8a-2ed0-4c50-ad9d-80a47195774b.png">

**Comment by RemcoSimonides** [comment]
I requested access to Media Financiers, and I received an email that my request is being processed. Then I went on CRM app and gave appAcces to media financiers, but I never received this email even though this screen says I should. Maybe I used to wrong process to give access but I don't know any other way.
<img width="1438" alt="Screenshot 2021-09-01 at 10 26 08" src="https://user-images.githubusercontent.com/27687382/131638383-f03d5532-b04f-4fc5-ad3c-915c4e6e02b5.png">

**Comment by RemcoSimonides** [comment]
I noticed that there is no way to delete my user in the apps themselves - Isn't this needed to have for GDPR? This would be a feature and not a debug for the release though

But I tried to delete my user from the CRM and nothing happened it seemed. Until I looked in the console and I saw that I can't delete this user because it's the only super admin. Would be nice to show the warning at least.

**Comment by phpgeekfr** [comment]
>     * [ ]  I requested access to Media Financiers, and I received an email that my request is being processed. Then I went on CRM app and gave appAcces to media financiers, but I never received this email even though this screen says I should. Maybe I used to wrong process to give access but I don't know any other way.
> 
> 
> <img alt="Screenshot 2021-09-01 at 10 26 08" width="1438" src="https://user-images.githubusercontent.com/27687382/131638383-f03d5532-b04f-4fc5-ad3c-915c4e6e02b5.png">

maybe you missed to tick the checkbox : 
![image](https://user-images.githubusercontent.com/1194344/131677469-ecda7963-da41-42d1-aef2-4c2b2ca54245.png)

I will make it has checked on page load to prevent this

**Comment by RemcoSimonides** [comment]
> maybe you missed to tick the checkbox :
> ![image](https://user-images.githubusercontent.com/1194344/131677469-ecda7963-da41-42d1-aef2-4c2b2ca54245.png)
>

I did forget it indeed. Good solution
> I will make it has checked on page load to prevent this

**Comment by phpgeekfr** [comment]
> But I tried to delete my user from the CRM and nothing happened it seemed. Until I looked in the console and I saw that I can't delete this user because it's the only super admin. Would be nice to show the warning at least.
(not high priority for release)

Indeed. When you try to remove the last superAdmin from org members you have a message. But you don't have this message if you try to remove user from CRM. Will make the required changes

**Comment by phpgeekfr** [comment]
>     * I noticed that there is no way to delete my user in the apps themselves - Isn't this needed to have for GDPR? This would be a feature and not a debug for the release though

created #6574

**Comment by RemcoSimonides** [comment]
Log In / Account Creation

- [ ] When access the platform via invitation and want to create account, the email is filled in right away, but it takes time that the company information appears (about 4-5 sec). Is it possible to make it appear quicker?

@Bruce not mandatory for release ☝️ only when time left

**Comment by Jackseed** [comment]
- [ ] I tried to request access to an app but never received admin email saying "user x from org y requested access..."

**Comment by phpgeekfr** [comment]
>     * [ ]  I tried to request access to an app but never received admin email saying "user x from org y requested access..."

Just tried now with my latest fixes. Try again once a new deploy to staging is done. It should work

**Comment by phpgeekfr** [comment]
> Log In / Account Creation
> 
>     * [ ]  When access the platform via invitation and want to create account, the email is filled in right away, but it takes time that the company information appears (about 4-5 sec). Is it possible to make it appear quicker?
> 
> 
> @bruce not mandatory for release point_up only when time left

I'm afraid we cannot do anything on this.. This is the time for the backend-function to be instantiated. We could maybe find a way to keep it "hot" but this would result in a lot of resources used for nothing
