### ISSUE TITLE
Org: CRUD, List, View

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6529]
Tester: Antoine
Debugger: Remco

- [x] Public org list
- [x] Public org view (tab Screenings on festival)
- [x] Org filters > test on MF for specific filter
- [x] Delete: CRM

**Comment by Poppe-A** [comment]
_CRM - organization update :_
- spelling mistake
"admin can add **an** remove"

_Public org view :_ 
When clicking on a tab (ex: contact) the page jump up, then goes down after loading the content, but not in the original place.

![jumpBug](https://user-images.githubusercontent.com/35397614/131632095-0ea0452b-3599-4996-a7f6-202ef9fbea79.png)

**Comment by RemcoSimonides** [comment]
Your login issue looks related to this issue #5940 !! Let me know if it happens more often because we haven't been able to reproduce this :S

**Comment by RemcoSimonides** [comment]
I don't fully understand the issue about the page jumps. For me it looks like it just go to the top of the tab. Do you expect the page to scroll to the location where you were previously when you were at the same tab or something?

**Comment by RemcoSimonides** [comment]
**Organization page**
- [ ] When navigating from Line-up to Contact the images are jumping
![organization page.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7bb5f334-5812-49b9-a56d-3a4d04e73855)

N.B. verified on Chrome - no problem detected
