### ISSUE TITLE
Invitations, Notifications & Emails

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6530]
- [ ] Notifications
- [ ] Invitations (screening: check the status of the invitation)
- [ ] Emails => Timezones

Changes that should be tested
#6493
#6370
#6071
#6178

**Comment by Jackseed** [comment]
> ### Media Financiers App
> In Movie 1 (BnZFKrKwXIFQvIX0HqI2) Investment tab, Project Funding > Open Discussion
> 
> ![image](https://user-images.githubusercontent.com/8731418/131695173-745aa3c5-5283-42d7-b202-a55e43be5935.png)
> 
> sends out an email even when other fields are empty.

Thanks, solution here would be to change Message as a mandatory field

**Comment by Jackseed** [comment]
- [ ] I think  was an error during the implementation of #6179: the 2 first lines are to be dedicated to the invitation message and the third one to the invitation date. 
Here the first line is for the invitation message and then the second line introduce event date but it shouldn't be alone on 2nd line, it's included in the notification text. 
![image](https://user-images.githubusercontent.com/14964443/131890645-217af123-dc43-4435-a57e-38777674252e.png)

**Comment by RemcoSimonides** [comment]
**Invitations**
- [ ] the clear filters button is not aligned, if possible would be better to center it. 
![Снимок экрана 2021-09-02 в 10.23.53.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/40248d76-bdd9-4533-8357-744e05da9fb0)

- [ ] if possible, align the Accepted/Declined Status on the right 
![Снимок экрана 2021-09-02 в 10.43.39.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/bd1f42f9-79bd-4ced-8ef3-1bc931ff89c5)

**Notifications**
- [ ] Change "Activity Feed" by "Notifications" 
- [ ] Got two exactly the same notifications at the same time
![Снимок экрана 2021-09-02 в 10.26.41.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/e8a58ce8-2450-4a12-b1d0-73cfdaf6956b)

**Comment by Jackseed** [comment]
Reminder event emails
- [ ] It looks like there is a bug for the 1h reminder. I created 2 events to test it on last Thursday: 
1. Thursday 9:30 PM GMT+2
2. Friday 9:30 PM GMT+2 

And I received the reminders at 8:00 PM GMT+2, ie 1h30 before instead of less than an hour

![image](https://user-images.githubusercontent.com/14964443/132225845-a9721702-25f5-4e9b-a516-edbcbe7f36b0.png)

![image](https://user-images.githubusercontent.com/14964443/132225799-0879ada7-b098-454f-96a3-57840a64cdc3.png)

**Comment by Jackseed** [comment]
**Meeting invitation**
- [ ] The new style for user name with bold breaks event text 
![image](https://user-images.githubusercontent.com/14964443/132229066-4d34e5ae-0564-4b7a-a142-a14048bfb52f.png)
