### ISSUE TITLE
Meetings: File explorers, CRUD, Stats, Privacy, Share documents, Videoconference, Invitations

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6532]
Tester: Mano, Vincent
Debugger: Remco

- [x] Screening form (find someone by the orgname)

Changes that should be tested
#5334

**Comment by RemcoSimonides** [comment]
- [ ] As meeting host can't start videos. I press play and it pauses again almost instantly. Black screen with watermark.

**Comment by xmano** [comment]
Getting 'ownerOrgId' of undefined when navigating to MyCalendar after creating a Meeting event 
![image](https://user-images.githubusercontent.com/8731418/131983341-f7b1680f-9d91-48b9-b633-54e1d46e037a.png)

Steps:
1. Login dev+josue-ldg@blockframes.io (V2aiERoOotZv3BBgp4IkLZPkuaw1)
2. Create a private Meeting event add some files - used The Killing Of Two Lovers > Banner > TKOTL_Still_1.webp & video
3. Invite one user - (dev+claudine-rya@blockframes.io)
4. Save the event
5. Now switch to Buyer's platform and then My Calendar.. I noticed the 'ownerOrgId' of undefined every time.

**Comment by xmano** [comment]
Tracebacks related to JW Player, when starting the meeting at Seller's side:

![image](https://user-images.githubusercontent.com/8731418/131991238-15f8fcfa-4519-4947-ae62-2d5fdb1849b5.png)

1. Related to missing image .. 404s
2. JW Player event related traceback.

**Comment by Jackseed** [comment]
- [ ] If I start a meeting with mic & camera disabled, and then re-enable it during the call, camera will stay black and mic mute
(if camera & mic are enabled at first then disabling/enabling during the call works fine...) 
No sentry error, nor console logs

![Kapture 2021-09-06 at 16 15 43](https://user-images.githubusercontent.com/14964443/132230650-4f8bda82-6e50-4539-a766-502c1695bbaf.gif)

**Comment by Jackseed** [comment]
- [ ] Video sharing is not working

https://user-images.githubusercontent.com/14964443/132231933-5da3407c-df66-45cf-94a7-1fbe18ab244e.mp4

**Comment by RemcoSimonides** [comment]
Created new issue for meeting bug: #6532
