### ISSUE TITLE
CRM: Stats

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6533]
Changes that should be tested
#6326

**Comment by phpgeekfr** [comment]
Created a new account from market and asked for a password reset from CRM with a blockframesAdmin account:
![image](https://user-images.githubusercontent.com/1194344/131481735-1ce63863-4975-4ed9-949d-3528752ef651.png)


Looks like I have the good template and the password change worked well.

**Comment by phpgeekfr** [comment]
@RemcoSimonides maybe the only issue I see is that it says "... to reset your Blockframes **CRM** password" . And also the request was not comming from me. But maybe this is not an issue since Mary will do this only if user is not able to do it on is own ?

**Comment by RemcoSimonides** [comment]
What do you mean with the request wasn't coming from you? You mean it says "Best regards, The Blockframes CRM team" instead?

The text "reset your Blockframes CRM password" should be fixed indeed

**Comment by phpgeekfr** [comment]
> What do you mean with the request wasn't coming from you? You mean it says "Best regards, The Blockframes CRM team" instead

Request was not coming from `eelios+testemail@gmail.com` account but from a CRM user. And the mail says "If this request came from you, please click on the following link"

**Comment by phpgeekfr** [comment]
The mail subject `Blockframes CRM password reset` is also not good.

**Comment by RemcoSimonides** [comment]
- [ ] Can't select user on Users dashboard

**Comment by Jackseed** [comment]
- [ ] Don't know if that has already been changed but indeed we should replace "Blockframes CRM" by "Cascade8" everywhere

**Comment by phpgeekfr** [comment]
>     * [ ]  Don't know if that has already been changed but indeed we should replace "Blockframes CRM" by "Cascade8" everywhere

@Jackseed  Is this mandatory for the release ?

**Comment by RemcoSimonides** [comment]
Fixed it
