### ISSUE TITLE
Landing pages

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6537]
- [ ] Request Demo

**Comment by RemcoSimonides** [comment]
Festival
- [ ] Marie should give updated text for this banner
![image](https://user-images.githubusercontent.com/27687382/131302864-d9e486b9-e901-4ba7-a685-3d4d70719c93.png)

**Comment by maltmayer** [comment]
> Festival
> 
> * [ ]  Marie should give updated text for this banner
>   ![image](https://user-images.githubusercontent.com/27687382/131302864-d9e486b9-e901-4ba7-a685-3d4d70719c93.png)

Here you go:
# 1 
Name: Nate Bolotin
Job Title: Partner
Quote: We use Archipel to recreate the momentum of live market screenings outside markets. It helps generate emulation around our projects and has often led to some interesting bidding wars. 
Company: XYZ Films

# 2
Name: Inès Papo
Job Title: Sales Assistant
Quote: I love working with Archipel. The platform is smooth, the team is available, and most importantly, they understand how this industry works. 
Company: Orange Studio
Logo: https://www.thefilmcatalogue.com/assets/company-logos/242863/LOGO-OS.PNG

**Comment by RemcoSimonides** [comment]
- [ ] Would be nice to have these cards clickable and open the article in a new tab
![image](https://user-images.githubusercontent.com/27687382/131648995-d6885278-4d73-4521-b7d3-82a33b35e16b.png)

**Comment by RemcoSimonides** [comment]
- [ ] Festival: at a certain width the alignment isn't perfect
![image](https://user-images.githubusercontent.com/27687382/131649595-c577048f-a313-44eb-8077-0797e3803de5.png)

**Comment by RemcoSimonides** [comment]
**Review after the updates**

## Environment
**- OS:** MacOS Big Sur (11.5.1)
**- Browser** (& version if possible): Chrome 92.0.4515.159 

### Landing Page 
- [ ] _Welcome to Archipel Market_ should be in capitals 
![Снимок экрана 2021-08-31 в 12.04.10.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/902d8185-963e-4b53-9cf3-122aeeeedfb9)

- [ ] Add the * for the required fields in the "Want to learn more" section. 
Fields concerned: 
First Name *
Last Name *
Company Name * 
Role * 
Email Address * 

- [ ] New footer is missing 

- [ ] When the form is successfully sent, following [the snackbars inventory](- [ ] Following the [snackbars inventory](https://docs.google.com/spreadsheets/d/11mgu0-s9i0KIBRgRUAlE-WjuJQLOaTmMcdrVLEUKwAk/edit#gid=833953278)
) change the snackbar text from _Your request has been sent!_ to _Request sent._

**Comment by Jackseed** [comment]
- [ ] Tried 3 times to request a demo but didn't get any email as admin. mb I'm checking wrong email address but it looks like email is not sent

**Comment by RemcoSimonides** [comment]
### Localization
- App name: **Media Financiers**
**- Page: Home**

- [ ] Img disappeared ? It doesn't seem to be a problem of loading, but I'm not sure.
<img width="1434" alt="Capture d’écran 2021-08-31 à 10 59 44" src="https://user-images.githubusercontent.com/66258851/131474524-f0abf9cd-6fef-4c5c-bce2-55f123f7f73a.png">

**Comment by RemcoSimonides** [comment]
Archipel Content:
- [ ] Space and line-height are wrong in the header. 
h1: line-height should be 1.
margin-top: 24px;
margin-bottom: 24px;

before
<img width="778" alt="Capture d’écran 2021-08-31 à 10 26 09" src="https://user-images.githubusercontent.com/66258851/131469194-60f8ff9c-524f-4dab-bfbf-fdfe54035163.png">

after
<img width="1215" alt="Capture d’écran 2021-08-31 à 10 26 00" src="https://user-images.githubusercontent.com/66258851/131469301-e749c818-60cf-4f8d-b396-278a7c6dbf3c.png">

**Comment by RemcoSimonides** [comment]
Created new issue for left-over tickboxes:
#6641
#6642

**Comment by phpgeekfr** [comment]
>     * [ ]  Tried 3 times to request a demo but didn't get any email as admin. mb I'm checking wrong email address but it looks like email is not sent

Email is sent, just tried on my local.
But what you could do @Poppe-A  is to remove the unsubscribe link : 
![image](https://user-images.githubusercontent.com/1194344/132650859-0597c37b-4f58-48b1-8d11-cf263821717a.png)

I suggest that you first take a look yourself to find out how (there are existing examples on the repo)
