### ISSUE TITLE
Review Staging UI

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#6547]

**Comment by RemcoSimonides** [comment]
## Your environement
_Please describe your environment_ 
- OS:
- Browser (& version if possible):

## Review item
_Copy & fill this section for each item._
### Localization
- App name: 
- Page:
- Url: 
- User used (if anonymized):

### Context
_Explain what leads you to this situation_

### Fix
_What would be for you the correct behaviour_

### Steps to reproduce
_If there is an action sequence, please describe it_

### Images
_Add any relevant images or videos_

**Comment by stephanie-cascade8** [comment]
### Localization
- App name: **Archipel Content**
**- Page: Home**

- [ ] Header background-img missing?
<img width="1303" alt="Capture d’écran 2021-08-31 à 10 16 38" src="https://user-images.githubusercontent.com/66258851/131467898-8cb4c932-55dc-4d05-a055-5fcf33444dde.png">

- [ ] Space and line-height are wrong in the header. 
h1: line-height should be 1.
margin-top: 24px;
margin-bottom: 24px;

before
<img width="778" alt="Capture d’écran 2021-08-31 à 10 26 09" src="https://user-images.githubusercontent.com/66258851/131469194-60f8ff9c-524f-4dab-bfbf-fdfe54035163.png">
after
![Uploading Capture d’écran 2021-08-31 à 10.26.00.png…]()

**Comment by stephanie-cascade8** [comment]
### Localization
- App name: **Media Financiers**
**- Page: Home**

- [ ] Img disappeared ? It doesn't seem to be a problem of loading, but I'm not sure.
<img width="1434" alt="Capture d’écran 2021-08-31 à 10 59 44" src="https://user-images.githubusercontent.com/66258851/131474524-f0abf9cd-6fef-4c5c-bce2-55f123f7f73a.png">

**Comment by RemcoSimonides** [comment]
> **- Page: Sales Agents List**
> 
> * [ ]  Can we have the magnifying glass icon inside the search field ?
> 
> <img alt="Capture d’écran 2021-08-31 à 10 38 40" width="859" src="https://user-images.githubusercontent.com/66258851/131471067-bfcabd17-52ff-406e-8ca5-6d2c1b7835a9.png">

No, but we can remove the icon. Titles page doesn't have it either :)
