### ISSUE TITLE
ARCHIPEL MARKET Marketplace Screening List - loading issue

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#6548]
- [ ] the screening took over a minute to load
- [ ] when it finally loads, the screening image is displayed and then disappears...

https://user-images.githubusercontent.com/55785823/131360434-53a0fb9e-0c82-4a96-a101-71eb3f912dd7.mov

**Comment by RemcoSimonides** [comment]
I cannot reproduce this error and also I don't see any recent changes about this page. Let me know if this keep occuring. Otherwise I'd say that there was an internet or connection issue with firebase

**Comment by xmano** [comment]
Tried the test on tile : "The Killing of Two Lovers" in 2 different ways, it is basically slow but does play:


https://user-images.githubusercontent.com/8731418/131677628-7ebf8879-e0ae-432c-ab47-29bea4a11ce5.mp4

**Comment by maltmayer** [comment]
> Tried the test on tile : "The Killing of Two Lovers" in 2 different ways, it is basically slow but does play:
> 
>  playback.mp4 
> Will try with that specific title and check if we can recreate.

The issue is on the poster image, not the video. I keep getting a list of components without posters (on prod)
![image](https://user-images.githubusercontent.com/55785823/131679684-24407c23-f434-4c07-a859-e7e9c118aecf.png)
 @RemcoSimonides knows all about the issue I think :)

**Comment by xmano** [comment]
> > Tried the test on tile : "The Killing of Two Lovers" in 2 different ways, it is basically slow but does play:
> > playback.mp4
> > Will try with that specific title and check if we can recreate.
> 
> The issue is on the poster image, not the video. I keep getting a list of components without posters (on prod)
> ![image](https://user-images.githubusercontent.com/55785823/131679684-24407c23-f434-4c07-a859-e7e9c118aecf.png)
> @RemcoSimonides knows all about the issue I think :)

Ah got it .. I mistook this for video issue. Will check screening posters

**Comment by xmano** [comment]
For me as of now the screening list has poster images displayed. Will keep a watch if there are any issues:

![image](https://user-images.githubusercontent.com/8731418/131680756-35437afd-c859-462e-bceb-4117b0d7010b.png)

**Comment by RemcoSimonides** [comment]
Hee @maltmayer, curious if this still encounter this issue even after the last release
