### ISSUE TITLE
Review Archipel Market 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6549]
## Environment
**- OS:** MacOS Big Sur (11.5.1)
**- Browser** (& version if possible): Chrome 92.0.4515.159 

### Sign Up (Cross-App)
**The two following issues concern the update of links/buttons**. Need to verify with UI team and be assured that we are ready for this update. Update should be common, not isolated (Verify with @jdrns and @stephanie-cascade8). 

- [x]  Following [this documentation](https://www.notion.so/cascade8/Links-vs-Buttons-275bc1c81ee04cae98511bdc487a7b52) update the links in this part
![Снимок экрана 2021-08-31 в 08.44.04.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1ef1d05f-b126-47b2-a811-7a11a4bad1d1)

- [x] Check the links documentation for this part also 
![Снимок экрана 2021-08-31 в 08.46.58.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/74e97538-4802-4f0e-bbbe-fc4ce3d8beae)

Checked on Firefox (91.0.2) to avoid blocking on the page : 
- [x] Managed to Sign up, even if user hasn't entered the company name 
![company.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7f70c338-3d9b-4647-83e3-089f1b02874e)

**Comment by 2amarkina** [comment]
## Environment
**- OS:** MacOS Big Sur (11.5.1)
**- Browser** (& version if possible): Chrome 92.0.4515.159 

### Marketplace

**Toolbar / Cross-App**
- [ ] Following [this issue](https://github.com/blockframes/blockframes/issues/6227) make the label (the user's name) and the avatar clickable 
![Снимок экрана 2021-08-31 в 09.18.51.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/0e9205ac-78e8-464e-9648-d5b1d1c48736)

**Comment by 2amarkina** [comment]
**Review after the updates**

## Environment
**- OS:** MacOS Big Sur (11.5.1)
**- Browser** (& version if possible): Chrome 92.0.4515.159 

### Landing Page 
- [ ] _Welcome to Archipel Market_ should be in capitals 
![Снимок экрана 2021-08-31 в 12.04.10.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/902d8185-963e-4b53-9cf3-122aeeeedfb9)

- [ ] Add the * for the required fields in the "Want to learn more" section. 
Fields concerned: 
First Name *
Last Name *
Company Name * 
Role * 
Email Address * 

- [ ] The checkbox to Subscribe to newsletter is missing in "Want to learn more" section 

- [ ] New footer is missing 

- [ ] When the form is successfully sent, following [the snackbars inventory](- [ ] Following the [snackbars inventory](https://docs.google.com/spreadsheets/d/11mgu0-s9i0KIBRgRUAlE-WjuJQLOaTmMcdrVLEUKwAk/edit#gid=833953278)
) change the snackbar text from _Your request has been sent!_ to _Request sent._

**- Browser** (& version if possible): Safari 14.1.2 (16611.3.10.1.3) 
- [ ] Following [this issue ](https://github.com/blockframes/blockframes/issues/6455#issuecomment-909061803) concerning the representation of the logos on different browsers, the logo of AM on Safari is blured 
![Снимок экрана 2021-08-31 в 12.39.49.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/18c3aea6-991d-4121-abf2-8651ac8a8ea9)

## Environment
**- OS:** MacOS Big Sur (11.5.1)
**- Browser** (& version if possible): Chrome 92.0.4515.159 

### Toolbar (cross-app)
- [ ] Before the updt. the Name of the user was aligned, but now no (cf screenshot). Is it due to the fact that label is clickable now? Is it because the space below is dedicated to Role? Can we align the text if the role is not filled in? 
![Снимок экрана 2021-08-31 в 12.48.30.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/df8c2127-02ea-4a4c-86a1-f2bc1e8b46f2)

**Comment by 2amarkina** [comment]
## Environment
**- OS:** MacOS Big Sur (11.5.1)
**- Browser** (& version if possible): Safari 14.1.2 (16611.3.10.1.3)

account used: Estevan Murray

### Marketplace

**Titles page**
- [ ] Cross App: According to the [snackbar inventory](https://docs.google.com/spreadsheets/d/11mgu0-s9i0KIBRgRUAlE-WjuJQLOaTmMcdrVLEUKwAk/edit#gid=0), when adding title to wishlist "[ Title name ] was successfully added to your Wishlist. / GO TO WISHLIST". The snackbar should be there for 4-5 seconds and the action button in a snackbar should lead to the wishlist. 

- [ ] When title is removed from the Wishlist use the following snackbar text: "[ Title name ] was removed from your Wishlist."

**Film Page**
- [ ] When open a modal with one particular image, we need to add some space at the bottom. Check with @stephanie-cascade8 for the exact space needed. 
![Снимок экрана 2021-09-02 в 10.07.38.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9f71723d-741d-4bb0-8512-e72984355f2a)

- [ ] show the arrows only if there are n+1 image
![Снимок экрана 2021-09-02 в 10.09.49.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4777bbfa-72f9-4115-88f6-e31a43793bca)

- [ ] This Hero section should change accordingly to the[ following ](https://app.zeplin.io/styleguide/5fce4283f696fa5197244ad3/components?coid=60f004838dbc1aafdc89e624 )

from this ![Снимок экрана 2021-09-02 в 10.15.01.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/32942d5a-579e-41f3-bd22-f0a9db1e46c4)

to that ![Снимок экрана 2021-09-02 в 10.20.46.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/aeb79f4a-8720-4bbd-99f9-67f3102d347d)

N.B. Clicking on [ Organization name ] should lead to [ Organization page ].

- [ ] For the Hero section, change the text when a user has already applied for the session 
From this 
![Снимок экрана 2021-09-02 в 10.52.36.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/6ad58109-dd3f-41e6-9bc2-b44ee869db2c)

To that 
![Снимок экрана 2021-09-02 в 10.52.58.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/c0828f81-08b2-48be-988b-30fbe2d4503f)

- [ ] Also, verify with @stephanie-cascade8 if we put the "ongoing screening" element into the Hero section, as shown on [this mock-up](https://app.zeplin.io/styleguide/5fce4283f696fa5197244ad3/components?coid=60e5b9ed07325d05bb6e05a5) + screenshot below
![Снимок экрана 2021-09-02 в 10.54.49.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/6c063b42-fbea-40e6-8538-64623b91490d)


 

**Invitations**
- [ ] the clear filters button is not aligned, if possible would be better to center it. 
![Снимок экрана 2021-09-02 в 10.23.53.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/40248d76-bdd9-4533-8357-744e05da9fb0)

- [ ] if possible, align the Accepted/Declined Status on the right 
![Снимок экрана 2021-09-02 в 10.43.39.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/bd1f42f9-79bd-4ced-8ef3-1bc931ff89c5)

**Notifications**
- [ ] Change "Activity Feed" by "Notifications" 
- [ ] Got two exactly the same notifications at the same time
![Снимок экрана 2021-09-02 в 10.26.41.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/e8a58ce8-2450-4a12-b1d0-73cfdaf6956b)

**Organization page**
- [ ] When navigating from Line-up to Contact the images are jumping
![organization page.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7bb5f334-5812-49b9-a56d-3a4d04e73855)

N.B. verified on Chrome - no problem detected

**Meetings Module**
- [ ] During the test with @frenchyrules we remarked that the video couldn't be played 

- [ ] It takes quite a long time loading the video of other user. We waited about 7-9 sec. Not sure if this can be reduced? 
N.B. it took less time for the second test. 

**Log In / Account Creation**
- [ ] When access the platform via invitation and want to create account, the email is filled in right away, but it takes time that the company information appears (about 4-5 sec). Is it possible to make it appear quicker?

**Comment by 2amarkina** [comment]
## Environment
**- OS:** MacOS Big Sur (11.5.1)
**- Browser** (& version if possible): Safari 14.1.2 (16611.3.10.1.3)
profile used: Karolann Adams


### Dashboard
**Movie Tunnel** 
- [ ] Animation problem. As you can see on gif when we navigate to the next page, then animation effect comes from right to left. If we go to the previous page - then from left to right. This process is not ok between Additional And Shooting information 
![movie tunnel.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/ae99fd2a-5220-4238-a2dc-0f21861dbf11)

**Screening Creation Page** 
- [ ] The time setting is not not it's usual place (only Safari problem, everything ok on Chrome)
Safari problem 
![Снимок экрана 2021-09-02 в 11.19.45.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4baf15f7-ddac-4609-b9ee-370a1413bcf3)

Chrome OK
![Снимок экрана 2021-09-02 в 11.23.19.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/ddffeab1-4480-4620-bc62-605d04e6fbfd)

- [ ] Also, the typography is not ok on Safari (see the previous screenshots)

- [ ] Add a tooltip on the sending invitations icon. Tooltip text: Send invitations.
![Снимок экрана 2021-09-02 в 11.24.31.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/5f722a67-6fd3-4ad4-a47d-ab893c32b6fe)

**Screening Room**
- [ ] @stephanie-cascade8 Not sure but to verify, the necks of little people on the illustration are blue, is in ok ? 

- [ ] @stephanie-cascade8 Also remarked a little line on the chair 
![Снимок экрана 2021-09-02 в 11.26.34.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/e466d14c-df44-4ddf-9de3-71f44b1a1c5f)

- [ ] @stephanie-cascade8 and also on the same image, some chair lines pass over the heads 
![Снимок экрана 2021-09-02 в 11.35.53.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9c54a21b-8548-4dc5-84bf-234a0d4eda55)

**Meeting Room**
- [ ] @stephanie-cascade8 i guess we are missing feet of these two little people 
![Снимок экрана 2021-08-31 в 17.35.49.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/5f295f48-e4ab-460d-98fa-1f63a2e12ad6)

**Comment by RemcoSimonides** [comment]
> **Movie Tunnel**
> 
> * [ ]  Animation problem. As you can see on gif when we navigate to the next page, then animation effect comes from right to left. If we go to the previous page - then from left to right. This process is not ok between Additional And Shooting information
>   ![movie tunnel.gif](https://camo.githubusercontent.com/8bdfe7deed675dde233c8d68fa5bb92cbaf0375def724b65c02401af17e0cd3d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f61653939666432612d353232302d343233382d613264632d306632313836316462663131)

Gif isn't working

**Comment by RemcoSimonides** [comment]
> * [ ]  For the Hero section, change the text when a user has already applied for the session
>   From this
>   ![Снимок экрана 2021-09-02 в 10.52.36.png](https://camo.githubusercontent.com/a01b5c24b00bea068fbde6d2393840c73471dd93cba8447bcf52347f110df6bc/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f36616435383130392d646433662d343165362d396263322d623434656538363964623263)
> 
> To that
> ![Снимок экрана 2021-09-02 в 10.52.58.png](https://camo.githubusercontent.com/98941b4ff61b46a5c0138150c5b6f5dda0ac2bed3692ed748dc9066a64047b28/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f63303832386638312d303862322d343862652d393838622d333066626532643435303366)
> 
> * [ ]  Also, verify with @stephanie-cascade8 if we put the "ongoing screening" element into the Hero section, as shown on [this mock-up](https://app.zeplin.io/styleguide/5fce4283f696fa5197244ad3/components?coid=60e5b9ed07325d05bb6e05a5) + screenshot below
>   ![Снимок экрана 2021-09-02 в 10.54.49.png](https://camo.githubusercontent.com/862b1585b509f304df0569486a78a95826da8405632bcf92c2db1cc241a42719/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f36633036336234322d666265612d343065362d383533382d363436323362393134393064)
> 

Open issue #6247

> **Notifications**
> 
> * [ ]  Change "Activity Feed" by "Notifications"
Open issue #6251

**Comment by RemcoSimonides** [comment]
> * The checkbox to Subscribe to newsletter is missing in "Want to learn more" section

Leaving this out of the release because it requires some work to create this feature. Discussed with Stephanie and it was ok to leave it for now.

**Comment by 2amarkina** [comment]
> > **Movie Tunnel**
> > 
> > * [ ]   Animation problem. As you can see on gif when we navigate to the next page, then animation effect comes from right to left. If we go to the previous page - then from left to right. This process is not ok between Additional And Shooting information
> >   ![movie tunnel.gif](https://camo.githubusercontent.com/8bdfe7deed675dde233c8d68fa5bb92cbaf0375def724b65c02401af17e0cd3d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f61653939666432612d353232302d343233382d613264632d306632313836316462663131)
> 
> Gif isn't working

Here it is 
![movie tunnel](https://user-images.githubusercontent.com/55499036/131969978-4487b963-08bb-4c35-b56c-8c258efea8df.gif)
