### ISSUE TITLE
Dashboard avails Specs

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6552]
#### Context
Currently buyers are the only one able to look for titles' avails. It means that sellers can't even look at their own avails. 
It's all the more annoying that they can't even create it since, for now, we as admin can only create it through the sales import. Last but not least, once created we can't modify or a delete a sale except through firebase. 

#### Objectives
This new feature has 2 main objectives:
- let sellers list, view, create, modify and delete their pre-existing sales and mandates (fundamentals to create avails cf #4996) 
- let sellers search for avails on all their titles (avails filter) or a specific one (calendar & worldmap #5573)

#### Warning
Mandates and sales that are created this way must be differentiated from the ones created through marketplace. The main difference is the presence of Archipel Content / Cascade8 as a stakeholder. 
To be clear it means that we'll have 2 sort of contracts: the ones from outside the platform (without AC) and the others from within (with AC). 

**/!\ This will imply a super important difference /!\\**
- when a buyer is looking for title's avails within marketplace we compare **AC's mandate** with every existing sales on this title
- when a seller will be looking for its title's avails within dashboard, we shall compare **its own mandate on this title** with every existing sales on this title
cc @GrandSchtroumpf 

### User scenarii
- Seller can import contracts
- Seller can create contracts
- Seller can modify contracts
- Seller can delete contracts
- Seller can list contracts
- Seller can view contracts
- Seller can look for a title's avails
- Seller can search for multi titles' avails

### What's new
- Contract list will also list contracts from outside the platform
- CRUD for sellers
- Avails search for sellers (algo a bit different from marketplace, cf. Warning)

**Comment by pldespaigne** [comment]
Spec has been detailed in #6692 & #6709
