### ISSUE TITLE
[Release Test] Avails: Create, Delete, View

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6553]
Tester: Francois
Debugger: Springfield

### To test
Avails filter
Add to selection button
Cards on selection page
World map view 
Calendar view

Please write down what else you tested so I can add it to this issue next release

**Comment by GrandSchtroumpf** [comment]
# [Page Avails](https://staging.archipelcontent.com/c/o/marketplace/title/NnhsksCPbqMRzux0hPiT/avails) 
- [ ] Error in form not updated
![image](https://user-images.githubusercontent.com/8143464/131648421-f0100842-ca14-48cf-a28f-bf30db8dffe1.png)
How to reproduce: 
- Set start to 9/1/2021 & end to 9/30/2021
- Set start to 10/31/2021
- Set end to 10/1/2021
- Set back state to 9/1/2021
- The error on end should have disappeared too, but it doesn't. Some kind of change detection issue. Maybe an ErrorStateMatcher...

- [ ] runs should not accept negative numbers
![image](https://user-images.githubusercontent.com/8143464/131646876-cf4f4c67-d42d-462a-8531-911ccdc509d8.png)

# Page Selection
- [ ] Currency in total doesn't update on local change. You have to (blur) the input to see a change
![image](https://user-images.githubusercontent.com/8143464/131650488-9edbed87-daf7-47fa-a82a-a48000dc2429.png)

## Holdback Dialog
- [ ] Territory & media don't have error message
![image](https://user-images.githubusercontent.com/8143464/131651029-c5e63a56-e1fc-4021-86a3-ac644415dcd4.png)

- [ ] Date should display error when `start` is after `end` & vice versa
![image](https://user-images.githubusercontent.com/8143464/131650729-71cbdc6c-fcf4-4603-b9c7-83353542f605.png)

- [ ] Remove version in the table
![image](https://user-images.githubusercontent.com/8143464/131651229-058c7ece-81b5-4d45-ba32-3ad59ceda364.png)

**Comment by Jackseed** [comment]
- [ ] Existing holdbacks modale: change text for
Title: Holdbacks exist for this Right _(capital R on Right)_
Text: "There are some holdbacks that exist for this Right.
You can still add this Right to your Selection."
(no s for exist, capital R & S for Right & Selection)
Table title: Existing Holdbacks
![image](https://user-images.githubusercontent.com/14964443/131887793-f32ca507-d9b5-48a0-b4d9-e1e7f76c916b.png)
