### ISSUE TITLE
Review Archipel Market

### ISSUE THREAD

**Issue by frenchyrules** [blockframes/blockframes#6566]
### Environment - OS: Windows 10 Pro 64 bits version 20H2
- Browser: Chrome version 93.0.4577.63

### Archipel Market
Profile used: Rosario Gottlieb
Light mode

**Home page**

- [ ] Empty featured sales agents section - here bug happened when clicking on "see all", and then going back to homepage.
![image](https://user-images.githubusercontent.com/85220905/131866733-6dcb23ca-86f5-49df-9f81-13e3a8f51ca1.png)

- [x] This carousel feels huge, take ups the entire screen + some vertical scroll room before you have seen the entire section. --> reduce box height ?
![image](https://user-images.githubusercontent.com/85220905/131869049-07a0fa9f-6e3b-491a-ae4e-947cd6289729.png)

- [ ] _View more_ overlay text can be difficult to read depending on background image --> Try a lighter overlay
![image.png](https://images.zenhubusercontent.com/611a265d2ea95c7880c91192/7cd6ecaf-3d39-4894-8e88-ee315856c7ca)

- [ ]  Scroll arrows can be difficult to see depending on the image shown behind it
![image.png](https://images.zenhubusercontent.com/611a265d2ea95c7880c91192/2d77d0a1-05c0-42aa-8c8f-4608ef07f102)
By making the grey circle less transparent and adding a white linear gradient to the right/left (depending on the direction of the movement), the arrow "pops" a lot more
<img width="201" alt="Screenshot 2021-09-06 at 16 24 22" src="https://user-images.githubusercontent.com/85220905/132231895-4cde5ae6-e9d7-4906-8e2f-fffdd7f3364f.png">

**Meeting**

- [ ]  As meeting host can't start videos. I press play and it pauses again almost instantly. Black screen with watermark. Invite takes some time to send (users: Rosario + Moris). Not sure if related but in private navigation invite sending was almost instant (users: Jeffery + nat)

**Titles**

- [ ]  After clicking on an individual movie, I scrolled down and checked out the tabs “Main” and “Upcoming screenings”. I switched back and forth a few times. I then scrolled back up and clicked back to go back to the main titles page and to my surprise it went back, back and forth between each tab until I reached the titles page again, which felt slightly annoying.
![image](https://user-images.githubusercontent.com/85220905/131688263-8b813249-02e6-458a-bcee-574c7e027f80.png)

- [ ] The number here may be an accessibility issue for certain people due to it’s low contrast and thin font style (dark mode)
![image](https://user-images.githubusercontent.com/85220905/131688786-e11acb4c-7a6c-4c64-a04d-21cc2fc1d909.png)

- [ ] I wrote a word like “comedy”, and instead of clicking on the proposal for “comedy” as it pops up, I instinctively clicked save instead, and it doesn’t take you to comedy unless you click on the popup word comedy. Save button feels like it doesn’t do anything as choices are already updated as soon as you select a keyword.

Because of the way I input a word manually instead of clicking on a suggested term that pops up, the clear button loses its purpose as it only works when you click on a specific term.
![image](https://user-images.githubusercontent.com/85220905/131689817-9913b89a-3918-4c19-aab9-af52f5a0d9bb.png)

**My titles - dashboard**
- [ ]  Too many icons to say the same thing; keep the arrow icon but remove the 3 dots ? 
![image](https://user-images.githubusercontent.com/85220905/131689445-572af4ba-7877-4a7e-a1f5-8567d0920e3c.png)

**Comment by RemcoSimonides** [comment]
Hee @frenchyrules , would be nice if you can propose a solution too so the developers know what to change it to.

The bug you have regarding the video in meetings is a bug. I'm looking into it.
The improvement we can make with navigating back after clicking on tabs is already an open issue and will be solved one day ;) #6369

**Comment by 2amarkina** [comment]
**Dedicated issues created:** 

[Simplify actions box #6740 ](https://app.zenhub.com/workspaces/design---ui-60ab5f96c64ec50014c46754/issues/blockframes/blockframes/6740)

[Slider component #6739](https://app.zenhub.com/workspaces/design---ui-60ab5f96c64ec50014c46754/issues/blockframes/blockframes/6739)

[Scroll arrows difficult to see #6738](https://app.zenhub.com/workspaces/design---ui-60ab5f96c64ec50014c46754/issues/blockframes/blockframes/6738)

**Comment by RemcoSimonides** [comment]
Thanks Ana :) can we close this one then?
