### ISSUE TITLE
Catalog Dashboard - Permission issue

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6575]
url: https://staging.archipelcontent.com/c/o/dashboard/home / https://staging.archipelcontent.com/c/o/dashboard/title
user: dev+carmella-rtq@blockframes.io
browser: brave

I'm trying to log in with a user with tens of movies on catalog but got permission issues on dashboard home & title list, only contracts load

**Comment by phpgeekfr** [comment]
The org (`IWWJ6eLjnYqGd0odKize`) linked with this userId  is missing `documentPermissions` sub-collection on `permissions` document.

The rules needs it to access analytics data if `analytics/movieId` document exists :
```
    match /analytics/{docId} {
      allow read: if userHasValidOrg()
        && notInMaintenance()
        && ( resource == null
          || (existingData().type == 'movie' && orgCan('canUpdate', userOrgId(), docId))
        );
    }
```

I will try to create a new movie to check if `documentPermissions` is created.  One of the movies in error (`2zm7lVUURlfDUaZmI2Ec`) is pretty new.

I will also check if there is other movies in that situation.

**Comment by Jackseed** [comment]
This org has been created with the org import; maybe that's related?

**Comment by phpgeekfr** [comment]
New movie creation correctly added the sub collection. I will look at import issue as @Jackseed suggested

**Comment by phpgeekfr** [comment]
Solved, when importing movies for this org, field `user Owner Id` was not specified & movie.orgIds was updated manually to correct error. But documentPermissions was not updated

**Comment by phpgeekfr** [comment]
It does not look to be linked to #6489 afterall

**Comment by Jackseed** [comment]
Problem solved manual update on documentPermissions 👍
