### ISSUE TITLE
AC - Use "World" and "World excluding..."

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6576]
Currently when a buyer selects all the countries it's hard to read. Worst, if only one country is missing, it's almost impossible to see it. 
We should have a rule that replace all countries by "World" and if a few amount of countries is missing, we use "World excluding..." instead of the full list of countries. 
Territory modale should stay as it is with the full list of countries if needed.

![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/dd441d0c-c9dd-4d42-8792-588f05b88aa6)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/449dec31-d526-45de-a671-c9540baf5f20)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/60eab977-6814-4175-a014-754916291372)

**Comment by RemcoSimonides** [comment]
Estimation
UX: 4 days
UI: 1 day

**Comment by 2amarkina** [comment]
[Wireframes are accessible here](https://www.figma.com/file/79BGwNLKjmH7QH1tgH50o3/%5B-World-%5D)

**Comment by 2amarkina** [comment]
- [ ] Inventory of use cases with prototypes

**Comment by stephanie-cascade8** [comment]
Hey @jackseed @cams-goussale @2markina, tell me what you think.
[Whole page Mockup ](https://www.figma.com/file/l9BpFo1XbEZqTGTLaaAI10/Titles?node-id=150%3A1205)WIP here

<img width="762" alt="Capture d’écran 2022-01-26 à 17 27 06" src="https://user-images.githubusercontent.com/66258851/151204519-461ecc78-3653-4182-8104-da3b67a1bef9.png">

**Comment by cams-goussale** [comment]
Should we put capital letter to `Including` `Excluding` ? I am really not sure, so I can ask Marie if needed.
Is there any possibility to have the typo of these 2 words a bit smaller?
Otherwise lgtm

**Comment by stephanie-cascade8** [comment]
> Should we put capital letter to `Including` `Excluding` ? I am really not sure, so I can ask Marie if needed. Is there any possibility to have the typo of these 2 words a bit smaller? Otherwise lgtm

yeah I have a smaller range, you're right it will be better. Ok I'll ask Marie ;)

**Comment by stephanie-cascade8** [comment]
Here is what it looks like with cap letters and smallest typo.
@maltmayer is it good with the cap letter ? And since you're here now, what do you think of this design?

<img width="795" alt="Capture d’écran 2022-01-27 à 11 13 46" src="https://user-images.githubusercontent.com/66258851/151339253-39f9bc8c-ea8d-4bb9-b8f7-3a8527b427fe.png">

**Comment by cams-goussale** [comment]
I like it! Well done. Good for me

**Comment by stephanie-cascade8** [comment]
> I like it! Well done. Good for me

Just in case, can we have a dev confirm that we can:
- use chips with an icon on the left in this special case (knowing that in case it's a country there will be no icon) 
- reduce the opacity on the excluded chips (that's what makes kind of a hierarchy effect here).

**Comment by phpgeekfr** [comment]
If all world is sectioned, is this the expected display ? 
![image](https://user-images.githubusercontent.com/1194344/160361439-7c812114-3090-437c-8667-1a56990a1404.png)

**Comment by 2amarkina** [comment]
If all World is chosen we should not display "excluding" at all
