### ISSUE TITLE
Deal notification flow

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6578]
Currently the only notification that exists related to deals is for the buyer when s/he creates an offer. 

We should add notifications along the flow, let's agree on when and to whom. 

An issue is already there for sellers receiving an offer #6577

**Comment by 2amarkina** [comment]
This issue should be done according to the whole Deal Negotiation process. 

Some propositions can be already started.

**Comment by 2amarkina** [comment]
[Actual document about notifications ](https://docs.google.com/spreadsheets/d/1DCO2PH0HaSnt3y6DSPnIX6hXbGsaCw10tCR38gG8LyM/edit#gid=0)

- [ ] Check if it's up-to-date

**Comment by Jackseed** [comment]
@2amarkina I merged notification list with emails since now they are tied together with the notification settings. 
It's not completely up-to-date but better than the one you linked. [It's over here](https://docs.google.com/spreadsheets/d/1b1K7YfnquxnfCgGGPxIz5ZNIjr9eK_bUrRJqLvPYGIk/edit#gid=97734814)

**Comment by 2amarkina** [comment]
[Proposition of flows + texts](https://www.figma.com/file/HsorzxuXtd89Seqj5jvFeK/Deal-notifications?node-id=0%3A1)

After business validation can be added to the Excel document.

**Comment by 2amarkina** [comment]
- [ ] Validate the texts with Marie and Yuki

**Comment by 2amarkina** [comment]
**[All the notification texts can be found here](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=0)** for easier access.
