### ISSUE TITLE
Be able to change movie.orgIds[] from CRM to avoid manual updates

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#6579]
Be able to change `movie.orgIds[]` from CRM to avoid manual updates.

Need to:

- change movie.orgIds[]
- create new `permissions/orgId/documentPermissions` document for new org(s)
- remove `permissions/orgId/documentPermissions` in previous one(s) 
- other things to think about ?

CF #6489

**Comment by phpgeekfr** [comment]
idea: use a backend function trigger `onMovieUpdate`. Like this, even if update is done in DB manually, it will be ok.

**Comment by RemcoSimonides** [comment]
Should CRM support entering multiple orgIds or do we keep only 1 orgId for now?

**Comment by phpgeekfr** [comment]
Right now I think we always have only 1 org in this array. @Jackseed can you confirm ?

**Comment by Jackseed** [comment]
Indeed we have only one but the whole system is built to accept more than one and with the rise of catalog it could happen more and more so we should keep with solution that works with an array

**Comment by RemcoSimonides** [comment]
So you should be able to enter multiple orgIds in CRM. Correct me if I understood wrong.

**Comment by Jackseed** [comment]
Ideal would be to add or remove any orgIds indeed
