### ISSUE TITLE
Design new password page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6604]
This page should stay as simple as the one used to ask for a password reset, ie a title, an illu, input and button. 
This page should have 3 states:
- form state (user has to fill in new password)
- success state (new password saved)
- error state (page expired or already used; text: Try resetting your password again
Your request to reset your password has expired or the link has already been used)

Current new password page (default from Google)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/9c3471e6-c5f0-4f97-90f4-52670756b503)

Current password reset page
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/030f65c5-0ce8-448e-9f59-17b0dc55f4f7)

**Comment by cams-goussale** [comment]
@dmoncadalv can you add your WIP mockup links to the issue?

**Comment by dmoncadalv** [comment]
[WIP UI Mockups](https://www.figma.com/file/ODvbgSYOb0OyVK6WWVp3NU/Log-in%2FSign-up?node-id=305%3A1230)
