### ISSUE TITLE
Remake toolbar on mobile versions

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#6613]
- [ ] Login/signup button come outside of screen, slight horizontal scroll. left margin small
![File](https://user-images.githubusercontent.com/85220905/131811963-687208eb-d93d-49e2-b053-597bf69ddf81.jpg)

**Comment by Jackseed** [comment]
This should be done at the same time that UX will work on nav bar & sidenav

**Comment by stephanie-cascade8** [comment]
UI: 3 days

**Comment by 2amarkina** [comment]
I guess @stephanie-cascade8 has already started the work on it[ here](https://app.zeplin.io/project/5f3100d317a0041be2ad99c4/screen/61b8cb7d7e36025fdf0d9464) inside this[ issue ](https://app.zenhub.com/workspaces/design---ui-60ab5f96c64ec50014c46754/issues/blockframes/blockframes/7194)

**Comment by cams-goussale** [comment]
@stephanie-cascade8 @frenchyrules we are closing this issue as it is done with #7194

**Comment by cams-goussale** [comment]
Screens are [here](https://www.figma.com/file/AkPrTIPD10O3mjuuwgDsxn/Responsive-Global-View?node-id=37%3A1307)

@frenchyrules @stephanie-cascade8 we didn't talk about this this morning (i forgot). Do you think we could prioritize this so I can send it to dev asap?

**Comment by RemcoSimonides** [comment]
Toolbar is responsive for landing page now but not yet for other pages

**Comment by stephanie-cascade8** [comment]
@Camille Goussale ***@***.***> I guess we could just use the
mockups you pointed out. We can have a call if you need.
Basically we decide to sacrifice content in every version of the toolbar.
Not sure you have every version in the mockup there so let's have a call
with Camille and/or Anastasiia when you're working on it.

**Comment by RemcoSimonides** [comment]
For dev:
- follow this design https://www.figma.com/file/AkPrTIPD10O3mjuuwgDsxn/Responsive-Global-View?node-id=1%3A1305
- Some of the content is moved from the toolbar to the sidenav so don't forget to also update this sidenav according to the design.
