### ISSUE TITLE
Missing catch-up view on contracts & offers

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6618]
There is no way for a buyer or a seller to see catch up rights within the terms table. 

I think we should refactor this view to differentiate essential info (dates, exclusivity, territory and medias, versions (?)) from additional ones (runs, catch up, and mb more to come). 

![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/a1cf68ad-375a-4529-9ada-e8fcc7e0cfe4)

**Comment by 2amarkina** [comment]
For the moment the additional info should be there with the essential one as continuation. 

For example: 
![table.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/eac78e6e-64bd-4f79-b569-987be7aa3c5d)

**Comment by 2amarkina** [comment]
Sorry, forgot to put them. 

[Here they are ](https://www.figma.com/file/oUCgDCGJndPiVhel04GdIH/%5B-Archipel-Content-Renaissance-%5D?node-id=4148%3A64137)

**Comment by RemcoSimonides** [comment]
Estimation
UX:
UI: 2 days

**Comment by GrandSchtroumpf** [comment]
Related dev issue #7076
