### ISSUE TITLE
[Cleanup] do not use 4Go/cloud function by default

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#6622]
Currently the cloud functions use 4Go of memory by default. Most of them don't require this amount of memory.
- Update the default value
- Redeploy everything
- Test that it's still working

![image](https://user-images.githubusercontent.com/8143464/132467555-a2dffee1-5c60-4b2b-a1fe-1b41e0281f4f.png)

**Comment by phpgeekfr** [comment]
This could also be useful:

https://firebase.google.com/docs/functions/manage-functions

```
const envProjectId = JSON.parse(process.env.FIREBASE_CONFIG).projectId;

exports.renderProfilePage = functions
    .runWith({
      // Keep 5 instances warm for this latency-critical function
      // in production only. Default to 0 for test projects.
      minInstances: envProjectId === "my-production-project" ? 5 : 0,
    })
    .https.onRequest((req, res) => {
      // render some html
    });
```
