### ISSUE TITLE
Holdbacks - Differentiate other buyers' holdbacks from current offer ones

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6625]
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/f26f3c5f-85db-4320-8ab9-8c198a180551)![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/3bf9b060-44bc-4f50-adc8-5ed84340d52f)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/efbc81c8-42b5-4ab5-9c7c-c41182e1800b)
![Kapture 2021-09-08 at 09.37.37.gif](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/367cc701-4698-4aff-833a-8e7b8967b0a2)

**Comment by pldespaigne** [comment]
Seems to be duplicated from #6526
