### ISSUE TITLE
Fix bug - jump when adding a filter (mobile)

### ISSUE THREAD

**Issue by frenchyrules** [blockframes/blockframes#6629]
- Using the content type filter felt weird with horizontal scrolling and displacement of the content as soon as I opened the Keyboard. 
- When I start to type in a content type like “animation”, the filter closes by itself and no content is found, without me writing a complete word yet.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/85220905/132482321-1c04adcf-2e01-465f-a951-0eb39fbadcb0.gif)

**Comment by cams-goussale** [comment]
I suggest we review the filters on mobile and not just this isolated bug. Sending this to UX.

**Comment by cams-goussale** [comment]
Please also consider this issue when working on this #6628
