### ISSUE TITLE
Re-build (or see what's possible) table-cells on mobile

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#6630]

**Comment by stephanie-cascade8** [comment]
Some article 
https://www.behance.net/gallery/90059503/Complex-data-tables-on-mobile

**Comment by stephanie-cascade8** [comment]
UI: 5 days

**Comment by stephanie-cascade8** [comment]
After discussing technical possibilities with François, we concluded that many solutions are conceivable, from the longest to do to the simplest.

eg: simplest 
(remove padding and surface , make it scrollable from left to right)
https://user-images.githubusercontent.com/66258851/151144102-c30d6393-1547-4834-8046-a6e967ff0d60.mov



difficult and hard to maintain
scrollable under the most important column
https://user-images.githubusercontent.com/66258851/151144061-b973871d-abcc-4a47-a73e-e23a80103b8a.mov


long (on the UX part)
rebuild and synthesize the table so that there is only the most impostant info
<img width="375" alt="Capture d’écran 2022-01-26 à 11 06 37" src="https://user-images.githubusercontent.com/66258851/151143979-5a90ad5f-1813-4fe0-bb2b-6b7c449e43c7.png">

@2markina what are the most used tables in our apps? Do we need a particular treatment depending on the table?

**Comment by stephanie-cascade8** [comment]
- [ ] For UI - make the mockup of the simplest solution (nbr 1 in list of propositions above)

**Comment by stephanie-cascade8** [comment]
**Inventory of current situation:** 
Borders and surface padding are giving too much lost space.





https://user-images.githubusercontent.com/66258851/151206763-1a6c0e32-b9d0-4905-b21c-b6b5e39cd522.mov


<img width="1338" alt="Capture d’écran 2022-01-26 à 16 01 48" src="https://user-images.githubusercontent.com/66258851/151206356-c977e4ac-130f-49a3-85ed-1b5616e694d7.png">

**Comment by stephanie-cascade8** [comment]
Here are the final mockups for tables that will be integrated in a mobile version : 

- [Content Dashboard (My sales)](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=61%3A2218)
- [Content / Rights & Holdbacks](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=62%3A3326)
[- Content Marketplace - Offers & Deals](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=62%3A4824)

And here some [technical comments](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=62%3A4739)

**Comment by 2amarkina** [comment]
Check the rule for paginator. 
Proposition: always show paginator after 5 (desktop and mobile)
