### ISSUE TITLE
Cascade8.com - Wordpress - Update plugins

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6631]
It looks like we're spammed on the contact form because of plugin that is outdated. In fact all plugins are outdated since last update, PHP update; we should check if the updates are needed

**Comment by phpgeekfr** [comment]
I updated all extensions and activated reCaptchaV3 to prevent spam in contact form 

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/11cb76d4-85c4-4947-96d4-693171bf7461)
