### ISSUE TITLE
Some HTML issues spotted after 3.4 release

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#6638]
See https://github.com/blockframes/blockframes/pull/6623

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/dde52138-af01-4202-879b-808d9446e47b)

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/68fd5b4e-624f-44ee-a7e8-84abd31cbf3c)

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/befb54b3-7d3d-43ac-a88b-806900b08910)

**Comment by pldespaigne** [comment]
1 & 2 code is not like that anymore, 3 have been done to correct an issue about validators
