### ISSUE TITLE
 Put the eye icon on the right inside form fields.

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#6647]

**Comment by RemcoSimonides** [comment]
You mean on the password field(s), right?

**Comment by stephanie-cascade8** [comment]
> > You mean on the password field(s), right? and it should show/not show password
> 
> yes sorry!

@RemcoSimonides I don't remember what we said at the time. Should I make a quick mockup or should it go directly to dev?

**Comment by 2amarkina** [comment]
Really old issue, quick recheck design + tech needed

**Comment by RemcoSimonides** [comment]
What do you mean?

**Comment by 2amarkina** [comment]
> What do you mean?

I remember that some time ago we had a discussion about this eye that raised also other questions about all the logic of the icons inside the fields and their usage. As this issue is pretty old, and they are not enough comments, I would like to verify quickly what kind of discussion we had and if it would be ok to go for it right now.

**Comment by RemcoSimonides** [comment]
All I remember is that I checked the code if it would be possible and I didn't foresee any issues. We do have more icons in form fields in the app and it is supported by material by default
```
<mat-form-field>
  <mat-label>Search for titles, directors, keywords...</mat-label>
  <mat-icon matPrefix svgIcon="search"></mat-icon>
  <input matInput type="text">
</mat-form-field>
```
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/27687382/167617867-192ce93f-ba52-4ae8-8682-7ed04ab32841.png">

**Comment by 2amarkina** [comment]
> All I remember is that I checked the code if it would be possible and I didn't foresee any issues. We do have more icons in form fields in the app and it is supported by material by default
> 
> ```
> <mat-form-field>
>   <mat-label>Password</mat-label>
>   <mat-icon matSuffix svgIcon="eye"></mat-icon>
>   <input matInput [type]="text or password">
> </mat-form-field>
> ```
> 
> <img alt="image" width="1118" src="https://user-images.githubusercontent.com/27687382/167617867-192ce93f-ba52-4ae8-8682-7ed04ab32841.png">

Ok, if it was ok, let's go for it! 
And in suck case we need to introduce two tooltips: 
- Show Password 
- Hide Password 

Putting them into the [Tooltips Inventory lines 4 and 5 in Cross-App ](https://docs.google.com/spreadsheets/d/152BY91BxRHMksMK-t9Xw_WzKAnxLhl0M4jtex9NY32Y/edit#gid=0)

**Comment by KvnMrs** [comment]
@2amarkina should I add the eye icon in the 'invitation pass' field?

![Capture.PNG](https://images.zenhubusercontent.com/61712a8c95d99512a311887c/62e664fa-4d8e-4a84-a2f6-3dd6447bd9b2)
