### ISSUE TITLE
Remove users that haven't accepted org join invitation in 3 months

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6648]
There are about 1000 users in our db that were created because they were invited to join an organisation but they never signed up. It's time to remove those users and check every-so-often (maybe every release?) to see if any new users haven't accepted their invitation in more than 3 months and remove them.

Link to original discussion about this issue: #6324

**Comment by Jackseed** [comment]
Great at the time we implement this change we shall modify the sendgrid template for invitations in order to warn users of this behaviour. I assign myself for that part.

**Comment by phpgeekfr** [comment]
linked to #6460

**Comment by phpgeekfr** [comment]
So, idea is to remove users created more than 3 months (use `_meta.createdAt` or `auth`  ?) ago that does not have `orgId` field.

- [ ] remove user from db and auth
- [ ] remove invitation and notifications linked to this user
- [ ] create uni-test

**Comment by Jackseed** [comment]
I'll also have to: 
- [ ] change the invitation email text to warn users that credentials will be working for the next 3 months only
so please ping me when dev is done

**Comment by phpgeekfr** [comment]
@cams-goussale Assigning this also because of previous comment :
>Great at the time we implement this change we shall modify the sendgrid template for invitations in order to warn users of this behaviour. I assign myself for that part.

**Comment by cams-goussale** [comment]
@phpgeekfr can I make the change in the active emails already? or do I have to wait for the release day?

**Comment by phpgeekfr** [comment]
you can but maybe wait for it to be implemented and on develop branch, like this we are sure that this will be in next release

**Comment by phpgeekfr** [comment]
Given the auditUsers command that I just ran on production, approx `1319` users will be removed from prod DB and AUTH

**Comment by phpgeekfr** [comment]
```
@phpgeekfr can I make the change in the active emails already? or do I have to wait for the release day?

Also, does this concern only the joinOrg invitation? Or any invitation with credentials (meaning event invitations are also concerned)?
```

@cams-goussale You can now implement it ;)

Any invitation with credentials is concerned.
To make it more general: any account (invited or created directly on the app) have 90 days to join an org or user will be deleted on next release.

**Comment by cams-goussale** [comment]
Ok, done. I'll activate the new templates on the release day. Thanks!

**Comment by phpgeekfr** [comment]
@cams-goussale If you want you can activate them right now,  user created today for example are already concerned

**Comment by cams-goussale** [comment]
aah ok ! done, thanks
