### ISSUE TITLE
Delete users without connexion for the last 3 years and anonymous accounts

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6656]
RGPD requires that we delete user accounts after 3 years of inactivity. We're not quite here yet but would be nice to have something that do check for these users and delete it. 
- [x] Could be during the cleaning script as it's ok if it's 3 years and a month, we don't have to do it on the exact day (and it shouldn't cost us too much to respect that).
- [x] remove anonymous account older than 3 months ? @Jackseed what do you think ?

**Comment by phpgeekfr** [comment]
same for anonymous accounts #6756

**Comment by phpgeekfr** [comment]
should be done with #6460

**Comment by phpgeekfr** [comment]
> remove anonymous account older than 3 months ? @Jackseed what do you think ?

@cams-goussale In order to keep userAuth list on production as clean as possible, I suggest to remove anonymous users created more than 3 months  ago and that never connected since, what do you think ?

**Comment by cams-goussale** [comment]
Yes, sounds good @phpgeekfr

**Comment by phpgeekfr** [comment]
@cams-goussale if an user created more than 3 years ago and did not connected since but is the last member of his organization, what should we do ?
- don't delete user and handle the case manually ?
- remove also the organization ? What if this org have movies linked to it ?

**Comment by cams-goussale** [comment]
Let's do the first option: don't delete user and handle the case manually

**Comment by phpgeekfr** [comment]
Right now we don't have users with account older than 3 years but approx 420 anonymous users will be deleted
