### ISSUE TITLE
UX KPIs

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6657]
Now that we master our analytics, next level would be to use it to verify:
1. If a feature is used.
2. How successful users are while using it.

This is a long term goal that should be divided into smaller tasks to be done:
- List and prioritise existing features to be analysed
- Define objectives per feature (targeted population, usage rate goal, steps to success)
- Implement a UX dashboard to watch these metrics
- Compare real data vs expectations
- Take actions to meet our goals

**Comment by RemcoSimonides** [comment]
UX: 3 days
