### ISSUE TITLE
Contract import improvements

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6661]
Here is a list of improvements that could be useful regarding users’ perspective:
- [x] Not completely sure but it feels like we have to fill cells with lower case words (eg “yes”, “mandate”); would be easier to have capital letters (“Yes”, “Mandate”) and in fact even better if you lower case it code-side so users may fill it with whatever caps they want
- [ ] International Title, Licensor & Licensee name currently accept names, best would be to have possibility to fill it with ids as well (for admin purposes). This is important when we have the same title name for different movies.
- [ ] Territories: it’s really hard to fill territories like “World excluding France”, currently we have to copy paste a list of all the countries and remove France from it. It’s extremely hard to read afterwards and prompt to errors. A while ago we had 2 columns: “Territories included” (eg “World”) and “Territories excluded” (eg “France”); if we could get back to something similar it would be really precious.
- [ ] It would be also really useful to be able to fill in region names like “Africa” or “Europe” and that every territories from that region are included.
- [ ] We are having more and more often multiple terms attached to one contract. It looks like the admin columns (purple ones N-P) are not working for these cases. A solution would be to adapt the excel to this logic: several lines for each term, and one merged cell representing the contract of these terms (similar to what we have on the movie form with the cast)

_Originally posted by @Jackseed in https://github.com/blockframes/blockframes/issues/6567#issuecomment-916711017_

**Comment by cams-goussale** [comment]
Please call me whenever the dev works on this, and we can check the issue together.

Attach is a template proposal (it can't be uploaded like that in the code, but needs to be discussed).
It answers the following points:

`Territories: it’s really hard to fill territories like “World excluding France”`
I have added a column "Including" and a column "Excluding"

`It would be also really useful to be able to fill in region names like “Africa” or “Europe” and that every territories from that region are included.`
I have included the regions in the drop down options.

`We are having more and more often multiple terms attached to one contract. It looks like the admin columns (purple ones N-P) are not working for these cases.`
In this proposal, we have one line per term, and 1 mandate/sale refering to all the terms.

[Template here](https://drive.google.com/file/d/1Cood2uS7K9GWBjOVNVv6A9OfyYOSTitr/view?usp=sharing)

It also answers some of the questions requested in this issue #7225

`Add a status column as mandatory on the template`
`Add a price column as facultative on the template (this may wait if too complex)`

Finally, some modifications that need to be taken into account:
In the parameters, under the category Media, I have added in green some parameters to add, and in yellow some parameters to remove.
