### ISSUE TITLE
Meetings - Set shared video volume for all participants

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6665]
We'd like to give sellers the ability to set the volume of the shared video for all the participants. This way they could speak over the shared video and still be heard. 

Is it doable?
cc @pldespaigne

**Comment by RemcoSimonides** [comment]
What's the difference with #4496 ?

**Comment by Jackseed** [comment]
The difference is that here the control would be only seller's side but would concern the shared video for every participants. 
But you're right it's one or the other but not both. I need to check what to be done here

**Comment by Jackseed** [comment]
@RemcoSimonides I close this one; actually it was just a question from Marie but we need more to implement this, if we do it
