### ISSUE TITLE
Wordpress - Help Logical Pictures

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6671]
They have 2 issues:
- [x] https://bloodmachines.com/index.php/fr/ is totally broken
- [x] There is a text error on logical pictures.com, it's "Latest" not "Lastest"
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/9ab1c37f-91c4-4ace-8f78-cbb60819ac0b)

- [x] update bloodmachines.com WP and extensions to prevent futures backdoors

WP creds are in 1password

**Comment by phpgeekfr** [comment]
solved ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/113c6f03-2385-4f18-b78c-407b392725c1)

**Comment by Jackseed** [comment]
thanks you rock :)

**Comment by phpgeekfr** [comment]
still for logicalpictures: update WP to latest version and extensions

**Comment by phpgeekfr** [comment]
Bloodmachines.com:
removed some backdoors..
