### ISSUE TITLE
Event creation buggy / slow

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6677]
Pulsar team gave another try to meetings and they noted bugs when creating event. They were in a low-connexion zone but:
- [ ] it's either slow (3-5s from click on calendar to small event form opening)
- [ ] or not working (small event form doesn't open at all)
- [ ] or buggy (click on "More details" button on small event form, closes the form but doesn't redirect to event form nor create the event)

These 3 issues need investigation and solutions since event creation is the core of festival app. 

If we want to find back the yandex videos or sentry logs related to these errors; it was made on Thursday 9th, around 10AM-11AM CET

**Comment by RemcoSimonides** [comment]
Their network must have been really bad. If I throttle my internet down to like 5kbs it's still pretty fast. Even when offline, the small even form opens. Only the redirect to 'more details' doesn't happen when offline. After going back online the event is created and I can continue.

Do you know if this behaviour is consistent on their side?

**Comment by Jackseed** [comment]
Yeah, one of their users who creates often events has experimented this already and know she has to be patient with this small form. I also experimented it myself from time to time. Could it be link to numerous event to load on calendar or big statistics..? I mean anything that could make it harder for some accounts vs others

**Comment by RemcoSimonides** [comment]
Just tested this with 186 events and there is no noticeable performance drop... There is also no statistics being loaded. I don't see the reason why this can happen except for slow computer and loading the calendar taking up the CPU but I can't test this hypothesis

**Comment by phpgeekfr** [comment]
linked to #6953

**Comment by xmano** [comment]
Fixes for #6953 wont help here since it will be in E2E Test code. The manual operation with browser is faster so this does not seem to be related.

Only thing that might help is if there is slow operation due to Google Analytics then it might help both app and test scenarios. In this case dependency is other way around.

**Comment by Poppe-A** [comment]
I just want to add that sometime, on event edition page, when clicking on "go to event page", it can take quite a long time before going to the right page. My internet connexion is fast and my computer totally ok. Maybe is it related to this issue ?

**Comment by Jackseed** [comment]
Thanks for confirming, it happen to me as well but quite randomly. I wonder if it's not the same problem as #5940 something like observable or router that is not working..?
@GrandSchtroumpf would you have an idea here? we're on a dead end though it happens on critical actions (log in & event creation)

**Comment by phpgeekfr** [comment]
is this still an issue that occurred recently or can we close ?
Does the spinner that @RemcoSimonides added is enough ?

**Comment by Jackseed** [comment]
I created a lot of screenings during Cannes demo with bad internet connexion and everything was fine. I think that indeed even if it's not quicker, we know that something is on its way thanks to @RemcoSimonides spinners. 
Closing this
