### ISSUE TITLE
Meeting - Buggy File manager (in-meeting)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6679]
Issue based on Pulsar meeting test.
This feedback is based on 2 tests:
- Thursday 9th 3:30 PM
- Friday 10th 4:00PM
Both were on iPad.

Thursday test led to a buggy file manager:
- a line up pdf file was already uploaded from long ago
- meeting created and started nicely
- during the meeting, Pulsar tries to add the line up to meeting > it works; then click on it > line up disappeared. 
They did so 2-3 times before giving up.

2nd test, same scenario, it worked! 

It look like the only difference between the 2 tests was that they used 2 different users: `PqGiZQ3rhUeu7Lp5FeW1HQplOm43` and `NGKwG6VtYXVbAv1xP1O979Y4vtB2`.
Maybe a permission issue?

**Comment by RemcoSimonides** [comment]
Can't reproduce... what is the 'line up'? I can only add 'presentation deck', 'scenario' and 'moodboard / artistic deck' in the movie form, right?

**Comment by Jackseed** [comment]
@RemcoSimonides Oh it's pdf file they uploaded on org files

**Comment by RemcoSimonides** [comment]
Still can't reproduce this issue. I'm moving it to icebox. Let me know if it occurs again

**Comment by phpgeekfr** [comment]
This issue was not mentioned during last tests. Maybe we can close it ?

**Comment by Jackseed** [comment]
Yes
