### ISSUE TITLE
Pulsar meeting feedback - small improvements (meetings)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6680]
Meetings: they had to accept a request to attend the meeting (they didn't invited the buyer but just sent him a link), but they thought it was accepting the buyer to lobby. 
Maybe we should think of making public by default meetings, ie accepting automatically requests from buyers to access it since there is the lobby protection after that. 

Last thing, they didn't really understand what the Organizer was implying (email on her/his name) and they were not aware that anyone from their org could join / accept people during the meeting. We should clarify that

**Comment by Jackseed** [comment]
For meeting invitations: if you're invited, remove the need of lobby acceptation? (google meet like)

**Comment by RemcoSimonides** [comment]
Estimation
UX: 3 days
UI: 3 days

**Comment by 2amarkina** [comment]
as we stop maintaining the feature, do we put this one into icebox? 
@Jackseed @cams-goussale @RemcoSimonides

**Comment by RemcoSimonides** [comment]
oui

**Comment by cams-goussale** [comment]
I actually put it up in the backlog because I thought the first part of the issue goes together with our strategy of "more data for sellers". Or in this case, it would be more "accurate data for sellers". Do you agree @Jackseed ?

**Comment by Jackseed** [comment]
Indeed that's the good moment to tackle this but then maybe best to create 2 different issues so we icebox the one for meeting
