### ISSUE TITLE
Improve navigation (Desktop + Mobile)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6685]
Since the menu is hidden within the burger menu, I'm wondering if users see easily this page. 
It would be interesting to see through analytics how many marketplace users go to the title list and with what button / what pathway

**Comment by 2amarkina** [comment]
First step to do: 
- [ ]  See all the sidenav + toolbars on all the apps 
- [ ]  Propose the mini-navs accordingly 
- [ ] Propose two solutions: when we keep the same icons and when we do not

**Comment by frenchyrules** [comment]
https://user-images.githubusercontent.com/85220905/142403507-bee1b324-7804-4c51-beda-9bf1d306b5fb.mov

**Comment by 2amarkina** [comment]
- [ ] Check for the Profile / Organizations Settings representation on Mobile 
- [ ] Check for the Log Out

**Comment by frenchyrules** [comment]
On mobile:
The nav overlay cannot go over the toolbar. It'll cover everything underneath it though, just not the toolbar. Toolbar icons on mobile will be moved into overlay nav.

On desktop:
Devs will try to implement the sidenav pushing the content on the staging version, see if it works well with every page and prevents every page from needing to be worked individually to function with this new sidebar behavior.

**Comment by 2amarkina** [comment]
- [ ] Correct wireframes following the dev review

**Comment by stephanie-cascade8** [comment]
Uploading Enregistrement de l’écran 2021-12-09 à 15.31.54.mov…

**Comment by stephanie-cascade8** [comment]
https://user-images.githubusercontent.com/66258851/146589322-6cea9fff-ad03-47e3-b577-888da48f7fa3.mov

**Comment by dmoncadalv** [comment]
To the Dev : [Here’s the link](https://www.figma.com/file/7jYrZUTAXck7lp4FBqt9cX/Components?node-id=928%3A4058) for the UI components of the Sidebar Closed, I haven’t put them on mock ups yet.

I know this isn’t an issue that will be treated anytime soon so just contact me when you’ll be working on this !

**Comment by cams-goussale** [comment]
# Review 23/08/22

## Desktop Tests

- [ ] When screen width is too small, we go back to the old version of the side nav.

https://user-images.githubusercontent.com/93206363/186092223-19cd2b9e-f973-4fd4-a339-502ccb183ecb.mp4

**Comment by phpgeekfr** [comment]
- [ ] when left menu is closed, My files screen is missing text "Company" & "Titles" 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/caa7fc9b-4191-4f8b-a608-7c397714e53a)
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/f7e9fc66-e0e5-48b3-8ff2-793791d7bb12)

**Comment by phpgeekfr** [comment]
A lot of bugs, due to `viewEncapsulation` . @cams-goussale @Jackseed Let's discuss this but it looks like that merging this is a bad idea.

Lot of bugs described will be hard to solve and this is highly possible that some have not be found yet.

Best (but time consuming) would be to start from scratch, starting from design in close relation with developers to find a solution avoiding current bugs we have.

**Comment by cams-goussale** [comment]
Let's close this issue for now. To be reopenned when UX and dev have more resources

**Comment by phpgeekfr** [comment]
Branch where Kevin D worked on that Francois suggested not to push to develop as it was creating too many sides effects.

https://github.com/blockframes/blockframes/pull/8779
