### ISSUE TITLE
Archipel Market - Account Creation bug (Cannot read property)

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6686]
Apparently user has received an invitation as all the infos are filled in. 
Nevertheless, the field "invitation pass" doesn't appear. 

User receives an error snackbar "Cannot read property 'uid' of null" bug. 

Then user makes another attempt, here the invitation pass appears. 

The example can be found [**here**](https://drive.google.com/drive/folders/1oFkA2slQHqmAR00QcRoLmSAoZBX-w_dY?ths=true)
_timecode: 0:25_

UPDT. : user connected on the 6th of September

**Comment by phpgeekfr** [comment]
maybe linked to https://github.com/blockframes/blockframes/issues/6622#issuecomment-923809714
