### ISSUE TITLE
Update wireframe & mockup tables according to inventory

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6724]
Every new tables are listed [here](https://docs.google.com/spreadsheets/d/1Et6lZpTcdkJ6nMHmIsTaVD_yObp6GGbvoqUHEB-o-iM/edit#gid=857044763). Grey lines are the one we erase and red comment are new things to add (mainly actions).

Mockups & screens should be updated accordingly. Please add an arrow on columns that can be sorted so we may know it visually. Ideally the filter bar should also list what it filters so screens may live by themselves. 

Please link on that issues updated screens so we can pass it to devs for updates when it's done

**Comment by cams-goussale** [comment]
Note for Camille: inventory sent to Marie & Aurore :white_check_mark:
