### ISSUE TITLE
Genre grid implementation

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6725]
Following the new genre grid, export the new gradient images and implement them. 

![132698976-40031226-6d36-47e3-ad30-508cf167137f.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/df5ca4e5-8f43-435c-a80a-3bdc04d9b170)

**Comment by 2amarkina** [comment]
If I'm not mistaken, the "easy" way to implement the gradients was to export them as the images, put them as backgrounds and then find a better way to integrate them (dynamic / advanced one). 

@stephanie-cascade8 is that it?

**Comment by stephanie-cascade8** [comment]
Illustrations in the right size are available here on [zeplin](https://zpl.io/agEQZkM)
Background images (with gradients) are here
