### ISSUE TITLE
Dynamic gradients (advanced genre grid)

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6726]
After implementing the "easy" method of gradients for genre grid, work on the dynamic gradients, that would be a cleaner solution 

![132698976-40031226-6d36-47e3-ad30-508cf167137f.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9a390383-33ee-4e93-bc83-102a3b2c3102)

**Comment by RemcoSimonides** [comment]
#4736
