### ISSUE TITLE
Invitation pass appears after org loading on signup

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6728]
Loading of specific fields when there is a pending invitation is made on 2 times:
- first org related fields (name, activity, marketplace/dashboard)
- invitation pass

It's disturbing to have it in 2 times, instead it should arrive all at once they notice everything when it comes.

**Comment by RemcoSimonides** [comment]
This page, right?
In the code the fields are updated at the same time... Meaning they are one process already. Does this always happen to you? if yes, how can I reproduce.
<img width="898" alt="Screenshot 2021-09-29 at 14 48 28" src="https://user-images.githubusercontent.com/27687382/135271412-5144b195-a1fa-48e2-9c84-1b216ac5104e.png">

**Comment by phpgeekfr** [comment]
@Jackseed this is already implemented. I updated this page https://www.notion.so/cascade8/Release-troubleshooting-8085a54303de4019b0a129116d60fa13 so we can keep a trace of the cost. We will also need to setup staging with this when testing

**Comment by Jackseed** [comment]
oh great! then I close the issue :)
