### ISSUE TITLE
Buyer list 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6729]
This feature has 2 main objectives:
- list to sellers what buyers already have an account
- give them a way to reach buyers they don't know

Later on we could upgrade that list for sellers to tag buyers into groups in order to invite them more easily. They could also add notes on buyers. 

This list could be either a list of orgs or persons, @maltmayer will ask sales agents what they would prefer and we shall think of what's more convenient to fulfil our objectives.

**Comment by 2amarkina** [comment]
- [ ] Update sidenav Dashboard side of AM 
- [ ] Compare the content to put for Sellers and Buyers pages 
- [ ] See with devs what's possible for the "card" component 
- [ ] Make a subpage example 
- [ ] List view for this layout

**Comment by 2amarkina** [comment]
- [ ] Create a specific filter component pour Sales / Buyers

**Comment by Jackseed** [comment]
I created #7034 for buyers' permission

**Comment by Jackseed** [comment]
Note for future implementation: should we add an export button?

**Comment by RemcoSimonides** [comment]
@frenchyrules I see this issue has been added to "Ready for Dev" but don't we need UI first? If it's already done, can you add the links to the designs?
