### ISSUE TITLE
Budget component

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6737]
See if we change the Budget filter (which is a slider) by radio buttons? 
(idea following the user interviews, Eloisa)

**Comment by RemcoSimonides** [comment]
UX: 1 day
UI: .5 day

**Comment by 2amarkina** [comment]
[Work in progress is here](https://www.figma.com/file/vmwPJzLshwzT1FGwrECDlo/%E2%9A%99%EF%B8%8FFilters-Update-(IN-PROGRESS)?node-id=601%3A6972)

**Comment by 2amarkina** [comment]
**Last version approved:** 
- Use multi-select 
- Use the same budget intervals as in the Movie Tunnel 

![Снимок экрана 2022-02-22 в 17.03.47.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7f16b513-7681-4b69-95c8-33927fdf4328)

**Comment by 2amarkina** [comment]
**after dev review:** 
if it's not urgent, maybe we could wait for a new version of Material that could give us an opportunity to create better sliders (with the range)
