### ISSUE TITLE
Scroll arrows difficult to see

### ISSUE THREAD

**Issue by frenchyrules** [blockframes/blockframes#6738]
- [ ] Scroll arrows can be difficult to see depending on the image shown behind it
![image.png](https://images.zenhubusercontent.com/611a265d2ea95c7880c91192/1489f920-3b93-47a3-9dcb-0d009d61db53)
**Solution proposal:**
By making the grey circle less transparent and adding a white linear gradient to the right/left (depending on the direction of the movement), the arrow "pops" a lot more
![image.png](https://images.zenhubusercontent.com/611a265d2ea95c7880c91192/e72692b6-b769-4dea-bab6-fd285937c3f5)

**Comment by stephanie-cascade8** [comment]
> lgtm

same here. I should work on it to connect this button's features to the builder first. Then if visibility is still a problem, we can see solutions such as the background gradient mentioned by Anthony or something else.
