### ISSUE TITLE
Import Optimization 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6743]
As the user will soon receive a possibility to upload a contract list, the aim is to improve the existing Import page. 

We should take into account the cases:
- [x] Only one document can be downloaded, 
- [x] Many documents could be downloaded / imported (+ select a type) 

See the flows how can a user arrive to this page.  

**[Work in progress is already here](https://www.figma.com/file/SiYgdZcNCMqgdTSy1fVLNB/%5B-Import-%5D)**

**Comment by 2amarkina** [comment]
Take into account #6462

**Comment by Jackseed** [comment]
@frenchyrules do you have the last wireframes for this plz?

**Comment by 2amarkina** [comment]
[Last wireframes for the pre-import optimization can be found here ](https://www.figma.com/file/SiYgdZcNCMqgdTSy1fVLNB/%5B-Import-%5D?node-id=0%3A1)
