### ISSUE TITLE
App animation (Cascade site)

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6749]

**Comment by RemcoSimonides** [comment]
The video is a good option imo
- I can autoplay the video, make it loop (start again when finished), and hide the controls
- The only downside is that the background color has to match the theme. Or is it possible to have transparent background in videos nowadays? ^^
![image](https://user-images.githubusercontent.com/27687382/142829012-cc60f9a1-eb2b-4c04-9765-20994aea725d.png)

**Comment by stephanie-cascade8** [comment]
> The video is a good option imo
> 
> * I can autoplay the video, make it loop (start again when finished), and hide the controls
> * The only downside is that the background color has to match the theme. Or is it possible to have transparent background in videos nowadays? ^^
>   ![image](https://user-images.githubusercontent.com/27687382/142829012-cc60f9a1-eb2b-4c04-9765-20994aea725d.png)

This page is not part of the builder so it's not a problem, I can choose the same background color as the page background for the video.
Thanks for the test.

**Comment by RemcoSimonides** [comment]
> > The video is a good option imo
> > 
> > * I can autoplay the video, make it loop (start again when finished), and hide the controls
> > * The only downside is that the background color has to match the theme. Or is it possible to have transparent background in videos nowadays? ^^
> >   ![image](https://user-images.githubusercontent.com/27687382/142829012-cc60f9a1-eb2b-4c04-9765-20994aea725d.png)
> 
> This page is not part of the builder so it's not a problem, I can choose the same background color as the page background for the video. Thanks for the test.

It is part of the builder but it's forced to show only light theme ;)

**Comment by Jackseed** [comment]
Let's close this issue and re-open it when we'll have more content for Cascade8 website

**Comment by frenchyrules** [comment]
Might be possible to [export with a transparent background](https://www.schoolofmotion.com/blog/how-to-export-transparent-background-after-effects) @RemcoSimonides :)

**Comment by stephanie-cascade8** [comment]
Well even if it's not possible. Since the landing is blocked in light
theme, there is no pb
