### ISSUE TITLE
Update watermark when user name is changed

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6754]
I changed my name within app but watermark didn't. It's important for users with generic email address that regularly pass from one person to another. 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/3449fb84-01b3-4f43-b5ef-ae33276a1280)

**Comment by RemcoSimonides** [comment]
Related: #6393

**Comment by phpgeekfr** [comment]
Inside the storage, I made many tries and the watermark is always updated:

https://firebasestorage.googleapis.com/v0/b/blockframes-bruce.appspot.com/o/public%2Fusers%2FLIXEkDP2jTXPxHcfZ9h05NVdu3p2%2Fwatermark%2FLIXEkDP2jTXPxHcfZ9h05NVdu3p2.svg?alt=media&token=ba47b4a4-cabb-4e3e-8be3-b6bae22c7546

Issue seems to be with watermark refreshing on JwPlayer side

**Comment by phpgeekfr** [comment]
Edit, watermark is not handled by Jwplayer. but by ImgIx.

https://blockframes-bruce.imgix.net/users/LIXEkDP2jTXPxHcfZ9h05NVdu3p2/watermark/LIXEkDP2jTXPxHcfZ9h05NVdu3p2.svg?auto=compress,format&fit=crop

So issue is with imgx caching duration (that should not be very long).

**Comment by phpgeekfr** [comment]
If caching takes too long, a simple update would be to generate a random file name at each generation :  `LIXEkDP2jTXPxHcfZ9h05NVdu3p2.svg` => `LIXEkDP2jTXPxHcfZ9h05NVdu3p2-some_random_string.svg`
