### ISSUE TITLE
Sign up - Add an error message for same invitation pass and password

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6755]
We had users copying their invitation pass in order to use it as a password. But then it blocks the sign up form as a new password must be different from the existing one (ie invitation pass) and no error are telling the user what's wrong. 

![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/9afbdf98-86ac-4ab8-9882-ab2625ba079b)

It should in fact create an error on the form with the message: "Your new password has to be different than the invitation pass."

**Comment by phpgeekfr** [comment]
We should have a look to https://github.com/blockframes/blockframes/issues/6622#issuecomment-923809714  to improve the form update when we have a invitation pass.

**Comment by phpgeekfr** [comment]
can maybe be linked with #6728

**Comment by RemcoSimonides** [comment]
Yes, it is. But does the error then disappear again when you start typing a different Invitation pass?
Also, we handle all errors with a dialog in this auth sections. Also when normally logging in for example. In my opinion, if we change how errors are handled here we should change it for all potential errors when doing something auth related.

**Comment by Jackseed** [comment]
Yes the error should disappear if the user types anything different than invitation pass. 
I don't get your comment about the dialog..?

**Comment by RemcoSimonides** [comment]
I meant snackbar instead of dialog

**Comment by Jackseed** [comment]
Oh ok, true that we handle errors with snackbar but here it's not an error, it's something we forbid. So same as password being too short or username being a string and not a number, we need to prevent users from doing it in the first place, not afterwards

**Comment by RemcoSimonides** [comment]
Without reworking the form too much; I'm able to do this.
However, password and confirm password field are considered as 1. So I can only know if it's equal to invitation pass if they are both filled in (password and confirm password field).

Is this good enough? Otherwise a relative big rework is needed to separate the password and confirm password fields.

https://user-images.githubusercontent.com/27687382/142215875-bbf4ef72-e963-4ffb-9602-9bb7cda8acc4.mp4

**Comment by RemcoSimonides** [comment]
Or I can put the error message underneath the new password confirmation field instead

**Comment by RemcoSimonides** [comment]
@Jackseed  ☝️ 🙂

**Comment by Jackseed** [comment]
Sorry missed it, yeah that's perfect thanks!

**Comment by RemcoSimonides** [comment]
No problem; so error message underneath the 'password confirmation' field then? and not underneath the 'password' field like in the video

**Comment by Jackseed** [comment]
I didn't see that the 2 error messages were different from 'password' and 'password confirmation', could we have it on both?

**Comment by RemcoSimonides** [comment]
Hee @Jackseed, it's more difficult than expected to show a warning on both 'password' and 'password confirmation' field. Before I dive in too deep, I'd like to go back and ask why we want this change in the first place and what would be the best solution. The best solution would be to immediately show an error on the first password field if it's the same as invitation pass, right?

**Comment by Jackseed** [comment]
Yep indeed that would be ideal so then user immediately knows that s/he can't use that password

**Comment by RemcoSimonides** [comment]
After some research and discussion with Francois, I come to the conclusion that a decent amount of rework is needed to implements this warning message. I'd estimate it to about ±3days of work

@Jackseed let me know if you still want me to pursue with this or that I should drop it for now

**Comment by Jackseed** [comment]
Yeah please go ahead, everything related to login / sign up is important
