### ISSUE TITLE
Wishlist notification & email

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6768]
Add a notification & email to sellers: "[User name] just added [Title name] to whishlist."

**Comment by 2amarkina** [comment]
- [ ] see the actual logic 
- [ ] check with devs the possibilities

**Comment by frenchyrules** [comment]
Wireframes in progress [here](https://www.figma.com/file/psDUUgycLBd5yk02ZZj1VB/Untitled?node-id=0%3A1)

**Comment by 2amarkina** [comment]
**After dev review**: 
Having the wishlist shared within the whole org doesn't let us have personalized notifications. 

To change the logic of the Wishlist (from org to user level) we will need to rework data base and that can take time. 

The question which is raised and need to be worked on: 
- [ ] What do we need to do with previous wishlists? 

To do:
- [ ] also need to observe the actual use of the wishlists (find already saved session replays)

**Comment by Jackseed** [comment]
Some propositions to discuss:
- duplicate existing wishlists as a personal wishlist to every org members
- keep org wishlist but add a new user wishlist: it means that when adding to wishlist you can choose on which to add

**Comment by 2amarkina** [comment]
- [ ] go for a personal wishlist / profile level (if an org has a wishlist it should be copied to all the organization members)

**Comment by 2amarkina** [comment]
- [ ] check the specific actions instead of "More details" 
- [ ] recheck "Someone added a title" for notifications that are old (after the pass to profile level)

**Comment by 2amarkina** [comment]
- [ ] propose email text for a Seller

**Comment by frenchyrules** [comment]
Email text proposition
![image](https://user-images.githubusercontent.com/85220905/152981349-caf99e44-180d-45f9-bfe2-932d12758dcf.png)

Looking at this email makes me feel like it should link to said event in a way. Maybe a link to the referenced title's stats page ? Is "Number of adds to whishlist" a stat we plan to include ? @2amarkina

**Comment by 2amarkina** [comment]
> Email text proposition ![image](https://user-images.githubusercontent.com/85220905/152981349-caf99e44-180d-45f9-bfe2-932d12758dcf.png)
> 
> Looking at this email makes me feel like it should link to said event in a way. Maybe a link to the referenced title's stats page ? Is "Number of adds to whishlist" a stat we plan to include ? @2amarkina

It is a great proposition! I like the idea to lead a user directly to the Stats page of the concerned film on the Archipel Market. BUT! as the wishlist is a cross-app feature we need to have a discussion with the devs if we have this possibility to make wishlist part app-specific and how much time it will cost us.

**Comment by cams-goussale** [comment]
Hi guyys! @maltmayer we have this project of sending a notification + email to a Seller whenever their title is added to someone's wishlist. Could you check the text in blue in both [Email tab](https://docs.google.com/spreadsheets/d/1b1K7YfnquxnfCgGGPxIz5ZNIjr9eK_bUrRJqLvPYGIk/edit#gid=97734814) and [Notification tab](https://docs.google.com/spreadsheets/d/1b1K7YfnquxnfCgGGPxIz5ZNIjr9eK_bUrRJqLvPYGIk/edit#gid=874886288)?

**Comment by 2amarkina** [comment]
> @frenchyrules @2amarkina i have created a [Sendgrid template](https://mc.sendgrid.com/dynamic-templates/d-4a3dbb47f1124a919293df3fa8cc9104/version/72124e3f-1106-44b7-aa57-7a61ceacca05/editor/modules?moduleId=bd8pdwp8LpthgXuV1zXaB3) if you wish to play around. I think linking to the Stats page is cool but as mentionned by Ana, it doesn't work cross-app... So maybe too complicated?

For the moment , we need to see the actions and inside the notification and inside the mail. 
If we want it to stay cross-app, we need that "more button" in notifications leads to the Film Page (Marketplace tab in All Apps). If we keep this way, then we could also add the CTA with the same action to the mail. 

If we start adding the app-specific action inside the notification ("more button" on AM leads to Film Activity Rapport, and "more button" on AC leads to Film Page), then we should do the same to stay consistent, but this seems to me difficult to maintain, even if if more personalized as action (---> nevertheless need to verify with devs, but i'm pretty sure it's not an easy brick).

Other optimisations that could help: 
- The Statistics should be accessible via the Film Page, so user will still be able to go to the page we want. 
- The Access to the Statistics can be done via app-specific actions, but also might be more visible (See if we want to keep "Organize Screening" as future Main CTA or we could replace it with "Activity Report")

Other idea: to maintain our cross-app logic, we could keep the "Marketplace" tab everywhere, even on the AM. 
Need to check with devs if inside we could have an app-specific zone to introduce one more CTA. 

See the three solutions below and one that combines everyth
<img width="559" alt="1" src="https://user-images.githubusercontent.com/55499036/153442968-969f4406-193d-4384-a7a5-7b3220c917c1.png">
<img width="578" alt="2" src="https://user-images.githubusercontent.com/55499036/153442976-d8842f02-46e9-4a84-be90-9de1ea8431d6.png">
<img width="549" alt="3" src="https://user-images.githubusercontent.com/55499036/153442980-5fff9653-2d36-498e-8c0a-5cb595ea33bc.png">
<img width="589" alt="4" src="https://user-images.githubusercontent.com/55499036/153442982-ed7a65f2-b342-4015-b77f-47aa6be0c9c4.png">
ing :

**Comment by cams-goussale** [comment]
> If we want it to stay cross-app, we need that "more button" in notifications leads to the Film Page (Marketplace tab in All Apps). If we keep this way, then we could also add the CTA with the same action to the mail.
Should lead to Dashboard side, no? because in any case, if you're notified that someone added your title to their wishlist, it means you're a Dashboard user (Seller). In any case, I think this is the good solution. **The CTA / More option buttons should lead to the title page, and be cross-app**.


> Other optimisations
Great ideas here. I would prefer to keep `ORGANIZE SCREENING` as the main action on the title page. That's what the app is for after all. And `SEE STATISTICS` can be either in the drop-down, or at the end of the page, or both, as you see fit!

**Comment by 2amarkina** [comment]
**Last decisions**

- [ ] This issue should be taken into account after the Seller's Dashboard is done.
- [ ] We go to the User's level for the Wishlist.
- [ ] If an org already has a wishlist it should be duplicated to all the organization members.
- [ ] The "more action" in notifications should lead to the "Film Page".
- [ ] The CTA in the emails should lead to the "Film Page".
- [ ] Last wording validation with Marie _(in progress)_

**Comment by frenchyrules** [comment]
![image](https://user-images.githubusercontent.com/85220905/153621208-251fc61f-5ef3-43a0-91b6-cdaa2763c5de.png)
![image](https://user-images.githubusercontent.com/85220905/153621255-4f741fef-51b4-4a8d-a0c3-d96a58889bbc.png)

**Comment by 2amarkina** [comment]
Email text: 

Hi [[Username]],

We wanted to let you know that [[Username]] from [[OrgName]] added [[Titlename]]
to their wishlist on Archipel Market.

Best regards,
The Archipel Market team

CTA "See Title"
