### ISSUE TITLE
Demo 24 July 

### ISSUE THREAD

**Issue by VicoDraye** [blockframes/blockframes#677]
- [ ] Slow "welcome page" loading
- [x] add some label to "change password"
- [x] add a way to go to the organisation view
- [ ] activity report : add side nav when clicking on a row
- [ ] duplicated encrypted spinner (remove the one in the navbar)
- [ ] slow encrypting after creating a key with mnemonic
- [ ] slow deployment : there is a problem 
- pretend it works
- [ ] transaction processus to complicated
- try to make it better 
- [ ] bug when we go in the movie, there is no template 
- [x] slow search for organisation
- [x] there is no component to display organisation invit 
- [ ] bug: movie not correctly displayed 
- [ ] bug: after signing a delivery you need to refresh the page, no real time 
- [ ] bug: can't see the delivery 
- [ ] bug: no "bigger boat" icon in html 
- [x] logout doesn't work
- [x] No invitation mail when user was added to organization
- [ ] verify status in topbar is not updated in real time (you have to refresh after clicking on verify)

**Comment by Jackseed** [comment]
outdated issue > closed
