### ISSUE TITLE
 move all firestore.ts files into a new models library

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#6771]
move all firestore.ts files into a new models library to prevent bad import that cause backend-functions to crash because of missing modules (like `@angular/forms`) for example

**Comment by phpgeekfr** [comment]
currently handled in #7930

**Comment by phpgeekfr** [comment]
@george43g everything have been moved to new model library, can you have a look ?

**Comment by george43g** [comment]
please see #8051
