### ISSUE TITLE
WP Logical Pictures - Slider revolution not working

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6772]
We can't upload new image or change the text anymore at http://logicalpictures.com/wp-admin/admin.php?page=revslider&view=slide&id=39

**Comment by Jackseed** [comment]
Par contre depuis les reprises sur le site Logical je n’arrive plus à changer le Slider Revolution. Je peux ajouter des slides mais je ne peux plus changer la photo ou le texte :
![image](https://user-images.githubusercontent.com/14964443/135125089-984dc1e2-5274-4c2d-bd7c-42cec0d84ef6.png)
![image](https://user-images.githubusercontent.com/14964443/135125107-3b11a3ae-e339-4865-9c04-33101c2368b1.png)
(Exemple avec Spectre que j’essaie d’ajouter à partir d’une copie de Resurrected (c’est ce que je fais d’habitude)


D’habitude je peux changer la photo ici:
![image](https://user-images.githubusercontent.com/14964443/135125289-30a50d69-7915-4f3f-bf1a-3a9aaa1cb8e8.png)
Et le texte ici :
![image](https://user-images.githubusercontent.com/14964443/135125326-570067ed-5074-46b5-83ea-89ae600b9e0b.png)

**Comment by phpgeekfr** [comment]
@Jackseed  There is indeed an error in the revslider plugin that what not updated (v5.1.5 from 2015) This is because this plugin is not free and we need an account to get latest version from https://account.sliderrevolution.com/portal/pricing/ 
Or maybe pay it again ..

**Comment by Jackseed** [comment]
Thanks! Céline will handle it herself, I close this ticket
