### ISSUE TITLE
Events related emails updates

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#6784]
1. Lot of email templates to update/duplicate for the three accessibility types of an event: public, private, super-private and if user is already a member or not.

The invitation system should not be changed. For the 3 kind of events, we invite users by their email. An user is then created in `auth` and `db` with an invitation pass. 

Handle the various cases described here : https://docs.google.com/spreadsheets/d/1K14j5gtDSKcscXpF8Z2hqOigaH_RgfvyQbgFq1TLJsA/edit#gid=0

- all emails sent to user that does not have an account will contain a invitation pass.
- link into email body should contain at least eventId and invitationId if event is not `public` (`invitation-only` or `private`)  . Example: `/events/01HwnSypEDprUOr8rZpw?id=invitatationId`

2. We will also need an email for private events: not-member users will have to verify their email address to access event.

**Comment by Poppe-A** [comment]
To send an invitation email depending on the user status (register or not) we only check if the user doesn't exist in DB, or if it has an organisation.
After sending an invitation to an email, the email adress is added in then DB, but the user is not linked to an org. So this case is not covered by the code (email register but no org)
