### ISSUE TITLE
Weekly backups - save only new storage files

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6788]
Currently every week we save all the storage as a backup. Problem is that we pay 0,12$ per GB backup and this creates exponential costs. Instead we should backup only new files created during the week or find cheaper solutions.

**Comment by Jackseed** [comment]
If we go for backup of only new files, would we still be able to get back all the files at once if ever we have a full db removal?

**Comment by phpgeekfr** [comment]
linked to #7483

**Comment by phpgeekfr** [comment]
closed and moved to #8532
