### ISSUE TITLE
Error Snack bar for Invitation Pass

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6796]
Nowadays when a user enters the wrong Invitation Pass on the CreateAccount page, s/he sees the password snackbar error message. 

Users are strongly confused and try to change their passwords and do not change the Invitation Pass. 

See examples [here ](https://drive.google.com/file/d/1lfEZN6tD0GL33pWG9JsKarQ17fdQJAj3/view?usp=sharing) 

_invitation : password error.gif_ and _password invalid. check if not invitation pass problem.png_

Solution: introduce a new snackbar for Invitation Pass 
text for snackbar: Incorrect Invitation Pass. Please check your invitation email.

**Comment by cams-goussale** [comment]
When trying to loggin with incorrect Invitation pass, i get this snackbar:
_Error: The password is invalid or the user does not have a password._

- [ ] Solution: introduce a new snackbar for Invitation Pass
text for snackbar: Incorrect Invitation Pass. Please check your invitation email.

**Comment by Jackseed** [comment]
Hum I'm not sure we can differentiate invitation pass from a plain password as under the hood they are the same.. @RemcoSimonides?

**Comment by RemcoSimonides** [comment]
That's true but why would you want to login with invitation pass instead of sign up? Or was it just a test?

**Comment by cams-goussale** [comment]
Yes, It was a test trying to sign up with an incorrect Invitation pass, as mentionned in the initial issue

>Nowadays when a user enters the wrong Invitation Pass on the CreateAccount page, s/he sees the password snackbar error message.
Users are strongly confused and try to change their passwords and do not change the Invitation Pass.

**Comment by RemcoSimonides** [comment]
> When trying to loggin with incorrect Invitation pass, i get this snackbar:

Beware there is difference between "log in" like you mentioned and "sign up". Which did you test? because I changed the snackbar text when signing up with incorrect invitation pass, but I can't do it for login.

**Comment by cams-goussale** [comment]
Ah Ok, sorry! I confirm I was signing up with a wrong invitation pass, [here a gif](https://drive.google.com/file/d/1u9XYMBJVsRgR1f2RpZ6Ys2Ax4s8Ebgd-/view?usp=sharing)
