### ISSUE TITLE
Archipel Content landing page refactoring

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6802]
### Context
We renewed AM landing and we shall do the same for AC since we changed a lot of things on both UI and business since it was made at first.

### Objective
I discussed with Yuki about what should be like the new one, main objective is to **keep it as simple as possible** so users have only one thing in mind: sign up.

### Architecture
To go simple we'll remove a lot of things. New architecture should be:
1. banner
2. How it works section 
3. CTA Hero 
4. News section
5. CTA Hero
6. Footer

### Specs
- [x] Banner: 
- should be shorter, 
- colours updated to match AM new banner, 
- wording and movie posters on the background should be updated following Yuki's recommandations

- [x] How it works section:
- is renamed "Features"
- opening image for both buyer and seller should be replaced by an animation we discussed for cascade8 website (features to showcase to be confirmed by Yuki)
- For the features we can either go with the same design as AM landing but I'd like to try with something that gives more space to each features since it will become the main content of this page; something similar to netflix.com for example that take the whole width for each feature
![image](https://user-images.githubusercontent.com/14964443/139410798-cc08e0f5-91e2-4526-8b3e-4acd07027b03.png)
- texts are updated by Yuki over [here](https://docs.google.com/presentation/d/1CahzMzL38DPoG_8uo8qERPFguaaZ-OdjMfXXsGjM0Yk/edit#slide=id.ge5b888a01d_0_0) (**WIP**)

- [x] CTA hero: 
- title: Interested? Join now!
- CTA: "Sign up" + right arrow icon

- [x] News section: same as AM, news to be given by Yuki

- [x] CTA hero 2: 
- title: Want to learn more?
- button: Contact us

**Comment by stephanie-cascade8** [comment]
WIP here on [zeplin ](https://zpl.io/2jKQRZ6
)

**Comment by RemcoSimonides** [comment]
Dev estimation: 1 week 1 dev

**Comment by Jackseed** [comment]
Question for devs but to keep it mind: could we remove the "First invitation" button in the toolbar and keep it only for Archipel Market?

**Comment by Jackseed** [comment]
@isseymiyuki this is a test, do you copy?

**Comment by Jackseed** [comment]
@isseymiyuki test n°2

**Comment by stephanie-cascade8** [comment]
(WIP)All design is ready. 
But we're still missing content:

For @isseymiyuki :
- [ ] Articles Section (image+title+short abstract)
- [ ] "Our expertise" the content is not done and the illustration can't be made without it but the section layout (structure and alignements) can be implemented as it is.

- [ ] Needs business confirmation on illustrations 4 on each version (buyer and seller)
- [ ] Animations scenario need business valdiation.

Zeplin here

**Comment by Jackseed** [comment]
Should be done with #7083

**Comment by RemcoSimonides** [comment]
@stephanie-cascade8 what's status of this issue? Would be nice if Antoine can start implementing it, otherwise not enough time to include it in next release

**Comment by stephanie-cascade8** [comment]
The page can be started tomorrow morning (just few things to check on sizes
and margins). But illustrations and videos still have corrections to make
from Yannick and won't be ready until next sprint.
