### ISSUE TITLE
Animation System - Preparation

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6840]
- [ ] Study on the best tools to use with angular to make an animation system work in a design system ([Rive](https://rive.app/welcome/?m=direct), [Lottie](https://www.placeme.io/blog/lottie-airbnb-ng-lottie-angular-animations)…)
- [ ] Work on the best svg exports from animate and after effects.
- [ ] Test Rive (exports are canvas but possibilities are wider) tool recommended by François.
- [ ] Make a list of all places where animations can be a real asset for us (explain why and give concrete examples)
- [ ] Follow [training](https://www.awwwards.com/academy/course/design-meaningful-experiences-through-an-animation-system) on awwwards (animations in a design system) 
- [ ] Agree with a dev on what tool to learn, how to export, how to implement… Choose together a methodology and rules to follow.
- [ ] Write down your findings in this issue or in notion

**Comment by cams-goussale** [comment]
@dmoncadalv it seems that you've started touching the scope of this issue recently ! I think it's a good idea to start a notion when you start digging into Rive. So your learning can be mutualized.
