### ISSUE TITLE
Event - Slate Presentation

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6844]
Link to design issue #5397

[Zeplin](https://app.zeplin.io/project/61129744b469ce8a0c470c3e/screen/6137610c5416a6b9a2f9b603)
Add Slate Presentation to the Event Type list
![image.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/614da846-b645-4ef9-bb0d-e8a5b586c099)

[Zeplin](https://app.zeplin.io/project/61129744b469ce8a0c470c3e/screen/612c942b62c57412f5ee8ce4)
![image.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/5d01c8ff-f334-4ae1-9838-e8c14500f0bf)

Event page
[Zeplin](https://app.zeplin.io/project/61129744b469ce8a0c470c3e/screen/612c942be064d714dbc44c68) - old
[Figma](https://www.figma.com/file/HQ2FBvm2u0vyWO0QpIKeTs/%E2%9C%85-Event-Form-Structure-(IN-PROGRESS)?node-id=0%3A1)

As we are doing the Slate Presentation and Events with no connexion almost in parallel we need to pay attention to the Privacy Settings block. For the new Events with no connexion representation, the Privacy Settings will appear inside the Event Page ([example](https://www.figma.com/file/HQ2FBvm2u0vyWO0QpIKeTs/[-Event-Form-Structure-]?node-id=2%3A3443))

**Comment by RemcoSimonides** [comment]
Bruce: 2 week 1 dev
Remco: 2 week
PL: 2 week 1 dev
Francois: 2 week 2 dev

**Comment by Poppe-A** [comment]
Last Figma version : 
https://www.figma.com/file/HQ2FBvm2u0vyWO0QpIKeTs/%E2%9C%85-Event-Form-Structure-(IN-PROGRESS)?node-id=0%3A1

**Comment by cams-goussale** [comment]
@Poppe-A here is a first review for Slate Presentation

- [ ] (B) On the mini-creation form: change `Slate` to `Slate Presentation`

![slate.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/dd7ec29c-2e8d-4aee-bed3-0460a0874d79)

- [ ] (B) Here we need to keep only with the underline and remove bold, following buttons and links rules

![presentation.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/6b86b73c-64d3-491b-99df-396fa0bec821)

- [ ] (B) I would propose to use the same disabled color as for Presentation link, but need confirmation from @stephanie-cascade8, what do you think?

![disabled color.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/ea175e5c-7216-4c63-9d9d-a23c9a7273d2) 

- [ ] (B) Change the text `Direct link to presentation Room` to `Direct link to Presentation Room`

- [ ] (B) Is it possible that the link "My Files/Company/Videos" opens directly in the Company Video's sections?

![company : videos.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/ad1a0f5c-d55c-4f71-a0f2-a1398d9db9b3)

- [ ] (A) If a video is chosen, we need to remove a tag `Video file missing`

![video missing file.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/2c585b0f-00bf-4a01-ab6b-36aba815f0d9)

- [ ] (A) On the event page on the Dashboard side, the titles carousel doesn't work. The flash appears, but it's not clickable (doesn't work on Safari, ok on Chrome)

![not clickable carousel.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b02136d1-361d-43bd-afc5-340f14a046a5)

- [ ] (A) Invitations do not work on the Slate presentation 

![invitations.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/68f838f0-ca3a-4e49-b101-cb80aec83c6e)

- [ ] (A) Slate Presentations should work as Screenings and be published on the Screening list as the Upcoming Screenings 

- [ ] (A) The same as for the Screeners we need to have the statistics/attendance tab

![statistics.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4923555b-5e17-425b-bd8e-af1c05068eb1)

**Comment by 2amarkina** [comment]
- [ ] On the event page change the CTA text from "Access Slate Room" to "Access Screening Room" for Buyers point of view this event remains a Screening. If we still need to dissociate , then " Access Presentation Room" cc: @cams-goussale 

<img width="725" alt="Снимок экрана 2022-05-02 в 16 14 46" src="https://user-images.githubusercontent.com/55499036/166249358-0b4ddbbf-1a11-4e01-8e8e-aa718be6a2ec.png">

- [ ] Same for the type of event. If we need to dissociate (I guess it's the case), then let's use "Private Slate Presentation" or "Private Presentation" as wording. 
<img width="1132" alt="Снимок экрана 2022-05-02 в 16 18 28" src="https://user-images.githubusercontent.com/55499036/166249990-84e9ed0a-e6bd-4df4-a5d7-e26ea11ff4f1.png">

**Comment by 2amarkina** [comment]
- [ ] When a user is trying to connect to the protected event with an email that was not listed, the action try with other email should lead to the Guest view of invitation. For the moment it doesn't lead anywhere (tested on Safari 15.4 (17613.1.17.1.13))
<img width="716" alt="Снимок экрана 2022-05-02 в 16 25 24" src="https://user-images.githubusercontent.com/55499036/166251373-e94a8077-36ce-461b-ae0a-6c411df0c375.png">

**Comment by 2amarkina** [comment]
- [ ] Couldn't play the video for Slate presentation (event ID: TbHDQuI8RTZgRdkTGhxa) 
<img width="893" alt="Снимок экрана 2022-05-02 в 16 30 01" src="https://user-images.githubusercontent.com/55499036/166251877-d03a0070-52ae-4ad6-abf9-49379bac91f3.png">

- [ ] Snackbars are not inside the snackbar box @KvnMrs 
<img width="893" alt="Снимок экрана 2022-05-02 в 16 30 01" src="https://user-images.githubusercontent.com/55499036/166252009-bd8eaa21-4e73-4075-b9a7-0c5c289d851a.png">

**Comment by 2amarkina** [comment]
_Not sure about where to put this one_

When I'm connected as an anonymous user (for the Public Presentations, no account on Archipel Market) I can still "add" a title to wishlist... 

- [ ] Possible solutions: hide this feature for not connected users / Send a user to the Account Creation page (as we do when they click on "View more") 
<img width="1282" alt="Снимок экрана 2022-05-02 в 16 32 53" src="https://user-images.githubusercontent.com/55499036/166252518-d5273e97-05b5-4f86-ae67-9de4405a2066.png">
