### ISSUE TITLE
Tooltip Improvements

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6851]
[Excel](https://docs.google.com/spreadsheets/d/152BY91BxRHMksMK-t9Xw_WzKAnxLhl0M4jtex9NY32Y/edit#gid=0)

- [ ] Rows in yellow represent the tooltips that have to be updated
- [ ] Remove color on rows in excel to show it has been updated.

**Comment by cams-goussale** [comment]
Closing this issue as redundant with #7294
