### ISSUE TITLE
backend: rework stakeholders.ts to avoid the genericity tangle

### ISSUE THREAD

**Issue by lsenta** [blockframes/blockframes#686]
The `stakeholders.ts` module tries to be generic too soon:
the current code goes generic then tries to retrieve lost information down the line with a ton of ifs and ternary operators.

Refactor the code to make it clear and specific, THEN extract generic parts. (refactor to patterns, don't go generic to early).

**Comment by lsenta** [comment]
the `SnapObject` is another symptom of this approach.

**Comment by ioaNikas** [comment]
Get rid of genericity as stakeholder only exists as delivery subcollection.
