### ISSUE TITLE
UI Improvements for Mobile

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6860]
### Archipel Market 

**Google Chrome Version 93.0.4577.63**

**landing page**

- [x] (Global) Have all titles smaller on mobile. 
media-query sm : font-size: 48px / line-height: 1.2;
Antoine: H1 font-size is already 36px. I just changed mat-display-1 and 2

- [x] Off centered buyer logos --> add a line:
"justify-content: center;" on mobile only.
<img width="996" alt="Capture d’écran 2021-09-07 à 13 48 03" src="https://user-images.githubusercontent.com/85220905/132339771-fc2ec38c-31b6-4757-9751-bbabe9d0aa8a.png">

- [x] Footer layout broken --> margin bottom; 16px (between logos)
![File (6)](https://user-images.githubusercontent.com/85220905/131813968-653aa0f7-d84a-427f-b31a-84ae8e168f5d.jpg)

**Sign up**

- [x] Increase space between H1 and logo --> margin-top 24px on H1
![bfc2f1edee8745d1a07936569a4b6ff3-0001](https://user-images.githubusercontent.com/85220905/131818965-f65384e5-6548-48ee-a744-67d18a8a3ddc.jpg)

**Dashboard**

- [x] Wrap button and "+" under H1
![File (7)](https://user-images.githubusercontent.com/85220905/131823829-4735b883-7fd0-457e-ad7d-101c8ebf2354.jpg)

**Wishlist**

- [x] Add horizontal scroll
![File (8)](https://user-images.githubusercontent.com/85220905/131824650-b9cbc729-5b18-40b0-ad8a-05d31fa566b3.jpg)

- [x] Global responsive fix to do on modals. 
media-queries mobile : padding-left and right 24px;
![File (11)](https://user-images.githubusercontent.com/85220905/131829182-d28440ed-27f3-4833-a595-de744fd8b7d5.jpg)

Antoine: I think the modals already have a 24px padding. But for some specifics ones we add more padding. So we need to check every modal

**Film detail**

- [x] Can't put the video in fullscreen ? --> Make it bigger on mobile and include option to see it in fullscreen
![File (1)](https://user-images.githubusercontent.com/85220905/131829910-29b39106-684d-4023-842c-a2338c5accec.jpg)

### General Padding

- [x] Replace padding:80px by 20px left and right on mobiles.
<img width="983" alt="Capture d’écran 2021-09-07 à 13 29 44" src="https://user-images.githubusercontent.com/66258851/132337614-0e9cb2f6-1f51-4739-89c8-288e6d7ad408.png">

- [x] same for mat-tab-group
<img width="1110" alt="Capture d’écran 2021-09-07 à 13 38 46" src="https://user-images.githubusercontent.com/66258851/132338513-6eaa6189-55f5-48a5-a21d-b44338320e42.png">

### Archipel Market 

**Landing page**

- [x] Center H1
![image](https://user-images.githubusercontent.com/85220905/132368383-606d50fd-be2b-41c9-babd-ca126965c7bd.png)

**Home**

- [x] This should be written as “We’ve got more”
![image](https://user-images.githubusercontent.com/85220905/132368584-36331309-3690-465d-a75d-eb67871217d4.png)

**Film page**

- [x] Center title cards
![image](https://user-images.githubusercontent.com/85220905/132369141-82c2867a-6864-4086-a7ed-22c5ecf2f1b0.png)

**Sellers**

- [x] Center column
![image](https://user-images.githubusercontent.com/85220905/132369273-2309411e-1c4f-420b-88df-fe4ba0cf340d.png)

**Comment by cams-goussale** [comment]
@Poppe-A here is the review for Mobile

(those are screenshots from an  Iphone 11)

- [ ] (B) `Sign up here` in the bottom needs to be on a new line with an underline.

![IMG_0648.PNG](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/c07a6c23-5786-479f-901e-145200f20b96)

- [ ] (B) On the movie list. The export button should come under the text (on a new line).

![IMG_0649.PNG](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/2d2162eb-cb8f-4961-8da3-174652478ec4)

- [ ] (A) Antoine I'm not sure if the grid system allows us to add some space between movies. (if yes, 12px would be great).

![IMG_0650.PNG](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/1550861d-a08f-4110-9cff-3612f0607f47)

- [ ] (A) We had decided to get rid of the banner still image in the background (mobile only). and have a background color instead (#010314)

![IMG_0651.PNG](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/38d5d1f4-085e-48fd-9d59-158326a0c16c)

- [ ] (B) Here in the movie page it would be better to cards content horizontally.

![IMG_0652.PNG](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/bfaeafa7-6ec2-40cc-abb7-b93e1505d578)

- [ ] (A) In the Movie Page again, center the title in the section. (mobile only)

![IMG_0653.PNG](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/85784fe7-ce2f-49d1-9a2e-03d6e6196ff1)

- [ ] (B) Here in the footer, before we design it properly for mobile, we could at least have the logo on a separate line and other links under.

![IMG_0654.PNG](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/55efd1b0-2339-4260-b2a6-e202175ec663)

- [ ] (A) The buttons on the slider on mobile are overlapping
![hero section hp.jpg](https://images.zenhubusercontent.com/617811d92b89e7733866d8a0/53dd6c10-3ce8-4406-98db-56911f502547)

**Comment by 2amarkina** [comment]
**Archipel Market** 

MOBILE
**Landing Page > Cookies Change parameters > Data Privacy Policy Modal**
- [ ] The scrolling should not be there (should be like Change Parameters modal). Check if it happens because of a table. 
![Image d’iOS](https://user-images.githubusercontent.com/55499036/166236459-8ce7088e-cc78-4219-af7f-b276235ccd29.png)

**Signing up + Terms & Conditions + Data Privacy**
- [ ] Is it possible that clicking on "<-" on the "Terms & Conditions" page or "Data Privacy" page brings a user to the Sign up with pre-saved fields (if a user has already started filling in)? 

**Last Step**
- [ ] The logo is overlapping the title 
![Image d’iOS](https://user-images.githubusercontent.com/55499036/166237878-e75f7e6e-e1cf-4c8f-942f-35d87c978728.png)
