### ISSUE TITLE
Archipel bridges - Strategy

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6874]
As define within #6801 we need to create links between Market and Content. 

The easiest way to go is to literally add links to Content on a lot of places. I think we should be careful for this to be done softly so it doesn't look like agressive advertising. 
On top of that, if we could include it nicely into flows I think it will have more impact.

This issue is about finding ways to create bridges, aside from adding Content links.

**Comment by Jackseed** [comment]
Idea I had to discuss: list all buyers from Market that could be interested in Content and add them to the latter (warn them before with nice marketing email) so they receive the app access email and may connect to Content out of curiosity.
In time, maybe automatically add certain type of org from Market to Content

**Comment by 2amarkina** [comment]
[Some ideas are listed here ](https://docs.google.com/document/d/14F2o2cRrIwbCLrTs-NdaO0Pa6AjGXRVrJZjulOkyF7s/edit)

[+ Wireframes here](https://www.figma.com/file/GY8lt9tI3nx5xmeMawCtxQ/%5B-Bridge-AC-%2B-AM-%5D?node-id=0%3A1)

**Comment by 2amarkina** [comment]
- [ ] Landing page to go into details with the Archipel Family
