### ISSUE TITLE
Archipel bridges - Links

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6875]
The most obvious way to create links between the 2 archipels is to literally add links within the apps. 

Here is a list of possible links we could add after a business brainstorm:

![Capture d’écran 2021-09-14 à 17.06.33.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/8f416fb9-6dd8-413c-a121-9002543b7401)
<img width="1403" alt="Capture d’écran 2021-09-14 à 17 07 17" src="https://user-images.githubusercontent.com/14964443/136987127-75c05e92-3138-45a7-9829-397d5a41d1e4.png">
)
<img width="1405" alt="Capture d’écran 2021-09-14 à 17 07 27" src="https://user-images.githubusercontent.com/14964443/136987147-3fd9a849-c52e-402b-b096-cc5cb3d31064.png">
<img width="678" alt="Capture d’écran 2021-09-14 à 17 07 56" src="https://user-images.githubusercontent.com/14964443/136987173-13f15001-b109-4853-88f1-e0ff428550f2.png">

<img width="1401" alt="Capture d’écran 2021-09-14 à 17 08 21" src="https://user-images.githubusercontent.com/14964443/136987185-96e4af77-03f2-4abc-9363-dee8744b3c23.png">
<img width="1404" alt="Capture d’écran 2021-09-14 à 17 09 01" src="https://user-images.githubusercontent.com/14964443/136987192-e482c4b9-6d48-4afa-93da-b360c11bbc8d.png">
<img width="1400" alt="Capture d’écran 2021-09-14 à 17 09 19" src="https://user-images.githubusercontent.com/14964443/136987203-5d3c4733-6b6c-43e5-bf3d-9a0cfe45cf3d.png">
<img width="240" alt="Capture d’écran 2021-09-14 à 17 09 28" src="https://user-images.githubusercontent.com/14964443/136987210-5e1f6cec-62a0-4904-9b2c-14c6ab7b8b4d.png">

<img width="1406" alt="Capture d’écran 2021-09-14 à 17 09 42" src="https://user-images.githubusercontent.com/14964443/136987224-99a4a01d-d306-4742-ae75-bc8aa1341e55.png">

**Comment by 2amarkina** [comment]
**[Wireframes can be found here](https://www.figma.com/file/GY8lt9tI3nx5xmeMawCtxQ/%5B-Bridge-AC-%2B-AM-%5D?node-id=8%3A471)**

**Comment by cams-goussale** [comment]
Adding here some comments we had following the refactoring of AC landing page:

- [ ] Add a header of "Archipel community" with the 2 logos which leads to each app
- [ ] Add the 2 logos in the footer

**Comment by 2amarkina** [comment]
[All the screens with green etiquettes can go to UI. ](https://www.figma.com/file/GY8lt9tI3nx5xmeMawCtxQ/%5B-Bridge-AC-%2B-AM-%5D?node-id=0%3A1)
See the comment above to introduce two logos in a footer of Landing on UI level too

**Comment by stephanie-cascade8** [comment]
Zeplin here https://zpl.io/a83xkvX

**Comment by cams-goussale** [comment]
Hello @stephanie-cascade8 we have the [approved wording](https://docs.google.com/presentation/d/1CahzMzL38DPoG_8uo8qERPFguaaZ-OdjMfXXsGjM0Yk/edit#slide=id.g10b4000274b_1_131) for the bridges. Let me know if you see something missing.

**Comment by stephanie-cascade8** [comment]
Hey @Jackseed @cams-goussale @2amarkina , I need your opinion on this 
https://user-images.githubusercontent.com/66258851/149505968-aa6253a5-6397-4fa6-9214-9df53fe97908.mov

**Technical remarks:** 
background shapes would be an animated svg.
The animation would happen after user's click (so we probably need JS not just CSS).
Surfaces will need a customizable background. (can't use the builder here).

**Comment by Jackseed** [comment]
I love it =)

**Comment by cams-goussale** [comment]
Yeah, niiice! Looks great

@maltmayer @isseymiyuki what do you think?

**Comment by isseymiyuki** [comment]
Looks good for me. Do you prefer "Online Playground" or "Digital Playground"?

**Comment by cams-goussale** [comment]
Wording will be changed later on, following the slides you approved

**Comment by cams-goussale** [comment]
@stephanie-cascade8 @2amarkina after discussing with Business, we decided not to do any link on these pages:
- On the Library page when you couldn’t find any movie
- On the Screening page when you couldn’t find any screening
- On the Org page
(You have the [summary here](https://docs.google.com/presentation/d/1CahzMzL38DPoG_8uo8qERPFguaaZ-OdjMfXXsGjM0Yk/edit#slide=id.g10b4000274b_1_131))

So could you please maintain wireframe & zeplin updated with only the remaining pages? I will create the dev issues to start working on this.

**Comment by 2amarkina** [comment]
**Checklist of bridges following the business doc :** 
_Let's see if we have all the wireframes / mock-ups up-to-date for this issue_

@stephanie-cascade8 could you please put a check if it's done?

### Archipel Market
**Landing Page Header** 
- [ ] Global heading : Welcome to the Archipel ecosystem
The online playground for global Buyers & Sellers.

- [ ] Logo AM + The ongoing film market 
- [ ] Logo AC + The content marketplace

**Landing Page Hero**
- [ ] Title: Interested in buying content from a curated catalog?
- [ ] Paragraphe: Learn more about Archipel Content, the first digital marketplace offering multi-seller deals.
- [ ] CTA: Explore Archipel Content
 
**Toolbar Marketplace** 
- [ ] Change text to BUY CONTENT

**Toolbar Dashboard**
- [ ] Change text to SELL CONTENT

### Archipel Content

**Landing Page Header**
- [ ] Global heading : Welcome to the Archipel ecosystem
The online playground for global Buyers & Sellers.

- [ ] Logo AM + The ongoing film market 
- [ ] Logo AC + The content marketplace

**Landing Page Hero**
- [ ] Title: Looking to discover exclusive line-up titles?
- [ ] Paragraphe: Learn more about Archipel Market, the ongoing film market!
- [ ] CTA: Explore Archipel Market

**Toolbar Marketplace**
- [ ] Change text to  DISCOVER EVENTS & LINE-UPS

**Toolbar Dashboard** 
- [ ] Change text to  PROMOTE YOUR LINE-UP

### Check-up
@cams-goussale @Jackseed 
We also had the bridges in the sidenav and on the Homepages, but as I can see in the doc above, these two were crossed out, could you please confirm?

**Comment by 2amarkina** [comment]
- [ ] Remove sidenav Bridge from all the page

**Comment by cams-goussale** [comment]
@2amarkina
> Also, seems that the contact page with a hero section is not mentioned in the business doc, should we still add it?

Isn't it [this slide](Also, seems that the contact page with a hero section is not mentioned in the business doc, should we still add it?) which has been crossed out? Or are you refering to something else?

**Comment by 2amarkina** [comment]
It's the org page in the slide, and the contact page was this one 
<img width="552" alt="Снимок экрана 2022-01-27 в 10 00 19" src="https://user-images.githubusercontent.com/55499036/151325996-bbac184e-4204-4d5e-9cc6-b3eb856f06ab.png">

**Comment by cams-goussale** [comment]
Ah I see! I don't think that page is very visited so I don't think it's necessary to add a bridge here.

**Comment by cams-goussale** [comment]
I've wrote 2 issues for Devs, as suggested by Remco.
- 1 for the links between the 2 apps #7653
- 1 for the Ecosystem + animation header #7654

I am waiting for the Zeplin links to update the issues

**Comment by stephanie-cascade8** [comment]
@2amarkina @cams-goussale it's done. I put the links in the titles list above. Can you 2 have a second check on buttons inside toolbar for marketplace and dashboard? 

- I made 3 variants of this button (a primary, an accent and a default discret one) I prefer the discret one (it is visible enough for me and it doesn't disrupt the other potential cta that we might find in the various pages that will welcome this toolbar.) 

- I put the artwork logo inside, but not sure about what do you think?

**Comment by cams-goussale** [comment]
Thanks @stephanie-cascade8, lgtm with the discret one.

Just highlighting some text fixes that i have noticed:

- [ ] Typo text: `currated` with 2 r [here](https://www.figma.com/file/PGobBB7H317PZO326rCLcz/Landing?node-id=96%3A424)
- [ ] Logo question: do we highlight in blue the word `Content` the same way we highlight `Market`? (we can have this discussion separately)
- [ ] [Here](https://www.figma.com/file/mx5vhUSuslt4ekCAswR8Qv/Homepage?node-id=35%3A628) add the new Archipel Market logo
- [ ] [Here](https://www.figma.com/file/mx5vhUSuslt4ekCAswR8Qv/Homepage?node-id=35%3A628) and [Here](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=6%3A182) can we put lower case?
- [ ] [Here](https://www.figma.com/file/PGobBB7H317PZO326rCLcz/Landing?node-id=100%3A1194) and [Here](https://www.figma.com/file/PGobBB7H317PZO326rCLcz/Landing?node-id=100%3A1349) there is a typo to `ongoing` and also could we add capital letter to `Buyer` and `Seller`

**Comment by stephanie-cascade8** [comment]
I remade the logos on figma to help maintain them [here.](https://www.figma.com/file/Yi5RKQuroGJtpnPUCcAO67/Assets?node-id=186%3A12) 
See what it looks like with the blue rectangle behind on both of them.

![Logos](https://user-images.githubusercontent.com/66258851/153599685-418ba43b-4eda-48ad-adbf-d6495a6cf8b1.png)

**Comment by cams-goussale** [comment]
nice! lgtm, let's roll with that

**Comment by stephanie-cascade8** [comment]
All cleaning done. For me, it can be closed !

**Comment by RemcoSimonides** [comment]
Do we have an issue for implementing the new logo for devs? I've noticed that https://github.com/blockframes/blockframes/issues/7291 was also already closed so curious which one is left for the dev

**Comment by cams-goussale** [comment]
Yeah indeed, it's a mistake!
