### ISSUE TITLE
Marketplace movie view - Available materials pdf doesn't appear

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6876]
app: catalog
url: /c/o/marketplace/title/movieId/main 

At the bottom of the movie view, My Files section that includes the available materials download button doesn't appear if Available Materials is the only file. You have to upload at least a scenario or deck for My Files section to appear. 
Instead it should be here even if Available Materials is the only file

![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/e466df21-3bd4-4567-ba88-da451a4660ac)

**Comment by pldespaigne** [comment]
There is also another bug linked to that, after uploading an "Available Material" (delivery) if the user navigate to `/c/o/dashboard/title/<MOVIE_ID>/delivery` there will be an error

`FirebaseError: Firebase Storage: User does not have permission to access ...`
