### ISSUE TITLE
Quick UI fix - movie with multiple orgIds

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6888]
Issues when movie has multiple orgIds:

Archipel Market
Movie page:

On movie page; multiple organisation show up and all of them have screening ongoing despite only one organization having organised the screening.
![image](https://user-images.githubusercontent.com/27687382/134878792-c6471eb7-2e40-44fb-89c5-31786339133e.png)

We need a quick fix to have at least 3 orgs displayed and then a more button (could go to 5 organizations max). We can remove the contact button when there is more than 1 org

**Comment by 2amarkina** [comment]
I'm afraid we still need to test the case with a very long organization name and if not OK then make a character limit. 

For the moment the longest OrgName we have contains 25 characters, could we see what it gives us if three orgs have such long names?
