### ISSUE TITLE
Videos displayed higher on title page

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6893]
Yuki noticed that on the film page, the video display is at the very bottom, that users would totally miss it; is it possible to higher it like:
![image.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/48618f30-973a-437c-a343-e7ee1423f75d)

**Comment by RemcoSimonides** [comment]
Estimation
UX: 2 days
UI: 1 day

**Comment by 2amarkina** [comment]
[WIP and wireframes are here](https://www.figma.com/file/il7Em1NaQvGWwX4TL0SUPw/%5B-Promo-Elements-Tab-%5D)

**Comment by 2amarkina** [comment]
**LEFT TO DO**

- [ ] Verify with devs the Cross-Tab logic of Promotional Elements + Hero Section 

**Verify the possibilities for following solutions :** 
- [ ] Re-work the order of promotional elements (extract videos before Hero section)? 
- [ ] See if we can put Trailer at the Main section (verify the logic with different video types)
- [ ] See how will the "watch trailer" button behave

**Comment by 2amarkina** [comment]
follow comments in figma

**Comment by 2amarkina** [comment]
**Solution 1 - Promo Tab**
We could put the new Promotional Elements tab and reverse the order of repeating elements, but need to take into account that this section is cross-app and will be changed everywhere. 

**Solution 2 - Video in main section**
We can't know the first video user uploaded. 
_Solution:_ so it would be easier to set the video type as mandatory and say that instead of sales pitch we show trailer. Also, we could add the labels to the videos at the bottom. 

- [ ] Verify with Marie if ok to move the Sales Pitch.

**Comment by 2amarkina** [comment]
- [ ] Check if we can choose a random video to show

**Comment by 2amarkina** [comment]
The possible solution would be to say: 

If there is no Sales Pitch uploaded, then show a Public video from other videos.

**Comment by 2amarkina** [comment]
:bell: See together with design when working on it to be sure to have the good result

**Comment by RemcoSimonides** [comment]
@2amarkina can we have a summary of the chosen solution? I see two possible solutions in the comments here and the wireframe links also still have multiple possible solutions

**Comment by 2amarkina** [comment]
Yes, cleaned that up. 
The last decision that was taken is to go up with this:
<img width="535" alt="Снимок экрана 2021-12-06 в 11 14 34" src="https://user-images.githubusercontent.com/55499036/144828339-038c6c6d-69c2-4ef6-80c7-24e4b024b899.png">

- [ ] remove the Sales Pitch title of the section
- [ ] for the video itself: If there is no Sales Pitch uploaded, then show a Public video from other videos, like a "stairs" (if there is a trailer, then show a trailer, if not then show a clip, for example)
- [ ] remove sales pitch description 
- [ ] instead the sales pitch description put the synopsis 
- [ ] if there is a video, then synopsis should be on the right, if there is no video, then put synopsis aligned left as usual 
 
[Cleaned wireframes can be found here ](https://www.figma.com/file/il7Em1NaQvGWwX4TL0SUPw/%5B-Promo-Elements-Tab-%5D?node-id=0%3A1)
