### ISSUE TITLE
Review My Avails / My Sales

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6914]
**Testing Environment:** environment of Springfield 

**OS:** MacOS BigSur (version 11.5.2)
**Browser:** Chrome (version 94.0.4606.81) 
**App Side:** Dashboard

### Contract Page
- [x] Change "Delivery Wishlist" by "Delivery Specifications" (we can change it everywhere: Dashboard, Marketplace, CRM) 
![Снимок экрана 2021-10-19 в 18.20.25.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/8d2c1309-d4f3-4054-886f-85a5a0c41090)

- [ ] If possible centralize the text in the Rights Card 
![Снимок экрана 2021-10-19 в 18.27.47.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/07871791-1d88-450a-b1eb-c7cd85a73203)

### My Sales 
- [x] The approval / status is not shown in a table and on the contract page 
![Снимок экрана 2021-10-19 в 18.29.17.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/e1c1f1f2-e8ca-485f-9b2a-e559f1b3b957)

- [x]  It is not shown on the Contract Page neither
![Снимок экрана 2021-10-19 в 18.31.05.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/8bff58b2-2105-424b-9c2b-861f6bd0c5e9)

### My Avails
- [x] When leaving a cursor for a long time on the map or calendar icon for about 3 sec, then there are icon details that appear. 
![Снимок экрана 2021-10-22 в 15.31.07.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b6f0ef0e-1477-46f9-b8ad-c8fcfabc6e93)

![Снимок экрана 2021-10-22 в 15.35.21.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/c09eb204-9f4a-4a98-b9ab-2d0a81e0c8a5)

- [x] Add tooltip "See Available Territories" when hovering on Map Icon (text to confirm with business team)
- [x] Add tooltip "Add Available Terms" when hovering on Calendar icon (text to confirm with business team)

- [x] If possible, could we make the Title Name clickable and make it go to the concerned Film Page? ![Снимок экрана 2021-10-22 в 17.17.25.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b3f488a9-1dc0-4952-a168-01657af144da)

**Comment by iPR0D1G1** [comment]
> ### Dashboard
> **Calendar view of Avails**
> 
> * [x]  The "Download .CSV" is disabled, even if we entered the info needed: Territories, Rights and Exclusivity.
> 
> The .CSV file generated should take the same form it takes for the Map: International Title, Territories, Medias, Exclusivity, Terms

Don't really understand what you mean with the .CSV generated file should take same form it takes for the map. Nonetheless, both the map and single territory files are generated as per the specifications found [here](https://github.com/blockframes/blockframes/issues/6705#issuecomment-939821764).

**Comment by iPR0D1G1** [comment]
> ### Dashboard
> * [ ]  Could not load the avails page on Safari...
>   ![Снимок экрана 2021-10-27 в 14.37.18.png](https://camo.githubusercontent.com/a079bd4334bbb5e1e2615c5c1e8690dbd291da00b39fdd31f5e32b4286ccafef/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564643534353238633063636433303030313336373263332f61393633323538372d326265352d346631612d393632342d356637366337336164666232)

This is a false positive. Tested with PL and Francois and came to a conclusion I provided you with with users who possessed stale data in the db reason as to why you had this problem.

**Comment by yspringfield** [comment]
>  If possible centralize the text in the Rights Card
If we are to do this, it'll be for all the columns of the table. that's why we decided not to implement it.
