### ISSUE TITLE
Tooltips still bugs

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#6920]
In spite of many updates and corrections on tooltips. We still notice contrast problem.  (light theme only)

![Capture d’écran 2021-10-20 à 11.40.37.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/a1893eba-ab70-4449-adbd-ee41a1ca3644)

**Comment by dmoncadalv** [comment]
We have this [components for the tooltips](https://www.figma.com/file/7jYrZUTAXck7lp4FBqt9cX/Components?node-id=36%3A309) on Figma, we could follow this new colors on the app to correct this problem.

**Comment by 2amarkina** [comment]
- [ ] do with a dev together
