### ISSUE TITLE
Circle Ci - high monthly costs

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#6923]
CircleCi is currently charging us a lot.

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/246002cf-7818-4223-bee6-ab3e46e0872c)

Maybe linked to the cache size

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/cbad14ec-e576-4bee-ab93-c2e6533d271d)

@george43g please have a look to check what can be done. Can a quickfix be found with cache purge for example ?

@Jackseed maybe we need to go to another billing plan ?

as @GrandSchtroumpf suggested, github action could be used instead, for free. Let's have a look to this.

**Comment by phpgeekfr** [comment]
Maybe a plan with an higher amount of credit would be profitable. 
When our credits are near zero, we are charged $33 for `1,000 Credit Refill Package: 56 packages`

**Comment by GrandSchtroumpf** [comment]
An alternative could be to use Github Action : https://github.com/pricing
It's free for public repositories. Here are some details : https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions : 
> GitHub Actions usage is free for both public repositories and self-hosted runners. For private repositories, each GitHub account receives a certain amount of free minutes and storage, depending on the product used with the account.

**Comment by phpgeekfr** [comment]
Email received today : 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/f6fbd954-969f-4a38-809a-25c2f3756f64)

**Comment by george43g** [comment]
The solution here will be multi-step and gradual.
First order of priority is accessing free credits if possible
Then also work on optimisations with caching. I know ways I can quickly reduce this and the PRs should only take couple days.

**Comment by george43g** [comment]
@Jackseed  what's the latest on applying for free credits?

**Comment by george43g** [comment]
After looking through this carefully, if we can get 400k free credits per month then CircleCI might continue to be viable for us as long as I stay on top of some optimisations. Time will tell how big of an impact the optimisations have. Just have to keep an eye on it.

Our average monthly usage has been around 400k credits (although this may change with new billing also) so if we can access an open-source free tier that could work?

**Comment by Jackseed** [comment]
For the records here was CircleCi answer for the free tier account:

> -You will need to be on Free tier to utilize the free credits, currently, you are on Performance plan. You will need a separate account if you would like to access this credit. Organizations on our free plan get 400,000 free credits per month ($2,880 annual value) to use for Linux open source builds. You are allow to run up to 4 concurrent jobs available. Keep your repo public for access.

I just created a new github account to circleci@cascade8.com so we may create a new CircleCi account with this one.

Re the 400k free credits, idk if it will be enough. Our last 6 months usage varied between 500Gb to 2.5Tb of network, which would represent between 210k credit to 1M.

**Comment by george43g** [comment]
I'm hoping that combining that with further optimisations should at least reduce the cost significantly for now. Let's see how it pans out - if it's still too expensive then we may have to rewrite our CI config for github actions instead.

**Comment by george43g** [comment]
the open source plan may have been pointless. This is only currently accessible via the free tier only. You cant pay for overuse. see https://support.circleci.com/hc/en-us/articles/360038512113--How-does-CircleCI-charge-credits-for-Private-and-Public-Repositories-

The only way forward is to keep doing optimisations and see how costs are affected moving forward, and also we can vote on the open source performance plan issue on github to entice them to allow us to use free credits then pay for credits above that

**Comment by phpgeekfr** [comment]
@george43g  Just an idea, maybe the dockerFile that is built is responsible of many network et storage usage ? Is there something we can do about this ?

**Comment by phpgeekfr** [comment]
on CircleCI https://app.circleci.com/settings/project/github/blockframes/blockframes/advanced?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fblockframes%2Fblockframes
this is already checked ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/fcc3aeb2-be6a-4e72-b131-a98e1ab0492d)

Does this mean we already have the free credits ? @george43g @Jackseed

**Comment by Jackseed** [comment]
This being enabled looks new to me and when I look at our plan the 400k free credits don't appear. 
![image](https://user-images.githubusercontent.com/14964443/148069664-977cd869-685a-4e0d-9e76-5b9c86cd6d47.png)

We definitely need to take care of #7452 and clear things out

**Comment by phpgeekfr** [comment]
Regarding Free and Open Source: 
`Enabling this will allow this project’s builds to use them and let others see your builds, both through the web UI and the API.`

- [ ] We need to be extra careful with this. During deploy functions, some credentials are displayed. We need to remove this.

- [ ] If we go with free credits, will this display our build history ?

**Comment by phpgeekfr** [comment]
at mainly each step in `circlci/config.yml` we use `executor: blockframes-ci` 
```
  blockframes-ci:
    docker:
      - image: blockframes/ci:latest
        environment:
          NODE_OPTIONS="--max-old-space-size=8192"
    working_directory: ~/repo
    resource_class: large
```

with resource class **large**
and docker pulled from `https://hub.docker.com/r/blockframes/ci`

Image size :
```
blockframes/ci                                  latest                 19ec73357429   5 months ago    3.24GB
```
- [ ] can the image size be reduced and will it lower our pricing significantly (reduce network usage) ?

@see https://circleci.com/docs/2.0/executor-types/#docker-image-best-practices

**Comment by phpgeekfr** [comment]
- [ ] does network usage consume credits ?

**Comment by phpgeekfr** [comment]
- [ ] 4 concurrents jobs on free tier only?
- [ ] we don't understand this screen, aren't we supposed to have 55k at each month and pay extra $15 for 25k credits?

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/b6d2d80a-84bb-46df-87d2-2acfa76fadee)

- [ ] what is the source of this network usage? even plan at $2000 give 50GB and we use 2.5TB .. 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/abe54583-6275-43be-9d25-4a9e85aa3102)

Docker pulls ? 269 e2e jobs × 3 docker per job × 3,2GB image pulled from docker-hub
CF https://app.circleci.com/insights/github/blockframes/blockframes?reporting-window=last-30-days

**Comment by phpgeekfr** [comment]
- [ ] given this example https://app.circleci.com/pipelines/github/blockframes/blockframes/22631/workflows/20c4d1d1-5c20-4957-8c83-3df1cdb24f51/jobs/43183/resources
looks like that we can lower resources for Docker container

**Comment by phpgeekfr** [comment]
- [ ] how to reduce caching ?

**Comment by phpgeekfr** [comment]
Notes after the call with CircleCi team:

New pricing should not affect us because `Network transfer` in the project tab is not the one we will be charged for.
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/4bf31231-ce21-45a2-b0a5-fde5528d9d1f)
We will be charged for what is in theses tabs :
 ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/1d7f42e0-493b-48d4-bf0c-3968f24f3275)

So right now, the only thing we need to care about regarding network & storage is the caching that will cost us around $30/month . Since this price is quite low regarding the whole bill, I don't think this is a priority.

Main priority would be to reduce `Compute` minutes by making the build and e2e test steps faster (optimize process or go with a bigger docker container).(Build time average on other companies is around 10min.)

@Jackseed will open a support ticket to get information about open-source plan :

1. 4 concurrent builds
2. What if we use more than 400,000 credits
3. Could we enable it to the current account?
4. Privacy on older builds

**Comment by Jackseed** [comment]
For future generations: the cost for credits included in the pre-bought packages are exactly the same as the ones bought if we run out of credits, ie $0.0006. 
The only difference is the granularity, first are bought 25k per 25k, second 56k per 56k

**Comment by Jackseed** [comment]
New support ticket opened #103110 about open source plan questions

**Comment by Jackseed** [comment]
@phpgeekfr @GrandSchtroumpf @george43g CircleCi answers regarding open source plan:
1. Q: Do we really need to open a new account to benefit from open source plan (oss)
```
I have checked internally and as my colleague previously mentioned you must have new account to fully use oss credit on CircleCI.
When you enable open source plan, it will not charge for the user fee but all the build minutes will still be consumed.
I understand that this is a lot of work creating another plan, but to benefit from oss plan.
```
2.  Q: It says that once on an open source plan, our builds will be public. That's ok for the next ones but what about older ones (before we toggle that open source plan)? Will they become public?
```
When you set as open source plan, it means code from Github will be all public, therefore your private keys will be shown to public.
Secret keys which are set on CircleCI will not be open to public.
```
3. It also says that we can only have 4 concurrent builds with the open source plan, could we pay for more in addition to these 4?
```
Unfortunately only 4 concurrency is available on oss plan and you can not pay for additional container.
```
4. Q: Same question for the 400,000 credits, what if we run out of credits? Can we still pay for more then?
```
On oss plan through the overview page, your oss plan consumption is available. Please adjust accordingly.
```

Conclusion: It looks to me that moving to open source plan will be expensive (time setting up a fresh new account) and not enough (concurrent builds); so better working on small improvements and/or maybe switch to Github actions (need more research beforehand)
