### ISSUE TITLE
Improvement of the Map 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6955]
Maybe it would be nice to improve the box that a user sees on the right side, when a user hovers the country. 

Maybe add the info about the Terms and Rights ? ![Снимок экрана 2021-10-26 в 09.51.18.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/7e29c9d1-3ec0-438d-83c4-25fcaa019177)

**Comment by Jackseed** [comment]
Imo terms and rights will overcharge the card with redundant info since every countries will have the same Terms & Rights from the form. 
Do you think we need to add more clarity to this card?

**Comment by 2amarkina** [comment]
Yes, thinking it over it seems to be quite redundant. 
Yes, I feel like we could improve it a bit. Maybe we could make the country name a bit bigger? (it could be better for the small countries to better "catch" them).

**Comment by Jackseed** [comment]
Ok then it looks more of an UI issue, I transfer it

**Comment by Jackseed** [comment]
Ok after discussion, not a priority since it's working fine at the moment, I close this
