### ISSUE TITLE
UI Improvements of filters

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6986]
[_Following this issue in UX_](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/6068)

When we use our filters right now in a lot of places we have three times the same info repeated: ![Снимок экрана 2021-10-28 в 14.20.57.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/aeecaae4-e4b3-4d4e-aeaa-2e6a1d9b7aac)

The idea is that for not repeating the same thing many times, we could delete the title on the card that opens and reduce padding between filter and card. 

![cf9a2c47-5e32-4d5f-8264-19eb2f7c273a.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b699f121-cfa4-48a8-b44a-aa55bbf76511)

**Comment by stephanie-cascade8** [comment]
By François : 
- [ ] take off "mat-card-header" of list-filter
- [ ] in "list-filter.component.scss " change mat-card margin-top from 32px to 16px.

Remark : we can't reduce the padding inside the mat-card (we should replace mat-card by surfaces there anyway)
