### ISSUE TITLE
Add "export results" button on the Library page

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6991]
See if cross-app or AC specific; 
See if use "export results" for all filters or for Avails only; 
See where to put this export visually. 

Respect the new visuals to come ![Снимок экрана 2021-10-28 в 17.52.45.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/76c164bd-11b1-42ab-8296-53a7dd71e75c)

+ See the format PDF

**Comment by Jackseed** [comment]
File sample of how it should look
[Catalogue 202110 Kid & Teen series for GMA.docx](https://github.com/blockframes/blockframes/files/7475909/Catalogue.202110.Kid.Teen.series.for.GMA.docx)

**Comment by Jackseed** [comment]
Comment from @phpgeekfr  
> library to generate pdf  on backend : pdfkit

**Comment by RemcoSimonides** [comment]
Dev estimation: 
Bruce; 1 week 1 dev
PL: 2 week 1 dev
Francois: 2 week 1 dev

**Comment by 2amarkina** [comment]
- [ ] flow + download widget

**Comment by 2amarkina** [comment]
**[Link to the wireframes](https://www.figma.com/file/k0n3VUcXhMmvAS7t8uUTh3/%5B-Export-results-%5D)**

**Comment by 2amarkina** [comment]
**[The design of the PDF can be found here](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/issues/blockframes/blockframes/7045)**

**Comment by 2amarkina** [comment]
Should already in dev,[ in progress with this one ](https://app.zenhub.com/workspaces/dev---sanity-team-5f6b0067599064680cd2c617/issues/blockframes/blockframes/7045)

**Comment by Jackseed** [comment]
Yep, let's close it as duplicate
