### ISSUE TITLE
Yuki's email signature

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6994]
She'd like to have a signature that includes poster from titles she wants to promote. 
Structure would be:
1. Name
2. Position
3. Tel number
4. Cascade8 logo
5. 3 Posters 

Films will be:
[Marona's](https://archipelcontent.com/c/o/marketplace/title/2RiPSrvGorkwKnT0EhIV/main), [Shut up and play the piano](https://archipelcontent.com/c/o/marketplace/title/EmRSAa0ACdKzPbU3PGgi/main) and [Bingo](https://archipelcontent.com/c/o/marketplace/title/Iw75A7cmq9g9EWkURTbO/main)

I don't know what format is best for a Gmail signature but an interesting thing would be to find a way for the posters to be changed easily by Yuki whenever she wants. @RemcoSimonides was pointing to specialized service like [this](https://www.letsignit.fr/), could be interesting

**Comment by stephanie-cascade8** [comment]
I signed up there for a trial on [this](https://www.letsignit.fr/), and was called by a seller. They can organize a demo with us if we want bu their price are from 50€ not less (that is for 50 signatures).

I'm testing free ones those from this list : (see if I can find a template that enables several images for posters )
 
<img width="758" alt="Capture d’écran 2021-11-04 à 16 30 47" src="https://user-images.githubusercontent.com/66258851/140372426-26d05a8f-bb7f-4c5a-b95c-c84c19e0ccb2.png">

**Comment by stephanie-cascade8** [comment]
The best to use is this one : hubspot[](https://www.hubspot.com/email-signature-generator#esg-gmail-info)
It offers many templates and possibilities for free (eg: cta, banners...)
I tested it here but I will have to let @yuki do it by herself (it's connected to personal gmail accounts)
<img width="660" alt="Capture d’écran 2021-11-04 à 19 00 50" src="https://user-images.githubusercontent.com/66258851/140394389-facc7511-82af-4e91-a8dd-7859958d9cfd.png">

**Comment by yuki** [comment]
Please, don't refere as ATyuki, because this is my username and I'm not the Yuki you refer to! XD

**Comment by stephanie-cascade8** [comment]
> Please, don't refere as ATyuki, because this is my username and I'm not the Yuki you refer to! XD

Haha ok sorry 👍
