### ISSUE TITLE
Buyer buying preferences 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6996]
For both Archipels we'd like to add a small form for buyers to know what are their buying preferences which include territories, media and genre they are used to buy. 

We had early [wireframes](https://www.figma.com/file/j6QCVEIFmarhgA2q9oKkXi/Buyer-Marketplace-pre-tests?node-id=273%3A0) on this matter but they included other parameters we won't use for now. 

This information will be used:
- AM: instead of company's nationality we shall use buying countries if we have it on invitations, notifications and event stats
- AC: informative only for Yuki's to send buyers relevant titles on newsletters

Flow is important here: when and where to show this form?

**Comment by RemcoSimonides** [comment]
Highly depending on design. But can be between 2 and 4 weeks.

**Comment by 2amarkina** [comment]
[WIP and wireframes are accessible here](https://www.figma.com/file/vTxVOIxGEEvuldEa4kbzRE/%5B-Buyer's-preferences-%5D?node-id=15%3A1817)

**Comment by 2amarkina** [comment]
**TO BE DISCUSSED**
- [ ] See if preferences are on the profile or org level
- [ ] Verify if we propose to create many preferences or only one

**Comment by Jackseed** [comment]
For future reference (dev issue) we'll need integration with mailchimp to push this info as tags

**Comment by 2amarkina** [comment]
It might be difficult to make the pop-up work correctly and can be disturbing for a user if it appears many times. So it would be better not to show it, but to send to the "old" users the newsletter with a link to the Preferences page. 

Ok for the "waiting" page after the onboarding and Ok for having Preferences on the Profile level, but it would be much better to make them cross-app, as if not will make the things much more complicated.

**Comment by RemcoSimonides** [comment]
1. Is it only displayed for the first connection per org? Or is it displayed for first connection per person, except when it's already filled in by someone before)
2. Is there difference in settings, or sometime in the future, between AM and AC settings?

**Comment by 2amarkina** [comment]
1. It should be displayed for the first connection of a user, all the preferences should be managed by a profile
2. Probably we could have some differences between AC and AM as we have between the filters they use (production status for example)

**Comment by 2amarkina** [comment]
As discussed: 

**Pop-up modal should appear if:** 
- User's role is set to Buyer
- User arrives on the Marketplace homepage
- User hasn't filled in the Preferences before. 

If user clicks on "Do it later" the modal is closed and the fields are filled with "empty" information. 
![Снимок экрана 2021-11-25 в 15.52.43.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/e00e7ef9-fb7b-41ea-aad6-f84e004cec8c)

**User can manage the settings in the Profile** 
![Снимок экрана 2021-11-25 в 15.52.07.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/460b3b67-2d48-45fc-9d5d-c471346a5fc4)

**Settings are common for AM and AC**

**Comment by 2amarkina** [comment]
- [ ] Last step: Texts from Marie (ongoing, will add as a comment to this issue)

**Comment by 2amarkina** [comment]
Title: Buyer Preferences 
Description: For a more curated experience on Archipel, we offer you to specify your buying preferences.

**Comment by 2amarkina** [comment]
@RemcoSimonides Important updt. 

- [ ] Need to add Languages 
![Снимок экрана 2021-11-25 в 17.41.07.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9f06768f-6de8-42ca-8665-4838c376e535)

![Снимок экрана 2021-11-25 в 17.42.07.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/49378657-7a96-4347-8efa-6c34ae0338cd)

**Comment by RemcoSimonides** [comment]
This is ready for UI now, right?

**Comment by stephanie-cascade8** [comment]
After choosing and saving preferences should we have a snackbar "Your preferences have been saved" or something like that ?
