### ISSUE TITLE
As a Distributor or a Sales Agent, I want to be able to create new template for my delivery lists or modify and delete old ones.

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#70]

**Comment by lsenta** [comment]
Note réunion (20 Mars 2019):
Template = liste de materiel, pas rattaché à un film
C'est la matrice de base du fournisseur, ils veulent créer leurs matrices.
Après ils les spécialisent pour un client.

L'organisation a un role sur un film, ce n'est pas un role absolu.

1. création d'un template,
2. organisation est ajoutée à un film (distributeur ajouté par le producteur)
3. la discussion se fait sur la "unapproved delivery list",
4. les deux parties sont d'accords => "approved delivery list", (définitive, module changements exceptionnel),
5. Laboratoire reçoit le matériel et valide chaque item du materiel,
6. Quand la liste est complétement validée, la liste passe en "delivered".

Note: dans un premier temps on va valider toute la liste.

Plus tard (TODO: créer le ticket correspondant),
on ajoutera du feedback pour permettre aux user de valider ligne par ligne.

On aggrege la liste de tout les matériels dans les templates des utilisateurs pour fournir de l'auto-complétion.
