### ISSUE TITLE
Secure the admin pages

### ISSUE THREAD

**Issue by lsenta** [blockframes/blockframes#700]
We have a few admin pages in the firebase backend, served at `/admin`.
They are used in #573 and #571 

We should secure these pages, at least with a simble password check for admins, or IAM checks, and at best using firebase auth and adding `cascade8` admin to some users.

**Comment by Jackseed** [comment]
linked to #492

**Comment by Jackseed** [comment]
Really high priority

**Comment by lsenta** [comment]
@Jackseed 
(update after moving on issue #492)

- I can either implement the full firebase auth machinery so that users login with an account like on the main app to be able to trigger a backup / restore and others authentication operations.
   - time to implement: ~3 days, a bunch of decision to make regarding implementing admin as a fully fledged angular app, taking front dev away from the app.
   - works like any other blockframes app.
- Or I can implement a single admin password that we store in the secrets, all the users will copy and paste this password in the admin forms.
  - time to implement: 20min
  - lower security
  - you have to copy and paste this password to auth organization & trigger backups / restore.

**Comment by Jackseed** [comment]
I'll go with your recommandation @lsenta. Admin app is on the roadmap anyway so let's keep the (A) option for the sprint that will launch it.
