### ISSUE TITLE
Optimization of Content Type filter

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7000]
- [x] Validate with Yuki and Marie if OK to go on with following Content Types: 
Film, Series, Short Film

When validated, then 
- [x] Change for checkboxes
- [x] Verify if Titles previously uploaded have Content Type that is deleted. Define Strategy how to manage this case.
[Wireframe here](https://www.figma.com/file/vmwPJzLshwzT1FGwrECDlo/Filters-Update?node-id=327%3A1210)

**Comment by 2amarkina** [comment]
As we decided to go for only two content types (Films / TV Series), then two new versions are proposed in wireframes (check with product team).

**Comment by 2amarkina** [comment]
Last decision: 
Go for a toggle, as only two variants are possible here. 
The default state : nothing is chosen. 

[Link to the wireframe](https://www.figma.com/file/vmwPJzLshwzT1FGwrECDlo/Filters-Update?node-id=365%3A6951)

Wireframe itself 
![Снимок экрана 2021-11-12 в 09.27.16.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/92caf5e2-7a7e-45c6-9950-e5d3e00bedf0)

**Comment by 2amarkina** [comment]
Can go to devs. 
The mockups in UI should be updated accordingly. [The related cleaning design issue is created here.  ](https://app.zenhub.com/workspaces/design---ui-60ab5f96c64ec50014c46754/issues/blockframes/blockframes/7329)

**Comment by cams-goussale** [comment]
Last wording from @maltmayer and @isseymiyuki :

**TV
Movie**
