### ISSUE TITLE
Optimization of Genres filter

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7001]
- [x] Reduce the list of Genres. Verify with Marie and Yuki

When validated, then
- [x] Go to the Checkboxes 
- [x] Verify if Titles previously uploaded have a Genre that is deleted. Define Strategy how to manage this case.
[Wireframe is here ](https://www.figma.com/file/vmwPJzLshwzT1FGwrECDlo/Filters-Update?node-id=330%3A3972)

**Comment by 2amarkina** [comment]
List of Genres is updated. 
[It can be found here, H8](https://docs.google.com/spreadsheets/d/1BShPU5jcOajYCqEIAQaSshs3ojpFhOi0qHVnXTC5dQM/edit#gid=0)

Wireframes are updated accordingly
![Снимок экрана 2021-11-08 в 16.34.22.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/129ab37f-771c-4db2-a6ac-463226ddc254)

If a title contains a genre that was removed, then this genre should become a keyword. All genres should be verified manually to avoid errors.

**Comment by 2amarkina** [comment]
Can go to devs. 
The UI mockups should be updated accordingly. [The cleaning design issue is created here](https://app.zenhub.com/workspaces/design---ui-60ab5f96c64ec50014c46754/issues/blockframes/blockframes/7328)

**Comment by Poppe-A** [comment]
Genres to remove :
Period Drama
Young Adult
War
Police
Web Series
Wildlife
Hunting & Fishing
Archeology & History
Travel & Discovery
Nature & Environment
Fashion
Western
TV Show
Virtual Reality
