### ISSUE TITLE
Org member can accept/decline request to join org in Invitations

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7005]
An user with 'member' permissions in the organisation cannot send invites to users, accept/decline request on the Organisation page, but the user can accept/decline requests to join org on the Invitations page.

@Jackseed this bug must have been in the apps for years. Did nobody notice it or did we never prioritise it to fix it?

**Comment by RemcoSimonides** [comment]
Related to #6753

**Comment by Jackseed** [comment]
Let's wait for #7006 before going on with this one

**Comment by RemcoSimonides** [comment]
Just tested again. Member can see the invitation and accept/decline button but will receive a 'firebase insufficient permissions' error when clicking the action button

**Comment by Jackseed** [comment]
And do you know if we already have a way to filter who's receiving an invitation based on their org permissions? To me this was the only time where it could have happen...

**Comment by RemcoSimonides** [comment]
As far as I know, we don't

**Comment by Jackseed** [comment]
Alright then let's wait for the UX issue to have a broader plan before tackling this bug

**Comment by phpgeekfr** [comment]
There is a proposal to remove 'super admin', 'admin', and 'member' 
https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/6753

So this may be not an issue anymore
