### ISSUE TITLE
Movie creation : fields not mandatory create an error

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7023]
## Your environement
- OS: Windows
- Browser (& version if possible): Chrome

## Review item
_Copy & fill this section for each item._
### Localization
- App name: Festival
- Page: Create movie
- Url: https://staging.archipelmarket.com/c/o/dashboard/tunnel/movie/X2Qkx9aHgL7jwBCd7bcf/summary
- User used (if anonymized): (seller userId) X2Qkx9aHgL7jwBCd7bcf

### Context
1) After filling all mandatory fields to create a movie, there are 2 errors blocking the publication: Production Company and Distributor. However, these fields are not mandatory so they should not be considered errors.

![image](https://user-images.githubusercontent.com/93206363/140063591-9bcfa926-66df-4bf7-9bae-010493632583.png)
![image](https://user-images.githubusercontent.com/93206363/140063648-bf8d8905-e944-4361-b81f-819d86434606.png)

In the database, these fields are also empty:
![image](https://user-images.githubusercontent.com/93206363/140069318-d1afe6e8-d30b-4616-9f61-fa6491d709f7.png)

2) The error sentence warning (in red) is to techy and we would like to modify it.

### Fix
- [ ] These 2 missing fields should not be detected as errors: **Production Company** and **Distributor**
- [x] Can we change the sentence to "You have _n_ errors blocking the publication: _..._"

**Comment by Jackseed** [comment]
Updated as high priority since we ran into this issue a lot during the release tests and we saw users on prod blocked by this. There basically 0 fix when you encounter the issue so the user is blocked with a wrongly formatted movie and has to do it over again...

**Comment by RemcoSimonides** [comment]
https://github.com/blockframes/blockframes/issues/7150#issuecomment-971343729
It's with Excel import that I get this error.

You can see an example:
-userId rzf1Zw3fxTXYp56UlJj01pSbaCG3
-movieId TifZ3y8uE2CQZIdKY76N

[v2_TEST_101121_import titles test sept 21.xlsx](https://github.com/blockframes/blockframes/files/7552846/v2_TEST_101121_import.titles.test.sept.21.xlsx)
![Title with ERROR_AC_import_1711](https://user-images.githubusercontent.com/93206363/142162165-b5c52d5a-5a84-4360-a94b-a02be8e8975c.gif)

**Comment by Jackseed** [comment]
I also ran a lot into this error bug without using excel import, though I'm not able to reproduce it as it looks 'random' so far

**Comment by RemcoSimonides** [comment]
Tried to reproduce it again but to no success :/

**Comment by cams-goussale** [comment]
Hola @RemcoSimonides I used Chrome. Should we try to reproduce it during a call?

**Comment by RemcoSimonides** [comment]
I managed to reproduce the error locally. When I switch to the exact same code as on Staging, then I get the error. If I go back to our latest code, then it’s gone. So someone somewhere somehow fixed it

**Comment by cams-goussale** [comment]
Hello @RemcoSimonides :) can you confirm this point of my initial comment will also be implemented on the next release?

> The error sentence warning (in red) is to techy and we would like to modify it.
Can we change the sentence to "You have n errors blocking the publication: ..."

**Comment by RemcoSimonides** [comment]
Ye it's in there ;)
