### ISSUE TITLE
Analytics for Sellers

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7031]
### Description

One strategic axis for the Archipels is to give more and more analytics to sellers as this would be a true competitive advantage. 
Objectives here are:
- help sellers to know how their titles are performing
- give sellers a list of buyers interested in their titles
- overall, these analytics are meant to increase sellers' sales

Thus outcomes of this project are:
- increase sellers' engagement, meaning connexions to our apps
- nurture the need for these analytics for all their titles, increasing title creation
- lastly it should nudge sellers to increase their activity on titles for better analytics, increasing overall app activity (screenings, title info)

### What's new

More research has to be done to test and learn what's the best analytics we could show and how handy it could be but here is a first list of ideas:
- Add an Analytics section to dashboard
- "Linkedin vibe" analytics: amount and name of buyers who viewed sellers' titles, added to whishlist or watch a promotional video
- "Mailchimp vibe" analytics: comparison of a title vs all titles average | vs all seller titles average | vs all alike titles (genre) average. Eg you made 20% more views than average for this title your first month
- Report emails 

### User Scenarios

- As a Seller I want to know who interacted with each of my Titles
- As a Seller I want to know what interactions Buyers had with each of my Titles
- As a Seller I want to know  how each of my Titles is performing compared to others

### Estimation

TBD

### Priority

Medium

**Comment by RemcoSimonides** [comment]
Most of this data can come from Google Analytics. For some events we need to add an extra event to Google Analytics. But since some browsers block the data sent to Google Analytics, I'm wondering if it's better to 'create our own' analytics so the data will be more accurate.

**Comment by cams-goussale** [comment]
Dev epic #7689
