### ISSUE TITLE
User without orgId doesn't receive invitation email to event

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7032]
I sent an invitation to an email address which isn't connected with a user yet.
The invitation email with credentials to create their account is created correctly. I don't activate the account yet.
Then I sent another invitation for a different event to the same email address. This time the user does not receive an email.

@Jackseed what is the expected behavior? should we send another email with their credentials? (if that's even possible) or just a normal invitation email as if the user has already activating their account

**Comment by Jackseed** [comment]
We discussed that with @Poppe-A and solution was to send a new invitation email without credentials that points to the previous email with creds [cf this template](https://mc.sendgrid.com/dynamic-templates/d-454847c886d4485586c3d1b4f467c03f/version/906fbcd2-2f5c-4d7e-8e4b-72e40c34fa9b/editor)
