### ISSUE TITLE
Buyer validation for email address sharing

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7034]
In order to implement the buyer list we will update our T&Cs and Privacy policy to warn users that their email address may be shared with Sellers. 
This means that we need to design:
- a flow for existing buyers to accept our new T&Cs & Privacy Policy
- a way for buyers to set their email address as private if they don't want to share it

**Comment by Jackseed** [comment]
@Jackseed check if users have to accept these new T&Cs

**Comment by cams-goussale** [comment]
After legal discussion, yes, the 2 points above must be handled.
About this one, let's think of 2 places where user can hide their email: in the Auth flow + on Profile page
> a way for buyers to set their email address as private if they don't want to share it

**Comment by frenchyrules** [comment]
As we cannot use a tooltip for an action (like clicking on a link) a text may be better suited here. 
![image](https://user-images.githubusercontent.com/85220905/156567552-b0aa75b6-342e-4e67-b654-d4aea1466caa.png)

**Comment by frenchyrules** [comment]
wireframe link [here](https://www.figma.com/file/Jte3fEhov35fVKAiRudnjj/Buyer-validation-for-email-address-sharing?node-id=18%3A336)

**Comment by cams-goussale** [comment]
This is cool @frenchyrules thanks. Can we try with a toggle or switch button?

**Comment by frenchyrules** [comment]
> This is cool @frenchyrules thanks. Can we try with a toggle or switch button?

Yes, here's what it would look like:
![image](https://user-images.githubusercontent.com/85220905/156749568-6e6e731c-9143-4a30-80c2-46cfb7763624.png)

**Comment by cams-goussale** [comment]
I really prefer the switch button ! And we should desactivate it by default. We want users to show their email adress as much as possible.

I've asked Marie & Aurore for the text. Will let you know asap

**Comment by cams-goussale** [comment]
After Business review:

- [ ] Let's go for the switch button on both Auth form and Profile page
- [ ] About the 'Delete my data' section -> let's create an issue dedicated to this. It might need some discussions with Business.

**Comment by cams-goussale** [comment]
Text validated by Aurore 👍

**Comment by 2amarkina** [comment]
**Updt. :** 

1. Put a **banner on the Homepage** for a month after the update of privacy
![homepage.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/216d1628-5e65-4bc8-adda-d2ee5776f3e9)

2. Introduce a **notification about the new privacy policy**. 
![notification.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a40e234b-183a-4617-ad3d-c892e5940ce9)

3. **Profile page update**
![Снимок экрана 2022-03-11 в 14.05.01.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/f15717cc-ee9f-469a-871d-badc24dcd6d9)

4. **Sign up page**
![sign up.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/f384bfdb-4a67-4fea-8849-ed13fe5a9b69)

**Last question which is left**: 
Do we agree that if we keep an email secret, we make it secret only on the Organization page, but user's email can still be shown when we invite a user to the events or does it "disappear" completely ?

**Comment by cams-goussale** [comment]
> Do we agree that if we keep an email secret, we make it secret only on the Organization page, but user's email can still be shown when we invite a user to the events or does it "disappear" completely ?

Yes we agree. Email still appear in case of interaction with a movie (Sellers analytics) or invitaton to a screening (core of the app).

**Comment by frenchyrules** [comment]
UI[ here](https://www.figma.com/file/ODvbgSYOb0OyVK6WWVp3NU/Connection-flow?node-id=0%3A1)

**Comment by frenchyrules** [comment]
**UI Designs** (wip)

- [Temporary homepage banner ](https://www.figma.com/file/OMMs8YORBwwvZOMkuw7Vu2/Cookies?node-id=115%3A1099)
- [Sign up page](https://www.figma.com/file/ODvbgSYOb0OyVK6WWVp3NU/Connection-flow?node-id=20%3A210)

**Comment by frenchyrules** [comment]
- Following dev review, it was recommended by that we keep the logo on the AUTH pages as is so that when we scroll it comes out of view. Changing the way it's currently being displayed (position : fixed or other) may cause some jumps when scrolling. 

- I have worked on some new [illustrations](https://drive.google.com/file/d/1Kqy83Rj8RRvCI6ke6JbVhsVoTm43EvHq/view?usp=sharing) for the Sign up page and login page and we need to test it to see how the illustration behaves on a long page, as well as a shorter page (sign up page vs login page). 

@cams-goussale could we please have a dev test this ?

- For the input box proposition on the profile page (position input box 1/2 of the surface width and placed by itself, instead of it taking up the entire width of the surface), it will be developed this way for the profile page, but if any other  pages ever require a similar input box design style it won't be recommended to also build them this way as it complicates things and becomes hard to maintain.

**Comment by cams-goussale** [comment]
> @cams-goussale could we please have a dev test this ?

Yes sure, whenever this issue is treated by a dev, please have a talk with Anthony to make some tests.

**Comment by cams-goussale** [comment]
@frenchyrules there were some comments left on the figma about texts. Could I let you update them?
Also, I'll split this issue in 2 for the devs:1 for the banner (#8168) and 1 for the toggle option.

**Comment by frenchyrules** [comment]
@cams-goussale Updated 👍

**Comment by frenchyrules** [comment]
**UI Design links** 

- [Temporary homepage banner ](https://www.figma.com/file/OMMs8YORBwwvZOMkuw7Vu2/Cookies?node-id=115%3A1099)
- [Sign up page](https://www.figma.com/file/ODvbgSYOb0OyVK6WWVp3NU/Connection-flow?node-id=20%3A210)
- [Profile page](https://www.figma.com/file/ZEwI6O9G61FKgv6X8yt3SE/Profile?node-id=0%3A1)

**Comment by cams-goussale** [comment]
Closing the design issue. Dev issues are created
