### ISSUE TITLE
[CATALOG] Decline modal + Notification

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#7035]
[Figma](https://www.figma.com/file/bs1vDcQEjbqqPggOYMpdd6/%5B-Deal-Negotiation-%5D?node-id=461%3A124665)

TODO

**Comment by 2amarkina** [comment]
[Texts for the emails and notifications](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit)

**Comment by pldespaigne** [comment]
Figma link is broken and we don't have any details on what to do.

**Comment by 2amarkina** [comment]
> Figma link is broken and we don't have any details on what to do.

Did you manage to access the document? I've resent the access to the file.

**Comment by 2amarkina** [comment]
Here is a screenshot
<img width="749" alt="Снимок экрана 2021-11-22 в 15 06 21" src="https://user-images.githubusercontent.com/55499036/142875545-84ee5d0b-e542-42f6-974d-eb0de6a9f7df.png">

**Comment by pldespaigne** [comment]
Thanks for the screen, also I can access the the link now 👍
