### ISSUE TITLE
Shift temporary sendgrid template to prod

### ISSUE THREAD

**Issue by Poppe-A** [blockframes/blockframes#7038]
The last sendgrid templates (reminder for 1h and 24h) are just temporary templates to avoid modifying those used on prod.
Once they will be validated, we need to use them on prod

**Comment by phpgeekfr** [comment]
From my understanding, these old templates will have to be deleted :
```
oneDay: 'd-0c7bcb6e4a234ddc95ed74b9ecc433dc',
oneHour: 'd-8a9439a404cc4b51887e9dea44f7fbd7'
```

and the new ones will be used instead: 
```
  oneDay: 'd-a2f3a222b3a34fce9f5ce6effccdba15',
  oneHour: 'd-f2e4d3c9f55c458a84296c7b66ccad22'
```

@Poppe-A can you confirm ?

@Jackseed I assume that this is what we usually do when updating templates ?

**Comment by Jackseed** [comment]
Best way to go on prod is to use template versions to keep an history of what we had. It means
- duplicating new template content to existing template new version
- activating new versions just after the release
- then I would say delete the dev versions
I can take of it if you want. And I don't know if you could have used template versions on dev, I don't remember how Clélia used to do to test on her side

**Comment by phpgeekfr** [comment]
Finally ,
```
  oneDay: 'd-a2f3a222b3a34fce9f5ce6effccdba15',
  oneHour: 'd-f2e4d3c9f55c458a84296c7b66ccad22'
```
are the ones to delete

**Comment by phpgeekfr** [comment]
deleted
 ```
oneDay: 'd-a2f3a222b3a34fce9f5ce6effccdba15',
  oneHour: 'd-f2e4d3c9f55c458a84296c7b66ccad22'
````
