### ISSUE TITLE
Festival App - Request invite for Private Screening Event is not received by the event creator.

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#7041]
Can be recreated with Create-screening test or checked manually.

![image](https://user-images.githubusercontent.com/8731418/140380630-64aad6be-edd0-49f7-8005-2b1df6f893d9.png)

![image](https://user-images.githubusercontent.com/8731418/140380200-2a88cf9b-083a-41cf-9e96-c552a794ba82.png)

**Comment by phpgeekfr** [comment]
looks like linked to #7004
