### ISSUE TITLE
Design PDF of Catalogue export

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7045]
To go with the new feature of exporting the catalogue in pdf (#6991) we need a design of a pdf to go along with when exporting it. 
Here is a file sample of what Yuki is currently using: [Catalogue 202110 Kid & Teen series for GMA.docx](https://github.com/blockframes/blockframes/files/7475909/Catalogue.202110.Kid.Teen.series.for.GMA.docx)

We can differentiate from that but it gives us the important info to mention:
- poster
- title
- content type 
- length 
- release year 
- available versions
- synopsis
- trailer link (if available)
- festival selections & rewards
- link to the title in-app

**Comment by Jackseed** [comment]
@isseymiyuki could you have a look to this [file](https://github.com/blockframes/blockframes/files/7511424/pdf.pdf) and give us a review plz?
@GrandSchtroumpf (if you're the one who reviewed) - is there some parameters that are particularly complex to use?

**Comment by GrandSchtroumpf** [comment]
The main limitations related to pdf generation are : 
- PDF have large margins (larger than what you've got here I think)
- We won't be able to specify when there is a new page (might be in the middle of a paragraph). I think PDF don't cut images though.
- We won't support theme, so if a user download a list during screen-daily event it'll still be blue.

Also let's keep in mind that we won't be able to use angular, so everything we already spend time on (button style, feature line below the title, ...) will have to be recreated with a less efficient tool (handlebar in this case I think). The feature line below the title might take some time depending on the limitation (what if there is many countries, ...)

**Comment by frenchyrules** [comment]
Updated PDF design 
![research results export](https://user-images.githubusercontent.com/85220905/141124537-a54ee752-417d-44fb-9414-4a3a34548a3b.png)

**Comment by frenchyrules** [comment]
[Zepelin link](https://zpl.io/V1A8G95)

**Comment by stephanie-cascade8** [comment]
@isseymiyuki @Jackseed it's ready for a business review

**Comment by Jackseed** [comment]
Latest version:
![image](https://user-images.githubusercontent.com/14964443/142647926-fb46e711-aa7c-45ad-8d43-c27c89998fc6.png)

**Comment by phpgeekfr** [comment]
@stephanie-cascade8 @frenchyrules I think I will be able to display only 2 titles per page. 
Depending of the festival count and of the synopsis length, I will maybe have to crop synopsis so we can always have 2 titles per page.

Do I need to repeat app logo at each page header ? Is there a footer to implement ?

Where I'm so far
[https://app.zenhub.com/files/165818079/e0b065fc-968f-4edc-8b1c-a5a4b9af449e/download](https://app.zenhub.com/files/165818079/e0b065fc-968f-4edc-8b1c-a5a4b9af449e/download)

**Comment by phpgeekfr** [comment]
- [ ] on technical side, is it better to send file directly (using `https.onRequest`) or to store it to bucket with a TTL and send the url (using `https.onCall`) ?

**Comment by phpgeekfr** [comment]
@stephanie-cascade8 @frenchyrules  please find 2 examples:

First example is the better IMO, because no need to handle page breaks that can be hard to  accomplish with various synopsis length and prizes count, but on firefox and external PDF reader, since this is only 1 big page, I cannot zoom in it as I want :
[https://app.zenhub.com/files/165818079/8f9b175a-af62-46ef-8dbd-6641f7a5be95/download](https://app.zenhub.com/files/165818079/8f9b175a-af62-46ef-8dbd-6641f7a5be95/download)

second one is with page breaks (a4 format) but it will be hard to handle page break with movies like `Whale Island` (page 14) for example :

[https://app.zenhub.com/files/165818079/5c822f9a-97a9-4393-b280-b4a991080c6b/download](https://app.zenhub.com/files/165818079/5c822f9a-97a9-4393-b280-b4a991080c6b/download)

**Comment by stephanie-cascade8** [comment]
Hi Bruce ! It looks really great :)
Actually I should have been more precise (we just want a one pdf page to
scroll like you have, no need for A4 format and break pages management)
Can we have the top of the movie title aligned with top of the movie poster
? And blue links in bold?

**Comment by phpgeekfr** [comment]
@stephanie-cascade8 
A few more questions: 
For now I added the PDF export button like this (last one right):
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/c4abffa6-a17e-48f3-ae17-9ef3f6351e6c)

Is there a better button to use ?
Currently, only added on festival, do I need to add it on another apps ?

**Comment by stephanie-cascade8** [comment]
Ideally we should have a button like yours but with a "download" icon it's
a cloud with arrow inside. And if possible quickly : a tooltip that says
"download pdf".

**Comment by cams-goussale** [comment]
hello @phpgeekfr :) this is for Content only, not Festival

**Comment by phpgeekfr** [comment]
Updated icon : 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/6e9708dd-e7c8-4978-bf50-d676b02ea8d0)

**Comment by phpgeekfr** [comment]
@cams-goussale added only on catalog for now but can be added on other apps easily

Latest example with suggestions taken into account :[https://app.zenhub.com/files/165818079/f6091cf4-46fc-4554-8c7c-b33e98b3662c/download](https://app.zenhub.com/files/165818079/f6091cf4-46fc-4554-8c7c-b33e98b3662c/download)

**Comment by phpgeekfr** [comment]
To prevent pages too big that does not render well on some PDF softwares, here is a new example with page breaks every `6000 px` :

[https://app.zenhub.com/files/165818079/b53a1918-a392-439a-a0f0-1668c004f58c/download](https://app.zenhub.com/files/165818079/b53a1918-a392-439a-a0f0-1668c004f58c/download)

- If page (depending of movies count) does not exceed 6000px => no white space at end of PDF
- If number exceed 6000px, PDF will be split in several pages of 6000px height, this can cause large white space at end of PDF

Waiting for @isseymiyuki's feedback

**Comment by Jackseed** [comment]
Feedbacks from Yuki: 
- Content type is missing (just below title)
- If possible, could we also add genres aside content type? Something like "Feature Film - Horror, Action"
- A poster is broken on an example, is it because there is none? If so, could we use poster fallback from the app?
