### ISSUE TITLE
Update theme and logo for new Screen operation

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7046]
We'll start again the partnership with Screen International for the Oscar race from November 22nd till April. 
On dev side what it implies is:
- [ ] Change theme:

In `apps\festival\festival\src\styles.scss`:
Change 
```scss
@import "../../../../styles/themes/blockframes.scss";
```
to :
```scss
@import "../../../../styles/themes/screen-daily.scss";
```

- [ ] Add logo : 

In `apps\festival\festival\src\app\marketplace\marketplace.component.html`
Add in the header :
```html
<a href="https://www.screendaily.com/">
  <img src="/assets/image/screen-logo.png" width="300" height="85" />
</a>
```
Update the style of the header if needed

-----

We'll release these changes during the 3.5 release to avoid doing a specific release for this.

**Comment by RemcoSimonides** [comment]
@Jackseed 
Where should the logo be positioned?
![image](https://user-images.githubusercontent.com/27687382/140891279-33b593e8-4199-4334-af3e-b691b5c7b42e.png)

**Comment by Jackseed** [comment]
- [ ] Small change but click on screen logo should open a new tab
cc @phpgeekfr & @Poppe-A for the anonymous pages

**Comment by phpgeekfr** [comment]
I'm on it. @RemcoSimonides I can update it for marketplace also

**Comment by phpgeekfr** [comment]
done, included in current release branch
