### ISSUE TITLE
Screen operation

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7047]
We'll start again the partnership with Screen International for the Oscar race from November 22nd till April.
On UI side what it implies is:
- [x] prepare the posters to be sent by @maltmayer 
- [x] change the banner image with new text & dates (to come)
- [x] theme review

Estimated for 1,5-2day of work

**Comment by stephanie-cascade8** [comment]
Adds are done and validated by marie and yannick but

- [ ] posters movie to chose by Yuki for the fullpage
- [ ] MPU animation returns from marie and Yannick

(Anthony is on the MPU gif animation on after effects)
<img width="824" alt="Capture d’écran 2021-12-01 à 14 34 38" src="https://user-images.githubusercontent.com/66258851/144245191-4251baeb-3ff4-4fcf-9f98-fea8d7314f9d.png">
