### ISSUE TITLE
Screen advertisements

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7050]
3 advertisements on Screen are planed:
- [x] 1 banner 
- [x] 1MPU (small square on their website) 
- [x] 1 print for February 

@maltmayer will be the one briefing all this

**Comment by frenchyrules** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/85220905/144592528-49a69cf7-2223-4ac0-b55b-7a673ba4f4ea.gif)
