### ISSUE TITLE
Release 3.5 - Profile

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7053]
[Test scenarios and Test cases](https://www.notion.so/cascade8/Profile-e2e236dfdab24c44af03db17a44aed43)

Changes in this release so please double check:
- #6754
- #6845
- #6718

**Comment by xmano** [comment]
Misleading status when trying to change password with incorrect old password

![image](https://user-images.githubusercontent.com/8731418/141059749-241ae4ca-35e9-436e-be54-d969652963b4.png)

Error message needs to be corrected. Functionality is ok since the password isn't changed.

**Comment by xmano** [comment]
Profile Picture - an error message is displayed when pausing / cancelling profile picture upload:

![image](https://user-images.githubusercontent.com/8731418/141066958-4aebbae1-ed5e-45ee-96ff-fbac82d7104c.png)
