### ISSUE TITLE
Release 3.5 - Organisation

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7054]
[Test scenarios and Test cases](https://www.notion.so/cascade8/Organisation-55ded6f0e09c4aa29fb2e3f716bb8b50)

Changes in this release so please double check:
- #6805

**Comment by xmano** [comment]
In org member view edit button (extreme right) seems to do nothing. If there is no functionality attached, can it be removed?

![image](https://user-images.githubusercontent.com/8731418/141306964-a4898926-a6b8-4533-9103-a8f895edcb76.png)

**Comment by Jackseed** [comment]
> In org member view edit button (extreme right) seems to do nothing. If there is no functionality attached, can it be removed?
> 
> ![image](https://user-images.githubusercontent.com/8731418/141306964-a4898926-a6b8-4533-9103-a8f895edcb76.png)

Indeed, this edit button is for admins only and shouldn't be visible for all users

**Comment by xmano** [comment]
> > In org member view edit button (extreme right) seems to do nothing. If there is no functionality attached, can it be removed?
> > ![image](https://user-images.githubusercontent.com/8731418/141306964-a4898926-a6b8-4533-9103-a8f895edcb76.png)
> 
> Indeed, this edit button is for admins only and shouldn't be visible for all users

It is displayed for super-admin but does nothing.. the issue reported is for this.

**Comment by cams-goussale** [comment]
- [ ] Admin view doesn't have the edit option to add or remove members
![image](https://user-images.githubusercontent.com/93206363/142191452-ac6139ad-61f2-4614-8fb1-8e117e2ccb13.png)

**Comment by RemcoSimonides** [comment]
If you scroll down, you can invite members. You can't remove them indeed which is a bug.
I've already mentioned the issue in #7005
![image](https://user-images.githubusercontent.com/27687382/142224682-f4a311cb-a15f-4e2e-929e-8a6a3a77cfe8.png)
