### ISSUE TITLE
Release 3.5 - File explorer

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7057]
[Test scenarios and Test cases](https://www.notion.so/cascade8/File-Explorer-08ea83d7e82f437c9b96e22e87d8df7c)

Changes in this release so please double check:
- #6824

**Comment by yspringfield** [comment]
url: https://staging.archipelmarket.com/c/o/dashboard/files
page: titles -> title name -> images -> other images

During upload of image, when we cancel it, it rather indicates an error occurred giving the impression that something went kaput even though nothing went wrong.
<img width="525" alt="Bildschirmfoto 2021-11-10 um 10 43 31 AM" src="https://user-images.githubusercontent.com/22674720/141093184-7cfaec1b-06fb-4dd5-b488-39c7761268c5.png">

**Comment by RemcoSimonides** [comment]
Fixed ☝️
