### ISSUE TITLE
Release 3.5 - Screening

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7060]
[Test scenarios and Test cases](https://www.notion.so/cascade8/Screening-69f2b3a496394341aa16227d58109eb4)

Open Bug:
- #7041
- #7004

Bugs fixed in this release so please double check:
- #3900
- #5895
- #6247
- #6562
- #6643
- #6784
- #6786
- #6787
- #6828
- #6829
- #6917
- #6933
- #6944

**Comment by Jackseed** [comment]
- [ ] Stats not recorded on event https://staging.archipelmarket.com/c/o/dashboard/event/FIhq58m4cdUttZ4peU6O/edit/statistics
with dev+daphne-mhe@blockframes.io

**Comment by Jackseed** [comment]
- [ ] "More details" link on notifications for acceptation / decline of event invitation need to be updated with new event links
![image](https://user-images.githubusercontent.com/14964443/141306738-4c6c2fc7-cea2-4c10-96e6-c6ac3c9a2f62.png)

**Comment by Jackseed** [comment]
- [ ] Request access button disappears on a private event, marketplace event view

https://user-images.githubusercontent.com/14964443/141338870-c60f679e-8a96-4eac-92a9-2b9a864d7f69.mp4

**Comment by cams-goussale** [comment]
- [ ] If possible, add an Asterisk to the Title selection as it is mandatory

![image](https://user-images.githubusercontent.com/93206363/141460449-a3059836-108d-4727-b35c-24f81c03dd13.png)

- [ ] **Edit event** button on the Screening page on marketplace doesn't work

![image](https://user-images.githubusercontent.com/93206363/141460541-505e8b5a-4ecd-4ac0-b4c3-4dbf1bf30818.png)

- [ ] In-app notification for **Reminder of the event in 1h** is not sent. Only "1 day reminder" and "about to start" reminders
Tried with user id xKIJf1ZFqVVKaHfUAwXWASvARLA3
Event "Test notif 1h reminder" | Guermantes | id gN56EhwLCStHgRBj1j8h

**Comment by phpgeekfr** [comment]
> Edit event button on the Screening page on marketplace doesn't work

Can you provide more details ? From which page where you coming and what was the behavior please ?

**Comment by phpgeekfr** [comment]
> In-app notification for Reminder of the event in 1h is not sent. Only "1 day reminder" and "about to start" reminders
Tried with user id xKIJf1ZFqVVKaHfUAwXWASvARLA3

Ok, we may need to make more tests on this, if "1 day" and "about to start" worked, other should have also. Maybe due to today issues on googlecloud

**Comment by cams-goussale** [comment]
> > Edit event button on the Screening page on marketplace doesn't work
> 
> Can you provide more details ? From which page where you coming and what was the behavior please ?

Edited in my review. Is it ok now?

**Comment by phpgeekfr** [comment]
> > In-app notification for Reminder of the event in 1h is not sent. Only "1 day reminder" and "about to start" reminders
> > Tried with user id xKIJf1ZFqVVKaHfUAwXWASvARLA3
> 
> Ok, we may need to make more tests on this, if "1 day" and "about to start" worked, other should have also. Maybe due to today issues on googlecloud

I created a new event to test this

**Comment by phpgeekfr** [comment]
>  If possible, add an Asterisk to the Title selection as it is mandatory

This can look easy to solve but it messes up with the save button on top right. I think this will need more investigation and check with the business side after the release.

**Comment by phpgeekfr** [comment]
> > > In-app notification for Reminder of the event in 1h is not sent. Only "1 day reminder" and "about to start" reminders
> > > Tried with user id xKIJf1ZFqVVKaHfUAwXWASvARLA3
> > 
> > 
> > Ok, we may need to make more tests on this, if "1 day" and "about to start" worked, other should have also. Maybe due to today issues on googlecloud
> 
> I created a new event to test this

In fact, we only have two types of reminder :
```
  'eventIsAboutToStart', // 1h Reminder before event
  'oneDayReminder', // 24h Reminder before event
```

**Comment by phpgeekfr** [comment]
![image](https://user-images.githubusercontent.com/1194344/141479283-27341fe5-9b3e-4163-82a3-f381158614d5.png)

I received the  eventIsAboutToStart' / 1h Reminder before event email

Also got the in-app notification : 
![image](https://user-images.githubusercontent.com/1194344/141479731-2f0ee641-256d-485a-bc6c-c6b8658cd9f0.png)

**Comment by cams-goussale** [comment]
hello @phpgeekfr :) is it possible to include in this release some improvments of the Event Statistics Report? The idea is to have:

[movies.title.international on Archipel Market event.start - Report.xlsx](https://github.com/blockframes/blockframes/files/7538965/movies.title.international.on.Archipel.Market.event.start.-.Report.xlsx)

- [ ] 2 tabs with more details on the guests (see excel attached)
- [ ] change the _Export to CSV_ button to _Export to Excel

![image](https://user-images.githubusercontent.com/93206363/141789779-d03421aa-7ac3-4b85-b826-2098b4270420.png)

If too late, i'll just create a dedicated issue

**Comment by Jackseed** [comment]
@cams-goussale it's gonna be too much for the release, we need to make it as a dedicated issue for next one ;)

**Comment by RemcoSimonides** [comment]
## MARKETPLACE
### HOMEPAGE / Event Slider
- CTA should not send request here. It should be "Check Out Event" and lead to the event page. Otherwise it's confusing. When I click "Access Event" for public events, I expect to go on the event page, but instead, the status changes to "Request Pending" and then leads me to the screening room... It's too abrupt and super confusing, not what the user would expect. I would generalize the behavior and just lead everyone to the event page where they can then request access or access directly when public.

### SCREENING SESSION 
- [ ] Problem with the illustration (if you look close, some seats go over people's bodies)
![image](https://user-images.githubusercontent.com/55785823/141773911-00c9174d-4afc-4048-bc6c-6ad641c4e949.png)

### SCREENING SESSION - No video
- This page should be improved visually. Have an illustration or at least a CTA to contact us or the sales company
![image](https://user-images.githubusercontent.com/55785823/141771432-5e4cb30f-6ade-472b-a8c7-f5a1246fecfb.png)

### CALENDAR
- [ ] Calendar page doesn't show up (weird url) when I click on it from event page. It works from other pages just not event pages...

https://user-images.githubusercontent.com/55785823/141801175-a6b80bcf-c25a-4d18-824c-183ad52f31d4.mov

**Comment by cams-goussale** [comment]
Hello! I have a light blue color on the logo with **Firefox**
might be linked to #4454

![image](https://user-images.githubusercontent.com/93206363/141823531-bd63ae79-15f1-4af7-800b-ba44572a20d5.png)

**Comment by RemcoSimonides** [comment]
** On the Event details page.**

- [ ] Event description should be a mat-body-1 and the line-height should be 24px.

<img width="1167" alt="Capture d’écran 2021-11-15 à 12 53 41" src="https://user-images.githubusercontent.com/66258851/141777768-d3ce6307-3b6f-47dc-bcbd-a11785f49f62.png">

**Comment by RemcoSimonides** [comment]
## Item Reviewed: Event Creation
_Copy & fill this section for each item._
### Localization
- App name:  Market (dashboard)
- Page: Calendar (new event)
- Url: https://staging.archipelmarket.com/c/o/marketplace/event/calendar
- User used (if anonymized): admin

### Context
I'm looking at the events creation

- [ ] cross should be simple without background and there must be space around (surface padding: 24px)
<img width="733" alt="Capture d’écran 2021-11-15 à 13 01 59" src="https://user-images.githubusercontent.com/66258851/141779132-3629ec95-9d45-4a34-8bd7-ba1a96352630.png">

- after editing an event (seller's side)

- [ ] popup needs to show buttons one above the other.
- [ ] New line (<br>) before "if you leave now"
- [ ] Blur effect missing on the background
- [ ] popup width should respect the new min-width implemented (Min-width: 50vw, max-width: 80vw more details on modals rules [here](https://www.notion.so/cascade8/Modals-warnings-0c8d7ccd3bab4c1c904da5c4b8aa48e4)
<img width="1230" alt="Capture d’écran 2021-11-15 à 16 24 53" src="https://user-images.githubusercontent.com/66258851/141808333-1bd52113-cf7d-4443-a1b2-a0b8d872811f.png">

- when joinin an event without log in or sign up (from an invitation by email)

- [ ] This part is way too big (the surface needs to be 80% of the container size , which is here the button)
- [ ] We need the logo on this page to be in the layout (not on position fixed) so that elements can align properly.
- [ ] Buttons should be 215px width and height and border-radius: 100%;
- [ ] I should provide images without the circle, so we can have to rounded button behind react on hover.
<img width="900" alt="Capture d’écran 2021-11-15 à 16 58 09" src="https://user-images.githubusercontent.com/66258851/141813978-e3e65592-0ccb-4ad5-870d-8fd8067889d7.png">

<img width="663" alt="Capture d’écran 2021-11-15 à 17 03 42" src="https://user-images.githubusercontent.com/66258851/141814319-17576348-6706-4202-9c99-fa5c7f636d85.png">

- [ ] "organizer" and "guest" should be outside of the button circle

**Comment by phpgeekfr** [comment]
@RemcoSimonides regarding 
![image](https://user-images.githubusercontent.com/1194344/141968863-3264d7b7-6f35-4dfa-9c18-2ec6cf9b0d50.png)

If we make the changes in #7134 this page should not appear anymore

**Comment by phpgeekfr** [comment]
> hello @phpgeekfr :) is it possible to include in this release some improvments of the Event Statistics Report? The idea is to have:
> 
> [movies.title.international on Archipel Market event.start - Report.xlsx](https://github.com/blockframes/blockframes/files/7538965/movies.title.international.on.Archipel.Market.event.start.-.Report.xlsx)
> 
>     * [ ]  2 tabs with more details on the guests (see excel attached)
> 
>     * [ ]  change the _Export to CSV_ button to _Export to Excel_
> 
> 
> ![image](https://user-images.githubusercontent.com/93206363/141789779-d03421aa-7ac3-4b85-b826-2098b4270420.png)
> 
> If too late, i'll just create a dedicated issue

moved to https://github.com/blockframes/blockframes/issues/7135

**Comment by cams-goussale** [comment]
When sending an invitation for a Public screening to user without account, user can access the screening room but buttons Accept and Decline are not doing anything

event id pBX4qOmn48rpxwmtBgXy

![image](https://user-images.githubusercontent.com/93206363/142187027-bcbf34ee-4ef9-4476-bae4-d51d948f15ad.png)

**Comment by RemcoSimonides** [comment]
Separate issues have been created for the leftover tasks so closing this one.
