### ISSUE TITLE
Release 3.5 - Meeting

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7061]
[Test scenarios and Test cases](https://www.notion.so/cascade8/Meeting-7d16f2abef1a4b5b85b5a1889dfa1eab)

Changes in this release so please double check:
- #5219
- #6639

**Comment by cams-goussale** [comment]
hello @phpgeekfr and @antoine :)
This is the review from last week's meeting test with 9 persons. Can some of these points be fixed for the release next week?

## Your environement
_Please describe your environment_ 
- OS: Windows and Mac depending on users
- Browser (& version if possible): Chrome, Safari

## Review item
_Copy & fill this section for each item._
### Localization
- App name: Market
- Page: Meeting page
- Url: https://staging.archipelmarket.com/c/o/marketplace/event/OpchYPkh0m4PK1CkUrte/lobby
- User used (if anonymized): 9 users with 2 sellers, 7 buyers. See [details here](https://docs.google.com/spreadsheets/d/1CenZNjfrP8rnHTQyRwrohYYJnYOnD_XeutntDV95Gmc/edit#gid=0)

**1. Color background**
Context: When there are some users who haven't join the meeting yet, there is a white/transparent rectangle for the missing persons.
- [ ] Fix: Change the color to the background layout which is called "--background" in our builder - to test with Stéphanie

![image](https://user-images.githubusercontent.com/93206363/140716179-7f0a9114-3006-4479-b7c7-28e5809d9075.png)
![image](https://user-images.githubusercontent.com/93206363/140719286-06e248fe-ec1e-4621-ab86-2505e02e74de.png)


**2. Too much black for the large view.**
- [ ] Fix: If possible, have the cameras in format 16:9 to avoid all the black spaces.

![image](https://user-images.githubusercontent.com/93206363/140782796-931110d1-4c24-46bf-ac01-5c66c1c15e41.png)


**3. Watermark to be higher**
- [ ] Fix: Place the watermark higher so it doesn't overstep too much on the content displayed.

![image](https://user-images.githubusercontent.com/93206363/140718771-893ebcfa-625c-4632-97ce-715e6a646dc4.png)


**4. Maximize button on the video conference room**
Context: A user can maximise / expand in full screen the content shared, but they can't with the room's cameras.
- [ ] Fix: If possible, add a maximize button for the video conference section.

![image](https://user-images.githubusercontent.com/93206363/140783297-6efd828e-648f-4ef4-ab19-50217fc969dc.png)


**5. PDF sharing issues**
- [ ] PDF quality is bad (tested with other pdf and still low quality)
- [ ] The page switchers should _not_ be visible for the buyers, only the sellers

![image](https://user-images.githubusercontent.com/93206363/140782504-5dc422ce-7c75-41bb-a6be-189d6a38b148.png)


**8. Issues with sound and muting**
Context:  We couldn't hear one user when he changed his mike from earplugs to computer.
- [ ] Fix: Automatically switch on the main audio channel of the device if something is unplugged.

**Comment by phpgeekfr** [comment]
- [ ]   Events pages are accessible for connected users that does not have access to marketplace : maybe add the "hasAccess" guards that redirect to "Request access" page.
- [ ]  On the login page (after choosing organizer): if we click on "forgot password" "signup" or "create account" on the snackbar if credentials are not ok, user is redirected to good page but then redirected to home page
- [ ]  Prevent two user (or more) to connect with the same email to a "invitation-only" event ?
- [ ]  On event edit page, invitations should be sent only after saving the event form 
- [ ]  add the screening international icon on top bar

**Comment by Jackseed** [comment]
I put it here to gather reviews but it can wait after the release if it's too much:
### Dashboard event form
- [ ] We'll eventually remove the statistics tab from meetings
- [ ] Meetings should always lead to "Meeting" tab on opening
- [ ] If possible (?), remove "Secret" from Privacy settings when it's a meeting

**Comment by Jackseed** [comment]
- [ ] **Safari** turning off camera breaks the page

https://user-images.githubusercontent.com/14964443/141306119-2fa78a12-7ee4-40e3-9481-ee59f3c3bc97.mp4

**Comment by Jackseed** [comment]
- [ ] Margins are missing on event view
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/6f36e3e3-bc32-4a7b-9dbb-8f2e6c31327f)
vs
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/d2369109-2b14-47f5-b87f-038a30ba8088)

**Comment by RemcoSimonides** [comment]
@Jackseed I just tried it on Safari and I don't have any issue... Using v15 of Safari.

**Comment by Jackseed** [comment]
tested again with a fresh new event and alone in the meeting, it happened on the 2nd click on camera button, Safari v15.1
![Kapture 2021-11-11 at 15 31 07](https://user-images.githubusercontent.com/14964443/141315407-7218efbd-4743-453b-808b-9b2438394b4b.gif)

**Comment by RemcoSimonides** [comment]
I've upgraded to Safari 15.1 but still no issue with toggling the camera...

**Comment by phpgeekfr** [comment]
regarding `Place the watermark higher so it doesn't overstep too much on the content displayed.`
I'm moving it up a bit but not too much for 16:9 videos

**Comment by phpgeekfr** [comment]
regarding `Margins are missing on CRM event view`

I can harmonize the margins but can you be more specific ?

**Comment by cams-goussale** [comment]
- [ ] No In-app notification received for the 1-day reminder and neither for the 1h reminder
Tested with user id GD18SKwkG0hWSIouCuRZe2G6G6P2
The 2 events below were accepted, but no Notification received

![image](https://user-images.githubusercontent.com/93206363/141476069-995ac86f-fdfb-4757-93db-21d71b8407b0.png)
![image](https://user-images.githubusercontent.com/93206363/141476116-d292fa81-b461-4075-93f0-49061e5aace2.png)

- [ ] CRM Invitation list doesn't load. Tried with Chrome, Firefox and different users. Other list works well
![image](https://user-images.githubusercontent.com/93206363/141476890-9de5eeb9-741a-4fc5-a0b3-6dd0152d0f37.png)

**Comment by phpgeekfr** [comment]
> CRM Invitation list doesn't load. Tried with Chrome, Firefox and different users. Other list works well

Indeed, error in console : 
```
TypeError: e is undefined
    $paginate https://staging-blockframes-crm.web.app/6046.9f5c7905705397126f1d.js:1
    e/this.data$< https://staging-blockframes-crm.web.app/6046.9f5c7905705397126f1d.js:1
    value https://staging-blockframes-crm.web.app/main.264e66565edffe5fc340.js:1
    value https://staging-blockframes-crm.web.app/main.264e66565edffe5fc340.js:1
    value https://staging-blockframes-crm.web.app/main.264e66565edffe5fc340.js:1
    value https://staging-blockframes-crm.web.app/main.264e66565edffe5fc340.js:1
    value https://staging-blockframes-crm.web.app/main.264e66565edffe5fc340.js:1
    value https://staging-blockframes-crm.web.app/main.264e66565edffe5fc340.js:1
    value https://staging-blockframes-crm.web.app/main.264e66565edffe5fc340.js:1
    value https://staging-blockframes-crm.web.app/main.264e66565edffe5fc340.js:1
    r https://staging-blockframes-crm.web.app/main.264e66565edffe5fc340.js:1

```

**Comment by phpgeekfr** [comment]
> No In-app notification received for the 1-day reminder 
Tested with user id GD18SKwkG0hWSIouCuRZe2G6G6P2
The 2 events below were accepted, but no Notification received

Updated to 
```
> No In-app notification received for the 1-day reminder 
Tested with user id GD18SKwkG0hWSIouCuRZe2G6G6P2
The 2 events below were accepted, but no Notification received
```

since the "about to start" and "1 hour reminder" are the sames

**Comment by phpgeekfr** [comment]
> No In-app notification received for the 1-day reminder
Tested with user id GD18SKwkG0hWSIouCuRZe2G6G6P2
The 2 events below were accepted, but no Notification received

I did received a notification 

![image](https://user-images.githubusercontent.com/1194344/141483652-fbfabe77-1445-4339-8556-5f6bf7209cf4.png)

Email was also sent: 

![image](https://user-images.githubusercontent.com/1194344/141483796-93c70053-b0b3-415a-9e57-c47654ca4383.png)

**Comment by phpgeekfr** [comment]
> CRM Invitation list doesn't load. Tried with Chrome, Firefox and different users. Other list works well

This was already solved and will be updated in next staging update

**Comment by RemcoSimonides** [comment]
### General layout
- [ ]  is it possible to have a max-width and min-width on the whole section that contains attendee's self videos (to decide with dev on live tests if possible).
We need to harmonize the grid there (there is too much space between people)
![Capture d’écran 2021-11-10 à 12.05.02.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/8e4d2990-609c-48d9-88f6-066307592b84)
![Capture d’écran 2021-11-10 à 12.11.59.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/c9aeb419-16e2-4c98-8afa-f9f0c7ea9614)
### Icon visibility
- [ ] When the shared content (video or pdf...) has a white background. The "enlarge screen" icon is not visible anymore.
We could have a discret circle background behind or a transparent band behind. (something to test live)
![Capture d’écran 2021-11-10 à 12.06.14.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/e9a1b334-bff2-423c-ac70-0e707d41603a)

- [ ] Icon should stay fixed in the bottom of the container no matter what the height of the shared content is. Here you can see that it goes up when the shared content is loading for example.
![Capture d’écran 2021-11-10 à 12.13.53.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/e8e5613f-e706-4176-8b57-9988bcc3acae)


### Attendees Names 
- [ ] Truncate and have body-2 or caption instead of body-1?
![Capture d’écran 2021-11-10 à 12.15.42.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/c4b8727c-0abd-4df4-9af3-fb241a11dc0e)

**Comment by phpgeekfr** [comment]
If event did not started and I'm logged in as anonymous, `add to my calendar` should be hidden
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/c255b69d-aa8f-4713-9439-77ce45ca4bf1)

**Comment by phpgeekfr** [comment]
null watermark as anonymous ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/dc09bb68-bdcb-4238-bafc-37cbf90a1da5)

**Comment by phpgeekfr** [comment]
when scrolling, the fullscreen icon is moving with the page [Uploading... image.png]https://files.slack.com/files-pri/TFHC3ULG7-F02MB4DQ5AS/image.png

**Comment by phpgeekfr** [comment]
should display  0:0:0
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/5b2c00fe-1210-44ad-acb7-d9b1ed6cceb4)

**Comment by phpgeekfr** [comment]
Some people have no legs :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/0e920909-4ef8-4125-a557-79dc6f422d09)

**Comment by phpgeekfr** [comment]
- [ ] when user is already muted , the sound icon should be muted for every participants
- [ ] Safari:  camera turns black when turning of the mic
- [ ] Safari:  now when going full screen on video shared, there is still a toolbar that stays at the bottom
- [ ] Safari:  the full screen button once on full screen is not closing the full screen
- [ ] Vincent’s status is ‘ended’ because he crashed himself when toggling camera. Now he gets the pop-up to leave everytime :index_vers_le_haut: . Status should have been reset when he rejoined ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/69c85662-c95c-48d6-b83d-4f5197027d25)
- [ ] Safari: every time media changes, I got that modale
- [ ] Safari: still the error when cutting off camera
- [ ] the page switcher as a buyer is shown when in full screen mode

**Comment by phpgeekfr** [comment]
- [ ] If I invite an non-existing user to an event A and right after the same user to an event B (invitation-only) the invitation should be accepted by default (public or invitation-only) cf `getOrInviteUserByMail` => `if (invitation.type === "attendEvent" && !user.orgId) {`

**Comment by phpgeekfr** [comment]
>     * [ ]  **BRUCE** Margins are missing on CRM event view
>       ![image.png](https://camo.githubusercontent.com/ecb94441506f941ed9b9da56ebc127a79ae675ba5375cb2da6f10c6e7f2747f0/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563366138396163386465316233316435343433616239392f36663336653365332d626333322d346137622d396462622d386632653663333133323766)
>       vs
>       ![image.png](https://camo.githubusercontent.com/a3e1a4a0feb959a663eb15bf0487a9da1777325b1771d75105c2d8b0f38c7318/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563366138396163386465316233316435343433616239392f64323336393130392d326231342d343766352d623837662d303338613330626138303838)

@Jackseed can you provide more info on this please ?

**Comment by RemcoSimonides** [comment]
@phpgeekfr one last open question? ☝️  otherwise you can close this one if you've finished creating the issues for whatever is leftover to do

**Comment by phpgeekfr** [comment]
@RemcoSimonides good now
