### ISSUE TITLE
No connexion events - review

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7067]
OS: Mac
Browser: Safari (& Brave for meetings)
Env: https://festival-blockframes-bruce.web.app 11/08
Users: dev+gerda-isl@blockframes.io (organizer)

### Event form
- [x] When entering the form, I'm redirected to the statistics tab, it should be a redirection to Main tab (Screening / Meeting) when event is present or future and Statistics when it's closed.
- [x] Wording to change for Privacy settings:
PUBLIC - Open to anyone with a link + tooltip with text "Best for Meetings"
PROTECTED - Open to anyone invited to the event (Archipel Market user or not)
PRIVATE - Open to invited, identified Archipel Market users only + tooltip with text "Best for Screenings"
 ![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/3f9a50ad-110f-4aec-8cb9-190cd363a42a)
- [x] Add a snackbar when clicking on "Save" (and saving): "Event saved." for 4s
- [x] Add a snackbar when clicking on Copy the link for screening button: "Link copied." for 4s
- [x] Add a snackbar when clicking on Copy guest emails button: "Guests' emails copied." for 4s
- [x] Statistics didn't show up for this private event https://festival-blockframes-bruce.web.app/c/o/dashboard/event/20R763fRQUQ8BDzPWn2D/edit/statistics (user above)

### Public / Invitation only connexion page
- [x] Split first name & last name inputs in 2 on the same line instead of one above the other
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/a30b7e9b-8c31-44d2-9ec9-0fb242ddd549)

### Anonymous pages 
- [x] Remove the top right settings, name & profile picture to keep only logo on the toolbar
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/ed5ec72e-998c-4e2a-9cb1-62c886b8b0ab)
- [x] Log out automatically the anonymous account if the user navigates to a page different than the event page
- [x] Event view & session pages:  logo doesn't navigate to landing
- [x] I got this error on Brave on the Organizer / guest page while there is no Gmap 
```
Google Maps JavaScript API error: RefererNotAllowedMapError
https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: https://festival-blockframes-bruce.web.app/event/ecsTUwPW11PBbGRp7XIu/r/i/session
```

### Notifications
- [x] I didn't receive the notification as an organizer when an invited guest (for private event) accepted or declined my invitation; should have been so mething like this:
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/e2ec3cf4-07bc-461f-a1bd-f416bc9f3dc2)

### Marketplace event page
- [x] Calendar icon disappear from the toolbar on both event view & session pages

**Comment by phpgeekfr** [comment]
`I got this error on Brave on the Organizer / guest page while there is no Gmap`
Google maps is injected on all pages, you see this only because you are on my env (blockframes-bruce)

**Comment by phpgeekfr** [comment]
`Statistics didn't show up for this private event https://festival-blockframes-bruce.web.app/c/o/dashboard/event/20R763fRQUQ8BDzPWn2D/edit/statistics (user above)`

This should be tested on staging, I'm not sure that analytics is enabled/configured on my env

**Comment by Jackseed** [comment]
> `Statistics didn't show up for this private event https://festival-blockframes-bruce.web.app/c/o/dashboard/event/20R763fRQUQ8BDzPWn2D/edit/statistics (user above)`
> 
> This should be tested on staging, I'm not sure that analytics is enabled/configured on my env

Oh indeed their were warnings that analytics might not work ...

**Comment by phpgeekfr** [comment]
> I didn't receive the notification as an organizer when an invited guest (for private event) accepted or declined my invitation;


Working on my side: 
![image](https://user-images.githubusercontent.com/1194344/141322549-d8f02442-f97a-44c4-a3f2-69d66aa49138.png)

But please notice that this notifications are sent only to org admins (as mentioned in #7004)  was the user an org admin when you tried ?

**Comment by Jackseed** [comment]
I don't remember but I guess the issue comes from this then
