### ISSUE TITLE
Meeting 9 person - review

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7069]
## Your environement
_Please describe your environment_ 
- OS: Windows and Mac depending on users
- Browser (& version if possible): Chrome, Safari

## Review item
_Copy & fill this section for each item._
### Localization
- App name: Market
- Page: Meeting page
- Url: https://staging.archipelmarket.com/c/o/marketplace/event/OpchYPkh0m4PK1CkUrte/lobby
- User used (if anonymized): 9 users with 2 sellers, 7 buyers. See [details here](https://docs.google.com/spreadsheets/d/1CenZNjfrP8rnHTQyRwrohYYJnYOnD_XeutntDV95Gmc/edit#gid=0)

**1. Color background**
Context: When there are some users who haven't join the meeting yet, there is a white/transparent rectangle for the missing persons.
- [ ] Fix: Change the color to the background layout which is called "--background" in our builder - to test with Stéphanie

![image](https://user-images.githubusercontent.com/93206363/140716179-7f0a9114-3006-4479-b7c7-28e5809d9075.png)
![image](https://user-images.githubusercontent.com/93206363/140719286-06e248fe-ec1e-4621-ab86-2505e02e74de.png)

**2. Too much black for the large view.**
- [ ] Fix: If possible, have the cameras in format 16:9 to avoid all the black spaces.

![image](https://user-images.githubusercontent.com/93206363/140782796-931110d1-4c24-46bf-ac01-5c66c1c15e41.png)

**3. Watermark to be higher**
- [ ] Fix: Place the watermark higher so it doesn't overstep too much on the content displayed.

![image](https://user-images.githubusercontent.com/93206363/140718771-893ebcfa-625c-4632-97ce-715e6a646dc4.png)

**4. Maximize button on the video conference room**
Context: A user can maximise / expand in full screen the content shared, but they can't with the room's cameras.
- [ ] Fix: If possible, add a maximize button for the video conference section.

![image](https://user-images.githubusercontent.com/93206363/140783297-6efd828e-648f-4ef4-ab19-50217fc969dc.png)

**5. PDF sharing issues**
- [ ] PDF quality is bad (tested with other pdf and still low quality)
- [ ] The page switchers should _not_ be visible for the buyers, only the sellers

![image](https://user-images.githubusercontent.com/93206363/140782504-5dc422ce-7c75-41bb-a6be-189d6a38b148.png)

**8. Issues with sound and muting**
Context:  We couldn't hear one user when he changed his mike from earplugs to computer.
- [ ] Fix: Automatically switch on the main audio channel of the device if something is unplugged.

**Comment by stephanie-cascade8** [comment]
@Camille Goussale ***@***.***> About the background color for
missing attendees, the color should probably be the color of the background
layout which is called "--background" in our builder. (We need to test
cause I can't see without testing)
