### ISSUE TITLE
Seller & Buyer Tabs in position "sticky" 

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#7083]
Put the Mat-Tab Header in position "sticky" on Market and Content landing pages.

**Comment by stephanie-cascade8** [comment]
<img width="1196" alt="Capture d’écran 2021-11-10 à 10 34 37" src="https://user-images.githubusercontent.com/66258851/141089504-faf08baa-411b-428d-a73e-7bfaa1680b9b.png"

https://user-images.githubusercontent.com/66258851/141089519-954cb3a5-da12-4255-a9dd-20d1d7532679.mov

>

Replace background color #f4f4f4 by the builder variable --background.

**Comment by Jackseed** [comment]
@stephanie-cascade8 can we give this issue to devs?

**Comment by stephanie-cascade8** [comment]
> @stephanie-cascade8 can we give this issue to devs?

Yes, there is nothing more to do on my side. Can you transfer the exact same css in the screenshot and the right background color as I commented above ? Thanks
