### ISSUE TITLE
move <bf-footer></bf-footer> outside of main in layouts

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7087]
In folder `libs/ui/src/lib/layout` move  `<bf-footer></bf-footer>` outside of `<main>` in layouts.

created from https://github.com/blockframes/blockframes/pull/6915#discussion_r743777100

**Comment by RemcoSimonides** [comment]
Moving `bf-footer` outside of `main` will cause the footer to be outside of the scroll and always visible. Leaving less space for the main content. We don't want that.
