### ISSUE TITLE
JW Player - Error code 224003 - Video still being encoded?

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7097]
When uploading a new video, if user clicks on play to preview the video just a bit after uploading the error 224003 shows up.
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/9481c73f-d5f5-40ee-be6f-7acabb304ed6)

It looks to me that it's related to encoding since if we wait a few more minutes the video works fine. 

I got 2 questions here:
- do we have a way to monitor upload & encoding status inside JW Player?
- is 224003 only related to encoding? if so, could we change the message to give a better feedback to users?

cc @pldespaigne

**Comment by pldespaigne** [comment]
> - is 224003 only related to encoding? if so, could we change the message to give a better feedback to users?

JWP docs says that this is caused by:
```
Failed to play the associated resource because it is not supported by this browser. Equivalent to the HTML5 MEDIA_ERR_SRC_NOT_SUPPORTED mediaError.
```
But if this error only appear just after uploading and 5min after everything works fine, then it's probably the encoding 🤷‍♂️

**Comment by pldespaigne** [comment]
> - do we have a way to monitor upload & encoding status inside JW Player?

No

**Comment by RemcoSimonides** [comment]
You can fetch and get the status of the upload
https://developer.jwplayer.com/jwplayer/docs/stream-fetch-upload-via-url

**Comment by pldespaigne** [comment]
This will force us to actively ping jwp api every x, to monitor the status of an upload.
This is a super-complicated and costly (because we need a cron job or something) solution just for a minor benefit.
Usually encoding takes only some minutes

**Comment by RemcoSimonides** [comment]
We could maybe check if there is an error in the player, and then ping jwp api
or
Create a webhook and sync the status in our db too
https://developer.jwplayer.com/jwplayer/reference/post_v2-webhooks

**Comment by Jackseed** [comment]
Otherwise quick fix could be to replace that error message with something like:
"Encoding your video, it may take a few minutes." + a spinner 

I never ran into that error message except while encoding so I think it's enough even if it means that we may show this message while it's something else

**Comment by Jackseed** [comment]
Not a priority > closing
