### ISSUE TITLE
Connect the main app with other apps so they can all be built & served through main.

### ISSUE THREAD

**Issue by lsenta** [blockframes/blockframes#711]
For ticket:
https://app.zenhub.com/workspaces/blockframes-5c6a8ada8de1b31d5443abd7/issues/blockframes/blockframes/569

We started working on this in: https://github.com/blockframes/blockframes/pull/663

We simplified it for now with: https://github.com/blockframes/blockframes/pull/709

**Comment by Jackseed** [comment]
@GrandSchtroumpf could you have a look on this ? we need some new blood

**Comment by lsenta** [comment]
@GrandSchtroumpf can we close this?
