### ISSUE TITLE
Review Archipel Market

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7114]
## Environment 
- OS: MacOS BigSur, 11.6
- Browser: Safari 15.0 (16612.1.29.41.4, 16612)

#DARK THEME
- [x] Dark Theme looks very different in Safari 

_This is Safari_ 
<img width="1403" alt="Снимок экрана 2021-11-12 в 16 42 43" src="https://user-images.githubusercontent.com/55499036/141493897-4ea35b99-9f26-48d1-962c-279cb2a9dbbe.png">
_This is Chrome_
<img width="1315" alt="Снимок экрана 2021-11-12 в 16 42 55" src="https://user-images.githubusercontent.com/55499036/141493869-63bfbcf5-cc86-475b-8c53-271f38ede5c8.png">

## Archipel Market / Marketplace
**Landing Page**
- [x] The placeholder in in the Newsletter subscription should be center-aligned 
<img width="706" alt="Снимок экрана 2021-11-12 в 16 10 51" src="https://user-images.githubusercontent.com/55499036/141489176-fcfe578d-4635-4e14-91dd-b8c0ddb44aa4.png">

**Homepage**
- [x] If no screenings ongoing and / or nothing is chosen in CMS, then do not show the new slider section **(important)**
<img width="1421" alt="Снимок экрана 2021-11-12 в 16 13 33" src="https://user-images.githubusercontent.com/55499036/141489620-3667e507-016e-464a-b63e-1a7a1e3dac65.png">

- [ ] when clicking on "see all" in the animation section, the "animation" genre should be chosen (important) 
![see all](https://user-images.githubusercontent.com/55499036/141490229-48bcdcd2-fb63-42fd-866e-661d631529cf.gif)

- [x] to see with @stephanie-cascade8 but maybe need to add some color to make the chair texture a bit less visible
<img width="1417" alt="Снимок экрана 2021-11-12 в 17 03 54" src="https://user-images.githubusercontent.com/55499036/141497275-4d0d9b39-fad6-4d91-a249-539cdb63b449.png">

- [x] "see all" in this new slider space should lead to Screening List page (logic is - see all ongoing screenings/slate presentations)

**Film Page**
- [x] In Hero section, the [ Org name ] should lead to the Org Page (CTA is ok, it should open the mail)
<img width="1423" alt="Снимок экрана 2021-11-12 в 16 21 00" src="https://user-images.githubusercontent.com/55499036/141490880-ac62bcee-1b27-422d-bc3c-90ea0f5c9241.png">

**Invitation Page**
- [x] Add tooltip to "More details" button
- [x] Time of apparition of tooltip of a tooltip for "accept invitation" should be shorter.
![invitations](https://user-images.githubusercontent.com/55499036/141492386-a510da43-bbf5-47d4-92c4-6b1b4b6b1c6b.gif)

## Archipel Market / Dashboard
**My Dashboard**
- [x] Time of loading of My Marketplace activity took about 16sec, should be reduced 

**Film Page**
- [x] Put the "Edit" action on the first place
<img width="1148" alt="Снимок экрана 2021-11-12 в 16 48 23" src="https://user-images.githubusercontent.com/55499036/141494762-3f653e04-dee0-4e52-98c3-0d7ad1058d7b.png">

 **Screening creation page**
- [x] The tooltips are a way to far from the text 
<img width="922" alt="Снимок экрана 2021-11-12 в 16 49 46" src="https://user-images.githubusercontent.com/55499036/141495271-b364f00b-f7d2-41ae-ba80-43361f4deeff.png">

- [x] The tabs should stay on the same level and avoid scrolls as they do on the film page **(important)**
![screenings](https://user-images.githubusercontent.com/55499036/141495721-8f41b115-fdf6-41cd-a833-0d8d9d44b836.gif)

- [x] In the Leaving page Modal Put the primary CTA before secondary one 
<img width="1246" alt="Снимок экрана 2021-11-12 в 16 57 26" src="https://user-images.githubusercontent.com/55499036/141496407-13632442-2336-4e82-aa4e-f1218d1ca6b9.png">

**Comment by 2amarkina** [comment]
### Event creation form

**Invitations**
- [ ] Need more space between progress bar and surface below 
![Снимок экрана 2021-11-15 в 08.58.33.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/d2425f0c-2b13-4651-a09c-e6590fe565cd)

**Meetings**
- [ ] Also problem with spacing here, need more space between "add files" and selected files
![Снимок экрана 2021-11-15 в 08.57.07.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/bcb6d32d-298e-4935-bb5a-9800ce4c00ab)

**During the meeting**
- [ ] Seller's camera on Safari was turned on, then a Buyer joined the meeting (via Mozilla 94.0.1) and at this moment Seller's camera turned off. Then clicking on camera icon helped. But still important to know why camera turned off. 

P.S. at the same time camera on Buyer's side worked well (Buyer could see Seller on Mozilla, but Seller could not see himself on Safari). 
![meeting camera.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4b2604a2-359b-46c3-acd5-cd701019a943)

- [ ] Buyer (Mozilla) still can see and manipulate the pages while presentation, that should not be the case
![Снимок экрана 2021-11-15 в 09.13.54.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1e9896a0-8ba5-4935-b46e-667925cd914c)

- [ ] On the Seller's side it took a lot of time to turn the pages. It should be synchronized. 
![meeting pages.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/bb5a40de-f3b9-4d29-bf8b-e59ec5c542c4)

- [ ] Full screen mode didn't work correctly 
![Снимок экрана 2021-11-15 в 09.14.55.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/d17b256d-7fdd-459e-86aa-bbca54afe9a3)

**Comment by 2amarkina** [comment]
**Events without connection**

- [ ] Need to have a pointer cursor while hovering Organizer (same as for Guests)
![cursor.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/dd3a6386-7fd5-43f6-91d4-496d2665aef2)

- [ ] when user connects with an existing account, could we lead him directly to the event page without passing through the homepage

**Comment by 2amarkina** [comment]
### Landing page

- [ ] Misprint for email in demo section. Should be aDdress. 
![Снимок экрана 2021-11-15 в 16.23.17.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/59e461de-f15a-4823-b311-53b06b49f82f)

**Comment by RemcoSimonides** [comment]
Sorry Ana, I'm seeing your review issues too late :(

> [ ] Dark Theme looks very different in Safari
You're showing two different apps too. We changed the theme of Archipel Market to the Screendaily theme.

**Comment by 2amarkina** [comment]
> Sorry Ana, I'm seeing your review issues too late :(
> 
> > [ ] Dark Theme looks very different in Safari
> > You're showing two different apps too. We changed the theme of Archipel Market to the Screendaily theme.

No pb, I've just checked, it seems to be ok on chrome and safari now!

**Comment by RemcoSimonides** [comment]
> * Add tooltip to "More details" button

What should the tooltip say?

**Comment by 2amarkina** [comment]
> > * Add tooltip to "More details" button
> 
> What should the tooltip say?

It should say "More details"

**Comment by RemcoSimonides** [comment]
Ok. Moved the items to dev issues :) Merci for the review. Closing this one
