### ISSUE TITLE
Sorting animation in tables 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7117]
_Not urgent_

While clicking on "sorting" icon in tables, there is a moment when a circle transforms into a square inside of staying circle 

![sorting animation.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/06c64a23-f842-4a1b-be8c-c70c75c33945)

**Comment by cams-goussale** [comment]
Sounds a bit too deep hehe.. closing this one :)
