### ISSUE TITLE
Review Archipel Content: Tables & Notifications Deal Nego

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7119]
## Environment 
- OS: MacOS BigSur, 11.6
- Browser: Safari 15.0 (16612.1.29.41.4, 16612)

### Dashboard

**My Sales**
- [x] Add sorting to the columns (all of them)

**My Avails**
- [x] Add sorting to all columns instead of Titles 

### **Notifications**
**If Buyer creates an offer, enters the price and sends it, then** 
_Seller_ receives the following: 
- [ ] [ Buyer’s Name ] offers [ $60 000 ] for [ Title’s Name ]. If possible, then title's name should be clickable. (Action: leads to the Contract Page). 

_Buyer_ receives the following: 
- [ ] Your offer [ Offer Reference ] was successfully sent. It includes XXXX titles, for a total price of XXXX. (Action: leads to the Offer Page). 

**If price field is empty, then** 
_Seller_ receives the following: 
- [ ]  [ Buyer’s Name ] requests Asking Price for [ Title’s Name ]. If possible, then title's name should be clickable. More details button should lead to the Contract Page. 

_Buyer_ receives the following: 
- [ ] Your offer [ Offer Reference ] was successfully sent. It includes XXXX titles, for a total price of XXXX. (Action: leads to the Offer Page). 

**If seller accepts, then:**
_Seller_ receives the following: 
- [ ] [ Buyer’s Name ] will be notified of your approval of their offer for [ Title’s Name ]. (Action: leads to the Contract Page)

_Buyer_ receives the following: 
- [ ] Your offer for [ Title’s Name ] was accepted. (Action: leads to the Contract Page)

**If seller declines, then:** 
_Seller_ receives the following: 
- [ ] [ Buyer’s Name ] will be notified that you declined their offer for [ Title’s Name ]. (Action: leads to the Contract Page)

_Buyer_ receives the following: 
- [ ] Your offer for [ Title’s Name ] was declined. (Action: leads to the Contract Page)

[See the whole list of notifications here and check out the mails to send](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=0)

**Comment by frenchyrules** [comment]
OS: MacOS BigSur, 11.2.3
Browser (& version if possible): Safari 14.0.3 (16610.4.3.1.7)

Archipel Content - dark mode

- [ ] Tooltip typo when hovering above calendar icon (My avails)

![image](https://user-images.githubusercontent.com/85220905/141756483-9fe4284c-9e8b-43bb-acdf-3f45db5602d2.png)

**Comment by cams-goussale** [comment]
@yspringfield on this [list of Notifications](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=0) and emails, it looks like many of them are not implemented. Letus know if we are not able to include a lot of details in the notification itself. We need to send something even if it's simplified.

I have identified these lines missing:
- Buyer accepts the offer
- Seller accepts the offer
- Buyer sends a counter-offer
- Seller sends a counter-offer

**Comment by cams-goussale** [comment]
- [ ] In the summary table in the email, when the last piece of data is shown, we shouldn't add the separator " , "

![image](https://user-images.githubusercontent.com/93206363/147768852-8b98b11d-69b0-4846-ae9f-6f7c74d3b941.png)

**Comment by cams-goussale** [comment]
(WIP)

Category | Seller Notif | Seller Email | Buyer Notif | Buyer Email
--- | --- | --- | --- | ---
Buyer sends an offer, with price | ✔️ | ❌ | ✔️ | ✔️
Buyer sends an offer, without price |  |  |  | 
Seller sends a counter-offer |  |  |  | 
Buyer sends a counter-offer |  |  |  | 
Seller accepts the offer |  |  |  | 
Seller declines the offer | ❌ |  | ✔️ | 
Buyer accepts the offer |  |  |  | 
Buyer declines the offer |  |  |  |

**Comment by cams-goussale** [comment]
- [ ] If all contracts are declined, Buyer receives an email which I can't find in the list and links to one contract of the offer, instead of the entire offer.

![image](https://user-images.githubusercontent.com/93206363/147770267-204d6619-debc-4bad-8b91-602ea2ff856c.png)

**Comment by cams-goussale** [comment]
**Review about wording issues**

- [ ] There is a typo on [this email](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=657134932&range=D3), on the first sentence. Currently there is both exclamation point and normal point at the end `the concerned seller(s)!.` Let's keep just the exclamation point
- [ ] In the same email, we are also missing the 2 dots on the second line `Here are some useful details` should be `Here are some useful details:`
- [ ] In the table summary, data is separated by comma (France, Belgium, Germany). But the last piece of data should not have the comma. Example: currently we have `France, Belgium, Germany,` and should be `France, Belgium, Germany`

**Comment by cams-goussale** [comment]
- [ ] Remove the capital "O" in `offer` for this notification
![image](https://user-images.githubusercontent.com/93206363/149738700-bbb5671a-204c-4ca8-a8eb-1e843a73348c.png)

**Comment by cams-goussale** [comment]
- [ ] Change `will` for `would` in t[his email](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=657134932&range=B6)
- [ ] Add capital letters to `Asking Price`

![image](https://user-images.githubusercontent.com/93206363/149739329-3f230c25-37cb-46a4-b9a6-15fb01a38783.png)

**Comment by cams-goussale** [comment]
- [ ] [Reception of a counter-contract](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=657134932&range=A9:D10) doesn't have any email or notif triggered.

**Comment by cams-goussale** [comment]
- [ ] [Declined contract](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=657134932&range=A15:D18) doesn't trigger and notification or email, neither for the user making the action, neither for the one receiving it.

**Comment by cams-goussale** [comment]
- [ ] If Buyer is the one accepting the Contract, he [does not receive any notification nor email](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=657134932&range=C12:D12).

**Comment by cams-goussale** [comment]
- [ ] Once all Contracts from the Offer are finished, the email received by Buyer has a buggy button and there is [no Notification](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=657134932&range=C20) sent to the Buyer.
- [ ] The Seller doesn't receive anything at all, though [there should be an email and a notification](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=657134932&range=A20:B20).
 

https://user-images.githubusercontent.com/93206363/149743517-aa9e41a6-addd-4989-bd7c-bf7ce8edab71.mp4

**Comment by cams-goussale** [comment]
- [ ] Let's add a dash here to `counter-offer`

![image](https://user-images.githubusercontent.com/93206363/149753815-1c480dbb-1e3b-40ee-b922-3a035aa370bf.png)

**Comment by cams-goussale** [comment]
- [ ] Let's remove the `for` [here](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=657134932&range=D3)

![image](https://user-images.githubusercontent.com/93206363/149755680-2acad67b-9ba7-4662-a8bb-982331fde8ea.png)

**Comment by cams-goussale** [comment]
- [ ] Let's remove the capital letter here on `will`

![image](https://user-images.githubusercontent.com/93206363/149760848-c740138d-4d8a-4596-a85e-981f385c3503.png)

**Comment by cams-goussale** [comment]
- [ ] Let's remove the capital "O" in [this email subject](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=657134932&range=A17:D18)


![image](https://user-images.githubusercontent.com/93206363/149762212-e1b48692-4ea4-4bf6-8502-df7114a91c90.png)

**Comment by cams-goussale** [comment]
- [ ] We need to change the subject of [this email](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=657134932&range=D22) for `Your offer is declined`

![image](https://user-images.githubusercontent.com/93206363/149763913-5faaa0d3-5fd5-44f4-9d50-cdcb65e86c81.png)
