### ISSUE TITLE
Review Events

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#7121]
## Your environement
_Please describe your environment_ 
- OS: Mac OS Big Sur
- Browser (& version if possible): Safari v 14.1.2

## Review item
_Copy & fill this section for each item._
### Localization
- App name: Market
- Page: Meeting 
- User used (if anonymized): Buyer

### Context
After joining a meeting of 9 people

### Fix
is it possible to have a max-width and min-width on the whole section that contains attendee's self videos (to decide with dev on live tests if possible).
We need to harmonize the grid there (there is too much space between people)
![Capture d’écran 2021-11-10 à 12.05.02.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/8e4d2990-609c-48d9-88f6-066307592b84)

**Comment by stephanie-cascade8** [comment]
## Review item
_Copy & fill this section for each item._
### Localization
- App name: Market
- Page: Meeting 
- User used (if anonymized): Buyer

### Context
After joining a meeting of 9 people

### Fix
is it possible to have a max-width and min-width on the whole section that contains attendee's self videos (to decide with dev on live tests if possible).
We need to harmonize the grid there (there is too much space between people)
![Capture d’écran 2021-11-10 à 12.05.02.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/8e4d2990-609c-48d9-88f6-066307592b84)

**Comment by RemcoSimonides** [comment]
All issues have been passed to devs so I'm closing this one
