### ISSUE TITLE
Marie's Business Review for 17/11 release

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#7122]
### BANNER

- [ ] Change text to: "One tool for your year-round B2B promotions & acquisitions"

### THEY'RE USING IT

- [ ] Change text to: Over 1400 buyers are already using Archipel, from companies like:
- [ ] Remove 1 or 2 logos so it fits on 1 line instead of 2 (on a standard computer screen like mike - Macbook 13")

### HOW IT WORKS / Sales agents / User Benefits

- [ ] Correct text to: "Simplify your buyers' lives"

### WHAT OUR CLIENTS SAY

- [ ] Correct name with capital letter: "Nate Bolotin"

### WANT TO LEARN MORE? Hero

- [ ] Correct Email Label and Placeholder to "Email Address" (not Email Adress or E-mail address)
- [ ] Correct Phone Placeholder to: "Phone Number" (with capital letter)
- [ ] Change checkbox text to: "Subscribe to our newsletter"

### FOOTER

- [ ] Add hyperlinks to the partners' logos:
- BPI : https://www.bpifrance.fr/
- Creative Europe MEDIA: https://ec.europa.eu/culture/funding-creative-europe/creative-europe-media-strand
- IFCIC: http://www.ifcic.fr/
- CNC: https://www.cnc.fr/

**Comment by maltmayer** [comment]
## LOGIN PAGE

- [ ] Correct Email Placeholder to "Email Address"

**Comment by maltmayer** [comment]
## MARKETPLACE HOMEPAGE
## Event Slider
- CTA should not send request here. It should be "Check Out Event" and lead to the event page. Otherwise it's confusing. When I click "Access Event" for public events, I expect to go on the event page, but instead, the status changes to "Request Pending" and then leads me to the screening room... It's too abrupt and super confusing, not what the user would expect. I would generalize the behavior and just lead everyone to the event page where they can then request access or access directly when public.

**Comment by maltmayer** [comment]
## DASHBOARD

### EVENT FORM / SCREENING - Privacy Settings

- [ ] Add an "i" tooltip icon otherwise the tooltip text is way too low to understand which line it refers to. 
![image](https://user-images.githubusercontent.com/55785823/141771074-f2d1eeb3-25c1-483e-a79c-22c2089ed43f.png)
![image](https://user-images.githubusercontent.com/55785823/141771092-da14a7c1-d3d4-40c4-9ec0-1bd74d7d9819.png)

**Comment by RemcoSimonides** [comment]
Hey, I've forwarded the issues you mentioned to the devs. Let me know if you find more or edit above text ;) merci for the review!

**Comment by maltmayer** [comment]
> Hey, I've forwarded the issues you mentioned to the devs. Let me know if you find more or edit above text ;) merci for the review!

Sorry but I spotted new feedbacks I'll keep posting here

**Comment by maltmayer** [comment]
## DASHBOARD 
### MOVIE FORM
- Countries and lists in general are not well referenced (example here: UK or USA. The point of including it in the title of the territory was to make the work appear in the search. Here, it just searches for words beginning with the letters typed, not including the letters typed)
![image](https://user-images.githubusercontent.com/55785823/142038621-62c29c6b-1e18-4af5-b4af-edd0b3ca4753.png)
![image](https://user-images.githubusercontent.com/55785823/142038596-d0975926-61c8-4cac-9452-d51f1f3f4c7d.png)

- When I don't change the metric for the box office (keeping the standard info: USD), it shows up as if I didn't select anything instead of showing "USD":
![image](https://user-images.githubusercontent.com/55785823/142039391-8d263392-6928-418c-80c1-9467cdd035f6.png)

## MARKETPLACE
### MOVIE VIEW
- The movie page should be improved. A lot of the elements displayed make no sense and take to much space. Here for example, the all have the same title, why separate them?
![image](https://user-images.githubusercontent.com/55785823/142038820-c7e9a880-5bf1-426e-8137-92e7264bcde0.png)

- Also some elements are not consistent (some put the country as a title, some as a text)
![image](https://user-images.githubusercontent.com/55785823/142038903-5541946b-46b2-494a-aa9d-d5ab06ee27d5.png)
![image](https://user-images.githubusercontent.com/55785823/142038947-e32d4fee-ce99-4ab3-8dc3-78269567d606.png)

- Release information are not pretty. Instead of unformatted "Theatrical 5/20/21" it could be improved with something simple like: 5/20/2021 (Theatrical)"
![image](https://user-images.githubusercontent.com/55785823/142038985-4589b2b8-941e-4cb7-9538-0adbb7b90fa2.png)

- video files should be improved when possible. this is not pretty. I think we can do better.
![image](https://user-images.githubusercontent.com/55785823/142039526-765575bf-5718-4eec-8456-fcdb4d3aea14.png)

**Comment by maltmayer** [comment]
## MEETINGS 
### SESSION PAGE

- [ ] Remove thin line around the camera images
![image](https://user-images.githubusercontent.com/55785823/142210163-38dc8d6e-27aa-4912-92a4-c99ef3488b24.png)
![image](https://user-images.githubusercontent.com/55785823/142210139-de8b1498-7ca9-4c45-a94b-76e8f5611058.png)

- [ ] As a buyer, I can see (and manage!) the controls here:
![image](https://user-images.githubusercontent.com/55785823/142210690-6f4e79e8-b997-44df-8631-b7bc6b36c91c.png)

- [ ] Once everyone is gone from the meeting, I can stay here indefinitely (more than 10 min here)
![image](https://user-images.githubusercontent.com/55785823/142210576-99e01467-2543-4688-9eeb-6e17e4b7a0c8.png)

**Comment by maltmayer** [comment]
## MARKETPLACE

- [ ] I've spotted that the link in the logo varies if I arrived on Archipel with a direct link to a specific page. Here, it doesn't lead me back to the homepage as it should

https://user-images.githubusercontent.com/55785823/142211758-a413685a-381f-4cc5-8207-d4a6358a99db.mov

**Comment by phpgeekfr** [comment]
@maltmayer since it is now to late to performs the changes you requested, they have been moved to #7160 #7134 and #7161

**Comment by RemcoSimonides** [comment]
and #7165 & #7166 for movie form issues
