### ISSUE TITLE
Review Content / Dashboard-My Sales

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#7125]
## Your environement
_Please describe your environment_ 
- OS: Mac Os Big Sur 11.5.2
- Browser (& version if possible): Safari 14.1.2

**Comment by stephanie-cascade8** [comment]
- [ ] 24px space between buttons and text
- [ ] 4px before mat-button
<img width="1346" alt="Capture d’écran 2021-11-15 à 17 31 59" src="https://user-images.githubusercontent.com/66258851/141818744-5d1e3c3e-ce8d-45d2-ae80-077ec94cee08.png">

- My Avails

-[ ] Reduce "exclusivity" field (if possible in any variant of this component) 

bfore
<img width="1130" alt="Capture d’écran 2021-11-15 à 17 32 55" src="https://user-images.githubusercontent.com/66258851/141819053-7a5e7b0e-24ad-4f20-a24d-c6b28262fcf1.png">

after
<img width="878" alt="Capture d’écran 2021-11-15 à 17 34 04" src="https://user-images.githubusercontent.com/66258851/141819066-d109280b-99e9-469a-ad3b-4b7e82b2afff.png">

- My Avails

- [ ] 24px margin between filters and the 2 buttons 
- [ ] Have the  "clear filters " icon and it's circle behind come inside the surface. padding around should be 8px at least.
<img width="1410" alt="Capture d’écran 2021-11-15 à 17 44 59" src="https://user-images.githubusercontent.com/66258851/141821077-713b7ff0-12a1-4bb9-89c2-00a5d7833be3.png">

<img width="549" alt="Capture d’écran 2021-11-15 à 17 45 12" src="https://user-images.githubusercontent.com/66258851/141821098-b4d2b2dc-a1e5-42ba-9dd8-1845773a6775.png">

**Comment by RemcoSimonides** [comment]
All issues have been passed to devs so I'm closing this one. Thanks for the review!
