### ISSUE TITLE
Export event stats to Excel instead of CSV

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7135]
hello @phpgeekfr :) is it possible to include in this release some improvments of the Event Statistics Report? The idea is to have:

[movies.title.international on Archipel Market event.start - Report.xlsx](https://github.com/blockframes/blockframes/files/7538965/movies.title.international.on.Archipel.Market.event.start.-.Report.xlsx)

- [ ] 2 tabs with more details on the guests (see excel attached)
- [ ] change the _Export to CSV_ button to _Export to Excel_

![image](https://user-images.githubusercontent.com/93206363/141789779-d03421aa-7ac3-4b85-b826-2098b4270420.png)

If too late, i'll just create a dedicated issue

_Originally posted by @cams-goussale in https://github.com/blockframes/blockframes/issues/7060#issuecomment-968911001_

**Comment by phpgeekfr** [comment]
@cams-goussale so we should have, instead of ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/4eff77b5-727f-4353-be6e-dc7085c308be) two tabs with one table each or two tables in the same existing tab ?

**Comment by cams-goussale** [comment]
@phpgeekfr No, it concerns the CSV export. It's not in-app, it's the excel that needs some improvements

**Comment by phpgeekfr** [comment]
@cams-goussale styling feature (center text, add border and colors) is only available in the pro version of the library we use.

Lets have a discussion with @KevinDurand974 to check what we should do

**Comment by cams-goussale** [comment]
@phpgeekfr @KevinDurand974 I don't think we need styling. Could we have a look at what we could have with the library we use?

Regarding declined invitations, it's a good insight. Indeed, we could add it below the accepted and pending persons.

**Comment by KevinDurand974** [comment]
@cams-goussale
Here we go, the Excel file with no style (I added declined invitations)

[Film test on Archipel Market 05_09_2022 - Report (55).xlsx](https://github.com/blockframes/blockframes/files/8676266/Film.test.on.Archipel.Market.05_09_2022.-.Report.55.xlsx)

**Comment by cams-goussale** [comment]
Looks good! Can we **not** merge the cells here and just have all of them aligned left?

<img width="500" alt="image" src="https://user-images.githubusercontent.com/93206363/168050026-bfb05fa9-87d7-4d22-8b93-d613e38008eb.png">


<img width="581" alt="image" src="https://user-images.githubusercontent.com/93206363/168050070-d5ef9812-df08-466c-9d27-2b652603ecbd.png">

**Comment by KevinDurand974** [comment]
I cant change the alignment of cells, if I remove the merged cells i've this :
![image](https://user-images.githubusercontent.com/89908055/168070961-e58a1621-7910-4bb2-9294-14cd57894549.png)

**Comment by cams-goussale** [comment]
Could you remove it here too?
<img width="344" alt="image" src="https://user-images.githubusercontent.com/93206363/168071301-333abade-30ea-4fba-b1fe-99823d0a014a.png">

**Comment by KevinDurand974** [comment]
yes

**Comment by KevinDurand974** [comment]
Here the corrected version :
[Film test on Archipel Market 05_09_2022 - Report (60).xlsx](https://github.com/blockframes/blockframes/files/8679776/Film.test.on.Archipel.Market.05_09_2022.-.Report.60.xlsx)
