### ISSUE TITLE
Improvement of "Add files" widget

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7137]
Following the meeting with WTFilms and their feedbacks, some improvements can be done for the Meeting Creation. 

- [x] Highlight recently added files (to find them easily); 
- [x] Search / filter for a particular file name (also to go faster); 
- [x] Show the files in an alphabetical order.

**Comment by Jackseed** [comment]
As discussed, here we're one nice to have features. I think search/filter will be too much work there but let's check that with a dev, same as other propositions. Please ask them for a time estimation so we can evaluate if & when to do this.

**Comment by 2amarkina** [comment]
Checked all the possibilities. 

One that we could go for is 
**Show the folders names in an alphabetical order**
