### ISSUE TITLE
Meeting Creation / Management Improvements 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7138]
Following the meeting with WTFilms, the Sellers find it time-consuming to re-create the same event several times. 
- [ ] See maybe we could copy the events? 

Also, it would be more confortable to have 1 link to an event for a Seller, but different links for Buyers. 
- [ ] See if there is something we could do about it or maybe just be limited with copy event feature?

**Comment by cams-goussale** [comment]
Adding here some suggestions from Marie.

1) Meeting Invitation Link Visible for each user
In the Protected case, users can only access the event through their email, there is one unique link per user for the same event. Could it be possible to add this URL next to the participant list so the Organizer can re-send the link at last minute?

2) Should we hide the Generic event link in the case of Protected events?

3) Brainstorm to be done on how we improve the understanding of the 3 event settings (private, public, protected) for the organizer.

4) Is it possible to resend the invitation without deleting a guest?
