### ISSUE TITLE
[CATALOG] Avails Filter - State of the art

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#7139]
There are a lot of misunderstanding on "how should the avails filters work" depending on the situation.

Find all the place where there is an avails filter and specify : 
- If the filter should have default value (duration, exclusivity)
- If the filter should be optional
- What should be the behavior of the filter: `allOf` / `someOf` / ...
- Should we consider holdbacks
- Write unit test scenario to based on this behavior.

Update the patched that have been put for the release (referenced with this issue in the code).

**Comment by pldespaigne** [comment]
## Dashboard
- Avails List : `filterDashboardAvails`

  ![image](https://user-images.githubusercontent.com/5858657/144206929-61a323ac-f605-49b5-a566-10d24faa4b1b.png)

**Comment by cams-goussale** [comment]
Hello @pldespaigne @GrandSchtroumpf @Jackseed, I have updated my first comment to add
- The issue related to Test scenarios (not for this release)
- The rules we discussed and defined yesterday

Let's talk if something is not clear

**Comment by pldespaigne** [comment]
Related dev epic issue: #7356

**Comment by cams-goussale** [comment]
### Review Dashboard

**1/ Map view**

- [ ] It seems that the logic with Exclusive / Non Exclusive is reversed.
_-if sale excl and research non excl => no
-if sale non excl and research non excl => yes_

Test done with Movie [Import 1](https://docs.google.com/spreadsheets/d/1YAsKVdFt_ybheXlLJsKoXYdlma-iB1W_ilKPTuHME2w/edit#gid=1224333819&range=B16:B25)

<details><summary>Mandate parameters:</summary>
<p>

Terms | Territory | Rights | Exclusivity
--- | --- | --- | ---
01/01/2021 - 01/31/2035 | World excluding South Korea | All excluding Planes | Yes
</p>
</details>

<details><summary>Sales parameters:</summary>
<p>

Sales | Terms | Territory | Rights | Exclusivity
--- | --- | --- | --- | ---
1 | 06/01/2019 - 12/31/2030 | Argentina | Pay TV; Pay Per View; Free TV; EST; N-VOD; A-VOD; F-VOD; Video | Yes
2 | 06/01/2019 - 12/31/2030 | Germany | Pay TV; Pay Per View; Free TV; EST; N-VOD; A-VOD; F-VOD; S-VOD; Video | No
3 | 06/01/2019 - 12/31/2030 | Canada | Pay TV; Pay Per View; Free TV; EST; N-VOD; A-VOD; F-VOD; S-VOD; Video | No
</p>
</details>

<details><summary>Research parameters:</summary>
<p>

Terms | Territory | Rights | Exclusivity
--- | --- | --- | ---
12/24/2021 - 12/31/2030 | none (map) | Pay TV | No
</p>
</details>

Expected result: Germany and Canada available ; Argentina not available
Actual result: Germany and Canada sold ; Argentina available
![image](https://user-images.githubusercontent.com/93206363/147347038-5a1f4d19-44b2-4995-854c-e0c1c4757efc.png)

**Comment by cams-goussale** [comment]
### Review Dashboard

**1/ Map view**

- [ ] Terms (dates) are not taken into account when importing Sales.
_allOf AvailsResearch in Mandate_

Test done with Movie [Import 1](https://docs.google.com/spreadsheets/d/1YAsKVdFt_ybheXlLJsKoXYdlma-iB1W_ilKPTuHME2w/edit#gid=1224333819&range=B16:B25)

<details><summary>Mandate parameters (same as above):</summary>
<p>

Terms | Territory | Rights | Exclusivity
--- | --- | --- | ---
01/01/2021 - 01/31/2035 | World excluding South Korea | All excluding Planes | Yes
</p>
</details>

<details><summary>Sales parameters (same as above):</summary>
<p>

Sales | Terms | Territory | Rights | Exclusivity
--- | --- | --- | --- | ---
1 | 06/01/2019 - 12/31/2030 | Argentina | Pay TV; Pay Per View; Free TV; EST; N-VOD; A-VOD; F-VOD; Video | Yes
2 | 06/01/2019 - 12/31/2030 | Germany | Pay TV; Pay Per View; Free TV; EST; N-VOD; A-VOD; F-VOD; S-VOD; Video | No
3 | 06/01/2019 - 12/31/2030 | Canada | Pay TV; Pay Per View; Free TV; EST; N-VOD; A-VOD; F-VOD; S-VOD; Video | No
</p>
</details>

<details><summary>Research parameters:</summary>
<p>

Terms | Territory | Rights | Exclusivity
--- | --- | --- | ---
12/24/2021 - 12/24/2036 | none (map) | Pay TV | No
</p>
</details>

Expected result: Germany and Canada Not Licensed
Actual result: Germany and Canada sold
![image](https://user-images.githubusercontent.com/93206363/147348503-235a414c-42bf-4eae-8d23-80beb6aaec5f.png)

**Comment by cams-goussale** [comment]
### Review Dashboard

**1/ Map view**

- [ ] It seems some territories included in the mandate are not showing. Maybe the territories name on the Map are not the same as the ones in the Excel import template?

Test done with Movie [Import 1](https://docs.google.com/spreadsheets/d/1YAsKVdFt_ybheXlLJsKoXYdlma-iB1W_ilKPTuHME2w/edit#gid=1224333819&range=B16:B25)

<details><summary>Mandate parameters (same as above):</summary>
<p>

Terms | Territory | Rights | Exclusivity
--- | --- | --- | ---
01/01/2021 - 01/31/2035 | World excluding South Korea | All excluding Planes | Yes
</p>
</details>


<details><summary>Research parameters:</summary>
<p>

Terms | Territory | Rights | Exclusivity
--- | --- | --- | ---
12/24/2021 - 12/24/2022 | none (map) | Pay TV | No
</p>
</details>



Expected results: Switzerland, Congo, Guinea, Cote d'Ivoire, Tadjikistan, Azerbadjan available
Actual restults: these countries are missing
![image](https://user-images.githubusercontent.com/93206363/147350834-c8bbe90f-d228-4ef4-ae94-41c419986542.png)

**Comment by cams-goussale** [comment]
### Review Dashboard

**2/ Calendar view**

- [ ] Same remark as in the [first comment of map view](https://github.com/blockframes/blockframes/issues/7139#issuecomment-1000797767). It seems that the logic with Exclusive / Non Exclusive is reversed.
_-if sale excl and research non excl => no
-if sale non excl and research non excl => yes_

Test done with Movie [Import 1](https://docs.google.com/spreadsheets/d/1YAsKVdFt_ybheXlLJsKoXYdlma-iB1W_ilKPTuHME2w/edit#gid=1224333819&range=B16:B25).

<details><summary>Mandate parameters (same as above):</summary>
<p>

Terms | Territory | Rights | Exclusivity
--- | --- | --- | ---
01/01/2021 - 01/31/2035 | World excluding South Korea | All excluding Planes | Yes
</p>
</details>

<details><summary>Sales parameters (same as above):</summary>
<p>

Sales | Terms | Territory | Rights | Exclusivity
--- | --- | --- | --- | ---
1 | 06/01/2019 - 12/31/2030 | Argentina | Pay TV; Pay Per View; Free TV; EST; N-VOD; A-VOD; F-VOD; Video | Yes
2 | 06/01/2019 - 12/31/2030 | Germany | Pay TV; Pay Per View; Free TV; EST; N-VOD; A-VOD; F-VOD; S-VOD; Video | No
3 | 06/01/2019 - 12/31/2030 | Canada | Pay TV; Pay Per View; Free TV; EST; N-VOD; A-VOD; F-VOD; S-VOD; Video | No
</p>
</details>

<details><summary>Research parameters:</summary>
<p>

Terms | Territory | Rights | Exclusivity
--- | --- | --- | ---
None (calendar) | Germany | Pay TV | No
</p>
</details>

Expected result: Germany available
Actual result: Germany not available

https://user-images.githubusercontent.com/93206363/147352230-130d99a6-cba7-4eb5-9ca9-3b77c1787056.mp4

**Comment by cams-goussale** [comment]
### Review Dashboard

**1/ Map view**

- [ ] Snackbar error showed after filtering some specific parameters
![image](https://user-images.githubusercontent.com/93206363/147357246-921abb98-d5e9-4895-ba21-30d83c81c3ed.png)

**Comment by cams-goussale** [comment]
### Review Dashboard

**3/ List view**

- [ ] Territories selector filter does not allow white spaces in Dashboard List Avails view.

![image](https://user-images.githubusercontent.com/93206363/147357605-f9bb8dc4-8335-4762-b9a7-a979ecc86140.png)

**Comment by cams-goussale** [comment]
### Review Dashboard

**3/ List view**

- [ ] According to [rules](https://docs.google.com/spreadsheets/d/1YAsKVdFt_ybheXlLJsKoXYdlma-iB1W_ilKPTuHME2w/edit#gid=177209628&range=A14), the list view should _withdraw the tiltes which don't match the search criteria_. It seems to withdraw everything

<details><summary>Research parameters on the whole List view:</summary>
<p>

Terms | Territory | Rights | Exclusivity
--- | --- | --- | ---
01/01/2022 - 06/30/2023 | South Korea | Free TV | No
</p>
</details>


Criteria of Movie [Import 2](https://docs.google.com/spreadsheets/d/1YAsKVdFt_ybheXlLJsKoXYdlma-iB1W_ilKPTuHME2w/edit#gid=1224333819&range=B26:B35)


<details><summary>Mandate parameters:</summary>
<p>

Terms | Territory | Rights | Exclusivity
--- | --- | --- | ---
01/01/2021 - 01/31/2040 | World | Pay TV; Pay Per View; Free TV; EST; N-VOD; F-VOD; S-VOD; Video; Hotels; Planes | Yes
</p>
</details>

<details><summary>Sales parameters:</summary>
<p>

Sales | Terms | Territory | Rights | Exclusivity
--- | --- | --- | --- | ---
1 | 06/01/2022 - 01/01/2023 | Afghanistan | Free TV | Yes
2 | 06/01/2022 - 01/01/2029 | World | Planes | Yes
3 | 06/01/2022 - 01/01/2035 | Germany | Free TV | No
</p>
</details>


Criteria of Movie [Import 3](https://docs.google.com/spreadsheets/d/1YAsKVdFt_ybheXlLJsKoXYdlma-iB1W_ilKPTuHME2w/edit#gid=1224333819&range=B36:B45)

<details><summary>Mandate parameters:</summary>
<p>

Terms | Territory | Rights | Exclusivity
--- | --- | --- | ---
01/01/2021 - 01/31/2040 | World excluding France | Pay TV; Pay Per View; Free TV; EST; N-VOD; A-VOD; F-VOD; S-VOD; Video; Hotels; Planes | Yes
</p>
</details>

<details><summary>Sales parameters:</summary>
<p>

Sales | Terms | Territory | Rights | Exclusivity
--- | --- | --- | --- | ---
1 | 06/01/2021 - 01/01/2023 | Germany | Free TV | Yes
2 | 06/01/2022 - 01/01/2023 | Argentina | S-VOD | No
</p>
</details>


Expected result: Movie 2 and Movie 3 to show
Actual result: No result

https://user-images.githubusercontent.com/93206363/147358514-b918fafa-bc1a-4dc5-9208-77f82b867475.mp4

**Comment by cams-goussale** [comment]
This one can be discussed with @Jackseed, even though it's not blocking and might be over complexifying.

- [ ] Should we consider a priority of check between Mandate and Sale?
Refering to the [comment above](https://github.com/blockframes/blockframes/issues/7139#issuecomment-1000800443) 👆, the title has a mandate until 2035 and a sale until 2030. If Research parameter goes from today until 2036, it includes the sale but goes beyond the mandate. Should we show the territory as Sold or Not available?

In terms of rule, the question is: are we checking first `allOf AvailsResearch in Mandate` and second `nonOf AvailsResearch in Sale` or first `nonOf AvailsResearch in Sale` and second `allOf AvailsResearch in Mandate`

![image](https://user-images.githubusercontent.com/93206363/147681513-ee60aee4-73a7-4f30-80d7-a501e3ecd1c0.png)

**Comment by cams-goussale** [comment]
- [ ] [This comment](https://github.com/blockframes/blockframes/issues/7139#issuecomment-1000855583) is still not working : Movie 2 and Movie 3 are not showing when filtering by the criterias.


A similar example below:

<details><summary>Research parameters on the whole List view:</summary>
<p>

Terms | Territory | Rights | Exclusivity
--- | --- | --- | ---
01/01/2022 - 06/30/2036 | Afghanistan | Free TV | No
</p>
</details>


Criteria of Movie [Import 3](https://docs.google.com/spreadsheets/d/1YAsKVdFt_ybheXlLJsKoXYdlma-iB1W_ilKPTuHME2w/edit#gid=1224333819&range=B36:B45)


<details><summary>Mandate parameters:</summary>
<p>

Terms | Territory | Rights | Exclusivity
--- | --- | --- | ---
01/01/2021 - 01/31/2040 | World excluding France | Pay TV; Pay Per View; Free TV; EST; N-VOD; A-VOD; F-VOD; S-VOD; Video; Hotels; Planes | Yes
</p>
</details>

<details><summary>Sales parameters:</summary>
<p>

Sales | Terms | Territory | Rights | Exclusivity
--- | --- | --- | --- | ---
1 | 06/01/2021 - 01/01/2023 | Germany | Free TV | Yes
2 | 06/01/2021 - 01/01/2023 | Argentina | S-VOD | No
</p>
</details>

Expected result: Movie 3 to show
Actual result: Movie 3 not showing


https://user-images.githubusercontent.com/93206363/147683681-1b84be24-f769-4338-b7b8-c3fa0b355d35.mp4

**Comment by pldespaigne** [comment]
Are you sure mandates & sales corresponding to Movie 2 & 3 are `accepted` ?
If the status is still `pending` they are not taken into account.

**Comment by cams-goussale** [comment]
You're right, I forgot about this. Will update my review

**Comment by cams-goussale** [comment]
- [ ] When clicking on any value in a filter field, it jumps to the previous value. Can we remove that?

https://user-images.githubusercontent.com/93206363/147737051-07c34a8c-194e-45bc-b01d-0de81246f8d2.mp4

**Comment by cams-goussale** [comment]
- [ ] When selecting several territories in the filter, the 1st country selected is never saved (I tried many examples).

https://user-images.githubusercontent.com/93206363/147737408-09cb857f-edd2-48d7-9fc3-169a7b946586.mp4

**Comment by RemcoSimonides** [comment]
Hee @cams-goussale, I see three open tick boxes in this issue. Do you know if they are fixed in the meantime perhaps? If not, could you create new issues for them and close this one? merci

**Comment by cams-goussale** [comment]
Closing this issue now
