### ISSUE TITLE
Recurrent random Error on some fields of the movie form

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7150]
Recurrent random Error on some fields of the movie form

- [ ] Red wording "Error" on the summary of the movie form. It tends to change when you open or close a movie, it is random.

![image](https://user-images.githubusercontent.com/93206363/141182868-95b0ffb9-04ae-4a8f-974f-164489d9cecf.png)
![image](https://user-images.githubusercontent.com/93206363/141182979-9dede13a-1f79-4480-822b-ad0175e6b8c3.png)

1) this field should not be blocking since it's not a mandatory field
2) if you scroll down the page, next to this field, it says "Error". We usually have either "Missing" for optional missing fields, or "Mandatory info missing" for mandatory missing fields, but i don't think "Error" is an accepted wording

@cams-goussale how do I create a movie to trigger this error? I've tried to create a movie while only filling in the mandatory fields, but Social Responsibility Goals doesn't show an error then

**Comment by cams-goussale** [comment]
@RemcoSimonides i think i've identified the pattern. It's with Excel import that I get this error.

You can see an example:
-userId rzf1Zw3fxTXYp56UlJj01pSbaCG3
-movieId TifZ3y8uE2CQZIdKY76N

[v2_TEST_101121_import titles test sept 21.xlsx](https://github.com/blockframes/blockframes/files/7552846/v2_TEST_101121_import.titles.test.sept.21.xlsx)
![Title with ERROR_AC_import_1711](https://user-images.githubusercontent.com/93206363/142162165-b5c52d5a-5a84-4360-a94b-a02be8e8975c.gif)

**Comment by RemcoSimonides** [comment]
duplicate of #7023
