### ISSUE TITLE
Remove all from available versions on Movie

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7151]
Some movies (e.g. oHdU7uVJvXjpkd2THvuV) have 'all' in available versions. This blocks adding languages in the movie form so these empty all objects should be removed.

![image.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/7c2ce5f4-b740-4d7e-a56c-e1f22085b1ad)

**Comment by cams-goussale** [comment]
@RemcoSimonides if you can extract the list of movies concerned, i'll clean this manually in db

**Comment by RemcoSimonides** [comment]
Thanks but no need to do it manually ;) this can be done automatically with a migration script
