### ISSUE TITLE
Illustrations issues for events

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7158]
### SCREENING SESSION 
- [ ] Problem with the illustration (if you look close, some seats go over people's bodies)
![image](https://user-images.githubusercontent.com/55785823/141773911-00c9174d-4afc-4048-bc6c-6ad641c4e949.png)

_Originally posted by @RemcoSimonides in https://github.com/blockframes/blockframes/issues/7060#issuecomment-969038506_

### MEETING  SESSION 
- [ ]  Some people have no legs, so they can't walk :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/0e920909-4ef8-4125-a557-79dc6f422d09)

_Originally posted by @phpgeekfr in https://github.com/blockframes/blockframes/issues/7061#issuecomment-970398155_

**Comment by Jackseed** [comment]
Illustrations are working and we never had complaints so let's stick with what we got
