### ISSUE TITLE
Meeting room issues

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7161]
- [ ] when user is already muted , the sound icon should be muted for every participants
- [ ] Safari:  camera turns black when turning of the mic
- [ ] Safari:  turning off camera breaks the page
https://user-images.githubusercontent.com/14964443/141306119-2fa78a12-7ee4-40e3-9481-ee59f3c3bc97.mp4

Note: not sure but it looks related to #5219 cc @RemcoSimonides
Note from Remco: It was indeed caused in the same PR. But main reason was the fix for issue #6639

- [ ] Safari:  now when going full screen on video shared, there is still a toolbar that stays at the bottom
- [ ] Safari:  the full screen button once on full screen is not closing the full screen
- [ ] Vincent’s status is ‘ended’ because he crashed himself when toggling camera. Now he gets the pop-up to leave everytime. Status should have been reset when he rejoined ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/69c85662-c95c-48d6-b83d-4f5197027d25)
- [ ] Safari: every time media changes, I got the modal "don't leave"
- [ ] Safari: still the error when cutting off camera
- [ ] the page switcher as a buyer is shown when in full screen mode (maybe solved already)

_Originally posted by @phpgeekfr in https://github.com/blockframes/blockframes/issues/7061#issuecomment-970456340_

- [ ]  is it possible to have a max-width and min-width on the whole section that contains attendee's self videos (to decide with dev on live tests if possible).
We need to harmonize the grid there (there is too much space between people)
![Capture d’écran 2021-11-10 à 12.05.02.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/8e4d2990-609c-48d9-88f6-066307592b84)
![Capture d’écran 2021-11-10 à 12.11.59.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/c9aeb419-16e2-4c98-8afa-f9f0c7ea9614)
### Icon visibility
- [ ] When the shared content (video or pdf...) has a white background. The "enlarge screen" icon is not visible anymore.
We could have a discret circle background behind or a transparent band behind. (something to test live)
![Capture d’écran 2021-11-10 à 12.06.14.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/e9a1b334-bff2-423c-ac70-0e707d41603a)

- [ ] Icon should stay fixed in the bottom of the container no matter what the height of the shared content is. Here you can see that it goes up when the shared content is loading for example.
![Capture d’écran 2021-11-10 à 12.13.53.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/e8e5613f-e706-4176-8b57-9988bcc3acae)

### Attendees Names 
- [ ] Truncate and have body-2 or caption instead of body-1?
![Capture d’écran 2021-11-10 à 12.15.42.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/c4b8727c-0abd-4df4-9af3-fb241a11dc0e)

_Originally posted by @RemcoSimonides in https://github.com/blockframes/blockframes/issues/7061#issuecomment-970054838_

- [ ] Fix: If possible, have the cameras in format 16:9 to avoid all the black spaces.

![image](https://user-images.githubusercontent.com/93206363/140782796-931110d1-4c24-46bf-ac01-5c66c1c15e41.png)

.
- [ ] Fix: Automatically switch on the main audio channel of the device if something is unplugged.

- [ ] Context: When a user disables the camera before entering the meeting, and enables it afterwards, it doesn't work. Some users could see me, others couldn't. Can we identify what's causing this?

Some users can not see user FB
![image](https://user-images.githubusercontent.com/93206363/141106167-30710fc1-d425-494d-b134-9c9a6b2b06f7.png)

Some users can see user FB
![image](https://user-images.githubusercontent.com/93206363/141106250-6d3ee0d3-e8f4-4f60-a53e-afe0f25132e3.png)

- [ ] Fix: give the 2nd seller the same video display as the 1st seller.

_Originally posted by @cams-goussale in https://github.com/blockframes/blockframes/issues/7061#issuecomment-964927654_

- [ ] Remove thin line around the camera images
![image](https://user-images.githubusercontent.com/55785823/142210163-38dc8d6e-27aa-4912-92a4-c99ef3488b24.png)
![image](https://user-images.githubusercontent.com/55785823/142210139-de8b1498-7ca9-4c45-a94b-76e8f5611058.png)

- [ ] As a buyer, I can see (and manage!) the controls here:
![image](https://user-images.githubusercontent.com/55785823/142210690-6f4e79e8-b997-44df-8631-b7bc6b36c91c.png)

- [ ] Once everyone is gone from the meeting, I can stay here indefinitely (more than 10 min here)
![image](https://user-images.githubusercontent.com/55785823/142210576-99e01467-2543-4688-9eeb-6e17e4b7a0c8.png)

_Originally posted by @maltmayer in https://github.com/blockframes/blockframes/issues/7122#issuecomment-971589867_

- [ ] When I'm on an event, the link in the logo doesn't lead me back to the homepage as it should, it leads me to the page I'm on (as you can see in the bottom left with the url

https://user-images.githubusercontent.com/55785823/142211758-a413685a-381f-4cc5-8207-d4a6358a99db.mov

_Originally posted by @maltmayer in https://github.com/blockframes/blockframes/issues/7122#issuecomment-971595397_

**Comment by RemcoSimonides** [comment]
- [ ] Also problem with spacing here, need more space between "add files" and selected files
![Снимок экрана 2021-11-15 в 08.57.07.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/bcb6d32d-298e-4935-bb5a-9800ce4c00ab)

**During the meeting**
- [ ] Seller's camera on Safari was turned on, then a Buyer joined the meeting (via Mozilla 94.0.1) and at this moment Seller's camera turned off. Then clicking on camera icon helped. But still important to know why camera turned off. 

P.S. at the same time camera on Buyer's side worked well (Buyer could see Seller on Mozilla, but Seller could not see himself on Safari). 
![meeting camera.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4b2604a2-359b-46c3-acd5-cd701019a943)

**Comment by cams-goussale** [comment]
- [ ] On Edge browser, add the little hand cursor for the Organizer. (It's ok on the Guest)
![image](https://user-images.githubusercontent.com/93206363/142234811-d634dbdb-0851-43d3-b5d8-da5994a0ad10.png)
