### ISSUE TITLE
Important Improvements on New Slider

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#7163]
@2amarkina @frenchyrules fell free to put suggestions here.

**Comment by stephanie-cascade8** [comment]
New Slider : 

- [ ] Reduce the ongoing screening button (it was made to be smaller initially but it was not mentioned at first review)
- [ ] Provide a picture with the gradient overlay (I thought that the gradient would be made in css on top of the sits images but we can include it in the image instead, it will be better)
- [ ] Find the issue that went to sanity team long time ago about the new variant on mat-buttons when they are aligned on the left.

- [ ] Center the movie title on top of the content and make the poster smaller still aligned on the left with the other elements on the right.

**Comment by RemcoSimonides** [comment]
>     * Provide a picture with the gradient overlay (I thought that the gradient would be made in css on top of the sits images but we can include it in the image instead, it will be better)

Why are pictures better? They are bigger and don't adapt to the theme?

**Comment by Jackseed** [comment]
To see with @stephanie-cascade8 but maybe need to add some color to make the chair texture a bit less visible

![image](https://user-images.githubusercontent.com/27687382/142446319-1af21862-d014-4dfd-ad30-871db796a68d.png)

_Originally posted by Ana in #7114_

**Comment by stephanie-cascade8** [comment]
@RemcoSimonides Pictures are not better to me but if I'm not wrong the overlay gradient is not made in css on this slider so I need to make the overlay on the picture and re-upload it. 
That's unless you wanna work the overlay in css but we would have to do it live.

**Comment by frenchyrules** [comment]
![Uploading Slider.png…]()

**Comment by frenchyrules** [comment]
![Slider](https://user-images.githubusercontent.com/85220905/144240333-d1d36deb-b085-44df-b7cd-012b9384ff6d.png)

**Comment by stephanie-cascade8** [comment]
@frenchyrules could you show it inside a homepage to what it looks like between the other section? I'm worried about the alignement on the left and also about a small title on top to ensure consistency with other section?

**Comment by stephanie-cascade8** [comment]
New zeplin here https://zpl.io/VQzm53R
