### ISSUE TITLE
Margins are missing on CRM event view

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7169]
Margins are missing on CRM event view
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/6f36e3e3-bc32-4a7b-9dbb-8f2e6c31327f)
vs
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/d2369109-2b14-47f5-b87f-038a30ba8088)

_Originally posted by @Jackseed in https://github.com/blockframes/blockframes/issues/7061#issuecomment-966330906_

**Comment by phpgeekfr** [comment]
@Jackseed can you provide more info on this please ?

**Comment by RemcoSimonides** [comment]
You'll see it when you go to event page in CRM.
The whole page just needs some margin on the left
