### ISSUE TITLE
Small improvements for Event Form UI

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7171]
**Event creation page**
- [ ] The tabs should stay on the same level and avoid scrolls as they do on the film page **(important)**
![screenings](https://user-images.githubusercontent.com/55499036/141495721-8f41b115-fdf6-41cd-a833-0d8d9d44b836.gif)
=> linked to #6778 #6759 and #7134

- [x] In the Leaving page Modal Put the primary CTA before secondary one 
<img width="1246" alt="Снимок экрана 2021-11-12 в 16 57 26" src="https://user-images.githubusercontent.com/55499036/141496407-13632442-2336-4e82-aa4e-f1218d1ca6b9.png">

**Invitations**
- [x] Need more space between progress bar and surface below 
![Снимок экрана 2021-11-15 в 08.58.33.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/d2425f0c-2b13-4651-a09c-e6590fe565cd)

_Originally mentioned by Ana in #7114_

**Comment by phpgeekfr** [comment]
- [ ] In the Leaving page Modal and the one when we want to set event as private if there is already invited users, missing cross to close 
![image](https://user-images.githubusercontent.com/1194344/145576095-e19e1991-1c9d-4c51-a2fb-cddd47dd7854.png)
