### ISSUE TITLE
No screener page - visual improvement

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7178]
created from #7060

This page should be improved visually. Have an illustration or at least a CTA to contact us or the sales company
image
![image](https://user-images.githubusercontent.com/93206363/142406305-bbdc9145-8a8e-48b2-80ff-3e0558516133.png)

**Comment by Jackseed** [comment]
It's really hard to come in that situation (event has to be started and not have any movie), especially since in near future we will be able to have events with movies without screener. It will then be even less likely to happen
