### ISSUE TITLE
Landing Page in Mobile

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7194]
The landing page is a "face" of the app. We can see that many users who arrive on the landing are using their phones. It's important to make a good impression on them, especially as some are really reading the text. 

:bell: **The following concerns the vertical format on mobile use.** Everything is OK when using phone horizontally. :bell: 

**The sections that have to be improved at first (urgent as need to make them readable)**: 
- [x] Description of Sales Agents / Buyers 
- [x] Features block

**The second round of corrections**
- [x] The section "Testimonials" need to reduce the space around the text surfaces
- [x] Add space in the "Demo" section

**Comment by stephanie-cascade8** [comment]
Zeplin here https://zpl.io/agEKq6D

Some parts are still in review (not ready for dev I guess)

**Comment by RemcoSimonides** [comment]
It would be nice to know what has been changed otherwise the dev has to play the game 'find the differences' without knowing how many differences the are ^^

**Comment by cams-goussale** [comment]
@2amarkina @stephanie-cascade8 can you confirm if the only changes made are the ones listed at the beginning of the issue?

> The sections that have to be improved at first (urgent as need to make them readable):
> - Description of Sales Agents / Buyers
> - Features block


> The second round of corrections
> - The section "Testimonials" need to reduce the space around the text surfaces
> - Add space in the "Demo" section

**Comment by 2amarkina** [comment]
Here are the changes according to the actual situation / zeplin screens: 

### Archipel Market **MOBILE ONLY** (check up all the tech possibilities, @stephanie-cascade8 please confirm if everything below is ok and you can edit this present comment with more specific details)

**Toolbar:** 
Keep up only with "Join us" button on the right

- [ ] Remove Log In
- [ ] Remove Sign Up
- [ ] Remove "First Invitation" 

- [ ] Keep only with "Join us" 

**Header Banner**

- [ ] Align-center to all the content inside 
- [ ] Add "down arrow" icon to anchor the content

_from this_ 
![Image d’iOS](https://user-images.githubusercontent.com/55499036/150785159-29a6ee33-1fe6-4ad3-99ad-c5eb6818dd3a.png)

_to that_ 

<img width="227" alt="Снимок экрана 2022-01-24 в 13 45 14" src="https://user-images.githubusercontent.com/55499036/150785260-bb0e06a4-2df7-462c-bd78-6939715db1d0.png">

**Logos bloc**
Can keep as it is 

**Archipel Community**
Should come together with Archipel Bridges ---> verify if need the specifications right now

**How it works**

- [ ] Expand the text area
- [ ] Make the tabs visible
- [ ] Remove the title "For XXXX" 

from this 
![Image d’iOS (1)](https://user-images.githubusercontent.com/55499036/150786064-b88c00bc-cb9e-4c0e-b2a3-ee31e519292a.png)

to that 
<img width="235" alt="Снимок экрана 2022-01-24 в 13 51 46" src="https://user-images.githubusercontent.com/55499036/150786225-d86beb85-fc6a-4e25-ad42-b6dcf933d261.png">


**Features + Benefits**
@stephanie-cascade8 please confirm, but if i'm not mistaken, it was quite difficult to have carousels here as presented on mock-ups below? 
<img width="233" alt="Снимок экрана 2022-01-24 в 13 53 22" src="https://user-images.githubusercontent.com/55499036/150786462-ad342ec3-bb4a-4379-ac99-c1e0d4c7b8f3.png">
<img width="224" alt="Снимок экрана 2022-01-24 в 13 53 28" src="https://user-images.githubusercontent.com/55499036/150786465-17a490e5-a4ac-4f45-937e-ff780582085d.png">

_If it's the case and it takes too much time to provide carousels for mobile version, then_
- [ ] expand the feature to take more space to make the text "readable", @stephanie-cascade8 if ok for you, could we have a mockup to illustrate the example? 
![Image d’iOS (2)](https://user-images.githubusercontent.com/55499036/150786733-095712ae-80cd-4e3f-9dc4-be32eaf9572e.png)


**Interested Hero**
All good


**Testimonials**
- [ ] Expand the content area 
- [ ] Put the text in two lines "What our / clients say" 
- [ ] Align the content in the surface to the left 

_from this_
![Image d’iOS (3)](https://user-images.githubusercontent.com/55499036/150787225-df442b18-6307-4b4e-93db-bd9b520f7cc3.png)

_to this_
<img width="227" alt="Снимок экрана 2022-01-24 в 14 01 04" src="https://user-images.githubusercontent.com/55499036/150787357-1aaf075f-4e8c-45e3-b64c-f90c81ff3325.png">

<img width="229" alt="Снимок экрана 2022-01-24 в 14 01 25" src="https://user-images.githubusercontent.com/55499036/150787416-ef4d95a3-f705-4db4-8dca-a36ecf9112af.png">

**Comment by 2amarkina** [comment]
[Supp techncal infos: ](https://app.zeplin.io/project/60f1bfbe8ba3cb10f41d498e/screen/61cde0e87b3b0fb66546e07b)

<img width="435" alt="Снимок экрана 2022-01-24 в 14 04 21" src="https://user-images.githubusercontent.com/55499036/150787908-b5d58d30-2ca8-4481-ad15-7926e047cb7f.png">

**Comment by 2amarkina** [comment]
### Archipel Content (mobile ONLY)
**Toolbar** @cams-goussale if we go for it right now? 
- [ ] Remove Log In
- [ ] Remove Sign Up
- [ ] Remove "First Invitation"
- [ ] Keep only with "Join us"

For AC the actual elements on staging seem all good !

**Comment by cams-goussale** [comment]
Yes, let's go for it: only "Join us" button on the toolbar in both apps :)

**Comment by 2amarkina** [comment]
**Archipel Market** 

MOBILE
Landing Page > Cookies Change parameters > Data Privacy Policy Modal
- [ ] The scrolling should not be there (should be like Change Parameters modal)
![Image d’iOS](https://user-images.githubusercontent.com/55499036/166236459-8ce7088e-cc78-4219-af7f-b276235ccd29.png)
