### ISSUE TITLE
Homepage movie slider - improvements

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7199]

**Comment by stephanie-cascade8** [comment]
![Slider](https://user-images.githubusercontent.com/85220905/144240333-d1d36deb-b085-44df-b7cd-012b9384ff6d.png)

@frenchyrules sorry that was the wrong github issue. I reassigned you in the good one and copy paste your screen here above

**Comment by stephanie-cascade8** [comment]
@frenchyrules could you show it inside a homepage to what it looks like between the other section? I'm worried about the alignement on the left and also about a small title on top to ensure consistency with other section?

**Comment by frenchyrules** [comment]
![home_test_movie-slider](https://user-images.githubusercontent.com/85220905/144255450-624f8f01-eb6e-4558-aa10-19a9fa9473fa.jpg)
Is this ok @stephanie-cascade8 ?

**Comment by stephanie-cascade8** [comment]
Zeplin final [here ](https://zpl.io/aXpkK18)(the carousel is located at the end of page)
