### ISSUE TITLE
create a Pipe for `{{ getStaticBySlug('GENRES', item) }}`

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#720]
like : ``` {{ item | code: 'GENRES' }} ```
https://angular.io/guide/pipes

**Comment by phpgeekfr** [comment]
did you manage to use this `translateLabel` pipe somewhere ?

**Comment by Maxstgt** [comment]
not yet, didn't encounter a use case. Maybe with the new ux/ui.

**Comment by phpgeekfr** [comment]
roger that
