### ISSUE TITLE
AC Landing animations - File preparation

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7200]
- [x] Test with a dev if we can have a video with autoplay or we need an svg
- [ ] File prep

**Comment by Jackseed** [comment]
see comment for video working with autoplay on #6749

**Comment by stephanie-cascade8** [comment]
[Detailed description ](https://zpl.io/2vXvl1v)
Needs validation by Yannick before we launch work in after effects

**Comment by Jackseed** [comment]
@stephanie-cascade8 this is done right?

**Comment by stephanie-cascade8** [comment]
Yes!
