### ISSUE TITLE
Stills & videos disappear on prod

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7206]
Marie uploaded multiple videos & still photos on the same movie and they keep disappearing.

**Comment by maltmayer** [comment]
Yes I've noticed this recurring problem on this film XMhUtlpcxb9a2KvJWJ9G
I uploaded 10 images and 4 videos multiple times (at first thinking that the mistake was coming from me). I uploaded everything one by one and saved everytime. I also checked everytime that the images and videos showed up on the marketplace movie page and they did. And when I checked the day after, most of the images and videos had disappeared (first time : 1 image and 1 video were still there / second time : no image and 1 video (the same as the first time) was left)

**Comment by maltmayer** [comment]
Okay so some news: last time I went back on the film's marketplace movie page, all the images and videos were there. 
BUT only 3 images appeared on the movie form and no video. I thought it was a display issue so I continued what I was doing. But when I saved, everything disappeared except the 3 images.

**Comment by phpgeekfr** [comment]
moved to #7255
