### ISSUE TITLE
Dashboard - My Titles issue with SumPipe 

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7219]
Bug is on staging, so I guess it is on prod also: 

uid: 2OJUZoWtTVcew27YDZa8FQQdg5q2
email: dev+mohammed-vse@blockframes.io
visit :  https://staging.archipelcontent.com/c/o/dashboard/title

First error is PermissionError, then if I make user blockframes admin, I have a new error related to `SumPipe` : because there is no income for the movies.

```
@Pipe({ name: 'getIncomesFromTitle' })
export class GetIncomesFromTitlePipe implements PipeTransform {
  constructor(
    private contractService: ContractService,
    private incomeService: IncomeService
  ) { }

  transform(titleId: string) {
    return this.contractService.valueChanges(ref =>
      ref.where('titleId', '==', titleId)
        .where('status', '==', 'accepted')
        .where('type', '==', 'sale')
    ).pipe(
      map(contracts => contracts.map(contract => contract.id)),
      switchMap(contractIds => this.incomeService.valueChanges(contractIds)),
    );
  }
}
```

```
@Pipe({ name: 'sum' })
export class SumPipe implements PipeTransform {
  transform(source: number[])
  transform(source: unknown[], key: string)
  transform(source: number[] | unknown[], key?: string) {
    if (key) {
      return source.reduce((sum, item) => {
        const value = key.split('.').reduce((result, k) => result[k], item);
        return sum + value;
      }, 0)
    } else {
      return source.reduce((sum, i) => sum + i, 0);
    }
  }
}
```

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/28f030fd-dbbc-41ca-9206-6402aaed4842)

**Comment by phpgeekfr** [comment]
sentry error https://sentry.io/organizations/cascade-8/issues/2810353248/?environment=staging&project=1540126&query=is%3Aunresolved

**Comment by xmano** [comment]
Also found a traceback when just navigating to Library Page

![image](https://user-images.githubusercontent.com/8731418/143210923-b9ffa185-ae01-4fc8-bad8-25ebf5b9dd32.png)

Please check if it is related to movie data.

**Comment by yspringfield** [comment]
> Please check if it is related to movie data.

Was unable to reproduce this. Seems I don't have this problem in my env.
