### ISSUE TITLE
New territories to include on the map

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7220]
### Description

We have noticed some small territories cannot be clicked on the avails map (Hong Kong, Monaco, Andora..). These territories are in the **list** of territories but not in the **geojson coordinates map.**

(Hong Kong is an important one, Yuki might bring some clients for this territory)

### What's new

We've searched for new maps which would include these territories but would need some input from you @GrandSchtroumpf @pldespaigne:

- https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_50m_admin_0_countries.geojson
This file includes Andorre, HK, Monaco. But it's hard for us to see if all territories are included.

- https://github.com/simonepri/country-iso
This one is an API but it's based on the official iso list of territories.

**Comment by cams-goussale** [comment]
Hello @GrandSchtroumpf :) after the different comparison you made, I confirm we can go with the new geojson proposition:

https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_50m_admin_0_countries.geojson

**Comment by cams-goussale** [comment]
[Research doc](https://docs.google.com/spreadsheets/d/1-vkPqbzE9qB-_dRlk6q46FCfxFaQrbZCgXcJ0ngA)

Should we treat this issue together with #7235 ? There is a bit of mess currently when uploading mandates, some territories are not showing in the map due to incorrect match between the static model and the geojson ([see this comment here](https://github.com/blockframes/blockframes/issues/7139#issuecomment-1000810390))

In any case, when this issue is done, we need the final list of territories included in the geoJSON so we can update the excel imports.

**Comment by RemcoSimonides** [comment]
These countries are in our current territories list but are not in the geojson
World, Bonaire, Bouvet Island, Christmas Island, Cocos Islands, Northern Cyprus, French Guiana, Gibraltar, Guadeloupe, Republic of Kosovo, Martinique, Mayotte, Sint Eustatius and Saba, Réunion, Svalbard and Jan Mayen, Tokelau, Tuvalu, United States Minor Outlying Islands

World we can keep of course, but let me know if I can remove the others

**Comment by RemcoSimonides** [comment]
Three more countries that have iso_a3 of "-99" and do not exist in our territories list. Should I add them to the territories or remove them from the map?
* Ashmore and Cartier Islands
* Indian Ocean Territories (Australia (not British))
* Siachen Glacier

**Comment by RemcoSimonides** [comment]
I will make a migration for the countries that are removed (Bonaire, Bouvet Island, Christmas Island, Cocos Islands, French Guiana, Gibraltar, Guadeloupe, Martinique, Mayotte, Sint Eustatius and Saba, Réunion, Svalbard and Jan Mayen, Tokelau, Tuvalu, United States Minor Outlying Islands). My suggestion would be to simply remove the country if it's in an array (e.g. the list of territories in terms) and for non-array values (e.g. org address) to remove the value.

These are the locations where the territories are used in our data:
* bucket => holdback => territories[]
* bucket => term => territories[]
* movie => originCountries => territories[]
* movie => BoxOffice => territory
* movie => MovieOriginalRelease => territory
* movie => MovieRating => territory
* movie => MovieShootingLocatinos => territory
* movie => stakeholder => territories[]
* user => preferences => territories[]
* organization => location => territory

**Comment by cams-goussale** [comment]
@RemcoSimonides could you send me the final list of territories we have:
- in our territories list
- in our new geojson map

I must update the template excel import.

**Comment by RemcoSimonides** [comment]
Templates updated.
