### ISSUE TITLE
Merge invitation email with cred reminder 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7227]
We created a new template `Template ID: d-454847c886d4485586c3d1b4f467c03f` for invitations to users that already received an invitation with credentials but didn't activate their account yet. 

I think this template can be merged with the pre-existing invitation without credentials `Template ID: d-1a7cc9ca846c4ae1b4e8cf8a76455cc5` by adding a simple if on the last text block. 

I already added the if block so we should just agree on the variable to use and test it before replacing ids. 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/5e857f2b-228e-4a53-9163-f395531e8e6a)

**Comment by Poppe-A** [comment]
@Jackseed I choosed the variable name `isInvitationReminder`. 
Don't forget to merge the template version 6 and 7 (see #7338)
