### ISSUE TITLE
Signup page - Mobile optimization

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7229]
On mobile, checkboxes are too small and/or too close from the text, we saw users clicking on the link while trying to click on the checkbox. As it redirects them they can be confused and stop the signup process
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/183cb327-924f-4c57-af70-5e5c4fc4f566)

**Comment by stephanie-cascade8** [comment]
On mobile only (media query)

- [ ] change chexbox's width and height from 16px to 24px.
- [ ] change checkbox margin-right from 8 to 24px.
- [ ] Change checkbox margin-top to 4px (to align it with the top of the text)
- [ ] have more space (24px) between the checkboxes group and the rest of the form.
- [ ] take off the surface behind (only mobile not tablets) 

See result here:
<img width="914" alt="Capture d’écran 2021-12-17 à 14 13 32" src="https://user-images.githubusercontent.com/66258851/146550326-49fc5a73-91c5-4da0-aa36-35c6d567e67c.png">
<img width="828" alt="Capture d’écran 2021-12-17 à 14 13 06" src="https://user-images.githubusercontent.com/66258851/146550338-b1b2e46d-aa40-487f-8530-a721d6206a73.png">

**Comment by stephanie-cascade8** [comment]
To improve the top of this page : 

- [ ] title line-height : 36px (that can be set to all similar titles in our apps)
- [ ] between logo and title (maybe padding on the layout for it to be global) : 32px.
<img width="796" alt="Capture d’écran 2021-12-17 à 14 20 13" src="https://user-images.githubusercontent.com/66258851/146550952-5fbf169f-20d0-483f-a926-f819d5ff1b29.png">
