### ISSUE TITLE
[Static Model] Territories use iso_a3

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#7235]
Currently in the database we are using a custom key to map the territories (for example: `united-state-of-america`).
As we work with other tools like `geojson` we need to add some "glue" to bind the standard iso_a3 with our keys.

We should use `iso_a3` instead of the custom key: 
- Do a migration of all the content that are using territory
- Update the static-model to use iso_a3 instead of the custom key
- Update bindings with geojson's map
- Make sure the `territories` static model matches exactly the geojson territories (no more, no less)

**Comment by RemcoSimonides** [comment]
I've noticed that the `geojson` has multiple countries with `ISO_a3` of '-99'. Therefore it probably shouldn't be used as the unique key. Our custom key not causing any issue at the moment and we can still "glue" the `territories` and `territoriesISOA3` together using this custom key
