### ISSUE TITLE
[Catalog] Remove Sellers list in Markeplace

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7243]
Yuki suggested we remove the access to the Seller's list. She will change the access from the homepage buttons through cms. We need to remove it as well from the sidenav.

**Comment by cams-goussale** [comment]
@RemcoSimonides would it be possible to add this in the release?

**Comment by RemcoSimonides** [comment]
I think so ye. I've added it to the list.

**Comment by RemcoSimonides** [comment]
Reason to remove the access is because it looks poor since we don't have many sellers yet. Enable it again once there are enough sellers to display.

**Comment by cams-goussale** [comment]
@aamarkina we are going ahead with this, in case you want to update wireframes.
