### ISSUE TITLE
Inventories clean up

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7256]
### Context

The January release shall be dedicated to various type of clean ups. Let's pick up the inventories topic back on track.

### Execution

Let's try to do the following:

-1 issue per inventory
-1st step: Design to clean the inventory document. Once done, advise Marie
-2nd step: Marie/Yuki to check the final version
-3rd step: Highlight the changes
-4th step: Issue to send to devs

### Priorities
-Tables
-Snackbars
-Text
-Tooltip
-Modal

**Comment by phpgeekfr** [comment]
- [ ] once everything will be done, we will deploy to an env so everything can be reviewed before next release
