### ISSUE TITLE
Put Sales Pitch with Key assets

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7258]
**Idea from Marie:** 
Put the Sales Pitch video near to the Key Assets

**Comment by Jackseed** [comment]
Following #6893 it looks like we should in fact remove completely sales pitch description from the movie form as it won't be display anymore. Then the sales pitch video can be kept only as a video type (and will be treated equally with other videos). 
What do you think of this? If we go along with that if think this issue has no use. 
cc @2amarkina @maltmayer

**Comment by cams-goussale** [comment]
Closed after business approval
