### ISSUE TITLE
load firestore rules into emulator during e2e tests

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#7261]
This is an ongoing discussion - if it's possible or needed to ensure that the emulator (when run on CI for e2e tests) reads and enforces our database access rules.

We already have unit tests for rules that use a specific lib that I believe calls undocumented functions in the emulator that loads the rules. However, I might be wrong because there have been updates to the emulator suite since I looked into this issue last.

I have tagged people to discuss the issue.

**Comment by xmano** [comment]
In my opinion, it is better to have E2E test check the app completely taking into consideration the firestore rules. This will guy us early indication if something is broken or not working as intended.

Although, Unit Tests would cover security rules, but there might be cases when unit-test is not ready or itself having a bug.

If E2E tests can replicate the actual user behavior and the issues face that would be best.

**Comment by phpgeekfr** [comment]
When running e2e tests, rules are evaluated.
