### ISSUE TITLE
prevent double click on "sign up" and "sign in" buttons in a more robust way

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7265]
It looks like that some people are having issues while creating their account :
- this.user is null in snackbar
- incorrect invitation pass in snackbar

This errors can happen if we double click on the button. This is already prevented in code but maybe some slow computers are a not updating the page fast enough to prevent double click.

A more robust solution should be implemented

**Comment by Jackseed** [comment]
tagged as high priority since it's a login issue

**Comment by RemcoSimonides** [comment]
What do you have in mind @phpgeekfr ? I tried spamming the buttons but nothing breaks

SIgn up button is disabled when the account is being created. Log in button is not so I could disable that

**Comment by Jackseed** [comment]
This issue is really about sign up and not log in because it has the side effects listed in the issue that prevent users from logging in after account creation

**Comment by phpgeekfr** [comment]
> What do you have in mind @phpgeekfr ? I tried spamming the buttons but nothing breaks

I also tried, without success, but @Jackseed did . I assume that slow computers may not update the HTML view fast enough so they can click multiple times..

My idea is to prevent double login/ sign-in in the `ts` file
