### ISSUE TITLE
Events pages are accessible for connected users that does not have access to marketplace module or festival app

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7266]
Currently, users with a real account can access an event even if their org does not have access to marketplace module or festival app.

If they do so, links in top bar and left menu will not work.

We need to check with UX / Business team what to do in this case. 

- Prevent users to access the event ?
- Hide the menu with incorrect links ?

@2amarkina  @Jackseed  any ideas ?

**Comment by 2amarkina** [comment]
For the moment I would say that the users who have no org access to the app should be treated as as users with no account. So we do not show neither top bar with profile nor sidenav menu. 

BUT, if we say that AC and AM users have accesses to both apps, then we should keep up with toolbar and sidenav. @Jackseed what do you think?

**Comment by Jackseed** [comment]
I agree with you, users without org or app access should be consider like anonymous accounts.

AC and AM accesses won't be by default so shouldn't be a problem here.

**Comment by cams-goussale** [comment]
@2amarkina @phpgeekfr I am a bit lost on this issue. Currently we have this:

If user has the link to a Private event, user will see this:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/93206363/168256490-07592cd4-c937-41ed-ac2b-d64b3ee3413a.png">

Current behavior: after choosing his role, user lands on the event page where he can request access. When clicking on navigation buttons, user gets redirected to `You don't have access to the app`.

Question: wouldn't it be weird that a seller receives a request from a user who doesn't have access to marketplace or to the app? It makes me think of the undesired behavior identified in this issue #8058

Protected event, user will get redirected to homepage with the message we discussed last week
<img width="375" alt="image" src="https://user-images.githubusercontent.com/93206363/168238461-fa3091be-ed28-462b-bf49-371cbcaf62bf.png">

Question: this behavior makes sense to me. Why don't we use the same one for private events?

Public event, user will see this
<img width="334" alt="image" src="https://user-images.githubusercontent.com/93206363/168237895-823a7a6b-efff-478c-a6b3-b8399d446f63.png">

This one makes sense to me.

**Comment by phpgeekfr** [comment]
> If user has the link to a Private event, user will see this:

I assume you logged in with an user that does not have access to festival app but only catalog for example ?

> wouldn't it be weird that a seller receives a request from a user who doesn't have access to marketplace or to the app? 

From a technical point of view, event creator was able to approve the request
![image](https://user-images.githubusercontent.com/1194344/168277884-d00491ec-b97e-4de7-9d40-2d41f6aff2cb.png)

> Question: this behavior makes sense to me. Why don't we use the same one for private events?

For private events we could prevent an user to access event page if he does not have access to festival app or marketplace but I think this is not what was defined at first. We could also hide menus as first suggested


This issue looks like linked with #7627
