### ISSUE TITLE
Events without connexion - Mobile Optimization

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7267]
We need to adapt this part for the mobile. The example is shown below. 
![Image d’iOS.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/3af15495-8208-4339-b579-8f33b65da8cf)

**Comment by 2amarkina** [comment]
- [ ] Add the AM logo to the event page in mobile version to help user to fine out some new information

**Comment by stephanie-cascade8** [comment]
Mockup on zeplin [here ](https://zpl.io/amJOQZA)

- [ ] take off stars background
- [ ] take off surfaces
- [ ] all content layout (width: 90% centered)
- [ ] the content should be vertically centered in the screen or (if not possible) be at distance of 32px from the logo.
<img width="394" alt="Capture d’écran 2021-12-17 à 14 52 04" src="https://user-images.githubusercontent.com/66258851/146554519-e8b9c292-ca91-4c72-b4ae-ec3712c8664a.png">
