### ISSUE TITLE
Modify the display of Running time for TV series

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7268]
### Localization
- App name: Content
- Page: Movie page
- Url: c/o/marketplace/title/[title.id]/main

### Context
-When a title is a TV Series, we should display [Average Episode Running Time] x [Number of Episodes]
-The structure would be the following (the main change is in bold):

[Format] | **[episodeCount] x [runningTime.time]** | [Genre] | [Country of origin] | [Original Languages] | [Season Number] | [Production Status]

### Example
TV Series | 16 épisodes x 20 min | Documentary | FR | French | Season 1 | Released

### Images
![image](https://user-images.githubusercontent.com/93206363/143839433-ee193ddc-bcf7-45ef-8a0d-63548038d5f5.png)

**Comment by RemcoSimonides** [comment]
@cams-goussale I don't think we have this information. If you want this, it should be possible to fill in this information in the movie form.

**Comment by cams-goussale** [comment]
Hello @RemcoSimonides yes we do have these 2 fields in the movie form. I've updated the issue, they're actually called
[runningTime] x [episodeCount]

![image](https://user-images.githubusercontent.com/93206363/143866086-f9f1db15-ce61-441c-a3fc-a9306bc4555a.png)

**Comment by phpgeekfr** [comment]
In PDF export (#7045) as @isseymiyuki asked I implemented this `"YxZ min", Y being the amount of episodes`

But in this issue it is ` [runningTime.time] x [episodeCount] `

Having `12 x 24 min` is more logical than `24 min x 12` looks like more logical

**Comment by isseymiyuki** [comment]
12 x 24 min is more common.

**Comment by cams-goussale** [comment]
I updated my initial comment

**Comment by phpgeekfr** [comment]
@cams-goussale on movie summary, what do you want :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/6fc36a94-8cf4-4c19-bfba-b5d9994f858b)
or (current)
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/711ae355-4fc8-4db6-9473-473976f4b968)

I can also remove `Count of Episodes 10`

**Comment by phpgeekfr** [comment]
Same question here :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/d4db59f1-95d5-4ceb-83a4-3fb66da3b4fb)

https://staging.archipelcontent.com/c/o/marketplace/title/e3byaWljpKY46mfrZJQT/main

**Comment by cams-goussale** [comment]
@phpgeekfr 

For the movie tunnel summary and the markeplace film page, I think we can do:
Number of Episodes **10**
Running time **10 x 24 min**

For the wishlist we can have only `10 x 24 min`, as you said.

For the movie header, can we get rid of the `8 episodes` and keep only `8 x 50 min` ?
