### ISSUE TITLE
Logos AC/AM: differentiation

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7291]
In the line of the Archipel Bridges strategy, we need to revise the logos of the 2 apps, to make them different and recognizable.

## Directions
-We want to differentiate the 2 logos
-We want to keep the current artistic line: geometric forms, the lines, the cercles

## Context: where these logos will be used?
-Next to each other (on landing pages - the Archipels ecosystem)
-In the nav bar
-In the side nav
-See some WIP examples in [figma](https://www.figma.com/file/GY8lt9tI3nx5xmeMawCtxQ/%5B-Bridge-AC-%2B-AM-%5D?node-id=82%3A9013)

## Versions we would like to have
-Artwork + app name
-Artwork + app name + catchphrase
_(TBC Business: AM - The ongoing film market | AC - Multi-seller deals)_
-Artwork only

**Comment by Jackseed** [comment]
@stephanie-cascade8 here are the logos as they were first design. As you can see it's a visual variation of lines and dots. The difficulty is that it plays with the first letter of the app that is here the same (Archipel Market, Archipel Content). For the current Archipel logo there is also a visual reference to islands > Archipels that is working pretty well. 

I think we should try to stay close the current Archipel logo but find a variation that differentiates more Content from Market

![LogoDApps](https://user-images.githubusercontent.com/14964443/145020466-b54486ef-0588-4a6d-85e6-1665188f9f54.jpg)

**Comment by stephanie-cascade8** [comment]
Hey :) Thanks for all those information @Jackseed . 
Please have a look at this first try. 
![logo-content-1](https://user-images.githubusercontent.com/66258851/145605191-6e3140e4-d9ff-43b5-a637-2049e2e9ebd8.jpg)

![logo-content-2](https://user-images.githubusercontent.com/66258851/145605207-21db9085-7abf-4162-86ee-45e8aab7c774.jpg)

![logo-content-3](https://user-images.githubusercontent.com/66258851/145605231-4719d101-0109-4b41-906d-5f4c3a7330a0.jpg)

![logo-content-4](https://user-images.githubusercontent.com/66258851/145605253-a7a17a25-a52c-45f4-96e8-5758b5d5800c.jpg)

**Comment by Jackseed** [comment]
Imo the last one is really good: both different and really similar from Market, though it's really a subjective opinion. 
@cams-goussale any feedbacks? 
@stephanie-cascade8 did you have other ideas that we could explore?

**Comment by cams-goussale** [comment]
I personally like the 3rd one. The semi circles make me think of a waves when water moves; still in the island/archipel vibe. The C character is pretty recognizable as well. But yeah, it is a bit subjective

**Comment by Jackseed** [comment]
Ok I'll take feedbacks from the business team to see if this is enough or if we need more propositions

**Comment by Jackseed** [comment]
Feedbacks: 
- we keep the current logo for Content
- we change it for Market with a new external shape (instead of the circle + dot)
- we use something relative to Market activities: either screenings or data
![20220103_173426](https://user-images.githubusercontent.com/14964443/148208479-b262bf88-9d72-4309-aee4-d61af20d604e.jpg)

**Comment by stephanie-cascade8** [comment]
Following what we discussed, here is a new propositio
<img width="474" alt="Capture d’écran 2022-01-14 à 12 14 09" src="https://user-images.githubusercontent.com/66258851/149506941-f66f1b88-ef4b-4af2-9648-514537563a43.png">
<img width="658" alt="Capture d’écran 2022-01-14 à 12 15 41" src="https://user-images.githubusercontent.com/66258851/149506956-b8d63dff-6865-463d-8ff4-c156cfa3a59c.png">


n

**Comment by Jackseed** [comment]
The inside is good but I really think we need to change the circle to differentiate it more from AC, could you make propositions with different shapes?

**Comment by stephanie-cascade8** [comment]
![Frame 1](https://user-images.githubusercontent.com/66258851/151370470-872951d1-422c-475e-b523-4dac80548c10.png)

**Comment by cams-goussale** [comment]
We have the go from Business for this last version with the losange 👍

**Comment by cams-goussale** [comment]
Reopenning & sending to dev
