### ISSUE TITLE
Snackbars cleaning UX

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7293]
[Inventory](https://docs.google.com/spreadsheets/d/11mgu0-s9i0KIBRgRUAlE-WjuJQLOaTmMcdrVLEUKwAk/edit#gid=0)

**Comment by 2amarkina** [comment]
- [ ] When general cleaning is done, verify the tone of all the snackbars (when we say "you" or "my")

**Comment by phpgeekfr** [comment]
- [ ] as I already did for error snackbars with the refresh button (https://github.com/blockframes/blockframes/pull/8185/files ) lets also create one component for regular messages with link: 
- apps/festival/festival/src/app/event/login/login.component.html
- libs/user/src/lib/auth/pages/login/login.component.html
- libs/user/src/lib/auth/pages/reset-password/reset-password.component.html
- libs/user/src/lib/auth/pages/identity/identity.component.html

(search for `openFromTemplate`) 
Like this we will have unified code for all custom snackbars

**Comment by phpgeekfr** [comment]
- [ ] check if all existing `this.snackBar.open(error.message, ` and `this.snackBar.open(err.message,` should use the new errorComponent
