### ISSUE TITLE
Floating tooltip

### ISSUE THREAD

**Issue by frenchyrules** [blockframes/blockframes#7296]
Shouldn't the tooltip appear closer to where the mouse is hovering ? In this case I was hovering the "private" radio button, and the tooltip appears in the middle of the screen.
![floating tooltip.PNG](https://images.zenhubusercontent.com/611a265d2ea95c7880c91192/7172885f-5225-452c-99d1-cb58b75161d1)

**Comment by Jackseed** [comment]
@phpgeekfr it looks like it was something already mentioned for release 3.5, do you know if it has been done already or where is the issue about it?

**Comment by phpgeekfr** [comment]
Yeah I think this is solved. @Poppe-A can you confirm ?

**Comment by Poppe-A** [comment]
Yes it's solved, it will be included in the next release.
