### ISSUE TITLE
[Catalog] Timestamp definition: Mandates/Sales/Avails Search

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7310]
### Description

When a Buyer is searching on Marketplace by dates/terms which are included in a seller's mandate dates, we want to make sure the buyer gets a result. We need to specify the timestamp logic for each side (marketplace research vs dashboard mandates).

### Example

In some test, I created 2 mandates in 2 periods of time: Period A and Period B. They were consecutive, ie Period B started the following day after Period A finishes. So there were no gap in betweeen, however, to get a result when searching for Period B on the marketplace, I had to put startDate == (Period B + 1 day) to get a result.

### What's new

We are proposing the following specs to prevent the case above from happening:

Dashboard mandates or sales import
- [ ] Start date should be 00:01 am
- [ ] End date should be 23:59 pm

Markeplace date search in avails filter
- [ ] Start date should be 01:00 am
- [ ] End date should be 23:00 pm

**Comment by pldespaigne** [comment]
For the future dev working on that and to be super clear (so we don't miss the point):
This issue is about setting hours/minutes of the **avails filter form** and not in the mandates/sales in db.

We could do that on `valueChange` on the duration field for example.

However the logic is different between marketpalce and dashbaord so we need to find a clever way of implementing this without adding too much specificity to the code.

**Comment by RemcoSimonides** [comment]
I just tested this and it seems to be working or I am testing incorrectly. @cams-goussale could you check and close this issue if it's working.

**Comment by cams-goussale** [comment]
No this is still an issue. Whenever you upload a mandate with start date == today, in the app it will only show availabilities from today+1. It won't show availabilities on today, even if I uploaded a mandate with today's start date.

Here is a video (not my best video sorry ^^)

https://user-images.githubusercontent.com/93206363/151947742-ab3e04b8-cedc-487f-955b-f72e62a1e273.mp4

**Comment by yspringfield** [comment]
I just inspected in the db and the terms of the mandates are saved as follows
`from`'s time is 11 pm
and `to`'s time is 12am.

This means, setting  `1am` and `11pm` as indicated [above](https://github.com/blockframes/blockframes/issues/7310#issue-1069461593) won't resolve the problem. Rather, setting it to 11pm and 12am respectively does.
Should we maintain the above figures or use these new ones...

**Comment by cams-goussale** [comment]
Actually, I think I am starting to get it. If I upload `start date == 02/08/2022` then the db will put `February 08, 2022 at 11:00:00 PM UTC+1` which actually means (in Paris timezone) `February 09, 2022 at 12:00:00 AM UTC`

**Comment by yspringfield** [comment]
Which means both the dashboard and marketplace filters should be updated to the 11pm and 12am values respectively right?

**Comment by cams-goussale** [comment]
Yes, indeed

**Comment by yspringfield** [comment]
Great, thanks.

**Comment by yspringfield** [comment]
So, upon further investigation, I've come to the following configuration.
1. During import, we set the hours, minutes and milliseconds of the dates to 2,0,0 respectively. //2am
2. In the avails Filter, the startDate hour, minutes and milliseconds is set to 3,0,0 respectively. //3am
3. In the avails Filter, the endDate hour, minutes and milliseconds is set to 1,0,0 respectively.  //1am

This Permits to search the startDate of the avail for the selected date just after the start of the avail and search the endDate just before the end of the avail.

**Comment by cams-goussale** [comment]
Ok, lgtm, I'll have to test it during the release :)
