### ISSUE TITLE
Avails Logic E2E Scenarios

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7313]
As requested in #7139, [here are some E2E and Unit Test scenarios](https://docs.google.com/spreadsheets/d/1YAsKVdFt_ybheXlLJsKoXYdlma-iB1W_ilKPTuHME2w/edit#gid=0) for the Avails Filter Logic.

There were already some tests done in the past that we can reuse:
- 1 title Avails Search #4918 
- Multi-title research #5224 
- E2E scenario #5353 

In the excel, you can find:
- [ ] 3 E2E scenarios: 2 new, 1 improved from the past
- [ ] many unit tests: 5 new, 1 with a change

**Comment by cams-goussale** [comment]
Hello @RemcoSimonides this issue gathers the different tests that should be done to secure the Avails logic. PL estimated the first 2 issues about unit tests #4918 #5224 to 3 days of dev. Any chance we can include it for the release of January?

**Comment by RemcoSimonides** [comment]
Hee @cams-goussale, could you be explicit in what needs to be done? Issue #4918 contains only checked checkboxes, #5224 contains only open checkboxes but then a merged PR and closed, and the excel file contains several sheets and I don't know where to look at.

Also, let's not focus on e2e test for now since they are largely disabled and waiting for rework from George to be more reliable.

**Comment by cams-goussale** [comment]
It's not e2e, it's [unit tests ](https://docs.google.com/spreadsheets/d/1YAsKVdFt_ybheXlLJsKoXYdlma-iB1W_ilKPTuHME2w/edit#gid=1782901115)which are written in these 2 issues #4918 #5224
The sheet in the excel is the one called "Unit test". It contains:
- 1 block for Single movie Avails Research
- 1 block for Multiple movies Avails Research

The tests with box checked are the same as in the issue. The tests not checked are new ones which complete the initial issue. We thought these unit tests were already in place, but from what PL told us, they're not.

When talking about "Single movie" or "Multiple movies" I refer to the information that you can find in the tabs [Import Movies ](https://docs.google.com/spreadsheets/d/1YAsKVdFt_ybheXlLJsKoXYdlma-iB1W_ilKPTuHME2w/edit#gid=1224333819)and [Import Contracts](https://docs.google.com/spreadsheets/d/1YAsKVdFt_ybheXlLJsKoXYdlma-iB1W_ilKPTuHME2w/edit#gid=989765594).

**Comment by RemcoSimonides** [comment]
@yspringfield do you think you can do this after deal negotiation? You probably know a thing or two about avails :)

**Comment by yspringfield** [comment]
Sure, with pleasure!

**Comment by Jackseed** [comment]
@yspringfield when you'll start working on that please send a message to Camille first so she may present you and explain all the rules that support the logic

**Comment by cams-goussale** [comment]
Adding here the [message from PL](https://cascade8.slack.com/archives/C0165RHHK6J/p1641376029001000) which could help
