### ISSUE TITLE
Wording Movie Tunnel 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7319]
Check out the wording for the First and Last step of Movie Tunnel to make it more explicit. 

![Снимок экрана 2021-12-03 в 10.38.01.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/41e9c0c9-1fac-4d2c-8f07-f16c646d3c5d)

**Comment by Jackseed** [comment]
@maltmayer do you have wording propositions please? The idea here was to be more descriptive on what these steps do (ie first= production status and last = submission/publication)
Tricky part is that Production status can't be the step title cause it's already the page title and last step can do both submission or publication but we must have the same word for both

**Comment by 2amarkina** [comment]
**Proposition**, maybe change an icon of the home to something more appropriate to production status? maybe this ![Снимок экрана 2021-12-14 в 14.19.30.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b8d43a2d-8a0c-4866-80ba-4fc1589a8f5d) to see with @stephanie-cascade8 

**Ideas for the first step:** 
1. first step -> stages of production  / production status -> production status
2. first step -> production status / stages of title's production 


**Ideas for last step**
1. last step -> summary / summary & submission -> Submission & Publication

**Comment by 2amarkina** [comment]
@maltmayer what do you think of these :point_up: ? if ok, will move it to "ready for ui/dev" 

cc: @Jackseed @cams-goussale

**Comment by maltmayer** [comment]
I would suggest:

First Step ->  Production Status / Production Status -> Before we begin...
Last Step -> Summary & Submission / Summary & Submission -> One last check!

**Comment by 2amarkina** [comment]
Can go to UI and even to dev in parallel  

Some supporting wireframes to show the changes 
![Снимок экрана 2022-01-20 в 12.28.13.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b47cdca3-131f-4d88-9746-1790a691ca5a)

![Снимок экрана 2022-01-20 в 12.35.25.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/3f88a3c5-b128-4a6f-9068-17a923e532ba)

**Comment by cams-goussale** [comment]
- [ ] Include the transfer of the Movie tunnel to Figma together with this issue

**Comment by 2amarkina** [comment]
moving the transfert of Sketch to Figma and the split of the pages [here ](https://app.zenhub.com/workspaces/design---ui-60ab5f96c64ec50014c46754/issues/blockframes/blockframes/8005)
