### ISSUE TITLE
Meetings max attendies limit

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7324]
Right now, we forbid event creator to invite more than 9 persons (`MEETING_MAX_INVITATIONS_NUMBER`).

Since we now have public events feature, more than the invited people can assist.
We tested with more than this limit so maybe we can get rid of it ?

@Jackseed

**Comment by Jackseed** [comment]
It was more of a UI issue that made us block at 9 here (I created a dedicated issue for that #7339). But I thought the limitation was also when you try to join the event and not only on invitations. 
To me it looks like indeed we can remove that limit but let me check first with business as it may have undesired side effects

**Comment by Jackseed** [comment]
Ok let's go!
