### ISSUE TITLE
Movie Card Structure update

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7332]
Too introduce the app specific zone in Movie Cards we'll need to review it's structure. ![Снимок экрана 2021-12-03 в 17.04.29.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/af6de9e5-ff61-4a8c-9c76-b64e10caae98)

[Link to related wireframe](https://www.figma.com/file/GY8lt9tI3nx5xmeMawCtxQ/%5B-Bridge-AC-%2B-AM-%5D?node-id=56%3A11944)

- [ ] Provide a documentation

**Comment by Jackseed** [comment]
We have currently no titles in both AC and AM and working on movie cards is always difficult so I'd rather wait for something with more impact; closing it for now
