### ISSUE TITLE
Film Banner structure update

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7333]
- [x] Review and document the rules of the Film Banner functioning 

Aim: to be able to introduce new actions and potentially new information ![Снимок экрана 2021-12-03 в 17.06.16.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4089c213-f9c4-4793-9960-642a8a37236e)

**Comment by 2amarkina** [comment]
[Documentation proposition](https://www.notion.so/cascade8/WIP-Banner-Film-Page-WIP-b1464efef5bb46958cd84fc361630268)

**Comment by 2amarkina** [comment]
Can go to UI, need to follow carefully the documentation and verify the possibilities with devs

**Comment by 2amarkina** [comment]
Some updates of the structure to optimize the understanding of the new banner structure
![film banner.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/3d85fe2e-83e6-4955-acba-852e4bab6f35)

**Comment by cams-goussale** [comment]
hello @2amarkina do you still have to review the documentation with Stéphanie & François (or a dev) about the movie banner? or do we close it? I see some highlighted points that might need discussions. Maybe these discussions with dev can happen when they tackle the movie banner issue.

**Comment by cams-goussale** [comment]
actually I see that @stephanie-cascade8 suggested we update the documentation for the mobile decisions. Since mobile is an issue you have during this sprint, I think it'd be great to keep the documentation updated with the UX & UI decisions taken

**Comment by 2amarkina** [comment]
> hello @2amarkina do you still have to review the documentation with Stéphanie & François (or a dev) about the movie banner? or do we close it? I see some highlighted points that might need discussions. Maybe these discussions with dev can happen when they tackle the movie banner issue.

We have a meeting with Stéphanie about Movie Banner on mobile as a part of this issue #7961 . 
So this one might be closed and we concentrate for the mobile & documentation in #7961 .
