### ISSUE TITLE
Distinguish External / Internal sales

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7335]
**HIGH PRIORITY**

After a dev review, it was discussed that it would be better to maintain different designs for external and internal sales. 

Seems to be a good distinction for the moment, as we do not allow the user to modify the external sales after they are entered. 

Should be seen on all the levels (list, page, CRM)

**Comment by Jackseed** [comment]
So far we decided to import only mandates for new titles and no sales. It means that if an external sale exist we will consider it as not part of our mandate. This works well for making marketplace sales. 

It means that external sales are then only relevant for dashboard users that want to manage their external sales with our platform. So far we don't have that much user doing so, so I wouldn't consider it as high priority even if it's indeed a good idea.

**Comment by 2amarkina** [comment]
[Work in progress can be found here](https://www.figma.com/file/bs1vDcQEjbqqPggOYMpdd6/%5B-Deal-Negotiation-%5D?node-id=0%3A1)

**Comment by Jackseed** [comment]
I added a few comments but overall lgtm
