### ISSUE TITLE
Screen advertisement (2nd wave)

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7337]
There are 2 upcoming deliveries for the Screen partnership:
- 18/01/22
- 10/02/22

Assets are the same as previously:
- 1Full page
- 1MPU (small square on their website)
- 1Billboard

@maltmayer can I let you brief this? :)

**Comment by stephanie-cascade8** [comment]
All deliverables were uploaded in drive folder for Marie
everything is validated by Marie and Yannick
![mpu-anime](https://user-images.githubusercontent.com/66258851/151205385-871f504b-8edb-45b0-b497-7003c6b75602.gif)

![billboard-content](https://user-images.githubusercontent.com/66258851/151205491-f962b778-15b4-44af-99cb-3d57e3a18a3c.png)
![full-page_Content_2022 Copy](https://user-images.githubusercontent.com/66258851/151205657-26e14c82-3372-4bdf-95b0-3addca9bbfa0.jpg)
