### ISSUE TITLE
Email - Event invitation - Add multiple time zones

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7338]
Currently event invitation emails display only start & end time in GMT+0 as we don't know users' timezones. 

Instead we should give them a range of classic timezones to help them find the relevant one. 

Classic timezones should be:
- Pacific (UTC-8)
- Central America (UTC-6)
- Eastern America (UTC-5)
- Eastern Europe (UTC+1)
- Central Europe (UTC+2)
- Japan (UTC+9)

To limit dates (since they can change from timezone to timezone), we will only show the start date for UTC and precise it if it's different for a specific timezone. 
We will also display the duration of the event (eg "3 hours" or "3 days"). Minutes should be used for events that last less than an hour, hours for events that last less than 72 hours and days after. 

Invitation emails already have a lot of info, that's why we need UI here: to make the time and date and possible other relevant info (like credentials) visible and readable. 

This time is used in 3 different emails:
- [AM -EVENT - Non private Invitation with credential ](https://mc.sendgrid.com/dynamic-templates/d-5123a0ceda2d463db60717dc94005b65/version/9178f554-c088-4bc6-8320-6d062980b077/editor)(`Template ID: d-5123a0ceda2d463db60717dc94005b65`)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/41ead55b-9427-4ba3-b591-bddc70199b33)

- [AM - EVENT - Invitation with credentials](https://mc.sendgrid.com/dynamic-templates/d-ce3e57248a694cefacad49bc4c820078/version/e57ca86c-9e2d-46ff-8694-f6b12f624e17/editor)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/118d509f-1e7b-4b95-96ad-e04a742aa153)

- [AM - EVENT - Invitation without credentials](https://mc.sendgrid.com/dynamic-templates/d-1a7cc9ca846c4ae1b4e8cf8a76455cc5/version/1f6aee13-906d-4ef3-b7da-2bcc6a0be459/editor)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/05201345-375e-4c25-ac24-a9e47e93379d)

**Comment by frenchyrules** [comment]
Here is a first UI suggestion for AM -EVENT - Non private Invitation with credential. @Jackseed @cams-goussale 
![Capture 1](https://user-images.githubusercontent.com/85220905/150351650-33375f25-2fc1-47da-8254-13efb3a4b9f0.png)
Mobile version
![mobile version](https://user-images.githubusercontent.com/85220905/150351111-f9c90ec8-5ed6-47f8-a889-9a219dacd6c0.gif)

**Comment by cams-goussale** [comment]
@frenchyrules looks nice but it takes a lot of space and I feel we're missing the main information here, which is the Join event. Could we make the time zone a bit more discrete?

**Comment by frenchyrules** [comment]
Still too much ? @cams-goussale Reduced font size, line height, and used a lighter color to quieten it down a bit
![image](https://user-images.githubusercontent.com/85220905/150492628-ecf01cc7-5fef-4f08-9d6f-76c700cb1b04.png)

**Comment by cams-goussale** [comment]
I still think it's too predominant ^^" Could it be not centered, like a side note? Or even a note that would appear only when you click or hover?

**Comment by frenchyrules** [comment]
With this placement the join event button comes first and the timezones info comes second but is still visible and easy to read. The illustrations are still here but don't stretch out the email to make us scroll for important content on mobile either. What do you think @cams-goussale @stephanie-cascade8 ?
![image](https://user-images.githubusercontent.com/85220905/150510967-bc2f917f-207f-49a2-a7ee-c0f39c4dacf0.png)

**Comment by Jackseed** [comment]
The solution we keep should also work for the 2 other email templates. I'm afraid "AM - EVENT - Invitation with credentials" will get really long with your proposition. 
There is a column option in Sendgrid, maybe it could help?
![image](https://user-images.githubusercontent.com/14964443/150800951-65432f94-d913-4fd3-bce5-93792e62b802.png)

**Comment by frenchyrules** [comment]
![image](https://user-images.githubusercontent.com/85220905/152173175-0124b364-f1bd-43f8-9e72-a2af005468c4.png)

**Comment by cams-goussale** [comment]
hey  @frenchyrules thanks, good job :) I want to put some test data to see how it would look like irl. Still, I have made some modifications on this one: https://mc.sendgrid.com/dynamic-templates/d-5123a0ceda2d463db60717dc94005b65/version/2e94b784-4d1a-4cbb-843e-e472c2fcc311/editor

- I think the duration & start should be all in the same sentence
- Now that you've found a solution to make the timezone smaller, maybe we could add them right under the text, and before the Join now

Can you take a look? And then i'll try to add some test data.

**Comment by frenchyrules** [comment]
Timezones have been moved up !
![image](https://user-images.githubusercontent.com/85220905/152517046-530870e6-d813-4d74-a84e-6d053a2dd782.png)

**Comment by cams-goussale** [comment]
Is there a way to reduce the padding on the right & left of the time zones?
I have also added some padding here on the green mark.

I think there is also too many different fonts and colors in this timezone block. It should be fixed

But overall I like it! Here's how it would look with some data. Once we're good with this one we'll have to move on to the other templates.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/93206363/152533571-9e0f748e-5b80-48fd-88b0-f22f1f1692fd.png">

**Comment by frenchyrules** [comment]
I've unified the colors in the timezone box, and reduced the padding by 40px on each side
![image](https://user-images.githubusercontent.com/85220905/152545681-2e22c0f4-e359-4d10-b172-57f75001ffc9.png)

**Comment by cams-goussale** [comment]
hello @frenchyrules, Marie has made some modifications on the template you worked on. Appart from these changes, we have the green light from Business. So could you finish with the 2 remaining templates?


`d-ce3e57248a694cefacad49bc4c820078`
`d-1a7cc9ca846c4ae1b4e8cf8a76455cc5`

Once you're done, let's have a dev review with @stephanie-cascade8 and @phpgeekfr

**Comment by frenchyrules** [comment]
[AM - EVENT - Invitation with credentials](https://mc.sendgrid.com/dynamic-templates/d-ce3e57248a694cefacad49bc4c820078/version/b8cc99e8-02fd-44d1-b485-25f26628579d/editor)
![image](https://user-images.githubusercontent.com/85220905/155117845-4101d023-7066-4e5e-93c3-6cb771fbbffd.png)

**Comment by frenchyrules** [comment]
[https://mc.sendgrid.com/dynamic-templates/d-1a7cc9ca846c4ae1b4e8cf8a76455cc5/version/e9cfca12-2bfd-4de1-8fa4-7584614cd669/editor](url)

**Comment by 2amarkina** [comment]
@phpgeekfr could you please see if the last version is possible? :point_up: 
and have a call with @frenchyrules and @stephanie-cascade8 if needed?

**Comment by frenchyrules** [comment]
**[AM -EVENT - Non private Invitation with credential](https://mc.sendgrid.com/dynamic-templates/d-5123a0ceda2d463db60717dc94005b65/version/5101b6d3-335e-40d2-bd09-33500951aa4b/editor)** 
Template ID: d-5123a0ceda2d463db60717dc94005b65

**[AM - EVENT - Invitation with credentials](https://mc.sendgrid.com/dynamic-templates/d-ce3e57248a694cefacad49bc4c820078/version/f6944d12-6c6d-4840-8989-74e867cecc05/editor)**
Template ID: d-ce3e57248a694cefacad49bc4c820078 

**[AM - EVENT - Invitation without credentials](https://mc.sendgrid.com/dynamic-templates/d-1a7cc9ca846c4ae1b4e8cf8a76455cc5/version/a3fd2b3a-fc0f-4028-8435-7fe30a13bc14/editor)**
Template ID: d-1a7cc9ca846c4ae1b4e8cf8a76455cc5

@phpgeekfr

**Comment by phpgeekfr** [comment]
After a call with @frenchyrules & @stephanie-cascade8  here is what needs to be changed on dev side:

- [ ] Update templates ids with new templates in `libs/utils/src/lib/emails/ids.ts`

- [ ] Change `EventEmailData` interface to something like : 
```
export interface EventEmailData {
  id: string,
  title: string,
  start: string, 
  otherTimezones: {
    centralAmerica: string, // start  plus/minus x hours
    easternAmerica: string, // start  plus/minus x hours
    ...
  },
  end: string,
  duration: string; // eg "3 hours" or "3 days". Minutes should be used for events that last less than an hour, hours for events that last less than 72 hours and days after.
  type: EventTypes,
  viewUrl: string,
  sessionUrl: string,
  accessibility: AccessibilityTypes,
  calendar: AttachmentData
}
```

- [ ] update `getEventEmailData` function to populate this new interface

estimate : half a day

**Comment by Jackseed** [comment]
@Poppe-A underlined that "Eastern Europe (UTC+1)" & "Central Europe (UTC+2)" felt strange; and indeed here [Eastern refers to Greenwich](https://upload.wikimedia.org/wikipedia/commons/8/88/World_Time_Zones_Map.png), which is not a classic reference for our users but more of a time zone thing.
To be easier to understand I recommended changing Eastern Europe for Western Europe, which should be easier to understand for everyone

**Comment by Jackseed** [comment]
I checked emails and they are not all the same:
1. [AM -EVENT - Non private Invitation with credential](https://mc.sendgrid.com/dynamic-templates/d-5123a0ceda2d463db60717dc94005b65/version/2e94b784-4d1a-4cbb-843e-e472c2fcc311/editor)
Template ID: d-5123a0ceda2d463db60717dc94005b65
![image](https://user-images.githubusercontent.com/14964443/171184536-65e72dac-f808-4a5c-aad3-f99feeae4edd.png)

2. [AM - EVENT - Invitation with credentials](https://mc.sendgrid.com/dynamic-templates/d-5123a0ceda2d463db60717dc94005b65/version/2e94b784-4d1a-4cbb-843e-e472c2fcc311/editor)
Template ID: d-ce3e57248a694cefacad49bc4c820078
Same variables
![image](https://user-images.githubusercontent.com/14964443/171185689-a0f0fed5-8bfe-475c-95fb-c49e945117b7.png)

3. [AM - EVENT - Invitation without credentials]([https://mc.sendgrid.com/dynamic-templates/d-1a7cc9ca846c4ae1b4e8cf8a76455cc5/version/e9cfca12-2bfd-4de1-8fa4-7584614cd669/editor](https://mc.sendgrid.com/dynamic-templates/d-1a7cc9ca846c4ae1b4e8cf8a76455cc5/version/a3fd2b3a-fc0f-4028-8435-7fe30a13bc14/editor))
Template ID: d-1a7cc9ca846c4ae1b4e8cf8a76455cc5
This one looks like the only one correctly updated
![image](https://user-images.githubusercontent.com/14964443/171185951-9ef0dd38-8e72-4624-abf8-443d6a77cdfc.png)


Should I change the first 2 emails with the same variables as the 3rd one?
@Poppe-A
