### ISSUE TITLE
Release 3.6 - Profile

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7345]
Issues fixed in this release so please double check them:
- #6996

**Comment by RemcoSimonides** [comment]
Feedback from @2amarkina
OS: Mac BigSur, 11.6
Browser:  Safari 15.0  

# App tested: ARCHIPEL MARKET
_same remarks can be applied to Archipel Content as well_ 

### Buying Preferences (modal)

- [ ]  Follow up the design remarks in [#7326 ](https://app.zenhub.com/workspaces/design---ui-60ab5f96c64ec50014c46754/issues/blockframes/blockframes/7326)

- [ ] In the field "Languages" we have "All languages" (this element we do not find neither in "Languages and versions" filter, nor in Movie Tunnel). I guess that all the languages are ordered alphabetically, but maybe it's possible to put it on the 1st place? ![Снимок экрана 2021-12-08 в 09.57.20.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b389283e-d6dd-42da-b712-15b6b767bc9f)

### Buying Preferences (profile page)
- [ ] To keep the naming consistent, change the name of the tab from "Buyer Preferences" to "Buying Preferences", @maltmayer is it ok for you?

- [ ] As for the modal, remove the titles to have make the make less "heavy" 
![Снимок экрана 2021-12-08 в 10.10.57.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/02faf852-8112-493f-b70b-8443e0879f59)

- [ ] @Jackseed , @cams-goussale , @maltmayer if we use "all languages" logic, maybe need to introduce the "all genres" logic too, or maybe remove the "all languages" ? 

- [ ] Snackbar text proposition instead of "Preferences updated !" : "Buying preferences successfully updated", @maltmayer is ok for you? 
![Снимок экрана 2021-12-08 в 10.20.36.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/fbd760ba-c896-4e7f-9861-092946030252)

### Buying Preferences (modal + page)
- [ ] When a user clicks on "Save" or "Update" CTAs, Marie and Yuki should receive these informations by mail

**Comment by RemcoSimonides** [comment]
Answer from @Jackseed 
> * [ ]  @Jackseed , @cams-goussale , @maltmayer if we use "all languages" logic, maybe need to introduce the "all genres" logic too, or maybe remove the "all languages" ?

- [ ] We should remove "All languages" and keep genre list as it is

> Buying Preferences (modal + page)
 When a user clicks on "Save" or "Update" CTAs, Marie and Yuki should receive these informations by mail

- [ ]  Emails will be too much / out of the scope of this release but indeed we need to be able to extract that data. Ideally we should add the 4 columns to user list in the crm and add these same columns to the csv export.

**Comment by RemcoSimonides** [comment]
> * If you update Cookies > no snack bar showing. Can we add this to the inventory?
Sure

**Comment by 2amarkina** [comment]
### Archipel Content 

**Authentification problem**
- [ ] Again I had this bug when click on "log in", then stayed watching "logging in" and could access only after the second click.... 
![loggin in.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/0e6fca99-50f7-46e2-b3ef-2b2ebda4351c)

**Comment by cams-goussale** [comment]
Wasn't sure where to put that, it's actually an Auth bug:

- [ ] When receiving an Invitation to Sign up from an Org, open the Sign up form, the Intercom disappears. Also the "?" next to Invitation Pass leads to nothing.

**Comment by cams-goussale** [comment]
Good morning @RemcoSimonides, the modale has a different size on AM and AC
On AC, it has a lot of white space on the right whereas on AM it looks good.

AC
![image](https://user-images.githubusercontent.com/93206363/145542983-2b7b646b-7c84-479b-876d-362238200e6e.png)
 
AM
![image](https://user-images.githubusercontent.com/93206363/145544655-cf52745f-917b-4547-8712-e30aaa8ac2b5.png)

**Comment by RemcoSimonides** [comment]
> ### Archipel Content
> **Authentification problem**
> 
> * [ ]  Again I had this bug when click on "log in", then stayed watching "logging in" and could access only after the second click....
>   ![loggin in.gif]

Do you know how to reproduce this? Otherwise I can't do much about it because I don't know what caused it :/

**Comment by 2amarkina** [comment]
> > ### Archipel Content
> > **Authentification problem**
> > 
> > * [ ]   Again I had this bug when click on "log in", then stayed watching "logging in" and could access only after the second click....
> >   ![loggin in.gif]
> 
> Do you know how to reproduce this? Otherwise I can't do much about it because I don't know what caused it :/

Unfortunately I couldn't find the step-by-step way to reproduce it... The only thing that I could distinguish was that I logged out from one account and was logging in with another one.

**Comment by phpgeekfr** [comment]
- [ ] If I go to org page ( for example https://staging.archipelmarket.com/c/o/organization/sLchj1Ib4Cxhwr0ZBW4m/view/org), click on `members` tab  and then click on previous page
 ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/0f93401c-a32d-40ee-8541-d7a1d83f8455)

I cannot leave the "org page" anymore and there is no way to go back to application

**Comment by phpgeekfr** [comment]
>  Unfortunately I couldn't find the step-by-step way to reproduce it... The only thing that I could distinguish was that I logged out from one account and was logging in with another one. 

This bug is described in #5940 but still no fix..

**Comment by phpgeekfr** [comment]
> When receiving an Invitation to Sign up from an Org, open the Sign up form, the Intercom disappears. Also the "?" next to Invitation Pass leads to nothing.

Can't reproduce, the  `?` icon is showing the tooltip and intercom is here (tested on staging.archipelmarket)

**Comment by RemcoSimonides** [comment]
> Wasn't sure where to put that, it's actually an Auth bug:
> 
> * [ ]  When receiving an Invitation to Sign up from an Org, open the Sign up form, the Intercom disappears. Also the "?" next to Invitation Pass leads to nothing.

I was able to reproduce this. For this to happen I had to disable the cookies (or only the cookie for Intercom). Then none of the '?' buttons in the app will work because Intercom is blocked by user settings.

However, I noticed that Intercom is always launched (despite disabled cookies) on the landing page. I couldn't find anything in our code that can trigger this. @Jackseed do you know if there is a setting on Intercom website that cause this? I'm thinking about a welcome message. If yes, then probably we should trigger this welcome message in our code so we can check if the user accepted the cookies first.

**Comment by phpgeekfr** [comment]
> > Wasn't sure where to put that, it's actually an Auth bug:
> > 
> > * [ ]   When receiving an Invitation to Sign up from an Org, open the Sign up form, the Intercom disappears. Also the "?" next to Invitation Pass leads to nothing.
> 
> I was able to reproduce this. For this to happen I had to disable the cookies (or only the cookie for Intercom). Then none of the '?' buttons in the app will work because Intercom is blocked by user settings.
> 
> However, I noticed that Intercom is always launched (despite disabled cookies) on the landing page. I couldn't find anything in our code that can trigger this. @Jackseed do you know if there is a setting on Intercom website that cause this? I'm thinking about a welcome message. If yes, then probably we should trigger this welcome message in our code so we can check if the user accepted the cookies first.

created #7424
