### ISSUE TITLE
Review the logic of "previous page" in tabs

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7362]
Sometimes the use of the previous page can be misleading on the pages where we use tabulation, here are the main ones (but all the marketplace can be taken into account): 
- Film Page, 
- Organization Page, 
- Profile Page. 

**The most painful case we find in Org and Profile pages as  a user has no way to "get out"** 

Example: 
1. User modifies the profile info, then buying preferences, then notifications... well, does a lot of things. 
2. When wants to come back to the platform, needs to pass through a lot of clicks.. 
![come back.gif](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/5fd217ce-af7e-4efe-ad5f-7bf81a96e84b)

Solutions: 
- Introduce a logo to let a user come back to the plateforme (also need to be accurate, as cross-app space) for Org and Profile pages
- Need to provide more accurate way of use of "previous page"

**Comment by Jackseed** [comment]
We already had an issue on this (#6369) but I guess we forgot about the settings. I transfer it directly to sanity
