### ISSUE TITLE
Unit-Test : Create unit test for cloud function 'inviteUsers'

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#7373]
To completely test the invite() function of invitation service we need few additional tests

- [ ] unit-test for `this.functions.httpsCallable('inviteUsers')`
- [ ] Additional test code checking invite()

**Comment by RemcoSimonides** [comment]
Hee Mano, no need to also add the Sanity team label because then the issue will also show up on the Sanity Team board ;) It's enough if it only shows up on your board
