### ISSUE TITLE
Issues on account creation flow

### ISSUE THREAD

**Issue by lsenta** [blockframes/blockframes#738]
- [ ] when a user invitation is validated, they stay on the "no org part" (where they can pick an organization), this should redirect
- [ ] when a user requests to join an organization, the admin won't see the notification until they refresh, this should be updated live
- [ ] when a user is created by invitation (add a mail that does not exists), they can signin without firstname and lastname and the page to fill details won't show up. The page should appear until they filled the required information.
  - [ ] if you refresh once you'll get the page, but a 'no uid' error when you fill the form
  - [ ] if you refresh twice you might be able to fill the form and get in
- [ ] when a user invites another user to their organizatin, the "pending members" page doesn't refresh every time

**Comment by Jackseed** [comment]
Duplicate #707

**Comment by Jackseed** [comment]
I close it since we cut it into pieces.

**Comment by pldespaigne** [comment]
#740 also fix the firstname lastname part
- new user login with email & generated password sent to him by email
- he chose between join/create/search org
- if he click on join, he is redirected to a loading page that wait until the backend function has finalized the joining process
- this page then trigger a reaload that will send the user to the firstname/lastname form
