### ISSUE TITLE
[CATALOG] Negotiation feedbacks

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#7389]
## Utils
Link: https://catalog-blockframes-yonga.web.app

Users
dev+branson-ekp@blockframes.io
dev+arnold-tel@blockframes.io
dev+brendon-htz@blockframes.io

Users with an ongoing negotiation on arkeon collection.
dev+israel-goi@blockframes.io
dev+murray-ldg@blockframes.io

----

## Issues: 
- [ ]

**Comment by 2amarkina** [comment]
**Selection Page**
- [ ] Following [this wireframe ](https://www.figma.com/file/bs1vDcQEjbqqPggOYMpdd6/%5B-Deal-Negotiation-%5D?node-id=461%3A111851) we need to add one more button "Create offer" (main action) in the header and a button "Add Titles" (secondary action) near "Create Offer" button at the bottom of the page. Also, need to center them. 
<img width="1298" alt="Снимок экрана 2021-12-13 в 14 02 32" src="https://user-images.githubusercontent.com/55499036/145817454-7a629df5-d3f9-4124-bb41-c14fa4fa0efb.png">

<img width="618" alt="Снимок экрана 2021-12-13 в 14 04 19" src="https://user-images.githubusercontent.com/55499036/145817615-01795320-6f72-4c69-a6d4-9cf88d9f37dd.png">

**Buyer's Platform**
- [ ] When offer is created and there is a price entered in price field, we need to show this price on the Offer Page. In this example we see that there is a price of 10000€ for a title and it should appear on the Contract page. 

![Запись экрана 2021-12-13 в 14 11 18](https://user-images.githubusercontent.com/55499036/145819017-eaf79ba8-4708-4886-acb6-26c47a3130b2.gif)

- [ ] The Asking price appears only if the field is = to 0 or if there is nothing entered. Also, on the Contract Page the the text should be just "Asking Price requested", with no "1"
<img width="1355" alt="Снимок экрана 2021-12-13 в 14 15 48" src="https://user-images.githubusercontent.com/55499036/145819325-80a15037-b058-44a6-97d2-0ae8bee675b8.png">

- [ ] The price, if it is entered should also be shown in the the table on the Offer page 
![Запись экрана 2021-12-13 в 14 19 58](https://user-images.githubusercontent.com/55499036/145820053-958ebfb1-3aa8-42a3-9157-df1f3d88a15f.gif)

- [ ] The Buyer should see the details of each contract (media, territories etc.), so there is Rights Card missing 
<img width="1322" alt="Снимок экрана 2021-12-13 в 14 23 21" src="https://user-images.githubusercontent.com/55499036/145820408-d5ab49bf-0376-45c0-846f-add90a8dc788.png">


**Seller's Dashboard** 

- [ ] On the Seller's Dashboard / Contract Page the button "See standard terms" should be in grey color (# 454e5d)
<img width="1088" alt="Снимок экрана 2021-12-13 в 11 37 41" src="https://user-images.githubusercontent.com/55499036/145816231-96cc4685-290f-4aeb-92e7-c2ee540a6928.png">

- [ ] On the Seller's Dashboard / Contract Page the button "See standard terms" should be opened in a new tab
<img width="1101" alt="standard terms" src="https://user-images.githubusercontent.com/55499036/145816292-9ce31b3c-addd-418d-b06b-a7522178399a.png">

- [ ] On the Seller's Dashboard / Contract Page / Negotiation 

- [ ] When Seller has just received information that there was his title inside a package, then it should go to "New". If Sellers starts to "react" (accepts, negotiates) then -> negotiating, if declines, then -> declined. 
<img width="1080" alt="Снимок экрана 2021-12-13 в 14 32 16" src="https://user-images.githubusercontent.com/55499036/145821773-aa45baa8-0df4-4f5d-95b1-ac004d75a221.png">

- [ ] On the Contract Page the Seller should be able to "Accept" or "Negotiate"  + we need to show the Rights Card below
<img width="1078" alt="Снимок экрана 2021-12-13 в 14 34 39" src="https://user-images.githubusercontent.com/55499036/145822005-5f96c6c6-e5a4-4ddd-aedd-121acafc8f2b.png">

- [ ] Inside the negotiation page, we need to change the wording "Add" by "Validate" 
<img width="1093" alt="Снимок экрана 2021-12-13 в 14 36 50" src="https://user-images.githubusercontent.com/55499036/145822355-df091681-450d-4b78-87cd-c56a935554ea.png">

- [ ] Here the edit button should be changed by the "negotiate" one. check it with @stephanie-cascade8 . We discussed a lot with @Jackseed and @maltmayer before and the best one that was chosen was that one 
button: <img width="218" alt="Снимок экрана 2021-12-13 в 14 40 40" src="https://user-images.githubusercontent.com/55499036/145822836-e81d7228-dffa-40e6-94c7-4fb00bb65fb2.png">

where to put 
<img width="1073" alt="Снимок экрана 2021-12-13 в 14 37 55" src="https://user-images.githubusercontent.com/55499036/145822892-258c088d-ce68-4438-8074-c94bd2ffdd7a.png">

I need to precise that it should be changed only in the negotiation process, so only in the edit state of contract

- [ ] When click on decline button (always on the Seller's side) we need to have the select and the modal, see the example below. The select should contain the following and we should leave a user an opportunity to choose the following: The offer is not satisfactory, The Title is not available, Other) 
<img width="651" alt="Снимок экрана 2021-12-13 в 14 46 27" src="https://user-images.githubusercontent.com/55499036/145823670-ebbb6a4b-1d4b-4d81-ab2b-eba44013a9a7.png">

**Comment by cams-goussale** [comment]
- [ ] For the offer on Arkeo Collection (the initial one done by @yspringfield), price was in € for seller and $ for buyer. Should be the same currency for both
- [ ] After a tentative to Negotiate the contract of Arkeo Collection (on Seller's side), we don't receive the changes on Buyer's side. So we can't continue testing the flow. _[We changed price to 700€ and added 1 media to the Rigths card]_
- [ ] The notifications should be changed:

- Buyer's notifications to redirect to Offer view (currently it leads to /Dashboard, which is weird)
- Seller's notifications to redirect to Contract view (currently it leads to Dashboard /Movie view)

**Comment by cams-goussale** [comment]
- [ ] I feel the _Status_ and _Negotiation stage_ are messy and need some clarification. Maybe @2amarkina we should share a [summary ](https://docs.google.com/spreadsheets/d/14Z7gVA_6SNzTtDXt1911eiLLEtbb1xz2NL0oUQCbNCg/edit#gid=1193701986)of:
What is the status + negotiation stage for each user at each step of the nego
When is a change of status triggered
What are the different status depending on the view (Contract / Offer)

Here are some errors I saw which led me to think this is not clear yet:
- Buyer just created an offer. Status is the offer is NEW for a second and immediately changes to IN NEGOTIATION.
- Buyer just created an offer. Status of the contract is NEGOTIATING whereas should be PENDING first. Same for Seller: status should be PENDING first.
- Buyer has submitted a new Negotiation. It's now the Seller's turn to answer. The Negotiation stage should change to "Waiting for [Seller's Orgname] answer" but unless it stays the same as before (Buyer's Orgname).

_______________________________________________________________________________

Other bugs/doubts:
- [ ] Edit button on Rights card before should lead to anchored map

https://user-images.githubusercontent.com/93206363/146367461-60217f0f-8171-439a-a05b-93d4078b4b1d.mp4


- [ ] Seems like all snackars are staying permanently on the pages. ("Your counter offer has been sent", "You accepted contract for [TitleName]"). Should disappear after 6 sec.

- [ ] In the tables view, the price displayed is always the initial price. Is this what we want @Jackseed ? if yes, let's change the column name to "Initial Price" @2amarkina

- [ ] As a seller having an offer on 1 of my titles, why is the Licensor's name another org than mine?
![image](https://user-images.githubusercontent.com/93206363/146363515-6de98fdb-b384-41e2-aafc-caa5b1a02b2e.png)

**Comment by cams-goussale** [comment]
Dedicated issue for Snackbars #7446

**Comment by cams-goussale** [comment]
Dedicated issue for Tables and Notifications #7119

**Comment by cams-goussale** [comment]
- [ ] Enter in the Contract view of a Declined contract. The Status is incorrect and the rights card is missing
![image](https://user-images.githubusercontent.com/93206363/146803549-bccbb9bd-e9f3-4b94-bdf8-0890e5a8c1c0.png)

**Comment by 2amarkina** [comment]
To avoid the confusion with the come back arrows, the last decision is the following: 

- [ ]  Do not show "come back arrows" on the top of the page (as user can always come back to the list clicking on the sidenav menu) 

- [ ]  But precise on the Marketplace > Offer > Contract page the arrow that leads a user to the Contract's list. Maybe discuss the wording with business team, but explanation text should be there
![Deals](https://user-images.githubusercontent.com/55499036/146909624-920c8c43-f0c4-463e-ba92-bfb706c6c870.png)

**Comment by cams-goussale** [comment]
- [ ] When Seller negotiates and modifies Dates on a Contract, Buyer receives completely different dates. @yspringfield we suggest that you keep 2 columns all the time to simplify and minimize errors: 1 column for Terms Start Date, 1 column for Terms end date

See the Video with date changes due to Seller's negotiation

https://user-images.githubusercontent.com/93206363/146970533-8e7db83f-bc6d-4a3f-b902-8dac91aa5209.mp4


The reception on the Buyer's side:
![image](https://user-images.githubusercontent.com/93206363/146970592-734adfa6-6438-43c9-ad47-592ac44cfb13.png)

**Comment by cams-goussale** [comment]
- [ ] When negotiating a Contract, there is a jump on the Edit button Rights card

https://user-images.githubusercontent.com/93206363/147124608-7287b8d1-27d0-4619-b54a-5341c21ae43e.mp4

**Comment by cams-goussale** [comment]
- [ ] In CRM Offer view, we are missing the Rejected / Declined titles

![image](https://user-images.githubusercontent.com/93206363/147129479-297992a2-257c-4da6-a6fb-d8d491d4a066.png)

**Comment by cams-goussale** [comment]
@2amarkina do you know if we need the field "Title price suggested" in CRM? What does it mean and what is it for?
FYI this is the view of a Contract inside an Offer in CRM.

![image](https://user-images.githubusercontent.com/93206363/147129886-4d760dbe-b64d-40d9-b6c4-c0e1cda4ae18.png)

**Comment by cams-goussale** [comment]
- [ ] When entering a Rights card of a Contract inside an Offer in CRM, the fields are empty

![image](https://user-images.githubusercontent.com/93206363/147130139-7e88527e-bdce-4b9d-a461-a3f8595b16c9.png)

![image](https://user-images.githubusercontent.com/93206363/147130066-ac1adf69-f286-4611-b001-061d105160cd.png)

**Comment by 2amarkina** [comment]
> @2amarkina do you know if we need the field "Title price suggested" in CRM? What does it mean and what is it for? FYI this is the view of a Contract inside an Offer in CRM.
> 
> ![image](https://user-images.githubusercontent.com/93206363/147129886-4d760dbe-b64d-40d9-b6c4-c0e1cda4ae18.png)

We used this field when the negotiation processes was not designed. Like that admin could talk irl with a Seller and then enter this price that Seller proposed. Now maybe we could get rid of it.

**Comment by cams-goussale** [comment]
- [ ] Buyer's offer view seems to be buggy. Table view is now missing almost all parameters, and Offer page doesn't show the Contracts.

In this example, I had purchased 2 titles with several Rights cards.
https://user-images.githubusercontent.com/93206363/147264905-f5d63cb7-ab16-4393-af6c-ffbfd9546ae8.mp4

**Comment by cams-goussale** [comment]
- [ ] Seller's contract view is now missing the action buttons

In this example, it is the first time Seller recieves an offer.
![image](https://user-images.githubusercontent.com/93206363/147265173-17702465-2efe-412a-970c-695bd383a0e9.png)

**Comment by yspringfield** [comment]
> https://github.com/blockframes/blockframes/issues/7389#issuecomment-1000396199

> Seller's contract view is now missing the action buttons

These problems actually don't exist. Reason being you tested on code that debugging. I just finished the debugging. Now if you test, you won't have the previous issues. Sorry for not notifying you not to test.

**Comment by cams-goussale** [comment]
- [ ] Currency in the table view should be the same as in the contract view

https://user-images.githubusercontent.com/93206363/147481533-992b0b7d-6892-4241-96da-0a4c6c09d365.mp4

**Comment by cams-goussale** [comment]
- [ ] When entering the Edit view of a Rights cards, the parameters selected should be validated with the availabilities of the title.

In the video below, a Buyer negotiates a contract. He edits the Rights card and adds France territory. He validates and submits the counter offer. 

Then, from the Seller perspective, we can see in "My avails" that this title doesn't have avails  in France for the media / duration / exclusivity requested. The seller receives the counter offer. He can accept this counter offer, even though he doesn't have rights for France, for the requested parameters.

This is an issue, because the system allows us to sell a title which is already sold. The solution is, when negotiating and when clicking on "Validate", we should check that the new rights selected (media/duration/territories/exclusivity) are indeed available (= in the seller's avails list). If not available, show a warning and disable the "Submit" button.

https://user-images.githubusercontent.com/93206363/147482585-c9b65133-2be8-4b33-aacb-56bc248fd2b1.mp4

**Comment by cams-goussale** [comment]
Dedicated issue for CRM review #7482

**Comment by cams-goussale** [comment]
- [ ] As a buyer, if it's not my turn to negotiate, I shouldn't have the option here. Even if I left no price, I should only see "Asking Price requested"

![image](https://user-images.githubusercontent.com/93206363/147486902-16cea995-ad69-4bce-a826-80ab54a88ecd.png)

**Comment by cams-goussale** [comment]
- [ ] When a buyer is adding a title to his bucket, he can add Versions. He can select a specific language without clicking on the type of version he wants (subs, dubs, cc) and then add the title to his selection. But when the Seller receives this offer, he is forced to select a version type. I think we should make this field mandatory to the Buyer, at the beginning.

https://user-images.githubusercontent.com/93206363/147487447-be4555a1-9f8e-4cb5-9dcd-622ef52118f2.mp4

**Comment by cams-goussale** [comment]
- [ ] The mandatory field (Dubs, Subs, CC) [explained above](https://github.com/blockframes/blockframes/issues/7389#issuecomment-1001630671) 👆 works for the 1st Rights card created, but not the following ones.



https://user-images.githubusercontent.com/93206363/147582497-3391b752-fd3e-498d-b863-e7ea50b40b81.mp4

**Comment by cams-goussale** [comment]
- [ ] In the page /c/o/marketplace/selection, when managing and editing holdbacks, there is a bug on the table view. If there is 2 holdbacks selected, when modifying the 2nd one, it overwrites the table with empty data.

Maybe we can leave this bug on hold, as there is already an open issue here #7248

https://user-images.githubusercontent.com/93206363/147583210-a68a3b3c-e934-4b8b-ba52-2953ac767796.mp4

**Comment by cams-goussale** [comment]
- [ ] Page: c/o/marketplace/offer
When many titles are added to the Offer, text overlaps on the following column. According to the [inventory](https://docs.google.com/spreadsheets/d/1Et6lZpTcdkJ6nMHmIsTaVD_yObp6GGbvoqUHEB-o-iM/edit#gid=1085447321), the rule should be:

> 50 characters, then ""..."" and clickable cell

![image](https://user-images.githubusercontent.com/93206363/147642245-bf8aee2f-513e-4d5c-a562-97de9c901ff1.png)

**Comment by cams-goussale** [comment]
- [ ] When a contract is ACCEPTED, termIds are created in db. However, when filtering in db > terms, the id doesn't correspond to the termId.

Data in Contracts
![image](https://user-images.githubusercontent.com/93206363/147664852-06ce7243-ab38-463e-b713-4754e4d9153a.png)

Data in Terms
![image](https://user-images.githubusercontent.com/93206363/147664931-64ff2ae9-a204-426e-bd47-03a6d60ea72f.png)

**Comment by cams-goussale** [comment]
To be discussed with @2amarkina @Jackseed the Contract statuses available for the user are:
NEW
IN NEGOTIATION
ACCEPTED
DECLINED

In CRM, we have the following ones:
NEW
NEGOTIATING
ACCEPTED
DECLINED
ARCHIVED

Could we align both sides to avoid confusion? Both for the wording, and the options available. Do we still need "Archived"?

**Comment by cams-goussale** [comment]
- [ ] When selecting Versions, Subs & Dubs are reversed.
Subtitles -> Subs
Dubbings -> Dubs

https://user-images.githubusercontent.com/93206363/147678347-cdc83a85-b4be-4e0a-bf88-1de0c2ee64cb.mp4

**Comment by cams-goussale** [comment]
- [ ] For the Rejected contracts, the currency should be the same in the table view and inside the contract page

https://user-images.githubusercontent.com/93206363/148064910-f95d1ecc-9b16-47c1-b37f-78097b88aa75.mp4

**Comment by cams-goussale** [comment]
- [ ] The link to go from Notifications to the Offer pages seem buggy.

https://user-images.githubusercontent.com/93206363/149737942-6788e39c-1d23-4470-8986-2052e9093b15.mp4
