### ISSUE TITLE
When a user is added to an org, clear other invitations

### ISSUE THREAD

**Issue by laurentsenta** [blockframes/blockframes#739]
users can have only one org, clear other invites and block orgId updates on users

**Comment by ioaNikas** [comment]
:fire: :fire: :fire: We could have multi-organization back again soon.

**Comment by fritzschoff** [comment]
@phpgeekfr is this still valid?

**Comment by phpgeekfr** [comment]
Yeah I think. Need to check

**Comment by pldespaigne** [comment]
ping @phpgeekfr @fritzschoff

**Comment by phpgeekfr** [comment]
I think this is still the case, need  to be tested

**Comment by Jackseed** [comment]
I just tested to invite the same new user on 2 orgs:
- I received the first invitation email but not the 2nd
- When I connected with the creds received I was linked to the 1st org
- I had a pending invitation for the 2nd org that I could accept or decline
- I accepted and ended up being in the 2 orgs
I don't want to mess with the invitation flow as it's robust and this is an edge case. I think that the simplest way to go here is to block org invitations to users that already exist with a snackbar message: "This user is already attached to another organization."

If users want to change their org they should then come to us so we change it manually on a case by case basis

**Comment by phpgeekfr** [comment]
@Mussuranae can you confirm that #2638 is solving this issues since it will not be possible anymore to invite the same person to joinOrg many times?

**Comment by Mussuranae** [comment]
Yes, my PR will limit the number of invitation to join an org at one per email. So we won't have this case anymore.

**Comment by pldespaigne** [comment]
according to @phpgeekfr there is still one thing to do before we can close this
