### ISSUE TITLE
Invitation issue in case of invite to event and then invite to org 

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7392]
if I invite a new user to an event and then invite the same user to my org, he will receive invitation to event email but not the org one. I'm not sure this is a big issue, because user will receive his credentials in the event email, and if he decide to create an account, form will be filled with org data coming from invitation

created from https://github.com/blockframes/blockframes/issues/7349#issuecomment-990938579

**Comment by cams-goussale** [comment]
Adding another issue: if i invite a user to join my org and then invite the same user to an event, he will receive
- 1 joinOrg invitation (normal)
- 2 event invitations: 1 with Join screening, 1 with Answer invitation (not normal)

**Comment by phpgeekfr** [comment]
> Adding another issue: if i invite a user to join my org and then invite the same user to an event, he will receive
> 
>     * 1 joinOrg invitation (normal)
> 
>     * 2 event invitations: 1 with Join screening, 1 with Answer invitation (not normal)

@cams-goussale this as been solved here already https://github.com/blockframes/blockframes/issues/7349#issuecomment-990894752

**Comment by RemcoSimonides** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dev---Sanity-Team-5f6b0067599064680cd2c617/issues/blockframes/blockframes/7392?planning-poker) with ZenHub @phpgeekfr

**Comment by cams-goussale** [comment]
After discussion with @Jackseed we think this is the expected behavior. We prevent 1 user of receiving 2 invitations (hence why you receive only the invitation for the event). And then when signing up, you already have the org prefilled, which is nice. I'll close this issue
