### ISSUE TITLE
when we create an invitation, the userDoc doesn't exist directly, so the doc is not found

### ISSUE THREAD

**Issue by lsenta** [blockframes/blockframes#740]
I have no context on that one, comes from a refactoring on https://github.com/blockframes/blockframes/pull/732#discussion_r312456999

**Comment by ioaNikas** [comment]
We use the uid from `getOrCreateUserByMail` which returns the uid from Authentication and not `users` collection. A function react to this event and create a document of this user in the database.

Problem is that the invitation is generated from the client, which is faster, and try to load a the user doc that doesn't exists yet.
