### ISSUE TITLE
Removing TunnelService crashes CRM and CMS build

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7414]
`import { TunnelService } from '@blockframes/ui/tunnel';` isn't used on `libs/organization/src/lib/organization/pages/view/view.component.ts` but CRM and CMS build crash if it's removed.

**Comment by cams-goussale** [comment]
@RemcoSimonides could we add this to the epic #6456 ?

**Comment by phpgeekfr** [comment]
already solved
