### ISSUE TITLE
Choose empty state in directors category

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7418]
- [ ] In the Movie Tunnel > Main Information > **Director's Category** introduce a possibility to choose nothing in dropdown. 
![Снимок экрана 2021-12-14 в 17.36.40.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/434609a2-1e2e-4e47-8d6c-91653820da8b)

_Originally posted by @2amarkina in https://github.com/blockframes/blockframes/issues/7347#issuecomment-993728916_

**Comment by RemcoSimonides** [comment]
Placeholder disappears after selection the empty value though; is that ok?
https://user-images.githubusercontent.com/27687382/147082687-3980640c-b4a1-4341-93ff-7d6596989bdb.mp4

**Comment by 2amarkina** [comment]
That's ok!
