### ISSUE TITLE
Main app : "/layout/o/appName" redirect to welcome page from auth routes

### ISSUE THREAD

**Issue by ioaNikas** [blockframes/blockframes#742]
We force route with  "/layout/o/appName/movie/list" until we find a solution to this problem.

**Comment by Jackseed** [comment]
@GrandSchtroumpf any advice on this ?

**Comment by GrandSchtroumpf** [comment]
I need to check the code. I might encounter this issue when I'll do the main app. Thanks for the reference to the issue, I'll keep it in mind

**Comment by Jackseed** [comment]
not relevant anymore
