### ISSUE TITLE
Intercom/cookies issue on Sign Up

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7424]
When receiving an Invitation to Sign up from an Org, open the Sign up form, the Intercom disappears. Also the "?" next to Invitation Pass leads to nothing.

_Originally posted by @cams-goussale in https://github.com/blockframes/blockframes/issues/7345#issuecomment-989758988_

Remco:
For this to happen I had to disable the cookies (or only the cookie for Intercom). Then none of the '?' buttons in the app will work because Intercom is blocked by user settings.

However, I noticed that Intercom is always launched (despite disabled cookies) on the landing page. I couldn't find anything in our code that can trigger this. @Jackseed do you know if there is a setting on Intercom website that cause this? I'm thinking about a welcome message. If yes, then probably we should trigger this welcome message in our code so we can check if the user accepted the cookies first.

**Comment by Jackseed** [comment]
@RemcoSimonides I honestly have no idea.. I gave access to intercom to dev group inside 1password if you or the dev working on this issue wants to have a look (please don't open or answer any unread messages :) )
