### ISSUE TITLE
Remove "First invitation" from the navbar for AC only

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7426]
Also interesting to check with devs: could we remove "First invitation" from the navbar for AC only?

_Originally posted by @Jackseed in https://github.com/blockframes/blockframes/issues/6802#issuecomment-954872467_

**Comment by RemcoSimonides** [comment]
We can but of course we prefer to keep it the same for all apps. So why not remove it from all the apps? Or maybe we should wait until we have analytics about clicks on buttons before we change this. If I remember correctly, the heatmap from Yandex showed a lot more clicks on 'Log in' and 'Sign up' than 'First Invitation'

**Comment by Jackseed** [comment]
@2amarkina what do you think?
cc @cams-goussale

**Comment by 2amarkina** [comment]
If look on the data from the 1 september till today we can see that the 'First invitation' is pretty used on Market. Not as much as 'Sign Up', but still !  
<img width="529" alt="Снимок экрана 2021-12-17 в 17 22 57" src="https://user-images.githubusercontent.com/55499036/146575976-6e919bf9-ed6a-44c7-b96c-005990c5be63.png">


Surprisingly, the "First Invitation" is also quite used on Content!
<img width="529" alt="Снимок экрана 2021-12-17 в 17 26 40" src="https://user-images.githubusercontent.com/55499036/146576483-e039acc3-9b9f-4d87-a4ba-a3a6c46e9d45.png">

**Comment by Jackseed** [comment]
Hum seeing that it's clicked on Content is a bit disturbing, to me it shows that people click on it because... it's a button. But does it fill its main purpose? 
(thinking out load but don't have a clear answer yet)

**Comment by cams-goussale** [comment]
So Marie thinks this First invitation button is necessary on AM. It's a real helper for users entering the app for the first time, who tend to be confused between login and sign up.

It's not completely irrelevant on AC either, where you can be invited to Join an org for ex.

**Comment by RemcoSimonides** [comment]
So do we keep it or remove it from AC? ^^

**Comment by Jackseed** [comment]
Yep let's keep it then I close this :)
