### ISSUE TITLE
Buyer/Seller interactions

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7431]
### Description

One of the outcome of the strategic meeting is to create more interactions between buyers and sellers. This is a first step to reach our final objective: use these interactions to generate qualitative data for sellers (this part will be in a future issue).

### What's new
We want to show these interaction buttons for the Berlin Film Festival in February 2022. With this deadline in mind, let's focus first on 2 interactions for Archipel Market:

**1) Ask for a Screener**
This has already been described in this issue #7078 

**2) Make an offer**
The user has seen as Screening and then wants to make an offer to the Buyer. The action should be simple for the moment (no territory or price consideration).

### Flows to think over

**Where do we place those 2 buttons and what hierarchy should exist between them?**

_Ask for a screening_
- Title page main CTA (banner and hero)
- Title list, poster action (same as add to selection on catalog)
- Closed event view
- Seller page banner CTA & screening schedule

_Make an offer_
- During the screening session
- After the screening session (=Closed event view)
- Title page main CTA (banner and hero)
- Title list, poster action (same as add to selection on catalog)

**Notification and Email flow**

- After the user went to a screening, they receive a "What did you think of this screening? Make an offer" email
- If user was invited but didn't go to the screening, they receive a "You missed it? No worries, ask for a screening" email
- The seller receives a screening request in his notifications
- The seller receives an offer request in his notifications

**How do we highlight these features after the release** (animated icones, learn how it works)
See Figma example or Slack example

https://user-images.githubusercontent.com/93206363/146339806-d00edd81-55e8-4015-b1a4-5d1822ef7fa0.mp4

**Comment by 2amarkina** [comment]
[Work in progress is here](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=0%3A1)

**Comment by cams-goussale** [comment]
Created 2 template IDs for
[Ask for a screening](https://mc.sendgrid.com/dynamic-templates/d-a03d096d252f4c27a500ff16d13f1795/version/eee02836-bacd-4d06-96ac-e43e5bb0ccf9/editor) - d-a03d096d252f4c27a500ff16d13f1795
[Make an offer](https://mc.sendgrid.com/dynamic-templates/d-ebf41f86fa124978a15b27bec75faf09/version/bd9d9d34-404c-4464-a4da-6a04818448b8/editor) - d-ebf41f86fa124978a15b27bec75faf09

**Comment by 2amarkina** [comment]
All the wireframes can be found [here](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=0%3A1). 

### Homepage
- [ ] Add an icon to represent screening in app-specific zone of a movie card (all types of movie cards are concerned)(can use the same as on wireframes or propose a new one in UI); 
![Снимок экрана 2021-12-23 в 15.57.35.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/868055ae-89a0-4579-98fd-ca746fac2fda)

- [ ] When a user hovers this icon show the tooltip with the following text "Ask for a Screening" 

- [ ] When user clicks on the icon, then snackbars appears for 5 seconds with the following text: Request for a Screening successfully sent. 

- [ ] Also, when an icon has been clicked and screening has been already requested, then change the color of an icon to "disabled". 

- [ ] Also, when an icon has been clicked and screening has been already requested, then show the following text on hover "Screening Requested". 

- [ ] As there are modifications on the homepage, include this one: in Hero section replace an image of "down" by a button with the text symbol "↓"
_from this_
 ![Снимок экрана 2021-12-23 в 15.59.07.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/76310168-5c87-4472-8a94-ebac708933fe)

_to this_
![Снимок экрана 2021-12-23 в 16.02.27.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/8f7a9d62-a3d5-4764-aa80-a677b52767eb)

**Homepage wireframe** 
![Снимок экрана 2021-12-23 в 16.10.54.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/c5e1af81-d8f8-42bd-a364-e67ed41b0ac1)

**Comment by 2amarkina** [comment]
### Titles page
- [ ]  Add an icon to represent screening in app-specific zone of a movie card
![Снимок экрана 2021-12-23 в 16.12.09.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/80353651-6fb7-4058-8720-638825b03004)

**Comment by 2amarkina** [comment]
### Film page / Marketplace
**Visualisation of New Banner**
- [ ] Introduce the new version of Film Banner presented in [this issue ](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/7333). Follow [the notion documentation](https://www.notion.so/cascade8/WIP-Banner-Film-Page-WIP-b1464efef5bb46958cd84fc361630268) and verify with the devs the upcoming modifications (app-spcific zones, actions etc.) In documentation the main tech points to review are highlighted with red color. 
![Снимок экрана 2021-12-23 в 16.15.15.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/ad0c0565-60dc-4ca0-be45-b1ed557faaaa)

**Behavior on Banner**
- [ ] When a user clicks on "Ask for a Screening" button, a snackbar appears for 5 seconds with the following text: Request for a Screening successfully sent. 

- [ ] If a button "Ask for a screening" has been clicked and screening has been already requested, then change the color of the CTA to "disabled" one. 

- [ ] If a button "Ask for a screening" has been clicked and screening has been already requested, then change the text to "Screening Requested".  

**Hero section** 
- [ ] If no ongoing screening, but with upcoming screenings, then show "Make an Offer" button below "Register for the Session" 
![Снимок экрана 2021-12-23 в 16.15.45.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/56c255af-677c-4d38-aaf3-a0e5be506211)

- [ ] If no ongoing screenings, if no upcoming screenings, then change the "Contact seller" button by "Ask for a screening" CTA and add the "Make an offer" button under it. 
 ![Снимок экрана 2021-12-23 в 16.15.45.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/0c8333f7-fffb-43db-ba56-5bda527d12f4)

- [ ] When a user clicks on "Ask for Screening" CTA, then a snackbar appears for 5 seconds with the following text: Request for a Screening successfully sent.

- [ ] Also, when a CTA "Ask for a screening" has been clicked and screening has been already requested, then change the color of the CTA to "disabled" one. 

- [ ] Also, when a CTA "Ask for a screening" has been clicked and screening has been already requested, then change the CTA's text to "Screening Requested". 

- [ ] If screening ongoing and no upcoming screenings, then add "Make an Offer" below "Access event" CTA.

**Comment by 2amarkina** [comment]
### Make an Offer Behavior 

:bell: **Phare Version (if possible)**
- [ ] When user clicks on "Make an Offer" button, then a modal appears. In this modal Buyer can precise the details of his offer proposition. 
![Снимок экрана 2021-12-23 в 16.29.47.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1e35a1ae-08b7-45cb-9253-7fb9a0d5074a)

- [ ] When user clicks on "Send Offer Proposition" then show a snackbar "Offer successfully sent." for 4 seconds. 

- [ ] When user clicks on "Send Offer Proposition" then there is a mail with the information from the modal, that should be sent to the Seller's organization, who is the owner of the title in question. 

@cams-goussale do you think we need to sent a summary mail to buyer too? (subject: "Recap of your Offer for the [ Title's name ] )

:bell: **If the phare version is not possible**
- [ ] Then, instead of having a modal, keep up with the snackbar only.

**Comment by 2amarkina** [comment]
### Seller's page 
- [ ] In the line-up of the Seller we show an "Ask for a Screening" icon in the app-specific zone. 
![Снимок экрана 2021-12-23 в 16.43.04.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/682fc298-cbe1-4e7d-82fc-cd81c91884fa)

**Comment by 2amarkina** [comment]
### Closed screening session 

- [ ] When an event with the type "screening" or the type "slate presentation" is closed, then introduce two CTAs : main CTA "Ask for a Screening" and secondary CTA "Make an Offer". 

- [ ] The behavior of these two buttons should remain the same as described above :point_up:

**Comment by 2amarkina** [comment]
### Ongoing Screening Session 
- [ ] Introduce a CTA "Make an Offer" below the video player. 
- [ ] The behavior of this CTA remains the same as described above. 

![Снимок экрана 2021-12-23 в 16.49.47.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/dcaf6e55-4d4a-4211-b027-e48c6b6ad028)

**Comment by cams-goussale** [comment]
> @cams-goussale do you think we need to sent a summary mail to buyer too? (subject: "Recap of your Offer for the [ Title's name ] )

Yes it would be great indeed. Email + Notif ideally

**Comment by 2amarkina** [comment]
### Screening List & Screening Schedule on the Seller's Page

- [ ] Introduce a button "Make an Offer" on the right side of Screening and at the bottom. 

- [ ] Behavior is the same as described above. 

![Снимок экрана 2021-12-23 в 16.54.11.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/530b1685-cb5a-4934-9f0c-cbe33ac883d3)

**Comment by 2amarkina** [comment]
### Marketplace notifications

**Ask for a Screening** 
@cams-goussale Do we really need it as we already have a snackbar? Maybe can be useful to keep as a history (if buyer doesn't click on "Mark all as read" :see_no_evil:)

- [ ] Text proposition: "Your request for a Screening of  [ Title's Name ] is successfully sent". Action: Leads to the Film Page on the Marketplace 

**Make an Offer**
- [ ] Text proposition: "Your Offer for [ Title's name ] is successfully sent". Action: Leads to the Film Page on the Marketplace. 
![Desktop - 5.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/21bc9543-fd4c-46ae-ae98-97e49f8d3b97)

**Comment by cams-goussale** [comment]
Yes let's keep also the Notification for Buyer who requested a Screening.
Here's the summary of all [Emails & Notifications](https://docs.google.com/spreadsheets/d/1Xv3HJjYEM-kTnACnu-uHCmlbQ_KXlXMMExMY2JoURHA/edit#gid=0).

**Comment by 2amarkina** [comment]
### Dashboard notifications

- [ ] If there was a request of a Screening, the show the following text: "[ Buyer’s Name ] requested a Screening for [ Title’s Name ]." 


**More details icon**
- [ ] :bell: If possible, then redirect a user to the Screening Form creation page. The following elements should be filled in by default: 
- Event type set to Screening, 
- Time of the event set to the actual time for the start, 
- The Title concerned should be preselected in the field "Select the title to display",  
- The "Invite Guests" field should be pre-filled with a Buyer's email address, _but should not be sent_ (!important)
![Снимок экрана 2021-12-23 в 17.37.57.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/90a2d91e-47eb-435c-b300-e6a68f33c61e)
@cams-goussale the eventual problem here might happen if we want the Slate Presentations to be reproduced as Screenings, as in such case we need to choose the other "Event type". 

- [ ] if the behavior presented above is not possible, then just lead a user to the Calendar page (Dashboard side). 


:bell: The notifications' visualisation of "Make an offer" depends a lot on what is possible to do on the Marketplace side. 

**If we can introduce a modal, then**
- [ ] show the following text: "[ Buyer’s Name ] made an offer for [ Title’s Name ]. Please consult your mails." Actions: "More details" button opens the user’s mail client, not the new message, but the default state with incoming mails. 
![Снимок экрана 2021-12-23 в 17.51.07.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/6a3be21f-360b-4220-8924-8bc47a371c00)

**If we can't introduce a modal, then**
- [ ] use the following text "[ Buyer’s Name ] made an offer for [ Title’s Name ]. " Actions "More details" opens the user’s mail client with the new message, the buyer’s mail is pre-filled (if buyer has no email, then use organization mail)
![Снимок экрана 2021-12-23 в 17.50.56.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/4d41e4a7-da32-4d24-be99-6053709a15de)

**Comment by 2amarkina** [comment]
Ready for UI and the versions proposed should be checked on the devs side

**Comment by cams-goussale** [comment]
It'd be nice if we could also include an animation on this new action the first time the user enters on the homepage. Something similar to what Figma did in the video above ☝️. If you don't have time for this @2amarkina maybe @frenchyrules could take a look at it?

**Comment by 2amarkina** [comment]
**Animation ideas:** 
1. Introduce animation for the icon "Ask for Screening". 
The behavior: the animation should appear only for the users who connect to Marketplace for the first time (for both users Sellers and Buyers). 
![Снимок экрана 2021-12-24 в 15.04.17.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/f3134d7c-64e6-4c0c-a267-b545c10f3989)

2. Introduce animation for the "Make an Offer" button on the screening list. 
The behavior: the animation should appear only for the users who connect to Marketplace for the first time (for both users Sellers and Buyers). 

![Снимок экрана 2021-12-24 в 15.04.50.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9462af9b-0ecb-4977-8fca-d32191aa659d)

**Comment by cams-goussale** [comment]
hello @2amarkina @frenchyrules @stephanie-cascade8 after discussing with @maltmayer we think the best wording for the 2 interactions should be:

- "Request Asking Price" instead of "Make an offer"
- "Ask for a Screening" (no change)

Let's reflect this in wireframes + zeplin

**Comment by frenchyrules** [comment]
Figma wireframes updated.
Starting work on Sketch [here](https://sketch.com/s/3e7b1177-afab-4f3f-8547-0779c035c4d3)

**Comment by cams-goussale** [comment]
hello @2amarkina @frenchyrules @stephanie-cascade8 we are still under discussions regarding the wording to use between "Request Asking Price" and "Make an offer". Tomorrow afternoon we will have a final decision.

In the meantime, we would like to improve a bit [that modale](https://github.com/blockframes/blockframes/issues/7431#issuecomment-1000383925) so it includes:
- field with Territory selector
- field to indicate Price (if no price, then show "Request Asking Price)
- field to add text

Also, we should start reviewing this with the Devs, so maybe @stephanie-cascade8 I could join your meeting with Francois tomorrow?

**Comment by stephanie-cascade8** [comment]
> hello @2amarkina @frenchyrules @stephanie-cascade8 we are still under discussions regarding the wording to use between "Request Asking Price" and "Make an offer". Tomorrow afternoon we will have a final decision.
> 
> In the meantime, we would like to improve a bit [that modale](https://github.com/blockframes/blockframes/issues/7431#issuecomment-1000383925) so it includes:
> 
> * field with Territory selector
> * field to indicate Price (if no price, then show "Request Asking Price)
> * field to add text
> 
> Also, we should start reviewing this with the Devs, so maybe @stephanie-cascade8 I could join your meeting with Francois tomorrow?

Yes :) You can join us ( 3:30 pm)

**Comment by cams-goussale** [comment]
Final decision: we go with "Request Asking Price"

**Comment by cams-goussale** [comment]
Following all of the discussions and the short timings, we will do these first screens for Berlin:
#7502 #7503

And after Berlin will work on a second phase, with a better animation
#7507

**Comment by stephanie-cascade8** [comment]
@Jackseed @cams-goussale  here is a visual of the animation I would like on the scroll button. 

<img width="883" alt="Capture d’écran 2022-01-06 à 10 31 02" src="https://user-images.githubusercontent.com/66258851/148361295-fa2b1762-96cd-42b7-a77c-4c6283b5b7e4.png">


https://user-images.githubusercontent.com/66258851/148362037-73520060-b7a2-442b-a693-887bb6408f2a.mov


https://user-images.githubusercontent.com/66258851/148362043-286cd998-2fd1-4af6-a6db-9bfeb40c5a7c.mov

**_Reminders of what we discussed :**
-We can't have the pulse halo behind since our stroke button have a transparent background. Plus, the pulse will also be present on button "ask for screening" and the ongoing button if there is one. (on the right side).
- We can't have animated icons in the flat/Stroke buttons, that would give too many icons on the global sight. The importance effect we want to give would be cancelled and it would be to crowded and repetitive._

**- Technical questions:** 
This stroke animation is based on a linear gradient inside the button's border. 
I think we can't have linear gradient inside borders in css. 
_The 2 solutions I could see in my tests were: 
- adding a stroke &:before on top of the button (animated the linear background of the stroke)
- playing with the dash array / offset of the stroke button but we need the btn to be an svg.
**Needs dev review before dev launch**

**Comment by Jackseed** [comment]
Ok cool looks good to me!

**Comment by 2amarkina** [comment]
> hello @2amarkina @frenchyrules @stephanie-cascade8 we are still under discussions regarding the wording to use between "Request Asking Price" and "Make an offer". Tomorrow afternoon we will have a final decision.
> 
> In the meantime, we would like to improve a bit [that modale](https://github.com/blockframes/blockframes/issues/7431#issuecomment-1000383925) so it includes:
> 
> * field with Territory selector
> * field to indicate Price (if no price, then show "Request Asking Price)
> * field to add text
> 
> Also, we should start reviewing this with the Devs, so maybe @stephanie-cascade8 I could join your meeting with Francois tomorrow?

Modal with a form updated accordingly in [wireframes ](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=11%3A5620)
![Page](https://user-images.githubusercontent.com/55499036/148913969-cfa99ea7-3c50-47bc-89cc-8d6a25a383d0.png)

P.S. wording still to be checked

**Comment by Jackseed** [comment]
Hum we go for asking price instead of making an offer, could you update the modale plz? @2amarkina

**Comment by 2amarkina** [comment]
![Снимок экрана 2022-01-11 в 12.25.21.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/d309f932-1129-468c-b780-33cb46a1af87)

**Comment by stephanie-cascade8** [comment]
About the buttons animations , we finally decided with François to choose something even more simple. 
Instead of animating the border (see in videos above in this issue) we will animate the text color. 

**See an example [here](https://codepen.io/shshaw/pen/YpERQQ?editors=1100) :** 

The code would be this : 
.linear-wipe {
  text-align: center;
  
  background: linear-gradient(to right, #9eb1ff 20%, #9eb1ff 40%, #FF0 60%, #FFF 80%);
  background-size: 200% auto;
  
  color: #000;
  background-clip: text;
  text-fill-color: transparent;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  
  animation: shine 5s linear infinite;
  @keyframes shine {
    to {
      background-position: 200% center;
    }
  }
}

**Comment by stephanie-cascade8** [comment]
Hey :) I need to finish some figma cleaning and components  in this

**Comment by cams-goussale** [comment]
Finished!
