### ISSUE TITLE
FSNFT - Token view page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7438]
This page is accessible only by token owners. It's here to enable them to watch and showcase video or image related to the token they bought.
Currently this page only supports video:
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/0d7500de-ad88-4c68-9103-8e4c1b3eb251)

We need to improve this page a bit to include images and make it a bit prettier.

At first it's gonna be really simple and minimal UI, later on it could also include more metadata.

Concretely what we need to add right now to this page is:
- the token title 
- a frame to display either a video or an image

**Comment by 2amarkina** [comment]
[Work in progress is here](https://www.figma.com/file/EPXrmhxEE5LX2wsewhcybw/Token-view-page?node-id=0%3A1)

**Comment by 2amarkina** [comment]
[Here are wireframes. ](https://www.figma.com/file/EPXrmhxEE5LX2wsewhcybw/Token-view-page?node-id=0%3A1) 

@frenchyrules here is the list of actions that should be done / checked 
1. Back arrow should lead to the page "Your Tokens". 
2. For the Image : the "-", "+" and "full screen" should appear only on hover
3. The signature below the video or the image should contain the name of an artwork. 
4. Then, if possible, we would like to show the name of the author (creator) of corresponding artwork. 

@pldespaigne maybe you could already have a look if it's ok? 

I also put the wireframes directly in this issue. 

![Image.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/3ce602bf-d9ae-4386-8df4-b6bcc47d9615)
![Video.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/8b9009ac-c189-473a-871e-1620cfe7ca2f)

**Comment by pldespaigne** [comment]
Alright, that's perfect! Thanks!

About this
> 4. Then, if possible, we would like to show the name of the author (creator) of corresponding artwork.

It's possible but will require a little more work so I view it as a bonus, what do you think ?

**Comment by cams-goussale** [comment]
hello @pldespaigne! It'd be really nice to show the name of the author, to make it more collection-style. If we only show the name of the artwork, without the author, it would look a bit empty.

@frenchyrules could we have the 2 zeplin options:
- With author name and artwork name
- Without author name, with artwork name (-> maybe here text  will need to be aligned with the image/video?)

**Comment by frenchyrules** [comment]
Voici quelques versions différentes, avec et sans le author name. 
<img width="814" alt="Screenshot 2021-12-28 at 18 32 48" src="https://user-images.githubusercontent.com/85220905/147592081-13d21bec-4fb2-4f08-85df-adec43cf7647.png">

**Comment by frenchyrules** [comment]
![Token page](https://user-images.githubusercontent.com/85220905/147687756-b7e140bd-56a7-40d5-bf14-f96ea073ad28.jpg)

![Desktop HD Copy 3](https://user-images.githubusercontent.com/85220905/147687755-da23b63f-4a73-47a6-8eba-b6ce9102a8c7.jpg)

**Comment by frenchyrules** [comment]
Zepelin files [here](https://zpl.io/aBv4Bpp). @pldespaigne

**Comment by pldespaigne** [comment]
Perfect, Thanks 👍

**Comment by pldespaigne** [comment]
done in https://github.com/blockframes/nft/pull/92
