### ISSUE TITLE
FSNFT - IP addresses backend-functions

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7441]
Currently we get IP addresses of token owners only when they play a video once. 

Instead, we should have a backend function that get these IP addresses once users load their token list, and then save it to our db. This way it will be one step before so we'll have more IP addresses. 

The end objective is to be able to have a list of buyers' eth addresses and IP addresses (+ country) per token. This way we should be able to give back royalties per territories if users visit their token list page.

**Comment by pldespaigne** [comment]
[moving](https://github.com/blockframes/nft/issues/79)issue to the correct repo
