### ISSUE TITLE
Update offer status, create sales terms and income on negotiation accepted.

### ISSUE THREAD

**Issue by yspringfield** [blockframes/blockframes#7445]
Currently, the terms/income sales are not created during the initial creation of the sale.
[ ] On acceptance of a negotiation, we should create the term and negotiation.
[ ] Add termIds of the just created terms to the sale.
[ ] On contract update, update status of offer accordingly.

Here are the rules for updating the offer and contract status.
1) Check on the Contract level (the most specific one)
CONTRACT STATUS RULES
pending: when offer was first created and seller has not submitted any action yet
negotiating: 1st time seller hits the "Submit" button after clicking "Negotiate"
accepted: 1st user who clicks on the confirmation modale after "Accept" button
declined: 1st user who clicks on the confirmation modale after "Decline" button
2) Check on the Offer level (which depends on the Contract status)
OFFER STATUS RULES
new: all contracts are “pending” ;
negotiating: 
if there is 1 contract in the offer, check that the contract has status "negotiating"
if there is 2 or more contracts in the offer, at least one contract has status "negotiating" or "accepted" or "declined";
accepted: when all contracts are accepted ; 
declined: when all contracts are declined

**Comment by cams-goussale** [comment]
- [ ] First time Seller recieves a contract, Status should be "Pending" as mentionned in the rules above. As soon as he clicks on Negotiate + Submit, then status should change to "In Negotiation".
>CONTRACT STATUS RULES
pending: when offer was first created and seller has not submitted any action yet
negotiating: 1st time seller hits the "Submit" button after clicking "Negotiate"


@yspringfield  In the video below, Seller has just received the offer for the first time and has not clicked yet on Negotiate nor Submitted.

https://user-images.githubusercontent.com/93206363/146963912-e126c59a-6771-450b-a0bf-8aaf62d80fae.mp4

**Comment by cams-goussale** [comment]
- [ ] First time Buyer creates an Offer with Contracts, the Negotiation stage of the Contracts should be "Waiting for [Seller's org name] answer"

In the video below, the dark theme represents the Buyer. He just created an offer with 2 contracts inside. The Negotiation stage says "Waiting for [Buyer's org name] answer" aka waiting for his own company to answer. It should be the Seller's org name.

This sentence is like a ping pong: first it's for the Seller (Licensor) to answer, then it's the Buyer (Licensee), then again the Seller, then again the Buyer, etc. etc. until the contract is Accepted.

https://user-images.githubusercontent.com/93206363/146966004-96978fb2-404d-4cc5-b651-c72f5a96a868.mp4

**Comment by cams-goussale** [comment]
- [ ] As said in the rules above, if 1 or more contracts is In Negotiation, the Offer status should be In Negotiation.

> OFFER STATUS RULES
negotiating:
if there is 1 contract in the offer, check that the contract has status "negotiating"
if there is 2 or more contracts in the offer, at least one contract has status "negotiating" or "accepted" or "declined"


![image](https://user-images.githubusercontent.com/93206363/147481377-7fbe69e0-b6ba-4d12-9ca4-7efd0b789efe.png)

**Comment by cams-goussale** [comment]
- [ ] If one contract is Accepted and one contract is Declined, the Offer should be Accepted

![image](https://user-images.githubusercontent.com/93206363/147488266-d0678610-56f2-4673-bde2-5d710bc0e7f4.png)

**Comment by cams-goussale** [comment]
I have been revising the status for the OFFER, and I think the rules above have a mistake. I think we should follow this table. Also I think it's important to check the contract status in the same order as below.

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Status | Trigger
-- | --
New | All contracts must be Pending
Declined | All contracts must be Declined
Accepted | (All contracts must be Accepted) OR (All contracts are in Declined with at least 1 Accepted)
Negotiating | All the other cases
On signature | Manually in CRM (dropdown)
Signed | Manually in CRM (dropdown)


</body>
</html>
