### ISSUE TITLE
Reduce the weight of background image (Landing)

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7453]
As Yuki said the landing page of Archipel Content takes quite long time to be loaded. 
Following her remark the page's performance was tested via [GTMetrix tool](https://gtmetrix.com/)

The results show that one of the loading problems might be caused by content_header_background that is pretty heavy. ![Снимок экрана 2021-12-21 в 13.44.09.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/860b6e1a-a0b1-4cbd-b333-47a1b642d856) 

Need to see if it's possible to reduce it's weight.

**Comment by stephanie-cascade8** [comment]
Hi! Here it is, I reduced it down to 1,4 MO. tell me if loading is better and send a screenshot to see quality if possible. 
![content_header_background-min](https://user-images.githubusercontent.com/66258851/151520233-e5b8b920-5cc6-487c-8157-1e69a95ffbe6.png)
