### ISSUE TITLE
Regression : Rules unit tests

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#7457]
The following commit introduced a change in firebase testing library:

https://github.com/blockframes/blockframes/commit/8bb84cbc34b554cd3d88fb47d09c32a0d6ed2495#diff-597c37e9085f945b4014fd9b308536a6a6aace147af705a460700c054fc78c73

Earlier we were using @firebase/rules-unit-testing and the changed library (@firebase/testing) is deprecated : 
https://www.npmjs.com/package/@firebase/testing

For backend-functions unit testing, I developed tests which were working with rules-unit-testing library and seem to fail with testing. Also reverting the function.ts file to original rules-unit-testing breaks rules unit test.

So this change has to be reworked.

**Comment by phpgeekfr** [comment]
- [ ] `@firebase/testing` lib is deprecated (https://www.npmjs.com/package/@firebase/testing) so lets try to remove this lib from the repo and use `@firebase/rules-unit-testing` instead
