### ISSUE TITLE
Possible unused db fields

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7475]
Looks like that theses fields are unused :

```typescript
buckets: [
  'uid' 
],
permissions: [
  'canCreate',
  'canRead',
  'canUpdate',
  'canDelete',
],
```

- [x] check if this is really the case
- [x] update interfaces (and perform a migration if some fields are set to null)
- [x] update `userMap` in `apps/backend-ops/src/internals/utils.ts`

**Comment by RemcoSimonides** [comment]
If I remember correctly; `uid` ion bucket s not saved in the db, but it is used to send an email to the person who created the bucket and the admin can contact that person specifically. Or this is the case for offer, not bucket.

**Comment by phpgeekfr** [comment]
Merging #8676

Regarding Movies:

Some movies have duplicated attributes with typos :
- `reviews` (singular is the good attribute)
- `ratings` (again, singular is the good one)
- `boxoffice` (camelCase is the good one)

examples:
```
1Dke1O1HrYuhpYDeOp8S
FPma2XAECsCo1yLwtGXP
VaFFWCB2oaGkWXsESTLn
mTnUeCG4nAQvTN9hII0v
rkVOCVskSQYoM1nataKg
```

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/2446a098-da19-44a4-a945-48c87d5568a0)
