### ISSUE TITLE
[Catalog] Deal nego - CRM review

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7482]
- [x] Statuses available in the Contract view in CRM are not exactly the same we see in app. In particular the one called "pending" corresponds to "new" in the app. It could be clearer to use the same wording in both sides.

CRM
![image](https://user-images.githubusercontent.com/93206363/147484184-0c041d4e-8717-4234-9cf9-17884fa5fb58.png)

In app
![image](https://user-images.githubusercontent.com/93206363/147486774-ea7bb1fb-8e0b-43f2-a414-71134cc3ccf7.png)

**Comment by cams-goussale** [comment]
- [ ] When modifying the status of a Contract in CRM, it doesn't save the change.

https://user-images.githubusercontent.com/93206363/147484575-87e49fac-8313-4d63-b677-81a9bdbe8a69.mp4

**Comment by cams-goussale** [comment]
- [ ] In the page /crm/offer/[offerReference]/[salesId]/form, when editing the first Rights card, and then editing the 2nd Rights car, the table view disappears. (Similar bug for holdbacks [here](https://github.com/blockframes/blockframes/issues/7389#issuecomment-1002172162))

https://user-images.githubusercontent.com/93206363/147584479-768d57c9-5410-4d01-a787-e621e25cb98b.mp4

**Comment by cams-goussale** [comment]
- [ ] Modifying Contract status from ACCEPTED to IN NEGOTIATION
A Contract was ACCEPTED and changed manually from to IN NEGOTIATION in the CRM. Users can't see the Accept / Decline buttons so they are not able to re-start the negotiation. We should give these actions to the last one who was negotiating (aka the one who accepted the contract). Also the Negotiation Stage is missing in the table views.

Buyer table view:
![image](https://user-images.githubusercontent.com/93206363/147653874-2252d4bb-eb02-47ed-98fc-fffe72401ac3.png)

Buyer contract view:
![image](https://user-images.githubusercontent.com/93206363/147653919-6030f38c-a38d-43c7-971d-abd452ca1a4f.png)

Seller table view:
![image](https://user-images.githubusercontent.com/93206363/147654096-e990f800-4d51-4153-877d-86109c894ec2.png)

Seller contract view:
![image](https://user-images.githubusercontent.com/93206363/147654164-6f93e3eb-5577-49ed-b50b-f445247278b3.png)

**Comment by cams-goussale** [comment]
- [ ] Modifying Contract status from IN NEGOTIATION to NEW
A Contract was IN NEGOTIATION and I manually changed it to NEW with the CRM. However, the change doesn't get saved.

https://user-images.githubusercontent.com/93206363/147655532-95762a08-7117-413d-b6f3-ed5c1e31a425.mp4

**Comment by cams-goussale** [comment]
- [ ] Modifying Contract status from NEW to ACCEPTED
A Contract was NEW with "request asking price" = no price. I manually changed the status to ACCEPTED in CRM, which led to an accepted contract with no price.

2 options:
- We prevent user to manually accept a contract in CRM if there is no price (best option)
- Or we add a warning next to the status selector

![image](https://user-images.githubusercontent.com/93206363/147666271-46fbe38a-a5b2-43c3-88ee-9bd6dadc307a.png)

**Comment by cams-goussale** [comment]
- [ ] Modifying Contract status from IN NEGOTIATION to DECLINED
A Contract was IN NEGOTIATION and I manually changed it to DECLINED with the CRM. However, the change doesn't get saved.

**Comment by cams-goussale** [comment]
I have written [here ](https://docs.google.com/spreadsheets/d/14Z7gVA_6SNzTtDXt1911eiLLEtbb1xz2NL0oUQCbNCg/edit#gid=1789935074)a summary of the changes possible through CRM and the different case scenario we should be able to manage.

**Comment by cams-goussale** [comment]
- [ ] When a contract is In Negotiation, it doesn't appear in CRM contract view.

https://user-images.githubusercontent.com/93206363/148056202-9390fd39-6a4b-46a9-8296-d99f8db3096e.mp4

**Comment by cams-goussale** [comment]
- [ ] When changing manually the status to "IN NEGOTIATION", it actually changed to "NEW".

https://user-images.githubusercontent.com/93206363/148066101-d560de08-5ba8-442b-835f-d0a681cbefda.mp4

**Comment by RemcoSimonides** [comment]
Created new issue for open tickbox. Closing this one
https://github.com/blockframes/blockframes/issues/7687
