### ISSUE TITLE
Unit-Test : Implement a simple example of `onCreate` db trigger

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7488]
A simple db trigger to test can be this one : 
```
export const onDocumentPermissionCreateEvent = onDocumentCreate(
  'permissions/{orgID}/documentPermissions/{docID}',
  onDocumentPermissionCreate
);
```

This is triggered when `addDocumentPermissions` from `PermissionsService` is called.

When `onDocumentPermissionCreate` is triggered, it simply creates a new doc in `docsIndex` so the test can be to check if document exists after the call.

Another test could be `onEventDelete` : 

```
export const onEventDeleteEvent = onDocumentDelete('events/{eventID}', onEventDelete);
```
When an event document is deleted, it is supposed to remove related `notifications` and `invitations` so the test can be to check if thoses documents are deleted when an event is deleted

**Comment by xmano** [comment]
Achieved unit tests for both the functions. The PR is here:
https://github.com/blockframes/blockframes/pull/7489

Final review comments need to be checked and changes approved. It should be good to merge.
