### ISSUE TITLE
[NFTs] Access different Collections

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7498]
### Description

Currently when landing on https://www.filmseriesnft.com/ there is only 1 collection available, the one of "Cascade8". When we start having different NFT projects, it means they will be all mixed together in the same room. We want to be able to create different sections for each project.

### What's new

After the landing page, we need an intermediate page where the user sees all the projetcs available. He/She can click on the one they're interested in to see all the NFTs under that project. Each project card should include: 

- Card
- Description
- Title
- CTA
- CTA  & redirection is editable by us through a cms

Technically, we will use a category called "Movies" which would appear in the properties of the NFT. When user clicks on the project card, he basically enters in the Cascade8 Collection filtered by movies == project name.

![image](https://user-images.githubusercontent.com/93206363/148738987-0b2f239f-f51f-40c8-ac4e-9c2a97a08806.png)

**Comment by 2amarkina** [comment]
I would say 2 days for UX (maybe less, but i prefer take more time)

**Comment by frenchyrules** [comment]
Work in progress [here](https://www.figma.com/file/JPAdwlrqRaoCxDHqeBbclC/Access-different-Collections?node-id=0%3A1)

**Comment by frenchyrules** [comment]
UI version completed [here](https://www.figma.com/file/JPAdwlrqRaoCxDHqeBbclC/Access-different-Collections?node-id=0%3A1)
![image](https://user-images.githubusercontent.com/85220905/155311502-4c0d4a9e-a687-4b97-abad-6a3459daf3ce.png)

@GrandSchtroumpf Would it be possible to incorporate a smooth drop shadow animation when hovering the cards ? Example below:
![shadow animation](https://user-images.githubusercontent.com/85220905/155307971-64ec256d-0f05-4b45-b096-470e70d59b61.gif)

**Comment by GrandSchtroumpf** [comment]
We can use the `mat.elevation-transition()` to go from one elevation level to another. See documentation here : 
https://material.angular.io/guide/elevation#animating-elevation
