### ISSUE TITLE
As a stakeholder on a film, when we all agree on a delivery list, I want the agreeement to be timestamp on the blockchain.

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#75]

**Comment by pldespaigne** [comment]
What does this means ? Is it inside an org or also cross-orgs ? When you say `all agree` do you mean 100% or only the quorum ?

**Comment by Jackseed** [comment]
`All agree` means all orgs participating to the delivery (according to their respective quorum).
Best thing would be to have only one transaction sent & signed by both orgs. 
Sub-level acceptance is to send a transaction signed by the org when it pass the quorum for each org (e.g. 2 transactions if 2 orgs stakeholders).

**Comment by Jackseed** [comment]
outdated issue, will be updated with UX plan > closed
