### ISSUE TITLE
Debug Blood Machines Wordpress

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7501]
Hard to say what's buggy but on some computer it's displayed like this
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/8c78a075-1e5b-4228-a360-3fbac4f22d49)

on other like that 
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/4b14a605-c91d-4a44-9101-ce3e3c5deac4)

for the same browser

**Comment by Jackseed** [comment]
We have more details, it's in fact related to https, http is working but not https.
Here is a screenshot from the https console
![image](https://user-images.githubusercontent.com/14964443/148209441-f2b78e9b-9a41-4fab-b5bb-59c748ded005.png)

**Comment by phpgeekfr** [comment]
Best way is to migrate the whole website to https. This can take some time to perform

**Comment by phpgeekfr** [comment]
- [ ] update db to replace `http://bloodmachines.com` by `https://bloodmachines.com`
- [ ] add a 301 redir from non https to https
