### ISSUE TITLE
[Interactions] Ask for a screening

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7502]
This issue concerns the new interactions that we want to build between Buyer and Seller. It allows a Buyer to request to the Seller a screening session on a movie. We want these features to be released for Berlin festival in early Feb, so we have split the issue in 2 parts: the minimum viable product, and the bonus feature.

**MVP "Ask for a screening"**

Pages where they will be:

- [x] Movie page: [case 1](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=3%3A7) / [case 2](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=8%3A3467) / [case 3](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=7%3A2352)
- [x] [Org page](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=3%3A8)
- [x] [Screening closed session](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=6%3A2)

Flow:

- [x] Disable button after click: [case 1](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=28%3A6929)
- [x] [1 snackbar for Buyer](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=27%3A7589)
- [x] [1 notification for Buyer](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=49%3A11858)
- [x] [1 email for Seller](https://docs.google.com/spreadsheets/d/1Xv3HJjYEM-kTnACnu-uHCmlbQ_KXlXMMExMY2JoURHA/edit#gid=0&range=F6) (action: leads to Event form)
- [x] [1 notification for Seller](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=28%3A11741) (action: [leads to Event form](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=31%3A8435))

Notif / Email wording: [here](https://docs.google.com/spreadsheets/d/1Xv3HJjYEM-kTnACnu-uHCmlbQ_KXlXMMExMY2JoURHA/edit#gid=0)

**Bonus**
Let's do the list of actions above above and the one from #7503 before continuing with these bonus.

- [ ] https://github.com/blockframes/blockframes/issues/7567

**Comment by RemcoSimonides** [comment]
Should the current "Contact" button be replaced? Should this button appear on all apps?
![image](https://user-images.githubusercontent.com/27687382/148730422-ff4bee34-eb69-4ed6-b4f7-51f9410f6816.png)

**Comment by cams-goussale** [comment]
@RemcoSimonides yes the "Contact" button should be replaced. And these new interactions are only for festival app for the moment

**Comment by RemcoSimonides** [comment]
@cams-goussale @2amarkina is it ok if the 'ask for screening' button is enabled again if the user is reloaded? because we can send the notification to the seller without saving anything in the database. If it's not ok if the button is enabled again, then we need to save something.

**Comment by 2amarkina** [comment]
The idea was to avoid the behavior when a user doesn't remember if asked for a screening or not and also to avoid too many demands from one particular user, that's why we thought about the disabled state of a button. 

Does it demand a lot of work to save this info and keep the button disabled? If yes, then we could go without saving (with a risk that a Seller can get a lot of demands from one particular user, but after all Seller is not obliged to accept these demands). 

cc: @cams-goussale @Jackseed

**Comment by RemcoSimonides** [comment]
And seller is able to disable these notifications ;) also, even if we save a state in the database, then the seller can still receive  an email for each of his movies on which it is requested. Especially on Org's line-up page it's easy to request screening for each movie ^^

**Comment by cams-goussale** [comment]
After discussions with Francois, it seems indeed the easiest way is to only disable when user clicks on the button. If s/he reloads the page, it's enabled again.

We kinda trust buyers on this one. Buyers should also have snackbar + notif confirming that s/he requested a screening, so we hope this will prevent behavior where they ask several times the same screening.

@RemcoSimonides @2amarkina

**Comment by RemcoSimonides** [comment]
- [ ] Spinner when creating event on event page.
- [ ] Event should be opened on screening tab instead of event tab.

**Comment by cams-goussale** [comment]
@RemcoSimonides maybe the spinner on event page could be added by default? When user opens calendar in dashboard, there seem to be a bit of time for all the existing events to load. So if we add a spinner here, it would also work in the case of the notification redirecting to the event form.

**Comment by RemcoSimonides** [comment]
Good addition from Bruce is to load the same spinner when creating event (the wait time after the small dialog)

**Comment by RemcoSimonides** [comment]
The loading spinner:
- when loading events:
Uploading Jan-19-2022 11-11-46.mp4…

- when creating an event after clicking on button on 'screening requested' email
https://user-images.githubusercontent.com/27687382/150113569-4c0100ab-b351-46e3-bb80-b8f2d03aa212.mp4
- When creating an event

https://user-images.githubusercontent.com/27687382/150113756-0acb47bf-8729-4a99-997b-dcb175cbb5bc.mp4

**Comment by Jackseed** [comment]
That's awesome! we should definitely take more care to have loading state on new pages

**Comment by RemcoSimonides** [comment]
- [ ] invite buyer

**Comment by RemcoSimonides** [comment]
Created separate issue for the bonus https://github.com/blockframes/blockframes/issues/7567
