### ISSUE TITLE
[Interactions] Request Asking Price

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7503]
This issue concerns the new interactions that we want to build between Buyer and Seller. It allows a Buyer to a price to the Seller about a movie. We want these features to be released for Berlin festival in early Feb, so we have split the issue in 2 parts: the minimum viable product, and the bonus feature.

NB: in some places of the figma, you might see the wording "make an offer" or "offer". It refers to "ask price" (waiting for Anastasia to come back from holidays).

**MVP "Request Asking Price"**

Pages where they will be:

- [x] Movie page: [case 1](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=3%3A7) / [case 2](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=8%3A3467) / [case 3](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=7%3A2352)
- [x] [Screening closed session](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=6%3A2)
- [x] [Ongoing screening](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=12%3A6631)

Flow:

- [x] Disable button after click: [case 1](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=31%3A8889)
- [x] [Modale with Territory filter + Text field](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=11%3A5620) (figma to be updated)
- [x] [1 snackbar for Buyer](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=31%3A9282)
- [x] [1 notification for Buyer](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=49%3A11858)
- [x] [1 email for Seller](https://docs.google.com/spreadsheets/d/1Xv3HJjYEM-kTnACnu-uHCmlbQ_KXlXMMExMY2JoURHA/edit#gid=0&range=F10) (action: leads Seller email adress prefilled with Buyer email)
- [x] [1 notification for Seller](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=51%3A12078) (action: [leads Seller email adress prefilled with Buyer email](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=55%3A12268))

Notif / Email wording: [here](https://docs.google.com/spreadsheets/d/1Xv3HJjYEM-kTnACnu-uHCmlbQ_KXlXMMExMY2JoURHA/edit#gid=0)

**Bonus**
Let's do the list of actions above and the ones from #7502 before continuing with these bonus.

- [ ] #7567

**Comment by RemcoSimonides** [comment]
@cams-goussale @2amarkina  Movie can have multiple orgs. So we should either put all the org names here to which we've sent it, or we should change the text.
![image](https://user-images.githubusercontent.com/27687382/149301788-ddbb4922-98aa-4c0b-99a9-a0ff67bb5926.png)

Also, the "Start Discussions" should "Leads to user email box with Archipel Content email adress prefilled." according to the excel doc. Have we done this before? because the button isn't working yet in the email template. And shouldn't it be Archipel Festival ^^
![image](https://user-images.githubusercontent.com/27687382/149302262-0d966126-1213-439a-bb03-3c42535ddf28.png)

**Comment by cams-goussale** [comment]
@RemcoSimonides 
1- Yes, lets put all org names in the email
2- I am not sure if this has ever been done before. However, it was Marie's idea to link it to Archipel Content (we're inviting them to discuss, negotiate and potentially make a deal on AC).

Also, please note im the one who created the templates, and it was my first time ^^

**Comment by RemcoSimonides** [comment]
Alright. It's probably my mistake that the button isn't doing anything yet I just noticed. So far good job with the templates ;)

**Comment by RemcoSimonides** [comment]
It's working. Would you like to have a subject to the email too? if yes, then what should it be?

**Comment by cams-goussale** [comment]
There is a subject currently for template id d-fa8f0f0f5799468ca3ac478c7ceeeb68

`You've received an Asking Price Request`

**Comment by RemcoSimonides** [comment]
Ah sorry, I wasn't clear. When you click the "Start discussion" button in the received email, it opens the mail client of the user with the Archipel Content email prefilled. But this doesn't have a subject yet. What would that be? ^^
![image](https://user-images.githubusercontent.com/27687382/149488294-ab66353e-e45c-4a67-a5e8-1533ddfef554.png)

**Comment by cams-goussale** [comment]
Ok all clear! after discussions with Marie:

1. Can we make the field Territory mandatory with an asterisk? (fyi @stephanie-cascade8 @2amarkina )
And if no text has been given let's put:
```
Please find below the details of their request:
Territories selected: "territories from Buyer modal".
Message: "No message provided".
```

2. Once seller clicks on Start Discussions, it opens the email with Buyer email adress and subject should be:
`Interest in [Title Name] via Archipel Market`

3. After discussing with everyone, let's indeed redirect the Seller to the email adress of the Buyer everywhere (and not to Archipel Content)
