### ISSUE TITLE
Callouts

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7507]
### Description

We launched the Buyer/Seller interactions in a first phase for Berlin. Now we can go further and move on to the second phase. The wireframes are already done (see links below). What needs to be added is an animation similar to the Figma example below.

https://user-images.githubusercontent.com/93206363/146339806-d00edd81-55e8-4015-b1a4-5d1822ef7fa0.mp4

### What's new

**Ask for a screening**
- [x] [Library page](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=7%3A3385)
- [x] [Tooltip on hover](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=27%3A7538)
- [x] Disable button after click: [case 2](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=27%3A7538)
- [ ] An "Animation onboarding" for the homepage. We want to show the new feature, explain how it works.
- [x] [Homepage](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=2%3A3)

**Request Asking Price**
- [x] [Screening list](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=11%3A9148)
- [x] Disable button after click: [case 2](https://www.figma.com/file/c62IFnbBC2UFcHZFY861jV/%5B-New-Market-Interactions-%5D?node-id=11%3A9148) 
- [ ] An "Animation onboarding" for the screening list. We want to show the new feature, explain how it works.

**Comment by 2amarkina** [comment]
@2amarkina to do list: 
- [ ] document the different types of onboarding (subcategory of providing) tooltips ;
- [ ] describe the behavior of onboarding tooltips (when it appears, for how long, when it disappears etc.)
- [ ] recheck the intercom solution ; 
- [ ] check if there are other external tools that provide this feature ;
- [ ] check how much it will cost us to use Intercom, other solution or develop internally ; 

@frenchyrules 
- [ ] benchmark 3-5 onboarding examples (Figma, Asana...?)
- [ ] propose a wireframe of a general onboarding tooltip 

@2amarkina and @frenchyrules 
- [ ] validate the best proposition with business
- [ ] check all the possibilities with the devs
- [ ] place the new tooltip together on the wireframes according to the new features to come

**Comment by 2amarkina** [comment]
[First reflexions are presented in this document](https://docs.google.com/document/d/1j4tysT_-jiQTBuzRzUcq28-yhGqbZDpe6dyxtr5ZO5M/edit)

**Comment by frenchyrules** [comment]
Two proposals; a carousel/media type callout which contains flat design styled images, a screen capture GIF or short motion design which explains visually as well as with description text. Second proposal is a simpler callout which points towards the area of interest.
![image](https://user-images.githubusercontent.com/85220905/153192402-ce49294b-b006-4de1-a4de-ef657e2831cb.png)
![image](https://user-images.githubusercontent.com/85220905/153192470-8dfa4b4e-625e-436c-a2cf-10c34d9dce8b.png)

**Comment by frenchyrules** [comment]
Callout variants (carousel/no carousel)
![image](https://user-images.githubusercontent.com/85220905/153217353-a8acc0b5-c8df-48d2-93b4-84553eb42966.png)

**Comment by cams-goussale** [comment]
My initial idea was to launch the missing parts of Buyers Interactions together with a callouts. But looking at the issue now, it makes more sense to split both topics. So I will rename this issue "Callouts" and create a dedicated dev issue for the last Interactions needed (Homepage & Library, Movie card) #7770

**Comment by frenchyrules** [comment]
UI [here](https://www.figma.com/file/IZWIqP8XmRDfriiESZtE80/Callouts?node-id=0%3A1)

**Comment by 2amarkina** [comment]
- [ ] have a button "New" and it opens the window / modal of a call out
