### ISSUE TITLE
[NFT] Change filmseriesnft button on landing

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7512]
### Description

Can we do a quick PR on filmseriesnft to already change the following things:

- [ ] Hide "marketplace" button on the header
- [ ] Change CTA link to redirect to http://bloodmachines.com/
- [ ] Change CTA text to "Coming soon: Blood Machines NFT"

**Comment by pldespaigne** [comment]
Moved to https://github.com/blockframes/nft/issues/93
