### ISSUE TITLE
Title oriented analysis

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7517]
### Description

This would be one of the categories of the new Sellers' Analytics Dashboard. It would contain some metrics related to one specific title.

### What's new

- Create a new page with a table
- The table should contain the titles and their metrics
- When clicking on a title, it opens the title_report page
- Export to csv option
----------------
- Create a dedicated surface in the Sellers' Analytics Dashboard
- This surface contains a sneek peak of 1 title_report page
- This surface has a "see more" buttons which leads to the table view

### User Scenarios

As a Seller, I want to know about Title A:
- The number of Buyers who viewed its page + their names
- The number of Buyers who requested a screening for Title A + their names
- The number of Buyers who requested the Asking Price for Title A + their names

=> these 3 metrics follow a kind of "funnel logic". First you visit the page of a title to know about it. If you are interested, you ask for a Screening. If you liked the Screening, you want to make an offer and ask for the Price. It'd be nice to reflect this funnel somehow.

- The number of Buyers who added the movie in their Wishlist + their names

**Comment by Jackseed** [comment]
Re the report page, best would be to use graphs from the[ implemented library ApexCharts](https://apexcharts.com/angular-chart-demos/)

**Comment by cams-goussale** [comment]
Research documents:

[Figma](https://www.figma.com/file/gjMhPg9k7xKQYvfb7vkcPu/Notes-Analytics-Sellers?node-id=0%3A1): benchmark of other players + list of ideas for AM
[Drive](https://drive.google.com/drive/folders/1sy-5b9_tOCdG_9i41-UZffjtfpGolrR_): survey to send to sellers + list of metrics in an excel

**Comment by 2amarkina** [comment]
[Some screens in progress ](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/Title-oriented-analysis?node-id=0%3A1)

**Comment by 2amarkina** [comment]
**Top Priority :** [Film Page Report Activity](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/%E2%8F%B3Sellers'-Dashboard-(IN-PROGRESS)?node-id=413%3A93922)

**Less Priority :** [Titles List](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/%E2%8F%B3Sellers'-Dashboard-(IN-PROGRESS)?node-id=381%3A84782)

**Comment by 2amarkina** [comment]
**The dashboard view** 
![Снимок экрана 2022-02-17 в 10.21.12.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/94b7df64-c58a-42e7-9671-fd8c62582319)

**Comment by 2amarkina** [comment]
Here are some examples of empty states for Titles Page : 
-[ Case where is no screenings](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/%E2%9A%99%EF%B8%8F-Sellers'-Dashboard-(DONE)?node-id=287%3A84364) 
- [Case where is nothing ](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/%E2%9A%99%EF%B8%8F-Sellers'-Dashboard-(DONE)?node-id=322%3A73175) 

The case where is nothing might be variable.

**Comment by stephanie-cascade8** [comment]
Empty States mockup[ here](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=298%3A28495)
