### ISSUE TITLE
Buyers oriented analysis

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7518]
### Description
This would be one of the categories of the new Sellers' Analytics Dashboard. It would correspond to the Buyers list, ordered or filtered by different criterias.

### What's new

- Create a new page with a table
- The table should contain the buyers' names and their metrics
- When clicking on a buyer, it opens the buyer_report page
- Export to csv option
_______________________________

- Create a dedicated surface in the Sellers' Analytics Dashboard
- This surface has a "see more" buttons which leads to the table view

### User Scenarios
As a Seller, I want to know:
- Buyers who added my titles to their wishlist + titles concerned
- Buyers who viewed my titles + titles concerned
- Buyers who requested a screening for my titles + titles concerned
- Buyers who requested the asking price for my titles + titles concerned
- Buyers whose buying territories (preference) match my titles availabilities + titles concerned

**Comment by cams-goussale** [comment]
[Research documents detailed here](https://github.com/blockframes/blockframes/issues/7517#issuecomment-1015390668)

**Comment by 2amarkina** [comment]
**Top Priority :** [Buyer Activity Page](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/%E2%8F%B3Sellers'-Dashboard-(IN-PROGRESS)?node-id=372%3A88942)

Less Priority : [Buyer Activity List](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/%E2%8F%B3Sellers'-Dashboard-(IN-PROGRESS)?node-id=438%3A91655)

**Comment by 2amarkina** [comment]
[Here is the link to the empty states for the Buyers' Activity](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/%E2%9A%99%EF%B8%8F-Sellers'-Dashboard-(DONE)?node-id=325%3A76993)

**Comment by cams-goussale** [comment]
Devs have dedicated issues for this so we can close it.
