### ISSUE TITLE
Movie model updates

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#752]
General updates
* [ ] merge `MovieSalesCast` section into `MovieCast`
* [x] #751
* [ ] #618 
* [ ] update draw.io and other spreadsheets
* [ ] add a field for the operatorName avatar @see https://projects.invisionapp.com/d/main#/console/17971669/375071591/preview
* [x] `rightsEnd`, `rightsStart` => move to object: `rights { from, to } `

Move `main.languages`  into `versionInfo` section and refactor into a mapping: `{  french: { lang: bool, dubbing: bool, subtitle: bool }}` to comply with: https://projects.invisionapp.com/d/main#/console/17971669/374501284/preview
* [ ]  update movie form & display
* [ ]  update excel import
* [ ] update draw.io and other spreadsheets

**Comment by Jackseed** [comment]
outdated issue > closed
