### ISSUE TITLE
CRM bug (Organization's resources)

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7523]
On the CRM, when come to the particular organization page (CRM dashboard > Organizations > [ Org Name ]) the part "Organization's resources" is not displayed correctly. 

![Снимок экрана 2022-01-11 в 11.33.13.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/bfaab55f-01fe-4769-ab1a-af71180a7efc)

Should work as on the dashboard "My Files" section
![Снимок экрана 2022-01-11 в 11.35.39.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/c0de74a6-1c99-45ba-bb1d-968ec304d962)

**Comment by RemcoSimonides** [comment]
Can't reproduce - Might already be fixed
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/27687382/177477787-347d8cae-94cd-47e3-ba6c-9eda04877fdb.png">
