### ISSUE TITLE
States of Sales page

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7530]
- [x] **Naming of the section** is "My Sales" right now, but I remember that Yuki and Marie asked that part to be called "My Deals". @Jackseed @cams-goussale do we keep with "My Sales" or change it to "My Deals"? 

- [x] **Full empty state**
Texts should be seen following the decision above (use a word "deals" or "sales) :point_up: 
![Dashboard_Layout.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/f94d8e28-8f2a-40d0-8d1b-447419ce58ad)

- [x] If there are **only Internal Sales** (only the Sales made via Archipel Content)
![Dashboard_Layout (1).png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/a02b7218-06b8-4e08-b668-c3e8aeb4bf11)

**Columns for Internal Sales:** 
- Date created
- Licensor
- Licensee
- Offer reference 
- Title 
- Price
- Status 
- Negotiation Stage

- [x] If there are **only External Sales** (only the Sales made outside Archipel Content)
![Dashboard_Layout (2).png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/fb1a3aaa-2afd-42e2-8dd8-a205de120021)

**Columns for External Sales:** 
- Import Date
- Licensor
- Licensee
- Title 
- Price

- [x] Full view with **Internal and External Sales**
![Dashboard_Layout.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/5e25b36a-0743-4d6c-a705-70061e9b7ebd)

**Comment by Jackseed** [comment]
I think "My Deals" is good since it has a broader sense (then mb one day we can add mandates in that list)

**Comment by isseymiyuki** [comment]
1) 'Deals' is neutral so that we can use it for both Sellers & Buyers. 2) I doubt if Sellers will reveal the price of their external deals but we can keep such column for now and see. 3) what's the difference between 'mandate' & 'external deals'?

**Comment by cams-goussale** [comment]
> 3) what's the difference between 'mandate' & 'external deals'
currently mandates are not visible in Dashboard for the Sellers and only us can import Mandates in the db. It represents the "technical contract" we have to upload in the system to make their avails visible to Buyers

**Comment by RemcoSimonides** [comment]
Hee @yspringfield , I see you've merged a PR and tagged this issue. Is it finished or still something to be done?
