### ISSUE TITLE
Mat-buttons variant for alignement problems

### ISSUE THREAD

**Issue by stephanie-cascade8** [blockframes/blockframes#7531]
We agreed on creating a new issue to solve this alignement problem.

_Reminder_:  we have an alignement issue (only at some places) where mat-buttons are aligned with other elements. 
Indeed, they have internal padding and an invisible background that creates a visual gap. 
See the main example bellow. The mat-button "add to wishlist" seems not correctly aligned on it's left.
![Capture d’écran 2022-01-12 à 14.39.29.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/5462e882-d0f8-4f08-82a4-1dbaac2324e5)

We want to solve this visual issue by having a lightly visible background in the mat-button. (But only where we need it).

![Capture d’écran 2022-01-12 à 14.44.26.png](https://images.zenhubusercontent.com/5ed502afe9914e7fd8671c31/7f19cdd0-dc4f-42e7-a594-881525ea8c12)

**Comment by stephanie-cascade8** [comment]
Todo List for UI (validated with François Jan.11)

- [ ] List places where we want to add this class on mat-buttons
- [ ] Communicate the right color and opacity to use.
background: rgb(255 255 255 / 16%);

**Comment by 2amarkina** [comment]
@stephanie-cascade8 
This one also seems to be ready or are there some more technical points to be discussed?

**Comment by stephanie-cascade8** [comment]
> @stephanie-cascade8 This one also seems to be ready or are there some more technical points to be discussed?

yes it's all ready :)

**Comment by RemcoSimonides** [comment]
> (WIP) Todo List for UI (validated with François Jan.11)
> 
> * [x]  List places where we want to add this class on mat-buttons
> 
> -> in the movie-header -> in the seller's page screening list <img alt="Capture d’écran 2022-01-12 à 15 03 57" width="815" src="https://user-images.githubusercontent.com/66258851/149155146-9f45a5bd-45db-4c3f-a192-fae2f97a7f65.png">
> 
> -> in the new event-slider available on Zeplin [here](https://zpl.io/299Pvow) <img alt="Capture d’écran 2022-01-12 à 14 51 05" width="884" src="https://user-images.githubusercontent.com/66258851/149152837-2e5a27c6-8645-4e90-ba8c-aeec7bf45a1a.png">
> 
> * [x]  Communicate the right color and opacity to use.
>   background: primary / opacity 0.16%.
> 
> (from François) "put the css class in this file : styles/components/mat-button.scss"
> 
> @GrandSchtroumpf do you agree on this ? Let me know if there is anything else to do on my side. (this color should work on both dark and light themes, it can be replaced by primary-500 but I would need a review)

@stephanie-cascade8 I still see "WIP" and an open question to Francois in the comment so it's not fully clear what needs to be done. Let me know if something is lost in communication but this is the conclusion I see.

A transparent background color (background: primary / opacity 0.16%) needs to be given to only these specific buttons (see images above)
-> in the movie-header
-> in the seller's page screening list
-> in the new event-slider

And (from François) "put the css class in this file : styles/components/mat-button.scss"

**Comment by RemcoSimonides** [comment]
## Movie banner
- 
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/27687382/161932768-b3d9b567-af1e-4598-b56f-f4390bb4aca6.png">

The wishlist button is impacted everywhere it is used
- Movie banner
- Movie cards
- Home page slider
<img width="570" alt="image" src="https://user-images.githubusercontent.com/27687382/161933036-79176b37-c132-430f-903b-f827cbb677db.png">


## Seller's page screening list + event-slider
Changing the style of the button impacts the 'invitation-action' component which is used on the
Screening list page, Event page, Org screening list page, event slider on home page.

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/27687382/161934125-50a9c15f-7e7e-43f8-9ce7-dcecb50efaf7.png">

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/27687382/161934243-86e66b6c-59f0-44be-8571-a8f8fe95b1f3.png">

**Comment by stephanie-cascade8** [comment]
@RemcoSimonides thanks for this complete review ! 

About the rounded wishlist button, I think it's fine. 
About the headers when having to many/not aligned buttons need to be restructured with UI/UX (with the responsive mobile version at the same time) I’ll ask @cams-goussale  for an issue.

Here : The space needs to be worked on just like in mockups (I'll put the link here)
<img width="400" alt="Capture d’écran 2022-04-06 à 11 00 46" src="https://user-images.githubusercontent.com/66258851/161937934-3b5f8b7f-45a2-4ea0-a6d7-1ad4831475e3.png">
