### ISSUE TITLE
[Deal Nego] Illu for Offer Notifications

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7541]
During the Deal Negotiation flow, each party of the negotiation can receive notifications ("you've received an offer", "your offer was accepted"...)

A notification can concern either **a contract** or **the offer**. Reminder: the offer is made of one or several contracts.
- A contract is the negotiation between 1 Seller and 1 Buyer about the terms of 1 title.
- The offer is the combination of all the contracts, which binds the Buyer to multiple Sellers.

In consequence, for notifications related to a contract, we can use the logo of the party who made the action (because it's a 2-party discussion). However, when it comes to the nofitication related to the offer, we should have a dedicated illustration (because it's a discussion with many orgs and many titles).

For now, Springfield put the one below, but it's too small and with too many details.
![image](https://user-images.githubusercontent.com/93206363/149516174-4a8b2301-b2ad-4ab5-81d8-efdc8d679818.png)

**Comment by cams-goussale** [comment]
@stephanie-cascade8 this is the issue i mentioned in slack. I'm curious to know if you need to create something from scratch or you can reuse something you have already

**Comment by stephanie-cascade8** [comment]
<img width="292" alt="Capture d’écran 2022-01-21 à 11 32 36" src="https://user-images.githubusercontent.com/66258851/150512127-f55450ea-c26f-4029-af01-c0d72475d
<img width="304" alt="Capture d’écran 2022-01-21 à 11 32 26" src="https://user-images.githubusercontent.com/66258851/150512152-32cda01a-5086-4416-856c-2d15c4aa407f.png">
02c.png">

You can download them here.
[illu_list-offer.zip](https://github.com/blockframes/blockframes/files/7912527/illu_list-offer.zip)
