### ISSUE TITLE
remove isBlockchainEnabled & ActiveDaoGuard

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7543]
remove isBlockchainEnabled & ActiveDaoGuard

**Comment by RemcoSimonides** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Dev---Sanity-Team-5f6b0067599064680cd2c617/issues/blockframes/blockframes/7543?planning-poker) with ZenHub @phpgeekfr

**Comment by phpgeekfr** [comment]
#7943 was created with more details and `ActiveDaoGuard` was already removed.
