### ISSUE TITLE
Reduce GCP costs 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7545]
Our GCP invoice more than doubled up between November and December from 175€ to 440€!

It almost entirely comes from 1 specific line:  `GCP Storage egress between NA and EU`
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/604f5888-d4b8-4f41-9d82-799f2bf23d03)

I made some research and it looks like it's related to [the location of our docker image](https://blog.fgribreau.com/2020/06/finops-reducing-google-cloud-storage.html). 

Given the trajectory of the cost I think we should investigate on it and search for solution asap.

**Comment by GrandSchtroumpf** [comment]
After first investigation it seems that the main issue comes from transfers between blockframes (eu) & blockframes-ci (us).
A simple solution would be to move blockframes-ci to eu, but would require some refactoring as we cannot change the storage from one place to another like that.

**Comment by george43g** [comment]
We would need to create a new Firebase project in the EU. This would require new service account keys and firebase API keys to be updated in the env variables in Circle CI.

**Comment by phpgeekfr** [comment]
Check if we can remove `blockframes-ci.ts` and firestore `db`, `auth` `hosting` to keep only storage buckets

**Comment by phpgeekfr** [comment]
- [ ] create a temporary bucket, and use gsutil to copy all the contents to a temp bucket. Then delete the bucket you want to move and create another one  with the exact same name except in the region you want. Then copy over from the temp bucket to the new bucket. Done

**Comment by phpgeekfr** [comment]
Ci buckets have been migrated. We should see on the next bill if cost have decreased

**Comment by phpgeekfr** [comment]
Transfer is now much faster, this would also decrease a bit circleCi costs (less credits used for this operation)
