### ISSUE TITLE
Screening stat improvements

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7555]
Pulsar team thought there was an error with the screening statistics being updated from one connexion to another (first see a user at 10min viewing; then 45min). It looks like we should:

- [x] add something to explain how the stats are created (almost instantly updated)
- [x] add a warning or something to underline that screening is still happening and data not complete
- [x]  **bruce** add a "Watching now" status on users (to prevent sellers but also to create fun) => moved to #8717

- [x] There also was uncertainty on the "0min": does it mean that user didn't click on play? left right away?

_Originally posted by @Jackseed in https://github.com/blockframes/blockframes/issues/6680#issuecomment-1014660277_

**Comment by 2amarkina** [comment]
[Work in progress ici](https://www.figma.com/file/HQ2FBvm2u0vyWO0QpIKeTs/%5B-Event-Form-Structure-%5D?node-id=710%3A4957)

**Comment by 2amarkina** [comment]
- [ ] add participation rate 
- [ ] check together with @cams-goussale the new improvements that can be added to this issue

**Comment by cams-goussale** [comment]
Listing here all the metrics that we will include in the excel export (in reference to this issue #7135). So it'd make sense to also include them in the Statistic section, inside the app. We don't need to add everything, we can be selective.

(Vanity)
- Number of invitations sent
- Number of invitations with status accepted / unanswered
- Number of Requests to join the event
- Number of attendees

(Analytics)
- Attendance rate `=sum(all.events.attendees)/sum(all.accepted)`
- Average watchtime `=sum(all.invitations.watchTime)/sum(all.events.attendees)`
- Acceptation rate `=sum(all.accepted)/sum(all.invitations)`
- Traction rate `=sum(all.invitation.mode == "request")/sum(all.invitations)` | Traction generated by the app itself

**Comment by 2amarkina** [comment]
![Screening.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/585e6801-e9c5-4269-86c5-0f3d2ec4abca)


![Screening (1).png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9746a106-d6a2-4ead-8cf0-73d97a913e93)

**Comment by stephanie-cascade8** [comment]
[WIP Mockup here](https://www.figma.com/file/xigwniq5ZYfpD80gzQWYvO/Event-Creation?node-id=119%3A6897)

**Comment by Jackseed** [comment]
@RemcoSimonides it looks like this wireframe is included in others but will you (or have you) take care of it?

**Comment by RemcoSimonides** [comment]
It goes with Sellers' Analytics because it's using similar components. So yea, I will take care of it.

**Comment by RemcoSimonides** [comment]
If this still goes in Release 4.3, could you add it to the [release issue](https://github.com/blockframes/blockframes/issues/8608) please? So it will be tested

**Comment by phpgeekfr** [comment]
@yspringfield was this taked into account in the current release ?

**Comment by yspringfield** [comment]
Nope, it wasn't.

**Comment by phpgeekfr** [comment]
here is the result ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/991408e9-e77a-41a7-9ad8-1f985e31be29)

**Comment by Jackseed** [comment]
looks great!
