### ISSUE TITLE
[Festival] Event Stats not showing

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7560]
## Your environement
- OS: Windows
- Browser (& version if possible): Chrome + Firefox

### Localization
- App name: Archipel Market
- Page: Event form
- Url: /event/[eventId]/edit/screening

### Context
It looks like stats are not showing anymore. I've tried several tests:

1/ In staging
Protected event: ViYzOmVt1lwzpPDoteV9
Invitation id - user without an account - watchtime saved in db: djlGTAyKFlOZG9S3Jj4V
Invitation id - user with an account - didn't play the screeening so no watchtime in db: WCajaD8tNENlXUmPtQBf 

Private event: 82ZgRjggv9C9JHcnc4Ai
Invitation id - user with an account - watchtime saved in db: Mcmljvve4JVQDlCbwjun
Invitation id -  user with an account - didn't play the screeening so no watchtime in db: 9TgdmT8g9EIrg6Yd6fj6

2/ In prod
Private event: kvUGMsOM4AZCqrZYJkC8
Invitation id - user with an account - watchtime saved in db: YLVzl1StrGmfsvlOU0zU

Result showing on app:
![image](https://user-images.githubusercontent.com/93206363/149927047-06cbb3a8-8139-48ac-afe1-0f69e9337e65.png)

### Fix
How long has this been broken? We need to rebuild the stats for the events impacted by this bug.

**Comment by phpgeekfr** [comment]
Example with event ViYzOmVt1lwzpPDoteV9
![image](https://user-images.githubusercontent.com/1194344/149958033-4f1f1f68-e56c-409c-8d48-565e74efeb60.png)

The users ids that created a pageView event are not the same that have a watchtime in DB.  But data should be displayed even if there is no watchTime associated

Query :
 ```
SELECT
  event_name as event_name,
  COUNT(*) as hits,
  value.string_value as eventIdPage,
  user_id as userId,
  REGEXP_EXTRACT(value.string_value, '(?:.*)?/event/([^/]+)/(?:r/i/)?session') as eventId
FROM `blockframes-staging.analytics_194475853.events_*` ,
 UNNEST(event_params) AS params
WHERE
    (
      event_name = 'pageView'
      AND key = 'page_path'
      AND REGEXP_EXTRACT(value.string_value, '(?:.*)?/event/([^/]+)/(?:r/i/)?session') in UNNEST(['ViYzOmVt1lwzpPDoteV9'])
    )

GROUP BY
  event_name, eventId, eventIdPage, userId
ORDER BY
  event_name
```

**Comment by phpgeekfr** [comment]
Looks like date takes some times to be available in bigQuery, I will check tomorrow

**Comment by phpgeekfr** [comment]
If the current logged in user is a blockframesAdmin, analytics events are not pushed, so uid will not be displayed in bigQuery for event `pageView` that is needed to display stats on event page.

I did a new test on staging with user `bMlhoO6asTfb68BQX1LixYqtOdz1 | dev+helmer-qzs@blockframes.io` and I can see the data in BigQuery : 
![image](https://user-images.githubusercontent.com/1194344/150110501-09ac72d7-7b44-42e4-b2de-f6835194d337.png)


I can also see it on event stats page : 

https://staging.archipelmarket.com/c/o/dashboard/event/HLl0ZB04uxlk8D33lbEF/edit/statistics

![image](https://user-images.githubusercontent.com/1194344/150110572-3d2c7e70-905f-4702-a379-53972f42d435.png)


So keep in mind that blockframesAdmin users should not be used to tests statistics

@cams-goussale can you make a new test on your side so we can close the issue ?
