### ISSUE TITLE
Buyer Interactions - Post release emails

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7567]
- [ ] Additional email to users who attended a screening session
https://docs.google.com/spreadsheets/d/1Xv3HJjYEM-kTnACnu-uHCmlbQ_KXlXMMExMY2JoURHA/edit#gid=0
Row 10 and 12 ☝️

**Comment by cams-goussale** [comment]
When treating this issue, make sure you take into account these comments from #7624


#### AM - BUYER - CTA ASK FOR A SCREENING - Interactions
Template-id: `d-a03d096d252f4c27a500ff16d13f1795`
- [ ] Add a link to the event (`event.url`)

#### AM - BUYER - CTA ASKING PRICE - Interactions
Template-id: `d-ebf41f86fa124978a15b27bec75faf09`
- [ ] `movie.international.title` should be `movie.title.international`

**Comment by phpgeekfr** [comment]
After a small talk with @RemcoSimonides we think that a discussion with devs and design/business is necessary before starting implementation

**Comment by RemcoSimonides** [comment]
UX question @2amarkina: Why do not want to send notification to the buyer? The buyer doesn't know yet on what date/time the screening will be. Would be nice to notify him/her, no?

Dev discussion: I would prefer to rework how we manage the information regarding who asked for screening. This information is currently saved in the email and not in our db. It wasn't needed to save it in our db with the functionalities which were initially required.

However, in #https://github.com/blockframes/blockframes/issues/7749 you would like to see whether a user is already invited to a screening.
And in https://github.com/blockframes/blockframes/issues/8438 we're doing concessions because of this limitation.

**Comment by 2amarkina** [comment]
Here we are on the first step of the event creation. So, when an event is created and a Buyer is not invited yet, we do not notify him as a Seller might change the date for example. 

The moment when we notify a Buyer is after sending an invitation (as in our usual flow), so s/he will be notified at this particular moment. 

As the second step, that is in UX at the moment #8438 , we pre-fill the event with an email of Buyer that has requested the screening. 

Actually, it's really our usual event creation flow, the only difference is in pre-filling some fields.

**Comment by cams-goussale** [comment]
> UX question @2amarkina: Why do not want to send notification to the buyer? The buyer doesn't know yet on what date/time the screening will be. Would be nice to notify him/her, no?

@RemcoSimonides this was actually a business decision. If it's easier to push a notification with an email, we can send it. It's just that I think the message is quite "complex" and not so appropriate in a short notification. But again, if it makes you life easier to have both notif + email, then let me know and I'll add something.

**Comment by cams-goussale** [comment]
also @phpgeekfr @RemcoSimonides im available for a quick chat about this this afternoon!

**Comment by RemcoSimonides** [comment]
After call it's more clear what to do. This issue focusses now only the emails sent after a Screening session.
