### ISSUE TITLE
Optimize circleCi and e2e tests to reduce credits usage

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7569]
Following #6923.

In order to reduce credits consumed on CircleCi, we need to optimize e2e test to make them faster. 
- [ ] a first optimization can be done by removing various `wait` between page changes
- [ ] also check if a docker with more CPU and RAM can make tests faster and cost less credits

Also remove unnecessary jobs on circleCI
- [x] #7574

**Comment by george43g** [comment]
our e2e testing will likely take longer once we fix all of our disabled tests. The overall costs of our CI are likely to increase. I'm surprised they havent sharply reduced since optimisations made in December....

**Comment by phpgeekfr** [comment]
- [ ] remove `blockframes-ci.ts` and firestore db to keep only storage @see #7545 ?
