### ISSUE TITLE
Improve event page statistics

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7570]
Following #7560

Currently, to display this kind of page
 ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/02ff38da-64ef-451f-a719-810525cb217a)

We first fetch `pageView` from BigQuery and we consolidate data with `WatchTime` coming from invitations. (note that data for users of the same orgId as event owner or blockframesAdmin will not be displayed )

This is working ok for users that have a real account because uid in bigquery is the same as in the invitation document. But this does not work for anonymous users for protected events.

What we could do is, instead of fetching pageView, then watchTime, we could fetch watchTime only and display a table like this:

```
First Name1 | LastName | OrgName | WatchTime
Anonymous1                                      | WatchTime
First Name2 | LastName | OrgName | WatchTime
First Name2 | LastName | OrgName | WatchTime
Anonymous2                                      | WatchTime
```

The only problem with this is that users that went to event page without starting the video will have no watchTime so we will not be able to display users with watchTime = 0

**Comment by cams-goussale** [comment]
It's ok if users with watchTime = 0 dont show.
In the table, could we add the email adress?

**Comment by phpgeekfr** [comment]
Need to confirm this but yes I think we can
