### ISSUE TITLE
[Sellers' Analytics] Dev Research

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7587]
### Description

The next big feature for Archipel Market will be to provide qualitative analytics to Sellers. In this context, we'd like to have some answers on how we shall organize, structure and treat the data, which probably will need some research.

### What's new

Our suggestion is to start with 2 modules of analysis:
- Title oriented analysis (ux issue #7517)
- Buyer oriented analysis (ux issue #7518)

Below are the metrics we'd like to show to Sellers, but this can change depending on your research & your restrictions.

### User Scenarios

As a Seller, I want to see qualitative data on my titles:
- The number of Buyers who viewed its page + their names
- The number of Buyers who requested a screening for Title A + their names
- The number of Buyers who requested the Asking Price for Title A + their names
- The number of Buyers who added the movie in their Wishlist + their names

As a Seller, I want to see qualitative data on Buyers:
- Buyers who added my titles to their wishlist + titles concerned
- Buyers who viewed my titles + titles concerned
- Buyers who requested a screening for my titles + titles concerned
- Buyers who requested the asking price for my titles + titles concerned
- Buyers whose buying territories (preference) match my titles availabilities + titles concerned

To be complete, there are other metrics we have considered for future iterations of this project:

As a Seller, I want to see:
- Total nb of Buyers who added my titles to Wishlist
- Total nb of Title Page views
- Total nb of Screenings organized by my org
- Median attendance rate of my Screenings
- Median traction rate of my Screenings
- Total nb of internal sales
- Median sales price
- Number of page views on 1 title compared to average number of page views on all my titles
- Number of page views on 1 title page compared to the general average of the platform
- Number of page views on 1 title compared to the average number of page views on titles with similar genres
- My screening metrics compared to the general average of the platform during a specific period of time

### Estimation
Main points are:
- Where will the data be stored? analytics or db?
- We want to build long term & solid data structure
- We want to show complete and accurate data (so need to think of potential missing data with Analytics)
- How long do you estimate the time to build the data model for 1 module? for 2 modules?

**Comment by Jackseed** [comment]
We already have analytics displayed to users and they use different models, maybe we can use this issue to update it and use always the same model for all analytics displayed to clients. 

Currently we have: 
- Marketplace movie views, add to wishlist and click on other videos > saved on BigQuery, which is saved on Firebase daily ("analytics" collection, to confirm with a dev)
- Screening watch time: save directly on firebase, on the invitation documents

**Comment by Jackseed** [comment]
Also we should highlight some constraints and objectives:
- data need to be consistent (beware browser blocking cookies or analytics), we may not display 100% of the data because of browser blocking but it has to be consistent.
eg: we can't show 100 video clicks on a movie and 50 movie views whereas you need to view movie before making a video click
- data need to be loaded quickly: we already tried to load data from both firebase and analytics and it was taking minutes instead of seconds, this can't happen

**Comment by RemcoSimonides** [comment]
Scribbling down findings comment:
- [Proxy Google Analytics event data](https://www.freecodecamp.org/news/save-your-analytics-from-content-blockers-7ee08c6ec7ee/)
