### ISSUE TITLE
Automatic email when organizer modifies an event

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7592]
Following comments here #7538

When organizer has already sent invitations for an event, and deletes the event afterwards, we should send an email to invited people to let them know.

**Comment by cams-goussale** [comment]
Adding to this issue: when an organizer changes the date of the event after sending the invitations, it should send an automatic email to invitee to let them know there's been a change.

**Comment by frenchyrules** [comment]
_When organizer has already sent invitations for an event, and deletes the event afterwards_

**Proposition 1:**
`Hey ! Please note that the event [[event name]] has been canceled by its’ organizer. You may want to contact them to request a new event. `
**Proposition 2**
`Hey ! Please note that the event [[event name]] has been canceled by its’ organizer. You can contact them here[[link]] to request a new event. `

_when an organizer changes the date of the event after sending the invitations_

`Hey ! Please note that the event [[event name]]s’ date has been changed and will now be taking place on the [[event date]] [[event time]].`

Would a small illustration be needed here to dress up the email a bit ?

**Comment by cams-goussale** [comment]
@frenchyrules I'll create a[ Sendgrid template](https://docs.google.com/spreadsheets/d/1b1K7YfnquxnfCgGGPxIz5ZNIjr9eK_bUrRJqLvPYGIk/edit#gid=97734814&range=A30) as soon as we have the ok from dev.
The first step is really to ask if we can technically do this.
