### ISSUE TITLE
Deal negotiation emails - Variable refactoring

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7617]
To stay consistent some changes to make on email variables sent:

#### Price
- [ ] When there is a `price` variable, format it to be American number
- [ ] `negotiation.currency` should be changed from text (eg "Euro") to symbol (eg "€")

#### AC - Contract - Offer under signature 
Template-id: `d-38ee6949f4724b1c8796b8df9229f21d`
- [ ] `offerId` should be `offer.id`
- [ ]  `title` should be `movie.title.international`

#### AC - Contract - received counter offer
Template-id: `d-eccc758b6e09492b8449dc218fa762db`
- [ ] `offerId` should be `offer.id`
- [ ]  `title` should be `movie.title.international`

#### AC- Contract - Buyer Offer created
Template-id: d-1d6a00bab6f448299e9fcdaec7c4c787
- [ ] `offerId` should be `offer.id`

#### AC - Contract - send counter offer
Template ID: `d-ea33a9ce21534aaa99377590c52bf362`
- [ ] `org.denomination.full` should be `org.denomination.public`
- [ ] `title.title.international` should be `movie.title.international`

#### AC - Contract - Declined Contract
Template-id: `d-8227446674064157991ffc8b00b70224`
- [ ] `title.title.international` should be `movie.title.international`

#### AC - Contract - Contract Declined
Template-id: `d-5c4a64135974424592504a5409b35ad8`
- [ ] `title.title.international` should be `movie.title.international`

#### AC - Contract - Contract Accepted
Template-id: ` d-54c26ec9b0c54039b64bc40255513fba`
- [ ] `title.title.international` should be `movie.title.international`

#### AC - Contract - Accepted Contract
Template-id: ` d-5f45ee1375c04ddba84e6dd60664a689`
- [ ] `title.title.international` should be `movie.title.international`

**Comment by Jackseed** [comment]
@cams-goussale I assigned you to remind you to change sendgrid templates when this issue comes.

**Comment by RemcoSimonides** [comment]
Merged with https://github.com/blockframes/blockframes/issues/7624 since it's the same task but just different emails
