### ISSUE TITLE
Email variables refactoring 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7624]
#### AM - BUYER - CTA ASK FOR A SCREENING - Interactions
Template-id: `d-a03d096d252f4c27a500ff16d13f1795`
- [ ] Add a link to the event (`event.url`)

#### AM - BUYER - CTA ASKING PRICE - Interactions
Template-id: `d-ebf41f86fa124978a15b27bec75faf09`
- [ ] `movie.international.title` should be `movie.title.international`

#### AM - BUYER - ASKING PRICE REQUEST - Interactions
Template-id: `d-fa8f0f0f5799468ca3ac478c7ceeeb68`
- [x] `movieTitle` should be `movie.title.international`
- [ ] `orgNames` should be `org.denomination`
**Antoine**: Not possible, we currently handle the case where a a movie has several orgIds
- [ ] Activate V1 for the release

#### AM - ORG - ASKING PRICE REQUEST - Interactions
Template-id: `d-13c1cbe54bb74a9c9e9ea506db02669f` 
- [x] `movieTitle` should be `movie.title.international`
- [x] `buyer` should be `buyer.firstName buyer.lastName`
- [x] Add a `org.denomination` variable
- [x] Add a `org.country` variable
- [ ] Activate V1 for the release

#### AM - ORG - SCREENING REQUEST - Interactions
Template-id: `d-1a4f08ee48734343bb02f5f3238a5713`
- [x] Add a `buyer.email` variable
- [x] `buyer` should be `buyer.firstName buyer.lastName`
- [x] Add a `org.denomination` variable
- [x] Add a `org.country` variable
- [ ] Activate V1 for the release

## Deal Negotiation emails
To stay consistent some changes to make on email variables sent:

#### Price
- [x] When there is a `price` variable, format it to be American number
- [x] `negotiation.currency` should be changed from text (eg "Euro") to symbol (eg "€")
@cams-goussale we should define which symbol to use for every currency : 
ex: australian dollar $ or A$ ?

#### AC - Contract - Seller receives an offer
Template-id: `d-f7c2e13b7d6b427daf08bdfdf904d697`
- [x] `title.title.international` should be `movie.title.international`

#### ~AC - Contract - Offer under signature~
~Template-id: `d-38ee6949f4724b1c8796b8df9229f21d`~
- [x] ~`offerId` should be `offer.id`~
- [x]  ~`title` should be `movie.title.international`~
- [x] ~Activate V3 for the release~

#### AC - Contract - received counter offer
Template-id: `d-eccc758b6e09492b8449dc218fa762db`
- [x] `offerId` should be `offer.id`
- [x]  `title` should be `movie.title.international`
- [x]  Activate V3 for the release

#### AC- Contract - Buyer Offer created
Template-id: `d-1d6a00bab6f448299e9fcdaec7c4c787`
- [x] `offerId` should be `offer.id`
- [x] Activate V3 for the release

#### AC - Contract - send counter offer
Template ID: `d-ea33a9ce21534aaa99377590c52bf362`
- [x] `org.denomination.full` should be `org.denomination.public`
- [x] `title.title.international` should be `movie.title.international`
- [x] Activate V3 for the release

#### AC - Contract - Declined Contract
Template-id: `d-8227446674064157991ffc8b00b70224`
- [x] `title.title.international` should be `movie.title.international`
- [x] Activate V3 for the release

#### AC - Contract - Contract Declined
Template-id: `d-5c4a64135974424592504a5409b35ad8`
- [x] `title.title.international` should be `movie.title.international`
- [x] Activate V3 for the release

#### AC - Contract - Contract Accepted
Template-id: `d-54c26ec9b0c54039b64bc40255513fba`
- [x] `title.title.international` should be `movie.title.international`
- [x] Activate V3 for the release

#### AC - Contract - Accepted Contract
Template-id: ` d-5f45ee1375c04ddba84e6dd60664a689`
- [x] `title.title.international` should be `movie.title.international`
- [x] Activate V3 for the release

**Comment by RemcoSimonides** [comment]
Aren't the values working when you test the email?
I called it movieTitle instead of movie.title.international in the code since I'm not sending the whole movie object. We can't just change the sendgrid template here - then the code needs to be edited too

**Comment by Jackseed** [comment]
Yep everything works and nothing was changed in the Sendgrid templates. 
My issue is about consistency, we use the same interfaces as the db so we may use always the same variable names and be sure of how will be named the variables beforehand. 
For example here we have 3 different variable names for the same thing: `movieTitle`, `movie.title.international`, `movie.international.title`. It's ok for the release but we should clean that afterwards for consistency, thus this issue. 

And as you mentioned we indeed need to change both code & sendgrid template with this issue, so Camille can do the Sendgrid part but we still need a dev to implement it.

**Comment by RemcoSimonides** [comment]
Issue below can be done too when working on this issue.
https://github.com/blockframes/blockframes/issues/7491

**Comment by cams-goussale** [comment]
| Template name | Old Template id | New template id |
------------------ |-------------------|-------------------|
| AC - Contract - User accepts the offer | `d-5f45ee1375c04ddba84e6dd60664a689` | `d-e127e70b634347788d07cad355421999` 
| AC - Contract - User receives an accepted offer | `d-54c26ec9b0c54039b64bc40255513fba` | `d-df1f3b4ce57c4634961223fa309729dd`|
| AC - Contract - User receives a declined offer | `d-5c4a64135974424592504a5409b35ad8` | `d-b928481ce938423dabb34e50c264d320`|
| AC - Contract - User declines the offer | `d-8227446674064157991ffc8b00b70224` | `d-c32f642c1c2d45f285aa926322518957`
| AC - Contract - User sends a counter offer | `d-ea33a9ce21534aaa99377590c52bf362` | `d-0b967db91fec4ef39f175e373953766c`|
| AC - Contract - Buyer created an offer | `d-1d6a00bab6f448299e9fcdaec7c4c787` | `d-a4ee1970187e4fd8bef47a4008a2267a`|
| AC - Contract - User receives a counter offer | `d-eccc758b6e09492b8449dc218fa762db` | `d-516fc0e2d4094fa9a2afa55e89f0f5a3`|
| AM - ORG - SCREENING REQUEST - Interactions | `d-1a4f08ee48734343bb02f5f3238a5713` | `d-4fbb3fbe74d04353bb7185303969fbf9`|
| AM - ORG - ASKING PRICE REQUEST - Interactions | `d-13c1cbe54bb74a9c9e9ea506db02669f` | `d-107203d5807e48f68e5725518e71354f`|
| AM - BUYER - ASKING PRICE REQUEST - Interactions | `d-fa8f0f0f5799468ca3ac478c7ceeeb68` | `d-51bdd9e408a64cdb8b4dec7704f66267`|
| AM - BUYER - CTA ASKING PRICE - Interactions | `d-ebf41f86fa124978a15b27bec75faf09` | `d-f837688f118046f4bd1f91f43258647c`|
| AM - BUYER - CTA ASK FOR A SCREENING - Interactions | `d-a03d096d252f4c27a500ff16d13f1795` | `d-6de42f37071340b39d8fa3a953ee7ae2`|

**Comment by cams-goussale** [comment]
| Template name | Old Template id | New template id |
------------------ |-------------------|-------------------|
| AC - Contract - Seller receives an offer | d-f7c2e13b7d6b427daf08bdfdf904d697 | d-268b02ed0eb9452ba3acb2a97457d172

**Comment by cams-goussale** [comment]
@Poppe-A hey ! I've found this template which wasn't listed in the initial issue. But it also needs a variable refactoring

**Comment by cams-goussale** [comment]
After the 1st contract was made by Yuki, I realized the correct variable for the org name should be `org.denomination.full` instead of `org.denomination.public` so we updated the templates and the code.
