### ISSUE TITLE
Table filter bug.

### ISSUE THREAD

**Issue by yspringfield** [blockframes/blockframes#7632]
Currently, there's a bug in the table as documented in the first issues [here](https://github.com/blockframes/blockframes/issues/7558#issuecomment-1016427570).

[Here's](https://github.com/blockframes/blockframes/pull/7584/commits/3c13424cb1a0e43ea6643705226d8c6feadb4c3f#diff-313922ca98910bfc1b90ee0fe68a343e350168152d78b8aa257cb345dfaaa8f8R54-R56) a temporal fix to it.
We should look for and correct the root cause of the problem.

**Comment by yspringfield** [comment]
Upon close inspection, I found the culprint.
in `libs/ui/src/lib/list/table/paginator.ts` `maxIndex` getter line 55.

When we search for an entry that doesn't exists in the table,
- `this.size` equals zero which is normal
- `this.pageSize` >= 0 which is normal, but it's most likely greater than 0.

for `this.size` equals `0`and `this.pageSize` greater than `0`, the expression 
`Math.ceil(this.size / this.pageSize)` equals `0`. Which is how javascript functions. 

So I guess, the temporal fix might be the proper fix after all.

**Comment by RemcoSimonides** [comment]
So let's close this issue ;)
