### ISSUE TITLE
Illustrations for deal negotiation emails

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7637]
### Context
We decided to add illustrations on core emails (such as user onboarding and events) and deal negotiation is definitely core for Content!
We have about 10 different emails for deal negotiations but we'll illustrate only 3 different steps: new offer, counter offers, validated offers. 

### What's new
- [x] New offer illustration:
I guess all illustrations should keep a contract document as common object. Here we want to underline the novelty so maybe a glow or something to show that it was created just now. 

- [x] Counter offer illustration:
Here we want to show that it's still the previous contract but new stuff was added or modified. Maybe new line in colours? or like a crossed number with a new one instead (smthg like ~~10,000~~ > 12,500)

- [x] Validated offers:
All good all green maybe a signature or check or confetti party

**Comment by frenchyrules** [comment]
New offer illustration:
![image](https://user-images.githubusercontent.com/85220905/156592794-f85ff563-94d9-4f65-b4a7-a31f3184340f.png)

Counter offer illustration:
![image](https://user-images.githubusercontent.com/85220905/156592918-e1fa929c-6e4c-4e9e-aa7f-1602602ca7b7.png)

Validated offers:
![image](https://user-images.githubusercontent.com/85220905/156593044-8c9eaabb-cae2-4674-bef0-def834f30818.png)

**Comment by cams-goussale** [comment]
@frenchyrules thanks, look nice! Could  you upload the images of Deal nego & Interactions in Sengrid in the `Design Library` section, `image` tab? And please let me know when done so i can update the emails ;)

**Comment by frenchyrules** [comment]
> @frenchyrules thanks, look nice! Could you upload the images of Deal nego & Interactions in Sengrid in the `Design Library` section, `image` tab? And please let me know when done so i can update the emails ;)

All done @cams-goussale ! :)
