### ISSUE TITLE
Illustration for buyer interaction emails

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7638]
### Context
We have new emails that may be introduced more and more for buyers to interact with sellers. Right now they can either ask for a screening or request a price on a title. 
We'd like to add a generic illustration on these emails. 

### What's new
We should illustrate a request (independently of the request object); not sure of that idea but maybe 2 persons discussing with one question mark to underline the question? 
Could be something else :)

**Comment by frenchyrules** [comment]
First proposition @cams-goussale @stephanie-cascade8 
![image](https://user-images.githubusercontent.com/85220905/156386215-92120129-aa0c-4b3b-ba24-77bf1a6f234c.png)

**Comment by stephanie-cascade8** [comment]
> First proposition @cams-goussale @stephanie-cascade8 ![image](https://user-images.githubusercontent.com/85220905/156386215-92120129-aa0c-4b3b-ba24-77bf1a6f234c.png)

can you put it in the context of the corresponding email ?

**Comment by cams-goussale** [comment]
If it can help you @frenchyrules here are the templates concerned by this illu:

[AM - ORG - SCREENING REQUEST - Interactions](https://mc.sendgrid.com/dynamic-templates/d-1a4f08ee48734343bb02f5f3238a5713/version/f4a3cb6a-d136-4c0d-8ece-a2a6a470d899/editor) | you can work with V1

[AM - BUYER - ASKING PRICE REQUEST - Interactions](https://mc.sendgrid.com/dynamic-templates/d-fa8f0f0f5799468ca3ac478c7ceeeb68/version/76b9a0a0-4a3d-4efa-884c-96aba96b8cfb/editor) | you can work with V1

[AM - ORG - ASKING PRICE REQUEST - Interactions](https://mc.sendgrid.com/dynamic-templates/d-13c1cbe54bb74a9c9e9ea506db02669f/version/4c32a59f-6fbd-4818-a22a-064633537e91/editor) | you can work with V1

[AM - BUYER - CTA ASK FOR A SCREENING - Interactions](https://mc.sendgrid.com/dynamic-templates/d-a03d096d252f4c27a500ff16d13f1795/version/eee02836-bacd-4d06-96ac-e43e5bb0ccf9/editor) | you can work with V0 (this email is not sent for the moment)

[AM - BUYER - CTA ASKING PRICE - Interactions](https://mc.sendgrid.com/dynamic-templates/d-ebf41f86fa124978a15b27bec75faf09/version/bd9d9d34-404c-4464-a4da-6a04818448b8/editor) | you can work with V0 (this email is not sent for the moment)

**Comment by frenchyrules** [comment]
![image](https://user-images.githubusercontent.com/85220905/156748265-8f5f9099-7358-4a3d-9644-0ce984b7eb4f.png)
figma file [here](https://www.figma.com/file/1Zxy4d96Vq5tFO17oTKpBK/C8-Sandbox?node-id=126%3A747)

**Comment by cams-goussale** [comment]
@frenchyrules I know we closed this issue, but I got a feedback from the business team a bit late. Would it be possible to put the green triangle pointing to the right? As if it were a play button.

**Comment by Jackseed** [comment]
re-opening this for the slight change (so we don't forget)

**Comment by frenchyrules** [comment]
**Changed file here:**
- [In Google Drive](https://drive.google.com/drive/u/8/folders/1sdJ_76FiiSw4EQVEigpHOyxFvVq2haOI)
- [On figma](https://www.figma.com/file/1Zxy4d96Vq5tFO17oTKpBK/C8-Sandbox?node-id=126%3A747)
