### ISSUE TITLE
Missing Pdf Standard Terms

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7639]
- [x] Creating the offer

![image](https://user-images.githubusercontent.com/93206363/151154080-d2e3df72-83ac-4fb3-9f1d-ab45ef1441ab.png)

- [x] Marketplace offer page
![image](https://user-images.githubusercontent.com/93206363/151155700-0d1ec450-e597-49d6-aba8-ed185878a2c5.png)

- [x] Dashboard contract page
![image](https://user-images.githubusercontent.com/93206363/151155964-17967f14-46cf-463d-ad91-2d372ff6b276.png)

**Comment by RemcoSimonides** [comment]
I see you created screenshot of the links leading to this page 
![image](https://user-images.githubusercontent.com/27687382/151169735-71876b2b-f498-406f-9563-5767c7126fc5.png)
On which the PDF file didn't work. Correct?

**Comment by cams-goussale** [comment]
yes exactly, the PDF was not showing. It does open a page, but with no PDF file
