### ISSUE TITLE
Marketplace movie view - Avails - Add a 'no mandate' state 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#7646]
### Context
pages: `/c/o/marketplace/title/{{titleId}}/avails/map` & `/c/o/marketplace/title/{{titleId}}/avails/calendar`
Avails are always the last thing to come when importing new titles to AC. Currently, business developers prefer not to display titles that don't have avails in the marketplace because they would be marked as "Not licensed", which is inaccurate. 
Because of that, there are tens of new titles that are not displayed even if their metadata are filled in. 

### What's new
We should introduce a new state on the avails tab which is triggered only when **there is no mandate on the title**.
Then it should
- [ ] Disable the avails form
- [ ] Change the text in the overlay for: "Avails to be ready soon on this Title" 
- [ ] Do it for both map & calendar views
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/34c6ad3c-7e7a-474d-9daf-0baafc8b272b)
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/c78355e3-e330-4270-8b84-75c217c3363c)

**Comment by RemcoSimonides** [comment]
The sentence "Avails are coming soon for this Title" would make more sense to me
@maltmayer what do you think?

**Comment by maltmayer** [comment]
I would just put "Avails coming soon" :)
