### ISSUE TITLE
[NFT] Banner collection

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7669]
For the launch of the first NFT campagin, we will need to complete the FilmSeriesNFT collection. The collection page looks like that:

![image.png](https://images.zenhubusercontent.com/617811d92b89e7733866d8a0/6e6bbd6c-4ef3-4f82-871e-0d2c92fad599)

We need a to create a banner at the top. Let's keep the same vibe & visual as the [current app](https://www.filmseriesnft.com/). OpenSea recommends a 1400x400 size.

A "complete page" looks like that:
![image](https://user-images.githubusercontent.com/93206363/151527913-4672802b-6b56-4d45-a24c-b9e5a9d8cfd8.png)

**Comment by frenchyrules** [comment]
First banner proposal. 1400x400 size.
![Nft background](https://user-images.githubusercontent.com/85220905/151963737-c056ad3e-79cb-4467-b68f-cc7c40f29054.png)

**Comment by cams-goussale** [comment]
so fast! lgtm already :) don't have much to add!

**Comment by frenchyrules** [comment]
Smaller sized icons + Linear gradient. I think this is the version where the logo stands out the most 
![Group 3](https://user-images.githubusercontent.com/85220905/151979355-c18c37b2-eef0-4aae-8e91-26a658a21924.png)

**Comment by frenchyrules** [comment]
Banner png can be found [here](https://drive.google.com/file/d/1duGBfwuzIbyiAh1FuY2QvGl-MbxDlPx2/view?usp=sharing)
