### ISSUE TITLE
When a contract is In Negotiation, there have been side effects on its status.

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7687]
- [ ] When a contract is In Negotiation, there have been side effects on its status.

1. it doesn't appear in CRM contract view (see video)
2. the contract status stays in "NEW" but it should be "NEGOTIATING" (see screenshot)

https://user-images.githubusercontent.com/93206363/148056202-9390fd39-6a4b-46a9-8296-d99f8db3096e.mp4

![image](https://user-images.githubusercontent.com/93206363/148067030-ac08cbb3-4f12-4050-8409-a73aa91db497.png)

_Originally posted by @cams-goussale in https://github.com/blockframes/blockframes/issues/7482#issuecomment-1004750348_

**Comment by RemcoSimonides** [comment]
Check if it's still an issue though

**Comment by yspringfield** [comment]
I just verified, it functions well.

**Comment by yspringfield** [comment]
Closing for now.
