### ISSUE TITLE
Notifications are cut if too long

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7716]
### Context
When reading notifications in a small screen, the "..." is shown after a certain number of characters. We shall find a solution for the user to extend the notification, or click on a read more button to see it completely.

### Images
![image](https://user-images.githubusercontent.com/93206363/152755949-bef14706-294a-4b30-b7c5-cfa8bb48f10b.png)

**Comment by 2amarkina** [comment]
Reflexion started in this issue [#6768](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/6768)

**TO DO:** 

@2amarkina 
- [ ] clean up notifications (make the list of all existing ones)

@frenchyrules 
- [ ] check the specific actions instead of "More details"

**Comment by 2amarkina** [comment]
[Work in progress here](https://docs.google.com/spreadsheets/d/1b1K7YfnquxnfCgGGPxIz5ZNIjr9eK_bUrRJqLvPYGIk/edit#gid=874886288)

**Comment by 2amarkina** [comment]
- [ ] re-check the notification logic (Thursday, Friday notifications and the Last week notifications create duplicates)

**Comment by frenchyrules** [comment]
> * [ ]  re-check the notification logic (Thursday, Friday notifications and the Last week notifications create duplicates)

Recent notifications (<24h) are marked in "new" category, and anything older than that goes into "earlier" category
![image](https://user-images.githubusercontent.com/85220905/153382987-68b933a3-57f0-4d87-94fd-643048f77a09.png)

**Comment by cams-goussale** [comment]
- [ ] No dev required
- [ ] Business check to make notif smaller (max 80 characters)
- [ ] Product Inventory
