### ISSUE TITLE
Avails date in custom CMS link

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7724]
In CMS, we can set up the redirection to the /library page filtered by some parameters. Currently, Yuki set it up in catalog app, so that user is redirected either to Feature films, either to TV shows.

![image.png](https://images.zenhubusercontent.com/617811d92b89e7733866d8a0/4bb8a689-12fa-4518-a9d3-0fc431846350)

The problem is that the **avails start date** is saved at the date when she set up the link in CMS, which makes the start date in the past. Is there a way to include in the CMS link that avails start date == today?

This is the link we put for Feature films button:
`../title?formValue=%7B"search":%7B"query":"","genres":%5B%5D,"originCountries":%5B%5D,"contentType":"feature_film"%7D,"avails":%7B"medias":null,"exclusive":true,"territories":%5B%5D,"duration":%7B"from":"2022-02-03T23:00:00.000Z","to":"2023-02-03T23:00:00.000Z"%7D%7D%7D`

This is the one for TV Shows:
`../title?formValue=%7B"search":%7B"query":"","genres":%5B%5D,"originCountries":%5B%5D,"contentType":"series"%7D,"avails":%7B"medias":null,"exclusive":true,"territories":%5B%5D,"duration":%7B"from":"2022-02-03T23:00:00.000Z","to":"2023-02-03T23:00:00.000Z"%7D%7D%7D`

**Comment by RemcoSimonides** [comment]
For dev: Something is similar with the `startAt` property. This can be set to "now". Check out how that works and do something similar for the where queries.
`libs/utils/src/lib/pipes/cms.pipe.ts`
