### ISSUE TITLE
async & transactions are unsafe

### ISSUE THREAD

**Issue by laurentsenta** [blockframes/blockframes#773]
Some transactions are invalid, code gets data outside of the transaction context which makes it useless and unsafe.

- [ ] teach the team about firestore transactions & batches
- [ ] fix cases where transactions are incorrect

**Comment by Jackseed** [comment]
- [ ] @lsenta Prepare a presentation for the team

**Comment by GrandSchtroumpf** [comment]
Note: 
On the frontend, `akita-ng-fire` uses batch & transaction by default
ex with Batch
```typescript
onUpdate(updated, { write }) {
  write.set(...) // write is a batch from the update function below
}
...
service.update({ name: 'blockframes' }) // uses batch to update the entity
```
ex with Transaction 
```typescript
service.update(entity => ({ count: entity.count + 1 })) // uses Transaction to update the entity
```

**Comment by Jackseed** [comment]
@phpgeekfr @pldespaigne  is it still an open issue?
