### ISSUE TITLE
[Seller's onboarding] AC Landing Page

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7733]
### Description

Yuki is struggling to onboard Sellers on the platform, due to the legal agreement we currently have in place: the `MRA`. The solution we've found is to change this legal agreement and use a `Representation agreement` instead.

What's the main impact? AC can no longer do Package Deals for Buyers. So we need to review the landing page to reflect this branding change.

### What's new

The arguments of the landing will be changed. Also the structure: in the end, the business suggests a mix between the surfaces we have on AM and AC.

1/ The new header "Archipel Ecosystem" (part of the Bridges) - `no change`
2/ The header "[Welcome to Archipel Content](https://docs.google.com/presentation/d/1CahzMzL38DPoG_8uo8qERPFguaaZ-OdjMfXXsGjM0Yk/edit#slide=id.ge5b888a01d_0_0)" - `some wording changes`
3/ "Deals made easy" section with the 2 tabs Buyer / Seller - `changes to make it similar to AM`

3.1 [Sellers](https://docs.google.com/presentation/d/1CahzMzL38DPoG_8uo8qERPFguaaZ-OdjMfXXsGjM0Yk/edit?pli=1#slide=id.g113a02f4c11_3_0):

- [ ] 1 animation with descriptive text on the right
- [ ] 3 features in the form of cards similar to AM
- [ ] 2 user benefits with the surfaces similar to AC 

3.2 [Buyers](https://docs.google.com/presentation/d/1CahzMzL38DPoG_8uo8qERPFguaaZ-OdjMfXXsGjM0Yk/edit?pli=1#slide=id.g113a02f4c11_3_22):

- [ ] 1 animation with descriptive text on the right
- [ ] 3 features in the form of cards similar to AM
- [ ] 2 user benefits on one surface  similar to AC 

4/ Hero section "Subscribe for free" - `no change`
5/ Our Expertise section - `no change`
6/ Hero section for the Demo - `no change`
7/ Footer - `no change`

**Comment by stephanie-cascade8** [comment]
Hello :) New mockups are here:
[Seller](https://www.figma.com/file/PGobBB7H317PZO326rCLcz/Landing?node-id=192%3A1068)
[Buyer](https://www.figma.com/file/PGobBB7H317PZO326rCLcz/Landing?node-id=194%3A5425)

**Comment by cams-goussale** [comment]
Cool! Here are my feedbacks. You can wait before making any change, let me talk to Business first.

On Seller's part:

- [ ] This illu has a typo, should be International title. Also I'm not sure we understand the black play triangle?

![image](https://user-images.githubusercontent.com/93206363/154725145-ce3c8e83-0d3e-46c5-bf91-10eddce55439.png)

On Buyer's part:

- [ ] The first section is about Sellers
- [ ] The features have the wrong text. The illu are ok to keep but the text should match what's in the [slides](https://docs.google.com/presentation/d/1CahzMzL38DPoG_8uo8qERPFguaaZ-OdjMfXXsGjM0Yk/edit#slide=id.g113a02f4c11_3_22).

![image](https://user-images.githubusercontent.com/93206363/154725657-3dac6211-840c-4c19-8d70-de7d3ae77f53.png)

**Comment by stephanie-cascade8** [comment]
@cams-goussale corrections are done. For the illustration "Save time, get results", I prefer having this mail notif thing (I think it is clearer and less repetitive with other illus), but I can change it quickly if that is not ok for you. 

Little detail, but do you want me to take of the mouse triangle in the illu "easy export"?

**Comment by cams-goussale** [comment]
@stephanie-cascade8 all good on the changes you made ('international title' and the new illu for 'save time, get results').

About the mouse triangle: my bad, i did not understand it was a mouse. It's a mac mouse, right? maybe a hand would be more universal? or maybe it's just me..

Last thing, I think the Buyer's first features are reversed (Red should come first and Green second).
The export/share arrow should come here, sorry for the confusion. You can leave it also in the Curated Content part, it's fine for me.

![image](https://user-images.githubusercontent.com/93206363/154998521-b3c40c25-432b-499f-925f-dd65f61707c6.png)

**Comment by stephanie-cascade8** [comment]
> @stephanie-cascade8 all good on the changes you made ('international title' and the new illu for 'save time, get results').
> 
> About the mouse triangle: my bad, i did not understand it was a mouse. It's a mac mouse, right? maybe a hand would be more universal? or maybe it's just me..
> 
> Last thing, I think the Buyer's first features are reversed (Red should come first and Green second). The export/share arrow should come here, sorry for the confusion. You can leave it also in the Curated Content part, it's fine for me.
> 
> ![image](https://user-images.githubusercontent.com/93206363/154998521-b3c40c25-432b-499f-925f-dd65f61707c6.png)

ok! It's done as well :)

**Comment by cams-goussale** [comment]
Thanks @stephanie-cascade8 it's a GO from Business :partying_face:
Let's not forget the little modification on the animation (for Buyers) by @frenchyrules 

And then, let's send to dev

**Comment by frenchyrules** [comment]
Animation modification done @cams-goussale 
[video here](https://drive.google.com/drive/u/8/folders/1_rT1lQiSMW6RTFAY_Qq677yDKmjZ7CjK)
