### ISSUE TITLE
[Seller's onboarding] Reviewing Emails & Notifications

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7742]
### Description

Yuki is struggling to onboard Sellers on the platform, due to the legal agreement we currently have in place: the `MRA`. The solution we've found is to change this legal agreement and use a `Representation agreement` instead.

What's the main impact? AC can no longer do **Package Deals for Buyers**. So we need to modify some Emails & Notifications that are being sent during the flow.

### What's new

- [x] These emails are related to the Package deal for Buyer. They must be desactivated, meaning they shouldn't be sent.
[Buyer receives summary of all contracts (all declined)](https://mc.sendgrid.com/dynamic-templates/d-c92f8799273f497cb2256eb6ed8baa78/version/8f18eade-21f0-48df-9ec7-47db6324bc17/editor) - `template id : d-c92f8799273f497cb2256eb6ed8baa78`
[Buyer receives summary of all contracts (at least 1 accepted)](https://mc.sendgrid.com/dynamic-templates/d-4f067ef3abca42cc9d8dc25b57935ccc/version/17913ecb-1a68-4483-805d-5442841f2863/editor) - `template id : d-4f067ef3abca42cc9d8dc25b57935ccc`
[Seller receives confirmation his offer is now under signature](https://mc.sendgrid.com/dynamic-templates/d-38ee6949f4724b1c8796b8df9229f21d/version/19b7e9e9-47d5-4d76-a0d9-511b65f6bb66/editor) - `template id : d-38ee6949f4724b1c8796b8df9229f21d`

- [x] The corresponding notifications of these emails also need to be desactivated. I do not know the id of the notification, I can only link to the excel with the text.
[Buyer receives summary of all contracts (at least 1 accepted)
](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=657134932&range=C20)[Seller receives confirmation his offer is now under signature](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=657134932&range=A20)

- [x] These emails need a few wording changes.
[Buyer created an offer](https://mc.sendgrid.com/dynamic-templates/d-f7c2e13b7d6b427daf08bdfdf904d697/version/d077abe3-385f-4ef3-9bb6-35f79d3cabab/editor) - `templage id d-1d6a00bab6f448299e9fcdaec7c4c787` - new subject with variables - ok
[Seller receives the offer](https://mc.sendgrid.com/dynamic-templates/d-f7c2e13b7d6b427daf08bdfdf904d697/version/d077abe3-385f-4ef3-9bb6-35f79d3cabab/editor) - `template id d-f7c2e13b7d6b427daf08bdfdf904d697` - new subject with variables - ok
[User sends a counter-offer](https://mc.sendgrid.com/dynamic-templates/d-ea33a9ce21534aaa99377590c52bf362/version/30a475e4-2a92-444f-9389-49f045fb66bd/editor) - `template id d-ea33a9ce21534aaa99377590c52bf362` - new subject with variables - ok
[User receives a counter-offer](https://mc.sendgrid.com/dynamic-templates/d-eccc758b6e09492b8449dc218fa762db/version/7ba1f628-e102-43dc-b95d-e14b6edf3d2b/editor) - `template id d-eccc758b6e09492b8449dc218fa762db` - [new text] - ok    (https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=2095735367&range=E6:F6) + new subject with variables
[User accepts the offer](https://mc.sendgrid.com/dynamic-templates/d-5f45ee1375c04ddba84e6dd60664a689/version/cab79b50-e23d-4266-b98b-d85dd6fe0eca/editor) - `template id d-5f45ee1375c04ddba84e6dd60664a689` - [new text](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=2095735367&range=E7:F7)
[User receives an accepted offer](https://mc.sendgrid.com/dynamic-templates/d-54c26ec9b0c54039b64bc40255513fba/version/0569d36e-753d-421b-8369-d2e677b08c0a/editor) - `template id d-54c26ec9b0c54039b64bc40255513fba` - [new text](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=2095735367&range=E8:F8) + new subject with variables
[User declines the offer](https://mc.sendgrid.com/dynamic-templates/d-8227446674064157991ffc8b00b70224/version/c936006a-197f-4609-8f3d-d13c5de80214/editor) - `template id d-8227446674064157991ffc8b00b70224` - [new text](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=2095735367&range=E9:F9)
[User receives a declined offer](https://mc.sendgrid.com/dynamic-templates/d-5c4a64135974424592504a5409b35ad8/version/87e1501a-0522-401a-acff-cc6e13660b5e/editor) - `template id d-5c4a64135974424592504a5409b35ad8` - [new text](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=2095735367&range=E10:F10)

- [x] These notifications need some improvements to be completed ([column G](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=2095735367&range=G2:G10)).
Buyer makes an offer
Seller receives the offer
User sends a counter-offer
User receives a counter-offer
User accepts the offer
User receives an accepted offer
User declines an offer
User receives a declined offer

- [x] Some new admin emails should be sent ([column J](https://docs.google.com/spreadsheets/d/1OflJnj5dcEyWeorBVhHsIqWSovRldJpk5yYd20U5_Mw/edit#gid=2095735367&range=J3:J10)). Can be similar to what is sent to users.
User sends a counter offer - `template id d-ac1dfcbf692d4ef8888ccad9b6938c8e`
User accepts the contract - `template id d-6750c3d980834301a057403668deceed`
User declines the contract - `template id d-fba5c684bdbc4187b27b82e2ba703a2a`

**Comment by cams-goussale** [comment]
@2amarkina I push this issue directly into Business review. Deadline for Yuki to give us a legal feedback is 10th March at the latest. Also asking Marie & Aurore for text check in parallel.

**Comment by RemcoSimonides** [comment]
Blocked by #7624

For #7624 Camille created new version of the email in Sendgrid with the new variables names already. So maybe it's easier to first fix #7624 before implementing the changes for this issue.
