### ISSUE TITLE
[Seller's onboarding] Adding some legal validations during the flow

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7743]
### Description

Yuki is struggling to onboard Sellers on the platform, due to the legal agreement we currently have in place: `the MRA`. The solution we've found is to change this legal agreement and use a `Representation agreement` instead.

What's the main impact? With the MRA, AC was actually in a position of a "seller", meaning we were receiving the payment from the Buyer, keeping our commission and redistributing the rest to the Seller. Now with this new Rep agreement, we won't be in that position. The Seller will have to ask the Buyer to do a "direction to pay". A direction to pay means the Buyer will make 2 payments: 1 to the Seller, and 1 to Archipel Content (our fee).

So what's the problem? This works well on paper. But the truth is we're losing control over the payment process, and we're risking that some Buyer's just won't pay us.

What's the solution? We want to be pushy and remind the user during the negotiation flow that s.he agreed to these conditions at the account creation (in the CGV).

### What's new

1/ Seller has received an offer for the first time. Want to see the offer? You need to:

- [x] Add your phone number to your profile so the Archipel team can contact you

<img width="613" alt="image" src="https://user-images.githubusercontent.com/93206363/153464310-5908852c-403a-4c7b-8dfb-2231e40b5e6c.png">

2/ After the ping-pong of counter-offers, the Seller finally accepts the Contract. Before the click on Validate, he must:

- [x] Acknowledge that, according to the CGV he agreed on, he must agree on the conditions of the Representation agreement
- [x] Acknowledge that, according to the CGV he agreed on, he must agree on the conditions of the Direction to pay

<img width="346" alt="image" src="https://user-images.githubusercontent.com/93206363/153464601-0b053c7b-b5ba-4b72-bb84-a41753a4dc25.png">

3/ After the ping-pong of counter-offers, the Buyer finally accepts the Contract. Before the click on Validate, he must:

- [x] Acknowledge that, according to the CGV he agreed on, he must proceed to a Direction to pay

<img width="536" alt="image" src="https://user-images.githubusercontent.com/93206363/153465004-91e92544-bb76-4f7b-b959-679184854841.png">

4/ After the ping-pong of counter-offers, the Seller finally declines the Contract. Before the click on Decline, he must:

- [x] Acknowledge that, according to the CGV he agreed on, he must apply the Representation agreement conditions & the Direction to pay in case any deal happens with this Buyer on this title during the next following year.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/93206363/153465602-cfa344bd-1f09-4e75-bfbc-b27a31526817.png">

5/ After the ping-pong of counter-offers, the Buyer finally declines the Contract. Before the click on Decline, he must:

- [x] Acknowledge that, according to the CGV he agreed on, he must apply the Direction to pay in case any deal happens with this Seller on this title during the next following year.
<img width="508" alt="image" src="https://user-images.githubusercontent.com/93206363/153465835-5970896a-81f9-4915-9062-39329ad9e2a2.png">

**Comment by 2amarkina** [comment]
[Work in progress is here ](https://www.figma.com/file/bs1vDcQEjbqqPggOYMpdd6/%E2%9C%85-Deal-Negotiation-(DONE))

**Comment by 2amarkina** [comment]
**Last wireframes are here:** 
_N.B. Be aware that the texts might be changed._ 

- [Seller accepts an Offer](https://www.figma.com/file/bs1vDcQEjbqqPggOYMpdd6/%E2%9C%85-Deal-Negotiation-(IN-PROGRESS)?node-id=1431%3A77345)
- [Seller declines an Offer ](https://www.figma.com/file/bs1vDcQEjbqqPggOYMpdd6/%E2%9C%85-Deal-Negotiation-(IN-PROGRESS)?node-id=461%3A124665)
- [Buyer accepts a counter-offer](https://www.figma.com/file/bs1vDcQEjbqqPggOYMpdd6/%E2%9C%85-Deal-Negotiation-(IN-PROGRESS)?node-id=464%3A142440)
- [Buyer declines a counter-offer](https://www.figma.com/file/bs1vDcQEjbqqPggOYMpdd6/%E2%9C%85-Deal-Negotiation-(IN-PROGRESS)?node-id=464%3A152137)
- [Seller received an Offer for the first time ](https://www.figma.com/file/bs1vDcQEjbqqPggOYMpdd6/%E2%9C%85-Deal-Negotiation-(IN-PROGRESS)?node-id=1531%3A71045)

**Comment by cams-goussale** [comment]
@2amarkina if you want to update the wireframes, we'll go with this sentence in the checkbox:

`I hereby accept the policy regarding accepted offers, as mentioned in the GCS.`
`I hereby accept the policy regarding declined offers, as mentioned in the GCS.`

(with link on the word CGS)

**Comment by Poppe-A** [comment]
The code is finished, i'm just waiting for the new legal terms to be ready (#7938) before merging it.

**Comment by frenchyrules** [comment]
Page transfer inventory and process:

- [ ] Main
- [ ] Buyer
- [ ] Seller
- [ ] Asking Price
