### ISSUE TITLE
Auth form - rework

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7746]
It has been raised several time that the Auth form could use some clarifications to improve user behavior. Nicolas recently pointed out that he hadn't select a Role (forgot to do so) and he did not have any error message to point out what was the issue. Also in the past, it has been mentionned that a stepper would be cleared for the user, to walk him/her through the form.

In parallel, we're having some discussions together with AC Seller's Onboarding Epic about whether or not this form can be app specific. Could we clarify the rules? Could we check if the current Terms and Conditions are app specific or cross app? Also what would be the impact of having CGV on AC, but not on AM?

**Comment by cams-goussale** [comment]
![image](https://user-images.githubusercontent.com/93206363/153562635-4cd75a0a-0299-412b-ab0f-45761739eea5.png)

**Comment by 2amarkina** [comment]
[Work in progress is here](https://www.figma.com/file/UMbfjswSE7stwg4riRLOjH/%E2%9C%85Easier-connection-flow-(IN-PROGRESS)?node-id=2205%3A7538)

**Comment by 2amarkina** [comment]
**This issue contains three main axes:**

**1. Improving the "choose your role" section.** 
All the fields on this page are mandatory. So, the simplest solution would be to add a tooltip on hover on the "Sign up" CTA. Tooltip text proposal: "Please fill in all the fields" 
![Снимок экрана 2022-02-22 в 17.11.00.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/8efcdb56-62ec-4c69-b1d4-540d3b448625)

**2. Auth rework - Request Access to other app** 
This bloc is pretty big. The following obstacles were detected, some ideas were discussed but need further digging. 
- We see that the T&C are app specific, so a user needs to accept then while request access to other app. 
- Same concerns the Data Privacy. Even if the text is the same and only the app name changes, the privacy policy should be accepted on the user's level. 
- All the org members go automatically to the new app, if requested, but they still need to accept the T&C and DP. 
The solutions for today: send all users a mail that one of the members requested access, block the users on the "acceptance page". 

**3. The Stepper Solution**
This one was seen and discussed and decided to put it aside for the moment.

@cams-goussale maybe we need to create a special issue for "role" and keep this one as a big one for Auth rework? or vice versa?

**Comment by 2amarkina** [comment]
The issue about the improving of "Create you account" page is created [here #7825](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/7825)

**Comment by 2amarkina** [comment]
[Work in progress](https://www.figma.com/file/UMbfjswSE7stwg4riRLOjH/%E2%9C%85Easier-connection-flow-(IN-PROGRESS)?node-id=2205%3A7538)

**Comment by cams-goussale** [comment]
After the business call, here are the final decisions @2amarkina :

- No major change on the current Auth flow
- In case a user hasn't agreed to CGV or CGU or Privacy Policy, find a way to have him/her accept them before entering the app (modale / page...). See how this can co-exist with the Buyer Preferences modale.
- For @cams-goussale : let's review the wording of the email sent to users when they have access to new org. Maybe we could update it a bit.

- For devs: Need for an change in db to make the Privacy Policy app specific. We should also track the acceptance of CGV, CGU (currently I don't think we do). And since we're on it, is it possible to have a kind of versionning? Each time we change our CGV / CGU / Privacy policy, could we know if user accepted V1, but not V2, etc ?

**Comment by 2amarkina** [comment]
Ready to go for dev, all wireframes can be found [here](https://www.figma.com/file/UMbfjswSE7stwg4riRLOjH/%E2%9C%85-Easier-connection-flow-(IN-PROGRESS)?node-id=2205%3A7538)

On the design level the idea is to add a supplementary page  яшер T&C acceptation when an org has requested access to another app. 

Also in this issue we've taken into account the issue [#7034](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/7034) with a "make my email secret"

**Comment by frenchyrules** [comment]
UI in progress [here](https://www.figma.com/file/ODvbgSYOb0OyVK6WWVp3NU/Connection-flow?node-id=5%3A222)

**Comment by 2amarkina** [comment]
**After business review** 
- [ ] For the consistency reasons we need to take out the titles from the surfaces during the request access flow, if ok for @stephanie-cascade8 . 
[The wireframes could be found here](https://www.figma.com/file/UMbfjswSE7stwg4riRLOjH/%E2%9C%85-Easier-connection-flow-(IN-PROGRESS)?node-id=2205%3A7538)

- [ ] On the wireframes we can find the propositions of new text that should be validated with business team 

- [ ] Illustrations might be also updated within this issue

**Comment by frenchyrules** [comment]
During dev review, @GrandSchtroumpf  recommended that we animate the hot air balloon illustration by having the illustrations as separate layers in background position. 

- [ ] The animation steps will be detailed in the figma file.

- [ ] move "almost there!" outside of surfaces

**Comment by frenchyrules** [comment]
- Illustrations were updated and can be found [here](https://www.figma.com/file/Yi5RKQuroGJtpnPUCcAO67/Assets?node-id=373%3A586)
- supplementary T&C acceptation page [here](https://www.figma.com/file/ODvbgSYOb0OyVK6WWVp3NU/Log-in%2FSign-up?node-id=146%3A2344)

**Comment by cams-goussale** [comment]
Dedicated dev issue here #8282
