### ISSUE TITLE
Title publish preview

### ISSUE THREAD

**Issue by frenchyrules** [blockframes/blockframes#7747]
Include a button allowing the user to preview their title before publishing it in the movie tunnels. Possibly also a button once the title has been succesfully published, that says "click here to see it on the marketplace". The latter could appear everytime as a button, or maybe just once as a snackbar or callout, when the user publishes a title for the first time.

**Comment by 2amarkina** [comment]
Should be cross-app and should be done within AM, AC, MF

**Comment by 2amarkina** [comment]
The work with this part should be done using the Movie Tunnel elements: sidenav, layout etc. 

The necessary elements could be found[ here ](https://www.figma.com/file/qpLBi85x3y0s4fLpJPACOm/%5B-Wireframing-Elements-%5D?node-id=2137%3A9221)

**Comment by frenchyrules** [comment]
- [ ]  Change button text to adapt for content and financiers
- [ ] Check with a dev if clicking Marketplace preview button will cause save problems

**Comment by frenchyrules** [comment]
From Dev review:

Right now it would work best as a Archipel market only feature, as the "marketplace preview" button takes us away from the dashboard and onto the marketplace page. 

Making this cross app would require importing the marketplace page to the dashboard for the financiers and content app, and while it may be technically doable it will be very time consuming to do, and may not be worth it in terms of time investment and effort to reward ratio.
