### ISSUE TITLE
[E2E] Auth Identity Page ( /auth/identity )

### ISSUE THREAD

**Issue by n-germain-work** [blockframes/blockframes#7751]
- [x] Fill in all fields correctly (pass)
- [x] Fill with an existing company (pass)
- [x] Fill in all fields except one - do this for all available fields (fail)
- [x] Fill in an already used email address (fail)
- [x] Fill in an wrongly formatted email address (fail)
- [x] Fill in different passwords in the password and confirm password field (fail)
- [x] Fill in a password containing less than 6 characters (fail)
- [x] Fill in a password containing more than 24 characters (fail)

**Comment by phpgeekfr** [comment]
check duplicates or other scenarios from catalog `landing/account-creation.spec.ts`
