### ISSUE TITLE
Release 4.0 - Organisation

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7758]
[Organisation test scenarios](https://www.notion.so/cascade8/Organisation-55ded6f0e09c4aa29fb2e3f716bb8b50)

Akita has been removed for Invitations, Notifications, Meeting (Twilio), Contract, Bucket, Offer, Income, Campaign, Organisation, Permissions, User & Auth. This means that anything can be broken. For example some parts of the page don't load or missing information on pages. Let's find what has been broken if anything! :)

**Comment by Poppe-A** [comment]
CRM :
Deleting a user doesn't work everytime. Form validation prevents click on delete, or there is a firebase error.

**Comment by cams-goussale** [comment]
- [ ] (A) CRM: it seems that the /users and /organisation pages only display 1 row of data

**Comment by RemcoSimonides** [comment]
> * [ ]  (B) CRM : Deleting a user doesn't work everytime. Form validation prevents click on delete, or there is a firebase error.

@Poppe-A You wrote down this issue under Organisation. Did you remove the user from the Organisation via CRM? Or did you delete the users from the User page on CRM?
I've tried both and it's working for me... So I'm curious what exactly you did which didn't work

**Comment by cams-goussale** [comment]
>  (A) CRM: it seems that the /users and /organisation pages only display 1 row of data

Seem fixed after the deploy on staging made on monday
