### ISSUE TITLE
Release 4.0 - Wishlist

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7760]
[Wishlist test scenarios](https://www.notion.so/cascade8/Wishlist-c0141971a24c44afa6df11fbd6689cc7)

Akita has been removed for Invitations, Notifications, Meeting (Twilio), Contract, Bucket, Offer, Income, Campaign, Organisation, Permissions, User & Auth. This means that anything can be broken. For example some parts of the page don't load or missing information on pages. Let's find what has been broken if anything! :)

**Comment by yspringfield** [comment]
All tests were successful without any hic.
