### ISSUE TITLE
Release 4.0 - File explorer

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7761]
[File explorer test scenarios](https://www.notion.so/cascade8/File-Explorer-08ea83d7e82f437c9b96e22e87d8df7c)

Akita has been removed for Invitations, Notifications, Meeting (Twilio), Contract, Bucket, Offer, Income, Campaign, Organisation, Permissions, User & Auth. This means that anything can be broken. For example some parts of the page don't load or missing information on pages. Let's find what has been broken if anything! :)

**Comment by Poppe-A** [comment]
The file page is not working `Cannot read properties of null (reading 'id')`

**Comment by RemcoSimonides** [comment]
> The file page is not working `Cannot read properties of null (reading 'id')`

Fixed ☝️  once we have new version on staging we can test again
