### ISSUE TITLE
Release 4.0 - Deal Negotiation

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7767]
[Deal negotiation test scenarios](https://www.notion.so/cascade8/Deal-Negotiation-ce5198d8e0904b91a6bf1a2500376dd1)

Issues fixed for the release
- [x] https://github.com/blockframes/blockframes/issues/7389
- [x] https://github.com/blockframes/blockframes/issues/7571
- [x] https://github.com/blockframes/blockframes/issues/7633
- [x] https://github.com/blockframes/blockframes/issues/7641

Akita has been removed for Invitations, Notifications, Meeting (Twilio), Contract, Bucket, Offer, Income, Campaign, Organisation, Permissions, User & Auth. This means that anything can be broken. For example some parts of the page don't load or missing information on pages. Let's find what has been broken if anything! :)

**Comment by yspringfield** [comment]
The email sent to blockframes admin when a new offer is created seems a buggy. As can be seen in the below image, we receive two emails at once. One wrongly parsed and another  appropriately parsed.
<img width="1118" alt="Bildschirmfoto 2022-02-16 um 9 35 46 AM" src="https://user-images.githubusercontent.com/22674720/154228974-fb014675-046c-4cb0-a169-b19746d2bc00.png">
<img width="1118" alt="Bildschirmfoto 2022-02-16 um 9 46 18 AM" src="https://user-images.githubusercontent.com/22674720/154228996-4e45bfb6-1a9f-44c3-a3f1-b468447205d2.png">

**Comment by cams-goussale** [comment]
- [ ] The Org names in the Contract table of /c/o/marketplace/offer/[offerId] are wrong. Here the blue and green lines are from different Orgs and yet they show the same name. Blue row should be from `Kautzer LLC`

<img width="780" alt="image" src="https://user-images.githubusercontent.com/93206363/154240015-8de6958d-5318-4f88-ba56-46481da9e73b.png">

**Comment by cams-goussale** [comment]
- [ ] When logged in with dev+mike-eha@blockframes.io , permission error on c/o/dashboard/sales and the list does not load : `FirebaseError: Missing or insufficient permissions.`

<img width="832" alt="image" src="https://user-images.githubusercontent.com/93206363/154302886-f6017c7e-ff58-4b82-9fd9-37946d94b1a4.png">

**Comment by cams-goussale** [comment]
> (A) When logged in with dev+mike-eha@blockframes.io or dev+rosalee-sru@blockframes.io, permission error on c/o/dashboard/sales and the list does not load : FirebaseError: Invalid document reference. Document references must have an even number of segments, but orgs has 1.

@yspringfield  this review is still happening after a new deploy to staging on monday afternoon. Is it linked to the users specifically?


https://user-images.githubusercontent.com/93206363/154983081-7cf649e5-03cd-4af2-876f-fc63782a39e7.mp4

**Comment by RemcoSimonides** [comment]
> > (A) When logged in with [dev+mike-eha@blockframes.io](mailto:dev+mike-eha@blockframes.io) or [dev+rosalee-sru@blockframes.io](mailto:dev+rosalee-sru@blockframes.io), permission error on c/o/dashboard/sales and the list does not load : FirebaseError: Invalid document reference. Document references must have an even number of segments, but orgs has 1.
> 
> @yspringfield this review is still happening after a new deploy to staging on monday afternoon. Is it linked to the users specifically?
> 
>  not.loading.mp4

Ah, last friday Springfield and I did some investigation into this one. It is caused because of a wrong import. The wrong organisation name was used for one of the contracts if I remember correctly. Without an incorrect import, this bug doesn't happen. It would be nice to make it impossible to import incorrect data. @yspringfield could you make the issue with the detailed explanation and possible solution?

**Comment by cams-goussale** [comment]
I think the mistake I made in the excel import is the cause of this review. But it concerns a different title.
> (A) The Org names in the Contract table of /c/o/marketplace/offer/[offerId] are wrong. Here the blue and green lines are from different Orgs and yet they show the same name. Blue row should be from Kautzer LLC




The sales page not loading is a different cas. There wasn't any mistake in the excel import. Here is what I did:
1- Imported 5 Movies for the org `Rolfson - Gusikowski` with user id `oRlMomSwLIO89J39Qa60g8PzRTt2`
2- In CRM, add the Org Id of `Jacobson and Sons` to Movie 2

So we have [Movie 2 MpiVmlIFsZbmjw2r1Afl](https://staging-blockframes-crm.web.app/c/o/dashboard/crm/movie/MpiVmlIFsZbmjw2r1Afl) with 2 org Ids, which should be possible. But now, none of the users of each org (`dev+mike-eha@blockframes.io` and `dev+rosalee-sru@blockframes.io`) can see the titles page or the avails, as [mentionned in this review](https://github.com/blockframes/blockframes/issues/7766#issuecomment-1041471440).

**Comment by yspringfield** [comment]
Hi here, 
The issue is properly detailed [here](https://github.com/blockframes/blockframes/issues/7810#issue-1146554643). @cams-goussale , a good way to properly test this problem is to verify if only the users of `Kautzer LLC` are the ones facing this problem and those of `Rolfson - Gusikowski` aren't. But as explained in the issue, the movie isn't the one with the problem. Rather the problem originates because of the mandate and as sales and by extension negotiations and incomes are created from the  mandate, that's how the error propagates.
Let me know if anything isn't clear.

**Comment by RemcoSimonides** [comment]
We can run a prepareForTesting to "reset" all the data

**Comment by cams-goussale** [comment]
After re-test with @yspringfield it seems the bugs of pages not loading is fixed.
However another bug detected in the process:

- [ ] External sales are not created in db

**Comment by cams-goussale** [comment]
Regarding the guards issue that Springfield created, let's treat it after the release (not urgent) #7810
