### ISSUE TITLE
Video fails loading in jwplayer

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7768]
### Description

Marie has identified a user who had their video upload failed, but were not informed. Are we handling these cases with an error message? If not, we should think of a "failed" status on the file manager. Maybe also a notification, if there isn't one already.

![image](https://user-images.githubusercontent.com/93206363/153901215-772f5947-056d-4044-bf25-d6595cda84af.png)

**Comment by 2amarkina** [comment]
**Following the dev review:** 
This one seems to be a dev issue, as we can't do much on design. As a user doesn't really need to upload a file into the Movie Tunnel, but we need to "retry" the video on our side. 

- So ,we can't manipulate the widget.
- But we can warn a user if an uploaded file was corrupted (via notification for example).

**Comment by RemcoSimonides** [comment]
There should have been an error message in the pop-up when uploading the file. Maybe the upload failed because they closed the website? In that case, no error message is shown.

**Comment by Jackseed** [comment]
looks like an edge case, I close it and we can re open if it happens again
