### ISSUE TITLE
New Social Media Banners

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7769]
A bit of refresh is needed on the banners used for our social media (LinkedIn, Fb, Twitter). Brief to come by @maltmayer

![image.png](https://images.zenhubusercontent.com/617811d92b89e7733866d8a0/6eb9f5b5-f647-4d15-82a4-1b637a4ff362)

**Comment by stephanie-cascade8** [comment]
Let's agree on some good practices to use when designing Social Banners :[ in progress here ](https://www.notion.so/cascade8/84d6d5254b7647f69881d99b2990e2b5?v=80f67a83cf77439e94acaa7cb91b55cc&p=a8addf3af2d34b3bad6ec8302130e1cf)

And here is [my proposition](https://www.figma.com/file/Yi5RKQuroGJtpnPUCcAO67/Assets?node-id=266%3A27) 

<img width="597" alt="Capture d’écran 2022-03-08 à 12 00 27" src="https://user-images.githubusercontent.com/66258851/157225634-364bd509-784c-41cb-ae72-51cde1812fab.png">

@maltmayer lets have a brieff on this first base if you need, or just send your comments here ;)

**Comment by cams-goussale** [comment]
Hey :) let's start including @afleutot in this type of discussions related to marketing or brand image

**Comment by cams-goussale** [comment]
@afleutot it'd be nice if you could spend some time with Stéphanie before she leaves (end of april) to catch up about design, illus, the tone we have, etc. There is some documentation in notion that might interest you

**Comment by afleutot** [comment]
With pleasure! @stephanie-cascade8 let me know when you'll be free! I already checked lots of things in notion but I'm gonna do some more deep documentation as soon as I can!

**Comment by cams-goussale** [comment]
@stephanie-cascade8 your proposition is good for @afleutot and the business team. Can we make adapted formats for each channel? These are the formats Aurore gave me:

Linkedin: 1776x 444
Twitter: 1500×500
Facebook: 851×315

**Comment by stephanie-cascade8** [comment]
Alright! I’ll mais that today 👍

Le ven. 18 mars 2022 à 09:31, cams-goussale ***@***.***> a
écrit :

**Comment by stephanie-cascade8** [comment]
![LinkedIn](https://user-images.githubusercontent.com/66258851/159898881-ba74cf60-05af-48e7-bd1b-dbe31ea27b9c.jpg)
![Twitter-cover](https://user-images.githubusercontent.com/66258851/159898898-70b47123-5e03-4a7f-b3ea-f8e4cb1b07c0.png)
![Facebook cover - 1](https://user-images.githubusercontent.com/66258851/159898906-583d40a0-e7f5-4a21-b178-4006a5dfe4a2.jpg)

**Comment by afleutot** [comment]
Hi @stephanie-cascade8 Is it possible to only have this written: "Tech solutions for the audiovisual industry" ?

**Comment by stephanie-cascade8** [comment]
Hi @afleutot
Yes of course.
For next time you need to ask for changes before we make the other sizes
and finitions ;)
Tell me if you need anything else before I re-export all of them.

**Comment by afleutot** [comment]
Ok got it, no it's perfect this time, thank you :)

**Comment by frenchyrules** [comment]
Hey @afleutot , j'ai le fichier avec les modifications apportées, où aimerais tu que je le dépose ?

**Comment by afleutot** [comment]
Hi @frenchyrules génial, merci!! https://drive.google.com/drive/folders/12MdEkuAZaveUwnzkxZy_TDohj4X5bD8D Ici ça te convient?

**Comment by frenchyrules** [comment]
@afleutot Done ! Let me know if you need any further changes :)

**Comment by afleutot** [comment]
Woooo that rocks!!!!! Thank you everyone, it's amazing!
