### ISSUE TITLE
[Seller's onboarding/Deal nego] Change background image

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7793]
Is there a way these statuses could be more visible? They are a bit hard to read.

![image.png](https://images.zenhubusercontent.com/617811d92b89e7733866d8a0/99d352ad-f854-4ca1-9764-1bb594c53283)

**Comment by stephanie-cascade8** [comment]
To UI : 

- [ ] business and @cams-goussale approval ?

- [ ] François's technical approval for background image here.

To DEVS :

- [ ] Change this section background (on a global level) into a background image. (png will be available to download here)
- [ ] Put a white background (#light-background-900 in the builder which is the cards background as well for ex.) to every status no matter where they are ( on a global level, make sure it's maintainable in themes).

Here is what it would look like: 
<img width="631" alt="Capture d’écran 2022-03-07 à 17 50 29" src="https://user-images.githubusercontent.com/66258851/157079824-b91e8308-e381-447d-9dac-e9e55e772a28.png">


[mockup figma](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=213%3A25391)

**Comment by cams-goussale** [comment]
Lgtm

**Comment by cams-goussale** [comment]
@stephanie-cascade8 i think we are missing the link to the png file

**Comment by stephanie-cascade8** [comment]
To help find movie avails in the app :

https://user-images.githubusercontent.com/66258851/159894965-105c8aff-46ae-4810-839e-00027a551da2.mov
