### ISSUE TITLE
Contract import

### ISSUE THREAD

**Issue by yspringfield** [blockframes/blockframes#7815]
Main issues
1. #7225
2. #6661
3. https://github.com/blockframes/blockframes/issues/6661#issuecomment-1027096108
4. #5267

### Common with admin and seller imports. ###
1. Not sure if it's not already the case but to be sure: users (and admin) shouldn't be enabled to attach a contract to another org than theirs, but they should be able to add an org name as Licensor of a contract to view it on the contract view, taking this into account too. #7810 
2. Imported contracts shouldn't trigger notifications nor emails ("You received an offer")
3.  Add a status column as mandatory on the template
4. Territories: it’s really hard to fill territories like “World excluding France”, currently we have to copy paste a list of all the countries and remove France from it. It’s extremely hard to read afterwards and prompt to errors. A while ago we had 2 columns: “Territories included” (eg “World”) and “Territories excluded” (eg “France”); if we could get back to something similar it would be really precious.
5. It would be also really useful to be able to fill in region names like “Africa” or “Europe” and that every territories from that region are included. Also have `Media` too in mind when doing this. 
6. We are having more and more often multiple terms attached to one contract. It looks like the admin columns (purple ones N-P) are not working for these cases. A solution would be to adapt the excel to this logic: several lines for each term, and one merged cell representing the contract of these terms (similar to what we have on the movie form with the cast)

### Specific to the seller. ###
1.  Add a price column as facultative on the template (this may wait if too complex)

### Specific to the admin. ###
1. International Title, Licensor & Licensee name currently accept names, best would be to have possibility to fill it with ids as well (for admin purposes). This is important when we have the same title name for different movies.

**Comment by cams-goussale** [comment]
Notes for Camille:

- Column R won't be useful anymore. Can be deleted
- Update parameters (add the green ones and remove the yellow ones). Add the media scope categories (VOD, TV, Ancillary Rights, DVD)
- Status column not mandatory
- TBC with Springfield if Stakeholders column? to keep or not?

**Comment by yspringfield** [comment]
[here's](https://drive.google.com/file/d/10O8KwdS0DpnWoFkeqCm-WCQEfTcIxzsi/view?usp=sharing) the final template used
