### ISSUE TITLE
prevent mail overlapping for landing/email-check.spec.ts

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7823]
If two E2E tests are running at the same time, overlapping can occur when checking mailosaur mailbox for `landing/email-check.spec.ts` in festival.

So some tests can fail because another test took and deleted the mail or some tests can pass even if it should not.

Solution is to generate an unique random ID

**Comment by n-germain-work** [comment]
@phpgeekfr 
I believe this has already taken care of inside #7773 :
- `email-check.spec.ts` renamed to `demo-request.spec.ts`
- use of faker to generate firstname, lastname, and the corresponding email

![image](https://user-images.githubusercontent.com/78768220/160826452-62d2e4f1-f4bd-40a0-b801-f08513872139.png)
![image](https://user-images.githubusercontent.com/78768220/160826472-9d5af129-ed34-4fc3-87cb-5661ec18b798.png)
![image](https://user-images.githubusercontent.com/78768220/160826493-c77b3ae9-2fe9-4a4b-aae1-9955dd6fe36b.png)
