### ISSUE TITLE
Improving of "Create you account" page (quick fix)

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#7825]
All the fields on this page are mandatory. So, the simplest solution would be to add a tooltip on hover on the "Sign up" CTA. Tooltip text proposal: "Please fill in all the fields"

![8efcdb56-62ec-4c69-b1d4-540d3b448625.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/fddeb321-e796-4a1b-aada-5cbcee341cbf)

**Comment by cams-goussale** [comment]
If easy, go
If not, forget about it
