### ISSUE TITLE
Add to bucket button doesn't work

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7830]
When using the `Add to bucket` button on the Movie Card, it creates the offer correctly in the `/selection` page, but:

- [ ] Buyer has to click twice on `Send offer` button in the modale
- [ ] The offer sent is empty when going to the page /marketplace/offer/[offerId]
- [ ] Sellers don't receive the offer

https://user-images.githubusercontent.com/93206363/156161655-4600b8da-c088-4f8d-8b34-bbea603ec468.mp4

**Comment by phpgeekfr** [comment]
@cams-goussale this issue should not be included in the current release ?

**Comment by cams-goussale** [comment]
We have already a lot of fixes for Springfield, so I don't think this can enter in the release
