### ISSUE TITLE
(B) Sellers' Analytics - Dashboard - Buyers' Insights Table

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7844]
[Wireframe](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/%E2%9A%99%EF%B8%8F-Sellers'-Dashboard-(DONE)?node-id=438%3A145660)
[UI Design](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=78%3A2478)

![image.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/3d4a945f-7016-499b-bb6a-8334594c4100)

**Comment by 2amarkina** [comment]
**Beginning of the table:** 
![Снимок экрана 2022-05-12 в 09.15.13.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/2826b0d9-2bb9-4d2c-a832-b6745c4f8119)

**Middle**
![Снимок экрана 2022-05-12 в 09.15.00.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/79875ccd-9065-476e-8b89-14aefb031955)

**End**
![Снимок экрана 2022-05-12 в 09.15.07.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/f9b81d4d-c79a-4e40-b1b1-843bd223a934)
