### ISSUE TITLE
(B) Sellers' Analytics - Buyers Activity Page - Table

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7845]
[Wireframe](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/%E2%9A%99%EF%B8%8F-Sellers'-Dashboard-(DONE)?node-id=438%3A91655)
[UI Design](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=94%3A5577)

- [x] Setup routing and page
- [ ] Add table

<img width="335" alt="image" src="https://user-images.githubusercontent.com/27687382/155301968-c65f2ece-a47a-4688-906e-b5b759dff1b1.png">

**Comment by RemcoSimonides** [comment]
Hee @2amarkina,

I noticed we don't show 'pageView' in the table. Should I filter out the users who only have pageView but no other analytic events?

Also, what do you want me to display if the table is empty? I forgot your answer when I asked before 😊

**Comment by 2amarkina** [comment]
> Hee @2amarkina,
> 
> I noticed we don't show 'pageView' in the table. Did you forget about that statistic perhaps? Most of the buyers have now 0 at every other statistic so doesn't seem appealing to click on the buyer to see more details atm. Could just be me. Maybe the sellers search for particular names/orgs anyway
> 
> Also, what do you want me to display if the table is empty? I forgot your answer when I asked before 😊

Hello @RemcoSimonides ! For the "pageViews" I thought that might be difficult to have as we need to see the page Views per title and if not it will be total pageViews for all the titles, but it might be not really clear for a user what do we mean. But i've just had an idea: maybe we could have something like "Titles viewed" ? and show the # of Seller's titles this particular Buyer saw? 

If the table is empty, we can just not show anything.

**Comment by RemcoSimonides** [comment]
> > Hee @2amarkina,
> > I noticed we don't show 'pageView' in the table. Did you forget about that statistic perhaps? Most of the buyers have now 0 at every other statistic so doesn't seem appealing to click on the buyer to see more details atm. Could just be me. Maybe the sellers search for particular names/orgs anyway
> > Also, what do you want me to display if the table is empty? I forgot your answer when I asked before 😊
> 
> Hello @RemcoSimonides ! For the "pageViews" I thought that might be difficult to have as we need to see the page Views per title and if not it will be total pageViews for all the titles, but it might be not really clear for a user what do we mean. But i've just had an idea: maybe we could have something like "Titles viewed" ? and show the # of Seller's titles this particular Buyer saw?
> 
> If the table is empty, we can just not show anything.

So Titles viewed is only max 1 per title, right? Even if the user visited a title page 5 times, it will count as 1.

**Comment by 2amarkina** [comment]
> > > Hee @2amarkina,
> > > I noticed we don't show 'pageView' in the table. Did you forget about that statistic perhaps? Most of the buyers have now 0 at every other statistic so doesn't seem appealing to click on the buyer to see more details atm. Could just be me. Maybe the sellers search for particular names/orgs anyway
> > > Also, what do you want me to display if the table is empty? I forgot your answer when I asked before 😊
> > 
> > 
> > Hello @RemcoSimonides ! For the "pageViews" I thought that might be difficult to have as we need to see the page Views per title and if not it will be total pageViews for all the titles, but it might be not really clear for a user what do we mean. But i've just had an idea: maybe we could have something like "Titles viewed" ? and show the # of Seller's titles this particular Buyer saw?
> > If the table is empty, we can just not show anything.
> 
> So Titles viewed is only max 1 per title, right? Even if the user visited a title page 5 times, it will count as 1.

Yes. Like this pageViews - #of visits of a particular Film Page, Titles viewed - #of Titles / Film Pages visited (and if a user has visited the same film page 5 times, indeed it will count as 1 title)
