### ISSUE TITLE
Delivery Homepage

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#785]
- [x] Add Welcome title line
- [x] Add action button
- [x] Use movie cards from catalog app with action buttons
- [ ] Use movie view from catalog app (sections Poster, Production, Principal info & Synopsis)
https://projects.invisionapp.com/d/main#/console/18107883/375773868/preview
https://projects.invisionapp.com/d/main#/console/17971669/374501283/preview
- [ ] Use a real home for delivery instead of movie-list component

**Comment by ioaNikas** [comment]
###Home component for delivery app

##Issue

When we try to lazy load delivery app with its own home component, we get a `/welcome` at the end of the url leading us to an unwanted page.

##Clues about how to solve this

Seems like the wrong router is loaded. Maybe look for empty path redirection.
