### ISSUE TITLE
Promotional elements on two lines

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7861]
- [ ] (B) chrome only - if we have a scroll bar in left menu, `promotional elements' is displayed on two lines (scroll bar is larger on chrome than firefox)
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/d7df2d1a-68a3-41c6-be26-d84d036be102)

_Originally posted by @phpgeekfr in https://github.com/blockframes/blockframes/issues/7759#issuecomment-1041590875_

**Comment by dmoncadalv** [comment]
When displayed on two lines, could we reduce the line spacing ?
Example in Online App vs Figma mock up

![Capture d’écran 2022-05-16 à 14.24.46.png](https://images.zenhubusercontent.com/6258184d440b61b47c763ef1/fc2f3233-7e07-469d-90ed-b4aadb97f128)

![Capture d’écran 2022-05-16 à 14.29.56.png](https://images.zenhubusercontent.com/6258184d440b61b47c763ef1/68f72264-e251-40b7-862f-6d5294bcd355)


_Comments for later :_ 
- I noticed that the sidebars (dashboard / movie tunnel for example) have not the same font size. 14px for Movie tunnel vs 16px on Dashboard. Could we maybe make them all the same ? (All 14px)
- Do we know why the scroll bar is larger on chrome than in firefox ?

**Comment by cams-goussale** [comment]
@dmoncadalv for this issue we concluded that there isn't much we can do, is that correct? If there is nothing to implement for devs, let's close this

**Comment by RemcoSimonides** [comment]
> When displayed on two lines, could we reduce the line spacing ? Example in Online App vs Figma mock up
> 
> ![Capture d’écran 2022-05-16 à 14.24.46.png](https://camo.githubusercontent.com/a7d1213eaeb1832fb2a89b3af87fd288fe14e391eb28e2fe0a29f9447c14736e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632353831383464343430623631623437633736336566312f66633266333233332d376530372d343639642d393065642d623461616462393766313238)
> 
> ![Capture d’écran 2022-05-16 à 14.29.56.png](https://camo.githubusercontent.com/9d3437eb930c582d61858c9797df8e461ec2a7cce8dbc27dd353a6292a8a578f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632353831383464343430623631623437633736336566312f36386637323236342d653235312d343062372d383632662d366435323934626364333535)
> 
> _Comments for later :_
> 
> * I noticed that the sidebars (dashboard / movie tunnel for example) have not the same font size. 14px for Movie tunnel vs 16px on Dashboard. Could we maybe make them all the same ? (All 14px)
> * Do we know why the scroll bar is larger on chrome than in firefox ?

1. yea we could. But if movie tunnel is already 14px, it doesn't change this issue, no?
2. I don't but that should be fixable too ;)

**Comment by dmoncadalv** [comment]
1. Indeed, it doesn't change the fact that it'll be in two lines when the there's a scroll bar. After talking with @2amarkina, we agreed that it’ll be better if all the sidebars had the same font size, so let's change the font size to 14px everywhere and close the issue :) 
![Capture d’écran 2022-06-10 à 14.21.11.png](https://images.zenhubusercontent.com/6258184d440b61b47c763ef1/6b520f19-0a1d-472f-8942-5fd1e97a4825)

2. Perfect !
