### ISSUE TITLE
E2E Refactor page objects into page modules

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7868]
Refactor page objects into page modules 
see `apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts`

**Comment by phpgeekfr** [comment]
@n-germain-work I don't remember what this issue is about. Can you clarify ?

**Comment by n-germain-work** [comment]
in the end we use none of this two

**Comment by phpgeekfr** [comment]
so this can be closed ?

**Comment by n-germain-work** [comment]
indeed
