### ISSUE TITLE
Firestore rules - Improve array of fields to define field path

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7889]
Francois noticed that the function `isRequestFieldValueEqualTo ` in firestore rules expect an array of up to 3 fields. We should check if we can just use 'path.to.field' instead of ['path', 'to', 'field'] instead:

I think there is an issue with the definition of the function, we should be able to read the FieldPath directly instead of breaking it into an array limited to 3 values.
Please check if we can check the value with a FieldPath instead: https://firebase.google.com/docs/rules

**Comment by phpgeekfr** [comment]
merged with #7534
