### ISSUE TITLE
Handle special caracters in emails

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7897]
We have seen an example of an email sent from Sendgrid with special characters which didn't pass.

Expected result: `You've been invited to join Shu Kei's Creative Workshop Ltd on Archipel Market`
Actual result: `You've been invited to join Shu Kei&apos;s Creative Workshop Ltd on Archipel Market`

Are the special characters being handled on our hand or on Sendgrid's hand? Can we fix this?

![image](https://user-images.githubusercontent.com/93206363/156378893-6722fdca-3801-407e-b0fb-2fb2ef796743.png)

**Comment by Poppe-A** [comment]
@Poppe-A : Resolved, in email template subject, we need to get the properties this way :
`{{{prop}}}` instead of `{{prop}}` in order to get the property in a string format instead of html format
