### ISSUE TITLE
Time selector dropdown button on event page needs to be bigger

### ISSUE THREAD

**Issue by frenchyrules** [blockframes/blockframes#7915]
We need the clickable zone to be as big as possible without it having an impact on the height of the component. 
Live test with a dev would be nice
![event bug.gif](https://images.zenhubusercontent.com/611a265d2ea95c7880c91192/2aea505b-a311-4f8b-a208-5bdea71d7379)
![image.png](https://images.zenhubusercontent.com/611a265d2ea95c7880c91192/24e8d544-2e74-475f-87c1-c596b719260f)

**Comment by frenchyrules** [comment]
> or date input smaller ? :)

Could help, but it seems here that the clickable zone for _time_ is too thin, we need to check this with a dev to see if we can't increase that zone vertically

**Comment by Jackseed** [comment]
oh ok got it 👍

**Comment by frenchyrules** [comment]
Height of the input field could be increased from 18px to 40px, if this solution is approved by @GrandSchtroumpf 
 
**Would go from this 👇**
![image](https://user-images.githubusercontent.com/85220905/172643714-41b23900-cb09-4654-a721-ee3c01460af9.png)

**To this 👇**
![image](https://user-images.githubusercontent.com/85220905/172643809-f4e5a3d9-69a7-466a-8126-f111810e8451.png)
