### ISSUE TITLE
Integrate Hotjar Free plan

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7935]
We are going to desactivate Yandex due to the context. Could we estimate the dev time needed to implement Hotjar Free plan?
https://www.hotjar.com/

The important features we need are:
- Recordings
- Heatmap

You can create a free account on their site and investigate what needs to be done.

![image](https://user-images.githubusercontent.com/93206363/157431672-31497992-0eb2-44e1-bd7c-3781ef2a9f94.png)

**Comment by RemcoSimonides** [comment]
Adding this snippet is 30 minutes of work.
We should also display this 3rd party service in the cookie / privacy policy. Which is not within this estimation.

**Comment by cams-goussale** [comment]
- [ ] Add a paragraph in the privacy policy. In the section `6. Who else can access your Personal Data` in the list of partners, add

```
Hotjar (Hotjar, Ltd)
Hotjar is a service provided by Hotjar, Ltd.
Personal data collected: id, name, surname, email address, IP address, browser, device, OS, pages visited, time spent on each page, clicks on page elements, cookies
Place of Processing: Malta - [Privacy Policy](https://www.hotjar.com/legal/policies/privacy/)
```

- [ ] Add a section in the optional cookies, below intercom. Enable by default.

```
Hotjar
Audience analysis to design better experience
```

**Comment by cams-goussale** [comment]
@RemcoSimonides let me know if we can push this into the release.
