### ISSUE TITLE
(A) Track the pageView on Archipel Content

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7937]
We want to be able to track whose Buyers visited which Film page, on Archipel Content. It would help us to justify, in case a sale happens outside the platform, that they owe us the fee. This would be a way to secure Buyers bypassing us and doing deals outside the platform.

Before doing anything, could we have an estimation of how long it would take to implement this tracking? Considering this might be in development on Archipel Market (with the Seller's analytics epic).

**Comment by RemcoSimonides** [comment]
Adding the data to the database is really easy. 10 minutes of work.
Is displaying the data somewhere also within the scope of this issue?

**Comment by cams-goussale** [comment]
Can we query this information with BigQuery afterwards? That'd be a great solution to start with.

But indeed, let's also estimate if we want to display the data somewhere. It'd be for Admin so it can be basic. For ex, on the Movie page in CRM, show the list of Users who visited the page (with the date if possible?)

**Comment by RemcoSimonides** [comment]
I would use the same method as we use for Sellers Analytics, which means we save everything in Firestore. So we could query it directly from Firestore.

If we want to query it from BigQuery, I'll have to add data to the automated processing of sending it from Firestore to BigQuery (Which we should do anyway one day). If we do this, the data can be added in the data studio reports.

What it comes down to; how would we like to display the information? If it's only showing a table or an aggregated number, then Firestore could be enough. Otherwise, it's probably better to add it to BigQuery so it can be used in Data Studio reports.

**Comment by cams-goussale** [comment]
> What it comes down to; how would we like to display the information? If it's only showing a table or an aggregated number, then Firestore could be enough

Yes it'd be just a table for the moment.

When you say we could query directly from Firestore, you mean filtering by titleId in the Firestore database, right?

Anyway, since having the data in Firestore is a 10min work, can we go ahead and add it?

**Comment by RemcoSimonides** [comment]
> When you say we could query directly from Firestore, you mean filtering by titleId in the Firestore database, right?

Correct

And sure, we can 👍

**Comment by cams-goussale** [comment]
Could you also give me an estimation on "how would we like to display the information"

It'd be a table with the aggregated pageViews of each buyer for each movie. Something like:

Movie | Buyer | Aggregated PageViews
----------|----------|--------------
Movie A | Buyer 1 | 2 pageViews
Movie A | Buyer 2 | 1 pageView
Movie A | Buyer 3 | 6 pageViews
Movie B | Buyer 1 | 2 pageViews

**Comment by RemcoSimonides** [comment]
±3 hours

**Comment by cams-goussale** [comment]
Ok thanks
Can we prioritize this? It's a request from Management. We can delay Seller's Analytics to push this one

**Comment by RemcoSimonides** [comment]
No because it uses a lot of the same code as we are making for Sellers' Analytics. What we can do is to add it as (A) priority to Sellers' Analytics Epic and we'll have it for April's release.

**Comment by cams-goussale** [comment]
Ok let's go for this !

**Comment by cams-goussale** [comment]
@RemcoSimonides is this included in the release?
