### ISSUE TITLE
privacy page is not rendered the same on each apps

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#7944]
financiers:
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/d0e0c852-1400-47f3-9cda-cad11c9d4b3f)

market:
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/105e0cd6-866d-4422-9545-2a4c27692831)

catalog:
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/563d85b3-f2e1-486a-ad7c-6f0db4729e24)

**Comment by cams-goussale** [comment]
@phpgeekfr we are going to change the privacy policy when we launch seller's analytics. I think we can skip this issue and start with a clean slate when we update the new privacy policy
