### ISSUE TITLE
Movie banner on mobile

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7961]

**Comment by cams-goussale** [comment]
There has been already some mockups & wireframes done. Let's rediscuss and finalize both of them.

**Comment by stephanie-cascade8** [comment]
Everything was validated by François and camille. 

Note for dev: when implementing, live test with UI will be needed. 
First contraint is to make the header fit inside the height of small phones. (we'll reduce the poster size until we manage that)
[header component link](https://www.figma.com/file/7jYrZUTAXck7lp4FBqt9cX/Components?node-id=46%3A123)
