### ISSUE TITLE
Include Buyer list in Side nav

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7964]

**Comment by frenchyrules** [comment]
Done. Sidenavs [here](https://www.figma.com/file/qpLBi85x3y0s4fLpJPACOm/%5B-Wireframing-Elements-%5D?node-id=2137%3A7429)

**Comment by cams-goussale** [comment]
Sorry I did not specify, but the Buyer's list will be available for Sellers, so only on Dashboard (and only for AM)

**Comment by 2amarkina** [comment]
![Снимок экрана 2022-03-21 в 10.41.51.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/c6321f9f-b088-4a62-9506-bf142b48237f)

P.S. Updated on all the Market screens

**Comment by cams-goussale** [comment]
Ready for UI. Good taks for @dmoncadalv

**Comment by 2amarkina** [comment]
[Link to UI components ](https://www.figma.com/file/7jYrZUTAXck7lp4FBqt9cX/Components?node-id=167%3A896)

![Снимок экрана 2022-04-22 в 15.31.35.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/43a0a8ca-c8b0-4993-8872-1ba8c71dd9da)

**Comment by 2amarkina** [comment]
**Screenshot:** 
![Снимок экрана 2022-05-06 в 15.01.36.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/3d342793-fc3b-466b-9a93-10a05a6e39ee)

**Comment by cams-goussale** [comment]
@RemcoSimonides I saw this is already implemented on your env. Do you need this issue or has it been taken into account already with the Buyer list?

**Comment by RemcoSimonides** [comment]
Yea, this has been implemented 👍 
@Poppe-A reopen if it's not
