### ISSUE TITLE
End of Google Analytics

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#7970]

**Comment by cams-goussale** [comment]
Can we list the metrics currently being tracked on GA ?
Once we have this clear, let's decide if we need to:

- Substitute GA by another tool
- Make our own tracking tool

**Comment by RemcoSimonides** [comment]
1. We track what browser and browser version the user uses. This information is used to be able to determine which browsers/versions we should support. 
2. We track what url they came from and go to. This information is used to see what path the user took through the app. Also, Marie used to use this information when she was helping a customer and see where they got stuck for example.
3. We have some dashboards on CRM app. They will not have new data anymore so they should be removed too.
4. GA was tracking a lot more data which we don't use. For example: operating system, language, geolocation.

For dev:
If replace 1: Add the browser and version to the `meta` property for each event triggered.
If replace 2: Create new type of analytics event which will create new doc on every page navigation (might create too many docs though)

**Comment by RemcoSimonides** [comment]
@Jackseed @cams-goussale we keep GA for now, no? Can we close this issue for now?

**Comment by Jackseed** [comment]
Yep we keep it for now, I close it
