### ISSUE TITLE
Release 4.1 - Deal Negotation

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#7985]
[Deal negotiation test scenarios](https://www.notion.so/cascade8/Deal-Negotiation-ce5198d8e0904b91a6bf1a2500376dd1)

Akita for Router has been removed in this release. Which means extra attention needs to be paid whether every link is still working properly and the correct app names are displayed (https://github.com/blockframes/blockframes/issues/7287)

Other issues that have been resolved for this release:
- [ ] https://github.com/blockframes/blockframes/issues/7860

**Comment by RemcoSimonides** [comment]
Please also update the test scenarios if something new needs to be tested.

**Comment by cams-goussale** [comment]
Review regarding this issue #7742

- [ ] In template id `d-a4ee1970187e4fd8bef47a4008a2267a` we send a table with all the titles purchased by the Buyer. The titles are links clickable which redirect to the title page /marketplace/title/[titleId]. There is an issue in the construction of the url because it redirects to `http:///c/o/marketplace/title/[titleId]`

Email received:
![image](https://user-images.githubusercontent.com/93206363/158581617-f0828b01-d430-4d4b-aa91-0ad395adb4d1.png)

Click on one title:
![image](https://user-images.githubusercontent.com/93206363/158581674-9776d321-9310-4a47-a817-08dffbec99e9.png)

**Comment by cams-goussale** [comment]
Review regarding this issue #7742

- [ ] This template doesn't link to `/crm/offer/HEG-843594/view`

**Comment by cams-goussale** [comment]
Review regarding this issue #7742

- [ ] This template id `d-e127e70b634347788d07cad355421999` the CTA Contact Us should redirect to the user's email adress with this email prefilled `support@archipelcontent.com`

**Comment by cams-goussale** [comment]
- [ ] External sales are now correctly created in db, but they don't show on the app. They should show in a table as External Sales.

**Comment by phpgeekfr** [comment]
- [ ] I have 1 item in "all"  that is in negotiation :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/9f5e50b6-2c7f-4b52-9fdb-dea226ed6303)
Nothing in "ongoing" but there is a `(1)` : ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/8194be07-61fc-48a2-9f06-15e79fa6f61b)
Something in "new" bur there is a `(0)` ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/7c554aeb-7114-457c-9abc-d60e78b0491b)

**Comment by 2amarkina** [comment]
**My Deals page**
- [ ] Change the meta-title from "My Sales" to "My Deals" ![my deals.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/5146cba9-c512-4976-ae02-6668ef096e88)

Empty State
- [ ] For the consistency with other empty states remove "My Deals" title and CTA on the right, as we already have it below
![Снимок экрана 2022-03-22 в 11.44.30.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/6b95200d-5874-467c-a4f1-cb1c72bbbbee)

**Comment by cams-goussale** [comment]
- [ ] (C) Status is not showing well when importing sales
![image](https://user-images.githubusercontent.com/93206363/159527450-a163fad4-1e35-4efb-9acf-5042ca289a54.png)

**Comment by yspringfield** [comment]
> * [x]  _Springfield is working on this_ (C) Status is not showing well when importing sales
>   ![image](https://user-images.githubusercontent.com/93206363/159527450-a163fad4-1e35-4efb-9acf-5042ca289a54.png)

This issue has been resolved by disabling the functionality in favor of #8075
