### ISSUE TITLE
Movie Component Documentation

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8005]
Update / Clean the Gsheet to give the team a proper support during release days.
https://docs.google.com/spreadsheets/d/1z4FFNABgDyRGgD5AQZf-ebWbA_m-7hlueFMCVUuk2fI/edit#gid=1003782809

**Comment by 2amarkina** [comment]
@frenchyrules to continue the work on this inventory you can go to the [Fields details tab ](https://docs.google.com/spreadsheets/d/1z4FFNABgDyRGgD5AQZf-ebWbA_m-7hlueFMCVUuk2fI/edit#gid=279324582) 

Need to verify if the texts and component behavior described in the document correspond to those that we have in the real Movie Tunnel. Pay spacial attention to the "Suggestions" to add and put all the propositions in purple color.

**Comment by 2amarkina** [comment]
All the proposions issued from the intern tests are reflected in the inventory with purple color.

**Comment by 2amarkina** [comment]
last steps before moving to dev: 
- [ ] waiting for the definite list of festivals; 
- [ ] decide for the Release Media (Fields details > line 112)

**Comment by 2amarkina** [comment]
It would also be a good task for UI to insert the new text while working on the transfert of Movie Tunnel from Sketch to Figma. 

After deciding the last wording, I could move this one to devs and UI at the same time, @cams-goussale ?

**Comment by 2amarkina** [comment]
- [ ] Update wireframes with new texts

**Comment by cams-goussale** [comment]
>  waiting for the definite list of festivals;

I have added 2 and added an Other field (if possible) for the user to specify their festival themselves.

> decide for the Release Media (Fields details > line 112)

I put it in red following my call with Yuki yesterday evening.

I am adding dev and ui tags as it seems you all teams can work at the same time. Maybe it'd be worth having a call with @dmoncadalv to explain how to read and understand the document.

**Comment by 2amarkina** [comment]
**Split of pages:** 
total 14 pages for Movie Tunnel (for total production status) 

@dmoncadalv 7 pages : Main, Storyline, Production Info, Artistic, Additional, Shooting, Technical 

@frenchyrules Versions, Videos, Files, Images, Notes, Summary page

**Comment by cams-goussale** [comment]
When a dev starts working on this, we also need to update the excel import for titles (some fields will be changing). Please call me

**Comment by cams-goussale** [comment]
Inconsistencies with the excel import:

- Distributor is not mandatory in the excel import. It's one of the stakeholder drop down option.
- Same for Sales Agents.
- There is no field for Director's filmography in the template.
- Same for the Cast

@2amarkina it's quite hard to find the differences between the movie tunnel and the excel template. I think it'd be easier to work together on this (one looking at the movie tunnel and the other one at the excel template)

**Comment by 2amarkina** [comment]
**Add the following to the documentation:** 
- [ ] Define Film Page Tabs logic (Cross app & App Specific / Dashboard & Marketplace)
Precise which information goes to Marketplace tabs and which information goes to the Dashboard

**Comment by 2amarkina** [comment]
[Here is the link](https://docs.google.com/spreadsheets/d/1z4FFNABgDyRGgD5AQZf-ebWbA_m-7hlueFMCVUuk2fI/edit#gid=880544882) to the regroupment of the information that we show inside the Tabs on the Marketplace and Dashboard

**Comment by cams-goussale** [comment]
For devs: the work is to make the changes highlighted in red in the tab `Fields details`
