### ISSUE TITLE
Remove requestFromUserToJoinOrgDeclined notification

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#8026]
Since requestToJoinOrgDeclined hasn't been working for about ±10 months now and nobody misses it, we decided to remove the notification instead of fixing it.

For release 4.1 I have removed the code to trigger the notification, but the code is still there to display the notification. The notifications need to be removed with a migration and then also the front-end code can be removed.

**Comment by phpgeekfr** [comment]
- [ ] also check if `invitationToJoinOrgDeclined` is really useful, for me this case cannot happen : invited user does not have the ability to refuse a invitation to joinOrg

**Comment by phpgeekfr** [comment]
- [ ] in fact, maybe `requestToJoinOrgDeclined` should be sent by email to requesting user instead of orgadminIds of the org that refused the request

**Comment by RemcoSimonides** [comment]
> 

Tried to trigger the notification by doing: "If you're already a user of Archipel, attached to orgA. But for some reason, orgB invites you to join. You could decline? I've never tried that". But it isn't possible to invite a user who already has an org.

**Comment by RemcoSimonides** [comment]
If this still goes in Release 4.3, could you add it to the [release issue](https://github.com/blockframes/blockframes/issues/8606) please? So it will be tested

**Comment by Jackseed** [comment]
> * also check if `invitationToJoinOrgDeclined` is really useful, for me this case cannot happen : invited user does not have the ability to refuse a invitation to joinOrg
>   if we ever keep this,  notifications settings for this one cannot be edited so all admins gets email and in-app notif

Indeed we can remove it as well

**Comment by phpgeekfr** [comment]
@cams-goussale, @KevinDurand974 is currently working on this issue (sub issue of  #8355)
