### ISSUE TITLE
Identify why so difficult to add several chips in a field without leaving the field

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8029]
When a user tries to add several elements in a field (for example, several Genres to a movie), s/he has to click outside of the field before being able to add another element. Design & dev needs to investigate what is the root of this issue.

A video to illustrate:

https://user-images.githubusercontent.com/93206363/158977177-220d3815-b049-4b31-97bb-166754953e18.mp4

**Comment by frenchyrules** [comment]
After a quick check with Remco, an option here could be to live the list opened until the user is done adding in all of the wanted chips.

**Comment by cams-goussale** [comment]
If the list remains open, how would the user indicates he's done selecting the chips?

**Comment by cams-goussale** [comment]
After UI & dev review, it seems this needs some investigation by the dev. Probably clean some code, check the way this component is integrated, as it seems to be working well on angular material.

To be treated with #7915
