### ISSUE TITLE
sameFolder for storage backups to save costs - incremental backups

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#8067]
new backup folder means full backups each week

do incremental backups Without losing ability to go back in time

**Comment by phpgeekfr** [comment]
linked with #6788

**Comment by phpgeekfr** [comment]
linked with #7483

**Comment by phpgeekfr** [comment]
this was done in #7483
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/4ca02dbd-6021-426f-ab5e-034bf135131d)

**Comment by phpgeekfr** [comment]
closed and moved to #8532
