### ISSUE TITLE
Separate the import of contracts for sellers and admins.

### ISSUE THREAD

**Issue by yspringfield** [blockframes/blockframes#8075]
Currently, both sellers and blockframe admins use the same contract template to import contracts, internal and external sales. Thanks to #8074, importing of internal sales have been temporarily commented out. That's because, we will like to separate the importation of contracts into two. A contrived one for the seller and another for blockframe's admins.
This entails:
 
### For the seller:
 - [x] Create a new excel template for sellers
 - [x] Sellers can't import internal sales and mandates.
 - [x] Sellers can import only external sales of movies of his org.
 
 ### For Blockframe Admins:
 - [x] Adapt existing template to suit only admins.
 - [x] can import both mandates and internal sales irrespective to whom belongs the movie.

**Comment by cams-goussale** [comment]
@yspringfield you will find some TEMPLATE_PROPOSAL [here](https://drive.google.com/drive/folders/1hmsmslJxLxrPpA5Cy5K814Rgd_bHYaQb) for the Sellers and for blockframesAdmin.

I have some points open for discussion:

- Should we distinguish internal sales and external sales in the blockframesAdmin template?
- Could we allow blockframesAdmin to use either the `international.title` either the `titleId` in the first column?
- Could we allow Sellers to use only the international.title in the first column?

=> see this comment for reference https://github.com/blockframes/blockframes/issues/7984#issuecomment-1074112718

- The changes I've made between the 2 templates are:
1/ For Seller template, I removed the Mandate option in the drop-down menu in column B
2/ For Seller template, I removed the Admin columns at the end (P,Q,R)
Let me know if more changes are needed.

**Comment by cams-goussale** [comment]
- [ ] With Seller's template, I imported the sales attached. It told be it was created and then I was unable to load the page /dashboard/sales. I had the error `FirebaseError: Invalid document reference. Document references must have an even number of segments, but movies has 1.` Contract was not created in db
[import-contracts-template seller.xlsx](https://github.com/blockframes/blockframes/files/8519375/import-contracts-template.seller.xlsx)

**Comment by yspringfield** [comment]
>  Could you explain how to use the Admin columns in purple?

 column P: used to define the id of the contract to be imported a default value is generated when absent but the column needs to exist.
 column Q: Used to set the parentTerm of the contract to be imported.
 column R: used to include additional stakeholders to the contract to be imported.

**Comment by cams-goussale** [comment]
- [ ] I imported an external sale as a Seller. It worked but the Sale doesn't show in the My Deals page.

contract id `m7UgblvChYLSQafkHFwa`
title id `S512yYOhaMlezFIgUnrF`

[import-contracts-template mandate.xlsx](https://github.com/blockframes/blockframes/files/8554046/import-contracts-template.mandate.xlsx)


<img width="956" alt="image" src="https://user-images.githubusercontent.com/93206363/165079613-12ec031a-ec78-406d-b871-96d2760c7a92.png">

**Comment by yspringfield** [comment]
Hi @cams-goussale, here's how the final templates should look like.
* Admin template:
[import-contracts-template.mandate.xlsx](https://github.com/blockframes/blockframes/files/8560709/import-contracts-template.mandate.xlsx)
* Seller template: 
[import-contracts-template.seller.xlsx](https://github.com/blockframes/blockframes/files/8560715/import-contracts-template.seller.xlsx)

### The differences between seller and admin templates are:
1. The seller template does not have a `contract-type` column. Which is `column b` in the admin templates.
2. the seller template does not have a `Mandate ID or Row number` column because it doesn't need it.

This is so that we can conclude on what the template is and I include in the application.

### Small remarks.
columns 'Contract Id` and `stakeholders` respectively column `p`, `r` in the admin templates are not admin only columns.
They too are required in the seller templates albeit even when they are empty as their position is used to set the contractId or stakeholders of a sale (external) or mandate.

**Comment by cams-goussale** [comment]
Last testing session went well. Nothing to highlight. I would like to keep the templates added [here](https://drive.google.com/drive/folders/1hmsmslJxLxrPpA5Cy5K814Rgd_bHYaQb) so that:

1/ The last "blue" columns now have some indications of how to fill them. I've removed the mention "admin only".
2/ Let's keep the extension .xlsm because the documents have a macro

It's good to go for me!
