### ISSUE TITLE
[Catalog] Specific terms modale

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8132]
Before making any wireframe, let's have a discussion with Yuki.
<img width="494" alt="image" src="https://user-images.githubusercontent.com/93206363/160367684-78221ce0-2ead-4ea3-bbd3-b8cf973abf34.png">

Context: When doing the internal user test with Lorena & Yuki, Lorena added a question about the "Asking Price" in the first section of the modale. This opens 2 issues:

- Was it not clear enough for the Buyer that this modale is about Specific Terms & Delivery Specifications ? why did the Buyer asked for the Asking Price here ?
- We do not give the possibility to the Seller to answer the questions or request of the Buyer. During the user test, the Buyer requested some specific materials that the Seller did not have. Seller was struggling to communicate this info to the Buyer
- Product-wise, we did not remove the "structure" of the package deal. Meaning a Buyer can still add several titles to his selection and send the offer. Is it clear enough that the Specific terms & Delivery Spec apply to ALL of the titles in the selection?
- Do we want to give the option for a text message in this modale ? If we do so, we open the door to a complex flow of discussion (almost a chat functionality). If we want to go for this, it'll have to be validated by top management.

**Comment by cams-goussale** [comment]
Let's change the text but remove the specific terms & delivery

**Comment by 2amarkina** [comment]
Yes we could remove `Specific terms `and `Delivery Specifications` everywhere. 
Still, I need to precise that even if we change the text to the "Are you sure you want to submit contract", we have to keep the checkboxes and their present behavior + disable the CTA until the checkbox is checked. 
![terms and conditions](https://user-images.githubusercontent.com/55499036/210790428-b896e8bf-a4d1-4777-b03c-e25fe8a262fb.png)

**Comment by 2amarkina** [comment]
**UPDT.**
- [ ] Still keep up with the field "Specific Terms"

**Comment by phpgeekfr** [comment]
- [ ] when deploying this issue to production, update template `d-a4ee1970187e4fd8bef47a4008a2267a` on sendgrid to remove delivery part ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/2b45639c-479e-4823-8815-e8f64b85c534)

**Comment by phpgeekfr** [comment]
- [ ] after deploy to production, remove "delivery" field from bucket collection

**Comment by 2amarkina** [comment]
### **Modal texts proposition**

**New hint text for the Specific Terms field:** 
- [ ] `You can precise any specific conditions such as: MG, Revenue Sharing, Delivery Specifications... ).`

**Heading:** 
- [ ] From `Specific Terms` to `Are you sure you wish to send your Offer?`

**Paragraph:**
- [ ] From `Please indicate any specific conditions you'd like to request for this deal.` to `Please verify that all the Offer details are convenient to you`

**CTA**
- [ ] Keep up with `Send your Offer`


@Jackseed what do you think?

**Comment by phpgeekfr** [comment]
Example : 
![image](https://user-images.githubusercontent.com/1194344/211610664-b108cfeb-a521-47ae-9fa4-10906d2f2974.png)

@2amarkina ok for you ?

**Comment by 2amarkina** [comment]
> Example : ![image](https://user-images.githubusercontent.com/1194344/211610664-b108cfeb-a521-47ae-9fa4-10906d2f2974.png)
> 
> @2amarkina ok for you ?

Yes, maybe just a little change `Please verify that all the details of the current Offer are convenient to you`

**Comment by phpgeekfr** [comment]
ok, updated 
![image](https://user-images.githubusercontent.com/1194344/211611748-f426985f-99db-48c6-a8c4-b60089ee9937.png)
