### ISSUE TITLE
Show new negotiations in My Deals table in a color

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8134]
### Description

Could we find a way to highlight the rows of the My Deals (Dashboard) and Offers & Deals (Marketplace) tables when they are new, meaning:

- [ ] When Seller just received an offer
- [ ] When Seller or Buyer receive a counter-offer

This higlighting could disappear once the user has entered in the contract page.

**Comment by dmoncadalv** [comment]
UI  Mock up Proposal 
![Capture d’écran 2022-06-08 à 18.06.15.png](https://images.zenhubusercontent.com/6258184d440b61b47c763ef1/5f961830-b4d2-40f3-8276-3d97f203aa49)

[Figma Link](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=4%3A257)

**Comment by cams-goussale** [comment]
@dmoncadalv this works well. Could we do the same for the Seller? You've done the mockup when the Buyer recieves a new offer. We should do the same on [this mockup](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=61%3A1369)

![image](https://user-images.githubusercontent.com/93206363/173017180-ad893827-19af-43aa-97cc-edebb19bc1c8.png)

Also, I see there are some mockups done for mobile. Can we update them accordingly?

**Comment by dmoncadalv** [comment]
[Figma UI mockup](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=1169%3A16826) 
I updated the seller’s mockup as well as mobile mockups :)
