### ISSUE TITLE
[Catalog] Add some surfaces to improve ui

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8135]
### Description

Through user testing and yandex, we've identified 2 pages on Archipel Content where the user was stuck or struggling to see the main information. Maybe adding some surfaces could help, or maybe there is another suggestion from UI.

1/ The Negotiation Page (Marketplace + Dashboard)
After clicking on "Negotiate", user was struggling to see where to input the price.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/93206363/160378259-e1ef0ca5-7032-4c6f-a4d8-94cac1c2b441.png">

2/ The Avails Page (Marketplace only)
After clicking on Search & Buy Rights, user did not use any of the filters at his disposal. Maybe their color look like they are disable.

<img width="945" alt="image" src="https://user-images.githubusercontent.com/93206363/160377396-d7f80933-b2d9-4b0f-9cda-a48307dae50b.png">

**Comment by dmoncadalv** [comment]
[UI Mockups here](https://www.figma.com/file/IKBGYfmCXpbJZnfjw0NrDg/Deals-Negotiation?node-id=201%3A15570)

**Comment by cams-goussale** [comment]
When I was testing, I was wondering if we could slightly change the UX of this page @2amarkina. When a Buyer or Seller clicks on Negotiate, they enter in the Edit mode of the offer. And the first term is alway open by default:

![image](https://user-images.githubusercontent.com/93206363/173397034-4cd90a70-cf6c-4847-b3a1-730a825a101f.png)

What do you think about openning the Edit mode with all the terms "closed"?
![image](https://user-images.githubusercontent.com/93206363/173397120-57127a91-cd16-4f5e-971c-6e690ee625f4.png)
