### ISSUE TITLE
[CRM] Movie page improvements

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8144]
@isseymiyuki needs some improvements of the movie page in CRM.

On AC, the flow is: 1/ user creates a movie 2/ user submits the movie 3/ blockframesAdmin accepts or not the movie through CRM 4/ movie gets published (or not) on marketplace

The problem is that Yuki is stuck at point 3 because she can't see all the fields of the movie in CRM (you can only see images and videos but not text fields like synopsis, materials...).

Let's list all the fields Yuki would like to see in CRM and update the /movie page.

**Comment by cams-goussale** [comment]
Can we also improve the excel export to include more info from movie?

- length column
- other columns tbc with Business

**Comment by cams-goussale** [comment]
[WIP]

Fields | Currently in Excel Export | Currently editable on CRM Movie page? | Business need to edit on CRM Movie page | Business need in Excel export
-------|----------------------------|-----------------------------------|------------------------------------------------|--------------------
International title | y | n | A/B/C | A/B/C
Original title | n | n | A/B/C | A/B/C
Format (TV, Movie) | n | n | A/B/C | A/B/C
Number of Episodes | n | n | A/B/C | A/B/C
Season number | n | n | A/B/C | A/B/C
Title reference | y | y | A/B/C | A/B/C
Image - Film Poster | n | y | A/B/C | A/B/C
Image - Film Banner | n | y | A/B/C | A/B/C
Release year | n | n | A/B/C | A/B/C
Country of origin | n | n | A/B/C | A/B/C

**Comment by cams-goussale** [comment]
**Update of this issue**

It will be too complex to include components of the movie form into the CRM page. Therefore, to simplify, let's do the following:

- The links we have redirecting to the apps should be accessible by all blockframesAdmin (meaning we don't need to connect with concierge, but our Cascade8 accounts are enough)
![image](https://user-images.githubusercontent.com/93206363/176174025-54698b40-3e45-4f3e-822e-60b333b02fd4.png)

- The table on the page /crm/movie should include additional columns.

- [ ] Keywords
- [ ] Has a screener? (y/n)
- [ ] Has a poster? (y/n)
- [ ] Has avails? (y/n)
- [ ] Festival
- [ ] Certification
- [ ] Release media

![image](https://user-images.githubusercontent.com/93206363/176174248-0d65ed2c-74e9-45d5-a3f7-a36f03c6f1f8.png)

**Comment by yspringfield** [comment]
Hi @cams-goussale , concerning the below.

> The links we have redirecting to the apps should be accessible by all blockframesAdmin (meaning we don't need to connect with concierge, but our Cascade8 accounts are enough)

I presume she's going there just to view info, or is she going there to update data too?

**Comment by cams-goussale** [comment]
@yspringfield no the objective is to be able to edit data as well. would that be possible ?

**Comment by yspringfield** [comment]
yes, she now has edit access to the movie's tunnel.
