### ISSUE TITLE
Design rules & Graphic identity

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8146]
This issue is to open the discussion with the Business team around corporate identity, style guidelines and general design rules.

**Comment by stephanie-cascade8** [comment]
The process is details [here](https://www.notion.so/cascade8/84d6d5254b7647f69881d99b2990e2b5?v=80f67a83cf77439e94acaa7cb91b55cc&p=e4a76277e127496e9bd88e18b03878c6)
