### ISSUE TITLE
Create "Price" type with currencies from static-models

### ISSUE THREAD

**Issue by ioaNikas** [blockframes/blockframes#816]

**Comment by phpgeekfr** [comment]
Here is the price interface :
![image](https://user-images.githubusercontent.com/1194344/66926724-cec9bc00-f02e-11e9-82f9-e1580758039a.png)

see https://docs.google.com/spreadsheets/d/1_zTkmjRqTZMKh5EoU_gdJ9rT3o7Eq2Qh316USVA5-I8/edit?usp=sharing for details

**Comment by Jackseed** [comment]
thanks @phpgeekfr > closed
