### ISSUE TITLE
[NFT] Logo & Graphic chart

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8162]
Yannick needs for next week a bit of elements to make a full page about our NFT lab on the website of Cascade8. We can reuse the elements we already have from filmseriesNFT but just centralize a bit the info in some place. I think we can try to have:

- the logo
- some guidelines about the graphic chart
- a couple of illustrations

**Comment by stephanie-cascade8** [comment]
The logo for NFTLab is available in different versions [here](https://drive.google.com/drive/folders/1_wk0rLNbmAR0BjCKcuF-UWQlq0sRU7k_)
