### ISSUE TITLE
In dashboard, it shouldn't be possible to create an event in the past

### ISSUE THREAD

**Issue by n-germain-work** [blockframes/blockframes#8203]
As of now, you can create an event in the past :
![image](https://user-images.githubusercontent.com/78768220/162152747-4732188a-86f8-49c2-8578-fc754fcdda49.png)

## Problems :
- no one will be able to interact with this event
- no statistics will be provided
- it's not possible to delete it (because in the past)

## Possible solutions :
- find a way to disable past dates (not clickable)
- if not possible, warn the user that he cannot create an event in the past, and cancel creation

**Comment by 2amarkina** [comment]
There is an issue for the calendar improvements. 
This one #8203 should be taken into account while working on General [Calendar Improvements #5967  ](https://app.zenhub.com/workspaces/design---ux-60ab5f37bd1f990011c933a2/issues/blockframes/blockframes/5967) inside the Archipel Refinements epic.
