### ISSUE TITLE
E2E : festival dashboard - My events - Create an event

### ISSUE THREAD

**Issue by n-germain-work** [blockframes/blockframes#8220]
# Admin

## pass

- [x] add a future public screening event (pass)
- [x] add a future protected screening event (pass)
- [x] add a future private screening event (pass)
- [x] add a future public secret screening event (pass)
- [x] add an all day future public screening event on next week (pass) (next week to prevent CI crash on sundays)
- [x] add a future public meeting event (pass)
- [x] add a future public slate event (pass)
- [x] add a future public and secret slate event (pass)
- [ ] ⬆️ for all slate tests, after may release, check if slates are visible
- [x] add multiple events at the same date and hour (pass with shrinked events)
- [x] delete an upcoming event (pass)
- [x] edit an upcoming event (pass)
- [x] add a screening event for a movie without screener (pass with warning chip)
- [x] add a screening event for a movie with screener (pass without warning chip)

_Below test have been removed due to low value (already tested in screenings) and to prevent 'out of memory' issue in Cypress_
~~add a future private meeting event (pass)~~
~~add a future protected meeting event (pass)~~
~~add a future private slate event (pass)~~
~~add a future protected slate event (pass)~~

## fail
- [ ] add a past public screening event (should fail, see issue #8203)
- [ ] move an upcoming event to the past (should fail, see issue #8203)
- [x] add a meeting with ending time before starting time (fail)
_____________________
# Member

## pass
- [x] add a future public screening event

**Comment by phpgeekfr** [comment]
- [ ] remove previous test & clean code
