### ISSUE TITLE
can't have twice the same movie poster

### ISSUE THREAD

**Issue by VicoDraye** [blockframes/blockframes#824]
![image.png](https://images.zenhubusercontent.com/5d25963dc78b914564d10881/978f44af-8784-4a61-96a2-7ec47b5f87c4)

When puting the same movie poster as an existing one, this will break the first one.

**Comment by jenna1k** [comment]
this issue hasn't been solved yet
![simpson](https://i.imgur.com/AaBbBPT.png)

**Comment by Jackseed** [comment]
solved by @phpgeekfr
