### ISSUE TITLE
Title import bugs

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8270]
- [x] Updating a movie with excel import
If user imports an excel of an existing title, it should update the movie. In other words, if I create Movie A, B and C and later on I upload the title-import template for movie A, B and C, it should update these movies with the fields modified.

To avoid side effects, we should use titleId in column A when a user wants to update an existing movie using the excel import.

Template used when creating movies for the first time:
[AM x Screen Partnership _drafts.xlsx](https://github.com/blockframes/blockframes/files/8522215/AM.x.Screen.Partnership._drafts.xlsx)

Template used when wanted to update existing movies:
[AM x Screen Partnership_accepted.xlsx](https://github.com/blockframes/blockframes/files/8522237/AM.x.Screen.Partnership_accepted.xlsx)

- [x]  Available versions (columns BH, BI, BJ, BK) show an error
I can't fill in these columns with languages. It gives an error in CRM.

**Comment by yspringfield** [comment]
Hi, here are the expected values of the columns.
- `bh` : list of languages
- `bi, bj, bk, bl` : yes or no

In the above attached templates, I could notice that columns `bi, bj, bk, bl` are all list of languages. That's what was causing the error.

**Comment by cams-goussale** [comment]
Ah shoot ! I've corrected the template [here](https://drive.google.com/drive/folders/1hmsmslJxLxrPpA5Cy5K814Rgd_bHYaQb) (Title_Import). You can re-upload it on the app.
