### ISSUE TITLE
Cannes preparation

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8284]

**Comment by 2amarkina** [comment]
**TO DO:** 
- [ ] Questions draft for Archipel Content
- [ ] Questions draft for Archipel Market

**Comment by 2amarkina** [comment]
[Work in progress](https://docs.google.com/document/d/1ZpoIjsWNCVnC7-BzqYii3qKkw9P_dwMjYEMt2nqFc1U/edit)
