### ISSUE TITLE
Implement "watchingStatus" on screening events

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#8286]
Right now we only have the watchTime for a screening event on the invitation document but we don't know if user is currently watching the screening or not. 

Also, instead of saving watchTime & watchingStatus on invitation document and in order to have this data even for public screenings (ie: possibly no invitation) this should be stored elsewhere (maybe on event document ? )

**Comment by RemcoSimonides** [comment]
Or somehow on a document in analytics collection.

**Comment by Jackseed** [comment]
Not sure if it's a duplicate or just a more focused issue but [this one ] #7555 (https://github.com/blockframes/blockframes/issues/7555) includes wireframes and a bit more improvements
