### ISSUE TITLE
successful login should discard displayed snackbars

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#8290]
let say I add an extra space on my email field to login `dev+kurt-fil@blockframes.io ` and click login: a snack bar shows up saying that there is an error.
If I correct it quickly and login, I'm redirected to c/o/dashboard but the snackbar is still displayed

**Comment by KevinDurand974** [comment]
Cant reproduce this,
I've tried to :

- Add a space before & after : This will connect the user normally
- Add a space before '@' : Show 'not correct email' but tried to login with this, and change it to correct one and login but the snackbar fade out normally

**Comment by phpgeekfr** [comment]
> Cant reproduce this, I've tried to :
> 
>     * Add a space before & after : This will connect the user normally
> 
>     * Add a space before '@' : Show 'not correct email' but tried to login with this, and change it to correct one and login but the snackbar fade out normally

@KevinDurand974  After successful login, I still have the snackbar displayed showing previous error : 
![image](https://user-images.githubusercontent.com/1194344/166641863-eb974d81-f0cb-4e2f-8633-7cef6f2f48d8.png)

**Comment by KevinDurand974** [comment]
🤷‍♂️🤷‍♂️🤷‍♂️

https://user-images.githubusercontent.com/89908055/166643865-0a5ec7e6-4184-4842-a659-f4799893c93b.mp4

**Comment by KevinDurand974** [comment]
What you want is that when the user logs in successfully, the snack disappears?
