### ISSUE TITLE
Release 4.2 - Other

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#8304]
Mailchimp:
- [ ] https://github.com/blockframes/blockframes/issues/7297

Sendgrid
- [ ] https://github.com/blockframes/blockframes/issues/7624

Usability
- [ ] https://github.com/blockframes/blockframes/issues/8046

**Comment by cams-goussale** [comment]
- [ ] It seems the email variable changes have broken this [email template](https://docs.google.com/spreadsheets/d/1b1K7YfnquxnfCgGGPxIz5ZNIjr9eK_bUrRJqLvPYGIk/edit#gid=97734814&range=L37) where there was an if statement. In case Buyer sends an offer with no price, it should send text mentionning the Asking Price.

![image](https://user-images.githubusercontent.com/93206363/166265178-572f4928-8b68-4e60-93d6-6f486d2e646a.png)

**Comment by cams-goussale** [comment]
- [ ] I can't get to the /notification page, it loads forever with this console error.

![image](https://user-images.githubusercontent.com/93206363/166265444-c4e44659-311b-4be6-90f1-b94cef5a3edb.png)
