### ISSUE TITLE
Harmonize movie FieldsConfig with Movie model.

### ISSUE THREAD

**Issue by yspringfield** [blockframes/blockframes#8333]
In file `libs/import/src/lib/view-extracted-elements/titles/fieldConfigs.ts`, the types of language and stakeholders attributes of the 
`FieldsConfig` interface don't match with that of the `Movie` interface. Subsequently, the imported title has the wrong structure for these two attributes.

- [ ] Create necessary utility methods in `libs/model/src/lib/movie.ts` that creates the right structure for languages and stakeholders from the imported data so that 
- [ ] When an imported movie is upserted, these attributes respect the structure of the `Movie` model.

**Comment by RemcoSimonides** [comment]
Hey @yspringfield, would you mind adding labels to the issues you create? That way they will show up in our Zenhub boards.
