### ISSUE TITLE
Header with action design decision

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#8334]
It's a common pattern we have in the app so we should make a decision and maybe a global style so it's consistent throughout the app.

It's about a <h1234> with a <button> on the same row. On desktop, it needs to be far apart. But on smaller screen, should it be centered? When should it center? Should it wrap whenever there is no space like on the second image? Or should the button still be all the way to the right?

![image](https://user-images.githubusercontent.com/27687382/165959582-671942f0-eb9b-4433-94bc-2648273ac962.png)
![image](https://user-images.githubusercontent.com/27687382/165959606-8fcb8cb9-aa0b-473a-81f3-2bc1efb3e55c.png)

More occurances:
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/27687382/165960376-5cfaae1e-58e8-4abf-91c0-73b419c01d8a.png">

<img width="539" alt="image" src="https://user-images.githubusercontent.com/27687382/165960433-bed20f19-caf7-471d-a3c6-a18aa894bbdf.png">

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/27687382/165960543-53c75d3f-2117-4b84-8d13-b1f83cfced40.png">

And many more

**Comment by 2amarkina** [comment]
Document the decision in notion

**Comment by cams-goussale** [comment]
Let's make sure any decision taken for mobile is reflected in [Stéphanie's documentation](https://www.figma.com/file/AkPrTIPD10O3mjuuwgDsxn/Responsive-Global-View?node-id=1%3A2)
