### ISSUE TITLE
No name titles in Titles' list - Dashboard

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#8343]
Have "No name yet" instead of blank might be more appropriate 
![Снимок экрана 2022-05-02 в 15.58.05.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b0da83cd-8d77-4465-9892-f667899f84d0)

**Comment by frenchyrules** [comment]
[My Titles](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/%E2%9A%99%EF%B8%8F-Sellers'-Dashboard?node-id=1063%3A106347)
![image](https://user-images.githubusercontent.com/85220905/168803440-7257eed7-d6af-4e81-9341-9a5ef026b248.png)
[My files ](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/%E2%9A%99%EF%B8%8F-Sellers'-Dashboard?node-id=1067%3A113718)(wip)

**Comment by frenchyrules** [comment]
Following UX weekly call, changes have been reflected in the [wireframe](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/%E2%9A%99%EF%B8%8F-Sellers'-Dashboard?node-id=1063%3A105573)

**Comment by 2amarkina** [comment]
Need to check this part with business team

**Comment by cams-goussale** [comment]
The `untitled ( number )` looks good to me. If ok for dev, we can move on with this
