### ISSUE TITLE
org.denomination.public should be removed

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#8355]
`org.denomination.public` is still used on the app but it is not set on org creation and cannot be updated/set after.
Looks like only org import allows this.

So new organizations does not have public denomination

check existing issue  #2860

**Comment by Jackseed** [comment]
Unfortunately I think we can back pedal and go back to org.name. 
Public / Private was meant to be used for in-app invoicing but it's not on the roadmap so far

**Comment by phpgeekfr** [comment]
- [ ] updating org name does not update algolia indexes if org have denomination.full defined

on the form, input is for `denomination.full` 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/bc8975fe-39e3-4b5f-a7d9-2f194a3c47f8)

but `orgName` pipe displays `denomination.public`  by default (example in `<organization-display>`) and algolia is also updated with public denomination by default

( NB: only old orgs have `denomiation.public` defined)

Quick fix would be to update both public and full denomination

**Comment by phpgeekfr** [comment]
- [ ] remove `interface Denomination` from `PublicOrganization`
- [ ] remove `orgName` Pipe and function
- [ ] create a migration to change org documents from `denomination` to `name`
  => this should be  a separate issue. 
  => if org have only denomination.full  we will take this value for `org.name`
  => if org have only denomination.public  we will take this value for `org.name`
  => if org have both but with equal value , take one or another
  => (on prod db) @phpgeekfr create a list of org that have both full and public with distinct values to decide what to do
- [ ] remove org.fiscalNumber from code and from db (in same migration as above)
- [ ] update various org forms

**Comment by RemcoSimonides** [comment]
If this still goes in Release 4.3, could you add it to the [release issue](https://github.com/blockframes/blockframes/issues/8606) please? So it will be tested
