### ISSUE TITLE
Do not instantiate firebase db or auth objects inside your functions!

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#8376]
It might be convenient to get it working, however this causes problems down the line when we need to switch between environments (ie emulator etc) or other configs. Instantiating firebase should be confined to a single module, and that module should be able to keep track of - multiple apps, and only let you run initialise once per firebase app, otherwise return the existing app.

We can also use the module to set process.env vars to get rid of those annoying warnings - only time this may be an issue is if we have multiple apps hitting multiple projectIds. We'll see if this causes any issues.
One place we hit multi project IDs is when we try to access CI/prod during devops tasks.

**Comment by phpgeekfr** [comment]
look for `#8376` in code

**Comment by phpgeekfr** [comment]
@george43g every `admin.firestore()` should use `export const db = admin.firestore();` from `apps/backend-functions/src/internals/firebase.ts` ? Or is there another approach ?
