### ISSUE TITLE
Screening list filters

### ISSUE THREAD

**Issue by Poppe-A** [blockframes/blockframes#8383]
For the release (4.2) we removed the filter from screening list header, choosing the first solution @2amarkina offered :

![screeningFilter.png](https://images.zenhubusercontent.com/611a26af814edaca4297991a/a7fd2160-0a31-4392-8aa7-3d2f4548985a)

Should keep this page without any filters, or do you prefere to implement the search bar and filters ?

**Comment by cams-goussale** [comment]
I think this is a duplicate with #7195
