### ISSUE TITLE
Card NFT

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#8386]
Design of the cards to represent collects and token

**Comment by cams-goussale** [comment]
This is how an NFT card looks like (when metadata is visible).

Desktop
![image](https://user-images.githubusercontent.com/93206363/179691797-8798d763-bc8c-48eb-a66d-15e8739f35ca.png)
Mobile
![image](https://user-images.githubusercontent.com/93206363/179691930-3c0ffe80-02b2-4a61-828d-aaee1b2dd641.png)

How could we add the following elements to the card:

- [ ] Rarity (can be either `common`, `medium`, `rare`, `legendary`)
- [ ] Attributes (can be several attributes amongst the list below)

Attributes list:
Text type (ex.

**Comment by frenchyrules** [comment]
UI [here](https://www.figma.com/file/WVrgqlKLM07bOGBYBAa81z/Card-NFT?node-id=0%3A1) (WIP)
