### ISSUE TITLE
Use RXJS firstValueFrom

### ISSUE THREAD

**Issue by yspringfield** [blockframes/blockframes#8409]
The `observable$.toPromise()` method is marked as deprecated.
it's mostly used in the following forms
`observable$.pipe(take(1)).toPromise();`
`observable$.pipe(first()).toPromise();`

Now that we've updated to latest rxjs version, we can update it to `firstValueFrom(observable$)`

**Comment by phpgeekfr** [comment]
linked with #7595  
![image](https://user-images.githubusercontent.com/1194344/167386073-ba53aef5-1961-4b7e-b9c0-de8d951513c5.png)
