### ISSUE TITLE
Signing up - Remember sign-up form state when visiting terms page

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#8433]
Originally posted in [Release 4.2 - General UI](https://github.com/blockframes/blockframes/issues/8301#issuecomment-1115788544)

> **Signing up + Terms & Conditions + Data Privacy**
> - [ ] (C) Is it possible that clicking on "<-" on the "Terms & Conditions" page or "Data Privacy" page brings a user to the > Sign up with pre-saved fields (if a user has already started filling in)? 

When I click on the "Terms & Conditions" or "Data Privacy", then it opens in a new tab. The "<-" is not shown there. Am I doing something different than you?

To answer your question; yes, it is theoretically possible. Not sure if Francois is a fan of using local storage or saving the state in a service though but that's to be determined by the dev.

**Comment by cams-goussale** [comment]
Shouldn't we just remove the arrow on the T&C / Privacy pages? since it opens in a separate tabs, there is no logic in returning to previous page

**Comment by RemcoSimonides** [comment]
> Shouldn't we just remove the arrow on the T&C / Privacy pages? since it opens in a separate tabs, there is no logic in returning to previous page

Does it show up for you? Because I think the button shouldn't be there if there is no previous page to go to (it looks as the history of the tab)

Is opening the T&C / Privacy pages only possible in a new tab? I remember we used to also be able to open it in a modal - on the sign up page if I recall correctly. But maybe that has been changed the meantime

**Comment by cams-goussale** [comment]
Ah indeed, if you open the Privacy Page through the cookies for instance, it does make sense to have the back-arrow here.

But I don't get this issue though.

1/ If I'm on the sign up page, start filling in the form, then open the Cookie Preferences > Privacy policy and click back on the arrow, I still get my info saved on the sign up page.

2/ If I start filling the sign up form and click on the links at the bottom for Privacy policy or T&C, it opens separate tabs. And my sign up form is still intact in the initial page.

**Comment by RemcoSimonides** [comment]
Same. I also don't see the issue :) Closing for now. @2amarkina re-open if you do see the issue
