### ISSUE TITLE
Notifications settings for Slate Presentation

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#8440]
Originally posted by Bruce in [Release 4.2 - Events](https://github.com/blockframes/blockframes/issues/8302#issuecomment-1121160757)

- [ ] User cannot chose preferences for "slate" events, they are currently merged with "screenings"

see `apps/backend-functions/src/internals/invitations/events.ts`

```typescript
    recipients.map(recipient => {
      notifications.push(createNotification({
        toUserId: recipient,
        organization: invitation.fromOrg,
        docId: invitation.eventId,
        invitation: createPublicInvitationDocument(invitation),
        type: event.type === 'meeting' ? 'invitationToAttendMeetingCreated' : 'invitationToAttendScreeningCreated',
        _meta: createDocumentMeta({ createdFrom: 'festival' }) // Events are only on festival
      }));
    });
```

a new kind of notification should be created.

also needs to be added here `apps/backend-functions/src/notification.ts`

```typescript
      case 'invitationToAttendMeetingCreated':
      case 'invitationToAttendScreeningCreated':
```

**Comment by RemcoSimonides** [comment]
Starting the flow from Design UX so it can be added to notification docs or wireframes/designs

**Comment by cams-goussale** [comment]
Using issue #7658 for this
