### ISSUE TITLE
Sellers' Analytics - Add user activity on CRM

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8461]
Similar to what was done with this issue #7937, Yuki would like to see on a user level which titles he has seen. Could we add an Analytics table on the user page in CRM?

**Comment by RemcoSimonides** [comment]
Let's order the last Sellers' Analytics by priority in the Sprint Backlog and let's see what Springfield is able to finish before the release as I'm on holidays. Also, it depends on whether we move the release due to holidays.

**Comment by RemcoSimonides** [comment]
If this still goes in Release 4.3, could you add it to the [release issue](https://github.com/blockframes/blockframes/issues/8610) please? So it will be tested

**Comment by Jackseed** [comment]
needs a bit of specs from product

**Comment by RemcoSimonides** [comment]
What about

Title |  Aggregated PageViews | Video plays | In Wishlist | Screening Requested | Asking Price Requested
----------|----------|--------------|--------------|--------------|--------------
Movie A | 4 | - | - | 1 | 1
Movie B | 1 | - | - | - | -
Movie C | 1 | - | - | - | -
Movie D | 1 | - | - | - | -
