### ISSUE TITLE
Organization of Figma UI

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#8478]
See how we could improve the arrangement / organization of the board UI. 

**Ideas:**
- Have the same working space logic as for UX? 

**Essential to do:**
- Verify the actual logic of UI arrangement. 
- Check all the drafts and move them to the dedicated spaces.

**Comment by cams-goussale** [comment]
If posssible, prioritize the UI mockups of Archipel Market's Dashboard (aka Seller's Analytics). For some reason, we left all the mockups in the Drafts section, which fills extremely disorganized and unclear. This is the main development we did these past 6 months, so it should be clean.

[UX Wireframes](https://www.figma.com/file/FhY2dJqeYrVTXh7Q7HA0m7/%E2%9C%85-%2B-%E2%9A%99%EF%B8%8F-Sellers'-Dashboard?node-id=53%3A8239)
[UI Mockups to reorganize](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=78%3A2428)

The flow is the following:
1/ User is on Dashboard view. There is 1 surface for Titles Analytics, 1 surface for Buyers Analytics, 1 surface for Buyers you might not know

1a/ User clicks on View all titles analytics. User gets the list of all his titles + some charts related to this cumulative data
1a-i/ User clicks on 1 titles and gets to the Title report page. If no data, show empty states surfaces.

1b/ User clicks on View all Buyers activity. User gets the list of all buyers who interacted with his movies + some charts related to this cumulative data
1b-i/ User clicks on 1 buyer and gets to the Buyer report page. If no data, show empty states surfaces.
