### ISSUE TITLE
Clear filter bad position / style

### ISSUE THREAD

**Issue by KevinDurand974** [blockframes/blockframes#8479]
The button Clear Filter isn't align with other filter, small bigger...
Some exemple:

From AC:
![preview](https://i.imgur.com/1DqblMU.png)

From AM:
![preview](https://i.imgur.com/2swdD6T.png)

**Comment by dmoncadalv** [comment]
Hello ! 
For this issue, could we : 
- [ ] **Vertically align** the « Clear filters » button to the **middle** of the other buttons (Production status, budget, etc.) ?

- [ ] Completely remove the background of the button so we only have the text ? e.g. of the background :
![Capture d’écran 2022-06-08 à 14.21.52.png](https://images.zenhubusercontent.com/6258184d440b61b47c763ef1/3eb298c0-5eca-4f2a-8bb4-8b3e273033a7)

**Comment by dmoncadalv** [comment]
Would it be possible to change the background of this button to 0% opacity ? (and keep the hover as it is today) to have something like this : 

![Capture d’écran 2022-06-09 à 12.53.18.png](https://images.zenhubusercontent.com/6258184d440b61b47c763ef1/0182cc1e-ab43-4b77-af20-e21402f69871)

In general, as seen with @2amarkina, this change will concern only "reset" or "clear" buttons on the apps.

**Comment by 2amarkina** [comment]
- [ ] remove the class "translude"
