### ISSUE TITLE
re-shrink shrinked DB

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#8487]
A lot on new movies have been added recently, increasing the number of users and orgs kept during db shrinking.
Check if this can cause any issues regarding E2E tests and maybe remove some movies from the db.

**Comment by RemcoSimonides** [comment]
Linked to #8723

**Comment by phpgeekfr** [comment]
check inconsistency 
during process 
```
Found 197 inconsistencies when auditing users (192 in _meta).
Found 1 inconsistencies when auditing orgs (0 in _meta).
```

**Comment by phpgeekfr** [comment]
- [x] keepAlive and timeout set to 20 for increased db
