### ISSUE TITLE
Remove useless libraries

### ISSUE THREAD

**Issue by lsenta** [blockframes/blockframes#85]
When we created the delivery app, for some reason we had to:

```npm i --save @ngrx/effects @ngrx/store @ngrx/router-store```

@GrandSchtroumpf noted we should be able to remove these useless dependencies & raise the issue to nrwl maintainers.

**Comment by Jackseed** [comment]
@lsenta issue still valid?

**Comment by Jackseed** [comment]
no idea on what is it, closed issue
