### ISSUE TITLE
remove emulator config from env.ts files

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#8524]
we already have a way of getting emulators to be the target,
ie
`npx nx serve <app> --configuration=emulator`

**Comment by phpgeekfr** [comment]
update with new command to use
- https://www.notion.so/cascade8/Emulator-79492738d2614b35b6435eb80584ff26
- https://www.notion.so/cascade8/E2E-testing-with-Emulator-4069418c783444a3951247781040337c
