### ISSUE TITLE
Hotjar - Heatmaps not showing full height of the page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#8525]
Currently Hotjar heatmaps show only the first screen but can't scroll to the bottom of the page.
E.g.
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/c24f0536-c56b-4ae8-8640-147437ff03f1)

It's listed in their [heatmap limitations](https://help.hotjar.com/hc/en-us/articles/115011867928-Heatmap-Limitations) that:

> Scrolling element on the < div > container: Hotjar builds Heatmaps on top of screenshots. When we load your page to take a screenshot of it, we check how large the page is and take a full-sized screenshot of it. The issue with pages that contain the scrolling part of a page within a < div > container rather than using the < body > container is that Hotjar cannot detect the scrolling content inside the < div > container when we take a screenshot.

Is changing div with body something we could do? 
cc @RemcoSimonides @GrandSchtroumpf

**Comment by RemcoSimonides** [comment]
François knows this better but I think it's highly likely we cannot do this

**Comment by GrandSchtroumpf** [comment]
We would have to rethink the whole design to achieve that. Like removing the sidenav for example.

**Comment by Jackseed** [comment]
Ok I guess best would be either to find another dedicated service for heatmap or forget about it (for now). 
cc @cams-goussale @2amarkina
