### ISSUE TITLE
Catalog Martketplace - List of minor issues to fix before Toronto

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#854]

**Comment by Maxstgt** [comment]
[ ] - the user clicks on movie card in the search page and should get redirect to the movie detail view

**Comment by Jackseed** [comment]
- [ ] Discover our films button (homepage) linked to Search page
![image](https://user-images.githubusercontent.com/14964443/64021478-5d908100-cb34-11e9-867e-74383cded980.png)

**Comment by Jackseed** [comment]
- [ ] The page title *Search* should not have the same background image than the horizontal "search what you want" (it should have no image background)
![image](https://user-images.githubusercontent.com/14964443/64021792-0a6afe00-cb35-11e9-94b1-36401c5ec7ff.png)

**Comment by Jackseed** [comment]
- [ ] old movie cards to replace with the new ones (?)
