### ISSUE TITLE
Bucket with invalid data on production database

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#8551]
On prod, centralOrgId (jnbHKBP5YLvRQGcyQ8In) have a bucket with invalid data.

This is triggering warnings during `databaseConsistencyAudit` script.

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/322e86ec-a976-4a63-8cda-0367ce9b792c)

From what I understand, `orgId` should not be undefined.  `price` field  have `null` or `NaN` values  but interface shows that it should have a non-optional number entry.

Another prod bucket have invalid data on price (but orgId is ok ) `0lgFJpVxNO6fOSK9YrpS`: 

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/d4fc59b1-d7bc-461a-a1d0-dcedf4110f49)

@yspringfield can you look how to improve data verification before submitting the form ?

@cams-goussale Can we clean this invalid data ( from `jnbHKBP5YLvRQGcyQ8In`, the only one creating warnings)) ? 
I think that hitting ` Delete all Terms for this Title `button is enough 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/9da44c48-0ca4-4cf2-84af-5d65a83a4bcb)

**Comment by RemcoSimonides** [comment]
@yspringfield I see you have a pending PR. Is it going to be merged? And what about this issue, is it still relevant to keep it open or can we close it?
