### ISSUE TITLE
Titles order on Library list

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8567]
- [x] Check how the order is currently set and what is the business expectation.

@Lorena-Amaral @isseymiyuki the titles on the Library page are currently ordered alphabetically. Do you need it to be ordered differently?

**Comment by Lorena-Amaral** [comment]
The best would be to have at least the following possibilities for buyers:

- [x] Alphabetical order
- [ ] Year of production order
- [ ] Entry order

Would it be possible?

**Comment by Lorena-Amaral** [comment]
Yes!
