### ISSUE TITLE
migrate shell env vars in CI to demo-blockframes

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#8574]
CI runs `projectId = 'demo-blockframes` but uses values from `blockframes-ci` as a backup. These values should be migrated.

Also.

our whole environment setup is flaky - majority of issues with tests happen becaues of missing keys etc...
tests should be catching bugs before they hit production, but instead we still spend time fixing tests themselves.

Overall, code changes to make it easier to detect missing env vars etc... to make onboarding automated and easier

**Comment by phpgeekfr** [comment]
Looks like linked with #7858

**Comment by george43g** [comment]
it's used by any project that still uses blockframes-ci and also demo-blockframes. If we migrate everything to demo-blockframes we can migrate the prefix, but this works for now
