### ISSUE TITLE
[Media] Remove file from bf-form-list does not remove file from queue

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#8578]
This bug applies to notes and otherVideos

How to reproduce using otherVideos:
1. Go to movie tunnel => Promotional elements => Videos
1. Select a video
2. Click on "Save video"
3. Remove file from the list
4. Click on Save and you'll see that the file is uploading even though you just removed it from the list.

**Comment by KevinDurand974** [comment]
Another bug found on pre-release:

You only have to select the video type to be able to click on `Save video`, the file is not taken into account.
