### ISSUE TITLE
Trigger analytics event on opening of movie promotional elements.

### ISSUE THREAD

**Issue by yspringfield** [blockframes/blockframes#8580]
Currently, analytics events are triggered for video open events.
```
libs/movie/src/lib/movie/marketplace/shell/shell.component.ts
line 88
```
Following in the steps of the above piece of code, we should trigger `promoElementOpened` events.

You can start by adding them here:
```
libs/movie/src/lib/movie/marketplace/shell/shell.component.html 
```
everything in the footer tag.

**Comment by RemcoSimonides** [comment]
@yspringfield please don't forget to add "Dev - Feature team" or "Dev - Sanity team" label otherwise the issue doesn't appear on our Zenhub boards

**Comment by cams-goussale** [comment]
@yspringfield could  you rephrase this issue? i dont understnad it very well
