### ISSUE TITLE
Releases 4.3 - Movie

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#8611]
[Movie test scenarios](https://www.notion.so/cascade8/Movie-8506fba333d64b8cb9e857351a6c7989)

Issues that have been completed in this release:
- [x] https://github.com/blockframes/blockframes/issues/7863
- [x] https://github.com/blockframes/blockframes/issues/8100
- [x] https://github.com/blockframes/blockframes/issues/8213
- [x] https://github.com/blockframes/blockframes/issues/8434
- [x] https://github.com/blockframes/blockframes/issues/8436
- [x] https://github.com/blockframes/blockframes/issues/7893
- [x] https://github.com/blockframes/blockframes/issues/8572

**Comment by Poppe-A** [comment]
Vidéos are not working on title page. I tried with differents existing movies, with newly created movies (differents videos), and the video player is never displayed.
![videoKo](https://user-images.githubusercontent.com/35397614/173531666-464736e2-e5f6-4a5b-8b96-b3350c1755c3.png)

**Comment by Poppe-A** [comment]
When importing movies from the template, the summary page show no error. 
But when I'm trying to publish imported movies, an error about the title is shown, even if the title is correctly entere
![title](https://user-images.githubusercontent.com/35397614/173553746-df5df6d0-58f9-4199-beb3-63f51ab7e8ca.png)
d

**Comment by Poppe-A** [comment]
I don't know if it's normal or not, but if a user click on add to wishlist several times, the wishlist counter is incremented as many times

**Comment by Poppe-A** [comment]
When a user click on a promo element of a movie, the related statistics is supposed to increased. But it doesn't work.
Wishlist and page view statistics are working though

**Comment by Poppe-A** [comment]
May not be a bug :
On CRM -> movies, clicking on export to CSV will export all movies, not only the filtered ones

**Comment by frenchyrules** [comment]
No tooltips upon hover on titles table 
![image](https://user-images.githubusercontent.com/85220905/173775901-979527c8-09a3-4352-8e9c-1ca1393dce38.png)
Proposition has been noted in tooltip inventory [here](https://docs.google.com/spreadsheets/d/152BY91BxRHMksMK-t9Xw_WzKAnxLhl0M4jtex9NY32Y/edit#gid=0) (line 54-56)

**Comment by n-germain-work** [comment]
## Main information

- [ ] "Format" shouldn't have "Movie" by default, to match with the rest of the app
![image](https://user-images.githubusercontent.com/78768220/173779013-ec888ddb-2c1d-4cb2-aaff-9ab1a117f99c.png)

## Production information

- [ ] Missing * in 4 country fields
![image](https://user-images.githubusercontent.com/78768220/173779159-2e67835d-7baf-41bd-bbd0-3123b41e44a8.png)
![image](https://user-images.githubusercontent.com/78768220/173779174-cc0cf618-fd91-49dc-8d3c-3898d81a2ea4.png)

## Videos

- [ ] Videos : it shouldn't be possible to hit 'Save Video' if no vidéo has been added in the upload component
![image](https://user-images.githubusercontent.com/78768220/173779293-3df51cf0-2ac8-4b06-b506-ab9ae862a810.png)
![image](https://user-images.githubusercontent.com/78768220/173779313-e201b363-026a-4737-ba9f-6318d51c81bb.png)

## Last step

- [ ] Images & Files : shouldn't tell 'missing' but rather 'waiting save' or something like that
![image](https://user-images.githubusercontent.com/78768220/173779428-ed7986c4-04e0-402e-a440-e892313b8af4.png)

- [ ] Film review : the link and quote can be quite long, might be more readable to have each element on a different line
![image](https://user-images.githubusercontent.com/78768220/173779496-1edea30a-1f98-4751-b33e-fb857b58a897.png)

**Comment by frenchyrules** [comment]
### Snackbar that appears when you have input the wrong information to change your password:
proposition to change text to _your information to modify your password is invalid._
<img width="540" alt="image" src="https://user-images.githubusercontent.com/85220905/173779299-48496dbe-8806-4ddf-8072-0b8b224c0849.png">
