### ISSUE TITLE
Send an admin email each time an Event is created

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8622]
### Description

In order for the business team to follow who is organizing an event, we shall send to support@archipelmarket.com each time a new event is organized.

Do I need to create a sendgrid template? Some emails triggered by actions in-app do not have a sendgrid template. For ex, `A movie has been submitted`.

As for the content of the email, we can go with

```
A new event has been created.
Visit https://crm.blockframes.io/c/o/dashboard/crm/event/[eventId]
```

cc @Jackseed

**Comment by Jackseed** [comment]
So far all the admin emails (org created, new user connexion, movie submitted,..) are sent directly by the app without using any Sendgrid template

**Comment by cams-goussale** [comment]
```
A new [eventType] has been created: [eventName]
Visit https://crm.blockframes.io/c/o/dashboard/crm/event/[eventId]
```
