### ISSUE TITLE
Media Financiers - Toronto quick fixes

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#864]
Marketplace (explorer) part:
- [x] Delete Annette on the homepage 
- [x] Fix the profile toolbar 
- [x] Replace profile name inputs with display info
- [x] Replace Buy tokens section & the the buying bar of ethers on the profile page with a Rank section with subtitle "Upgrade my rank" and 3 buttons: silver / gold / platinium.
Each button change a "rank" parameter on Firebase
![image](https://user-images.githubusercontent.com/14964443/64115401-d0e1ff00-cd8f-11e9-99a2-571008f19c46.png)
- [x] Link "Rank position" above the profile picture to this new rank parameter 
![image](https://user-images.githubusercontent.com/14964443/64115459-ff5fda00-cd8f-11e9-81fe-09970c476cc9.png)
- [x] The Owners movie page must be accessible if you are gold or platinium but not silver
- [ ] Upgrade: Send Ethereum transaction when the user clicks on the gold or platinium buttons that send 0.1 ethers to the user address and the user Ethereum balance gives the user rank (0 = silver / 0.1 = gold / 0.2 platinium)

**Comment by pldespaigne** [comment]
- [ ] route problem -> `/explorer`
