### ISSUE TITLE
Sellers' analytics - Remove sellers' page view & interactions

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#8644]
### Context 
Competitors or org members watching movie pages and promo elements from other sellers shouldn't be counted as views

### To do
- [x] Remove analytics created by org members if their org has access to festival dashboard

**Comment by yspringfield** [comment]
Hi @Jackseed , as indicated [here](https://github.com/blockframes/blockframes/pull/8718#issue-1282219903), we simply ignore other sellers' data when showing the statistics to the seller.
Does this issue also involve avoiding saving analytics data when the initiator of such events are other sellers?
Or should we save the event data irrespective of who creates it and simply ignore those when showing the stats to other sellers ( which is what is currently implemented )?

**Comment by Jackseed** [comment]
Ignore it is the good way to go, thanks 👍
