### ISSUE TITLE
Update CMS Link

### ISSUE THREAD

**Issue by KvnMrs** [blockframes/blockframes#8655]
@cams-goussale  As we have seen with François I am creating this new issue so that if you wish you can add/modify a 'duration' party more easily from a Link CMS. And reuse it dynamically like the 'now' seen during the issue: https://github.com/blockframes/blockframes/issues/7724

For dev: The logic for it can be find in the file: `libs\utils\src\lib\form\form-state-url-encoder.ts`

**Comment by cams-goussale** [comment]
This issue is about having the possibility to have more parameters in the avails CMS link so we can set up things like `nextYear`, `nextWeek`, etc.

**Comment by phpgeekfr** [comment]
By default going to title list without any params (https://archipelcontent.com/c/o/marketplace/title) should set current date + 1 year to "licence end date" but the `load` function in `apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts` will erase this default value created in `new AvailsForm`.

So if any of our users types in https://archipelcontent.com/c/o/marketplace/title directly, end date will not be set correctly.

On https://archipelcontent.com/c/o/dashboard/avails end date is the good one : 

![image](https://github.com/blockframes/blockframes/assets/1194344/c86d1265-c509-4412-a553-f8a853e8967e)

**Comment by Jackseed** [comment]
Ok so if a user gets to catalog marketplace title list through a link within the app it works correctly but not if they go there with url, right?

**Comment by phpgeekfr** [comment]
yes, if they go there with url, "licence end date" will be current date

**Comment by phpgeekfr** [comment]
And in fact, this can be an issue because we have a link here 
![image](https://github.com/blockframes/blockframes/assets/1194344/a3c21160-d6b0-48d3-b680-273766f33cad)

that is `https://archipelcontent.com/c/o/marketplace/title`
