### ISSUE TITLE
Update pdf export

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8658]
### Update naming
Generate a title depending on the filters used, and use it as a header and as the file name? It would be a different format for AC and AM.

- [x] catalog: Archipel Content Library - Avails for [Territory] in [Rights] - [Content Type] - [Genre]
- [x] festival: Archipel Market Library - [Genre] - [Country of Origin]

If the filters were not filled in, then we ignore this field in the title.

_Originally posted by @cams-goussale in https://github.com/blockframes/blockframes/issues/8568#issuecomment-1157441542_

### Update pdf content
We discussed with Jokers team since they want to replace [their actual catalogue pdf manually updated ](https://drive.google.com/drive/u/1/folders/1c4Ec64_phEOnRTOPUR9xDFUfKruVnV8h)with our automatically generated catalogue.
They gave us pretty good feedback since they crafted their catalogue over the years for concrete use. Here is important stuff we should add to be complete:
- Link to title avails
- Title image ratio (eg `2.35`)
- Certifications (EOF + European Qualification), a badge or something visual would be good
- origin countries
- change a bit OV presentation for better understanding
- cast (top 3)
- sales pitch
- Rating

ex
<img width="725" alt="image" src="https://user-images.githubusercontent.com/14964443/176402226-ceb164b6-c825-4604-bfb3-8dd7975d3fc4.png">

**Comment by Jackseed** [comment]
app specific ?

**Comment by cams-goussale** [comment]
After UI/Dev/Product review:

- [ ] Validate with @Jackseed if we want the pdf export only on catalog-app.
- [ ] Identify exactly which changes have been made for the dev issue (if possible, add pastilles on mockup)
- [ ] Exclude the european flag from the header

Dev estimation: 4-5 days

**Comment by dmoncadalv** [comment]
[UI mockups ](https://www.figma.com/file/l9BpFo1XbEZqTGTLaaAI10/Titles-Lists?node-id=609%3A1917)

**Comment by cams-goussale** [comment]
> Validate with @Jackseed if we want the pdf export only on catalog-app.

Keep cross-app

**Comment by cams-goussale** [comment]
Add the button also on Dashboard side

**Comment by frenchyrules** [comment]
UPDATE
Export button UI [here](https://www.figma.com/file/TJWy1rkpF7rNMC07xGGHld/My-Titles?node-id=9%3A1623)

**Comment by Jackseed** [comment]
Small text change: instead of "See title" could we have something more dynamic like "Check online"?
sounds good to you @cams-goussale ?

**Comment by Jackseed** [comment]
![image](https://user-images.githubusercontent.com/14964443/188919674-3d884d23-9ffd-495e-a074-35cbd4dd82fc.png)

Some feedbacks:
- [ ] smaller space between each first lines (film type, countries, minutes)
- [ ] put closer versions to the title "Available Versions"
- [ ] change "Original Version" for "OV"
- [ ] Add "Directed by [director 1 first name + last name], [director 2 first name + last name],..."
- [ ] Remove the 3 dots "..." after the cast
- [ ] Rating is missing (from the design as well ...): could you add it below the duration and image format (and before qualifications) with: [rating value 1] ([rating country 1]),  [rating value 2] ([rating country 2]), ..// eg -12 ans (France), rated R (USA),..

**Comment by phpgeekfr** [comment]
@Jackseed is it ok for you like this ?
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/e91ded2b-174d-49e6-95b6-67dad843113d)

**Comment by cams-goussale** [comment]
Another review:

- [ ] The links Avails and Trailer redirects to the marketplace, so it doesn't work if it's exported from the dashboard side. On catalog, most dashboard users won't have access to marketplace. Can we differentiate the links depending if the export was done from dashboard or from marketplace side?
- [ ] There was a comment above to change the wording 'See title' by 'Check online'
- [ ] Also, would it make sense @Jackseed to add the link to the `Screener` instead of the `Trailer`?
- [ ] The initial issue mentionned updating the name of the file

 ```
catalog: Archipel Content Library - Avails for [Territory] in [Rights] - [Content Type] - [Genre]
 festival: Archipel Market Library - [Genre] - [Country of Origin]
```

**Comment by phpgeekfr** [comment]
> The initial issue mentionned updating the name of the file 

@cams-goussale  This is not already the case ?

example `titles-export-Archipel-Content-Library---Avails-for-Europe-in-TV---TV-1.pdf`
Or do you want to remove `titles-export-` ?

**Comment by phpgeekfr** [comment]
> would it make sense @Jackseed to add the link to the Screener instead of the Trailer?
To display or not the "trailer" link, I look for otherVideos or publicScreener (if on catalog).
On marketplace, both videos types are displayed at the same place. I can either update the link "trailer" to "screener" if there is one or add a third link (avails, trailer, screener)

**Comment by phpgeekfr** [comment]
> There was a comment above to change the wording 'See title' by 'Check online'

I did not have confirmation for this. Should I do it ?

**Comment by cams-goussale** [comment]
> example titles-export-Archipel-Content-Library---Avails-for-Europe-in-TV---TV-1.pdf
> Or do you want to remove titles-export- ?

Yes I think you can remove `titles-export` at the beginning. Also it only works on Marketplace side, not Dashboard.

> To display or not the "trailer" link, I look for otherVideos or publicScreener (if on catalog).
On marketplace, both videos types are displayed at the same place. I can either update the link "trailer" to "screener" if there is one or add a third link (avails, trailer, screener)

I think we can put the 3 links (avails, trailer, screener). If one of these elements is missing, we don't display it

> There was a comment above to change the wording 'See title' by 'Check online'
> I did not have confirmation for this. Should I do it ?

Yes let's do it

**Comment by phpgeekfr** [comment]
on dashboard side:

"see title/check online" should redirect to `/c/o/dashboard/title/5exussLOXeQGkNiibqnB` ?

for "trailer/screener" :
 - /c/o/dashboard/title/5exussLOXeQGkNiibqnB/main ?
 - or movie tunnel  /c/o/dashboard/tunnel/movie/5exussLOXeQGkNiibqnB/media-videos#videos

 where should the "avails" link redirect to ?
- /c/o/dashboard/avails/5exussLOXeQGkNiibqnB/map
- /c/o/dashboard/avails/select/5exussLOXeQGkNiibqnB/manage

**Comment by cams-goussale** [comment]
> "see title/check online" should redirect to /c/o/dashboard/title/5exussLOXeQGkNiibqnB ?

yes

> for "trailer/screener" :

/c/o/dashboard/title/5exussLOXeQGkNiibqnB/main

> where should the "avails" link redirect to ?

/c/o/dashboard/avails/5exussLOXeQGkNiibqnB/map

**Comment by phpgeekfr** [comment]
@cams-goussale @Jackseed 
I updated my env with latests updates: 

- https://catalog-blockframes-bruce.web.app/
- https://festival-blockframes-bruce.web.app/
- https://financiers-blockframes-bruce.web.app/

As explained earlier, I set a max limit of 450 movies that can be exported.

Please have a look and tell me if there is other things to update before merging into develop.

**Comment by cams-goussale** [comment]
- [ ] Let's revert back to links redirecting to marketplace everywhere
- [ ] Add a tooltip on the Export to Pdf button of the Dashboard side which says : `Links in the export will redirect to the marketplace`
- [ ] Modify the title in the file as follow:

Title: `Archipel Content Library`
Subtitle:

```
Filtered by:
Avails: [territories]
Content Type: [contenttype]
Genres: [genres]
```

We can use the same sizes as we have for the available versions:

![image](https://user-images.githubusercontent.com/93206363/189920102-894bdd5e-ba16-4f86-bc4a-d0a09f861f3d.png)

**Comment by phpgeekfr** [comment]
- [ ] and always display an h1 (title list dashboard side)

**Comment by phpgeekfr** [comment]
@cams-goussale @Jackseed 
This can be tested again here :

- https://catalog-blockframes-bruce.web.app/
- https://festival-blockframes-bruce.web.app/
- https://financiers-blockframes-bruce.web.app/

using same user accounts as `staging`.

**Comment by cams-goussale** [comment]
Sorry, still another little bug on this issue.. 
If a title is not with status == accepted, it shouldn't be included in the Dashboard export. Otherwise when clicking on the links (which goes to marketplace), it creates an error.

The rest looks good to me

**Comment by phpgeekfr** [comment]
request from #7546 
- [ ] change "AC library" with "Org name Library"
- [ ] when there is no org logo we currently use Archipel Content logo, I would remove it for nothing as you suggest

**Comment by phpgeekfr** [comment]
@cams-goussale @Jackseed should be all good
