### ISSUE TITLE
Documentation - Upload components in a form list

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8671]
Add comments in the code

**Comment by RemcoSimonides** [comment]
Hee, I don't understand what needs to be done here. What does it mean to upload components in a form list?

**Comment by cams-goussale** [comment]
@phpgeekfr could you explain what you had in mind when you talked about this?

**Comment by phpgeekfr** [comment]
I mean:  document existing components that uses a formList to upload data.

This one for example  `libs/movie/src/lib/movie/form/media-videos/media-videos.component.html`: 
![image](https://user-images.githubusercontent.com/1194344/177138905-be0b613b-3f0a-40ff-a28e-4ce690fead3d.png)


We can add many "other videos" with `title`, `video type` and upload a video.

This feature is hard for me to understand (and also a bit buggy: reset/cancel for example and I think the "add" button is currently missing)

**Comment by phpgeekfr** [comment]
related to https://github.com/blockframes/blockframes/pull/8579  https://github.com/blockframes/blockframes/issues/8578

**Comment by RemcoSimonides** [comment]
The "add" button is only shown if there is no active form. If the @Input keepFormOpen is true on `bf-form-list` component, there will always be an active form and thus the "add" button doesn't need to be shown.

There is only a file-uploader component in form-list in two places:
Notes / Statement (libs/movie/src/lib/movie/form/media-notes/notes.component.html)
Videos (libs/movie/src/lib/movie/form/media-videos/media-videos.component.html)

However, similar is how still photos are uploaded (libs/movie/src/lib/movie/form/media-images/media-images.component.html) and in the file explorer (libs/media/src/lib/file/explorer/explorer.model.ts), the uploads in a file list don't work properly either.
Media types which are of type array and potentially could use the same file list upload component:
On Movie: Still photos, videos, notes
On Org: Documents, Videos
