### ISSUE TITLE
Changes on filters of the Library page

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8680]
On festival app, can we add these additional filters to the /library page:

- Release year
- Festival name
- Qualification

Can we also group the festival names by category: A festival / B festival / C festival. Business team should provide this categorization.

**Comment by 2amarkina** [comment]
**v1 of Festival Filter (quick)**
![Снимок экрана 2022-06-30 в 16.11.29.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/cbba229a-8ac8-424c-b5d6-a1101f391dcf)

**v2 of Festival Filter (with categories)**
![Снимок экрана 2022-06-30 в 16.55.06.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/d3c2c5b9-ec02-493a-bc4f-ccf88d87e5fd)

**Qualifications**
![Снимок экрана 2022-06-30 в 17.01.08.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/b3b60ce4-2320-49a0-bd58-1898ff486192)

**All together on the Library Page**
![Снимок экрана 2022-06-30 в 17.19.27.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/9bb07b27-320b-4897-9d92-8ade9328b79b)

[All the wireframes can be found here](https://www.figma.com/file/M3bVHcVyEzmNWOXuBq0m3Q/Titles-Page?node-id=0%3A1)

**Comment by cams-goussale** [comment]
Qualifications
- Remove Arts & Essais
- EOF: Add french speaking

**Comment by cams-goussale** [comment]
[List of titles with Arts & Essais or Awards](https://docs.google.com/spreadsheets/d/10jJ7uRHhd-TCl4_7vmT3K9SFVDkRYnE_6AyJtrCUrBo/edit#gid=0)
