### ISSUE TITLE
Label to place either on movie cover, either on org

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8685]
We'd like to be able to add and personnalize a tag/label on either the movie cover, either the organization logo. The idea is to do marketing in-app by pushing some content or organization. For example
- `Going to Cannes` label could be put on org logos before the Cannes festival
- `Premium` label could be used on movie covers when we have a very good title we want to push
- etc.

The idea is that we should be able to personnalize the tags with the wording we need (maybe through CMS).

**Comment by dmoncadalv** [comment]
[Ui Mockup Drafts](https://www.figma.com/file/mx5vhUSuslt4ekCAswR8Qv/Homepage?node-id=323%3A916)
