### ISSUE TITLE
Add a filter on org page catalog

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8686]
Add the same filter we have on the Library page into the Organization page. So that Buyers can filter content of a specific Seller.

**Comment by cams-goussale** [comment]
[UI mockups](https://www.figma.com/file/sygFKSH1P53d8TdZ4n8xWi/Sellers?node-id=0%3A1)

**Comment by phpgeekfr** [comment]
- Do we have to implement load/save filter as in #8673 ?
- Here data comes from firestore directly but from algolia on organization page, so it can take some time to implement

**Comment by KevinDurand974** [comment]
Sould I add on Financiers too?
It has the same page but with few or no movies. (more like no movie)

**Comment by cams-goussale** [comment]
Yes let's put it everywhere for consistency.

**Comment by phpgeekfr** [comment]
Closed this PR https://github.com/blockframes/blockframes/pull/8847 as work should be reworked with title search coming from Algolia (https://github.com/blockframes/blockframes/pull/8847#pullrequestreview-1054179349)

**Comment by Jackseed** [comment]
deprecated issue
