### ISSUE TITLE
Save analytics events for promotional elements clicked.

### ISSUE THREAD

**Issue by yspringfield** [blockframes/blockframes#8693]
Currently, we save only the analytics events for no other promotional elements but videos.

We'll need to do same for all promotional elements. A good place to start will be to proceed by adding an onclick listener to
`libs/movie/src/lib/movie/marketplace/shell/shell.component.html` line 56 and in the listener we trigger the event.

Similar to how it's done in `libs/movie/src/lib/movie/marketplace/main/main.component.ts` line 43

**Comment by RemcoSimonides** [comment]
@cams-goussale  Where this statistic is shown, the column name is named "Video Plays". Should I change it back to "Promo reels opened"?

**Comment by cams-goussale** [comment]
@RemcoSimonides so if now clicks on any promotional elements is tracked (weather it's a video type other, a sales pitch video, a moodboard, a scenario, a still image, etc etc) then let's use the column name `Promo Elements Clicked`

**Comment by RemcoSimonides** [comment]
The term we use in the code for this analytic is 'promoReelOpened'. Should it instead be 'promoElementOpened' and every file/video opened counts to that?

FYI, Still images are obviously already displayed without clicking on them, but I could trigger this promoElementOpened if the image is clicked and they look at it in full screen

**Comment by cams-goussale** [comment]
> The term we use in the code for this analytic is 'promoReelOpened'. Should it instead be 'promoElementOpened' and every file/video opened counts to that?

Yes, I think `promoElementOpened` would be more meaningful.

> FYI, Still images are obviously already displayed without clicking on them, but I could trigger this promoElementOpened if the image is clicked and they look at it in full screen

That would be great indeed
