### ISSUE TITLE
Sellers' analytics - Buyers' Activities - Pie chart loading super long

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#8702]
app: festival
page: c/o/dashboard/home/buyer

I went on seller with a good amount of analytics and the pie chart is super long to load (2-3min) though the numbers itself are loaded.
![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/17f9958c-a83a-465e-b57b-de729d46c2a1)

**Comment by yspringfield** [comment]
[dev+hollie-lnl@blockframes.io](mailto:dev+hollie-lnl@blockframes.io)
https://staging.archipelmarket.com/c/o/dashboard/home/buyer
Tried reproducing in the following ways:
* Empty my cache and reconnect anew as the indicated user.
* Opened a new incognito tab and connected as the user.

In both attempts, the page loaded properly in under 5seconds.
Couldn't reproduce the issue.

**Comment by phpgeekfr** [comment]
If I go directly to the page, I have no issue and it loads within less than 3 secs.

But if I'm on https://staging.archipelmarket.com/c/o/dashboard/home/buyer then go to https://staging.archipelmarket.com/c/o/account/profile/view/settings and using back arrow from browser I'm having the same issue as @Jackseed .

It started to work after 2 or 3 retries and cannot reproduce anymore but CPU usage is very high on this page.

**Comment by Jackseed** [comment]
Did you have any improvements on this? I made a demo last week and it was really buggy since as long as the pie chart is loading, if I scroll down, it keeps anchor me to the top of the page each 2-3sec
