### ISSUE TITLE
Screening stat improvements - add a "Watching now" status on users

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#8717]
Currently, we only save watchTime (duration) for a screening or slate directly in `invitation` document . As already suggested in #8286 we could move this information to `event` document ( a bit like `attendees` for meetings) or move this information into `analytics` collection directly.

To be able to display a `Watching now` information, we should add a timestamp when we increment WatchTime in `trackWatchTime`. Like this, if timestamp is less than a minute from now, we could say that user is currently watching the video.

I see several solutions:
- 1 update `Invitation` interface to add a `watchDate` and update it when we increment `watchTime`
- 2 move `watchTime` and `watchDate` in `event` document meta data
- 3 add new `analytics` event types to store this data

First solution looks like the fastest one to implement as is does not even require a migration. But we will not be able to track watchTime for `public screenings` that may not have a invitation.

Second and third solution can be cleaner but will be much hard to implement as it will require a migration and a lot of refactoring in existing code related to event and analytics.

@Jackseed @yspringfield what do do think ? And what would be the easiest solution to display this kind of data in analytics panels ?

**Comment by yspringfield** [comment]
I opt for `1 update Invitation interface to add a watchDate and update it when we increment watchTime`

For posterity, 
With @RemcoSimonides, we were in preliminary talks on bringing the event statistics into the event collection. This will entail a lot of moving pieces as there already is some statistics that depend on it being located in the `invitation` as is currently. But we might have to change that in the future.

**Comment by phpgeekfr** [comment]
3 places to implement:
- http://localhost:4200/c/o/dashboard/home/buyer/YfLdeeIKAKXdSkiAJPLo3WhQj8z1
![image](https://user-images.githubusercontent.com/1194344/175979291-83722e9d-4436-4c98-8705-d13e594af018.png)

-  http://localhost:4200/c/o/dashboard/home/title/rkT1PdqZbPXaTqvdpEPw
![image](https://user-images.githubusercontent.com/1194344/175979396-7b2d60d0-4f98-41fd-8c3a-32aec74e2ba5.png)

- http://localhost:4200/c/o/dashboard/event/RHHIPCrgV0yJVxg77Iln/edit/statistics
![image](https://user-images.githubusercontent.com/1194344/175979457-52abc763-e7dc-4f90-8873-df2520666f95.png)

Column name `Watching now` yes/no

For exports: add Date only as `Watching Ended`

**Comment by phpgeekfr** [comment]
how to display if user is Watching now : 
![image](https://user-images.githubusercontent.com/1194344/176145697-39fe55e8-f0f0-429e-8bd1-03a6c14d1f71.png)

**Comment by cams-goussale** [comment]
@phpgeekfr can we change the column name from `Watching Ended` to `Screening Session Ended` ?

**Comment by Jackseed** [comment]
Sorry I see this too late but I re-open it cause it looks really cleaner to go for proposition `3` as in the near future we might go for event analytics displayed in the Sellers' analytics section. Also not having watch time for public screenings is an important bug that would be really nice to fix.
@phpgeekfr could you estimate the complexity and/or time to implement this solution?

**Comment by phpgeekfr** [comment]
Need to check deeper but this will be really time consuming as existing analytics pages are relying on this data being stored on invitation documents

CF @yspringfield https://github.com/blockframes/blockframes/issues/8717#issuecomment-1164039543

This solution should be considered as a separate issue as all event statistics should be stored into analytics collection, not only the watch time but number of attendees, invitation count etc.

**Comment by cams-goussale** [comment]
I've created a dedicated issue #8733 and we can rediscuss in the future backlog with Bruce.
