### ISSUE TITLE
Movie tunnel - Screeners for Cross app

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8731]
Currently in the movie tunnel, we have 3 places where a seller can upload their video:

- Sales pitch
- Screener (= whole movie)
- Other videos (trailers, teasers, promoreel, etc.)

By default, the screener video is private (= not visible on the marketplace). And the other videos are public.

The problem is that the behavior for the screener is different on Archipel Market and Archipel Content:
- AM : fresh movies, the screener must be private. The goal is for the Seller to organize a Screening event, to promote the movie.
- AC: catalog titles, the screener must be public. No buyer will buy the title until they have seen it. So the movie must be available on the marketplace.

How can we find an easy solution for Sellers of both apps? Some ideas:
- a checkbox to make the screener public or private (but can be difficult to explain to sellers what it means)
- change the wording? instead of screener, we use "Private Screener"
- an adhoc page for AM only to upload the screener
- ...

**Comment by 2amarkina** [comment]
[Work in progress here](https://www.figma.com/file/qpLBi85x3y0s4fLpJPACOm/%5B-Wireframing-Elements-%5D?node-id=2921%3A27186)

**Comment by cams-goussale** [comment]
# WIP Review 08.07.2022

## Archipel Content

- [ ] When uploading the screener on the screener page, i had this error
![image](https://user-images.githubusercontent.com/93206363/177984538-ae1b5210-d3bc-4706-891c-00fb8208f07d.png)
