### ISSUE TITLE
Move events analytics in analytics collection

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8733]
_Originally posted by @phpgeekfr in https://github.com/blockframes/blockframes/issues/8717#issuecomment-1168905726_

Implement Option `3` of the initial issue https://github.com/blockframes/blockframes/issues/8717#issue-1280267790

**Comment by RemcoSimonides** [comment]
I agree with Bruce's comment (https://github.com/blockframes/blockframes/issues/8717#issuecomment-1168905726)

> Need to check deeper but this will be really time consuming as existing analytics pages are relying on this data being stored on invitation documents.
> 
> CF @yspringfield https://github.com/blockframes/blockframes/issues/8717#issuecomment-1164039543
> 
> This solution should be considered as a separate issue as all event statistics should be stored into analytics collection, not only the watch time but number of attendees, invitation count etc.

This feature requires quite some changes. We'd have to create triggers for events like
* Send invitation/request
* Accepted invitation/request
* Declined invitation/request
* Visit screening page (maybe have watch time on this doc)

A migration is required.
Rework of all components which have event statistic (takes time but the code will be easier to maintain once it's the same as all the other analytics we have for Sellers' Analytics).

**Comment by Jackseed** [comment]
Ok thanks for the feedback, looks like a great and must-have clean but don't know if we'll have the ressource to take care of it; stays on hold for now

**Comment by Jackseed** [comment]
Not a priority anymore > closing
