### ISSUE TITLE
CRM exports

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8834]
We'd like to be able to export more info from the CRM to improve our internal KPIs documentation, and our operational follow ups (media upload, avails upload etc.).

Here is a list of items that would be needed:

- [x] blockframesAdmin can export all fields from movie collection. If there is some nested data, I think it's fine and we can do something basic.
- [x] blockframesAdmin can export Analytics collection. Currently, some of this data is displayed on movie page, so we could either add it to the Movie export, either do a separate Analytics page. (FYI the query Bruce gave me in BigQuery to extract the buyer interactions doesn't return any data any more. I think it's because it was previously tracked with GA and now it's internally in firebase.
- [x] blockframesadmin can export all contracts
- [x] blockframesAdmin can export all offers

**Comment by RemcoSimonides** [comment]
Movie fields chosen not to export: boxOffice, originalRelease, review (they are array (a.k.a. list) of objects (a.k.a. multiple values per item in list) and therefore complex to put into single excel cells.

**Comment by RemcoSimonides** [comment]
2 tasks done
2 left to do

**Comment by cams-goussale** [comment]
If possible, add to this issue:

- [ ] in the csv export of org, add a column for the creation date of the organization

**Comment by Jackseed** [comment]
@phpgeekfr let's see how difficult/long it is to conclude that issue and if we can keep it for next release

**Comment by cams-goussale** [comment]
In the movie export, can we add some fields to what Remco already did?

- [ ] if title has a poster
- [ ] if title has a screener video
- [ ] if title has a publicVideo
- [ ] if title has a salesPitch video
- [ ] if title has otherVideos
- [ ] season number (titles.series)

**Comment by Jackseed** [comment]
To be complete I would also add:
- [ ] if title has a banner
- [ ] if title has stills

**Comment by phpgeekfr** [comment]
- [ ] some movies (`1oWLiyBJTV6Xs0XlRH7f` for example) have a media value for OriginalRelease that does not exists: 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/571a98f2-07b0-4139-91c2-1a63b07c81ef)

**Comment by cams-goussale** [comment]
>  some movies (1oWLiyBJTV6Xs0XlRH7f for example) have a media value for OriginalRelease that does not exists:

Oh, I thought we removed `Theatrical` in the Media list for Avails, but I didn't remember it was for OriginalRelease too.
FYI @Jackseed we currently have  Pay TV, Free TV, Festival and Empty as options for the Release Media

![image](https://user-images.githubusercontent.com/93206363/189298973-2400ea1a-8c71-4593-945e-259d3ee79159.png)

I wouldn't say it's a priority now, so if ok with @Jackseed , let's just remove the media value with Theatrical for the movies concerned. Can we have the list of movies concerned?

**Comment by phpgeekfr** [comment]
I created a new list for releaseMedia :
```
export const releaseMedias = {
  payTv: 'Pay TV',
  freeTv: 'Free TV',
  payPerView: 'Pay Per View',
  est: 'EST',
  nVod: 'N-VOD',
  aVod: 'A-VOD',
  fVod: 'F-VOD',
  sVod: 'S-VOD',
  tVod: 'T-VOD',
  inflight: 'Inflight',
  boats: 'Boats',
  hotels: 'Hotels',
  educational: 'Educational',
  festival: 'Festival',
  rental: 'Rental',
  theatrical: 'Theatrical',
  through: 'Sell Through',
} as const
```

This is the exact same as other with `theatrical` in addition.

But by looking at the movie form, we remove theses values : `[withoutValues]="['payPerView', 'est', 'nVod','aVod', 'fVod', 'sVod', 'tVod', 'inflight', 'boats', 'educational', 'rental','through', 'hotels']"` ending with this only : 

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/0cf41bec-af98-4590-8c31-3ff332bebb49)

Theses are not the same as in Excel template : 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/52e71067-1178-4c16-8c82-e687b6f1848a)

Current used values on production: `['theatrical', 'festival', 'video', 'freeTv', 'payTv', 's-vod']`



In order to uniformize, values from movie form and excel template should be the same. ReleaseMedia list should contain only the desired values. Depending on the choice we make, a migration could be necessary.

**Comment by phpgeekfr** [comment]
new `releaseMedia` list :
```
export const releaseMedias = {
  payTv: 'Pay TV',
  freeTv: 'Free TV',
  sVod: 'S-VOD',
  video: 'Video',
  festival: 'Festival',
  theatrical: 'Theatrical',
} as const
```

- [ ] With this new config, only one movie in production should be updated: `VTITy9knNEHls6fO4v0A` (from `s-vod` to `sVod`) @cams-goussale @Jackseed do you want me to do it manually right now ?

**Comment by Jackseed** [comment]
alright I did it
