### ISSUE TITLE
New analytics to track for CRM / admin

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8855]
This data is for blockframesAdmin only.

- [x] Could we track the clicks on the pdf export button?

Need to know:
- who clicked on the export button
- when
- optional, if doable: what research was exported
- tracker on marketplace & dashboard

- [x] Could we track users who used the filters on the title page - marketplace? (catalog app as a priority. If we can have both apps, great).

Need to know:
- who clicked on a filter or search bar
- when
- optional, if doable: which filter was clicked
- not optional: if avails filter was clicked

- [x] Could we track users who used the avails (map or calendar) on a title page?

Need to know:
- who searched avails
- when
- optional, if doable: what research was done
- calendar or map use

**Comment by cams-goussale** [comment]
Track on dashboard & marketplace

**Comment by phpgeekfr** [comment]
> Could we track the clicks on the pdf export button?

Should we track when user click on export but with too many tiles (ie with snackbar: `Sorry, you can\'t have an export with that many titles.`) ?

**Comment by cams-goussale** [comment]
> Should we track when user click on export but with too many tiles (ie with snackbar: Sorry, you can\'t have an export with that many titles.) ?

If possible yes. It could help us detect users who are trying to export the whole catalog for ex.

**Comment by phpgeekfr** [comment]
- [ ] also track save & load clicks on saved search button
