### ISSUE TITLE
Poster ratio movie tunnel

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8856]
After @Jackseed tried to import some movie posters which were very long, we noticed than indeed our ratio 3/4 is insufficient to handle these cases, and it cuts the credits. We need to find another ratio which allows longer posters to be included completely.

Please contact me for poster examples.

**Comment by cams-goussale** [comment]
- [ ] PM to find the correct ratio
- [ ] What will happen to previous posters?

**Comment by Jackseed** [comment]
Outdated
