### ISSUE TITLE
Tracking clicks on the screener video on AC

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8857]
This was a suggestion from a Seller I had on the phone. She wanted to know if we were able to tell her the average nb of clicks on the screener videos, so she could evaluate the importance of uploading her screener.

I think it can be very valuable data indeed. Either for Sellers, either for us... to target better the Buyers having a deep interest in a movie. What do you think @Jackseed ?

**Comment by Jackseed** [comment]
I would definitely go for it but we need to think about the UI. We can't bring all the analytics part from AM and we shouldn't diverge too much title list & view from the 2 apps.
That being said I would go for a crm solution first and build on that later if stats are interesting to share. 
Though we should be cautious with data loading, that was a pain point before. I guess we can go for a firestore solution (and not GA) that should be quick but let's keep that in mind when discussing with Bruce.

**Comment by cams-goussale** [comment]
Currently enough with analytics crm export
