### ISSUE TITLE
support@archipelcontent.com doesn't receive emails

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8866]
Seems this emails has been broken since early june. Still can't find the rout of the problem
cc @Jackseed

**Comment by cams-goussale** [comment]
Actually the email itself seems to work (Aurore receives it) but our email "A movie has been submitted" or "New user connexion" isn't sent

**Comment by Jackseed** [comment]
Problem solved: email transfer from google domain was canceled, which marked the email address as "bounce" in Sendgrid. 
Back to normal
