### ISSUE TITLE
Video player enhancements 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#8867]
I guess it's never as easy as it seems but JW Player updated their custom video player and it looks like we can enable 2 features that are promising for our buyers:
- playback speed
- casting (=> Airplay?)

If it's as easy as the 2 clicks from that [video](https://jwp.io/s/XRQJakfO) I would go for it. Otherwise let's discuss this and close it if too complex.

cc @cams-goussale for playback speed, I know it's a controversial feature but based on our research sellers want what's best for buyers and buyers want to save their time. 
Please confirm to be sure :)

**Comment by cams-goussale** [comment]
Yeah i'm in! I also saw the video and wasn't sure if it was as easy as it looks like ^^
If Devs are ok, i'd go for it

**Comment by phpgeekfr** [comment]
I updated dev jwplayer (`LVeBD5vf` staging and dev envs)  and activated 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/159ad59a-2c13-47ac-b051-d52c75bb6518)

I can now choose speed : 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/5d8fd316-46b9-4131-bbbd-12a8c2087ec9)

For the casting, I think we need to test with a compatible device. @Jackseed @cams-goussale 

If you want, I think you can already enable new features for prod player `lpkRdflk` as it is really just choosing config and hitting save

**Comment by cams-goussale** [comment]
It's done for playback speed 👯‍♀️

**Comment by Jackseed** [comment]
Close it, no budget for testing Airplay. I will create a dedicated issue if things change.
