### ISSUE TITLE
Also skip uploaded movies of public directory when doing restoreStorageFromCi

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#8883]
Also skip uploaded movies of public directory when doing restoreStorageFromCi

Currently :
```
const exclude = 'protected.*.mp4$|protected.*.mov$|protected.*.mkv$|protected.*.3gpp$|protected.*.wmv$|protected.*.avi$';
```

in `libs/devops/src/lib/firebase-utils/restore-storage-from-ci.ts`

**Comment by phpgeekfr** [comment]
Linked with #8532 ( for the record )

**Comment by phpgeekfr** [comment]
Performing this will reduce a bit the storage used by `CI` but most disk usage is located in prod backups : 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/19c466f8-821d-449a-b1ee-af615c7fb552)

Currently we keep 45 days of backups (1 backup per week). @cams-goussale @Jackseed do you want to keep only half of this ? or less ?

**Comment by cams-goussale** [comment]
Is the CI using the storage backup? what for?
(i suppose the more we can reduce the better)

**Comment by phpgeekfr** [comment]
CI is only using `LATEST-ANON-STORAGE` directory. Others directories are just security measures to keep some productions backups. 
IMO, we should have at least 2 or 3 backups in case we take more than 2 weeks to discover an important issue on storage

**Comment by cams-goussale** [comment]
3 weeks sounds good. @Jackseed what do you think?
