### ISSUE TITLE
Event Statistics Excel export

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8892]
When exporting statistics of an event on the event form, there is a mistake in the field `average watchtime`, which shows 0sec if there is at least 1 invitee with `watchtime == null`. We decided to ignore these users when calculating the average watchime (as you can see on the cards in app).

See eventId `sG3BdjJMbp5Y4AhPU8C8` in prod for example
Or eventId `FZhpIu1rlLk0hU8NHxFA` in staging for example

![image](https://user-images.githubusercontent.com/93206363/189611606-2d1ca88a-11e3-4777-8082-c58a9b57b4d2.png)

![image](https://user-images.githubusercontent.com/93206363/189611837-af428351-6bb3-4ff9-8c8b-5cea401634d5.png)

**Comment by phpgeekfr** [comment]
Ok solved.
Number of attendees was also not the same: 
- on app, number of attendees are users with a watchtime duration, they actually attended the screening
- on export, it was the number of accepted invitation, even if user did not go to the screening room

I updated export so it takes only  users with a watchtime duration as the front app do.

**Comment by cams-goussale** [comment]
Looks good. I'm closing the issue
