### ISSUE TITLE
Issue with "load more" and page number in url on list pages

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#8893]
With no filters, when reaching end of results, loader displays `You've viewed 1000 of 0 titles` : 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/a23bbca2-0b1a-4c3a-8834-dca32038be69)

The page number is not correctly set, is this example page 22 will display zero titles because we reached end of results of algolia side. So if we take this url, no results will be shown.
example : https://festival-blockframes-bruce.web.app/c/o/marketplace/title?formValue=%7B%22query%22:%22%22,%22page%22:20,%22storeStatus%22:%5B%22accepted%22%5D,%22genres%22:%5B%5D,%22originCountries%22:%5B%5D,%22languages%22:%7B%22languages%22:%5B%5D,%22versions%22:%7B%22original%22:false,%22dubbed%22:false,%22subtitle%22:false,%22caption%22:false%7D%7D,%22productionStatus%22:%5B%5D,%22minBudget%22:0,%22minReleaseYear%22:0,%22sellers%22:%5B%5D,%22socialGoals%22:%5B%5D,%22contentType%22:null,%22runningTime%22:0,%22hitsPerPage%22:50,%22festivals%22:%5B%5D,%22certifications%22:%5B%5D%7D

Also, If I set page to 2 for example, I should see 250 titles but I only see 50 starting from 200.

Finally, this code does not seems to work or to be used, need to check (used on title and org lists) : 
```
        /* hitsViewed is just the current state of displayed movies, this information is important for comparing
        the overall possible results which is represented by nbHits.
        If nbHits and hitsViewed are the same, we know that we are on the last page from the algolia index.
        So when the next valueChange is happening we need to reset everything and start from beginning  */
        this.hitsViewed = this.movieResultsState.value.length;
        if (this.lastPage && this.searchForm.page.value !== 0) {
          this.hitsViewed = 0;
          this.searchForm.page.setValue(0);
        }
        this.lastPage = this.hitsViewed === this.nbHits;
```

**Comment by phpgeekfr** [comment]
Also, if I'm on page 5 for example and I update filters (country set o france), if there is not enough results (250), no titles will be shown

**Comment by Jackseed** [comment]
Go for the easy solution: remove page number in the url

**Comment by phpgeekfr** [comment]
When reaching end of results, this also disappear :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/3c95e1e0-fc58-4f1f-85f6-5c47eede4ab3)

**Comment by phpgeekfr** [comment]
search for `#8893` in code
