### ISSUE TITLE
To take into account when catalog app will have more than 1000 movies

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#8894]
On catalog app, behavior to retrieve title list is different than archipel.
Since avails data is not on algolia side, we first take a maximum of 1000 movies (algolia limitation per page) corresponding to common filters (genre, origin country etc) and then we filter with contract and avails data using firebase.

If catalog have move than 1000 movies, method to fetch all movies on algolia side will have to be updated, using a recursing call.

linked with #8893

**Comment by phpgeekfr** [comment]
- [ ] check `paginationLimitedTo` introduced in #8990 for 1000 limitation
- [ ] there is no page number in the url for catalog, so as soon as user has loaded all titles once, then they're always all showing. (from #8990)

**Comment by cams-goussale** [comment]
> there is no page number in the url for catalog, so as soon as user has loaded all titles once, then they're always all showing.

Let's talk about this during a review before making any change. I'd like to discuss what's the best behavior
