### ISSUE TITLE
Review Release 4.5

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#8907]
Issues included in the release (complete the list if needed):

- [x] https://github.com/blockframes/blockframes/issues/8834
- [x] https://github.com/blockframes/blockframes/issues/8658
- [x] https://github.com/blockframes/blockframes/issues/7546
- [x] https://github.com/blockframes/blockframes/issues/6447
- [x] https://github.com/blockframes/blockframes/issues/8833
- [x] https://github.com/blockframes/blockframes/issues/8620
- [x] https://github.com/blockframes/blockframes/issues/8680
- [x] https://github.com/blockframes/blockframes/issues/7268
- [x] https://github.com/blockframes/blockframes/issues/8892
- [x] https://github.com/blockframes/blockframes/issues/8693
- [x] https://github.com/blockframes/blockframes/issues/8784
- [x] https://github.com/blockframes/blockframes/issues/8804
- [x] https://github.com/blockframes/blockframes/issues/8805
- [x] https://github.com/blockframes/blockframes/issues/8841
- [x] https://github.com/blockframes/blockframes/issues/8917

**Comment by cams-goussale** [comment]
## Events

- [ ] In all events email invitations, could we add the `s` to `hour` only if the number is > 1 ? Email templates concerned: `d-ecd4fd15707142cdbb1a72179be9d20b`, `d-de129a43fb43430a8e1d4e8de4d43e46`
![image](https://user-images.githubusercontent.com/93206363/191008636-181d6e68-41fe-4b4a-a71f-4c753fa69181.png)

**Comment by phpgeekfr** [comment]
> I think this notification and the corresponding email isn't sent.

Have you made the changes through CRM and the checkbox selected ?
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/0038ac54-328f-4cd5-a76d-a75eb4cbacd5)

**Comment by phpgeekfr** [comment]
> In the movie tunnel, page /movie/[titleId]/available-version, user shouldnt be able to save a language if it isn't from the drop down list.

Ok, please note that the fix will also be present on other pages : contract and negotiation

**Comment by cams-goussale** [comment]
> Looks like the template was not active because you would have at least : from orgName ( - ) with parentheses containing -

Ok I tried again and it works

> Have you made the changes through CRM and the checkbox selected ?

Also tried again and works

**Comment by phpgeekfr** [comment]
>The dashboard page is very slow to load, especially the map. Could we add the logo spinner here?

About the map loading issue, looks like there not really much we can do, there is one html tag added per country, this slows down computer.

**Comment by phpgeekfr** [comment]
- [ ] added new spinner almost everywhere where old was still used

**Comment by cams-goussale** [comment]
## Analytics

- [ ] On the /c/o/dashboard/home/title/[titleId] report page, when there never was a screening organized, there should be an empty state artwork instead of empty data. [UI mockups here](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?node-id=298%3A28495).

![image](https://user-images.githubusercontent.com/93206363/191307175-c76cfcb0-3b5f-413e-975d-349596459fc8.png)

![image](https://user-images.githubusercontent.com/93206363/191307114-14610011-db10-4e31-a1d8-2450a8e9937d.png)

**Comment by phpgeekfr** [comment]
>![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/957ce0da-3915-4453-ab36-4277baa33619)

**Comment by phpgeekfr** [comment]
>![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/957ce0da-3915-4453-ab36-4277baa33619)

**Comment by phpgeekfr** [comment]
>![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/957ce0da-3915-4453-ab36-4277baa33619)

**Comment by phpgeekfr** [comment]
> Is there a reason why the cards of the page /c/o/dashboard/home/title/[titleId] and the page /c/o/dashboard/event/[eventId]/edit/statistics have a different size? I think it's more estheatics on the event statistics page, as they are displayed in 1 row.

This is the same component used for both screens. Only size difference I see is when left panel is opened or not : 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/8d1eb213-9277-4fa0-be0b-4bf64d65bed7)

**Comment by phpgeekfr** [comment]
>I did a test again with an event 02L9gsoY4WTdGbxpOKha having 3 users invited, 1 who requested access. I expect the traction rate to be 1/4 (25%) but it shows 0%

tested right now and it shows:
https://staging.archipelmarket.com/c/o/dashboard/event/oxKNV139HUGbOMWuHMCo/edit/statistics
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/9a6d2fb9-07a5-4f35-b4d3-168cefb79304)

But the in formula for "traction"   :`total_requests/total_invitation * 100`, `total_requests` is not the amount of users that request access but the ones that clicked on "request screeening"

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/cf1cc941-674e-48d8-9345-3ad1c7be1bcb)

**Comment by phpgeekfr** [comment]
>This notification has a bug on the name of the event. Here it should show Test name screening (8VvsLP9hMC233rtzyb9b)

now :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/9fdacccb-1945-44de-b165-c6e33714e45e)


>This notification doesn't have the right button text. It should be Go to [Event Type]

now :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/b9eb9956-01d3-4e18-b8aa-f8bafeb54b6a)

**Comment by phpgeekfr** [comment]
- [x] as discussed with @Jackseed this table is now displaying 25 items per page ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/db4d8b6c-f925-4ac0-92f1-d8420a8d8b4d)
- [x] other tables from analytics dashboard that had 5 items per page are now set to 10 items per page

**Comment by Jackseed** [comment]
### CRM Exports 
#### Movie
- [ ] That's weird export fail on some titles I don't know why. Here on line 33 the line starts with `English"` whereas it should be an id. In fact it's part of the above title data (line 32) that came to the line. 
It looks to me that it's link to a missing `"` before `English`. I don't know why there are `"` everywhere but here it's missing. 
Also lines 35, 37, 39 and 40 are strange. 
The strangest thing in all that is that I tested it with @cams-goussale and she hadn't any error... Maybe that's my excel version? Anyway it's keep happening so I guess it's worth mentioning and investigating.
I keep the file untouch if needed

<img width="191" alt="image" src="https://user-images.githubusercontent.com/14964443/191703386-90e4ac6a-5640-4488-8b77-1cc703062fb4.png">

**Comment by phpgeekfr** [comment]
- [ ] Should not have app "blockframes" to create an org on CRM 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/47ae5768-6c9c-46fb-a4a5-e603fc4c2ca9)

**Comment by phpgeekfr** [comment]
- [ ] last column should not be called "uid" but "actions"
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/0edcd552-cc16-4404-a902-3f9308fce707)

**Comment by phpgeekfr** [comment]
- [ ] When I receive a mail to attend an event, I cannot click on "activate account" 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/c6c17d2b-6d0a-42ee-bc0b-47b9cb5f9006)

**Comment by phpgeekfr** [comment]
- [ ] If user is removed from company, he can ask to join an existing company but not create a new one (permission denied). And if user is kicked again from new company, he cannot access app anymore because he already have an accepted invitation to join org (guard issue)

**Comment by phpgeekfr** [comment]
- [ ] with few data (1 title and 1 user who interacted with) map is broken in dashboard home ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/a82b1367-a014-472e-b192-b4c7e0d3ccfb)

**Comment by phpgeekfr** [comment]
- [ ] top 1 country should be USA but it is south korea ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/a9fd8a16-d273-44bd-845b-6a1df228e40d)

**Comment by Jackseed** [comment]
sorry one more review on the pdf export.. can wait next release 
- [ ] Pdf export dashboard side on avails, add also exclusivity & dates used for the search
eg Avails: [Countries] in [medias], [exclusive / non exclusive] rights for [start date - end date / american format]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/14964443/191768297-972e6f9c-f53c-45f6-bb5f-f6a34a45d33f.png">

**Comment by Jackseed** [comment]
### Festival title list - new filters 
- [ ] rename `Festival Name` `Festival Selection` 
- [ ] add Festival & Qualifications new filters to catalog (B priority)

**Comment by cams-goussale** [comment]
- [ ] Can we change the contract import templates? There was a typo in one column header. I've uploaded the [updated versions here](https://drive.google.com/drive/folders/1hmsmslJxLxrPpA5Cy5K814Rgd_bHYaQb): Contract_Import_Cascade8_Admin and Contract_Import_Cascade8_User

**Comment by cams-goussale** [comment]
- [ ] Add a tooltip in the following screens:
`This data only includes Buyers and excludes all Sellers from Archipel Market.`

`/c/o/dashboard/home`

![image](https://user-images.githubusercontent.com/93206363/191960620-a603b73a-7272-4306-bb86-e4354f0fd89f.png)

![image (1)](https://user-images.githubusercontent.com/93206363/191960614-896fddb8-315a-4d55-9b1e-460c2542ae44.png)

`/c/o/dashboard/home/title/[titleId]`

![image (2)](https://user-images.githubusercontent.com/93206363/191960603-367d5e1a-f22c-47d5-8291-50c64a7e5259.png)

![image (3)](https://user-images.githubusercontent.com/93206363/191960588-ef8e7854-b7ee-4480-bd44-16af48bb5516.png)

`/c/o/dashboard/home/buyer`

![image (4)](https://user-images.githubusercontent.com/93206363/191960628-ea02f593-f5d6-4efe-a9eb-a093e9ea2bbc.png)

`/c/o/dashboard/home/buyer/[buyerId]
`
![image (5)](https://user-images.githubusercontent.com/93206363/191960624-fb53fc6e-499d-4d56-badc-a94e25043bb6.png)

**Comment by cams-goussale** [comment]
## Avails

- [ ] The empty states when there are no avails uploaded are different from the [UI mockups](https://www.figma.com/file/KDtXtcYk8YHw0W7ZOu0bAW/My-Availabilities?node-id=0%3A1). Also this empty state isn't showing on Dashboard side. Could we add it?

Currently for map:
![image](https://user-images.githubusercontent.com/93206363/191967188-bcc29e89-cdb5-4d2f-becc-2523a8c876eb.png)
![image](https://user-images.githubusercontent.com/93206363/191967258-1289430f-cf8d-4a09-b217-acdce91c361e.png)

Expected for map:
![image](https://user-images.githubusercontent.com/93206363/191967644-0489e2b4-db89-426e-a46b-45ef0add823a.png)


Currently for calendar:
![image](https://user-images.githubusercontent.com/93206363/191967374-0dd93412-3dd6-4495-93bc-82a8d69bb1ad.png)
![image](https://user-images.githubusercontent.com/93206363/191967325-a68c96f2-8b66-4407-bd85-397b84599987.png)

Expected for calendar:
![image](https://user-images.githubusercontent.com/93206363/191967564-ec41f454-e139-4b7f-9a28-b14eb5cf2e6e.png)

**Comment by cams-goussale** [comment]
> https://github.com/blockframes/blockframes/issues/8907#issuecomment-1254963639

@phpgeekfr do you still have this issue? Because it's working fine on my side

**Comment by cams-goussale** [comment]
> When I receive a mail to attend an event, I cannot click on "activate account"

This bug is on prod. Do we no where the problem comes from?

**Comment by phpgeekfr** [comment]
> On these 2 notifs, can change the action text to See [Event Type] Details which leads to the Event form? I know we won't have Change to Declined because this was for another issue.

In fact these 2 notifs and the two on lines 34-35 are the same, only the status, the mode (request/invitation) and (dashboard/marketplace) are changing. But on excel file, `Notification Text` and `Button text` are not the same so I don't know what to do here.

For these 4 notifs, text should be like :
```
[ User Name  ( Organization Name ) | Organization Name ] has [Invitation Status] your [Invitation mode] to attend [Event type] [ Event Name ].
```

**Comment by phpgeekfr** [comment]
> When I receive a mail to attend an event, I cannot click on "activate account"
This bug is on prod. Do we know where the problem comes from?

Yes, we moved from `pageURL` to `pageUrl` but this was not updated in template `de129a43fb43430a8e1d4e8de4d43e46`
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/85466090-1d20-4245-ac8a-30ee88956b1c)

**Comment by cams-goussale** [comment]
- [ ] When a title has access to both apps, if it gets published on festival-app, user receives the email confirmation about catalog-app.

Title in Draft on AM

![image](https://user-images.githubusercontent.com/93206363/192250980-a6801090-cf96-4c55-91f1-6917dbf5324e.png)

Title in Draft on AC

![image](https://user-images.githubusercontent.com/93206363/192251092-abe824f7-5eaf-45a5-b61f-7992d9ea8e1b.png)

Publish to Marketplace on AM

![image](https://user-images.githubusercontent.com/93206363/192252034-8bad6f2f-cbc0-40f4-86f6-223d908c7e5d.png)

Email received concerns AC

![image](https://user-images.githubusercontent.com/93206363/192252360-269d4703-c81c-4c50-acdc-35ad47bef35a.png)

Though title is correctly published on AM and still as draft on AC

![image](https://user-images.githubusercontent.com/93206363/192252477-43b1de51-640b-4990-a4cd-6a33ad8320bd.png)

**Comment by phpgeekfr** [comment]
- [ ] on `/c/o/dashboard/home`
we don't have the sentence bellow title like this 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/448d0573-745a-4578-ab3e-8454aed83d67)

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/c9658ba3-0889-43de-9c69-083330e6f762)
