### ISSUE TITLE
CRM Movie view - Add Organization name & link to it 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#8926]
Same as on marketplace movie view, it would be really useful to have a direct link to org(s) that own the movie on crm movie view. It can be on the banner, same as marketplace.

![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/fb4d5845-af79-4b81-84d8-d81c990deb35)

**Comment by Jackseed** [comment]
- [ ] Also add the createdAt & By info + a link to the user who created it

**Comment by phpgeekfr** [comment]
example :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/3a4a6752-5512-4269-bcbd-97f76d236aa7)

**Comment by Jackseed** [comment]
That's perfect!
