### ISSUE TITLE
bugs on movie-tunnel : other videos

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#8950]
- [x] if user choose a video, and then click on delete file to choose another one, privacy checkbox is un-checked
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/14d05534-af30-4371-8120-f64483753628)
after video removal:
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/19ec92a4-bcd5-49fd-963d-6097e786f250)

- [x] if user upload "other video" without clicking on "save video" button,
 ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/632a7f5e-4c3c-48c2-886a-4b1b9c1123c1)
then click on "save" and re-click on "save" after upload is ended, video will not be saved. If user click on "save video" (even after upload) and click on save, video will be back. This does not happen if user click on save after video upload if he changed component

**Comment by Jackseed** [comment]
As discussed: 
- [ ] test to remove the table for other videos and see if the bug is fixed
- [ ] export a list of existing titles with more than 1 other video
- [ ] migration from array to 1

**Comment by phpgeekfr** [comment]
see https://github.com/blockframes/blockframes/issues/8877#issuecomment-1289013156 for code to update

**Comment by phpgeekfr** [comment]
here is the list of existing titles with more than 1 other video (with db from october 22)
http://crm.blockframes.io/c/o/dashboard/crm/movie/33iVOex2uwzVhysaqsTD
http://crm.blockframes.io/c/o/dashboard/crm/movie/5EHTTk5wsDIS8vKre4Nz
http://crm.blockframes.io/c/o/dashboard/crm/movie/5ht9T8IMnD54LGryjdvU
http://crm.blockframes.io/c/o/dashboard/crm/movie/6CjCdl4bUl0P9oHEneCh
http://crm.blockframes.io/c/o/dashboard/crm/movie/8Y6dSfG5UEQ4G4iJ8Uam
http://crm.blockframes.io/c/o/dashboard/crm/movie/9b6mxQ39a9bHJd0Y0hG2
http://crm.blockframes.io/c/o/dashboard/crm/movie/AWj9C1gHxVjnE5gExde3
http://crm.blockframes.io/c/o/dashboard/crm/movie/B7xZ6gqr59VXdboMZb1p
http://crm.blockframes.io/c/o/dashboard/crm/movie/CWAC218kAFThLszTPJUQ
http://crm.blockframes.io/c/o/dashboard/crm/movie/RkBUlP4njrzYeWgnx9Wo
http://crm.blockframes.io/c/o/dashboard/crm/movie/XMhUtlpcxb9a2KvJWJ9G
http://crm.blockframes.io/c/o/dashboard/crm/movie/XdQgW4oTCKyLOZKPBT9g
http://crm.blockframes.io/c/o/dashboard/crm/movie/cFmWQYM7iPfwRgAClKbf
http://crm.blockframes.io/c/o/dashboard/crm/movie/jtMFyAcl2OBeJZeDQCTC

**Comment by Jackseed** [comment]
- [ ] Updates video upload boxes on crm movie page > keep only public screener, private screener, sales pitch video and other video

**Comment by Jackseed** [comment]
I deleted all the other videos listed above (for future reference, it was mainly subtitled content like trailer with russian sub)
@phpgeekfr could you confirm me that now no video has more than 1 other video?

**Comment by phpgeekfr** [comment]
- [ ] check if #8846 can be done here

**Comment by phpgeekfr** [comment]
To test when done or before release:
- [ ] PDF trailer link and public screener link are present
- [ ] upload of otherVideo from movie tunnel is ok
- [ ] upload of otherVideo from org file (explorer) is ok
- [ ] other video can be used in meeting events
- [ ] otherVideo privacy can be changed and file is moved in storage & updated in db
- [ ] deleting a video (otherVideo & salesPitch) from movie-tunnel  set privacy toggle to previous state
- [ ] on movie delete, file is removed from storage
- [ ] file is removed from storage and db when deleted from movie tunnel
- [ ] otherVideo & publicScreener can be uploaded via CRM (useless description input on screener & public screener removed)
- [ ] `has otherVideo` field in CSV export is ok
- [ ] anonymization of otherVideo is ok
- [ ] on `marketplace/title/view`  movie-promotional-links display link to trailer
- [ ] migration 85 is ok
- [ ] otherVideo is displayed in movie summary
- [ ] otherVideo is displayed in movie "main information" (top & bottom) only if public

**Comment by phpgeekfr** [comment]
> I deleted all the other videos listed above (for future reference, it was mainly subtitled content like trailer with russian sub)
could you confirm me that now no video has more than 1 other video?

@Jackseed 3 new other videos where added on october 26 to :
```
5ht9T8IMnD54LGryjdvU
8Y6dSfG5UEQ4G4iJ8Uam
9b6mxQ39a9bHJd0Y0hG2
```

Looks like by same user, using "Org Files" instead of movie tunnel since there is no title or type 

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/20bbad97-2e70-47b0-a3ad-f437248ecfc4)

**Comment by Jackseed** [comment]
deleted 👍

**Comment by phpgeekfr** [comment]
> deleted 

- [ ] ok lets see on next monday after migration is executed on ci

**Comment by phpgeekfr** [comment]
> * you confirm me that now no video has more than 1 other video

From latest anonymization, looks like every movie have max 1 otherVideo.

https://app.circleci.com/pipelines/github/blockframes/blockframes/28079/workflows/4a8de1cc-a2f0-4265-bfb4-c79a7adb907b/jobs/77270
