### ISSUE TITLE
Review Release 4.5.1

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#8952]
- [x] #8914
- [x] #8924

**Comment by phpgeekfr** [comment]
Changelog:
- new way of setting the jwPlayerId on a video file. It used to be done during second call of linkFile, after it is moved to good directory. It is now done directly after file copying in the same call. Tried with a 4.5GB file and it worked
- corrected method `moveMovieMedia` that is used to move file from protected to public dir (or reverse) when privacy is changed for otherVideos or salesPitch
- corrected sender for emails about movie status changes. Added a `submittedAt` date (like existing `acceptedAt`) to be able to know for which movie the status changed. This also impact notifications `movieAccepted` and `movieSubmitted`.
- submittedAt value is now displayed on CRM
- "save" button on movie-tunnel is disabled during 1 second after a click on it. This prevent multiple saves potential bugs
- saving movie via "save" and "publish" buttons is disabled during five seconds after a successful file upload. This should handle **most cases** when user wants to save movie right after an upload ends.
- added a tooltip on disabled "save" and "publish" buttons in movie-tunnel during five seconds after a successful file upload
- files uploads on movie-tunnel are not erased anymore if user clicks on save button after file upload when on another component than the one used to upload the file. This includes all kinds of uploads, not only videos.
- if upload metadata is invalid, an error is sent to Sentry (I don't know if this error occurs or not)

**Comment by cams-goussale** [comment]
## Review

- [ ] Tooltip on disabled button Save not showing
![image](https://user-images.githubusercontent.com/93206363/194346272-0bcb751d-3712-457b-925e-622acb4e7bdc.png)

**Comment by phpgeekfr** [comment]
> By testing the flow, I'm wondering if we could apply the disabled Save button with tooltip during the whole time when the upload box is open. 

Yes we can, but if user uploads a 10GB file for example, he will not be able to save movie form until the end of uploads. Might be blocking

> Otherwise it feels almost buggy that the Save button is disabled, sometimes with tooltip and sometimes without.
Save button is disabled in 2 situations:
- after click on save, disabled until snackbar is dismiss 
- after an upload ends, 5 seconds, with tooltip

@cams-goussale I can add a tooltip "Saving..." for the first one if you want

**Comment by phpgeekfr** [comment]
> Upload of the 2nd pdf finishes. Save button gets disabled with tooltip. I wait 5sec and when it's enable i click again on Save. Now it uploads again the 2nd pdf.

There is already an existing feature than prevents double uploading: If a file is being uploaded, hitting save button again should not put this file into queue again. When upload is finished, file is removed from queue but hitting save button again should not re-add the file to queue.  I will try to reproduce and find a fix for this.  But despite this double upload, file looks like uploaded correctly and linked to the movie.

**Comment by cams-goussale** [comment]
> Yes we can, but if user uploads a 10GB file for example, he will not be able to save movie form until the end of uploads. Might be blocking

Okok, then let's keep as it is.

> @cams-goussale I can add a tooltip "Saving..." for the first one if you want

No, I think I understand better where my confusion comes from.
The tooltip stays for as long as there is the upload box open, correct? But the upload box stays open forever, even if the upload is finished.
So let's say I upload a file, click save. I get the tooltip, the upload finishes. And then I continue updating the metadata of the movie (no file upload), I still get the tooltip saying you're uploading my files, even though the upload is finished in reality.

I don't think it's really important, because I assume users don't go back to editing their metadata once they've uploaded their files. But I guess one fix could be to have the upload box close once upload is done.

![image](https://user-images.githubusercontent.com/93206363/194821635-e6c26efe-fef7-4720-9930-fee6d88d9a74.png)

**Comment by cams-goussale** [comment]
It's likely to be my connexion causing this, but just in case we can do something:

I add 2 pdf, click on save
I add 1 otherVideo, click on save
I add salesPitch video, click on save
I add image, click on save
I edit some metadata

Video link

In the upload box it shows these files have been correctly uploaded:
- 1 pdf
- 1 salesPitch
- 1 image

The rest of the files seem to be uploading when suddenly the upload box disappears.
`Failed to load` error in console

When checking in db (: 
- 2 pdfs correctly uploaded
- salesPitch correctly uploaded
- no otherVideo uploaded
- no image uploaded

User reclicks on save in movie tunnel and then suddenly it triggers the upload of the otherVideo. It gets created in db (with a duplicated for a moment which is then corrected)

**Comment by cams-goussale** [comment]
Are we able to send to sentry when there is a Failed to load inside the movie tunnel? I have the filling i'm not the only user with a bad connexion.

**Comment by phpgeekfr** [comment]
> Are we able to send to sentry when there is a Failed to load inside the movie tunnel? I have the filling i'm not the only user with a bad connexion.

Ok I will try to catch and send to sentry any error related to failed upload.
