### ISSUE TITLE
prod storage backups on CI take a lot of disk

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#8967]
prod storage backups on CI take a lot of disk.
check if we can:
- keep 45 days of backups but move old storage backups on CI to cold storage
- reduce number of backups (45 days now) and check folder size to prevent deletion if too small regarding previous backup

**Comment by Jackseed** [comment]
After discussions with Bruce & Yannick, we'll change for cold storage here (should /10 the costs)

**Comment by phpgeekfr** [comment]
- [x] A virtual machine`eth-events-server`  running from 2019 was found on `blockframes-staging` compute engine API.
Instance was deleted and api disabled.
https://console.cloud.google.com/compute/instances?project=blockframes-staging

**Comment by phpgeekfr** [comment]
- [ ] check hetzner server

**Comment by phpgeekfr** [comment]
Looking at pricing simulator  (https://cloud.google.com/products/calculator#id=0bb46f29-065d-4351-b18b-7609eff02ff5) :

Price for `15TB` on multi-regional EU cost 2 times more than a single-regional EU (paris) .

- [ ] For storage-backups we definitely does not need a replication on mutli EU regions.
- [ ] For Firebstore buckets (the ones actually used by our applications) : "prod" ,"staging" "dev project", I don't think we need this also as ImgIx & jwPlayer are used to read the front data

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/a49eaf58-fc09-4de6-90b9-81221aae0b89)

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/8b00df4d-1e7a-4eae-b6b7-485c9bd4db1f)

**Comment by phpgeekfr** [comment]
- [x] created notion about storage https://www.notion.so/cascade8/Storage-buckets-6159d5afbe4c4706af0321028f649421

**Comment by phpgeekfr** [comment]
- [ ] check with @Jackseed if new defined rules are ok. Especially for `gs:/blockframes-ci-backups`

**Comment by phpgeekfr** [comment]
- [ ] clean remaining unused buckets

**Comment by phpgeekfr** [comment]
Keeping it open until 45 days to check if buckets are cleaned accordingly to lifecycle rules

**Comment by phpgeekfr** [comment]
Buckets are cleaning. Closing this issue
