### ISSUE TITLE
CRM Movie page - Add org logo as link to crm org page

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#8993]
Same as on marketplace movie view, it would be really useful to have a direct link to org(s) that own the movie on crm movie view. It can be on the banner, same as marketplace.

![image.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/fb4d5845-af79-4b81-84d8-d81c990deb35)

**Comment by phpgeekfr** [comment]
@cams-goussale @Jackseed looks like a duplicate of #8926

**Comment by Jackseed** [comment]
woups I thought I hadn't created it already ><
