### ISSUE TITLE
Add a "send me a copy of the invitation" to event form

### ISSUE THREAD

**Issue by cams-goussale** [blockframes/blockframes#9013]
When a seller is organizing an event, after sending invitations to their buyer, s.he doesn't have visibility on what the buyers receive. We could add the option "send me a copy of the invitation" checkbox, so that the seller knows what happens to his buyers. We could send the most standard template (`d-ecd4fd15707142cdbb1a72179be9d20b`)

**Comment by Jackseed** [comment]
Not a priority anymore > closing
