### ISSUE TITLE
Pushier Buyer preferences

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9038]
Right now we show the user buyer preferences form only once at the first connexion and then hide it in the user settings. 

We'd like to be pushier on this feature and have some propositions that need to be validated on dev side. We don't want to spend too much time on this so we'll do it only if it's easy. 
Propositions (they all concern only catalog marketplace users)
1. Show it again at each connexion until buyers filled it + add a button "Don't show this again" and stop displaying it if they clicked on that button.
2. Add the same banner we had for Safari users (bottom of the page) but displayed only if the user hasn't filled in buyer preferences (with different message of course)
3. Add a snackbar when the buyer cancels the buyer preferences modale that link to user settings, so user will know where to find it

**Comment by cams-goussale** [comment]
for reference

![image](https://user-images.githubusercontent.com/93206363/203294134-aea079a0-1f3d-431f-bf5c-c675cf2edf76.png)

**Comment by phpgeekfr** [comment]
First proposition is the quickest: approximately 10 lines of code to update

**Comment by phpgeekfr** [comment]
What the modal could looks like : 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/655330da-c38e-4263-8588-8db590c15165)

**Comment by Jackseed** [comment]
Ok so we go for propositions 1 & 3 but not 2
Texts:
1. ok for your proposition
3. Snackbar: You can fill in your buyer preferences later in your settings.
CTA: Take me there > links to user settings, anchor to buyer preferences form if possible

**Comment by phpgeekfr** [comment]
@Jackseed @2amarkina  Do you have a smaller text to avoid having the snackbar on two lines ? 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/3629505d-aff3-4b0c-9c2b-87b962a9c2d4)

**Comment by phpgeekfr** [comment]
- [ ] display this snackbar always, unless user saved his preferences

**Comment by phpgeekfr** [comment]
@2amarkina @Jackseed we can currently save form without any data, do you want me to check if there is at least one input with data in it and if not, prevent the saving and add a snackbar error message ?
If so, please provide the snackbar text 

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/6b949c74-3870-421e-a5c9-29becdc0a58f)

**Comment by 2amarkina** [comment]
**Here are some propositions for the snackbar checked with Aurore:** 
Snackbar: You can fill in your buyer preferences later.
CTA: TAKE ME THERE

Snackbar: You can fill in your buyer preferences later.
CTA: SETTINGS

**Comment by phpgeekfr** [comment]
> **Here are some propositions for the snackbar checked with Aurore:** Snackbar: You can fill in your buyer preferences later. CTA: TAKE ME THERE
> 
> Snackbar: You can fill in your buyer preferences later. CTA: SETTINGS

Thanks, first proposition is ok

**Comment by 2amarkina** [comment]
> @2amarkina @Jackseed we can currently save form without any data, do you want me to check if there is at least one input with data in it and if not, prevent the saving and add a snackbar error message ? If so, please provide the snackbar text
> 
> ![image.png](https://camo.githubusercontent.com/d29af3873075e1609dcf2086c02ac6e4f421c0440a3f973d067b8eb14f0dbb71/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563366539353566646563643265336336396236633164322f36623934396337342d333837302d343231652d613563392d323962656364633061353866)

I think we could add if it doesn't take a lot of time. If it takes too much time, then we could keep as it is. 

Snackbar text proposition: 
Please choose at least one of your buying preferences.
