### ISSUE TITLE
Validators on avails form

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9053]
I don't know if it's linked but I don't have the same validator as in avails filter, which verifies that end date is greater than start date
<img width="975" alt="image" src="https://user-images.githubusercontent.com/14964443/203363519-ee2ab7e0-1747-42dc-a9da-79cd3440f907.png">

> * [ ]  when saving avails (`/c/o/dashboard/avails/select/RoXcNo18sMj3dLxMwI03/manage` or CRM) start and end dates are correct @Jackseed

_Originally posted by @Jackseed in https://github.com/blockframes/blockframes/issues/9023#issuecomment-1323910536_

**Comment by phpgeekfr** [comment]
WIP https://github.com/blockframes/blockframes/pull/9054

**Comment by Jackseed** [comment]
Ok both are good! I thought Yesterday we were discussing `from` must be in the future and this may have some corner cases where it's needed but `to` in the future is good :)
