### ISSUE TITLE
Add KPI tables in CRM homepage

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9056]
It's been months that we have crafted KPI tables with @cams-goussale to check the apps' success. 

We've updated csv export to facilitate the update of these tables @phpgeekfr .

Why not creating the tables directly in CRM? It will be automatically updated and easily accessible to all. 

First we need to discuss the time & scope of this issue. Depending on complexity we may reproduce all or only part of the existing tables.

**Comment by Jackseed** [comment]
After discussion with Bruce:
- It would imply a new collection
- Then he'll need to reproduce our cross dynamic tables (2-4 days)
- Finally to save weekly the results to be able to have history and WoW (2-4 days)

On my side I had second thoughts: I will still need csv export to be able to update Pipedrive. 
Overall I think we should focus first what's most valuable and don't need/can't be in Pipedrive. 

Thus I think we could start with live tables (new collection but no weekly save) that will help business developers daily:
- List of catalog marketplace users (Buyers) that connected to the app in the past week (from Thursday to Thursday to match our weekly meetings)
- List of Buyers who interacted with titles with title name and interaction dates
-
@cams-goussale, I would love to have your input on this

**Comment by cams-goussale** [comment]
2 questions :)

1- Does this mean the excel KPI won't be maintained?
- if yes (the excel won't be maintained) then these metrics sound good to have in CRM.
- if no (the excel will be maintained) then I don't see why bother putting all this in CRM. We should be able to have this same info from the csv exports and put it all in the excel KPI sheets.

2- When you say `List of catalog marketplace users (Buyers) that connected to the app in the past week` but `no weekly save`, it means it'll be a dynamic collection? Like it'll be refreshed weekly and some data might go out of the collection if a user didn't interact on the app that week, correct?

**Comment by Jackseed** [comment]
1. Yes exactly, and indeed we can forget about it, I thought we could remove the excel but in fact Pipedrive we still need it.
2. This may still be useful as it's dynamic, excel is not the good medium (too static) and we don't care of history on this so eventually I think it's the only thing we could keep from that issue
Do you have idea of dynamic data that would be useful for #2?

**Comment by Jackseed** [comment]
And in fact even the solution 2 is doable with excel (and I'm doing it on Pipedrive): each week I update Pipedrive to underline the users who interacted with the app during the previous week.
We have 1 week delay but that's more than ok so I guess we can just close that issue after all 😬
