### ISSUE TITLE
Check FSNFT - how to display private videos on tokens we didn't mint

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9057]
The idea would be that NFT owners could connect to filmseriesNFT and if their NFT is listed in our db (even if we didn't mint it); they can watch the video attached through JwPlayerId

**Comment by phpgeekfr** [comment]
Right now filmseriesNFT is meant to work only with 1 contract and rely on custom data stored on ETH contract like `contract.uri` (example https://c8-nft-default-rtdb.europe-west1.firebasedatabase.app/titles/1.json) to retrieve token information.

It looks like that technically, we could :
- store a list of ERC 1155 contracts addresses that we want to work with
- store some description for those contracts (name, description, image etc)
- store a list of tokens for each contracts with id, jwPlayerId and optionally a name/description
- display token id list owned for a specific ETH address (by filtering transfer events to this address) (@Jackseed this might be the reason of the bug you showed me.)
- check that user is owner of a token (signed message to prove he is owner of a given address and check that this address owns a token)
- display video for jwPlayerId only if previous point is ok

**Comment by Jackseed** [comment]
Time estimation:
- public token list: not that long to get the token list itself (manually not with a form); displaying the list neither; but then it means that we need to get the new token emitted by ourselves to list it
> Could take a whole week if we need to add a form; a few days otherwise. Call OpenSea API would be easier than a form.
- 2 weeks (maybe more) to modify the existing app to accept multiple contracts, list these contracts
- a function that would get the token list based on a contract address (+ a refresh button) would take a couple of days 
- fork for an external player app that shows the tokens you own and enable you to play it would take 2 weeks
