### ISSUE TITLE
Catalog marketplace - Elaborate on user feedbacks

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9061]
User feedback we can work on:
1. Downloadable excel results (#9031)
2. More consistent keyword search: @2amarkina could you please link the list of indexed parameters used for the searchbar?
3. Not sure about the problem behind the text, @cams-goussale @2amarkina what do you understand?
4. Let's keep them in the loop as soon as we have created the related issues and prioritized it
5. Let's be sure that business developers will send them proposition 
@cams-goussale could you follow 4 & 5?

>  I was missing the option to download the searches result into excel.
>  
> 
> The key Word search sometimes showed me sometimes content not related to the keyword.  
>  
> 
> When filtering the search, I have to click on every title in order to see territory availabilities. And is for example I choose “Worldwide rights”, the search will discard all other options and maybe I miss something which in fact is available for countries we are interested in, right?
>  
> 
> I would like to know if these are things that could be changed in the upcoming months and in order to take further steps, I would also like to ask you if you could send us your avails in an excel file with these descriptions:
> 
>  
> 
> Field: wine, sustainability, nature, climate change, food, travel
> Languages: English, Spanish (Castilian), German, Italian, French (we’d also like to know if you have dubbed or subtitled versions in these languages)
> Territory: WW or any of these countries: US, UK, Spain, Italy, France, Germany
> Term: We do not have restrictions on that
> Year of production
> Quality of the content
> Links to the titles’ screeners / trailers

**Comment by 2amarkina** [comment]
**Document and previous reflexion:**
Here is [the document of the Search bar optimisation](https://docs.google.com/spreadsheets/d/13BMJIk-8qHPbkW_Ek7gmwP4jH9RYGWxlfMSBA5mb2ew/edit#gid=0) that we have been working on. 

**Actual state of things:**
Nowadays we can search inside the following elements : 
- International Title ( 'title.international' )
- Original Title ( 'title.original' )
- Country of Origin ( 'originCountries' )
- Director's First Name ( 'directors' )
- Director's Last Name ( 'directors' )
- Original Language ( 'originalLanguages' )
- Genre ( 'genres' )
- Keywords ( 'keywords' )
- Production Company Name ( 'productionCompany' )
- Festival Name ( 'festivals' )
- Seller ( 'salesAgent' )

Also there is a  'orgNames' , that is not reflected in the excel document above. 

**Possible source of the problem:**
Nevertheless, as the search passes through all the parameters listed, we can be faced to the following situation:
A user searches for the keyword "start up" (only one film has this keyword). 
A)  If a user enters entirely "start up", s/he will get the needed film. 
B) If a user typed only "start", s/he will get 24 available results (for some films the production company's name is START, some titles begin with "star..." etc. )

**Possible solutions:** 
1. Propose to a user to precise the category of the search (amazon style) and separate each search parameter 
<img width="1359" alt="amazon ex" src="https://user-images.githubusercontent.com/55499036/204513241-aa2589b1-c71d-4c56-820c-992b9bfae7a3.png">
2. Propose to a user to precise the category ONLY IF s/he wants to search by a keyword (very quick draft, will need more reflexion)

<img width="739" alt="test_keywords" src="https://user-images.githubusercontent.com/55499036/204514512-06ebe68f-c454-4878-96b0-5075d9c5d274.png">

**Comment by cams-goussale** [comment]
> When filtering the search, I have to click on every title in order to see territory availabilities. And is for example I choose “Worldwide rights”, the search will discard all other options and maybe I miss something which in fact is available for countries we are interested in, right?
>> Not sure about the problem behind the text, @cams-goussale @2amarkina what do you understand?

I think she 'misunderstands' a bit our avails logic. (I used to think like her).

1- Imagine I search for Europe, and I get 10 movies as a result. Imagine we have 1 movie available in France but not in Italy and Germany. Therefore, this title is discarded from the Europe research. However, she would expect that movie to show because France is in Europe.

2- Because she understands wrong our avails logic, she thinks that when searching for Europe, maybe title 1 is available in Spain, title 2 in Norway, title 3 in Italy, etc. So she'd like to know which territory is available exactly for each title, without entering into the movie page.

=> that's what I understood from her text. But we should ask her directly to explain what she means.

> Let's keep them in the loop as soon as we have created the related issues and prioritized it
> Let's be sure that business developers will send them proposition

Sure. Lorena is on it. Just beware that they told her they wouldn't do an offer without rev share. Quote: `In case there are interesting titles for us we can pay symbolic MGs to cover operacional costs, recuperable with revenue share and we do not work with flat fees for now.`

**Comment by 2amarkina** [comment]
concerning the problem 3
_`When filtering the search, I have to click on every title in order to see territory availabilities. And is for example I choose “Worldwide rights”, the search will discard all other options and maybe I miss something which in fact is available for countries we are interested in, right?`_

 If I understand right, it seems that the user would like to see all the available territories directly on the "titles page" without checking a film by film. 
 
 For example, i choose "Worldwide rights" and I want to be able to see what exact territories are available (in her case directly, but maybe on hover or in a list) ? 
 
Step 1
<img width="1436" alt="step 1" src="https://user-images.githubusercontent.com/55499036/204515924-721c15b6-0d29-4799-8892-e38995aa18a2.png">

Step 2 (very quick draft)
<img width="765" alt="step_2" src="https://user-images.githubusercontent.com/55499036/204516010-4c68dc82-7a54-4449-858a-fe22f8d73577.png">

**Comment by cams-goussale** [comment]
to complete Ana's ideas, here is something I found in PowerBI and that I like. It's indeed a tooltip, with additional data showing when user hovers.

![image](https://user-images.githubusercontent.com/93206363/204516667-625749d5-4256-4c40-a32d-c3da83c2006e.png)

**Comment by Jackseed** [comment]
Ok many thanks for the feedbacks. 
Re 2) Keywords: I like your proposition Ana, doesn't look too hard and would indeed answer the problem #9064 created based on your answer. 
Re 3) Ok got it. The thing is that we actually show results that answers **exactly** the search. At first we had thoughts on showing semi-acceptable results but it would mean a way more complex avails search algorithm that would definitely be too difficult to implement with our current ressources (kind of what you both suggest). 
It looks to me that the only thing we can do here is to be more explicit on how our avails logic works so at least buyers understand, even if it's not what they would like to have. 
Any ideas on how to be clearer?

**Comment by cams-goussale** [comment]
> Any ideas on how to be clearer?

- A tooltip inside the Avails research filter?

![image](https://user-images.githubusercontent.com/93206363/205868571-847209bf-430e-4c38-aa88-6245ae3e716d.png)

- A "How does it work" button with video tutorial video
![image](https://user-images.githubusercontent.com/93206363/205868816-5487ba35-05a1-4f21-b6f9-7ce32403b32e.png)

- A tooltip here when indicating the # results, also explain how they're being found
![image](https://user-images.githubusercontent.com/93206363/205869149-1f87d407-5b13-4cda-a94c-bbb15b820c40.png)

- Ideas for wording:
`The results of your Avails Research will show Titles which exactly match your criteria. For instance, if you're searching for a group of territories, only Titles available for all the territories of the group will show.`

**Comment by Jackseed** [comment]
I like these proposition, re the tooltip / how it works in the form, it's the same component used in every places with this form so I'm afraid it will be weird sometimes (eg dashboard avails form when seller is creating avails).

The text seems pretty good as well, maybe limit this text to be there only when at least one filter is active?
@2amarkina what do you think? 

I'll create an issue when I got your feedbacks

> * A tooltip here when indicating the # results, also explain how they're being found
>   ![image](https://user-images.githubusercontent.com/93206363/205869149-1f87d407-5b13-4cda-a94c-bbb15b820c40.png)
> * Ideas for wording:
>   `The results of your Avails Research will show Titles which exactly match your criteria. For instance, if you're searching for a group of territories, only Titles available for all the territories of the group will show.`

**Comment by 2amarkina** [comment]
Indeed, we use the same component in a lot of places, that might be confusing sometimes... But maybe we could check with the devs if this part might be excluded and used only on the marketplace side ? 
![205868571-847209bf-430e-4c38-aa88-6245ae3e716d](https://user-images.githubusercontent.com/55499036/205894311-c8f1a667-eed1-40a7-909e-c4e6533e7951.png)


I also like the text, it would be great to emphasis "exactly match you criteria" and put it in bold if we can. And agreed to show it only when at least one filter is active.

**Comment by Jackseed** [comment]
I prefer not to go into dev consideration of reworking existing component, it's always long discussion and we don't have enough ressources for that.

To summarize the issue:
1. Answered with #9031 
2. Answered with #9064 
3. Answered with #9079 
4. @cams-goussale could you explain them the solution we plan to implement? Or do you prefer I write them to do so? We can loosely plan it for T1-23
5. Lorena is on it 👍
