### ISSUE TITLE
Marketplace title list - Add a search parameter select aside the searchbar 

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9064]
**Document and previous reflexion:**
Here is [the document of the Search bar optimisation](https://docs.google.com/spreadsheets/d/13BMJIk-8qHPbkW_Ek7gmwP4jH9RYGWxlfMSBA5mb2ew/edit#gid=0) that we have been working on. 

**Actual state of things:**
Nowadays we can search inside the following elements : 
- International Title ( 'title.international' )
- Original Title ( 'title.original' )
- Country of Origin ( 'originCountries' )
- Director's First Name ( 'directors' )
- Director's Last Name ( 'directors' )
- Original Language ( 'originalLanguages' )
- Genre ( 'genres' )
- Keywords ( 'keywords' )
- Production Company Name ( 'productionCompany' )
- Festival Name ( 'festivals' )
- Seller ( 'salesAgent' )

Also there is a  'orgNames' , that is not reflected in the excel document above. 

**Possible source of the problem:**
Nevertheless, as the search passes through all the parameters listed, we can be faced to the following situation:
A user searches for the keyword "start up" (only one film has this keyword). 
A)  If a user enters entirely "start up", s/he will get the needed film. 
B) If a user typed only "start", s/he will get 24 available results (for some films the production company's name is START, some titles begin with "star..." etc. )

**Possible solutions:** 
1. Propose to a user to precise the category of the search (amazon style) and separate each search parameter 
<img width="1359" alt="amazon ex" src="https://user-images.githubusercontent.com/55499036/204513241-aa2589b1-c71d-4c56-820c-992b9bfae7a3.png">
2. Propose to a user to precise the category ONLY IF s/he wants to search by a keyword (very quick draft, will need more reflexion)

<img width="739" alt="test_keywords" src="https://user-images.githubusercontent.com/55499036/204514512-06ebe68f-c454-4878-96b0-5075d9c5d274.png">

_Originally posted by @2amarkina in https://github.com/blockframes/blockframes/issues/9061#issuecomment-1330465395_

**Comment by Jackseed** [comment]
Warn EYZ when it's done

**Comment by 2amarkina** [comment]
### UPDT. 29/03/2023
It was decided to go for a multi-select with a possibility to refine the search not only with the keywords, but also with other parameters. 

Also we will clean some of the parameters that are indexed nowadays to avoid the duplicates, that might be possible with the new dropdown. 

**Default state :** 
- [ ] User can search throughout all the indexed parameters using the search bar. 
- [ ] We change the text of the search bar from "Search for titles, directors, keywords..." to "Search everywhere..."

- [ ] Multi select is enabled everywhere, user can see only the button "Advanced Search" or "Search by...". Wording to confirm with Aurore and / or Claire 
![Capture d’écran 2023-03-29 à 12.34.28.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/27bd45ff-863d-4c7e-a749-e2185ae750ff)

**Opened state**
User can enable the search inside each category (user can choose one or several categories): 
- Title (International and Original Title combined)
- Director (Director's First Name and Director Last Name)
- Keywords
- Production Company 
![Capture d’écran 2023-03-29 à 12.35.58.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/1d068ee6-34cf-4099-a810-096c8f0a4358)

**Parameters that will be no longer activated (AM & AC) :**
- Country of Origin 
- Original Language 
- Genre 
- Festival  

❗️ ATTENTION ❗️ 
For the AC we will also need to remove the indexation of Seller, but keep it for AM. 
See what is possible.
