### ISSUE TITLE
Festival dashboard - Deleted user breaks analytics buyer tables

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9065]
Bug found thanks to these 2 sentry errors:
- [Cannot read properties of null (reading 'orgId')](https://sentry.io/organizations/cascade-8/issues/3741910248/?referrer=slack)
- [Cannot destructure property 'uid' of 'object null' as it is null.](https://sentry.io/organizations/cascade-8/issues/3777971795/?referrer=slack)

User id `bMlhoO6asTfb68BQX1LixYqtOdz1`

It breaks the top 5 active buyers table on dashboard homepage ((/c/o/dashboard/home)

![image](https://user-images.githubusercontent.com/14964443/204805473-8546d955-1ead-4779-b469-159490472f7b.png)

and then all the buyers stats (/c/o/dashboard/home/buyer)

<img width="701" alt="image" src="https://user-images.githubusercontent.com/14964443/204805523-733105a6-b49b-43b6-a1da-d283b0894b8f.png">

Could we exclude data that are pointing to deleted users?

**Comment by phpgeekfr** [comment]
check `activeBuyers$ = this.titleAnalytics$.pipe(` in `apps/festival/festival/src/app/dashboard/home/home.component.ts`

**Comment by phpgeekfr** [comment]
Sentry issue: [CASCADE-8-5MH](https://sentry.io/organizations/cascade-8/issues/3770224455/?referrer=github_integration)

**Comment by Jackseed** [comment]
Tested with dev+kacey-lgd@blockframes.io (uid `bMlhoO6asTfb68BQX1LixYqtOdz1`) on staging first load everything is working fine but I had a bug when:
- I go from homepage to buyer analytics list and then to buyer analytics view
- then go back home (click on the Dashboard button, nav menu)
Then I got what looks like an infinite loop that made the tab really slow and crash once 
![Dec-01-2022 12-50-23](https://user-images.githubusercontent.com/14964443/205045652-ab3ebd1f-5974-44ed-8cfe-834c97762b0f.gif)

I got this error once, maybe linked:
```
ObjectUnsubscribedErrorImpl {stack: 'Error\n    at _super (https://staging.archipelmarke…/staging.archipelmarket.com/polyfills.js:1811:16)', name: 'ObjectUnsubscribedError', message: 'object unsubscribed', __sentry_captured__: true}
```

**Comment by phpgeekfr** [comment]
- [ ] added `(Deleted User)` on tables instead of removing the line on all `dashboard/analytics` tables and on CRM movie page
- [ ] draft or archived titles are displayed on statistics. Only`access===true` is checked.

**Comment by phpgeekfr** [comment]
- [ ] converted some observables to promises to prevent huge amount of `setTimeout` violations

**Comment by Jackseed** [comment]
Not sure if it comes from the hotfixes but I list here issues I find:
- [ ] Titles are not all listed in the stats title list (`/c/o/dashboard/home/title`), though their stats are available when using urls. I couldn't find any pattern and once loaded they appear in the list.
Got it for movieIds: BtuMTH5Jik8wruYYZF0A & 83mxbXLYfgzyRsfCcd9k using user bMlhoO6asTfb68BQX1LixYqtOdz1
- [ ] Got 0 attendees on old screenings, it's also there on prod so it's not linked to this hotfix but would be curious to understand why (after the release)
Event ids: fJNZTltVKeOvFZSIVOoR & uWTebEREg7hGMGBLWclD
- [ ]

**Comment by phpgeekfr** [comment]
>Titles are not all listed in the stats title list (/c/o/dashboard/home/title), though their stats are available when using urls. I couldn't find any pattern and once loaded they appear in the list.
Got it for movieIds: BtuMTH5Jik8wruYYZF0A & 83mxbXLYfgzyRsfCcd9k using user bMlhoO6asTfb68BQX1LixYqtOdz1

On my side, the two movies mentioned are listed
