### ISSUE TITLE
Check if bigQuery backend functions can be deleted

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9076]
If they are not used, would be cool to remove theses backend functions: 

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/435387c6-04b8-4b78-afd5-a0bdb6a9555f)

**Comment by phpgeekfr** [comment]
- [ ] also remove data studio iframes in CRM

**Comment by phpgeekfr** [comment]
- [ ] check if this will not interfere with `queryAnalyticsActiveUsers`

**Comment by phpgeekfr** [comment]
- [ ] notion doc https://www.notion.so/cascade8/Setup-BigQuery-on-your-project-65b29ad767274d6c8df94c6d36bdd06f

**Comment by phpgeekfr** [comment]
- [ ] `queryAnalyticsActiveUsers` should be kept as it is used on crm users page exports (bigQuery integration )
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/7c74cec2-4366-4019-8ba1-30b08310e724)
- if we remove data-studio iframes on CRM we can remove
    - [ ]  the mentionned backend-functions (staging & prod)
    - [ ]  webhooks on sendrid
    - [ ]   delete remaining bigQueries tables on staging & prod
    - [ ]   the extensions "export to bigQuery"  on staging & prod 
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/dfaef967-6869-4c15-811f-44ec89ae7c2b)

**Comment by Jackseed** [comment]
Yep we can remove all this now that we have our own stats

**Comment by phpgeekfr** [comment]
Keeping this issue open until next release as the `iframes` on prod CRM are still there
