### ISSUE TITLE
Title list search analytics - small improvements

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9088]
- [x] Add new aggregated columns in the user export ("export to csv"):
- saved searches
- pdf exports
- loaded searches
- title list filtered
- avails map search
- avails calendar search
- total interaction
- dates first/last 
- app/module
- title view

- [x] Merge into 1 extract:
- exported titles analytics
- saved filters / loaded filters analytics
- filtered titles
- avails map search
- avails calendar search

- [x] CRM Event list: add a "Attended" column" (users with watchtime > 0)

- [x] Invitation list extract: add a watchtime in seconds (for sorting purposes) + watching start column

- [x] Change date format for first & last interaction dates: use the same as first & last connexion date format used in the user export (to enable sorting)
![image](https://user-images.githubusercontent.com/14964443/206180184-aea876a6-8b66-46e4-a88a-cb1fcaa8f616.png)
vs
![image](https://user-images.githubusercontent.com/14964443/206180139-75966805-5882-450f-82e5-e9bb6f71ac25.png)

**Comment by phpgeekfr** [comment]
> Invitation list extract: add a watchtime in seconds (for sorting purposes) + watching start column

Ok for watchtime in sec  but we don't store data for "watching start", we only keep last watch date
