### ISSUE TITLE
Handle multiple pending distribution rights

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#918]
We need to make a decision about how we want to handle multiple pending distribution rights states and how we want to display them in the selection page. 
- Do we want to bundle them when the buyer makes a bid?
- Or do we want to sort them by the buyer?

**Comment by Jackseed** [comment]
We have an answer from UX team: we will treat all distribution rights equally with a color or an icon to specify when the rights asked are not available. The bid will be for all the distribution rights.
