### ISSUE TITLE
undefined org in negotiationStage pipe

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9223]
undefined org in negotiationStage pipe:

```
map(org => `Waiting for ${org.name} answer`)
```

Sentry error : https://cascade-8.sentry.io/issues/3947988572/?environment=production&project=1540126&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/4fea4d90-b092-47c1-9b44-03601e329993)

![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/ed625c92-9327-4ffc-a138-b7c75294a36c)

**Comment by phpgeekfr** [comment]
check that page https://staging.archipelcontent.com/c/o/dashboard/sales is not broken anymore.
with user `dev+al-vhd@blockframes.io` 

It looks like contract `coUueBKa08643nzt7qNg`  was made with same buyer and seller, preventing app to find the negotiation reviewer.

@Jackseed @2amarkina maybe create a new issue to prevent org with access to catalog dashboard & marketplace to create offer on there own avails ?

**Comment by 2amarkina** [comment]
For making the capture I used the view from the same org, but the negotiation was happening between Cascade8 (me) and International Pictures (out test org) with the avails of the film owned by International Pictures. 

For me it is a really corner case, the user will not create an offer on their own films.

**Comment by phpgeekfr** [comment]
I that particular corner case `reviewer` will be displayed in place of org.name
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/64b7618f-459f-4501-8787-6797f31f2d16)

**Comment by Jackseed** [comment]
To avoid users creating offers on their own title, normally no seller has access to marketplace on catalog (except us). 
So it should really be a corner case

**Comment by phpgeekfr** [comment]
@2amarkina tested ok .
