### ISSUE TITLE
Poland Map bug - Production

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9231]
1. When we search the avails on the Library page with the following parameters : 
- Poland 
- VOD
- 02/22/2023 - 12/31/2024
- Exclusive 

2. We receive a list of films corresponding to the search. 

3. We click on the "Afterthought" film and put exactly the same parameters on the Single Territory view (Map). 

4. We can see that Poland is not shown on the map. 

5. At the same time the Multi-Territory view is working correctly and Poland appears there. 

Other films and other searches seem to work correctly. 

UPDT. : 
**The organization impacted:** 
VOq6jqLDsVdr6ZmQaG3N 

**Examples of the impacted films:** 
yxDqZdTk30g36gEwPFod 
t7pCiYmD8FIvET96kWc8
dOVITuEh3ID53BshGHXt

**Addition:**
_On the avails map view page_
When we click on the EST rights only, then everything is shown correctly.
When we click on the N-VOD rights only, then everything is shown correctly.
If we choose both EST and N-VOD rights, even with the same available territories, there are no results. 

**Context:** 
Has very complex mandates, has external sales

**Comment by phpgeekfr** [comment]
linked to #9140.

**Comment by phpgeekfr** [comment]
@2amarkina @Jackseed there should be no bug left except :
-  when adding a territory that belongs to multiple terms, territory will not be selected on map. Using the pencil icon under `Preselected Terms` should do the trick.
- clicking on a territory that is available with same medias in more than one term (one exclusive and the other not for example) will add territory multiple times.
example with "Afterthought" and "brazil" and this config :
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/15903980-7297-4ca7-9cca-84816894705d)

To test: 
- [ ] check that the initial bug is fixed
- [ ] check that results from movie titles, calendar view and map view are the same
- [ ] test click on ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/a7587052-8c06-4219-ae93-9db6317b7adc)
- [ ] check the whole process: add to selection, make offer, negotiate etc ..
- [ ] check tooltip top right of the map: available, selected, already in selection etc.
- [ ] maybe compare results with prod ..

**Comment by 2amarkina** [comment]
The template of contracts is in .xlsm and other import templates are in .xlsx format. Was there a special purpose for that? I'm saying that, because there is no problem opening .xlsx in google sheets for example, but .xlsm could not be opened there.

**Comment by phpgeekfr** [comment]
@2amarkina to test when on staging:
- [ ] brazil bug should be solved
- [ ] on map view, check a bit that my new fixes did not break any existing feature

**Comment by 2amarkina** [comment]
everything seems to work correctly
