### ISSUE TITLE
Organization line-up on festival

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9234]
Organization line-up on festival is not showing all movies because of org name changes. 
- [x] When org name is updated on app, movies on algolia are not updated with new name.
- [x] we should store orgIds on movie algolia document
- [x] when deleting an org, related movies should not be deleted if movie belong to other orgs but orgId should be removed from `movie.orgIds`

To test:

- [x] org line-up movies and movie count should be the good one, even if we change orgName
- [ ] **Bruce** after `upgrade` (staging & prod) all movie documents on algolia should have orgIds
- [x] when orgName changes, orgName in algolia movie document for all movies of this org should change
- [x] when an org is deleted,  all movies that belongs to this org, and only this org, should be deleted. If movie belongs to multiple orgs, deleted org should be removed from `movie.orgIds` and algolia should be updated accordingly.
- [x] algolia title search is ok ( test various filters, including search by buyers)

**Comment by 2amarkina** [comment]
all good here
