### ISSUE TITLE
Catalog update - new T&C, hide seller logo, remove commission on landing

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9239]
For business reasons we'll change a bit catalog on 3 spots:
- [x] Landing page, remove the sentence "We take 10% commission when there is a deal" (and keep only the title "Subscribe for free")
- [x] Terms and conditions change a bit, cf this file: [https://app.zenhub.com/files/165818079/4ba80b64-76d0-4e01-81e4-616a01425f62/download](https://app.zenhub.com/files/165818079/4ba80b64-76d0-4e01-81e4-616a01425f62/download) 
Changes are in red if you have Word, contact me if you can't see it. Also we should add a subtitle after "General Terms and Conditions of the Archipel Content Service", "Last edited March 1st, 2024"
- [x] Remove the seller logo and name on the marketplace movie view (banner) - the page can stay active but we remove the link to it (only on catalog!)

**Comment by phpgeekfr** [comment]
@2amarkina To test when on staging :
- [ ] removed sentence "We take 10% commission when there is a deal"
- [ ] new term & conditions for catalog + "last edited march 1st 2023" on top. Existing users does not have to accept new terms, only new users
- [ ] movie header on catalog only does not have org logo / or name anymore

**Comment by 2amarkina** [comment]
all good
