### ISSUE TITLE
Catalog - Remove "Contact XXX" on the marketplace movie view avails tab

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9244]
We removed the logo and seller name but I forgot about this little sentence where we show the seller's name and email. 
It should be removed as well
![Pasted Graphic.png](https://images.zenhubusercontent.com/5c6a89ac8de1b31d5443ab99/d180dc87-3557-4d03-b7f0-0b496f71f7e2)

**Comment by 2amarkina** [comment]
text: contact Archipel Content 
action: opens Intercom
