### ISSUE TITLE
Catalog - Commission to add 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9246]
**Context:** 
During the business point it was decided to add the information about the commission to provide a clearer information to the user. 

It is important to add the following phrase `This amount includes the commission due to Archipel Content` on several levels: 
1. Add it to **the mail that a Seller** receives with an offer created (when an Offer has a price)
```
`Hi {{{user.firstName}}},

Great news! {{buyerOrg.name}} 
         {{#if negotiation.price}}offers {{negotiation.currency}} {{negotiation.price}} for {{movie.title.international}}. This amount includes the commission due to Archipel Content. 
          {{else}}is interested in {{movie.title.international}} and would like to know your Asking Price.
          {{/if}}

--- Start discussions button {{{pageUrl}}} ---

All our best,
The {{app.name}} team`
```

2. Add this phase on the Seller's Dashboard page 
As this component is used in a lot of places we need to put it only : 
- on the Seller's dashboard side
- if there is a price proposed by a Buyer. 
![Capture d’écran 2023-03-08 à 16.19.48.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/8e210c61-03c0-421a-827d-ccf115f87157)

For the issue 2, we need to estimate the time with devs and if it takes too much time then maybe put it aside

**Comment by n-germain-work** [comment]
Point2 done.
@2amarkina can you please close the issue when the email part is done please :)
