### ISSUE TITLE
Catalog - Small T&C text updates

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9248]
- [x] From `Last edited March 1st, 2023` to `Last edited: the 1st of March 2023`
- [x] from "Casacde8" to "Cascade8"
- [x] Change the spaces before : everyone (delete the spacing) 
- [x] From` rightholder` to `right holder`

The highlighted corrections could be found [here ](https://docs.google.com/document/d/17giet_6T6aQnInUgxPC6AqE1jrQX4mb66TKffa8eYVQ/edit) (p.1, pp.10-11)

**Comment by n-germain-work** [comment]
Regarding this issue, I found that most of the time, there was a space between Cascade & 8, so I've added this space when replacing `Casacde8`.
Please tell me if this is not ok.
