### ISSUE TITLE
Finish waterfall app setup : todos

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9257]
App setup and data model updates

**Comment by phpgeekfr** [comment]
- [ ] a migration will have to be ran in order to setup new algolia indexes

**Comment by phpgeekfr** [comment]
- [ ] make required CRM updates

**Comment by phpgeekfr** [comment]
- [ ] update org & movie excel import

**Comment by phpgeekfr** [comment]
- [ ] check todo `#9257` in code (email, logo etc)

**Comment by phpgeekfr** [comment]
- [ ] @2amarkina please provide terms & conditions for this app ( https://github.com/blockframes/blockframes/pull/9262#discussion_r1189576540 )

**Comment by phpgeekfr** [comment]
- [ ] @2amarkina please provide title & meta description .
`apps/waterfall/waterfall/src/index.html` 
<img width="577" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVhZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f61b7294f553ee48b43191720c87db7a5cc3c10d/image.png" alt="image.png" />

**Comment by phpgeekfr** [comment]
- [ ] @2amarkina please provide app description for email footer :
```
export const appDescription = {
  catalog:
    'Archipel Content is an ongoing digital marketplace for TV, VOD and ancillary rights. Let’s make content buying simple!',
  festival:
    'Archipel Market is an ongoing film market platform, one tool for your year-round promotion and acquisitions.',
  financiers:
    'Media Financiers enables private investors to co-produce exclusive films and TV series on the same conditions as top professional content financiers.',
  blockframes: // TODO #9257
    'Blockframes is a set of tools to help you manage your film business.',
};
```

**Comment by 2amarkina** [comment]
> * [ ]  @2amarkina please provide title & meta description .
>   `apps/waterfall/waterfall/src/index.html`
> 
> <img alt="image.png" width="577" src="https://camo.githubusercontent.com/eaf695173a0927ea1e2fa9b5d65a36c0c6687ffcb5a9213cfb901da18038c663/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424e56685a5157633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d663631623732393466353533656534386234333139313732306338376462376135636333633130642f696d6167652e706e67">

**Meta-title:** Blockframes: simple management of films & series revenues
**Meta-description:** Blockframes: the rights and revenues management tool designed for producers and financiers.

**Comment by phpgeekfr** [comment]
- [ ] @2amarkina please provide `hotjar` id for new app
