### ISSUE TITLE
Differentiation between TV Shows and Series

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9287]
N.B. see on the product level if this issue is ok 

**Context:** 
Following the feedback from Claire, it would be more confortable to have a differentiation of the Titles as following : 
TV / Series / Movies 

This issue might be a large one as requires : 
- The changing of the Movie Form ; 
- Update of old Titles ; 
- Update of the Homepage CTAs & Filters (sf. screenshot)

![CTAs.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/f5b4c81a-2322-46ec-8667-4a5e54d28956)

**Solutions**
Need to see if we go for this solution presented above, as might be risky and might take pretty much time. 

The other solution that might be undertaken and that Claire is using is to use a keyword "Series".

**Comment by Jackseed** [comment]
Outdated
