### ISSUE TITLE
Bug "Save preferences"

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9298]
**Context:**
Claire is using the feature of "Save" & "Load" Research Preferences to simplify her search. 
When Claire is trying to save the research with the following parameters: World, Boats, 1 an, Non Exclusif this search is saved, but can't be loaded after. 

Nevertheless, when we put Content Type (Movie), Genre (Comedy), Country of Origin (France) this kind of search is loaded with no problems. 

Maybe it's the avails filter that induces the problem?

**Comment by phpgeekfr** [comment]
Looks like we hit the maximum allowed characters in URL

**Comment by n-germain-work** [comment]
To prevent the same issue with originCountries filter, the same url encoding will be used :
- replacing all countries from a continent with the name of this continent
- using 2 letters code for countries (ex: FR for France)
