### ISSUE TITLE
Algolia Question

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9308]
Following the recent discussion about algolia, we need to find an appropriate solution. 
For further details, please follow the Slack discussion (#algolia-issue).

**Comment by phpgeekfr** [comment]
- [ ] Also check if we need it for the new `blockframes` app

**Comment by phpgeekfr** [comment]
- [x] updated notion :
-  https://www.notion.so/cascade8/CircleCi-Environment-variables-1f80cb80b560489bad1f88c6b220b757
-  https://www.notion.so/cascade8/Algolia-1c7ac7f04d0b4981b4685f047c1a3b88

**Comment by phpgeekfr** [comment]
- [ ] linked with #6908
