### ISSUE TITLE
Document actions & conditions on notion

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9316]
@n-germain-work started a documentation about actions. Lets improve it and put it on Notion.

@Jackseed already started here https://www.notion.so/cascade8/Glossary-98507241e5994b189aef2e4f2d8be9db

[https://app.zenhub.com/files/165818079/ab4f9390-1906-4d79-b0a8-84b3d0723926/download](https://app.zenhub.com/files/165818079/ab4f9390-1906-4d79-b0a8-84b3d0723926/download)

**Comment by Jackseed** [comment]
Work in progress [over here](https://www.notion.so/cascade8/Waterfall-creation-88029a78e9cf47bc97a4680645fee3b8)

**Comment by Jackseed** [comment]
Still to be done:
- [ ] Interest
- [ ] Contract
- [ ] Maybe define a new one on the licensor/licensee?
