### ISSUE TITLE
Cross-App UI changes (Blockframes, Archipel Content, Archipel Market)

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9325]
While working on the new Waterfall application we are would like to introduce some UI updates that are cross-app. 

- [x] Verify the logic of the color chart and see the naming for the new BG color for the light-theme (@2amarkina) ; 
- [x] Apply new background color for the light theme #FAFBFF (to be tested with design in life to check if all good) ; 
- [x] Remove the logo in the footer (Dashboard, Marketplace) ; 

For the card-surfaces on the Dashboards (see example below):  ![card_suface.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/8ab43ddc-338b-45ec-b61a-80f96050ce36)

- [x] make the entire the card-surface clickable ; 
- [x] add shadowing effect on hover for the light theme on hover 
`.surface.ng-star-inserted {
   filter: drop-shadow(0px 5px 5px rgba(8, 11, 15, 0.20));
} 
` where RGB is a variation of #080b0f (Light Theme / Foreground 900) ; 

- [x] add shadowing effect on hover for the dark theme on hover 
`.surface.ng-star-inserted {
    filter: drop-shadow(0px 5px 5px rgba(199, 207, 242, 0.20));
}
`
where RGB is a variation of #C7CFF2 (Dark Theme / Foreground 800) ;

- [x] change the cursor to pointer to emphasize the possibility to click for the user.

**Comment by pldespaigne** [comment]
@2amarkina seems like we cannot really create an alt background key as material will not be aware of how to use this new value.
Maybe there is way but I'm not aware of it.

I think the best solution is too simply replace light-theme `background: 900` from `#f4f4f4` to `#fafbff`.
It's what I've done, and after a quick check around catalog & festival it seems to be ok everywhere

**Comment by 2amarkina** [comment]
@pldespaigne ok, perfect, let's keep like this and i'll pay attention if it will "jumps out" somewhere

**Comment by 2amarkina** [comment]
For @2amarkina : 
- [ ] Update the documentation about colors and replace `background: 900 from #f4f4f4 to #fafbff.`

**Comment by phpgeekfr** [comment]
@2amarkina I'm closing this issue but you have an unchecked checkbox
