### ISSUE TITLE
Right Holders Management - Waterfall

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9335]
### Context
One of the most important parts of the Blockframes app is the ability too manage the different actors that can be presented in the Waterfall. 

This block was inspired by the invitation system that we have for Archipel Market (event creation) and the invitation system on CRM. 

Also, for the moment we will concentrate on the Right Holders Management system accessible via the Movie Page:
User clicks on the CTA "Right Holders Management" on the Movie page and accesses the invitation part. 

### Goals
- [x] The go back" button redirects the user back to the Movie Page ; 
- [x] Under the Title we need to precise the name of the Movie and add a little icon ;
- [x] To avoid possible problems with access, the both fields should be mandatory ;
- [x] Like we do with the invitations for the events, when a user starts typing the email address, we propose the list of people that already have the access to the app (Avatar, First Name Last Name (Company)) ; 
- [x] Attention, the list of the Waterfall roles might be not exhaustive : Sales Agent, Main Distributor, Local Distributor, Author, Producers, Co-producers, Financiers, Institution, Performers. 

The new block, that is pretty different from what we do for the Archipels, is the table with the invited people. 
- [x] We need to be able to filter the participants in the table ;
- [x] If an invited person is not signed up to the plateforme, we show "Not Registered yet" in the "Name" column and "Organization Name". 
- [x] We introduce the status "pending" or "accepted" for the invited people. 
The actions in the last column should depend on the status : 
- [x] if the status is "accepted", then an action is "Remove Right Holder" ;
- [x] if the status is "pending", then two actions are "Resend Invitation" and "Remove Right Holder" ;
- [x] Introduce a tooltip "Resend Invitation" on hover on the action icon ;
- [x] Introduce a tooltip "Remove Right Holder" on hover on the action icon. 

### Ressources
[Link to Figma / No table](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=180-26203&t=oWelagNxIFt9imfF-4)
[
Link to Figma / Users suggested](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=180-26754&t=oWelagNxIFt9imfF-4)
[Link to Figma / List of Roles](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=180-26270&t=oWelagNxIFt9imfF-4)
[Link to Figma / Table with Invited Right Holders with not Registered](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=180-26312&t=oWelagNxIFt9imfF-4)
[Link to Figma / Table with invited Right Holders ](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=180-26917&t=oWelagNxIFt9imfF-4)

**Comment by phpgeekfr** [comment]
- [ ] producer can invite anybody on waterfall, other users can only invite producer

**Comment by phpgeekfr** [comment]
- [ ] check todo #9335 in code

**Comment by phpgeekfr** [comment]
- [x] on CRM, movie can only be set to "accepted" for blockframes app. When access is set to true, waterfall and permissions documents will be created if they does not exist

**Comment by phpgeekfr** [comment]
- [x] updated cleaning script, this will have to be checked (notification & invitation cleaning)

**Comment by phpgeekfr** [comment]
- [x] created 4 emails templates: 
```
    credentials: {
      joinWaterfall: 'd-15fb499c411448dd9328af06d11eb0a0'
    },

  invitation: {
    joinWaterfall: {
      created: 'd-8be5d46bcc764f04964ffbd17f094a52',
      accepted: 'd-80a560156925474292a3cf589f72f421',
      declined: 'd-6a5bd8adf8914e2394a068c2049696ac'
    }
  },
```
For now, templates can access `waterfall.titleId` and `waterfall.title`
