### ISSUE TITLE
Remove Waterfall dashboard dev menu

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/blockframes#9336]
Before any release or when the links becomes useless, we should remove the button that toggle the dev menu on waterfall dashbaord

![image](https://github.com/blockframes/blockframes/assets/5858657/dc1617ee-e7e2-4e49-94ca-149aec23594b)

**Comment by phpgeekfr** [comment]
link is now shown only if you are blockframes admin CF https://github.com/blockframes/blockframes/pull/9351

**Comment by phpgeekfr** [comment]
check `#9336` in code.

**Comment by Jackseed** [comment]
Even if it's only for BF admins we can remove it right? I mean it's not useful anymore since we have everything inside CRM

**Comment by phpgeekfr** [comment]
We don't have "versioning" examples on CRM  nor the "table" view created by Francois yet but they can be viewed on your demo version : https://github.com/blockframes/blockframes/pull/9446
So yes this can be removed from main branch
