### ISSUE TITLE
Restrict access to blockframes app per user

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9362]
- [ ] An org that already have access to blockframes app should be able to define which users of this org can access the app.
This could be done in the organization page.
- [ ] how to handle first user ?

**Comment by phpgeekfr** [comment]
moving this issue to icebox as "real" organizations access on waterfall app is not scheduled yet

**Comment by Jackseed** [comment]
Close it since we decided that we keep the org's app access system for blockframes
