### ISSUE TITLE
Create a "World sales" page like archipel content but with sales instead of avails

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9372]
WIP here : 
https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=489-32260&t=mn0bx0zGIbyGg5i9-0

**Comment by phpgeekfr** [comment]
@2amarkina here is a screenshot, if you have some UI changes to request
![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/0daf0ddd-c440-4246-a68c-b44c83468f98)

**Comment by 2amarkina** [comment]
**Updt.**  

As we have an hover that is different from the ordinary tooltip, we could add more information in it (see the screenshot)

- [ ] Add Buyer Organization Name
- [ ] Add the information about the duration of the contract (past, ongoing future). 

To present the duration of the contract we do not need to get into the details, but to show the general info with the following logic: 

- If **past contract**, then "Contract expired XX months ago" ; 
- If **ongoing contract**, then "Contract expires in XX months" ; 
- If **future contract**, then "Contract begins in XX months". 

For the time values we can use: 
- Days ; 
- Months (after 31 days) ; 
- Years (after 12 months). 

![world_sales.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/c27d585d-7829-4ad0-b235-be1ed204c83b)

For the UI it would be better to check "in real time" to be able to inspect the element. The elements to be checked: 
- headings ; 
- spacings ; 
- see if we could add a little stroke effect or something on hover to highlight a particular country.

**Comment by phpgeekfr** [comment]
@2amarkina if you want to live test, you can login with `eelios@gmail.com` and visit https://waterfall-blockframes-bruce.web.app/c/o/dashboard/title/kJcNULSZlg29dnuxho48/sales
