### ISSUE TITLE
Territory Filter Country bug - Avails

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9376]
Reported by several people already: sometimes we add several countries in the filter and continue to do the other manipulations with the filter. Sometimes the different countries disappear. 

- [x] We need to find out the pattern how this happens; 
- [x] Once pattern found, find the solution to resolve the bug

**Comment by 2amarkina** [comment]
**Pattern:** 
1. We select or type countries. 
2. Then we exit the avails filter.
3. We come back to the avails filter. 
4. And if we type (not select) n+1 country, then the new search is starting, erasing the previous one. 

The search should stay until user clicks "clear" and s/he should be able to continue to add countries

**Comment by phpgeekfr** [comment]
issue is located here `libs/ui/src/lib/static-autocomplete/group/group.component.ts` : 
```
    this.itemsSub = combineLatest([
      this.filteredGroups$.pipe(map(getItems)),
      this.form.valueChanges.pipe(pairwise())
    ]).subscribe(([filteredItems, [prev, next]]) => {
      if (prev) {
        // checked but filtered out values
        const hiddenValues = prev.filter(value => !filteredItems.includes(value));
        if (hiddenValues.length && !next.includes(hiddenValues[0])) {
          // add back the values
          this.form.setValue(next.concat(hiddenValues),{emitEvent:false});
        }
      }
      this.allItems = this.form.value;
    })
```

**Comment by phpgeekfr** [comment]
linked with https://github.com/blockframes/blockframes/issues/6990
