### ISSUE TITLE
setup firebase env for Vincent

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9386]
- [x] setup firebase env for Vincent for demo purposes
- [x] change `appUrl.waterfall` on `env.blockframes-bruce`

**Comment by Jackseed** [comment]
I got a demo on Wednesday, could you setup this Tuesday? (the 6th)

**Comment by phpgeekfr** [comment]
Env is ready to use. With latest code from branch `waterfall`

Apps:
- waterfall https://waterfall-blockframes-demo-1.web.app
- catalog https://catalog-blockframes-demo.web.app/
- festival https://festival-blockframes-demo.web.app/
- financiers https://financiers-blockframes-demo.web.app/
- crm https://crm-blockframes-demo.web.app/
- cms https://cms-blockframes-demo.web.app

@Jackseed & @2amarkina you should have access to firebase project if you need to interact with db

**Comment by Jackseed** [comment]
Perfect thanks! I'll check everything this afternoon and get back to you to confirm
