### ISSUE TITLE
Documents Management 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9389]
### Context
As discussed it would be better to introduce the file system to be able to manage all the documents inside the Waterfall app. That could help to get more space in the tabs navigation section of the film page. 

We could use the system that already exists for the Festival app in the "My Files" section with adding some supplementary upgrades. 

### Goals 
**General** 
- [x] Merge the existing tabs Financing Plan, Budget and Contracts to get one tab called "Documents" 
- [ ] Introduce three pre-built folders inside documents : Financing Plan, Budget and Contracts 
- [ ] Introduce the sharing icon in front of each folder 
- [ ] If possible highlight each line on hover 
- [ ] Inside the "Contracts" folder there are the following folders that are pre-built (order to confirm): Co-productions, Institutions (subsidies), Financiers, Mandates, Authors, Cast, Music, Other. 
- [ ] Introduce the sharing logic and on the folder's level and on each document (see the specs below)

**Sharing process & Roles' Access**
- [ ] Clicking on the "share" icon opens the modal.
- [ ] The header should say what kind of document user is about to share "You are about to share [Document Name]" or "Your are bout to share [Folder Name]". 
- [ ] User can see the list of the organizations and their roles (Right Holders involved into the Waterfall). User doesn't see the name or the email address of a particular user.
- [ ] User can choose one or several organizations with the help of checkboxes.
- [ ] The documents are automatically shared with the people associated with the concerned organizations
- [ ] After sending the documents (after sharing) show a snackbar "[Document Name] was successfully shared." or "[Folder Name] folder was successfully shared."
- [ ] Everyone can upload documents 
- [ ] Creator can edit, delete the documents 
uploaded

### Sources

[Documents View ](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=632-39695&t=krGmae3sDzghAMfN-4)

[Contracts View](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=632-39844&t=krGmae3sDzghAMfN-4)

[View end of the root of the folder](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=632-40033&t=d6cvkpNXKGGk9giK-4) (ex. Documents > Financing Plan, Documents > Budget, Documents > Contracts > Other)

[Sharing, step 1](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=632-40339&t=krGmae3sDzghAMfN-4)

[Sharing, step 2](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=632-40483&t=krGmae3sDzghAMfN-4)

[Snackbar after sharing](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=632-40965&t=krGmae3sDzghAMfN-4)

**Comment by phpgeekfr** [comment]
@2amarkina be able to share a folder will be complicated. We should be able to share all exiting documents inside a folder but not newly updated files. I suggest to postpone this for now.

**Comment by phpgeekfr** [comment]
@pldespaigne here is a PR that sets up model and rules https://github.com/blockframes/blockframes/pull/9401/files
Lets discuss this next week

**Comment by phpgeekfr** [comment]
- [ ] @phpgeekfr update unit test (`TODO #9389`)

**Comment by phpgeekfr** [comment]
Some bugs I noticed a few weeks ago :
- [ ] I added a pdf to my contracts, but if I click on "continue" instead on save, file is not uploaded
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXhDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bca975f035708a0d11731d70d17e4d96a8e1be6d/image.png)

- [ ] tooltip shrink/expand are inverted
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTlDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c7d58fede6519ac37ab7280270ffc164e1a0658/image.png)

- [ ]  If I upload a file, save, delete file, save, re-upload and click on continue instead of saving. When I go back to contract list, the same contract is duplicated (tested with a "sales agent" contract).

- [ ] When I already have uploaded contracts with CRM/Excel and rightholders linked to those contracts have no roles : If I choose the role of my rightholders and click on next, I need to refresh the page manually to view associated contracts (maybe not a real bug).

**Comment by phpgeekfr** [comment]
- [ ] when clicking on "add contract" we don't enter `create()` method on `ContractsFormComponent`, preventing document to have an ID, making `this.documentService.upsert<WaterfallDocument>(document, { params: { waterfallId: this.movieId } }),` to crash when saving.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkpZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e60e7ecd0cc27053ba0aebc8f9d83ea9c8cd08b/image.png)

- [ ] when editing an already created contract and want to create a new one on another role by clicking on "add contract" form is not reseted and contains previous contract data.

**Comment by phpgeekfr** [comment]
- [ ] given chosen contract type, buyerId/sellerId should be switched in `libs/waterfall/src/lib/components/contracts-form/contracts-form.component.ts` when assigning roles
