### ISSUE TITLE
Update Medias in Excel templates

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9409]
Medias list in Excel was not updated  : 

 ![image.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/cc1ddd99-03d8-4f42-bc74-9d1f88f6a092)

Static models :
```
export const medias = {
  payTv: 'Pay TV',
  freeTv: 'Free TV',
  payPerView: 'Pay Per View',
  est: 'EST',
  nVod: 'NVOD',
  aVod: 'AVOD',
  fVod: 'FVOD',
  sVod: 'SVOD',
  tVod: 'TVOD',
  inflight: 'Inflight',
  boats: 'Boats',
  hotels: 'Hotels',
  educational: 'Educational',
  festival: 'Festival',
  rental: 'Rental',
  theatrical: 'Theatrical',
  nonTheatrical: 'Non theatrical',
  through: 'Sell Through',
} as const
```

**Comment by phpgeekfr** [comment]
also :
- [ ] `Video (DVD, Bluray)` (excel) !== `Video (DVD, BluRay)` ( static group )
- [ ] mediaGroup with label `Theatrical` will conflict with media list `'theatrical', 'nonTheatrical'` another naming should be found

**Comment by 2amarkina** [comment]
Proposition: 
Name the group "Theatrical Rights"
