### ISSUE TITLE
E2E : email issues

### ISSUE THREAD

**Issue by n-germain-work** [blockframes/blockframes#9416]
Randomly, the emails are not retrieved.

Tests impacted :
- crm/create-orgs & festival/demo-request
`Error: No email found for this query, check node console for more data`

- festival/signup
`AssertionError: expected 'Congrats! Your request to join Jeanie Zieme corporation on Archipel Market was accepted' to include 'Your request to join Jeanie Zieme corporation on Archipel Market is being processed`

**Comment by phpgeekfr** [comment]
examples:
![image](https://github.com/blockframes/blockframes/assets/1194344/2dff02fb-d836-42e0-a2d0-04479427de31)
https://app.circleci.com/pipelines/github/blockframes/blockframes/29308/workflows/54c39835-e40a-4696-9362-5f03d7f52dc6/jobs/84305/tests

![image](https://github.com/blockframes/blockframes/assets/1194344/cd72d306-2196-4871-bc1b-0c0823dfe7f8)
https://app.circleci.com/pipelines/github/blockframes/blockframes/29322/workflows/ae34f1d0-dab4-4d61-a807-7d0f1c8e51a8/jobs/84374/tests#failed-test-0

**Comment by phpgeekfr** [comment]
not so much issues since. Closing
