### ISSUE TITLE
E2E : KPI on CI fails

### ISSUE THREAD

**Issue by n-germain-work** [blockframes/blockframes#9417]
It could be interesting to have a way to export from CircleCI :
- which tests fail the most
- in each test, class the erros by fail category

It would help to know which tests need rework in the long term.

**Comment by phpgeekfr** [comment]
we already have this in fact: https://app.circleci.com/insights/github/blockframes/blockframes/workflows/e2e-tests/tests?branch=income-waterfall-tests

**Comment by n-germain-work** [comment]
perfect, no need for more.
