### ISSUE TITLE
Contracts , Incomes & Expenses currencies

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9422]
We should discuss about what currencies will be allowed within the waterfall app for contracts, incomes & expenses.

Right now, on catalog contracts, only USD & EUR is allowed.

This should be updated
```typescript
export interface TotalIncome {
  EUR: number;
  USD: number;
}

export function getTotalIncome(incomes: Income[]) {
  const initialTotal: TotalIncome = { EUR: 0, USD: 0 };
  incomes.forEach(i => initialTotal[i.currency] += i.price);
  return initialTotal;
}
```

- [x] A dedicated component/pipe, should be created for this :
```typescript
        <ng-container *ngIf="totalIncome.USD"> {{ totalIncome.USD | currency:'USD' }} </ng-container>
        <ng-container *ngIf="totalIncome.USD && totalIncome.EUR"> and</ng-container>
        <ng-container *ngIf="totalIncome.EUR"> {{ totalIncome.EUR | currency:'EUR' }} </ng-container>
        <ng-container *ngIf="!totalIncome.USD && !totalIncome.EUR"> - </ng-container>
```

**Comment by phpgeekfr** [comment]
- [ ] check `#9422` in code

**Comment by Jackseed** [comment]
@2amarkina please add Currency input screen over here

**Comment by 2amarkina** [comment]
The currency should be chosen on the Movie Creation level<img width="764" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWlHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b6fcb17620dcc91ec0f40f651d6fd9081d67599/Create%20Film.png" alt="Create Film.png" />

**Comment by phpgeekfr** [comment]
I suggest not to tackle this now as this will require a lot of changes for a few benefits.
Right now all waterfall are set to EUR as main currency but incomes, expenses etc can be defined in USD also (with an arbitrary conversion rate)

**Comment by phpgeekfr** [comment]
- [ ] update or remove `PricePerCurrencyComponent`

**Comment by phpgeekfr** [comment]
- [ ] remove `mainCurrency` const in `libs/model/src/lib/waterfall/action.ts` and use waterfall document or shell to fetch main waterfall currency

**Comment by 2amarkina** [comment]
the list of the currency symbols can be found [here](https://wise.com/fr/blog/monnaies-du-monde-symboles)

**Comment by phpgeekfr** [comment]
- [ ] remove `price` and `currency` on terms as this is not used.
- [ ] get rid of `getDeclaredAmount` and create `contractPrice` that only sums contract.price.value[]
- [ ] keep `convertCurrenciesTo` for future use

**Comment by phpgeekfr** [comment]
- [ ] @2amarkina once merged, excel i18n file should be updated
- [ ]  @Jackseed @2amarkina currency columns on statement import should be removed from excel files (see template)
- [ ]   @Jackseed @2amarkina currency column on document import & last 2 columns (term price & term currency) should be removed from excel files (see template)

**Comment by phpgeekfr** [comment]
- [ ] need missing currency icons in svg

**Comment by 2amarkina** [comment]
All the new currency icons in svg are sent in slack and can also be found in [figma assets document](https://www.figma.com/design/Yi5RKQuroGJtpnPUCcAO67/Assets?node-id=1631-164&t=QVwXhR4docz8qAwQ-0)

Links to currency files have been added to notion internalization documentation.

**Comment by Jackseed** [comment]
- [ ] As discussed with Rita, we should replace all currencies with their 3 letters symbols (eg EUR) and add euro as first one in the list

**Comment by phpgeekfr** [comment]
I would like to close this issue but I don't quite understand what to do for
> As discussed with Rita, we should replace all currencies with their 3 letters symbols (eg EUR)
