### ISSUE TITLE
LP website bugs (WP)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9424]
Some bugs have been reported and they have no one to fix it so we're in charge.. (they're looking for a new SI company) 

Here are the reported bugs:
- « We are » and other elements from the homepage don't display 
- logo not displaying
- Menu not working
(contact me for admin creds)

**Comment by phpgeekfr** [comment]
@Jackseed can you check and tell me if everything is now good ?

**Comment by Jackseed** [comment]
lgtm 👍 
I'll check with Céline
