### ISSUE TITLE
Refactor CRUD operations in MovieService

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#944]
The Movie Service is now a CollectionService from akita-ng-fire. So this means that most CRUD operations are build in and need to be refactored. Like update is now updateById cause update is already defined by the CollectionService.

- [x] Use full potential of akita-ng-fire built in CRUD operations.
- [x] Move hooks (onCreate, onUpdate, onDelete) from service into backend-functions.

**Comment by ioaNikas** [comment]
As distributionDeal is a new subcollection, we need a dedicated state to use full potential of CollectionService CRUD.

:fire: There's already a distribution-deal folder into catalog marketplace app. Is it related to it ?

Need to discuss this issue with @Jackseed before going further.

**Comment by Jackseed** [comment]
@Maxstgt can you review @ioaNikas's PR and close the ticket if ok for you?
