### ISSUE TITLE
Statements - Template 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9485]
**Context** 

As already for a moment we do not change the design of the Statements table, let's start developing the template / shell for this part. We need to pay attention that this screen might be different according to the role of the user (Producer, Distributor), also the different views will exist for the empty state of this table. 

In our case we will start with the FULL view that a Producer will have. 

**TO DO:**
- [x] **Create the empty state** 
In the Producer's case, the empty state contains three CTAs with the images (for future UI update we'll have different images). Here are the three CTAs: Add distribution statement, add Sales Agent Statement, Add Outgoing Statement. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHRYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4579bbea64d6463ff46caa3dbe7ee192e83f514a/Waterfall_empty%20state.png)

After clicking on the CTAs user is rediricted to the Statement creation page, but as this part is not validated yet, we are moving to the next part.

- [x] **Create the inside chips navigation** 
When there is one statement added, then the table appears. For the main navigation we use the tabs, but to navigate inside the statements we use the clickable chips. They range the statements by role : Distributors, Sales Agents (incoming statements) and then they are separated with the outgoing statements Authors, Coproducers and Financiers. 

By default we keep the Distributors page opened after clicking on the Statements tab.

- [x] **Dropdown per role**
When user clicks on the distributor chip, then there is a dropdown with all the distributors. Near the dropdown there is a document icon that opens the contract related to the distributor in the other tab. In the drop down we have the name of the org and in the brackets we put the country

- [x] **CTAs "Add Statement"** 
This CTA creates a new statement for the chosen distributor. 

- [x] **Table**
In the table we need to show the following infos : the statement period, amount due, amount paid, le statut (draft / reported) and the date when the statement was issued. 

- [x] **Actions in the table for the statements in Draft**
For the statements in Draft we have "Notify Distributor" (might be changed) and "Edit" (will definitely stay)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclpYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--79b4876e2d46b4ded2cda0021c5a0655dca6f1c9/actions.png)

- [x] **Actions in the table for the statements Reported**
For the reported statements we have the other actions. The first one is "Download statement"-> directly downloads the statement and the second one is "View Statement" opens it in a new tab. To see if we not keep up only with "View Statement". 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnhYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0f8cfebd4bd81fd7af950accc988b75cbd612119/actions_reported.png)

**Comment by 2amarkina** [comment]
updt. as the first column we need to add the order from 1 to n. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTFDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f145e0b9266b788965ca2d7e4a6536e0619e4cf/Statements_Distrib.jpg)

**Comment by 2amarkina** [comment]
Updated example 
![Statements_Distrib](https://github.com/blockframes/blockframes/assets/55499036/eba180d0-94f6-4b3f-8d7e-616642a7c9d0)

**Comment by Jackseed** [comment]
Regarding my comment on Empty state, my bad, I forgot that you can create a contract directly from the statement flow if there is none yet. 

But then I would only keep "add distrib" or "add seller" statement since there is no use adding an outgoing statement without at least one of these 2 ones. 

I think we miss a intermediate state when: there is at least one statement for distributor but no outgoing yet

**Comment by 2amarkina** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFcxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e30e257a32eb8a97d9f7b336dae8fa1feaf6a2e/Waterfall.png)

**Comment by phpgeekfr** [comment]
-  [ ] @phpgeekfr check `// TODO #9485` in code
