### ISSUE TITLE
Change text in the invitation emails

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9506]
When a user is invited to join Archipel Content, then s/he receives an email (_Org invitation credentials_). In the email there is an embedded text (app.description) that need to be changed. 

Template ID: d-5c03ed5bde6d40768a44e3d1e1c95b67 

From this text: "Archipel Content is an ongoing digital marketplace for TV, VOD and ancillary rights. Let’s make content buying simple : One massive library, One package offer, One negotiation, One contract." 

To this text: "Archipel Content is an ongoing digital marketplace for TV, VOD and ancillary rights. Let’s make content buying simple : One massive library, One negotiation, One contract."

**Comment by Jackseed** [comment]
Update on text, we also need to remove `One massive library, One negotiation, One contract.`
So updated text is:
```
Archipel Content is an ongoing digital marketplace for TV, VOD and ancillary rights. Let’s make content buying simple!
```
