### ISSUE TITLE
Payment Management

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9517]
**Context:** 
Issue how user declares the payment.
To be done in parallel, or after the [Statements template issue](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/issues/gh/blockframes/blockframes/9485 )

**General:** 
- [ ] Need to add the column Payment date to the Statements’ List.

**When nothing is declared and the statement is in Draft:** 
- [ ] Actions are: edit statement.

**When Statement is reported and everything is already declared, then :** 
- [ ] Actions are: download statement, certify documents

**When Statement is reported, but payment is not declared yet :** 
- [ ] Actions are: download statement, certify documents, declare payment.
- [ ] If possible, add pulse animation to the “declare payment” icon.
- [ ] When the user clicks on the “Declare Payment” icon, then the modal appears. 
- [ ] In the modal we need to show the infos about the statement and the amount due field. 
- [ ] User should be able to open the Statement .pdf document in the separate tab

Idea: do we add one more column saying “left to be paid” @Jackseed ? 

[Link to Figma](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=1579-9300&mode=design&t=Qgm5MghJcWOKoNIL-4)

**Comment by Jackseed** [comment]
Since we can only make 1 payment on a statement I think it's not useful to add "left to be paid": it would be either equal to the total amount or 0
