### ISSUE TITLE
Waterfall dashboard 

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9519]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ055IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--59de90620fd9b070650cb4ad5ee9b479a1a393d1/image.png)

start with :
- Info globale: Total recettes du film (somme des incomes)
- un tableau avec une ligne par société et ces 4 colonnes:
  - total gagné par la société (= résultat instantané du waterfall)
  - total payé à la société (facultatif, que pour le prod /// on n’a pas l’info pour l’instant mais data remplie plus tard par la société)
  - total redistribué par la société à d’autres ayd (prod uniquement)
  - total net (gagné - redistribué) pour la société

ex:
UFO distrib France touche 10k€ sur la salle > il prend 10% de com donc 1K€ puis 2k frais puis 5K MG ça donne:
Total gagné: 10k€
Total reçu: NSP
Total redistribué: 2k (= 10k - 1 - 2 - 5)
Total net: 8k

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2x5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7f6b6d4c8298d69bfb6abd1ebe14d10cd6bde42e/image.png)

**Comment by Jackseed** [comment]
Design has changed 🙊 
cc @2amarkina

**Comment by 2amarkina** [comment]
New Design is here and also can be found on the Demo platform (Dashboard tab) and here is [the Figma link](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=1299-8067&mode=design&t=weSZQVWj8chCFQfY-4)

![Dashboard_Demo_Full_v7](https://github.com/blockframes/blockframes/assets/55499036/a4026f25-2400-46f2-9b7c-c48302829e04)

**Comment by Jackseed** [comment]
Sandbox demos:
- [Right Holders Revenue split](https://codesandbox.io/s/apx-pie-simple-forked-f3twyg)
- [Right Holders ROI](https://codesandbox.io/s/apx-bar-grouped-forked-pksr49) 
- [Net Revenue Over Time](https://codesandbox.io/s/apx-combo-multiple-yaxis-forked-xyd93c?file=/src/main.ts)

**Comment by 2amarkina** [comment]
The icons in .svg format for the dashboard can be found [here](https://drive.google.com/drive/folders/1kBn8z99io0Lzch5h_qFsKntx_kwb0UFv)
