### ISSUE TITLE
Outgoing Statements

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9531]
**Context:** 
When we are talking about the outgoing Statments, we are talking about a Producer who will issue his Statements for the Author, Co-Producer or Financer for example. 

### General 
The principle of the creation of the working statement is the same as for the Distributors and Sales Agents : the user chooses what kind of a statement he needs via the navigation chips 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0pzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57f0699dcfcee9187a610f54000f2caafb41c476/nav_chips.png)

Then the user access the Statement creation flow. Counter to the Distributors and Sales Agents, Outgoing Statement doesn't need to be filled with revenues data, everything is already calculated by the software. So, Producer will technically land on the Summary Page. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzlzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--814bd616d345b210a9574dcd8a2249652d780198/Statement%20%281%29.png)

### Advanced Modifications - WIP
The other important difference between the Distributors, SA statements and Outgoing Statement is that we need to let the Producer to choose if s/he wants to : 
- Continue and send the statement with **no modifications** (the one and only version is created), 
- Modify the statement **for everyone** (Producer should be able to modify all the informations presented in the Statement and this will create the new version of the Statement. In this case all the changes are visible for everyone).
- Modify the statement only for the particular company for which the statement should be issued (here we come with the necessity to clearly distinguish the "public" versions and the "private" versions)
 
**To do**
- [ ] Proposition of the modification flow [can be found here ](https://www.figma.com/file/bu5jFTcdDk4frztQ3v7nFA/Redditions?type=design&node-id=753-24589&mode=design&t=QyMpyMYzwqeWFdi1-4) & need to be validated on the product/design level.

**Comment by Jackseed** [comment]
Regarding revenues that are displayed on these outgoing statements the logic is that:
1. it takes all incoming payments that have been made **during** the outgoing statement period **and** that recoup rights related to the outgoing statement contract between producer and this right holder
2. it takes all incoming payments that have been made **prior to** the outgoing statement period but that haven't been declared to this right holder yet (**and** that recoup rights related to the outgoing statement contract between producer and this right holder)
- selected revenues are displayed by distributor/sale agent that first declared related incomes
- we display the detail of each distributor/sale agent statement related to this revenue
- 0 distributor/sales agent revenue statement should be considered as payed directly and thus be shown in this outgoing statement if it matches 1 or 2

As discussed with @2amarkina we still need to add a way for users to add/remove proposed payments.

**Comment by 2amarkina** [comment]
[figma link à jour ](https://www.figma.com/file/bu5jFTcdDk4frztQ3v7nFA/Redditions?type=design&node-id=1130-9574&mode=design&t=9M8aabkYGq5drKmQ-4)
