### ISSUE TITLE
Producer's Revenues & Expenses  (directSales)

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9532]
**Context**
As discussed, our Producer should be able to add his Revenues and Expenses in the devoted part. 

### General
The idea is the same as for the all previous Statement flows, there is no particular differencies. 

- [ ] [The screens are still to be validate on the product / design level. ](https://www.figma.com/file/bu5jFTcdDk4frztQ3v7nFA/Redditions?type=design&node-id=693-11886&mode=design&t=QyMpyMYzwqeWFdi1-4)

**Comment by 2amarkina** [comment]
IMPT. screens to be changed on the design level

**Comment by phpgeekfr** [comment]
https://www.figma.com/file/bu5jFTcdDk4frztQ3v7nFA/Redditions?type=design&node-id=974-42481&mode=design&t=mZAlUCs0Ieqkv5rv-0
