### ISSUE TITLE
Sharing and collaboration : documents, statements etc

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9553]
This issue is here to gather ideas and todos related to sharing and collaboration on the waterfall.

Right now rules are quite permissive regarding db acces: a `waterfallMember` can read almost everything.
We decided to check if user can access documents or not on the front side.

This will be done mainly using Angular `guards`.

TODO :
- [x] Statement guard `libs/waterfall/src/lib/guards/statement-active.guard.ts`

**Comment by 2amarkina** [comment]
**Rules for now:** 
- For the documents: shared on demand
- For the waterfall: the user can see the transfers above (the one with whom everything was shared)

Only Producer can see all the documents by default. All the others should be shared via sharing fonction.

**Comment by phpgeekfr** [comment]
- [ ] check `TODO #9553` in code

**Comment by 2amarkina** [comment]
**Context:** 
Producer should be able to share the particular documents with the particular organization. 

For example, producer wants to share the Distribution Contract and the Financing plan with an organization Sunset Distribution. Still, Sunset Distribution should have the Viewer access to the overall of the platform and has no access to the other documents. 

**To do:** 
- [ ] Add sharing icons on the item/document level (FP, Budget...)
<img width="856" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3RGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0f2140700bf6908123a4231bc92f63928bc27f8/End%20root.png" alt="End root.png" />

- [ ] Add sharing icons on the item / document level (Contracts...) 
<img width="1755" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzFGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e41f4ab8483f9b2f8961a53afea6d66ce75c37e7/Capture%20d%E2%80%99e%CC%81cran%202024-04-09%20a%CC%80%2011.54.22.png" alt="Capture d’écran 2024-04-09 à 11.54.22.png" />

- [ ] Prepare sharing modal with the following texts : 
Title : Share document with company 
Paragraph: Share this document with all users within the organization who are using Blockframes to ensure seamless collaboration and access.

**Comment by phpgeekfr** [comment]
created `Statements access rules and guards` #9758

**Comment by 2amarkina** [comment]
- [ ] Add the little text after the Select Companies field on the modal
Can't find the right holder's company on the list? 
**Please invite the right holder's company** and then share your document. 

PLease invite... should be a link that leads to the rights holders invitation section
