### ISSUE TITLE
Film Amortization

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9567]
**Context**
The Main user needs to be able to calculate the Film Amortization. It is needed to see if the film was successful or not. 
The calculation can differ according to the calculation method, so we need to be able to cover all possible cases. 

### **Details**
1. **User can access the calculation via the dedicated tab**
<img width="1253" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWtyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dffd902cb1a6cecc8257c84f3c27d3b570b19c3b/template.png" alt="template.png" />

2. **User access the layout for calculation.** 
This layout consists of. : 
- Choosing the organizations for which the calculation will be used (here user can give a name to the calculation method)
- Stepper with 3 main steps to assure the proper calculation.

<img width="632" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3FIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6543eab15baa72095a1c1e3c23b0a8b564691860/Film%20Amortization.png" alt="Film Amortization.png" />

3. **Film Cost Step** 
usually the calculation consists of four main elements (Producers Salary, General Expenses, Financing Fees and Production budget). But eventually s/he should be able to add a specific field. The table contains : 
- Nature 
- Amount 
- Percentage
- Base for percentage (a checkbox with multiple choice)
- Calculated amount

Logically the calculated amount should appear the last, but needed to be compared with the initial amount, so the Nature and the Amount colomns should remain fixed while scrolling. 

<img width="646" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3VIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d538ed15261c70f4288434fda88bdd9d1919d0dc/Film%20Amortization_Opened.png" alt="Film Amortization_Opened.png" />

4. **Financing Step**
User should also be able to describe the receipts to provide an accurate calculation. To do so, we let the user specify : 
- Name,
- Nature.

<img width="637" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEdIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--620c4bbd66f7c26fc384840888bea5ddc62c1b55/Financing_Film%20Amortization.png" alt="Financing_Film Amortization.png" />

5. "Net Revenue Producer Shares step"
For the last step, user should be able to tell us which conditions should be taken into account to provide the accurate calculation. To do so, we take the list of the existing conditions with the checkboxes to make a multiple choice. 

<img width="544" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFNIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e03c87ebfad6421e0628cb12283914bcb0e24bc/RNPP_Film%20Amortization.png" alt="RNPP_Film Amortization.png" />

6. **After the calculation** 
- After clicking on the "Calculate Amortization" after the last step provided, user can find the calculations used for different groups on the dedicated page. User is able to add the new calculation method, or modify the existing one. 
 
- Also, when calculation method exists, it should appear on the outgoing statements to inform the Right Holders if the film has succeded or not. 
 <img width="845" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejRyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f71febd213fa1a0c841ceb97259ce6496b1f1060/template.png" alt="template.png" />

<img width="245" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFdIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5c1c561b53962cab5012f49a55ff2d6f6f6fb33/Statement_opened.png" alt="Statement_opened.png" />

### Documents
- [Figma Screens](https://www.figma.com/file/0NDJn66qe0SWpjzF1Xk0s3/Film-Amortization?type=design&node-id=173-5556&mode=design&t=IDuAduVz0JfZcski-0)
- [Notion explanation ](https://www.notion.so/cascade8/Film-amortisation-69fce6eb70a84c2990be83cc17145f8d)

**Comment by Jackseed** [comment]
- [ ] Add the [condition](https://www.notion.so/cascade8/Film-amortization-69fce6eb70a84c2990be83cc17145f8d?pvs=4#f751ca9597a24932a5be5d77f9c7557d) related to film amortization

**Comment by 2amarkina** [comment]
This issue is divided into several pieces to make it easier to develop & follow up : 
1. Creating the space for the Amortization & establish the first logic #
2. Layout of the Effective Film Cost & Film Financing (simplified view) #
3. Producer's Net Participation (simplified view) #
4. Outgoing Statements (table of amortization to integrate) #
