### ISSUE TITLE
Right / group list & pool creation

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9574]
## Context
We need to add a way for users to create pools and rename groups (since they are automatically created). 

### Right list
For this purpose we'll introduce a new component which is the right list ([figma](https://www.figma.com/file/dzoXGi5WFvHN7t2mPWC4zq/Waterfall-(UX%2FUI)?type=design&node-id=802-15716&mode=design&t=CJSxS6ZDg1DpKTYt-4))
<img width="544" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGhxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1da65ccf70790854f1ec1cd0aa13fc7b117041fd/rs_list.png" alt="rs_list.png" />
>

- [ ] Ideally we re-use what can be taken from the multi-select list with groups like the territory or media list
<img width="411" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4813cdf4d04dea1ae2fec0beeecbe84b44767c8/image.png" alt="image.png" />

- [ ] Rights are listed with their names
- [ ] Groups are bold and inside rights are indented
- [ ] Edit button opens an edit in place input (to confirm with @2amarkina )
- [ ] Delete button well.. delete right (we'll add protection later)
- [ ] A master checkbox allow to check all the rights
- [ ] Aside the master checkbox you can type to filter the rights through their name
- [ ] A new "See list of all Receipt Shares" button will be added on the right form on "Receipt Share" tab to open that right list

<img width="438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGxxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ada0db5fb7c3f2988e5d2187477daa036a1e6e9b/rs.png" alt="rs.png" />

### Pool creation
Through this list users will be able to create pools:
- [ ] A bouton "Group Receipt Shares" is on top of the list, disable by default
- [ ] Once more than 1 right are selected, a "Group Receipt Shares" button is enabled
- [ ] This button opens a pool creation modale with 2 fields: 
- [ ] Pre-selected rights (using still a multi-select component)
- [ ] A string input for the Pool name
 <img width="698" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3RSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2829f6d1460f863c9839b23d7ce334b71a05c220/image.png" alt="image.png" />

### Pool list
Once at list one pool exists:
- [ ] The pool name is listed above the right list as a filtering chip
- [ ] Each right of the pool has the pool name aside its name as a status (existing component)

### Pool creation through conditions
We'll use the same pool creation system through conditions (see [figma](https://www.figma.com/file/dzoXGi5WFvHN7t2mPWC4zq/Waterfall-(UX%2FUI)?type=design&node-id=833-14552&mode=design&t=tEQbFJACJXktKrML-4)).
<img width="435" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek5SQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b096996d68184a2c05ac1142e111fcf3270d177c/image.png" alt="image.png" />

- [ ] At the bottom of the pool list we always have an option which is "+ CREATE POOL"
- [ ] It opens a modale with the right list and "Pool creation" as the title
- [ ] A text "_No pools created_" is visible is there is no pool.

**Comment by 2amarkina** [comment]
**Some supplementary flows and descriptions are presented below** 

### Flow Edit
[Figma Link](https://www.figma.com/file/dzoXGi5WFvHN7t2mPWC4zq/Waterfall-(UX%2FUI)?type=design&node-id=968-6142&mode=design&t=rqMiXJlkJi4KUxcE-4)
Here we are showing a case, when a user wants to edit the name of the automatic group. 

- [ ] User should see a dropdown with multiselect to know what kind of elements are regrouped
- [ ] User should be able to change the Group Name via the free field. 
- [ ] Then, we need to have an "Update Receipt Shares’ Group" CTA

<img width="1730" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHBxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6a5bb4d3e505ac539d16a98c166608dd81b6faa/FLOW%20EDIT.png" alt="FLOW EDIT.png" />

### Flow Delete
[Figma Link](https://www.figma.com/file/dzoXGi5WFvHN7t2mPWC4zq/Waterfall-(UX%2FUI)?type=design&node-id=968-6356&mode=design&t=rqMiXJlkJi4KUxcE-4)
Here we give a user an option to delete a Receipt Share. 
- [ ] As for Edit flow, we also need to open the modal for the Delete  flow. 
- [ ] We show the user the full name of the Receipt Share, but s/he is not able to change it. This information is informative. 
- [ ] CTA "Delete Receipt Share"

<img width="1636" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHRxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--024143bc743248a38f8f23fafffe99bf3e88dbe8/FLOW%20DELETE.png" alt="FLOW DELETE.png" />

### Flow Filtering
[Figma link](https://www.figma.com/file/dzoXGi5WFvHN7t2mPWC4zq/Waterfall-(UX%2FUI)?type=design&node-id=968-6776&mode=design&t=rqMiXJlkJi4KUxcE-4)

- [ ] When the pool is created, we need to show the Pool Name as a chip.
- [ ] When a user clicks on the pool name, then the filtreing function is abled. 
- [ ] User will see only the Receipt Share that were labeled with the concerned Pool Name. 

<img width="1377" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDFxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--163afaaf62b7e7a0c0be9c7a93f673e130d430c8/FLOW%20FILTERING.png" alt="FLOW FILTERING.png" />

### Flow Edit Pools 
[Figma link](https://www.figma.com/file/dzoXGi5WFvHN7t2mPWC4zq/Waterfall-(UX%2FUI)?type=design&node-id=968-7364&mode=design&t=rqMiXJlkJi4KUxcE-4)
We need to be able not only to filter the pools, but only edit them (edit the names and the Receipt Shares included into the pools). 

- [ ] To do so, we re-use our Tab system (RS List & Pools only).
- [ ] The tabs should appear only when at least one pool has been created. 
- [ ] When we switch to the "Pools only" we see the list with the pools' names and with edit and ungroup icons. 
- [ ] As usual we can see the modal with two CTAs : "Update Pool", and "Unpool" 
- [ ] We need to prevent a user about the consequences "❗️Pay attention, if you unpool the Receipt Shares, it will have an impact on Waterfall Conditions." 
- [ ] Also, we need to check together about the exact list where we use the pools and show this list to the users.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHRxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--354467eba93054f2f2cc76ac5b264fe0b2d71d94/FLOW%20EDIT%20POOLS%20%281%29.png" alt="FLOW EDIT POOLS (1).png" />

**Comment by 2amarkina** [comment]
**Some supplementary flows and descriptions are presented below** 

### Flow Edit
[Figma Link](https://www.figma.com/file/dzoXGi5WFvHN7t2mPWC4zq/Waterfall-(UX%2FUI)?type=design&node-id=968-6142&mode=design&t=rqMiXJlkJi4KUxcE-4)
Here we are showing a case, when a user wants to edit the name of the automatic group. 

- [ ] User should see a dropdown with multiselect to know what kind of elements are regrouped
- [ ] User should be able to change the Group Name via the free field. 
- [ ] Then, we need to have an "Update Receipt Shares’ Group" CTA

<img width="1730" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHBxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6a5bb4d3e505ac539d16a98c166608dd81b6faa/FLOW%20EDIT.png" alt="FLOW EDIT.png" />

### Flow Delete
[Figma Link](https://www.figma.com/file/dzoXGi5WFvHN7t2mPWC4zq/Waterfall-(UX%2FUI)?type=design&node-id=968-6356&mode=design&t=rqMiXJlkJi4KUxcE-4)
Here we give a user an option to delete a Receipt Share. 
- [ ] As for Edit flow, we also need to open the modal for the Delete  flow. 
- [ ] We show the user the full name of the Receipt Share, but s/he is not able to change it. This information is informative. 
- [ ] CTA "Delete Receipt Share"

<img width="1636" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHRxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--024143bc743248a38f8f23fafffe99bf3e88dbe8/FLOW%20DELETE.png" alt="FLOW DELETE.png" />

### Flow Filtering
[Figma link](https://www.figma.com/file/dzoXGi5WFvHN7t2mPWC4zq/Waterfall-(UX%2FUI)?type=design&node-id=968-6776&mode=design&t=rqMiXJlkJi4KUxcE-4)

- [ ] When the pool is created, we need to show the Pool Name as a chip.
- [ ] When a user clicks on the pool name, then the filtreing function is abled. 
- [ ] User will see only the Receipt Share that were labeled with the concerned Pool Name. 

<img width="1377" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDFxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--163afaaf62b7e7a0c0be9c7a93f673e130d430c8/FLOW%20FILTERING.png" alt="FLOW FILTERING.png" />

### Flow Edit Pools 
[Figma link](https://www.figma.com/file/dzoXGi5WFvHN7t2mPWC4zq/Waterfall-(UX%2FUI)?type=design&node-id=968-7364&mode=design&t=rqMiXJlkJi4KUxcE-4)
We need to be able not only to filter the pools, but only edit them (edit the names and the Receipt Shares included into the pools). 

- [ ] To do so, we re-use our Tab system (RS List & Pools only).
- [ ] The tabs should appear only when at least one pool has been created. 
- [ ] When we switch to the "Pools only" we see the list with the pools' names and with edit and ungroup icons. 
- [ ] As usual we can see the modal with two CTAs : "Update Pool", and "Unpool" 
- [ ] We need to prevent a user about the consequences "❗️Pay attention, if you unpool the Receipt Shares, it will have an impact on Waterfall Conditions." 
- [ ] Also, we need to check together about the exact list where we use the pools and show this list to the users.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHRxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--354467eba93054f2f2cc76ac5b264fe0b2d71d94/FLOW%20EDIT%20POOLS%20%281%29.png" alt="FLOW EDIT POOLS (1).png" />
