### ISSUE TITLE
Contracts - Roles relation

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9577]
### Context
The main way to create fake orgs & roles will be through contracts (either excel import or contract form). Fake org name will be taken from licensor/licensee field and `type` will enable us to infer fake org role.

### Contracts - Roles relation
- [x] All contract except `Authors` will give a role to the `licensee` of the contract, being the same as the contract type 
- [x] Regarding `Authors` contract, the `author` role will be given to the ` licensor` and `producer` role to the `licensee`. It's the only contract that sets 2 roles, both producer & author. Thus it's also the only one that gives a role to the `licensor`. 

### Right holder tab
- [x] All roles can be changed or supercharged on the Right holders tab (see #9537)

### Agent
~~- [ ] Agent is a role that has no contract associated. It's possible to set a fake org as agent with `authors`  and `cast` contracts. They have a checkbox “Agent attached”, if checked new text field with Agent name appears. Once author contract saved, it creates a contract copy with all the same info than author except that there is no price and Agent replaces Authors (@2amarkina we have to update design to add this)~~

### Other
- [x] Other contracts don't add any role to licensor / licensee orgs but still creates fake orgs 

Here is a summary table on this Contracts - Roles relation, [available on Notion](https://www.notion.so/cascade8/eb56d56d637842d0b8c0d2232f65f750?v=fd5ad9231da4446eb35803ae519dbacd&pvs=4)
<img width="860" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZtQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06893e6150430a5c178bd7e7d1520e18b0a9f811/image.png" alt="image.png" />

**Comment by Jackseed** [comment]
Regarding contract form and automatic roles, there is currently a `Licensor waterfall role` multi select that updates when the Licensor is selected. That's great!

- [ ] Best would be to add the same to Licensee + the rules described above so when the licensee is chosen it automatically charges its previous roles (if any) + supercharges roles with the contract role

**Comment by phpgeekfr** [comment]
> Agent is a role that has no contract associated. It's possible to set a fake org as agent with authors and cast contracts. They have a checkbox “Agent attached”, if checked new text field with Agent name appears. Once author contract saved, it creates a contract copy with all the same info than author except that there is no price and Agent replaces Authors

@Jackseed @2amarkina need to validate this before implementing it

**Comment by Jackseed** [comment]
I'm open to change the logic (I did it on my own) but we need something for agents. All actors have an agent and they always are included in the same contract as the actor. Agent don't have a contract on their own connecting them to the film, so user won't create one for them. 

That's why I proposed this checkbox but best would be to have multiple licensors and add them to the author's contract.

**Comment by phpgeekfr** [comment]
IMO, until we find something more appropriate overtime, I would add another role and contract type for agents and handle them as any other rightholder. 
It may be be frustrating to duplicate everything manually but we would have something working without this custom case that really looks like a source of many bugs in contracts, rightholder, statements, graph etc

**Comment by Jackseed** [comment]
You got a point.. alright then let's go for
- [ ] Add agent as new role
