### ISSUE TITLE
Waterfall sources - Allow same terms on multiple sources

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9581]
Currently we block the creation of sources that overlap with other sources' terms. In fact it's not needed to block since when we declare incomes in the statement form the user select the attached sources (active tab). 
- [ ] Remove the block

The only problem is on Excel import so we have to add a check on this so on statement import:
- [ ]  If income terms target more than one source we add a blocking error saying that user must declare source name on that income
(but we keep the auto-assignment of incomes to sources otherwise)

**Comment by phpgeekfr** [comment]
- [ ] check `TODO #9581` in code
