### ISSUE TITLE
Interests calculation

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9582]
Full doc [over here](https://www.notion.so/cascade8/Interests-calculation-9812e8e1549f48b3bed00c796232a6c0)

### Job to be done
- [x] Implement [condition](https://www.notion.so/cascade8/Interests-calculation-9812e8e1549f48b3bed00c796232a6c0?pvs=4#31100e4e20dd4e609ab3b412b5f21a02) UI & logic
- [x] Add payments & dates to contract price (not amendment), app only (not excel)
- [x] Include summary table inside the outgoing statements ( & pdf )

cc @2amarkina for corresponding designs

**Comment by 2amarkina** [comment]
Example of the table of the Interest Rate Details
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTZIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--107c84f27072b88aba73089c1cdae9f123e48865/Gestion%20des%20taux%20d%27inte%CC%81re%CC%82ts.png" alt="Gestion des taux d'intérêts.png" />

Example of the table inside the Outgoing Statement
<img width="269" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOStIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e653db388f9c999ebc37057af88874a6506046b6/Outgoing%20Stament_Interests.png" alt="Outgoing Stament_Interests.png" />
