### ISSUE TITLE
Collaboration step 2 - Stakeholder invitation

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9585]
## Description
After step 1 (statement sharing), step 2 will be to give an actual app access to stakeholders. They will have access to 3 tabs only: Statements, Documents & Waterfall. 
[Figma](https://www.figma.com/file/s0qk9gGKVSJl8zXTPuNipr/UI---Blockframes?type=design&node-id=1775-51731&mode=design&t=UZ5uCuJ8SmwesDv5-4) to be updated by @2amarkina 

## Job to be done
- [x] Add roles (Member / admin) on the right holders table and form
- [x] Implement admin / member rules
<img width="524" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUIvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--281b85131f8e6502a15ef20c1c5c4884f2efb84e/image.png" alt="image.png" />

- [x] Add the invitation section in both right holders tab and statement sharing feature
- [x] Enable current admin org to embody fake org(s)
- [x] Pending invitations section
- [x] Accepted members section

**Comment by phpgeekfr** [comment]
- [ ] re-use `apps/waterfall/waterfall/src/app/dashboard/waterfall/right-holders/right-holders.module.ts` ?

**Comment by 2amarkina** [comment]
Here is the up to date mock up with the Invitation System, following our latest discussions. 
Also, I would propose to change "Admin / Member" to "Editor / Viewer", as : 
1. The main difference between "Admin" and "Member" is the ability of Admin to edit documents, so I think it's better to be more straight forward.
2. This will help to establish the difference between the information that we have about Right Holders and the Members of the organization. 

<img width="454" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG1TQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3574d5249692070d072320b01c3db0a27ea8ef7/RH_MAJ.png" alt="RH_MAJ.png" />

**Comment by Jackseed** [comment]
Great! Looks good to me

**Comment by phpgeekfr** [comment]
@2amarkina @Jackseed we need to review quickly the rules for document creation
