### ISSUE TITLE
World sales map

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9589]
## Context 
World sales map is already in the app but the mandate/sale approach is outdated. We need to update it. 
The logic about this map is: 
- take the world / all rights as available since we're on the producer side (if we really need to have a mandate, we can use the contract with sales agent)
- use all local distributors, main distributors & broadcasters contracts to show if rights are sold in the map or not (and list the concerned contract in the card list)

## TODO
- [x] Update the map with above logic
- [ ] 🥤 Add a sum up table below the world map with columns Licensor | Licensee | Territories | Medias | Amount (sortable on amount)

**Comment by 2amarkina** [comment]
New screen with World Sales table above the map
<img width="633" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2VIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--695277b34faffa33c819a39598947fdde004c0eb/World%20Sales.png" alt="World Sales.png" />
