### ISSUE TITLE
Improve conditionToString to string function.

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9623]
instead of displaying right, expense and contracts ids, we could improve the function to use real names instead.
<img width="953" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelVRQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5239a3f082e685a6ad4ffb29b5e98283fd66e352/image.png" alt="image.png" />

`libs/waterfall/src/lib/components/graph/conditions/condition-item/condition.ts`

Maybe use a caching system to avoid to much queries on the db to fetch contract, rights etc..

**Comment by Jackseed** [comment]
Looks important to me to have names instead of ids so I've tagged it Release 5.0
