### ISSUE TITLE
Trackpad actions for the Graph

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9647]
### Context
We need to make the graph experience really fluid and easy for the users. To do so, we should adapt the usage to the mouse and trackpad users, also as MC and Windows users.

#### Mobile Users
We need to inform mobile and tablet users that the app was originally designed for desktop use. 
- [ ] So, we could show a modal message if the user tries to access via mobile or tablet. 

Title: Desktop-Exclusive Software Notice
Text: Our software is designed exclusively for desktop use and is not compatible with mobile or tablet devices. Attempting to use it on such devices may result in unexpected issues and loss of functionality. For the best user experience, please ensure you use our software on a desktop computer. Thank you for your understanding. 

#### Gestures and the attended actions (Trackpad)
- [ ] Instead of double-click, do the simple click action to access the Pools list. 
- [ ] If a user uses two fingers to swipe up or down, the graph should scroll instead of zooming. 
<img width="592" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0V5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc995def1b7fac41e0d718aff27cf2c853252d8a/trackpad2-two-finger.png" alt="trackpad2-two-finger.png" />

- [ ] If a user uses two fingers to swipe left or right, the graph should scroll left or right accordingly. 
<img width="592" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0l5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87fc7f466886129b02cd85679e6f38ea4689a170/trackpad2-pinch-to-zoom.png" alt="trackpad2-pinch-to-zoom.png" />

- [ ] Zoom in and zoom out should be done by spreading fingers. 
- [ ] Grabbing can be kept. 

#### Gestures done with a mouse (Mouse)
- [ ] Scrolling should not trigger the zooming, but also the scrolling of the graph. 
<img width="296" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK015QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3488c0da46798b7f919e24ccf5535baf21c0bdd3/magic_mouse-scroll.png" alt="magic_mouse-scroll.png" />

- [ ] Grabbing can be kept.

**Comment by Jackseed** [comment]
- [ ] +/- buttons are disabled, it should work
- [ ] [Natural scrolling settings](https://support.apple.com/en-mz/guide/mac-help/mchlp1226/mac) is not respected
If that's not too much it would be cool to have it. Don't know if we can have the info from the browser but GPT offered to test it directly 
<img width="676" alt="image" src="https://github.com/blockframes/blockframes/assets/14964443/da017f38-918c-4c3b-9003-216615c13ade">

**Comment by 2amarkina** [comment]
Following the last updates, I think that we are all good with this issue
