### ISSUE TITLE
App Review - Left to do

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9657]
Created from #9586 with only things left to do to make it more clear.

## General UI

 - [ ]  ☕ In different places we display the page before data is loaded so it creates a little spike. I guess that's not the time but would be great to have a loader before data is loaded and then display the page
 (example on statement form)
<img width="640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelNDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73e477e4cdf7c3eb40360cead231edd07f4d5d99/Dec-22-2023%2014-31-40.gif" alt="Dec-22-2023 14-31-40.gif" />

- [ ] add terms & conditions  ( https://github.com/blockframes/blockframes/pull/9262#discussion_r1189576540 ) & DATA PRIVACY POLICY

### Documents
- [x] Fake org name are saved lowercase, we should keep the capital letters instead
- [x] Add Document name in the template

### Statements
- [x] Expense type: accept string (so `frais_indie_sales` can be `Frais IndieSales`)

## Waterfall Graph
- [ ] Group collision on Gaspard at the wedding ([graph](https://waterfall-blockframes-bruce.web.app/c/o/dashboard/title/UOAxqGsWmON1YhWO88H4/waterfall) on Bruce's env or [excels](https://drive.google.com/drive/u/2/folders/1qj6-fiymi2nBP_0C-sYfn4byaSzmVAFb) for import)
<img width="1493" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1NDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7dcf5182133db74754b4a05eaceb7714bdcf13d8/image.png" alt="image.png" />

### Graph form (right side)
- [ ] "Receipt Sources" select:
- Rename it `Parent Revenue Element(s)`
- Label "Source Name" becomes `Parent Name(s)`
- Hint: `Choose parent revenue elements from which this Receipt Share draw funds. You can add as many parents as you want.`
- [ ] If a user clicks away from the Graph's right Form and there is no saved RS, the modal should show "before we begin" text. 
- [ ] If a user clicks away from the Graph's right form and there are n+1 RS, then the modal should show the RS list. 
- [ ] If we change the name of the Receipt Share Name, the change should be automatically applied in the conditions. 
- [ ] If possible during the creation of the waterfall, it would be better to add the name of the right holder in brackets. It's needed to distinguish the Reciept Shares with the same names
<img width="1433" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDBrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4f71999c603f3d694a323c95848eae3d4faa693/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-02-02%20%D0%B2%2015.59.14.png" alt="Снимок экрана 2024-02-02 в 15.59.14.png" />

- [x] rightholder should be a simple select (or input search => select ), it should not be possible to enter a not existing rightholder as we don't create it.
<img width="1828" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1k1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--417c04066a8c9fca1922d70a33a5a6b3ff83cb49/image.png" alt="image.png" />

### Graph form (left side)
- [ ] see issue #9647 for the trackpad gestures
- [ ] ☕️ add some space inside on the left the waterfall Scheme Surface and more space between "Please provide the condition" and the scheme itself
<img width="1571" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkFQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9b0fa7d1ef9932cbe14c7dca271373aee5ed699/Capture%20d%E2%80%99e%CC%81cran%202024-01-30%20a%CC%80%2014.50.23.png" alt="Capture d’écran 2024-01-30 à 14.50.23.png" />

## Contract form
- [ ] ☕ Sticky header on the form (for this component wherever it is)
- [x] If we have already entered the signature start and end date, and then we change the first date and play with duration number and duration period, the end date remains related to the previous date and not the new one
<img width="1262" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1FrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ffb1fda00e750184bcaf62601f198cb9af801cd9/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-02-02%20%D0%B2%2016.41.53.png" alt="Снимок экрана 2024-02-02 в 16.41.53.png" />

## Dashboard
- [x] add link to document in dashboard bottom table (Revenue Summary table)

## Statements
- [x] add link to document in statements ( outgoing), statement list etc ...
### Statement form
**Receipt form**
- [ ] Don't know if there is a logical reason but receipts are by default saved on an empty line. Instead could we have the form open without the table (see below screenshots) and ofc best would be to have the [Table + form component ](https://github.com/blockframes/blockframes/issues/9587)
_Current default_
<img width="1876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXlDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19d9f19c625b834f73ab4767a8214747e662002f/image.png" alt="image.png" />
_Change asked_
<img width="1880" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXVDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2dd0fdc2771e82cd10311e7a04f08652f27cc75b/image.png" alt="image.png" />

~~- [ ] Not completely sure of this solution ( @2amarkina please confirm or propose something else) but I think the "Save Receipt" button is not visible enough > change it for a blue button ? If so, maybe we can move the buttons Continue / Saved & Come back later to top right of the page?~~ 

**Expense form**
- [ ] Remove the * on "Nature" input (renamed Expenses name)

### Statement list
**Right Holder selection**
- [x] Either remove the "See Contracts" button or add a link to the actual document (if we have the document list going)
- [x] The action should lead to the particular contract 
<img width="1454" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejRRQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d17a6e0de55dce1e4db6c83e28cdc6e3940240b9/Capture%20d%E2%80%99e%CC%81cran%202024-01-30%20a%CC%80%2015.05.17.png" alt="Capture d’écran 2024-01-30 à 15.05.17.png" />

**Sharing**
- [x] configure sendgrid template ID : d-7a07c39d8c104674ad278669c9ce787a (BF - STATEMENT - Share statement)
something like :
``` 
Hi, 

{{ org.name }} is sending you a statement for **{{ waterfall.title }}** on behalf of {{statement.receiverOrgName}} for the period  {{statement.from}} - {{statement.to}}. 

Please find the statement file attached.

```

Variables that can be used:
```
user.firstName
user.lastName
user.email
waterfall.title
app.description
app.logo
app.name
app.url 
statement.senderRightholderName
statement.receiverRightholderName
statement.from
statement.to
org.name
org.email
org.id
org.country
org.activity
```
- [x] and also put this picture in email
![Property 1=Illustrations_380px_feature_key1_light](https://github.com/blockframes/blockframes/assets/55499036/de579427-32fc-4f97-8ed9-45b867c3353e)

**New statement button**
- [x] I think this is not visible enough, @2amarkina do we have something in between so it's not main CTA but not invisible?

**Comment by 2amarkina** [comment]
- [ ] Add more space below the CTA "Group Right Share" when there are pool chips (about 20px)<img width="676" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejVBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f18c436bf5d54d293dec29e64b4e2b5b1b45280/RS%20padding.png" alt="RS padding.png" />

**Comment by 2amarkina** [comment]
Answers for the design changes: 

`1. Not completely sure of this solution ( @2amarkina please confirm or propose something else) but I think the "Save Receipt" button is not visible enough > change it for a blue button ? If so, maybe we can move the buttons Continue / Saved & Come back later to top right of the page?` 👈🏻 I do not think that it's necessary at the moment as this component will soon be changed to the "table+form" one. 

`2.  I think this is not visible enough, @2amarkina do we have something in between so it's not main CTA but not invisible?` 👈🏻 I totally agree with you that we could make this part more visible. On the mock-ups I've used the grey color (that we have on hover), but it's the new element. So, I would propose to use the light blue CTA version, thzt we have for "Manage or Create Waterfall" on the header <img width="794" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWxMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--598c521542fe89813ba95935fd407369d7a9b9a8/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-02-12%20%D0%B2%2010.36.20.png" alt="Снимок экрана 2024-02-12 в 10.36.20.png" />

**Comment by phpgeekfr** [comment]
> Don't know if there is a logical reason but receipts are by default saved on an empty line. Instead could we have the form open without the table (see below screenshots) and ofc best would be to have the

As @2amarkina said for another point, I would suggest to wait for the  "table+form" component

> Remove the * on "Nature" input (renamed Expenses name)

I don't know what to do with this one, as this field is used in the summary view.
Example with many expenses for the same "expense type" : 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2RMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dff0a0add16b2504842181e5b8ec712db1963ed0/image.png" alt="image.png" />

**Comment by 2amarkina** [comment]
- [ ] Check for the padding in the "documents" modal and add about 50px to the bottom<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjlOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de981fec71b3d2fc66172023bc86359dc57e6394/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-02-12%20%D0%B2%2016.16.50.png" alt="Снимок экрана 2024-02-12 в 16.16.50.png" />

**Comment by 2amarkina** [comment]
**Waterfall creation flow:** 
- [ ] We already have a CTA "publish waterfall" at the bottom of the page, so do not need to repeat it above. Need to remove it from the top 
- [ ] Need to add the same tooltip to the CTA at the end
<img width="856" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelpVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16b32e854f4e3a2a5dd7eb4c8fc8bdf372708a4b/screencapture-app-blockframes-io-c-o-dashboard-title-7hdNwhVrEcVLmITOtlJd-init-2024-02-13-16_36_43.png" alt="screencapture-app-blockframes-io-c-o-dashboard-title-7hdNwhVrEcVLmITOtlJd-init-2024-02-13-16_36_43.png" />

**Comment by phpgeekfr** [comment]
- [x] add "BLOCKFRAMES" (BF) to `DATA PRIVACY POLICY` page, with same config as AM

**Comment by phpgeekfr** [comment]
moved what is left to do to #9675
