### ISSUE TITLE
Update of the demo 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9660]
### Context
In preparation for Berlin festival we need to update our demo with images that better correspond to the changes that we've recently made. 

[drive link](https://drive.google.com/drive/folders/1yo83tIyNtq9PwTvE-P0dDXTd-2YhEtJ5?usp=drive_link)

### General updates
- [x] Update the order of the tabs
- [x] Update the header (see "from" "to")
<img width="1355" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWhIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38cf668884eb59cb64f8257937ba85b3e3cb2f21/Header%20Update.png" alt="Header Update.png" />

### Statements' List
- [x] Update[ navigation chips](https://drive.google.com/file/d/1XdkaXDqSGu5oxBw_rj_4P26ten9kyNte/view?usp=drive_link) (Distributors)

- [x] Update [Distributors' Statements list](https://drive.google.com/file/d/1RvYOjebdt7hN7z6NmLwmD_JsWAHeX9gR/view?usp=drive_link)

- [x] Update [navigation chips](https://drive.google.com/file/d/1us6BajGVj9GXEKhZ65Tik4bhfPVAVEu0/view?usp=sharing) (Outgoing / Coproducers)

- [x] Update [Outgoing statements list](https://drive.google.com/file/d/1RHPqxq3Do3PcDYGcC4N8qEJYCUDPWlV6/view?usp=drive_link)

### Distributor's Statements
- [x] Replace all the flow of the Distributors Statements with [the new elements](https://drive.google.com/drive/folders/139yDdfdlci-N0YRfzL_fWGYLrCCSOmE9?usp=drive_link )

### Outgoing
- [x] Update the Outgoing Statement with [a new one](https://drive.google.com/file/d/1h7Nxy-i7XidOBdZB00FtF5QTpRS4uZ_E/view?usp=drive_link)

### Right Holders
- [x] Update the Right Holders image with [a new one](https://drive.google.com/file/d/1OAcyjqTGYdigewLkwwun-kHeQX9ynCjc/view?usp=drive_link)

### Waterfall
- [x] Update the Waterfall image with [a new one](https://drive.google.com/file/d/1DKCHWCpuEUAM1K2SpYCTOLeVwNV4MHM5/view?usp=drive_link)

### World Sales
- [x] Update the two images of world sales with a table
[1 image to add](https://drive.google.com/file/d/1UORd3_-0V4konHcdJSWLNSctyjv65M_R/view?usp=drive_link)

[2 image to add](https://drive.google.com/file/d/10Bv8IPkL_yTXmogz-yUZyUvJj1i7DrJq/view?usp=drive_link)

### Film Amortization (WIP)
- [x] Add the image of [film amortization default state ](https://drive.google.com/file/d/12myf_zUTF1QLDSDHD0P0GrimmxeGzOQ1/view?usp=drive_link)

(and the other images will come when validate all the numbers)

**Comment by phpgeekfr** [comment]
@2amarkina you can find the updated version here https://waterfall-blockframes-demo-1.web.app

**Comment by 2amarkina** [comment]
### More demo updates: 

**General**
Everywhere when we "go out" to the other "creation/form" layout (Statements editing, Waterfall Management) we need to make our "page-image" easier visible. 

- [ ] Add to all the "creation / form" layout width:80%
<img width="290" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEpUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cb07291634bd4bf8db72c96efce7eae9399c590/Capture%20d%E2%80%99e%CC%81cran%202024-02-13%20a%CC%80%2014.29.08.png" alt="Capture d’écran 2024-02-13 à 14.29.08.png" />

- [ ] Center the image
<img width="1384" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFZUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b28a73ce69e38e61d08a22be4c1ad0a97eee9ac1/Capture%20d%E2%80%99e%CC%81cran%202024-02-13%20a%CC%80%2014.30.32.png" alt="Capture d’écran 2024-02-13 à 14.30.32.png" />


**Statements**
- [ ] Replace the navigation chips for the Main Distributor 
<img width="1418" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1JUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2b9c5ec4bdc02b2d89e89ce22941fa589b40b2d/navigation_main_distrib.svg" alt="navigation_main_distrib.svg" />

- [ ] Replace the navigation chips for outgoing
<img width="1418" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2hUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e2f602d0070ccbfb2eecf5eb54fbda8be869895/navigation_outgoing.svg" alt="navigation_outgoing.svg" />

- [ ] Replace the List of outgoing statements
<img width="1440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2xUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccc335fa51087d3104657fc653f346f574d3e615/Statements_Coprod.svg" alt="Statements_Coprod.svg" />

- [ ] After the last Distribution Statement screen (see screenshot) add the very last click that directs to the Distributors Statement List (not repeats the flow)
<img width="336" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDFUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8594dc5a84f823fd1d7179c5207c379b5f5f530c/last_screen_distrib.png" alt="last_screen_distrib.png" />

- [ ] After the Outgoing Statement, we need to add more screens to show the sharing process
<img width="815" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelZUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3694c8f10143bab6416f51215e8a2323e915b83/Sharing_Outgoing_1.svg" alt="Sharing_Outgoing_1.svg" />

- [ ] After the Sharing modal, we need to add a click and it should lead to the Outgoing Statements list. 

**Waterfall**
- [ ] Add the second screen to the Waterfall visualisation 
<img width="732" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUJUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c6a89471a660f5bc068c5566bd8a0977b54eee0/Waterfall_2.svg" alt="Waterfall_2.svg" />

- [ ] After the "Waterfall creation" flow, the last click should lead to the Waterfall visualisation screen. 

**Film Amortization**
- [ ] As discussed before, we need to add the new tab "Film Amortization". 

In this tab we should see the following flow:
- [ ] This image goes as default inside the tab <img width="1395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80586a58861f2ad201726198c34c7f9c34a3e787/Amortissement_default.svg" alt="Amortissement_default.svg" />

- [ ] Then we "go out" to the "creation/form" flow. 
<img width="687" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk5UQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40271fab7fc6dc9381762fc1b7f56ea165791b86/Film%20Amortization_1.svg" alt="Film Amortization_1.svg" />

- [ ] <img width="687" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlJUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--599f4d79c0a65f3c3208114fc543bd5d6daadc0b/Film%20Amortization_2.svg" alt="Film Amortization_2.svg" />

- [ ] <img width="687" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlZUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--713a6e2dbf7e2aaffb2eb175da3fd6ef3a08161d/Film%20Amortization_3.svg" alt="Film Amortization_3.svg" />

- [ ] <img width="687" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmRUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46cfbbb96117b77b8728ce0682403bd175e48fa2/Film%20Amortization_4.svg" alt="Film Amortization_4.svg" />

- [ ] <img width="575" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmhUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1be1d6d1bfdd28c4eaa961ed00e4657b6e4710eb/Film%20Amortization_5.svg" alt="Film Amortization_5.svg" />

- [ ] <img width="1395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmxUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--446d83dfc58fd652f88b53deb2e98f4c19ac7e1d/Film%20Amortization_Last.svg" alt="Film Amortization_Last.svg" />

**Comment by phpgeekfr** [comment]
@2amarkina `After the last Distribution Statement screen (see screenshot) add the very last click that directs to the Distributors Statement List (not repeats the flow)` The attached screenshot is not the last one.

@2amarkina `After the Sharing modal, we need to add a click and it should lead to the Outgoing Statements list.` => It will redirect to default view of statement list : distributor statements

- Add to all the "creation / form" layout width:80% 
- Center the image

I'm not sure to understand, lets check together

**Comment by 2amarkina** [comment]
New updates: 

**All the distributor Statements (creation/form layout)**
- [ ] Add the "false back" image just above the statement. 
<img width="1440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmhZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71b72abbccb1e32814cbf0577802a171fbd26ab8/faux%20back.svg" alt="faux back.svg" />

- [ ] The click on this image should lead back to the distrib statements list. 
- [ ] Check together what it looks like and adapt the size of image is needed. 

**Waterfall**
- [ ] Replace the second image of the waterfall by new one
<img width="732" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0JZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ee3e3f09719f0dc499c1662d18b51456a20abf4/Waterfall_2.svg" alt="Waterfall_2.svg" />

**Sharing / Outgoing**
- [ ] Replace the sharing screen of the outgoing statement by this one
<img width="815" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0pZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6fd70525903558b3eff5fad99532b8cf5dcb449b/Sharing_Outgoing_1.svg" alt="Sharing_Outgoing_1.svg" />

**Amortization**
- [ ] Replace the default image (layout with tabs) by this one
<img width="1395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1JZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c31b8daae888203af3eff3359790f70a58facfc0/List_Amortissement.svg" alt="List_Amortissement.svg" />

- [ ] Also add the "false" background to the creation/form layout, as the flow is long. Check together if ok. SHould lead to the amortization list.
<img width="1440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1ZZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bfaa644319ed5d0a2c260fa284abb545151b3840/faux%20back.svg" alt="faux back.svg" />

- [ ] Replace the last step of amortization creation by this one
<img width="1395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2hZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0298e12e210f68bd2406d530c099e5b76e104941/Film%20Amortization_Last.svg" alt="Film Amortization_Last.svg" />
