### ISSUE TITLE
App Review - Left to do bis

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9675]
Created from #9657 with only things left to do to make it more clear.

## General UI

 - [ ]  ☕ In different places we display the page before data is loaded so it creates a little spike. I guess that's not the time but would be great to have a loader before data is loaded and then display the page
 (example on statement form)
<img width="640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelNDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73e477e4cdf7c3eb40360cead231edd07f4d5d99/Dec-22-2023%2014-31-40.gif" alt="Dec-22-2023 14-31-40.gif" />

- [ ] add terms & conditions  ( https://github.com/blockframes/blockframes/pull/9262#discussion_r1189576540 ) & DATA PRIVACY POLICY

## Waterfall Graph
- [ ] Group collision on Gaspard at the wedding ([graph](https://waterfall-blockframes-bruce.web.app/c/o/dashboard/title/UOAxqGsWmON1YhWO88H4/waterfall) on Bruce's env or [excels](https://drive.google.com/drive/u/2/folders/1qj6-fiymi2nBP_0C-sYfn4byaSzmVAFb) for import)
<img width="1493" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1NDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7dcf5182133db74754b4a05eaceb7714bdcf13d8/image.png" alt="image.png" />

### Graph form (right side)
- [x] "Receipt Sources" select:
- Rename it `Parent Revenue Element(s)`
- Label "Source Name" becomes `Parent Name(s)`
- Hint: `Choose parent revenue elements from which this Receipt Share draw funds. You can add as many parents as you want.`
- [ ] If a user clicks away from the Graph's right Form and there is no saved RS, the modal should show "before we begin" text. 
- [ ] If a user clicks away from the Graph's right form and there are n+1 RS, then the modal should show the RS list. 
- [x] If we change the name of the Receipt Share Name, the change should be automatically applied in the conditions. 
- [ ] If possible during the creation of the waterfall, it would be better to add the name of the right holder in brackets. It's needed to distinguish the Reciept Shares with the same names
<img width="1433" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDBrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4f71999c603f3d694a323c95848eae3d4faa693/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-02-02%20%D0%B2%2015.59.14.png" alt="Снимок экрана 2024-02-02 в 15.59.14.png" />
- [ ] Add more space below the CTA "Group Right Share" when there are pool chips (about 20px)<img width="676" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejVBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f18c436bf5d54d293dec29e64b4e2b5b1b45280/RS%20padding.png" alt="RS padding.png" />

### Graph form (left side)
- [x] see issue #9647 for the trackpad gestures
- [x] ☕️ add some space inside on the left the waterfall Scheme Surface and more space between "Please provide the condition" and the scheme itself
<img width="1571" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkFQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9b0fa7d1ef9932cbe14c7dca271373aee5ed699/Capture%20d%E2%80%99e%CC%81cran%202024-01-30%20a%CC%80%2014.50.23.png" alt="Capture d’écran 2024-01-30 à 14.50.23.png" />

## Contract form
- [ ] ☕ Sticky header on the form (for this component wherever it is)

### Statement form
**Receipt form**
~~- [ ] Don't know if there is a logical reason but receipts are by default saved on an empty line. Instead could we have the form open without the table (see below screenshots) and ofc best would be to have the [Table + form component ](https://github.com/blockframes/blockframes/issues/9587)~~ => **#9587**

~~- [ ] Not completely sure of this solution ( @2amarkina please confirm or propose something else) but I think the "Save Receipt" button is not visible enough > change it for a blue button ? If so, maybe we can move the buttons Continue / Saved & Come back later to top right of the page?~~ => **#9587**

**Expense form**
~~- [ ] Remove the * on "Nature" input (renamed Expenses name)~~ => **I don't know what to do with this one, as this field is used in the summary view.**

**Comment by 2amarkina** [comment]
! important

- [ ] When adding the receipt share the contract field has not appeared, and block the further building of waterfall
<img width="966" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU5ZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed186e430d419236c26b61cc4c028e4718c48df6/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-02-14%20%D0%B2%2012.14.12.png" alt="Снимок экрана 2024-02-14 в 12.14.12.png" />

**Comment by 2amarkina** [comment]
- [ ] the certify icon should be the same color as the others. 
- [ ] When certification requested, the icon should become disabled and to distinguish it from others, we need to put 0.5 opacity ---> `rgba(102,107,129, 0.5)`

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE5aQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--088da6cdc0769a404a927cff6e75e6c195e87895/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-02-14%20%D0%B2%2014.47.02.png" alt="Снимок экрана 2024-02-14 в 14.47.02.png" />

**Comment by 2amarkina** [comment]
- [ ] When I switch between the Receipt Shares and I'm in the conditions tab, we need to change the steps accordingly as we already do for the "receipt Share Type" and "Reciept Share Name" <img width="1195" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTlaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc0e026ed218b6c16241f924156ce82acf44b3bb/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-02-14%20%D0%B2%2015.04.41.png" alt="Снимок экрана 2024-02-14 в 15.04.41.png" />

**Comment by 2amarkina** [comment]
Closed as all remaining issues have bees transformed into different issues
