### ISSUE TITLE
Change Text / Hide Mail

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9684]
### Context:

When user wants to sign up to our applications, we give the possibility to show or to hide the email that will be shown on the Marketplace side of the apps. Nowadays we are using the Archipel name, but it should something more general for the Media Financiers and for the Blockframes this part has no sense. 

<img width="1774" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2VTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c96c0c352b9a8d4b8f35b7ea31b05f97eea405c2/Capture%20d%E2%80%99e%CC%81cran%202024-02-27%20a%CC%80%2016.11.34.png" alt="Capture d’écran 2024-02-27 à 16.11.34.png" />

### To Do:

- [x] Change the text to make it more general for the Media Financiers (+ @2amarkina)
- [x] Hide this part for Blockframes

**Comment by phpgeekfr** [comment]
@2amarkina hide this part on blockframes app is done, if you want me to do the first checkbox for this release, please provide the text

**Comment by 2amarkina** [comment]
> @2amarkina hide this part on blockframes app is done, if you want me to do the first checkbox for this release, please provide the text

We can go with just hiding for these release.

**Comment by 2amarkina** [comment]
Finally, for Media Financiers the text might be changed just for "Your email address will be visible to all **Media Financiers** users unless you decide to hide it." The part about the event might be removed as has no sense in this app.
