### ISSUE TITLE
i18n 

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#969]
We should think about if we want to have a translation. EN/FR/DE etc...
Because of the territories we maybe want to translate into other languages, ISO standard. Only special words or the whole (d)app?

https://angular.io/guide/i18n

**Comment by GrandSchtroumpf** [comment]
There are two options : 
- compiled : [Official Angular i18n](https://angular.io/guide/i18n) that create one app / language (the creator is in Lyon)
- interpreted : [Transloco](https://angular.io/guide/i18n) Netbasal's library for i18n that enables change of languages on the same app.

The first option if more optimized and the second is more dynamic.

**Comment by Jackseed** [comment]
This will be definitely needed and we should have a try to implement it in French as we can easily make a translation of an app. 
Still have to make a decision on the two options above.

**Comment by GrandSchtroumpf** [comment]
Let's use Transloco then

**Comment by Jackseed** [comment]
Let's wait for the UX plan to know how much we need geolocalization - since i18n should be better on this issue but much heavier to implement

**Comment by Jackseed** [comment]
related to #1260

**Comment by Jackseed** [comment]
Question answered & documented, will be implement in near future
