### ISSUE TITLE
Internationalization FR-ES

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9699]
### Context :
For the moment the app exists in English. 
Nevertheless, our goal client is a French producer (meeting them is the focus of Cannes 204), so we need to have the French version of the app before Cannes.

**Comment by phpgeekfr** [comment]
check `TODO #9699` in code

**Comment by phpgeekfr** [comment]
as for #9642, internationalization has been set up on `waterfall` app only.
see `apps/waterfall/waterfall/src/main.ts`.

- every html tag with text that needs translation will need `i18n` property (ex: `<h1 i18n>My Movies</h1>`)
- locale file example that need to be translated : 
https://github.com/blockframes/blockframes/blob/91c2f007cb44b2da9debf2c49f11f75738cb1cd3/apps/waterfall/waterfall/src/assets/messages.fr.json

**Comment by phpgeekfr** [comment]
For the next steps:
- [ ] add an attribute `preferedLanguage` on user object in db & also store it on localstorage.
- [ ] update profile page to allow user to switch between languages (en, fr) ( will need a refresh)
- [ ] use saved attribute `preferedLanguage` to add a new variable to sendgrid templates

**Comment by 2amarkina** [comment]
The working document on the texts can be found here https://docs.google.com/spreadsheets/d/1al3B7G1FlRry5yUzlVi4Qucz7lki4gP2qQgrysH5zFY/edit#gid=0

**Comment by phpgeekfr** [comment]
- [ ] need to find a solution for static-models (`libs/model/src/lib/static/static-model.ts` does not accept `$localize`)

**Comment by phpgeekfr** [comment]
- [ ] check how to translate PDF statements

**Comment by phpgeekfr** [comment]
- [ ] add translation for country, languages, medias etc..

**Comment by 2amarkina** [comment]
- [ ] check the lines that do not correspond exactly (en/fr) because of the articles (e.g. l'invitations / les invitations) 
Lignes détectées au présent : 

- 112
- 113

**Comment by phpgeekfr** [comment]
- [ ] create fr sendgrid templates and add them in code

**Comment by 2amarkina** [comment]
- [ ] 5072230974607840423 / 2411717922174348092 add variable to change from "Achipel products to Blockframes products

**Comment by phpgeekfr** [comment]
> Regarding Sendgrid, what about sending language preference so we add a if statement to handle it inside one and only template?
I'm afraid to have too many templates to handle if we start duplicate already existing ones

yes, as for `firstName` , this should be accessible in emails via `preferredLanguage.language`

**Comment by Jackseed** [comment]
- [ ] Check places where we mix static model + plain text like here within contract form header. It should be "Contrat financier"
<img width="1302" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemJKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18c80095cdd6cfb5b31cbfb72ff1ecdf74c11199/image.png" alt="image.png" />

**Comment by phpgeekfr** [comment]
- [ ] invitation statuses: should be `a accepté votre ...`
<img width="462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGpjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--422f4d2aef7860013492bd8a6e1cd75238d96e98/image.png" alt="image.png" />

**Comment by 2amarkina** [comment]
## Translation & Internationalization
#### Some places where the translation must be updated

- [ ] change to "ajouter des frais"

<img width="1783" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkVqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b67ba1a3c0f7f7334f24c07ed24c118a680b1ec5/Capture%20d%E2%80%99e%CC%81cran%202024-05-30%20a%CC%80%2016.03.34.png" alt="Capture d’écran 2024-05-30 à 16.03.34.png" />

**Comment by 2amarkina** [comment]
Also, for the internationalization part we will need to add quickly the Spanish version. 
The aim is to have a Spanish version to show to freeway colleagues for their review.

So, the Spanish version should be implemented to the separated branch, so while waiting the review we could work on other subjects.

**Comment by 2amarkina** [comment]
[Here is the JSON in Spanish to use](https://docs.google.com/document/d/1ZJeK2erPuliLDsI8cGXTRBw4WuM-ZKDPXfjPsfJoiyw/edit)

**Comment by phpgeekfr** [comment]
- [ ] translate this page into Spanish http://localhost:4200/c/o/dashboard/security
<img width="1195" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU5TQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--639a802369e1d569118f5ca174f9f43c706cde8e/image.png" alt="image.png" />

**Comment by 2amarkina** [comment]
fyi - the first version of spanish version is released

closing this issue for cleaning reasons and [the new one is created ](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/issues/gh/blockframes/blockframes/9870)
