### ISSUE TITLE
🟠 Important improvements for the demo 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9704]
### Context 
Important improvements are needed to ensure the smooth functioning of the application. The primary aim here is to provide our initial users with the easiest experience of using the app. 

## Fluid Statements

- [x] 🧩 Navigation chips update (Distinguish the incoming and outgoing statements with color or change the toolbar). @Jackseed, we couls go for the easiest version with the color as for the demo (as Yannick proposed) and then we'll upgrade it to the better version ? 

- [x] 🧩 (from Jackseed) UX detail: could we select by default a contract when creating a first outgoing statement? (80% of the time there is only 1 contract anyway)
<img width="1746" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3BoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20ce0234a0887f98cb90988ecbdeae1fce84611e/image.png" alt="image.png" />

- [x] 🧩 ❗️ When we are inside the statement, and there were no reported amounts before, then we need to start with the default state with the empty fields and not with the line (component problem and solution before implementing the table + form).
<img width="1531" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDNUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c7a57dbf1f82ef9a08a38588097bc00cd04213b/Capture%20d%E2%80%99e%CC%81cran%202024-03-12%20a%CC%80%2016.17.52.png" alt="Capture d’écran 2024-03-12 à 16.17.52.png" />

- [x]  ❗️(from Jackseed) Expense details should list all the expenses to date not just the one reported on that statement
**on distributor statements**:
- one table per expense type with max 2 lines (capped/not capped)   with prior current cumulative
- one table "history" that list all expenses

**on outgoing statements** (this table is hidden on PDF in some cases cf #9677 calculation details ):
- one table per expense type per distributor with max 2 lines (capped/not capped)   with prior current cumulative
- one table "history" per distrib  that list all expenses + possibility to edit current expenses 
<img width="1367" alt="image" src="https://github.com/blockframes/blockframes/assets/14964443/a886744b-ef88-4ede-8676-e6660b8f4935">

- [x] ❗️ /!\ (from Jackseed) Logic issue: I declared both capped (above the cap) and uncapped expenses but uncapped expenses haven't been recouped. 
[Here](https://app.blockframes.io/c/o/dashboard/title/OWpR2aAjmvo57Nukp8mp/statement/kino_1) expenses recoupment should have been:
20k (capped expenses) + 194€ (uncapped expense) = 20 194€ (recouped)

<img width="1551" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenRpQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e1beffd9a0e3cd2d38605343cc8b36eb3a963de0/image.png" alt="image.png" />

- [x] ❗️❗️ (from Jackseed) I'm doing a direct sales statement and that feels strange: 0 on net revenue though no commission (so it should be 100% of the incomes in net revenue) + the other part which is more of an outgoing statement thing but here because this nodes belongs to the prod. 
I think we should review the logic here to get something closer to a classic distribution statement
EDIT: new logic for direct sales - show only rights that are type `Expenses` or `Commission` and add a warning sentence on the statement header (below "Contract:") with a warning icon:
⚠️ Warning: Direct sales statements displays only producer's rights that have a type "Expenses" or "Commission" for the Net receipts calculation.
Also: 
- add a "Total due" blue line that does net receipts - commission nodes - expenses nodes
- Remove the nodes that are not related to the the source declared (even if they are commission/expenses)

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL05oQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d6e13d8e85533b3c57443aeed595f0d0c255a12/image.png" alt="image.png" />

- [x] 🧩  If possible during the creation of the waterfall, we should add the name of the right holder in brackets. It's needed to distinguish the Receipt Shares with the same names.
<img width="875" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1BUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85938c3b8482d8ead4376d9793c0283c9ac0d95f/Capture%20d%E2%80%99e%CC%81cran%202024-03-12%20a%CC%80%2016.08.14.png" alt="Capture d’écran 2024-03-12 à 16.08.14.png" />

- [x] 🧩 If we change the name of the Receipt Share Name, the change should be automatically applied in the conditions.
- [x] 🧩 When I switch between the Receipt Shares and I'm in the conditions tab, we need to change the steps accordingly as we already do for the "receipt Share Type" and "Receipt Share Name".

## Fluid Use of Published Waterfall
- [x] 🧩 Icon near the statement, should be clickable and lead to the concerned statement. 
- [x] 🧩 We need to differentiate the Statements that were issued on the same date. Let's apply this format: Org Name - 12/31/2024.
- [x] 🎨 When waterfall is published, but is still editable (no first statement reported) and we are on the Waterfall tab, then we should not show the pluses on click. 

## Fluid Contracts
- [x] 🧩 Prevent user to save changes when go from one contract to the other.

## Good Perception 
🎨 Placeholders Design : 
- [x] Dashboard graphs ; 
- [x] World Sales ; 
- [x] Pools. 

- [ ] 🎨 (from Jackseed) The 2 cards take the same space but it makes a lot of empty space on the left side graph. Could we make it 100% or the card width?

<img width="1419" alt="image" src="https://github.com/blockframes/blockframes/assets/14964443/92227f92-d76c-4601-bf83-cf114959fc52">

- [x] 🎨 Add more space below the CTA "Group Right Share" when there are pool navigation chips (about 20px)
<img width="676" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ROQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c20a46f312bd124b1d1344bc682530cc49d0f6d/RS%20padding.png" alt="RS padding.png" />

## Right Holders Tab
- [x] 🧩 After the invitation has bees sent, then we list the pending users in the dedicated table. it would be better to precise the fake Organization name (add one more column), not to forget the email associated.

**Comment by Jackseed** [comment]
> * [ ]  🧩 Navigation chips update (Distinguish the incoming and outgoing statements with color or change the toolbar). @Jackseed, we couls go for the easiest version with the color as for the demo (as Yannick proposed) and then we'll upgrade it to the better version ?
Alright

>  🧩 ❗️ When we are inside the statement, and there were no reported amounts before, then we need to start with the default state with the empty fields and not with the line (component problem and solution before implementing the table + form).
I would also add Aurore's feedback: when there is data already filled in this table don't open the form by default but only the table view

**Comment by 2amarkina** [comment]
- [ ] Indeed, the trackpad gestures are not the same as in figma. Need to reserse the logic

**Comment by 2amarkina** [comment]
- [ ] There should be "Still be recouped", right?
<img width="1385" alt="image" src="https://github.com/blockframes/blockframes/assets/14964443/27e467c5-b989-4622-a24f-aeaa6a557b32">

**Comment by Jackseed** [comment]
> * [ ]  There should be "Still be recouped", right?
> 
> <img alt="image" width="1385" src="https://private-user-images.githubusercontent.com/14964443/305093914-27e467c5-b989-4622-a24f-aeaa6a557b32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDUxNjMsIm5iZiI6MTcxMDQwNDg2MywicGF0aCI6Ii8xNDk2NDQ0My8zMDUwOTM5MTQtMjdlNDY3YzUtYjk4OS00NjIyLWEyNGYtYWVhYTZhNTU3YjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA4Mjc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZDIyOGE0ZjkyZjk4YzNhMzRlYjk5NjIxMWFjYWJhYWFjZGU1MzY3MjkwNWIxOTBmNDc0ZDE1Yzc3OWRhZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.719WgGbTOLhM7Z83TFkv3-0_a2C2w_HWqqpgW5-5rSw">

Indeed, if UFO MG is well set up

**Comment by 2amarkina** [comment]
## Dashboard

### Placeholders images and texts : 
General text to add inside each section : There is no statistics available yet.  
See visualisation example below : 

<img width="752" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi9lQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fbd9458ff5887d7ccd4b21f2b5dcc43e234e52cf/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-03-14%20%D0%B2%2013.31.01.png" alt="Снимок экрана 2024-03-14 в 13.31.01.png" />



**Figma links to find the images:**
- [ ] [Right Holders revenue split ](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?type=design&node-id=312-12669&mode=design&t=nXAkvD7HqMvzBlyS-4)
- [ ] [Net Revenue over time ](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?type=design&node-id=312-15973&mode=design&t=nXAkvD7HqMvzBlyS-4)
- [ ] [Right Holders ROI](https://www.figma.com/file/aNbs0XSJBqIvKrffJSzViH/Dashboard?type=design&node-id=1612-12374&mode=design&t=nXAkvD7HqMvzBlyS-4)

**Comment by phpgeekfr** [comment]
> The 2 cards take the same space but it makes a lot of empty space on the left side graph. Could we make it 100% or the card width?

We cannot know the height of the graph before rendering it. And height will change depending of the rightholder count on the waterfall state

**Comment by Jackseed** [comment]
Ok, I can't think of a trick to hide that.. @2amarkina mb?
