### ISSUE TITLE
🟢 Not urgent app improvements for the demo

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9705]
## General
- [ ] ☕️ In different places we display the page before data is loaded so it creates a little spike. I guess that's not the time but would be great to have a loader before data is loaded and then display the page (example on statement form)
<img width="640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelNDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73e477e4cdf7c3eb40360cead231edd07f4d5d99/Dec-22-2023%2014-31-40.gif" alt="Dec-22-2023 14-31-40.gif" />

#### 🧩 Usability
- [x] **DESIGN FIRST.** Sticky header on the form (for this component wherever it is) or toolbar. (N.B. I love the idea of the fixed toolbar + add the new buttons of creation of sources and RS)
- [ ] Give users possibility to Delete contracts (?) 
- [ ] (from Jackseed) UX proposition (cc @2amarkina) what about downloading automatically the statement pdf once reported? It feels like we could do more about it
\ + mb add an icon aside the Statement title to show it's reported? like the blue mark on X or something like that

#### 🎨 Design
- [ ] The CTAs with images -> change the texts or the size of the button to enter ; 
- [ ] Add the link + bold to “Contact our team” text and a link to Intercom ; 
<img width="1292" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1BNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04d2245453885f2cef595f36c62be3ccdaf970be/CTA%20and%20image.png" alt="CTA and image.png" />

#### Activated Waterfall 
- [ ] 🎨  **DESIGN FIRST.** See more bright way to highlight the source. 
- [ ] 🧩 When we filter Right Holders by activity (breakdown by Right holder), the dropdown should contain only the Roles should participate in the Waterfall. 
- [ ] 🧩 Think about an icon for clearing filters. 

## General Statements
- [ ] 🧩 (from Jackseed) Add statement button change location if the distributor as multiple contracts. This button should be always at the same place so maybe use the multiple contracts position all the time
<img width="1665" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWRnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3fc7abaffc11c336b747ca21d2754f31ff2bf02/image.png" alt="image.png" />

- [ ] 🧩 Keep the “-” if the amount needs to be paid, but hasn’t been declared yet and change to “N/A” when there is no action to be done on the users’ side and there is no amount due or to be declared (see together with @Jackseed, as different opinions).
- [ ] 🧩 See if we can hide the columns for the Direct Sales as they are different from the other (Sales, Distrib, Outgoing).
- [ ] 🎨 **DESIGN FIRST**: See how we could differentiate the incoming and outgoing statements. 

## Direct Sales
- [ ] 🎨  **DESIGN FIRST**: Rework the visualisation of the statement details for the sharing and declaration (1 column).

**Comment by Jackseed** [comment]
> #### Dashboard
> * [ ]  📑 Dashboard: add tooltip for "Total Film Revenue" ->
>   The overall income a movie earns from all sources.
> * [ ]  📑 Dashboard: add tooltip for "My Total Cash Flow" -> Refers to the sum of all incoming and outgoing money, reflecting your overall financial movement.
> * [ ]  📑 Dashboard: add tooltip for "My Total Revenue" -> The overall income earned from all sources.
> * [ ]  📑 If no data,  in the first row, replace “-” by No revenue declared yet

I think all text changes should be put in red otherwise we will never change it though it's really quick to be done

**Comment by 2amarkina** [comment]
- [ ] The 2 cards take the same space but it makes a lot of empty space on the left side graph. Could we make it 100% or the card width?

<img width="1419" alt="image" src="https://github.com/blockframes/blockframes/assets/14964443/92227f92-d76c-4601-bf83-cf114959fc52">

**Comment by 2amarkina** [comment]
- [ ] (from Jackseed) Too much space between distributor select and table

<img width="1875" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVpnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5611664a7aed7ac665111ed92a789ef161a645d/image.png" alt="image.png" />

- [ ] (from Jackseed) Add statement button change location if the distributor as multiple contracts. This button should be always at the same place so maybe use the multiple contracts position all the time
<img width="1665" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWRnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3fc7abaffc11c336b747ca21d2754f31ff2bf02/image.png" alt="image.png" />

**Comment by 2amarkina** [comment]
The non-urgent "green" tasks will be added to the changes per scenario.
