### ISSUE TITLE
Changelog release 5.0.5

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9742]
Issues :
- Important improvements for the demo #9704
- Statements Improvements #9736

Change log / To test :
- PDF statements: 
  - [x] text changes, added "Total Participation Due" for direct sales. 
  - [x] added expenses details & history (all kind of statements)
  - [x] outgoing statement will not display duplicated info if already present in attached distrib/direct sales statements 
- [x] fixed backend bug when deleting statement with existing duplicates on other version
- general debug on statements:
  - [x] display "Participation" blue line on direct sales (net receipt - (comm & expenses)
  - [x] only comm & expense rights are displayed on direct sales (with a warning on header)
  - [x] fixed various bug with expense/income changes on version
  - [x] on statement list, moved button "add statement" the the same place as "add statement (contract id)"
  - [x] when on a standalone version with no statements yet, added possibility to create a direct sales directly
  - [x] added more data about expenses (tables history & details)
  - [x] fixed form to add incomes & expenses
  - [x] fixed "real time expenses" count when adding expenses
- Graph
  - [x] fixed horizontal scroll 
  - [x] fixed condition "sentence" that was displayed contract id instead of name
  - [x] fixed vertical groups (steps) creation & deletion when vGroup was in a horizontal group (hGroup)
  - [x] added "revenue" on steps cards
  - [x] fixed overall vertical group revenue display

**Comment by phpgeekfr** [comment]
03-04-2024 updates:
- updated statement URL in email & notif when statement is rejected to redirect directly to `edit`.
- "see contract" button on statement list is hidden when user cannot read it. "create statement" button is also hidden
- updated default new statement dates
- on arbitrary change modal, changed text "gross receipts" to "Amount"

**Comment by 2amarkina** [comment]
Not sure to correctly understand this point `"on statement list, moved button "add statement" the the same place as "add statement (contract id)"" `
