### ISSUE TITLE
 Important bugs and updates

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9749]
#### User can CRUD Receipt Shares 

- [x] !!! 🔴🐞 When we create several Vertical Groups and then we want to attach them to one particular source, then they are automatically merged in one RS group instead of remain as they are
<img width="1588" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGt2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--178b34357dfd7eaada6c58191fbeeb11b58f281b/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-04-03%20%D0%B2%2013.08.17.png" alt="Снимок экрана 2024-04-03 в 13.08.17.png" />

- [x] 🔴🐞 (from Jackseed) I can't change the % of a vertical step, though contract is well set
<img width="1737" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTh6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d92e4adb6a7fdb51e2166e2376f32fa2115cf0e1/image.png" alt="image.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk16QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94b45f502f466a00a81d953e041e6ad1f49d1453/image.png" alt="image.png" />

- [x] 🟠 🧩 (from Jackseed) 115% written on the excel import but 114,9999999% on the app
<img width="1350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU16QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8a5d577e55c45de3bbc8b81de2e3383aa2ca71f/image.png" alt="image.png" />

- [x] 🟠 🧩 [ Release 5.0.7] Add a possibility to modify / delete the waterfall after publication and when if there are statements coming. For example, if the RS has been impacted user can't modify it, but can modify/delete the others (see together the possibilities).
- [x] 🟠 🐞 (from user) Unable to enter 'Producer' as the 'licensor' under 'other' category

**Comment by phpgeekfr** [comment]
> (from Jackseed) I can't change the % of a vertical step, though contract is well set
you have multiple org with same name : 
<img width="596" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG81QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85eb37e1c5fc906df84424e38008e46e305f504d/image.png" alt="image.png" />

**Comment by 2amarkina** [comment]
- [ ] 🟠 remove % from the conditions when choosing the expenses

**Comment by 2amarkina** [comment]
- [ ] Revenue Shares bug (be able to show all the revenue shares, even if they are in a list)
