### ISSUE TITLE
Film Amortization. Part 1

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9753]
### Context:
The Producer needs to be able to calculate the Film Amortization. It is needed to see if the film was successful or not.

The calculation can differ according to the calculation method, so we need to be able to cover all possible cases.

[Detailed documentation about Amortization](https://www.notion.so/cascade8/Film-amortization-69fce6eb70a84c2990be83cc17145f8d)

In this part we will concentrate on the creation of the tab, layout for the empty state, preparation for the layout of the form. 

### To Do: 
- [x] Add tab Film Amortization after the Waterfall tab
- [x] Prepare the empty state of the page : 
Description text : Here you can define your own calculation method for film amortization. You can have several different calculation methods for different right holders.
CTA : Calculate Film Amortization
[Find the image for the CTA here](https://www.figma.com/file/0NDJn66qe0SWpjzF1Xk0s3/Film-Amortization?type=design&node-id=179-6221&mode=design&t=PFY14FEEfBT8IWUi-4)

See the mock-up:
<img width="1253" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmhHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cdb6ce716c11b0f7cb292f48d998d0198f988e01/template.png" alt="template.png" />

Prepare the layout of the Film Amortization form :
- [x] When user clicks on CTA "Calculate Film Amortization" s/he is redirected to the form
- [x] Add title : Film Amortization and the Movie name below like we do for the Statements
- [x] Add Block with title : "Organizations" ; paragraph : The amortization of the film cost will be added to their reports. Field "Choose Contracts concerned" (may choose several contracts) ; Free text field "Give name to Calculation".
- [x] Add Stepper : 1. Film Cost / 2. Financing / 3. Net Revenue Producer Shares 
- [x] User should be able like for the Statements come back and continue.
- [x] User should be able to Save and come back later. 

Here is the mockup of the layout 
<img width="632" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2xHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9aa18963c7b4224f93c190a01881b0f3bed7f1ae/Film%20Amortization.png" alt="Film Amortization.png" />

_**!! For the moment we do not start working on the Film Cost table. Let's do it on the next step.**_ 

- [x] If user has been working on the calculation method and still have it in draft, then the calculation method appears on the page. 
<img width="630" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d3b172b3492954851049e1aad87198950ab7c49/Capture%20d%E2%80%99e%CC%81cran%202024-04-09%20a%CC%80%2016.18.18.png" alt="Capture d’écran 2024-04-09 à 16.18.18.png" />

**Comment by phpgeekfr** [comment]
- [ ] check `TODO #9753` in code
