### ISSUE TITLE
Film Amortization 2 (Stepper details)

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9770]
**Context:** 
Now we enter inside the calculation the Film Amortization. 
For the moment we will stay with the simplified version and will make it more complex later. 

Reminder of the links you may need: 
[Notion documentation](https://www.notion.so/cascade8/Film-amortization-69fce6eb70a84c2990be83cc17145f8d)
[Figma](https://www.figma.com/file/0NDJn66qe0SWpjzF1Xk0s3/Film-Amortization?type=design&node-id=173-5556&mode=design&t=wBByde3fwzSHc9A3-0)

### TO DOs
**The first step is the film cost.** 
For the first version of Amortization we will just keep with one field : Effective Film Cost (Total Amount)

- [x] Integrate the 1st step of the Film Cost 
Subheading: Please provide us with the following information so we can calculate the film amortization. 

<img width="810" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFoyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec6dae0bd33aba751957b8bc8940b7005843333b/Film%20Amortization_Simplified.png" alt="Film Amortization_Simplified.png" />

**The second step is the Financing.** 
The same as for the first step, we need to simplify the process for the first version. 
So we'll use only one total field "Total Financing Amount"

- [x] Integrate the 2nd step of the Financing
Subheading: Please take into account all the financing sources that need to be considered when calculating the amortization of the film's costs.
<img width="810" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHQyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f5dfe63fd3fb1d1055b3c7ba129fcab25a658d0/Financing_Film%20Amortization_Simple.png" alt="Financing_Film Amortization_Simple.png" />

**The third step is the Net Revenue Producer Shares.** 
Here we need to let the users define what are the RNPP for them. 
We can use the same component that we are using for the pools creation

- [x] Integrate the 3rd step of the RNPP
Title: Producer's Net Participation Definition 
Subheading: Please choose the receipts that will be summed to amortized the film cost. You can modify them in the Waterfall Management section. 

_Waterfall Management_  should be a link and open the new tab with Waterfall Builder. 

<img width="544" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFYzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36b121a9b62d50f533ecb4c3cece1687efb2404d/RNPP_Film%20Amortization%20%282%29.png" alt="RNPP_Film Amortization (2).png" />

**Summary Page**
For the moment the Summary page is really basic, but it prepares the ground for the future when we'll need to use the recap tables for the. film cost and financing. 

CTA : Apply Calculation Method

- [x] Integrate the Summary Page
<img width="776" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVYzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc4951c56c7bf379a05e07fd27c8b3346c974ffa/Summary_Film%20Amortization.png" alt="Summary_Film Amortization.png" />

**Comment by phpgeekfr** [comment]
- [ ] check `TODO #9753` in code
