### ISSUE TITLE
Film Amortization (Step 3)

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9771]
### Context
Here is the result of the Calculation Method set up previously 

That means that inside the Statements (Outgoing statements concerned. For example for the authors it's the rule now in France to show this part) there should be the information about the film amortization. 

### TO DOs: 
- [x] Add to the concerned Statements (organizations impacted are defined by Producer inside the Calc Method Form) the information about how much money is left for the film to be amortized<img width="808" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTUzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b1d5055dc438bb02c7b66d7e9638afcf73bda3a/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-04-19%20%D0%B2%2010.09.29.png" alt="Снимок экрана 2024-04-19 в 10.09.29.png" />

- [x] Add the special block film amortization at the bottom of the statement
In the future blocks will be expandable, but for the moment we have to show only the basic lines
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemgzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--006b6013bd2ac04640daea088bad3d44526a31e3/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-04-19%20%D0%B2%2010.13.59.png" alt="Снимок экрана 2024-04-19 в 10.13.59.png" />

**Comment by phpgeekfr** [comment]
- [ ] implement condition "film amortized" which will look poolRevenue used for calculation >= filmCost - financing
- [ ] check if we can implement an event "film Amortized" for standalone versions

**Comment by phpgeekfr** [comment]
- [ ] make outgoing statement changes on PDF export also

**Comment by phpgeekfr** [comment]
- [ ] check `TODO #9771` in code

**Comment by phpgeekfr** [comment]
Example for Excel Import: 

- Evaluated Value Type (condition name): `film amortization` or `film amortized` or `filmAmortized`
- Evaluated Value Name : can be left empty. If provided, will create the new amortization calculation using this pool
- Operator: `Less than` or `Greater than or equal to`
-  Target Type: empty or `amortization.filmCost`
-  Target Value : name or id of existing calculation. If not existing, will be created using provided name and value from Evaluated Value Name as pool. **new calculation will need to be completed with cost, financing, orgs and set to status "applied" using front**
-  % Target : optional, default is 100. Can be used to say "when 10% of the film is amortized"

<img width="1151" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW1TQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1975844145bebe09876e7836e763cf0d43c3760f/image.png" alt="image.png" />
