### ISSUE TITLE
filter availabilities in search page - marketplace

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#979]
What should we do with the filter availabilities function? This is actually done by the distribution right creation page...

**Comment by Jackseed** [comment]
@Maxstgt the filter should be working in this page also but we separate it from the other filters and add a "Apply" button or similar so the user decide to use the filter availability separate from the other filters. 
UX is working on a way to display the films that are 'almost' available but we should at least be able to display those who are.

**Comment by Jackseed** [comment]
not relevant anymore
