### ISSUE TITLE
🎨 Update of the Waterfall Builder to make it more user-friendly

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9835]
### Context
According to the users' feedbacks + our own assumptions, we need to make the process of the waterfall creation easier. 
This issue is dedicated at first to design and then should evolute to dev issue. 

### To take into account
Some important remarks have been already made, so need to take them into account : 

**ORANGE LIST to take into account**
- [ ]  🟠 🧩 ‼️ (from afleutot)When I’m building the waterfall, and I add a new source, then on the right it should be this new source page. And the same for all the new right/source. This is really annoying, in particular when I'm building waterfall with a lot of sources, because then I have to search for my new right/source.
- [ ]  🟠 🧩 ‼️ When creating the waterfall scheme, I have to click back again on a receipt source to be able to create a new source. I don't think this is clear enough to create a new receipt source.
- [ ]  🟠 🧩 Find better solution for the first screen of the conditions adding ;
- [ ]  🟠 🧩 On top of Conditions we need to add a sentence like "The conditions will be tested in order that if they are true, the Receipt Share will take its percentage."
- [ ]  🟠 🧩 In the Condition view (the sentence) "contract contractId" should be replaced by "contract 'contractName' "
- [ ]  🟠 🧩 In the Condition view (the sentence) "contract contractId" should be replaced by "contract 'contractName' "
- [ ]  🟠 🧩 It would be better I think when we write conditions that the name of the group that is automatically create have the name we chose for the receipt share. Indeed, when we create conditions, the name we chose for the receipt share is automatically deleted, when most of the time the group should actually take the name of the condition.
- [ ]   🟠🧩 Best would be to select the first contract attach to the org by default here (waterfall builder, RS form)
- [ ]   🟠 🧩 When clicking on "Add Next Receipt Share" it should select the new created right automatically
- [ ]   🟡 🧩 As we have the sticky header now, the CTAs "+ New RS" and "+ Create New Source" are not visible enough. We need or put them into the top or add them inside the waterfall scheme.
- [ ]   🟠 🧩 RS type should be empty default instead of "Other"

**GREEN LIST to take into account**
- [ ] 🟢 🧩 When we add expenses from the conditions block during waterfall building, it should be more fluid (not edit, but add, maybe ?? -> to think over)
- [ ]  🟢 🧩 Condition form: add a % inside the Percentage input
- [ ]  🟢 🧩 Be able to copy/paste the conditions
- [ ]  🟢 🧩 Be able to save and undo/redo actions on the Waterfall
- [ ]  🟢 🧩 When the waterfall is published, the user should be redirected to the Waterfall tab (Published version of Waterfall).

**Comment by Jackseed** [comment]
> [ ] 🟠 🧩 ‼️ (from afleutot)When I’m building the waterfall, and I add a new source, then on the right it should be this new source page. And the same for all the new right/source. This is really annoying, in particular when I'm building waterfall with a lot of sources, because then I have to search for my new right/source.

I totally agree, also, bonus but would be great if we can focus the graph to the new created source/right

**Comment by Jackseed** [comment]
I got several issues not listed here:
- [ ] Change the name of the selects in the condition form to match what's listed in the to [tables](https://www.notion.so/cascade8/Conditions-88029a78e9cf47bc97a4680645fee3b8) (user naming/user values columns). Especially the 2nd table
- [ ] When there is no possibility in the select we should display an option like "No .. created" or an error message and help the user go to contract and create it. (here an example with investments)
<img width="678" alt="image" src="https://github.com/blockframes/blockframes/assets/14964443/91788f55-d590-4ae1-88eb-5fa81b2d2a0e">
- [ ] New step / Next conditions still unclear; not sure what has been changed from previous design
- [ ] Step selection inside a group is too complex. Maybe add the group form inside all steps, and always add the condition tab inside the step. If possible with only the concerned conditions and not all of them. Also, add the percentage input inside the step form so user knows what has been set for this step (same as name and type but inside the condition form not above it)
- [ ] If possible, would be amazing to add a simple simulation inside the builder: gross receipts on top of the sources could be editable so user can test and try any value. If we go for that we should also add a number for expenses (and MG/investment) to be recouped from the concerned node visible in the graph directly. Then this number could be editable as well
- [ ] Numbers inside the arrows should be bigger
- [ ] Add duplicate button on a node 
- [ ] On the starting screen, maybe add options to not start from scratch but add a pre-filled scenario (like our demo film)?

**Comment by 2amarkina** [comment]
## Work in progress / for validation

#### Flow for a user to select how to proceed via template or scratch 
Two versions of the flow
[Link to figma](https://www.figma.com/design/zsxsYzg5083IIs22tBxfIq/Optimization-of-the-Waterfall-Builder?node-id=32-4518&t=Lbby7IBcMqZzuJDp-4)

#### Update  of the instructions 
Depending if user chooses the template or scratch 
[Link to figma](https://www.figma.com/design/zsxsYzg5083IIs22tBxfIq/Optimization-of-the-Waterfall-Builder?node-id=36-4457&t=Lbby7IBcMqZzuJDp-4)

#### Flows of RS duplicating
With the phare solution proposition
[Link to Figma](https://www.figma.com/design/zsxsYzg5083IIs22tBxfIq/Optimization-of-the-Waterfall-Builder?node-id=36-4834&t=Lbby7IBcMqZzuJDp-4)

#### Updated flow of condition creation 
Proposition of some new wording, emphasize the new bar tool to avoid the "hidden" actions as double clicking

[Link to figma](https://www.figma.com/design/zsxsYzg5083IIs22tBxfIq/Optimization-of-the-Waterfall-Builder?node-id=53-5206&t=Lbby7IBcMqZzuJDp-4)

#### Simple simulation proposition - upcoming

**Comment by 2amarkina** [comment]
## Update screens 
[Link to figma with new simulation, conditions and "ne created" screens](https://www.figma.com/design/zsxsYzg5083IIs22tBxfIq/Optimization-of-the-Waterfall-Builder?node-id=105-9533&t=gzIJaJRBTgwcKfg2-0)

**Comment by 2amarkina** [comment]
#### User CRUD conditions
- [ ] 🧩 🟠 verify all the "enlarge" modals, sometimes they do not take all the place (Conditions is not ok, but Receipt Share is ok)
<img width="1685" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0V2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f90099de39cc65c818fdfb4a65504426a870f76a/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-03%20%D0%B2%2017.18.57.png" alt="Снимок экрана 2024-06-03 в 17.18.57.png" />

**Comment by 2amarkina** [comment]
after the last design validation (conditions especially), this issues is divided in four dedicated issues to facilitate the dev work : 
- [ New Waterfall Builder toolbar #9897](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/issues/gh/blockframes/blockframes/9897)
- [Revenue Simulation inside waterfall builder #9894](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/issues/gh/blockframes/blockframes/9894)
- [User CRUD Receipt Share #9895](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/issues/gh/blockframes/blockframes/9895)
- [User can CRUD Conditions #9896](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/issues/gh/blockframes/blockframes/9896)

**Comment by 2amarkina** [comment]
Closing this one as other dedicated issues were created
