### ISSUE TITLE
Review apps (technical updates)

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9852]
**Context:** 
As we have made the important updates on the technical side, we need to verify that the applications are still working correctly. 

**Goals:**
Hard testing - Blockframes
Medium testing - Archipel Content
Light testing / just a quick look - Archipel Market / Media financiers

**Important**
While testing we try to click everywhere and pay special attention to the visual elements that might be different from the previous apps' versions. 

**Useful**
For all the visual elements concerning spacing, forms, etc [the documentation for Material 3 will be used](https://m3.material.io/)
To check the elements "irl" check out[ figma file with the Material 3 updates](https://www.figma.com/design/ihdxda85hyrkFxbTOmUrJj/Material-3-Design-Kit-(Community)?node-id=49848-6285&t=1taTXsY97Pf69LTb-0)

**Comment by afleutot** [comment]
- [ ] 🐞

Small bug when correcting the name of a receipt source when creating the waterfall (the waterfall is not published).
When I change the name of the receipt source, it changes directly on the waterfall, but not on the right bloc.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1JYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd2ac0152dff81c384d65fa967561d7b2862fd4a/Enregistrement%20de%20l%E2%80%99e%CC%81cran%202024-06-12%20a%CC%80%2009.54.29.mov)

**Comment by afleutot** [comment]
- [ ] 🐞
Overlap of texts at the bottom of Receipt share box
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHRYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3ff2941a83ec8feab6de822858fd8d02ed34644/Capture%20d%E2%80%99e%CC%81cran%202024-06-12%20a%CC%80%2010.07.16.png" alt="Capture d’écran 2024-06-12 à 10.07.16.png" />

**Comment by 2amarkina** [comment]
## Cross-app changes

For all the visual elements concerning spacing, forms, etc [the documentation for Material 3 will be used](https://m3.material.io/)

### Fields, placeholders, spacing, labels
- [ ] I find it quite choking to keep the letter spacing inside the placeholders.

**Comment by afleutot** [comment]
- [ ] 🐞
CRM - for the import of sources
A couple of times, when I add the sources, the checkbox on the left does not appear. For the other import there is no problem. Just for the sources.

**Comment by 2amarkina** [comment]
### Small changes to take into account for this release : 
- [ ] change the email [on this page](https://staging.app.blockframes.io/c/o/dashboard/terms ) from teamc8 to new email of team blockframes
- [ ][ Add this text about AI ](https://docs.google.com/document/d/1Hw8JqF_MurU4rcazzKOkq_dx3QpY-ENUKirX0vRo3eg/edit#heading=h.mudfa9i60prk)to data security page

**Comment by afleutot** [comment]
I'm having a bit of trouble with the new font. I'm not sure if it's because it's new and I was too used to the old version, but I find the spacing between the letters to be perhaps a bit too wide?

**Comment by afleutot** [comment]
Also, with the dark theme, I have trouble with the light pink. I don't find it very appealing. Coral looks good, but the light pink, not so much.<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHhaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--838b711c79596a02ecd2de9b65b3f72288529c2e/Capture%20d%E2%80%99e%CC%81cran%202024-06-12%20a%CC%80%2015.27.50.png" alt="Capture d’écran 2024-06-12 à 15.27.50.png" />

**Comment by 2amarkina** [comment]
## Marketplaces (AC, AM, MF)

- [ ] The text inside the field is no longer visible. Need to come back to the white color as we had on prod. 
"from-to"
<img width="1896" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWxaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e46286261f413f6737990da74889ef0e7afd54ab/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-12%20%D0%B2%2016.09.11.png" alt="Снимок экрана 2024-06-12 в 16.09.11.png" />

- [ ] In our home-updated component with select/groups we need to change the alignment to show that the sub categories are inside. 
"from-to "
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkZaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c09ff3b0601a36aea1f291e5f6e4310c81bb55b4/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-12%20%D0%B2%2016.12.08.png" alt="Снимок экрана 2024-06-12 в 16.12.08.png" />

- [ ] Too much space between the checkbox and the text, need to come back as was before 
"from-to"
<img width="1678" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmxaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51062f32a5d375f5ab4511d3cd767d8d9e5eb8b5/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-12%20%D0%B2%2016.14.30.png" alt="Снимок экрана 2024-06-12 в 16.14.30.png" />

- [ ] Icons are not aligned correctly
<img width="974" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnBaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86252f8e54979a1f3782b9ee78542d65537735da/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-12%20%D0%B2%2016.16.40.png" alt="Снимок экрана 2024-06-12 в 16.16.40.png" />

- [ ] Supplementary line that we do not need in this component 
<img width="709" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnRaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--000205010b82afcabb3ef14fed708c9397202962/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-12%20%D0%B2%2016.17.12.png" alt="Снимок экрана 2024-06-12 в 16.17.12.png" />

**Comment by 2amarkina** [comment]
> Also, with the dark theme, I have trouble with the light pink. I don't find it very appealing. Coral looks good, but the light pink, not so much.<img alt="Capture d’écran 2024-06-12 à 15.27.50.png" width="1280" src="https://camo.githubusercontent.com/7ad1ad033ed066fd3c9c0a96c20f4859ead84aca161a4da1548ba589b9f7b8bc/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424d486861516c453950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d383338623731316337393539366130326563643264653962363562336637323238383532396332652f4361707475726525323064254532253830253939652543432538316372616e253230323032342d30362d31322532306125434325383025323031352e32372e35302e706e67">

Agreed for the light pink, but how could you access the dark theme on Blockframes? Normally it is desactivated for BF and is available only for the Maketplaces (AM, AC, MF)

**Comment by 2amarkina** [comment]
- [ ] Activated switches toggle doesn't seem to less user-friendly as we can't see that it's clickable anymore (great for the check, but need to have the "tail")

<img width="1372" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelJhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa65de20f55840211b749efaffa0982b25c9a6ff/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-12%20%D0%B2%2017.16.38.png" alt="Снимок экрана 2024-06-12 в 17.16.38.png" />

**Comment by 2amarkina** [comment]
- [ ] As we have released the documentation we can add the link to it to the platform. 
Let's add the link at the footer as CTA and also as the text link in the waterfall builder 

[Link to use](https://www.blockframes.io/doc/welcome-page)
<img width="1250" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTllQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--309ba884ae24b5756e8a4d366ac7c2f6be76b7f4/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-13%20%D0%B2%2010.14.40.png" alt="Снимок экрана 2024-06-13 в 10.14.40.png" />

**Comment by 2amarkina** [comment]
- [ ] DIsabled fields are not visible at all, need to add more contrast
<img width="1548" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1ZlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--444ff4b94eb065a4ee91f24e9d10d0db5f7e0a13/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-13%20%D0%B2%2010.29.35.png" alt="Снимок экрана 2024-06-13 в 10.29.35.png" />

**Comment by 2amarkina** [comment]
- [ ] Guess that's the same type of the problem, but here are more CTAs that are not ok
<img width="628" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUJlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--adff45172a72378caf3c989b98fad91b47ef4ca7/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-13%20%D0%B2%2011.21.19.png" alt="Снимок экрана 2024-06-13 в 11.21.19.png" />

<img width="1006" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUZlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9080cba9cf0f8644cc20001d6616cba98ca6fb6/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-13%20%D0%B2%2011.21.31.png" alt="Снимок экрана 2024-06-13 в 11.21.31.png" />

**Comment by afleutot** [comment]
@afleutot Agreed for the light pink inside the dark theme, but how could you access the dark theme on Blockframes? Normally it is desactivated for BF and is available only for the Maketplaces (AM, AC, MF)

My laptop automatically switches on dark theme after a certain time, and every apps automatically goes dark theme. So Blockframes actually was also on dark theme, with the rest of all the apps.

**Comment by afleutot** [comment]
- [ ] 🐞
I think this is a bug, because when I try to filter, nothing comes, when I'm literally trying to filter with what is there.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cad54c65397b805d644474ef16fcb12a47f97f1c/Enregistrement%20de%20l%E2%80%99e%CC%81cran%202024-06-13%20a%CC%80%2014.52.23.mov)

**Comment by afleutot** [comment]
- [ ] Font
Here at contracts, i don't like a lot the difference between the first line and the second line. I think the second line is way too small in comparison to the first. But maybe it is because of the new font.
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a72fb96aaee5dbab2626b4b0ed6e4de1a16226a/Capture%20d%E2%80%99e%CC%81cran%202024-06-13%20a%CC%80%2015.17.03.png" alt="Capture d’écran 2024-06-13 à 15.17.03.png" />

**Comment by 2amarkina** [comment]
closing this one, as most of the changes are successfully released and open[ the new one for more clear vision ](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/issues/gh/blockframes/blockframes/9869)
