### ISSUE TITLE
Review of technical updates part 2

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9869]
### Context
Listing here the bugs / breaks that remain from the previous ticket. 

- [x] **Bug persists**
(from afleutot)Small bug when correcting the name of a receipt source when creating the waterfall (the waterfall is not published).

When I change the name of the receipt source, it changes directly on the waterfall, but not on the right bloc.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1JYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd2ac0152dff81c384d65fa967561d7b2862fd4a/Enregistrement%20de%20l%E2%80%99e%CC%81cran%202024-06-12%20a%CC%80%2009.54.29.mov)

- [x] **Line on the left on hover inside the field**
Strange hover effet that apperas inside the fields. Couldn't find this in any documentation, maybe i'm not quite attentive, but would propose to remove it. 

<img width="978" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHRaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd86b4a2fd2a6b4e2f0f2bb0254c8f0617d2db23/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-12%20%D0%B2%2015.03.24.png" alt="Снимок экрана 2024-06-12 в 15.03.24.png" />

- [x] **Default background should be white not light-grey**
<img width="1228" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVZsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d976e67d0c98983544aee072f257463109e79d2/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-14%20%D0%B2%2015.17.47.png" alt="Снимок экрана 2024-06-14 в 15.17.47.png" />

- [x] **CTAs broken (e.g. AM / Statistics .csv import)**
<img width="702" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXBsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2cd08bdcaf6a59605f77087e1873787653c7025/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-14%20%D0%B2%2014.07.58.png" alt="Снимок экрана 2024-06-14 в 14.07.58.png" />

- [x] **Tables with the fixed actions on the right became transparent instead of having white background**
now: 
<img width="940" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0JsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23f8cf20bd75d90245a513141ebce5f0be01daf5/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-14%20%D0%B2%2015.22.19.png" alt="Снимок экрана 2024-06-14 в 15.22.19.png" />

should be: 
<img width="276" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0ZsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8843462447ee9ef652e3c4e586a18848250296ec/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-14%20%D0%B2%2015.23.58.png" alt="Снимок экрана 2024-06-14 в 15.23.58.png" />

**Comment by 2amarkina** [comment]
- [ ] Contract icon is not centered compared to the field (is ok on prod)
<img width="1326" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2RsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62e3dc72b172e443dbf1a67199245c4d60e9e457/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-14%20%D0%B2%2015.29.34.png" alt="Снимок экрана 2024-06-14 в 15.29.34.png" />

**Comment by 2amarkina** [comment]
- [ ] The spacing between the icon and the input text is too large (ok in the prod version)
<img width="504" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFZxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd93c30ce19f116a9dc34b205dc8eaa57eceaea8/Capture%20d%E2%80%99e%CC%81cran%202024-06-17%20a%CC%80%2009.29.47.png" alt="Capture d’écran 2024-06-17 à 09.29.47.png" />

**Comment by afleutot** [comment]
- [ ] Bug in creation of conditions
I can not create new conditions here, when i click nothing happens.
I'm on staging with the new conditions. 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTdFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--491f99d67ef2a5de526ee6e5749e714bef18c75a/Enregistrement%20de%20l%E2%80%99e%CC%81cran%202024-09-10%20a%CC%80%2017.37.40.mov)
