### ISSUE TITLE
Internationalization Step 2

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9870]
### Context
As the main work on the Internationalization has been done and the previous issue becomes pretty overwhelmed the new one if created to centralize the left to to for the internationalization. 

The actions should be undertaken by two poles: product & dev. 

P.S. The work in progress on [the documentation and centralisation of the translation ressources can be found here](https://www.notion.so/cascade8/Internationalization-6933123009aa444189efcd6210c8528c)

###  📑 To do (product) 
- [x] **Create translation verification document**
Aim: the document should be easy to use by extern people and at the same time it should not be time-consuming to update for product part following the verification notes.

- [x] Centralize the translation ressources 
- [x] Traslate medias (FR, ES)
- [x] Translate territories (FR, ES)
- [x] Translate new parts in Spanish (assets/ static model)
- [x] Translate Sendrid templates into Spanish
- [ ] Thick over the strategy & process for the maintenance of such kind extern translation (sendgrid e.g.) + see how to include them into verification document
- [ ] Webflow FAQ multi-language solution 

### 👨‍💻 To do (dev) 
~~- [ ] check `TODO #9699` in code~~
- [ ] check how to translate PDF statements : will be in the same lang when generated/reported on front ( translated data in `reportedData` section)
- [x] fr sendgrid templates
- [x] es sendgrid templates 
- [x] notification statuses: should be `a accepté votre ...`
<img width="462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGpjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--422f4d2aef7860013492bd8a6e1cd75238d96e98/image.png" alt="image.png" />

**Comment by phpgeekfr** [comment]
- [ ] check `TODO #9870` to reactivate `ES` lang

**Comment by 2amarkina** [comment]
Sendgrid templates translations in french (updated) and Spanish are ready. 
For centralizing information, [the notion document has been created  ](https://www.notion.so/cascade8/Sendgrid-translations-f2a83ae8d73246d7b61944f2ca37ec48) with the links to the corresponding excel sheets if needed.

**Comment by 2amarkina** [comment]
Saw one untraslated phrase on the french version of the notifications : 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkdIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--774e7fa61ed404148428b078a918fe6f9157fc07/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-24%20%D0%B2%2014.50.00.png" alt="Снимок экрана 2024-06-24 в 14.50.00.png" />

French text to use : `Vous êtes invité(e) à rejoindre un Waterfall. (RECOMMANDÉ)`
Spanish text to use : `Se le invite a unirse a un Waterfall. (RECOMENDADO)`

**Comment by 2amarkina** [comment]
English word  found inside the french translation inside the "notifications"
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlNIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01a2b90bc4577a2874e24fa7b8f26244ed535c92/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-24%20%D0%B2%2014.52.52.png" alt="Снимок экрана 2024-06-24 в 14.52.52.png" />

**Comment by phpgeekfr** [comment]
- [ ] check `TODO #9870` in code

**Comment by phpgeekfr** [comment]
- [ ] issue with `8436351042167499978`  & `1977110923519959622`
<img width="1328" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2l1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c52e6bdfe2f57bf31ca73abf9e97a000a5c519fd/image.png" alt="image.png" />

should be `le|la ${source|droit} suivant|suivante`

**Comment by phpgeekfr** [comment]
- [ ] `sont de inferieur`
<img width="1679" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEt1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a124cf3bb7fddb68b8a79568bcf2a809869540fd/image.png" alt="image.png" />

**Comment by Jackseed** [comment]
- [ ] Media & territories display the English version on view (not on form) 
<img width="1129" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVN1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bfc6c62d5c9d2cfb16b529d33ff048e832db805e/image.png" alt="image.png" />
- [ ] Search bar inside media / territories select uses the English version of the searched word
- [ ] Add new source/right on tooltip
<img width="306" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVd1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e37409e1ea73dea64f119b8076f0205645dfa46/image.png" alt="image.png" />

**Comment by phpgeekfr** [comment]
- [ ] `Blockframes la plateforme`
<img width="1712" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGJ1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01aba8479e96d657709f6d9f7dcdc72ab8231aec/image.png" alt="image.png" />

**Comment by phpgeekfr** [comment]
- [ ] "contacter blockframes l'équipe" & it should be "actuali**ser** la page"
<img width="873" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTd1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88fdff956d50d131262ea9e058fb63d02524c7ff/image.png" alt="image.png" />

**Comment by phpgeekfr** [comment]
- [ ] maybe `Merci de patienter pendant que notre équipe `
```"5052158702138860710": "Votre compte a été créé. Merci de patienter en attendant que notre équipe vérifie les informations de votre société.",```

**Comment by phpgeekfr** [comment]
- [ ] translations to review (probably same in ES)
```
    "7082811056049876681": " Veuillez saisir une {$START_TAG_STRONG}valid{$CLOSE_TAG_STRONG} adresse e-mail. ",
    "4057855208853567886": " L'adresse e-mail est {$START_TAG_STRONG}required{$CLOSE_TAG_STRONG}. ",
```

**Comment by phpgeekfr** [comment]
@2amarkina updated notion page with a tutorial on how to setup internationalization in Sendgrid templates https://www.notion.so/cascade8/Sendgrid-translations-f2a83ae8d73246d7b61944f2ca37ec48

**Comment by 2amarkina** [comment]
as there is a dedicated issue created for the PDF internationalization and the work on the sendgrid templates is left only for the product team, i guess we can close this one

**Comment by phpgeekfr** [comment]
closed. 
see #9890 & #9951 for what is left to do
