### ISSUE TITLE
📑 Outgoing Statements updates 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9880]
### User creates an outgoing statement
We need to improve the view of the calculation details for the outgoing statements to make them easier to read. 

**TO DO / Example**
<img width="652" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3h3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03843270e5789b11ebec8efc23a7d175c2a38bfa/312899237-42619736-9664-4e2b-aa2f-c7c4cd3b2ffb.png" alt="312899237-42619736-9664-4e2b-aa2f-c7c4cd3b2ffb.png" />

- [ ] 🟠 🗒️ ~~Replace From & To columns with only "Revenue Share" column then the % column and finally the 3 prior / current / cumulative columns (from previous outgoing statements)~~

So the table above would become:

Revenue Share | % | Prior | Current | Cumulative
Festivals | - | €10,000.00 | €27,820.00 | €37,820.00
Distribution Fee Mystic Sales Festivals | 50% | €5,000 | €13,910.00 | €18,910.00
Expenses Mystic Sales | 100% | €5,000 | €13,910.00 | €18,910.00
MG Mystic Sales | 0% (? here it should be the theorical % not the effective one so if the right has 100% it should be 100% even if it takes 0)| 0 | 0 | 0
Producer's Net Participation | 0% (same remark than above) | 0 | 0 | 0

[Outgoing.Statement.1.-.actual.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2lIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0030a0f08aaa1fa17faadf34bbf4fdda60512960/Outgoing.Statement.1.-.actual.pdf)
[Outgoing.Statement.1.-.new.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3FIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aaa24587c08446dfeba75f663238fa0d1732958e/Outgoing.Statement.1.-.new.pdf)

**Comment by phpgeekfr** [comment]
- [ ] make same changes on PDF

**Comment by phpgeekfr** [comment]
@Jackseed can you provide another example for this  :
<img width="1836" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVdNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f61b18fd2b35c105a6f358790e2c89b3e63b941/image.png" alt="image.png" />

**Comment by phpgeekfr** [comment]
and regarding `here it should be the theorical % not the effective one so if the right has 100% it should be 100% even if it takes 0` :
If current row is a group (Producer's Net Participation for example) I cannot calculate the percentage without money going into the group, especially for vertical groups (or horizontal containing verticals) where an income can be distributed on several steps.

I could display the group percentage but it will always be 100% and I'm not sure this will be understandable for users

**Comment by phpgeekfr** [comment]
please also provide data for this example <img width="1824" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeitOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--064c9ddf0d66d16866bc12c07c995131141b5623/image.png" alt="image.png" />

**Comment by phpgeekfr** [comment]
should this also be modified with current, previous cumulated ?
<img width="1829" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnVOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7b03e097555221f8dd691bcf2e8a672c86e0639/image.png" alt="image.png" />

**Comment by Jackseed** [comment]
Following our discussion:
- forget about % in the table
- breakdown groups so each inside block appear as a distinct row: if it's an horizontal group each block inside, if it's a vertical each step. 
- yes we do add current | previous | cumulated in the first table

So here:
<img width="1836" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVdNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f61b18fd2b35c105a6f358790e2c89b3e63b941/image.png" alt="image.png" />
It would be (assuming every previous was 0)
Recettes DVD France  0 | 21k | 21k
Part auteur (inside Parts sur RBD DVD FR): 0 | 0 | 0
Royalties DVD | 0 | (17,5k) | (17,5k)

Net receipts: 4K (see @2amarkina new statement with results in top right corner + bottom right corner)

Recettes VOD France 0 | 3k6 | 3k6
Redevance VOD France 0 | 1k4 | 1k4

Net receipts: 2,2k

And here
 <img width="1824" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeitOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--064c9ddf0d66d16866bc12c07c995131141b5623/image.png" alt="image.png" />

Recettes inter 0 | 47k | 47
Part auteur inter 0 | 0 | 0
Comm inter 0 | 11,7K | 11,7K
Récupération Frais 0 | 1,2K | 1,2K
Récupération MG 0 | 0 | 0
Part auteur (or whatever other block inside the Part sur recettes nettes block) 0 | 0 | 0

Net receipts: 34K

**Comment by phpgeekfr** [comment]
- [ ] check `TODO #9880`

**Comment by phpgeekfr** [comment]
- [ ] check if `skipEmptyTransfers` must me set to true or not for `outgoingDetails$`
example with wrong and `Expenses Autres droits Monde` that does not take anything:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0lGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b243b8b3d6ac3dd68225fb14e1cf76f00ed4b669/image.png" alt="image.png" />

**Comment by Jackseed** [comment]
lgtm!
