### ISSUE TITLE
Revenue Simulation inside waterfall builder

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9894]
### Context
One of the most requested features is to be able to see how money would possibly be redistributed even without statements yet. 

That might be important for:
- checking if the waterfall was correctly configured ; 
- pure simulation. 

### To do 
- [x] Add the Revenu simulation CTA inside the toolbar (see the issue # to create a new toolbar) ; 
- [x] When clicking on this CTA, then user accesses the simulator. 
- [x] User sees the list of the possible sources with associated Gross Receipts Amount input. 
- [x] If there are the conditions that contain the expenses, then, user sees the names of the associated companies, the cap and the expenses amount input. 
<img width="581" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeldOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cb1eb427ba6537564eacdd26c0d3ced43500a36/Simulation.png" alt="Simulation.png" />
- [x] If there is no expenses entered, the show "No expenses added yet phrase.
- [x] If there is no sources yet, then disable Revenue Simulation CTA and add tooltip "Add sources to enable access to the simulator"

- [x] When user clicks on the CTA simulate revenue distribution, the numbers on the graph are adapted accordingly. 
- [x] Also, when the simulation is launched, then on the right side user can see on the right side the Simulation results. There user can see the revenue distribution among the companies mentioned in the waterfall. 
- [x] The CTA on the results simulation page refreshes the page and comes back to the initial simulation screen. 
<img width="581" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemFOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--acbc28ec96ba23ac18f57696059efe368fb121e9/Simulation%20%281%29.png" alt="Simulation (1).png" />

- [x] (from Jackseed) If possible, would be amazing to add a simple simulation inside the builder: gross receipts on top of the sources could be editable so user can test and try any value. If we go for that we should also add a number for expenses (and MG/investment) to be recouped from the concerned node visible in the graph directly. Then this number could be editable as well <-- do we add MG also?

### Sources
[Figma link](https://www.figma.com/design/zsxsYzg5083IIs22tBxfIq/Optimization-of-the-Waterfall-Builder?node-id=105-9534&t=mCekCorB8o9Le2ZW-4)

**Comment by phpgeekfr** [comment]
- [ ] we will need to add a date for incomes & expenses: one global for all or a different for each 
<img width="249" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzZOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3d80888dfd5e11b30d6fd9183921d0a57d3e888/image.png" alt="image.png" />

**Comment by Jackseed** [comment]
- [ ] Need to add (facultative) terms (media & territories) form to respect corresponding condition. cc @2amarkina for a design proposition

**Comment by Jackseed** [comment]
- [ ] Add a button "populates with current values" so the form uses the current income values. But then let the user change these values

**Comment by phpgeekfr** [comment]
> Add a button "populates with current values" so the form uses the current income values. But then let the user change these values

@Jackseed it would be more easy to add a toogle,  "start from zero" or "append to existing"

**Comment by Jackseed** [comment]
Looks good to me, please confirm design with @2amarkina
