### ISSUE TITLE
User CRUD Receipt Share 

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9895]
- [x]  🟠 🧩 ‼️ When creating the waterfall scheme, I have to click back again on a receipt source to be able to create a new source. I don't think this is clear enough to create a new receipt source.
- [x]  🟠 🧩 Best would be to select the first contract attach to the org by default here (waterfall builder, RS form).
- [x]  🟠 🧩 When clicking on "Add Next Receipt Share" it should select the new created right automatically.
- [x]  🟠 🧩 RS type should be empty default instead of "Other". 
- [x]  🟠 🧩 If contract is not added, or if there is an error with the contract we need to show it to the user. 
- [x]  🟠 📑 Change "Group RS" when creating a pool to "Pool Receipt Shares". 

- [x]  🟢 🧩 When the waterfall is published, the user should be redirected to the Waterfall tab (Published version of Waterfall).
- [x] 🟢 🎨 Numbers inside the arrows should be bigger (from 12px to 16px)

- [x] 🐞 (from afleutot) When I'm editing the Right holders part of the platform, and then I click on the 'Continue' blue button to go on the edit of the waterfall, I immediately go on the back of the page and not on the start of the page.

Cf. screenshot<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXNIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d3a0b64b3068c2da55dbbee0edf391be4f09e34/Capture%20d%E2%80%99e%CC%81cran%202024-03-25%20a%CC%80%2012.54.55.png" alt="Capture d’écran 2024-03-25 à 12.54.55.png" />

**Comment by 2amarkina** [comment]
- [ ] 🧩 🟠 When a user closes the right sidebar and keeps the waterfall builder in full mode, the right sidebar should automatically re-open when the user clicks on the RS or a source.

**Comment by phpgeekfr** [comment]
> (from afleutot) When I’m building the waterfall, and I add a new source, then on the right it should be this new source page. And the same for all the new right/source. This is really annoying, in particular when I'm building waterfall with a lot of sources, because then I have to search for my new right/source.

Please add this to a dedicated issue about graph/layout refactoring
