### ISSUE TITLE
User can CRUD Conditions

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9896]
- [x]  🟠 🧩 If the user has not filled in the Receipt Share information, then Conditions tab is disabled to tooltip "First, fill Receipt Share information."
- [x]  🟠 🧩 Once user clicks on "Add tier" CTA, then enters the mode with modal enlarged view by default.
- [x]  🟠 🧩 Find better solution for the first screen of the conditions adding ;
- [x]  🟠 🧩 On top of Conditions we need to add a sentence like "The conditions will be tested in order that if they are true, the Receipt Share will take its percentage."
- [x]  🟠 🧩 In the Condition view (the sentence) "contract contractId" should be replaced by "contract 'contractName' 
- [x]  🟠 🧩 It would be better when we write conditions that the name of the group that is automatically create have the name we chose for the receipt share. Indeed, when we create conditions, the name we chose for the receipt share is automatically deleted, when most of the time the group should actually take the name of the condition.
- [x] 🟠 🧩 verify all the "enlarge" modals, sometimes they do not take all the place (Conditions is not ok, but Receipt Share is ok)
<img width="1685" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0V2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f90099de39cc65c818fdfb4a65504426a870f76a/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-06-03%20%D0%B2%2017.18.57.png" alt="Снимок экрана 2024-06-03 в 17.18.57.png" />

- [x] 🟢 🧩 When we add expenses from the conditions block during waterfall building, it should be more fluid (not edit, but add, maybe ?? -> to think over)
- [x]  🟢 🧩 Condition form: add a % inside the Percentage input

from Jackseed: 
I got several issues not listed here:
- [ ] Change the name of the selects in the condition form to match what's listed in the to [tables](https://www.notion.so/cascade8/Conditions-88029a78e9cf47bc97a4680645fee3b8) (user naming/user values columns). ~Especially the 2nd table~ => moved to #9959
- [x] When there is no possibility in the select we should display an option like "No .. created" or an error message and help the user go to contract and create it. (here an example with investments)
<img width="678" alt="image" src="https://github.com/blockframes/blockframes/assets/14964443/91788f55-d590-4ae1-88eb-5fa81b2d2a0e">

- [x] New step / Next conditions still unclear; not sure what has been changed from previous design
- [x] Step selection inside a group is too complex. Maybe add the group form inside all steps, and always add the condition tab inside the step. If possible with only the concerned conditions and not all of them. Also, add the percentage input inside the step form so user knows what has been set for this step (same as name and type but inside the condition form not above it)
~~- [ ] On the starting screen, maybe add options to not start from scratch but add a pre-filled scenario (like our demo film)?~~

### Sources
**Wording**
All the new wording and formulations for the modal conditions [can be found here](https://www.notion.so/cascade8/Conditions-88029a78e9cf47bc97a4680645fee3b8)

**Update screens** 
[Link to figma with new simulation, conditions and "not created" screens](https://www.figma.com/design/zsxsYzg5083IIs22tBxfIq/Optimization-of-the-Waterfall-Builder?node-id=105-9533&t=gzIJaJRBTgwcKfg2-0)

**Comment by 2amarkina** [comment]
- [ ] validate the last design and check the new wordings together with @Jackseed

**Comment by Jackseed** [comment]
- [ ] 🟠🧩 I found the break even condition not instinctive: you have to add a percentage but in fact conditions are always either: the break even is done or not. I would opt for a boolean select instead of the % (the sentence is correct by the way and that's reassuring to read "le film est amorti" as that's what I want to do)
<img width="1410" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk91QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb16ef8a9944693b586a35990948622e87928a10/Pasted%20Graphic%205.png" alt="Pasted Graphic 5.png" />

**Comment by Jackseed** [comment]
Following last demo/free trial feedback:
- [ ] 🟠 🧩 Change "tier" for "threshold"
- [ ] 🟠 🧩 Add a source turnover condition: enable user to focus all incomes coming from a selected source as the left operand. I updated the [condition graph](https://www.notion.so/cascade8/Conditions-88029a78e9cf47bc97a4680645fee3b8), first route on the image below:
<img width="1982" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm5KQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5300f24308c6b740336c932157c45d223d2ad20/image.png" alt="image.png" />

- [ ] 🟠 🧩 Add all equality symbols in the numerical operator select: `<`, `<=`, `>`, `>=`

- [ ] 🟠 🎨 Enlarge the waterfall schema either by limiting the header / footer (removing text, moving things on the same lines,..) and/or by reducing the right side of the form for something like 60/40 or even 70/30

- [ ] 🟠 🎨 🧩 Could be an issue on its own, not sure what's possible here but really important as it blocks us to create some waterfalls: sometimes the revenues are not in % of a source but an absolute value like "$50,000" bonus. Could be added as a toggle option on the percentage field?

**Comment by Jackseed** [comment]
- [ ] 🔴🧩 When selecting expenses as a target user can only select the expenses of the linked contract. I can't see why, and if no particular reason we should remove this filter and allow to select any expenses

**Comment by 2amarkina** [comment]
- [ ] See together how we could adapt the size of the fields accordingly to their meaning size (for example: the field for the date should not take all the line, but should be small)

**Comment by phpgeekfr** [comment]
- [ ] check `TODO #9896` in code

**Comment by phpgeekfr** [comment]
> Could be an issue on its own, not sure what's possible here but really important as it blocks us to create some waterfalls: sometimes the revenues are not in % of a source but an absolute value like "$50,000" bonus. Could be added as a toggle option on the percentage field?

This needs to be discussed, please create a dedicated issue

**Comment by 2amarkina** [comment]
[Dedicated issue for toggle option](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/issues/gh/blockframes/blockframes/9962)
[
Amortization (breakeven) boolean ](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/issues/gh/blockframes/blockframes/9963)

**Comment by phpgeekfr** [comment]
- [ ] @2amarkina  review changes and translate new sentences (https://github.com/blockframes/blockframes/pull/9952/files)

**Comment by phpgeekfr** [comment]
- [ ] also check the "read only" part that should be reworked for vertical rights :
<img width="1691" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVI3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33c4be7affbfdf2894b73937aa07bb55297494f3/image.png" alt="image.png" />

**Comment by phpgeekfr** [comment]
- [ ] fix the "blank" condition tab issue

**Comment by 2amarkina** [comment]
- [ ] Change snackbar text from the "no expense types found" to "no expenses found"

**Comment by 2amarkina** [comment]
- [ ] typos: from "You didn't entered the expected value. Action cancelled.", to "You didn't enter the expected value. Action canceled."
