### ISSUE TITLE
New Waterfall Builder toolbar

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9897]
### Context
To improve the usage of the waterfall builder we decided to introduce the new toolbar that we help user to make different actions more fluently. 

### To do
- [x] Introduce the toolbar
- [x] There should be the following CTAs: 
- add source,
- add receipt share, 
- see receipt's share list, 
- access revenue simulation, 
- and the "need help" that sends to documentation. 

If no choose waterfall CTA
<img width="1326" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2VOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cac86a9a13bc4b2b600007d7427eb9b4f6f699ae/Capture%20d%E2%80%99e%CC%81cran%202024-06-25%20a%CC%80%2015.05.08.png" alt="Capture d’écran 2024-06-25 à 15.05.08.png" />

If there is Choose waterfall CTA, then it should appear under the stepper and above the toolbar

**Comment by phpgeekfr** [comment]
- [ ] check `TODO #9897` in code
