### ISSUE TITLE
Pupille bugs

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9907]
I recreated a buggy version of the film I tried to create with a few bugs I'll list in this issue. 
The [film](https://staging.app.blockframes.io/c/o/dashboard/title/BZuo0lpgpfvs5sKj2855/statement/QXJShxTWS7ziz2q0nUhW/edit) 
The [excel master file](https://docs.google.com/spreadsheets/d/1tOVfxEG1btrcBxbnjfCGXOInjWDnL108dI2hxOSVgxg/edit?gid=186312408#gid=186312408) (click on the export button on the first tab to get all the docs our the download button on each page to get only the current tab) 
The [excel exports](https://drive.google.com/drive/folders/1XC9lGtzJOcwNgFrIShQmNCgu4ykv6MTL). 

- [ ] **Statement import doesn't work**, I can't say why. On the current film I imported a sales agent statement. Only the first income & expense are created. 

- [x] **Vertical group inside horizontal group at the source, all rights being to the same org**: it doesn't work. It's currently on the source "Recettes salles france" and this source doesn't appear on the statement form.

**Comment by phpgeekfr** [comment]
> Statement import doesn't work, I can't say why. On the current film I imported a sales agent statement. Only the first income & expense are created.

- First columns must be merged as shown in the template
- Current config is max 11 incomes per statement, if more is needed, config can be adjusted but existing excel for statements will need to be updated (if a statement have only 2 incomes, we have 9 blank lines)
