### ISSUE TITLE
Copy & paste waterfalls | save as a template

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9916]

**Comment by Jackseed** [comment]
I add it here from Feedback list:
- [ ] Add multiple blocks at once (like semi templates)
« C’est comme si on refaisait le monde à chaque fois »
=> would love to click on something and add sources + commission + expenses recoupment + MG recoupment (for instance)

**Comment by Jackseed** [comment]
Feedback from a user: we should look at DocuSign they have a good flow with saving as a template

**Comment by 2amarkina** [comment]
[Work in progress here ](https://www.figma.com/design/zsxsYzg5083IIs22tBxfIq/Optimization-of-the-Waterfall-Builder?node-id=79-2723&t=ktyloCipl8JDEXnh-0)

**Comment by 2amarkina** [comment]
Updated screen proposition for the import following the last review
[Link to Figma](https://www.figma.com/design/zsxsYzg5083IIs22tBxfIq/Optimization-of-the-Waterfall-Builder?node-id=359-7238&t=wGBCPMhyX1DnBVHj-4)

**Comment by Jackseed** [comment]
Designs look almost good - a bit of rework and we should be ok for a design review. Though the issue may be a bit more describing. Could you have a try with your new template @2amarkina ?

**Comment by 2amarkina** [comment]
> Designs look almost good - a bit of rework and we should be ok for a design review. Though the issue may be a bit more describing. Could you have a try with your new template @2amarkina ?

[Here is the issue in WIP for the simplified flow ](https://app.zenhub.com/workspaces/development-5f6b0067599064680cd2c617/issues/zh/2)

**Comment by 2amarkina** [comment]
Closing this big one issue, as the main topic was separated into two steps : 
- Simplified Flow <-- almost done
- [ Waterfall template creation from other film (Step 2)](https://app.zenhub.com/workspaces/product--design-60ab5381e3b4eb000f7e732b/issues/gh/blockframes/blockframes/10062) <-- follow the link to the new issue
