### ISSUE TITLE
Pre-creation dashboard

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#9918]
List the different states. Cf Feedback list
Rita couldn’t understand why we can’t see the work in progress waterfall inside the film page (Need to click on “Create waterfall”) ⇒ doubt that it was well saved

**Comment by 2amarkina** [comment]
[Some ideas were seen during template creation are here](https://www.figma.com/design/zsxsYzg5083IIs22tBxfIq/Optimization-of-the-Waterfall-Builder?node-id=79-2723&t=QlbcXgYbkaOqBn6t-0)
Idea: in the dashboard space to list the waterfall templates

**Comment by Jackseed** [comment]
I'm not sure to see design proposition for that specific issue on the template creation part. Let's discuss it

**Comment by 2amarkina** [comment]
The first step for this will be seen already during [this #9998](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/issues/gh/blockframes/blockframes/9998)

**Comment by 2amarkina** [comment]
Closing this one, as with [the issue #9998](https://app.zenhub.com/workspaces/development-5f6b0067599064680cd2c617/issues/gh/blockframes/blockframes/9998) we are already changing the dashboard and other updates will come with the [#10062](https://app.zenhub.com/workspaces/product--design-60ab5381e3b4eb000f7e732b/issues/gh/blockframes/blockframes/10062)
