### ISSUE TITLE
Form field sizes

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9961]
### Context
Following the discussion with @phpgeekfr while working on [this issue](https://app.zenhub.com/workspaces/blockframes-60b0a31838e485001b3a619f/issues/gh/blockframes/blockframes/9896), it was decided to create the dedicated issue concerning the changing of the form field size. 

### To do (reminder)
It is important to adapt the field size according to the meaning that the concerned field has (e.g. small field for the dates and amounts / large fields for the names)

**Comment by 2amarkina** [comment]
To take into account these screens : 
<img width="1268" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWg4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23d2e562afcdbc53c817873ae5d9b9cc790b6606/investment%20with%20interests.png" alt="investment with interests.png" />


and the icon "Manage"
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWw4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1430d150a92e3682fb48ab94b1701963cf5cc674/icon.png" alt="icon.png" />

**Comment by phpgeekfr** [comment]
- [ ] make changes on all forms ( builder, contracts etc..)

**Comment by 2amarkina** [comment]
- [ ] when dev solution found, then integrate fidma component

**Comment by phpgeekfr** [comment]
- [ ] check https://www.notion.so/cascade8/Dynamic-Condition-fields-e49b9d0c11e5408095901cabdd8a824c
