### ISSUE TITLE
Add a source turnover condition

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9964]
Add a source turnover condition: enable user to focus all incomes coming from a selected source as the left operand. I updated the [condition graph](https://www.notion.so/cascade8/Conditions-88029a78e9cf47bc97a4680645fee3b8), first route on the image below:
<img width="1982" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm5KQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5300f24308c6b740336c932157c45d223d2ad20/image.png" alt="image.png" />

**Comment by phpgeekfr** [comment]
maybe look at existing `amount` condition in `blockingConditions`

**Comment by phpgeekfr** [comment]
@2amarkina here is what I did so far
<img width="1497" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEdaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a78e787a55310eb549b41eb2167efc9d00ed3a5a/image.png" alt="image.png" />

**Comment by Jackseed** [comment]
- [ ] "by source" should be "by Receipt Source" (and btw same here in the header:
![image](https://github.com/user-attachments/assets/5b2c752f-b1dd-4647-a903-1da79a62be93)
)
