### ISSUE TITLE
Change log release 5.4.1

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#9997]

**Comment by phpgeekfr** [comment]
*Issues includes in this release:*

- Outgoing Statements updates #9880
- Contracts , Incomes & Expenses currencies #9422
- Waterfall schema bug #9929
- blank page on first access #9722
- User CRUD Receipt Share #9895
- Outgoing statements add parenthesis around previous rights #9968
- Amortization (breakeven) boolean #9963
- Bugs to resolve #9954
- Add a source turnover condition #9964
- conditions form : add all equality symbols in the numerical operator select: <, <=, >, >= #9959
- Form field sizes #9961
- User can CRUD Conditions #9896
- firebase-functions & gcloud functions deploy will default on functions V2 #9830

**Comment by phpgeekfr** [comment]
- [ ] Translation issue, should be "Le revenu de la société XXX est inférieur à 100,00 €." . Also check other sentences
<img width="1192" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK215Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43b9d0fe403ec21b90fc4fec89afc607016766d1/image.png" alt="image.png" />

**Comment by 2amarkina** [comment]
- [ ] Check out the French and Spanish translations that are in the phrases when creating the conditions: the media and territories are not translated 
<img width="885" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3V5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2940584e7c51ea36245b8e1e6763f30ed2971130/Capture%20d%E2%80%99e%CC%81cran%202024-09-05%20a%CC%80%2016.19.46.png" alt="Capture d’écran 2024-09-05 à 16.19.46.png" />

<img width="918" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3l5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be3150a1632a6bce4aea0d58be6d685c4c229af0/Capture%20d%E2%80%99e%CC%81cran%202024-09-05%20a%CC%80%2016.19.57.png" alt="Capture d’écran 2024-09-05 à 16.19.57.png" />

**Comment by 2amarkina** [comment]
Little check in the Statement's PDFs:
- [ ] If there is "O" alone, it's seems to be a letter "O" instead of zero number, as writing is not the same as for the other numbers
<img width="780" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2kzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46101e537b1d43f43de982cec12f4ff4880020f6/letter%20vs%20number.png" alt="letter vs number.png" />

**Comment by 2amarkina** [comment]
- [ ] translate the title of the RH page
<img width="1487" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK20zQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98c7ab92a47d417ccedcd8ba961773bf00694771/title.png" alt="title.png" />

**Comment by 2amarkina** [comment]
- [ ] When we click on "Manage Expenses" inside the snackbar (the case when there is no expenses added) it should open the manage expenses modal. For the moment it doesn't do anything. 

<img width="619" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEc0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67c7ff1ddb878dea5e9e2697e4d7c087ed493188/snackbar%20CTA.png" alt="snackbar CTA.png" />

**Comment by 2amarkina** [comment]
- [ ] We've changed the wording on the CTA "Pool Receipt Shares" and need to update the modal below 
title: Pool Receipt Shares
label: Pool of the Receipt Shares
<img width="999" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHk0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89a52e8d5cc1d698e1a32a4a796bb6d9ce5001b7/modal%20pool.png" alt="modal pool.png" />

**Comment by 2amarkina** [comment]
**Wordings and sizes for the conditions** (let’s validate if wording is ok @Jackseed ) : 

- [ ] Change the wording of “By who” to “By whom” 
- [ ] Change “By whom” field size to 230px
- [ ] “Will get / will give” - 100px width
- [ ] “Name” - 300px
- [ ] Change “has” to “Revenue Allocation” 
- [ ] Add “has” inside the select “Revenue Allocation” to make “has turnover”, “has amount kept”, has “theoretical profit” 

**Can we distinguish operators?** 
	Example: date operator / numerical operator ?

- [ ] Like this for the date operators (is on or before etc.) let’s have 210px. 
- [ ] For only the symbol fields let’s have 100px ; 
- [ ] For the operators with the select “lower”, “greater” -> 120px.
- [ ] For the operators with the select “contains”, “doesn’t contain” -> 215px. 
- [ ] Target type: 275px

**Comment by 2amarkina** [comment]
- [ ] Tooltip on disabled "Waterfall Management" CTA to transale en fr & es 
<img width="784" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2ZEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40ecfe0ceedd02d4e83bef43f2332e27a7aa1d13/CTA.png" alt="CTA.png" />

EN: Not enough permissions to manage Waterfall 
FR: Permissions insuffisantes pour gérer Waterfall
ES: Permisos insuficientes para gestionar el Desglose de ingresos

**Comment by 2amarkina** [comment]
- [ ] Add tooltip on the disabled button "Continue" inside the Waterfall Creation flow

EN: Please add at least one contract to continue.
FR: Veuillez ajouter au moins un contrat pour continuer.
ES: Por favor, añade al menos un contrato para continuar.

<img width="1080" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGZEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0742403e467b7654479fe598081fb7d245c55b11/continue.png" alt="continue.png" />

**Comment by 2amarkina** [comment]
Following user experience remarks experience : 
- [ ] put the CTA «add condition» as disabled until all the info is filled in  - add a tooltip «fill in the actual condition information» 
- [ ] add a tooltip near this CTA "Complete the current condition information before adding a new one.”
- [ ] highlight the field "condition type" -> pu the focus on it 
<img width="1964" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEhIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a7936b7ab18dab0a4f34cbca6785f34f88950f7/conditions.png" alt="conditions.png" />

**Comment by 2amarkina** [comment]
- [ ] Add a tooltip "Edit Pool"
FR: Modifier Pool
ES: Editar el Pool

- [ ] Add a tooltip "Delete Pool"
FR: Supprimer Pool
ES: Eliminar el Pool

- [ ] Add a warning modal when user clicks on "Delete Pool"
Title: Are you sure to delete this Pool?
FR: Êtes-vous sûr de vouloir supprimer ce pool ?
ES: ¿Estás seguro de que quieres eliminar este pool?

Paragraph: Pay attention, if you delete the following Pool, it will have an impact on conditions and the whole Waterfall.
FR: Attention, si vous supprimez ce pool, cela aura un impact sur les conditions et sur l'ensemble du Waterfall.
ES: Atención, si eliminas el siguiente pool, esto tendrá un impacto en las condiciones y en todo el Desglose de ingresos

_if possible, list the concerned conditions_

CTA: Yes, delete Pool
FR: Oui, supprimer Pool
ES: Sí, eliminar el Pool.

Secondary button: No, come back to Waterfall Builder
FR: Non, revenir au constructeur de Waterfall
ES: No, volver al constructor de Desglose de ingresos. 



- [ ] Update the french texts and make them more correct (modal that appears when we try to delete the Receipt Share from the list): 
<img width="1806" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1ROQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc7f50e9e23556541f8be1ba02430417530058cf/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-09-12%20%D0%B2%2011.34.55.png" alt="Снимок экрана 2024-09-12 в 11.34.55.png" />

Title: Êtes-vous sûr de vouloir supprimer cette part de recettes?
Paragraphe: Faites attention, si vous supprimez la part des recettes suivante, cela aura un impact sur les conditions et tout le waterfall.
CTA: Oui, supprimer cette part de recette.
Secondary button : delete "." at the end of the phrase

**Comment by viktoria-steppan-freeway** [comment]
Wording remained incorrectly "territories" --> should be "rights" instead  #9954
<img width="1225" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmZUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eab567d012c93fbe2ca1f015aaab15c4485cccec/image.png" alt="image.png" />

and here: 
<img width="1113" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmpUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--914287ac1f55824ca131566951ab049cc2690bae/image.png" alt="image.png" />

**Comment by balint-novak-fw** [comment]
- [ ] Is it possible that you meant "[Compound](https://en.wikipedia.org/wiki/Compound_interest)" instead of "Composite" here?
<img width="912" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBei9VQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b2215dba9672905f63b9c7ea3d69cb385e3e1da/image.png" alt="image.png" />

**Comment by 2amarkina** [comment]
indeed, Balint, so it should be :

- [ ] EN: Compound interest
- [ ] FR: Intérêts composés 
- [ ] ES: Interés compuesto
